### ISSUE TITLE
Permission denied to access property "localStorage" , inline javascript.

### ISSUE THREAD

**Issue by sheratsuki** [mozilla/geckodriver#100]
**Marionette**      TRACE   conn0 <- [1,4,null,{}]
12:56:44.402 INFO - Done: [get: **https://signup.live.com/signup**]
12:56:44.406 INFO - Executing: [**execute script**:**localStorage.setItem('loading_selenium',0);**, []])

1466254604416   Marionette      TRACE   conn0 -> [0,5,"executeScript",{"args":[],"newSandbox":false,"script":"localStorage.setItem('loading_selenium',0);","scriptTimeout":null,"specialPowers":false}]

1466254604421   Marionette      TRACE   conn0 <- [1,5,
    {"error":**"javascript error"**,
     "message":"Error: **Permission denied to access property "localStorage"**",
     "stacktrace":"execute_script **inline javascript**, line 0
                        src: "**    var __marionetteFunc = function(){
                                        localStorage.setItem('loading_selenium',0);
                                    };
                                    __marionetteFunc.apply(null, __marionetteParams);
                           **"
Stack:
__marionetteFunc@dummy file:0:63
@dummy file:0:112
"},null]

12:56:44.705 WARN - Exception thrown
org.openqa.selenium.WebDriverException: **Error: Permission denied to access property "localStorage"** (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 16 milliseconds

Build info: 
version: '**2.53.0**', 
revision: '**35ae25b**', 
time: '2016-03-15 17:00:58'
System info: host: '',
ip: '',
os.name: 'Windows 7',
os.arch: 'amd64',
os.version: '6.1',
java.version: '1.8.0_92'
Driver info: **org.openqa.selenium.firefox.MarionetteDriver**
Capabilities [
    {
        rotatable=false, 
        raisesAccessibilityExceptions=false,
        marionette=true, 
        appBuildId=20160604131506, 
        version=47.0, 
        platform=XP,
        proxy={},
        command_id=1, 
        specificationLevel=0, 
        acceptSslCerts=false,
        browserVersion=47.0, 
        platformVersion=6.1, 
        XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384},
        browserName=Firefox, 
        takesScreenshot=true, 
        takesElementScreenshot=true, 
        platformName=Windows_NT, 
        device=desktop
    }
]
Session ID: 695352e4-74c7-4639-a13b-c05bbb06d0dd

**Comment by andreastt** [comment]
This was fixed in [bug 1123506](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506), available in Firefox 48+.
