### ISSUE TITLE
GeckoDriver Loses focus when using multiple Instances 

### ISSUE THREAD

**Issue by kabone** [mozilla/geckodriver#1002]
Using Selenium 3.6.0
GeckoDriver 19
Firefox 56

As the title says Geckdriver keeps losing focus on the browser window when running multiple instances using multiple geckdriver.exe Is there anyway to fix this? Been trying this for days with no luck. It works for a little while then the browser stops automating..

**Comment by whimboo** [comment]
Keep in mind that there is always only one single OS level window which can have focus at a time. So if a browser instance currently not in focus absolutely needs focus, it has to be switched.

Generally commands should be not affected if the browser runs in background or not. Sadly you haven't given any detail in what actually went wrong for you. It means we need a testcase, and as best a trace level log, as it was requested when filing an issue.

Please come back with that information which covers the problem you have, and shows the failure in the log.

**Comment by kabone** [comment]
I've attached the source, a trace log and videos of the issue. Essentially what is happening is one or 2 browsers stop actually doing anything, and the only thing I can think that is causing it is it is losing focus. 

Videos can be found here -
https://youtu.be/2GiDdNqaEbI
https://youtu.be/zTN9zYxz58U
https://youtu.be/JjXrxCtCp_A
https://youtu.be/o0UBh3BT7ms

As you can see it doesn't happen constantly, but if I am running 20 threads at the same time, 1 or two will happen every 10-20 mins. And those have to be closed causes others not to launch after.




Source, trace log, and everything else is included here - 
[Mover.zip](https://github.com/mozilla/geckodriver/files/1372340/Mover.zip)
https://www.mediafire.com/file/kn35qljjk8mdb06/Mover.zip

**Comment by whimboo** [comment]
Thank you for your feedback. In case you still have a problem with this issue, feel free to comment on it again. But then as best with a trace log, so we can better analyze it.

**Comment by kabone** [comment]
So I keep getting this before it stops losing focus.

```
[GFX1-]: (gfxWindowsPlatform) Detected device reset: 3
[GFX1-]: (gfxWindowsPlatform) scheduled device update.
[GFX1-]: LayerManager::EndTransaction skip RenderLayer().
[GFX1-]: GFX: D3D11 skip BeginFrame with device-removed.
[GFX1-]: (gfxWindowsPlatform) Detected device reset: 3
[GFX1-]: (gfxWindowsPlatform) scheduled device update.
[GFX1-]: LayerManager::EndTransaction skip RenderLayer().
[GFX1-]: (gfxWindowsPlatform) Detected device reset: 3
[GFX1-]: (gfxWindowsPlatform) scheduled device update.
[GFX1-]: LayerManager::EndTransaction skip RenderLayer().
[GFX1-]: (gfxWindowsPlatform) Detected device reset: 3
[GFX1-]: (gfxWindowsPlatform) scheduled device update.
[GFX1-]: LayerManager::EndTransaction skip RenderLayer().
IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)

IPDL protocol error: Handler returned error code!

###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer
 Processing error: message was deserialized, but the handler returned false (ind
icating failure)
```

**Comment by whimboo** [comment]
So that's clearly a bug in Firefox. As given by the source the message `IPDL protocol error: Handler returned error code!` would be very helpful for developers to investigate the problem. @kabone do you have a Bugzilla account and would file a bug under [Core :: IPC](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=IPC)? That would be fantastic. For the initial comment please include what you are trying to do with Selenium, and the info from above. Additionally the data from about:support will be helpful. Let us know about the bug number. Thanks.

**Comment by kabone** [comment]
I have filed a bug on Bugzilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1410187

I am trying to login to Gmail and move multiple emails from the spam folder to the inbox. It works great for a little while then eventually just hangs once this error pops up. 
[logs.txt](https://github.com/mozilla/geckodriver/files/1399546/logs.txt)

videos of what are happening - 
https://youtu.be/2GiDdNqaEbI
https://youtu.be/zTN9zYxz58U
https://youtu.be/JjXrxCtCp_A
https://youtu.be/o0UBh3BT7ms

**Comment by whimboo** [comment]
Thank you. So lets continue the investigation on that bug.
