### ISSUE TITLE
geckodriver just stops executing after some time randomly

### ISSUE THREAD

**Issue by wolfy027** [mozilla/geckodriver#1006]
## System
* Version: 0.18
* Platform: Windows
* Firefox: 55,56
* Selenium: 3.53.0

## Testcase

I am trying to run a particular piece of code generically for all browsers, this software application runs for a long time and works perfectly for Chrome, however i get this error   

**Canceled page load listener because no navigation has been detected**

and the execution just stops,

code  👍 

	**public void selectDropdownUsingIndex(GenericUIDriver driver) {
		int indexForDropdown = FNObjectUtil
				.intValue(navActions.getNavigationPreferencesHash().get("indexForDropdown").toString());
		String optionXpath = "//select[not(@multiple) and not(ancestor::*[contains(@class,'dataTables_scroll')])]/option["
				+ indexForDropdown + "]";
		List<? extends UIWebElement> optionElements = driver.findUIElementsByXpath(optionXpath);
		List<String> optionTextList = optionElements.stream().map(optionElement -> optionElement.getWebElementText())
				.collect(Collectors.toList());

		for (int i = 0; i < optionElements.size(); i++) {
			UIWebElement currentOptionElement = optionElements.get(i);
			try {
				PrintData.logInfo("Option Element Text\t\t:\t\t" + currentOptionElement.getWebElementText());
				if (currentOptionElement.findUIElementByXpath("../following-sibling::a/span[@class='selectBox-arrow']")
						.isDisplayed()) {
					UIWebElement relativeSelectArrow = currentOptionElement
							.findUIElementByXpath("../following-sibling::a/span[@class='selectBox-arrow']");
					relativeSelectArrow.scrollTo();
					relativeSelectArrow.highlight("");
					driver.getActionObject().moveToElement(relativeSelectArrow.getWebElement(), 5, 5).pause(1000)
							.click().build().perform();
					UIWebElement optionToSelect = driver
							.findUIElementByXpath("//ul[contains(@class,'selectBox-options-')]//a[contains(text(),'"
									+ optionTextList.get(i) + "')]");
					optionToSelect.scrollTo();
					optionToSelect.highlight("");
					optionToSelect.click();
				}
			} catch (NoSuchElementException nse) {
				continue;
			} catch (StaleElementReferenceException ser) {
				appObject.pauseDriverForSeconds(5);
				continue;
			} catch (WebDriverException ser) {
				continue;
			} catch (Exception e) {
				continue;
			}
		}
	}**

**Comment by kabone** [comment]
I'm having the same issue

**Comment by andreastt** [comment]
No reproducible test case. Closing.

**Comment by whimboo** [comment]
@wolfy027 and @kabone, you both will have to upload the trace log, or at least an excerpt which covers session creation and the part including the command run before the failing command. Otherwise we are not able to help you. Please provide that information and I can have a look at, and if necessary reopen the issue. Thanks.
