### ISSUE TITLE
Event onChange seems not to be activated of input type=files

### ISSUE THREAD

**Issue by VitoAlbano** [mozilla/geckodriver#101]
Creating an automation with : 

FF 47.0 
Marionette 0.8.0
Selenium  2.53.5
Robot Framework  3.0

Attached the example page : 

[example_page.html.zip](https://github.com/mozilla/geckodriver/files/323524/example_page.html.zip)

Here the example test : 

1.Open Browser
  Initialise Library #Add the required capability for using Marionett with FF 47
  Open Browser  path/to/the/example/page  browser=firefox
  Maximize Browser Window
  Choose File  id=files_list  path/to/the/file

What i would have expected is that the alert is triggered but nothing happen.

Manually tested ( simulate upload of a file) and the alerts are triggered.

Is there something missing?  

Thanks

**Comment by andreastt** [comment]
I filed [bug 1280947](https://bugzilla.mozilla.org/show_bug.cgi?id=1280947) about this.

This is probably because we are using privileged chrome-space APIs to set a file on `<input type=file>` elements because they have security privileges preventing them from being scripted from the content frame. This means we aren’t calling the regular interactions library on the element, resulting in no DOM events being fired.

**Comment by lippoliv** [comment]
Hey folks, have a look here: https://bugzilla.mozilla.org/show_bug.cgi?id=1279854

**Comment by Toilal** [comment]
I found a workaround for this issue thanks to this [stackoverflow post](http://stackoverflow.com/questions/2856513/how-can-i-trigger-an-onchange-event-manually).

It's possible to trigger the event manually through javascript.

Here's an example using Selenium.

```java
// Create marionette driver.
WebDriver driver = new MarionetteDriver();
...

// Find some input type=file
WebElement element = driver.findElement(...);

// This doesn't raise the change event :(
element.sendKeys(tempFile.getAbsolutePath());

// But it's possible to trigger it manually with javascript :)
driver.executeScript(
"var element=arguments[0];" +
"if ('createEvent' in document) {" +
    "var evt = document.createEvent('HTMLEvents');" +
    "evt.initEvent('change', false, true);" +
    "element.dispatchEvent(evt);" +
"} else { " +
    "element.fireEvent('onchange')" + 
"};",
getElement());
```

**Comment by andreastt** [comment]
This issue is now fixed in Firefox 49, 50, and 51.
