### ISSUE TITLE
Javascript "qxwebdriver = {};" doesn't create any object

### ISSUE THREAD

**Issue by tfreitasleal** [mozilla/geckodriver#1010]
## System
* Version: 0.19.0 (64-bit)
* Platform: Windows 10 (64-bit)
* Firefox: 56.0 (64-bit)
* Selenium: 3.6.0

## Testcase

C# binding
Driver created using
`IWebDriver driver = new FirefoxDriver();`

When executing
```
string script = "qxwebdriver = {};"
((IJavaScriptExecutor) driver).ExecuteScript(script);
```
the response Status is `WebDriverResult.Success` but the object isn't created.

## Workaround

Inject Javascript as follows
```
string script =
    "var new_script = document.createElement('script');" +
    "new_script.type = 'text/javascript';" +
    "new_script.text = 'qxwebdriver = {};';" +
    "new_script.className = 'QxWorkAround';" +
    "document.getElementsByTagName('head')[0].appendChild(new_script);";
((IJavaScriptExecutor) driver).ExecuteScript(script);
```
and the object is created.

NOTE - The failing line works all rigth in Chrome and Edge drivers (creates qxwebdriver object).

**Comment by andreastt** [comment]
I don’t understand exactly what you mean that “the object isn’t created” when you injected `qxwebdriver = {}`. Do you have a reproducible test case of what you mean?

**Comment by whimboo** [comment]
Yes, please create a minimized test, and if possible also add a [trace level log](https://dxr.mozilla.org/mozilla-central/rev/20d57b9c4183973af4af5e078dff2aec0b74f928/testing/geckodriver/doc/TraceLogs.md#114-116) from geckodriver.
