### ISSUE TITLE
Should throw "invalid argument" error on an attempt to click file input (legacyClick)

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#1011]
According to the spec of the click command  [1], "If the element is an input element in the file upload state return error with error code invalid argument."

At the moment it opens file selection dialogue and don't throw.

[1] https://w3c.github.io/webdriver/webdriver-spec.html#element-click

**Comment by andreastt** [comment]
That’s unfortunate… I thought this would be handled by https://searchfox.org/mozilla-central/rev/31606bbabc50b08895d843b9f5f3da938ccdfbbf/testing/marionette/interaction.js#158-162:

```js
  // step 3
  if (el.localName == "input" && el.type == "file") {
    throw new InvalidArgumentError(
        "Cannot click <input type=file> elements");
  }
```

**Comment by andreastt** [comment]
Ah, of course this code path doesn’t run because we don’t use the WebDriver conforming Element Click implementation yet. This is tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1321516.

Can you try running your testcase again with `moz:webdriverClick` set to true?

**Comment by whimboo** [comment]
@barancev if you have the time it would be great to get a response. I'm working towards making this feature the default one and would like to know if that fixes your issue. Thanks.

**Comment by barancev** [comment]
Sorry, I've checked but forgot to respond :(
Yes, this capability resolves the issue.

**Comment by whimboo** [comment]
Great. Thanks a lot.

**Comment by andreastt** [comment]
I guess we’ll leave this open for tracking.

**Comment by barancev** [comment]
`moz:webdriverClick` is true by default now, the issue can be closed.
