### ISSUE TITLE
Click Element is broken with Chrome 61, geckodriver 0.16.1,ChromeDriver 2.33.506120, Selenium 3.6.0

### ISSUE THREAD

**Issue by danosoft77** [mozilla/geckodriver#1012]
System: Win10/ Win server 2008
Crhome: Version 61.0.3163.100 (Build ufficiale) (a 64 bit)
Gecko driver version: 0.16.1
ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)
Selenium: 3.6.0

When i tried to point CLICK  to element it do this error (in my browser i have scrollbar becouse the page is long and the element is down the page:

{WebDriverException}Message: unknown error: Element is not clickable at point (245, 1116)
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

I tried to click the element with: 
browser.find_element_by_link_text(config.btn_next).click()
or
browser.find_element_by_id(config.btn_next).click()

same error
but element exist.... why it do that?

**Comment by andreastt** [comment]
I don’t know why that is. You will have to provide us with a minimal HTML document that shows exemplifies the problem. There is nothing reproducible about your bug report, and I can’t guess what is wrong.

I am happy to re-open this once you add this.
