### ISSUE TITLE
Not clicking simple link texts

### ISSUE THREAD

**Issue by jsa34** [mozilla/geckodriver#1017]
## System
* Version: 0.19.0
* Platform: Linux and Windows
* Firefox: 56.0
* Selenium: java 3.6.0

## Testcase

When presented with a simple link text, Firefox is unable to click on it.  I have also tried clicking on the parent.  It is able to locate the WebElement, successfully waits for it to be clickable and thinks it has clicked it, but doesn't.

## Stacktrace

No stack trace available as it thinks it has clicked the item.

## Code executed
findElement(By.linkText("Add vacancy")).click;
(This works successfully and all other iterations in Chrome, but not in Firefox)

## HTML of site interaction

```html
<form action="#" method="post" class="col-8 right-2 col first last">
        <input type="hidden" name="...">
        <input type="hidden" name="...">
        <ol class="buttons list-add">
            <li><a href="..." class="button no-process">Find vacancies</a></li>
            <li><a href="position_list" class="button no-process">Add vacancy</a></li>
        </ol>
    </form>
```

**Comment by andreastt** [comment]
I can’t find any links with the text `xxx` in that HTML document, so I can’t reproduce this.

**Comment by jsa34** [comment]
Sorry - my mistake - renamed the linkText reference, but didn't rename the actual link text for anonyminity - now updated so that it actually makes sense (apologies!)

**Comment by andreastt** [comment]
Thanks for the update. As far as I know, nothing it supposed to happen when you click a `<li>` element unless it is associated with some JS event?

**Comment by jsa34** [comment]
It is clicking the element with <a> tags which is contained within the <li>.  I have tried clicking the <a> element explicitly and the <like> parent but neither work

**Comment by jsa34** [comment]
After some further investigation, it appears when the class associated with the button is removed (so there is no "button no-process") it clicks fine.  It appears something with this class is not clicking the button properly.

**Comment by jsa34** [comment]
This is where the "button no-process" class is being implemented in the code, but as I said, the button behaves as expected in Chrome, it just appears to be an issue with Firefox thinking it has clicked the button when it hasn't.

`$.fn.fix = function() {
    var $html = $('html');
    var $this = this;

    $('#header li:not(.help) a:not([href])', this).addClass('current');
    $('button, input[type="button"], input[type="submit"]', this).addClass('button');
    $('input[type="submit"]', this).addClass('no-process');
    $('a.button', this).filter(function (i) { return $(this).attr('href') }).addClass('no-process');
    
    // Create help icons for labels that have the title attribute
    $('label[title]', this).each(function() {
        var label = $(this);
        var text = $("<div/>").html($(label).attr('title'));
        var input = $('#'+$(label).attr('for'));
        var helpid = 'help-field-' + $(input).attr('id');
        var hideDelay = $(text).find('a').length > 0 ? 2000 : 1000; 
        $(label).after('<img src="'+config.style+'help.png" class="help" id="'+helpid+'" />');
        $('#'+helpid).qtip({content: $(text), hide: { delay: hideDelay }, position:{ at:"left center", my:"right center"}, show: { delay: 300 }, style: { tip: { corner:true } } });
        $(label).removeAttr('title');
    });
    
    $('input[id^="search-"]', this).each(function() {
        $this = $(this);
        var search = $this.attr('id');
        if(!$this.hasClass('fixed')) {
            $this.attr('id', search+'-field');
            $this.addClass('no-validate no-process fixed search');
            $this.wrap('<form class="search" id="'+search+'"></form>');
            $this.after('<input class="button no-process" type="submit" value="Search" />');
            $form = $('#'+search+'');
            $form.after('<div id="'+search+'-results"></div>');
            $form.focusFirst();
        }
    });
    
    $('input[type="text"]:not(.fixed)', this).wrap('<span class="input"></span>').addClass('fixed'); // So the datepicker icon can appear within the input

    // Help browsers know what type a field is
    if($html.is('.browserIE7, .browserIE8, .browserFirefox2')) {
        $('input[type="text"]', this).addClass('text');
        $('input[type="checkbox"]', this).addClass('checkbox');
        $('input[type="radio"]', this).addClass('radio');
    }
    
    // Some grid fixes
    $('.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12', this).addClass('col');
    $('.row > .col:first-child', this).addClass('first');
    $('.row > .col:last-child', this).addClass('last');
    $('.container > .row:first-child', this).addClass('first-row');
    $('.container > .row:last-child', this).addClass('last-row');
    
    // Datepicker
    $('input[type="text"].date:not([disabled]):not([readonly])', this).datepicker({ isRTL: true, beforeShow: function() { $(this).addClass('no-validate'); }, onClose: function() { $(this).removeClass('no-validate'); }, onSelect: function() { $(this).removeClass('no-validate').blur(); } });
    $('#ui-datepicker-div').hide();
    
    // Table fixes
    $('table', this).each(function() { if(!$('caption', this).length) $(this).addClass('no-caption'); });
    $('legend:not(.fixed)', this).wrapInner('<span></span>').addClass('fixed');

    // Sortable tables
    $('table.sort:not(.tablesorter)', this).each(function() {
        var options = {
            dateFormat: "ddmmyyy",
            cssHeader: "header",
            cssAsc: "headerSortUp",
            cssDesc: "headerSortDown",
            cssChildRow: "expand-child",
            sortList: [],
            headers: {},
            widgets: ["filter", "zebra"]
        };

        $("thead th", this).each(function (index) {
            if($(this).hasAttr("class")) {
                var classes = $(this).attr('class').split(/\s+/);
                $.each(classes, function() {
                    var split = this.split('-');
                    if(split[0] == 'sort' && !isNaN(split[1])) {
                        var sort = new Array();
                        sort[0] = index;
                        if(split[2] && split[2] == 'desc')
                            sort[1] = 1;
                        else
                            sort[1] = 0;
                        options.sortList.push(sort);
                    }
                });
            }
            if($(this).children('span.sort-icon').length == 0) {
                $(this).prepend('<span class="sort-icon"></span>');
            }
            if($(this).hasClass('not-sortable')) {
                options.headers[index] = {};
                options.headers[index].sorter = false;
            } else {
                $(this).addClass('sortable');
            }
        });

        var pagerId = $(this).attr("id") + "-pagination";
        var pagerRows = (config.paginator ? config.paginator : 15);

        $(this).after(
            '<ul id="' + pagerId + '" class="pagination">' +
                '<li class="page">' +
                    '<label>' +
                        'Page ' +
                        '<select title="Select page number" class="gotoPage"></select>' +
                    '</label>' +
                '</li>' +
                '<li><a class="first" href="#">First</a></li>' +
                '<li><a class="prev" href="#">Previous</a></li>' +
                '<li><span class="pagedisplay"></span></li>' +
                '<li><a class="next" href="#">Next</a></li>' +
                '<li><a class="last" href="#">Last</a></li>' +
                '<li class="rowsPerPage">' +
                    '<label>' +
                        'Rows ' +
                        '<select title="Select number of rows per page" class="pagesize">' +
                            '<option value="' + pagerRows   + '" selected="selected">' + pagerRows + '</option>' +
                            '<option value="' + pagerRows*2 + '">' + pagerRows*2 + '</option>' +
                            '<option value="' + pagerRows*3 + '">' + pagerRows*3 + '</option>' +
                            '<option value="' + pagerRows*4 + '">' + pagerRows*4 + '</option>' +
                            '<option value="' + pagerRows*5 + '">' + pagerRows*5 + '</option>' +
                        '</select>' +
                    '</label>' +
                '</li>' +
            '</ul>'
        );

        var pagerOptions = {
            container: $("#" + pagerId),
            size: pagerRows,
            // possible variables: {page}, {totalPages}, {filteredPages}, {startRow}, {endRow}, {filteredRows} and {totalRows}
            output:'{startRow} to {endRow} of {filteredRows} ({totalRows})'
        };

        $(this).tablesorter(options).tablesorterPager(pagerOptions);
        $(this).addClass('tablesorter');
    });

    $(':not(table.tablesorter) tbody tr:nth-child(even)', this).addClass('even');
    $(':not(table.tablesorter) tbody tr:nth-child(odd)',  this).addClass('odd');

    // Exportable tables
    $('table.export:not(.export-done)', this).addClass('export-done').before('<a class="link export process" id="export-'+$(this).attr('id')+'">Export</a>');
    
    // Files list
    $('.files:not(.fixed)', this).addClass('fixed').after('<div style="clear: both;"></div>');

    if ($html.is('.browserIE7, .browserIE8, .browserFirefox2, .browserFirefox30')) {
        $html.addClass('no-nth-child');
    }

    // For browsers than can't handle :nth-child
    if ($html.hasClass('no-nth-child')) {
        $('li:first-child').each(function() { $(this).addClass('first'); });
        $('li:last-child').each(function() { $(this).addClass('last'); });
    }

    // use select2 for multi-selects
    var selectElems = $("select[multiple='multiple']", this).filter(function () {
        return $(this).parents('.tablesorter, .tablesorter-pager').length < 1;
    });
    $(selectElems).each(function (i, e) {
        var blankOption = $(selectElems).find('option[value=""]');
        $(e).select2({
                placeholder:"Select value",
                allowClear:$(blankOption).length > 0,
                dropdownCss:{"min-width":"200px"}
            }
        );
    });
}
`

**Comment by whimboo** [comment]
@jsa34 how are `button` and `no-process` defined? I cannot find that in this issue.

**Comment by whimboo** [comment]
Maybe you can create a minimized HTML testcase which shows this behavior? That would be much more helpful. Also try to run your test with Firefox 57 beta, and with the `moz:webdriverClick` capability set to `true`. Does that make a difference?

**Comment by jsa34** [comment]
I can confirm, this is fixed with Firefox57 Beta - shame will have to wait for its release for the bug to be fixed

**Comment by whimboo** [comment]
@jsa34 is it fixed just by using Firefox 57, or with the `moz:webdriverClick` tweak?

**Comment by jsa34** [comment]
With just the upgrade to FF57 beta

**Comment by whimboo** [comment]
Great to hear then. Sadly I cannot tell which patch actually fixed it. But when it works out of the box we are just fine. Thank you for the feedback!
