### ISSUE TITLE
Capybara using Selenium fails to even navigate to the specified route.

### ISSUE THREAD

**Issue by TheJayWright** [mozilla/geckodriver#1018]
## System
* Version: 0.19.0
* Platform: MacOS 
* Firefox: 56.0
* Selenium: Selenium WebDriver 3.6.0 ran by Ruby Gem 2.53 and Capybara

## Testcase

Selenium is required in the application's test_helper.rb. It successfully runs Chrome and PhantomJS. It will open Firefox and Firefox states that it is being controlled by automated software, but it never performs another action (expected action being navigation to the specified webpage.)

I'm wondering if this is due to the major changes Firefox has released in 56.0 and geckodriver requires certain changes?

## Stacktrace

There is no error besides Selenium will eventually just timeout. Capybara used to say that marionette had to be set to false and it did indeed work. Capybara's github no longer says that and it will only load the browser on marionette: true, but won't perform anymore actions.

```Ruby
  Capybara.register_driver :firefox do |app|
    Capybara::Selenium::Driver.new(app, browser: :firefox, marionette: true)
  end
```

## Trace-level log

It's just a Selenium timeout.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment]
No update by the reporter in the last 16 days. Closing issue for now.
