### ISSUE TITLE
Navigating to an malformed URL breaks Firefox

### ISSUE THREAD

**Issue by samzhang111** [mozilla/geckodriver#102]
The top chrome of the browser is duplicated using Selenium 2.53 to open a Firefox 47 browser with marionette (geckodriver-0.8.0-OSX).

![screen shot 2016-06-20 at 10 54 06 am](https://cloud.githubusercontent.com/assets/2800289/16199066/2b9224e2-36d6-11e6-8a84-f667d78383cf.png)

When Selenium opens a Firefox instance, it opens two browsers, one of which is like this. The other one hangs until focus is given to the malformed one.

**Comment by andreastt** [comment]
@samzhang111 Firefox 47 isn’t supported. Can you try again with Nightly and report back if that exhibits the same problem?

**Comment by drobota** [comment]
I tred out it with firefox 50.0a1 and it does not work as expected when I omit protocol
f.e. ff.get("google.com") it navigates to the similar url

**Comment by andreastt** [comment]
I can confirm this:

```
>>> m = Marionette(bin="/home/ato/1/gecko/build/desktop-release/dist/bin/firefox-bin")
>>> m.start_session()
{u'rotatable': False, u'raisesAccessibilityExceptions': False, u'takesScreenshot': True, u'acceptSslCerts': False, u'appBuildId': u'20160629181137', u'XULappId': u'{ec8030f7-c20a-464f-9b0e-13a3a9e97384}', u'processId': 27822, u'browserVersion': u'50.0a1', u'specificationLevel': 0, u'platform': u'LINUX', u'browserName': u'Firefox', u'version': u'50.0a1', u'device': u'desktop', u'proxy': {}, u'platformVersion': u'3.16.0-4-amd64', u'takesElementScreenshot': True, u'platformName': u'Linux', u'command_id': 1}
>>> m.navigate("sny.no")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ato/1/gecko/src/testing/marionette/client/marionette_driver/marionette.py", line 1400, in navigate
    self._send_message("get", {"url": url})
  File "/home/ato/1/gecko/src/testing/marionette/client/marionette_driver/decorators.py", line 38, in _
    return func(*args, **kwargs)
  File "/home/ato/1/gecko/src/testing/marionette/client/marionette_driver/marionette.py", line 692, in _send_message
    self._handle_error(err)
  File "/home/ato/1/gecko/src/testing/marionette/client/marionette_driver/marionette.py", line 725, in _handle_error
    raise errors.lookup(error)(message, stacktrace=stacktrace)
marionette_driver.errors.UnknownException: UnknownException: Error loading page
>>> m.get_url()
u'chrome://browser/content/sny.no'
```

**Comment by andreastt** [comment]
The specification [is unclear](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-go) on whether calling _Go_ with a malformed URL should return an error or be accepted. My strong suspicion is that we should not allow malformed URLs.

**Comment by jgraham** [comment]
Yes, I think we should reject such urls. I can patch this in geckodriver.

**Comment by andreastt** [comment]
We shouldn’t patch this in geckodriver, but in Marionette.

**Comment by andreastt** [comment]
This was resolved by https://github.com/mozilla/gecko-dev/commit/175975b04b3b5712f851802ffcec77e4c9dd2c30.
