### ISSUE TITLE
Timed out error for Yahoo search page

### ISSUE THREAD

**Issue by rajamarwah** [mozilla/geckodriver#1021]
## System
* Version:  0.19
* Platform:  Mac
* Firefox: 
* Selenium: 3.x

## Testcase

waitForElementVisible('body',10000) is giving me error

Timed out while waiting for element <body> to be visible for 10000 milliseconds.  - expected "visible" but got: "not visible"

**Comment by andreastt** [comment]
`waitForElementVisible` isn’t a geckodriver primitive, and there’s nothing actionable in this bug report relating to geckodriver.

I’m happy to re-open this issue if you add a reproducible test case and a [trace-level log] from geckodriver.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs
