### ISSUE TITLE
Input Not Accepted To Proceed Forward Using geckodriver 0.19.0

### ISSUE THREAD

**Issue by metallica1973** [mozilla/geckodriver#1023]
## System
* Version: 
* Version: 
* Platform: 
* Firefox: 
*Chromium
* Selenium: 

In a nutshell, I am using Python 2.7, Selenium, latest Gecko and Chrome Web Drrivers. I created a script that opens two browsers. All works well in opening both browsers (Chrome and Firefox) and creates everything ok which opens a iframe (scan wizard (5 steps)) for creating a vulnerability scan-job). All of the selenium steps work fine in Chrome but when Firefox gets to the same section of creating the scanjob name and attempts to proceed forward, it spits a error message and an alert saying, "You must enter a unique name for this scan job":

Here is a snippet of the import section of my code written in Python:

__init__.py

        try:
                self.ff = webdriver.Firefox(log_path=gecko, firefox_options=options)
                self.ff.set_page_load_timeout(120)
                self.ff.maximize_window()
                self.ff.get(self.rm)
        except:
                logging.exception('Firefox Browser Will Not Launch\n')

        try:
                self.ch = webdriver.Chrome('/usr/bin/chromedriver')
                self.ch.set_page_load_timeout(120)
                self.ch.maximize_window()
                self.ch.get(self.rm2)
        except:
                        logging.exception('Chrome Browser Will Not Launch\n')
and 

Scanning.py

There are 2 try blocks in which the first one throws an exceptions because the element does exist (excepted) and this the second part of the code that is executing correctly but throws the error of (you must enter a unique name for this scan) on the screen in which I have attached a screen-shot:

snippet 2 which pertains to the error:

ssjname = string.join([str(uuid.uuid4().hex),"Second Attempt Heavy Scanjob"])

`try:
       self.ff.switch_to_default_content()
        ActionChains(self.ff).move_to_element(self.ff.find_element_by_xpath("//li[@id='dmenuactive']/a/span")).perform()
        self.ff.find_element_by_xpath("//ul[@class='sub-menu']/li/a[text()='Scan Jobs']").click()
        time.sleep(10)
        ActionChains(self.ff).move_to_element(self.ff.find_element_by_xpath("//div[@class='pulldown-menu' and contains(text(),'Grid Actions')]")).perform()
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//a[@onclick='createJob(); return false;']").click()
        time.sleep(20)
        self.ff.switch_to.frame(1)
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//input[@type='text']").send_keys(ssjname)
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//textarea[@id='description']").send_keys(ssjname)
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//div[@id='policy-cat-selector']/button").click()
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//li[contains(.,'Vulnerability')]").click()
        self.ff.find_element_by_xpath("//div[@id='policy-selector']/button").click()
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//li[contains(.,'Heavy/Vulnerability Scan')]").click()
        self.ff.implicitly_wait(120)
        self.ff.find_element_by_xpath("//div[@class='actionBar']/a[text()='Next']").click()
`

Here is the html section of the page where I am sending the scan-job name to:

`<input id="name" name="name" maxlength="128" title="Enter a name for your scan job." class="ui-widget-content ui-corner-all" type="text">
`
## Stacktrace && Trace-Log-Level
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1402581/geckodriver.log)
![unique-error](https://user-images.githubusercontent.com/31518470/31830860-8008b3b8-b58f-11e7-91ff-7c58d408f18c.png)

I have been stumped for weeks on this so I decided to post my question. Thank you in advance.

**Comment by andreastt** [comment]
This issue isn’t actionable because you haven’t included a reproducible test case, information about what version of the software you are using, or a trace-level log. I would encourage you to read the [reporting bugs](https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md#reporting-bugs) section of our contribution guide first.

**Comment by whimboo** [comment]
The log is attached right above the screenshot. And as it tells me the issue here is the open alert, which blocks further commands from executing. So there is a patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1416284 which will hopefully land soon for Firefox 59. Maybe we uplift for 58 as well.

For the time being you have to switch to the alert, and accept/dismiss it yourself.
