### ISSUE TITLE
Hover functionality with dropdown/flyouts

### ISSUE THREAD

**Issue by crcraig92** [mozilla/geckodriver#1029]
## System
* Version: 0.19
* Platform: Windows 10 Enterprise (1703)
* Firefox: 56 and 57b10
* Selenium: v3.4.4, Ruby 2.3.3-p222

Note: I'm using Capybara 2.15.1, but I tested this using selenium only code and saw the same functionality. 

## Testcase

I'm not able to copy paste my applications code as it's in development.  Here is essentially what it looks like.

```HTML
<div id="navigationBar" class="navigationBar">
  <div id="openList">
    <ul id="mainMenu" class="mainMenu">
      <li id="firstOption" class="firstOption><a href="/somewhere/first">Click Me</a></li>
      <li id="secondOption" class="secondOption><a href="/somewhere/second">Or me</a></li>
      <li id="thirdOption" class="thirdOption><a href="/somewhere/second">Not me</a></li>
    </ul>
  </div>
</div>
```
Excuse the HTML if it's a little weird, I don't do much HTML, I'm almost pure Ruby.  
The div has CSS that triggers on mouse enter to open the list as a dropdown/flyout type menu.
Note, in this example the div#openList is a small square button that opens a 3 row list to its right, where each rows height is that of the square.  

## Stacktrace

N/A

You'll just get an element not visible, because it's not.

## Issue

In the HTML above I want to click the div#openList to open the flyout.  This works.
Next I want to hover the first option, this doesn't work.  It will hover the mouse along some path from the top corner I'm guessing, and at some point trigger a hover on the body of my page which will close the flyout.  I found a work-a-round, if I hover the div#openList, it will know the cursor was there, and the hover on the first option will work.  However, in the next test where I then hover the 3rd option on the list, it will fail.  It will hover from the square button to the bottom option taking a direct path which, again, triggers the hover over the body of the page at some point.  This closes the flyout and when the hover gets to the element, it's no longer visible. Again, I figured out the next logical work around.  After opening the flyout, I will hover the first option, that way any subsequent option is in line and the mouse will not leave the dialog.

This is a very strange thing to have to do in automation from my perspective.  The way I see it, this is not how a user would hover, the user knows it must stay over the flyout to keep it open and will take a slightly arched path to allow this.  At the same time, the automation doesn't think clicking the link required the mouse to be there.  I have to hover it to click it, shouldn't that be taken into account if this is really the way the Firefox automation is going?

Again, I'm sorry if their isn't the right information here to reproduce this.  I'm fairly new to this scene.  I'll do my best to assist where I can.  My company will not allow me to post images or code that stems from the product.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver and a reproducible test case? Read more about reporting actionable bugs in our [contribution guidelines]. The HTML by itself is in this case not sufficient, and you haven’t described which steps you are taking.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by crcraig92** [comment]
I have tried several things to get the trace-level log.  I'm not able to get the STDOUT in my console.  I googled the issue and came across multiple threads, a few of which you were active in, describing how to get the log to be accepted by selenium.  I'm using cucumber, so I execute tests using "bundle exec cucumber" and it appears to be suppressing any logging.  The profile is taking the option for trace-level logs and when I call Selenium.page.driver.options in a pry session I can see the logging option is set.  However, it's not giving me anything.  The best I could get is "bundle exec --verbose cucumber /path/to/test --verbose" which would tell me DevTools listening on ws://127.0.0.1:12803/devtools/browser/0d448554-9956-4079-96b3-18f8bbbc4a87 and when it failed it will give me a larger stack trace.  However, this will not help you.  The part that fails is legitimate.  It can't find the element visible on the page, and it's not anymore, due to the previous hover call triggering a mouse exit on the flyout menu.  I'll try to describe the issue once more below, but if you insist on getting the logs to consider this valid, then you can just close it.  I'm not interested in reporting on my specific instance.  I'm just trying to generate a discussion on the direction Firefox automation is going, as I do not believe it's the best path for my test cases.  The general case issue is- calling mouse_over triggers events that were not expected.  I understand they are "expected" now.  I've determined a work-a-round, I just don't think it should be necessary.

Specific case:  
My application has a "context menu" which gives several options in a non-persistent dropdown style menu.  When you click the context menu, a list opens to the right of it.  The menu is only open while the cursor is over either the context menu button to open it, or the menu itself.  If you mouse over the body of the page, the menu is dismissed.  (Side note: I think this is terrible UX but I'm not in a position to challenge it)  In previous versions of FF and in Chrome and IE the hover command in capybara, which calls the mouse_over from selenium, works fine.  It simply hovers the element.  The new action chaining determined from the W3C standards is that a user does not simply hover an element but rather uses the mouse to move to that element.  It now triggers all mouseenter events in a direct line from the last known cursor location.  (Another side note: This doesn't appear to be set with clicking, but it does with hovering)  This has had a negative impact on my testing of the menu.  When I click the context menu button, it opens the dialog as expected.  Then I call a hover on one of the options to expand a second tier of options.  This hover takes the mouse from the top left corner of the screen, where the cursor is positioned at the start of the tests, and triggers every mouseenter in a straight line to the element the hover was called on.  At some point on this path, the hover is not on the menu, so the menu is dismissed, then I'm presented with "unable to find visible css (Capybara::ElementNotFound)".  As I said, this is a valid failure, the element is no longer visible at some point DURING the hover.  When I call it, it is visible.  

The work-a-round is as follows, I must call hover before clicking the context menu button.  This sets the last known cursor location here.  Then I can hover the first few elements which are adjacent to the button.  By the 3rd or 4th element in the menu, the mouse must leave the button, cross the body of the page, and reenter the menu, to take a straight path.  Users do not do this.  To continue to lower elements, after the menu opens I must hover the top element in the list.  This sets the last known cursor location to the top of the list.  From this point any subsequent option in the list can be hovered because a straight line from the top of the list to the bottom of the list never crosses the body of the page and keeps the menu open.

My issue isn't that my tests are failing, per se.  My issue is the mouse movement that has been implemented.  [See the standards](https://www.w3.org/TR/webdriver/#dfn-perform-a-pointer-move) I believe this new functionality was based on.  When actions were removed from Firefox circa Firefox 48, the discussion was that they would be re implemented using the W3C standards that were TBD.  W3C was attempting to create standards that more closely resemble the user experience.  This has not been achieved in this case.  The user does not always take the mouse in a straight line from one point to another. 

My suggested solution to this is to write the duration to 0, such that when the mouse is moved for a hover, the default is an instantaneous movement of the mouse, triggering nothing from point A to point B.  This would replicate the previous function of hover.  If someone decides they want these events triggered they should be able to change this setting.  At the very least clicking should set the location of the cursor.
