### ISSUE TITLE
how to download the latest geckodriver without git tag?

### ISSUE THREAD

**Issue by abioneperhobby** [mozilla/geckodriver#1034]
i'm making a script to download all the latest version of all the driver i needed.
for the chrome driver i use the LATEST txt file in the binary folder in order to match and download the new one. 
For geckodriver there is not a binary folder (e.g.  https://chromedriver.storage.googleapis.com/index.html ) and i can't know how to understand, with http call, what the last tag version is in order to download

https://github.com/mozilla/geckodriver/releases/download/LATEST/geckodriver-v0.19.0-win64.zip

**Comment by andreastt** [comment]
A script to download the latest version is a terrible idea for a CI for all sorts of reliability versions. I would strongly encourage you to vendor the latest checked version instead.

To answer your question, you can get a list of tags by inspecting any git repository remotely (`git ls-remote --tags https://github.com/mozilla/geckodriver | awk '{print $2}'`) which you then need to parse with a semantic versioning library to find the latest version. It is also possible GitHub offers some special API for finding the latest release.

**Comment by abioneperhobby** [comment]
What do you mean for "I would strongly encourage you to vendor the latest checked version instead."? building the webdriver from the latest checkout from git?

**Comment by andreastt** [comment]
Yes that, or provide a binary you have previously tested and approved from a local store. This will not be affected by GitHub network outage or unavailability.

**Comment by abioneperhobby** [comment]
Sure
