### ISSUE TITLE
TypeError: 'block' member of ScrollIntoViewOptions 'nearest' is not a valid value for enumeration ScrollLogicalPosition.

### ISSUE THREAD

**Issue by vavdagic** [mozilla/geckodriver#1035]
## System
* Version: v0.19.0
* Platform: Windows 10
* Firefox: 56.0.2 (64-bit)
* Selenium: 3.6.0

## Testcase

                driver.execute_script ('''
                arguments[0].scrollIntoView({behavior: "instant", block: "nearest", inline: "nearest"});
                ''', node )

## Stacktrace

selenium.common.exceptions.WebDriverException: Message: TypeError: 'block' member of ScrollIntoViewOptions 'nearest' is not a valid value for enumeration ScrollLogicalPosition.

**Comment by andreastt** [comment]
`nearest` and `center` are only available in Firefox 58: https://bugzilla.mozilla.org/show_bug.cgi?id=1389274

**Comment by andreastt** [comment]
And this is not a geckodriver bug.

**Comment by vavdagic** [comment]
@andreastt thanks
