### ISSUE TITLE
geckodriver doesn't skip unknown names in capabilities

### ISSUE THREAD

**Issue by ElijahCapricorn** [mozilla/geckodriver#1038]
## System
* Version: geckodriver-v0.19.1-win64
* Platform: Windows 10 
* Firefox: 56.0.2

## Testcase
Run webdriver on local machine. 
Send **POST** request on [http://localhost:4444/session](http://localhost:4444/session) endpoint with capabilities:
```
{
  "desiredCapabilities": {
    "browserName": "firefox",
    "enableVNC": true
  },
  "capabilities": {
    "firstMatch": [{
      "browserName": "firefox",
      "enableVNC": true
    }]
  }
}
```
**enableVNC** is unknown capability and it comes from a tool named 'Selenoid'. 

Geckodriver returns an **invalid argument** error as a response:
```
{
  "value": {
    "error": "invalid argument",
    "message": "enableVNC is not a the name of a known capability or a valid extension capability",
    "stacktrace": "stack backtrace:
   0:       0x47e934 - <no info>
   1:       0x47f0a3 - <no info>
   2:       0x442649 - <no info>
   3:       0x4395f9 - <no info>
   4:       0x4430c6 - <no info>
   5:       0x42a890 - <no info>
   6:       0x406f5e - <no info>
   7:       0x40cfc9 - <no info>
   8:       0x6bef19 - <no info>
   9:       0x420756 - <no info>
  10:       0x6b96e0 - <no info>
  11:   0x7fffab8d2774 - BaseThreadInitThunk"
  }
}
```
Validation algorithm is described in W3C specification for WebDriver (https://w3c.github.io/webdriver/webdriver-spec.html). Section **7.2 Processing Capabilities** contains a definitions of **_validate capabilities_** algorithm. By specification the algorithm doesn't return an error for unknown names in fist match capabilities. 
## Expected result
Geckodriver should skip unknown names in first match capabilities and create new session.

**Comment by jleyba** [comment]
I think the behavior here is correct, even if the error is cryptic. You've request a new session using capabilities from `firstMatch`. Since `"enableVNC"` is unrecognized, geckodriver won't be able to match any of the requested capabilies and should thus fail to create the session.

**Comment by andreastt** [comment]
@jleyba is entirely correct. WebDriver is meant to complain about unrecognised keys in `firstMatch`/`alwaysMatch`/`capabilities`.

We have https://github.com/mozilla/geckodriver/issues/832 filed on improving the error messages for the New Session capabilities matching.
