### ISSUE TITLE
WebDriverException: Expected [object Undefined] undefined to be a string when calling WebElement.send_keys()

### ISSUE THREAD

**Issue by horsewithnoname1985** [mozilla/geckodriver#1047]
## System
* Version: 0.19.0
* Platform: Windows 7 64Bit
* Firefox: Nightly 58.0a1 (2017-11-06) (64-bit)
* Selenium: 3.6.0 (Python)

## Testcase
Script contains a call on a _selenium.webdriver.remote.webelement.WebElement.send_keys()_ such as:
my_web_element.send_keys(my_string_variable).
At this line the script crashes and the following exception is raised:
`selenium.common.exceptions.WebDriverException: Message: Expected [object Undefined] undefined to be a string`
even though the passed variable is definitely of the type string.
I used mozregression to track down the initial commit to this issue:
```
Bug 1348782: Updated expected key parameter for sendKeysToElement. r=ato

The expected command parameter has been updated from `value`
to `text`. This aligns marionette with W3C WebDriver
Send Keys To Element command.

MozReview-Commit-ID: EkQ1UJ58V7f
```

The first failing commit is:

> app_name: firefox
> build_date: 2017-03-28 13:47:44.880000
> build_file: C:\Users\Nyscan\.mozilla\mozregression\persist\04503f8fae7e--autoland--firefox-55.0a1.en-US.win64.zip
> build_type: inbound
> build_url: https://queue.taskcluster.net/v1/task/XTxuhhv2S6-GCOQivK-TPA/runs/0/artifacts/public%2Fbuild%2Ffirefox-55.0a1.en-US.win64.zip
> changeset: 04503f8fae7e9f91df17dcfdf61522ed482553b8
> pushlog_url: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=4599b4096eff86339a13917c28dd2a3762619040&tochange=04503f8fae7e9f91df17dcfdf61522ed482553b8
> repo_name: autoland
> repo_url: https://hg.mozilla.org/integration/autoland
> task_id: XTxuhhv2S6-GCOQivK-TPA

I attached a trace-log log below.

## Trace-level log

```
1509980138887	geckodriver	INFO	Listening on 127.0.0.1:52705
1509980142737	mozprofile::profile	INFO	Using profile path C:\Users\Nyscan\AppData\Local\Temp\rust_mozprofile.8fFPLztHbQ1x
1509980144287	geckodriver::marionette	INFO	Starting browser c:\\Users\\Nyscan\\AppData\\Local\\Temp\\tmpxbjfn3\\firefox\\firefox.exe
1509980144897	webdriver::server	DEBUG	Returning status InternalServerError
1509980144897	webdriver::server	DEBUG	Returning body {"error":"session not created","message":"Failed to start browser c:\\\\Users\\\\Nyscan\\\\AppData\\\\Local\\\\Temp\\\\tmpxbjfn3\\\\firefox\\\\firefox.exe: no such file or directory","stacktrace":"stack backtrace:\n   0:           0x4744af - <no info>\n   1:           0x475289 - <no info>\n   2:           0x437711 - <no info>\n   3:           0x41d7dc - <no info>\n   4:           0x405ca7 - <no info>\n   5:           0x6bff09 - <no info>\n   6:           0x415457 - <no info>\n   7:           0x6b1e73 - <no info>\n   8:         0x770f59cd - BaseThreadInitThunk"}
1509980144897	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1509980144897	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1509980144897	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(567) )
1509980144897	hyper::server::response	DEBUG	writing head: Http11 InternalServerError
1509980144897	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 44, tm_min: 55, tm_hour: 14, tm_mday: 6, tm_mon: 10, tm_year: 117, tm_wday: 1, tm_yday: 309, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 897242100 })) )
1509980144897	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 567
, Date: Mon, 06 Nov 2017 14:55:44 GMT
, }]
1509980144897	hyper::server::response	DEBUG	write 567 bytes
1509980144897	hyper::server::response	TRACE	ending
1509980144897	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:52710
1509980144897	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:52710
```

**Comment by andreastt** [comment]
I somewhat suspect you’re not using geckodriver 0.19.0 base don that output. Can you show what `geckodriver --version` outputs?

**Comment by horsewithnoname1985** [comment]
You're right. I totally missed that Firefox uses a copy of geckodriver.exe from C:\Program Files\Mozilla Firefox\ instead of the version I kept somewhere else, so was actually using geckodriver 0.14.0. I can't say, how that directory got into my system variables...
The issue does not occur on the latest Nightly built 58.0a1 (2017-10-06) and geckodriver 0.19.1.
Thanks for you hint!

**Comment by andreastt** [comment]
Thanks for the feedback! Glad it was fixed!

**Comment by bamaniyasamir19** [comment]
Firefox latest version, this is working with Geckodriver 0.19.1 version. Thank you for suggestion.
