### ISSUE TITLE
Can't change Firefox preferences by serenity.properties

### ISSUE THREAD

**Issue by vivregenek** [mozilla/geckodriver#1048]
erenity-core 1.6.0, selenium-java 3.5.3, geckodriver 0.19.0 FF 56.0.2 (64)

I am trying changed FF preferences with serenity.properties:
`firefox.preferences="browser.download.dir=C:\\temp;browser.helperApps.alwaysAsk.force=false;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.download.folderList=2;"`

But it doesn't work. In about:config I see deafult values for this preferences.  
Also get this entries in output

`INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
Separator = ;
arg = browser.download.dir=C:\temp\
arg = browser.helperApps.alwaysAsk.force=false
arg = browser.download.manager.showWhenStarting=false
arg = browser.download.useDownloadDir=true
arg = browser.download.folderList=2
arg = browser.helperApps.neverAsk.saveToDisk=text/html`

**Comment by vivregenek** [comment]
@whimboo actually it works for profile, somthing like this:
`FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("browser.download.folderList", 1);
profile.setPreference("browser.download.manager.showWhenStarting", false);
profile.setPreference("browser.download.useDownloadDir", true);`
WebDriver driver = new FirefoxDriver(profile);

But doesn't work for serenity.properties, what I need:
`firefox.preferences="browser.download.dir=C:\\temp;browser.helperApps.alwaysAsk.force=false;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.download.folderList=2;"`

It also work for chrome:
`hrome_preferences.profile.default_content_setting_values.automatic_downloads=2`

**Comment by andreastt** [comment]
What is `serenity.properties`? I don’t understand what this bug is about. Is it a file you specify preferences in? I can say straight away that it’s not a file geckodriver looks at.

I’m not sure what the relevance of Chrome is here. We are talking about two different browsers with different implementations.

Generally speaking you should use the `moz:firefoxOptions` dictionary to set preferences. See the README on how to use this capability.

**Comment by whimboo** [comment]
I assume it's that code we would have to look at:
https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/serenitybdd/core/webdriver/driverproviders/FirefoxDriverCapabilities.java

As it looks like FirefoxOptions are not really used to specify preferences. So as what I see this framework needs to be updated.

**Comment by vivregenek** [comment]
Thanks for all! @whimboo I will think what can do for Serenity project.
