### ISSUE TITLE
Click on element in iframe does not scroll the element into view

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1049]
## System
* Version: 0.19.1
* Platform: Windows 10 Fall Creators Update (1709)
* Firefox: 56, 57, Nightly 58.0a1 (2017-11-06)
* Selenium: 3.5.3

## Testcase

The following Java Selenium test clicks on a button inside an iframe which is not visible in the viewport.
The `WebElement.click()` has to scroll the element into view before clicking on it.
This "scroll into view" does not happen and, even worse, the click fails silently (has no effect).
Therefore the last assert in the test fails.

```java
@Test
public void testClickOnButtonInIFrameOutsideViewport() {
    // given
    driver.navigate().to("http://localhost/iframe-outside-viewport.html");
    driver.switchTo().frame(0);
    WebElement button = driver.findElementByTagName("button");

    // when
    button.click(); // does nothing / fails silently

    // then
    WebElement clickCount = driver.findElementById("click-count");
    assertEquals("1", clickCount.getText().trim()); // <<== FAILS
}
```
HTML pages (just host them at http://localhost):
[iframe-outside-viewport-html.zip](https://github.com/mozilla/geckodriver/files/1450041/iframe-outside-viewport-html.zip)

## Stacktrace
```java
org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at IFrameOutsideViewportTests.testClickOnButtonInIFrameOutsideViewport2(IFrameOutsideViewportTests.java:49)
```

## Trace-level log

[geckodriver-log.txt](https://github.com/mozilla/geckodriver/files/1450053/geckodriver-log.txt)

**Comment by codingphil** [comment]
Just noticed that there is already a similar issue:
https://github.com/mozilla/geckodriver/issues/1039

**Comment by whimboo** [comment]
Yes, lets track that all in this other issue.
