### ISSUE TITLE
switch_to.frame seems not to work?

### ISSUE THREAD

**Issue by hjwp** [mozilla/geckodriver#105]
tried two different ways:

```python
driver.switch_to.frame('myiframe')
```

and

```python
iframe = driver.find_element_by_css_selector('iframe[name="myiframe"]')
driver.switch_to.frame(iframe)
```

both give:

```
NoSuchFrameException: Message: frame id has unexpected type
```

Here's the html of my iframe:

```html
<iframe width="50%" class="soft_keyboard_sensitive" src="/blabla/" name="myifame" id="id_console" style="height: 694px; width: 1274px;">
</iframe>
```

firefox 46, geckodriver 0.8

**Comment by vladikoff** [comment]
@hjwp might help https://github.com/mozilla/geckodriver/issues/46#issuecomment-187346333

**Comment by hjwp** [comment]
sorry, that does look like a duplicate.  I promise i did do a search!  Must have missed it.

**Comment by hjwp** [comment]
But that issue is closed?  It doesn't work even if I pass a reference to the element...

**Comment by vladikoff** [comment]
@hjwp yeah I also had trouble with frame switching. Probably need to somehow attach a trace log of what is happening.

**Comment by hjwp** [comment]
Sorry.  I was being an idiot.  I only fixed one occurrence of my switch_to.frame, i was still using the name parameter in the other.  sorry sorry sorry.

**Comment by andreastt** [comment]
@vladikoff @hjwp I imagine we will have to come up with a shim for the Selenium API clients when speaking to WebDriver-conformant remotes, much like we have for _Get Element Attribute_ in https://github.com/SeleniumHQ/selenium/issues/2301#issuecomment-227206507.

**Comment by vladikoff** [comment]
@andreastt yeah, sadly especially if Safari's "WebDriver" is gonna be using Selenium APIs

**Comment by andreastt** [comment]
@vladikoff I don’t know anything about that, but if the client bindings provide shims that make it possible to use Selenium and W3C WebDriver remotes interchangeably, the path of switching to providing a spec conformant remote API will be easy.

In this sense Marionette/Mozilla is leading the way by laying the groundwork for a future interoperable WebDriver.
