### ISSUE TITLE
Mouse move is not working FF 56 and geko v19

### ISSUE THREAD

**Issue by anuvratashu** [mozilla/geckodriver#1052]
## System
* Version: geckodriver-v0.19.1
* Platform: Windows
* Firefox: FF 56
* Selenium: selenium-server-standalone-3.7.1.jar

When trying to mouse move ,it says not supported
mouseMoveClick() :: in FF
(node:6996) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WebDriverError: null
click() :: in FF
click() :: in FF
(node:6996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

#

**Comment by andreastt** [comment]
This sounds like a programming problem in your script, but it is definitely not geckodriver related.
