### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by dyrby76** [mozilla/geckodriver#1053]
The license file was created and listed in the changes.md file as begin added in version 0.6.2.
There is no mention of it being removed or changed, yet the license file is no longer there.

The commits show it was added:

commit cb22af6bbb65142c224a567f2d6d2734b07574d1 refs/tags/v0.6.2
Author: Joshua Bruning <joshbruning@gmail.com>
Date:   Fri Jan 15 00:00:42 2016 +0000

**Comment by dyrby76** [comment]
The file was removed in this commit: 4030c529d6b10b0d9e00cd08b5fb43579fe8a290

**Comment by andreastt** [comment]
geckodriver’s canonical repository is mozilla-central: https://searchfox.org/mozilla-central/source/testing/geckodriver

We only use the GitHub repo for issue triage and distribution of binaries.

**Comment by dyrby76** [comment]
The binaries doesn’t contain the LICENSE file anymore

**Comment by andreastt** [comment]
I don’t understand what it means for a binary to contain a text file.

**Comment by elgohr** [comment]
This might help you to understand https://opensource.guide/legal/#are-public-github-projects-open-source

**Comment by andreastt** [comment]
@elgohr Did you read my earlier reply? Our GitHub repository is no longer the canonical source of geckodriver.
