### ISSUE TITLE
not able to communicate with firefox  

### ISSUE THREAD

**Issue by chalakprabhu** [mozilla/geckodriver#1054]
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by chalakprabhu** [comment]
plz give me solution

**Comment by curtisy1** [comment]
We don't even know what the problem is without any kind of information.

Please provide a Trace-Log or a Test-Case or at least describe your problem.

**Comment by andreastt** [comment]
Read more about reporting actionable bugs in our [contribution guidelines].

[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by chalakprabhu** [comment]
![screenshot 17](https://user-images.githubusercontent.com/30229373/32643789-99adb640-c603-11e7-8b04-7eb7c85112db.png)


i am updated latest version of  gecko driver & 52.0.20 firefox version

**Comment by chalakprabhu** [comment]
![screenshot 17](https://user-images.githubusercontent.com/30229373/32643890-512dcc4c-c604-11e7-9e07-01224d43e3e4.png)

**Comment by chalakprabhu** [comment]
plzz give me solution on this problem.
Thanks in advance.

**Comment by curtisy1** [comment]
If I'm not mistaken, geckodriver recommends Firefox >52. Any specific
reason you're not updating Firefox?

As for the issue, it looks like this happens at the exec command, which to
be honest I have no idea what it does (or rather what the executable you
call does). Can you add something like driver.loglevel =
FirefoxDriverLogLevel.Trace below the Webdriver instantion so we can get a
Tracelog?

chalakprabhu <notifications@github.com> schrieb am Fr., 10. Nov. 2017,
06:12:

**Comment by mgavilan** [comment]
Looking at [Changelog for geckdrover version 0.19.0](https://github.com/mozilla/geckodriver/releases/tag/v0.19.0) it is even recommended to use **_Firefox 55 (and greater)_**. Don't think you'll be succeesful with Firefox version 52.

Even the Selenium Version needs to be a pretty ne one (**_Selenium 3.5 and greater_**), but I don't know whether your are already using an up-to-date selenium version.

**Comment by chalakprabhu** [comment]
yes am using selenium 3.7.0 version

**Comment by mgavilan** [comment]
OK fine, that's already the first step! Now you may consider to update your Firefox browser version to at least 55, as this is explicitely mentioned as first supported Firefox version for geckodriver 0.19.0!
