### ISSUE TITLE
Browser under remote control for Firefox version 57- Geckodriver19.0-selenium-server-standalone-3.7.1

### ISSUE THREAD

**Issue by Geethachock** [mozilla/geckodriver#1057]
System
 * Version: <geckodriver-v0.19.1>
* Platform: <Windows 10>
* Firefox: <57.0 (64-bit)>
* Selenium: <selenium-server-standalone-3.7.1>******

## Testcase
**when I run my testcase for opening the amazon url, it opens but the browser window says the browser under remote control and shows a crash icon in my firefox browser**

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver", "C:\\Program Files\\Geckodrive\\geckodriver.exe");
		DesiredCapabilities capabilities=DesiredCapabilities.firefox();
               capabilities.setCapability("marionette", true);
	      WebDriver driver= new FirefoxDriver();
	      driver.manage().window().maximize();
	      driver.get("https://www.amazon.com/");

	}

}

**Error Log**
1510748901646	geckodriver	INFO	geckodriver 0.19.1
1510748901652	geckodriver	INFO	Listening on 127.0.0.1:40190
1510748902450	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Geetha\\AppData\\Local\\Temp\\rust_mozprofile.od2PW7I8TJfd"
1510748903251	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Geetha\AppData\Local\openvr\openvrpaths.vrpath
[Child 10944, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 10944, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1510748907133	Marionette	INFO	Listening on port 52444
1510748907664	Marionette	WARN	TLS certificate errors will be ignored for this session
1510748907736	Marionette	DEBUG	Register listener.js for window 4294967297
Nov 15, 2017 5:28:27 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1510748911339	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1510748911751	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1510748911751	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1510748912498	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.amazon.com/"
1510748925806	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.amazon.com/"

**Comment by whimboo** [comment]
If you are saying that the location bar has an alternating background and a robot visible, then this is expected. That is not a crash.

I can the the IPC issues which could indicate a crash, but I miss further information. So please attach a trace log for that run. The howto was listed in the new issue template, but can be found at https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html.

**Comment by Geethachock** [comment]
Yes, you are correct, it shows an alternating background and a robot visible.  How to resolve this?
I am new to selenium, Please suggest what version of firefox, selenium jar and gecodriver works fine.

**Comment by Geethachock** [comment]
yes you are correct, an alternating background and a robot is visible. How to resolve this?
If this is expected, as I am new to selenium ,can you plz suggest which version of firefox, selenium jar and gecko driver works fine?

**Comment by whimboo** [comment]
Yes this is all expected. But what I don't understand is this part of your original comment: " shows a crash icon". What does that mean?

In regards of versions please always use at least the latest releases of all of them.

**Comment by iulianvechiu** [comment]
Anymore info on this ? I seem to also have the problem running the same setup. The browser can only set itself on the url but can't interact with any elements, keeps trying untill all the tests fail. I'm figuring the new Firefox can't use geckodriver 0.19.1 ? Can i get a confirmation on that?

**Comment by eskomj** [comment]
I found same kind of problem. I have WebDriver / Java and Geckodriver 0.19.1. When I try to run my test, which previously worked with old Firefox version, it won't do nothing but opens browser window. I have maven project dependency as follows:

<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-java</artifactId>
		<version>3.7.1</version>
	</dependency>
	<dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>htmlunit-driver</artifactId>
	    <version>2.28</version>
	</dependency>

**Comment by whimboo** [comment]
As long as we don't get any trace log as requested above, there is nothing we can do here.

I'm happy to reopen the issue once such a log has been provided.

**Comment by eskomj** [comment]
Here is trace:

org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'
System info: host: 'EW7K0798', ip: '157.129.249.150', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:131)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:116)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
	at fi.tulli.liitu.testit.LiitteenLatausSof.testNettiLiituLiitteenLatausSof(LiitteenLatausSof.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:166)
	at junit.framework.TestCase.runBare(TestCase.java:140)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:131)
	at junit.framework.TestSuite.runTest(TestSuite.java:173)
	at junit.framework.TestSuite.run(TestSuite.java:168)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:13567/hub/status] to be available after 45003 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:129)
	... 26 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 27 more

**Comment by iulianvechiu** [comment]
`1511772570351   geckodriver     INFO    geckodriver 0.19.1
1511772570353   webdriver::httpapi      DEBUG   Creating routes
1511772570363   geckodriver     INFO    Listening on 127.0.0.1:4444
1511772652766   webdriver::server       DEBUG   -> POST /wd/hub/session {"desiredCapabilities":{"browserName":"firefox"}}
1511772652802   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"POST /wd/hub/session did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772653026   webdriver::server       DEBUG   -> POST /wd/hub/session//window/current/maximize
1511772653029   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"POST /wd/hub/session//window/current/maximize did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772653970   webdriver::server       DEBUG   -> POST /wd/hub/session//url {"url":"http:\/\/vd-dev.atf.atf-all46208-all-dev.atf.c.emag.network\/ro-en\/user\/auth\/login"}
1511772653973   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"POST /wd/hub/session//url did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772654198   webdriver::server       DEBUG   -> POST /wd/hub/session//element {"using":"id","value":"login"}
1511772654200   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"POST /wd/hub/session//element did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772654418   webdriver::server       DEBUG   -> GET /wd/hub/session//log/types
1511772654419   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /wd/hub/session//log/types did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772654630   webdriver::server       DEBUG   -> POST /wd/hub/session//log {"type":"unknown command"}
1511772654632   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"POST /wd/hub/session//log did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772654861   webdriver::server       DEBUG   -> GET /wd/hub/session//screenshot
1511772654862   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /wd/hub/session//screenshot did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772655062   webdriver::server       DEBUG   -> GET /wd/hub/session//source
1511772655064   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /wd/hub/session//source did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772655296   webdriver::server       DEBUG   -> DELETE /wd/hub/session//cookie
1511772655298   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"DELETE /wd/hub/session//cookie did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}
1511772655518   webdriver::server       DEBUG   -> DELETE /wd/hub/session/
1511772655520   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"DELETE /wd/hub/session/ did not match a known command","stacktrace":"stack backtrace:\n   0:           0x47e934 - <no info>\n   1:           0x47f0a3 - <no info>\n   2:           0x442649 - <no info>\n   3:           0x43c3f0 - <no info>\n   4:           0x40530f - <no info>\n   5:           0x40d01a - <no info>\n   6:           0x6bef19 - <no info>\n   7:           0x420b85 - <no info>\n   8:           0x6b96e0 - <no info>\n   9:     0x7ff938528364 - BaseThreadInitThunk"}}`

**Comment by andreastt** [comment]
@iulianvechiu Looks like there's something wrong with your client. It is requesting `/wd/hub/session`, whereas the geckodriver endpoint is just `/session`.

**Comment by iulianvechiu** [comment]
Sorry for all the ruckus, apparently the issue is not with the geckodriver, but with Selenium. 3.4.0 is the latest version that works apparently, everything above will return undefined index upon searching for elements.

**Comment by whimboo** [comment]
@iulianvechiu if you haven't checked a [trace level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) for more up-to-date versions of Selenium please do so. If the failure comes from geckodriver or Marionette please feel free to raise another issue with all the details.

**Comment by eskomj** [comment]
I tried to set trace log on with this, but I don't know where I can find trace log. It's not there where is gecko driver.

FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.TRACE);
driver = new FirefoxDriver(options);

**Comment by whimboo** [comment]
It might depend on the binding you are using, which I don't know what it is. But generally have a look at a `geckodriver.log` file in the current working directory first.

**Comment by andreastt** [comment]
The geckodriver log in the Java binding goes to stdout by default, I believe.

**Comment by eskomj** [comment]
I got geckodriver working with this modification. Log comes to console.
//System.setProperty("webdriver.firefox.marionette","C:\\temp\\geckodriver.exe");
System.setProperty("webdriver.gecko.driver", "C:\\temp\\geckodriver.exe");

**Comment by plutosolutions** [comment]
It work for me when geckodriver@1.10.0 and Firefox 57.0 (64 bits).

**Comment by sandeepjain1987** [comment]
Which is the latest stable Firefox , selenium stand-alone jar and  gecko driver version that works with remote webdriver and not standalone?
