### ISSUE TITLE
Error while installing geckodriver in Protractor - npm install --save geckodriver

### ISSUE THREAD

**Issue by nalandha** [mozilla/geckodriver#1064]
## System
* Geckodriver Version: 1.10.0 
* Platform: Windows + 2007
* Firefox: v57
* Protractor: npm - 5.5.1

## Testcase

Unable to install geckodriver in the protractor framework 

I have listed the current npm version installed in my system and the error which occurs when i try to install geckodriver.I read [npm module version] - [geckodriver version] 1.10.x - geckodriver 0.19.1 in geckodriver npm site.It looks i have the 1.10.1 version only installed.Still i face error while installation.Also ran **webdriver-manager update** which unzipps the v0.19.1.zip

C:\Users\crk>**npm version**

{ npm: '5.5.1',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '57.1',
modules: '48',
node: '6.9.2',
openssl: '1.0.2j',
uv: '1.9.1',
v8: '5.1.281.88',
zlib: '1.2.8' }

W:\Wgn\JS_UIAutomation>**npm install --save geckodriver**

    geckodriver@1.10.0 postinstall W:\Wgn\JS_UIAutomation\node_modules\geckodriver node index.js

Downloading geckodriver... events.js:160 throw er; // Unhandled 'error' event ^

RequestError: connect ETIMEDOUT 192.30.253.113:443 at ClientRequest. (W:\Wgn\JS_UIAutomation\node_modules\got\index.js:69:21) at ClientRequest.g (events.js:291:16) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at TLSSocket.socketErrorListener (_http_client.js:310:9) at emitOne (events.js:96:13) at TLSSocket.emit (events.js:188:7) at emitErrorNT (net.js:1278:8) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9) npm WARN Error: EPERM: operation not permitted, scandir 'W:\Wgn\JS_UIAutomation\node_modules\geckodriver\node_modules' npm WARN at Error (native) npm WARN { Error: EPERM: operation not permitted, scandir 'W:\Wgn\JS_UIAutomation\node_modules\geckodriver\node_modules' npm WARN at Error (native) npm WARN stack: 'Error: EPERM: operation not permitted, scandir

\'W:\Walgreens\JS_UIAutomation\node_modules\geckodriver\node_modules\'\n at Error (native)', npm WARN errno: -4048, npm WARN code: 'EPERM', npm WARN syscall: 'scandir', npm WARN path: 'W:\Walgreens\JS_UIAutomation\node_modules\geckodriver\node_modules' } npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! geckodriver@1.10.0 postinstall: node index.js npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the geckodriver@1.10.0 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by whimboo** [comment]
This is not an issue tracker for the node-geckodriver package. Instead please get in contact with the maintainer of that package. Thanks.
