### ISSUE TITLE
Failed to select options by visible text, if the text with '&lrm;'

### ISSUE THREAD

**Issue by adam-zjy** [mozilla/geckodriver#1066]
## System
* Version: v0.19.0
* Platform: Windows/Mac
* Firefox: 56
* Selenium: 3.5.3

## Testcase

Xpath = //span[@id='sf_career_lang_container']//select
Select select = new Select(By.xpath);

select.selectByVisibleText("English Debug"); //Success
select.selectByVisibleText("Deutsch (German)"); //Fail

![2017-11-20_10-59-20](https://user-images.githubusercontent.com/16423729/33000416-d8365ca0-cde2-11e7-86b4-66705370e309.png)

[select inner HTML.txt](https://github.com/mozilla/geckodriver/files/1486852/select.inner.HTML.txt)

## Stacktrace

1511146066192	webdriver::server	DEBUG	-> POST /session/486169c7-3347-4743-a8d5-43ea31da5439/element/7b003815-e70c-a445-af22-c6e35078fa49/elements {"using":"xpath","id":"7b003815-e70c-a445-af22-c6e35078fa49","value":".//option[normalize-space(.) = \"Deutsch (German)\"]"}
1511146066192	geckodriver::marionette	TRACE	-> 152:[0,234,"findElements",{"element":"7b003815-e70c-a445-af22-c6e35078fa49","using":"xpath","value":".//option[normalize-space(.) = \"Deutsch (German)\"]"}]
1511146066193	Marionette	TRACE	0 -> [0,234,"findElements",{"element":"7b003815-e70c-a445-af22-c6e35078fa49","using":"xpath","value":".//option[normalize-space(.) = \"Deutsch (German)\"]"}]
1511146066201	Marionette	TRACE	0 <- [1,234,null,[]]
1511146066201	geckodriver::marionette	TRACE	<- [1,234,null,[]]
1511146066202	webdriver::server	DEBUG	<- 200 OK {"value":[]}
1511146136237	webdriver::server	DEBUG	-> POST /session/486169c7-3347-4743-a8d5-43ea31da5439/element/7b003815-e70c-a445-af22-c6e35078fa49/elements {"using":"xpath","id":"7b003815-e70c-a445-af22-c6e35078fa49","value":".//option[contains(., \"(German)\")]"}
1511146136237	geckodriver::marionette	TRACE	-> 136:[0,235,"findElements",{"element":"7b003815-e70c-a445-af22-c6e35078fa49","using":"xpath","value":".//option[contains(., \"(German)\")]"}]
1511146136237	Marionette	TRACE	0 -> [0,235,"findElements",{"element":"7b003815-e70c-a445-af22-c6e35078fa49","using":"xpath","value":".//option[contains(., \"(German)\")]"}]
1511146136243	Marionette	TRACE	0 <- [1,235,null,[{"element-6066-11e4-a52e-4f735466cecf":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0","ELEMENT":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0"}]]
1511146136244	geckodriver::marionette	TRACE	<- [1,235,null,[{"element-6066-11e4-a52e-4f735466cecf":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0","ELEMENT":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0"}]]
1511146136244	webdriver::server	DEBUG	<- 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0"}]}
1511146184839	webdriver::server	DEBUG	-> GET /session/486169c7-3347-4743-a8d5-43ea31da5439/element/8c4b9b70-73a1-d74d-adba-40a8f5837ed0/text 
1511146184839	geckodriver::marionette	TRACE	-> 70:[0,236,"getElementText",{"id":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0"}]
1511146184840	Marionette	TRACE	0 -> [0,236,"getElementText",{"id":"8c4b9b70-73a1-d74d-adba-40a8f5837ed0"}]
1511146184849	Marionette	TRACE	0 <- [1,236,null,{"value":"Deutsch ‎(German)‎"}]
1511146184850	geckodriver::marionette	TRACE	<- [1,236,null,{"value":"Deutsch ‎(German)‎"}]
1511146184850	webdriver::server	DEBUG	<- 200 OK {"value":"Deutsch ‎(German)‎"}

==================================================================
I think the root cause is that WebElement.getText() will return an extra block for the "lrm" so the expected str is not matched with the one get from the HTML source.

**Comment by whimboo** [comment]
This happens because `findElement(s)` doesn't take the rendered text into account. We cover that case already via issue #802.
