### ISSUE TITLE
The driver executable does not exist

### ISSUE THREAD

**Issue by chalakprabhu** [mozilla/geckodriver#1072]
gecko version : 0.19.0
win 10 64 bit
firefox 55.0.3
java binding 3.7.1not able to communicate  with 
![screenshot 31](https://user-images.githubusercontent.com/30229373/33167365-56a9f63c-d063-11e7-8737-e7d5d8276da1.png)
browser

**Comment by andreastt** [comment]
The exception is pretty self-explanatory. That binary does not exist on the file system.

In any case, this is not a geckodriver bug.
