### ISSUE TITLE
Erroe: Message: Expected [object Undefined] undefined to be a string

### ISSUE THREAD

**Issue by HeisenbergTP** [mozilla/geckodriver#1077]
## System
* Version: 
geckodriver 0.14.0
* Platform: 
Ubuntu 16.04
* Firefox: 
Mozilla Firefox 59.0a1
* Selenium: 
 __version__ = '3.7.0'

## Stacktrace

Getting this error via python
Mon Nov 27 09:42:37 2017       fatal                exception                      Message: Expected [object Undefined] undefined to be a string

## Trace-level log

None

**Comment by whimboo** [comment]
This report doesn't contain enough information that we can react on it. So specify the code you are using, or/and attach the trace level log. I'm happy to reopen then.
