### ISSUE TITLE
Clicking any element freezes the whole browser

### ISSUE THREAD

**Issue by eirslett** [mozilla/geckodriver#1078]
## System
* Version: 0.19.0
* Platform: MacOS
* Firefox: 56.0
* Selenium: I use node + node-geckodriver directly, not via Selenium (I think)

## Testcase
With selenium/geckodriver:

1) open [https://listen.tidal.com](https://listen.tidal.com)
2) click on any item - for example the "login" button which has CSS selector `[data-test-id="no-user--login"]`

The browser freezes.

Can anybody else reproduce this? I'm not sure what it's caused by. It would take a while to distill a minimal reproducible example...

**Comment by andreastt** [comment]
When it “freezes”, what do you actually mean?

If you could attach a [trace-level log] that would be much appricated.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by eirslett** [comment]
When it "freezes", it means the browser page becomes unresponsive. It's just like a still image. You cannot interact with it, none of the buttons can be clicked. When you resize the browser window, it doesn't reflow or rerender anything, it just pads the extra space with white color. Scrolling is not possible.
I can open another browser tab with another web site, which works fine. So it's just the tab that is controlled by GeckoDriver that is frozen.

Before GeckoDriver triggered the click, I could interfere with the browser tab running the integration test, click the button manually, which worked like expected. The browser freezes when GeckoDriver tries to click.

**Comment by eirslett** [comment]
Here is a node.js script to reproduce (you need to npm install selenium-webdriver and geckodriver):

```
import webdriver from 'selenium-webdriver';
import firefox from 'selenium-webdriver/firefox';
import until from 'selenium-webdriver/lib/until';
import 'geckodriver';

const { By } = webdriver;

export default function createSession () {
  const options = new firefox.Options()

  const service = new firefox.ServiceBuilder()
    .enableVerboseLogging(true)
    .build();

  return firefox.Driver.createSession(options, service)
}

async function run () {
  const driver = createSession();
  await driver.get('https://listen.tidal.com');
  await driver.wait(until.elementLocated(By.css('[data-test-id=no-user--login]')), 30000);
  const element = await driver.findElement(By.css('[data-test-id=no-user--login]'));
  console.log('Found the element, now click it.');
  await element.click();
  console.log('The element was clicked.');
}

run().then(console.log).catch(console.error)
```

**Comment by whimboo** [comment]
And manually clicking the button doesn't cause such a freeze?

**Comment by eirslett** [comment]
> And manually clicking the button doesn't cause such a freeze?

correct.

**Comment by whimboo** [comment]
I cannot see a freeze by clicking the login button, but using webdriver interactability checks I get a failure:

> ElementClickInterceptedException: Element <a class="btn js-login current-user__login" href="/login"> is not clickable at point (124.5,130.3000030517578) because another element <embed id="sm2movie" name="sm2movie" src="/soundmanager2_flash9.6080e2.swf" type="application/x-shockwave-flash"> obscures it

I would suggest that you run your test again with the latest Firefox 58 beta release, and supply the trace log as requested earlier by @andreastt. Thanks.

**Comment by eirslett** [comment]
> I cannot see a freeze by clicking the login button, but using webdriver interactability checks I get a failure:

If you try to "click" (with selenium webdriver) this element instead: `data-test-id="menu--my-music"` do you get the same ElementClickInterceptedException  error? I experience the browser freeze independent of which element I click on the page.
The `sm2movie` thing might be unrelated - I experienced a problem related to that in Google Chrome as well. There is an invisible flash element running on top of the Login button, which causes other problems. The "my music" link is not covered.

> and supply the trace log as requested earlier by @andreastt. Thanks.

How can I find the trace logs? Are they stored to disk somewhere? My script doesn't output anything...

**Comment by whimboo** [comment]
When you use Firefox 57 can you please set the capability `moz:webdriverClick` to `True`? See https://dxr.mozilla.org/mozilla-central/source/testing/geckodriver/README.md#283.

It will enable the same click behavior in Firefox 57, so it may also fix your problem with this release.
