### ISSUE TITLE
Unable to find the iframe 

### ISSUE THREAD

**Issue by anandkerur** [mozilla/geckodriver#1079]
## System
* Version: geckodriver version 0,18.0 
* Platform: Windows 10
* Firefox: -56 
* Selenium: 3.6.0 

Shows issue as :+1: 
: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //iframe[@id="content"]' (tried for 125 second(s) with 500 MILLISECONDS interval)

Please help me

**Comment by whimboo** [comment]
Sorry, but this issue doesn't contain any information which allows us to help. So paste your code, examples, and most importantly the trace log from running the test. I'm happy to reopen in case this information can be provided.
