### ISSUE TITLE
No permission to access jQuery from selenium javascript executor 

### ISSUE THREAD

**Issue by neeasade** [mozilla/geckodriver#108]
Firstly, thanks to the authors/contributors of this project. 

## Versions
- Selenium version 2.53, .NET bindings
- marionette/geckdriver version 0.8, renamed to wires.exe in path. 
- Firefox 47 stable

## Issue
On a webpage with jquery loaded, I use the following to check for active ajax calls:
``` cs
return (bool)((IJavaScriptExecutor)webdriver).ExecuteScript("return jQuery.active == 0") == true;
```

When the above executes, I get the following `InvalidOperationException`:
``` txt
An exception of type 'System.InvalidOperationException' occurred in WebDriver.dll but was not handled in user code

Additional information: Error: Permission denied to access property "jQuery" (UnexpectedJavaScriptError)
```

I am launching firefox with the following (derived from issue #91):
``` cs
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
IWebDriver driver = new FirefoxDriver(service);
```

The above code functions as expected in Firefox46 + non-marionette setting.

Is this intended behavior (not allowing JS access now) or a bug?

edit: also apologies if this should be filed with selenium.

**Comment by andreastt** [comment]
Fixed in [bug 1123506](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506), which is available in Firefox >= 48.

More generally, Firefox 46 and 47 are not supported.
