### ISSUE TITLE
Process unexpectedly closed with status: {unknown}

### ISSUE THREAD

**Issue by hqbrice** [mozilla/geckodriver#1088]
## System
* Version: 0.19.1
* Platform: CentOS 7
* Firefox:  V57
* Selenium: 3.7.1

## Testcase

```
DesiredCapabilities capability = new DesiredCapabilities();
capability.setBrowserName("firefox");
FirefoxOptions firefoxOptions = new FirefoxOptions(); 
firefoxOptions.setLogLevel(FirefoxDriverLogLevel.TRACE);
capability.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions);
String url = "http://" + getConfig("selenium.hub.adress")+ ":" + getConfig("selenium.hub.port")+"/wd/hub";
webDriver = new RemoteWebDriver(new URL(url), capability);
```

## Starting Selenium

Xvfb :99 -ac is launch before

```
export DISPLAY=:99

nohup /test/tools/Java/jdk1.8.0_40/bin/java -Dwebdriver.gecko.driver=$GECKO -Dwebdriver.chrome.driver=/test/tools/slave/selenium/webdrivers/chromedriver -jar /test/tools/slave/selenium/standalone/selenium-server-standalone-3.7.1.jar -role webdriver -hub http://10.1.11.20:44444/grid/register -port 5556 -host 10.1.11.22 -browser "browserName=firefox, maxInstances=1, platform=LINUX, seleniumProtocol=WebDriver, version=POSTGRES.CENTOS_1" -browser "browserName=chrome,version=POSTGRES.CENTOS_1,maxInstances=1,platform=LINUX" >>/test/tools/slave/selenium.log 2>/test/tools/slave/selenium-err.log &
```

## Stacktrace

```
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status: {unknown}
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.5.2.el7.x86_64', java.version: '1.8.0_40'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43
   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
Caused by: org.openqa.selenium.WebDriverException: Process unexpectedly closed with status: {unknown}
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.5.2.el7.x86_64', java.version: '1.8.0_40'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43
   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
```

## Trace-level log

```
16:26:25.234 INFO - Capabilities are: Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:firefoxOptions: {args: [], log: {level: trace}, prefs: {}}, version: POSTGRES.CENTOS_1}
16:26:25.236 INFO - Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:firefoxOptions: {args: [], log: {level: trace}, prefs: {}}, version: POSTGRES.CENTOS_1} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1512401185456   geckodriver     INFO    geckodriver 0.19.1
1512401185460   geckodriver     INFO    Listening on 127.0.0.1:21666
1512401185676   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.p0Jxumh4TNxx"
1512401185703   geckodriver::marionette TRACE     connection attempt 0/600
1512401185804   geckodriver::marionette TRACE     connection attempt 1/600
1512401185904   geckodriver::marionette TRACE     connection attempt 2/600
1512401186005   geckodriver::marionette TRACE     connection attempt 3/600
1512401186105   geckodriver::marionette TRACE     connection attempt 4/600
1512401186206   geckodriver::marionette TRACE     connection attempt 5/600
1512401186306   geckodriver::marionette TRACE     connection attempt 6/600
1512401186407   geckodriver::marionette TRACE     connection attempt 7/600
1512401186507   geckodriver::marionette TRACE     connection attempt 8/600
1512401186608   geckodriver::marionette TRACE     connection attempt 9/600
ExceptionHandler::GenerateDump cloned child 2788
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1512401186714   geckodriver::marionette TRACE     connection attempt 10/600
1512401186814   geckodriver::marionette TRACE     connection attempt 11/600
1512401186920   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: {unknown}","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43\n   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684\n   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
```

**Comment by andreastt** [comment]
Not sure why this happens, especially why the process exits with an unknown status. It’s also not clear to me if it’s the geckodriver or Firefox process that exits: I’m assuming it is the latter.

Is this consistently reproducible? Have you tried Firefox Nightly?

**Comment by hqbrice** [comment]
Yes, it's consistently reproducible with FF 57
Tried with Firefox Nightly : The problem is reproduced in 3 attempts
How can I help you to get if crash comes from driver or browser ?

**Comment by whimboo** [comment]
Can you please run the test with a debug Nightly build of Firefox? You can find one here:

https://queue.taskcluster.net/v1/task/cbY2rrQXRC6QD-O1fM7zLQ/runs/0/artifacts/public/build/target.tar.bz2

It will dump way more output to the log which should give us an indication. I'm fairly sure it's Firefox which unexpectedly closes.

**Comment by hqbrice** [comment]
This is I get : 
`1512494150555   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.TIyHMl6iPpDY"
1512494150580   geckodriver::marionette TRACE     connection attempt 0/600
1512494150681   geckodriver::marionette TRACE     connection attempt 1/600
1512494150781   geckodriver::marionette TRACE     connection attempt 2/600
1512494150882   geckodriver::marionette TRACE     connection attempt 3/600
1512494150982   geckodriver::marionette TRACE     connection attempt 4/600
1512494151083   geckodriver::marionette TRACE     connection attempt 5/600
1512494151183   geckodriver::marionette TRACE     connection attempt 6/600
1512494151283   geckodriver::marionette TRACE     connection attempt 7/600
1512494151384   geckodriver::marionette TRACE     connection attempt 8/600
1512494151490   geckodriver::marionette TRACE     connection attempt 9/600
ExceptionHandler::GenerateDump cloned child 2764
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1512494151597   geckodriver::marionette TRACE     connection attempt 10/600
1512494151698   geckodriver::marionette TRACE     connection attempt 11/600
1512494151798   geckodriver::marionette TRACE     connection attempt 12/600
1512494151899   geckodriver::marionette TRACE     connection attempt 13/600
1512494152006   geckodriver::marionette TRACE     connection attempt 14/600
1512494152141   geckodriver::marionette TRACE     connection attempt 15/600
1512494152247   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: {unknown}","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43\n   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684\n   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
`
No more than release.
But, I didn't reproduce in headless mode. Is it normal ?

**Comment by andreastt** [comment]
That log tells us you’re using /usr/bin/firefox, which is presumably not the build @whimboo linked to?

**Comment by hqbrice** [comment]
I removed Firefox and install it from https://ftp.mozilla.org/pub/firefox/nightly/2017/12/2017-12-04-23-41-37-mozilla-central/firefox-59.0a1.en-US.linux-x86_64.tar.bz2 file.

**Comment by hqbrice** [comment]
`wget https://ftp.mozilla.org/pub/firefox/nightly/2017/12/2017-12-04-23-41-37-mozilla-central/firefox-59.0a1.en-US.linux-x86_64.tar.bz2
tar xjf firefox-59.0a1.en-US.linux-x86_64.tar.bz2
sudo rm -r /opt/firefox
sudo mv firefox /opt/firefox
sudo ln -s /opt/firefox57/firefox /usr/bin/firefox
`

**Comment by whimboo** [comment]
You are moving the installation files to `/opt/firefox`, but then creating a symlink to `/opt/firefox57/firefox`. So not sure which firefox version is really picked up. Basically you should not replace a system installation of Firefox. You can basically untar the bz2 file whereever you want, and just use that path to run Firefox. Just mark the binary in the Firefox options inside of the capabilities.

**Comment by hqbrice** [comment]
The same when I specify firefox binaries (folder after extract tar.bz2) : 
`11:00:21.319 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@46e6f0d0
11:00:21.321 INFO - /session: Executing POST on /session (handler: BeginSession)
11:00:21.326 INFO - Capabilities are: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_binary: /tmp/firefox/firefox-bin, moz:firefoxOptions: {args: [], binary: /tmp/firefox/firefox-bin, log: {level: trace}, prefs: {}}, version: POSTGRES.CENTOS_1}
11:00:21.326 INFO - Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_binary: /tmp/firefox/firefox-bin, moz:firefoxOptions: {args: [], binary: /tmp/firefox/firefox-bin, log: {level: trace}, prefs: {}}, version: POSTGRES.CENTOS_1} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1512554421390   geckodriver     INFO    geckodriver 0.19.1
1512554421394   geckodriver     INFO    Listening on 127.0.0.1:4851
1512554421545   mozrunner::runner       INFO    Running command: "/tmp/firefox/firefox-bin" "-marionette" "-profile" "/tmp/rust_mozprofile.uYL6NacM22Sl"
1512554421556   geckodriver::marionette TRACE     connection attempt 0/600
1512554421658   geckodriver::marionette TRACE     connection attempt 1/600
1512554421758   geckodriver::marionette TRACE     connection attempt 2/600
ExceptionHandler::GenerateDump cloned child 9114
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1512554421859   geckodriver::marionette TRACE     connection attempt 3/600
1512554421960   geckodriver::marionette TRACE     connection attempt 4/600
1512554422060   geckodriver::marionette TRACE     connection attempt 5/600
1512554422161   geckodriver::marionette TRACE     connection attempt 6/600
1512554422261   geckodriver::marionette TRACE     connection attempt 7/600
1512554422371   geckodriver::marionette TRACE     connection attempt 8/600
1512554422473   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status: {unknown}","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43\n   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684\n   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
`

**Comment by hqbrice** [comment]
If I use FF in headless mode, not reproduce

**Comment by andreastt** [comment]
OK, is the problem here that you don’t have an X display running?

**Comment by hqbrice** [comment]
When I start Selenium jar in webdriver role, I start too Xvfb like this : 
`export DISPLAY=:99

Xvfb :99 -ac &`

**Comment by whimboo** [comment]
Hm, the output still doesn't look like that it comes from a debug build. Here I have a more recent one from today:

https://queue.taskcluster.net/v1/task/ICN9snuTSU2sIBEXaKOiqA/runs/0/artifacts/public/build/target.tar.bz2

Please make sure that the trace log is definitely enabled. Thanks.

**Comment by jlawrynowicz** [comment]
I just had the very same problem on centos 7 + selenium 3.8.1 + geckodriver v0.19.1 + firefox 58.0 setup in docker container.

The solution was to alter the way Xvfb was launched (add `-ac -screen 0 resolution`), e.g.

`/usr/bin/Xvfb :99 +extension  RANDR -nolisten tcp -fbdir /var/run -ac -screen 0 1366x768x24`

**Comment by grem11n** [comment]
I ran into similar issue on MacOS with Selenium Grid in Docker

Docker images: `selenium/hub:3.8.1-francium` and `selenium/node-firefox:3.8.1-francium`

Inside the container with Firefox I have

```
Xvfb :99 -screen 0 1360x1020x24 -ac +extension RANDR -nolisten tcp -auth /tmp/xvfb-run.IqyTYV/Xauthority
```
and 
```java -jar /opt/selenium/selenium-server-standalone.jar -role node -hub http://hub:4444/grid/register -nodeConfig /opt/selenium/config.json```

Here is a trace I'm getting while running tests:

```
org.openqa.selenium.WebDriverException:
Process unexpectedly closed with status: {unknown}
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'f8e4c178738f', ip: '172.21.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.75-linuxkit-aufs', java.version: '1.8.0_151'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43
   3:           0x4487ce - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
Command duration or timeout: 713 milliseconds
```

I run maven inside a container as well.
