### ISSUE TITLE
Firefox Headless Python Windows Scheduled Task error

### ISSUE THREAD

**Issue by iHaagcom** [mozilla/geckodriver#1089]
## System
* Version: 0.19.1
* Platform: Windows 10 1607
* Firefox: 58.0b8 (64bit)
* Selenium:3.7

## Testcase

import subprocess
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.firefox.options import Options
#from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
import requests
from seleniumrequests import Firefox
import json
import subprocess
import urllib.parse
import urllib.request
import os
baseurl = "https://www.gmail.com"
username = "username"
password = "password"
xpaths = { 'usernameTxtBox' : "//input[@name='username']",
           'passwordTxtBox' : "//input[@name='password']",
           'submitButton' :   "//input[@name='login']"
}
#binary = FirefoxBinary('C:\Downloads\FirefoxPortable\FirefoxPortable.exe')
os.environ['MOZ_HEADLESS'] = '1'
#options = Options()
#options.addPreferences("security.sandbox.content.level",5)
mydriver = Firefox() #only required if not in PATH 
mydriver.maximize_window()
mydriver.get(baseurl)
#Clear Username TextBox if already allowed "Remember Me" 
mydriver.find_element_by_xpath(xpaths['usernameTxtBox']).clear()
#Write Username in Username TextBox
mydriver.find_element_by_xpath(xpaths['usernameTxtBox']).send_keys(username)
#Clear Password TextBox if already allowed "Remember Me" 
mydriver.find_element_by_xpath(xpaths['passwordTxtBox']).clear()
#Write Password in password TextBox
mydriver.find_element_by_xpath(xpaths['passwordTxtBox']).send_keys(password)
#Click Login button
mydriver.find_element_by_xpath(xpaths['submitButton']).click()

## Stacktrace

1512451727819 geckodriver INFO geckodriver 0.19.1
1512451727834 geckodriver INFO Listening on 127.0.0.1:51683
1512451729870 mozrunner::runner INFO Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofile.GJXpjkkEWPpk"
*** You are running in headless mode.
1512451730430 Marionette INFO Enabled via --marionette
###!!! [Parent][MessageChannel] Error: (msgtype=0x150090,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0040,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150081,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0040,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0040,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C00FE,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150001,name=PBrowser::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2C001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150090,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
Unable to read VR Path Registry from C:\Users\Administrator\AppData\Local\openvr\openvrpaths.vrpath
JavaScript error: resource://shield-recipe-client/lib/ShieldRecipeClient.jsm, line 70: TypeError: log is undefined
###!!! [Parent][MessageChannel] Error: (msgtype=0x150090,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

## Trace-level log

 {"moz:firefoxOptions": {"log": {"level": "trace"}}} as a capability.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment]
@iHaagcom you are facing a crash of a tab here, and as such Firefox gets closed. Did you only try with Firefox 58.0b8, or does the same also happen with Firefox 57? Does changing the sandbox help?

If you can get Selenium to not delete the temporary profile, and check for minidump files inside the `minidump` subfolder that would be great. I would appreciate if you could attach those to this issue, or send them via email.

@andreastt a trace log will not help here given that this is a startup crash in Firefox.

**Comment by iHaagcom** [comment]
Hi whimboo,
The crash happened on version 57 before I tried the beta version. The sandbox option wouldn't work, it would give a AttributeError: 'Options' object has no attribute 'addpreferences', that is with from selenium.webdriver.firefox.options import Options imported. Im fairly new to python, any tricks to get Selenium to not delete the temp file?

**Comment by whimboo** [comment]
Alternatively to the Options object (which I haven't worked with yet) you could use the following:
```
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["moz:firefoxOptions"] = {
            "prefs": {
                "security.sandbox.content.level": 4,
            }
        }
        self.driver = webdriver.Firefox(capabilities=capabilities)
```

To not let Selenium delete the profile immediately you might have to add a `sys.exit()` right after the instantiation of the driver, which you encapsulate in try/except.  But seeing issue #299 the profile must still be around. Just find the line `mozrunner::runner INFO Running command` in the log, which has the path of the profile listed.

**Comment by iHaagcom** [comment]
Am i to define  capabilities?? = DesiredCapabilities.FIREFOX.copy()
I get NameError: name 'DesiredCapabilities' is not defined?

**Comment by iHaagcom** [comment]
ahh right, include: from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

**Comment by iHaagcom** [comment]
Still no luck, also it didn't like sys.exit()

**Comment by iHaagcom** [comment]
I changed the security level to 5, and the last thing in the log is:
1512557228768  addons.productaddons INFO downloadXHR File download. status=200
1512557228768  addons.productaddons INFO Downloaded file will be saved to C:\Users\ADMINI\Appdata\Local\Temp\tmpaddon-806469

**Comment by whimboo** [comment]
@iHaagcom if you still have the chance to get me a minidump file as requested earlier that would be very helpful. Otherwise you would see this problem again in one of the next releases of Firefox, in the case it's an unknown problem. I would really like to make sure that we can fix this crash. Thanks!

Given that this is not a geckodriver issue I will close it now, but we can continue to figure out the remaining parts. Thanks.
