### ISSUE TITLE
Click/Subject is not working 

### ISSUE THREAD

**Issue by AutomationObject** [mozilla/geckodriver#1092]
## Mac MacBook Pro
* Version: v0.19.1
* Platform :  macOS 
* Firefox: 57.0.1 (32-bit)
* Selenium: selenium standalone server 3.8.1

## Testcase

* I am using the slenide lib steward for selenium test.
I have the issue when testing with firefox when submitting a form (via a click or via a submit) firefox does not load the redirected page. The event was firing but it seems like the request have been canceled and the next command failed because the html element is missing, due to not changing the webpage.
I tried implicid and explicid wait but that do not work.
It is working fine when i run the script in chrome.

* Same case happening with filters over UI.

Is this an issue or am I doing something wrong. Is there a way to workaound?
In chrome it works.

**Comment by whimboo** [comment]
@AutomationObject you are not providing neither a testcase nor a trace level log. Both have been requested when filing a new issue. Without we cannot do anything. 

Please note that if the submit button delays the form submission you might hit issue #1026.

I'm happy to reopen if trace logs verify that this is not the same issue.
