### ISSUE TITLE
GeckoDriver fails to start FireFox-57.0.2 when Windows Screen is Locked

### ISSUE THREAD

**Issue by ChrisSwan** [mozilla/geckodriver#1100]
## System
* Windows 10
* Selenium 3.8.0
* Firefox 57.0.2 (64 bit)
* geckodriver 0.19.1 win64

## Testcase

I have boiled this down to a C# app that simply starts up the FirefoxDriver, and I add it to a scheduled task. If my Windows machine is locked or (my main use case) I've switched to another user, then the Driver crashes on startup.
Through adding debug logs I can see that an exception is thrown, but error.message is empty.

This appears to be a reopening of Issue [#972](https://github.com/mozilla/geckodriver/issues/972)

**Comment by cgoldberg** [comment]
> If my Windows machine is locked or (my main use case) 
> I've switched to another user, 
> then the Driver crashes on startup.

What is the expected behavior when running with screen locked?  AFAIK, this disables mouse and keyboard events and you won't get very far with your automation.

**Comment by ChrisSwan** [comment]
I already a number of Selenium tests using the ChromeDriver while not logged in, and they all work fine. Currently though I can't automate any Firefox Selenium tests due to this issue. I'm assuming if it works in Chrome it should be fine in Firefox too?

**Comment by tttower** [comment]
Historically Chrome & FF automation via Selenium was transparent to Screen status. 
IE always required Unlocked screen.

**Comment by andreastt** [comment]
I believe Gecko has a closer-to-reality input emulation which could explain why events are not sent when the screen is locked, for the same reasons @cgoldberg gave.

I would suggest running with the screen unlocked for the moment. If you do care deeply about this issue I would suggest filing an issue against Firefox.

**Comment by ChrisSwan** [comment]
Ok, since this is being closed as expected behaviour I'll remove Firefox from my automated tests. Thank you for letting me know.

**Comment by whimboo** [comment]
@ChrisSwan I fail to understand your reported issue. What exactly is not working? Does Firefox not start, or does geckodriver fail in some way? Please attach trace level logs for further details: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
