### ISSUE TITLE
The import org.openqa cannot be resolved why??

### ISSUE THREAD

**Issue by geetagunjan** [mozilla/geckodriver#1106]
unresolved error for openqa.selenium

import org.**openqa.selenium**.firefox.FirefoxDriver;

public class selenium1 {

	public static void main(String[] args) {
		FirefoxDriver d1= new FirefoxDriver();

	}

The above code does not work even when gecko driver is used becasue The import org.openqa cannot be resolved. I dont understand wht I am missing?

## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by whimboo** [comment]
This is an issue with your Selenium binding but not with geckodriver.

**Comment by geetagunjan** [comment]
Thanks but do you have any pointers how I could solve this.

Thanks
G

**Comment by whimboo** [comment]
Sorry, I don't have that. Try to find support on IRC or a support forum for Selenium.
