### ISSUE TITLE
Open the Firefox browser，firefox_options How to set the parameters

### ISSUE THREAD

**Issue by namexiaohuihui** [mozilla/geckodriver#1109]
webdriver.Firefox(executable_path=firefoxgeckobdriver) 
You can run the browser，

I want to run the Firefox in the following way
webdriver.Firefox(executable_path=firefoxgeckobdriver,firefox_options=options) ..

But I don't understand how to set up ---->options。。

Do you have a way of learning?

    Version: 0.19.1
    Platform: Windows 10
    Firefox: Nighly 57.0.1 (64-bit)
    Selenium: python 3.8.0
    python:3.6.4

**Comment by andreastt** [comment]
This is a question for the maintainer of the client you’re using. This tracks issues with geckodriver itself.

**Comment by namexiaohuihui** [comment]
Thank you

It's been done.
