### ISSUE TITLE
Can not open Pages using a proxy

### ISSUE THREAD

**Issue by gouzal-pi** [mozilla/geckodriver#1110]
## System
* Version: 18
* Platform: Windows 64 bit SP1
* Firefox: 57.0.2 (64-bit)
* Selenium: 3.6.0
* JDK : 1.8

## Testcase

```
public class Main {

    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "D:\\geckodriver\\18\\geckodriver.exe");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("proxy", getProxyJson("185.59.136.33", 1235));
        FirefoxOptions firefoxOptions=new FirefoxOptions(capabilities);
        firefoxOptions.setLogLevel(Level.ALL);
        WebDriver driver = new FirefoxDriver(firefoxOptions);
        driver.get("http://google.com");
    }

    private static JsonObject getProxyJson(String proxy, int port) {
        com.google.gson.JsonObject json = new com.google.gson.JsonObject();
        json.addProperty("proxyType", "manual");
        json.addProperty("httpProxy", proxy);
        json.addProperty("httpProxyPort", port);
        json.addProperty("sslProxy", proxy);
        json.addProperty("sslProxyPort", port);

        return json;
    }

}

```

## Expected behavior
google.com page to be opened with the given proxy

## Actual behavior
![timedout](https://user-images.githubusercontent.com/28804247/34306482-3f20d83e-e73b-11e7-9ae5-c662d0d266d2.PNG)

## Notes:

- By removing DesiredCapabilities the page can be load without any problem.
- I tested it with different proxies
- The issue can be related the last firefox's update (Quantum) ( 57 ), because  It was working before.

## Stacktrace

1513962416095	geckodriver	INFO	geckodriver 0.18.0
1513962416101	geckodriver	INFO	Listening on 127.0.0.1:48503
1513962416757	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1513962417463	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\EL Arbi\AppData\Local\openvr\openvrpaths.vrpath
[Parent 13832, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1513962432773	Marionette	INFO	Listening on port 49520
Unable to read VR Path Registry from C:\Users\EL Arbi\AppData\Local\openvr\openvrpaths.vrpath
[Child 7912, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 7912, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1513962432986	Marionette	INFO	Proxy settings initialised: {"proxyType":"manual","httpProxy":"185.59.136.33:80","sslProxy":"185.59.136.33:443"}
1513962433048	Marionette	DEBUG	Register listener.js for window 4294967297
déc. 22, 2017 5:07:13 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C
1513962433139	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1513962433400	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1513962433400	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1513962433406	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "http://google.com/"
1513962433408	Marionette	DEBUG	Received DOM event "pageshow" for "http://google.com/"
BUILD SUCCESSFUL (total time: 18 seconds)

## Trace-level log

1513961918160	geckodriver	INFO	geckodriver 0.18.0
1513961918166	geckodriver	INFO	Listening on 127.0.0.1:8488
1513961918831	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1513961919298	Marionette	DEBUG	Received observer notification "profile-after-change"
1513961919510	Marionette	DEBUG	Received observer notification "command-line-startup"
1513961919510	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\EL Arbi\AppData\Local\openvr\openvrpaths.vrpath
[Child 15580, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 15580, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1513961920928	geckodriver::marionette	TRACE	  connection attempt 0/600
1513961920999	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1513961921853	Marionette	DEBUG	Setting recommended pref browser.safebrowsing.passwords.enabled to false
1513961921853	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1513961921853	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1513961921854	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1513961921854	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1513961921855	Marionette	DEBUG	New connections are accepted
1513961921855	Marionette	INFO	Listening on port 49341
1513961922033	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:49341
1513961922040	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:49360
1513961922041	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1513961922042	geckodriver::marionette	TRACE	-> 315:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{"proxy":{"httpProxy":"185.59.136.33","httpProxyPort":1235,"proxyType":"manual","sslProxy":"185.59.136.33","sslProxyPort":1235}}},"proxy":{"httpProxy":"185.59.136.33","httpProxyPort":1235,"proxyType":"manual","sslProxy":"185.59.136.33","sslProxyPort":1235}}]
1513961922046	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"proxy":{"httpProxy":"185.59.136.33","httpProxyPort":1235,"proxyType":"manual","sslProxy":"185.59.136.33","sslProxyPort":1235}}},"proxy":{"httpProxy":"185.59.136.33","httpProxyPort":1235,"proxyType":"manual","sslProxy":"185.59.136.33","sslProxyPort":1235}}]
1513961922049	Marionette	INFO	Proxy settings initialised: {"proxyType":"manual","httpProxy":"185.59.136.33:80","sslProxy":"185.59.136.33:443"}
1513961922129	Marionette	DEBUG	Register listener.js for window 4294967297
1513961922151	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"e36db503-08ca-4848-a2c9-e7b736cf42e4","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"proxy":{"proxyType":"manual","httpProxy":"185.59.136.33:80","sslProxy":"185.59.136.33:443"},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":15680,"moz:profile":"C:\\Users\\EL Arbi\\AppData\\Local\\Temp\\rust_mozprofile.jqgHuATUDA8B","moz:webdriverClick":false}}]
1513961922151	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"e36db503-08ca-4848-a2c9-e7b736cf42e4","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"proxy":{"proxyType":"manual","httpProxy":"185.59.136.33:80","sslProxy":"185.59.136.33:443"},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":15680,"moz:profile":"C:\\Users\\EL Arbi\\AppData\\Local\\Temp\\rust_mozprofile.jqgHuATUDA8B","moz:webdriverClick":false}}]
1513961922152	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"e36db503-08ca-4848-a2c9-e7b736cf42e4","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"57.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":15680,"moz:profile":"C:\\Users\\EL Arbi\\AppData\\Local\\Temp\\rust_mozprofile.jqgHuATUDA8B","moz:webdriverClick":false,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","proxy":{"httpProxy":"185.59.136.33:80","proxyType":"manual","sslProxy":"185.59.136.33:443"},"rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
déc. 22, 2017 4:58:42 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C
1513961922240	webdriver::server	DEBUG	-> POST /session/e36db503-08ca-4848-a2c9-e7b736cf42e4/url {"url":"http://google.com"}
1513961922241	geckodriver::marionette	TRACE	-> 39:[0,2,"get",{"url":"http://google.com"}]
1513961922243	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://google.com"}]
1513961922262	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1513961943273	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1513961943274	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1513961943274	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1513961943308	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "about:neterror?e=netTimeout&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20server%20at%20google.com%20is%20taking%20too%20long%20to%20respond."
1513961943318	Marionette	TRACE	0 <- [1,2,{"error":"unknown error","message":"Reached error page: about:neterror?e=netTimeout&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20server%20at%20google.com%20is%20taking%20too%20long%20to%20respond.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:235:5\nUnknownError@chrome://marionette/content/error.js:533:5\nhandleReadyState@chrome://marionette/content/listener.js:317:21\nhandleEvent@chrome://marionette/content/listener.js:285:9\n"},null]
1513961943319	geckodriver::marionette	TRACE	<- [1,2,{"error":"unknown error","message":"Reached error page: about:neterror?e=netTimeout&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20server%20at%20google.com%20is%20taking%20too%20long%20to%20respond.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:235:5\nUnknownError@chrome://marionette/content/error.js:533:5\nhandleReadyState@chrome://marionette/content/listener.js:317:21\nhandleEvent@chrome://marionette/content/listener.js:285:9\n"},null]
1513961943322	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Reached error page: about:neterror?e=netTimeout&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20server%20at%20google.com%20is%20taking%20too%20long%20to%20respond.","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x44ce14 - <no info>\n   4:           0x44944a - <no info>\n   5:           0x4203e1 - <no info>\n   6:           0x407dc7 - <no info>\n   7:           0x6d95b9 - <no info>\n   8:           0x4173a7 - <no info>\n   9:           0x6d38b3 - <no info>\n  10:         0x76b159cd - BaseThreadInitThunk"}}
Exception in thread "main" org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=netTimeout&u=http%3A//google.com/&c=UTF-8&f=regular&d=The%20server%20at%20google.com%20is%20taking%20too%20long%20to%20respond.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: '160-AGOUZAL', ip: '192.168.1.160', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\EL Arbi\AppData\Local\Temp\rust_mozprofile.jqgHuATUDA8B, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, proxy=Proxy(manual, http=185.59.136.33:80, ssl=185.59.136.33:443), moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0.2, platformVersion=6.1, moz:processID=15680, browserName=firefox, javascriptEnabled=true, platformName=XP, moz:webdriverClick=false}]
Session ID: e36db503-08ca-4848-a2c9-e7b736cf42e4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at com.pim.ui.Main.main(Main.java:31)
C:\Users\EL Arbi\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 26 seconds)

**Comment by whimboo** [comment]
Both the host and port have to be specified via the `httpProxy` and equivalent keys. They are no longer handled separately. See our documentation at https://github.com/mozilla/geckodriver#proxy-object

**Comment by gouzal-pi** [comment]
Hi @whimboo ,  I change the code as you suggested,:

```
public class Main {

    public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "C:\\Users\\Larbi\\Desktop\\geckodriver.exe");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("proxy", getProxyJson("70.169.70.88", 80));
        FirefoxOptions firefoxOptions = new FirefoxOptions(capabilities);
        firefoxOptions.setLogLevel(Level.ALL);
        WebDriver driver = new FirefoxDriver(firefoxOptions);
        driver.get("http://google.com");
    }

    private static JsonObject getProxyJson(String proxy, int port) {
        com.google.gson.JsonObject json = new com.google.gson.JsonObject();
        json.addProperty("proxyType", "manual");
        json.addProperty("httpProxy", proxy+":"+port);
        json.addProperty("sslProxy", proxy+":"+port);

        return json;
    }
}
```
But did I miss something, because i get the following error:
![e](https://user-images.githubusercontent.com/28804247/34329146-fba50fbe-e8eb-11e7-87e6-ce693dd07190.PNG)

Here is the stackTrace:

1514147365382	geckodriver	INFO	geckodriver 0.19.1
1514147365390	geckodriver	INFO	Listening on 127.0.0.1:38840
1514147366091	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Larbi\\AppData\\Local\\Temp\\rust_mozprofile.Zhm7I7KUV7Eh"
1514147366716	Marionette	DEBUG	Received observer notification "profile-after-change"
1514147366816	Marionette	DEBUG	Received observer notification "command-line-startup"
1514147366816	Marionette	INFO	Enabled via --marionette
1514147368098	geckodriver::marionette	TRACE	  connection attempt 0/600
Unable to read VR Path Registry from C:\Users\Larbi\AppData\Local\openvr\openvrpaths.vrpath
[Parent 10176, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\Larbi\AppData\Local\openvr\openvrpaths.vrpath
[Child 12180, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1514147368595	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1514147368961	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1514147368962	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1514147368962	Marionette	DEBUG	Setting recommended pref extensions.e10sBlocksEnabling to false
1514147368963	Marionette	DEBUG	New connections are accepted
1514147368963	Marionette	INFO	Listening on port 58156
1514147369206	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:58156
1514147369211	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:58171
1514147369215	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1514147369215	geckodriver::marionette	TRACE	-> 241:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{"proxy":{"httpProxy":"70.169.70.88:80","proxyType":"manual","sslProxy":"70.169.70.88:80"}}},"proxy":{"httpProxy":"70.169.70.88:80","proxyType":"manual","sslProxy":"70.169.70.88:80"}}]
1514147369226	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"proxy":{"httpProxy":"70.169.70.88:80","proxyType":"manual","sslProxy":"70.169.70.88:80"}}},"proxy":{"httpProxy":"70.169.70.88:80","proxyType":"manual","sslProxy":"70.169.70.88:80"}}]
1514147369229	Marionette	INFO	Proxy settings initialised: {"proxyType":"manual","httpProxy":"70.169.70.88:80","sslProxy":"70.169.70.88:80"}
1514147369303	Marionette	DEBUG	Register listener.js for window 4294967297
1514147369322	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"43137dac-debd-45be-9e51-466eead672ca","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"proxy":{"proxyType":"manual","httpProxy":"70.169.70.88:80","sslProxy":"70.169.70.88:80"},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":10176,"moz:profile":"C:\\Users\\Larbi\\AppData\\Local\\Temp\\rust_mozprofile.Zhm7I7KUV7Eh","moz:webdriverClick":false}}]
1514147369324	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"43137dac-debd-45be-9e51-466eead672ca","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"proxy":{"proxyType":"manual","httpProxy":"70.169.70.88:80","sslProxy":"70.169.70.88:80"},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":10176,"moz:profile":"C:\\Users\\Larbi\\AppData\\Local\\Temp\\rust_mozprofile.Zhm7I7KUV7Eh","moz:webdriverClick":false}}]
1514147369324	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"43137dac-debd-45be-9e51-466eead672ca","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"57.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":10176,"moz:profile":"C:\\Users\\Larbi\\AppData\\Local\\Temp\\rust_mozprofile.Zhm7I7KUV7Eh","moz:webdriverClick":false,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","proxy":{"httpProxy":"70.169.70.88:80","proxyType":"manual","sslProxy":"70.169.70.88:80"},"rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
déc. 24, 2017 8:29:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C
1514147369400	webdriver::server	DEBUG	-> POST /session/43137dac-debd-45be-9e51-466eead672ca/url {"url":"http://google.com"}
1514147369400	geckodriver::marionette	TRACE	-> 39:[0,2,"get",{"url":"http://google.com"}]
1514147369404	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://google.com"}]
1514147369406	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1514147403634	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1514147403637	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1514147403637	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1514147403675	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "about:neterror?e=nssFailure2&u=https%3A//www.google.com/%3Fgws_rd%3Dssl&c=UTF-8&f=regular&d=La%20connexion%20avec%20le%20serveur%20a%20%C3%A9t%C3%A9%20r%C3%A9initialis%C3%A9e%20pendant%20le%20chargement%20de%20la%20page."
1514147403679	Marionette	TRACE	0 <- [1,2,{"error":"unknown error","message":"Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.google.com/%3Fgws_rd%3Dssl&c=UTF-8&f=regular&d=La%20connexion%20avec%20le%20serveur%20a%20%C3%A9t%C3%A9%20r%C3%A9initialis%C3%A9e%20pendant%20le%20chargement%20de%20la%20page.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:235:5\nUnknownError@chrome://marionette/content/error.js:533:5\nhandleReadyState@chrome://marionette/content/listener.js:317:21\nhandleEvent@chrome://marionette/content/listener.js:285:9\n"},null]
1514147403677	geckodriver::marionette	TRACE	<- [1,2,{"error":"unknown error","message":"Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.google.com/%3Fgws_rd%3Dssl&c=UTF-8&f=regular&d=La%20connexion%20avec%20le%20serveur%20a%20%C3%A9t%C3%A9%20r%C3%A9initialis%C3%A9e%20pendant%20le%20chargement%20de%20la%20page.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:235:5\nUnknownError@chrome://marionette/content/error.js:533:5\nhandleReadyState@chrome://marionette/content/listener.js:317:21\nhandleEvent@chrome://marionette/content/listener.js:285:9\n"},null]
1514147403685	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.google.com/%3Fgws_rd%3Dssl&c=UTF-8&f=regular&d=La%20connexion%20avec%20le%20serveur%20a%20%C3%A9t%C3%A9%20r%C3%A9initialis%C3%A9e%20pendant%20le%20chargement%20de%20la%20page.","stacktrace":"WebDriverError@chrome://marionette/content/error.js:235:5\nUnknownError@chrome://marionette/content/error.js:533:5\nhandleReadyState@chrome://marionette/content/listener.js:317:21\nhandleEvent@chrome://marionette/content/listener.js:285:9\n"}}
Exception in thread "main" org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.google.com/%3Fgws_rd%3Dssl&c=UTF-8&f=regular&d=La%20connexion%20avec%20le%20serveur%20a%20%C3%A9t%C3%A9%20r%C3%A9initialis%C3%A9e%20pendant%20le%20chargement%20de%20la%20page.
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'LARBI-PC', ip: '192.168.1.12', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Larbi\AppData\Local\Temp\rust_mozprofile.Zhm7I7KUV7Eh, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, proxy=Proxy(manual, http=70.169.70.88:80, ssl=70.169.70.88:80), moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0.2, platformVersion=6.1, moz:processID=10176, browserName=firefox, javascriptEnabled=true, platformName=XP, moz:webdriverClick=false}]
Session ID: 43137dac-debd-45be-9e51-466eead672ca
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:310)
	at geckodriver3.GeckoDriver3.main(GeckoDriver3.java:29)
C:\Users\Larbi\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 39 seconds)

# Note:
This time,I am using :
GeckoDriver: v19.1
Selenium: 3.8.1
Firefox: 57.0.2 (64bit)

**Comment by schmidtkp** [comment]
@gouzal-pi Change your code to return a Proxy object, and set it using FirefoxOptions.setProxy(proxy)
