### ISSUE TITLE
[Parent][MessageChannel] Channel error: cannot send/recv

### ISSUE THREAD

**Issue by HardikModha** [mozilla/geckodriver#1111]
## System
* Version: [0.19.1](https://github.com/SeleniumHQ/docker-selenium/blob/3.8.1-bohrium/NodeFirefox/Dockerfile#L28)
* Platform: [Base image ubuntu:16.04](https://github.com/SeleniumHQ/docker-selenium/blob/3.8.1-bohrium/Base/Dockerfile#L1)
* Firefox: [57.0.2](https://github.com/SeleniumHQ/docker-selenium/blob/3.8.1-bohrium/NodeFirefox/Dockerfile#L13)
* Selenium: 3.8.1

## Stacktrace
```
###!!! [Parent][MessageChannel] Error: (msgtype=0x150083,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

1513687154976	Marionette	DEBUG	Register listener.js for window 17
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1513687155411	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.1
1513687155412	addons.xpi	DEBUG	Calling bootstrap method shutdown on shield-recipe-client@mozilla.org version 76.1
1513687155413	addons.xpi	DEBUG	Calling bootstrap method shutdown on screenshots@mozilla.org version 19.2.0
1513687155459	addons.xpi	DEBUG	Calling bootstrap method shutdown on onboarding@mozilla.org version 1.0
1513687155460	addons.xpi	DEBUG	Calling bootstrap method shutdown on formautofill@mozilla.org version 1.0
1513687155461	addons.xpi	DEBUG	Calling bootstrap method shutdown on followonsearch@mozilla.com version 0.9.6
1513687155461	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1513687155462	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 3.05
1513687155462	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 2.0
1513687155463	addons.xpi	DEBUG	Calling bootstrap method shutdown on activity-stream@mozilla.org version 2017.11.07.1100-7f4e3634
1513687156167	Marionette	DEBUG	Received DOM event unload for [object XULDocument]
1513687156179	Marionette	TRACE	0 <- [1,51905,null,{}]
1513687156197	geckodriver::marionette	TRACE	<- [1,51905,null,{}]
1513687156266	Marionette	DEBUG	Closed connection 0
1513687156377	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to find value field","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032\n   3:           0x44a7e0 - geckodriver::marionette::MarionetteSession::response::ha4a2fbbdd9abe262\n   4:           0x429f1a - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
1513687156458	addons.manager	DEBUG	shutdown
1513687156459	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1513687156459	addons.xpi	DEBUG	shutdown
1513687156459	addons.xpi-utils	DEBUG	shutdown
```

## Trace-level log
[See this gist](https://gist.github.com/HardikModha/7363b121fea2507dd38ee1c3f0d2d15b)

I am using the [standalone-firefox](https://github.com/SeleniumHQ/docker-selenium/tree/3.8.1-bohrium/StandaloneFirefox) image to run the Firefox. My application connects to this Firefox using the `RemoteWebDriver`. I have all the setup running inside a Kubernetes cluster. 

**Use case:**
I have (thousands of) URLs that I need to visit. When I visit these URLs one after the other continuously, Firefox crashes and I get the error log as mentioned. Further invocations to create a new Firefox driver instance results in an error (`Failed to decode response from Marionette`) until I manually kill and restart the Firefox. 

Official docs on [docker-selenium](https://github.com/SeleniumHQ/docker-selenium#running-the-images) advices to use the shared memory around `2GB` to successfully run it inside the docker container. But Kubernetes does not support the shared memory [#28272](https://github.com/kubernetes/kubernetes/issues/28272). So I have implemented a workaround as mentioned in the [openshift](https://docs.openshift.org/latest/dev_guide/shared_memory.html) docs. I have assigned 4 GB RAM to the Firefox pod and still, it crashes after visiting ~430 of URLs. 

I would appreciate any feedback.

**Update:**

I tried to disable the multiprocessor support in the hope that it would consume less memory and save Firefox from getting crashed but it, too, didn't work. 🤔  It's still getting crashed.

```
FirefoxProfile firefoxProfile = new FirefoxProfile();

firefoxProfile.setPreference("browser.tabs.remote.autostart", false)
firefoxProfile.setPreference("browser.tabs.remote.autostart.1", false)
firefoxProfile.setPreference("browser.tabs.remote.autostart.2", false)

FirefoxOptions firefoxOptions = new FirefoxOptions()
firefoxOptions.setHeadless(true).setProfile(firefoxProfile)

webDriver = new RemoteWebDriver(new URL(firefoxHost), DesiredCapabilities.firefox().merge(firefoxOptions))
```

**Comment by HardikModha** [comment]
No responses?

**Comment by whimboo** [comment]
The problem here is that one of the loaded URLs crashed the content process. Sadly your attached trace log doesn't contain information about which page got loaded. So please check that again, if it is always crashing on the same URL, of if that differs. This looks more like a problem in Firefox.

**Comment by HardikModha** [comment]
@whimboo Thanks for the response. No, it does not crash at the same URL every time. Before disabling the multi-processor support, It was able to visit ~180-200 URLs. Once I disabled the multi-processor support it was able to visit up to ~430 URLs. So I think the later has somewhat improved compared to the first one. Apart from this, Can you please explain which kind of URLs may cause Firefox content process to crash? I can also provide more detailed logs if needed. But it will take some time. I'll have to re-run the application.

**Comment by whimboo** [comment]
There can be various reasons why Firefox crashes. I would clearly need a crash report for that which is normally saved to the profile in use, and there inside the sub folder "minidumps". Right now we do not have anything in geckodriver which can analyze those files. What you could do is to add some extra lines of code in teardown of your test class which copies anything from inside this folder to a different location. This is needed because Selenium will remove your profile at the end.

When testing that please enable multiple-content processes because this is default now, and on the other end will give results earlier.  Which binding are you actually using?

**Comment by HardikModha** [comment]
I'm using bindings for Java and using `[Geb](https://github.com/geb/geb)` for the automation.

Is there any configuration option for Firefox that I can set to store `miniDump` in the different location. I Googled but only found a reference for chrome. We can pass `chromeOptions.minidumpPath` as mentioned in the [chrome capabilitties](https://sites.google.com/a/chromium.org/chromedriver/capabilities). But couldn't find for Firefox.

**Comment by whimboo** [comment]
No, we don't have support for minidump handling at the moment. For now you would have to copy those files on your own in the test, or instruct Selenium or Geb somehow to keep the profile afterward.

Otherwise a custom profile will also work, but some quirks would have to be applied to that at the moment. See https://github.com/mozilla/geckodriver/issues/1058#issuecomment-347830930 and following comments.

Sorry for not having something better at the moment.

**Comment by HardikModha** [comment]
Thanks for the alternative. I'll try the suggestions and get back to you by this weekend.

**Comment by HardikModha** [comment]
@whimboo I tried the latest nightly build version as suggested by you in [this comment](https://github.com/mozilla/geckodriver/issues/1125#issuecomment-356926571). That error is gone and now Firefox is able to visit all the URLs.

**Comment by whimboo** [comment]
@HardikModha would you mind also testing the latest 58 beta build? I would be interest if that works for you or not. You might not see the same as what has been reported on #1125.

**Comment by HardikModha** [comment]
Sure. I'll test it and will let you know the results. Just confirming, You are talking about this build right? https://www.mozilla.org/en-US/firefox/58.0beta/releasenotes/

**Comment by HardikModha** [comment]
@whimboo You mean latest 58beta build. RIght? https://www.mozilla.org/en-US/firefox/58.0beta/releasenotes/

**Comment by whimboo** [comment]
Firefox Beta is on 59 now. You can download it always from the following location:
https://treeherder.mozilla.org/logviewer.html#?job_id=1859037&repo=mozilla-beta#L1047

**Comment by Madhusudan-Devaraju** [comment]
Me too getting the same error. OS: Win10.
PFA log.
[log.txt](https://github.com/mozilla/geckodriver/files/2065186/log.txt)

**Comment by whimboo** [comment]
@Madhusudan-Devaraju please do not comment on already closed issues. Please file a new one if you can see something similar when using the most recent versions of Selenium, geckodriver, and Marionette.
