### ISSUE TITLE
Keys.chord(...) cannot work with geckodriver0.19.1 + Selenium 3.7.1 and Firefox 57.0.2 (64 bit)

### ISSUE THREAD

**Issue by duanzih** [mozilla/geckodriver#1112]
## System
* Version: 0.19.1
* Platform: Windows server 2008 R2
* Firefox: 57.0.2 (64 bit)
* Selenium: 3.7.1

  public static void main(String[] args) {
        File firefoxExecutable = new File("C:\\Program Files\\Mozilla Firefox\\firefox.exe");

        System.setProperty("webdriver.firefox.bin", firefoxExecutable.getAbsolutePath());

        System.setProperty("webdriver.gecko.driver", "E:\\gecko0.19.1\\win64\\geckodriver.exe");

        FirefoxOptions options = new FirefoxOptions();
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);
        WebDriver driver = new FirefoxDriver(options);

        driver.get("http://www.google.com");
        WebElement ele = driver.findElement(By.id("lga"));
        ele.click();
        Keys.chord(Keys.CONTROL, "a");
        System.out.println("============ test1 ====");
    }

After this section of code is executed, all elements on the web page should be selected. However, nothing happened when Keys.chord(Keys.CONTROL, "a"); is executed.

## Trace-level log
1514272419680	geckodriver	INFO	geckodriver 0.19.1
1514272419695	geckodriver	INFO	Listening on 127.0.0.1:23985
1514272420429	mozrunner::runner	INFO	Running command: "C:/Program Files/Mozilla Firefox/firefox.exe" "-marionette" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.xY0ZYju1Mo1g"
1514272420918	Marionette	DEBUG	Received observer notification "profile-after-change"
1514272420986	Marionette	DEBUG	Received observer notification "command-line-startup"
1514272420986	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Administrator\AppData\Local\openvr\openvrpaths.vrpath
[Parent 5316, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\Administrator\AppData\Local\openvr\openvrpaths.vrpath
[Child 14124, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1514272421911	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1514272422267	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1514272422268	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1514272422268	Marionette	DEBUG	Setting recommended pref extensions.e10sBlocksEnabling to false
1514272422268	Marionette	DEBUG	New connections are accepted
1514272422269	Marionette	INFO	Listening on port 57149
1514272422472	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:57149
1514272422460	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:57155
1514272422472	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1514272422472	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1514272422462	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1514272422462	Marionette	WARN	TLS certificate errors will be ignored for this session
1514272422517	Marionette	DEBUG	Register listener.js for window 4294967297
1514272422529	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"e02641a7-8a07-460a-8d2a-58426026c335","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":5316,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\rust_mozprofile.xY0ZYju1Mo1g","moz:webdriverClick":false}}]
1514272422535	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"e02641a7-8a07-460a-8d2a-58426026c335","capabilities":{"browserName":"firefox","browserVersion":"57.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":5316,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\rust_mozprofile.xY0ZYju1Mo1g","moz:webdriverClick":false}}]
1514272422535	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"e02641a7-8a07-460a-8d2a-58426026c335","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"57.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":5316,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\rust_mozprofile.xY0ZYju1Mo1g","moz:webdriverClick":false,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1514272422691	webdriver::server	DEBUG	-> POST /session/e02641a7-8a07-460a-8d2a-58426026c335/url {"url":"http://www.google.com"}
1514272422691	geckodriver::marionette	TRACE	-> 43:[0,2,"get",{"url":"http://www.google.com"}]
1514272422682	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://www.google.com"}]
1514272422684	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1514272425249	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1514272425249	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1514272425658	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.com/?gws_rd=ssl"
1514272428234	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.com/?gws_rd=ssl"
1514272428237	Marionette	TRACE	0 <- [1,2,null,{}]
1514272428247	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1514272428247	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1514272428263	webdriver::server	DEBUG	-> POST /session/e02641a7-8a07-460a-8d2a-58426026c335/element {"value":"#lga","using":"css selector"}
1514272428263	geckodriver::marionette	TRACE	-> 59:[0,3,"findElement",{"using":"css selector","value":"#lga"}]
1514272428259	Marionette	TRACE	0 -> [0,3,"findElement",{"using":"css selector","value":"#lga"}]
1514272428262	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"9a7892be-f21f-4cad-a808-f61ef918215b","ELEMENT":"9a7892be-f21f-4cad-a808-f61ef918215b"}}]
1514272428263	geckodriver::marionette	TRACE	<- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"9a7892be-f21f-4cad-a808-f61ef918215b","ELEMENT":"9a7892be-f21f-4cad-a808-f61ef918215b"}}]
1514272428263	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"9a7892be-f21f-4cad-a808-f61ef918215b"}}
1514272428279	webdriver::server	DEBUG	-> POST /session/e02641a7-8a07-460a-8d2a-58426026c335/element/9a7892be-f21f-4cad-a808-f61ef918215b/click {"id":"9a7892be-f21f-4cad-a808-f61ef918215b"}
1514272428279	geckodriver::marionette	TRACE	-> 66:[0,4,"clickElement",{"id":"9a7892be-f21f-4cad-a808-f61ef918215b"}]
1514272428277	Marionette	TRACE	0 -> [0,4,"clickElement",{"id":"9a7892be-f21f-4cad-a808-f61ef918215b"}]
1514272428500	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
1514272428501	Marionette	TRACE	0 <- [1,4,null,{}]
1514272428513	geckodriver::marionette	TRACE	<- [1,4,null,{}]
1514272428513	webdriver::server	DEBUG	<- 200 OK {"value": {}}
============ test1 ====
[26.12.17 15:13:42:566] INFO   org.openqa.selenium.remote.ProtocolHandshake createSession Detected dialect: W3C

From the trace, it looks like the geckodriver does not response  Keys.chord(Keys.CONTROL, "a"); at all.  In stead, if I use the following code to replace  Keys.chord(Keys.CONTROL, "a"); , everything work fine.
Actions action = new Actions(driver);
action.keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL).perform();

I can clearly see the geckodriver is handling this command by the following trace :

1514270308461	webdriver::server	DEBUG	-> POST /session/4a9bfa05-a4de-4609-8e50-3ad3737982e1/actions {"actions":[{"type":"key","actions":[{"type":"keyDown","value":"?"},{"type":"keyDown","value":"a"},{"type":"keyUp","value":"a"},{"type":"keyUp","value":"?"}],"id":"default keyboard"}]}
1514270308461	geckodriver::marionette	TRACE	-> 211:[0,5,"performActions",{"actions":[{"actions":[{"type":"keyDown","value":"?"},{"type":"keyDown","value":"a"},{"type":"keyUp","value":"a"},{"type":"keyUp","value":"?"}],"id":"default keyboard","type":"key"}]}]
1514270308451	Marionette	TRACE	0 -> [0,5,"performActions",{"actions":[{"actions":[{"type":"keyDown","value":"?"},{"type":"keyDown","value":"a"},{"type":"keyUp","value":"a"},{"type":"keyUp","value":"?"}],"id":"default keyboard","type":"key"}]}]
1514270308512	Marionette	TRACE	0 <- [1,5,null,{}]

There are lots of   Keys.chord(....) in our test cases and they work well on both Chrome and IE, but cannot work on Firefox browser with the latest geckodriver. It should be a defect of geckodriver. Please address it ASAP. 
Thanks!

**Comment by whimboo** [comment]
The first trace as given here doesn't contain anything which is related to any key press via the action chains. Instead it ends right after the `click`. I assume `chord()` is a helper for your used binding, and as such it is more a problem on that end as for geckodriver. Also you have proven that the following code just works:

> action.keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL).perform();
