### ISSUE TITLE
org.openqa.selenium.WebDriverException: Failed to decode response from marionette

### ISSUE THREAD

**Issue by shikha20s** [mozilla/geckodriver#1113]
i am using below mentioned line of code but i am getting the error :
  org.openqa.selenium.WebDriverException: Failed to decode response from marionette

System.setProperty("webdriver.gecko.driver", "//opt//geckodriver");
	 String Xport = System.getProperty("lmportal.xvfb.id", ":1");
	 final File firefoxPath = new File(System.getProperty("lmportal.deploy.firefox.path", "/usr/bin/firefox"));
	 FirefoxBinary firefoxBinary = new FirefoxBinary(firefoxPath);
	 firefoxBinary.setEnvironmentProperty("DISPLAY", Xport);
	 FirefoxOptions options = new FirefoxOptions();
		options.setBinary("//usr//bin//firefox"); 
	    options.addArguments("--headless");
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability("moz:firefoxOptions", options);
		WebDriver driver = new FirefoxDriver(capabilities);

**Comment by andreastt** [comment]
You provided very little information about your system. Please see https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs about writing good bug reports.
