### ISSUE TITLE
Allow an optional base-url to cope with tests expecting wd/hub

### ISSUE THREAD

**Issue by ylavoie** [mozilla/geckodriver#1114]
## System
* Version: 0.19.1
* Platform: Unbuntu Zesty
* Firefox: 57.0.3
* Selenium: 

## Testcase

Many tests and tools were developped to connect to host:port/wd/hub. The wd/hub was stripped from geckodriver, requiring modifications to the tests instead of providing a drop in replacement.
Please consider adding a `--url-base=wd/hub` switch when launching the server.

**Comment by andreastt** [comment]
We decided against adding a `--url-base` flag in https://github.com/mozilla/geckodriver/issues/343. Since you already have hard-coded URL paths in your test and you would need to make changes to your client to have it work with geckodriver, it seems like less work just to make that change.
