### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by jsonbruce** [mozilla/geckodriver#1119]
## System
* Version: 0.19.1
* Platform: Ubuntu 16.04.3 x64
* Firefox: Firefox Nightly 59.0a1 (2018-01-01) (64-bit)
* Selenium: 3.8.0 with python
* Python: 3.5.2

## Testcase

just a simple test:

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get("http://www.python.org")
```

## Stacktrace

```
---------------------------------------------------------------------------
SessionNotCreatedException                Traceback (most recent call last)
<ipython-input-1-87692f73a14a> in <module>()
      2 from selenium.webdriver.common.keys import Keys
      3 
----> 4 driver = webdriver.Firefox()
      5 driver.get("http://www.python.org")
      6 assert "Python" in driver.title

/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py in __init__(self, firefox_profile, firefox_binary, timeout, capabilities, proxy, executable_path, options, log_path, firefox_options)
    156                 command_executor=executor,
    157                 desired_capabilities=capabilities,
--> 158                 keep_alive=True)
    159 
    160         # Selenium remote

/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py in __init__(self, command_executor, desired_capabilities, browser_profile, proxy, keep_alive, file_detector, options)
    152             warnings.warn("Please use FirefoxOptions to set browser profile",
    153                           DeprecationWarning)
--> 154         self.start_session(desired_capabilities, browser_profile)
    155         self._switch_to = SwitchTo(self)
    156         self._mobile = Mobile(self)

/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py in start_session(self, capabilities, browser_profile)
    241         parameters = {"capabilities": w3c_caps,
    242                       "desiredCapabilities": capabilities}
--> 243         response = self.execute(Command.NEW_SESSION, parameters)
    244         if 'sessionId' not in response:
    245             response = response['value']

/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    309         response = self.command_executor.execute(driver_command, params)
    310         if response:
--> 311             self.error_handler.check_response(response)
    312             response['value'] = self._unwrap_value(
    313                 response.get('value', None))

/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    235         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
    236             raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
--> 237         raise exception_class(message, screen, stacktrace)
    238 
    239     def _value_or_default(self, obj, key, default):

SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by jsonbruce** [comment]
Below is the output of `geckodriver.log`:

```
1514963797260	geckodriver	INFO	geckodriver 0.19.1
1514963797265	geckodriver	INFO	Listening on 127.0.0.1:38529
```

**Comment by jsonbruce** [comment]
I've found solution:

I added the executable file of Firefox Nightly to `PATH` as `/usr/bin/firefox`.
Then everything is OK now.

**Comment by whimboo** [comment]
The message should be better, which actually will be fixed via issue #832.

**Comment by choosebest** [comment]
geckodriver : 0.18.0-win32
Platform: Windows 10
Firefox: 57.0 (64 bit)
Python 2.7.14
Robot Framework 3.0.2
wxPython 2.18.12.1 (unicode) for Python 2.7
RIDE 1.5.2.1.on Python2.7.14

*** Settings ***
Library           Selenium2Library

*** Test Cases ***
Open URL
    Open Browser    http://www.firefox.com    ff

Just open a web page on Windows 10, got the following error - 
FAIL - SessionNotCreatedException: Message: Unable to find a matching set of capabilities

[degug-20180201-144935.txt](https://github.com/mozilla/geckodriver/files/1687609/degug-20180201-144935.txt)

**Comment by whimboo** [comment]
@choosebest please don't hijack other ones issues. It's not clear if you see the same. So please file a new one and attach a trace level log. The above is a debug log only.

**Comment by far3ll** [comment]
**System**
Platform: Windows 10 64-bit
Firefox: 59.0.1 (64 bit)
geckodriver : 0.20.0-win32
Python 2.7.14 (32-bit)
Robot Framework 3.0.2
wxPython 2.18.12.1 (unicode) for Python 2.7
RIDE 1.5.2.1 on Python 2.7.14
selenium 3.11.0
robot-framework 3.0.2

**Error**

> Unable to find a matching set of capabilities

 after running `driver = webdriver.Firefox(firefox_profile=fp)`

**Solution**
Switching from 64-bit Firefox to 32-bit solved the problem. Probably 64-bit version of webdriver is needed for 64-bit Firefox?

**Comment by andreastt** [comment]
There is no point in switching to 32-bit Firefox. It has no impact on the result.
