### ISSUE TITLE
Fire Fox Browser doesnt open/navigate to requested URL

### ISSUE THREAD

**Issue by Prime2310** [mozilla/geckodriver#1122]
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## Testcase

The browser loads however it does not redirect to the URL as stated below.

```
Dim fireDriver As  New FireFoxDriver(New FireFoxOptions() With {.BrowserExecutableLocation = "C:\Program Files\Mozilla Firefox\firefox.exe"})                
                handler.WebsiteLogin(fireDriver)

    fireDriver.Navigate().GoToUrl("https://www.google.co.uk")
```

## Trace-level log

```
1514898589674   geckodriver     INFO    Listening on 127.0.0.1:63088
1514898590827   mozprofile::profile     INFO    Using profile path C:\Users\GRANTP~1\AppData\Local\Temp\rust_mozprofile.Mt3alKOXTMmE
1514898590829   geckodriver::marionette INFO    Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1514898590847   geckodriver::marionette INFO    Connecting to Marionette on localhost:63121
1514898592849   geckodriver::marionette DEBUG     connection attempt 0/600
1514898594955   geckodriver::marionette DEBUG     connection attempt 1/600
1514898597059   geckodriver::marionette DEBUG     connection attempt 2/600
1514898599160   geckodriver::marionette DEBUG     connection attempt 3/600
1514898601264   geckodriver::marionette DEBUG     connection attempt 4/600
1514898603368   geckodriver::marionette DEBUG     connection attempt 5/600
```

## Expected output
Fire fox browser opens with requested URL.

## Actual output
Firefox browser opens with a blank page.

**Comment by whimboo** [comment]
The attached log is not a trace level log. Please consult https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to create one.

**Comment by java123code** [comment]
Seeing kind of same issue 👍 

c:\tools>psexec /accepteula \\182.6.5.21 -u "MPproject" -p "fkfckfk?" -h "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "C:\MPproject\Automation\Automation.sln"

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


NUnit Console Runner 3.4.0
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.16299.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\MPproject\Automation\Automation.sln

1516139767201   geckodriver     INFO    geckodriver 0.19.1 (0000000000000000000000000000000000000000 2017-10-31)
1516139767208   geckodriver     INFO    Listening on 127.0.0.1:49893
1516139769432   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\kguig~2\\AppData\\Local\\Temp\\rust_mozprofile.ksE0ipxFfhK5"
1516139770193   addons.manager  DEBUG   Application has been upgraded
1516139770244   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider", "XPIInternal"]
1516139770247   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1516139770279   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1516139770281   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1516139770281   addons.manager  DEBUG   Starting provider: XPIProvider
1516139770282   addons.xpi      DEBUG   startup
1516139770282   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1516139770282   addons.xpi      INFO    Removing all system add-on upgrades.
1516139770283   addons.xpi      DEBUG   checkForChanges
1516139770283   addons.xpi      DEBUG   Loaded add-on state: ${}
1516139770284   addons.xpi      INFO    Mapping fxdriver@googlecode.com to C:\Users\MPproject\AppData\Local\Temp\rust_mozprofile.ksE0ipxFfhK5\extensions\fxdriver@googlecode.com
1516139770284   addons.xpi      DEBUG   New add-on fxdriver@googlecode.com in app-profile
1516139770285   addons.xpi      INFO    Mapping fxdriver@googlecode.com to C:\Users\MPproject\AppData\Local\Temp\rust_mozprofile.ksE0ipxFfhK5\extensions\fxdriver@googlecode.com
1516139770287   addons.xpi      INFO    Mapping activity-stream@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\activity-stream@mozilla.org.xpi
1516139770287   addons.xpi      INFO    Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1516139770287   addons.xpi      INFO    Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1516139770287   addons.xpi      INFO    Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1516139770287   addons.xpi      INFO    Mapping followonsearch@mozilla.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\followonsearch@mozilla.com.xpi
1516139770288   addons.xpi      INFO    Mapping formautofill@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\formautofill@mozilla.org.xpi
1516139770288   addons.xpi      INFO    Mapping onboarding@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\onboarding@mozilla.org.xpi
1516139770288   addons.xpi      INFO    Mapping screenshots@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1516139770288   addons.xpi      INFO    Mapping shield-recipe-client@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\shield-recipe-client@mozilla.org.xpi
1516139770288   addons.xpi      INFO    Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1516139770289   addons.xpi      DEBUG   New add-on activity-stream@mozilla.org in app-system-defaults
1516139770289   addons.xpi      INFO    Mapping activity-stream@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\activity-stream@mozilla.org.xpi
1516139770290   addons.xpi      DEBUG   New add-on aushelper@mozilla.org in app-system-defaults
1516139770290   addons.xpi      INFO    Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1516139770291   addons.xpi      DEBUG   New add-on e10srollout@mozilla.org in app-system-defaults
1516139770291   addons.xpi      INFO    Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1516139770291   addons.xpi      DEBUG   New add-on firefox@getpocket.com in app-system-defaults
1516139770292   addons.xpi      INFO    Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1516139770292   addons.xpi      DEBUG   New add-on followonsearch@mozilla.com in app-system-defaults
1516139770292   addons.xpi      INFO    Mapping followonsearch@mozilla.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\followonsearch@mozilla.com.xpi
1516139770293   addons.xpi      DEBUG   New add-on formautofill@mozilla.org in app-system-defaults
1516139770293   addons.xpi      INFO    Mapping formautofill@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\formautofill@mozilla.org.xpi
1516139770293   addons.xpi      DEBUG   New add-on onboarding@mozilla.org in app-system-defaults
1516139770293   addons.xpi      INFO    Mapping onboarding@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\onboarding@mozilla.org.xpi
1516139770293   addons.xpi      DEBUG   New add-on screenshots@mozilla.org in app-system-defaults
1516139770294   addons.xpi      INFO    Mapping screenshots@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1516139770294   addons.xpi      DEBUG   New add-on shield-recipe-client@mozilla.org in app-system-defaults
1516139770295   addons.xpi      INFO    Mapping shield-recipe-client@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\shield-recipe-client@mozilla.org.xpi
1516139770295   addons.xpi      DEBUG   New add-on webcompat@mozilla.org in app-system-defaults
1516139770295   addons.xpi      INFO    Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1516139770302   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1516139770303   addons.xpi      DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1516139770303   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1516139770303   addons.xpi      DEBUG   getInstallState changed: true, state: {}
1516139770303   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1516139770309   addons.xpi-utils        DEBUG   Opening XPI database C:\Users\MPproject\AppData\Local\Temp\rust_mozprofile.ksE0ipxFfhK5\extensions.json
1516139770311   addons.xpi-utils        DEBUG   New add-on fxdriver@googlecode.com installed in app-profile
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1516139770424   addons.xpi      WARN    Add-on fxdriver@googlecode.com is not correctly signed.
1516139770424   addons.xpi      WARN    Add-on fxdriver@googlecode.com is not correctly signed.
1516139770425   addons.xpi      WARN    Add-on fxdriver@googlecode.com is not correctly signed.
1516139770428   DeferredSave.extensions.json    DEBUG   Save changes
1516139770429   addons.xpi-utils        DEBUG   New add-on activity-stream@mozilla.org installed in app-system-defaults
1516139770652   DeferredSave.extensions.json    DEBUG   Starting timer
1516139770654   DeferredSave.extensions.json    DEBUG   Save changes
1516139770655   addons.xpi-utils        DEBUG   New add-on aushelper@mozilla.org installed in app-system-defaults
1516139770669   DeferredSave.extensions.json    DEBUG   Save changes
1516139770669   addons.xpi-utils        DEBUG   New add-on e10srollout@mozilla.org installed in app-system-defaults
1516139770682   DeferredSave.extensions.json    DEBUG   Save changes
1516139770682   addons.xpi-utils        DEBUG   New add-on firefox@getpocket.com installed in app-system-defaults
1516139770745   DeferredSave.extensions.json    DEBUG   Save changes
1516139770745   addons.xpi-utils        DEBUG   New add-on followonsearch@mozilla.com installed in app-system-defaults
1516139770758   DeferredSave.extensions.json    DEBUG   Save changes
1516139770758   addons.xpi-utils        DEBUG   New add-on formautofill@mozilla.org installed in app-system-defaults
1516139770901   DeferredSave.extensions.json    DEBUG   Save changes
1516139770901   addons.xpi-utils        DEBUG   New add-on onboarding@mozilla.org installed in app-system-defaults
1516139771017   DeferredSave.extensions.json    DEBUG   Save changes
1516139771017   addons.xpi-utils        DEBUG   New add-on screenshots@mozilla.org installed in app-system-defaults
1516139771048   DeferredSave.extensions.json    DEBUG   Save changes
1516139771048   addons.xpi-utils        DEBUG   New add-on shield-recipe-client@mozilla.org installed in app-system-defaults
1516139771099   DeferredSave.extensions.json    DEBUG   Save changes
1516139771099   addons.xpi-utils        DEBUG   New add-on webcompat@mozilla.org installed in app-system-defaults
1516139771117   DeferredSave.extensions.json    DEBUG   Save changes
1516139771117   addons.xpi-utils        DEBUG   New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1516139771143   DeferredSave.extensions.json    DEBUG   Save changes
1516139771144   addons.manager  DEBUG   Registering startup change 'installed' for fxdriver@googlecode.com
1516139771144   addons.xpi-utils        DEBUG   Make addon app-profile:fxdriver@googlecode.com visible
1516139771144   addons.xpi      DEBUG   Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"{834a770f-84ac-4cb0-8fdb-0cf6513849cd}","location":"app-profile","version":"3.8.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"installDate":1516139768678,"updateDate":1516139768678,"applyBackgroundUpdates":1,"bootstrap":false,"path":"C:\\Users\\MPproject\\AppData\\Local\\Temp\\rust_mozprofile.ksE0ipxFfhK5\\extensions\\fxdriver@googlecode.com","skinnable":false,"size":3280254,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"52.0"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":null},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null,"icons":{},"iconURL":null,"icon64URL":null,"blocklistState":0,"blocklistURL":null}
1516139771148   DeferredSave.extensions.json    DEBUG   Save changes
1516139771148   addons.manager  DEBUG   Registering startup change 'installed' for activity-stream@mozilla.org
1516139771155   addons.xpi      DEBUG   Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\activity-stream@mozilla.org.xpi
1516139771157   addons.xpi      DEBUG   Calling bootstrap method install on activity-stream@mozilla.org version 2017.11.07.1100-7f4e3634
1516139771158   addons.xpi-utils        DEBUG   Make addon app-system-defaults:activity-stream@mozilla.org visible

**Comment by whimboo** [comment]
Once again, without a trace level log we cannot help.

**Comment by eireland** [comment]
I have the same problem with geckodriver 0.19 webdriver 3.8 and FF57.0.4 64-bit.
I have tried to get a tracelog using both geckodriver -vv and 
```
Selenium::WebDriver.logger.level = :debug
opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
driver = Selenium::WebDriver.for :firefox, options: opts
```
and nothing appears. 
I did a logger.level =:info and got
```
Skipping handshake as we know it is W3C
->POST session
>>> http://127.0.0.1:4445/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}},"capabilities":{"firstWatch":[{"browserName":"firefox","timeout":{},"moz:firefoxOptions":{"log":{"level":"trace"}}}]}}
```
My code is basic:
```
require "selenium-webdriver"

Selenium::WebDriver.logger.level = :info
opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
driver = Selenium::WebDriver.for :firefox, options: opts
driver.navigate.to "https://google.com"

element = driver.find_element(name: 'q')
element.send_keys "Hello WebDriver!"
element.submit

puts driver.title

driver.quit
```

**Comment by andreastt** [comment]
@eireland To claim that that is the same problem without a stacktrace, error, or a trace-log is reaching.

**Comment by eireland** [comment]
![image](https://user-images.githubusercontent.com/7716653/35107563-21e0c0d6-fc26-11e7-9305-befc67b8a3f9.png)

**Comment by andreastt** [comment]
Without a [trace-level log] we are left to guessing what is wrong. Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by eireland** [comment]
Above iimage is the trace log

**Comment by andreastt** [comment]
First of all, it’s very hard to read a screenshot. As you can tell from the log, it shows that Firefox isn’t starting up. This isn’t the problem you reported originally, as that log does show that Firefox starts.

Which Firefox version are you using?

**Comment by Prime2310** [comment]
This is exactly what I am getting.

Fire fox does start but does not navigate to the URL as stated in the code.

**Comment by andreastt** [comment]
@Prime2310 Can’t help you without the information requested in the [issue template](https://github.com/mozilla/geckodriver/blob/master/ISSUE_TEMPLATE.md). See [CONTRIBUTING.md)(https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md#reporting-bugs) on how to report a good bug.

**Comment by Prime2310** [comment]
I'm ok then

Well I followed what I saw but ok. Anyway I thought what I provided was a
trace level log. I just shortened it. Is there no advice or help you can
give as to what the issue might be as I have done. Have you even tried the
code I put with using a new solution. I followed exactly what I saw on
YouTube videos and saw their solution work yet mine does not.


I just find it strange that. Oh you haven't done this we not helping full
stop where I have seen posts with the info that I have provided and they
have had help.

#peeved.

**Comment by Prime2310** [comment]
And I followed the trace level options that you have described. And that's
what was displayed in the CMD window so I don't know what you are referring
to then.

**Comment by eireland** [comment]
Finally figured out how to get the test out of command line. Trace log I got is:
```
2018-01-18 09:39:31 DEBUG Selenium Executing Process ["C:/Windows/System32/geckodriver.exe", "--binary=C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe", "--port=4444"]
1516297171795   geckodriver     INFO    Listening on 127.0.0.1:4444
2018-01-18 09:39:32 INFO Selenium Skipping handshake as we know it is W3C.
2018-01-18 09:39:32 INFO Selenium -> POST session
2018-01-18 09:39:32 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}}}]}}
2018-01-18 09:39:32 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"247"}
1516297172296   mozprofile::profile     INFO    Using profile path C:\Users\CCUSER~1\AppData\Local\Temp\rust_mozprofile.dgwhJtIjqqWS
1516297172312   geckodriver::marionette INFO    Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1516297172343   geckodriver::marionette INFO    Connecting to Marionette on localhost:12656
1516297174373   geckodriver::marionette DEBUG     connection attempt 0/600
1516297176489   geckodriver::marionette DEBUG     connection attempt 1/600
1516297178595   geckodriver::marionette DEBUG     connection attempt 2/600
1516297180714   geckodriver::marionette DEBUG     connection attempt 3/600
1516297182873   geckodriver::marionette DEBUG     connection attempt 4/600
1516297184985   geckodriver::marionette DEBUG     connection attempt 5/600
1516297187089   geckodriver::marionette DEBUG     connection attempt 6/600
1516297189194   geckodriver::marionette DEBUG     connection attempt 7/600
1516297191341   geckodriver::marionette DEBUG     connection attempt 8/600
1516297193474   geckodriver::marionette DEBUG     connection attempt 9/600
1516297195596   geckodriver::marionette DEBUG     connection attempt 10/600
1516297197741   geckodriver::marionette DEBUG     connection attempt 11/600
1516297199874   geckodriver::marionette DEBUG     connection attempt 12/600
1516297201984   geckodriver::marionette DEBUG     connection attempt 13/600
1516297204090   geckodriver::marionette DEBUG     connection attempt 14/600
1516297206195   geckodriver::marionette DEBUG     connection attempt 15/600
1516297208312   geckodriver::marionette DEBUG     connection attempt 16/600
1516297210462   geckodriver::marionette DEBUG     connection attempt 17/600
1516297212587   geckodriver::marionette DEBUG     connection attempt 18/600
1516297214691   geckodriver::marionette DEBUG     connection attempt 19/600
1516297216827   geckodriver::marionette DEBUG     connection attempt 20/600
1516297218964   geckodriver::marionette DEBUG     connection attempt 21/600
1516297221083   geckodriver::marionette DEBUG     connection attempt 22/600
1516297223192   geckodriver::marionette DEBUG     connection attempt 23/600
1516297225296   geckodriver::marionette DEBUG     connection attempt 24/600
1516297227442   geckodriver::marionette DEBUG     connection attempt 25/600
1516297229575   geckodriver::marionette DEBUG     connection attempt 26/600
1516297231679   geckodriver::marionette DEBUG     connection attempt 27/600
```

**Comment by andreastt** [comment]
@eireland And I ask, for the third time, what version of Firefox are you using?

**Comment by eireland** [comment]
Sorry, I've been answering the same question on multiple baords and don't remember where I have typed it in. FF 57.0.4 64 bit Win 10 geckodriver 0.19 webdriver ruby binding 3.8

**Comment by andreastt** [comment]
I can’t see anything immediately suspicious with the log, though it is interesting that the network read timeout happens after so few connection attempts. Are you able to launch the firefox.exe manually fine? Is there a firewall running on the machine that prevents geckodriver from listening?

**Comment by eireland** [comment]
Yes I can call firefox.exe in the mozilla folder fine. There should be no firewalls except for usual Windows Defender

**Comment by eireland** [comment]
Yippee! I think I solved my problem. Somehow, my PATH variable is not finding gecko, so I stuck it in the System folder, and now everything works fine. Thanks for the clue in terms of  the firefox.exe. I was able to understand the trace log better.

**Comment by whimboo** [comment]
I assume you mean geckodriver and not gecko. If yes, this executable was already in that system folder for your [last provided log](https://github.com/mozilla/geckodriver/issues/1122#issuecomment-358724863). So I don't see what really has been changed here. Btw. the mentioned log is a debug, but not a trace log.

**Comment by eireland** [comment]
Windows>System32. I will retry my PATH variable again as my other Win setup
does not require geckodriver to be in the system folder.
