### ISSUE TITLE
"Failed to decode response from marionette" on WebRTC test

### ISSUE THREAD

**Issue by jrcosmo** [mozilla/geckodriver#1125]
## System
* Version: geckodriver 0.19.1
* Platform: MacOSX High Sierra 10.13.2 and Ubuntu 16.04.3 LTS (Windows not tested)
* Firefox:
Linux: 59.0a1 latest nightly = 59.0~a1~hg20180102r397555-0ubuntu0.16.04.1~umd1
Mac: 59.0a1 latest nightly = 20180109234707

* Selenium: 3.7.1 Java

## Testcase
KITE-AppRTC-Test (https://github.com/webrtc/KITE): Opens https://appr.tc on Firefox nightly and Safari. Creates and joins a common WebRTC session, executes script every second to check value of WebRTC related object (PeerConnection status).

Result:
Testing Firefox nightly on MacOSX and Linux vs Safari 11 and Safari Tech Preview, results on WebDriver error "Failed to decode response from marionette", including stacktrace (see below)
Testing Firefox nightly against other Firefox versions doesn't show this.

geckodriver trace log shows these two lines, look suspicious:

`###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv`
`A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down`

## Stacktrace
See [marionette.error.bis.txt](https://github.com/mozilla/geckodriver/files/1617472/marionette.error.bis.txt)
and 
[marionette.error.txt](https://github.com/mozilla/geckodriver/files/1617474/marionette.error.txt)

## Trace-level log
Linux: [marionette.error.geckodriver.trace.txt](https://github.com/mozilla/geckodriver/files/1617477/marionette.error.geckodriver.trace.txt)
Mac: [marionette.error.geckodriver.trace.mac.txt](https://github.com/mozilla/geckodriver/files/1617514/marionette.error.geckodriver.trace.mac.txt)

**Comment by whimboo** [comment]
You are experiencing a content crash (tab) in Firefox, and as such the browser closes itself. As result you see this side-effect that geckodriver is not able to decode the message. There is https://bugzilla.mozilla.org/show_bug.cgi?id=1401131 for this particular problem.

I would appreciate if you could help us to identify the cause of the crash. Sadly there is no automation for that yet, so you would manually have to extrace the minidump file from the used profile. To do that please update your teardown method, and maybe add a long sleep, which would prevent the profile from getting deleted. Then go to the used profile on disk and copy everything from under the `minidumps` folder to another folder. Zip the content and send me that file. I can then investigate the crash.

Otherwise can you check when this crash started to happen? Do you also see it with Firefox 58 beta or Firefox 57?

**Comment by jrcosmo** [comment]
minidump folder is empty, keeping the profile for a while no dump is actually created.
Not seen on Firefox 57.04, Firefox 58.0b13
Including profile for one crash after some waiting.
[egHrNFBJDRaU.tar.gz](https://github.com/mozilla/geckodriver/files/1621366/egHrNFBJDRaU.tar.gz)
Very much happy to help troubleshoot, can maybe activating some debugging or logging options help?
I tried with RUST_LOG="debug" but that didn't show that much info.

**Comment by whimboo** [comment]
Strange that there is no minidump file present in that folder. I cannot try it out myself yet (I want to fix issue #1058 first).

For now I would suggest that you make use of a debug build of Firefox Nightly. You can grab one of the latest here:

https://queue.taskcluster.net/v1/task/FL3o11LRSSW3n-fMO8SiCg/runs/0/artifacts/public/build/target.dmg

It will output way more to the log, so hopefully we can see an assertion or such which would help us directly. Thanks.

**Comment by jrcosmo** [comment]
Attached two logs running the tests using [https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.latest.firefox.linux64-debug/artifacts/public/build/target.tar.bz2](https://index.taskcluster.net/v1/task/gecko.v2.mozilla-central.latest.firefox.linux64-debug/artifacts/public/build/target.tar.bz2)

In both cases the following appears, suggesting WebRTC related content process crash, if you agree I would close this and open in bugzilla.

```
Hit MOZ_CRASH() at /builds/worker/workspace/build/src/media/webrtc/signaling/src/peerconnection/PeerConnectionMedia.cpp:490
#01: ???[/tmp/firefox-trunk-debug/libxul.so +0x1509d30]
#02: ???[/tmp/firefox-trunk-debug/libxul.so +0x150bc35]
[...]
[Parent 17515, Gecko_IOThread] WARNING: pipe error (58): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x150082,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

++DOCSHELL 0x7f0d90ebe000 == 6 [pid = 17515] [id = {741409a7-d60e-48ab-b994-b97efab99194}]
++DOMWINDOW == 17 (0x7f0dc1cf56d0) [pid = 17515] [serial = 17] [outer = (nil)]
++DOMWINDOW == 18 (0x7f0daef5a800) [pid = 17515] [serial = 18] [outer = 0x7f0dc1cf56d0]

```

**Comment by whimboo** [comment]
Yes, totally! Please file that bug into https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=WebRTC%3A%20Signaling. Thanks a lot!

**Comment by jrcosmo** [comment]
[https://bugzilla.mozilla.org/show_bug.cgi?id=1430707](https://bugzilla.mozilla.org/show_bug.cgi?id=1430707) open, will close this one.
Thanks!

**Comment by whimboo** [comment]
Thanks!

**Comment by whimboo** [comment]
@jrcosmo does the latest nightly build with the fix work for you?

**Comment by jrcosmo** [comment]
Didn't have the chance to verify yet, plan to do it shortly.

**Comment by HardikModha** [comment]
@jrcosmo Hi, Did the nightly build work for you? I was facing the similar kind of error `Failed to decode response from marionette` and the latest nightly build worked for me. You can take a look at the [issue](https://github.com/mozilla/geckodriver/issues/1111)

**Comment by diraviya** [comment]
@whimboo Hi, `I am getting this failed to decode response from marionette` error while running selenium grid - parallel suite. I read your comments for issues similar to this, I have Firefox nightly build and it works if I run the test case just in Firefox browser. But it fails in driver.Quit() if i run the test case along with other tests in selenium grid for parallel suite execution. And my Firefox image in selenium grid is with the Firefox version of 60. I am not sure how to get the Firefox nightly build version:63 in docker image. Can you help me with this please.

**Comment by whimboo** [comment]
@diraviya please don't high-jack an already closed issue. Instead please file a new one and provide all the details as requested. Thanks.

**Comment by diraviya** [comment]
@whimboo Sorry, I didn't mean to high-jack this closed issue. I will raise a new issue if needed. Thanks
