### ISSUE TITLE
Need file rolling ability for geckodriver log

### ISSUE THREAD

**Issue by nddipiazza** [mozilla/geckodriver#1126]
## System
* Version: 0.19.1
* Platform: Linux 64-bit
* Firefox: 57.0.1
* Selenium: 3.5.3

## Testcase

Set log file using

```
new GeckoDriverService.Builder()
          .usingDriverExecutable(new File(geckoDriverBinaryPath))
          .withLogFile(geckoLogFile)
          .build();
```
We need to add log rolling ability otherwise this log can get very massive.

**Comment by andreastt** [comment]
I don’t understand what this issue is about, but it seems like a client issue and not related to geckodriver.

**Comment by nddipiazza** [comment]
@andreastt i meant that if you are running lots of tests using the same gecko driver service, when using the "withLogFile" option to write to a log, that log file can get many GB large. i was creating this issue to see if we can add log file rotation to this file to manage this.

**Comment by andreastt** [comment]
Again, that has nothing to do with the geckodriver project itself. You should file a bug against the client you are using which intercepts the geckodriver output.

**Comment by nddipiazza** [comment]
oh i see. didn't realize that. that would be selenium then.
