### ISSUE TITLE
ActionChains(driver).move_to_element(ele).perform() fails with "TypeError: action.inputStateMap is undefined"

### ISSUE THREAD

**Issue by kskashyap94** [mozilla/geckodriver#1127]
## System
* Version: 0.19
* Platform: macOS
* Firefox: 58.0b15 (Developer Edition)
* Selenium: 3.4.1

## Testcase
I am using selenium with python, trying to do mouse hover an element using ActionChains. I see the below exception when i try to do the same:
<b>selenium.common.exceptions.WebDriverException: Message: TypeError: action.inputStateMap is undefined</b>

Here is the code that i use to perform the said action:
`element = self._basic_utility.find_element_by_class_name("some-element-class-name")`
`hover = ActionChains(self._browser._driver).move_to_element(element)`
`hover.perform()`

## Stacktrace
selenium.common.exceptions.WebDriverException: Message: TypeError: action.inputStateMap is undefined

Is there anyone facing the same issue ?

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1621966/geckodriver.log)

**Comment by whimboo** [comment]
Sadly the attached log is too huge, and secondly not a trace level log. If you could reduce your test so only the important commands are getting logged that would be great. Further please read this document in how to get trace level logs: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by kskashyap94** [comment]
Please find the attached trace level log for further debugging
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1625597/geckodriver.log)

**Comment by whimboo** [comment]
You are using an outdated version of Firefox. Can you please check again with the latest 58b16?

**Comment by kskashyap94** [comment]
Great!, it works with the latest version (58b16) of firefox. Can i know was there any defect in the earlier version of firefox(58b15) that caused me this problem?

**Comment by andreastt** [comment]
@kskashyap94 Did you reply but accidentally delete your last message? 😕

**Comment by kskashyap94** [comment]
yeah it was by mistake sorry :( , I tried with latest 58b16. It worked for the very first time after I updated the browser version , but i'm seeing the same issue reported earlier from the next time onwards. 

Attaching the trace level log for after upgrading to latest version(58b16): 
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1633806/geckodriver.log)

**Comment by whimboo** [comment]
@kskashyap94 working on a more recent version of Selenium should always be a good idea. But not sure if this could affect this issue.

Which version of Firefox is working for you? Was it the 57, 56, or 55 release? It would be good to know since when it is broken.

**Comment by kskashyap94** [comment]
@andreastt Yes, it works against firefox nightly. But can i know what is the reason for the same to not work against Firefox Developer edition

**Comment by whimboo** [comment]
It seems that this was a fix which only landed for Firefox Nightly. So an upcoming Developer edition build with version 59 will fix it. It should be released in the next couple of days.

**Comment by kskashyap94** [comment]
@whimboo Sounds great!. I'll try on that and update this thread.

**Comment by AutomatedTester** [comment]
closing as this appears to have been fixed and running the trains
