### ISSUE TITLE
Not getting margin or padding python/OSX

### ISSUE THREAD

**Issue by Jiff21** [mozilla/geckodriver#1130]
Not getting margin or padding from Firefox.

## System
* Version: 0.17.0 or 0.19.1
* Platform: OS X 10.12.6
* Firefox: 57.0.4
* selenium python 3.8.1 or 3.5.0
* Python 2.7.10 or Python 3.6.2

## Testcase

```
driver = webdriver.Firefox()
driver.get("http://www.python.org")
print(driver.name)
elem = driver.find_element_by_id("id-search-field")
print(elem.value_of_css_property("padding"))
margin_elem = driver.find_element_by_id("submit")
print(elem.value_of_css_property("margin"))
driver.close()
```
Returns
```
(env) [|selenium_playground]$ python example.py 
firefox

.
----------------------------------------------------------------------
Ran 1 test in 6.006s
```

**Comment by whimboo** [comment]
This is not going to work, given that you are using a shorthand property name here. While it is allowed to use for setting a property, to actually retrieve it you will have to query the longhand property name. This is also described in the notes section of the [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#Notes).

To solve your issue use `padding-top` or equivalent.
