### ISSUE TITLE
Firefox Profile - Cannot open window as TAB.

### ISSUE THREAD

**Issue by 1dragosh** [mozilla/geckodriver#1139]
## System
* geckodriver 0.19.1
* Linux Mint Cinnamon 18.3
* Firefox: 57.0.4 (64-bit)
* Selenium: python - selenium 3.8.0

## Testcase

```
ffprof = webdriver.FirefoxProfile()
ffprof.update_preferences()
driver = webdriver.Firefox(firefox_profile=ffprof)
driver.execute_script('window.open("http://www.google.com", "_blank");')
```

OR:

```
ffprof = webdriver.FirefoxProfile()
ffprof.set_preference("browser.link.open_newwindow", 3)
ffprof.update_preferences()
driver = webdriver.Firefox(firefox_profile=ffprof)
driver.execute_script('window.open("http://www.google.com", "_blank");')
```

## Stacktrace

Whenever geckodriver loads a new profile, it cannot open a new tab with window open and it opens a new window instead.
If no profile is loaded, geckodriver proceeds to opening `window.open` links as tabs.
Even if setting `browser.link.open_newwindow` to `3`, geckodriver still opens tabs as windows.

**Comment by whimboo** [comment]
Do not set preferences via the profile instance, but via the Firefox options class: https://github.com/mozilla/geckodriver/#prefs-object. Also see the example below on that page.

Does that fix your problem?

**Comment by 1dragosh** [comment]
```
firefox_capabilities = DesiredCapabilities.FIREFOX.copy()
firefox_capabilities['prefs'] = ["browser.link.open_newwindow", 3]
firefox_capabilities['args'] = ['-headless']

driver = webdriver.Firefox(capabilities=firefox_capabilities)
driver.get("https://www.google.com")
driver.execute_script("window.open('https://www.google.com', '_blank')")
driver.switch_to.window(driver.window_handles[1])
```

Still the same..

**Comment by andreastt** [comment]
The default value of `browser.link.open_newwindow` is `3`, which I believe is new window. We don’t override it in geckodriver or Marionette. However, you are configuring your prefs incorrectly, see the README for what the capabilities object should look like. Consider using the `FirefoxOptions` helper in the Selenium Python client.

**Comment by 1dragosh** [comment]
Yes, the default value is 3, but however, a new profile will overwrite it to 2.
As for the capabilities, I've tried to read the page, but still haven't got a clue about setting it up

**Comment by andreastt** [comment]
Right, so I have no idea why you’re trying to set it to `3`. The JSON input is supposed to look like `{"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"prefs": {"browser.link.open_newwindow": 2}}}}}`, and the `FirefoxOptions` class will help you produce this.

**Comment by andreastt** [comment]
I don’t think there is any further action to be taken here.

**Comment by Hiram711** [comment]
I got the same problem.
When using the headless mode I tried to switch to a new window opened by click a link href using "window_handles",but the window_handles did not contians the new window handle.
Really confused!

**Comment by whimboo** [comment]
@Hiram711, your comment doesn't add any helpful information which would help us to investigate it. Also this is a closed issue, and you should not comment on it. Instead please file your own issue with all the requested information.
