### ISSUE TITLE
Releases of Marionette driver for MacOS both for 64 bit and 32bit?

### ISSUE THREAD

**Issue by pumano** [mozilla/geckodriver#114]
Very important question for me. I see only one download package for Mac, but without bits (32 or 64)?

**Comment by pumano** [comment]
somebody help me? I need to know details about 32 or 64 bit release of geckodriver?

**Comment by jgraham** [comment]
Releases will be 64bit only. Going forward there will be no Firefox releases for OSX < 10.9 Since 10.9 won't run on 32 bit CPUs there is no point in making a 32bit geckodriver release.

**Comment by rajeevpbn** [comment]
Hi, There is no releases in windows 32 bit too? from Mozilla side?

Please let me know.

**Comment by andreastt** [comment]
@rajeevpbn See https://github.com/mozilla/geckodriver/issues/146. This bug is about 32-bit macOS binaries.

**Comment by rajeevpbn** [comment]
Yes, I have seen it. Is it possible to make the build quickly. Really i am unable to move further. cant downgrade the browser or not able to use Geckodrivers. Thanks for your reply.

**Comment by andreastt** [comment]
@rajeevpbn If you have access to a Windows 32-bit machine you can compile it yourself if you have the Rust toolchain installed. The build steps are described in the [README](https://github.com/mozilla/geckodriver/blob/master/README.md#building).

**Comment by rajeevpbn** [comment]
Thanks for the information @andreastt - I don't have permission to install anything on my machine. That is why i was not able to degrade firefox. So only depends on your release builds. 

Regards,
