### ISSUE TITLE
no way to enable native events, while using geckodriver

### ISSUE THREAD

**Issue by dewanprakash** [mozilla/geckodriver#1147]
## System
* Version:  0.19.1 
* Platform: Windows 7 Pro
* Firefox: 57.0.3 (32 bit)
* Selenium: Java + 3.8.1

## Testcase

We could do the required action, by enabling the flag on Firefox profile with Se 2.46 & FF 46.
FirefoxProfile profile = new FirefoxProfile();
profile.setEnableNativeEvents(true);

However, seems to be no longer available with geckodriver

**Comment by andreastt** [comment]
The WebDriver implementation for Firefox prior to 47 was maintained by the Selenium project, but the current implementation is by Mozilla and does not have native events.
