### ISSUE TITLE
some elements works as they should only with opened and activated window of firefox.

### ISSUE THREAD

**Issue by Pilleo** [mozilla/geckodriver#1149]
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## Testcase
Dropdown with cities does not appears if the window is not active. After that selenium obviously canot find elements inside that dropdown. If you open that window and will actually see all the process with your eyes, than everything works as it should. It seems that firefox telling the page that it is not active now, and not all scripts are working as they should.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment]
I think that this is a dupe of issue #906.
