### ISSUE TITLE
Headless mode isn't working in Firefox

### ISSUE THREAD

**Issue by WarleyGabriel** [mozilla/geckodriver#1155]
## System
* Version: 0.19.1
* Platform: Linux
* Firefox version: 57.0.4
* WebdriverIO version: 4.10.1
* Node.js version: 5.6.0

## Testcase
When I use firefoxProfile for install the extension in browser, the headless mode isn't working. 
The headless option is not present in the parameters. 
I use the firefoxProfile to install the extension.
````
firefoxProfile: {
        extensions: ['Extension.xpi']
    }
````

And the firefoxOptions is set headless mode.
````
{
        maxInstances: 1,
        browserName: 'firefox',
        "moz:firefoxOptions":{
            "args":["-headless"]
        },
        "zal:recordVideo": false
}
````

## Trace-level log

The driver is created without headless mode.
````
 {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,
"handlesAlerts":true,"rotatable":true,"maxInstances":1,
"browserName":"firefox","moz:firefoxOptions":{"profile":"[base64] 218368 bytes"},
"zal:recordVideo":true,"firefox_profile":"[base64] 218368 bytes",
"loggingPrefs":{"browser":"ALL","driver":"ALL"},"_":"1 more keys: [\"requestOrigins\"]"}}
````
If I comment the firefoxProfile.
The driver is created with headless mode.
````
{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,
"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"firefox",
"moz:firefoxOptions":{"args":["-headless"]},"zal:recordVideo":false,
"loggingPrefs":{"browser":"ALL","driver":"ALL"},
"requestOrigins":{"url":"http://webdriver.io","version":"4.10.1","name":"webdriverio"}}}
````

**Comment by andreastt** [comment]
Your first capabilities object doesn’t contain `{"moz:firefoxOptions": {"args": ["-headless"]}}`, but only a profile, which explains why FIrefox isn’t started in headless mode.

This seems like a bug with your code or the client you are using?

**Comment by WarleyGabriel** [comment]
Hi @andreastt, I have see this diference, but in two cases the code "moz:firefoxOptions":{"args":["-headless"]}, is implemented.
I think when I implemented the firefoxProfile, the firefoxOptions isn't working.

**Comment by andreastt** [comment]
OK, if you will attach a trace-level log we can tell which it is.

**Comment by WarleyGabriel** [comment]
I added the trace-level ``` "logging:level": "trace" ```, but it did not make a diference. 

````
[21:48:07]  COMMAND     POST     "/wd/hub/session"
[21:48:07]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"firefox","moz:firefoxOptions":{"profile":"[base64] 218368 bytes"},"zal:recordVideo":false,"firefox_profile":"[base64] 218368 bytes","loggingPrefs":{"browser":"ALL","driver":"ALL"},"_":"1 more keys: [\"requestOrigins\"]"}}
[21:48:10]  INFO        SET SESSION ID cf71cceb-86b3-4e0f-99b4-87771a0058ab
[21:48:10]  RESULT              {"sessionId":"cf71cceb-86b3-4e0f-99b4-87771a0058ab","capabilities":{"moz:profile":"/tmp/rust_mozprofile.zAo6T7Kyc9Su","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"pageLoadStrategy":"normal","moz:headless":false,"moz:accessibilityChecks":false,"acceptInsecureCerts":false,"browserVersion":"58.0","platformVersion":"4.13.0-32-generic","moz:processID":9112,"browserName":"firefox","platformName":"linux","moz:webdriverClick":true}}
`````

**Comment by whimboo** [comment]
Try setting the `MOZ_HEADLESS=1` environment variable when calling your script. Does that work for you as a workaround for now? I'm sure that something doesn't work correctly here with webdriverio.

**Comment by WarleyGabriel** [comment]
Hi @whimboo, I tried with the variable, but it did not work.
I tried with the code below, but the driver is not created.
````
capabilities: [{
maxInstances: 2,
browserName: 'firefox',
"moz:headless": true,
"zal:recordVideo": false
}],
````

**Comment by andreastt** [comment]
In your [comment from ten days ago](https://github.com/mozilla/geckodriver/issues/1155#issuecomment-363261517) you aren’t sending the correct input at all. Did you see my [earlier comment](https://github.com/mozilla/geckodriver/issues/1155#issuecomment-362617425)?

The exact input should be, if you’re using the legacy `desiredCapabilities`/`requiredCapabilities` terminology:

```js
{"desiredCapabilities": {"moz:firefoxOptions": {"args": ["-headless"]}}}
```

**Comment by WarleyGabriel** [comment]
I tried, but it did not work.
The headless option is not present in the parameters.
I'll run the tests without headless mode.

**Comment by dzarasov** [comment]
Working solution, works perfect for me: https://github.com/webdriverio/webdriverio/issues/2299
