### ISSUE TITLE
Geckodriver TakesScreenshot class method getScreenshotAs() creates broken image for page with opened local image file in Firefox

### ISSUE THREAD

**Issue by beluha** [mozilla/geckodriver#1156]
## System
* Version: 3.7.1, 3.8.1
* Platform: Windows 7 64-bit
* Firefox: 57.0.4, 58.0.1 (64-bit)
* Selenium: 3.7.1, 3.8.1

## Testcase

<html>
    <head>
	    <meta name="viewport" content="width=device-width; height=device-height;">
		<link rel="stylesheet" href="resource://content-accessible/ImageDocument.css">
		<link rel="stylesheet" href="resource://content-accessible/TopLevelImageDocument.css">
		<link rel="stylesheet" href="chrome://global/skin/media/TopLevelImageDocument.css">
		<title>Moon.jpg (JPEG Image, 614&nbsp;×&nbsp;619 pixels)</title>
	</head>
	<body>
	    <img src="file:///C:/Temp/Moon.jpg" alt="file:///C:/Temp/Moon.jpg">
	</body>
</html>

## Stacktrace

No

## Trace-level log
In attach
[Log.txt](https://github.com/mozilla/geckodriver/files/1706023/Log.txt)

## Expected Behavior -
Image with browser page content
## Actual Behavior -
An empty/broken image
## Steps to reproduce -

1. There is Moon.jpg file in attach.
![moon](https://user-images.githubusercontent.com/19341020/35846261-f1471d0c-0b26-11e8-9197-1939e0d21862.jpg)

2. Open this file through code with help of geckodriver and FirefoxDriver.
3. Take screenshot with help of TakesScreenshot getScreenshotAs() method.
4. Validate captured image - just open it.

Or execute the following Java code to reproduce provided steps.
## Java code
import java.io.File;
import java.io.IOException;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;

public class BrowserCapture {
    public static void main(String[] args) throws IOException {
        WebDriver driver = new FirefoxDriver(new FirefoxOptions().setProfile(new FirefoxProfile()));
        driver.get("file:///C:/temp/Moon.jpg");
        File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
    }
}
## Verify
Open created image file "scrFile". Windows image viewer says it is empty, FF browser says it has errors.

## Note
Chrome driver and IE Driver server don't have such issue.

**Comment by andreastt** [comment]
And what is the actual output it returns?

**Comment by beluha** [comment]
This method ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE); returns null.

**Comment by andreastt** [comment]
Can you attach a trace-level log?

**Comment by beluha** [comment]
[Log.txt](https://github.com/mozilla/geckodriver/files/1695305/Log.txt)

**Comment by whimboo** [comment]
There is a null value returned for the screenshot:

```
1517838326703	geckodriver::marionette	TRACE	-> 63:[0,3,"takeScreenshot",{"full":false,"highlights":[],"id":null}]
1517838326710	Marionette	TRACE	0 -> [0,3,"takeScreenshot",{"full":false,"highlights":[],"id":null}]
1517838326713	Marionette	TRACE	0 <- [1,3,null,{"value":""}]
1517838326713	geckodriver::marionette	TRACE	<- [1,3,null,{"value":""}]
```
I filed that as https://bugzilla.mozilla.org/show_bug.cgi?id=1437485. Thanks.

**Comment by whimboo** [comment]
This broken behavior is no longer visible. Tested with Firefox 69 and later releases.
