### ISSUE TITLE
Behat + Selenium + GeckoDriver -> issue when launching Firefox, shows blank

### ISSUE THREAD

**Issue by Drillan767** [mozilla/geckodriver#1158]
## System
* Version: 0.19.1
* Platform: Windows 8.1
* Firefox: 58.0.1
* Selenium: 3.8.1 (what is a bind in this context?)

## Testcase

**behat.yml**

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  gherkin:
     cache: ~
  extensions:
    Behat\MinkExtension:
      base_url: http://www.website.rec
      goutte: ~
      selenium2:
        wd_host: http://localhost:4444/wd/hub
        capabilities: { "browserName": "firefox", "browser": "firefox", "version": "", "platform": "WINDOWS" }
      browser_name: firefox
    Drupal\DrupalExtension:
      blackbox: ~
```

**test.feature**

```
Feature: Some terse yet descriptive text of what is desired

 @javascript
  Scenario: Homepage is available
    Given I am on the homepage
    Then I should get a "200" HTTP response
    And I should see "ARTICLE LIST"
```

**FeatureContext.php**

```
<?php

use Drupal\DrupalExtension\Context\RawDrupalContext;
use Behat\Mink\Exception\ExpectationException;
use Behat\Behat\Context\SnippetAcceptingContext;
use Behat\Mink\Exception\ElementNotFoundException;
use DMore\ChromeDriver\ChromeBrowser;


/**
 * Defines application features from the specific context.
 */
class FeatureContext extends RawDrupalContext implements SnippetAcceptingContext {
  // Here go my custom functions
}
```

## Stacktrace

**stacktrace from selenium standalone server + gecko**

(both selenium standalone server and geckodriver are in the current directory)

> $ java -DWebdriver.gecko.driver=geckodriver.exe -jar selenium.jar

> 14:18:12.924 INFO - Selenium build info: version: '3.8.1', revision: '6e95a6684b'
> 14:18:12.924 INFO - Launching a standalone Selenium Server
> 2018-02-05 14:18:13.002:INFO::main: Logging initialized @281ms to org.seleniumhq.jetty9.util.log.StdErrLog
> 14:18:13.034 INFO - Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
> 14:18:13.049 INFO - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
> 14:18:13.049 INFO - Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
> 14:18:13.049 INFO - Driver class not found: com.opera.core.systems.OperaDriver
> 14:18:13.049 INFO - Using `new OperaOptions()` is preferred to `DesiredCapabilities.operaBlink()`
> 14:18:13.049 INFO - Using `new SafariOptions()` is preferred to `DesiredCapabilities.safari()`
> 14:18:13.049 INFO - Driver class not found: org.openqa.selenium.phantomjs.PhantomJSDriver
> 14:18:13.081 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
>  registration capabilities Capabilities {browserName: safari, platform: MAC, version: } does not match the current platform WIN8_1
> 14:18:13.112 INFO - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
> 14:18:13.112 INFO - Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
> 14:18:13.112 INFO - Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
> 14:18:13.126 INFO - Using `new OperaOptions()` is preferred to `DesiredCapabilities.operaBlink()`
> 14:18:13.126 INFO - Using `new SafariOptions()` is preferred to `DesiredCapabilities.safari()`
> 14:18:13.133 INFO - Using the passthrough mode handler
> 2018-02-05 14:18:13.146:INFO:osjs.Server:main: jetty-9.4.7.v20170914
> 2018-02-05 14:18:13.162:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@6950e31{/,null,STARTING} has uncovered http methods for path: /
> 2018-02-05 14:18:13.162:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@6950e31{/,null,AVAILABLE}
> 2018-02-05 14:18:13.240:INFO:osjs.AbstractConnector:main: Started ServerConnector@2fd66ad3{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
> 2018-02-05 14:18:13.240:INFO:osjs.Server:main: Started @517ms
> 14:18:13.240 INFO - Selenium Server is up and running
> 2018-02-05 14:18:23.781:INFO:osjshC.ROOT:qtp184966243-14: org.openqa.selenium.remote.server.WebDriverServlet-184f6be2: Initialising WebDriverServlet
> 14:18:23.812 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@7fadfff4
> 14:18:23.812 INFO - /session: Executing POST on /session (handler: BeginSession)
> 14:18:23.875 INFO - Capabilities are: Capabilities {browser: firefox, browserName: firefox, ignoreZoomSetting: false, marionette: false, name: Behat feature suite, platform: WINDOWS, tags: [64006A38B5DE, PHP 7.0.10], version: }
> 14:18:23.875 INFO - Capabilities {browser: firefox, browserName: firefox, ignoreZoomSetting: false, marionette: false, name: Behat feature suite, platform: WINDOWS, tags: [64006A38B5DE, PHP 7.0.10], version: } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.XpiDriverService)

**Stacktrace from Behat console**

>   @javascript
>   Scenario: Homepage is available
>     Given I am on the homepage
>        Given I am on "/" 
>      Could not open connection: Error forwarding the new session cannot find : Capabilities {browser: firefox, browserName: firefox, ignoreZoomSetting: false, marionette: false, name: Behat feature suite, tags: [64006A38B5DE, PHP 7.0.10]} (Behat\Mink\Exception\DriverException)

**(I hope this is what you're waiting for) Trace-level**

> $ java -Dwebdriver.gecko.driver=geckodriver.exe -jar selenium.jar -role node -hub http://localhost:4444/grid/register
> 17:50:29.376 INFO - Selenium build info: version: '3.8.1', revision: '6e95a6684b'
> 17:50:29.376 INFO - Launching a Selenium Grid node
> 2018-02-05 17:50:29.844:INFO::main: Logging initialized @687ms to org.seleniumhq.jetty9.util.log.StdErrLog
> 17:50:29.860 INFO - Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
> 17:50:29.876 INFO - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
> 17:50:29.876 INFO - Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
> 17:50:29.876 INFO - Driver class not found: com.opera.core.systems.OperaDriver
> 17:50:29.876 INFO - Using `new OperaOptions()` is preferred to `DesiredCapabilities.operaBlink()`
> 17:50:29.876 INFO - Using `new SafariOptions()` is preferred to `DesiredCapabilities.safari()`
> 17:50:29.876 INFO - Driver class not found: org.openqa.selenium.phantomjs.PhantomJSDriver
> 17:50:29.876 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
>  registration capabilities Capabilities {browserName: safari, platform: MAC, version: } does not match the current platform WIN8_1
> 17:50:29.907 INFO - Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
> 17:50:29.907 INFO - Using `new EdgeOptions()` is preferred to `DesiredCapabilities.edge()`
> 17:50:29.907 INFO - Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`
> 17:50:29.907 INFO - Using `new OperaOptions()` is preferred to `DesiredCapabilities.operaBlink()`
> 17:50:29.907 INFO - Using `new SafariOptions()` is preferred to `DesiredCapabilities.safari()`
> 17:50:29.907 INFO - Using the passthrough mode handler
> 2018-02-05 17:50:29.938:INFO:osjs.Server:main: jetty-9.4.7.v20170914
> 2018-02-05 17:50:29.954:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@3eb738bb{/,null,STARTING} has uncovered http methods for path: /
> 2018-02-05 17:50:29.954:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@3eb738bb{/,null,AVAILABLE}
> 2018-02-05 17:50:29.969:INFO:osjs.AbstractConnector:main: Started ServerConnector@d35dea7{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
> 2018-02-05 17:50:29.969:INFO:osjs.Server:main: Started @817ms
> 17:50:29.969 INFO - Selenium Grid node is up and ready to register to the hub
> 17:50:29.985 INFO - Starting auto registration thread. Will try to register every 5000 ms.
> 17:50:29.985 INFO - Registering the node to the hub: http://localhost:4444/grid/register
> 17:50:30.047 INFO - The node is registered to the hub and ready to use

Note : the error changed because it seems that I didn't start the servers (at least the hub and the node) properly, now it just returns an error (see Behat trace). Still, I have no idea how to make all of this works.

I already posted this question on StackOverflow, but didn't get much answer, so I'm trying my luck here

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by Drillan767** [comment]
@andreastt Edited my question, I deeply hope this is what you're waiting for

**Comment by whimboo** [comment]
This is not a trace level log. It actually looks identical to your first comment.

**Comment by whimboo** [comment]
@Drillan767 mind explaining why you closed the issue? Does it work now? What did you had to do to make it working? It would be good to know if a similar questions comes up later. Thanks.

**Comment by jboffel** [comment]
Well based on what I see above he tried to use a version of Firefox over 47 without marionette but this is not possible.
Normally you can disable eventually marionette protocol with Firefox and 3.0.0+ version of Selenium if your Firefox version is lower or equal to 47. The original driver in Firefox is dropped after that and so without marionette Selenium can't talk to Firefox...
