### ISSUE TITLE
Geckdriver(FIREFOX) issue WebDriverError: Unable to parse new session response using javascript language bindings

### ISSUE THREAD

**Issue by rakeshkmr516** [mozilla/geckodriver#1159]
## System
* Version: 1.10.0
* Platform:macOS 10.12.6
* Firefox: 58.0.1
* Selenium: 3.8.1

## Testcase
Launched the browser and navigate to Website 
Code 
const firefox = require('selenium-webdriver/firefox');
			options = new firefox.Options();
			//driver = driver.setFirefoxOptions(options);
			driver = new webdriver.Builder().withCapabilities(options.toCapabilities()).build();

## Stacktrace
WebDriverError: Unable to parse new session response: {"value": {"sessionId":"c55a8e2f-99c1-ae41-bc82-1e39a6dd3f41","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"58.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":8511,"moz:profile":"/var/folders/r6/xqkgw_cj0vs_x5wmf_zhss2w0000gp/T/rust_mozprofile.V7xmEGfqm3xP","moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.7.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by rakeshkmr516** [comment]
WebDriverError: Unable to parse new session response: {"value": {"sessionId":"c55a8e2f-99c1-ae41-bc82-1e39a6dd3f41","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"58.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":8511,"moz:profile":"/var/folders/r6/xqkgw_cj0vs_x5wmf_zhss2w0000gp/T/rust_mozprofile.V7xmEGfqm3xP","moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.7.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:445:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:777:24)
      at Function.createSession (node_modules/selenium-webdriver/firefox/index.js:640:55)
      at createDriver (node_modules/selenium-webdriver/index.js:167:33)
      at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
      at runTest (node_modules/selenium-webdriver/testing/index.js:166:22)
      at node_modules/selenium-webdriver/testing/index.js:187:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1067:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:186:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2860:25)
      at node_modules/selenium-webdriver/lib/promise.js:676:7

**Comment by andreastt** [comment]
That’s not a trace-level log (read more about it in [CONTRIBUTING.md](https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md)), but it looks like the problem here is that your Selenium client doesn’t understand the WebDriver conform return value from geckodriver.

Are you sure you’re using the latest Selenium client?

**Comment by rakeshkmr516** [comment]
Thank you @andreastt working with 3.6.0 and gecko 1.10.0 versions

**Comment by whimboo** [comment]
`darwin` is not an allowed platform name but `mac` is. I assume because of that the creation of the new session fails.
