### ISSUE TITLE
geckodriver release should be executable

### ISSUE THREAD

**Issue by lukeis** [mozilla/geckodriver#116]
curl -L https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-OSX.gz
gunzip geckodriver-0.8.0-OSX.gz
ls -l geckodriver-0.8.0-OSX

geckodriver-0.8.0-OSX  should be +x

I know your documentation says to make it executable, I'm requesting that you change that so it already is executable when a user gunzip's the file.

**Comment by andreastt** [comment]
Gunzipped files cannot contain file permissions, only archives can.

That said, we will use archives in the next release as laid out in https://github.com/mozilla/geckodriver/pull/83 for exactly this reason.

**Comment by lukeis** [comment]
:+1: thanks Andreas!
