### ISSUE TITLE
Windows 10 +geckodriver 0.19 + python : directory to keep the geckodriver?

### ISSUE THREAD

**Issue by amit2rockon** [mozilla/geckodriver#1160]
Please mention the directory in windows os, where should i keep the geckodriver ? I am getting  message 'geckodriver' executable needs to be in PATH .  and in sys.platform ==win32,

**Comment by andreastt** [comment]
You can keep geckodriver in any directory you’d like, as long as that directory is included in the system path.

**Comment by amit2rockon** [comment]
by default where should i keep it so that it can generalised ?

**Comment by andreastt** [comment]
I don’t understand the question. You need to put it in a directory that is included in the system path list. See https://www.computerhope.com/issues/ch000549.htm for more info.

**Comment by amit2rockon** [comment]
Thanks :)

**Comment by andreastt** [comment]
On Unix you would typically modify the colon separated `PATH` environment variable, as such:

    % export PATH=/path/to/folder/including/geckodriver:$PATH
    % geckodriver
    Listening on 127:0.0.1:4040...

**Comment by amit2rockon** [comment]
i am not facing any problem with Unix but . even putting the driver in system directory it is giving the same error , os.path.basename(self.path), self.start_error_message)  selenium.common.exceptions.webdriverexception: Message: 'geckodriver' executable needs to be in PATH

**Comment by whimboo** [comment]
Please also see issue #177 in how to set it through Selenium directly. 

Also you haven't given any source code in how you are trying to run the test. There is nothing else we can tell unless you offer that.

**Comment by amit2rockon** [comment]
Thanks for your response sir,  @marco-c has helped me in resolving this problem.
