### ISSUE TITLE
Script fails when triggered from other machine 

### ISSUE THREAD

**Issue by craab220** [mozilla/geckodriver#1161]
## System
* Version: 0.19.1
* Platform: Windows Server 2012 R2 Standard (64bit)
* Firefox: 58.0.1
* Splinter: 0.7.7

## Testcase
Script works fine when triggered by user locally or remotely logged onto host, but not when called from another machine.

from splinter import Browser
import time
browser = Browser('firefox', profile=r'C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\0r9gezm5.default')
browser.visit('https://confluence.com')
browser.find_by_id('login-link').click()
browser.fill('os_username', 'user')
browser.fill('os_password', 'pass')
browser.find_by_name('login').click()
with open ("C:\Webscraping\Download List\Contacts.txt") as sheet:
for website in sheet:
    browser.visit(website)
    browser.find_by_id('action-menu-link').click()
    browser.find_by_id('action-export-pdf-link').click()

## Stacktrace

Traceback (most recent call last):
    File "\\host\c$\Webscraping\Scripts\Contacts.py", line 6, in <module>
        browser = Browser('firefox', profile=r'C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\0r9gezm5.default')
File "C:\Anaconda2\lib\site-packages\splinter\browser.py", line 63, in Browser
        return driver(*args, **kwargs)
File "C:\Anaconda2\lib\site-packages\splinter\driver\webdriver\firefox.py", line 57, in __init__
    timeout=timeout, **kwargs)
File "C:\Anaconda2\lib\site-packages\selenium\webdriver\firefox\webdriver.py",
    line 158, in __init__
        keep_alive=True)
File "C:\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py",
    line 154, in __init__
        self.start_session(desired_capabilities, browser_profile)
File "C:\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py",
    line 243, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
File "C:\Anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py",
    line 312, in execute
        self.error_handler.check_response(response)
File "C:\Anaconda2\lib\site-packages\selenium\webdriver\remote\errorhandler.py
    ", line 237, in check_response
        raise exception_class(message, screen, stacktrace)
        selenium.common.exceptions.WebDriverException: Message: connection reset

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by craab220** [comment]
Script does not create geckodriver.log even after following setup instructions.

**Comment by whimboo** [comment]
Then it's a problem with the used binding or wrapper tool around Selenium. Talk with the maintainers of that tool in how to store a trace level log.

**Comment by whimboo** [comment]
There is nothing we can do for this issue unless the trace log is provided.
