### ISSUE TITLE
Nothing happens when clicked on geckodriver.exe

### ISSUE THREAD

**Issue by camzzzz** [mozilla/geckodriver#1162]
## System
* Version: 0.19.0
* Platform: Windows 10
* Firefox: 58.0.1 (64 bit)
* Selenium: 3.9

## Testcase

when I try to run geckodriver.exe, black screen appears and this is what I get:

1517973682027      geckodriver      INFO     geckodriver 0.19.1
1517973682036      geckodriver      INFO     Listening on 127.0.0.1:4444

after this, nothing happens...

**Comment by cgoldberg** [comment]
what are you expecting to happen?
It is listening and waiting for requests.

**Comment by andreastt** [comment]
As Corey said, geckodriver is an HTTP server so you need to use an HTTP client to interact with it. Many clients that support geckodriver are found in Selenium.
