### ISSUE TITLE
Move the sessionId property to the top level in responses

### ISSUE THREAD

**Issue by nesk** [mozilla/geckodriver#1166]
## System
* Version: 0.19.1
* Platform: macOS 10.13.2
* Firefox: 58.0.1
* Selenium: _Not using it_

## Testcase

Run the web driver:

```shell
geckodriver -p 9515
```

Start a new session:

```shell
curl -X "POST" "http://localhost:9515/session" -H 'Content-Type: application/json' -d '{"desiredCapabilities": {"platform": "ANY", "browserName": "firefox"}}'
```

The response contains:

```javascript
{
    "value": {
        "sessionId": "6fb60b10-f7fb-544c-9ebb-ae460e5fc571",
        "capabilities": {
            // ...
        }
    }
}
```

While the specification states:

<blockquote>
<p>Let <var>body</var> be a JSON Object initialised with:</p>
<dl>
<dt><code>sessionId</code></dt>
<dd><var>session id</var></dd>
<dt><code>capabilities</code></dt>
<dd><var>capabilities</var></dd>
</dl>
</blockquote>

`sessionId` should be a top-level property, thus the response should be:

```javascript
{
    "sessionId": "6fb60b10-f7fb-544c-9ebb-ae460e5fc571",
    "value": {
        "capabilities": {
            // ...
        }
    }
}
```

**Comment by andreastt** [comment]
You are likely expecting the response format to be the Selenium JSON wire protocol, but geckodriver implements the [WebDriver standard](https://w3c.github.io/webdriver/webdriver-spec.html).

**Comment by nesk** [comment]
@andreastt I forgot to link the specification, but my citation comes from the WebDriver standard, the same document you linked: https://w3c.github.io/webdriver/webdriver-spec.html#new-session

And it states that the `sessionId` property should be at top level. Chrome and Safari drivers already do that.

**Comment by nesk** [comment]
>The body is a JSON Object and has a field named "value" whose value is an object bearing three, and sometimes four, fields

Okay, I've didn't see that, my bad. 😅

**Comment by andreastt** [comment]
I somewhat suspect that the driver implementations for Chrome and Safari are not conforming to the WebDriver protocol yet.

**Comment by nesk** [comment]
That's what I think too. Thank you for your help!
