### ISSUE TITLE
Selenium automation receiving java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by studiospeaker** [mozilla/geckodriver#1167]
## System
* Version: 0.19.1
* Platform: Windows 7 Enterprise 64 bit
* Firefox: 58.0.2 (64-bit)
* Selenium: 3.9.0

## Testcase
Executing selenium automation test script.

## Stacktrace
org.openqa.selenium.WebDriverException: java.net.SocketTimeoutException: Read timed out
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:26:55.441Z'
System info: host: 'WKS20144', ip: '10.80.14.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_162'
Driver info: driver.version: FirefoxDriver

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by studiospeaker** [comment]
Stacktrace is attached for SocketTimeoutException. Thank you.

[StackTrace_SocketTimeoutException_020818.docx](https://github.com/mozilla/geckodriver/files/1708901/StackTrace_SocketTimeoutException_020818.docx)

**Comment by whimboo** [comment]
@studiospeaker this is not a trace log. Please read the instructions again. Thanks.

**Comment by studiospeaker** [comment]
1) I updated to the new Selenium WebDriver 3.9.1 and it resolved the issue.
2) Next time I will generate the trace log, based on the commands you have provided. Sorry, I took the output from the console.
3) I am closing this issue. Thank you for your help and your comments!
