### ISSUE TITLE
Geckodriver unable to run on windows 7 looking for VCRUNTime140.dll file

### ISSUE THREAD

**Issue by shashisd** [mozilla/geckodriver#117]
OS: windows 7
Description:When trying to execute geckodriver from command line getting error in launching.
Steps to reproduce:
1) Open command prompt
2) Type the geckodriver.exe path and hit enter getting the error VCRUNTIME.dll missing.
Please provide the VCRUNTIME.dll for running selenium on windows.

**Comment by andreastt** [comment]
Resolved by https://github.com/mozilla/geckodriver/pull/73. This will be fixed in the next release.
