### ISSUE TITLE
Interacting with driver clears open modal

### ISSUE THREAD

**Issue by elliterate** [mozilla/geckodriver#1171]
This is true whether you're trying to navigate away or simply query for elements.

## System
* Version: 0.19.1
* Platform: macOS 10.11.6
* Firefox: 59.0b8; 60.0a1 (passes with 58.0.2)
* Selenium: py/3.9.0

### `test_handle_alert.py`

```python
import inspect
import os.path
from time import sleep
from unittest import TestCase, main

from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


_DIR = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

def _get_fixture_url(filename):
    return "file://{}".format(os.path.join(_DIR, filename))


class TestHandleAlert(TestCase):
    @classmethod
    def setUpClass(cls):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["marionette"] = True
        capabilities["unexpectedAlertBehaviour"] = "ignore"
        capabilities["moz:firefoxOptions"] = {"log": {"level": "trace"}}
        cls.driver = webdriver.Firefox(capabilities=capabilities)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        
    def test_querying_while_an_alert_exists(self):
        self.driver.get(_get_fixture_url("with_alert.html"))
        self.assertIn("This page has an inline alert.",
            self.driver.find_element_by_tag_name("p").text)

        self.driver.find_element_by_link_text("Hello?").click()

        with self.assertRaises(UnexpectedAlertPresentException):
            self.driver.get(_get_fixture_url("other.html"))

        self.driver.switch_to.alert.accept()
        self.driver.get(_get_fixture_url("other.html"))

        sleep(0.25)
        self.assertIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)


if __name__ == "__main__":
    main()
```

### `with_alert.html`

```html
<html>
  <body>
    <p>This page has an inline alert.</p>
    
    <a href="#" onclick="alert('Boo!')">Hello?</a>
  </body>
</html>

```

### `other.html`

```html
<html>
  <body>
    <p>This is some other page.</p>
  </body>
</html>
```

## Stacktrace

```
$ python test_handle_alert.py
E
======================================================================
ERROR: test_querying_while_an_alert_exists (__main__.TestHandleAlert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_handle_alert.py", line 40, in test_querying_while_an_alert_exists
    self.driver.switch_to.alert.accept()
  File "/Users/ian/.pyenv/versions/2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/Users/ian/.pyenv/versions/2.7.9/lib/python2.7/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/Users/ian/.pyenv/versions/2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/ian/.pyenv/versions/2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoAlertPresentException: Message: No modal dialog is currently open


----------------------------------------------------------------------
Ran 1 test in 5.134s

FAILED (errors=1)
```

## Trace-level log

[geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1713069/geckodriver.log.txt)

**Comment by elliterate** [comment]
For context, this is especially troublesome when you can't know whether the page uses an unload alert, as [when capybara-py attempts to reset the browser between tests][1]. capybara-py attempts to:

1. navigate to "about:blank" and then
2. verify that it arrived by polling the body until it sees that it's empty.

If the navigation triggers an unload alert, the verification check will fail because of the unexpected modal. But, with the behavior reported above, the verification check will also inadvertently _clear_ the modal and cancel the navigation.

[1]: https://github.com/elliterate/capybara.py/blob/7f1b54b4ceb4f60db401ba0ebc94fc4230ee89db/capybara/selenium/driver.py#L165-L196

**Comment by cgoldberg** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1264259

**Comment by elliterate** [comment]
For further context, this [worked at the beginning of January][1] and [no longer worked at the end of January][2] (both times on v0.18.0). That, along with the fact that this works on Firefox 58.0.2, leads me to suspect this is a recent regression in Firefox.

[1]: https://travis-ci.org/elliterate/capybara.py/jobs/324711071
[2]: https://travis-ci.org/elliterate/capybara.py/jobs/334983247

**Comment by whimboo** [comment]
Yes, that was an expected change as landed by @AutomatedTester for Firefox 59 via https://bugzilla.mozilla.org/show_bug.cgi?id=1416284.

**Comment by AutomatedTester** [comment]
This is expected and aligns Geckodriver with the other drivers

**Comment by AutomatedTester** [comment]
since this issue is talking about https://bugzilla.mozilla.org/show_bug.cgi?id=1416284 and not https://bugzilla.mozilla.org/show_bug.cgi?id=1264259 let's not conflate issues by reopening it.
