### ISSUE TITLE
For input[type=file], should allow sendKeys even when display=none

### ISSUE THREAD

**Issue by kerrykimbrough** [mozilla/geckodriver#1173]
Issue #1150 was dismissed prematurely. This is a real problem that needs fixing. ChromeDriver got it right.

I understand the principle of WebDriver imitating human interaction. But file input is a special case that is the exception to this rule. That's because it is practically impossible for a Selenium test to simulate interaction with the OS-level file browser that pops up. Using `sendKeys` to the `input` element is the time-honored work-around for this situation.

It's especially important to preserve this work-around regardless of `display` state, because modern JavaScript-centric UI styles *always* keep the ugly raw HTML input field hidden.

## System
* Version: 0.19.1
* Platform: Mac OS X 10.10.5
* Firefox: 58.0.2
* Selenium: 3.8.1

## Testcase

Same as issue #1150 

## Stacktrace

Same as issue #1150 

## Trace-level log

Same as issue #1150

**Comment by andreastt** [comment]
It is not impossible for a UA to simulate interaction with a file upload control from a web platform perspective, since all the right DOM events get fired. I fail to see the relevance this has on the argument.

Your second point about JS frameworks _hiding_ the control and instead favours indirection via a “prettier” UX is more interesting. Can you provide a reduced, preferably self-contained, example of this?

If geckodriver were to always treat `<input type=file style="display: none">` as keyboard interactable, a specification change will be required. Do you mind filing a bug against the [WebDriver standard](https://github.com/w3c/webdriver)? At the moment I can’t think of a better solution than to treat the element as always-interactable, unless there is a way we can detect that interaction with something else will trigger manipulation of the form control.

**Comment by kerrykimbrough** [comment]
> It is not impossible for a UA to simulate interaction with a file upload control from a web platform perspective

My concern is from the perspective of a WebDriver API client. But you know the standard better than I, so perhaps it is not impossible. Can you show me a snippet of code that uses WebDriver to recognize a file upload control and use it to set the value of an `input[type=file]` element? *And* is guaranteed to work with all standard-compliant WebDriver implementations on all Web apps?

> Your second point about JS frameworks hiding the control and instead favours indirection via a “prettier” UX is more interesting.

I didn't mean to imply that JS frameworks hide these controls. I'm simply saying raw `input[type=file]` controls are not compatible with the visual style preferred by builders and consumers of modern Web apps. So apps don't use them, and WebDriver test programs have to deal with that.

**Comment by AlexanderArendar** [comment]
@andreastt  the thing is we, QA engineers, need to be able to automate use cases where file upload is needed. And the other thing is that a lot of webapps nowadays are implemented with Angular and other "JS frameworks" which often set visibility of the html input to hidden.
But this should nevertheless be an obstacle and a reason for geckodriver to not support what works let's say in chromedriver.
Regarding specification: probably it restricts, but if the implementation of webdriver for Firefox is not able to support file-upload test case then you will have less community support. At the moment I just commented tests which run on Firefox because file upload is not working, and use tests for other browsers.

**Comment by andreastt** [comment]
I’ve filed https://github.com/w3c/webdriver/issues/1230 against the specification.

**Comment by AlexanderArendar** [comment]
Thanks a lot. And sorry if I was sounding too demanding.
Will it help if I provide you with the piece of HTML markup? I cannot provide access to the QA environment which I work in, unfortunately, because it has sensitive data. But can provide some stripped HTML and screenshots from developer tools in Firefox which will show input element attributes.

**Comment by AlexanderArendar** [comment]
This is the part of HTML view where the file upload input is decorated by Angular JS stuff.
```
<!--Event logo -->
<div class="form-group">
    <label>Logo</label>
    <upload-file ng-model="vm.link.logo" ng-files="{&quot;id&quot;:43,&quot;link&quot;:&quot;https://stripped.domain/files-qa/74394e8b-eca8-42da-ac90-fd1b323cd0eb-testlogo.png&quot;}" class="ng-pristine ng-untouched ng-valid ng-isolate-scope ng-empty" aria-invalid="false">
        <div>
            <label class="btn btn-outline-primary btn-upload" ng-hide="files.length >= max" ng-disabled="disabled" aria-hidden="false" aria-disabled="false">
                <input ng-disabled="disabled" multiple="" type="file">
                <i class="glyphicon glyphicon-download-alt"></i>
                <span ng-bind="title || 'Upload image'" class="ng-binding">Upload image</span>
            </label>
            <!-- ngIf: type == 'file' -->
            <!-- ngIf: type != 'file' -->
            <div class="photo-preview ng-scope" ng-if="type != 'file'">
                <!-- ngIf: spinerLoader -->
                <!-- ngIf: !multiple && files.length != 0 -->
                <div class="photo-preview-item ng-scope photo-preview-item-single" ng-class="{'photo-preview-item-single': !multiple}" ng-if="!multiple &amp;&amp; files.length != 0">
                    <div class="inner">
                        <img ng-src="https://stripped.domain/files-qa/74394e8b-eca8-42da-ac90-fd1b323cd0eb-testlogo.png" alt="" src="https://stripped.domain/files-qa/74394e8b-eca8-42da-ac90-fd1b323cd0eb-testlogo.png">
                    </div>
                </div>
                <!-- end ngIf: !multiple && files.length != 0 -->
                <!-- ngRepeat: file in files track by $index -->
                <!-- ngIf: multiple && files.length != 0 -->
                <!-- end ngRepeat: file in files track by $index -->
                <!-- ngIf: multiple && files.length != 0 -->
                <!-- end ngRepeat: file in files track by $index -->
            </div>
            <!-- end ngIf: type != 'file' -->
        </div>
    </upload-file>
</div>
```
Also as you can see from the screenshot attached, the visibility of the input is hidden.
![hidden_file_input](https://user-images.githubusercontent.com/3185653/36486599-84d84c1a-1727-11e8-952e-ef8861fd8e36.png)

**Comment by chaseholdren** [comment]
I am also running into this problem. We hide the file input and style a label for it, because it is better to style. I think this is pretty common. It's now impossible for us to simulate uploads unless we change all our tests to unhide the raw file input button first.

**Comment by waterlink** [comment]
@chaseholdren thank you for "display = block" workaround!

**Comment by vsravuri** [comment]
I'm also running into this issue. It's works fine in all versions of Chrome and until Firefox 57. Not sure what has changed from Firefox 58 onwards. My test case is to simulate drag & drop a file in CKEditor DropZone.js plugin. 

Protractor: 5.3.1
Selenium: 3.11.0
Mac OS X 10.13.4

Appreciate any workaround to overcome this issue.

**element <input class="dz-hidden-input" type="file"> is not reachable by keyboard**

**HTML Code**
<input type="file" class="dz-hidden-input" accept="image/jpeg,image/gif,image/png" style="visibility: hidden; position: absolute; top: 0px; left: 0px; height: 0px; width: 0px;">

**Comment by whimboo** [comment]
@vsravuri with Firefox 58 we turned on WebDriver specific interactability checks. Can you please turn it off and see if that works? See https://github.com/mozilla/geckodriver/#mozwebdriverclick.

**Comment by lennylucas** [comment]
I have same issue but unfortunately setting 'moz:webdriverClick' did not work for me.  sendKeys() on input type file does not populate file at all, regardless of whether it's hidden or not.  Am using  nodejs with

node - v8.11.3
selenium-webdriver - 4.0.0-alpha.1
geckodriver - v0.21.0
firefox - 60.0.2
Ubuntu - 16.04.3

sample code:

```
const opts = new firefox.Options();
const caps = new webdriver.Capabilities();
caps.set('moz:webdriverClick', false);
caps.setBrowserName('firefox');
this.browser = new webdriver.Builder().setFirefoxOptions(profile).withCapabilities(caps);
...
this.browser.findElement(By.name('file')).sendKeys(file);
```

**Comment by whimboo** [comment]
@lennylucas please do not hi-jack unrelated issues then. Instead file a new issue please with all the requested details included. Once done, please remove your comment here. Thanks.

**Comment by shreyanshp** [comment]
@whimboo  Thanks man, it works now!

Do you have any timeline on when this temporary capability will be deprecated?

**Comment by whimboo** [comment]
We will not remove the capability as long as there are outstanding spec issues to solve which prevent using interactability checks everywhere.

**Comment by surajkakode** [comment]
kindly send the code, how to do same in JAVA.

**Comment by Seijan** [comment]
I have the same issue, as the file upload can't be interacted with, as it has no style or anything. I tried to use the solution from @chaseholdren but this didn't work for me, as the issue stays the same. So any further tipps or work that has be done on this issue would help.

**Comment by shreyanshp** [comment]
@Seijan Try setting 'moz:webdriverClick': false. Tested in Firefox 59+
 More - https://github.com/mozilla/geckodriver/#mozwebdriverclick

**Comment by fedealdosivi** [comment]
@shreyanshp Have the same issue, and It worked that solution. Tested in Firefox 60

**Comment by thanhhqq** [comment]
> @shreyanshp I had the same issue, and It worked that solution. Tested in Firefox 60

I dont know how to configure?
I tried setting like this (with C#) but still not working. Please, help me!
FirefoxOptions options = new FirefoxOptions();
options.AddAdditionalCapability("moz:webdriverClick", false);

**Comment by erichulburd** [comment]
Another option is to use opacity, position or width CSS properties to hide the file input as suggested on Mozillas dev page:

```
Note: opacity is used to hide the file input instead of visibility: hidden or display: none, because assistive technology interprets the latter two styles to mean the file input isn't interactive.
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by andreastt** [comment]
The Browser Tools and Testing WG has adopted to change the specification behaviour so that Firefox can reach compatibility with Chrome, see https://github.com/w3c/webdriver/issues/1230#issuecomment-433906729 for the full details.

I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1502864 to carry through with the first set of those changes in Firefox.

**Comment by XXN** [comment]
The same issue there. Even more, can't use neither `sendKeys `or `click` even on a **visible** (non-hidden) input[type=file]!

Version: 0.23.0 (also on 0.19.1)
Platform: Win 7 Ultimate
**Tor Browser** 8.0.4 (based on Mozilla Firefox 60.4.0esr Quantum) 
Selenium: 3.141.0

![2019-01-24_215615](https://user-images.githubusercontent.com/2727724/51705013-20569480-2023-11e9-834b-7f45d1174e8a.png)

**Comment by XXN** [comment]
The same issue there. Even more, can't use neither `sendKeys `or `click` even on a **visible** input[type=file]!

Version: 0.23.0 (also on 0.19.1)
Platform: Win 7 Ultimate
**Tor Browser** 8.0.4 (based on Mozilla Firefox 60.4.0esr Quantum) 
Selenium: 3.141.0

![2019-01-24_215615](https://user-images.githubusercontent.com/2727724/51705013-20569480-2023-11e9-834b-7f45d1174e8a.png)

**Comment by twalpole** [comment]
@XXN Nothing in that image proves the file input is actually visible.

**Comment by whimboo** [comment]
Guys, please stop commenting on this issue if your input is not hidden. Instead file a new issue for investigation, and importantly provide all the information as requested. Images don't help at all.

**Comment by amit210001** [comment]
DesiredCapabilities dc = new DesiredCapabilities();
			dc.setCapability("strictFileInteractability", true);
	 		FirefoxOptions opt = new FirefoxOptions();
	 		opt.merge(dc);
	 		driver = new FirefoxDriver(opt)		
			driver = new FirefoxDriver();
i am using send keys to upload file with gecko driver 0.24.0 which supports file upload through send keys but as per log mssg it is not set
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 67.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190516215225, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 14448, moz:profile: C:\Users\userName\AppDat..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, **strictFileInteractability: false**, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}

**Comment by amit210001** [comment]
> ```
>                    DesiredCapabilities dc = new DesiredCapabilities();
> 		dc.setCapability("strictFileInteractability", true);
>  		FirefoxOptions opt = new FirefoxOptions();
>  		opt.merge(dc);
>  		driver = new FirefoxDriver(opt)		
> 		driver = new FirefoxDriver();
> ```
> 
> i am using send keys to upload file with gecko driver 0.24.0 which supports file upload through send keys but as per log mssg it is not set
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 67.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190516215225, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 14448, moz:profile: C:\Users\userName\AppDat..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, **strictFileInteractability: false**, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}

It's look like we can upload all files available underneath the folder path ,we have to upload the file one by one , is it correct ?

**Comment by whimboo** [comment]
@amit210001 this is a closed issue. If you have problems please create a new issue, and provide all the required details including the trace level logs.
