### ISSUE TITLE
Unable To Create A New Session When I Configure A Session With Proxy Configuration

### ISSUE THREAD

**Issue by bhreinb** [mozilla/geckodriver#1174]
## System
* Version: geckodriver-v0.19.1
* Platform: Linux Centos7
* Firefox: Firefox59 (http://releases.mozilla.org/pub/firefox/releases/59.0b8/)
* Selenium: 3.9.1

## Testcase

```
"proxy": {
	 proxyType: 'manual',
         httpProxy: 'localhost:3128'
}
```

## Stacktrace

[12:37:23] W/launcher - Ignoring uncaught error WebDriverError: httpProxyPort is not a valid proxy configuration capability
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'
System info: host: 's1wfadvcilvm08', ip: '172.16.184.183', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.11.6.el7.x86_64', java.version: '1.8.0_151'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x4e9586 - webdriver::error::WebDriverError::new::hee9ff9dd0a444441
   3:           0x4ddb66 - webdriver::capabilities::SpecNewSessionParameters::validate_proxy::h3387fbc10633c5eb
   4:           0x436c1a - <&'a mut I as core::iter::iterator::Iterator>::next::hbb01b33ace84bf9d
   5:           0x4414c5 - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   6:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   7:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   8:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   9:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  10:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
  11:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84

## Trace-level log
Unable to get trace logs via protractor

Hi there,

As briefly mentioned in the following ticket 

`https://github.com/mozilla/geckodriver/issues/996`

I have been unable to pass proxy config to firefox on Centos7 using the above build lineup. I'm constantly getting the above exception been thrown no matter what combinations I try...some combinations I have tried are listed below...

```
"proxy": {
	 proxyType: 'manual',
         httpProxy: 'localhost:3128',
         httpProxyPort: '3128'
}
```

whenever I remove httpProxy or httpProxyPort firefox starts up but anytime they are in the payload firefox fails to start. Can somebody help with this as I spent the a few hours trying to get this working and I'm adhering to the guide here re setting the proxy on the firefox driver https://github.com/mozilla/geckodriver#proxy-object
Many thanks in advance.

**Comment by whimboo** [comment]
As the error says `httpProxyPort` is not supported and as it looks like Protractor somehow injects that key when you specify `httpProxy`. 

So this should be a Protractor issue, and you might want to get in contact with their support. Also without a trace log it's hard to give the full answer. Maybe try to start geckodriver yourself via `geckodriver -vv`, and let Protractor connect to this geckodriver instance.

I will close this issue as invalid.
