### ISSUE TITLE
UnsupportedOperationError: sendKeysToActiveElement with sendkeys

### ISSUE THREAD

**Issue by bsarkadi** [mozilla/geckodriver#1179]
## System

* Version: 0.19.1
* Platform: win7
* Firefox: 58.0.2 (64-bit)
* Selenium: standalone 3.9.1 used with Protractor 5.3.0

I'm getting UnsupportedOperationError: sendKeysToActiveElement when using sendkeys in Protractor.
The same test cases run flawlessly in Chrome, but fail in Firefox.

## Stacktrace

  Message:
    UnsupportedOperationError: sendKeysToActiveElement
    Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:2
8.403Z'
    System info: host: 'HU00043009', ip: '192.168.56.1', os.name: 'Windows 7', o
s.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
    Driver info: driver.version: unknown
  Stack:
    UnsupportedOperationError: sendKeysToActiveElement
    Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:2
8.403Z'
    System info: host: 'HU00043009', ip: '192.168.56.1', os.name: 'Windows 7', o
s.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
    Driver info: driver.version: unknown

**Comment by andreastt** [comment]
I don’t know what `sendKeysToActiveElement` is, but I’m willing to bet that the client or middleware that you’re using doesn’t support the W3C WebDriver standard yet. Chrome will work in this case because it isn’t spec conforming.

It would be easier to tell what exactly is wrong if you could attach a trace-level log.

**Comment by bsarkadi** [comment]
Thanks for your answer.
Unfortunately, I couldn't make trace-level logs with this Protractor-based set-up.
However, as I understand the issue is with Selenium server then.

**Comment by andreastt** [comment]
It’s hard to tell unless you provide a [trace-level log]. Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by AutomatedTester** [comment]
This is an issue with the bindings that you are using. There should be a little shim in the bindings that make sure the same functionality is given on older commands that have been removed. This issue will appear when chrome switch over to W3C support. This has been implemented in the core selenium binding, a python example at https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/action_chains.py#L343-L356

**Comment by bsarkadi** [comment]
As I understand Protractor is a wrapper around the Selenium JS binding. So the issue is with the Selenium JS binding then?

**Comment by andreastt** [comment]
That would be my guess! It’s hard to tell without a link to the source code of said client. Happy to have a look if you know where I can find it.

**Comment by bsarkadi** [comment]
Thanks! I guess this will be it:
https://github.com/SeleniumHQ/selenium/tree/master/javascript/webdriver

**Comment by andreastt** [comment]
I don’t think that particular client is a client-to-server implementation, as it seems to be coded to talk to the Selenium server.
