### ISSUE TITLE
Download link format for OSX and Windows are different

### ISSUE THREAD

**Issue by smccarthy** [mozilla/geckodriver#118]
OSX : https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-0.8.0-OSX.gz
Windows : https://github.com/mozilla/geckodriver/releases/download/v0.8.0/geckodriver-v0.8.0-win32.zip

Windows has the filename of geckodriver-v{VERSION}-{OS}.zip
OSX and Linux are : geckodriver-{VERSION}-{OS}.gz (no v before VERSION).

I noticed this when adding an auto upgrader for GeckoDriver to Selenium-Grid-Extras.

**Comment by jgraham** [comment]
The next version will be released with the travis based setup, which should normalize these filenames [c.f. https://github.com/mozilla/geckodriver/blob/master/ci.sh#L106]
