### ISSUE TITLE
Zombie unload alert after dismissed clickElement followed by dismissed get

### ISSUE THREAD

**Issue by elliterate** [mozilla/geckodriver#1181]
Given a page with an unload alert, when a `clickElement` navigation is dismissed, a subsequent `get` navigation that is also dismissed results in a zombie alert that cannot be seen via the Selenium API yet inhibits navigation:

1. Use `WebElement#click()` on an element that triggers a navigation.
2. Dismiss the unload alert.
3. Use `WebDriver#get()` to trigger a navigation.
4. Dismiss the unload alert.

   *(The unload alert is now a zombie, visible in the GUI.)*

6. Use `WebDriver#get()` to trigger a navigation.
7. Accept or dismiss the unload alert.

   *(The zombie alert is still visible in the GUI.)*

At this point, regardless of whether the third alert was accepted or dismissed, the browser is still on the original page and subsequent driver interactions do not raise an unexpected alert error.

## System
* Version: 0.19.1
* Platform: macOS 10.12.6
* Firefox: 59.0b8; 60.0a1
* Selenium: py/3.9.0

### `test_handle_unload_alert.py`

```python
import inspect
import os.path
import pytest
from unittest import TestCase, main

from selenium import webdriver
from selenium.common.exceptions import NoAlertPresentException, UnexpectedAlertPresentException
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


_DIR = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

def _get_fixture_url(filename):
    return "file://{}".format(os.path.join(_DIR, filename))


class TestHandleUnloadAlert(TestCase):
    @classmethod
    def setUpClass(cls):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["marionette"] = True
        capabilities["moz:firefoxOptions"] = {"log": {"level": "trace"}}
        cls.driver = webdriver.Firefox(capabilities=capabilities)

    def setUp(self):
        self.driver.get(_get_fixture_url("with_unload_alert.html"))

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    # ...

    def _click_with_unload_alert_dismissal(self):
        self.driver.find_element_by_link_text("Go away").click()

        self.driver.switch_to.alert.dismiss()

        # Navigation canceled
        self.assertNotIn("This is a landing page.",
            self.driver.find_element_by_tag_name("p").text)

    # ...

    def _get_with_unload_alert_acceptance(self):
        self.driver.get(_get_fixture_url("other.html"))

        self.driver.switch_to.alert.accept()

        # Navigation completed
        self.assertIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)

    def _get_with_unload_alert_dismissal(self):
        self.driver.get(_get_fixture_url("other.html"))

        self.driver.switch_to.alert.dismiss()

        # Navigation canceled
        self.assertNotIn("This is some other page.",
            self.driver.find_element_by_tag_name("p").text)

    # ....

    def test_click_with_dismissal_then_get_with_dismissal_then_get_with_acceptance(self):
        self._click_with_unload_alert_dismissal()
        self._get_with_unload_alert_dismissal()
        self._get_with_unload_alert_acceptance()

    def test_click_with_dismissal_then_get_with_dismissal_then_get_with_dismissal(self):
        self._click_with_unload_alert_dismissal()
        self._get_with_unload_alert_dismissal()
        self._get_with_unload_alert_dismissal()


if __name__ == "__main__":
    main()
```

(Complete set of tested combinations: [test_handle_unload_alert.py.txt](https://github.com/mozilla/geckodriver/files/1731697/test_handle_unload_alert.py.txt))

### `with_unload_alert.html`

```html
<html>
  <head>
    <script>
        window.onbeforeunload = function(e) {
          return 'Unload?';
        };
    </script>
  </head>
  <body>
    <p>This triggers an alert on unload</p>

    <a href="landing.html">Go away</a>
  </body>
</html>
```

### `landing.html`

```html
<html>
  <body>
    <p>This is a landing page.</p>
  </body>
</html>
```

### `other.html`

```html
<html>
  <body>
    <p>This is some other page.</p>
  </body>
</html>
```

## Stacktrace

When the second unload alert (the first triggered by `WebDriver#get()`) is dismissed, it remains visible in the GUI:

![zombie.png](https://user-images.githubusercontent.com/6326/36285967-966a7bca-127b-11e8-8fe9-e79616c9d169.png)

When the third unload alert (the second triggered by `WebDriver#get()`) is accepted, subsequent driver interactions that assume successful navigation fail:

```
$ py.test -k test_click_with_dismissal_then_get_with_dismissal_then_get_with_acceptance
# ...
    def test_click_with_dismissal_then_get_with_dismissal_then_get_with_acceptance(self):
        self._click_with_unload_alert_dismissal()
        self._get_with_unload_alert_dismissal()
>       self._get_with_unload_alert_acceptance()
# ...
E       selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: p
```

## Trace-level log

[test_click_with_dismissal_then_get_with_dismissal_then_get_with_acceptance-geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1729712/test_click_with_dismissal_then_get_with_dismissal_then_get_with_acceptance-geckodriver.log.txt)

**Comment by whimboo** [comment]
Would you mind to minimize the testcase to code which is absolutely necessary to reproduce? It would help us a lot. Thanks.

**Comment by elliterate** [comment]
I moved the non-failing test cases into a separate, linked file.

**Comment by whimboo** [comment]
@elliterate, I'm sorry that I missed your reply on this issue.

Recently I discovered a race condition in `dismiss` and `alert` which is fixed in Firefox 63 beta now. Would you mind testing this version with the above scenario and let me know if it is still happening? Thanks.

**Comment by whimboo** [comment]
Actually `onbeforeunload` is currently no longer handled, and the browser automatically dismisses the alert. As such the initial comment doesn't reproduce the problem anymore.
