### ISSUE TITLE
How to tell whether I'm using geckodriver?

### ISSUE THREAD

**Issue by l0b0** [mozilla/geckodriver#1191]
## System

* Version: 0.19.1
* Platform: Arch Linux
* Firefox: Developer Edition 59.0
* Selenium: 3.9.1
* Language: Java

I can't tell whether geckodriver is enabled. Could you document a "hello world"-style example to verify that it's being used?

**Comment by AutomatedTester** [comment]
There will be a file output with geckodriver logs and the default for 3.9.1 is to use geckodriver. Unless you have set `marionette:false` in your capabilities you're using it.

**Comment by andreastt** [comment]
There won’t be a file with geckodriver output in Java. I believed the Java client surfaced stdout from geckodriver, so you should see `geckodriver    Listening on 127.0.0.1:4444` there. In any case, you are probably mislead by output indirection of the client you use if that’s not the case. Please see the API documentation of the Java client.

**Comment by l0b0** [comment]
@AutomatedTester, @andreastt Thanks, for the record:

```
$ COMPOSE_HTTP_TIMEOUT=99999999 docker-compose logs selenium | grep gecko
selenium_1          | 1519768198167	geckodriver	INFO	geckodriver 0.19.1
selenium_1          | 1519768198181	geckodriver	INFO	Listening on 127.0.0.1:7451
```
