### ISSUE TITLE
Cannot use Firefox + Remote Selenium + Geckodriver Server in a docker container - Cannot recover from Timeout loading page

### ISSUE THREAD

**Issue by nddipiazza** [mozilla/geckodriver#1193]
## System

* Version: 0.19.1, also tried the latest nightly geckodriver from https://queue.taskcluster.net/v1/task/B08EaV_xTv-mruOj4X8IiA/runs/0/artifacts/public/build/target.common.tests.zip
* Platform: Debian stretch docker container, Docker version 17.05.0-ce, build 89658be
also tried a centos docker container, same issue
* Firefox: tried 58.0.2 (64-bit), firefox-59.0b13 and firefox-60.0a1.en-US.linux-x86_64
* Selenium: tried both 3.5.3, 3.9.1

## Testcase

Full reproducer available https://github.com/nddipiazza/geckodriver-issue1193-reproducer

**I also repeated this test using non-headless firefox with XVFB. Same issue.** 

Steps are below how to use it: 

**Pull docker instance, run it, open a bash**

```
docker pull debian:stretch
docker run -t -d --name reproduce1193 debian:stretch
docker exec -i -t reproduce1193 /bin/bash
```

**Install prereqs and run the reproducer**

```
apt-get -y --fix-missing update && \
	apt-get -y --fix-missing upgrade && \
	apt-get -y --no-install-recommends install apt-utils && \
	apt-get install -y wget lbzip2 git openjdk-8-jdk libdbus-glib-1-2 xvfb libgtk-3.0
git clone https://github.com/nddipiazza/geckodriver-issue1193-reproducer
cd geckodriver-issue1193-reproducer
wget https://ftp.mozilla.org/pub/firefox/releases/58.0.2/linux-x86_64/en-US/firefox-58.0.2.tar.bz2
tar xvf firefox-58.0.2.tar.bz2
./gradlew build
java -jar ./build/libs/reproduce-marionette-timeouts-1.0-SNAPSHOT.jar firefox/firefox >>reproducer.log 2>&1
```

## Stacktrace and trace level logging

Log when program is run from docker: https://gist.github.com/nddipiazza/088b874b575f85b847a4468424cde925

Log when program is run from non-docker (ubuntumate 16, 64-bit):
https://gist.github.com/nddipiazza/08484d65f1e9b2e814d2aca575b518ea

Main stack of interest seems to be:

```
1519919380559	geckodriver::marionette	TRACE	-> 133:[0,6,"executeScript",{"args":[],"newSandbox":false,"script":"return document.readyState","scriptTimeout":null,"specialPowers":false}]
1519919380563	webdriver::server	DEBUG	Deleting session
1519919380563	geckodriver::marionette	DEBUG	Stopping browser process
1519919380602	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to decode response from marionette","stacktrace":"stack backtrace:\n   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e\n   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46\n   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032\n   3:           0x4295be - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193\n   4:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25\n   5:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba\n   6:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic\n                        at /checkout/src/libpanic_unwind/lib.rs:99\n   7:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473\n   8:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>\n                        at /checkout/src/liballoc/boxed.rs:692\n                         - std::sys_common::thread::start_thread\n                        at /checkout/src/libstd/sys_common/thread.rs:21\n                         - std::sys::imp::thread::{{impl}}::new::thread_start\n                        at /checkout/src/libstd/sys/unix/thread.rs:84"}}
Exception in thread "Thread-0" org.openqa.selenium.WebDriverException: Failed to decode response from marionette
```

You can clearly see the non-docker version is able to recover from this timeout.
But when on docker, it will not recover.

I also tried this same test with Selenium + Chromium + Chrome Driver. seems not to have the issue. so it's not selenium itself as far as I can tell.

**Comment by andreastt** [comment]
Thanks for the logs, but neither of them include the [trace-level] from geckodriver. Can you please attach some with the trace-level?

[trace-level]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by nddipiazza** [comment]
oops! trace is on now @andreastt

**Comment by nddipiazza** [comment]
the memory setting as indicated here: https://github.com/mozilla/geckodriver/issues/285#issuecomment-300617774

`docker run -t -d --name reproduce1193 debian:stretch` -> `docker run -t -d --shm-size 2g --name reproduce1193 debian:stretch` fixes the issue for me.

This ticket was opened to address the need for documentation here: https://bugzilla.mozilla.org/show_bug.cgi?id=1442356

**Comment by nddipiazza** [comment]
@andreastt kubernetes users don't get access to this setting. so feel free to re-open this ticket if you feel like this can be avoided in the first place.

**Comment by nddipiazza** [comment]
https://github.com/kubernetes/kubernetes/issues/28272

**Comment by whimboo** [comment]
There is no way to get around that unless the above mentioned bug has been fixed.

So this issue is a dupe of #285.
