### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: timeouts

### ISSUE THREAD

**Issue by manoj0613mj** [mozilla/geckodriver#1194]
when i excite the below mentioned code i am getting a error "selenium.common.exceptions.WebDriverException: Message: timeouts"

from selenium import webdriver
from selenium.webdriver.common.by import By

class Runfftest():
    def test(self):
        """
        Inistitate the ff browser
        launch the browser
        :return:
        """
        baseUrl = "https://letskodeit.teachable.com/p/practice"
        driver = webdriver.Firefox(executable_path='/usr/local/bin/geckodriver')
        driver.maximize_window()
        driver.get(baseUrl)
        driver.implicitly_wait(10)

        header_by_xpath = driver.find_element_by_xpath("//*[@id='navbar']")
        links_in_header = header_by_xpath.find_elements(By.TAG_NAME,"a")
        size_of_links = len(links_in_header)
        print(size_of_links)

        for linkinheader in links_in_header:
            linkinheader.click()

ff = Runfftest()
ff.test()

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Please also tell us what versions of Firefox, geckodriver, and Selenium you’re using. This was all requested in the issue template.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by manoj0613mj** [comment]
i was able to solve the problem ,i just had to update my fire fox to the latest version and even geckodriver

**Comment by AutomatedTester** [comment]
closing based on last message
