### ISSUE TITLE
Unable to scroll a page in android or IOS. Vertical and horizontal both.

### ISSUE THREAD

**Issue by sagarsheth27** [mozilla/geckodriver#1195]
Used efforts are as below:
1. JavaScript executor way.
2. With dimension method.
3. Scrollto , Scroll exact and swipe methods are not coming in eclipse on the press of ctrl+space.
4. Touch points are also not working.

What is the problem i am unable to understand. Is there any compatibility problem or anything else.
Please help me for same.

**Comment by andreastt** [comment]
As far as I know geckodriver doesn’t yet work on iOS or Android.

**Comment by sagarsheth27** [comment]
It is Appium base automation on physical device. Not in any browser. It is
a hybrid app. In that I am unable to scroll a page vertical or horizontal
in Android as well as IOS.
