### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <a class="fedora-navbar-link navbar-link" href="/pages/practice"> stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

### ISSUE THREAD

**Issue by manoj0613mj** [mozilla/geckodriver#1196]
When i run the below code i am getting this issue ,i am not able to understand why .I did increase the implicitly wait but still i am facing the same issue

from selenium import webdriver
from selenium.webdriver.common.by import By

class Runfftest():
    def test(self):
        """
        Inistitate the ff browser
        launch the browser
        :return:
        """
        baseUrl = "https://letskodeit.teachable.com/p/practice"
        driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")
        driver.maximize_window()
        driver.get(baseUrl)
        driver.implicitly_wait(10)

        header_by_xpath = driver.find_element_by_xpath("//*[@id='navbar']")
        links_in_header = header_by_xpath.find_elements(By.TAG_NAME,"a")
        size_of_links = len(links_in_header)
        print(size_of_links)

        for linkinheader in links_in_header:
            linkinheader.click()

ff = Runfftest()
ff.test()

**Comment by AutomatedTester** [comment]
It looks like you are navigating away from the page with the click and since you're in a loop the next page doesn't understand the element ID you're sending. Please send further questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

**Comment by sangli00** [comment]
@manoj0613mj  hi ，how to fix this problem ?

**Comment by whimboo** [comment]
As usual the find element commands have to be run again to get fresh copies of element references.
