### ISSUE TITLE
select2 menus do not work using Select Object

### ISSUE THREAD

**Issue by SiKing** [mozilla/geckodriver#1197]
I was sent here from: https://github.com/SeleniumHQ/selenium/issues/5558

## System

* Version: 0.19.1
* Platform: any
* Firefox: 58.0
* Selenium: 3.8.1

## Testcase

```
driver.get("https://select2.org/dropdown");

List<WebElement> selectElements = driver.findElements(By.tagName("select"));
Assert.assertEquals(1, selectElements.size());

Select select = new Select(selectElements.get(0));
select.selectByValue("NV");
```

## Stacktrace

```
org.openqa.selenium.WebDriverException: Element <option> could not be scrolled into view
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'mac-207-254-53-65.browserstack.com', ip: 'fe80:0:0:0:75:bdb3:579e:f092%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_51'
Driver info: driver.version: unknown
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at org.openqa.selenium.support.ui.Select.setSelected(Select.java:324)
	at org.openqa.selenium.support.ui.Select.selectByValue(Select.java:201)
	at ...
Caused by: org.openqa.selenium.WebDriverException: Element <option> could not be scrolled into view
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'mac-207-254-53-65.browserstack.com', ip: 'fe80:0:0:0:75:bdb3:579e:f092%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_51'
Driver info: driver.version: unknown
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'SCG00845', ip: 'fe80:0:0:0:14:b5bd:eeda:a89a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_144'
Driver info: driver.version:  unknown
```

## Trace-level log

I am generating this through BrowserStack; not sure if I got the right thing: [trace.log](https://github.com/mozilla/geckodriver/files/1776120/trace.log).

## Additional comments

This code works fine with other drivers - tested with Chrome, Edge, and IE. But more importantly: **this code works with Selenium version 3.3.1 + Geckodriver 0.15.0 + Firefox 52**.

A workaround can be based on [this SO answer](https://stackoverflow.com/a/17757761/3124333).

**Comment by whimboo** [comment]
The real `select` node is overlayed by some kind of weird HTML construct with `ul` and `li`, so operating with the select is not possible because it's plainly not reachable. To select one of the options you will have to work with the generated HTML code.

**Comment by SiKing** [comment]
As I said:

> This code works fine with other drivers - tested with Chrome, Edge, and IE. But more importantly: this code works with Selenium version 3.3.1 + Geckodriver 0.15.0 + Firefox 52.

So it is possible. Just not for current Geckodriver I guess.
:(

**Comment by whimboo** [comment]
At least chromedriver is not using the W3C webdriver specification by default yet. Maybe try turning it on with an option (which I don't know yet). I cannot say something about Edge or IE.

Note that with Firefox 58 we turned on interactability checks for elements to be conformant with the specification. As such geckodriver 0.19.1 and Firefox 57 should also not cause a failure. Please see https://github.com/mozilla/geckodriver/#mozwebdriverclick.

**Comment by SiKing** [comment]
Geckodriver 0.19.1 + Firefox 57 fails for the above code sample.
The last version that I could get to work was Geckodriver 0.15.0 + Firefox 52.

**Comment by whimboo** [comment]
Well, with Firefox 52 we haven't had the interactability checks enabled for `click` and `send_keys` which the WebDriver spec actually wants to see. See my last comments.

Just to make it clear, if you call `getBoundingClientRect()` for the `select` element, you will get the following rect returned:

> DOMRect { x: 412, y: 157.6999969482422, width: 1, height: 1, top: 157.6999969482422, right: 413, bottom: 158.6999969482422, left: 412 }

Which means the select is only 1px x 1px in size. It's also marked to not being able to get the focus, and marked as `aria-hidden`. 

Using the Inspector of the Firefox developer tools, you will also see that clicking onto the rect where the dropdown is visible, a `span` element will be selected. That one obscures the select:

> DOMRect { x: 412, y: 159.76666259765625, width: 838, height: 28, top: 159.76666259765625, right: 1250, bottom: 187.76666259765625, left: 412 }

So what you actually want is to use one of the nested `span` elements which you can reach with a XPath selector like `"//span[contains(concat(' ', normalize-space(@class), ' '), ' select2 ')]"`. Clicking this element perfectly opens the dropdown for me.

**Comment by SiKing** [comment]
I was using the workaround you describe already.
However, this is starting to sound as if the _other_ browser-drivers are doing it incorrectly; if/when they get caught up this will be the only way of interacting with these elements.

Just out of curiosity: do the different Selenium-browser-driver vendors talk to each other, and try to do the same things the same way, whether right or wrong?

In any case, Thank You for all the info.

**Comment by AutomatedTester** [comment]
we are implementing the spec they have agreed to implement too. We can't talk for their timeline on specific tests and features but they are working against the wdspec test suite which is used in implementation reports for the W3C
