### ISSUE TITLE
sendkeys not working with latest FF and geckodriver

### ISSUE THREAD

**Issue by himildesai** [mozilla/geckodriver#1199]
## System

* Version: 0.19.1
* Platform: Win 10/ OSX
* Firefox: 58.0.2
* Selenium: 3.5.3

## Trace-level log

Failure message: Expected [object Undefined] undefined to be a string
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'hdesai.local', ip: 'fe80:0:0:0:1852:252:8bf:cd9e%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/5m/fhr4tsy57fb0kq_p2lc_sk0r0000gn/T/rust_mozprofile.jMcoXfDdDzd7, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=MAC, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0.4, platformVersion=16.7.0, moz:processID=51826, browserName=firefox, javascriptEnabled=true, platformName=MAC, moz:webdriverClick=false}]
Session ID: 59c3e750-3b33-0e43-8ad5-e9dce7da1241

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by himildesai** [comment]
NVM, there was some issue with my machine setup. Closing this bug.
