### ISSUE TITLE
win32 release filename not following pattern from OSX/linux

### ISSUE THREAD

**Issue by vvo** [mozilla/geckodriver#120]
could we have geckodriver-0.8.0-win32.zip instead of geckodriver-v0.8.0-win32.zip?

This is what we have for OSX/linux. I am asking this because I am maintaining https://github.com/vvo/selenium-standalone which is a programmatic interface to install selenium and drivers.

**Comment by jgraham** [comment]
This will be fixed in the next release using the travis-based release machinery: https://github.com/mozilla/geckodriver/blob/master/ci.sh#L106

**Comment by vvo** [comment]
Ok do you have any ETA? I just fixed my selenium standalone module do solve that. So that it won't fail for too long once you do a new release.

**Comment by jgraham** [comment]
Next couple of days? I think there's just two more PRs to land before we reach something we are happy to call 0.9.0.

**Comment by vvo** [comment]
thanks will set a reminder ;)
