### ISSUE TITLE
Firefox - Selenium - Failed to connect to binary FirefoxBinary

### ISSUE THREAD

**Issue by venkatraman-r** [mozilla/geckodriver#1203]
## System

* Version: v0.19.1-win64
* Platform: Windows 7
* Firefox: 58.0.2 (64-bit)
* Selenium: 3.9.1

I am getting following error message while trying to run below code. 
Code snippet : 
System.setProperty("webdriver.gecko.driver", "C:\\selenium browser drivers\\geckodriver-v0.19.1-win64");
WebDriver driver = new FirefoxDriver();

Error Message received: 
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
BUG	Registering shutdown blocker for LightweightThemeManager
1520415238579	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1520415238579	addons.manager	DEBUG	Starting provider: GMPProvider
1520415238586	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1520415238586	addons.manager	DEBUG	Provider finished startup: GMPProvider
...............................................

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by venkatraman-r** [comment]
Hi Andreastt,

I couldn't able to take trace-level log. If I try to use FirefoxOptions class, am getting following error in 
"FirefoxOptions cannot be resolved to a type". I tried the below code to take trace-level log. 

"FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.TRACE);
WebDriver driver = new FirefoxDriver(options);"

I tried most of the workaround mentioned in previous to fix Unable to connect to host 127.0.0.1 on port 7055 issue but nothing work out. 

Please let me know if you required any further clarification.

**Comment by andreastt** [comment]
I’m assuming you are using the Java bindings? `FirefoxOptions` exist in this type: https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxOptions.html

**Comment by venkatraman-r** [comment]
yes. But I don't know, why exactly I am facing this issue? I referred that article you provided above before logging this issue. In order to set binary for Firefox. Even that not work out for this issue in my concern. Please help me out.

**Comment by andreastt** [comment]
I’m assuming you’re facing this issue because you’ve not imported the type.

**Comment by venkatraman-r** [comment]
I tried importing both the packages below.  
"import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.firefox.FirefoxOptions;"

But getting the following error "The import org.openqa.selenium.firefox.FirefoxOptions cannot be resolved"

I couldn't find that in my "org.openqa.selenium" package. 
Please let me know, do I need to bind any other jars.

**Comment by andreastt** [comment]
Then I have exhausted my Java knowledge. Please consult the Java and Selenium documentation.

**Comment by soumyababy81** [comment]
System.setProperty("webdriver.gecko.driver", "C:\selenium browser drivers\geckodriver-v0.19.1-win64");
whole exe path to be given like
System.setProperty("webdriver.gecko.driver", "C:\\git\\geckodriver.exe");

**Comment by satinder-pal** [comment]
I am also facing the same issue while executing automation script. 

Platform -- Windows 8
selenium -- 4.4.0
Firefox version -- 50 and 48
error --  Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
e6fd}","syncGUID":"RkTNivgAqs6F","location":"app-global","version":"48.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1469556455000,"updateDate":1469556455000,"applyBackgroundUpdates":1,"skinnable":true,"size":21899,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"48.0","maxVersion":"48.0"}],"targetPlatforms":[],"seen":true}

**Comment by whimboo** [comment]
Are you both let geckodriver find the Firefox binary itself? This can fail in some cases, especially when you have a 32bit binary installed on a Windows 64bit system. Please try in setting the binary by explicitly specifying the path in the `moz:firefoxOpions`. See https://github.com/mozilla/geckodriver/#mozfirefoxoptions

**Comment by bikashmishra100** [comment]
Firefox version: Nightly 61.0a1
Gecko Driver version: 0.20

With the standard firefox version, the FireFox Webdriver addon is getting disabled. With nightly build and preference extensions.legacy.enabled set to true, the webdriver addon got enabled.

But I get the same error as others here. I have uploaded the log file. If you find the verbosity not good enough then please let me know.

[firefox_log.txt](https://github.com/mozilla/geckodriver/files/1844383/firefox_log.txt)

**Comment by whimboo** [comment]
@bikashmishra100 the fxdriver extension is not supported anymore. The replacement for it is to use geckodriver and Marionette. So forget about the extension.

Regarding your not being able to connect issue I cannot tell from what the log says because it doesn't contain the line which tells the version of geckodriver, and one which has the argument list for Firefox. Make sure you upload the full log, and then please attach the [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html).

**Comment by bikashmishra100** [comment]
@whimboo sincere apologies for the trouble. I overlooked the gradle script. The referred selenium version was too old. I updated it and everything works fine now.

**Comment by whimboo** [comment]
> But getting the following error "The import org.openqa.selenium.firefox.FirefoxOptions cannot be resolved"

@andreastt, doesn't the above mean that the Selenium installation might be busted? The docs clearly reference this package and class. So I doubt that this is a problem on our side, and that we should close this issue.

**Comment by andreastt** [comment]
I agree.
