### ISSUE TITLE
CONTRIBUTING.md references a marionette readme.md that does not exist

### ISSUE THREAD

**Issue by nddipiazza** [mozilla/geckodriver#1205]
https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md

references a marionette readme.md that does not exist

**Comment by whimboo** [comment]
@andreastt I assume it is a side-effect from your latest changes.

**Comment by whimboo** [comment]
oh, we might have to update the file from mozilla-central.

**Comment by andreastt** [comment]
@whimboo Indeed. Just need to copy the files over to the GitHub master branch.

**Comment by whimboo** [comment]
@andreastt that won't work because on central we reference `../marionette/README.md`. But this will not work on this repository. So we will have to add a direct link to the firefox-source HTML documention here.

**Comment by andreastt** [comment]
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1444593. CONTRIBUTING.md will be exported here when 0.20.0 is released.

**Comment by whimboo** [comment]
0.20.0 has been released.
