### ISSUE TITLE
Geckodriver couldn't simultaneously run more than one test.

### ISSUE THREAD

**Issue by marcelopontipedra** [mozilla/geckodriver#1213]
## System

* Version: 0.19.1.20171103
* Platform: Windows 10
* Firefox: Developer edition
* Selenium: 3.9.1

Running my test sequentially will take time. I've been able to configure my QA server to run more than one test, however, this is the problem of the geckodriver because it couldn't run more than one instance at the same time.

![image](https://user-images.githubusercontent.com/9210581/37327702-579e3fe2-26d2-11e8-9078-251893f0ea5f.png)

## Stacktrace

at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at Transim.Selenium.Browsers.FireFoxDriver()
   at Transim.Selenium.Browsers.Browser(String Browsername)
   at selenium_tests.Tests.Versions.Login() in D:\GitRepo\Selenium\Infineon-tests\HallDesk-Selenium-Tests\selenium-tests\Tests\Versions.cs:line 33
Result Message:	System.InvalidOperationException : Session is already started (SessionNotCreated)

**Comment by AutomatedTester** [comment]
Not seeing how you are running your test makes it incredibly hard to help here. Do you only start 1 geckodriver?

**Comment by whimboo** [comment]
Make sure that you have multiple instances of geckodriver running. Each of those will exactly manage a Firefox process, and will have its own local port.

**Comment by marcelopontipedra** [comment]
I've a one server where all my selenium tests are running. I can only start one Geckodriver where I think I realized now that I can only run one Geckodriver because I only use one local port in all of my tests. Unlike chrome we can run multiple instance by using one port only.

**Comment by marcelopontipedra** [comment]
The problem would be that how to get an exact available port.

**Comment by whimboo** [comment]
Can you please show some code which gives us an idea in how you specify the geckodriver binary and port?

**Comment by andreastt** [comment]
As whimboo says you need one geckodriver per session; you cannot currently re-use the same geckodriver process for multiple Firefox connections.

**Comment by marcelopontipedra** [comment]
I used this code to specify the available port.

        static int AvailablePort()
        {
            TcpListener l = new TcpListener(IPAddress.Loopback, 0);
            l.Start();
            int port = ((IPEndPoint)l.LocalEndpoint).Port;
            l.Stop();
            Console.WriteLine("Start at port: " + port);
            return port;
        }

**Comment by whimboo** [comment]
@marcelopontipedra which port are you trying to figure out here? The one for geckodriver or Marionette?

**Comment by marcelopontipedra** [comment]
@whimboo for geckodriver.

FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(SeleniumDriver, "geckodriver.exe");
FirefoxOptions profile = new FirefoxOptions();
service.Port = AvailablePort();

**Comment by whimboo** [comment]
@marcelopontipedra that doesn't show me that multiple instances of geckodriver are used. If you do so (as what you haven't said yet) we can continue the discussion. Otherwise it's not helpful. Thanks.

**Comment by marcelopontipedra** [comment]
@whimboo  Sorry, I've just shown you on how I used the available port method. The first problem was, I couldn't simultaneously run more than one test for Firefox. Then, what I've found out is that, I can re-use the same geckodriver process for multiple Firefox connections by supplying available port per session.

The method below returns webdriver for firefox which can be the instance of webdrivers. 
```
public IWebDriver FireFoxDriver()
        {
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(SeleniumDriver, "geckodriver.exe");
            FirefoxOptions profile = new FirefoxOptions();
           profile.SetPreference("browser.helperApps.alwaysAsk.force", false);
            service.Port = AvailablePort();
            service.FirefoxBinaryPath = FirefoxPath;
            TimeSpan time = TimeSpan.FromSeconds(120);
            IWebDriver driver = new FirefoxDriver(service, profile, time);
            driver.Manage().Window.Maximize();
            return driver;
        }
```

**Comment by AutomatedTester** [comment]
Since the default for the service is to randomly pick an available port it is already doing that. see https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Firefox/FirefoxDriverServer.cs#L132-L171

If you are doing 

```dotnet
IWebDriver driver = new FirefoxDriver();
```

Then it will find its own free port. I am not sure why you're doing this convoluted bit of code when the default does it already for you.

**Comment by andreastt** [comment]
I’m sorry, your last comment doesn’t make any sense. Given that FirefoxDriverServer.cs allocates a free port, why does it conflict Chrome?

**Comment by marcelopontipedra** [comment]
Sorry about that, I might do wrong in my code. I'l try to review it.
