### ISSUE TITLE
geckodriver + FF59 addPreference savetodesk not working

### ISSUE THREAD

**Issue by veluguri** [mozilla/geckodriver#1219]
## System

* Version: v0.20.0
* Platform: Windows 7
* Firefox:  59
* Selenium: 3.11.0
JDK : 1.8.0_161

i want the files to be automatically download  to local drive instead of opening in the browser or asking 
i have  added 

options.addPreference("browser.download.lastdir","C:\\MyDownloads");
options.addPreference("browser.download.dir","C:\\MyDownloads");
options.addPreference("browser.download.downloaddir","C:\\MyDownloads");
options.addPreference("browser.download.usedownloaddir",true);
options.addPreference("browser.download.defaultfolder","C:\\MyDownloads");

options.addPreference("browser.helperApps.neverAsk.saveToDisk","application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/download,text/html,text/webviewhtml,application/vnd.ms-excel.sheet.macroEnabled.12,application/octet-stream,application/pdf,text/plain,application/xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/ms-excel");

the same code is working fine with firefox older version(47) , but after upgrading to 59 and latest selenium , it is not working.

please help.

**Comment by andreastt** [comment]
This isn’t an issue with geckodriver. You should file it against Firefox instead.

**Comment by whimboo** [comment]
> This isn’t an issue with geckodriver. You should file it against Firefox instead.

Why do you think? A [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) would be needed to say more. @veluguri can you please provide one?

**Comment by whimboo** [comment]
There is nothing we can do for this issue unless the trace log is provided.
