### ISSUE TITLE
Starting Firefox 47.0.1 and Windows (Protractor)

### ISSUE THREAD

**Issue by inthegarage** [mozilla/geckodriver#122]
I'm struggling to get the driver to start properly in windows in a protractor environment.
If I start it standalone, with the following command I get:

C:\WINDOWS\system32>geckodriver.exe -b "C:\Program Files\Mozilla Firefox\firefox.exe"
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 10013, message: "An attempt was made to access a socket in a way forbidden by its access permissions." } })', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I did start it in an admin console, so permissions shouldn't be ans issue.
I also tried starting in IntelliJ using a protractor file, however this comes up with the following error:

[c:\work\proj\node_modules\protractor\node_modules\selenium-webdriver\error.js:26
  constructor(opt_error) {
                         ^
WebDriverError: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/jgraham/wires. The latest version can be downloaded from https://github.com/jgraham/wires
10:44:20    at WebDriverError (c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\error.js:26:26)
    at Object.checkLegacyResponse (c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\error.js:580:13)
]     at c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:64:13
    at Promise.invokeCallback_ (c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    at TaskQueue.execute_ (c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
E    at c:\work\ema\rms-web\RMS-Web\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7

The file is on the system PATH and my properties are set:

webdriver.gecko.driver=C:\tools\gecko
webdriver.ie.driver=C:\work\drivers\

What is the correct way of getting this going?

Thank you.

**Comment by andreastt** [comment]
From a quick search, a Windows socket error code 10013 seems to indicate that you do not have permission to bind to the socket. Not having admin permissions or running antivirus software are two likely candidates.

But in any case, this is unlikely a problem with the geckodriver software itself.

**Comment by inthegarage** [comment]
Do you know why the IntellIJ run doesn't find any of the properties?

**Comment by inthegarage** [comment]
Seems to be solely a IntelliJ issue, will run it by the Jetbrains guys.

**Comment by andreastt** [comment]
The `webdriver.gecko.driver` system property thing is a different issue entirely. I believe you set that by passing `-Dwebdriver.gecko.driver=/path/to/executable` to the java runtime binary. I don’t know about IntelliJ.

**Comment by inthegarage** [comment]
I have sorted this issue, there is a different one now (more permissions). I will create a new issue. Thank you.

**Comment by andreastt** [comment]
Great!

**Comment by sharvarik** [comment]
Hi @inthegarage I am experiencing this issue with Windows 7 , Firefox 47 and Selenium 3.1.0 in protractor. How did you resolve this issue?

**Comment by inthegarage** [comment]
@sharvarik 
Set the parameter on the -D parameter when you run Selenium. 

java -jar seleniumjar.jar -Dwebdriver.gecko.driver =</your/path/here>

Does that work for you?

**Comment by flik** [comment]
$ java -jar selenium-server-standalone-3.3.0.jar -Dwebdriver.gecko.driver =geckodriver.exe

Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.gecko.driver
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
        at org.openqa.grid.selenium.GridLauncherV3$1.setConfiguration(GridLauncherV3.java:227)
        at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)

**Comment by cgoldberg** [comment]
@flik 
The command posted by @inthegarage is not correct.  The `webdriver.gecko.driver` option needs to be passed to the Java runtime, so it should come before the name of the jar file.

for example:
`$ java -jar -Dwebdriver.gecko.driver=/path/to/geckodriver selenium-server-standalone-3.10.0.jar`

**Comment by andreastt** [comment]
Please let’s not hijack old threads. File a new issue instead.
