### ISSUE TITLE
geckodriver process still running after driver.quit

### ISSUE THREAD

**Issue by veluguri** [mozilla/geckodriver#1220]
## System

* Version: v0.20.0
* Platform: windows
* Firefox: 59
* Selenium: 3.11.0
JDK : 1.8.0_161

geckodriver.exe  process keeps running in task manager  after driver.quit is called 

we have many test cases where we need to initiate the webdriver for every test case , at the end of the day we are seeing many geckodriver processes running in task manager  even though all test cases are completed.

how to clean the geckodriver.exe  from task manager , please help.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver when this happens? Is it reproducible it some way? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by keeper32** [comment]
Hi, I'm having an issue very similar to this.

System specs:
Windows 8.1 64-bit
geckodriver-v0.20.0-win64
selenium-firefox-driver 3.11.0 (in pom.xml)
Firefox Quantum 59.0.1 (64-bit)

Please take a look on this java simple test case and attached trace log:

```
	@Test
	public void googleTest() {
		driver.get("https://www.google.com");
		driver.findElement(By.id("lst-ib")).sendKeys("Selenium");
		driver.findElement(By.cssSelector("form input[type=submit]")).click();
		
		Assert.assertTrue(isElementPresent(By.cssSelector("div.rc h3.r a")));
		driver.close();
	}
```

[trace-level-log.txt](https://github.com/mozilla/geckodriver/files/1830444/trace-level-log.txt)

**Comment by andreastt** [comment]
@keeper32 According to the log you attached it looks like a child process in Firefox crashes, which causes geckodriver to emit the `Failed to stop browser process` message. However, this does not explain why your client is failing to end the session.

I suspect this is a bug with the Java client. It doesn’t look like it at any point interrupts or stops geckodriver.

**Comment by andreastt** [comment]
@veluguri It would be good if you could also attach a trace-level log to confirm.

**Comment by veluguri** [comment]
Hi Andreas , i have a kind of problem here , i have updated my project to
work with latest FF , when i see this issue , i am forced to revert my
changes which i did. i am now struggling to  update to latest selenium to
reproduce this issue.

i am trying.

will provide you the logs ASAP.

appreciate your patience

Thank you

*Sampath Veluguri – QA – IT Support Services Lead*
*Consumer Insurance Americas IT*
*100 Connell Drive , Berkeley Heights, NJ 07922*

**Comment by bentoi** [comment]
I was seeing the same issue. In my case the responsible was the shim created by Chocolatey [ShimGen](https://chocolatey.org/docs/features-shim). The shim was first in my PATH and was therefore executed in place of `geckodriver.exe`. My understanding is that the Shim forks the real `geckodriver.exe` process when executed.

Since Selenium relies on terminating the process to shutdown the driver (the `geckodriver` doesn't implement a remote shutdown command?), selenium ends up killing the Shim geckodriver process but not the child process (because of the way `TerminateProcess` works).

Fixing my PATH to ensure the real `geckodriver.exe` is used fixes the accumulation of `geckodriver.exe` processes...

**Comment by whimboo** [comment]
There is nothing we can do for this issue unless the trace log is provided.

**Comment by shayngr** [comment]
I had the same issue but now it's fixed after switching to old geckodriver v.0.19.
Geckodriver: v0.19.1-win64
Firefox: 61.0.1
Selenium: 3.141.59
JDK : 1.8.0_45
Make sure to use driver.quite(); 
I hope this helps.

**Comment by cgoldberg** [comment]
> fixed after switching to old geckodriver v.0.19.

reverting to a previous version is certainly not a *fix*.
