### ISSUE TITLE
Virus reported by Windows Defender on file geckodriver-v0.20.0-win32.zip

### ISSUE THREAD

**Issue by enriverd** [mozilla/geckodriver#1221]
After downloading windows biranies for v0.20.0 (file geckodriver-v0.20.0-win32.zip), Windows Defender reports the file contains Trojan:Win32/Critet.BS. 

This is a serious and critical issue that should be addressed ASAP.

**Comment by andreastt** [comment]
I’m afraid there’s not really much we can do about this on our side. I would encourage you to report the problem as a false positive to Microsoft.

**Comment by whimboo** [comment]
Please see https://www.virustotal.com/#/url/cd53bf8d437183b205ad2b26279f601e4f40bd26214e925b46bf3c197d6ac22c/detection for such a report, which is all green.
