### ISSUE TITLE
Not able to run selenium tests

### ISSUE THREAD

**Issue by DSagai** [mozilla/geckodriver#1223]
## System

* Version: 0.19.1
* Platform: Ubuntu 16.04.2 LT
* Firefox: 58.0.2
* Selenium: 3.10.0

## Testcase
When I try to run TestNG project from jenkins job, WebDriver fails.
Problem doesn't reproduce stable, but quite often. 

## Stacktrace

Constructor threw exception; nested exception is org.openqa.selenium.WebDriverException: connection refused

Build info: version: '3.10.0', revision: '176b4a9', time: '2018-03-02T19:03:16.397Z'

System info: host: 'wolverine', ip: '192.168.0.42', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.0-36-generic', java.version: '1.8.0_05'

Driver info: driver.version: FirefoxDriver

remote stacktrace: stack backtrace:

   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e

   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46

   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43

   3:           0x447ba9 - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684

   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193

   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25

   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba

   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic

                        at /checkout/src/libpanic_unwind/lib.rs:99

   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473

   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>

                        at /checkout/src/liballoc/boxed.rs:692

                         - std::sys_common::thread::start_thread

                        at /checkout/src/libstd/sys_common/thread.rs:21

                         - std::sys::imp::thread::{{impl}}::new::thread_start

                        at /checkout/src/libstd/sys/unix/thread.rs:84

## Trace-level log

1521462467235	geckodriver::marionette	TRACE	  connection attempt 139/600
1521462467336	geckodriver::marionette	TRACE	  connection attempt 140/600
1521462467436	geckodriver::marionette	TRACE	  connection attempt 141/600
1521462467537	geckodriver::marionette	TRACE	  connection attempt 142/600
1521462467637	geckodriver::marionette	TRACE	  connection attempt 143/600
1521462467737	geckodriver::marionette	TRACE	  connection attempt 144/600
1521462467838	geckodriver::marionette	TRACE	  connection attempt 145/600
1521462467938	geckodriver::marionette	TRACE	  connection attempt 146/600
1521462468039	geckodriver::marionette	TRACE	  connection attempt 147/600
1521462468139	geckodriver::marionette	TRACE	  connection attempt 148/600
1521462468239	geckodriver::marionette	TRACE	  connection attempt 149/600
1521462468340	geckodriver::marionette	TRACE	  connection attempt 150/600
1521462468432	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1521462468440	geckodriver::marionette	TRACE	  connection attempt 151/600
1521462468540	geckodriver::marionette	TRACE	  connection attempt 152/600
1521462468574	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1521462468574	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1521462468574	Marionette	DEBUG	New connections are accepted
1521462468575	Marionette	INFO	Listening on port 34663
1521462468640	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:34663
1521462468641	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:46410
1521462468641	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1521462468641	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1521462468643	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1521462468644	Marionette	WARN	TLS certificate errors will be ignored for this session
1521462468686	Marionette	DEBUG	Register listener.js for window 2147483649
1521462468690	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"98bd6b8b-639a-46eb-94bf-c2c8bc365aae","capabilities":{"browserName":"firefox","browserVersion":"58.0. ... alse,"moz:headless":false,"moz:processID":2987,"moz:profile":"/tmp/rust_mozprofile.HdZPfaLii6Fq","moz:webdriverClick":true}}]
1521462468691	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"98bd6b8b-639a-46eb-94bf-c2c8bc365aae","capabilities":{"browserName":"firefox","browserVersion":"58.0.2","platformName":"linux","platformVersion":"4.8.0-36-generic","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":2987,"moz:profile":"/tmp/rust_mozprofile.HdZPfaLii6Fq","moz:webdriverClick":true}}]
1521462468691	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"98bd6b8b-639a-46eb-94bf-c2c8bc365aae","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"58.0.2","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":2987,"moz:profile":"/tmp/rust_mozprofile.HdZPfaLii6Fq","moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.8.0-36-generic","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1521462468715	webdriver::server	DEBUG	-> POST /session/98bd6b8b-639a-46eb-94bf-c2c8bc365aae/window/maximize {}
1521462468715	geckodriver::marionette	TRACE	-> 25:[0,2,"maximizeWindow",{}]
1521462468716	Marionette	TRACE	0 -> [0,2,"maximizeWindow",{}]
1521462469915	Marionette	TRACE	0 <- [1,2,null,{"x":65,"y":24,"width":1535,"height":876,"state":"maximized"}]
1521462470746	geckodriver::marionette	TRACE	<- [1,2,null,{"x":65,"y":24,"width":1535,"height":876,"state":"maximized"}]
1521462470747	webdriver::server	DEBUG	<- 200 OK {"value": {"height":876,"width":1535,"x":65,"y":24}}
1521462464181	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1521462464453	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1521462464453	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1521462464453	Marionette	DEBUG	New connections are accepted
1521462464454	Marionette	INFO	Listening on port 45701

**Comment by whimboo** [comment]
Nothing in the log indicates a failure. Only the random order of log lines is scary. Those are not sorted by time. 

When you say something is not working please be specific in what is not working. The above doesn't give any indication for a failure, so please send us more details.

**Comment by AutomatedTester** [comment]
Closing this as it appears to be more a user error or at worst a Selenium issue.
