### ISSUE TITLE
send_keys not working

### ISSUE THREAD

**Issue by altezza072** [mozilla/geckodriver#1229]
## System

* Version:  0.20
* Platform:  Windows 10 x64
* Firefox:  ver 59.0
* Selenium:  3.11

from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = Firefox(firefox_options=opts)
start_page = "http://www.yahoo.com"
spell = "ah-RAHN-ee-a EKS-su-may"
driver.get(start_page)	
search = driver.find_element_by_id("uh-search-box")
search.send_keys(spell)

Traceback (most recent call last):
  File "log.py", line 11, in <module>
    search.send_keys(spell)
  File "C:\Users\altez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Users\altez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\altez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\altez\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Expected [object Undefined] undefined to be a string

1521821054699	geckodriver	INFO	Listening on 127.0.0.1:58145
1521821057781	mozprofile::profile	INFO	Using profile path C:\Users\altez\AppData\Local\Temp\rust_mozprofile.M6vzqQPIOzan
1521821057795	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args []
1521821057802	geckodriver::marionette	INFO	Connecting to Marionette on localhost:58153
1521821058130	Marionette	DEBUG	Received observer notification "profile-after-change"
Unable to read VR Path Registry from C:\Users\altez\AppData\Local\openvr\openvrpaths.vrpath
1521821058224	Marionette	DEBUG	Received observer notification "command-line-startup"
1521821058224	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\altez\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\altez\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\altez\AppData\Local\openvr\openvrpaths.vrpath
1521821059178	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
Unable to read VR Path Registry from C:\Users\altez\AppData\Local\openvr\openvrpaths.vrpath
1521821059348	Marionette	DEBUG	Setting recommended pref browser.safebrowsing.passwords.enabled to false
1521821059348	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1521821059348	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1521821059348	Marionette	DEBUG	Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1521821059350	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1521821059350	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1521821059350	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1521821059350	Marionette	DEBUG	New connections are accepted
1521821059350	Marionette	INFO	Listening on port 58153
1521821059805	geckodriver::marionette	DEBUG	TCP connection established
1521821059806	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:58161
1521821059809	geckodriver::marionette	DEBUG	← {"applicationType":"gecko","marionetteProtocol":3}
1521821059809	geckodriver::marionette	DEBUG	→ 155:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"},"requiredCapabilities":{}},"sessionId":null}]
1521821059810	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"},"requiredCapabilities":{}},"sessionId":null}]
1521821059858	Marionette	DEBUG	Register listener.js for window 4294967297
1521821059862	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"3035362d-3350-46a9-bd40-dd07a88be6b3","capabilities":{"browserName":"firefox","browserVersion":"59.0" ... AppData\\Local\\Temp\\rust_mozprofile.M6vzqQPIOzan","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1521821059864	geckodriver::marionette	DEBUG	← [1,1,null,{"sessionId":"3035362d-3350-46a9-bd40-dd07a88be6b3","capabilities":{"browserName":"firefox","browserVersion":"59.0","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":2488,"moz:profile":"C:\\Users\\altez\\AppData\\Local\\Temp\\rust_mozprofile.M6vzqQPIOzan","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1521821059865	webdriver::server	DEBUG	Returning status Ok
1521821059865	webdriver::server	DEBUG	Returning body {"value": {"sessionId":"3035362d-3350-46a9-bd40-dd07a88be6b3","value":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"59.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":2488,"moz:profile":"C:\\Users\\altez\\AppData\\Local\\Temp\\rust_mozprofile.M6vzqQPIOzan","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1521821059865	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1521821059865	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1521821059865	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(537) )
1521821059865	hyper::server::response	DEBUG	writing head: Http11 Ok
1521821059865	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 19, tm_min: 4, tm_hour: 16, tm_mday: 23, tm_mon: 2, tm_year: 118, tm_wday: 5, tm_yday: 81, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 865493600 })) )
1521821059865	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 537
, Date: Fri, 23 Mar 2018 16:04:19 GMT
, }]
1521821059865	hyper::server::response	DEBUG	write 537 bytes
1521821059865	hyper::server::response	TRACE	ending
1521821059865	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:58152
1521821059865	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:58152
1521821059867	hyper::server	DEBUG	Incoming stream
1521821059867	hyper::buffer	TRACE	get_buf []
1521821059867	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1521821059867	hyper::buffer	TRACE	get_buf [u8; 4096][0..294]
1521821059867	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 51, 48, 51, 53, 51, 54, 50, 100, 45, 51, 51, 53, 48, 45, 52, 54, 97, 57, 45, 98, 100, 52, 48, 45, 100, 100, 48, 55, 97, 56, 56, 98, 101, 54, 98, 51, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 105, 100, 101, 110, 116, 105, 116, 121, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 51, 49, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 107, 101, 101, 112, 45, 97, 108, 105, 118, 101, 13, 10, 13, 10, 123, 34, 117, 114, 108, 34, 58, 32, 34, 104, 116, 116, 112, 58, 47, 47, 119, 119, 119, 46, 121, 97, 104, 111, 111, 46, 99, 111, 109, 34, 125])
1521821059867	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 294])
1521821059867	hyper::http::h1	TRACE	Request.try_parse Complete(263)
1521821059867	hyper::header	TRACE	raw header: "Host"=[49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53]
1521821059867	hyper::header	TRACE	raw header: "Accept-Encoding"=[105, 100, 101, 110, 116, 105, 116, 121]
1521821059867	hyper::header	TRACE	raw header: "Content-Length"=[51, 49]
1521821059867	hyper::header	TRACE	raw header: "Accept"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110]
1521821059867	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56]
1521821059867	hyper::header	TRACE	raw header: "User-Agent"=[80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104]
1521821059867	hyper::header	TRACE	raw header: "Connection"=[107, 101, 101, 112, 45, 97, 108, 105, 118, 101]
1521821059867	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/url") Http11
1521821059867	hyper::server::request	DEBUG	Headers { Host: 127.0.0.1:58145
, Accept-Encoding: identity
, Content-Length: 31
, Accept: application/json
, Content-Type: application/json;charset=UTF-8
, User-Agent: Python http auth
, Connection: keep-alive
, }
1521821059867	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1521821059867	hyper::http::h1	TRACE	Sized read, remaining=31
1521821059867	hyper::http::h1	TRACE	Sized read: 31
1521821059867	hyper::http::h1	TRACE	Sized read, remaining=0
1521821059867	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/url")
1521821059868	webdriver::command	DEBUG	Got request body {"url": "http://www.yahoo.com"}
1521821059868	geckodriver::marionette	DEBUG	→ 42:[0,2,"get",{"url":"http://www.yahoo.com"}]
1521821059868	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://www.yahoo.com"}]
1521821059874	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1521821060486	Marionette	DEBUG	Received DOM event pagehide for about:blank
1521821063258	Marionette	DEBUG	Received DOM event DOMContentLoaded for https://www.yahoo.com/
[Parent 2488, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1521821066884	Marionette	DEBUG	Received DOM event pageshow for https://www.yahoo.com/
1521821066884	Marionette	TRACE	0 <- [1,2,null,{}]
1521821066886	geckodriver::marionette	DEBUG	← [1,2,null,{}]
1521821066886	webdriver::server	DEBUG	Returning status Ok
1521821066886	webdriver::server	DEBUG	Returning body {"value": {}}
1521821066886	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1521821066886	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1521821066886	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(13) )
1521821066886	hyper::server::response	DEBUG	writing head: Http11 Ok
1521821066886	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 26, tm_min: 4, tm_hour: 16, tm_mday: 23, tm_mon: 2, tm_year: 118, tm_wday: 5, tm_yday: 81, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 886837600 })) )
1521821066886	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 13
, Date: Fri, 23 Mar 2018 16:04:26 GMT
, }]
1521821066886	hyper::server::response	DEBUG	write 13 bytes
1521821066886	hyper::server::response	TRACE	ending
1521821066886	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:58169
1521821066886	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:58169
1521821066888	hyper::server	DEBUG	Incoming stream
1521821066888	hyper::buffer	TRACE	get_buf []
1521821066888	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1521821066888	hyper::buffer	TRACE	get_buf [u8; 4096][0..327]
1521821066888	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 51, 48, 51, 53, 51, 54, 50, 100, 45, 51, 51, 53, 48, 45, 52, 54, 97, 57, 45, 98, 100, 52, 48, 45, 100, 100, 48, 55, 97, 56, 56, 98, 101, 54, 98, 51, 47, 101, 108, 101, 109, 101, 110, 116, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 105, 100, 101, 110, 116, 105, 116, 121, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 54, 48, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 107, 101, 101, 112, 45, 97, 108, 105, 118, 101, 13, 10, 13, 10, 123, 34, 117, 115, 105, 110, 103, 34, 58, 32, 34, 99, 115, 115, 32, 115, 101, 108, 101, 99, 116, 111, 114, 34, 44, 32, 34, 118, 97, 108, 117, 101, 34, 58, 32, 34, 91, 105, 100, 61, 92, 34, 117, 104, 45, 115, 101, 97, 114, 99, 104, 45, 98, 111, 120, 92, 34, 93, 34, 125])
1521821066888	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 327])
1521821066888	hyper::http::h1	TRACE	Request.try_parse Complete(267)
1521821066888	hyper::header	TRACE	raw header: "Host"=[49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53]
1521821066888	hyper::header	TRACE	raw header: "Accept-Encoding"=[105, 100, 101, 110, 116, 105, 116, 121]
1521821066888	hyper::header	TRACE	raw header: "Content-Length"=[54, 48]
1521821066888	hyper::header	TRACE	raw header: "Accept"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110]
1521821066888	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56]
1521821066888	hyper::header	TRACE	raw header: "User-Agent"=[80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104]
1521821066888	hyper::header	TRACE	raw header: "Connection"=[107, 101, 101, 112, 45, 97, 108, 105, 118, 101]
1521821066888	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/element") Http11
1521821066888	hyper::server::request	DEBUG	Headers { Host: 127.0.0.1:58145
, Accept-Encoding: identity
, Content-Length: 60
, Accept: application/json
, Content-Type: application/json;charset=UTF-8
, User-Agent: Python http auth
, Connection: keep-alive
, }
1521821066888	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1521821066888	hyper::http::h1	TRACE	Sized read, remaining=60
1521821066888	hyper::http::h1	TRACE	Sized read: 32
1521821066888	hyper::http::h1	TRACE	Sized read, remaining=28
1521821066888	hyper::http::h1	TRACE	Sized read: 28
1521821066888	hyper::http::h1	TRACE	Sized read, remaining=0
1521821066888	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/element")
1521821066889	webdriver::command	DEBUG	Got request body {"using": "css selector", "value": "[id=\"uh-search-box\"]"}
1521821066889	geckodriver::marionette	DEBUG	→ 77:[0,3,"findElement",{"using":"css selector","value":"[id=\"uh-search-box\"]"}]
1521821066890	Marionette	TRACE	0 -> [0,3,"findElement",{"using":"css selector","value":"[id=\"uh-search-box\"]"}]
1521821066910	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"daff46ae-28f2-4379-a8cd-98925b709266","ELEMENT":"daff46ae-28f2-4379-a8cd-98925b709266"}}]
1521821066910	geckodriver::marionette	DEBUG	← [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"daff46ae-28f2-4379-a8cd-98925b709266","ELEMENT":"daff46ae-28f2-4379-a8cd-98925b709266"}}]
1521821066910	webdriver::server	DEBUG	Returning status Ok
1521821066910	webdriver::server	DEBUG	Returning body {"value":{"element-6066-11e4-a52e-4f735466cecf":"daff46ae-28f2-4379-a8cd-98925b709266"}}
1521821066910	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1521821066910	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1521821066910	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(88) )
1521821066910	hyper::server::response	DEBUG	writing head: Http11 Ok
1521821066910	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 26, tm_min: 4, tm_hour: 16, tm_mday: 23, tm_mon: 2, tm_year: 118, tm_wday: 5, tm_yday: 81, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 910903900 })) )
1521821066910	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 88
, Date: Fri, 23 Mar 2018 16:04:26 GMT
, }]
1521821066910	hyper::server::response	DEBUG	write 88 bytes
1521821066910	hyper::server::response	TRACE	ending
1521821066910	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:58298
1521821066910	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:58298
1521821066912	hyper::server	DEBUG	Incoming stream
1521821066912	hyper::buffer	TRACE	get_buf []
1521821066912	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1521821066912	hyper::buffer	TRACE	get_buf [u8; 4096][0..518]
1521821066912	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 51, 48, 51, 53, 51, 54, 50, 100, 45, 51, 51, 53, 48, 45, 52, 54, 97, 57, 45, 98, 100, 52, 48, 45, 100, 100, 48, 55, 97, 56, 56, 98, 101, 54, 98, 51, 47, 101, 108, 101, 109, 101, 110, 116, 47, 100, 97, 102, 102, 52, 54, 97, 101, 45, 50, 56, 102, 50, 45, 52, 51, 55, 57, 45, 97, 56, 99, 100, 45, 57, 56, 57, 50, 53, 98, 55, 48, 57, 50, 54, 54, 47, 118, 97, 108, 117, 101, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 105, 100, 101, 110, 116, 105, 116, 121, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 50, 48, 55, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 107, 101, 101, 112, 45, 97, 108, 105, 118, 101, 13, 10, 13, 10, 123, 34, 116, 101, 120, 116, 34, 58, 32, 34, 97, 104, 45, 82, 65, 72, 78, 45, 101, 101, 45, 97, 32, 69, 75, 83, 45, 115, 117, 45, 109, 97, 121, 34, 44, 32, 34, 118, 97, 108, 117, 101, 34, 58, 32, 91, 34, 97, 34, 44, 32, 34, 104, 34, 44, 32, 34, 45, 34, 44, 32, 34, 82, 34, 44, 32, 34, 65, 34, 44, 32, 34, 72, 34, 44, 32, 34, 78, 34, 44, 32, 34, 45, 34, 44, 32, 34, 101, 34, 44, 32, 34, 101, 34, 44, 32, 34, 45, 34, 44, 32, 34, 97, 34, 44, 32, 34, 32, 34, 44, 32, 34, 69, 34, 44, 32, 34, 75, 34, 44, 32, 34, 83, 34, 44, 32, 34, 45, 34, 44, 32, 34, 115, 34, 44, 32, 34, 117, 34, 44, 32, 34, 45, 34, 44, 32, 34, 109, 34, 44, 32, 34, 97, 34, 44, 32, 34, 121, 34, 93, 44, 32, 34, 105, 100, 34, 58, 32, 34, 100, 97, 102, 102, 52, 54, 97, 101, 45, 50, 56, 102, 50, 45, 52, 51, 55, 57, 45, 97, 56, 99, 100, 45, 57, 56, 57, 50, 53, 98, 55, 48, 57, 50, 54, 54, 34, 125])
1521821066912	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 518])
1521821066912	hyper::http::h1	TRACE	Request.try_parse Complete(311)
1521821066912	hyper::header	TRACE	raw header: "Host"=[49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 53, 56, 49, 52, 53]
1521821066912	hyper::header	TRACE	raw header: "Accept-Encoding"=[105, 100, 101, 110, 116, 105, 116, 121]
1521821066912	hyper::header	TRACE	raw header: "Content-Length"=[50, 48, 55]
1521821066912	hyper::header	TRACE	raw header: "Accept"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110]
1521821066912	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 85, 84, 70, 45, 56]
1521821066912	hyper::header	TRACE	raw header: "User-Agent"=[80, 121, 116, 104, 111, 110, 32, 104, 116, 116, 112, 32, 97, 117, 116, 104]
1521821066912	hyper::header	TRACE	raw header: "Connection"=[107, 101, 101, 112, 45, 97, 108, 105, 118, 101]
1521821066912	hyper::server::request	DEBUG	Request Line: Post AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/element/daff46ae-28f2-4379-a8cd-98925b709266/value") Http11
1521821066912	hyper::server::request	DEBUG	Headers { Host: 127.0.0.1:58145
, Accept-Encoding: identity
, Content-Length: 207
, Accept: application/json
, Content-Type: application/json;charset=UTF-8
, User-Agent: Python http auth
, Connection: keep-alive
, }
1521821066912	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1521821066912	hyper::http::h1	TRACE	Sized read, remaining=207
1521821066912	hyper::http::h1	TRACE	Sized read: 32
1521821066912	hyper::http::h1	TRACE	Sized read, remaining=175
1521821066912	hyper::http::h1	TRACE	Sized read: 64
1521821066912	hyper::http::h1	TRACE	Sized read, remaining=111
1521821066912	hyper::http::h1	TRACE	Sized read: 111
1521821066912	hyper::http::h1	TRACE	Sized read, remaining=0
1521821066912	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/3035362d-3350-46a9-bd40-dd07a88be6b3/element/daff46ae-28f2-4379-a8cd-98925b709266/value")
1521821066913	webdriver::command	DEBUG	Got request body {"text": "ah-RAHN-ee-a EKS-su-may", "value": ["a", "h", "-", "R", "A", "H", "N", "-", "e", "e", "-", "a", " ", "E", "K", "S", "-", "s", "u", "-", "m", "a", "y"], "id": "daff46ae-28f2-4379-a8cd-98925b709266"}
1521821066913	geckodriver::marionette	DEBUG	→ 173:[0,4,"sendKeysToElement",{"id":"daff46ae-28f2-4379-a8cd-98925b709266","value":["a","h","-","R","A","H","N","-","e","e","-","a"," ","E","K","S","-","s","u","-","m","a","y"]}]
1521821066914	Marionette	TRACE	0 -> [0,4,"sendKeysToElement",{"id":"daff46ae-28f2-4379-a8cd-98925b709266","value":["a","h","-","R","A","H","N","-","e","e","-","a"," ","E","K","S","-","s","u","-","m","a","y"]}]
1521821066916	Marionette	TRACE	0 <- [1,4,{"error":"invalid argument","message":"Expected [object Undefined] undefined to be a string","stacktrace":"WebDriverErro ... et@chrome://marionette/content/server.js:505:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1521821066916	geckodriver::marionette	DEBUG	← [1,4,{"error":"invalid argument","message":"Expected [object Undefined] undefined to be a string","stacktrace":"WebDriverError@chrome://marionette/content/error.js:172:5\nInvalidArgumentError@chrome://marionette/content/error.js:299:5\nassert.that/<@chrome://marionette/content/assert.js:407:13\nassert.string@chrome://marionette/content/assert.js:316:10\nGeckoDriver.prototype.sendKeysToElement@chrome://marionette/content/driver.js:2512:14\ndespatch@chrome://marionette/content/server.js:557:20\nexecute@chrome://marionette/content/server.js:531:11\nonPacket/<@chrome://marionette/content/server.js:506:15\nonPacket@chrome://marionette/content/server.js:505:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1521821066916	webdriver::server	DEBUG	Returning status BadRequest
1521821066917	webdriver::server	DEBUG	Returning body {"value":{"error":"invalid argument","message":"Expected [object Undefined] undefined to be a string","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x43b0b5 - <no info>\n   3:           0x420313 - <no info>\n   4:           0x408307 - <no info>\n   5:           0x6750f9 - <no info>\n   6:           0x416877 - <no info>\n   7:           0x66ed53 - <no info>\n   8:     0x7ffa3e671fe4 - BaseThreadInitThunk"}}
1521821066917	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1521821066917	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1521821066917	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(487) )
1521821066917	hyper::server::response	DEBUG	writing head: Http11 BadRequest
1521821066917	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 26, tm_min: 4, tm_hour: 16, tm_mday: 23, tm_mon: 2, tm_year: 118, tm_wday: 5, tm_yday: 81, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 917419300 })) )
1521821066917	hyper::server::response	DEBUG	headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 487
, Date: Fri, 23 Mar 2018 16:04:26 GMT
, }]
1521821066917	hyper::server::response	DEBUG	write 487 bytes
1521821066917	hyper::server::response	TRACE	ending
1521821066917	hyper::server	DEBUG	keep_alive = false for 127.0.0.1:58300
1521821066917	hyper::server	DEBUG	keep_alive loop ending for 127.0.0.1:58300
1521821066934	Marionette	DEBUG	Closed connection 0

**Comment by whimboo** [comment]
This is not a supported version of geckodriver you are using here with Firefox 59. You said it's 20.0 but it isn't. Make sure that the path is correct, and not a different binary exists on your system in a path looked into first.

> 1521821066914 Marionette TRACE 0 -> [0,4,"sendKeysToElement",{"id":"daff46ae-28f2-4379-a8cd-98925b709266","value":["a","h","-","R","A","H","N","-","e","e","-","a"," ","E","K","S","-","s","u","-","m","a","y"]}]

Here the `value` property is used which which isn't checked anymore since Firefox 53. So I assume the used geckodriver binary is pre 18.0.
