### ISSUE TITLE
Cannot run Marionette with Firefox 47

### ISSUE THREAD

**Issue by louis57** [mozilla/geckodriver#123]
I am trying to using Marionette with FF 47, but I am not successful.

I followed the instructions on Mozilla Developer Network, here [https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver](url). I did step by step as follow:
1. Install selenium-webdriver with `npm install selenium-webdriver`
2. Download `geckodriver-0.8.0-OSX.gz`, unrar it, and rename it to `wires` as instructed in the link above. And I ensure it is executable with `chmod +x wires`
3. I write this in my code
`DesiredCapabilities capabilities = DesiredCapabilities.firefox();`
`capabilities.setCapability("marionette", true); `
`Webdriver driver = new FirefoxDriver(capabilities);`

But when I run the test, the same exception happens like when I used FirefoxDriver with FF47. A pop up says: Firefox quit unexpectedly. and this is log from IntelliJ

> org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
8-4474-a285-3208198ce6fd}","syncGUID":"bzOZ-mKAmGiQ","location":"app-global","version":"47.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1465552260000,"updateDate":1465552260000,"applyBackgroundUpdates":1,"skinnable":true,"size":7134,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"47.0","maxVersion":"47.0"}],"targetPlatforms":[],"seen":true}
1467199905301	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467199905302	DeferredSave.extensions.json	DEBUG	Save changes
1467199905302	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1467199905302	addons.xpi-utils	DEBUG	Updating add-on states
1467199905305	addons.xpi-utils	DEBUG	Writing add-ons list
1467199905308	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1467199905308	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1467199905308	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1467199905309	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.2
1467199905310	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1467199905311	addons.xpi	DEBUG	Calling bootstrap method startup on loop@mozilla.org version 1.3.2

Am I missing something? Can someone please help? Thanks.

**My environment:**
OS: Mac Capitan
Browser: Firefox 47
Language: Java

**Comment by andreastt** [comment]
Firefox 47 is not supported by geckodriver. You should consider trying the [latest Nightly](http://nightly.mozilla.org/), and increasing verbosity of your logs by setting the environment variable `RUST_LOG=debug`. If you compile the latest geckodriver from master (unreleased), it will additionally have a `-vv` flag to increase the output from Firefox.
