### ISSUE TITLE
Firefox 61 InvalidArgumentException: Message: File not found

### ISSUE THREAD

**Issue by lucfortunato** [mozilla/geckodriver#1230]
## System

* Version: 0.20
* Platform: Windows
* Firefox: Nightly 61.0a1
* Selenium: 3.8.1

## Testcase

When I try to send the sendkeys command to upload a file I get this error:

> selenium.common.exceptions.InvalidArgumentException: Message: File not found: E: /audio.mp3

On chrome it works great, I've seen that this problem has been found by other users in the old versions of firefox and that it has been fixed, but to me the problem persists.

## Stacktrace

> Traceback (most recent call last):
>   File "C:\Users\Luca\Desktop\pyBaiduSpeechRecognition-master\pyBaiduSpeechRecognitionAPI.py", line 26, in <module>
>     driver.find_element_by_xpath("//input[@type='file']").send_keys("E:/audio.mp3")
>   File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 479, in send_keys
>     'value': keys_to_typing(value)})
>   File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
>     return self._parent.execute(command, params)
>   File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Luca\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidArgumentException: Message: File not found: E:/audio.mp3

## Trace-level log

No error in log.
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1844849/geckodriver.log)

**Comment by whimboo** [comment]
@lucfortunato what caused the issue to be closed? Maybe you can give more details? Thanks.
