### ISSUE TITLE
WebDriverException - java.io.InterruptedIOException: thread interrupted

### ISSUE THREAD

**Issue by GlouFAC** [mozilla/geckodriver#1234]
## System

* Version: 0.20.0
* Platform: Linux64 + Ubuntu Server 17.10 
* Firefox: Firefox-58.0.2
* Selenium: Client-combined 3.11.0
* Java: JRE 1.8.0_161-b12

## Testcase

      try {
            System.setProperty("webdriver.gecko.driver", "/PathGD/geckodriver");
            System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE, "true");
            System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE, "Log.txt");
            WebDriver driver = new FirefoxDriver();

            // Open the Application
            driver.get("https://github.com/");
            JavascriptExecutor js = (JavascriptExecutor) driver;

        } catch (SessionNotCreatedException sNEx) {
            System.out.println("SessionNotCreatedException - " + sNEx.getMessage());
        } catch (ScriptTimeoutException stEx) {
            System.out.println("ScriptTimeoutException - " + stEx.getMessage());
        } catch (JavascriptException jEx) {
            System.out.println("JavascriptException - " + jEx.getMessage());
        } catch (TimeoutException tEx) {
            System.out.println("TimeoutException - " + tEx.getMessage());
        } catch (UnableToCreateProfileException utcpEx) {
            System.out.println("UnableToCreateProfileException - " + utcpEx.getMessage());
        } catch (WebDriverException wdEx) {
            System.out.println("WebDriverException - " + wdEx.getMessage());
        } catch (Exception ex) {
            System.out.println("Exception - " + ex.getMessage());
        }

## Stacktrace

WebDriverException - java.io.InterruptedIOException: thread interrupted
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:08.638Z'
System info: host: 'usertest', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-21-generic', java.version: '1.8.0_161'
Driver info: driver.version: FirefoxDriver

## Trace-level log

1522192591209   geckodriver     INFO    geckodriver 0.20.0
1522192591214   geckodriver     INFO    Listening on 127.0.0.1:27358

**Comment by andreastt** [comment]
A [`java.io.InterruptedIOException`](https://docs.oracle.com/javase/7/docs/api/java/io/InterruptedIOException.html) means something interrupted the thread you are running this code in. It is not something caused by geckodriver, but other code in your Java program.
