### ISSUE TITLE
facing Protocol handshake issue

### ISSUE THREAD

**Issue by SelvaGanesh3027** [mozilla/geckodriver#1237]
## System

* Version: 0.20.0
* Platform: Windows 10
* Firefox: Firefox Quantum
* Selenium: Oxygen.2 Release (4.7.2)

## Testcase
Trying to open a web browser using Testng but im getting an error of Protocol handshake connection, while the browser gets opened but the link doesnt get opened

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by SelvaGanesh3027** [comment]
sorry to ask but from where will I get this? or can I get this ?

**Comment by andreastt** [comment]
Did you see the links in my last comment?

**Comment by SelvaGanesh3027** [comment]
yes, i could see a link in trace-log

**Comment by whimboo** [comment]
There is nothing we can do for this issue unless the trace log is provided.
