### ISSUE TITLE
Unable to read VR Path Registry from 

### ISSUE THREAD

**Issue by lolaika** [mozilla/geckodriver#1239]
## System

* Version: geckodriver-v0.20.0-win64
* Platform: Windows 10 Home Single Language
* Firefox: 59.0.2 (64-bits)
* Selenium: selenium-java-3.11.0

## Testcase
I don't know why is happening this "Unable to read VR Path Registry from" and I've tried several solutions posted here. Someone can help me to figure out what is happening? Thanks!

<code>
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class firstTry {

   public static void main (String [] args){
       WebDriver driver = new FirefoxDriver();
   }
}
</code>

## Stacktrace

<code> 
1522648293354	geckodriver	INFO	geckodriver 0.20.0
1522648293391	geckodriver	INFO	Listening on 127.0.0.1:20559
1522648294843	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\Lolaika\\AppData\\Local\\Temp\\rust_mozprofile.m2GmnRWCOc9A"
Unable to read VR Path Registry from C:\Users\Lolaika\AppData\Local\openvr\openvrpaths.vrpath
1522648297128	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\Lolaika\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Lolaika\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Lolaika\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Lolaika\AppData\Local\openvr\openvrpaths.vrpath
1522648302360	Marionette	INFO	Listening on port 54428
1522648303620	Marionette	WARN	TLS certificate errors will be ignored for this session
abr 02, 2018 12:51:43 A.M. org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMACIÓN: Detected dialect: W3C
</code>

**Comment by andreastt** [comment]
The warning you see comes from Firefox and is nothing to worry about, but it does look like your Firefox crashes on shutdown. Can you please provide a link to the crash log submitted? It should be available in about:crashes.

**Comment by whimboo** [comment]
No, the crash is not available through `about:crashes` because the crash reporter is not enabled for any automation driver, and that also applies to geckodriver. Also nothing in the above log shows me that there is a potential crash of Firefox. @lolaika can you please attach a full [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html)? Thanks.

**Comment by DanielRuf** [comment]
I get the exact same error.

**Comment by whimboo** [comment]
No response from reporter for 1.5 months. So closing this issue.

**Comment by DanielRuf** [comment]
Hm well but I got it today with the update to release 60 of Firefox on macOS.

**Comment by whimboo** [comment]
@DanielRuf you didn't say any details nor what we requested to have actually an actionable issue. If it's just the "Unable to read VR Path Registry from" message in the log, it shouldn't cause any harm. 

So if you have something to add please do so. See my comment from Apr 3rd. Thanks.

**Comment by DanielRuf** [comment]
> If it's just the "Unable to read VR Path Registry from" message in the log, it shouldn't cause any harm.

Ok but it is new and annoying =/

**Comment by whimboo** [comment]
This is fixed in latest Firefox 62.0 Nightly builds. So if it annoys you please consider to temporarily use Nightly for development. See https://bugzilla.mozilla.org/show_bug.cgi?id=1373279.

**Comment by tonyaveniros** [comment]
Try upgrading to the latest chromedriver/ firefoxdriver http://chromedriver.chromium.org/downloads. I had the same issues and this cleared them up.

**Comment by DanielRuf** [comment]
Or cpuld have been that prevented by some extra unit tests? If so I would be glad to know where and how I could contribute those.
