### ISSUE TITLE
element.clear triggers the onchange event in Firefox 59

### ISSUE THREAD

**Issue by jpatel13** [mozilla/geckodriver#1240]
## System

* Version: 
* Platform: 
* Firefox: <! --  59 -->
* Selenium: 

## Testcase
1 http://mail.ff-qa.com 
2. call clear on the user name element 
      include PageObject
      page_url @@base_url

      text_field(:username, id: 'rcmloginuser')
      text_field(:password, id: 'rcmloginpwd')
      checkbox(:shared, id: 'session_expire')
      checkbox(:steyon, id: 'persist')
      button(:login, xpath: '//*[@id="login-form"]/div[2]/form/p/input')
      button(:exit, xpath: '//*[@id="login-form"]/div[2]/input')
      div(:message, id: 'message')
      div(:find_error) {message_element.div_element(class: 'warning')}
      div(:error) {message_element.div_element(class: 'error')}

      def signin(options)
       username_element.clear 
      end

Issue: When clear is called on the username text field the onchange event is triggered. 

Expected: onchange should not be triggered when clear is called on textfield 

## Trace-level log
24:07.122 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@d2730d4
13:24:07.126 INFO - Handler thread for session 62285e20-7de1-4754-972d-ab43c5a9a14b (firefox): Executing POST on /session/62285e20-7de1-4754-972d-ab43c5a9a14b/element/655f9462-7685-4d55-9a84-d944a4d19bd2/clear (handler: ServicedSession)
13:24:07.129 INFO - To upstream: {}
13:24:07.139 INFO - To downstream: {"value": {}}

**Comment by andreastt** [comment]
This is expected behaviour. See https://bugzilla.mozilla.org/show_bug.cgi?id=1430571.

However, on a second reading of https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-clear I don’t actually see this being called out in the specification. Filed https://github.com/w3c/webdriver/issues/1247 to align it with Gecko.

**Comment by jpatel13** [comment]
Hi Andreastt, 

 I reviewed the bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1430571. The issue is asking that the onchange event be fired when a non-empty text field is clear and not to fire a onchange event when clear is call on an empty textfield (Appologies my example wasn't clear). I think the fix is too broad and should only apply to the case where the field has a value. My case where value is "" should not trigger on change.  This breaks my situation where clear will cause the domain to get populated before the actual value is set. 
Thanks!

**Comment by andreastt** [comment]
I fixed that problem with https://github.com/w3c/webdriver/commit/bc32d801107b445a3268653671732d83b3dfac1f, and that was subsequently fixed in Gecko in https://bugzilla.mozilla.org/show_bug.cgi?id=1430575.
