### ISSUE TITLE
Firefox.exe an application error is popping up while closing selenium session.

### ISSUE THREAD

**Issue by ssaurav-1987** [mozilla/geckodriver#1244]
I am a setup for the automation where I am trying to use Firefox Gecko Driver for the UI automation.
But after completing 1 test case and selenium session is getting closed then I am getting one applicatiojn error popup and details of this pop up is like this :

Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	52.7.3.6655
  Application Timestamp:	5ab42cff
  Fault Module Name:	mozglue.dll
  Fault Module Version:	52.7.3.6655
  Fault Module Timestamp:	5ab42cf1
  Exception Code:	80000003
  Exception Offset:	0000000000011351
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	16393
  Additional Information 1:	8406
  Additional Information 2:	84066008ed393277e1a1a51b9b1b869c
  Additional Information 3:	2b31
  Additional Information 4:	2b31a8a1d7c97ecf7f0c2a57ee3a1b58

Below is the system details which I have
## System

* Version: geckodriver-v0.15.0-win64
* Platform: Windows Server 2012 R2
* Firefox: 52.7.3.6655
* Selenium: 3.3.1

Please help me here how to sortout this issue. I have seen one post for this issue but it is locked and closed due to lock I am not able to see any solution on this.

**Comment by whimboo** [comment]
Please upgrade geckodriver to the latest release and make use of a recent Firefox release too. The versions you are using are very outdated. If you have to use the ESR release, we might have to check which kind of Firefox crash you are experiencing here. 

In such a case please attach a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) for now, so that we can see for which test code it is failing.

**Comment by ssaurav-1987** [comment]
@whimboo Thanks for giving information here, but actually we have to use the same firefox version which have mentioned above also the selenium driver 3.3.1 need to use so based on that I tried lot of combination, but finally this worked that with this gecko driver version firefox instance is opening and performing the automation, and during the closing of session of selenium this issue is occuring. We have centos7.4 in our product which we have upgraded based on that we have firefox 52.7.3.6655 version. This is the restriction with us.

**Comment by whimboo** [comment]
In the original comment you wrote Windows, and now you are using CentOS. So on which platforms you see that problem?

For now I will give you two links to debug builds of Firefox build from the ESR52 branch. Depending on if you need 32bit or 64bit, select the correct one:

https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-esr52-win32-debug/1523219688/firefox-52.7.4.en-US.win32.zip
https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-esr52-win64-debug/1523219688/firefox-52.7.4.en-US.win64.zip

Just unzip the appropriate archive and use that version of Firefox instead. And then provide the trace logs as already requested in my last comment.

**Comment by ssaurav-1987** [comment]
We have both environment where we have to test. Ok I will check and will inform you about this.
Thanks for the link which you shared

**Comment by whimboo** [comment]
No response from reporter => closing issue.
