### ISSUE TITLE
Cannot set proxy for firefox through geckodriver

### ISSUE THREAD

**Issue by blutester** [mozilla/geckodriver#1245]
## System

* Version: 0.20.1
* Platform: macOS
* Firefox: 59.0.2
* Selenium: 3.11.0

## Testcase

I have been trying to set proxy for Firefox, but no matter what I do, that configuration doesn't seem to have any effect.

Best I can tell, this code should be correct:

        String PROXY = "localhost:8081"
        JsonArray NOPROXY = new JsonArray()
        DesiredCapabilities capabilities = new DesiredCapabilities()
        JsonObject json = new JsonObject()
        json.addProperty("proxyType", "manual")
        json.addProperty("httpProxy", "localhost:8081")
        json.addProperty("sslProxy", "localhost:8081")
        json.addProperty("noProxy", NOPROXY)
        capabilities.setCapability("proxy", json)
        FirefoxOptions options = new FirefoxOptions(capabilities)
        driver = new FirefoxDriver(options)

I can see that my proxy server is up. And I can manually configure firefox to use it.

## Stacktrace

N/A

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment]
Also which binding are you using? Please note that not all bindings have been updated yet to make use of a list for `noProxy`. See https://github.com/SeleniumHQ/selenium/issues/5004.

**Comment by bdellegrazie** [comment]
Also this: https://github.com/SeleniumHQ/selenium/issues/5627
Its where the hostname is set correctly but the port is not.

**Comment by whimboo** [comment]
@bdellegrazie please don't hijack other issues. Instead file a new one with all the details as requested included. Thanks.

Given that we haven't heard from the original reporter I'm going to close this issue.

**Comment by rat03nesh** [comment]
In am not able to select auto detect proxy for firefox61 and using selenium 3.14

**Comment by rat03nesh** [comment]
Cannot set proxy for firefox through geckodriver still the issue exist with selenium 3.14 and gecko.21 and firefox61

**Comment by whimboo** [comment]
@rat03nesh you didn't provide any steps nor details. As such there is nothing we can act on. If you have a problem file a new issue with all the requested information. This issue is closed.
