### ISSUE TITLE
unable to open Firefox URL

### ISSUE THREAD

**Issue by fims710** [mozilla/geckodriver#1246]
## System

* Version: 0.18\0.19\0.20\0.20.1 (32)
* Platform: Windows2008R2SP1
* Firefox: 56.0.2/57.0.4/58.0.2/59.0.2 (32)
* Selenium: selenium-webdriver-3.11

## Testcase

Selenium::WebDriver.logger.level = :debug
            opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
            @driver = Selenium::WebDriver.for :firefox, options: opts
            Browser.new(@driver).openBrowser(:value => 'https://172.21.11.175:8443')

## Trace-level log

2018-04-10 10:37:39 DEBUG Selenium Executing Process ["C:/Tools/geckodriver.exe", "--binary=C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe", "--port=4444"]
1523327859531	geckodriver	INFO	geckodriver 0.20.1 (685f18325cea0a282c736e65972f95aa6db7ca48 2018-04-03)
1523327859538	geckodriver	INFO	Listening on 127.0.0.1:4444
2018-04-10 10:37:39 INFO Selenium Skipping handshake as we know it is W3C.
2018-04-10 10:37:39 INFO Selenium -> POST session
2018-04-10 10:37:39 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}},"acceptInsecureCerts":true},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}},"acceptInsecureCerts":true}]}}
2018-04-10 10:37:39 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"301"}
1523327860000	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\3\\rust_mozprofile.A4PyjosaIdvC"
1523327860011	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
1523327860340	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1523327860669	Marionette	DEBUG	Received observer notification "profile-after-change"
1523327860892	Marionette	DEBUG	Received observer notification "command-line-startup"
1523327860893	Marionette	INFO	Enabled via --marionette
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 370: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIScriptSecurityManager.getLoadContextCodebasePrincipal]
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 370: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIScriptSecurityManager.getLoadContextCodebasePrincipal]
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
Extension error: [Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionParent.jsm :: _onExtensionBrowser :: line 346"  data: no] undefined 346
[[Exception stack
_onExtensionBrowser@resource://gre/modules/ExtensionParent.jsm:346:7
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:61:14
emit/promises<@resource://gre/modules/ExtensionUtils.jsm:256:55
emit@resource://gre/modules/ExtensionUtils.jsm:255:20
build@chrome://extensions/content/ext-backgroundPage.js:41:5
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
emit/promises<@resource://gre/modules/ExtensionUtils.jsm:256:55
emit@resource://gre/modules/ExtensionUtils.jsm:255:20
build@chrome://extensions/content/ext-backgroundPage.js:41:5
]]
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 370: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIScriptSecurityManager.getLoadContextCodebasePrincipal]
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 243: TypeError: frameLoader.tabParent is null
[Parent 5796] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 604
1523327862383	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1523327882634	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: timeout
C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/marionette/driver.rb:56:in `initialize'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:32:in `new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:32:in `new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
	from D:/AW调试.rb:120:in `<main>'

1523500953818	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: timeout
1523500995908	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
1523501086654	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by whimboo** [comment]
The above log is a trace log, but it seems that it has been cut-off at the end. Please attach a full log. Also it looks like Firefox has numerous problems in several components due to files not being found. But to say more I need the full trace log.

**Comment by fims710** [comment]
edited the log, there's no more, just stuck at the last words.
tried for more information: 
1, change the platform to win7, it works fine
2, on Platform Windows2008R2SP1 , it only works at firefox 52&geckodriver 0.15 ,  the newer version all get the same error.

But i need to work on Windows2008R2SP1 and the latest firefox& geckodriver

**Comment by whimboo** [comment]
@fims710 how are you running the tests? Just as a normal command in a current user session, or as Windows task or even as a service?

**Comment by fims710** [comment]
run the tests with cmd command or our own ruby compiler , not as windows task or service .
is it possible that the latest firefox& geckodriver is incompatible with win2008R2sp1 ?
have no idea what to do now...

**Comment by whimboo** [comment]
@fims710 please reinstall Firefox. Maybe it is a broken installation? When you do that please keep the installed files around. Thanks.

**Comment by fims710** [comment]
reinstalled Firefox and reboot the system many times , still can not work.

**Comment by whimboo** [comment]
So please run a debug build of Firefox Nightly and attach the trace log while running the tests:

Windows 32bit: https://queue.taskcluster.net/v1/task/PHxm530uTkmHSSnOedD42A/runs/0/artifacts/public/build/target.zip
Windows 64bit: https://queue.taskcluster.net/v1/task/S1-feyaGQOy1QH7SlqKuNg/runs/0/artifacts/public/build/target.zip

Just download the type of binary for your platform, unzip the archive, and directly run via Selenium.

**Comment by fims710** [comment]
run with 32bit Firefox Nightly, and can not open the firefox window.

2018-04-17 19:32:20 DEBUG Selenium Executing Process ["C:/Tools/geckodriver.exe", "--binary=D:/firefox/firefox.exe", "--port=4444"]
1523964740396	geckodriver	INFO	geckodriver 0.20.1 (685f18325cea0a282c736e65972f95aa6db7ca48 2018-04-03)
1523964740404	geckodriver	INFO	Listening on 127.0.0.1:4444
2018-04-17 19:32:20 INFO Selenium Skipping handshake as we know it is W3C.
2018-04-17 19:32:20 INFO Selenium -> POST session
2018-04-17 19:32:20 INFO Selenium    >>> http://127.0.0.1:4444/session | {"desiredCapabilities":{"browserName":"firefox","marionette":true,"timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}},"acceptInsecureCerts":true},"capabilities":{"firstMatch":[{"browserName":"firefox","timeouts":{},"moz:firefoxOptions":{"log":{"level":"trace"}},"acceptInsecureCerts":true}]}}
2018-04-17 19:32:20 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=utf-8", "Content-Length"=>"301"}
1523964740854	mozrunner::runner	INFO	Running command: "D:/firefox/firefox.exe" "-marionette" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.hHf8FiADWKfp"
1523964740865	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
[3680, Main Thread] WARNING: Failed to load startupcache file correctly, removing!: file z:/build/build/src/startupcache/StartupCache.cpp, line 217
1523964743132	Marionette	DEBUG	Received observer notification profile-after-change
[3680, Main Thread] WARNING: NS_ENSURE_SUCCESS(rv, rv) failed with result 0x80520012: file z:/build/build/src/extensions/cookie/nsPermissionManager.cpp, line 2910
++DOCSHELL 19D99C00 == 1 [pid = 3680] [id = {97b3bdf0-babe-4ea3-b073-affecbff6070}]
++DOMWINDOW == 1 (0EAAF800) [pid = 3680] [serial = 1] [outer = 00000000]
[3680, Main Thread] WARNING: 'NS_FAILED(rv)', file z:/build/build/src/widget/windows/nsLookAndFeel.cpp, line 847
++DOMWINDOW == 2 (19D9AC00) [pid = 3680] [serial = 2] [outer = 0EAAF800]
[3680, Main Thread] WARNING: DWM not enabled, falling back to software vsync: file z:/build/build/src/gfx/thebes/gfxWindowsPlatform.cpp, line 1969
1523964743362	Marionette	DEBUG	Received observer notification command-line-startup
1523964743363	Marionette	DEBUG	Received observer notification nsPref:changed
++DOCSHELL 19D96800 == 2 [pid = 3680] [id = {8036ced1-e76c-4ae6-8e79-0fb905de0fe9}]
++DOMWINDOW == 3 (0EAAFE40) [pid = 3680] [serial = 3] [outer = 00000000]
++DOMWINDOW == 4 (0F21D800) [pid = 3680] [serial = 4] [outer = 0EAAFE40]
++DOCSHELL 0F21FC00 == 3 [pid = 3680] [id = {75069b59-569b-4fbc-8f61-62b6d5060b93}]
++DOMWINDOW == 5 (0EAB0200) [pid = 3680] [serial = 5] [outer = 00000000]
++DOMWINDOW == 6 (0F220800) [pid = 3680] [serial = 6] [outer = 0EAB0200]
[3680, Main Thread] WARNING: NS_ENSURE_SUCCESS(rv, rv) failed with result 0x80040111: file z:/build/build/src/netwerk/protocol/res/SubstitutingProtocolHandler.cpp, line 338
[3680, Main Thread] WARNING: 'NS_FAILED(GetAccentColor(unused))', file z:/build/build/src/widget/windows/nsLookAndFeel.cpp, line 473
++DOMWINDOW == 7 (0F22C400) [pid = 3680] [serial = 7] [outer = 0EAAFE40]
++DOCSHELL 1D5CB000 == 4 [pid = 3680] [id = {0883b751-82a5-474c-847f-8bcee35ae6ba}]
++DOMWINDOW == 8 (0EAB0480) [pid = 3680] [serial = 8] [outer = 00000000]
++DOCSHELL 1D5CB400 == 5 [pid = 3680] [id = {1b51d8b5-00eb-403e-9f2c-ed5966f3da1e}]
++DOMWINDOW == 9 (1E03DC00) [pid = 3680] [serial = 9] [outer = 00000000]
[Parent 3680, Gecko_IOThread] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 559
Assertion failure: mOtherPidState == ProcessIdState::eReady, at z:/build/build/src/ipc/glue/ProtocolUtils.cpp:621
#01: soundtouch::SoundTouch::operator=[D:\firefox\xul.dll +0xed73f6]
#02: mozilla_dump_image[D:\firefox\xul.dll +0x258dd3c]
#03: mozilla_dump_image[D:\firefox\xul.dll +0x2589ac8]
#04: mozilla_dump_image[D:\firefox\xul.dll +0x2586186]
#05: mozilla_dump_image[D:\firefox\xul.dll +0x179cbeb]
#06: mozilla_dump_image[D:\firefox\xul.dll +0x179858d]
#07: mozilla_dump_image[D:\firefox\xul.dll +0x179804f]
#08: DumpFrameArray[D:\firefox\xul.dll +0x2a0ba79]
#09: DumpFrameArray[D:\firefox\xul.dll +0x2a0a113]
#10: mozilla_dump_image[D:\firefox\xul.dll +0x16726d4]
#11: mozilla_dump_image[D:\firefox\xul.dll +0x176d93b]
#12: mozilla_dump_image[D:\firefox\xul.dll +0x21690b6]
#13: mozilla_dump_image[D:\firefox\xul.dll +0x1660080]
#14: mozilla_dump_image[D:\firefox\xul.dll +0x19321ea]
#15: mozilla_dump_image[D:\firefox\xul.dll +0x1eb3232]
#16: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0e04]
#17: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b867d]
#18: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b83ad]
#19: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0b34]
#20: XRE_GetBootstrap[D:\firefox\xul.dll +0x3d0a3f6]
#21: XRE_GetBootstrap[D:\firefox\xul.dll +0x3c7338b]
#22: XRE_GetBootstrap[D:\firefox\xul.dll +0x3c7bd84]
#23: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0e04]
#24: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b85ae]
#25: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b83ad]
#26: XRE_GetBootstrap[D:\firefox\xul.dll +0x40bbe14]
#27: XRE_GetBootstrap[D:\firefox\xul.dll +0x40c51b5]
#28: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b8733]
#29: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b83ad]
#30: XRE_GetBootstrap[D:\firefox\xul.dll +0x40bbe14]
#31: XRE_GetBootstrap[D:\firefox\xul.dll +0x40c51b5]
#32: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b8733]
#33: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b83ad]
#34: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0b34]
#35: XRE_GetBootstrap[D:\firefox\xul.dll +0x3d0a3f6]
#36: XRE_GetBootstrap[D:\firefox\xul.dll +0x3c7338b]
#37: XRE_GetBootstrap[D:\firefox\xul.dll +0x3c7bd84]
#38: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0e04]
#39: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b85ae]
#40: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b83ad]
#41: XRE_GetBootstrap[D:\firefox\xul.dll +0x40b0b34]
#42: XRE_GetBootstrap[D:\firefox\xul.dll +0x3962ec1]
#43: mozilla_dump_image[D:\firefox\xul.dll +0x1d4e99b]
#44: mozilla_dump_image[D:\firefox\xul.dll +0x207a4d9]
#45: mozilla_dump_image[D:\firefox\xul.dll +0x2085d2b]
#46: mozilla_dump_image[D:\firefox\xul.dll +0x20866f6]
#47: mozilla_dump_image[D:\firefox\xul.dll +0x208637e]
#48: mozilla_dump_image[D:\firefox\xul.dll +0x20855f0]
#49: mozilla_dump_image[D:\firefox\xul.dll +0x20856d6]
#50: mozilla_dump_image[D:\firefox\xul.dll +0x2086859]
#51: mozilla_dump_image[D:\firefox\xul.dll +0x2082d52]
#52: mozilla_dump_image[D:\firefox\xul.dll +0x2939995]
#53: DumpFrameArray[D:\firefox\xul.dll +0x35c6b58]
#54: DumpFrameArray[D:\firefox\xul.dll +0x35d9a29]
#55: DumpJSStack[D:\firefox\xul.dll +0x12c3aac]
#56: DumpJSStack[D:\firefox\xul.dll +0x12c742c]
#57: DumpJSStack[D:\firefox\xul.dll +0x12c3d16]
#58: DumpJSStack[D:\firefox\xul.dll +0x12c57f5]
#59: ???[D:\firefox\xul.dll +0xb612e0]
#60: mozilla_dump_image[D:\firefox\xul.dll +0x161d2a6]
#61: mozilla_dump_image[D:\firefox\xul.dll +0x161cbaf]
#62: mozilla_dump_image[D:\firefox\xul.dll +0x15f589c]
#63: mozilla_dump_image[D:\firefox\xul.dll +0x15f6d9b]
#64: mozilla_dump_image[D:\firefox\xul.dll +0x15f68d2]
#65: mozilla_dump_image[D:\firefox\xul.dll +0x161602f]
#66: mozilla_dump_image[D:\firefox\xul.dll +0x160bd0c]
#67: mozilla_dump_image[D:\firefox\xul.dll +0x160bb3c]
#68: mozilla_dump_image[D:\firefox\xul.dll +0x160b984]
#69: mozilla_dump_image[D:\firefox\xul.dll +0x15f2de8]
#70: ???[D:\firefox\xul.dll +0xada720]
#71: ???[D:\firefox\xul.dll +0xae2f59]
#72: soundtouch::SoundTouch::operator=[D:\firefox\xul.dll +0xed8dc9]
#73: ???[D:\firefox\xul.dll +0xeb1b82]
#74: ???[D:\firefox\xul.dll +0xeb1b33]
#75: ???[D:\firefox\xul.dll +0xeb1810]
#76: mozilla_dump_image[D:\firefox\xul.dll +0x276d5c6]
#77: mozilla_dump_image[D:\firefox\xul.dll +0x27bd6be]
#78: workerlz4_maxCompressedSize[D:\firefox\xul.dll +0x37d45a3]
#79: workerlz4_maxCompressedSize[D:\firefox\xul.dll +0x385d710]
#80: workerlz4_maxCompressedSize[D:\firefox\xul.dll +0x385b6d2]
#81: workerlz4_maxCompressedSize[D:\firefox\xul.dll +0x385b0d5]
#82: workerlz4_maxCompressedSize[D:\firefox\xul.dll +0x3867ef7]
#83: ???[D:\firefox\firefox.exe +0x1834]
#84: ???[D:\firefox\firefox.exe +0x1441]
#85: ???[D:\firefox\firefox.exe +0x1bf1]
#86: TargetNtUnmapViewOfSection[D:\firefox\firefox.exe +0x3c775]
#87: BaseThreadInitThunk[C:\Windows\syswow64\kernel32.dll +0x1336a]
#88: RtlInitializeExceptionChain[C:\Windows\SysWOW64\ntdll.dll +0x39902]
#89: RtlInitializeExceptionChain[C:\Windows\SysWOW64\ntdll.dll +0x398d5]
1523964745067	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}}
2018-04-17 19:32:25 INFO Selenium <- {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}}
C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': Process unexpectedly closed with status 1 (Selenium::WebDriver::Error::UnknownError)
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/marionette/driver.rb:56:in `initialize'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:32:in `new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/firefox/driver.rb:32:in `new'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from C:/TestTools/impeller/lib/Ruby/lib/ruby/gems/2.2.0/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
	from D:/AW调试.rb:122:in `<main>'

**Comment by whimboo** [comment]
Does it also happen when you start Firefox yourself? As best try it via the cmd console by running: `D:\firefox\firefox.exe -attach-console`. If that causes to Firefox start fine and that you can open/close tabs and navigate to websites, please use the same command again and add `-marionette`. Does that make a difference?

**Comment by whimboo** [comment]
To explain... Firefox is having a problem to create tabs in their own process, and as such completely fail during startup and finally crash on purpose with an assertion.

**Comment by fims710** [comment]
it worked when tried via the cmd console  by running: "D:\firefox\firefox.exe -attach-console" ,and also worked with -marionette.  
can not work by running the code:
    Selenium::WebDriver::Firefox::Binary.path="D:/firefox/firefox.exe" 
    Selenium::WebDriver.logger.level = :debug
    opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace) 
    @driver = Selenium::WebDriver.for :firefox, options: opts
    Browser.new(@driver).openBrowser(:value => 'https://172.21.11.175:8443')

**Comment by whimboo** [comment]
Mind adding the output as attachment when you run firefox with `-attach-console`? I wonder if the slashes vs backslashes make a difference here. Can you change that in your script please? Usually it shouldn't.

**Comment by fims710** [comment]
@whimboo there's no difference between slashes and backslashes .
the cmd console output:
[cmd_log1.txt](https://github.com/mozilla/geckodriver/files/1934262/cmd_log1.txt)
[cmd_log2.txt](https://github.com/mozilla/geckodriver/files/1934263/cmd_log2.txt)

**Comment by whimboo** [comment]
@fims710 just to make sure the logs from the last comment are from the same build as https://github.com/mozilla/geckodriver/issues/1246#issuecomment-381956898?

**Comment by fims710** [comment]
yes, they are from the same build

**Comment by whimboo** [comment]
Hi @alex. I have seen that you worked on https://bugzilla.mozilla.org/show_bug.cgi?id=1348361 in regards of IPC and processes. Would you mind to have a look at this https://github.com/mozilla/geckodriver/issues/1246#issuecomment-381956898? Maybe you have an idea what this crash means? Maybe it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1459011?

What I wonder is why we are getting the following warning and if that causes the assertion and crash:

> [Parent 3680, Gecko_IOThread] WARNING: Failed to launch tab subprocess: file z:/build/build/src/ipc/glue/GeckoChildProcessHost.cpp, line 559

**Comment by whimboo** [comment]
@fims710 would you mind retesting with a recent debug build? Please download the `target.zip` file as listed in the panel at the bottom after opening https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=build%20debug&selectedJob=181227298. Thanks.

**Comment by whimboo** [comment]
Closing due to no reply from reporter.
