### ISSUE TITLE
Is there a way to set proxies for versions earlier than Firefox 57?

### ISSUE THREAD

**Issue by GJFR** [mozilla/geckodriver#1250]
## System

* Version: 0.19.1
* Platform: macOS 10.13.1
* Firefox: 56.0.2
* Selenium: 3.11.0

## Question

I am aware that proxies are fully supported starting from Firefox 57. However, my project includes running Firefox 56 and earlier versions inside a docker container, for which I need to set a proxy through Selenium.

I found some corresponding issues (#928, #1022), in which is answered that proxies are not _fully_ supported for these earlier versions. What does this actually mean? Is it possible to set a proxy using a workaround or is it just not possible at all?

Like in #1022, I tried with `Proxy` and `JsonObject`, which also resulted in `org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object Undefined] undefined to be an integer`.
I also tried using `setPreference()`, which appeared to do nothing.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by andreastt** [comment]
This is related to incorrect configuration, not Docker.

**Comment by GJFR** [comment]
When using

```
...
FirefoxOptions options = new FirefoxOptions();
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
JsonObject json = new JsonObject();
json.addProperty("proxyType", "manual");
json.addProperty("httpProxy", "host.docker.internal:" + proxy.getPort());
json.addProperty("sslProxy", "host.docker.internal:" + proxy.getPort());
capabilities.setCapability(CapabilityType.PROXY, json);
options.merge(capabilities);
this.driver = new RemoteWebDriver(hubAddress, options);
```

I get this [trace-level log](https://github.com/mozilla/geckodriver/files/1903834/trace.txt).

**Comment by whimboo** [comment]
We cannot fully support that through geckodriver, given that the required end-points in Marionette are just not all existent in versions of Firefox before 57.0. The only way you can do that is to basically create a new profile, and set the the proxy preferences yourself.

**Comment by andreastt** [comment]
@whimboo Sorry, which endpoint does not exist in geckodriver? I thought this was a case of a malformed proxy configuration in capabilities.

**Comment by whimboo** [comment]
Sorry, wrong wording indeed. It was malfunctioning code in handling the proxy settings through capabilities.

**Comment by andreastt** [comment]
Oh I see, this is with Firefox 56. This should indeed by resolved by upgrading, @GJFR.

**Comment by GJFR** [comment]
Thanks for the information! Will try to set the proxies myself like you suggested or maybe just use container-wide proxies.

**Comment by andreastt** [comment]
I would highly recommend you upgrade to a more recent Firefox.

**Comment by GJFR** [comment]
I understand that upgrading to Firefox 57 or higher would solve this problem. However, my project includes running tests on earlier versions, so unfortunately I do not have the freedom to use a more recent version.
