### ISSUE TITLE
Robot Framework WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by ryankempster** [mozilla/geckodriver#1252]
## System

* Version: 0.2
* Platform: Centos7
* Firefox: FF 52.6.0
* Selenium: Selenium2

## Testcase

Using Robot Framework.
----------------------------------------------------------------

*** Settings ***
Documentation  ---
Library  Selenium2Library

*** Variables ***

*** Test Cases ***
User can sign in
    Open Browser  http://localhost:8001  ff
    Close Browser

*** Keywords ***
-------------------------------------------------------------

## Stacktrace

User can sign in                                                      | FAIL |
WebDriverException: Message: connection refused

## Trace-level log

1523632391057	geckodriver	INFO	geckodriver 0.20.1
1523632391063	geckodriver	INFO	Listening on 127.0.0.1:33066
1523632392158	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.7Eorh4t9ZNhT"
1523632392403	addons.manager	DEBUG	Application has been upgraded
1523632392528	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1523632392530	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1523632392534	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1523632392536	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1523632392537	addons.manager	DEBUG	Starting provider: XPIProvider
1523632392537	addons.xpi	DEBUG	startup
1523632392537	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1523632392538	addons.xpi	INFO	Mapping aushelper@mozilla.org to /usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi
1523632392539	addons.xpi	INFO	Mapping e10srollout@mozilla.org to /usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi
1523632392539	addons.xpi	INFO	Mapping firefox@getpocket.com to /usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi
1523632392539	addons.xpi	INFO	Mapping webcompat@mozilla.org to /usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi
1523632392540	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1523632392540	addons.xpi	DEBUG	checkForChanges
1523632392540	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1523632392541	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1523632392542	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1523632392543	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1523632392543	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1523632392544	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1523632392544	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1523632392544	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1523632392545	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1523632392545	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1523632392545	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1523632392546	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1523632392546	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi","st":1516806760000},"e10srollout@mozilla.org":{"d":"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi","st":1516806760000},"firefox@getpocket.com":{"d":"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi","st":1516806760000},"webcompat@mozilla.org":{"d":"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi","st":1516806760000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1516806760000}}}
1523632392555	addons.xpi-utils	DEBUG	Opening XPI database /tmp/rust_mozprofile.7Eorh4t9ZNhT/extensions.json
1523632392556	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1523632392566	DeferredSave.extensions.json	DEBUG	Save changes
1523632392566	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1523632392569	DeferredSave.extensions.json	DEBUG	Starting timer
1523632392571	DeferredSave.extensions.json	DEBUG	Save changes
1523632392571	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1523632392579	DeferredSave.extensions.json	DEBUG	Save changes
1523632392580	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1523632392585	DeferredSave.extensions.json	DEBUG	Save changes
1523632392586	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1523632392591	DeferredSave.extensions.json	DEBUG	Save changes
1523632392591	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1523632392591	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi
1523632392596	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1523632392596	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1523632392597	DeferredSave.extensions.json	DEBUG	Save changes
1523632392597	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1523632392597	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi
1523632392599	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.10
1523632392601	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1523632392601	DeferredSave.extensions.json	DEBUG	Save changes
1523632392602	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1523632392603	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi
1523632392606	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1523632392606	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1523632392606	DeferredSave.extensions.json	DEBUG	Save changes
1523632392607	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1523632392607	addons.xpi	DEBUG	Loading bootstrap scope from /usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi
1523632392608	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1523632392608	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1523632392609	DeferredSave.extensions.json	DEBUG	Save changes
1523632392609	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1523632392609	DeferredSave.extensions.json	DEBUG	Save changes
1523632392610	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{401b4467-0342-48f3-a996-3ea7ca121120}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi","installDate":1516806760000,"updateDate":1516806760000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8488,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.6.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1523632392610	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1523632392610	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{4026c7e9-9399-450c-9ae2-9580338d7493}","location":"app-system-defaults","version":"1.10","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi","installDate":1516806760000,"updateDate":1516806760000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8145,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.6.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1523632392610	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1523632392610	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{c6db98dd-6282-4c5b-97a5-97c9e7810ce6}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi","installDate":1516806760000,"updateDate":1516806760000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920281,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.6.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1523632392611	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1523632392611	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{b794394e-7bfb-4e59-a203-97c0881f1abc}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi","installDate":1516806760000,"updateDate":1516806760000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1456,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.6.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1523632392611	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1523632392611	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{8c1f6acd-14a6-4a92-947d-538a60b5d9ce}","location":"app-global","version":"52.6.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1516806760000,"updateDate":1516806760000,"applyBackgroundUpdates":1,"skinnable":true,"size":4932,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.6.0","maxVersion":"52.6.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1523632392611	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1523632392613	DeferredSave.extensions.json	DEBUG	Save changes
1523632392613	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1523632392613	addons.xpi-utils	DEBUG	Updating add-on states
1523632392614	addons.xpi-utils	DEBUG	Writing add-ons list
1523632392615	addons.xpi	DEBUG	Registering manifest for /usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi
1523632392615	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1523632392616	addons.xpi	DEBUG	Registering manifest for /usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi
1523632392616	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.10
1523632392617	addons.xpi	DEBUG	Registering manifest for /usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi
1523632392618	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1523632392620	addons.xpi	DEBUG	Registering manifest for /usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi
1523632392621	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1523632392624	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1523632392624	addons.manager	DEBUG	Provider finished startup: XPIProvider
1523632392624	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1523632392624	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1523632392624	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1523632392625	addons.manager	DEBUG	Starting provider: GMPProvider
1523632392632	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1523632392632	addons.manager	DEBUG	Provider finished startup: GMPProvider
1523632392632	addons.manager	DEBUG	Starting provider: PluginProvider
1523632392632	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1523632392633	addons.manager	DEBUG	Provider finished startup: PluginProvider
1523632392633	addons.manager	DEBUG	Completed startup sequence
1523632392922	Marionette	INFO	Listening on port 2828
1523632392951	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1523632392951	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1523632392952	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1523632392969	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1523632392970	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1523632392970	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1523632392974	DeferredSave.extensions.json	DEBUG	Starting write
1523632393128	DeferredSave.extensions.json	DEBUG	Write succeeded
1523632393128	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1523632453823	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/52.6.0/20180124150058/Linux_x86_64-gcc3/null/default/Linux%203.10.0-693.17.1.el7.x86_64%20(GTK%203.22.10%2Clibpulse%2010.0.0)/default/default/update.xml
1523632454524	addons.productaddons	INFO	Completed downloading document
1523632454932	addons.productaddons	INFO	downloadXHR File download. status=200
1523632454935	addons.productaddons	INFO	Downloaded file will be saved to /tmp/tmpaddon
1523632494126	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 1.0
1523632494127	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1523632494128	addons.xpi	DEBUG	Calling bootstrap method shutdown on e10srollout@mozilla.org version 1.10
1523632494128	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 2.0
1523632494259	addons.manager	DEBUG	shutdown
1523632494259	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1523632494259	addons.xpi	DEBUG	shutdown
1523632494260	addons.xpi-utils	DEBUG	shutdown
1523632494261	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1523632494261	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1523632494265	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1523632494265	addons.manager	DEBUG	Calling shutdown blocker for <unnamed-provider>
1523632494273	addons.manager	DEBUG	Calling shutdown blocker for PreviousExperimentProvider
1523632494280	addons.xpi	DEBUG	Notifying XPI shutdown observers
1523632494285	addons.manager	DEBUG	Async provider shutdown done

**Comment by andreastt** [comment]
Firefox 52 is not supported. See the README for supported Firefoxen.

**Comment by whimboo** [comment]
Just to add... Firefox 52 is not supported by geckodriver 0.20.1.
