### ISSUE TITLE
Problems with xpath

### ISSUE THREAD

**Issue by KarlosMarionette** [mozilla/geckodriver#1254]
## System

* Geckodriver: geckodriver-v0.20.1-win64.zip
* Platform: windows, linux
* Firefox version:  59.0.2 
* Selenium-webdriver (3.10.0)
* Watir: (6.10.3)

## Testcase
browser.element(:xpath, "/a[contains(@class,'xpath')]//img[@alt='Logo-inner']/ancestor::a").click

## Stacktrace

If i debug ruby script ,Chrome found this xpath without any problems, firefox not.
In developer tools firefox and chrome found this xpath without problem.

**Comment by andreastt** [comment]
You haven’t actually provided any information as to what is wrong.
