### ISSUE TITLE
IPDL protocol error: [PRemotePrintJobChild] Received an invalid file descriptor!

### ISSUE THREAD

**Issue by jeffguorg** [mozilla/geckodriver#1259]
## System

* Version: 0.20.1-linux64
* Platform: Ubuntu bionic + Python(3.6.5-conda) 
* Firefox: 59.0.2 (64-bit)
* Selenium: selenium (3.11.0)(conda)

## Testcase

```https://mp.weixin.qq.com/s?__biz=MzA3MTYyODU3Ng==&mid=2649751241&idx=1&sn=68be53a4a4562fc32cee7b1f3a492dc5&chksm=8731fc86b04675902ff8557d06ed279d8f1b326546c84e45eac1a495446f2e1e4786e737c4c2&mpshare=1&scene=1&srcid=0320nLXUl37EcakhYdoVmXIi#rd```

> it's full of images, and chromium freezed when print it after load all the images

I was trying to get the url and save it to a PDF with the following code
```python
from selenium import webdriver
driver = webdriver.Firefox()
driver.get(url)
driver.execute_script("window.print()")
driver.close()
```
firefox showed up and closed but no pdf was saved. 

and then i find that every time i execute window.print() i get a line like this
```
IPDL protocol error: [PRemotePrintJobChild] Received an invalid file descriptor!
```

## Stacktrace

selenium didn't complaint anything

## Trace-level log

[geckodriver-1.get.log](https://github.com/mozilla/geckodriver/files/1926417/geckodriver-1.get.log)
[geckodriver-2.print.log](https://github.com/mozilla/geckodriver/files/1926418/geckodriver-2.print.log)

**Comment by andreastt** [comment]
To download files you should not be using geckodriver, but consider alternatives such as libcurl or your language’s HTTP request library.

Popping up `window.print()` in Firefox will probably at the moment put geckodriver into an unrecoverable state due to the fact that we don’t implement auto-dismissal of user prompts yet, but even if we were to, `window.print()` is not meant to save a file to disk.

**Comment by andreastt** [comment]
That is not a supported use case.

**Comment by whimboo** [comment]
Please note that `window.print()` opens a OS modal dialog, which is not possible to interact with Marionette / geckodriver. There is a way to override it with the preference "print.always_print_silent" which then would print the page silently with the default printer. You would only have to setup all options in a profile, and feed that into Selenium / geckodriver.
