### ISSUE TITLE
geckodriver should consume firefox_profile capability

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#126]
When geckodriver is given a `firefox_profile` capability and uses it to populate a profile to use start Firefox with, it should consume it before making creating a new session with Marionette.

Currently, when Marionette gets this, it will be included in the return value from the _New Session_ command. Whether this is the correct behaviour or not is debatable, but it’s unnecessary to pass it to Marionette in the first place.

**Comment by jgraham** [comment]
This is not actually terribly easy :) (mainly because it requires changes in the WebDriver library).

**Comment by andreastt** [comment]
Resolved by https://github.com/jgraham/webdriver-rust/pull/38.
