### ISSUE TITLE
Gecko Driver: Unable to set Preferences with latest gecko driver.

### ISSUE THREAD

**Issue by Sindhusrini** [mozilla/geckodriver#1260]
## System

- Version: geckodriver 0.20.1
- Platform: Windows10
- Firefox: 59 
- Selenium: 3.11

**# Testcase:**
Unable to Download Excel File using Firefox Profile

#
**Code:**
public static WebDriver firefoxDriverProfile() throws Exception{
		
		FirefoxProfile profile = new FirefoxProfile();
		System.setProperty("webdriver.gecko.driver", "C:\\Driver\\geckodriver.exe");
		
		profile.addExtension(new File(CommonVariables.firebugFilePath));
		profile.addExtension(new File(CommonVariables.firepathFilePath));

		profile.setPreference("browser.download.folderList", 2);
		profile.setPreference("browser.download.manager.showWhenStarting", false);
		System.out.println("Path ->" + "D:\\git\\iAAcMMINonSalesForce\\Download_File");
		profile.setPreference("browser.download.dir", System.getProperty("user.dir")+"\\Download_File");
		profile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;octet/stream");
		profile.setPreference("browser.helperApps.neverAsk.openFile", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;octet/stream");
		profile.setPreference("browser.helperApps.alwaysAsk.force", false);
		profile.setPreference("browser.download.manager.alertOnEXEOpen", false);
		profile.setPreference("browser.download.manager.focusWhenStarting", false);
		profile.setPreference("browser.download.manager.useWindow", false);
		profile.setPreference("browser.download.manager.showAlertOnComplete", false);
		profile.setPreference("browser.download.manager.closeWhenDone", true);
		profile.setPreference("pdfjs.disabled", true);

		profile.setPreference("browser.helperApps.alwaysAsk.force", false);
		profile.setPreference("browser.download.manager.alertOnEXEOpen", false);
		profile.setPreference("browser.download.manager.focusWhenStarting", false);
		profile.setPreference("browser.download.manager.useWindow", false); 	
		profile.setPreference("browser.download.manager.showAlertOnComplete", false);
		profile.setPreference("browser.download.manager.closeWhenDone", true);
		//return profile;
		//System.out.println("Browser Wait");
		//driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		 return driver = new FirefoxDriver(profile);
	}

Syntax Error :->

> Remove argument to match Firefox Driver()

**Comment by andreastt** [comment]
Unless you absolutely need a profile, it would be easier to use the `FirefoxOptions` class to add your preferences, since this avoid the overhead of sending a compressed profile over the wire.

In any case, are you sure your preferences are being set?

**Comment by whimboo** [comment]
No response from reporter => closing issue.
