### ISSUE TITLE
driver.findElement(By.linkText("Link").getText() returns "LINK" for element styled with small-caps CSS

### ISSUE THREAD

**Issue by joshlandin** [mozilla/geckodriver#1261]
## System

* Version: geckodriver-v0.20.0-64bit
* Platform: Win7 Enterprise, Also Win Server 2012R2
* Firefox: FF 59.0.2-64bit & Nightly
* Selenium: Selenium-Java 3.10.0

## Testcase

HTML
`<a href="#" style="font-variant: small-caps;">Link</a>`

Java
`driver.findElement(By.linkText("LINK"))` will fail.
`driver.findElement(By.linkText("Link"))` will pass.
`driver.findElement(By.linkText("Link")).getText()` returns "LINK", not "Link" as expected.

## Stacktrace

N/A

## Trace-level log

```
1524258650581	webdriver::server	DEBUG	-> POST /session/8a860337-d51a-4c74-ac43-eb86a9d214d6/element {"value":"Link","using":"link text"}
1524258650582	geckodriver::marionette	TRACE	-> 79:[0,121,"findElement",{"using":"link text","value":"Link"}]
1524258650580	Marionette	TRACE	0 -> [0,121,"findElement",{"using":"link text","value":"Link"}]
1524258650584	Marionette	TRACE	0 <- [1,121,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"52280d11-5e5a-4ec4-9461-e000293484b1","ELEMENT":"52280d11-5e5a-4ec4-9461-e000293484b1"}}]
1524258650588	geckodriver::marionette	TRACE	<- [1,121,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"52280d11-5e5a-4ec4-9461-e000293484b1","ELEMENT":"52280d11-5e5a-4ec4-9461-e000293484b1"}}]
1524258650588	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"52280d11-5e5a-4ec4-9461-e000293484b1"}}
1524258652732	webdriver::server	DEBUG	-> GET /session/8a860337-d51a-4c74-ac43-eb86a9d214d6/element/52280d11-5e5a-4ec4-9461-e000293484b1/text 
1524258652733	geckodriver::marionette	TRACE	-> 70:[0,122,"getElementText",{"id":"52280d11-5e5a-4ec4-9461-e000293484b1"}]
1524258652730	Marionette	TRACE	0 -> [0,122,"getElementText",{"id":"52280d11-5e5a-4ec4-9461-e000293484b1"}]
1524258652738	Marionette	TRACE	0 <- [1,122,null,{"value":"LINK"}]
1524258652742	geckodriver::marionette	TRACE	<- [1,122,null,{"value":"LINK"}]
1524258652742	webdriver::server	DEBUG	<- 200 OK {"value":"LINK"}
```

**Comment by whimboo** [comment]
I don't see why `Link` should be the expected value. For `small-caps` all letters will be converted to capital letters, whereby they are drawn smaller than capital letters. Also the `getText` command is meant to return the text as rendered (https://w3c.github.io/webdriver/webdriver-spec.html#get-element-text).

So this works as intended.

**Comment by joshlandin** [comment]
@whimboo Shouldn’t the find and the getText be consistent then? From my view, it’s expected that the find (by linkText) searches for the element as rendered as well. As such, a link text styled as uppercase “S” should be findable separately from a link with text “s” without such styling, as these two links are distinguishable by a human.

**Comment by joshlandin** [comment]
See spec section “12.1.2 Link Text“ item 3 for consistency justification.

**Comment by whimboo** [comment]
@joshlandin yes, that was a bug which I fixed about a month ago for Firefox 61. Please see issue #802.

**Comment by joshlandin** [comment]
Thanks Henrik, we'll look for it in 61 then.
