### ISSUE TITLE
NoAlertPresentException UnhandledAlertException

### ISSUE THREAD

**Issue by Nawakator** [mozilla/geckodriver#1262]
## System

* Version: 0.20.0
* Platform: Windows 10
* Firefox: 59.0.2
* Selenium: 3.11.0

## Testcase
Load page with a proxy with authentication

-- Test 1
If I set a proxy before start firefox I have a UnhandledAlertException
Firefox has on strange beahaviour. It call the authentication windows for all configured adresse in about:config. The driver crash immediatly.

-- Test 2
If I set a proxy after start firefox and before load my test page I have an NoAlertPresentException
We have external process for manage authentication windows. It work fine on Ie, Edge and Chrome. Ie manage this popup and write the correct credentials. I cannot understand why I could not say to Firefox to continue.

None of parameters in setUnhandledPromptBehaviour( ... ); dosen't work.

How to avoid Firefox to manage popups.

Regards
Eric.

## Stacktrace
-- Test 1
Session ID: a588f3e2-c990-4e73-881d-8caf314d610d
> class org.openqa.selenium.UnhandledAlertException
> org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
> org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
> org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
> org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
> org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:836)
> webdriver.driver.cDriverThread.prepareDriver(cDriverThread.java:72)
> webdriver.driver.cDriverThreadBrowserFireFox.run(cDriverThreadBrowserFireFox.java:139)

-- Test 2
Session ID: 09a1b1b0-0760-4b51-84ce-ac2e97c351c4
> class org.openqa.selenium.NoAlertPresentException
> sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
> sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
> org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
> org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
> org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
> org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
> org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:435)
> webdriver.script.thread.cThreadWdBrowser$ThreadWebDriverClose.run(cThreadWdBrowser.java:844)

## Trace-level log
DEBUG

**Comment by whimboo** [comment]
@Nawakator you haven't added any example source nor a trace log as requested when filing an issue. So I'm closing it now.

**Comment by Nawakator** [comment]
I realy do not understand. :
- you haven't added any example source 
=> Load page with a proxy with authentication It is not implicit ?
- nor a trace log as requested !
Stack trace isn' not the trace log ?

**Comment by whimboo** [comment]
>    you haven't added any example source
>   => Load page with a proxy with authentication It is not implicit ?

This is not any code. Just a verbal expression of what you are seeing, which is also unclear because I'm not sure which kind of alert you are seeing here. So add some example code, and attach images if necessary.   

> nor a trace log as requested !
>    Stack trace isn' not the trace log ?

No, as we state in the new issue comments. See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html.
