### ISSUE TITLE
 NoAlertPresentException after page loaded properly

### ISSUE THREAD

**Issue by Nawakator** [mozilla/geckodriver#1263]
System

    Version: 0.20.0
    Platform: Windows 10
    Firefox: 59.0.2
    Selenium: 3.11.0

Test case

Set a procy with credentials

oDriver.get("http://euro.insight-performance.com/");
oDriver.findElement(".//h1[contains(., 'Reference Web Site')]}");

If I set a proxy I have an NoAlertPresentException on the findElement
The page was loaded properly !
We have external process for manage authentication windows. It work fine on Ie, Edge and Chrome. Ie manage this popup and write the correct credentials. I cannot understand why I could not say to Firefox to continue.
None of parameters in setUnhandledPromptBehaviour( ... ); dosen't work.

It's so bad beacause the page was loaded but the driver seem KO (See below => Marionette threw an error: [Exception... "Component not initialized")

How to avoid driver gecko to not manage popups and continue to do the job ?

Regards
Eric.

Stacktrace java

Exception cancelled : No modal dialog is currently open
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'QOE-ERIC', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 59.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 69448, moz:profile: D:\Temp\User\rust_mozprofil..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: e46bdfcf-ef56-45a8-8597-32435ce919fa
*** Element info: {Using=xpath, value=.//h1[contains(., 'Reference Web Site')]}
> class org.openqa.selenium.NoAlertPresentException
>  > sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>  > sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>  > sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>  > java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>  > org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
>  > org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
>  > org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
>  > org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
>  > org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
>  > org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
>  > org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:319)
>  > org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:421)
>  > org.openqa.selenium.By$ByXPath.findElement(By.java:361)
>  > org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:311)
>  > webdriver.script.thread.cThreadWdBrowser$ThreadWebDriverFindElement.run(cThreadWdBrowser.java:1134)

## Trace-level log
[webdriver-firefox.log](https://github.com/mozilla/geckodriver/files/1945728/webdriver-firefox.log)

**Comment by Nawakator** [comment]
Thanks for the answer.

Same behavior with official release 60.0.1 and 61.0b9.

**Comment by whimboo** [comment]
Please attach a trace log with 61.0b9. Thanks.

**Comment by Nawakator** [comment]
Thanks for the answer.
[WD_eBench_Proxy_Fx_16_93.browser.txt](https://github.com/mozilla/geckodriver/files/2063154/WD_eBench_Proxy_Fx_16_93.browser.txt)

Same behavior with official release 60.0.1 and 61.0b9.

**Comment by Nawakator** [comment]
I do not understand but I have enable DEBUG mode.
We can see ERROR and DEBUG events in log file

**Comment by andreastt** [comment]
See https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md for documentation on enabling trace-level logs. There are some examples near the bottom.

**Comment by Nawakator** [comment]
Sorry !
This is better like that :

[WD_eBench_93.browser.txt](https://github.com/mozilla/geckodriver/files/2096863/WD_eBench_93.browser.txt)

**Comment by whimboo** [comment]
The problem here is that you are interfering the test with some outside automation utilities which is bad practice. For now it would be better to detect the alert and enter the details via `Send Alert Text`. You can separate the username/password fields by `\t` or the Tab key, which I think should fill those into both fields. Then just accept the alert.

But we should better handle that failure, and should not bail out in case the alert has already been closed.

**Comment by whimboo** [comment]
Maybe my patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1468185 will already help.

**Comment by Nawakator** [comment]
Thanks for your answer.
I'll try the SendAlertText.

But I need to re-validate this feature for each browser because it's not working very well there is some year. The focus behavior is different between browser.

For your information, I know it's bad practice, but it's very helpful and so powerful to use opencv!
...

**Comment by whimboo** [comment]
Since Firefox 62 Marionette supports the `unhandledPromptBehavior` capability. As such you can set the option you need, so alerts aren't getting closed, or errors raised.

I think that this should fix this particular issue.

**Comment by Nawakator** [comment]
Thanks for the feedback
All my firefox test work fine now.

**Comment by whimboo** [comment]
Perfect.
