### ISSUE TITLE
Can't install Geckodriver on mac

### ISSUE THREAD

**Issue by boulouboulou** [mozilla/geckodriver#1265]
## System

* Version: 
* Platform:  MacOS High Sierra 10.13.3
* Firefox:  59.0.2
* Selenium: 

## Stacktrace

/Users/nicokiri/Downloads/geckodriver ; exit;
1525141083856	geckodriver	INFO	geckodriver 0.20.1
1525141083866	geckodriver	INFO	Listening on 127.0.0.1:4444

I try to install Geckodriver on Mac but it doesn't work. The processus in Bash don't stop running and I don't have Geckodriver in /usr/local/bin.

I try to install previous version but it doesn't work neither.

Could you please help me?
Thank you!

**Comment by boulouboulou** [comment]
I try to install Geckodriver on Mac but it doesn't work. The processus in Bash don't stop running and I don't have Geckodriver in /usr/local/bin.

In Bash I have:

/Users/nicokiri/Downloads/geckodriver ; exit;
1525141083856	geckodriver	INFO	geckodriver 0.20.1
1525141083866	geckodriver	INFO	Listening on 127.0.0.1:4444

Could you please help me?
Thank you!

**Comment by andreastt** [comment]
I’m not sure I understand the question. What does not work? It looks like you get geckodriver running.

The process runs forever until it is interrupted with SIGINT. To make it available system-wide you can put it in any one of the directories listed in `PATH`, including /usr/local/bin.

**Comment by boulouboulou** [comment]
Thank you for your answer.

So I change directory to /usr/local/bin in terminal and instal Gecko driver. 

But when I try to run a script in Python 3.6 it don't see it:

Message: 'geckodriver' executable needs to be in PATH. 

Should I install it there: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ or use -m command or anything else?

Thank you very much!

**Comment by andreastt** [comment]
Well, the geckodriver executable needs to be _in_ the /usr/local/bin directory, provided that is on your system path.

**Comment by whimboo** [comment]
The downloaded geckodriver package is not a DMG nor a pkg installer. You have to extract the archive and put the binary at a location which is also listed in your PATH environment variable.
