### ISSUE TITLE
Self-signed certificates policy aka acceptInsecureCerts=false

### ISSUE THREAD

**Issue by gregall** [mozilla/geckodriver#1267]
## System

* Version:  geckodriver 0.20.1
* Platform:  Linux
* Firefox:  59.x
* Selenium:  3.11.0

## Testcase

Hi,

Is there any chance to change default value of `acceptInsecureCerts` to `True`?
I think this is more natural because when we are testing in many cases we need to add self-signed cert to browser.
After upgrade to Selenium 3.x, we need to change multiple text files, because we use own certificates.

Regards!

**Comment by whimboo** [comment]
No, here the excerpt from the WebDriver spec:

> "acceptInsecureCerts"
>    Boolean initially set to false, indicating the session will not implicitly trust untrusted or self-signed TLS certificates on navigation. 

And this is expected.

**Comment by gregall** [comment]
@whimboo thx for answer. But should not geckodriver respect variables from node configuration json? We are using Selenium Grid.
For example we have capabilities:
```{
    "capabilities": [
        {
            "browserName": "firefox",
            "marionette": true,
            "version": "59",
            "platform": "LINUX",
            "maxInstances": 8,
            "seleniumProtocol": "WebDriver",
            "acceptSslCerts": true,
            "javascriptEnabled": true,
            "takesScreenshot": true,
            "cleanSession": true,
            "acceptInsecureCerts": true
        },
```
But test alway show that `acceptInsecureCerts` is `False` is there any other way to change it?

**Comment by andreastt** [comment]
The above is not a capabilities object geckodriver recognises. Is it some special Grid configuration?

The expected input for geckodriver is:

```
{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}
```

Or the legacy way:

```
{"capabilities": {"desiredCapabilities": {"acceptInsecureCerts": true}}}
```

**Comment by whimboo** [comment]
@gregall this is really a Selenium question, and doesn't belong to us.

**Comment by andreastt** [comment]
Yeah, I don’t possess any detail knowledge of how Grid works either I’m afraid.
