### ISSUE TITLE
Unable to return HTMLFormControlsCollection from evaluated script

### ISSUE THREAD

**Issue by testingsteve** [mozilla/geckodriver#127]
Firefox 47
Geckodriver 0.8.0
Selenium 2.53.0

Using javascript to find DOM elements should return a list, and does when using ChromeDriver, or the old FirefoxDriver. Marionette returns a Map, which breaks this snippet:

```
System.out.println("links:" + js.executeScript("return document.links.length;").toString());
List<WebElement> links = (List<WebElement>) (js.executeScript("return document.links;"));
for (WebElement element : links) {
     System.out.println(element.getAttribute("href"));
}
```

 with:

```
Exception in thread "main" java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List
    at marionettejavascriptexecutor.MarionetteJavascriptExecutor.main(MarionetteJavascriptExecutor.java:41)
```

See attached sample

[MarionetteJavascriptExecutor.java.txt](https://github.com/mozilla/geckodriver/files/340286/MarionetteJavascriptExecutor.java.txt)

**Comment by andreastt** [comment]
@testingsteve I’m unable to reproduce this. Can you try again with [Nightly](https://nightly.mozilla.org)?

```py
>>> d.navigate("https://sny.no")
>>> links = d.execute_script("return document.links")
>>> links
[<marionette_driver.marionette.HTMLElement object at 0x7f25406a6c90>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6cd0>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6d10>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6d50>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6d90>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6dd0>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6e10>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6e50>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6e90>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6ed0>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6f10>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6f50>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6f90>, <marionette_driver.marionette.HTMLElement object at 0x7f25406a6fd0>]
```

**Comment by testingsteve** [comment]
@andreastt  `return document.links;` is OK in nightly, but I get a similar error with `return document.forms[0].elements;`

e.g listing all form elements:

```
        List<WebElement> formElements = (List<WebElement>) (js.executeScript("return document.forms[0].elements;"));
        for (WebElement element : formElements) {
            System.out.println(element.getTagName());
        }
```

**Comment by andreastt** [comment]
I can confirm this. It looks like `document.forms[N].elements` returns a _HTMLFormControlsCollection_ which is unhandled in Marionette.

I filed bug [bug 1284232](https://bugzilla.mozilla.org/show_bug.cgi?id=1284232) about this.

**Comment by andreastt** [comment]
This is also a specification issue.

**Comment by andreastt** [comment]
The fix to Gecko has landed. Can you confirm that this resolves your issue, @testingsteve?

I will leave this issue open until the spec has also been fixed.

**Comment by testingsteve** [comment]
@andreastt 

It's returning the form elements as expected, hovever some of the elements have a null type

e.g.:
 using www.google.com,

```
        List<WebElement> formElements = (List<WebElement>) (js.executeScript("return document.forms[0].elements;"));
        for (WebElement element : formElements) {
            System.out.println(element.getTagName() + ", " + element.getAttribute("type"));
        }
```


outputs:

```
1470859776892	Marionette	INFO	Listening on port 57897
input, hidden
input, hidden
input, hidden
button, submit
input, text
input, null
input, null
input, submit
input, submit
input, hidden
input, hidden
input, hidden



Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 42626
Only local connections are allowed.
input, hidden
input, hidden
input, hidden
button, submit
input, text
input, text
input, text
input, submit
input, submit
input, hidden
input, hidden
input, hidden
```


Should I raise a new issue for this?

**Comment by andreastt** [comment]
@testingsteve You have to be aware that the _Get Element Attribute_ commands has entirely different characteristics in WebDriver conformant implementations than it does in Selenium.

The specification introduced [_Get Element Property_](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-property) to return the DOM properties of elements. As far as I can tell the Selenium bindings are still lacking a shim to reproduce the Selenium API behaviour with WebDriver conformant remote ends. I believe this is https://github.com/SeleniumHQ/selenium/issues/2301.

So what happens in your above example is, I suspect, that some of the `<input>` fields are added dynamically. If you try the same, but instead call the _Get Element Property_ command (which may not exist in your bindings yet), you will see the expected behaviour.

**Comment by testingsteve** [comment]
Working as expected with Selenium 3.0.1, Firefox 50, GeckoDriver 0.11.1
