### ISSUE TITLE
geckodriver tryes to connect 600 time but cant Using ESR52.7.3(32-bit)

### ISSUE THREAD

**Issue by rahmansa2010** [mozilla/geckodriver#1273]
## System

Version: 0.20.0
Platform:Windows 8.1
Firefox: ESR 52.7.3 (32-bit)
Selenium: 3.11.0

TestCase:

public class FFDriverTest {

	public static void main(String[] args) {

		System.setProperty("webdriver.gecko.driver","C:\\GeckoDriver\\geckodriver-v0.20.0-win32\\geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setCapability("marionette", true);
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		options.setBinary("C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe");
		WebDriver driver = new FirefoxDriver(options);

		driver.get("https://www.cnn.com/");

		driver.quit();
	}

}

## Stacktrace

1526399619160	geckodriver	INFO	geckodriver 0.20.0 (0ac3698a74a7b1a742682b8e704f1f418df827ed 2018-03-13)
1526399619176	geckodriver	INFO	Listening on 127.0.0.1:47203
1526399619781	mozrunner::runner	INFO	Running command: "C:/Program Files (x86)/Mozilla Firefox/firefox.exe" "-marionette" "-profile" "C:\\Users\\srahman\\AppData\\Local\\Temp\\rust_mozprofile.4XxeJxO2RkOi"
1526399620556	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1526399621512	Marionette	INFO	Listening on port 2828
1526399621560	addons.webextension.accessor@accessor.com	WARN	Loading extension 'accessor@accessor.com': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1526399621827	geckodriver::marionette	TRACE	  connection attempt 0/600
1526399623933	geckodriver::marionette	TRACE	  connection attempt 1/600
1526399626041	geckodriver::marionette	TRACE	  connection attempt 2/600
1526399628154	geckodriver::marionette	TRACE	  connection attempt 3/600
1526399630256	geckodriver::marionette	TRACE	  connection attempt 4/600
1526399632360	geckodriver::marionette	TRACE	  connection attempt 5/600
1526399634462	geckodriver::marionette	TRACE	  connection attempt 6/600
1526399636566	geckodriver::marionette	TRACE	  connection attempt 7/600
1526399638678	geckodriver::marionette	TRACE	  connection attempt 8/600
1526399640807	geckodriver::marionette	TRACE	  connection attempt 9/600
1526399642937	geckodriver::marionette	TRACE	  connection attempt 10/600
1526399645059	geckodriver::marionette	TRACE	  connection attempt 11/600

**Comment by andreastt** [comment]
Unfortunately FIrefox 52 is not supported by geckodriver, but I would encourage you to try 55 or greater. Nightly will have the most amount of bug fixes.

**Comment by rahmansa2010** [comment]
Which ESR version is supported in Selenium 3?

**Comment by andreastt** [comment]
No current ESR version is supported by geckodriver, though the forthcoming ESR 60 release will be.

**Comment by Kalste** [comment]
Hi,
I got Selenium Grid running with this versions:

Gecko-Version: 0.15.0
Platform: Windows 7
Firefox: ESR 52.7.3 (32-bit)
Selenium: 3.3.1

Maybe this helps you.

**Comment by schmidtkp** [comment]
@rahmansa2010 You can use Selenium v3.x against Firefox ESR v52.x as long as you use the Firefox Legacy webdriver - i.e. not GeckoDriver. To do this you need to change: `options.setCapability("marionette", **false**);`
You will also have to make sure your remote node registers in its capabilities that as well:
`{"browserName":"firefox","browserVersion":"52.8.0","marionette": **false**,"maxInstances":"1","platformName":"MAC"}`

**Comment by whimboo** [comment]
@rahmansa2010 do you have IPv6 enabled? If yes geckodriver would use that protocol to connect to Marionette, which fails. Disabling IPv6 would help, or at least that `localhost` doesn't resolve to `::1`.

**Comment by andreastt** [comment]
Also an override in /etc/hosts to (temporarily) avoid localhost from hitting ::1 would work.

**Comment by rahmansa2010** [comment]
Will try that option ...but for so far thinking to upgrade version.
