### ISSUE TITLE
GeckoDriver Block[or miss or swallow ] some events

### ISSUE THREAD

**Issue by karim-nabli** [mozilla/geckodriver#1276]
## System

* Gckeco Version: 0.13.0 to 0.20.1
* Platform: MacOs
* Firefox: 56 to 61
* Selenium: 3.11.0 & 3.12.0
* Java 8

## Prerequisite to reproduce the bug
Download the debug.zip 
[debug.zip](https://github.com/mozilla/geckodriver/files/2016700/debug.zip)
It is recommended to use eclipse or equivalent.
import the project. 
![screen shot 2018-05-18 at 12 56 26](https://user-images.githubusercontent.com/34517066/40233444-ef8760d0-5a9a-11e8-886a-e1a7396925a0.png)

start the jetty server with webMock-0.1.war in the server folder like this:
``` shell
$> java -jar jetty-runner-9.4.9.v20180320.jar --port 8888 --path / webMock-0.1.war
```
in the localhost:8888 there will be a page deployed: 
![target](https://user-images.githubusercontent.com/34517066/40233388-aa6344ce-5a9a-11e8-8978-ae36baf4d137.png)

the webpage content is available under resources directory index.html that use the js test-events.js

## Testcase
Go to localhost:8888
Click on "A Link"
Then verify that focus event has fired on A Capture success.
And verify that click event has fired on A Capture success.
And verify that blur event has fired on A Capture success.

### Chrome Manual 
__WORK AS DESIGNED: Test success__
![chrome-manual-ok](https://user-images.githubusercontent.com/34517066/40233562-6ca5dfec-5a9b-11e8-8946-5d1b0def3dc6.png)

### FireFox Manual 
__ALMOST WORK AS DESIGNED: Test success__
![firefoxmanualok](https://user-images.githubusercontent.com/34517066/40233583-7ccb1608-5a9b-11e8-8c8f-42e614cd0ff2.png)

### Chrome Automated 
__WORK AS DESIGNED: Test success__
![chrome-automated-ok](https://user-images.githubusercontent.com/34517066/40233603-917cd690-5a9b-11e8-9503-454d276074e3.png)

### /!\ FireFox Automated /!\ THE FAILING CASE
__NOT WORKING: Test FAIL__
![firefoxautomatedtest-fail](https://user-images.githubusercontent.com/34517066/40233628-adfdaf88-5a9b-11e8-9341-e1148bb00263.png)

--> there are focus and blur events are missing. 

### Run Automation
Execute the BugClass from eclipse as classic java app!

**Comment by andreastt** [comment]
Whilst I appreciate that you’ve taken the effort to try to create a reproducible test case, there is so much overhead involved here that the core of the issue is hard to understand.

I understand you are clicking something and you are not seeing all the events you expect. Can you link us the HTML document you use and attach a [trace-level log] from geckodriver running against Firefox Nightly?

I believe the Element Click implementation for Firefox is following the WebDriver specification fairly accurately, so the extra DOM events you see from chromedriver might not be warranted by the spec. In any case, we have a desire for WebDriver to be interoperable so there may be a spec problem here.

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by karim-nabli** [comment]
Hi andreastt, the html is in the zip file. the index.html call the test-events.js
I am showing how FireFox behave differently from automated side vs manual side. 
Except the trace-log-level all you need to do is use the project zipped, to see the difference. 
SO to summerize the situation: Chrome_automated=Chrome_manual=FireFox_manual != form FireFox_automated. What I am confident is the automation in FireFox at least need to match the same behave in manual test. 
The trace: 
```shell
1526656476877	geckodriver	INFO	geckodriver 0.20.1
1526656476883	geckodriver	INFO	Listening on 127.0.0.1:32867
1526656477154	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/f9/stpcc3kx4j729gxwlm1vzshr0000gn/T/rust_mozprofile.ZKq887pOB8Ei"
1526656477164	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
1526656477682	Marionette	DEBUG	Received observer notification profile-after-change
1526656477773	Marionette	DEBUG	Received observer notification command-line-startup
1526656477773	Marionette	DEBUG	Received observer notification nsPref:changed
2018-05-18 16:14:38.344 plugin-container[47511:7408627] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x743f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-05-18 16:14:38.545 plugin-container[47512:7408658] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7f3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2018-05-18 16:14:38.549 plugin-container[47511:7408627] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x74d7, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1526656478610	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
2018-05-18 16:14:38.660 plugin-container[47512:7408658] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7f5b, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1526656478747	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1526656478747	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1526656478779	Marionette	DEBUG	New connections are accepted
1526656478780	Marionette	INFO	Listening on port 53124
1526656478812	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:53124
1526656478814	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:53162
1526656478815	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1526656478815	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1526656478818	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1526656478818	Marionette	WARN	TLS certificate errors will be ignored for this session
1526656478846	Marionette	DEBUG	Register listener.js for window 4294967297
1526656478849	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"8de8bf53-52b6-814c-80a3-17c77577198c","capabilities":{"browserName":"firefox","browserVersion":"61.0" ... 29gxwlm1vzshr0000gn/T/rust_mozprofile.ZKq887pOB8Ei","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1526656478850	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"8de8bf53-52b6-814c-80a3-17c77577198c","capabilities":{"browserName":"firefox","browserVersion":"61.0","platformName":"darwin","platformVersion":"17.5.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":47510,"moz:profile":"/var/folders/f9/stpcc3kx4j729gxwlm1vzshr0000gn/T/rust_mozprofile.ZKq887pOB8Ei","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1526656478850	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"8de8bf53-52b6-814c-80a3-17c77577198c","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"61.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":47510,"moz:profile":"/var/folders/f9/stpcc3kx4j729gxwlm1vzshr0000gn/T/rust_mozprofile.ZKq887pOB8Ei","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"17.5.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
May 18, 2018 4:14:38 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1526656478893	webdriver::server	DEBUG	-> POST /session/8de8bf53-52b6-814c-80a3-17c77577198c/url {"url":"http://localhost:8888/"}
1526656478893	geckodriver::marionette	TRACE	-> 44:[0,2,"get",{"url":"http://localhost:8888/"}]
1526656478900	Marionette	TRACE	0 -> [0,2,"get",{"url":"http://localhost:8888/"}]
1526656478908	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1526656479030	Marionette	DEBUG	Received DOM event pagehide for about:blank
1526656479071	Marionette	DEBUG	Received DOM event DOMContentLoaded for http://localhost:8888/
1526656479113	Marionette	DEBUG	Received DOM event pageshow for http://localhost:8888/
1526656479121	Marionette	TRACE	0 <- [1,2,null,{}]
1526656479125	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1526656479125	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1526656479132	webdriver::server	DEBUG	-> POST /session/8de8bf53-52b6-814c-80a3-17c77577198c/element {"value":"#\\31 111","using":"css selector"}
1526656479133	geckodriver::marionette	TRACE	-> 64:[0,3,"findElement",{"using":"css selector","value":"#\\31 111"}]
1526656479134	Marionette	TRACE	0 -> [0,3,"findElement",{"using":"css selector","value":"#\\31 111"}]
1526656479142	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"1333c003-6b82-7143-a0e5-bbf98d529fdf","ELEMENT":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}}]
1526656479143	geckodriver::marionette	TRACE	<- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"1333c003-6b82-7143-a0e5-bbf98d529fdf","ELEMENT":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}}]
1526656479143	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}}
1526656479150	webdriver::server	DEBUG	-> POST /session/8de8bf53-52b6-814c-80a3-17c77577198c/element/1333c003-6b82-7143-a0e5-bbf98d529fdf/click {"id":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}
1526656479151	geckodriver::marionette	TRACE	-> 66:[0,4,"clickElement",{"id":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}]
1526656479152	Marionette	TRACE	0 -> [0,4,"clickElement",{"id":"1333c003-6b82-7143-a0e5-bbf98d529fdf"}]
1526656479169	Marionette	DEBUG	Received DOM event popstate for http://localhost:8888/#pageId1-div-1
1526656479177	Marionette	TRACE	0 <- [1,4,null,{}]
1526656479178	geckodriver::marionette	TRACE	<- [1,4,null,{}]
1526656479178	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

**Comment by karim-nabli** [comment]
Hi Henrik, 
it is very similar bug to #906 (may be the exact same bug), but bringing the firefox to the top does not really work. It triggers blur and focuses but these are not due to click or scroll event on the same page.

**Comment by whimboo** [comment]
Sorry, but I don't understand your last reply. What's different now? In your initial comment you added some images, how does it look like when Firefox runs in foreground? Note you should pass the `-foreground` option via `args` in `moz:FirefoxOptions`. 

Also we do not have Eclipse and I'm not going to install it. So what we need is just a HTML file, and if necessary some js files as a zip, and a simply Selenium test which shows the problem. Please get rid of everything else.

**Comment by karim-nabli** [comment]
Hi Henrik, thank you for your reply. 
When I first read your response I thought you did not understand the core message. I added the log in addition to my first description. And apologies if my bug description were too much detailed or over-detailed. 
Clarification required: I do not understand you when you said 'Note you should pass the -foreground option via args in moz:FirefoxOptions.' 

in the following zip you will find the html and js in the html directory, in the server directory there is shell script if you want to deploy the html quickly in your local host by running the ./start.sh. (localhost:8888)
[mihb.zip](https://github.com/mozilla/geckodriver/files/2035265/mihb.zip)
the java piece of code that I use to reproduce the bug: 
```java
public static void main(String[] args) {
		BugClass bc = new BugClass();
		bc.runFF();
	}
	
	private void runFF() {
		setGeckoDriver();
		testFF();	
	}

	private void setGeckoDriver() {
		System.setProperty("webdriver.gecko.driver","PATH_TO_GECKODRIVER");
	}
	
	private void testFF()  {
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		WebDriver driver = new FirefoxDriver(options);
		driver.get("http://localhost:8888/");
		driver.findElement(By.id("1111")).click();
	}
```
Note that the following dependencies are mandatory: 
``` java
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
```
and I am using  org.seleniumhq.selenium:selenium-firefox-driver:3.12.0
org.seleniumhq.selenium:selenium-java:3.12.0
org.seleniumhq.selenium:selenium-server:3.12.0

Please let me know if you need any further clarifications.

**Comment by whimboo** [comment]
Thanks. So it is indeed a dupe of #906 then.

**Comment by karim-nabli** [comment]
it is indeed.
