### ISSUE TITLE
Error: Channel error: cannot send/recv

### ISSUE THREAD

**Issue by yingjunjie831210** [mozilla/geckodriver#1279]
## System

* Version: 0.20.1
* Platform: Windows10
* Firefox: 60.0.1
* Selenium: 3.9.1

## Testcase

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.firefox.FirefoxDriver;

public class WebTests {

	private static FirefoxDriver browser;

	@BeforeClass
	public static void openBrowser() {
		System.setProperty("webdriver.gecko.driver", "D:/drivers/firefox/geckodriver.exe");
		browser = new FirefoxDriver();
	}
	@Test
	public void doNothing() {
		
	}
	@AfterClass
	public static void closeBrowser() throws InterruptedException {
		browser.quit();
	}

}

## Stacktrace

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

## Trace-level log

1526916998418	geckodriver	INFO	geckodriver 0.20.1
1526916998436	geckodriver	INFO	Listening on 127.0.0.1:39163
1526916999168	mozrunner::runner	INFO	Running command: "D:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\enc\\AppData\\Local\\Temp\\rust_mozprofile.Km0ZXw0aGmIQ"
Unable to read VR Path Registry from C:\Users\enc\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\enc\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\enc\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\enc\AppData\Local\openvr\openvrpaths.vrpath
1526917001765	Marionette	INFO	Listening on port 51551
Unable to read VR Path Registry from C:\Users\enc\AppData\Local\openvr\openvrpaths.vrpath
1526917002376	Marionette	WARN	TLS certificate errors will be ignored for this session
五月 21, 2018 11:36:42 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
1526917002526	addons.xpi	WARN	Exception running bootstrap method shutdown on activity-stream@mozilla.org: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://activity-stream/lib/SnippetsFeed.jsm :: uninit :: line 185"  data: no] Stack trace: uninit()@resource://activity-stream/lib/SnippetsFeed.jsm:185
onAction()@resource://activity-stream/lib/SnippetsFeed.jsm:201
_middleware/</<()@resource://activity-stream/lib/Store.jsm:49
Store/this[method]()@resource://activity-stream/lib/Store.jsm:28
uninit()@resource://activity-stream/lib/Store.jsm:151
uninit()@resource://activity-stream/lib/ActivityStream.jsm:300
uninit()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Program%20Files/Mozilla%20Firefox/browser/features/activity-stream@mozilla.org.xpi!/bootstrap.js:73
shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Program%20Files/Mozilla%20Firefox/browser/features/activity-stream@mozilla.org.xpi!/bootstrap.js:169
callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4436
observe()@resource://gre/modules/addons/XPIProvider.jsm:2287
GeckoDriver.prototype.quit()@driver.js:3300
despatch()@server.js:293
execute()@server.js:267
onPacket/<()@server.js:242
onPacket()@server.js:241
_onJSONObjectReady/<()@transport.js:500
[Child 2468, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 2468, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 5840, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 1336, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 1336, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

**Comment by whimboo** [comment]
Would you mind helping us to identify the problem in Firefox by running a latest Firefox 62.0a debug build? It will give more details about what's wrong. You could find such a build here: https://queue.taskcluster.net/v1/task/XTyw1FAVT8Kos20xjr_Oxg/runs/0/artifacts/public/build/target.zip

Just unzip and point Selenium to the Firefox binary included in that archive. Please provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) the next time.

Thanks.

**Comment by whimboo** [comment]
Without a proper reply we cannot help. If you have a chance please check my last comment and let us know about the newly generated trace log. Closing issue for now due to inactivity.

**Comment by bayegy** [comment]
@whimboo Hello, I faced the similar problem, too. This happened when i tried to use the following python code  in a linux enviroment:

`from selenium import webdriver`
`option = webdriver.FirefoxOptions()`
`option.set_headless()`
`d=webdriver.Firefox(firefox_options=option)`
`d.get("somepage")`

This code was supposed to run silently without open the browser. Well, my browser is Mozilla Firefox 66.0.3.
At the header of geckodriver.log the following was written:

> 1556249711209	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.skMzkJSglDM3"
1556249711644	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1556249711644	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1556249711644	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1556249713022	Marionette	INFO	Listening on port 38452
1556249713140	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 136681, Gecko_IOThread] WARNING: pipe error (71): 连接被对方重设: file /build/firefox-i2nBcb/firefox-66.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
[Parent 136681, Gecko_IOThread] WARNING: pipe error (79): 连接被对方重设: file /build/firefox-i2nBcb/firefox-66.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357
1556249715615	Marionette	INFO	Stopped listening on port 38452
1556249730284	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.hEdM6L5MHCAr"
*** You are running in headless mode.
1556249730750	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1556249730751	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1556249730751	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1556249731970	Marionette	INFO	Listening on port 42901
1556249731993	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 137000, Gecko_IOThread] WARNING: pipe error: 断开的管道: file /build/firefox-i2nBcb/firefox-66.0.3+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 726
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0087,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x350115,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0087,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x1E0087,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
JavaScript error: resource://activity-stream/lib/ActivityStreamPrefs.jsm, line 23: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.removeObserver]
WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"SessionStore: flushing all windows","state":{"total":1,"current":0},"filename":"resource:///modules/sessionstore/SessionStore.jsm","lineNumber":1624,"stack":["resource:///modules/sessionstore/SessionStore.jsm:ssi_onQuitApplicationGranted:1624","resource:///modules/sessionstore/SessionStore.jsm:ssi_observe:784","resource:///modules/ContentCrashHandlers.jsm:observe:152"]}] Barrier: quit-application-granted
###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv

and then keep on writting this: 

> ###!!! [Parent][MessageChannel] Error: (msgtype=0xA00001,name=PVsync::Msg_Notify) Channel error: cannot send/recv

until, i don't know, like forever.  geckodriver.log is too large to provide.

But the following code works well for me though:


`from selenium import webdriver`
`d=webdriver.Firefox()`
`d.get("somepage")`


I'd appreciate that if you can help me figure this out.

**Comment by whimboo** [comment]
@bayegy can you please go through https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html and tell me the Id of the uploaded crash report? Thanks!

**Comment by bayegy** [comment]
> @bayegy can you please go through https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html and tell me the Id of the uploaded crash report? Thanks!

Thanks a lot for your reply.

I actually went through the  https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html .

This is the situation i encountered in python:

>\>>> import tempfile
\>>> 
\>>> from selenium import webdriver
\>>> from selenium.webdriver.firefox.options import Options
\>>> 
\>>> # Custom profile folder to keep the minidump files
... profile = tempfile.mkdtemp(".selenium")
\>>> print("*** Using profile: {}".format(profile))
*** Using profile: /tmp/tmpkimlq5io.selenium
\>>> 
\>>> # Use the above folder as custom profile
... opts = Options()
\>>> opts.add_argument("-profile")
\>>> opts.add_argument(profile)
\>>> opts.binary="/usr/bin/firefox"
\>>> opts.set_headless()
\>>> driver = webdriver.Firefox(options=opts,
...     # hard-code the Marionette port so geckodriver can connect
...     service_args=["--marionette-port", "2828"])
\>>> driver.get('https://www.baidu.com/')
\>>> driver.page_source
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin1/miniconda3/envs/qm2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/home/admin1/miniconda3/envs/qm2/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/admin1/miniconda3/envs/qm2/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

When i navigated to  /tmp/tmpkimlq5io.selenium, i did found minidumps folder, but i found nothing in it. And the step of 'driver = webdriver.Firefox' and 'driver.get' took more time than expected. Is something i did wrong?

**Comment by bayegy** [comment]
@whimboo , Hello again. I actually solve my case by simply rebooting my computer. I don't understand why though.

**Comment by whimboo** [comment]
@bayegy ok, good to hear.

**Comment by murcraft** [comment]
Hey all!
I have the same issue.
Using packages:
**protractor-flake: "3.3.0",**
**protractor": "^5.4.2"**
**geckodriver v.0.24**
**$ firefox --version Mozilla Firefox 66.0.3**
OS version: http://joxi.net/EA4d5kOcoMv41A

My Firefox config file:
```
exports.config = {
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

  allScriptsTimeout: 11000,
  SELENIUM_PROMISE_MANAGER: false,
  framework: 'jasmine2',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 240000
  },
capabilities:
    {
      browserName: 'firefox',
      shardTestFiles: true,
      maxInstances: 4,
      acceptInsecureCerts: true,

      'moz:firefoxOptions': {
        args: [
          '--width=1920',
          '--height=1080',
          '--private',
          '--headless'
        ],
        prefs: {
          'browser.download.folderList': 2,
          'browser.download.dir': pathDownloads,
          'pref.downloads.disable_button.edit_actions': true,
          'services.sync.prefs.sync.browser.download.useDownloadDir': true,
          'browser.download.useDownloadDir': true,
          'browser.download.manager.alertOnEXEOpen': false,
          'browser.download.manager.closeWhenDone': true,
          'browser.download.manager.focusWhenStarting': false,
          'browser.download.manager.showWhenStarting': false,
          'browser.helperApps.alwaysAsk.force': false,
          'browser.download.manager.showAlertOnComplete': false,
          'browser.download.manager.useWindow': false,
          'browser.download.panel.removeFinishedDownloads': false,
          'browser.download.useToolkitUI': false,
          'browser.helperApps.neverAsk.saveToDisk': 'application/pdf',
          'browser.helperApps.neverAsk.openFile': 'application/pdf',
          'pdfjs.disabled': true, //not show ask window to save pdf
          'plugin.disable_full_page_plugin_for_types': 'application/pdf',
          'browser.download.forbid_open_with': true,
        },
      },
      log: {
        level: 'trace'
      }
    },
...
}
```
Commands to run job:
**webdriver-manager update --versions.standalone=3.14.0**
**webdriver-manager start --versions.standalone=3.14.0 --detach --quiet**
**npm test**

In this case my 4 tests run simultaneously, an as I can see - all is going good, but after passing several tests the next tests cannot be run by selenium. When suite with tests is not large, it is going good without any error. Could somebody help me to cope with this issue?
Here is the part of log from Travis:
log from Travis:
https://api.travis-ci.com/v3/job/196620512/log.txt?log.token=WDg0HT8k_vhrFTHeWG2OLw

**Comment by whimboo** [comment]
@murcraft please file your own issue report given that it is not clear if you really face the same issue. thanks.
