### ISSUE TITLE
geckodriver can launch firefox but cannot connect and run selenium tests.

### ISSUE THREAD

**Issue by StephenPerson** [mozilla/geckodriver#1280]
## System

* Version: 0.20.1
* Platform: RHEL 6
* Firefox: 52.7.3
* Selenium: 3.12.0

## Testcase

Running selenium-java through ant build

## Stacktrace

base_tests:
    [mkdir] Created dir: /home/persons/git/fv-regression-test/report
    [mkdir] Created dir: /home/persons/git/fv-regression-test/screenshots
    [junit] Running fv.test.BaseTestSuite
    [junit] 1526921490131	geckodriver	INFO	geckodriver 0.20.1
    [junit] 1526921490135	geckodriver	INFO	Listening on 127.0.0.1:19511
    [junit] 1526921490604	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.FkHRb93wYmGJ"
    [junit] 1526921491322	Marionette	INFO	Listening on port 2828
    [junit] Tests run: 0, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 60.83 sec
    [junit] Test fv.test.BaseTestSuite FAILED

## Trace-level log

base_tests:
    [mkdir] Created dir: /home/persons/git/fv-regression-test/report
    [mkdir] Created dir: /home/persons/git/fv-regression-test/screenshots
    [junit] Running fv.test.BaseTestSuite
    [junit] 1526923459957	geckodriver	INFO	geckodriver 0.20.1
    [junit] 1526923459961	geckodriver	INFO	Listening on 127.0.0.1:25531
    [junit] 1526923460248	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.HAnb7EVhuyH4"
    [junit] 1526923460249	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
    [junit] 1526923460842	Marionette	INFO	Listening on port 2828
    [junit] 1526923520285	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
    [junit] 1526923520313	geckodriver	INFO	geckodriver 0.20.1
    [junit] 1526923520317	geckodriver	INFO	Listening on 127.0.0.1:11911
    [junit] 1526923520353	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.hkk7dbpdnDWi"
    [junit] 1526923520354	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser
    [junit] 1526923520940	Marionette	ERROR	Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
    [junit] [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 95"  data: no]
    [junit] MarionetteServer.prototype.start@chrome://marionette/content/server.js:95:19
    [junit] MarionetteComponent.prototype.init@resource://gre/components/marionette.js:217:5
    [junit] MarionetteComponent.prototype.handle@resource://gre/components/marionette.js:112:5
    [junit] 
    [junit] 1526923521462	addons.productaddons	WARN	Failed downloading XML, status: 0, reason: error
    [junit] 1526923521470	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
    [junit] 1526923580382	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
    [junit] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 120.779 sec
    [junit] Test fv.test.BaseTestSuite FAILED

**Comment by whimboo** [comment]
We aren't supporting Firefox 52ESR anymore and geckodriver 0.20.1 doesn't work with that version. See the release notes for minimal Firefox versions.

Please note that Firefox 60ESR is available in the meantime, and you should upgrade.
