### ISSUE TITLE
Firefox webdriver doesnot have provision to run in current user mode on Mac OSX,it always run as a root user.

### ISSUE THREAD

**Issue by parshudhole** [mozilla/geckodriver#1283]
## System

* Version: 0.18, 0.20
* Platform:Mac OSX 10.12
* Firefox: Firefox 57 ,Firefox 58 ,Firefox 60
* Selenium: 3.5

## Testcase

on my Mac OSX platform ,I am working on automating the firefox related use cases wherein Firefox should be launched in current user context ,it also has one broker process associated with Firefox which should be launched in current user context.When I run the automation on Mac ,then it always launch the firefox in root user context and thats why I am not able to proceed the automation.
I found one workaround to run it in root context by modifying the webdriver code (service.py) 
Sharing the code snippet of service.py ,note that i added 'preexec_fn'  parameter
--------------------------
    def start(self):
        """
        Starts the Service.

        :Exceptions:
         - WebDriverException : Raised either when it can't start the service
           or when it can't connect to the service
        """
        try:
            cmd = [self.path]
            cmd.extend(self.command_line_args())
            self.process = subprocess.Popen(cmd, env=self.env,
                                            close_fds=platform.system() != 'Windows',
                                            stdout=self.log_file, stderr=self.log_file, preexec_fn=self.demote(502, 20))

  def demote(self, user_uid, user_gid):
        """Pass the function 'set_ids' to preexec_fn, rather than just calling
        setuid and setgid. This will change the ids for that subprocess only"""
        def set_ids():
            os.setgid(user_gid)
            os.setuid(user_uid)
        return set_ids    

But changing webdriver code is not good practise and not long term solution ,we need to maintain this again when we  update the selenium in future, there should be an provision to pass the user context from external (test scripts).

**Comment by AutomatedTester** [comment]
The python code from Selenium runs the code in the same context as it is executed and does not promote/demote itself so that would suggest that you are running this as root.

**Comment by AutomatedTester** [comment]
Closing this as user error as can not reproduce this on OSX with vanilla Selenium
