### ISSUE TITLE
fails to disable javascript.

### ISSUE THREAD

**Issue by dnuka** [mozilla/geckodriver#1284]
* Version: v0.20.1 linux64
* Platform: Linux 
* Selenium: 3.12.0
* Firefox: 60.0.1-5
`
```
firefox = webdriver.FirefoxProfile(profile_directory=profile_path)
firefox.set_preference("javascript.enabled", False)`

```
I cannot disable javascript using previous code.

geckodriver.log
```
JavaScript error: jar:file:///usr/lib/firefox/omni.ja!/components/addonsInfo.js, line 91: SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead

JavaScript error: resource:///modules/sessionstore/SessionFile.jsm, line 337: Error: _initWorker called too early! Please read the session file from disk first.
```

**Comment by whimboo** [comment]
The above is not a trace log. So please provide one. See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html. Also you should set any preferences as best via `prefs` of the `moz:firefoxOptions`: https://github.com/mozilla/geckodriver/#mozfirefoxoptions

**Comment by dnuka** [comment]
@whimboo Thank you for reaching out! I'm very much new to testing, working with geckodriver and open-source world. 
I actually tried couple of ways to implement `javascript.enabled", False`. using `FirefoxProfile, Options` and copied `prefs.js` file from a real firefox profile. none of them worked.

`about:config` says  value is modified. by still the value is `true` not `false`.
How can I implement `moz:firefoxOptions` using python?

**Comment by whimboo** [comment]
This works fine for me with the following code snippet:

```
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options


opts = Options()
opts.binary = binary
opts.preferences.update({
    "javascript.enabled": False,
})

capabilities = DesiredCapabilities.FIREFOX.copy()
driver = webdriver.Firefox(options=opts,
                           capabilities=capabilities)

driver.get("https://travis-ci.org/")
```

**Comment by dnuka** [comment]
yes! It worked. Thank you very much @whimboo . If possible can you give me a reference link or any advice, to learn more about this topic. Thanks again :)

**Comment by whimboo** [comment]
For geckodriver related issues just check the readme of https://github.com/mozilla/geckodriver/. For everything else please ask the Selenium community.
