### ISSUE TITLE
Firefox is not abel to click on link whose case changed to uppercase due to CSS properties

### ISSUE THREAD

**Issue by vinaybond** [mozilla/geckodriver#1296]
## System

* Version: v0.20.1
* Platform: Windows
* Firefox: 58, 59, 60
* Selenium: 3.10

## Testcase
Gecko driver cant click on link whose case is changed due to CSS properties.

I am attaching s sample html code. My actual link text is **Hello** which is turned into **HELLO** due to CSS properties. (For chromedriver, link=HELLO works but not **link=Hello**, Opposite woks for geckodriver)

```
<html>
	<head>
		<style>
		a.a {text-transform: uppercase;}
		</style>
	</head>
	<body>
		<a class="a" href="a.html" >Hello</a>
	</body>
</html>
```

**Comment by andreastt** [comment]
This is expected behaviour because WebDriver uses the Selenium `getText` atom, and it does not support CSS transformations. This is also a bug in all other WebDriver implementations.

**Comment by whimboo** [comment]
This is a dupe of #802 and is fixed in Firefox 61.
