### ISSUE TITLE
error retrieving new session, cannot open site

### ISSUE THREAD

**Issue by rajeevbarde** [mozilla/geckodriver#1300]
## System

* Version: 0.20.0
* Platform: Windows
* Firefox: 60.0.1
* Selenium: standalone geckodriver.exe

## Testcase
Open google.com using nightwatch.js
` client
        .url('http://www.google.com')
        .waitForElementVisible('body', 1000)
        .end();`

## Stacktrace

> [Sample] Test Suite
===================
   An occurred error while retrieving a new session

_________________________________________________

TEST FAILURE: 1 error during execution 0 tests failed, 0 passed. 4.462s

 × sample

  An occurred error while retrieving a new session

   SKIPPED:
   - google

## Trace-level log
`1529237997114   geckodriver     INFO    geckodriver 0.20.0
1529237997114   webdriver::httpapi      DEBUG   Creating routes
1529237997130   geckodriver     INFO    Listening on 127.0.0.1:4444
1529238004116   webdriver::server       DEBUG   -> POST /session {"desiredCapabilities":{"browserName":"firefox","acceptSslCerts":true,"platform":"ANY","marionette":true,"acceptInsecureCerts":true,"marionette.logging":"TRACE","name":"Sample"}}
1529238004138   mozrunner::runner       INFO    Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\raj\\AppData\\Local\\Temp\\rust_mozprofile.aw8ZyAuEnnxy"
1529238006347   geckodriver::marionette DEBUG   Connected to Marionette on localhost:52137
1529238006347   geckodriver::marionette TRACE   <- {"applicationType":"gecko","marionetteProtocol":3}
1529238006347   geckodriver::marionette TRACE   -> 367:[0,1,"newSession",{"acceptInsecureCerts":true,"acceptSslCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"acceptSslCerts":true,"browserName":"firefox","marionette":true,"marionette.logging":"TRACE","name":"Sample","platform":"ANY"}},"marionette":true,"marionette.logging":"TRACE","name":"Sample","platform":"ANY"}]
1529238006478   geckodriver::marionette TRACE   <- [1,1,null,{"sessionId":"44827309-5ba3-4e8d-b78b-fcbf9acb2c45","capabilities":{"browserName":"firefox","browserVersion":"60.0.1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":7272,"moz:profile":"C:\\Users\\raj\\AppData\\Local\\Temp\\rust_mozprofile.aw8ZyAuEnnxy","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1529238006478   webdriver::server       DEBUG   <- 200 OK {"value": {"sessionId":"44827309-5ba3-4e8d-b78b-fcbf9acb2c45","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"60.0.1","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":7272,"moz:profile":"C:\\Users\\raj\\AppData\\Local\\Temp\\rust_mozprofile.aw8ZyAuEnnxy","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
`

**Comment by whimboo** [comment]
This is not a geckodriver problem. A new session is correctly returned as you can see with:

> webdriver::server DEBUG <- 200 OK {"value": {"sessionId":"44827309-5ba3-4e8d-b78b-fcbf9acb2c45"...

So this is a client problem. Get in touch with the developer of nightwatch.
