### ISSUE TITLE
Windows 10 - After an OS update I get the following message "An invalid argument was supplied. (os error 10022)"

### ISSUE THREAD

**Issue by moshesak** [mozilla/geckodriver#1307]
Windows 10 - After an OS update I get the following message "An invalid argument was supplied. (os error 10022)" when I try to run geckodriver.exe from the network path.

Trying to run the same geckodriver version locally (from C:\) is successfully done.
I have tried both **geckodriver-v0.20.1-win64**, and **geckodriver-v0.19.1-win64**

The user that I am utilizing for this purpose has Read & execute and Write permissions over the folder that holds the geckodriver.
I have also tried to run geckdriver while disabling the FireWall and with Administrator priviledges
UAC level is - "Never notify"

The OS is Windows 10 Pro Version: 1803 OS build: 17134.1

What might be the problem ?

**Comment by andreastt** [comment]
I don’t have any clue what might be happening here, but it seems unlikely that this is an issue with geckodriver itself.

**Comment by moshesak** [comment]
Are you familiar with this issue ?
Can you guess what is the "invalid argument that was supplied" means " as I am not supplying any argument at all but either using the default ones

**Comment by whimboo** [comment]
Also without a full log as best trace log we cannot further help.
