### ISSUE TITLE
Please help with behavior of new geckodriver (v.21)

### ISSUE THREAD

**Issue by S-Kerrigan** [mozilla/geckodriver#1310]
Hello, i know, that this no place for simple-question, but i not know another where me will can help..

In last the change-log of geckodriver, in "changed" section, was wrote about two new default-flags (https://github.com/mozilla/geckodriver/releases/tag/v0.21.0):
- -no-remote
- -foreground
However not informated "how launch/use like a past build, without this changes".
What need write, for old behavior, in moz:firefoxOptions?

**Comment by whimboo** [comment]
What is your problem with those flags? Those shouldn't affect you in any case. Those only open Firefox as front-most application on MacOS now too similar to Windows and Linux, and don't let Firefox receive OS integration commands which would interfere with testing.

**Comment by S-Kerrigan** [comment]
I last year wrote async/multithread system for test-process of our main-product.
And, we always have array of runned browser instances, with subsystem for dynamic load-balancing between instances.
So we not want new behaviors...

**Comment by andreastt** [comment]
From your last reply, I don’t fully understand how geckodriver passing `-no-remote` and `-foreground` affects you. Do you understand how these flags work?

**Comment by S-Kerrigan** [comment]
> Do you understand how these flags work?

Of course i can wrong understand,... and i will be happy, if i my fears is unfounded :)
Just worried because was wrote in changes:

> will prevent remote commands
to this instance of Firefox and also ensure we always start a new
instance.

So, i understand it, how "i will can't connect to already runned, in early time, browser"... i seriously mistaken?

**Comment by andreastt** [comment]
`-no-remote` means a subsequent `firefox -new-window` can’t interfere with the already running instance of Firefox. It doesn’t mean that WebDriver or Marionette will be impacted in any way.

**Comment by whimboo** [comment]
So is actually something broken for you when running the tests? If not, there is nothing to worry about. 

Descriptions for all the supported command line options of Firefox can be found here:
https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options

`remote` in this case might have been a bit mis-leading in the release notes. But as I said above it's about OS integration not geckodriver.

**Comment by S-Kerrigan** [comment]
> So is actually something broken for you when running the tests? 


I not yet update test-platform - according to plans, it will be tomorrow, but developer must read change-log and to think before anything doing. So it was done and i was feared.
Sorry of my stupid questions and a lot of thank's of are your help!

**Comment by andreastt** [comment]
Thanks for your patience, and sorry about the confusing changelog. We will do better next time.
