### ISSUE TITLE
GeckoDriver-v0.21.0-linux64 does not seem compatible with Selenium

### ISSUE THREAD

**Issue by abhi2652254** [mozilla/geckodriver#1312]
## System

* Version: geckodriver-v0.21.0-linux64
* Platform: Linux16.04
* Firefox: 57 
* Selenium: 3.13.0
* Python: 2.7.15

I tried every procedure to fix the error below but none seem to work.
I also tried the below commands on the ubuntu terminal from the website given below.

https://askubuntu.com/questions/851401/where-to-find-geckodriver-needed-by-selenium-python-package/863211

wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
tar -xvzf geckodriver-v0.11.1-linux64.tar.gz
rm geckodriver-v0.11.1-linux64.tar.gz
chmod +x geckodriver
cp geckodriver /usr/local/bin/ 

from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

PATH = "/usr/local/bin/geckodriver-v0.21.0-linux64/geckodriver.exe"
driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver-v0.21.0-linux64/geckodriver.exe") 

firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
firefox_capabilities['binary'] = '/usr/bin/firefox'
browser = webdriver.Firefox(capabilities=firefox_capabilities)

Traceback (most recent call last):
  File "/home/abhi/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/geckodriver-v0.21.0-linux64/geckodriver.exe': '/usr/local/bin/geckodriver-v0.21.0-linux64/geckodriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhi/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service.start()
  File "/home/abhi/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver.exe' executable needs to be in PATH.

Can anyone please help me fix this issue? Thanks in advance.

**Comment by whimboo** [comment]
Yes, it's a  wrong version and even a very outdated one of geckodriver.
