### ISSUE TITLE
About Firefox preferences

### ISSUE THREAD

**Issue by Kryshtopenko** [mozilla/geckodriver#1314]
Please provide list of all exist Firefox preferences for the best tuning because these examples don't help anymore. (https://stackoverflow.com/questions/25251583/downloading-file-to-specified-location-with-selenium-and-python)
Please answer how to create and configure in runtime new Firefox profile and pick him for test execution.
A lot of fish text. I know. I just want to finally discover for myself solution how to control all browser features. Thank you in advance. You will help the entire community of testers.

**Comment by whimboo** [comment]
geckodriver sets all the required and recommended prefs on its own. So there is nothing which has to be specified by default. Only when you do specific activities there might be a reason to add some custom preferences. 

Also if you want to download a file just use your binding language to directly download it. Selenium with geckodriver/Firefox shouldn't be used for that. Python has HTTP clients.

Please note that for Firefox there is still issue #1065 which I'm now duping this issue against.
