### ISSUE TITLE
selenium 3.4.0 and FireFox 61.0 issues - elements can't be found

### ISSUE THREAD

**Issue by juzdarwin** [mozilla/geckodriver#1316]
## System 
Windows Server 2016

* Version: 0.18.0
* Platform: Windows Server 2016
* Firefox: Quantum 61.0 - 64bit
* Selenium: 3.4.0

## Testcase
The issue is that prior to my Firefox being updated, my tests were working fine.
i have cases where based on the user, if an element is not there, i expect that condition based on a Boolean value and verify it is false.  
But Selenium is still checking for the element and it is failing complaining the element can't be found!

I tried upgrading to selenium 3.11.0 and gecko driver 0.21.0 but that is not helping.

Please help

**Comment by whimboo** [comment]
There has no code, stacktrace, and trace level log provided. As such we cannot act at all on this issue, and I have to close it.
