### ISSUE TITLE
Click with modifier keys doesn't target given element

### ISSUE THREAD

**Issue by elliterate** [mozilla/geckodriver#1318]
## System

* Version: 0.21.0
* Platform: macOS 10.11.6; Ubuntu 14.04.5 LTS
* Firefox: 61.0; 62.0b4; 63.0a1
* Selenium: py/3.13.0

### `test.html`

```html
<html>
  <body>
    <div id="target">Target</div>
    <pre id="results"></pre>
    <script>
      (function() {
        var target = document.getElementById('target');
        var results = document.getElementById('results');
        var events = [];

        function serializeResults() {
          results.innerText = JSON.stringify(events);
        }

        ['click', 'contextmenu', 'dblclick'].forEach(function(event) {
          target.addEventListener(event, function(e) {
            e.preventDefault();
            events.push({event: event, altKey: e.altKey, ctrlKey: e.ctrlKey, metaKey: e.metaKey, shiftKey: e.shiftKey});
            serializeResults();
          });
        });

        serializeResults();
      })();
    </script>
  </body>
</html>
```

### `test_context_click.py`

```python
import inspect
import json
import os.path
from unittest import TestCase, main

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys


_DIR = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))

def _get_fixture_url(filename):
    return 'file://{}'.format(os.path.join(_DIR, filename))


class TestcontextClick(TestCase):
    @classmethod
    def setUpClass(cls):
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities['marionette'] = True
        capabilities['moz:firefoxOptions'] = {'log': {'level': 'trace'}}
        cls.browser = webdriver.Firefox(capabilities=capabilities)

    @classmethod
    def tearDownClass(cls):
        cls.browser.quit()

    def test_context_click(self):
        self.browser.get(_get_fixture_url('test.html'))
        results = self.browser.find_element_by_id('results')

        events = json.loads(results.text)
        self.assertNotIn('contextmenu', {e['event'] for e in events})

        target = self.browser.find_element_by_id('target')
        actions = ActionChains(self.browser)
        keys = [Keys.ALT, Keys.CONTROL, Keys.META, Keys.SHIFT]

        for key in keys:
            actions.key_down(key)

        actions.context_click(target)

        for key in keys:
            actions.key_up(key)

        actions.perform()

        events = json.loads(results.text)
        self.assertIn('contextmenu', {e['event'] for e in events})

        event = next(e for e in events if e['event'] == 'contextmenu')
        modifiers = {k: v for k, v in iter(event.items()) if k.endswith('Key')}
        self.assertEqual(modifiers, {
            u'altKey': True,
            u'ctrlKey': True,
            u'metaKey': True,
            u'shiftKey': True,
        })


if __name__ == '__main__':
    main()
```

## Stacktrace

```
$ python test_context_click.py
F
======================================================================
FAIL: test_context_click (__main__.TestcontextClick)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_context_click.py", line 58, in test_context_click
    self.assertIn('contextmenu', {e['event'] for e in events})
AssertionError: 'contextmenu' not found in set([])

----------------------------------------------------------------------
Ran 1 test in 7.939s

FAILED (failures=1)
```
![screen shot 2018-07-02 at 9 09 08 am](https://user-images.githubusercontent.com/6326/42166164-2796ca46-7dd8-11e8-9bc8-984b7b721748.png)

## Trace-level log

[geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/2153551/geckodriver.log.txt)

**Comment by whimboo** [comment]
Well, you call `key_up()` for each of the modifier keys before issuing the `context_menu` click, and call `key_down` afterward. How should this be supposed to work? You want the other way around, right?

**Comment by elliterate** [comment]
@whimboo Doh! 🤦‍♂️ (Interestingly, though, the test passed in Chrome.)

After fixing the order of the key actions, the test shows that the real issue is that the context menu isn’t triggering on the target element when modifier keys are pressed. (Title and description updated, with screenshot.)

**Comment by elliterate** [comment]
Upon further testing, I've discovered that the problem appears to be even more general. In 62.0b4 and 63.0a1, _any_ type of click (`click`, `context_click`, and `double_click`) with modifiers fails to occur on the targeted element. (On 61.0, only `context_click` has the issue.)

**Comment by elliterate** [comment]
Upon yet _further_ testing, it appears to be limited to the following combinations:
1. control + single/double click and
2. shift + context click.

Scenario 1 triggers the `contextmenu` event, as one would expect.

Scenario 2 is [by design](https://bugzilla.mozilla.org/show_bug.cgi?id=692139), as it allows the user to bypass any `contextmenu` handler.

**Comment by whimboo** [comment]
> @whimboo Doh! 🤦‍♂️ (Interestingly, though, the test passed in Chrome.)

I would call this a bug in the chrome driver then! It's clearly not working as expected then.

> Upon yet further testing, it appears to be limited to the following combinations:

So you closed this issue. As such I assume it's working all fine for you now?

**Comment by elliterate** [comment]
> So you closed this issue. As such I assume it's working all fine for you now?

More that I think I now understand _why_ the test fails as written:

1. [For many years][1], Firefox has allowed the user to hold the shift key during a context-click so as to bypass JavaScript event handlers that might otherwise intercept it.
2. With Firefox 62, control + click is now treated as a context-click.

As a result of (2), shift + control + click is now treated as shift + context-click which, because of (1), bypasses JavaScript event handlers. Because the test that uncovered this was passing all possible modifiers, it was skipping JavaScript event handling. To work around it, I'm simply avoiding that combination in Firefox: teamcapybara/capybara#2064.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=692139

**Comment by whimboo** [comment]
Yes, there was a bug that Ctrl + click didn't trigger the context menu, and this was fixed on https://bugzilla.mozilla.org/show_bug.cgi?id=1421323 for Firefox 62. 

So it sounds like everything is working fine here.
