### ISSUE TITLE
Travis caches built files

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#132]
I think. They should be deleted after the deploy (if any).

**Comment by AutomatedTester** [comment]
@jgraham is this still an issue or can we close?

**Comment by whimboo** [comment]
@andreastt given that you did all the last releases, was this ever a problem for you?

**Comment by andreastt** [comment]
Since we don’t build regularly on Travis anymore, it is at least for that reason not a concern we have at the moment.
