### ISSUE TITLE
Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by noobslayer404** [mozilla/geckodriver#1322]
## system

* Version: geckodriver-v0.21.0
* Platform: kali linux 2018
* Firefox: firefox 61 
* Selenium: selenium 3.13

## Testcase

from selenium import webdriver
import socks
import socket
import os

def connect_tor():
    socks.set_default_proxy(socks.PROXY_TYPE_SOCKS5, '127.0.0.1', 9050, True)
    socket.socket = socks.socksocket

def main():
    connect_tor()
    os.chdir('/etc/firefox')
    try:
        driver = webdriver.Firefox(r'/etc/firefox')
        driver.get("https://www.amazon.com")
        print(driver.title)
        element = driver.find_element_by_id("twotabsearchtextbox")
        usr_input = "lol"
        element.send_keys(usr_input)
        element = driver.find_element_by_css_selector('.nav-search-submit .nav-input').click()
        driver.close()
    except TimeoutError:
        print("fail")

if __name__ == '__main__':

    main()

## Trace-level log

/usr/bin/python3.6 /root/Desktop/selenium_training.py
Traceback (most recent call last):
  File "/root/Desktop/selenium_training.py", line 31, in <module>
    main()
  File "/root/Desktop/selenium_training.py", line 17, in main
    driver = webdriver.Firefox(r'/etc/firefox')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 160, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by noobslayer404** [comment]
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2179281/geckodriver.log)
also i would like to mention that i get an os error address already in use, i checked netstat and here are my results i tried reinstalling gecko but the same error kept poping.
![netstat](https://user-images.githubusercontent.com/26854386/42495777-bd96e58a-842c-11e8-9e4e-58605588249c.PNG)
![os-error](https://user-images.githubusercontent.com/26854386/42495778-bdb900a2-842c-11e8-8fb4-a6614fb8708f.PNG)

**Comment by andreastt** [comment]
I’m afraid what you attached is not a trace-level log. See documentation at https://searchfox.org/mozilla-central/search?q=TraceLogs.md on how to increase the logging verbosity.

It’s not really clear to me what issue you are having exactly. You cannot have multiple geckodrivers running on the same port.

**Comment by noobslayer404** [comment]
the issue is that after opening Firefox which worked when i added to my code: 

DesiredCapabilities().FIREFOX

the Browser stops at the default opening page, so the code stops working at:

driver.get("https://www.amazon.com")

**Comment by noobslayer404** [comment]
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2188261/geckodriver.log)

**Comment by whimboo** [comment]
The version of Firefox you have downloaded is not compatible with your system. See the failure line `Couldn't load XPCOM.` in the log. Maybe you run a 32bit system, and downloaded the 64bit version? As long as you cannot run Firefox manually, the automation won't work neither.
