### ISSUE TITLE
geckodriver-v0.9.0.tar.gz filename causes problem as missing last hypen

### ISSUE THREAD

**Issue by airudah2000** [mozilla/geckodriver#133]
Hi,

We are using io.github.bonigarcia.wdm.BrowserManager which downloads the latest geckodriver.

It expect the format of the filename to have two hypens. All the but the last file do have two, but the last doesn't and causes a `java.lang.StringIndexOutOfBoundsException:`
geckodriver-v0.9.0-arm7hf.tar.gz
geckodriver-v0.9.0-linux64.tar.gz
geckodriver-v0.9.0-mac.tar.gz
geckodriver-v0.9.0-win64.zip
geckodriver-v0.9.0.tar.gz 

Our automated tests have just started failing and we have traced it down to this. 

It is possible for the last file to be renamed to something with two hypens, e.g. geckodriver-v0.9.0-all.tar.gz ?

**Comment by jgraham** [comment]
I plan to remove this source tarball for the next release as it is duplicating functionality provided by github.

**Comment by bonigarcia** [comment]
Could you please remove it also for 0.9.0 release?

**Comment by jgraham** [comment]
I can, but I strongly feel your code should just ignore filenames that aren't in the expected format, rather than crashing. The exact form of the filenames isn't supposed to be a guaranteed-stable public API.

**Comment by bonigarcia** [comment]
I am going to fix it, but at this moment it is a open bug of WebDriverManager.

Nevertheless it can be easily solved simply removing that file. As you said, the source is already provided by GitHub.

**Comment by airudah2000** [comment]
I agree it should be removed if as you say, it's duplicating an existing functionality, never mind the trickle down effect on other libraries.
I'll also expect the file naming convention stays consistent as it has in all previous releases.
