### ISSUE TITLE
Webdriver-active flag support

### ISSUE THREAD

**Issue by erotavlas85** [mozilla/geckodriver#1330]
Hi,
I just wonder to know if geckodriver already supports [webdriver-active flag](https://w3c.github.io/webdriver/#interface). This allows to a Web site to detect BOT-like activity.
I'm using the latest version v.0.21.0 under GNU/linux 64 bit kernel 4.13.x with selenium v3.11 and python v3.5.
Thank you

**Comment by andreastt** [comment]
Firefox supports the `navigator.webdriver` IDL attribute. It is however not meant for sites to detect bot activity, as this is virtually impossible. Its primary function is to indicate to the document that it is under test so that you no longer need an in-house standard to do that.

**Comment by erotavlas85** [comment]
According to [this](https://intoli.com/blog/not-possible-to-block-chrome-headless/) it is possible and you have to follow a workaround. The tutorial is for chromium. Is there any clever way to achieve the same with firefox?

**Comment by andreastt** [comment]
Achieve the same? That document talks about the fact that it is _not_ possible to detect a headless/automated Chrome instance. That is also true for Firefox.
