### ISSUE TITLE
Link to  Firefox remote protocol is broken

### ISSUE THREAD

**Issue by Gozala** [mozilla/geckodriver#1332]
I've being trying to learn what commands does geckodriver supports but link in readme to  "Firefox remote protocol" is to a outdated MDN page that also points to broken other links

**Comment by andreastt** [comment]
Thanks for letting us know!

I’ve fixed most of the links in https://bugzilla.mozilla.org/show_bug.cgi?id=1477300 and will mirror over the changes to GitHub once they land in central.

Can you link me to which MDN pages had broken links?

**Comment by Gozala** [comment]
Then one I was referring is in readme and is this one:

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette

**Comment by andreastt** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1477468 requesting a permanent redirect of https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette to https://firefox-source-docs.mozilla.org/testing/marionette/marionette/ too.

I’ve also mirrored over the README changes to GitHub. It seems GitHub in the meantime has changed their table layouts causing some of the table entries to break at inappropriate pages. I will see if I can fix this as well.
