### ISSUE TITLE
Selenium not opening Tor correctly using Python

### ISSUE THREAD

**Issue by Alex24500** [mozilla/geckodriver#1333]
from selenium import webdriver
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

#path to TOR binary
binary = FirefoxBinary(r"C:...\Desktop\Tor Browser\Browser\firefox.exe")
#path to TOR profile
profile = FirefoxProfile(r"C:...\Desktop\Tor Browser\Browser\TorBrowser\Data\Browser\profile.default")

driver = webdriver.Firefox(firefox_binary=binary)
driver = webdriver.Firefox(firefox_profile= profile, firefox_binary= binary)
driver.profile.set_preference('network.proxy.type', 1)
driver.profile.set_preference('network.proxy.socks', '127.0.0.1')
driver.profile.set_preference('network.proxy.socks_port', 9150)
driver.get("http://google.com")
driver.quit()

## Problem

It seems that the driver.get command does not work, it doesn't open Google.

## System

* Version: <geckodriver-v0.21.0-win64>
* Platform: <Windows 10>
* Selenium: <3.12.0>

**Comment by andreastt** [comment]
I believe the Tor browser is based on Firefox 52 ESR, which is not supported by geckodriver.
