### ISSUE TITLE
can't save HTM(text/html) files to disk

### ISSUE THREAD

**Issue by fireson-gor** [mozilla/geckodriver#1335]
it's not work for *.htm page save to disk of firefox61 and geckodriver.exe, windows server2012 etc..
code is below, only pdf,xls,doc files can save when click the link of files. HTM(text/html) files will be opened in the firefox.

java code:

FirefoxOptions desiredCapabilities = new FirefoxOptions();
        desiredCapabilities.addPreference("browser.download.dir", "d:\\hkex\\pdf"); 
        desiredCapabilities.addPreference("browser.download.folderList", 2);
        desiredCapabilities.addPreference("pdfjs.enabledCache.initialized", true);
        desiredCapabilities.addPreference("pdfjs.enabledCache.state", false);
        desiredCapabilities.addPreference("pdfjs.migrationVersion", 2);
        desiredCapabilities.addPreference("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
        desiredCapabilities.addPreference("pdfjs.previousHandler.preferredAction", 4);        desiredCapabilities.addPreference("browser.helperApps.neverAsk.saveToDisk","application/pdf,application/msword,application/x-xls,application/vnd.ms-excel,text/html,application/xhtml+xml,application/xml");

**Comment by whimboo** [comment]
If you only want to download a HTML file using Selenium is probably the wrong way. There are plenty of libraries around eg. curl which let you do that easier.

If you only need the content of a HTML or text file, there is the [Get Page Source](https://w3c.github.io/webdriver/#get-page-source) command available for Selenium. You will have to check how Java implements that.

**Comment by fireson-gor** [comment]
thanks ，i fixed it
