### ISSUE TITLE
Selenium throwing an error but, the script is working fine. Please help here to fix the issue

### ISSUE THREAD

**Issue by vetrivel-muthusamy** [mozilla/geckodriver#1337]
## System

* Version: 0.21
* Platform: Windows 8.1
* Firefox: 60.0.2
* Selenium: 3.13

## Stacktrace

1532785648976	geckodriver	INFO	geckodriver 0.21.0
1532785648991	geckodriver	INFO	Listening on 127.0.0.1:45769
1532785649616	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\612005~1\\AppData\\Local\\Temp\\rust_mozprofile.2XlWf107hIzV"
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
1532785653776	Marionette	INFO	Listening on port 54246
1532785654392	Marionette	WARN	TLS certificate errors will be ignored for this session
Jul 28, 2018 7:17:34 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Unable to read VR Path Registry from C:\Users\612005424\AppData\Local\openvr\openvrpaths.vrpath
[Parent 6048, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\612005424\AppData\Local\openvr\openvrpaths.vrpath
[Child 5808, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 5808, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 6048, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\612005424\AppData\Local\openvr\openvrpaths.vrpath
[Child 5124, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 5124, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

**Comment by andreastt** [comment]
This is not geckodriver error, but a warning from the IPC subsystem in Firefox.

**Comment by whimboo** [comment]
I wouldn't go that far and close the issue immediately. First I would like to know some more details from @vetrivel-muthusamy...

1) The log show issues with your installed graphics driver. Can you please check its installation and correct the problem? None of those `GFX` lines should then appear in Firefox. Does it help?

2) You didn't specify any  source code in how you setup the driver and profile. Can you please show it to us? Is there anything special?

3) Is the test run under a normal user account, task, or service?

**Comment by divyakheria** [comment]
Hi @whimboo 

I am also getting a similar error when I try to run my script. Script runs fine but i get these error logs every time I try to run my script using geckodriver.

1535536924854	geckodriver	INFO	geckodriver 0.21.0
1535536924888	geckodriver	INFO	Listening on 127.0.0.1:22772
1535536926269	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\SAURAB~1\\AppData\\Local\\Temp\\rust_mozprofile.tSPZMdiX9Jee"
Unable to read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath
Unable to Unable to read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath
read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath
1535536942402	Marionette	INFO	Listening on port 65180
[Child 13652, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 13652, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1535536942760	Marionette	WARN	TLS certificate errors will be ignored for this session
Aug 29, 2018 3:32:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Unable to read VR Path Registry from C:\Users\Saurabh Bhasin\AppData\Local\openvr\openvrpaths.vrpath

Hope you can help.

Thanks

**Comment by divyakheria** [comment]
I ran following script:

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class LearnLocators {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		System.setProperty("webdriver.gecko.driver","C:\\Selenium\\geckodriver.exe"); //invoke .exe file for chrome driver
		WebDriver driver=new FirefoxDriver(); //create driver object for FF browser
		driver.get("https://login.salesforce.com/?locale=in");
		driver.findElement(By.name("username")).sendKeys("divya");
		driver.findElement(By.name("pw")).sendKeys("12345");
		driver.findElement(By.name("Login")).click();
	
	}

}

**Comment by whimboo** [comment]
@divyakheria, please don't hijack other issues but file your own one with all the details. Also I don't see how it should be related at all.

**Comment by whimboo** [comment]
Sadly no feedback from @vetrivel-muthusamy within 27 days. Closing issue now.

**Comment by whimboo** [comment]
@josephpissac this issue is closed, as such you should create your own one because it is not sure you are facing the same problem. Once you do make sure to provide all the information. The source alone is not that helpful.
