### ISSUE TITLE
Unable to launch the firefox on selenium grid (3.13.0)

### ISSUE THREAD

**Issue by Abhilash04** [mozilla/geckodriver#1342]
## System

* Version: 0.21
* Platform: Windows 10 
* Firefox: 61
* Selenium: 3.13.0

## Testcase

firefox_capabilities = webdriver.DesiredCapabilities.FIREFOX
firefox_capabilities['platform'] = self.platform
firefox_capabilities['browserName'] = 'firefox'
firefox_capabilities['javascriptEnabled'] = True
firefox_capabilities['marionette'] = True

opt = ff_options()
opt.log.level = 'trace'

driver = webdriver.Remote(command_executor='GRID_SERVER',desired_capabilities=firefox_capabilities, options=opt)

## Stacktrace

# Logs from grid console

19:02:33.199 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1533216753339   geckodriver     INFO    geckodriver 0.21.0
1533216753370   geckodriver     INFO    Listening on 127.0.0.1:27279
19:02:33.917 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "firefox",
  "javascriptEnabled": true,
  "marionette": true,
  "moz:firefoxOptions": {
    "log": {
      "level": "trace"
    }
  },
  "platform": "WINDOWS"
}

# Logs from IDE

selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
E       Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
E       System info: host: '<grid host>', ip: '<ip address>', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
E       Driver info: driver.version: unknown
E       remote stacktrace: 
E       Stacktrace:
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (None:-2)
E           at sun.reflect.NativeConstructorAccessorImpl.newInstance (None:-1)
E           at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (None:-1)
E           at java.lang.reflect.Constructor.newInstance (None:-1)
E           at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0 (W3CHandshakeResponse.java:57)
E           at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2 (W3CHandshakeResponse.java:104)
E           at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0 (ProtocolHandshake.java:123)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.Spliterators$ArraySpliterator.tryAdvance (None:-1)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyInto (None:-1)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
E           at java.util.stream.AbstractPipeline.evaluate (None:-1)
E           at java.util.stream.ReferencePipeline.findFirst (None:-1)
E           at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:126)
E           at org.openqa.selenium.remote.ProtocolHandshake.createSession (ProtocolHandshake.java:73)
E           at org.openqa.selenium.remote.server.RemoteSession$Factory.performHandshake (RemoteSession.java:145)
E           at org.openqa.selenium.remote.server.ServicedSession$Factory.apply (ServicedSession.java:160)
E           at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12 (ActiveSessionFactory.java:177)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$11$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
E           at java.util.Spliterators$ArraySpliterator.tryAdvance (None:-1)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyInto (None:-1)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
E           at java.util.stream.AbstractPipeline.evaluate (None:-1)
E           at java.util.stream.ReferencePipeline.findFirst (None:-1)
E           at org.openqa.selenium.remote.server.ActiveSessionFactory.apply (ActiveSessionFactory.java:180)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2 (NewSessionPipeline.java:65)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
E           at java.util.Collections$2.tryAdvance (None:-1)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyInto (None:-1)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
E           at java.util.stream.AbstractPipeline.evaluate (None:-1)
E           at java.util.stream.ReferencePipeline.findFirst (None:-1)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3 (NewSessionPipeline.java:68)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.DistinctOps$1$2.accept (None:-1)
E           at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$3$1.accept (None:-1)
E           at java.util.stream.ReferencePipeline$2$1.accept (None:-1)
E           at java.util.stream.Streams$StreamBuilderImpl.tryAdvance (None:-1)
E           at java.util.stream.Streams$ConcatSpliterator.tryAdvance (None:-1)
E           at java.util.stream.ReferencePipeline.forEachWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyIntoWithCancel (None:-1)
E           at java.util.stream.AbstractPipeline.copyInto (None:-1)
E           at java.util.stream.AbstractPipeline.wrapAndCopyInto (None:-1)
E           at java.util.stream.FindOps$FindOp.evaluateSequential (None:-1)
E           at java.util.stream.AbstractPipeline.evaluate (None:-1)
E           at java.util.stream.ReferencePipeline.findFirst (None:-1)
E           at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession (NewSessionPipeline.java:71)
E           at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute (BeginSession.java:65)
E           at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$3 (WebDriverServlet.java:247)
E           at java.util.concurrent.Executors$RunnableAdapter.call (None:-1)
E           at java.util.concurrent.FutureTask.run (None:-1)
E           at java.util.concurrent.ThreadPoolExecutor.runWorker (None:-1)
E           at java.util.concurrent.ThreadPoolExecutor$Worker.run (None:-1)
E           at java.lang.Thread.run (None:-1)

..\..\..\appdata\local\programs\python\python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py:242: SessionNotCreatedException

## Trace-level log

Unable to generate the trace-level logs while invoking the browser on grid.

I am running locally with same configuration and it's working fine. Unable to execute on grid.

**Comment by whimboo** [comment]
The platform should be `windows` and not `WINDOWS`. If you fix that it should work with Firefox Nightly 63.0a. For older releases please see issue #1030.

Marking as dupe.

**Comment by Abhilash04** [comment]
I'm using windows as platform only still not able to launch it. Same error is coming.

**Comment by whimboo** [comment]
Please attach an updated log.
