### ISSUE TITLE
Issue with the 'moz:firefoxOptions.binary'

### ISSUE THREAD

**Issue by cemol** [mozilla/geckodriver#1344]
## System

* Version: geckodriver 0.21.0 
* Platform: Linux/Windows 10
* Firefox: 
* Selenium: 

I have some issue with the 'moz:firefoxOptions.binary', i'm trying to open firefox with the gecodriver.

I'm trying to run selenium-side-runner with firefox on windows (and linux), but with no luck. I have downloaded the `geckodriver-0.21.0`, and included it in PATH. But when I run 
`selenium-side-runner -c "browserName=firefox" project.side`

I got this error:
```
FAIL ./project.test.js
  ● Test suite failed to run

    SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

```

What am I doing wrong or forgetting? What is wrong with the 'moz:firefoxOptions.binary'?
Where do i find the binary file?

**Comment by andreastt** [comment]
This means it can’t find the Firefox installation on your system. On Windows it looks in the Windows Registry for the installation path, and on Linux it looks in your system path for a `firefox` executable.

If you have Firefox installed in a non-default location which is not in your system’s search path, you can specify a `binary` field on the `moz:firefoxOptions` capabilities object (documented in README), or use the `--binary PATH` flag passed to geckodriver when it starts.

**Comment by cemol** [comment]
Thanks! Now I have able to fix it :)

**Comment by andreastt** [comment]
Great!

**Comment by qshwa3** [comment]
how fixed
