### ISSUE TITLE
Firefox capabilities  "useNonSpecCompliantPointerOrigin" not working

### ISSUE THREAD

**Issue by aglo65** [mozilla/geckodriver#1351]
## System

* Version: geckodriver 21
* Platform: macOS High Sierra 10.13.5
* Firefox: 61.0.2
* Selenium: 3.12

## Testcase

```
package com.java.testcases;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testng.annotations.Test;
import com.utility.generic.CoordinateUtils;
  
public class Test1 extends CoordinateUtils {

  @Test
    public void tc_AG_Cont_clickOnLadyBug(){
    	 System.setProperty("webdriver.gecko.driver", "/Users/test/workspace/WebDrivers/geckodriver");

    	 FirefoxOptions firefoxOptions = new FirefoxOptions();
    	 firefoxOptions.setCapability("moz:useNonSpecCompliantPointerOrigin", false);
    	 WebDriver driver = new FirefoxDriver(firefoxOptions);
   
String appUrl = "https://html5.tremorvideodsp.com/v7.0.17/index.html?#/desktop/default/jwplayer/basic?playerOptions%5Bautostart%5D=true&playerOptions%5Baspectratio%5D=16%3A9&playerOptions%5Badvertising%5D%5Bclient%5D=vast&playerOptions%5Badvertising%5D%5Badmessage%5D=Ad%20%E2%80%94%20xxs%20left&playerOptions%5Badvertising%5D%5Bautoplayadsmuted%5D=true&playerOptions%5Badvertising%5D%5Btag%5D=https%3A%2F%2Fs.tremorvideodsp.com%2Fm%2F2017%2F09%2FSkZvFXP9Z%2Fvast3.xml&playerOptions%5Bfile%5D=https%3A%2F%2Fwww.apple.com%2Fmedia%2Fus%2Fwatch%2F2015%2Fa718f271_b19c_47d8_928d_d108fc5d702a%2Ftour%2Fdesign%2Fwatch-design-cc-us-20140909_1280x720h.mp4&playerOptions%5Bid%5D=tesgreenayted3&adTagUri=https%3A%2F%2Fpterodactylus.tremorvideodsp.com%2Fws%2Frml%2Freplacer%3FvastUri%3Dhttps%253A%252F%252Fs.tremorvideodsp.com%252Fm%252F2018%252F08%252FEKJF7GwmH%252Fvast3.xml%26addTVEvents%3Dtrue%26sessionId%3Df87ca66d668ab0761d99f811b0dfddd84c2de635_tc_AFD3712_TimerIncreasesWhenLongformVideoBegins_1533359435209";
    	 
    	
    	
   //launch the firefox browser and open the application url
   driver.get(appUrl);
    	    
    //maximize the browser window
     driver.manage().window().maximize();

     waitFor(8);
     CoordinateUtils.clickAtBottomLeftIcon(driver, getCanvas());
  
    	     
  // close the web browser
   driver.close();
 	
}
}
```

## Stacktrace

> [RemoteTestNG] detected TestNG version 6.8.0
> [TestNG] Running:
>   /private/var/folders/gq/cphkhfzx3m1bjtpwdrg6782syxkt2_/T/testng-eclipse--1118580967/testng-customsuite.xml
> 
> 1534202341499	geckodriver	INFO	geckodriver 0.21.0
> 1534202341504	geckodriver	INFO	Listening on 127.0.0.1:10158
> 1534202341821	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/gq/cphkhfzx3m1bjtpwdrg6782syxkt2_/T/rust_mozprofile.HTNltADEbLOa"
> 1534202342360	addons.xpi-utils	WARN	addMetadata: Add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} is invalid: Error: Install manifest specifies unknown type: theme (resource://gre/modules/addons/XPIInstall.jsm:721:11) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:721:11
> loadFromRDF@XPIInstall.jsm:893:23
> awaitPromise@XPIProvider.jsm:240:3
> syncLoadManifestFromFile@XPIInstall.jsm:981:10
> addMetadata@XPIDatabase.jsm:2490:21
> processFileChanges@XPIDatabase.jsm:2833:23
> checkForChanges@XPIProvider.jsm:2139:34
> startup@XPIProvider.jsm:1591:25
> callProvider@AddonManager.jsm:207:12
> _startProvider@AddonManager.jsm:655:5
> startup@AddonManager.jsm:819:9
> startup@AddonManager.jsm:2885:5
> observe@addonManager.js:66:9
> 1534202342361	addons.xpi-utils	WARN	Could not uninstall invalid item from locked install location
> 2018-08-13 16:19:03.114 plugin-container[98711:23259883] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8043, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 2018-08-13 16:19:03.367 plugin-container[98712:23259915] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7c07, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 2189: TypeError: addon is null
> 1534202343538	Marionette	INFO	Listening on port 53579
> 1534202343581	Marionette	WARN	TLS certificate errors will be ignored for this session
> Aug 13, 2018 4:19:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C
> 2018-08-13 16:19:04.092 plugin-container[98713:23260035] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x873f, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> 13 Aug 2018 16:19:13  INFO logger - Clicking on Lady Bug
> Aug 13, 2018 4:19:13 PM org.openqa.selenium.interactions.Actions moveToElement
> INFO: When using the W3C Action commands, offsets are from the center of element
> FAILED: tc_AG_Cont_clickOnLadyBug
> java.lang.NullPointerException
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
> 	at org.openqa.selenium.interactions.PointerInput$Origin.fromElement(PointerInput.java:221)
> 	at org.openqa.selenium.interactions.Actions.moveInTicks(Actions.java:418)
> 	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:412)
> 	at com.utility.generic.CoordinateUtils.clickAtBottomLeftIcon(CoordinateUtils.java:72)
> 	at com.java.testcases.Test1.tc_AG_Cont_clickOnLadyBug(Test1.java:35)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
> 	at org.testng.TestRunner.run(TestRunner.java:617)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
> 	at org.testng.TestNG.run(TestNG.java:1031)
> 	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
> 	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
> 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by aglo65** [comment]
I'm newbie in using gecko driver in automation and this is my first issue that I'm posting here. 
I'm facing a problem with selenium click() on canvas using x, y coordinates on Firefox. The script 
moveToElement(WebElement, xOffset, yOffset) was working on Firefox 58 but start failing on 59 and above. I've found that moveToElement() function is usng the in-view centre point of the element instead of top left (0 , 0).
> From the WebDriver spec 17.4.3 Pointer Actions "dispatch a pointerMove action".
> An object that represents a web element
> Let element be equal to the result of trying to get a known element with argument origin.
> Let x element and y element be the result of calculating the in-view center point of element.
> Let x equal x element + x offset, and y equal y element + y offset.

However, because some clients like Selenium are behind and not supporting the latest changes yet, there were a new (Firefox specific) capabilities introduced as a temp workaround before W3C supported across all the clients and browsers.

So I'm trying to use these capabilities in my test environment(see for details under test section above) and it seems not working. Can some one help me here , please?

**Comment by whimboo** [comment]
Please provide a [trace level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html).

**Comment by aglo65** [comment]
I've added the log trace capability(see below) and re-ran the test (
[LogTrace.txt](https://github.com/mozilla/geckodriver/files/2288068/LogTrace.txt)

 is attached for your reference. Thanks for looking at it  @whimboo  !
`   
    	 FirefoxOptions firefoxOptions = new FirefoxOptions();
    	 firefoxOptions.setCapability("moz:useNonSpecCompliantPointerOrigin", false);
    	 firefoxOptions.setLogLevel(FirefoxDriverLogLevel.TRACE);
    	 WebDriver driver = new FirefoxDriver(firefoxOptions);
`

**Comment by whimboo** [comment]
@aglo65 why are you setting `moz:useNonSpecCompliantPointerOrigin` to `false` now? If you don't want the WebDriver spec behavior it has to be set to `true`. Please provide a new trace log.

**Comment by aglo65** [comment]
Trace log with `moz:useNonSpecCompliantPointerOrigin ` set to `true` is attached.
[TraceLog2.txt](https://github.com/mozilla/geckodriver/files/2291112/TraceLog2.txt)
 Thanks for your feedback, @whimboo !

**Comment by whimboo** [comment]
This has to be a bug in the Java code of the Selenium client you are using. As such there is no action command sent to geckodriver at all because it crashes already before. Please file an issue against the Selenium client project.
