### ISSUE TITLE
Actions.pause() with large pause causes subsequent release() to fail

### ISSUE THREAD

**Issue by gwtuser** [mozilla/geckodriver#1352]
## System

* Version: 21
* Platform: OpenSUSE 42.3 Linux 64-bit
* Firefox: 60.1.0ESR
* Selenium: 3.14

Issue is that when you use an Actions sequence that pause()s with the mouse down, the mouse can get STUCK down, so that the release() no-ops, and even running a separate action sequence afterwards Actions.release().perform() doesn't unstick the button.

I've seen this behavior with pause values as low as 200ms, but it starts happening very often at values around 1000ms.

Here is a code fragment, where element is some WebElement that can be dragged.  If you need the actual element, and HTML, i can create them, but just about anything that can be dragged will work:

`for (int i = 0; i < 100; i++) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`actions.clickAndHold(element);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`actions.moveByOffset(i%2==0 ? 200 : -200, 0);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`actions.pause(1000).release().perform();`
`}`

If you run this code snippet, you'll see the element start going back and forth, but after a few times it will stop even though the loop isn't done.  If you move your mouse into the browser at that point, you'll see the element move with your mouse - because the mouse button is stuck down.

Not only does this break the immediate action, but for me it seems to block all future communication with the browser and WebDriver.

(Finally, if you're wondering why I use pause() at all, it's because there's a separate bug I'm hitting where doing a drag like I do above (Actions.clickAndHold.moveByOffset().release()), will short-stroke without the pause, meaning that if I tell it to go 200px it will only go 190px (for example).  I plan on fiiling that as a separate bug, but am having trouble writing a standalone test case, as it only seems to happen in our JS Framework which executes JS as DOM elements are moved around.)

As mentioned, I can provide the exact HTML and WebDriver Java beyond the snippet if needed, but I think the devs here probably don't need more than that snippet to reproduce the problem.

**Comment by whimboo** [comment]
Please attach a [trace level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) which would show the failure. Given that each client has a different implementation there is nothing I can tell by just seeing your comment above.

Also a simplified testcase + HTML would be great.

**Comment by gwtuser** [comment]
I assumed that you'd have a test environment for each major platform (Linux, Windows, etc.) ready to go and could just drop snippets of WebDriver code into it to test them.  However, I've provided what was requested:
- the complete WebDriver code, as a JUnit test [MyTest.java.txt](https://github.com/mozilla/geckodriver/files/2288946/MyTest.java.txt)
- the HTML targeted by that test code [dragAndCalc.html.txt](https://github.com/mozilla/geckodriver/files/2288947/dragAndCalc.html.txt)
- the trace log output; note that the trace stops at the moment of the hang [geckodriver-log.txt](https://github.com/mozilla/geckodriver/files/2288948/geckodriver-log.txt)

As mentioned above, when you run this snippet, you'll see the element start to go back and forth under drag operations, but after a handful of cycles, it will stop, and you'll notice that if you move your mouse into the browser, the element will move with your mouse because the browser thinks button is still down.  The WebDriver code will hang at this point as well, even if you manually click the mouse to unstick the button.

**Comment by whimboo** [comment]
Well, we cannot cover each combination of platform, client, and hardware which all can introduce different behavior. As such and similar to other projects a bit of assistance is welcome so we can better and earlier figure out the problem and fix it. 

I checked the trace log for now and wonder if your problem might be related to [bug 1447449](https://bugzilla.mozilla.org/show_bug.cgi?id=1447449). You make use of a pause action for each command, and also delay the drag operation. Would you mind to try what happens when you remove the pause and the drag delays? Does it work in that case?

**Comment by whimboo** [comment]
Ok. Then lets track it in that bug. I will leave this issue open until it has been fixed.

**Comment by whimboo** [comment]
This is now fixed for Firefox 63 Nightly by the before-mentioned bug. We are working on uplifts for Firefox 62, and probably Firefox 60 ESR too.

**Comment by whimboo** [comment]
FYI the patch has been uplifted, so both the final Firefox 62 release, and the next Firefox 60ESR release will contain this fix.
