### ISSUE TITLE
GeckoDriver should work in IPv6-only environment

### ISSUE THREAD

**Issue by DrMarcII** [mozilla/geckodriver#1356]
## System

* Version: 0.21.0
* Platform: Linux
* Firefox: Any
* Selenium: Any

We use GeckoDriver in a Linux environment that has no IPv4 network stack. To get Firefox working in this environment we use a hack that uses an LD_PRELOAD library to make it use IPv6 connections when IPv4 connections are requested. In this environment, we need GeckoDriver to fallback to using IPv6 when IPv4 is not available (we tried using the same LD_PRELOAD with GeckoDriver as we use with Firefox and it did not work).

**Comment by andreastt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1483996

**Comment by whimboo** [comment]
geckodriver 0.24.0 has been released two days ago. Marking as fixed.
