### ISSUE TITLE
Screenshot in headless mode doesn't show form controls correctly

### ISSUE THREAD

**Issue by 04cfb1ed** [mozilla/geckodriver#1358]
Hello

When I take a screenshot using Selenium and headless mode, the screenshot doesn't show the borders of button and background, this only happens with headless mode activated.

The problem is present in inputs, buttons, textarea, radio buttons, checkboxes, selects

## System

* Version: geckodriver-v0.21.0-linux64
* Platform: Debian GNU/Linux 9 (stretch) 64-bit
* Firefox: 60.0.2 (64 bit), 61.0.2 (64 bit), 62.2b2 (64-bit), 63.0a1 (2018-08-20) (64 bit) - Nightly
* Selenium: Version: 3.12.0

## Testcase
```python3
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

_geckoBinary = FirefoxBinary('/firefox-63.0a1.es-ES.linux-x86_64/firefox/firefox')
_geckoExecutablePath = '/geckodriver-v0.21.0-linux64/geckodriver'

# Or archivo = 'http://localhost/1.html'
archivo = 'file:///1.html'

options = Options()
options.log.level = "trace"
options.set_headless(headless=True)
geckoDriver = webdriver.Firefox(firefox_options=options, executable_path=_geckoExecutablePath,
								firefox_binary=_geckoBinary)
geckoDriver.get(archivo)
geckoDriver.save_screenshot('screenshot.png')
geckoDriver.quit()
```

For see the whole problem (buttons, textarea, radio buttons, checkboxes, select)

```python3
geckoDriver.get("https://www.tutorialspoint.com/html/html_forms.htm")
firefox_elem = geckoDriver.find_element_by_tag_name('html')
firefox_elem.screenshot('screenshot-forms.png')
geckoDriver.quit()
```

Apparently the problem is only with native controls, if the controls have modified CSS (i.e border: 1px dotted;) the problem doesn't occur

### HTML
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <button>Botón de prueba</button> <br/>
	<input type="text" /> <br/>
	<textarea></textarea> <br/>
	<input type="checkbox" />Test check <br/>
	<input type="checkbox" />Test radio <br/>
	<select>
		<option>First option</option>
		<option>Second option</option>
	</select>
</body>
</html>
```

### Expected result
![screenshot](https://user-images.githubusercontent.com/12877898/44366874-b7775900-a493-11e8-8834-d7873804e1ee.png)

### Actual result
![screenshot - copia](https://user-images.githubusercontent.com/12877898/44366750-58194900-a493-11e8-8a33-13f4de153865.png)
## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2303963/geckodriver.log)

**Comment by andreastt** [comment]
@brendandahl Is this a known bug with headless mode, or do we file one?

**Comment by brendandahl** [comment]
I'm guessing this is the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1385711

**Comment by whimboo** [comment]
I don't see any problems with Firefox Nightly on Mac. @04cfb1ed can you please check again with a build from https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly. Thanks.

**Comment by 04cfb1ed** [comment]
Hello @whimboo 

I just tried again and the problem remains with Firefox Nigthly

- firefox-74.0a1.en-US.linux-x86_6
- geckodriver-v0.26.0-linux64

As far as I know, the last comment by Michael Smith in [https://bugzilla.mozilla.org/show_bug.cgi?id=1385711]() says that the problem is only present in Linux

**Comment by whimboo** [comment]
Ok, thanks for the feedback. Given that this is an issue with Firefox then, I'm going to close this issue in favor of the other bug.
