### ISSUE TITLE
Unable to retrieve html elements (Element not found) exception

### ISSUE THREAD

**Issue by cpintea** [mozilla/geckodriver#1362]
## System

* Version: 0.20.1
* Platform: Windows 10PRO
* Firefox: 61.0.2 (32-bit)  
* Selenium: mink/ selenium2Driver / selenium server 3.12.0

Any idea why it happen? 

## Testcase
I am using Behat/Mink (php binding). Config is:
analyticsFF: desktop with GUI browser
  autoload:
    '': %paths.base%/Analytics/bootstrap/
  extensions:
    Behat\MinkExtension:
     # base_url: http://google.com
      goutte: ~
      selenium2:
        wd_host: "http://127.0.0.1:4444/wd/hub"
        #acceptSslCerts: "true"
        # use chrome browser
        browser: "firefox"
        capabilities: {"marionette": true, "browserName":"firefox", "browser":"firefox", "name":"Behat Test", "extra_capabilities": {"acceptInsecureCerts": true,  "moz:firefoxOptions": {"log": {"level": "trace"}}}}
  suites: # list of test suites available for current profile ("default" in this case)
    default: # this suite is called "default"
      paths: # check these paths
        features: %paths.base%/Features
        bootstrap: %paths.base%/Analytics/bootstrap/
      contexts: # use these contexts (test suites)
        - FeatureContextAnalytics: # FeatureContext class
        - Behat\MinkExtension\Context\RawMinkContext

google search
php(behat + minkExtension):
$test = $this->getSession()->getPage()->find('xpath', "//input[@id='lst-ib']");
this return null
$test = $this->getSession()->getPage();
it return valid data.

## Stacktrace
The html element is not returned . Basically no html elements are recognized.
The webDrive implemented in php-webdrive library return after a curl comands:
{"state":"success","sessionId":null,"hCode":-1866216477,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}

On chrome the return from curl is:
{"sessionId":"76d9dc61a87071b6f818c194d0bb10f9","status":0,"value":[{"ELEMENT":"0.5462148508585996-1"}]}

## Trace-level log
[marionette_trace.txt](https://github.com/mozilla/geckodriver/files/2331783/marionette_trace.txt)

Update:
 It is a problem of " php-webdrive" php binding. The " php-webdrive" dost support new gekodrive.
Issue can be closed. Sorry for it. 
https://github.com/facebook/php-webdriver/issues/469 - for php users

**Comment by whimboo** [comment]
Closing as requested.
