### ISSUE TITLE
Driver fails to click button when it is out of screen bounds

### ISSUE THREAD

**Issue by johno1985** [mozilla/geckodriver#1363]
## System

Windows 10
Selenium Version:
3.11.0
Browser:
Firefox 59.0.3 (64-bit)

Expected Behavior -
I expect the driver to scroll to the position of the button, and click it

Actual Behavior -
No scrolling occurs, the driver successfully finds the button and seems to successfully click it but nothing happens. No errors occur, the only error that occurs is my test assertion fails because it is expecting an effect of the button click, which did not happen

Steps to reproduce -
The following markup results in the button rendering beyond the screen boundary of my 15.6" laptop display

[New.folder.zip](https://github.com/mozilla/geckodriver/files/2332204/New.folder.zip)

The following Java code is used to click the button:

WebElement field = waiter.until(ExpectedConditions.visibilityOf( By.xpath("/html/body/div[contains(@class, 'container content')]/form//div[button[contains(text(), 'Purchase')]]//button"))); field.click();

When I run the test, pause on a debug, manually scroll to the bottom and then resume, my test passes  #OK

This issue was originally reported to Selenium who advised that this is an issue with the Gecko Driver - https://github.com/SeleniumHQ/selenium/issues/5874

**Comment by johno1985** [comment]
It don't believe it matters, submit() can be used on the form itself whereas click() must be used on the input type="submit" element itself. I am doing the latter

**Comment by andreastt** [comment]
Clicking on a button that is outside the bounds of the viewport that cannot be scrolled into view should not be possible. If it is possible to scroll the element into view, the button should be clicked.

Can you please provide a reproducible test case, e.g. a self-contained HTML document that showcases the problem?

**Comment by johno1985** [comment]
I don't see any reason why the button is not scroll-able. I believe the attached zip contains all the required assets to produce the test case. if you need anything else please give me a shout

**Comment by whimboo** [comment]
@johno1985 there is nothing we can do without a [trace level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html). Please note that this was requested when filing an issue.

I checked the HTML page and tried with Marionette and Firefox Nightly, Beta, and Release, which all worked fine for me with the following Selenium test (Python bindings):

```
def test_button(driver):
    time.sleep(1)
    driver.get("file:///Volumes/data/Users/henrik/Downloads/New%20folder/Launch%20BI%20Billing%20Information.html")
    button = driver.find_element_by_xpath("/html/body/div[1]/form/div[11]/div/button")
    button.click()
```

**Comment by johno1985** [comment]
Hi Henrik

To this date, a trace log had not been requested on this ticket. I will get
one to you ASAP.

In the mean time, please can you retest using the Java bindings?

Kind regards

Jonathan

**Comment by whimboo** [comment]
If it's failing with the Java bindings it would be a bug in Selenium then. I don't have a chance to test it.

**Comment by johno1985** [comment]
I originally logged the issue with selenium and they said it's an issue
with gecko. Please refer to the selenium issue in the description

Kind regards

Jonathan

**Comment by johno1985** [comment]
@whimboo please find attached trace logs as requested
[firefox-trace.log](https://github.com/mozilla/geckodriver/files/2345778/firefox-trace.log)

**Comment by whimboo** [comment]
This is not a trace log from geckodriver, but the log from Maven. If you don't know how to get it and no-one can help from the Selenium project, maybe try locally with a simplified testcase.

**Comment by johno1985** [comment]
I am trying this locally and this is a simple test case. I followed the instructions in the link you provided and that is the output that was generated. Perhaps you can add instructions on how to retrieve the geckodriver logs?

**Comment by whimboo** [comment]
Then please show your test code. It's not part of the zip file in your original comment.

**Comment by johno1985** [comment]
As I am using Selenium with Cucumber and JUnit, the test code is somewhat extensive. I would have thought that the snippet I pasted above would suffice

**Comment by whimboo** [comment]
Again, this works for me with the Python bindings, or Marionette. See https://github.com/mozilla/geckodriver/issues/1363#issuecomment-418037171.

**Comment by johno1985** [comment]
Again, I'm not using the Python bindings, I'm using the java ones

**Comment by whimboo** [comment]
Then there is something you are doing wrong, or the provided HTML snippet is not mirroring your problem correctly. Check that, and provide a trace level log. Until then there is nothing we can do.

**Comment by whimboo** [comment]
In terms of geckodriver it's totally irrelevant which binding you are using. If it works for me, but not for you then something is wrong with the binding, or your test. If there are other people having this problem too then work with them together in how to retrieve a trace log, and to create a testcase which clearly demonstrates the problem. 

I'm happy to reopen once there is a way to reproduce.

Also please note that I'm one of the maintainers of geckodriver and know how to investigate issues.

**Comment by johno1985** [comment]
@whimboo as you are a maintainer of geckodriver and are asking me to provide a trace log, then please add instructions on how to do this.

**Comment by johno1985** [comment]
Also @whimboo to investigate/reproduce an issue, one should remove as many variables as possible, in this case, that means using the same binding. You say that the choice of binding does not matter, but even so, what if? Also, as previously stated, I have already reported this issue under the Selenium project - https://github.com/SeleniumHQ/selenium/issues/5874 and have been advised that this is a Gecko issue - https://github.com/SeleniumHQ/selenium/issues/5874#issuecomment-396662896

**Comment by johno1985** [comment]
@twalpole also, I followed the instructions and have attached the output in a earlier comment but @whimboo stated that the content of the attached file is not a Geckodriver log file

**Comment by twalpole** [comment]
@johno1985 You didn't attach a trace log - It would show every call made to geckodriver if you had, so obviously you're not turning on the logging (to the "trace" level) in Selenium correctly - The Selenium project would have to tell you how to pass those options through to their client (or by reading the instructions and/or thread I posted above)

**Comment by johno1985** [comment]
@twalpole right you are. Apologies. I saw the output generate on my console and I assumed that the output had also been written to that file. I used the following command in my test project:
mvn clean install > trace.log
expecting that the output generated would also be present in the file, but it was not

**Comment by johno1985** [comment]
@twalpole @whimboo please find attached the trace log file, this time actually containing the correct output!
[trace.log](https://github.com/mozilla/geckodriver/files/2349575/trace.log)

**Comment by whimboo** [comment]
There is nothing in the trace log which would indicate that there is a problem. The click on Purchase seems to work fine, except that click returns immediately because it doesn't detect a page load. Maybe there is a custom onclick handler set, which interferes with the page load process. 

```
1536082076708	Marionette	TRACE	0 -> [0,87,"WebDriver:ElementClick",{"id":"65d17780-4fc1-40b4-b9ee-3f61f4401aaa"}]
1536082077412	Marionette	DEBUG	Canceled page load listener because no navigation has been detected
1536082077414	Marionette	TRACE	0 <- [1,87,null,{}]
1536082077415	webdriver::server	DEBUG	<- 200 OK {"value": null}
```

That means as long there is no reproducible testcase available to us, there is nothing we can do.

**Comment by johno1985** [comment]
I can confirm that there is no custom click handler.

Can you confirm which version of Firefox you are using?

**Comment by johno1985** [comment]
At the time I originally reported the issue (with the selenium team)
version 59 was the latest version

**Comment by johno1985** [comment]
Also, please note that the 'detect page load' issue you mentioned earlier does not occur when I maximise the browser window during the test, resulting in a test pass
[trace2.log](https://github.com/mozilla/geckodriver/files/2353407/trace2.log)

**Comment by johno1985** [comment]
Also, according to your docs - https://github.com/mozilla/geckodriver - you current support firefox version 57.0 and above

**Comment by twalpole** [comment]
@johno1985 Rather than arguing about supported versions, could you please just try your test on the latest Firefox version (62) and see if the problem still exists.  If it was/is an issue in FF or marionette rather than geckodriver it would probably only get fixed in newer versions anyway, so the current release is all that really matters.

**Comment by johno1985** [comment]
@twalpole I will try that but what concerns me is that if there is an issue with geckodriver that is masked by the latest version of firefox, then that issue may never get fixed and may resurface in a future version of firefox

**Comment by twalpole** [comment]
geckodriver talks to marionette which is part of Firefox - any issue here is actually more likely to be in marionette - geckodriver is really just a translation layer from webdriver to marionette
