### ISSUE TITLE
The browser.link.open_newwindow config is not working

### ISSUE THREAD

**Issue by decreteii** [mozilla/geckodriver#1368]
hello,

* Version: 0.21.0
* Platform: Windows 10 version 1709
* Firefox: 62.0
* Selenium: 3.14.0 java

## Testcase

Any link with target="_blank":

`<a href="/whatevs/" target="_blank">Label</a>`

## Stacktrace

I am running my tests through a grid setup (selenium server version is also 3.14.0) and I cannot set the _blank links to open in the same firefox browser window as a new tab, they always open in a new window. The options I am trying to modify are browser.link.open_newwindow and browser.link.open_newwindow.restriction as follows:

`
public FirefoxOptions getFirefoxOptions(){

        FirefoxOptions options = new FirefoxOptions();

        FirefoxProfile profile = new FirefoxProfile();

        profile.setAcceptUntrustedCertificates(true);

        profile.setPreference("network.proxy.type", 0);

        options.setCapability("browser.link.open_newwindow", 1); //same effect if value 3

        options.setCapability("browser.link.open_newwindow.restriction", 2); //same effect if value 0        

        options.setCapability(FirefoxDriver.PROFILE, profile);

        return options;
}
`
 
Config keys documentation at 
http://kb.mozillazine.org/Browser.link.open_newwindow 
http://kb.mozillazine.org/Browser.link.open_newwindow.restriction

In the nodeLog from grid I can see that the capabilities are passed to the remote webdriver:

`{
  "acceptInsecureCerts": true,
  "browser.link.open_newwindow": 1,
  "browser.link.open_newwindow.override.external": 3,
  "browser.link.open_newwindow.restriction": 2,
  "browserName": "firefox",
  "firefox_profile": ".....",
  "marionette": true,
  "moz:firefoxOptions": {
    "args": [
    ],
    "profile": "......."
  }`

**Comment by andreastt** [comment]
`target=_blank` is _supposed_ to open in a new window. Am I missing something?

**Comment by whimboo** [comment]
This is not a problem with geckodriver but with the preferences maybe not correctly specified. I would suggest that you search https://support.mozilla.com/products/firefox to find your solution.

**Comment by 0TT0mation** [comment]
@whimboo

**Comment by whimboo** [comment]
geckodriver is a proxy only, which forwards any custom preference to Marionette. Only the latter updates it internally in Firefox, which you could verify by adding a breakpoint in your test, and manually opening "about:config" in Firefox. All the preference values as specified in the test have to be set correctly. Note that we have tests which verify that!

As such this is a problem with specifying the correct preferences and values, or a bug / misbehavior in Firefox, but not in geckodriver.

**Comment by lisabrauns** [comment]
i have some problem

**Comment by lisabrauns** [comment]
I also have a problem, I can't set the value of browser.link.open_newwindow correctly.
