### ISSUE TITLE
switchWindow not working on Firefox v57 + geckodriver v1.19.1

### ISSUE THREAD

**Issue by ravi005e** [mozilla/geckodriver#1371]
System Configuration
nightwatch v0.9.17
geckodriver v1.19.1
selenium-server-standalone-3.7.1
Node.js v7.6.0
Firefox v57.0.1 (Quantum)
MacOS Sierra v10.12.6

switchWindow doesn't seem to work in Firefox 57. Although no errors are thrown/logged, the browser never switches focus to the passed window.

Steps to reproduce
Open www.google.com,
Write something in the search box
Open a new tab at www.google.com
Focus to new tab, using switchWindow.
Write something in search box
Expected behaviour
'hello world - tab 1' is written in search box of Tab 1 (original tab)
'hello world - tab 2' is written in search box of Tab 2 (newly opened tab)
Actual behaviour
'hello world - tab 1 - hello world - tab 2'' is written in search box of Tab 1 (original tab)
Nothing is written in search box of Tab 2
The browser never focuses to Tab 2, even after adding an extended pause() to make sure the tab has opened and loaded.

MCVE
'use strict'

module.exports = {
  'Firefox not focusing window test case' : function (browser) {
    browser
      // Tab 1, write something in search box
      .url('https://www.google.com')
      .waitForElementVisible('body', 5000)
      .setValue('#lst-ib', 'hello world - tab 1')

      // Tab 2, write something in search box
      .execute(function () {
        window.open('https://www.google.com')
      }, [])
      .pause(2000)
      .window_handles(function(result) {
        this.switchWindow(result.value[1])
      })
      .waitForElementVisible('body', 5000)
      .setValue('#lst-ib', 'hello world - tab 2')

      .pause(20000)
      .end()
  }
}
Logs
Running the above MCVE with --verbose shows a POST 500 Error when attempting to switchWindow

INFO Request: POST /wd/hub/session/7c3873ed-1dae-3143-9124-f104f8e6ee19/window 
 - data:  {"name":{"handle":"2147483653"}} 
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":32}
ERROR Response 500 POST /wd/hub/session/7c3873ed-1dae-3143-9124-f104f8e6ee19/window (5071ms) { state: 'invalid argument',
  sessionId: null,
  hCode: 1180860869,
  value: 
   { additionalInformation: '\nDriver info: driver.version: unknown',
     localizedMessage: 'Missing \'handle\' parameter\nBuild info: version: \'3.7.1\', revision: \'8a0099a\', time: \'2017-11-06T21:07:36.161Z\'\nSystem info: host: \'Nicholass-iMac.local\', ip: \'192.168.0.10\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.12.6\', java.version: \'1.8.0_60\'\nDriver info: driver.version: unknown',
     systemInformation: 'System info: host: \'Nicholass-iMac.local\', ip: \'192.168.0.10\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.12.6\', java.version: \'1.8.0_60\'',
     supportUrl: null,
     cause: null,
     suppressed: [],
     message: 'Missing \'handle\' parameter\nBuild info: version: \'3.7.1\', revision: \'8a0099a\', time: \'2017-11-06T21:07:36.161Z\'\nSystem info: host: \'Nicholass-iMac.local\', ip: \'192.168.0.10\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.12.6\', java.version: \'1.8.0_60\'\nDriver info: driver.version: unknown',
     hCode: 722310431,
     class: 'org.openqa.selenium.InvalidArgumentException',
     buildInformation: null },
  class: 'org.openqa.selenium.remote.Response',
  status: 61 }
LOG     → Completed command window (5095 ms)

**Comment by beatfactor** [comment]
@ravi005e This is a Nightwatch.js issues. Please see https://github.com/nightwatchjs/nightwatch/issues/1663#issuecomment-420921482

**Comment by ravi005e** [comment]
thanks
