### ISSUE TITLE
Error: Channel closing: too late to send/recv, messages will be lost

### ISSUE THREAD

**Issue by damaid** [mozilla/geckodriver#1376]
## System

* Version: 0.22.0
* Platform: Windows 7 64bit
* Firefox: Nighty 64
[trace.log](https://github.com/mozilla/geckodriver/files/2391632/trace.log)
.0a 64bit
* Selenium: 3.14.0

## Testcase

import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TDC1 {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
	System.setProperty("webdriver.gecko.driver", "src\\resources\\geckodriver22.exe");
	DesiredCapabilities cap=new DesiredCapabilities();
	cap.setCapability("firefox_binary","C:\\......\\firefox.exe");
	FirefoxOptions options = new FirefoxOptions(cap);
    driver = new FirefoxDriver(options);
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void test() throws Exception {
	  driver.get("http://www.google.fr");
	  driver.get("http://www.google.fr/search?q=cake");
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}

## Stacktrace
[trace.log](https://github.com/mozilla/geckodriver/files/2391464/trace.log)

**Comment by whimboo** [comment]
Most likely there was a crash of Firefox but you are also using a very outdated version of Firefox Nightly. Please update it to the most recent one and test again. Also please add a new trace log as attachment to this issue. Thanks.

**Comment by damaid** [comment]
Thanks for your quick reply.
I updated nightly to 64.0a and produced a new trace log.
There is no more error of send/rcvd but there is still these warnings 
 WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

[trace.log](https://github.com/mozilla/geckodriver/files/2391635/trace.log)

**Comment by whimboo** [comment]
This is output from Firefox you don't have to worry about unless it is causing your test to fail. And I don't see indication for that.

As you said you cannot see the original issue anymore I'm going to close this report.
