### ISSUE TITLE
addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error

### ISSUE THREAD

**Issue by Avahdam** [mozilla/geckodriver#1387]
While running the test i am getting the message as "addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error" and waiting for more than hour and resuming the flow which causes the failure due to time elapsed.

Let me know how to disable this addons downloading in firefox settings based on below java code provided.

## System

* Version: 
* Platform: Ubuntu
* Firefox: Firefox 56

## Testcase
FirefoxBinary firefoxBinary = new FirefoxBinary();
		    firefoxBinary.addCommandLineOptions("--headless");
		    System.setProperty("webdriver.gecko.driver", "/usr/bin/geckodriver");
		    FirefoxOptions firefoxOptions = new FirefoxOptions();
		    firefoxOptions.setBinary(firefoxBinary);
		    driver = new FirefoxDriver(firefoxOptions);

## Stacktrace

Sep 27, 2018 5:08:59 PM org.openqa.selenium.firefox.FirefoxOptions toCapabilities
INFO: Preferring the firefox binary in these options (/usr/lib/firefox/firefox rather than /usr/lib/firefox/firefox)
Sep 27, 2018 5:08:59 PM org.openqa.selenium.firefox.FirefoxOptions toCapabilities
INFO: Preferring the firefox binary in these options (/usr/lib/firefox/firefox rather than /usr/lib/firefox/firefox)
1538048339875	geckodriver	INFO	geckodriver 0.19.1
1538048339904	geckodriver	INFO	Listening on 127.0.0.1:6266
1538048341075	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "-marionette" "--headless" "-profile" "/tmp/rust_mozprofile.CfoRmaXG1Css"
*** You are running in headless mode.
1538048342920	Marionette	INFO	Enabled via --marionette
1538048346874	Marionette	INFO	Listening on port 46448
Sep 27, 2018 5:09:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Running devops.capstone.ChangePasswordUnitTest
1538048370065	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error

**Comment by andreastt** [comment]
Thanks for the issue.

This warning is nothing to worry about. It is propagated from the Firefox stdout and should not affect geckodriver behaviour or performance.

**Comment by Avahdam** [comment]
Thanks for your response. 
But this stops the test to proceed and hold for long time. Is there any fix to avoid/suppress this issue or warning.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Also please upgrade geckodriver to its newest release. You are using the very outdated and no longer supported release 0.19.1.

**Comment by pgolukonda** [comment]
Hi Whimboo,

  Even I am facing similar issue, the test case gets stuck if its not able to find a element and takes a long time to time out or go to the exception block and it keeps generating this error.

Any help would be higly appreciated.

Reg,
Praveen

**Comment by whimboo** [comment]
We cannot help unless a trace log has been provided. See https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html how to generate one.
