### ISSUE TITLE
Driver not interacting with Page after accepting a popup or Alert.

### ISSUE THREAD

**Issue by hariharanravichandran** [mozilla/geckodriver#1388]
## System

* Version: 0.22.0
* Platform: Win7
* Firefox: 60.0.1
* Selenium: 3.12

## Testcase
on clicking go button, A popup will appear. Once, we accept the popup, next page. Driver is not able to find the element in the page which is present in the page.

[FirstDemo.zip](https://github.com/mozilla/geckodriver/files/2428091/FirstDemo.zip)
the attachment is the Web App model.

Test Script is as follows:

FirefoxDriverManager.getInstance().setup();
WebDriver driver = new FirefoxDriver();
driver.manage().window().maximize();
driver.get("http://localhost:8080/FirstDemo/HomePage.jsp");
Thread.sleep(5000);
driver.findElement(By.xpath("//input[@type='submit']")).click();
Thread.sleep(5000);
		if (isAlertPresent()) {
			driver.switchTo().alert().accept();
		}
String text = driver.findElement(By.xpath("//div[contains(text(),'User Status :')]")).getText();
		System.out.println(text);

Error Logs:
org.openqa.selenium.NoSuchElementException: Unable to locate element: //div[contains(text(),'User Status :')]
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Trace Logs: 
[TraceLogs.txt](https://github.com/mozilla/geckodriver/files/2433338/TraceLogs.txt)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by hariharanravichandran** [comment]
@whimboo Please find the Trace Level logs below,
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
1538383799326	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\449504\\AppData\\Local\\Temp\\rust_mozprofile.5m3ywFbn6Wbi"
1538383799495	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:65445
1538383806290	Marionette	DEBUG	Received observer notification profile-after-change
1538383807369	Marionette	DEBUG	Received observer notification command-line-startup
1538383807369	Marionette	DEBUG	Received observer notification nsPref:changed
1538383815626	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1538383816342	Marionette	DEBUG	Received observer notification domwindowclosed
1538383816407	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1538383816407	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1538383816407	Marionette	DEBUG	Setting recommended pref browser.EULA.override to true
1538383816408	Marionette	DEBUG	Setting recommended pref browser.offline to false
1538383816408	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1538383816408	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1538383816408	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1538383816408	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1538383816408	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1538383816409	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1538383816409	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1538383816409	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1538383816409	Marionette	DEBUG	Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1538383816409	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1538383816409	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1538383816409	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1538383816409	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1538383816410	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1538383816410	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1538383816410	Marionette	DEBUG	Setting recommended pref extensions.shield-recipe-client.api_url to 
1538383816410	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1538383816410	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1538383816410	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1538383816410	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1538383816410	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1538383816410	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1538383816411	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1538383816447	Marionette	DEBUG	New connections are accepted
1538383816448	Marionette	INFO	Listening on port 65445
1538383816587	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:65445. Waiting for Marionette handshake
1538383816604	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:65493
1538383816604	geckodriver::marionette	DEBUG	Connected to Marionette
1538383816608	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1538383816609	Marionette	WARN	TLS certificate errors will be ignored for this session
1538383826899	Marionette	DEBUG	Register listener.js for window 4294967297
1538383826904	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"cdb42ebb-7663-461d-8288-29ea39f7294a","capabilities":{"browserName":"firefox","browserVersion":"60.0. ... AppData\\Local\\Temp\\rust_mozprofile.5m3ywFbn6Wbi","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1538383826908	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"cdb42ebb-7663-461d-8288-29ea39f7294a","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"60.0.1","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.22.0","moz:headless":false,"moz:processID":11892,"moz:profile":"C:\\Users\\449504\\AppData\\Local\\Temp\\rust_mozprofile.5m3ywFbn6Wbi","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Oct 01, 2018 2:20:26 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1538383826957	webdriver::server	DEBUG	-> POST /session/cdb42ebb-7663-461d-8288-29ea39f7294a/url {"url":"http://localhost:8080/FirstDemo/HomePage.jsp"}
1538383826957	Marionette	TRACE	0 -> [0,2,"WebDriver:Navigate",{"url":"http://localhost:8080/FirstDemo/HomePage.jsp"}]
1538383826978	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1538383826994	Marionette	DEBUG	Received DOM event pagehide for about:blank
1538383827000	Marionette	DEBUG	Received DOM event DOMContentLoaded for http://localhost:8080/FirstDemo/HomePage.jsp
1538383827048	Marionette	DEBUG	Received DOM event pageshow for http://localhost:8080/FirstDemo/HomePage.jsp
1538383827048	Marionette	TRACE	0 <- [1,2,null,{}]
1538383827049	webdriver::server	DEBUG	<- 200 OK {"value":null}
1538383832056	webdriver::server	DEBUG	-> POST /session/cdb42ebb-7663-461d-8288-29ea39f7294a/element {"value":"//input[@type='submit']","using":"xpath"}
1538383832056	Marionette	TRACE	0 -> [0,3,"WebDriver:FindElement",{"using":"xpath","value":"//input[@type='submit']"}]
1538383832059	Marionette	TRACE	0 <- [1,3,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"5364e61b-f704-4e78-9c19-29c59ac3a2f6","ELEMENT":"5364e61b-f704-4e78-9c19-29c59ac3a2f6"}}]
1538383832061	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"5364e61b-f704-4e78-9c19-29c59ac3a2f6"}}
1538383832065	webdriver::server	DEBUG	-> POST /session/cdb42ebb-7663-461d-8288-29ea39f7294a/element/5364e61b-f704-4e78-9c19-29c59ac3a2f6/click {"id":"5364e61b-f704-4e78-9c19-29c59ac3a2f6"}
1538383832065	Marionette	TRACE	0 -> [0,4,"WebDriver:ElementClick",{"id":"5364e61b-f704-4e78-9c19-29c59ac3a2f6"}]
1538383832096	Marionette	DEBUG	Received observer notification tabmodal-dialog-loaded
1538383832097	Marionette	TRACE	0 <- [1,4,null,{}]
1538383832102	webdriver::server	DEBUG	<- 200 OK {"value":null}
Alert not present
1538383837126	webdriver::server	DEBUG	-> POST /session/cdb42ebb-7663-461d-8288-29ea39f7294a/element {"value":"//div[contains(text(),'User Status :')]","using":"xpath"}
1538383837127	Marionette	TRACE	0 -> [0,5,"WebDriver:FindElement",{"using":"xpath","value":"//div[contains(text(),'User Status :')]"}]
1538383837128	Marionette	TRACE	0 <- [1,5,{"error":"unexpected alert open","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nU ... et@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1538383837132	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unexpected alert open","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nUnexpectedAlertOpenError@chrome://marionette/content/error.js:507:5\nassert.that/<@chrome://marionette/content/assert.js:405:13\nassert.noUserPrompt@chrome://marionette/content/assert.js:178:3\nGeckoDriver.prototype._assertAndDismissModal@chrome://marionette/content/driver.js:3203:5\nGeckoDriver.prototype.findElement@chrome://marionette/content/driver.js:2012:3\ndespatch@chrome://marionette/content/server.js:293:20\nexecute@chrome://marionette/content/server.js:267:11\nonPacket/<@chrome://marionette/content/server.js:242:15\nonPacket@chrome://marionette/content/server.js:241:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"}}

**Comment by whimboo** [comment]
The log doesn't show that the alert is getting accepted. There is no such command called for Marionette. What is `isAlertPresent()` actually doing? Which binding of Selenium are you using?

**Comment by whimboo** [comment]
No response from reporter. Closing the issue.
