### ISSUE TITLE
Node.js selenium-webdriver is failing with version 0.9.0

### ISSUE THREAD

**Issue by marco-c** [mozilla/geckodriver#139]
I'm seeing this error: `Uncaught Error: Server terminated early with status 2`.

It works if I use 0.8.0.

**Comment by gauntface** [comment]
Just started seeing this as well except I get: 'Server terminated early with status 126' :(

**Comment by andreastt** [comment]
Exit code 126 indicates the file isn’t executable. Try:

    % chmod +x geckodriver

What operating systems are you on?

**Comment by gauntface** [comment]
This is on ubuntu. Will add that in.

**Comment by andreastt** [comment]
This is odd.  The _geckodriver-v0.9.0-linux64.tar.gz_ contains a file that appears to be executable:

```
% ls -l geckodriver
-rwxr-xr-x 1 ato ato 3434846 Jun 30 17:23 geckodriver
```

**Comment by gauntface** [comment]
I'm seeing the same:

    $ ls -l wires                                                                                       
    -rwxr-xr-x 1 mattgaunt eng 3440640 Jul  7 08:55 wires

**Comment by andreastt** [comment]
What version of geckodriver is that? You can check by using the `--version` flag.

**Comment by gauntface** [comment]
Plot thickens, get exec format error:

    $ ./wires --version
    zsh: exec format error: ./wires

**Comment by andreastt** [comment]
I suspect you’re running a binary for a different CPU architecture. Can you run file(1) and ldd(1) on it?

**Comment by andreastt** [comment]
I get:

```
% file geckodriver
geckodriver: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=af87b186558c131b368112e459a16f300204ef18, not stripped
% ldd geckodriver
        not a dynamic executable
```

**Comment by gauntface** [comment]
Ignore my issue. The release has changed from .gz to .tar.gz which has messed up with my automation for using geckodriver. Apologies for highjacking issue and thanks for the help.

**Comment by andreastt** [comment]
Sorry for breaking your code (-:

Starting with 0.9.0 we are deploying from Travis using a script, so the file names should be more predictable. Because gunzip-compressed files can’t hold executable information, we using a tar archive now so that users will not have to `chmod +x geckodriver`.

**Comment by gauntface** [comment]
Just to note @marco-c's original issue should still be open

**Comment by andreastt** [comment]
Sorry about that.

@marco-c Can you provide more debug information on your issue? Some of the things I’ve asked about above would be good.

**Comment by marco-c** [comment]
It's working again now, not sure what was the problem.
