### ISSUE TITLE
add Perl API link to README

### ISSUE THREAD

**Issue by davewood** [mozilla/geckodriver#1394]
Is it possible to have the Perl API included in the README next to python, c, java, ...

there is an excellent module for selenium under Perl

https://metacpan.org/pod/Selenium::Remote::Driver

cheers

**Comment by andreastt** [comment]
Thanks for suggesting it!

https://bugzilla.mozilla.org/show_bug.cgi?id=1497882

**Comment by andreastt** [comment]
Fixed.
