### ISSUE TITLE
Not able to Open Firefox Browser using Selenium with C#

### ISSUE THREAD

**Issue by suseelagomathi** [mozilla/geckodriver#1398]
## System

* Version:   geckodriver-v0.21.0-win32
*Platform: Win 10
* Firefox:  FF 57.0 32 bit
* Selenium: Selenium 3.11

## Testcase
Used the below code to launch Firefox browser, it is not working. Can any one please help me how to open google in FF.
code snippet:
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService("C:\\ELE");
                    service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                    IWebDriver Wd = new FirefoxDriver(service);
                   Wd.Navigate().GoToUrl("https://www.google.com");
Thanks
Suseela

**Comment by suseelagomathi** [comment]
Thanks a Whimboo for your reply.

In C:\ELE Folder, I kept GeckoDriver.exe and used below code snippet to launch FF 57 browser, it is not working. Can you please provide code snippet to Open FF 57 browser using Selenium, C#.

code snippet using Selenium with C#
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService("C:\ELE");
service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
IWebDriver Wd = new FirefoxDriver(service);
Wd.Navigate().GoToUrl("https://www.google.com");

**Comment by whimboo** [comment]
As already said in my last comment `C:\ELE` is not a path to geckodriver. You have to provide the full path, and not only the folder. For further questions in how to setup your testing please consult the Selenium community.
