### ISSUE TITLE
Location strategies by ID and by name

### ISSUE THREAD

**Issue by aplicacionamedida** [mozilla/geckodriver#140]
These locator strategies are not present in the specification of the new webdriver protocol:
https://w3c.github.io/webdriver/webdriver-spec.html#dfn-json-serialisation-of-an-element

But all the other drivers (including the driver of firefox for versions before 47) support them. They were present in the old specification:
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelement

I think that it's a good idea to support them (at least during some time), to don't break code of other users

**Comment by andreastt** [comment]
Marionette already supports the ID and name location strategies, but we should probably remove them to be conformant with the specification.

If I remember correctly, the idea is that name and ID can easily be replicated using the CSS selector.

**Comment by aplicacionamedida** [comment]
I tried to use these locator strategies. But geckodriver doesn't recognize them. Yes, these locator strategies can be replicated but maybe for perfomance reason, shouldn't be eliminated, because they can use document.getElementById and document.getElementsByName internally. Maybe these functions offer a better performance than document.querySelector or document.querySelectorAll.

**Comment by andreastt** [comment]
Please open a bug with the specification.
