### ISSUE TITLE
Geckodriver has no updated version in his descriptions

### ISSUE THREAD

**Issue by desezde** [mozilla/geckodriver#1400]
## System

* Version: 23
* Platform: Linux
* Firefox: N/A
* Selenium:  N/A

## Testcase

$ tar -xzf geckodriver-### **v0.23.0**-linux64.tar.gz 
$ geckodriver -V
geckodriver ### **0.16.1**

**Comment by andreastt** [comment]
I can’t reproduce this:

```
% tar xf geckodriver-v0.23.0-linux64.tar.gz geckodriver 
% ./geckodriver --version
geckodriver 0.23.0 ( 2018-10-04)

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

Are you sure you fetched the right package?

**Comment by desezde** [comment]
The problem was that I have in the $PATH geckodriver 16. When I use absolute path, the version is correct
$ ./geckodriver -V
geckodriver 0.23.0 ( 2018-10-04)

**Comment by andreastt** [comment]
Perfect 👍🏻
