### ISSUE TITLE
Click on 1-pixel element silently fails

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#1402]
## System

* Version: 0.23.0
* Platform: Windows 10 Version 1809 (Redstone 5) 10.0.17763.1
* Firefox: 62.0.3 (64-bit)
* Selenium: 3.13.0

## Testcase

The test clicks on an element which has a width and height of 1 pixel.
The `click()` call does not throw an exception but the click events are not triggered.
Therefore the following tests assert fails.

```java
@Test
public void testClickOnOnePixelElement() {
  driver.navigate().to("https://philipl-micro-focus.github.io/webdriver-testpages/OnePixelElement.html");
  WebElement onePixelElem = driver.findElementById("onePixel");
  WebElement clickCountElem = driver.findElementById("click-count");

  onePixelElem.click();

  assertEquals("1", clickCountElem.getText()); // FAILS in Firefox
}
```

## Stacktrace

```java
org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at OnePixelClickTests.testClickOnOnePixelElement(OnePixelClickTests.java:42)
```

## Trace-level log

[geckodriver-trace.log](https://github.com/mozilla/geckodriver/files/2483124/geckodriver-trace.log)

**Comment by andreastt** [comment]
That is the most evil manual test case I’ve encountered. 😈 But yes, it sounds like it could not only be a problem with Marionette, but also in the specification’s in-view centre point definition.

**Comment by andreastt** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1499360.

**Comment by whimboo** [comment]
Does it work when you turn off `moz:webdriverClick`?

**Comment by codingphil** [comment]
I added `caps.setCapability("moz:webdriverClick", false);` but the behavior was the same.

**Comment by andreastt** [comment]
That is definitely related. I’m managing to reproduce this and have posted some observations over in https://bugzilla.mozilla.org/show_bug.cgi?id=1499360.

**Comment by andreastt** [comment]
Specification change has landed:
https://github.com/w3c/webdriver/pull/1319

**Comment by andreastt** [comment]
Fixed:
https://hg.mozilla.org/mozilla-central/rev/ae99f2ef9464
https://hg.mozilla.org/mozilla-central/rev/d51f52d435da
https://hg.mozilla.org/mozilla-central/rev/6afa28099f1e
