### ISSUE TITLE
Message is empty for "no such alert" error in Firefox 63

### ISSUE THREAD

**Issue by p0deje** [mozilla/geckodriver#1404]
Since Firefox 63, when Selenium gets a response with "no such alert" error, "message" field in response is an empty string. Before Firefox 63, it contained some human-readable text like "No modal dialog is currently open".

### Response in Firefox 62.0.3

```json
{
    "value": {
        "error": "no such alert",
        "message": "No modal dialog is currently open",
        "stacktrace": "WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:377:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3216:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3180:3\ndespatch@chrome://marionette/content/server.js:297:20\nexecute@chrome://marionette/content/server.js:271:11\nonPacket/<@chrome://marionette/content/server.js:246:15\nonPacket@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"
    }
}
```

### Response in Firefox 63

```json
{
    "value": {
        "error": "no such alert",
        "message": "",
        "stacktrace": "WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:377:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3218:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3180:3\ndespatch@chrome://marionette/content/server.js:298:20\nexecute@chrome://marionette/content/server.js:271:11\nonPacket/<@chrome://marionette/content/server.js:246:15\nonPacket@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"
    }
}
```

## System

* Version: 0.23.0
* Platform: macOS 10.14
* Firefox: 63.0 (64-bit)
* Selenium: 3.14.1

## Testcase

```ruby
require 'selenium-webdriver'

Selenium::WebDriver.logger.level = :debug

begin
  options = Selenium::WebDriver::Firefox::Options.new(log_level: 'TRACE')
  driver = Selenium::WebDriver.for(:firefox, options: options)
  driver.switch_to.alert
ensure
  driver.quit
end
```

## Stacktrace

```
Selenium::WebDriver::Error::NoSuchAlertError:
  # WebDriverError@chrome://marionette/content/error.js:178:5
  # NoSuchAlertError@chrome://marionette/content/error.js:377:5
  # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3218:11
  # GeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3180:3
  # despatch@chrome://marionette/content/server.js:298:20
  # execute@chrome://marionette/content/server.js:271:11
  # onPacket/<@chrome://marionette/content/server.js:246:15
  # onPacket@chrome://marionette/content/server.js:245:8
  # _onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9
```

## Trace-level log

The relevant portion of log:

```
1540345597384	webdriver::server	DEBUG	-> GET /session/e0022963-3c06-5245-b789-0f5d093fe337/alert/text
1540345597387	Marionette	TRACE	0 -> [0,2,"WebDriver:GetAlertText",{}]
1540345597387	Marionette	TRACE	0 <- [1,2,{"error":"no such alert","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAle ... et@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
1540345597388	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"no such alert","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nNoSuchAlertError@chrome://marionette/content/error.js:377:5\nGeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3218:11\nGeckoDriver.prototype.getTextFromDialog@chrome://marionette/content/driver.js:3180:3\ndespatch@chrome://marionette/content/server.js:298:20\nexecute@chrome://marionette/content/server.js:271:11\nonPacket/<@chrome://marionette/content/server.js:246:15\nonPacket@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"}}
```

**Comment by whimboo** [comment]
This was removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1264259 because it actually didn't provide any meaningful value, and the reason what happened is already presented by the exception type. 

If a message has to be reintroduced we should find a better content which we want to provide through the message property. @andreastt what do you think?

**Comment by andreastt** [comment]
Not against providing a better message, but it would have to be substantial in some way. A no such alert error type with a message saying “there is no alert” is indeed meaningless.

**Comment by andreastt** [comment]
Any good ideas?

**Comment by p0deje** [comment]
I don't really have such a good idea. ChromeDriver returns "no alert open", IEDriver - "No alert is active". To some extent both duplicate error code of the response.

I'm actually fine with dropping the message altogether if that's what you want to do.

**Comment by andreastt** [comment]
The different error scenarios can be seen here: https://searchfox.org/mozilla-central/rev/e0c879c86b95bdc752b1dbff6088169735674e4a/testing/marionette/driver.js#3232-3254

We return this error on "accept and notify", "dismiss and notify", and "ignore". In the first two cases the user has consciously decided on a particular behaviour, so this seems like it might be worth notifying the user of.

Perhaps:

<table>
<tr>
<th>accept and notify
<td>"Accepted user prompt dialog: [text from dialog]"
</tr>

<tr>
<th>dismiss and notify
<td>"Dismissed user prompt dialog: [text from dialog]"
</tr>

<tr>
<th>ignore
<td>"Encountered unhandled user prompt dialog, pausing the session: [text from dialog]"
</tr>
</table>

WDYT?

**Comment by whimboo** [comment]
The messages for accept and dismiss are fine, but please leave out the text from the dialog, because that is handled by the [data](https://w3c.github.io/webdriver/#dfn-handle-any-user-prompts) property, which we haven't implemented yet. See [bug 1469752](https://bugzilla.mozilla.org/show_bug.cgi?id=1469752).

Regarding ignore, I'm not sure if `pausing the session` is the right wording. We only ignored the alert and returned from the command.

**Comment by andreastt** [comment]
So there’s no reason we couldn’t include the dialogue text in the message as well: it’s entirely implementation defined. We should have a `data` field so you don’t need to parse the message though.

**Comment by p0deje** [comment]
> So there’s no reason we couldn’t include the dialogue text in the message as well: it’s entirely implementation defined. We should have a data field so you don’t need to parse the message though.

You probably mean "unhandled alert" error while I meant "no such alert". It latter case, there is no alert on the page while we try to get one, so we can't return alert text or anything meaningful, right?

**Comment by p0deje** [comment]
Then I'm going to close this issue. The error type is probably all we need.

Thank you for investigating!
