### ISSUE TITLE
Latest Firefox update 63.0 broken session

### ISSUE THREAD

**Issue by andrewscul** [mozilla/geckodriver#1406]
## System

* Version: 0.23.0 ( 2018-10-04)
* Platform: macOS
* Firefox: 63.0 October 23, 2018

* Selenium: 3.14.1 

## Testcase

self.browser = webdriver.Firefox()

## Stacktrace

Error
Traceback (most recent call last):
  File "/functional_tests/base.py", line 23, in setUp
    self.browser = webdriver.Firefox()
  File "/venv-python3.6/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/venv-python3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/venv-python3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/venv-python3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/venv-python3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: newSession

**Comment by Michotastico** [comment]
It happens also in Debian based distros. I had to downgrade to the 62.0.3 to make it works.

**Comment by ibouchakour** [comment]
the same problem

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by andyshinn** [comment]
I guess Ubuntu 18.04 unattended upgrades will install Firefox 63 over 62 :(

Log at https://gist.github.com/andyshinn/1d61912e68762e957a98f8e76d9833d8

**Comment by RafalSkorka** [comment]
I am having the same issue under Windows 10 running Nightwatch. Here is the selenium-debug.log output (with trace-level enabled):

```
08:41:20.118 INFO - Selenium build info: version: '3.7.1', revision: '8a0099a'
08:41:20.118 INFO - Launching a standalone Selenium Server
2018-10-26 08:41:20.133:INFO::main: Logging initialized @211ms to org.seleniumhq.jetty9.util.log.StdErrLog
08:41:20.182 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:41:20.215 INFO - Driver provider class org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities {browserName: safari, platform: MAC, version: } does not match the current platform WIN10
08:41:20.248 INFO - Using the passthrough mode handler
2018-10-26 08:41:20.271:INFO:osjs.Server:main: jetty-9.4.5.v20170502
2018-10-26 08:41:20.297:WARN:osjs.SecurityHandler:main: ServletContext@o.s.j.s.ServletContextHandler@a1a8d5{/,null,STARTING} has uncovered http methods for path: /
2018-10-26 08:41:20.300:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@a1a8d5{/,null,AVAILABLE}
2018-10-26 08:41:20.485:INFO:osjs.AbstractConnector:main: Started ServerConnector@121c9d6{HTTP/1.1,[http/1.1]}{0.0.0.0:5557}
2018-10-26 08:41:20.486:INFO:osjs.Server:main: Started @564ms
08:41:20.486 INFO - Selenium Server is up and running
2018-10-26 08:41:21.365:INFO:osjshC.ROOT:qtp25376898-9: org.openqa.selenium.remote.server.WebDriverServlet-1c6f14e: Initialising WebDriverServlet
08:41:21.410 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@1f7658e
08:41:21.413 INFO - /session: Executing POST on /session (handler: BeginSession)
08:41:21.461 INFO - Capabilities are: Capabilities {acceptSslCerts: true, browserName: firefox, javascriptEnabled: true, loggingPrefs: org.openqa.selenium.logging..., moz:firefoxOptions: {args: [-headless], log: {level: trace}, prefs: {media.navigator.permission.disabled: true, media.navigator.streams.fake: true}}, name: TEST1}
08:41:21.462 INFO - Capabilities {acceptSslCerts: true, browserName: firefox, javascriptEnabled: true, loggingPrefs: org.openqa.selenium.logging..., moz:firefoxOptions: {args: [-headless], log: {level: trace}, prefs: {media.navigator.permission.disabled: true, media.navigator.streams.fake: true}}, name: TEST1} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1540536081518	geckodriver	INFO	geckodriver 0.19.1
1540536081524	geckodriver	INFO	Listening on 127.0.0.1:9724
1540536082445	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-headless" "-profile" "C:\\Users\\USER1\\AppData\\Local\\Temp\\rust_mozprofile.HequXMySpTZD"
*** You are running in headless mode.
1540536082817	Marionette	DEBUG	Received observer notification profile-after-change
1540536082860	Marionette	DEBUG	Received observer notification toplevel-window-ready
1540536082878	Marionette	DEBUG	Received observer notification command-line-startup
1540536082878	Marionette	DEBUG	Received observer notification nsPref:changed
1540536082879	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1540536082984	Marionette	DEBUG	Received observer notification toplevel-window-ready
1540536083538	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1540536083538	Marionette	DEBUG	Waiting for delayed startup...
1540536083598	Marionette	DEBUG	Setting recommended pref app.update.disabledForTesting to true
1540536083598	Marionette	DEBUG	Setting recommended pref security.turn_off_all_security_so_that_viruses_can_take_over_this_computer to true
1540536083599	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1540536083599	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1540536083599	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1540536083630	Marionette	INFO	Listening on port 59630
1540536083630	Marionette	DEBUG	Remote service is active
1540536083956	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:59630
1540536083958	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:59640
1540536083958	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1540536083958	geckodriver::marionette	TRACE	-> 109:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]
1540536083960	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]
1540536083960	Marionette	TRACE	0 <- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178: ... et@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
1540536083960	geckodriver::marionette	TRACE	<- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nUnknownCommandError@chrome://marionette/content/error.js:472:5\ndespatch@chrome://marionette/content/server.js:290:13\nexecute@chrome://marionette/content/server.js:271:11\nonPacket/<@chrome://marionette/content/server.js:246:15\nonPacket@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"},null]
1540536083960	webdriver::server	DEBUG	Deleting session
1540536083960	geckodriver::marionette	DEBUG	Stopping browser process
1540536084009	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown error","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nUnknownCommandError@chrome://marionette/content/error.js:472:5\ndespatch@chrome://marionette/content/server.js:290:13\nexecute@chrome://marionette/content/server.js:271:11\nonPacket/<@chrome://marionette/content/server.js:246:15\nonPacket@chrome://marionette/content/server.js:245:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"}}
08:41:24.023 INFO - HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)

```

**Comment by andreastt** [comment]
@RafalSkorka If it works after upgrading to the latest geckodriver, does that mean it’s not an issue any more? It also looks like your stacktrace is not the same as the original issue reported by @andrewscul, indeed it looks like you’re using a completely different client. If the issue persists, please file a separate issue.

**Comment by RafalSkorka** [comment]
@andreastt I confirm this is no longer an issue for me after upgrading to 0.21.0 (the latest version provided by [npm package geckodriver](https://www.npmjs.com/package/geckodriver)).
However root cause seems to be the same as in @andrewscul report:
old version sent:
`[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]`
and it fails with FF63, while the the new one sends:
`[0,1,"WebDriver:NewSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]`
and it succeeds.

**Comment by ibouchakour** [comment]
how to update geckodriver in ubuntu ?

**Comment by whimboo** [comment]
> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":

Then you had a version of geckodriver before 0.21.0, and by the supported platform table this is not supported with Firefox versions above 62.0: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html

@ibouchakour we don't provide any package for Ubuntu. So just download the tar.gz file from the releases page.

**Comment by surya-btps** [comment]
The issue arose after the latest update to Ubuntu 18.0 LTS which updated Firefox to 63.0. Fixed it by installing  geckodriver V 0.23 (I was using V geckodriver 0.17).

**Comment by ibouchakour** [comment]
> The issue arose after the latest update to Ubuntu 18.0 LTS which updated Firefox to 63.0. Fixed it by installing geckodriver V 0.23 (I was using geckodriver V 0.17).

How did you do ?

**Comment by whimboo** [comment]
All, please check https://github.com/mozilla/geckodriver/releases for downloads of geckodriver if your platform doesn't offer any kind of distribution.

I think we can call this issue as done.

**Comment by RiseInRose** [comment]
same too,
