### ISSUE TITLE
Failed to set implicitly_wait for Firefox 63.0 with geckodriver 0.23.0 win64

### ISSUE THREAD

**Issue by ftakanashi** [mozilla/geckodriver#1409]
Hello, my code is based on Selenium 3.7.0 with Python API. 
I meet error when set the implicitly_wait attribute for webdriver instance after I updating geckodriver to 0.23.0. And when I turn back geckodriver to 0.21.0, the problem does not exist.

## System

* Version:   0.23.0
* Platform:  Win7 x64
* Firefox: 63.0 64bit
* Selenium:  3.7.0 (Python API)

## Testcase
```python
        self.implicitly_wait(1)
```

## Stacktrace

  File "D:/PythonProjects/GuaHao/main.py", line 59, in __init__
    self.implicitly_wait(1)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 790, in implicitly_wait
    'implicit': int(float(time_to_wait) * 1000)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown field `sessionId`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 12

## Trace-level log

1540798412326	mozrunner::runner	INFO	Running command: "D:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\WEIYZ1~1\\AppData\\Local\\Temp\\rust_mozprofile.Etm4tEa7WxSW"
1540798415384	Marionette	INFO	Listening on port 52418
1540798415656	Marionette	WARN	TLS certificate errors will be ignored for this session
[Parent 7128, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 1392, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 1392, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 7128, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 7196, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 7128, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6184, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6184, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1540798422493	Marionette	INFO	Stopped listening on port 52418

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

[GPU 6596, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

**Comment by whimboo** [comment]
Please see https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html for supported platforms. Selenium 3.7.0 is no longer supported.

**Comment by ftakanashi** [comment]
Thx. I didn't think of the problem of the version of selenium!
