### ISSUE TITLE
Firefox Web Driver right click action is not working

### ISSUE THREAD

**Issue by maninwindow** [mozilla/geckodriver#141]
`RemoteWebDriver WebDriver;`
` Actions actions = new Actions(WebDriver);`
`actions.ContextClick(searchItem).Perform();`

Right click action code is working well on Chrome and IE, but for Firefox getting exception below:

![firefoxexception](https://cloud.githubusercontent.com/assets/6553154/16555894/9a5a6d42-4209-11e6-8751-9171b6f3a784.PNG)

It seems method `Perform();` is not implemented.
Same problem even on the latest version of `geckodriver`.
Have anyone had similar issue?

**Comment by andreastt** [comment]
Marionette implements the [WebDriver conformant](http://w3c.github.io/webdriver/webdriver-spec.html) actions API, which is not fully specified yet. Selenium will have to write a shim to convert from their API to the WebDriver API for this to work.
