### ISSUE TITLE
Driver crashes on file download when setting Firefox to not show confirmation for text/csv mimetype

### ISSUE THREAD

**Issue by tsibiski** [mozilla/geckodriver#1412]
## System

* Version: v0.23.0
* Platform: Windows 10
* Firefox: 63.0 (64 bit)
* Selenium: Selenium.WebDriver.3.14.0, Selenium.WebDriver.Extensions.3.3.0, Selenium.Support.3.14.0

## Testcase

1) Add following code to logic before driver is launched. I have tried both together, and each of the two preferences below separately. I get the same result.
` 
profile.SetPreference("browser.helperApps.neverAsk.openFile", "text/csv");
profile.SetPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv");
`
2) Run a test that tries to download a CSV file. 
3) Note that when the driver would be executing a click on the link that downloads the CSV file, the driver crashes with an error "Message: OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:54339/." This is despite the driver actually having started, and the test running properly up until the click event.

**Note**, I have also tried 
`
profile.SetPreference("browser.helperApps.neverAsk.openFile", "text/csv,application/x-msexcel,application/excel,application/x-excel,application/vnd.ms-excel,image/png,image/jpeg,text/html,text/plain,application/msword,application/xml");
profile.SetPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv,application/x-msexcel,application/excel,application/x-excel,application/vnd.ms-excel,image/png,image/jpeg,text/html,text/plain,application/msword,application/xml");
`
## Stacktrace

There is literally no stack outside of the method BaseTestSetup(), which launches the driver, and then the error:
"Message: Initialization method TestAutomation.Tests.SchedulingPageTests.SetUp threw exception. OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:54339/."

As mentioned in the steps, the code in the test runs fine up until the click event for the anchor tag that will trigger the CSV download, but that click event never happens, and the driver crashes at that point.

**Note**: This error does not occur if the above SetPreference lines are commented out!

## Trace-level log

Output gist with the following code implemented in C#
`FirefoxOptions options = new FirefoxOptions();
options.setLogLevel(FirefoxDriverLogLevel.TRACE);
WebDriver driver = new FirefoxDriver(options);
`

https://gist.github.com/tsibiski/be61508d9987d95145ca2b193e7eb945

**Comment by andreastt** [comment]
Can you get at the actual stdout from Firefox? Your gist doesn’t appear to contain any actual Firefox output.

Generally speaking, if there’s a problem with preferences in Firefox, geckodriver is not the culprit. Downloading files to a directory is not really a use case we support in geckodriver, so I’m just saying upfront that this may be a Firefox issue meant for Bugzilla instead of geckodriver.

**Comment by tsibiski** [comment]
Well, it doesn't seem that the Firefox browser is encountering any problems. The driver simply disconnects from the socket it is listening on. 

"Downloading files to a directory is not really a use case we support in geckodriver"

I merely want to be able to not have an alert popup asking if I really want to download that file. I tried changing this in the Firefox browser settings, but it simply doesn't work, unfortunately.

If geckdriver can't override this, then I will have to ignore tests involving downloading files for Firefox only. The other browsers and/or drivers offer ways to stop the browser from requesting you confirm a file download.

The directions for getting the Firefox logs say that trace logs are put in sdout. If that doesn't mean the logs are posted in the IDE's output, then I have no idea where the geckdriver is storing the sdout logs. 

Thanks!

**Comment by whimboo** [comment]
The preferences you need are:

>  "browser.download.dir": %path%,
>  "browser.download.folderList": 2
>  "browser.helperApps.neverAsk.saveToDisk": "application/x-csv"

But note that there is still https://bugzilla.mozilla.org/show_bug.cgi?id=1366035 which means that there is a timeout when using `driver.get()`. You could reduce the page load timeout, and ignore the resulting timeout error. But this is still special treatment for Firefox.

**Comment by tsibiski** [comment]
Thanks for the reply. Although application/x-csv did not work.

This is what I finally settled on and got working:
`profile.SetPreference("browser.download.dir", "%path%");
profile.SetPreference("browser.download.folderList", 2);
profile.SetPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv");`

**Comment by whimboo** [comment]
The MIME type might be different depending on from where the file is served. So if `text/csv` works fine for you, that's great.
