### ISSUE TITLE
Not able to run Firefox with geckodriver and jenkins slave machine as windows service

### ISSUE THREAD

**Issue by idRomanUdka** [mozilla/geckodriver#1415]
## System

* Version: 0.23.0
* Platform: Windows 7
* Firefox: 62.0 (64-bit)
* Selenium: 3.13.0

Note:  it works fine on  a local machine

## Log
https://gist.github.com/idRomanUdka/fb4c5742cdb828aabe68e8cb5c44d2fd

**Comment by andreastt** [comment]
geckodriver cannot be run as a Windows service.

**Comment by idRomanUdka** [comment]
@andreastt I mean that  I can't run autotests on Firefox geckodriver on jenkins slave (OS - windows 7)

**Comment by whimboo** [comment]
@idRomanUdka there is a crash of Firefox. It would be great if you could try to get some more details as layed out on https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html. Thanks!

**Comment by kLightyear** [comment]
hi, we have a similar issue here, we utilize Jenkins to trigger jenkins slave to execute robotframework for web testing, thanks!
**environment info**
		geckodriver version: v0.23.0-win64
		Library Name: robotframework-selenium2library / Version: 3.0.0
		Library Name: robotframework / Version: 3.0.4
		Library Name: selenium / Version: 3.12.0
		Platform: Windows Server 2012 R2
		Firefox: 62.0.3 (64-bit)
**geckodriver.log** for reference
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2541700/geckodriver.log)

**Comment by kLightyear** [comment]
hi,i have a similar issue
we utilize Jenkins to trigger jenkins slave to execute robotframework for web testing
thanks!

**environment info**
		geckodriver version: v0.23.0-win64
		Library Name: robotframework-selenium2library / Version: 3.0.0
		Library Name: robotframework / Version: 3.0.4
		Library Name: selenium / Version: 3.12.0
		Platform: Windows Server 2012 R2
		Firefox: 62.0.3 (64-bit)

**geckodriver.log**
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2541700/geckodriver.log)

**Comment by whimboo** [comment]
@kLightyear why do you think this is similar? I can tell you it's not. Please file your own issue where it can be handled. Thanks.
