### ISSUE TITLE
 jenkins slave failed to execute robotframework web test cases 

### ISSUE THREAD

**Issue by kLightyear** [mozilla/geckodriver#1416]
## System

* Version: v0.23.0-win64
* Platform: Windows Server 2012 R2
* Firefox: 62.0.3 (64-bit)
* Selenium: 3.12.0

## Testcase

Utilize Jenkins to trigger jenkins slave to execute robotframework test cases for web testing

robotframework info:

- Library Name: robotframework-selenium2library / Version: 3.0.0
- Library Name: robotframework / Version: 3.0.4

Note: there is no issue when login to test machine and execute same test cases

## Stacktrace

WebDriverException: Message: connection refused

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2541928/geckodriver.log)

**Comment by andreastt** [comment]
From the log it might look like Firefox crashes when opening a tab, but it’s hard to tell what causes this since you haven’t attached a trace-level log.

Additionally you might want to look for a crash dump in the profile as this could contain more information.

**Comment by whimboo** [comment]
> From the log it might look like Firefox crashes when opening a tab, but it’s hard to tell what causes this since you haven’t attached a trace-level log.

This is a trace log but Marionette wasn't started because Firefox failed before its initialization.
 
> Additionally you might want to look for a crash dump in the profile as this could contain more information.

As long as geckodriver removes the profile when it quits (ends the session), any dump file will be created. So only https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html would help for now.

**Comment by kLightyear** [comment]
> 
> How are your Jenkins slaves configured? Are the tests running as normal user, or as service? As it looks like Firefox fails to create sub processes:

Jenkins Slave is registered as service, which is running by a local account with admin permission

> 
> Which value has the `dom.ipc.processCount` preference in your profile? When you lower the number of processes does it work?

There is no special setting for dom.ipc.processCount

> 
> Does that also happen outside of Jenkins when starting Firefox manually? If not please show some code in how you setup the driver including the profile, and how the tests are run.

The original code is below:

    def open_browser_firefox(self, lang_code):
        profile = webdriver.FirefoxProfile()
        profile.set_preference('intl.accept_languages', lang_code)
        profile.update_preferences()
        browser = webdriver.Firefox(profile)
        browser.get("http://google.com")
        time.sleep(10)
        browser.quit()
        return browser

**Comment by kLightyear** [comment]
> 
> As long as geckodriver removes the profile when it quits (ends the session), any dump file will be created. So only https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html would help for now.

Updated code for CrashReport, but as result, minidumps folder is empty, no files were generated in that folder:

    def open_browser_firefox(self, lang_code):
        profile = tempfile.mkdtemp(".selenium")
        print("*** Using profile: {}".format(profile))
        opts = webdriver.firefox.options.Options()
        opts.add_argument("-profile")
        opts.add_argument(profile)
        opts.binary = "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
        browser = webdriver.Firefox(options=opts, service_args=["--marionette-port", "2828"])
        browser.get("http://google.com")
        time.sleep(10)
        browser.quit()
        return browser

**geckodriver.log & prefs.js when login to test machine and execute test cases**:
[localadmin.zip](https://github.com/mozilla/geckodriver/files/2548296/localadmin.zip)

**geckodriver.log & prefs.js when Jenkins to trigger jenkins slave test cases execution**:
[remote.zip](https://github.com/mozilla/geckodriver/files/2548300/remote.zip)

**Comment by whimboo** [comment]
> > Which value has the `dom.ipc.processCount` preference in your profile? When you lower the number of processes does it work?
> 
> There is no special setting for dom.ipc.processCount

There has to be. It's a preference in Firefox, and is always set. Please check again. You can also find it when opening `about:config` and searching for it. Maybe lowering its value might help?

> Updated code for CrashReport, but as result, minidumps folder is empty, no files were generated in that folder:

Ok, then it might be something else. But hard to tell. Please note that we officially don't support the use case of running Firefox via a service. But it would be good to get those cases fixed.

Something else which comes into my mind are sandboxes. Please check the Firefox preference `security.sandbox.content.level`, and maybe specify a lower number as the default one.

**Comment by kLightyear** [comment]
Many thanks for the help!
> 
> There has to be. It's a preference in Firefox, and is always set. Please check again. You can also find it when opening `about:config` and searching for it. Maybe lowering its value might help?
> Ok, then it might be something else. But hard to tell. Please note that we officially don't support the use case of running Firefox via a service. But it would be good to get those cases fixed.


> 
> Something else which comes into my mind are sandboxes. Please check the Firefox preference `security.sandbox.content.level`, and maybe specify a lower number as the default one.

still having same issue **WebDriverException: Message: connection refused**
with same **Failed to launch tab subprocess** warining ([geckodriver.log](https://github.com/mozilla/geckodriver/files/2560308/geckodriver.log))

following scenarios tested:
- security.sandbox.content.level = 1 &  dom.ipc.processCount = 1 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560337/prefs_sandbox_level_1_dom.ipc.processCount_1.js.txt))
- security.sandbox.content.level = 1 &  dom.ipc.processCount = 2 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560343/prefs_sandbox_level_1_dom.ipc.processCount_2.js.txt))
- security.sandbox.content.level = 2 &  dom.ipc.processCount = 1 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560345/prefs_sandbox_level_2_dom.ipc.processCount_1.js.txt))
- security.sandbox.content.level = 2 &  dom.ipc.processCount = 2 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560346/prefs_sandbox_level_2_dom.ipc.processCount_2.js.txt))
- security.sandbox.content.level = 3 &  dom.ipc.processCount = 1 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560351/prefs_sandbox_level_3_dom.ipc.processCount_1.js.txt))
- security.sandbox.content.level = 4 &  dom.ipc.processCount = 1 ([prefs.js](https://github.com/mozilla/geckodriver/files/2560370/prefs_sandbox_level_4_dom.ipc.processCount_1.js.txt))

**Comment by whimboo** [comment]
Ok, so I have no further idea for now. If you want to see it tracked maybe file a bug against Firefox at https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=IPC. If you do so, please reference the bug number here. Thanks!

Given that this is a Firefox problem, I will close this issue.

**Comment by whimboo** [comment]
Thanks! Lets continue with that investigation on that bug.

**Comment by whimboo** [comment]
@kLightyear your Bugzilla account has been disabled, and as such you might not have seen the recent updates on the above bug. Can you please check? Thanks.
