### ISSUE TITLE
Crash_firefox_52.9.0 (32-bit)

### ISSUE THREAD

**Issue by flagellantX** [mozilla/geckodriver#1418]
## System

* Version: firefox_52.9.0 (32-bit)
* Platform: Lniux
[https://github.com/flagellantX/firefox_52.9.0-32-bit-_Crash_PoC/raw/master/Crash_firefox_52.9.0%20(32-bit).7z](url)

**Comment by andreastt** [comment]
Sorry, this is not the appropriate forum for reporting crashes in Firefox. Especially not those in such an ancient version as 52.
