### ISSUE TITLE
feature request add -v / --version command line flag

### ISSUE THREAD

**Issue by lukeis** [mozilla/geckodriver#142]
please consider adding this flag, which would cause the version of the geckodriver to print out and then quit

**Comment by lukeis** [comment]
ha, it's there in 0.9, thanks! although the -v is mapped to verbose, so that's a bit confusing

**Comment by andreastt** [comment]
If you consider other Unix literature, `-v` as meaning “verbose” is fairly common practice. In fact, `-V` is more commonly aliased to `--version`.
