### ISSUE TITLE
webdriverio: timeouts('implicit', 5000) returns "Error: Remote end send an unknown status code"

### ISSUE THREAD

**Issue by sanjeethgwd** [mozilla/geckodriver#1420]
## System

* Version: 0.23.0
* Platform: Windows
* Firefox: 63.0.1
* Selenium: 3.9.0 <standalone server>
* nodeJS: v8.9.4
* webdriverio: 4.12.0

## Testcase

On webdriverIO, for the statement `browser.timeouts('implicit', 5000);` the response is "Error: Remote end send an unknown status code"
http://webdriver.io/guide/testrunner/timeouts.html
same goes to `browser.timeouts('script', 60000);`, `browser.timeouts('pageLoad', 10000);`

## Stacktrace

[firefox #0-0] unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at line 1 column 5
Build info: version: '3.9.0', revision: '698b3178f0', time: '2018-02-05T14:56:13.134Z'
System info: host: 'XXXX', ip: 'XX.XX.XX.XX', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[firefox #0-0] Error: Remote end send an unknown status code.
[firefox #0-0]     at timeouts("implicit", 5000) -     at D:\XXX\node_modules\wdio-sync\build\index.js:316:3
[firefox #0-0]
error Command failed with exit code 1.

**Comment by andreastt** [comment]
It’s hard to tell without an overview of the wire calls made by webdriverio (a trace-level log from geckodriver), but this is likely a problem in webdriverio and not geckodriver.

**Comment by whimboo** [comment]
The problem is that you are using the webdriverio [timeouts API](http://webdriver.io/api/protocol/timeouts.html) incorrectly. Two arguments only work for the non-spec variant of the driver, which geckodriver doesn't support.

**Comment by whimboo** [comment]
Btw I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1507283 for a possible more relaxed deserialization.

**Comment by andreastt** [comment]
See also https://github.com/mozilla/geckodriver/issues/1422#issuecomment-439384695 that a specification change is required.

**Comment by whimboo** [comment]
This is actually a dupe of issue #1422. So lets continue the discussion on that other issue.
