### ISSUE TITLE
Zombie process of Firefox created and hangs the selenium test case execution

### ISSUE THREAD

**Issue by ssethy** [mozilla/geckodriver#1421]
## System

* Version: OpenSSH_7.7p1, LibreSSL 2.7.3
* Platform: NAME="CentOS Linux" VERSION="7 (Core)" REDHAT_SUPPORT_PRODUCT_VERSION="7"
* Firefox: Mozilla Firefox 59.0.1
* Selenium: 3.13.0

## Testcase
Our test cases execute for more then 4 hours in middle of somewhere we notice the test case is not progressing and browser is not launched anymore. 
When we check there will be a default browser without any activity. When I check on command line i notice there is a defunct Firefox instance created with a Firefox process running. When I kill both of them then the everything resume back and runs properly. Its difficult to poll every time and kill the process safely. If we just kill Firefox instance every-time blindly in after method just after driver.quit(). It hangs due to abrupt killing of Firefox instance.
We have been facing  since a long causing our test cases to hang and consume lot of time to complete. Some time it times out as well. 

PROCESS DETAIL WHEN UI ACTIVITY IS HANGED DUE TO ZOMBIE FIREFOX PROCESS
[root@<hostname>]# ps -aef | grep firefox
root      1644  1357  0 22:02 pts/0    00:00:00 grep --color=auto firefox
root     23904 18518  0 19:06 ?        00:00:00 /root/com.mobileiron.automation.cms.ui/src/test/resources/drivers/linux/geckodriver --port=8642 -b /usr/local/firefox/firefox
root     23918 23904  0 19:06 ?        00:00:31 [firefox] <defunct>

KILLING ZOMBIE PROCESS AND FIREFOX INSTANCE
[root@<host>]# kill -9 23918
[root@<host>]# kill -9 23904

THE TEST CASE EXECUTE SMOOTHLY AFTER KILLING
[root@<host>]# ps -aef | grep firefox
root      1726 18518  1 22:03 ?        00:00:00 /root/com.mobileiron.automation.cms.ui/src/test/resources/drivers/linux/geckodriver --port=19254 -b /usr/local/firefox/firefox
root      1739  1726 72 22:03 ?        00:00:00 /usr/local/firefox/firefox -marionette -foreground -no-remote -profile /tmp/rust_mozprofile.i2okripqUYui
root      1824  1357  0 22:03 pts/0    00:00:00 grep --color=auto firefox

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

If it's too huge please only add all the lines from the failing geckodriver session.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by ssethy** [comment]
Hi Whimboo,
   I get this issue after 3 hrs or test case execution and that too once in 5 runs. I can change my code to capture exception/log.  however I am worried my changes may impact performance of my run causing unnecessary failures. Kindly confirm on same.

**Comment by whimboo** [comment]
Sorry, but I cannot help without a trace log.

**Comment by ssethy** [comment]
Please leave this case open I will attach logs on reproduce, added the code to capture the log.
