### ISSUE TITLE
Intern functionalTimeouts crashes geckodriver

### ISSUE THREAD

**Issue by GARMBoshouwers** [mozilla/geckodriver#1426]
## System

* Version: geckodriver 0.23.0
* Platform: Microsoft Windows 10 Pro
* Firefox: 63.0.1
* Selenium: selenium-server-standalone-3.14.0.jar
* Intern: 4.3.2
* Node: 9.3.0

## Testcase

In the above environment, setup the following files:
[run.js](https://pastebin.com/wRHv9sMH)
[test.js](https://pastebin.com/wGnv4peh)

Note: the test uses an environmental variable to set the path to the FireFox browser executable. Edit line 22 of run.js to hardcode this.

Run the test using
`node run.js firefox`

The test fails to run. The script fails after the capabilities check. The test works in Chrome, Edge and IE11. 
The test also works in FireFox if the functionalTimeout block is commented out in the config object (run.js, lines 11-13)

It seems the communication of timeout values is incorrect between Intern and geckodriver in these versions.

## Stacktrace

Added as attachment `functionalTimeout command line output.txt`

## Trace-level log

Added as attachment `functionalTimeout trace log.txt`

[functionalTimeout command line output.txt](https://github.com/mozilla/geckodriver/files/2576592/functionalTimeout.command.line.output.txt)
[functionalTimeout trace log.txt](https://github.com/mozilla/geckodriver/files/2576593/functionalTimeout.trace.log.txt)

**Comment by GARMBoshouwers** [comment]
OK, created an issue there

[#6654](https://github.com/SeleniumHQ/selenium/issues/6654)

**Comment by whimboo** [comment]
Btw I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1507283 for a possible more relaxed deserialization.
