### ISSUE TITLE
Returning shadow DOM elements from script evaluation

### ISSUE THREAD

**Issue by mayureshshirodkar** [mozilla/geckodriver#1428]
## System

* Version: v0.23.0
* Platform: Mac OS 10.14
* Firefox: 63.0
* Selenium: 3.14

## Testcase

Given Calendar date is shown
When User selects the date
Then   Correct date is selected
```
    root1 = helper_wait_for_presence_element(self, "//ph3-input-date", 2)
    shadow_root1 = helper_expand_root_element(self, root1)
    root2 = shadow_root1.find_element_by_css_selector("ph3-input-monthly-view")
    shadow_root2 = helper_expand_root_element(self, root2)
    root3 = shadow_root2.find_element_by_css_selector("td#day-index-" + value)
    get_driver(self).execute_script("arguments[0].setAttribute('style', 'background: yellow; border: 2px solid red;');", root3)
    get_driver(self).execute_script("arguments[0].click();", root3)
```

## Stacktrace

```      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "tests/personal_reminders/steps/personal_reminders.py", line 19, in user_creates_reminder
          personal_reminder_set_reminder_date(context, personal_reminder_get_day(date))
        File "/Users/shirodkm/Desktop/Git/greenlamb_qa/naviguide_bdd/tests/personal_reminders/personal_reminder_methods.py", line 74, in personal_reminder_set_reminder_date
          select_date(self, date_value.strftime('%Y-%m-%d'))
        File "/Users/shirodkm/Desktop/Git/greenlamb_qa/naviguide_bdd/tests/personal_reminders/personal_reminder_methods.py", line 256, in select_date
          shadow_root1 = helper_expand_root_element(self, root1)
        File "/Users/shirodkm/Desktop/Git/greenlamb_qa/naviguide_bdd/helper/navigation.py", line 254, in helper_expand_root_element
          shadow_root = get_driver(context).execute_script("return arguments[0].shadowRoot;", element)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
          'args': converted_args})['value']
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
          self.error_handler.check_response(response)
        File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
          raise exception_class(message, screen, stacktrace)
      selenium.common.exceptions.JavascriptException: Message: Cyclic object value
```

## Trace-level log

```
1542617664429	Marionette	TRACE	0 -> [0,101,"WebDriver:FindElement",{"using":"xpath","value":"//ph3-input-date"}]
1542617664431	Marionette	TRACE	0 <- [1,101,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"d0040e02-526a-5643-ac89-b1498d9f5a7b"}}]
1542617667572	Marionette	TRACE	0 -> [0,102,"WebDriver:ExecuteScript",{"args":[{"ELEMENT":"d0040e02-526a-5643-ac89-b1498d9f5a7b","element-6066-11e4-a52e-4f735466c ... 89-b1498d9f5a7b"}],"newSandbox":false,"script":"return arguments[0].shadowRoot;","scriptTimeout":null,"specialPowers":false}]
1542617667579	Marionette	TRACE	0 <- [1,102,{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/e ... esponse@chrome://marionette/content/listener.js:638:17\ndispatch/</<@chrome://marionette/content/listener.js:489:20\n"},null]
```

**Comment by blackgrouse** [comment]
I have the following setup:

- Geckodriver v0.23.0
- Firefox v63.0.3
- Selenium v3.141
- Windows 10

I am testing against [https://shop.polymer-project.org/](url) and trying to access the 'SHOP NOW', button, which I can access fine using

`$("shop-app").shadowRoot.querySelector("shop-home").shadowRoot.querySelector("div.item > shop-button")`

at Firefox's Developer Tools Console window.

When I execute the following code in C#:

`IWebElement root1 = _driver.FindElement(By.CssSelector("shop-app"));`
`IWebElement shadowRoot1 = (IWebElement)((IJavaScriptExecutor)_driver).ExecuteScript("return arguments[0].shadowRoot", root1);`

I get a similar trace to @mayureshshirodkar  when executing the second line:

`webdriver::server       DEBUG   -> POST /session/df40fe6d-c7cd-4d7e-bc1f-41bead690a29/execute/sync {"script":"return arguments[0].shadowRoot","args":[{"element-6066-11e4-a52e-4f735466cecf":"d0dcf147-25c1-4e88-8ae4-7199e87ce1e4","ELEMENT":"d0dcf147-25c1-4e88-8ae4-7199e87ce1e4"}]}`
`Marionette      TRACE   0 -> [0,7,"WebDriver:ExecuteScript",{"args":[{"ELEMENT":"d0dcf147-25c1-4e88-8ae4-7199e87ce1e4","element-6066-11e4-a52e-4f735466cec ... "d0dcf147-25c1-4e88-8ae4-7199e87ce1e4"}],"newSandbox":false,"script":"return arguments[0].shadowRoot","specialPowers":false}]`
`Marionette      TRACE   0 <- [1,7,{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/err ... esponse@chrome://marionette/content/listener.js:638:17\ndispatch/</<@chrome://marionette/content/listener.js:489:20\n"},null]`
`webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"javascript error","message":"Cyclic object value","stacktrace":"WebDriverError@chrome://marionette/content/error.js:178:5\nJavaScriptError@chrome://marionette/content/error.js:355:5\nassert.acyclic@chrome://marionette/content/assert.js:56:11\nevaluate.toJSON@chrome://marionette/content/evaluate.js:273:5\nsendResponse@chrome://marionette/content/listener.js:638:17\ndispatch/</<@chrome://marionette/content/listener.js:489:20\n"}}`

**Comment by andreastt** [comment]
Shadow DOM is not supported in WebDriver yet, see https://github.com/w3c/webdriver/issues/350 for further context.

**Comment by mayureshshirodkar** [comment]
@andreastt But this seems to be an issue with Firefox only, The same code works fine on Chrome

**Comment by blackgrouse** [comment]
@andreastt This is a blocker for me automating testing of my company's website on the latest version of Firefox.

A temporary fix to unblock me and probably others would be great, while a conformant fix is developed

**Comment by rudreshtrivedi** [comment]
This is not supported in Firefox 67. Please close this issue.

**Comment by whimboo** [comment]
> This is now supported in Firefox 67. Please close this issue.

Not sure what you are referring to, but as @andreastt already said above it's not defined for the WebDriver spec yet, and as such it is NOT implemented in geckodriver/Marionette.

**Comment by rudreshtrivedi** [comment]
Even if this is not defined in WebDriver Spec, It is working completely fine with Latest Firefox (V67) and Geckodriver (V0.24). 

[Please find linked screenshot as proof. ](https://imgur.com/a/NQa9psp)

@blackgrouse  just need to write case as below

`IWebElement finalElement = (IWebElement)((IJavaScriptExecutor)_driver).ExecuteScript("return document.querySelector(\"shop-app\").shadowRoot.querySelector(\"shop-home\").shadowRoot.querySelector(\"div.item > shop-button\"));
`

You will get your element directly without even iterating

**Comment by andreastt** [comment]
I think this may have been fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1495621, specifically [`49df528add26`](https://hg.mozilla.org/mozilla-central/rev/49df528add26):

```diff
--- a/testing/marionette/evaluate.js
+++ b/testing/marionette/evaluate.js
@@ -267,18 +267,17 @@ evaluate.toJSON = function(obj, seenEls)
     return [...obj].map(el => evaluate.toJSON(el, seenEls));
 
   // WebElement
   } else if (WebElement.isReference(obj)) {
     return obj;
 
   // Element (HTMLElement, SVGElement, XULElement, et al.)
   } else if (element.isElement(obj)) {
-    let webEl = seenEls.add(obj);
-    return webEl.toJSON();
+    return seenEls.add(obj);
 
   // custom JSON representation
   } else if (typeof obj.toJSON == "function") {
     let unsafeJSON = obj.toJSON();
     return evaluate.toJSON(unsafeJSON, seenEls);
   }
 
   // arbitrary objects + files
```

However, VCS seems to indicate that was on the milestone for 68. I suppose something else related could have landed in DOM before that, as it seems from the bug this has been work ongoing for a long time.

That said, there are two different problems here though:

1. Returning an open shadow root element through script evaluation.
2. Retrieving an element from either a closed or open shadow root through Find Element/Find Elements/Find Element From Element/Find Elements From Element commands.

The first appears fixed now, but the second is still valid.

Since the original bug was about accessing open shadow roots through script evaluation, I’m inclined to rename this issue accordingly and close it. But I just want to be clear on the fact that switching to a different shadow root as a top-level primitive in WebDriver is still yet to be defined in the specification (tracked in https://github.com/w3c/webdriver/issues/350).
