### ISSUE TITLE
Load a fake webcam video file with media.navigator.streams.fake flag

### ISSUE THREAD

**Issue by Darkensses** [mozilla/geckodriver#1429]
## System

* Version: 0.23.0 
* Platform: Windows 
* Firefox: 63 
* Selenium: 3.141.59 

## Description

I'm working with automated tests and I'm trying to stream a video simulating the webcam streaming. I'm using Selenium with Java.

Chrome has the feature to use a video file to 'simulate' a webcam passing a flag with the path of video file, like this: --use-file-for-fake-video-capture=path/to/video.y4m

Firefox also has a similar feature (media.navigator.streams.fake) and when the property is true, I get the multicolor video by default instead my webcam but it is possible to stream a local video file like chrome? how can I accomplish it?

## Code
FirefoxOptions options = new FirefoxOptions();
options.addPreference("media.navigator.streams.fake", true);
options.addPreference("media.navigator.permission.disabled", true);
this.webDriver = new FirefoxDriver(options);

What do I need to add?

**Comment by andreastt** [comment]
This isn’t a Firefox support forum, but I also don’t know the answer to your question.

**Comment by Darkensses** [comment]
My apologies and thanks for the answer. Best vibes
