### ISSUE TITLE
Selenium Can not open a connection with the specified URL of the desired application

### ISSUE THREAD

**Issue by mariamToujeni** [mozilla/geckodriver#1431]
## System

* Version: 0.23.0
* Platform: Linux
* Firefox: 63.0
* Selenium:  3.11.0

## Testcase

<ystem : Geckodriver: :0.23.0 Platform: Linux Firefox: 63.0 Selenium: 3.11.0

I am trying to run tests on an application :

 System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE,"true");

        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
       capabilities.setCapability("marionette", true);

        ProfilesIni profile = new ProfilesIni();

        FirefoxProfile profiles = profile.getProfile(profil);
        FirefoxOptions options = new FirefoxOptions();
        options.setProfile(profiles);
        options.addPreference("marionette.logging", "{level: trace}");

        driver = (FirefoxDriver)webdriverClass.getConstructor(FirefoxOptions.class).newInstance(options);

    }
    driver.manage().window().maximize();

    this.wait = new WebDriverWait(driver, implicitwait);
    return driver;
}
The test launcher :

@BeforeClass
public void initiate() throws Exception {

    pool = Executors.newFixedThreadPool(thread);

    final  String GECKODRIVER_PATH = "/home/geckodriver";

        if ( System.getProperty("webdriver.gecko.driver") == null)
            System.setProperty("webdriver.gecko.driver", GECKODRIVER_PATH);

@Test(priority = 1, testName = "test", description = "test")
public void testCase001() throws Exception {
    testSuites = execute.getScenario(sec1, firefoxDriver);
    pool.invokeAll(testSuites);

}

@AfterClass(alwaysRun=true)
    public void terminate(){

    pool.shutdown();
}
}

And the url of application has the format : with x.x.x.x is the ip adress of the application:

**https://x.x.x.x/XXapp**

The browser opens ,tries to connect but it closes without establishing the connection , if i replace the url with https://www.google.fr/ it works .

## Trace-level log

 see attachement 
[tracelog.txt](https://github.com/mozilla/geckodriver/files/2600125/tracelog.txt)

**Comment by whimboo** [comment]
This is not a geckodriver tracelog. Please check our docs in how to create a [trace-level log] for your Selenium binding. 
[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
No response from reporter. Closing issue.
