### ISSUE TITLE
Firefox is not opening the provided URL, is it a compatibility issue ? 

### ISSUE THREAD

**Issue by waleedfiyaz1** [mozilla/geckodriver#1432]
[Error LOG.txt](https://github.com/mozilla/geckodriver/files/2603296/Error.LOG.txt)

## System

* Version: geckodriver version 0.23.0 (64bit)
* Platform: Window 7 (64bit)
* Firefox: 62.0.3 (64bit) 
* Selenium: Webdriver version 3.141.59 

## Testcase
package Login;
import java.util.concurrent.TimeUnit;
import org.testng.annotations.*;
import static org.testng.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

public class test {

  private WebDriver driver;
  private String baseUrl;
  private StringBuffer verificationErrors = new StringBuffer();

  @BeforeClass(alwaysRun = true)
  public void setUp() throws Exception {
    driver = new FirefoxDriver();
    baseUrl = "https://www.google.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void testUntitledTestCase() throws Exception {
    driver.get(baseUrl);
    driver.findElement(By.id("lga")).click();
    driver.findElement(By.name("q")).clear();
    driver.findElement(By.name("q")).sendKeys("test");
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::span[1]")).click();
  }

  @AfterClass(alwaysRun = true)
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }
}

**Comment by waleedfiyaz1** [comment]
How do i get a Trace-level log from gecko

**Comment by whimboo** [comment]
If you can provide a trace log we will reconsider opening the issue.
