### ISSUE TITLE
driver.navigate().back() does not return until timeout

### ISSUE THREAD

**Issue by PratibhaMache** [mozilla/geckodriver#1434]
## System

* Version: 0.21.0
* Platform: Windows 7  64-bit
* Firefox: 61.0 (64-bit)
* Selenium: 3.14.0 

## Testcase

I'm working on specific application. In which i will have go from current page to next page and next page to previous page and verify both page loaded properly or not.

**Steps:**
1. Login to application
2. Goto 'Page A' to 'Page B'    : Verify 'Page B' load properly
3. Click on Browser back button

**Actual:** Able to click on back button and 'Page A' load but the method not completed until timeout with following error

###!!! [Parent][MessageChannel] Error: (msgtype=0x16008C,name=PBrowser::Msg_UpdateNativeWindowHandle) Closed channel: cannot send/recv

**Expected:** Page A should be loaded properly

## Stacktrace

02:14:13 [PASS]: assert true: Device Types: - Linux
[m1542871066757	addons.xpi-utils	WARN	disabling legacy extension firebug@software.joehewitt.com
1542871316003	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 2.0
1542871316004	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat-reporter@mozilla.org version 1.0.0
1542871316004	addons.xpi	DEBUG	Calling bootstrap method shutdown on screenshots@mozilla.org version 32.1.0
1542871316008	addons.xpi	DEBUG	Calling bootstrap method shutdown on onboarding@mozilla.org version 1.0
1542871316009	addons.xpi	DEBUG	Calling bootstrap method shutdown on formautofill@mozilla.org version 1.0
1542871316010	addons.xpi	DEBUG	Calling bootstrap method shutdown on followonsearch@mozilla.com version 0.9.7
1542871316010	addons.xpi	DEBUG	Calling bootstrap method shutdown on firefox@getpocket.com version 1.0.5
1542871316011	addons.xpi	DEBUG	Calling bootstrap method shutdown on aushelper@mozilla.org version 2.0
1542871316011	addons.xpi	DEBUG	Calling bootstrap method shutdown on activity-stream@mozilla.org version 2018.05.30.0900-c6d48b86
[Child 3292, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\SevOne\AppData\Local\openvr\openvrpaths.vrpath
[Parent 3592, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\SevOne\AppData\Local\openvr\openvrpaths.vrpath
[Child 4280, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 3592, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\SevOne\AppData\Local\openvr\openvrpaths.vrpath
[Child 3584, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

###!!! [Parent][MessageChannel] Error: (msgtype=0x16008C,name=PBrowser::Msg_UpdateNativeWindowHandle) Closed channel: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x16007F,name=PBrowser::Msg_Destroy) Closed channel: cannot send/recv

###!!! [Child][MessageChannel] Error: (msgtype=0x2D00C1,name=PContent::Msg_PrivateDocShellsExist) Closed channel: cannot send/recv

1542871316545	addons.manager	DEBUG	shutdown
1542871316545	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1542871316546	addons.xpi	DEBUG	shutdown
1542871316546	addons.xpi-utils	DEBUG	shutdown
1542871316546	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1542871316546	addons.manager	DEBUG	Calling shutdown blocker for GMPProvider
1542871316546	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1542871316552	addons.manager	DEBUG	Async provider shutdown done

**Comment by whimboo** [comment]
No further response from reporter. Closing the issue.
