### ISSUE TITLE
Behat + Selenium + GeckoDriver - Unable to proceed with test

### ISSUE THREAD

**Issue by p2635** [mozilla/geckodriver#1437]
## System

* Version: 0.23
* Platform: Windows 10
* Firefox: 63.0.3 (64 bit)
* Selenium: Selenium server stand alone 3.141.59

## Testcase

In my BeforeScenario of my behat file FeatureContext.php, it says this:

```
/** @BeforeScenario */
    public function before(BeforeScenarioScope $scope)
    {
        $tags = $scope->getScenario()->getTags();
        if (in_array('skip', $tags)) {
            throw new SkippedException();
        }

         // Reduce the page timeout to expedite test
       $this->getSession()->getDriver()->setTimeouts(['page load' => 60000]);
    }
```

## Stacktrace

```
  ┌─ @BeforeScenario # FeatureContext::before()
  │
  ╳  unknown field `ms`, expected one of `implicit`, `pageLoad`, `script` at line 2 column 6
  ╳  Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
  ╳  System info: host: 'COMPUTER', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
  ╳  Driver info: driver.version: unknown (Exception)
  │
```

## Trace-level log
```
16:41:16.974 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browser": "firefox",
  "browserName": "firefox",
  "ignoreZoomSetting": false,
  "marionette": "true;",
  "name": "Behat feature suite",
  "tags": [
    "COMPUTER",
    "PHP 7.0.32"
  ]
}
16:41:16.987 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1543250477607   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\USER~1\\AppData\\Local\\Temp\\rust_mozprofile.xc0wSA6bDzje"
1543250483964   Marionette      INFO    Listening on port 57143
1543250484413   Marionette      WARN    TLS certificate errors will be ignored for this session
16:41:24.544 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
16:41:24.583 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session a9efab3a-e3dd-40c5-811d-c6a6c01ba0b3 (org.openqa.selenium.firefox.GeckoDriverService)
1543250484859   Marionette      INFO    Stopped listening on port 57143
JavaScript error: resource://activity-stream/lib/TopSitesFeed.jsm, line 86: TypeError: setting getter-only property "_currentSearchHostname"
[Parent 17068, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 19036, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 19036, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 17068, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Parent 17068, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Chil
###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

[GPU 18804, Chrome_ChildThread] WA
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

16:41:26.461 INFO [ActiveSessions$1.onStop] - Removing session a9efab3a-e3dd-40c5-811d-c6a6c01ba0b3 (org.openqa.selenium.firefox.GeckoDriverService)
```

Please let me know if you need more info, I'm new to using all these tools so it would be awesome if you could provide support on this.

**Comment by andreastt** [comment]
This is a problem with the client you’re using not supporting the forthcoming [WebDriver standard](https://w3c.github.io/webdriver/). It specifically needs to be updated to not send `{type: "<timeout type>", ms: <N>}` payloads, but instead `{<timeout type>: <N>}`.

I hope this helps!

**Comment by whimboo** [comment]
Please also see https://github.com/mozilla/geckodriver/issues/1422#issuecomment-439384695 which is most likely the reason why it is visible those days.

**Comment by p2635** [comment]
Thanks @andreastt and @whimboo.

Sorry @andreastt, what did you mean by client? I tried to update all my packages in composer but that didn't fix it.  I'm still stuck... what do I have to do specifically to fix it? I think I have the latest copies for geckodriver and selenium.. sorry to bother you,

**Comment by andreastt** [comment]
@p2635 This is a bug _in_ the client, so if the latest version of it does not have a patch you should file a bug against it.

Feel free to reference this bug as it contains enough information for the client maintainer to fix the problem.

**Comment by p2635** [comment]
Hi @whimboo, it works with 0.21 but unfortunately my behat test still fails, it gives me this exception 'Fatal error: Class 'Behat\Mink\Exception\ExpectationException' not found in C:\dir\vendor\behat\mink\src\Exception\ElementNotFoundException.php on line 21'

It's not giving it enough time to load the page (I assume), I guess this is outside the scope of this ticket but if you are able to support me that would be great... as i'm stuck.

**Comment by whimboo** [comment]
Oh, and the other issue sounds like a bug in your Selenium client.

**Comment by p2635** [comment]
Thank you for your help @whimboo, I will try to ask the Selenium community for help on that noe
