### ISSUE TITLE
Can't read the browser console

### ISSUE THREAD

**Issue by borgogelli** [mozilla/geckodriver#144]
I use facebook/php-webdriver and the folowing commands work with Chrome driver, Firefox (Selenium built-in driver), PhantomJs and Safari but not with Marionette.

The code:
`$types = self::$webDriver->manage()->getAvailableLogTypes();`

The error:
`exception 'Facebook\WebDriver\Exception\UnknownServerException' with message 'GET /session/..../log/types did not match a known command `

Are there any other solutions to read the browser console ?

Regards

**Comment by andreastt** [comment]
Reading the console is not part of the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html). There have been ideas floating about to develop a “WebDriver Console” spec after it reaches maturity.

**Comment by borgogelli** [comment]
Thank you

**Comment by unki2aut** [comment]
But it would be awesome to extend it to the selenium specifications https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol :smiley:

**Comment by andreastt** [comment]
@unki2aut geckodriver/Marionette is not an implementation of the Selenium JSON wire protocol, but of the W3C WebDriver specification (linked above).
