### ISSUE TITLE
In headless mode for gecko driver,not able to scroll

### ISSUE THREAD

**Issue by sjdptn** [mozilla/geckodriver#1440]
In headless mode, we have a test scenario of tapping/clicking on the button in the bottom of the screen.We have no scroll added /implemented for our application.
We would like to minimize/ decrease the zoom level/ or use the keys like ctrl and subtract symbol so that the button is visible and the test execution happens in headless mode on linux server.

How can we resolve this issue?
Is there any option mentioned above which can be used to over come this issue?

**Comment by whimboo** [comment]
Without any trace log and some insight into the code you are running like with a minimized HTML testcase there is nothing we can help with. Also it's not even clear if you are using `Element Click` or `Perform Actions`.

**Comment by andreastt** [comment]
> We would like to minimize/ decrease the zoom level/ or use the keys like ctrl and subtract symbol so that the button is visible and the test execution happens in headless mode on linux server.

Theoretically speaking, issuing the `Control` and `+` or `-` sequence should not affect the zoom level because we don’t want key combinations to have any effect on the browser chrome…

**Comment by whimboo** [comment]
No feedback from reporter. Closing issue.
