### ISSUE TITLE
Selecting Elements not working - Failed to convert data to an object

### ISSUE THREAD

**Issue by GeorgeXCV** [mozilla/geckodriver#1445]
## System

* Version : 0.23.0
* Platform: Windows 64
* Firefox:  63.0
* Selenium: 3.14 

## Testcase

When I run my automated test, I get the following error instead of clicking the Google search box.

org.openqa.selenium.WebDriverException: Failed to convert data to an object

## Trace-level log

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/C:/Program%20Files/Eclipse/Cucumber/cucumber-jvm-deps-1.0.5.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1543677298614	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\George\\AppData\\Local\\Temp\\rust_mozprofile.61sqTXErL1wT"
1543677298617	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:1405
1543677298934	Marionette	DEBUG	Received observer notification profile-after-change
1543677298978	Marionette	DEBUG	Received observer notification toplevel-window-ready
1543677298996	Marionette	DEBUG	Received observer notification command-line-startup
1543677298996	Marionette	DEBUG	Received observer notification nsPref:changed
1543677298996	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1543677299095	Marionette	DEBUG	Received observer notification toplevel-window-ready
1543677299621	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1543677299621	Marionette	DEBUG	Waiting for delayed startup...
1543677299667	Marionette	DEBUG	Setting recommended pref security.turn_off_all_security_so_that_viruses_can_take_over_this_computer to true
1543677299667	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1543677299667	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1543677299668	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1543677299668	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1543677299668	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1543677299668	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1543677299669	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1543677299669	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1543677299669	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1543677299669	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1543677299669	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1543677299670	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1543677299670	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1543677299670	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1543677299670	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1543677299671	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1543677299671	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1543677299671	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1543677299671	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1543677299671	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1543677299672	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1543677299672	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1543677299673	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1543677299673	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1543677299703	Marionette	INFO	Listening on port 1405
1543677299703	Marionette	DEBUG	Remote service is active
1543677299721	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:1405. Waiting for Marionette handshake
1543677299722	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:1418
1543677299722	geckodriver::marionette	DEBUG	Connected to Marionette
1543677299724	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1543677299724	Marionette	WARN	TLS certificate errors will be ignored for this session
1543677299755	Marionette	DEBUG	[6442450945] Frame script loaded
1543677299758	Marionette	DEBUG	[6442450945] Frame script registered
1543677299759	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"b1d6d148-8d81-4215-911c-938953be4b0b","capabilities":{"browserName":"firefox","browserVersion":"63.0. ... AppData\\Local\\Temp\\rust_mozprofile.61sqTXErL1wT","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1543677299767	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"b1d6d148-8d81-4215-911c-938953be4b0b","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"63.0.3","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":false,"moz:processID":11896,"moz:profile":"C:\\Users\\George\\AppData\\Local\\Temp\\rust_mozprofile.61sqTXErL1wT","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
Dec 01, 2018 3:14:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1543677299830	webdriver::server	DEBUG	-> POST /session/b1d6d148-8d81-4215-911c-938953be4b0b/timeouts {
  "implicit": 10000
}
1543677299832	Marionette	TRACE	0 -> [0,2,"WebDriver:SetTimeouts",{"implicit":10000}]
1543677299832	Marionette	TRACE	0 <- [1,2,null,{"value":null}]
1543677299832	webdriver::server	DEBUG	<- 200 OK {"value":null}
1543677299837	webdriver::server	DEBUG	-> POST /session/b1d6d148-8d81-4215-911c-938953be4b0b/url {
  "url": "https:\u002f\u002fwww.google.co.uk"
}
1543677299838	Marionette	TRACE	0 -> [0,3,"WebDriver:Navigate",{"url":"https://www.google.co.uk"}]
1543677299844	Marionette	DEBUG	[6442450945] Received DOM event beforeunload for about:blank
1543677300214	Marionette	DEBUG	[6442450945] Received DOM event pagehide for about:blank
1543677300331	Marionette	DEBUG	[6442450945] Received DOM event DOMContentLoaded for https://www.google.co.uk/
1543677300999	Marionette	DEBUG	[6442450945] Received DOM event pageshow for https://www.google.co.uk/
1543677301001	Marionette	TRACE	0 <- [1,3,null,{"value":null}]
1543677301000	webdriver::server	DEBUG	<- 200 OK {"value":null}
1543677301006	webdriver::server	DEBUG	-> POST /session/b1d6d148-8d81-4215-911c-938953be4b0b/element {
  "value": "#lst\\-ib",
  "using": "css selector"
}
1543677301007	Marionette	TRACE	0 -> [0,4,"WebDriver:FindElement",{"using":"css selector","value":"#lst\\-ib"}]
1543677307414	Marionette	DEBUG	Received DOM event unload for [object XULDocument]
1543677307419	Marionette	DEBUG	Received observer notification message-manager-disconnect
1543677307428	Marionette	TRACE	0 <- [1,4,null,{"value":null}]
1543677307455	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Failed to convert data to an object","stacktrace":""}}
[Parent 11896, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6568, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1543677307477	Marionette	DEBUG	Closed connection 0
[Parent 11896, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 11800, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346 

> 

## Stacktrace

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/C:/Program%20Files/Eclipse/Cucumber/cucumber-jvm-deps-1.0.5.jar) to field java.util.TreeMap.comparator
> WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 1543674099922	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\George\\AppData\\Local\\Temp\\rust_mozprofile.ZjMT5lXMO0EJ"
> 1543674101125	Marionette	INFO	Listening on port 2802
> 1543674101532	Marionette	WARN	TLS certificate errors will be ignored for this session
> Dec 01, 2018 2:21:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C
> [Parent 6600, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
> 
> [31mFailed scenarios:[0m
> [31mSearch.feature:24 [0m# Scenario: I can find specfic product on Amazon
> 
> 1 Scenarios ([31m1 failed[0m)
> 7 Steps ([31m1 failed[0m, [36m4 skipped[0m, [32m2 passed[0m)
> 0m7.331s
> 
> org.openqa.selenium.WebDriverException: Failed to convert data to an object
> Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:05:20.749Z'
> System info: host: 'DESKTOP-83D16R2', ip: '192.168.0.12', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 63.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.23.0, moz:headless: false, moz:processID: 6600, moz:profile: C:\Users\George\AppData\Loc..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
> Session ID: 862e9ad2-b5db-4d58-96a5-8462fb56545f
> *** Element info: {Using=id, value=lst-ib}
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:322)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:368)
> 	at org.openqa.selenium.By$ById.findElement(By.java:188)
> 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:314)
> 	at Steps.Test_Steps.searchGoogle(Test_Steps.java:32)
> 	at ?.Then Search for shop Amazon UK(Search.feature:27)
>

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by GeorgeXCV** [comment]
> 
> 
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html).

Enabled debug and added output to original post, hope that helps, thanks.

**Comment by GeorgeXCV** [comment]
> 
> 
> @GeorgeXCV what happens if you add a sleep of about 5s or so between the navigation and call to find element? It looks like Firefox misbehaves here, and the browsing context gets closed. Maybe a crash? Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html

Figured it out, was related to the script, apologies. Thanks for the help!

**Comment by thismatters** [comment]
no breadcrumbs for other people encountering the same issue??
