### ISSUE TITLE
How to debug headless Firefox?

### ISSUE THREAD

**Issue by briandipalma** [mozilla/geckodriver#1448]
Not an issue as such but a question about debugging a headless Firefox. Adding 

```
args: ["--start-debugger-server"]
```

isn't enough, I believe that's because the `Enable remote debugging` and `Enable browser chrome...` options aren't switched on by that flag (at least they aren't in normal Firefox when using that flag).

Would I have point Firefox to a profile that has these features enabled? That's a rather awkward approach given that WebdriverIO seems to create fresh profiles each run. Are there some flags we can pass to Firefox to tell it to enable remote debugging and allow connections?

**Comment by andreastt** [comment]
You’re correct about needing some extra preferences to turn on remote debugging and chrome debugging. You will the necessary information documented here:
https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Debugging.html

You can provide custom preferences in `moz:firefoxOptions` that geckodriver will write to the profile (whether provided or to a fresh profile) on session creation. For example:

```js
{
  "moz:firefoxOptions": {
    "prefs": {
      "devtools.debugger.remote-enabled": true,
      "devtools.debugger.prompt-connection": false,
      "devtools.chrome.enabled": true
    }
  }
}
```

**Comment by briandipalma** [comment]
OK, thank you, that fixed it. I've added some documentation at https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode#Debugging_headless_Firefox

**Comment by DarioG** [comment]
> You’re correct about needing some extra preferences to turn on remote debugging and chrome debugging. You will the necessary information documented here:
> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Debugging.html
> 
> You can provide custom preferences in `moz:firefoxOptions` that geckodriver will write to the profile (whether provided or to a fresh profile) on session creation. For example:
> 
> ```js
> {
>   "moz:firefoxOptions": {
>     "prefs": {
>       "devtools.debugger.remote-enabled": true,
>       "devtools.debugger.prompt-connection": false,
>       "devtools.chrome.enabled": true
>     }
>   }
> }
> ```

Hi where do i have to add this configuration?

**Comment by whimboo** [comment]
@DarioG please check the geckodriver documentation, but not Marionette as linked in your blockquote. See https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html.
