### ISSUE TITLE
Browser process stopped: signal: 7

### ISSUE THREAD

**Issue by akostadinov** [mozilla/geckodriver#1453]
## System

Browser: Firefox
Browser version: 60.2.1 64bit
Browser Driver version: geckodriver 0.23.0
Language Bindings version: Ruby selenium-webdriver (3.141.0)
OS: Red Hat Enterprise Linux 7.6

## Description

Hello, I'm running Firefox test inside container. Since recently we notice that browser dies sometimes killed by signal 7 as shown in trace log. I realize this is not an ideal bug report but I'll appreciate any suggestions how to debug why browser dies... such that I can close the issue or provide more more useful information.

## Trace-level log

[trace.txt](https://github.com/mozilla/geckodriver/files/2699977/trace.txt)

**Comment by whimboo** [comment]
Could you run a debug build of Firefox? If yes we have those for ESR60 too. You can download one from https://queue.taskcluster.net/v1/task/ZEJOg08HQiiJ9UkJbJNYQA/runs/0/artifacts/public/build/target.tar.bz2. If it also quits the same way, it should give us more information in what is causing it.

**Comment by whimboo** [comment]
No reply from reporter. Closing issue.

**Comment by akostadinov** [comment]
@whimboo , where should I find this extra debug info?

**Comment by akostadinov** [comment]
Uploading a new marionette trace log from a custom debug build I have created. Does it contain any more meaningful information? It doesn't look like much details. That's why asking where should I have expected more output.

[tracedbg.txt](https://github.com/mozilla/geckodriver/files/3044272/tracedbg.txt)

**Comment by akostadinov** [comment]
Sorry for tripple posting. I managed to reproduce with the debug build from above link. Initially I couldn't so it took a couple of attempts. Anyway, attaching the debug log: 
[tracedbg.txt](https://github.com/mozilla/geckodriver/files/3045058/tracedbg.txt)

**Comment by whimboo** [comment]
Yes, there is a crash:

> A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down

To get the details please follow the steps on this page: https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html

**Comment by akostadinov** [comment]
After huge effort to figure it out, I managed to run Firefox with a new manually created profile (I tried to preserve auto-generated profile to no avail). Unfortunately it is generating a zero size dump:
```
# ls home/jenkins/.mozilla/firefox/f0jecsmr.test/minidumps/68bea329-d105-e885-d563-033647b7142e.dmp -lh
-rw-------. 1 1001 root 0 Apr 11 13:57 home/jenkins/.mozilla/firefox/f0jecsmr.test/minidumps/68bea329-d105-e885-d563-033647b7142e.dmp
```

Any ideas?

**Comment by whimboo** [comment]
That is unfortunate! Is the `.extra` file beside this minidump file also empty? 

Note that none of the above environment variables need to be set manually. Those necessary to create a dump file are all set by geckodriver itself. 

Do you know what exit code 7 actually means?

**Comment by akostadinov** [comment]
I removed the env variables but it is the same. Still zero size dumps and lack of `extra` file. I also increased  stack and memory lock limits to no avail. 

```
bash-4.2$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 23534
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1048576
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

No idea what exit code 7 means. Any other suggestions?

**Comment by whimboo** [comment]
Lets try a different scenario. Given that this is a content crash you will have to remove the `MOZ_CRASHREPORTER_SHUTDOWN=1` from the list of env variables when Firefox gets started or is running. Geckodriver sets it [here](https://searchfox.org/mozilla-central/rev/ee3905439acbf81e9c829ece0b46d09d2fa26c5c/testing/geckodriver/src/marionette.rs#165).

With that Firefox will not shutdown itself, and you should see a tab crashed page in the current tab. To be able to submit a crash you will also have to remove the other two environment variables. Best would be to comment out those lines and build geckodriver yourself. Would you be able to do that?

**Comment by akostadinov** [comment]
Ok, I have rebuilt `geckodriver` from `mozilla-central-02b89c29412b` with these variable commented out. Now tests hang and I have 300 seconds to grab a screenshot. I can only grab screenshot because my reproducer is inside a container and tests run in Xvfb.

Now my error message on test runner is:
```
Timeout loading page after 300000ms (Selenium::WebDriver::Error::TimeOutError)
```

Here you can see last log lines as well trying to grab a screenshot via `firefox --screenshot` result: 
[firefox_more_logs.txt](https://github.com/mozilla/geckodriver/files/3095862/firefox_more_logs.txt)

And this is the screenshot which appears mostly useless: 
![firefox_crash](https://user-images.githubusercontent.com/1408661/56385341-7d7b7400-6227-11e9-87d4-b74ea178c069.png)

Anything helpful there you can see?
