### ISSUE TITLE
Can't lounch tests on VM (Win server),but on local PC tests run perfectly

### ISSUE THREAD

**Issue by EvgenyaMukhtulova** [mozilla/geckodriver#1457]
## System

* Version: geckodriver version 0.19.1/0.21/0.23
* Platform: Windows Server
* Firefox: 60/64
* Selenium: 2.53.1 /3.3.1/3.3.0

## Testcase

        WebDriver driver=getDriver();
        WebDriver.Navigation navigate = driver.navigate();
        navigate.to(MY_URL);

## Problem description
On my local PC  tests run cotrrectly, bur when I try to run my autotests in remote machine have errors (Hovewer in Chrome browser with chrome driver on the same VM my tests run perfectly).

## Trace-level log

13:02:45.098 [pool-1-thread-1] DEBUG n.s.c.w.s.GeckoServicePool - Creating new driver instance with capabilities: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: false, marionette: true}
13:02:46.208 [pool-1-thread-1] WARN  n.s.c.w.s.GeckoServicePool - Remote driver creation failed (Unable to find a matching set of capabilities), falling back on default driver creation
1545818568749	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{ae7788fc-13a8-4b1f-b83b-e86fa278d8cb}","version":"35.0.0","type":"webextension","updateURL":null,"optionsURL":null,"optionsType":null,"optionsBrowserStyle":true,"aboutURL":null,"defaultLocale":{"name":"Firefox Screenshots","description":"Take clips and screenshots from the Web and save them temporarily or permanently.","creator":"Mozilla <screenshots-feedback@mozilla.com>","homepageURL":"https://github.com/mozilla-services/screenshots","developers":null,"translators":null,"contributors":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"installDate":1544154783338,"updateDate":1544154783338,"applyBackgroundUpdates":1,"path":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","skinnable":false,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"strictCompatibility":true,"locales":[{"name":"Firefox Screenshots","des...

**Comment by EvgenyaMukhtulova** [comment]
It's important for me, please, give me answer ASAP

**Comment by whimboo** [comment]
You are using an outdated release of Selenium. As you can see by our [support matrix](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html) it would require at least version 3.5.

Does upgrading Selenium fix your problem?

**Comment by EvgenyaMukhtulova** [comment]
Thanks for your answer!
I tried launch tests using versions 3.5/3.6/3.11/3.14 but I have the same problems (on local machine tests run correctly, but on remote machine there are errors like this and with some selenium versions tests failed by timeout)
-----
DRIVER NAME = class org.openqa.selenium.firefox.FirefoxDriver
2019-01-09T09:53:50.2285650Z 12:48:36.618 [pool-1-thread-1] DEBUG n.s.c.w.s.GeckoServicePool - Creating new driver instance with capabilities: Capabilities {acceptInsecureCerts: true, browserName: firefox, firefox_profile: org.openqa.selenium.firefox..., headless: false, marionette: true}
2019-01-09T09:53:50.2285650Z 12:48:37.524 [pool-1-thread-1] WARN  n.s.c.w.s.GeckoServicePool - Remote driver creation failed (Unable to find a matching set of capabilities), falling back on default driver creation...

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by EvgenyaMukhtulova** [comment]
[log.txt](https://github.com/mozilla/geckodriver/files/2744779/log.txt)
Is it enough for presentation?

**Comment by whimboo** [comment]
Yes, thanks. So Firefox gets started fine, and also a connection can be made to Marionette. After creating the session the test tries to load the following web page: https://moskva.beeline.ru/business/main/

But that fails and as such the navigation command runs into a timeout after 300s:

> 1547111725851	Marionette	TRACE	0 <- [1,4,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/cont ... 8:5\nTimeoutError@chrome://marionette/content/error.js:445:5\nnotify@chrome://marionette/content/listener.js:338:13\n"},null]

The problem is that it never finishes loading and the last load event which is fired on that page is `DOMContentLoaded`, which means that all the DOM content has been loaded, but not all the other resources like external ones. Once those have been loaded a `pageshow` event would be fired, and that is what the navigation command waits for.

This might be related to a networking issue, wrong proxy settings, a firewall, or some other software running on the affected host. But it is not a geckodriver issue.

**Comment by EvgenyaMukhtulova** [comment]
Okey,I get it...
Thank you for your explanations and time for me!
