### ISSUE TITLE
geckodriver 0.23 button click doesn't open new page on Firefox 64.0

### ISSUE THREAD

**Issue by ishtiaque06** [mozilla/geckodriver#1458]
I have a testcase that treis to send the user to a new URL once a button with a link is pressed. However, Firefox doesn't seem to be responding with the proper URL when I place `time.sleep(3)` after `button.click()`. The original testcase is below. 
**Note**: this same test case works perfectly fine with chromedriver. 

## System

* Version: 0.23.0
* Platform: Ubuntu 18.10 x64
* Firefox: 64.0
* Selenium: 3.141.0
* Python: 3.6.7 (Django 2.0)

## Testcase

```python
class AdminRegisterTest(LiveServerTestCase):
    ...
    @contextmanager
    def wait_for_page_load(self, timeout=10):
        old_page = self.browser.find_element_by_tag_name('html')
        yield
        WebDriverWait(self.browser, timeout).until(
            staleness_of(old_page)
        )
    ...
    def test_user_redirected_to_register_college(self):
        url = self.browser.get(self.live_server_url)
        button = self.browser.find_element_by_id('register-college')
        with self.wait_for_page_load(timeout=3):
            button.click()
        self.assertEqual(self.browser.title, "Register Your College")

```

## Stacktrace

```python
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
E
======================================================================
ERROR: test_user_redirected_to_register_college (functional_tests.test_college_creation.AdminRegisterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aishtiaque/projects/dibs_django/functional_tests/test_college_creation.py", line 49, in test_user_redirected_to_register_college
    button.click()
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/aishtiaque/projects/dibs_django/functional_tests/test_college_creation.py", line 29, in wait_for_page_load
    staleness_of(old_page)
  File "/home/aishtiaque/.virtualenvs/dibs_dev/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


----------------------------------------------------------------------
Ran 3 tests in 13.256s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

## Trace-level log

Attached as [pastebin](https://pastebin.com/Cc4rLv0S).

**Comment by whimboo** [comment]
Does this button have an event listener for `click` assigned, which is running some custom Javascript code? As I can see there is no page navigation happening after the click for about 200ms, which is kinda long:

> 1546059842927   Marionette  TRACE   0 -> [0,5,"WebDriver:ElementClick",{"id":"c4b3fc57-2825-4a4f-a16f-13249be49415"}]
> 1546059843145   Marionette  DEBUG   [4294967297] Canceled page load listener because no navigation has been detected

**Comment by ishtiaque06** [comment]
> Does this button have an event listener for `click` assigned, which is running some custom Javascript code? As I can see there is no page navigation happening after the click for about 200ms, which is kinda long:
> 
> > 1546059842927   Marionette  TRACE   0 -> [0,5,"WebDriver:ElementClick",{"id":"c4b3fc57-2825-4a4f-a16f-13249be49415"}]
> > 1546059843145   Marionette  DEBUG   [4294967297] Canceled page load listener because no navigation has been detected

I'm not using any JavaScript in the particular template so I can't think of any JS-related explanation for this. 

Here's the template code if you're interested:
```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome to Dibs!</title>
  </head>
  <body>
    <button id="register-college">
      <a href="{% url 'colleges:register-college' %}">
        Register Your College
      </a>
    </button>
    <button id="select-college">
      <a href="{% url 'colleges:select-college' %}">
        Log in
      </a>
    </button>
  </body>
</html>
```

Again, this code works perfectly fine with chromedriver 2.45.615279

**Comment by whimboo** [comment]
So there was a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1089326) which we had to implement a workaround for. As it looks like that didn't work that well in all the cases. But now that this bug is fixed in Firefox 66 (currently available as Nightly build) also Marionette/geckodriver works as expected. To test this you can grab a build at https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly.
