### ISSUE TITLE
Compile 32-bit Windows binaries

### ISSUE THREAD

**Issue by snowaid** [mozilla/geckodriver#146]
Would you be releasing the Windows 32-bit executable for v0.9.0? Thanks.

**Comment by andreastt** [comment]
Compiling a Windows 32-bit executable in Rust is currently a bit of a problem. You can see https://github.com/mozilla/geckodriver/pull/138 for more context.

32-bit OSes is a thing that IMO should die a slow and painful death, but I realise there might still be a somewhat significant portion of machines out there that have it installed. It would be good to get some data points on its current importance and trajectory. It would also be worth investigating if newer Rust version (1.10, beta, or nightly) has a better story for 32-bit Windows compilation.

**Comment by jgraham** [comment]
https://github.com/mozilla/geckodriver/pull/213
