### ISSUE TITLE
Is there a list for all status codes `geckodriver` might exit with?

### ISSUE THREAD

**Issue by emmi474** [mozilla/geckodriver#1460]
This is a general question. I don't have any errors right now. However, the regular error message

> geckodriver unexpectedly exited. Status code was: ...

ends with a status code number. Is there a list for all status codes `geckodriver` might exit with?

**Comment by andreastt** [comment]
The exit codes adhere losely to the BSD exit codes described in https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD%204.3-RELEASE&format=html.

**Comment by emmi474** [comment]
@andreastt Thanks for the reply :+1: However, I don't understand: why are exit codes not part of the geckodriver documentation?

**Comment by andreastt** [comment]
@finefoot We could absolutely document the exit codes in the documentation!

See https://searchfox.org/mozilla-central/rev/b4ebbe90ae4d0468fe6232bb4ce90699738c8125/testing/geckodriver/src/main.rs#55-59 for the currently used exit codes. We could document this on https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/, which would involve a change to testing/geckodriver/doc/ExitCodes.md or similar.

If you want to fix this, please file a bug and I can guide you through it.
