### ISSUE TITLE
Mozilla 64.0 element.click is not working on input type = file

### ISSUE THREAD

**Issue by iolesaberon** [mozilla/geckodriver#1463]
## System

* Version: 0.23.0
* Platform: Windows
* Firefox: 64.0
* Selenium: 3.8.1

## Testcase

public static void inputDataIntoWebElement(final WebElement targetElement, final String inputString) {

		if ((targetElement != null) && (inputString != null)) {
			try {
				targetElement.click();
				targetElement.clear();
				targetElement.sendKeys(inputString);
				UtilsUI.sleep(200);
				success = true;    }
}
}

## Stacktrace

Cannot click &lt;input type=file&gt; elements

**Comment by iolesaberon** [comment]
Added note: correct parameters are passed both targetelement and full path of the file + file name 
 it fails on the click event. this only started on the 64.0 update it was working on somewhere before xmas before the update happened

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Actually, please note that per the WebDriver specification a `click` is not allowed on file input element. So this makes this issue invalid.
