### ISSUE TITLE
allow pasting

### ISSUE THREAD

**Issue by sarulon** [mozilla/geckodriver#1466]
## System

* Version: geckodriver 0.23 32bit
* Platform: Windows 10 1803
* Firefox: 64.0
* Selenium: c# 3.141.0

## Testcase

running ExecuteScript() getting error because allow pasting in devtools console
is it possible to disable the allow pasting from the driver ?

**Comment by whimboo** [comment]
There is no minimized code example with an expected check, nor a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html). Even not sure what you are asking here.

In case you come back with the requested information we are happy to help. As of now I'm closing this issue.
