### ISSUE TITLE
geckodriver version for firefox 3.6.9 and selenium version

### ISSUE THREAD

**Issue by Drumering** [mozilla/geckodriver#1467]
Hello, I need to develop an automation using firefox in version 3.6.9. I can not find which driver I should use to communicate with the firefox of this version, and also, which version of selenium I should use. As far as I researched, something leads me to believe that I should use version 2.53.1 of selenium and use the wires 0.3.0 driver. Is this right?

**Comment by whimboo** [comment]
Not sure what you mean with `firefox in version 3.6.9`. There is no such version available, and the latest Firefox version is 64.0.

Also this is not a support forum but a bug tracker, as such you might want to use a different channel for the questions. But for a first start please check https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html.

**Comment by Drumering** [comment]
Right. Thank you for your help.

I'm sorry for the mistake.

Regarding the browser version. The system I need to test works only in this version of Firefox, 3.6.9. Therefore I need some driver to perform this action.

**Comment by whimboo** [comment]
Well, I don't understand why you need to test a system that tests an absolutely vulnerable browser version which is more than 9 years old. That shouldn't be used anymore. 

Also geckodriver doesn't work with such an old version of Firefox.

**Comment by Drumering** [comment]
I agree.

The system is very old, and many features do not work as they should in today's browsers. So the premise is that automation can interact with this version of the browser. Is there a driver that works with this version of Firefox?

**Comment by whimboo** [comment]
There was https://pypi.org/project/mozmill. But we don't offer any support for it anymore.

Lets close down this issue now. Thanks.

**Comment by Drumering** [comment]
Right!

Thanks a lot for the help! You're already a light at the end of the tunnel.
