### ISSUE TITLE
Won't update on Ubuntu

### ISSUE THREAD

**Issue by newenglandfall** [mozilla/geckodriver#1468]
geckodriver --version shows 0.20.1 but I have 0.23 installed and in my /usr/local/share/gecko_driver folder.

**Comment by whimboo** [comment]
Then you will have to look at your PATH environment variable which folder as listed earlier as `/usr/local/share/` also contains a geckodriver executable. Note that this will be always picked first by the system. It's not a geckodriver issue.

**Comment by andreastt** [comment]
Note that /usr/local/share is normally not path of the system path unless you make it so. You may have better luck putting it in /usr/local/bin/geckodriver, as this is—at least in bash(1)—included in the system path by default.

**Comment by newenglandfall** [comment]
There is no geckodriver executable in /usr/local/share/ or /usr/bin/..

**Comment by whimboo** [comment]
What does `echo $PATH` give as output?

**Comment by newenglandfall** [comment]
~/anaconda/bin:/home/doug/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/doug/.vimpkg/bin

**Comment by andreastt** [comment]
Right, so you either need to add /usr/local/share/gecko_driver to PATH, or move the geckodriver executable to one of the directories you just listed.

**Comment by newenglandfall** [comment]
Oh okay, thank you for your time. I apologize for the confusion.
