### ISSUE TITLE
Firefox crashes when using geckodriver inside of Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by hwine** [mozilla/geckodriver#1472]
## System

* Version: geckodriver 0.23.0 ( 2018-10-04)
* Platform: Linux 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
* Firefox: 59 & 64 (from ubuntu bionic)
* Selenium: 3.9.0

## Testcase

Won't start browser at all.

## Stacktrace

_non obtained_

## Trace-level log

https://gist.github.com/f7592f24ad78381b8194b8ae78c4fdae

# Additional information
``geckodriver`` had been working perfectly well in Ubuntu bionic in Windows Subsystem for Linux, until I installed the Windows Fall Update (to windows version 1809)

Note that Firefox itself continues to work, just not with ``geckodriver``.

In the pure windows environment, Firefox, ``geckodriver``, and selenium work fine.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by hwine** [comment]
trace log linked about

**Comment by whimboo** [comment]
@hwine, this is not a problem with geckodriver but Firefox. There is a content crash happening with the navigation to `https://github.com/login`:

> (firefox:20746): GConf-WARNING **: 11:38:29.037: Client failed to connect to the D-BUS daemon:
/usr/bin/dbus-launch terminated abnormally without any error message
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down

Please have a look at https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html in how to submit the crash details. It would be good to get this filed in Bugzilla. Please let me know about it. Thanks!

**Comment by hwine** [comment]
So, it only occurs when firefox is driven by geckodriver in WSL. I.e. there may be an interaction issue, but it "used" to work, and Firefox works (manually).

My interest is in having something work. Let me see if I can pin down what versions of geckodriver and Firefox worked (that solves my need), and gives you a shot at tracking down the change that broke this use case.

Otherwise, let's close this as "invalid" -- my initial goal was just to give a head's up to any other WSL user, and that's been achieved.

**Comment by whimboo** [comment]
Oh, that's interesting. So a regression range would clearly help. Also I would be still interested to see the crash details, so we can get this filed on Bugzilla.

**Comment by hwine** [comment]
Just to set expectations, this is a script I run once a month, so it may be a while before I have another update.

**Comment by whimboo** [comment]
Thanks for letting us know. We will keep the issue open, and let us revisit once you run the script again. If you could run it manually earlier, it would be appreciated.

**Comment by whimboo** [comment]
There might have been a startup crash related to IPC or whatever which got fixed in Firefox 66 beta, or 67 Nightly. As such I think we are fine here, and don't have to investigate further. If it happens again with a later version of Firefox feel free to reopen the issue.
