### ISSUE TITLE
geckodriver hung after interact with prompt

### ISSUE THREAD

**Issue by kovalev007** [mozilla/geckodriver#1474]
## System

* Version: geckodriver-v0.23.0-win64
* Platform: windows 10 and windows server
* Firefox: 64.0.2 (64-bit)
* Selenium: 3.141.59 for java

## Testcase

FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("dom.disable_beforeunload", false);
FirefoxOptions options = new FirefoxOptions();
options.setProfile(profile);
options.setUnhandledPromptBehaviour(UnexpectedAlertBehaviour.IGNORE);
options.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
options.setCapability(CapabilityType.UNHANDLED_PROMPT_BEHAVIOUR, UnexpectedAlertBehaviour.IGNORE);
.....
webDriver.switchTo().alert().accept();
.....

1) open new window
2) close new window
3) before close window - show prompt from beforeunload event
4) click accept in prompt
5) new window was closed but java code hung and not go next.
6) close firefox browser manualy.

## Stacktrace

1547627157003	Marionette	TRACE	0 -> [0,248,"WebDriver:AcceptDialog",{}]
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:750:13

## Trace-level log

[hublog_full.txt](https://github.com/mozilla/geckodriver/files/2763334/hublog_full.txt)
[nodelog_small.txt](https://github.com/mozilla/geckodriver/files/2763335/nodelog_small.txt)
[geckodriver_small.log](https://github.com/mozilla/geckodriver/files/2763336/geckodriver_small.log)

**Comment by whimboo** [comment]
Please note that disabling `dom.disable_beforeunload` is currently not supported. See also your filed issue here: https://github.com/w3c/webdriver/issues/1294

Can you please try the latest Firefox Nightly build if that works better?

**Comment by kovalev007** [comment]
Firefox Nightly 66.0a1 (2019-01-15) (64-bit) works good. Thanks.

geckodriver.log
1547634619484	Marionette	DEBUG	0 -> [0,262,"WebDriver:AcceptDialog",{}]
1547634619491	Marionette	TRACE	Received DOM event DOMModalDialogClosed for [object ChromeWindow]
1547634619492	Marionette	DEBUG	0 <- [1,262,null,{"value":null}]
1547634619492	webdriver::server	DEBUG	<- 200 OK {"value":null}

**Comment by whimboo** [comment]
Good to hear. I believe that was fixed with my patches on https://bugzilla.mozilla.org/show_bug.cgi?id=1504756.
