### ISSUE TITLE
JavaScript: Wrong size for type statvfs, followed by org.openqa.selenium.WebDriverException: connection refused

### ISSUE THREAD

**Issue by walde-k** [mozilla/geckodriver#1479]
## System

* Version: geckodriver 0.19.1
* Platform: Linux SLES 12 SP3 , arch s390x, kernel: '4.4.162-94.72-default', java.version: '1.8.0_151'
* Firefox: 60.4.0
* Selenium: version: '3.141.59', revision: 'e82be7d358'

## Testcase

Running Selenium test with headless Mozilla Firefox and geckodriver 

## Stacktrace

11:43:28 1547808207958	geckodriver	INFO	geckodriver 0.19.1
11:43:28 1547808207973	geckodriver	INFO	Listening on 127.0.0.1:28167
11:43:28 1547808208146	mozrunner::runner	INFO	Running command: "/usr/lib64/firefox/firefox" "-marionette" "-headless" "-profile" "/tmp/rust_mozprofile.2Fl2QO7bckvb"
11:43:28 *** You are running in headless mode.
11:43:29 JavaScript error: resource://gre/modules/workers/require.js line 141 > Function line 3 > eval, line 933: Error: Error: Wrong size for type statvfs: expected 88, found 96 (ctypes.StructType("statvfs", [{ "padding_0": ctypes.uint8_t.array(4) }, { "f_frsize": ctypes.int64_t }, { "padding_1": ctypes.uint8_t.array(12) }, { "f_bavail": ctypes.uint64_t }, { "padding_2": ctypes.uint8_t.array(56) }]))
11:43:32 console.error: "Could not write session state file " (new Error("_initWorker called too early! Please read the session file from disk first.", "resource:///modules/sessionstore/SessionFile.jsm", 337)) "_initWorker/<@resource:///modules/sessionstore/SessionFile.jsm:337:15\n_initWorker@resource:///modules/sessionstore/SessionFile.jsm:330:12\n_postToWorker@resource:///modules/sessionstore/SessionFile.jsm:354:11\nwrite@resource:///modules/sessionstore/SessionFile.jsm:394:19\nwrite@resource:///modules/sessionstore/SessionFile.jsm:66:12\n_writeState@resource:///modules/sessionstore/SessionSaver.jsm:357:12\n_saveState@resource:///modules/sessionstore/SessionSaver.jsm:295:12\n_saveStateAsync@resource:///modules/sessionstore/SessionSaver.jsm:341:5\nsaveStateAsyncWhenIdle@resource:///modules/sessionstore/SessionSaver.jsm:192:9\n"
11:44:28 2019-01-18 11:44:28 [FATAL] [e.wss.guitest.WifeGuiTest] Decoding 1: org.openqa.selenium.WebDriverException: connection refused
11:44:28 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:44:28 Driver info: driver.version: FirefoxDriver
11:44:28 remote stacktrace: 
11:44:28 org.openqa.selenium.WebDriverException: connection refused
11:44:28 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
11:44:28 Driver info: driver.version: FirefoxDriver
.....

FULL LOG IN ATTACHMENT
[geckotrace.txt](https://github.com/mozilla/geckodriver/files/2778697/geckotrace.txt)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? It would be good to know what's actually going on.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
