### ISSUE TITLE
Property mismatch FirefoxDriver vs. MarionetteDriver capabilities

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#148]
Dear geckodriver team,

we have invested a lot into automation infrastructure and frameworks using Selenium. While I'm very much in favor of having a dedicated Driver like geckodriver, I have found some differences in the properties of FirefoxDriver and MarionetteDriver although at then end they are ment to execute on the same browser, namely Firefox!

Some differences are as follows:
- FirefoxDriver returns for the property **_browserName_** the value **_firefox_** while MarionetteDriver returns **_Firefox_**!
  While this looks uncritical in the first glance, it made our framework to not work, as it was case sensitive and it took us some while to find the root cause.
- FirefoxDriver returns the version by the property named **_version_** while MarionetteDriver returns the same information by the property named **_browserVersion_**!
  Again, while this looks uncritical in the first glance, it made our framework behave strange, as it was operating on this information and now it was missing.

Is there some deeper meaning about this change in properties or would it be possible to provide properties in a compatible way with MarionetteDriver?

Best regards
mgavilan

**Comment by AutomatedTester** [comment]
There appears to be a bug here for us not lowercasing the `browserName` property. I have raised https://bugzilla.mozilla.org/show_bug.cgi?id=1288863

As for `version` this was changed in the [webdriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) and we should return [capabilities](http://w3c.github.io/webdriver/webdriver-spec.html#capabilities) like that.

**Comment by AutomatedTester** [comment]
I have submitted a patch for bug 1288863 and hopefully will be landed next week.

**Comment by andreastt** [comment]
We are now returning `browserName`, `browserVersion`, `platformName`, and `platformVersion`. https://bugzilla.mozilla.org/show_bug.cgi?id=1288863 fixes the lowercasing of `firefox` and is available in Firefox 49 onwards.

Considering this resolved.
