### ISSUE TITLE
WebdriverJs cannot connect to exist seleniumSessionId

### ISSUE THREAD

**Issue by tfaron** [mozilla/geckodriver#1481]
## System

* Version: geckodriver-v0.23.0
* Platform: Windows 10
* Firefox: 64.0.2 (64-bit) but tried older version like 62

"protractor": "~5.4.1"

using webDriverJs I started the webdriver and then created a firefox session.
In protractor conf.js I added seleniumSessionId to use the existing session

  `seleniumAddress` 'http://127.0.0.1:4444/wd/hub',
  seleniumSessionId: '95fab773-92b2-43e8-8416-23496a53b5e6',
  directConnect: false,
  capabilities: { browserName: 'firefox', marionette: true },`

When i execute protractor the follow error occurs:
`C:\svt-web-client\projects\client-ng\node_modules\.bin>protractor C:\svt-web-client\projects\client-ng\protractor.e2e.atf.conf.js --grep "C763889_OMNI_33968_2" -
[13:30:09] I/launcher - Running 1 instances of WebDriver
[13:30:09] I/attachSession - Using the selenium server at http://127.0.0.1:4444/wd/hub
[13:30:09] I/attachSession - Using session id - 95fab773-92b2-43e8-8416-23496a53b5e6
[13:30:09] E/launcher - GET /session/95fab773-92b2-43e8-8416-23496a53b5e6 did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WIN-73R0N5SIS5K', ip: '10.0.111.195', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: unknown
[13:30:09] E/launcher - UnsupportedOperationError: GET /session/95fab773-92b2-43e8-8416-23496a53b5e6 did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'WIN-73R0N5SIS5K', ip: '10.0.111.195', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_191'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.attachToSession()
    at Function.attachToSession (C:\svt-web-client\projects\client-ng\node_modules\selenium-webdriver\lib\webdriver.js:695:24)
    at AttachSession.getNewDriver (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\driverProviders\attachSession.js:37:58)
    at Runner.createBrowser (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\svt-web-client\projects\client-ng\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:834:54)
    at C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (C:\svt-web-client\projects\client-ng\node_modules\protractor\node_modules\q\q.js:125:13)
[13:30:09] E/launcher - Process exited with error code 199`

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by tfaron** [comment]
I created the firefox session with the following command:
curl http://16.100.206.160:4444/wd/hub/session -d
'{"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":
{"log": {"level": "trace"}}}}' --noproxy "*"
{
  "status": 0,
  "sessionId": "f99e6368-2c20-4f1c-a4aa-8e82996891a0",
  "value": {
    "acceptInsecureCerts": false,
    "browserName": "firefox",
    "browserVersion": "60.0.2",
    "moz:accessibilityChecks": false,
    "moz:geckodriverVersion": "0.23.0",
    "moz:headless": false,
    "moz:processID": 4136,
    "moz:profile":
"C:\\Users\\Administrator\\AppData\\Local\\Temp\\rust_mozprofile.1lAT8bhXRIlV",
    "moz:useNonSpecCompliantPointerOrigin": false,
    "moz:webdriverClick": true,
    "pageLoadStrategy": "normal",
    "platformName": "windows_nt",
    "platformVersion": "10.0",
    "rotatable": false,
    "timeouts": {
      "implicit": 0,
      "pageLoad": 300000,
      "script": 30000
    },
    "webdriver.remote.sessionid": "f99e6368-2c20-4f1c-a4aa-8e82996891a0"
  }

I also added it to the protractor.conf file but I am not seeing any
additional logging when I try to run using an existing session. Is there a
log file anywhere?
I am also not sure why the log setting is not show in the value hash above

**Comment by tfaron** [comment]
I was able to see some logging when starting the session: 
`
C:\svt-web-client\projects\client-ng>npm run webdriver-start

> hpe-simplivity-web-client@1.0.0 webdriver-start C:\svt-web-client\projects\client-ng
> webdriver-manager start

[17:29:32] I/start - java -Dwebdriver.chrome.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\chromedriver_2.45.exe -Dwebdriver.gecko.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\geckodriver-v0.23.0.exe -jar C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar -port 4444
[17:29:32] I/start - seleniumProcess.pid: 3508
17:29:32.964 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
17:29:33.104 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-01-24 17:29:33.182:INFO::main: Logging initialized @588ms to org.seleniumhq.jetty9.util.log.StdErrLog
17:29:33.526 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
17:29:33.745 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
17:29:52.933 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "moz:firefoxOptions": {
    "log": {
      "level": "trace"
    }
  }
}
17:29:52.933 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1548372593917   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofile.7CWQB9vqrXZA"
1548372593917   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:59757
1548372594422   Marionette      DEBUG   Received observer notification profile-after-change
1548372594557   Marionette      DEBUG   Received observer notification command-line-startup
1548372594557   Marionette      DEBUG   Received observer notification nsPref:changed
1548372596035   Marionette      DEBUG   Received observer notification sessionstore-windows-restored
1548372596155   Marionette      DEBUG   Setting recommended pref apz.content_response_timeout to 60000
1548372596155   Marionette      DEBUG   Setting recommended pref browser.download.panel.shown to true
1548372596156   Marionette      DEBUG   Setting recommended pref browser.EULA.override to true
1548372596156   Marionette      DEBUG   Setting recommended pref browser.offline to false
1548372596156   Marionette      DEBUG   Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1548372596157   Marionette      DEBUG   Setting recommended pref browser.search.update to false
1548372596157   Marionette      DEBUG   Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1548372596158   Marionette      DEBUG   Setting recommended pref browser.tabs.disableBackgroundZombification to false
1548372596158   Marionette      DEBUG   Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1548372596158   Marionette      DEBUG   Setting recommended pref browser.tabs.warnOnOpen to false
1548372596159   Marionette      DEBUG   Setting recommended pref browser.usedOnWindows10.introURL to
1548372596159   Marionette      DEBUG   Setting recommended pref browser.urlbar.suggest.searches to false
1548372596159   Marionette      DEBUG   Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1548372596160   Marionette      DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1548372596160   Marionette      DEBUG   Setting recommended pref dom.disable_open_during_load to false
1548372596160   Marionette      DEBUG   Setting recommended pref dom.file.createInChild to true
1548372596160   Marionette      DEBUG   Setting recommended pref dom.max_chrome_script_run_time to 0
1548372596161   Marionette      DEBUG   Setting recommended pref dom.max_script_run_time to 0
1548372596161   Marionette      DEBUG   Setting recommended pref extensions.getAddons.cache.enabled to false
1548372596161   Marionette      DEBUG   Setting recommended pref extensions.shield-recipe-client.api_url to
1548372596161   Marionette      DEBUG   Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1548372596161   Marionette      DEBUG   Setting recommended pref network.http.prompt-temp-redirect to false
1548372596161   Marionette      DEBUG   Setting recommended pref network.http.speculative-parallel-limit to 0
1548372596162   Marionette      DEBUG   Setting recommended pref security.fileuri.strict_origin_policy to false
1548372596162   Marionette      DEBUG   Setting recommended pref security.notification_enable_delay to 0
1548372596163   Marionette      DEBUG   Setting recommended pref signon.autofillForms to false
1548372596163   Marionette      DEBUG   Setting recommended pref signon.rememberSignons to false
1548372596235   Marionette      DEBUG   New connections are accepted
1548372596236   Marionette      INFO    Listening on port 59757
1548372596729   geckodriver::marionette DEBUG   Connection established on 127.0.0.1:59757. Waiting for Marionette handshake
1548372596741   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:59773
1548372596729   geckodriver::marionette DEBUG   Connected to Marionette
1548372596742   Marionette      TRACE   0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox"}]
1548372596926   Marionette      DEBUG   Register listener.js for window 4294967297
17:29:56.964 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
1548372596931   Marionette      TRACE   0 <- [1,1,null,{"sessionId":"ae2aebfe-b674-451d-82e2-dc5c4241b981","capabilities":{"browserName":"firefox","browserVersion":"60.0. ... AppData\\Local\\Temp\\rust_mozprofile.7CWQB9vqrXZA","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1548372596917   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"ae2aebfe-b674-451d-82e2-dc5c4241b981","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"60.0.2","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":false,"moz:processID":7648,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\rust_mozprofile.7CWQB9vqrXZA","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
17:29:57.058 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session ae2aebfe-b674-451d-82e2-dc5c4241b981 (org.openqa.selenium.firefox.GeckoDriverService)
1548372687698   webdriver::server       DEBUG   -> GET /session/ae2aebfe-b674-451d-82e2-dc5c4241b981
1548372687698   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /session/ae2aebfe-b674-451d-82e2-dc5c4241b981 did not match a known command","stacktrace":""}}`

However when I try to run protractor attaching to this session nothing new is logged .. i just get the return I initially posted above

**Comment by tfaron** [comment]
I started the session and then tried to connect to it.
As you can see when I attempt to connect to it the get fails. I am able to do the same workflow with Chrome successfully

`
C:\svt-web-client\projects\client-ng>npm run webdriver-start

> hpe-simplivity-web-client@1.0.0 webdriver-start C:\svt-web-client\projects\client-ng
> webdriver-manager start

[19:05:03] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[19:05:03] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[19:05:04] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[19:05:05] I/start - java -Dwebdriver.chrome.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\chromedriver_2.45.exe -Dwebdriver.gecko.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\geckodriver-v0.23.0.exe -jar C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar -port 4444
[19:05:05] I/start - seleniumProcess.pid: 2240
19:05:05.430 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
19:05:05.570 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-01-24 19:05:05.664:INFO::main: Logging initialized @606ms to org.seleniumhq.jetty9.util.log.StdErrLog
19:05:06.008 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
19:05:06.226 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
19:05:15.586 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "firefox",
  "marionette": true,
  "moz:firefoxOptions": {
    "log": {
      "level": "trace"
    }
  }
}
19:05:15.601 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1548378316617   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofile.Og9GpA9J0LSo"
1548378316617   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:60167
1548378317118   Marionette      DEBUG   Received observer notification profile-after-change
1548378317241   Marionette      DEBUG   Received observer notification command-line-startup
1548378317241   Marionette      DEBUG   Received observer notification nsPref:changed
1548378318871   Marionette      DEBUG   Received observer notification sessionstore-windows-restored
1548378319053   Marionette      DEBUG   Setting recommended pref apz.content_response_timeout to 60000
1548378319055   Marionette      DEBUG   Setting recommended pref browser.download.panel.shown to true
1548378319056   Marionette      DEBUG   Setting recommended pref browser.EULA.override to true
1548378319056   Marionette      DEBUG   Setting recommended pref browser.offline to false
1548378319056   Marionette      DEBUG   Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1548378319056   Marionette      DEBUG   Setting recommended pref browser.search.update to false
1548378319057   Marionette      DEBUG   Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1548378319057   Marionette      DEBUG   Setting recommended pref browser.tabs.disableBackgroundZombification to false
1548378319057   Marionette      DEBUG   Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1548378319058   Marionette      DEBUG   Setting recommended pref browser.tabs.warnOnOpen to false
1548378319058   Marionette      DEBUG   Setting recommended pref browser.usedOnWindows10.introURL to
1548378319058   Marionette      DEBUG   Setting recommended pref browser.urlbar.suggest.searches to false
1548378319058   Marionette      DEBUG   Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1548378319058   Marionette      DEBUG   Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1548378319058   Marionette      DEBUG   Setting recommended pref dom.disable_open_during_load to false
1548378319058   Marionette      DEBUG   Setting recommended pref dom.file.createInChild to true
1548378319059   Marionette      DEBUG   Setting recommended pref dom.max_chrome_script_run_time to 0
1548378319059   Marionette      DEBUG   Setting recommended pref dom.max_script_run_time to 0
1548378319059   Marionette      DEBUG   Setting recommended pref extensions.getAddons.cache.enabled to false
1548378319059   Marionette      DEBUG   Setting recommended pref extensions.shield-recipe-client.api_url to
1548378319059   Marionette      DEBUG   Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1548378319060   Marionette      DEBUG   Setting recommended pref network.http.prompt-temp-redirect to false
1548378319060   Marionette      DEBUG   Setting recommended pref network.http.speculative-parallel-limit to 0
1548378319060   Marionette      DEBUG   Setting recommended pref security.fileuri.strict_origin_policy to false
1548378319060   Marionette      DEBUG   Setting recommended pref security.notification_enable_delay to 0
1548378319060   Marionette      DEBUG   Setting recommended pref signon.autofillForms to false
1548378319060   Marionette      DEBUG   Setting recommended pref signon.rememberSignons to false
1548378319115   Marionette      DEBUG   New connections are accepted
1548378319116   Marionette      INFO    Listening on port 60167
1548378319398   geckodriver::marionette DEBUG   Connection established on 127.0.0.1:60167. Waiting for Marionette handshake
1548378319420   Marionette      DEBUG   Accepted connection 0 from 127.0.0.1:60178
1548378319414   geckodriver::marionette DEBUG   Connected to Marionette
1548378319426   Marionette      TRACE   0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox"}]
1548378319578   Marionette      DEBUG   Register listener.js for window 4294967297
19:05:19.617 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
1548378319591   Marionette      TRACE   0 <- [1,1,null,{"sessionId":"37a84d31-6258-4a95-83df-71636be0486b","capabilities":{"browserName":"firefox","browserVersion":"60.0. ... AppData\\Local\\Temp\\rust_mozprofile.Og9GpA9J0LSo","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
19:05:19.742 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 37a84d31-6258-4a95-83df-71636be0486b (org.openqa.selenium.firefox.GeckoDriverService)
1548378319586   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"37a84d31-6258-4a95-83df-71636be0486b","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"60.0.2","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":false,"moz:processID":8340,"moz:profile":"C:\\Users\\Administrator\\AppData\\Local\\Temp\\rust_mozprofile.Og9GpA9J0LSo","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1548378361023   webdriver::server       DEBUG   -> GET /session/37a84d31-6258-4a95-83df-71636be0486b
1548378361023   webdriver::server       DEBUG   <- 404 Not Found {"value":{"error":"unknown command","message":"GET /session/37a84d31-6258-4a95-83df-71636be0486b did not match a known command","stacktrace":""}}
`

**Comment by whimboo** [comment]
When you are trying to re-use the formerly used session the following command is getting sent by Protractor:

> 1548378361023 webdriver::server DEBUG -> GET /session/37a84d31-6258-4a95-83df-71636be0486b
1548378361023 webdriver::server DEBUG <- 404 Not Found {"value":{"error":"unknown command","message":"GET /session/37a84d31-6258-4a95-83df-71636be0486b did not match a known command","stacktrace":""}}

As you can see this is a `GET` request to the session end-point, which is not supported per the WebDriver spec: https://w3c.github.io/webdriver/#endpoints. Only a `DELETE` request is allowed.

If chromedriver works in this case you might not run it in `w3c` compatible mode. But if you do it would be a bug in its implementation.

As conclusion this is a bug in Protractor, and you should file an issue there.
