### ISSUE TITLE
send_keys fails to fill the text field which dynamically changes it's attributes

### ISSUE THREAD

**Issue by yavorek** [mozilla/geckodriver#1482]
## System

* Version: geckodriver 0.23.0 
* Platform: Linux debianVIR 4.9.0-6-amd64
* Firefox: 64.0.2 (also on *60.0.2)
* Selenium: 3.141.0

## Testcase
Sending keys 'Aa1234567' to a field, which changes it's class attributes after typing first character. (field type is password)
Also validation field under input appears at the same time.

## Stacktrace

Only 'A' is typed in text field.
Issue is also visible while typing: "Password" or "ACa1234567' or '123' or 'password'. Only first character is typed.
In non password fields issue is not visible. In password field without validation appearing after first character issue is not visible.

*In version 60.0.2 all characters except 'a' was typed in a field (Aa1234567). 

## Trace-level log

Look for "//input[@id='confirmPassword'" or "//input[@id='password']". (in "//div[@class='auth-container']//input[@id='password']" is working correctly - password without validation after first character).

[geckodriver.log](https://github.com/mozilla/geckodriver/files/2795448/geckodriver.log)

**Comment by whimboo** [comment]
You will have to provide a minimal HTML testcase which demonstrates that problem. Also it's not clear which class attributes are changing here.

**Comment by yavorek** [comment]
Before typing:
```
<input type="password" class="form-control ng-pristine ng-isolate-scope ng-empty ng-valid-password-confirmation ng-invalid ng-invalid-required ng-touched" id="confirmPassword" name="confirmPassword" password-confirmation="vm.password" ng-required="true" ng-model="vm.confirmPassword" required="required">
<my-messages control="$ctrl.form.confirmPassword" class="ng-isolate-scope"/>
```

After typing first character:
```
<input type="password" class="form-control ng-isolate-scope ng-invalid ng-touched ng-dirty ng-valid-parse ng-not-empty ng-invalid-password-confirmation ng-valid-required" id="confirmPassword" name="confirmPassword" password-confirmation="vm.password" ng-required="true" ng-model="vm.confirmPassword" required="required" style="">
<my-messages control="$ctrl.form.confirmPassword" class="ng-isolate-scope">
    <div ng-if="$ctrl.control.$invalid &amp;&amp; $ctrl.shouldValidate()" class="ng-scope">
        <ng-transclude>
            <my-message type="required" class="ng-scope ng-isolate-scope"/>
            <my-message type="passwordConfirmation" class="ng-scope ng-isolate-scope">
                <div class="mlc-validation-message ng-scope" ng-if="$ctrl.isAttached()">
                    <ng-transclude>
                        <span class="ng-scope">Passwords do not match.</span>
                    </ng-transclude>
               </div>
            </my-message>
        </ng-transclude>
    </div>
</my-messages>
```

**Comment by whimboo** [comment]
Does it work with validation turned off? I wonder if the Javascript code behind the scenes here is interfering with the input. I cannot reproduce it with a normal password textbox.

**Comment by yavorek** [comment]
With normal password text field (no validation checking after first character) issue is not visible.

**Comment by whimboo** [comment]
So you will have to provide a minimal HTML testcase including the validation function. Otherwise there is nothing we can do, because we don't know what states of the text field or the tab is getting modified.

**Comment by yavorek** [comment]
Issue is not reproducible with simple HTML without node app, which I cannot provide.

To close/deny.

**Comment by whimboo** [comment]
Thanks for your feedback. As such some registered event handler for the password field in React should be causing this problem.
