### ISSUE TITLE
Invalid host permission: resource://pdf.js/

### ISSUE THREAD

**Issue by wadimov** [mozilla/geckodriver#1483]
## System

* Version:  v.0.23.0
* Platform: Win7
* Firefox:  Firefox Quantum, 64.0.2
* Selenium: v.3

## Testcase
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

public class VerifyPageTitle {
	public WebDriver driver; 	
	@Test
	public void pageTitle() {		
		driver = new FirefoxDriver();
		driver.get("http://gmail.com");		
		String pageTitle = driver.getTitle();
		Assert.assertEquals(pageTitle, "Gmail");
		driver.close();
	}

## Stacktrace
[RemoteTestNG] detected TestNG version 6.14.2
1548439290673	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\VADIM~1.KOU\\AppData\\Local\\Temp\\rust_mozprofile.rWd0KjBo1keQ"
1548439292797	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1548439292797	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1548439300496	Marionette	INFO	Listening on port 42813
1548439300915	Marionette	WARN	TLS certificate errors will be ignored for this session
Jan 25, 2019 1:01:41 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1548439312919	Marionette	INFO	Stopped listening on port 42813
[Child 6528, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6528, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 9464, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, [Plairneent 6324, Gec k34o_IOThrea6d] WAR
NING: file z:/build/build/src/ipc/chromium/src/base/proc[eCss_util_win.cc, line 188
hild 9464, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6584, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 6584, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
PASSED: pageTitle
===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 0
===============================================
[GPU 2128, Chrome_ChildThread] WARNING: pipe error: 109: file z:/b

**Comment by wadimov** [comment]
I am new to Seleneuim, so I can not figur out why running this simple program as TestNG giving me those warnings, despite the test is executed successfully.

**Comment by whimboo** [comment]
It's a warning coming from Firefox. It doesn't affect your test at all, as you can see by the results. Otherwise see issue #1046 for having too many log lines.

**Comment by whimboo** [comment]
@mlgiter why do you think that? There error you are referring to is actually a warning and again has nothing to do if sessions cannot be created. Also this issue is closed, and if you cannot get it working file a new one with ALL the requested information included. This also applies to a trace log. Without it there is nothing we can do.
