### ISSUE TITLE
Geckodriver hangs when highlighting output in terminal

### ISSUE THREAD

**Issue by curtisy1** [mozilla/geckodriver#1485]
## System
* Version: 0.23.0
* Platform: Windows 10 Version 1803
* Firefox: 67 Nightly [Buildconfig](https://hg.mozilla.org/mozilla-central/rev/d305772af471766618393c01065556e739738e84)
* Selenium: .NET v3.141.0

## Testcase
See https://curtisy1.github.io/demo/indexof

Test:
```
    [Test]
    public void TestCase() {
      Browser.Driver.Navigate().GoToUrl("https://curtisy1.github.io/demo/indexof");
      var listOfParagraphs = Browser.Driver.FindElements(By.CssSelector("label"));
      var paragraphWithClassIndex = 0;

      foreach (var paragraph in listOfParagraphs) {
        if (paragraph.FindElement(By.XPath("../p")).GetAttribute("class").Contains("faildemo")) {
          paragraphWithClassIndex = listOfParagraphs.IndexOf(paragraph);
          break;
        }
      }

      Assert.That(paragraphWithClassIndex == 2);
    }
```

## Stacktrace
OpenQA.Selenium.WebDriverException: 'The HTTP request to the remote WebDriver server for URL http://localhost:55575/session timed out after 60 seconds.'

## Trace-level log
```
1548758684854   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Firefox Nightly\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\OBERLA~1\\AppData\\Local\\Temp\\rust_mozprofile.krRRRRzWtRvZ"
1548758684864   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:55580
```

## Description
This is a rather weird issue admittedly.
When debugging the above test (or any other) on Windows and opening a command prompt for logging, once something in the command prompt is highlighted manually, geckodriver seems to hang endlessly. If I press Ctrl + C, the hang stops and the test continues normally, until I highlight something again.

**Comment by jgraham** [comment]
This appears to be the expected behaviour of the Windows command prompt; if you highlight some text it will suspend the process when it next tries to write to stdout in order to preserve the selection c.f. https://superuser.com/questions/459609/what-does-it-do-exactly-if-i-click-in-the-window-of-cmd
