### ISSUE TITLE
Selenium throwing an error but, the script is working fine. 

### ISSUE THREAD

**Issue by josephpissac** [mozilla/geckodriver#1487]
Hello @whimboo, I am a beginner and I am facing a issue while automating a website that Script is running fine but in eclipse its showing Below given warning message,

1548929878813	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\josep\\AppData\\Local\\Temp\\rust_mozprofile.2dfONdCj9fhY"
1548929881361	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1548929881362	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
1548929897742	Marionette	INFO	Listening on port 49853
[Child 6864, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1548929898202	Marionette	WARN	TLS certificate errors will be ignored for this session
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd64 v= and igd10iumd64 v=
Jan 31, 2019 3:48:18 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

Please check the attached file for code.

[Code.txt](https://github.com/mozilla/geckodriver/files/2816649/Code.txt)

**Comment by josephpissac** [comment]
Hello @whimboo ...Please check attached file, I hope this will help you to understand the issue properly.

[Trace.txt](https://github.com/mozilla/geckodriver/files/2816794/Trace.txt)

**Comment by josephpissac** [comment]
Waiting For your response @whimboo .

**Comment by whimboo** [comment]
The attached tracelog actually doesn't show a problem with creating a session, as what this bug was filed for. But interestingly the log stopped at right shortly after a click was peformed. What did happen at this time?

**Comment by josephpissac** [comment]
Actually I have performed "Click Action" on login option of my website and the script is working fine and the its redirecting me to login page.

**Comment by whimboo** [comment]
So can you create a trace of the original problem?

**Comment by josephpissac** [comment]
> So can you create a trace of the original problem?

Can you help me in this?

**Comment by whimboo** [comment]
Sorry but I cannot. If the original issue is intermittent only, you might have to run your test multiple times until the correct situation has been captured.

**Comment by josephpissac** [comment]
I tried but I am unable to trace it, Anyways Thanks For your Kind Support @whimboo ........!!!

**Comment by whimboo** [comment]
Ok, if it happens again and you can catch the problem feel free to reopen the issue.
