### ISSUE TITLE
The latest version of Geckodriver v0.24.0 is being caught in Norton Antivirus

### ISSUE THREAD

**Issue by Rajagopalan-M** [mozilla/geckodriver#1489]
## System

* Version: <v0.24.0>
* Platform: 

I started using the latest version of Geckodriver, Norton anti virus is catching that as a virus and it's asking me allow. Once I allow it, it runs fine. This happens only in 0.24.0, It's not happening in 0.23.0. Hope you have added something new which Norton antivirus is detecting as virus?

**Comment by andreastt** [comment]
Please report it as a false positive to Norton. There is unfortunately little else we can do about this, except maybe digitally signing the binary (tracked in https://github.com/mozilla/geckodriver/issues/1116).
