### ISSUE TITLE
Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start

### ISSUE THREAD

**Issue by shaileshsingh9214** [mozilla/geckodriver#1490]
## System

* Version: 3.141.59
* Platform: Win10
* Firefox: 65
* Selenium: 3.141.59+java 10

## Testcase

public void testFireFox() {
//	System.setProperty("webdriver.firefox.marionette","D:\\Soft\\geckodriver.exe");
	File gecko = new File("D:\\Soft\\geckodriver.exe");    
	System.setProperty("webdriver.firefox.marionette", gecko.getAbsolutePath());
	WebDriver driver = new FirefoxDriver();
	//System.setProperty("webdriver.chrome.driver","G:\\chromedriver.exe");
	//WebDriver driver = new ChromeDriver();
    String baseUrl = "https://www.google.com";
    String expectedTitle = "Assesshub Admin";
    String actualTitle = "";
    driver.navigate().to(baseUrl);
    actualTitle = driver.getTitle();
    if (actualTitle.contentEquals(expectedTitle)){
        System.out.println("Test Passed!");
    } else {
        System.out.println("Test Failed");
    }
    driver.quit();
}
## Stacktrace

Exception in thread "main" org.openqa.selenium.WebDriverException: Timed out waiting 45 seconds for Firefox to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'OPTIMIZEQ-LTP03', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '10.0.2'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:247)
	at org.openqa.selenium.firefox.XpiDriverService.start(XpiDriverService.java:159)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at demo.selDemo.FireFoxDemo.testFireFox(FireFoxDemo.java:14)
	at demo.selDemo.App.main(App.java:13)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:27460/hub/status] to be available after 45002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.firefox.XpiDriverService.waitUntilAvailable(XpiDriverService.java:245)
	... 9 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 10 more

## Trace-level log

Nothing

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by shaileshsingh9214** [comment]
Thanks for link and guideline. I have got this much logs and don't know how much useful it is pleae let me know if i can improve

1549352809051	addons.xpi-utils	WARN	addMetadata: Add-on fxdriver@googlecode.com is invalid: Error: File C:\Users\shailesh.singh\AppData\Local\Temp\anonymous13831252165963459015webdriver-profile\extensions\fxdriver@googlecode.com.xpi does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:557:11) JS Stack trace: loadManifest@XPIInstall.jsm:557:11
awaitPromise@XPIProvider.jsm:188:3
syncLoadManifestFromFile@XPIInstall.jsm:620:10
addMetadata@XPIDatabase.jsm:2334:21
processFileChanges@XPIDatabase.jsm:2686:21
checkForChanges@XPIProvider.jsm:2581:34
startup@XPIProvider.jsm:2159:25
callProvider@AddonManager.jsm:203:12
_startProvider@AddonManager.jsm:652:5
startup@AddonManager.jsm:805:9
startup@AddonManager.jsm:2775:5
observe@addonManager.js:66:9
1549352809176	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1549352809176	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1549352809350	addons.xpi-utils	WARN	Disabling foreign installed add-on {4ED1F68A-5463-4931-9384-8FFF5ED91D92} in winreg-app-global
JavaScript error: resource://gre/modules/addons/XPIProvider.jsm, line 2625: TypeError: addon is null

**Comment by shaileshsingh9214** [comment]
hi there was configuration issue
tried after removing all extensions and cleared history and disabled legacy code to false and it worked with both of the drivers


1. webdriver.firefox.marionette

2. webdriver.geco.driver

thanks for speedy help close this issue

**Comment by shaileshsingh9214** [comment]
For code/case study please refer

public void test() throws FileNotFoundException, IOException {
	File gecko = new File("D:\\Soft\\geckodriver-v0.24.0-win64\\geckodriver.exe");  
	File logFile=new File("D:\\temp\\logs.txt");
	logFile.mkdirs();
	//System.setProperty("webdriver.firefox.marionette", gecko.getAbsolutePath());
	System.setProperty("webdriver.geco.driver", gecko.getAbsolutePath());
	System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE,"true");
	System.setProperty(FirefoxDriver.SystemProperty.BROWSER_LOGFILE,logFile.getAbsolutePath());
	
	LoggingPreferences pref = new LoggingPreferences();
    pref.enable(LogType.BROWSER, Level.FINEST);
    pref.enable(LogType.CLIENT, Level.FINEST);
    pref.enable(LogType.DRIVER, Level.FINEST);
    pref.enable(LogType.PERFORMANCE, Level.FINEST);
    pref.enable(LogType.PROFILER, Level.FINEST);
    pref.enable(LogType.SERVER, Level.FINEST);
	
	DesiredCapabilities capabilities=DesiredCapabilities.firefox();
    capabilities.setCapability("marionette", true);
    capabilities.setCapability(CapabilityType.LOGGING_PREFS, pref);
    FirefoxOptions options =  new FirefoxOptions(capabilities);
    options.setLogLevel(FirefoxDriverLogLevel.TRACE);
//    options.setLegacy(true);
    String baseUrl = "https://www.google.com";
    String expectedTitle = "Admin";
    String actualTitle = "";
    WebDriver driver=new FirefoxDriver(options);
    driver.manage().timeouts().implicitlyWait(50, TimeUnit.SECONDS);
    driver.navigate().to(baseUrl);
    actualTitle = driver.getTitle();
    if (actualTitle.contentEquals(expectedTitle)){
        System.out.println("Test Passed!");
    } else {
        System.out.println("Test Failed");
    }
    driver.quit();
}
