### ISSUE TITLE
Changelog typo for version 0.24

### ISSUE THREAD

**Issue by wKich** [mozilla/geckodriver#1494]
Title for version 0.24 has incorrect date `0.24.0 [917474f3473e] (2018-01-28)`
https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md#7

**Comment by andreastt** [comment]
How is the date wrong?

**Comment by wKich** [comment]
Because 0.23 is out 2018-10-03

**Comment by andreastt** [comment]
Ah, the _year_ is wrong. It took me a while to spot that. (-:

Thanks for reporting. I’ve fixed it in https://bugzilla.mozilla.org/show_bug.cgi?id=1525544.
