### ISSUE TITLE
Endpoint not found `POST /session/{session_id}/window/new`

### ISSUE THREAD

**Issue by catalandavid** [mozilla/geckodriver#1497]
(https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md, states that NewWindow endpoint has been implemented for geckodriver 0.24.0)

## System

* Version: 0.24.0 (2019-01-28)
* Platform: macOS 10.12.6
* Firefox: 65.0
* Selenium: Geckodriver directly, no Selenium server involved

## Testcase

1. Start geckodriver

```
./geckodriver --port 4444 -vv
```

2. Execute commands

```
curl -v -d '{"capabilities":{"firstMatch":[{"browserName":"firefox"}]}}' http://localhost:4444/session
```

Firefox opens and request returns

```
{"value":{"sessionId":"ecc297d1-352a-a947-a2ef-97b3f1c806a8","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"65.0","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.24.0","moz:headless":false,"moz:processID":59463,"moz:profile":"/var/folders/2d/gdlw59w54ds5_n_yfn8nx6580000gn/T/rust_mozprofile.DVQbjuNmuJkb","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"16.7.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
```

Note the `sessionId`, here `ecc297d1-352a-a947-a2ef-97b3f1c806a8`, then

```
curl -v -d '{"type":"window"}' http://localhost:4444/session/ecc297d1-352a-a947-a2ef-97b3f1c806a8/window/new
```

returns 404 Not Found

```
{"value":{"error":"unknown error","message":"WebDriver:NewWindow","stacktrace":"WebDriverError@chrome://marionette/content/error.js:179:5\nUnknownCommandError@chrome://marionette/content/error.js:473:5\ndespatch@chrome://marionette/content/server.js:283:13\nexecute@chrome://marionette/content/server.js:264:11\nonPacket/<@chrome://marionette/content/server.js:237:15\nonPacket@chrome://marionette/content/server.js:236:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:490:9\n"}}
```

## Stacktrace

See attachment below

**Comment by catalandavid** [comment]
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2844367/geckodriver.log)

**Comment by whimboo** [comment]
You are using `"browserVersion":"65.0"`. As the release notes of geckodriver states this is support by Firefox 66 and later.

**Comment by catalandavid** [comment]
Ah I missed this information. Can you point me to the link where this is documented?

**Comment by whimboo** [comment]
What do you mean where this is documented? The implementation for Marionette happened at least on https://bugzilla.mozilla.org/show_bug.cgi?id=1504756.

**Comment by catalandavid** [comment]
Ok I see, thanks for the link.
As mentioned in the description, I referred to https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md to consider this a bug as nothing points there that it's supported starting with version 66.0

**Comment by whimboo** [comment]
Oh, now I see. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1527083 to get this fixed.
