### ISSUE TITLE
Hang when trying to navigate to a URL containing a fragment

### ISSUE THREAD

**Issue by FrankBorland** [mozilla/geckodriver#150]
Firefox 48.0b7
Geckodriver 0.9.0
Selenium 2.53.0

```
MarionetteDriver driver = new MarionetteDriver();
String urlWithAnchor = "https://www.w3.org/TR/html4/struct/links.html#h-12.1";
driver.navigate().to(urlWithAnchor);
driver.navigate().to(urlWithAnchor); // hang
```

The second navigate call does not return.

**Comment by andreastt** [comment]
I filed [bug 1287766](https://bugzilla.mozilla.org/show_bug.cgi?id=1287766).

**Comment by whimboo** [comment]
Which is actually already covered by [bug 1280300](https://bugzilla.mozilla.org/show_bug.cgi?id=1280300)

**Comment by andreastt** [comment]
This has now landed in central. We will uplift it soon.
