### ISSUE TITLE
Unable to npm install geckodriver

### ISSUE THREAD

**Issue by whuey1992** [mozilla/geckodriver#1504]
I just tried to build a project and npm install was unable to find geckodriver. I tried doing "npm install geckodriver" and it isn't working. Please help this is causing builds to fail because it is a dependency.

**Comment by whuey1992** [comment]
Sorry I thought this was the github for the npm version as well, just saw there is already an issue for it in the npm github

**Comment by whimboo** [comment]
Dupe of #1505.
