### ISSUE TITLE
npm install geckodriver failing

### ISSUE THREAD

**Issue by nayeemd** [mozilla/geckodriver#1505]
## System

* Version: v0.24.0
* Platform: Mac,Linux and windows
* Firefox: -
* Selenium: --

## Testcase
npm install is failing on jenkins pipeline and local machine.
`npm install geckodriver`

## Trace-level log
npm ERR! path /work/git/app/node_modules/geckodriver/bin/geckodriver
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/work/git/app/node_modules/geckodriver/bin/geckodriver'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by andreastt** [comment]
This is not the repo for the npm package of geckodriver.
