### ISSUE TITLE
Can not set whole string value into the text field

### ISSUE THREAD

**Issue by DmitriyKapeliukh** [mozilla/geckodriver#1506]
## System

* Version: <0.24.0>
* Platform: <MacOS 10.14.3 >
* Firefox: <65.0>
* Selenium: <Serenity 2.0.27>

## Testcase

Firefox into some text field could not type the whole string.
e.g.
Steps:
`driver.sendkeys("Jhon")`

Expected:
driver set "Jhon" value into browser text field

Actual:
driver set only last char ("n") from the value

P.S.
If I evaluate javascript "arguments[0].value='Jhon';", the value seted successfully.

## Stacktrace

[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - FINISHING STEP
1550499803428	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:196:64
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:188:13

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by DmitriyKapeliukh** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html).

[geckodriver.log](https://github.com/mozilla/geckodriver/files/2900715/geckodriver.log)

Hi. Logs attached.

**Comment by whimboo** [comment]
Nothing in that log uses the `ElementSendKeys` command, but I can see a lot of Javascript code which gets executed. Maybe the client is doing it's own send keys. As such this looks like a client / binding problem, but not related to geckodriver.
