### ISSUE TITLE
geckodriver not displaying .exe in link

### ISSUE THREAD

**Issue by ashariff27** [mozilla/geckodriver#1509]
## System

* Version: <v0.24.0>
* Platform: <Windows 10>
* Firefox: <Quantum 65.0.1, 64 bit>
* Selenium: <3.141.59>

I downloaded the appropriate gecko driver from the github link.  I extracted then inserted the path link into my code and received the following error:

![geckodrivererror](https://user-images.githubusercontent.com/44793111/53136372-64668780-3544-11e9-8ed3-4a0a5d29cfeb.PNG)

Can someone help me resolve the error? I don't know why, but when I copy and paste the link location after extracting the file, the geckodriver.exe doesn't show up at the end.

**Comment by whimboo** [comment]
You didn't specify the full path to the geckodriver binary but to it's directory. This can also be seen when inspecting the failure message.

**Comment by ashariff27** [comment]
I know that, but how do I do that?  Because I've done exactly what every other video instructed me to do, and for whatever reason, I'm not able to get the full path: 

![screenshot 9](https://user-images.githubusercontent.com/44793111/53171619-e4bed400-35a8-11e9-9f2b-f7132e3f5b09.png)

Now, in anticipation of other questions, I've gone ahead and opened the geckodriver file.  Notice, at the title bar is what looks like the path I need for the code:

![image](https://user-images.githubusercontent.com/44793111/53171861-82b29e80-35a9-11e9-95f1-add1a18cee67.png)

In noticing that, I had two ideas, both of which failed and displayed the same error.  The first was to type out the path from the title bar into Eclipse:

![image](https://user-images.githubusercontent.com/44793111/53172072-0bc9d580-35aa-11e9-9212-6591dd57dbeb.png)

The other idea was to add \geckodriver.exe to the end of the path that I copied and pasted:

![image](https://user-images.githubusercontent.com/44793111/53172546-34060400-35ab-11e9-9135-5fbcb03991cc.png)

I hope this helps.  Please look over and advise.

**Comment by ashariff27** [comment]
Still doesn't work:

![image](https://user-images.githubusercontent.com/44793111/53173188-c8bd3180-35ac-11e9-934c-40f41a0279bf.png)

**Comment by ashariff27** [comment]
I tried changing the path, but the same error was raised.

**Comment by trinidad8516** [comment]
> Still doesn't work:
> 
> ![image](https://user-images.githubusercontent.com/44793111/53173188-c8bd3180-35ac-11e9-934c-40f41a0279bf.png)

System.setProperty("webdriver.gecko.driver", "C:\\Users\\ALiLLiNOiS\\Mozilla Driver\\geckodriver.exe")

**Comment by ashariff27** [comment]
@trinidad8516 You are a G.  I appreciate you

**Comment by trinidad8516** [comment]
@ashariff27 it depends in the programming language, when you construct the String there are characters that special. Here is a good example of those "[Special Characters](http://www.informit.com/articles/article.aspx?p=30241&seqNum=3l)" <-Link
