### ISSUE TITLE
'Connection refused' error and empty URL after Firefox launching

### ISSUE THREAD

**Issue by alesvyat** [mozilla/geckodriver#1511]
## System

* Version: 0.24.0 (64-bit)
* Platform: Windows 10 1703 (Build 15063.674)
* Firefox: 65.0.1 (64-bit)
* Selenium: 3.8.0 and 3.14.0
* PHP: 7.1 and 7.2

## Testcase
When I launch automated tests via Codeception, Firefox launches but it doesn't navigate to needed URL and tests crash with 'connection refused' error.

## Stacktrace

```
Facebook\WebDriver\Exception\UnknownServerException : connection refused
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'ZZI110143', ip: '172.22.64.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: driver.version: unknown
remote stacktrace: 
 C:\TestAutomation\testing_FirefoxClean\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114
 C:\TestAutomation\testing_FirefoxClean\vendor\facebook\webdriver\lib\Remote\HttpCommandExecutor.php:326
 C:\TestAutomation\testing_FirefoxClean\vendor\facebook\webdriver\lib\Remote\RemoteWebDriver.php:126
 C:\TestAutomation\testing_FirefoxClean\vendor\symfony\event-dispatcher\EventDispatcher.php:212
 C:\TestAutomation\testing_FirefoxClean\vendor\symfony\event-dispatcher\EventDispatcher.php:44
 C:\Users\SvyatkinAV\AppData\Local\Temp\ide-codeception.php:40
```

## Trace-level log
[trace.log](https://github.com/mozilla/geckodriver/files/2909632/trace.log)

## Notes
1. In the same environment, tests execute successfully with ChromeDriver
2. The same issue with x32 utilities
3. These tests sucessfully execute in another PC. This PC has the same Windows 10 1703 (but build number is little bit different), Selenium, Firefox and geckodriver versions
4. I also tried Firefox 60.0 - the same problem

**Comment by dharmendra-qait** [comment]
I am facing same issue  but without any connection refused.
* Version: 0.24.0 (64-bit)
* Platform: Ubuntu 18.04.2 LTS
* Firefox: 65.0.1 (64-bit)
* Selenium: 3.14.0.

StackTrace:
```
[RemoteTestNG] detected TestNG version 6.14.3

===============================================
FirefoxSuite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 1
===============================================

```

**Comment by whimboo** [comment]
@alesvyat does the same thing happen with an older Firefox release or a recent beta or nightly? The latter two versions could be downloaded from https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by dharmendra-qait** [comment]
@whimboo 
For me it's happening on downgrading as per this chart https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html .

**Comment by alesvyat** [comment]
@whimboo,

Results are below:
1. Older Firefox (58.0) - doesn't works with initial failure
2. Recent beta release (66.0b1) - doesn't works with initial failure
3. Last nightly release (67.0a1 2019-02-27) - works

All checks executed with WebDriver 3.8.0. Related trace-level logs attached.
[ffe_58.0_trace.log](https://github.com/mozilla/geckodriver/files/2914438/ffe_58.0_trace.log)
[ffe_beta_stacktrace.log](https://github.com/mozilla/geckodriver/files/2914439/ffe_beta_stacktrace.log)
[ffe_nightly_trace.log](https://github.com/mozilla/geckodriver/files/2914440/ffe_nightly_trace.log)


Well, is it possible to make Firefox autotestable for official releases in my case, not for nightly only? :-)

**Comment by whimboo** [comment]
@alesvyat please note that Selenium versions below 3.11 are not supported since Firefox version 57, and geckodriver 0.21.0. Can you please upgrade to the latest version, and run the checks again?

**Comment by alesvyat** [comment]
@whimboo,

The same issue with Selenium 3.14.0 and 3.141.59. Tests work with nightly build but don't work with 58 and beta. Logs attached.
[ffe3.141.59_beta_trace.txt](https://github.com/mozilla/geckodriver/files/2960354/ffe3.141.59_beta_trace.txt)

[ffe3.14.0_58.0_trace.txt](https://github.com/mozilla/geckodriver/files/2960351/ffe3.14.0_58.0_trace.txt)
[ffe3.14.0_beta_trace.txt](https://github.com/mozilla/geckodriver/files/2960352/ffe3.14.0_beta_trace.txt)
[ffe3.141.59_58.0_trace.txt](https://github.com/mozilla/geckodriver/files/2960353/ffe3.141.59_58.0_trace.txt)

**Comment by whimboo** [comment]
Interesting. Mind downloading the https://www.mozilla.org/en-US/firefox/developer/ edition of Firefox? It's the 67b1 release, which is built on code similar to the latest Nightly build of Firefox. Does it work for you with that release?

If not I'm wondering about the trash in the log around the time when it starts to fail. For example see your first attached log nearly at the end. Maybe running WireShark or a similar tool might be a good idea to find out what's causing those problems.

**Comment by alesvyat** [comment]
@whimboo,

LOL, I've found out that firefox directory changing fixes my issue. After I re-installed the browser to "C:\Program Files\Mozilla Firefox 2" (note, standard path is "C:\Program Files\Mozilla Firefox"), my tests started to work.
Some kind of magic...

Tracelog attached (maybe you will need it).
[ffe.relocation_trace.log](https://github.com/mozilla/geckodriver/files/2988922/ffe.relocation_trace.log)

Thanks Henrik for your assistance! If you need some additional info from me, feel free to ask.

**Comment by whimboo** [comment]
Maybe this was a broken Firefox installation. Good to hear that it works now.
