### ISSUE TITLE
Firefox Errors on console and thread id not printing

### ISSUE THREAD

**Issue by sudarsan-gouni** [mozilla/geckodriver#1513]
[log.txt](https://github.com/mozilla/geckodriver/files/2913666/log.txt)
## System

* Version: v0.24.0
* Platform: Windows + 64 bit
* Firefox: 65.0.1
* Selenium: 3.141.59

## Stacktrace

1551333899166	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\SGouni1\\AppData\\Local\\Temp\\rust_mozprofile.v4Wtbr1A27wF"
1551333902493	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1551333902494	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1551333907172	Marionette	INFO	Listening on port 56741
1551333907611	Marionette	WARN	TLS certificate errors will be ignored for this session
Feb 28, 2019 11:35:07 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1551333912790	Marionette	INFO	Stopped listening on port 56741
[Parent 27108, Gecko_IOThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332
[Child 30560, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 332

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

## Trace-level log

FF Browser launched successfully but seeing the error on console and thread id also not printing

Code:
	@Test
	public void getFirefox() {
		System.setProperty("webdriver.gecko.driver", currentDir + "\\drivers\\geckodriver.exe");  
		System.out.println("Chrome running on this thread:" + Thread.currentThread().getId());
		WebDriver driver = new FirefoxDriver();
		driver.get("https://www.anntaylor.com");
		driver.close();
	}

**Comment by andreastt** [comment]
Sorry, what is the actual problem?

**Comment by whimboo** [comment]
Any printing to the console like by using `System.out.println()` is part of your Selenium client. As such this is the wrong issue tracker which is geckodriver only.
