### ISSUE TITLE
arm7hf build

### ISSUE THREAD

**Issue by corbolais** [mozilla/geckodriver#1515]
Hello,

Thanks for your efforts in the new release!

One thing I'm missing is the armhf binary package! Where can I find it now? Why isn't it there any more?

cheers

**Comment by andreastt** [comment]
We announced our intention to not ship ARMv7 HF builds of geckodriver back in September 2018: https://lists.mozilla.org/pipermail/tools-marionette/2018-September/000035.html

You can still self-service a build through compiling yourself. I hope this helps.

**Comment by legut2** [comment]
Any instructions somewhere on how to build it ourselves? I might eventually need it.

**Comment by andreastt** [comment]
It depends on your environment, but the normal Rust build approach using `cargo build` should work fine if you compile directly on the ARM system itself.

To cross compile from another system you will first need to install the target toolchain with [rustup](armv7-unknown-linux-gnueabihf) and then specify this when building, like this:

    rustup target install armv7-unknown-linux-gnueabihf
    cargo build --target armv7-unknown-linux-gnueabihf

I hope this helps.

**Comment by andreastt** [comment]
The relevant system dependencies you need for cross-compilation are:

- gcc-arm-linux-gnueabihf
- libc6-armhf-cross
- libc6-dev-armhf-cross

**Comment by corbolais** [comment]
Here's how to run this on Ubuntu. Tested w/ Ubuntu 18.10:

[Good source of information for x-compiling with rust.](https://github.com/~/rust-cross)

Cross-compile geckodriver for **arm7hf**:
  * install x-compiler: `apt install gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross`
  * install rust: `curl https://sh.rustup.rs -sSf | sh`
  * either create a new shell or:  `source $HOME/.cargo/env`
  * install x-compile target: `rustup target install armv7-unknown-linux-gnueabihf`
  * without this step, linker stage will fail: 
```
cat >>~/.cargo/config <<EOF
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
EOF

```
  * Build it: `cargo build --release --target armv7-unknown-linux-gnueabihf`

HTH

**Comment by andreastt** [comment]
@corbolais Thanks!

I’ve put this documentation in central now: https://bugzilla.mozilla.org/show_bug.cgi?id=1532344

It should appear on https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html fairly soon.

**Comment by noloader** [comment]
> You can still self-service a build through compiling yourself. I hope this helps.

You should do two things. First, state that you are not providing binaries in [README.md](https://github.com/mozilla/geckodriver/blob/master/README.md). Second, provide the instructions to build the ARM binaries in the [README.md](https://github.com/mozilla/geckodriver/blob/master/README.md).

It is amazing how much time is wasted on tasks like this. It took me two hours to come across this report, which lead to the mailing list message. If every developer wastes 4 hours on this task, then 10's of thousands of man hours are wasted because of lack documentation.

**Comment by noloader** [comment]
@corbolais,

Thanks for the info. I know nothing about cargo or rust. When I attempt to follow your instructions (they were placed in a script):

```
~$ ./build-geckodriver.sh
info: downloading installer
error: it looks like you have an existing installation of Rust at:
error: /usr/bin
error: rustup cannot be installed alongside Rust. Please uninstall first
error: if this is what you want, restart the installation with `-y'
error: cannot install while Rust is installed
Failed to download rustup
```

Any ideas?

**Comment by corbolais** [comment]
@noloader Good point about the suboptimal docs.

@noloader Got your compile fixed already? You should:

error: rustup cannot be installed alongside Rust. **Please uninstall first**

Because:
```
error: it looks like you have an existing installation of Rust at:
error: /usr/bin
error: rustup cannot be installed alongside Rust. Please uninstall first
error: if this is what you want, restart the installation with `-y'
error: cannot install while Rust is installed
```

HTH

**Comment by andreastt** [comment]
Yes, the README does appear to be missing a direct link to [_Self-servicing an ARM build_](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html). But I should point out there _is_ documentation.

There is a lot more developer-centric documentation available at https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html#for-developers, but I suppose we could link to most of this from the Table of Contents in the README.

rustup is an environment tool used for managing Rust compilers and toolchains. If rustc is already present on the system, say in /usr/bin, it would compete with the rustc installed and managed by rustup in $HOME/.rustup. I should point out that rustup is technically not a requirement for cross-compilation, but it does make it significantly easier to get the right cross-compilation development environment set up.

If you uninstall your system rustc, then follow the steps in [_Self-servicing an ARM build_](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html), does that fix the build for you?

**Comment by andreastt** [comment]
I’ve updated the README (in [bug 1543946](https://bugzilla.mozilla.org/show_bug.cgi?id=1543946)) with direct links to the developer documentation, including the article on [_Self-serving an ARM build_](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html).

**Comment by corbolais** [comment]
@andreastt Thanks, very helpful.

Now, if the wording was something clearer like: 
**ARM users need to build their own binary, here's how** 
it would be even nicer! :)

cheers
