### ISSUE TITLE
Selenium Side Runner Error:  SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

### ISSUE THREAD

**Issue by patriciasimonep** [mozilla/geckodriver#1516]
Referencing to below issue and resolution. Is it possible to run selenium side runner headless without the installing browser or the executable? Just pure running it in a non graphical user environment?

"This means it can’t find the Firefox installation on your system. On Windows it looks in the Windows Registry for the installation path, and on Linux it looks in your system path for a `firefox` executable.

If you have Firefox installed in a non-default location which is not in your system’s search path, you can specify a `binary` field on the `moz:firefoxOptions` capabilities object (documented in README), or use the `--binary PATH` flag passed to geckodriver when it starts."

_Originally posted by @andreastt in https://github.com/mozilla/geckodriver/issues/1344#issuecomment-410963704_

**Comment by patriciasimonep** [comment]
I am trying to run my ide test thru selenium side runner on linux environment for both Chrome and Firefox, I keep getting similar error. 

Firefox error:
SessionNotCreatedError: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

Chrome error:
WebDriverError: unknown error: cannot find Chrome binary
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 3.10.0-957.1.3.el7.x86_64 x86_64)

Linux environment doesnt have any browser installed, and would it still possible to run headless tests without it?If not, do you have any recommendation on this requirement?Your input would be greatly appreciated and helpful. Thank you

**Comment by corbolais** [comment]
@patriciasimonep using geckodriver in headless mode will run the browser without graphical UI.

```
options = webdriver.FirefoxOptions()
options.add_argument('--headless')
try:
  driver = webdriver.Firefox(firefox_options=options)
except:
  pass
```

**Comment by patriciasimonep** [comment]
> @patriciasimonep using geckodriver in headless mode will run the browser without graphical UI.
> 
> ```
> options = webdriver.FirefoxOptions()
> options.add_argument('--headless')
> try:
>   driver = webdriver.Firefox(firefox_options=options)
> except:
>   pass
> ```
Thank you for reply. but im using the ide tests run thru selenium side runner like this.
**selenium-side-runner -c "browserName=firefox moz:firefoxOptions.args=[-headless]" MDMNextUITests.side** and it gave me output of binary error. So i would want to know if i can run it without really installing any browser

**Comment by corbolais** [comment]
I don't think you can use geckodriver w/o a browser binary. Basically, that's what the geckodriver is talking to as a webdriver-marionette proxy. If there's no "dummy mode" in geckodriver there's not much you can do without having a browser installed. I'm not aware of such a mode.

**Comment by whimboo** [comment]
This is not an issue tracker for selenium clients but for geckodriver only. And as it looks like this is clearly not a geckodriver related issue. So please open a support ticket with the appropriate client.
