### ISSUE TITLE
When running as a Windows service the GFX sanity window doesn't close

### ISSUE THREAD

**Issue by psicopep** [mozilla/geckodriver#1518]
## System

* Version: 0.24.0
* Platform: Windows Server 2016
* Firefox: 65.0.1
* Selenium: Python Client version 3.141.0,  Server version 3.141.59

## Testcase

Webdriver fails to start a Firefox instance when running as a Windows service. It works fine when running as a foreground process.
It also works fine with older versions, we recently made a big jump from 59 to 65 and we found this issue at that moment. Versions prior and including 59 work fine running as service. Analysis on which particular version between 59 and 65 made the affecting change is still pending.

## Stacktrace

[stacktrace.log](https://github.com/mozilla/geckodriver/files/2943500/stacktrace.log)

## Trace-level log

Attached two for failure when running as service and success when running as a foreground process:
[service.log](https://github.com/mozilla/geckodriver/files/2943499/service.log)
[foreground.log](https://github.com/mozilla/geckodriver/files/2943498/foreground.log)

**Comment by andreastt** [comment]
geckodriver cannot be run as a Windows service, I’m afraid.

**Comment by psicopep** [comment]
Oh, I was kind of expecting that. It was pure luck with an unsupported usage these past years, then. Now I'll have to fight security teams about autologon users again :-D
Ok, thanks for the quick response @andreastt :-)

**Comment by psicopep** [comment]
Closing issue as usage is unsupported.

**Comment by andreastt** [comment]
Note that you can prevent the Firefox application from opening by using [headless mode](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode). You can achieve this effect by setting the `MOZ_HEADLESS=1` environment variable or by passing the `--headless` flag to Firefox.

You can see an example of doing that through WebDriver and `moz:firefoxOptions` on MDN: https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#args

I hope this helps!

**Comment by psicopep** [comment]
Oh, this is actually using headless mode, but thanks anyway :-)

**Comment by whimboo** [comment]
The underlying problem here is that there is the GFX sanity window which Marionette waits for until it has been closed. But that never happens, and the connection times out after 60s. See the following line:

> 1551993036506	Marionette	TRACE	GFX sanity window detected, waiting until it has been closed...

@psicopep, I would be really interested since which version of Firefox this problem can be seen. As best also test the beta releases which should bring us closer to the underlying change. Thanks a lot in advance!

**Comment by psicopep** [comment]
Hi @whimboo :-) Thanks for your interest in this. I will try to make that analysis this weekend and I'll let you know :-)

**Comment by whimboo** [comment]
Thanks! Btw. are you on Windows 32-bit or 64-bit?

**Comment by psicopep** [comment]
Hi @whimboo :-) Sorry for the delay. I narrowed this down to the following:

- Version 59.0.3 is last to work fine when running as a service.
- Version 60.0b3 is the first to fail but this does not show the GFX message.
- Version 62.0b3 is the first to fail showing the GFX message.

Regarding the platform, this was using a 64-bit Windows, more specifically a Windows Server 2016.

[59.0.3.log](https://github.com/mozilla/geckodriver/files/2963647/59.0.3.log)
[60b3.log](https://github.com/mozilla/geckodriver/files/2963648/60b3.log)
[62b3.log](https://github.com/mozilla/geckodriver/files/2963649/62b3.log)

**Comment by whimboo** [comment]
Can you please also try the 60.0b1 and 60.0b2 builds as can be found here?

https://archive.mozilla.org/pub/devedition/releases/

How long is the GFX window open with 62.0b3? Until Firefox gets killed by geckodriver? When that happens do you see any errors in the browser/web console?

**Comment by psicopep** [comment]
Hi @whimboo :-) Sorry again for the (bigger) delay. I'm attaching below the logs for 60.0b1 and 60.0b2. Turns out 60.0b2 is the first to fail. 60.0b1 was still working fine.

Regarding the GFX window, I'm afraid this Windows is virtualized and VirtualBox doesn't seem to support keyboard/mouse input in the session 0 desktop, so I can't look into the browser console or move the window to check if there is another window behind it.
Having said that, I couldn't see any GFX window whatsoever.

[60b1.log](https://github.com/mozilla/geckodriver/files/3024559/60b1.log)
[60b2.log](https://github.com/mozilla/geckodriver/files/3024560/60b2.log)

**Comment by whimboo** [comment]
Sorry for the late reply. Somehow I missed this comment. But nevertheless it is really interesting! So here is the link to all the changes which went into the 60.0b2 release:

https://hg.mozilla.org/releases/mozilla-beta/pushloghtml?fromchange=a1098c825a9c5e07f03ec4ad7a760c868bf20d75&tochange=0938d48917b73d31fa8bfa4a7c3ccd79a3f4b3f5

Given that this is a huge list, would you mind helping to bisect this list? If yes we would have to find the appropriate builds which span from March 2nd to March 7th. To do that maybe start with March 5th and follow those steps:

1) Open https://tools.taskcluster.net/index/gecko.v2.mozilla-beta.nightly.2019.03.05.latest.devedition/win64-opt
2) Download the `target.zip` which can be found in the list of files on the right side
3) Unzip and use it with your test to verify

If that fails, go to March 3rd etc by just adjusting the URL above to `2019.03.03`. Once you have a single day left, go to the one where the failure happens (eg.3rd) and open:

https://tools.taskcluster.net/index/gecko.v2.mozilla-beta.nightly.2019.03.03.revision

Go through all the revisions and then please tell me for which of those it started to happen.

Thanks!

**Comment by Aprngp** [comment]
I am getting similar issue. 
Below is what I am using 

Selenium version: 3.141.59
Geckodriver version: 0.24.0
Firefox version: 68.0.1

Below is my trace log

1564429722811	mozrunner::runner	INFO	Running command: "firefox/app/firefox.exe" "-marionette" "-headless" "-disable-gpu" "-foreground" "-no-remote" "-profile" "C:\\Users\\SVC_QL~1\\AppData\\Local\\Temp\\rust_mozprofile.GGqhApQEXBEK"
1564429722827	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:50486
*** You are running in headless mode.
1564429723803	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1564429723803	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1564429723803	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1564429723803	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1564429723988	Marionette	TRACE	Received observer notification profile-after-change
1564429724063	Marionette	TRACE	Received observer notification toplevel-window-ready
1564429724111	Marionette	TRACE	Received observer notification command-line-startup
1564429724112	Marionette	TRACE	Received observer notification nsPref:changed
1564429724112	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1564429724322	Marionette	TRACE	Received observer notification toplevel-window-ready
1564429726491	Marionette	TRACE	Received observer notification marionette-startup-requested
1564429726492	Marionette	TRACE	GFX sanity window detected, waiting until it has been closed...
1564429783733	mozrunner::runner	DEBUG	Killing process 12580
1564429783733	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}

Works fine if I login to the server and run the process, but fails when triggered through remote console.

**Comment by whimboo** [comment]
@Aprngp can you please check https://github.com/mozilla/geckodriver/issues/1518#issuecomment-472620114 and try the two builds? Does the regression happen between the same versions for you? If yes, please also check my last comment, and if time permits I would appreciate if you could do a regression test so that we finally know since when it happens.

**Comment by Aprngp** [comment]
With `profile.setPreference("sanity-test.running", true);`  I don't see Waiting for GFX sanity window message, but firefox doesn't start and it gets stuck. 

Below is trace log --

```
1564430502025	mozrunner::runner	INFO	Running command: "firefox/app/firefox.exe" "-marionette" "-headless" "-disable-gpu" "-foreground" "-no-remote" "-profile" "C:\\Users\\SVC_QL~1\\AppData\\Local\\Temp\\rust_mozprofile.VtaLGrmnmsOe"
1564430502041	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:50641
*** You are running in headless mode.
1564430502905	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1564430502905	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1564430502906	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1564430502906	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1564430503068	Marionette	TRACE	Received observer notification profile-after-change
1564430503152	Marionette	TRACE	Received observer notification command-line-startup
1564430503152	Marionette	TRACE	Received observer notification nsPref:changed
1564430503152	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1564430503340	Marionette	TRACE	Received observer notification toplevel-window-ready
1564430505181	Marionette	TRACE	Received observer notification marionette-startup-requested
1564430505182	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1564430505200	Marionette	TRACE	All scripts recorded.
1564430505200	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1564430505200	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1564430505201	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1564430505201	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1564430505202	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1564430505202	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1564430505202	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1564430505202	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1564430505202	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1564430505203	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1564430505204	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1564430505204	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1564430505204	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1564430505204	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1564430505204	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1564430505204	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1564430505205	Marionette	DEBUG	Setting recommended pref security.certerrors.mitm.priming.enabled to false
1564430505205	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1564430505205	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1564430505205	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1564430505275	Marionette	INFO	Listening on port 50641
1564430505275	Marionette	DEBUG	Remote service is active
1564430505338	geckodriver::marionette	DEBUG	Connection established on 127.0.0.1:50641. Waiting for Marionette handshake
1564430505349	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:50646
1564430505338	geckodriver::marionette	DEBUG	Connected to Marionette
1564430505354	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1564430505355	Marionette	WARN	TLS certificate errors will be ignored for this session
```

**Comment by Aprngp** [comment]
https://archive.mozilla.org/pub/devedition/releases/62.0b3/win64/en-US/ contains setup exe, unfortunately I am not able to install anything on server, is there a zip which I can extract and use. 

Also I am unable to open https://tools.taskcluster.net/index/gecko.v2.mozilla-beta.nightly.2019.03.05.latest.devedition/win64-opt somehow this seems blocked my proxy of my organization.

**Comment by Aprngp** [comment]
I tried firefox zip from here https://archive.mozilla.org/pub/devedition/candidates/60.0b1-candidates/build2/win64/en-US/ but again it failed with below trace ---

```
1564502314591	mozrunner::runner	INFO	Running command: "firefox-60.0b1/firefox/firefox.exe" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\SVC_QL~1\\AppData\\Local\\Temp\\rust_mozprofile.ImnxPq3FNvlo"
1564502314607	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:65070
*** You are running in headless mode.
1564502315552	Marionette	DEBUG	Received observer notification profile-after-change
Unable to read VR Path Registry from C:\Users\<user id>\AppData\Local\openvr\openvrpaths.vrpath
1564502315694	Marionette	DEBUG	Received observer notification command-line-startup
1564502315694	Marionette	DEBUG	Received observer notification nsPref:changed
1564502317348	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1564502375482	mozrunner::runner	DEBUG	Killing process 10092
1564502375529	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
```

**Comment by whimboo** [comment]
@Aprngp this might be a different issue. How does the trace for 60.0b2 look like? I assume for 60.0b1 the GFX window didn't come-up, right?

**Comment by whimboo** [comment]
As the recently duped issue shows the regression might have already happened earlier. At least for some people. Means it could all be related to the graphics card in use, or the drivers. As such the best thing we could do is to stop opening it at all.

Means I or someone else will have to take a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1420864#c9, so that the window isn't getting opened at all.

**Comment by whimboo** [comment]
@psicopep and @Aprngp could you please test a nightly build of geckodriver and check if anything has changed for you? I [landed a patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1572687) yesterday and I'm hoping that you won't see the window anymore.

You can get it by navigating to this [Taskcluster job](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&searchStr=geckodriver%2Csign&selectedJob=261479882) and downloading the signed zip file. Thanks!

**Comment by psicopep** [comment]
Hi @whimboo :-)
Thanks a lot for keeping this up. I'm very sorry for the lack of response on my part. I'm having very tough weeks lately. Hopefully @Aprngp can give a quicker response, but nevertheless I will try to take a look at this on the weekend.

**Comment by psicopep** [comment]
Hi @whimboo :-)
Sorry again for the big delay in this.
I tried the zip file attached to the mentioned job and few more in subsequent jobs but all of them are throwing an Application Error with code 0xc000007b. I don't know if I'm missing something.
Is there an alternative build I could try or something I'm doing wrong?

**Comment by whimboo** [comment]
Please note that in the meantime I had to backout my patch, and get it reimplemented with a different approach. I won't have the time to do that in the near future but will let you all know here once it's available. Sorry for the inconvenience.

**Comment by DimitarTarkalanovMentorMate** [comment]
I have observed the same behavior on:
os.name: 'Windows Server 2012 R2'
os.version: '6.3'
firefox version: 62+

It appears that GFX sanity windows comes up, but never closes. This is preventing the initialization of the FirefoxDriver. The issue will be resolved with firefox version 70 until then the workaround is to execute the tests in headless mode.

**Comment by whimboo** [comment]
Starting with todays Firefox Nightly we will no longer run the GFX sanity check. So this will not be a problem anymore.
