### ISSUE TITLE
UnhandledPromiseRejectionWarning: WebDriverError: Failed to interpret value as array

### ISSUE THREAD

**Issue by Ch84** [mozilla/geckodriver#1519]
## System

* Geckodriver Version: 0.24.0
* Platform: Windows 10 17134.590
* Firefox: 65.0.2 (64-Bit)
* Selenium: Node v10.15.0

## Testcase

Don't know how to get it in a HTML file. Attaching image instead.

Testcase regards this code:

var chooseCountry = driver.wait(until.elementLocated(By.xpath("//li[@id='ctr_countrySE']")));
chooseCountry.isDisplayed();
chooseCountry.isEnabled();
chooseCountry.click();

![webdriverBugArrayInterpretError](https://user-images.githubusercontent.com/33604841/54160081-e1ec2c00-444e-11e9-9996-87b20c48a132.JPG)

I know that this issue has been encountered before although I have not seen any example code on how to solve it. I am quite new to webdriver so it would be good to have that.

## Stacktrace

Error: Failed to interpret value as array

## Trace-level log

Don't have a trace-level log.

**Comment by whimboo** [comment]
This is not a problem with geckodriver but the Selenium node.js client you are using. You want to file an issue on their issue tracker.
