### ISSUE TITLE
Firefox always crashes while I open "google maps" or "mapbox map" page

### ISSUE THREAD

**Issue by baconYao** [mozilla/geckodriver#1520]
## System

* Version: 0.21 (64-bit)
* Platform: Linux a2f8f6eee8d6 4.2.8 #1 SMP Sat Oct 13 10:09:30 CST 2018 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04.5 LTS)
* Firefox: 61.0.1
* Selenium: 3.14.0
* PyVirtualDisplay: 0.2.1

## Testcase

Firefox always crashes While I open "google maps" or "mapbox map" page. Below is my python code.

```
# coding:utf-8
#!/usr/bin/env python

from pyvirtualdisplay import Display
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options

# Set screen resolution to 1366 x 768 like most 15" laptops
display = Display(visible=0, size=(1366, 768))
display.start()

firefox_options = Options()
# Enable trace log
firefox_options.log.level = "trace"
# Disable multiprocessors
firefox_options.set_preference('browser.tabs.remote.autostart', False)
firefox_options.set_preference('browser.tabs.remote.autostart.1', False)
firefox_options.set_preference('browser.tabs.remote.autostart.2', False)
#
firefox_options.set_preference("browser.download.folderList", 2)
firefox_options.set_preference("browser.download.manager.showWhenStarting", False)
firefox_options.set_preference("browser.download.dir", "/home/vagrant/Downloads")
firefox_options.set_preference("browser.helperApps.neverAsk.saveToDisk", "image/jpeg;image/x-panasonic-raw;image/x-panasonic-rw2;image/png;application/x-compressed;application/x-zip-compressed;application/zip;multipart/x-zip")

# now Firefox will run in a virtual display.
browser = webdriver.Firefox(executable_path="/webdrivers/geckodriver", firefox_options=firefox_options)

# Work welll
#browser.get("https://www.mozilla.org/en-US/firefox/new/")        # see trace "geckodriver-firefox_download_page.log"

# Will crash
#browser.get("https://www.google.com/maps")         # see trace "geckodriver-google_map.log"
browser.get("https://docs.mapbox.com/mapbox-gl-js/example/simple-map/")         # see trace "geckodriver-mapbox.log"

print "Opend browser"
time.sleep(3)

# Take screenshot
print "Take a screenshot"
browser.save_screenshot('image/firefox_screenshot.png')

# quit browser
browser.quit()

# quit Xvfb display
display.stop()
```

However, I can work on chrome with almost same code. Below is my python code.

* chrome version: 68.0.3440.106
* chrome driver: 2.41.578700

```
# coding:utf-8
#!/usr/bin/env python

from pyvirtualdisplay import Display
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

display = Display(visible=0, size=(1366, 768))
display.start()

chrome_options = Options()
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")

browser = webdriver.Chrome(
    executable_path="/webdrivers/chromedriver",
    chrome_options=chrome_options
)

# Work well
#browser.get("https://docs.mapbox.com/mapbox-gl-js/example/simple-map/")
#browser.get("https://www.google.com/maps")
browser.get("https://www.mozilla.org/en-US/firefox/new/")

print "Opend browser"
time.sleep(3)

# Take screenshot
print "Take screenshot"
browser.save_screenshot('image/chrome-screenshot.png')

# quit browser
browser.quit()

# quit Xvfb display
display.stop()
```

## Stacktrace

For URL: "https://docs.mapbox.com/mapbox-gl-js/example/simple-map/" on Firefox

```
Traceback (most recent call last):
  File "firefox_selenium.py", line 32, in <module>
    browser.get("https://docs.mapbox.com/mapbox-gl-js/example/simple-map/")
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

For URL: "https://www.google.com/maps" on Firefox

```
Traceback (most recent call last):
  File "firefox_selenium.py", line 31, in <module>
    browser.get("https://www.google.com/maps")
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/vagrant/firefox-map/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

## Trace-level log

[(Work well) geckodriver-firefox_download_page.log](https://github.com/mozilla/geckodriver/files/2959610/geckodriver-firefox_download_page.log)
[(Crash) geckodriver-google_map.log](https://github.com/mozilla/geckodriver/files/2959611/geckodriver-google_map.log)
[(Crash) geckodriver-mapbox.log](https://github.com/mozilla/geckodriver/files/2959612/geckodriver-mapbox.log)

**Comment by whimboo** [comment]
You are using an outdated and no longer supported version of Firefox. Please upgrade to the latest release or even beta and try again. If it still doesn't work please provide trace logs again. Thanks

**Comment by baconYao** [comment]
@whimboo Okay, I'll use the latest version to try it again.

**Comment by baconYao** [comment]
@whimboo It still doesn't work. 

* Version: 0.24 (64-bit)
* Firefox: 65.0.1

Here are traces.
[(Work well) geckodriver-firefox_download_page.log](https://github.com/mozilla/geckodriver/files/2960550/geckodriver-firefox_download_page.log)
[(Crash) geckodriver-google_map.log](https://github.com/mozilla/geckodriver/files/2960551/geckodriver-google_map.log)
[(Crash) geckodriver-mapbox.log](https://github.com/mozilla/geckodriver/files/2960552/geckodriver-mapbox.log)

**Comment by whimboo** [comment]
Does it also happen when not using pyVirtualDisplay/xvfb?

**Comment by baconYao** [comment]
Here is the result after I use the "headless" option instead of "pyvirtualDisplay".

My python code:

```
# coding:utf-8
#!/usr/bin/env python

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options


firefox_options = Options()
# Enable trace log
firefox_options.log.level = "trace"

# Headless
firefox_options.add_argument("--headless")

# Window Size
firefox_options.add_argument("--window-size=1600,900")

# Disable multiprocessors
firefox_options.set_preference('browser.tabs.remote.autostart', False)
firefox_options.set_preference('browser.tabs.remote.autostart.1', False)
firefox_options.set_preference('browser.tabs.remote.autostart.2', False)
#
firefox_options.set_preference("browser.download.folderList", 2)
firefox_options.set_preference("browser.download.manager.showWhenStarting", False)
firefox_options.set_preference("browser.download.dir", "/home/vagrant/Downloads")
firefox_options.set_preference("browser.helperApps.neverAsk.saveToDisk", "image/jpeg;image/x-panasonic-raw;image/x-panasonic-rw2;image/png;application/x-compressed;application/x-zip-compressed;application/zip;multipart/x-zip")

# now Firefox will run in a virtual display.
browser = webdriver.Firefox(executable_path="/webdrivers/geckodriver", firefox_options=firefox_options)

#browser.get("https://www.mozilla.org/en-US/firefox/new/")
browser.get("https://www.google.com/maps")
#browser.get("https://docs.mapbox.com/mapbox-gl-js/example/simple-map/")

print "Opend browser"
time.sleep(3)

# Take screenshot
print "Take a screenshot"
browser.save_screenshot('image/firefox_screenshot.png')

# quit browser
browser.quit()
```

### Mapbox can't render the map (see the yellow warning block at photo)

![firefox_mapbox](https://user-images.githubusercontent.com/8318678/54269132-b9cc0c80-45b7-11e9-8cd0-a66de7574125.png)

It seems that "headless" mode doesn't support WebGL.... ?

### Google Map can render the map (see the below photo)

![firefox_google_map](https://user-images.githubusercontent.com/8318678/54269484-6ad2a700-45b8-11e9-8a48-fa0700d478f8.png)

### Here are traces

* [geckodriver-mapbox-without-pyvirtualDisplay.log](https://github.com/mozilla/geckodriver/files/2960802/geckodriver-mapbox-without-pyvirtualDisplay.log)
* [geckodriver-google-map-without-pyvirtualDisplay.log](https://github.com/mozilla/geckodriver/files/2960804/geckodriver-google-map-without-pyvirtualDisplay.log)

Since I use Mapbox's map in my product, so I need to test it without opening browser.

Does anyone have any idea?

**Comment by whimboo** [comment]
@brendandahl any idea about the WebGL issue with headless? Is that unsupported?

@baconYao so there are no crashes anymore when not using xvfb?

**Comment by baconYao** [comment]
@whimboo Yes, there are no crashes without using xvfb & pyvirtualDisplay if I open the page has WebGL service.

By the way, I can get the map when I use chrome without xvfb & pyvirtualDisplay. Below are my chrome code and results.

```
# coding:utf-8
#!/usr/bin/env python

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options


chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--window-size=1600,900")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--no-sandbox")

browser = webdriver.Chrome(
    executable_path="/webdrivers/chromedriver",
    chrome_options=chrome_options
)

#browser.get("https://docs.mapbox.com/mapbox-gl-js/example/simple-map/")
#browser.get("https://www.google.com/maps")
browser.get("https://www.mozilla.org/en-US/firefox/new/")

print "Opend browser"
time.sleep(3)

# Take screenshot
print "Take screenshot"
browser.save_screenshot('image/chrome-firefox-download-wo.png')

# quit browser
browser.quit()
```

### Mapbox opened by headless chrome

![chrome-mapbox-wo](https://user-images.githubusercontent.com/8318678/54325231-1bce5580-463c-11e9-8761-289bbcc5eb29.png)

### google map opened by headless chrome

![chrome-google-map-wo](https://user-images.githubusercontent.com/8318678/54325243-2ab50800-463c-11e9-94ff-f714c0e40e2f.png)

**Comment by whimboo** [comment]
I just found that webgl is not yet supported in headless mode. See https://bugzilla.mozilla.org/show_bug.cgi?id=1375585 for the enhancement request.

**Comment by whimboo** [comment]
As such there is nothing we can do for geckodriver to prevent crashes of Firefox when using your code  under xvfb. It would have to be a bug filed against Firefox.

What I would still suggest is that you grab a debug build of Firefox from https://queue.taskcluster.net/v1/task/W8GcnNaXTT-rQ13OAxhS4g/runs/0/artifacts/public/build/target.tar.bz2 and run your test under xvfb again. Maybe it gives some more information why it crashes.
