### ISSUE TITLE
Consultation about geckodriver standalone limitations

### ISSUE THREAD

**Issue by etanol** [mozilla/geckodriver#1523]
The [documentation about running geckodriver in *standalone* mode][d] states:

> Since geckodriver is a separate HTTP server that is a complete remote end implementation of WebDriver, it is possible to avoid using the Selenium remote server if you have no requirements to distribute processes across a matrix of systems.

This induced us to think that geckodriver was capable of handling multiple concurrent sessions.  But, according to #1213, it seems it is not going to be the case for a while.

However, is it possible to reuse the same geckodriver instance to handle multiple **sequential** sessions?  That is, only one concurrent session, but multiple different sessions over time.  This is how we use geckodriver.  We haven't found any noticeable issues so far, but we are willing to align with the expected usage, if geckodriver instances must be treated as throw away after one session.

[d]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone

**Comment by andreastt** [comment]
Yes your observation is correct regarding geckodriver’s behaviour here. The server can support a maximum of one concurrent session, but there’s no limitation on how many sessions it can host in sequence.

**Comment by etanol** [comment]
Thanks.
