### ISSUE TITLE
AngularJS and Angular testability are undefined

### ISSUE THREAD

**Issue by jagdheesh-reddy** [mozilla/geckodriver#1525]
My protractor scripts(javascript) are running fine on Windows 10.
When i launch the same scripts on windows server 2016 , it throws an error : 
"Unhandled Promise rejection : web driver error : Both angularjs and angular testability are undefined" . 

does anybody know the reason and resolution.

**Comment by andreastt** [comment]
This does not appear to be a geckodriver bug.

**Comment by jagdheesh-reddy** [comment]
yeah , this is not any particular driver issue. seems to be a problem with bootstrapping of protractor. $$testability is not defined or not available.
