### ISSUE TITLE
Change proxy setting running web driver

### ISSUE THREAD

**Issue by alfredonodo** [mozilla/geckodriver#1526]
Hi,
I'm using the latest geckodriver 0.24 on GNU/linux ubuntu 16.04 64 bit with firefox developer edition 67.0b2 and selenium 3.14 python.
I would like to know if it is possible to change the proxy setting while the web driver is already running i.e. in order to open and close multiple times the browser to change the proxy.

At the moment, I'm using the following code:
```
profile = webdriver.FirefoxProfile()
profile.set_preference("network.proxy.type", 1)
profile.set_preference("network.proxy.http", proxyIP)
profile.set_preference("network.proxy.http_port", proxyPort)
profile.update_preferences()
driver = webdriver.Firefox(firefox_profile=profile)
```
Thank you

**Comment by andreastt** [comment]
You can use the proxy configuration object as part of the capabilities:
https://w3c.github.io/webdriver/#dfn-proxy-configuration

**Comment by alfredonodo** [comment]
Thank you for your fast reply. I read the link, however I could not figure out how to change the proxy setting. Is there any example? Thank you

**Comment by andreastt** [comment]
You pass it as a normal capability. Untested code:

```python
webdriver.Firefox(capabilities={"proxy": <proxy configuration object>})
```

**Comment by andreastt** [comment]
Sorry that was inaccurate, there’s some API documentation for Python here:
https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html

Note that `proxy` kwarg on `webdriver.Firefox`.

**Comment by erotavlas85** [comment]
> Sorry that was inaccurate, there’s some API documentation for Python here:
> https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html
> 
> Note that `proxy` kwarg on `webdriver.Firefox`.

Well, this is the same documentation that I used to write my example in the first message. How can I change the proxy while the webdriver is running?

**Comment by andreastt** [comment]
You can’t change the proxy whilst Firefox is running. It must be preconfigured in the session’s capabilities.

**Comment by alfredonodo** [comment]
> You can’t change the proxy whilst Firefox is running. It must be preconfigured in the session’s capabilities.

Are you sure? According to [this](https://stackoverflow.com/questions/17082425/running-selenium-webdriver-with-a-proxy-in-python/) and [this](https://stackoverflow.com/a/48816584/9462629), there is a way to change a proxy with opened instance.

**Comment by whimboo** [comment]
Proxies are specified via capabilities. See the WebDriver spec at: https://w3c.github.io/webdriver/#proxy. Everything else is deprecated and had to be used while this capability didn't exist. The old way could still be used but it is not recommended.
