### ISSUE TITLE
Windows geckdriver 0.24.0 - "NetworkError when attempting to fetch resource" on Firefox 65, 66

### ISSUE THREAD

**Issue by jacattau** [mozilla/geckodriver#1529]
## System

* Version: 0.24.0
* Platform: Windows 10
* Firefox: 65,66
* Selenium: 3.141.59

## Testcase
Internal security protected website

## Stacktrace
`console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:190:13
`

Basically what is happening is that every website that gets launched from selenium on Windows Firefox 65 or 66 while using geckodriver 0.24.0 is that the pages take a VERY long time to actually finish loading about 50% of the time.  The page is completely rendered, but in the bottom left of the screen you see "Transferring from <insert website here..>" and it just sits there.  Sometimes it will eventually move on, but then the very next page has the same behavior.  I am not sure why it 50% of the time.  In every case where it happens, I get the output that I posted above in the stacktrace.

I do NOT experience this issue on Firefox 62.  The only reason I know this is because I had a coworker try it on his machine where he still had Firefox 62 installed and it worked no problem.  I then installed Firefox 62 on my machine, turned off the updates, and confirmed that it works no problem with 62.

I should also note I do not have this problem at all on Firefox 66 on a Mac.  That works just fine.  There appears to be some issue with Windows geckodriver with Firefox 65 and 66.

**Comment by andreastt** [comment]
This isn’t a reproducible bug report, and doesn’t sound like a Marionette specific issue. I would recommend reporting it against Firefox.

**Comment by jacattau** [comment]
@andreastt I realize it's tough to reproduce, and I logged it against Firefox.  However, I think it's very possible it's an issue with geckodriver as I don't experience this issue without automation.  It only happens when running through WebDriver and it started happening in Firefox 63.  I did provide more information in the [bug I created](https://bugzilla.mozilla.org/show_bug.cgi?id=1538196) and maybe that will be more help.  I also think I have a trace log here.

[tracelog.txt](https://github.com/mozilla/geckodriver/files/2997043/tracelog.txt)

**Comment by sunnyg522** [comment]
remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:190:13

I did got the same issue with chrome and firefox both

**Comment by sunnyg522** [comment]
But this was in mac this time

**Comment by dmreda** [comment]
I am also getting this error, on Windows 10, FF 66.0.1, gecko 0.24.

But I have not seen it on CentOS 7, FF 60.6.1esr, gecko 0.24

I'll update if I see in on FF 60.

**Comment by ajleksand** [comment]
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:190:13

In macOS, geckdriver v0.24.0

**Comment by whimboo** [comment]
This is not an error which is related to geckodriver or your testing. In this case the broadcast service is failing to reach the remote URL which we explicitly forbid by default. Your tests aren't affected by that.

Lets follow-up on the already filed bug as mentioned above.
