### ISSUE TITLE
Message: failed to decode response from marionette + Python (Minidumps + Trace log included)

### ISSUE THREAD

**Issue by sibeshkar** [mozilla/geckodriver#1531]
## System

Any help appreciated. How do interpret the trace logs and minidump file? Firefox keep crashing after a while when run inside a docker container.

* Version: 
0.24.0
* Platform: Ubuntu/xenial, running inside Docker container
* Firefox: 66.0
* Selenium: 3.141

Have attached minidumps zip file as instructed in https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/CrashReports.html

Trace file geckodriver.log also attached.
[minidumps.zip](https://github.com/mozilla/geckodriver/files/2997739/minidumps.zip)
[geckodriver.log](https://github.com/mozilla/geckodriver/files/2997740/geckodriver.log)

Do let me know if anything else is needed.

**Comment by whimboo** [comment]
Did you try to increase the SHM size? See https://github.com/SeleniumHQ/docker-selenium/blob/master/README.md#running-the-images

**Comment by sibeshkar** [comment]
I tried mounting `/dev/shm` from host but that didn't change anything(still keeps crashing). I'm not using the official selenium-docker image (have installed firefox and geckodriver in custom image) so I'm not sure I can increase SHM size by passing it during `docker run`.

**Comment by whimboo** [comment]
Ok, so I assume that you haven't submitted the minidumps to crash stats yet? In anyway I did that now. Here the crash details:

https://crash-stats.mozilla.org/report/index/d63230bf-16b2-4a49-9d06-70c7c0190328

Sadly the stack is pretty useless. Would you mind running it again with a Nightly build of Firefox? You can find it here: https://www.mozilla.org/en-US/firefox/channel/desktop/#nighty

**Comment by jsa34** [comment]
Hello - getting the same issue here :(  vania-pooh has referenced it above.

**Comment by whimboo** [comment]
No response from the reporter for months. Going to close this issue.
