### ISSUE TITLE
Firefox WebDriver throws UnsupportedCommandException when uploading a file on Firefox

### ISSUE THREAD

**Issue by louis57** [mozilla/geckodriver#1532]
## System

* Version: v0.24.0
* Platform: Local env: Linux, Remote Machine: Windows 10
* Firefox: v65.0.1
* Selenium: v3.141.59

## Testcase

I get the following exception when uploading a file on Firefox (local env):

    org.openqa.selenium.UnsupportedCommandException: POST /session/{sessionID}/file did not match a known command

The code I write to upload a file:

    // upload a file for both Local and Remote
    log.info("Upload a file attachment");
    LocalFileDetector detector = new LocalFileDetector();
    String path = new File("src/test/resources/files/testFile1kB.jpg").getAbsolutePath();
    File file = detector.getLocalFile(path);
    WebElement uploadBtn = driver().findElement(By.id("attQuestion"));
    ((RemoteWebElement) uploadBtn).setFileDetector(detector);
    uploadBtn.sendKeys(file.getAbsolutePath());

This code is working fine for a long time with Chrome and Firefox. It is still working with Firefox on Remote Machine, I only get this exception recently when I run the test for Firefox on local machine.

## Trace

> org.openqa.selenium.UnsupportedCommandException: POST /session/{sessionID}/file did not match a known command
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxx', ip: 'xxx', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-46-generic', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 65.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 10123, moz:profile: /tmp/rust_mozprofile.twpStB..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-46-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: {sessionID}

**Comment by whimboo** [comment]
There is no end-point for `file` defined by the WebDriver specification. You will have to use `send_keys()` for now to upload files. This will change once https://github.com/w3c/webdriver/issues/1355 has been finished.

**Comment by louis57** [comment]
@whimboo Thanks for your answer. Can I ask a silly question.

I write code with Java (as the code in my report above), and as I know, `send_keys()` is for python or ruby?!. Can you please tell me how to use `send_keys()` with Java.

I tried to use Javascript Executor,
`js().executeScript("arguments[0].value='" + file.getAbsolutePath() + "';", uploadBtn);`

but it didn't work as well, with this exception
> org.openqa.selenium.JavascriptException: SecurityError: The operation is insecure.

Thanks for your help.

**Comment by whimboo** [comment]
Just check eg stackoverflow: https://stackoverflow.com/questions/16896685/how-to-upload-file-using-selenium-webdriver-in-java

**Comment by andreastt** [comment]
Just a point of clarification: `POST /session/{session id}/file` in the Selenium remote server _is not_ equivalent to what is proposed in https://github.com/w3c/webdriver/issues/1355.

The Selenium `POST /session/{session id}/file` is normally called before `POST /session/{session id}/element/{element id}/value` to the file to the endpoint node system so that the latter can access it. From what I can tell, you’re using `FirefoxDriver` directly on the local system which is why the `LocalFileDetector` doesn’t work and complains the former endpoint doesn’t exist.

I may be wrong, but it could be worth filing a bug against Selenium to make the `LocalFileDetector` first check if the driver lives on the local system and if so skip the call to the `/file` endpoint in that case.
