### ISSUE TITLE
Argument renamed from webdriver-port to port

### ISSUE THREAD

**Issue by Marcelovk** [mozilla/geckodriver#154]
In the current revision (after 0.9.0), the argument webdriver-port was renamed to port.  This causes selenium to fail launching firefox via geckodriver, returning an invalid argument error in geckodriver

**Comment by jgraham** [comment]
@AutomatedTester This changed to better match EdgeDriver and ChromeDriver.

**Comment by andreastt** [comment]
@Marcelovk This sounds like a problem in Selenium. Have you filed a bug there?

I suggest we keep this open to track that the fix is deployed.

**Comment by Marcelovk** [comment]
I did not open a bug in selenium, as the chage came in the commit https://github.com/mozilla/geckodriver/commit/9e05d53902a9b8a72912815f012c4608b10524f7, which changed the args parser. But I will fill one there too, so that they change as well to be in sync with other drivers then
