### ISSUE TITLE
Error: Expected argument for flag '--target' but reached end of arguments

### ISSUE THREAD

**Issue by noloader** [mozilla/geckodriver#1540]
I'm trying to build geckodriver v0.24.0 from sources for an ARM platform. I'm using a script to drive the process (the script is below). I am not sure if the process is correct at this point. The script is dying somewhere in the bowels of rust:

```
$ SHELL=bash ./build.sh
...
error: Expected argument for flag '--target' but reached end of arguments.
```

The platform is a [Raspberry Pi 3B+](https://www.amazon.com/gp/product/B07BC6WH7V) running Raspbian. I'm building on the device, so it is a native build. I despise cross compiles because they are such a pain in the ass. I'm happy to build on-device and trade the extra 10 minutes of build time for peace of mind.

The [RPI 3B+](https://www.amazon.com/gp/product/B07BC6WH7V) is fully patched, and it is/has:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

$ gcc --version
gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516

$ gcc -dumpmachine
arm-linux-gnueabihf

$ python2 --version
Python 2.7.13
$ python3 --version
Python 3.5.3

$ rust --version
-bash: rust: command not found
$ cargo --version
cargo 0.15.0 (built 2017-03-22)
```

You can always trust `gcc -dumpmachine` to tell you the target you are building for. It is always accurate when using GCC.

Clang/LLVM provides `-dumpmachine`, but it is *only* accurate when you are building for the native platform. For example, on OS X x86_64 when building for x86_64, `clang -dumpmachine` is accurate. But when building for iPhone, `-dumpmachine` will still say x86_64.

-----

Here's the output of the rust process:

```
To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
++ print_versions
++ rustc -V
rustc 1.24.1 (f2dda7fd7 2018-08-16)
++ cargo -V
cargo 0.15.0 (built 2017-03-22)
++ cc --version
cc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

++ rustup_target_add
++ rustup target list
++ grep -E ' \((default|installed)\)'
armv7-unknown-linux-gnueabihf (default)
++ [[ '' == \i\6\8\6\-\p\c\-\w\i\n\d\o\w\s\-\g\n\u ]]
++ cargo_config
++ local prefix
++ case "$TARGET" in
++ return
++ cargo_build
++ local mode
++ '[' -z '' ']'
++ mode=debug
++ local modeflag
++ '[' debug == release ']'
++ cargo build --target
error: Expected argument for flag '--target' but reached end of arguments.

Usage:
    cargo build [options]
Failed to build geckodriver
```

-----

When I attempt to tell the build script the GCC triplet:

```
if ! SHELL=bash TARGET=$(gcc -dumpmachine) ./build.sh
then
    echo "Failed to build geckodriver"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi
```

It results in:

```
...
++ rustup_target_add arm-linux-gnueabihf
++ rustup target list
++ grep -E 'arm-linux-gnueabihf \((default|installed)\)'
++ rustup target add arm-linux-gnueabihf
error: toolchain 'stable-armv7-unknown-linux-gnueabihf' does not contain component 'rust-std' for target 'arm-linux-gnueabihf'
Failed to build geckodriver
```

-----

And when I attempt to tell the build script the Autoconf triplet after donloading [`config.guess`](https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html):

```
if ! SHELL=bash TARGET=$(./config.guess) ./build.sh
then
    echo "Failed to build geckodriver"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi
```

It results in:

```
...
++ rustup_target_add armv7l-unknown-linux-gnueabihf
++ rustup target list
++ grep -E 'armv7l-unknown-linux-gnueabihf \((default|installed)\)'
++ rustup target add armv7l-unknown-linux-gnueabihf
error: toolchain 'stable-armv7-unknown-linux-gnueabihf' does not contain component 'rust-std' for target 'armv7l-unknown-linux-gnueabihf'
Failed to build geckodriver
```

-----

Here is the script:

```
$ cat build-geckodriver.sh
#!/usr/bin/env bash

BUILD_DIR=build-geckodriver
GECKO_URL=https://github.com/mozilla/geckodriver/archive/
GECKO_TAR=v0.24.0.tar.gz

if [[ -z $(command -v wget) ]]; then
    echo "Please install wget"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi

rm -rf "$HOME/$BUILD_DIR" 2>/dev/null
mkdir -p "$HOME/$BUILD_DIR"
cd "$HOME/$BUILD_DIR"

if ! wget "$GECKO_URL/$GECKO_TAR" -O "$GECKO_TAR";
then
    echo "Failed to download $GECKO_TAR"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi

if ! tar -xf "$GECKO_TAR" --strip-components=1;
then
    echo "Failed to unpack $GECKO_TAR"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi

find $(pwd) -name '*.sh' -exec chmod +x {} \;

if ! SHELL=bash ./build.sh
then
    echo "Failed to build geckodriver"
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
fi

[[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 0 || return 0
```

**Comment by andreastt** [comment]
`cargo build --target <triple>` takes a target definition but the build.sh script you’re calling doesn’t seem to be providing it.

I’m assuming this is [build.sh](https://searchfox.org/mozilla-central/source/testing/geckodriver/build.sh) from geckodriver, but we don’t recommend using that for compiling locally. It’s a legacy script we use when geckodriver is exported from mozilla-central to GitHub/Travis for release, and depends on a couple of environment variables found in [ci.sh](https://searchfox.org/mozilla-central/source/testing/geckodriver/ci.sh) and [.travis.yml](https://searchfox.org/mozilla-central/source/testing/geckodriver/.travis.yml).

If you have a checkout of mozilla-central, you can build following the [official build instructions](https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html), but since you’re downloading a source tarball, a regular `cargo build` from the source directory should do the trick.

So instead of calling `./build.sh`, try replacing this with `cargo build`. Does that get you further?

**Comment by noloader** [comment]
> So instead of calling ./build.sh, try replacing this with cargo build. Does that get you further?

OK, thanks.

Running `cargo build` results in:

```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading hyper v0.12.26
 Downloading mozprofile v0.5.0
 ...
   Compiling crc v1.8.1
   Compiling unicode-width v0.1.5
error: environment variable `OUT_DIR` not defined
 --> /home/jwalton/.cargo/registry/src/github.com-1ecc6299db9ec823/crc-1.8.1/src/crc16.rs:8:18
  |
8 | include!(concat!(env!("OUT_DIR"), "/crc16_constants.rs"));
  |                  ^^^^^^^^^^^^^^^

error: couldn't read "/home/jwalton/.cargo/registry/src/github.com-1ecc6299db9ec823/crc-1.8.1/src/0/crc16_constants.rs": No such file or directory (os error 2)
 --> /home/jwalton/.cargo/registry/src/github.com-1ecc6299db9ec823/crc-1.8.1/src/crc16.rs:8:1
  |
8 | include!(concat!(env!("OUT_DIR"), "/crc16_constants.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Build failed, waiting for other jobs to finish...
error: Could not compile `crc`.

To learn more, run the command again with --verbose.
Failed to build geckodriver
```

**Comment by andreastt** [comment]
I’m not sure, but I think this is due to an older (and incompatible) cargo executable being present somewhere on your system path. If you make sure that it picks up the cargo executable from $HOME/.cargo/bin, it should work.

You can test this theory very quickly:

    % PATH=$HOME/.cargo/bin:$PATH cargo build

**Comment by joywave** [comment]
It would be really nice to know how to build geckodriver on my Raspberry Pi as well, have you had any success?

**Comment by andreastt** [comment]
@joywave See the instructions on [Self-serving an ARM build](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html).

**Comment by whimboo** [comment]
@andreastt shall we close the issue? Looks like we didn't get the requested feedback from the reporter.

**Comment by andreastt** [comment]
Makes sense.
