### ISSUE TITLE
 Web page opening but then saying Element not found while its there!

### ISSUE THREAD

**Issue by BridgeQAAutomation** [mozilla/geckodriver#1541]
## System

* Version: geckodriver-v0.24.0-win64
* Platform:Windows 10 
* Firefox: 66.0.2 (64-bit)
* Selenium: 3.141.59

## Testcase

import org.openqa.selenium.By;
import org.openqa.selenium.PageLoadStrategy;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxDriverLogLevel;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

public class testout {
	@Test

	public static void main() {
		WebDriver driver;

		System.setProperty("webdriver.gecko.driver",
				"C:\\Users\\syarabarla\\Downloads\\geckodriver-v0.24.0-win64\\geckodriver.exe");
		FirefoxOptions options = new FirefoxOptions();
		options.setLogLevel(FirefoxDriverLogLevel.TRACE);
		driver = new FirefoxDriver(options);

		driver.get("https://www.google.com/");
		WebElement search = driver.findElement(By.xpath("input[@name=\"q\"]"));
		search.sendKeys("send something");
	}
}
Firefox is opening up and navigating to the correct webpage, but then is unable to interact with any elements on the page. It fails with an exception saying can't find the element, however the element is clearly there.
This test passes on Chrome.
Steps:
1.open google.com
2.try writing something on search bar.

## Stacktrace

[tracelog.txt](https://github.com/mozilla/geckodriver/files/3074065/tracelog.txt)

**Comment by whimboo** [comment]
Most likely the element is not present for you in that loaded page. Can you please add a sleep to the test and manually check if the search field has this name? Please attach a screenshot too.

**Comment by BridgeQAAutomation** [comment]
Whimboo,
Thanks for checking into it. I have added a implicit wait and checked manually for the element.Attaching SS for your reference. TO be true this is happening for all elements in the page and for every URL.
Please let me know If I can add anything to it.
Thanks.
![1](https://user-images.githubusercontent.com/49315639/56135696-47a46a00-5f5f-11e9-9c42-cff6727ef537.jpg)
![2](https://user-images.githubusercontent.com/49315639/56135703-4bd08780-5f5f-11e9-8cdb-9b0c0aaf0608.PNG)

**Comment by hubeflo** [comment]
I am doing multibrowser tests and ran into exactly the same problem using the exact same configuration as the op. Problem occured only with firefox/geckodriver. 

Version: geckodriver-v0.24.0-win64
Platform: Windows 10
Firefox: 66.0.2 (64-bit) or 66.0.3 (64-bit)
Selenium: 3.141.59

**Comment by hubeflo** [comment]
@BridgeQAAutomation  

Is your reproducer above correct? Try changing the XPath to "//input[@name='q']".

You can check what an Xpath you have provided evaluates to by opening a webpage in your browser then pressing F12, and then  using the console as below.

$x("//input[@name='q']")
[input.gLFyf.gsfi] 

$x("input[@name='q']")
[]

**Comment by whimboo** [comment]
Great that this was solved. @hubeflo if it continues to be a problem for you please file a new issue.
