### ISSUE TITLE
Actions sendKeys() not working on flash/flex elements with text input selected

### ISSUE THREAD

**Issue by PawelWojaczek** [mozilla/geckodriver#1543]
## System

* Version:  geckodriver 0.24.0-win64
* Platform: Windows 10
* Firefox: 66
* Selenium: Selenium-java 3.14

I need to pass through flash element, which has an input. The text input is focused by default and normally entering keys from keyboard works, same when using Actions library and chromedriver. In Firefox, clicking on flash elements work fine (moving by offset, then clicking on a point), but when I try to use sendKeys, nothing happens. Tried WebElement sendKeys method on an embed .swf element too, but it also doesn't work.  Tried Firefox 57+ and ESR, geckodriver 0.17+, Selenium 3.4+.

Trace logs doen't say anything besides the action was posted.

Code executed:
```
        clickImage(usernameImage);
        actions.sendKeys(login).perform();
```
Where clickImage is custom method using Actions library for moving and clicking to a point.

Log:
[trace.log](https://github.com/mozilla/geckodriver/files/3085136/trace.log)

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by PawelWojaczek** [comment]
Attached trace-level log and line of codes that was executed.

**Comment by andreastt** [comment]
When you say “flash/flex elements”, what is that?

**Comment by PawelWojaczek** [comment]
> When you say “flash/flex elements”, what is that?

There is a html wrapper of a flash application on the page I want to automate. Flash objects are not publicly accessible in the application, so i can't access any flash element directly. I've tested Actions sendKeys() on other sites with html inputs and they work fine. Seems like inputs inside flash or flex application do not work with the sendKeys method

**Comment by andreastt** [comment]
WebDriver is limited to interaction with web content, and Firefox explicitly doesn’t allow any form of interactions that might transcend that barrier. Examples include <kbd>Control</kbd> + <kbd>T</kbd> to open new tabs, dragging from anywhere outside the viewport (for example from the desktop), interacting with the context menu by right-clicking, and non-web plugins such as Flash.

**Comment by PawelWojaczek** [comment]
Thanks for answer. I don't quite understand.
If I can click on an element inside flash using Actions, why can't I send a text to the flash element that is inside a web page? 
So does it mean that, compared to chromedriver for example, there is no way for gecko (except awt robot workaround) to send keys through WebDriver to interact with flash?

**Comment by whimboo** [comment]
Could you check if `Element Send Keys` works here? It's not using actions yet, so worth a check if it might be a bug in the actions code.

**Comment by PawelWojaczek** [comment]
`
driver.findElement(By.cssSelector("embed")).sendKeys("aaa");
driver.findElement(By.cssSelector("body")).sendKeys("aaa");
`

Tried those, also didn't work.

**Comment by andreastt** [comment]
>  If I can click on an element inside flash using Actions, why can't I send a text to the flash element that is inside a web page?

I suspect this has to do with how interaction is done. Mouse interaction is _emulated_ through [`nsIDOMWindowUtils`](https://searchfox.org/mozilla-central/source/dom/interfaces/base/nsIDOMWindowUtils.idl), whereas keys are _simulated_ with a combination of faked DOM events and [`nsITextInputProcessor`](https://searchfox.org/mozilla-central/source/dom/interfaces/base/nsITextInputProcessor.idl).

I don’t know enough about this to pinpoint exactly what the difference is, but my guess would be that keyboard input targets a specific element, which might explain why a non-web element such as a plugin would not receive key input.

**Comment by PawelWojaczek** [comment]
Since we are saying farewell to Flash and Flex in 2020, I will just tell here workaround for sending input to remote WebDriver/FirefoxDriver for anyone struggling and close the issue.

1. Using AWT Robot (locally) - it has this flaw that Robot takes control of your keyboard

2. On Remote - use SSH to execute file with your string you want to send to browser
for Windows:
- install SSH Server if needed (e.g. OpenSSH Server for Windows)
- create SSH connection methods (e.g. JSch framework) with any needed configuration
- Install psexec (on Windows)
- create batch file with JSCript that focuses on firefox and sends keys (or AutoIT or any other script that you can pass an argument to)

Example command sent through SSH: "psexec -s -i 1 "C:/utils/sendKeys.bat" "exampleMessage"'

-i 1 is needed for Windows to use Session 1 (and therefore access user session as executable session)

If there are no active sessions on remote, you need to use this before:

tscon.exe 1 /dest:console

tscon is Windows built-in executable that opens session.
