### ISSUE TITLE
Unable to get Python 3, Selenium and gecko driver to work on Ubuntu 18.04 server

### ISSUE THREAD

**Issue by high5five** [mozilla/geckodriver#1544]
## System

* Version: v0.24.0
* Platform: Ubuntu 18.04
* Firefox: 66.0.3 and tried downgrading to Firefox 62 as well.
* Selenium: selenium 3.141.0

## Testcase
Code in python3
```
from selenium import webdriver
browser = webdriver.Firefox()
```

## Stacktrace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myfolder/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/myfolder/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/myfolder/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/myfolder/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/myfolder/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by andreastt** [comment]
With the information you’ve provided this looks like a Selenium client issue, and not a geckodriver issue specifically.

Could you please attach a [trace-level log] from geckodriver so we can confirm?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.htmll

**Comment by evrenmercan** [comment]
Do you execute on VS Code or Local Terminal ?

**Comment by ikisoft** [comment]
I am having the exact same problem. My code is working fine in a local environment with the same exact dependencies and browser/driver versions. Only difference is that my VPS does not have a screen which could be causing this problem? Tried using Xvfbwrapper for python that simply wraps Xvfb, but Xvfbwrapper cannot locate Xvfb despite it being installed and in PATH. 

Anyone know what could be causing this?

**Comment by whimboo** [comment]
@ikisoft I cannot see why it should be related. It's a totally different situation at least as described. So if you still have issues please file your own issue. Thanks.

**Comment by whimboo** [comment]
Closing issue due to no reply from original reporter.

**Comment by ocyisheng** [comment]
@high5five 这是因为你的脚本在root用户下运行的原因。解决方案：新建非root用户，在该用户下运行脚本即可解决。若运行时需要读写权限，请给予相应权限即可。
