### ISSUE TITLE
org.openqa.selenium.WebDriverException: connection refused

### ISSUE THREAD

**Issue by ElinaValieva** [mozilla/geckodriver#1545]
## System

* Version: 0.24.0
* Platform: Ubuntu 18.04 (OpenShift)
* Firefox: 66.0.3 (latest)
* Selenium: 3.4.0

## Testcase

```
        FirefoxOptions options = new FirefoxOptions();
        options.setProfile(new FirefoxProfile());
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);
        options.setHeadless(true);
        WebDriver webDriver = new FirefoxDriver(options);
        webDriver.get("http://example.com/");
        WebElement element = webDriver.findElement(By.xpath("/html/body/div/h1"));
        String text = element.getText();
        webDriver.quit();
        return text;
```

## Stacktrace

>   | 1555598883519	mozrunner::runner	INFO	Running command: "/opt/firefox/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.9kjjz6YTA64J"
>   | 1555598883520	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:39832
>   | *** You are running in headless mode.
>   | 1555598943535	mozrunner::runner	DEBUG	Killing process 48
>   | 1555598943548	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
>   | Exception in thread "main" java.lang.reflect.InvocationTargetException
>   | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   | at java.lang.reflect.Method.invoke(Method.java:498)
>   | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>   | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>   | at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>   | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
>   | Caused by: org.openqa.selenium.WebDriverException: connection refused
>   | Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
>   | System info: host: 'selenium-example-chv6-1-95vfn', ip: '10.1.81.103', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.1.3.el7.x86_64', java.version: '1.8.0_191'
>   | Driver info: driver.version: FirefoxDriver
> 

## Trace-level log

>   | 1555598883519	mozrunner::runner	INFO	Running command: "/opt/firefox/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.9kjjz6YTA64J"
>   | 1555598883520	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:39832
>   | *** You are running in headless mode.
>   | 1555598943535	mozrunner::runner	DEBUG	Killing process 48
>   | 1555598943548	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}
>   | Exception in thread "main" java.lang.reflect.InvocationTargetException
>   | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   | at java.lang.reflect.Method.invoke(Method.java:498)
>   | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
>   | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
>   | at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
>   | at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
>   | Caused by: org.openqa.selenium.WebDriverException: connection refused
>   | Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
>   | System info: host: 'selenium-example-chv6-1-95vfn', ip: '10.1.81.103', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.1.3.el7.x86_64', java.version: '1.8.0_191'
>   | Driver info: driver.version: FirefoxDriver
>   | remote stacktrace:
>   | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>   | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>   | at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
>   | at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
>   | at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
>   | at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 
>

**Comment by ElinaValieva** [comment]
As an experiment, I have tried to change version of **Firefox** from `66.0` to `60.0` and **geckodriver** from `0.24.0`to `0.20.0`

**Comment by parul19** [comment]
> As an experiment, I have tried to change version of **Firefox** from `66.0` to `60.0` and **geckodriver** from `0.24.0`to `0.20.0`

Did it work after degrading the version?

**Comment by ElinaValieva** [comment]
> > As an experiment, I have tried to change version of **Firefox** from `66.0` to `60.0` and **geckodriver** from `0.24.0`to `0.20.0`
> 
> Did it work after degrading the vers

Unfortunately, no :worried:

**Comment by parul19** [comment]
I tried uninstalling firefox and then reinstalling the updated version of both firefox and geckodrier.Then I deleted the gecko.log file as well as all the folders created in code and ran again the code.It worked for me well by clearing all the browser history as well

**Comment by ElinaValieva** [comment]
> I tried uninstalling firefox and then reinstalling the updated version of both firefox and geckodrier.Then I deleted the gecko.log file as well as all the folders created in code and ran again the code.It worked for me well by clearing all the browser history as well

My problem, that I have this error in OpenShift platform. :sob:
In this case, I can't clearing browser history. 
Also I'm running this browser in headless mode.

Which version of browser and driver have you used? :blush:

**Comment by parul19** [comment]
Firefox 66 (64bit) geckodriver 0.24 on windows 7

**Comment by andreastt** [comment]
I don’t understand what this bug is about. Read more about reporting actionable bugs in our [contribution guidelines].

[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by ElinaValieva** [comment]
> I don’t understand what this bug is about. Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html).

Problem was "Connection refused"
`555598943548	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"connection refused","stacktrace":""}}`

I have read about this error, but can't find solution for this problem. Problem like "Connection refused" so vague problem. 
Someone suggest to change version, someone suggest to clean cache. :weary:
But anyhow, I have solved problem via using Remote driver. ~Thanks for help.~
