### ISSUE TITLE
Incompatibility with firefox > 63 and headless mode

### ISSUE THREAD

**Issue by po-b** [mozilla/geckodriver#1549]
## System

* Version: 0.24.0
* Platform: Ubuntu 16.04
* Firefox: ok < 63 ;  not ok  64-66
* Selenium: 3.141.0 (python3)

## Problem

Hello, my problem is that by running a simple test (see testcase below) with geckodriver and Firefox with a version higher than 63 I observe a CPU consumption of 100% and the memory consumption increase quickly too. I don't receive any error from python but the extraordinary CPU and memory consumption.

With Firefox 63 it works fine. Without the headless mode (with all version) it works fine too.
I test this on an other computer with the same setup it works well, the only difference were that it runs Ubuntu version 18.04

Thank you in advance for the help

## Testcase

```
    options = Options()
    options.add_argument("--headless")

    driver = webdriver.Firefox(firefox_options=options)

    driver.get("https://www.google.com/search?q=cats&tbm=isch")
```

## Stacktrace

Geckodriver:

```
1556801359521   mozrunner::runner       INFO    Running command: "<firefox_path>" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.CKp3Ve5DbhGE"
*** You are running in headless mode.
1556801359840   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1556801359841   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1556801359841   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1556801361618   Marionette      INFO    Listening on port 33991
1556801361658   Marionette      WARN    TLS certificate errors will be ignored for this session
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
```

**Comment by whimboo** [comment]
@po-b so this issue isn't valid anymore?

**Comment by po-b** [comment]
Thank you for your answer.
It was valid but I succeed to solve the problem by doing a full update of the system and reboot it.
I don't know exactly what was the problem but after the reboot everything were ok. That's why I close the issue.

If you want more information, feel free to ask but now I can't reproduce the issue.

**Comment by whimboo** [comment]
Thanks, but it's fine as is. Looks kike an incompatibility which got fixed with the update.
