### ISSUE TITLE
"permission denied" error has no useful diagnostic information

### ISSUE THREAD

**Issue by M-Pixel** [mozilla/geckodriver#1550]
## System
* Version: 0.24.0
* Platform: Windows Nano Server 1809
* Firefox: 60.6.1esr-ssl
* Selenium: 

## Stacktrace
```
Unhandled Exception: OpenQA.Selenium.WebDriverException: permission denied
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
```

## Trace-level log
```
1557085440082   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "--headless" "-foreground" "-no-remote" "-profile" "C:\\rust_mozprofile.S43rchjPa1W2"
1557085440098   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:49181
1557085441202   mozrunner::runner       DEBUG   Killing process 1428
1557085441202   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"permission denied","stacktrace":""}}
```

I have a simple Hello World where a dotnet core application uses Selenium with Firefox.  It works great on my main system, but I run into the above error when attempting to run it inside of a container.

Regardless of my particular scenario, whether or not running this in a container is officially supported or not, the error is useless.  "permission denied" - so there's probably some path or command it's trying to use that it doesn't have permission for, or that doesn't exist.  That's a simple problem to fix, as long as I can know what the path _is_.

I searched for "permission" in the source code, and could not find any instances of that word.  I searched for error logging, and found one instance in which the message is passed from external code (as opposed to being something explicit that is not "permission denied"):

```rust
match TcpStream::connect((&self.host[..], self.port)) {
    Ok(stream) => {
        self.stream = Some(stream);
        break;
    }
    Err(e) => {
        if now.elapsed() < timeout {
            thread::sleep(poll_interval);
        } else {
            return Err(WebDriverError::new(
                ErrorStatus::UnknownError,
                e.description().to_owned(),
            ));
        }
    }
}
```

From this, and the fact that it occurs soon after "waiting to connect", I figured it's most likely failing to connect to the firefox port (rather than failing to kill the process, or anything else).  Indeed, I found that firefox.exe simply fails to launch on Nano Server.

So, it's on Rust's TCP library that it says "permission denied" instead of "port not open" or something more descriptive.  But there's a strong case for improvement to GeckoDriver as well.  I figured it out by reading the source code and conjecturing based on over a decade of software development experience.  For a lot of users, they're not going to be able to figure out their TCP connection issues as simply, and for myself as well, it would have saved a significant amount of time if the message said something more like "Failed to connect to Firefox over TCP @ 127.0.0.1:49181: permission denied".

**Comment by whimboo** [comment]
Can you please describe what happens on the Nano server when you are trying to start Firefox? Does it just quit, crash, or what happens exactly? If it's closing I would expect a different code path to fail.

**Comment by M-Pixel** [comment]
I ran Firefox.exe from CMD within Nano Server using identical command line arguments to those logged by `mozrunner::runner` - the program exited immediately with no output.  It could be that the stderr or stdout was not captured by my console, but it's my understanding that Firefox.exe doesn't log anything to either even in the case of a crash, relying on its GUI instead (even when `-headless` is specified).

**Comment by whimboo** [comment]
On Windows two things have to be obeyed to get console logs when starting Firefox manually. First make sure that the profile Firefox is using has the preference `browser.dom.window.dump.enabled` set to `true`. Also use the command line argument `--attach-console`, which will open an additional terminal window for all the output.

Anyway, this also seems to be the problem why geckodriver isn't able to launch Firefox.

**Comment by whimboo** [comment]
@M-Pixel any feedback? if we don't get further updates we will have to close this issue.

**Comment by M-Pixel** [comment]
What further feedback is required?  This issue is a suggestion to prepend additional information to the existing exception message that successfully prints.

**Comment by whimboo** [comment]
See my second last comment and I also would like to see a [trace-level log] from geckodriver. The one you pasted originally is `debug` only.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
