### ISSUE TITLE
Unable to take screenshots of WebExtension elements

### ISSUE THREAD

**Issue by sneakypete81** [mozilla/geckodriver#1551]
## System

* Version: 0.24.0
* Platform: macOS 10.14.4
* Firefox: 66.0.3
* Selenium: N/A - using geckodriver API directly

## Testcase

``` python
    gecko = GeckoDriver(BASE_URI)
    gecko.new_session()
    try:
        gecko.install_addon(ADDON_PATH)
        gecko.set_context("chrome")
        button = gecko.find_element("#_" + US_ID + "_-browser-action")
        gecko.click_element(button)

        time.sleep(1)
        gecko.take_screenshot()
    finally:
        gecko.delete_session()
```

## Expected Result:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/38854/57484573-44bc4100-72a1-11e9-8f57-299d7c0e6b25.png">

## Actual Result:
![image](https://user-images.githubusercontent.com/38854/57484605-5e5d8880-72a1-11e9-9bbc-b0c03fb86823.png)

Note that the WebExtension popup is not present, and the sidebar content is blank. I guess this is because these items are not part of the "Chrome" context.

Is it possible to capture these elements using geckodriver/marionette?

**Comment by whimboo** [comment]
This is not a geckodriver specific issue but a Marionette one. See https://bugzilla.mozilla.org/show_bug.cgi?id=1198432 for details.

**Comment by sneakypete81** [comment]
Ok, thanks for your help. I'm not sure that bug is the complete answer, since it probably isn't relevant for the missing sidebar contents.

**Comment by whimboo** [comment]
It might also be some kind of popup/notification. Is the code of the extension publicly available?

**Comment by sneakypete81** [comment]
The extension is at https://github.com/sneakypete81/updatescanner. The popup is using the standard [WebExtension API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups), there shouldn't be anything unusual about it.

I've uploaded my script that reproduces this problem to https://github.com/sneakypete81/geckodriver-test.

Given this isn't a geckodriver issue, please let me know if there's a better place for this kind of question.

**Comment by whimboo** [comment]
Mind pointing to the code inside the extension where this happens? It would help me a lot. Thanks.

**Comment by sneakypete81** [comment]
Thanks for your help. The popup is defined in https://github.com/sneakypete81/updatescanner/blob/master/src/app/popup/popup.html.

This is referenced from the `default_popup` line in the manifest: https://github.com/sneakypete81/updatescanner/blob/76e4597f1398040776f050acc813b0dee65ac4d5/src/manifest.json#L34.

There's no code in the extension to open the popup, this is done by Firefox itself. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Specifying_a_popup.

**Comment by whimboo** [comment]
Would you mind to check if normal sidebars like the bookmarks or history one are also not included in the screenshot? If that is the case it might be all the same underlying issue.

**Comment by sneakypete81** [comment]
From a window where both the bookmark sidebar and popup are open, the sidebar is captured but the popup is not:

Expected:
<img width="1280" alt="expected" src="https://user-images.githubusercontent.com/38854/57920227-78472e80-7892-11e9-914b-7d267e8335aa.png">

Actual:
![actual](https://user-images.githubusercontent.com/38854/57920242-81380000-7892-11e9-92d6-74b587bf5dcf.png)

**Comment by whimboo** [comment]
Ok, so maybe the sidebar for webextensions is something specific compard to the built-in ones. In that case I would say lets wait until the fix for Marionette got landed (whenever it will be), and re-check this issue then. Thanks for all your help so far!
