### ISSUE TITLE
Closing / opening developer tools at runtime

### ISSUE THREAD

**Issue by gaardiolor** [mozilla/geckodriver#1552]
## System

* Version: 0.24.0
* Platform: Windows 10
* Firefox: 66.0.5
* Selenium: 3.141.0

## Testcase
Any html document has this problem. 
I'm doing tests and generating HAR logs with the Firefox extension HarExportTrigger. I've configured persistent logs, evertything works fine. But, at some points in my script, I want to clear the HAR logs. Just setting persistency to false and then True doesn't help, a page needs to be fetched between those settings. In my case I don't want to fetch a page.

In the development tools it's possible to click a 'recycle bin' to clear the logs. However, I don't think Selenium can interact with the Development tools.

Closing and opening development tools seems to clear the log. But, sending F12 doesn't work. The development tools remain open. I've tried 2 ways:

method 1:
`driver.find_element_by_xpath('//body').send_keys(Keys.F12)`

method 2:
```
actions = ActionChains(driver)
actions.send_keys(Keys.F12).perform()
```

I've also tried to send `Keys.CONTROL + Keys.SHIFT + 'I'` in both methods. It doesn't work.

Any other way to close / open developer tools ?

## Stacktrace
No stacktrace is produced.

## Trace-level log
See attachment

**Comment by whimboo** [comment]
Interacting with ui elements of Firefox isn't possible by default which means when using the content context. To make it happen you would have to use the `chrome` context. The Python bindings offer some API here: https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html#module-selenium.webdriver.firefox.webdriver
