### ISSUE TITLE
NoSuchWindowException: Browsing context has been discarded // running multiple Firefox instances

### ISSUE THREAD

**Issue by fanilosendrison** [mozilla/geckodriver#1553]
## System

* Version: v.0.24.0
* Platform: Ubuntu 18.04 Server
* Firefox: Mozilla Firefox Nightly 68.0a1
* Selenium: 3.141.59

I'm building an app that sequentially launches multiple headless Firefox clients.

## Code executed

```
int i = 0;
while (i < 40) {
        try {
            File pathToBinary = new File("/usr/bin/firefox-trunk");
            FirefoxBinary firefoxBinary = new FirefoxBinary(pathToBinary);
            firefoxBinary.addCommandLineOptions("--headless");

            FirefoxOptions options = new FirefoxOptions();
            options.setBinary(firefoxBinary);
            options.setLogLevel(FirefoxDriverLogLevel.TRACE);

            Webdriver driver = new FirefoxDriver(options);
            driver.manage().window().setSize(new Dimension(1920,1080));
            driver.get("http://google.com");
            System.out.println("Actual page: " + driver.getTitle());

        } catch (Exception e) {
            e.printStackTrace();
        }
        i++;
}
```
I willingly don't use `driver.quit()` because I absolutely need each Firefox window to stay opened for a specific time. I expected to end up with 40 Firefox windows.

Well, the problem is this code is working perfectly until the exact 30th iteration. I suddenly get this error :
## Stacktrace

> INFO: Detected dialect: W3C
> org.openqa.selenium.NoSuchWindowException: Browsing context has been discarded
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
> System info: host: 'ip-172-31-13-131', ip: '172.31.13.131', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1035-aws', java.version: '9'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 68.0a1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190510185059, moz:geckodriverVersion: 0.24.0, moz:headless: true, moz:processID: 8330, moz:profile: /tmp/rust_mozprofile.RBclVw..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.0-1035-aws, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
> Session ID: f3d1da99-3547-4afe-912c-85d699b9027e
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
> 	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
> 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
> 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
> 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
> 	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:802)

## Trace-level log
[tracelog.log](https://github.com/mozilla/geckodriver/files/3169369/tracelog.log)

## What I tried to solve it until now

- I was initially using Firefox 66.0.4 before Firefox Nightly with the same results.
- I don't think this is a ressource problem. When this error is happening, used RAM is at 15/32Go and CPU is at 60%.
- I tried to brutally kill each geckodriver process with `Runtime.getRuntime().exec("kill " + PID);` at the end of each loop while keeping all my Firefox windows opened (which is needed in my use case)
- I read this issue could also occur if you are not using the complient version of the binaries (see [here](https://stackoverflow.com/questions/54525301/browsing-context-has-been-discarded-using-geckodriver-firefox-through-selenium/54529774#54529774)). But I don't see no obvious incompatibilities in my setup and my code is working for the first iterations of the loop.

**Comment by whimboo** [comment]
You are seeing a crash of Firefox. Notice the `MOZ_CRASHREPORTER_SHUTDOWN` line in the trace log. Please follow the steps on https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html to provide a helpful crash report. Thanks!

**Comment by fanilosendrison** [comment]
Thank you for helping !
I had the hardest time re-writing the python code for FF crash reports in Java.
When I finally succeeded, my code just stopped crashing so I can't provide any crash report.
The only thing I changed is the way I customize Firefox profiles. I used to edit the pref.js file directly which is apparently a DON'T according to FF docs. It may has been the cause.

**Comment by whimboo** [comment]
Maybe try with your old code which setting has been caused the crash. It would be good to know.

**Comment by whimboo** [comment]
Feel free to respond even after I closed this issue. Thanks for the positive feedback through!

**Comment by fanilosendrison** [comment]
Hi, 
well it seems I spoke too soon, it still crashes but at the 75th iteration now.
here is the zip file for FF crash report :
[Archive.zip](https://github.com/mozilla/geckodriver/files/3194896/Archive.zip)

**Comment by whimboo** [comment]
Thank you for the feedback and the crash report. I submitted it but sadly there is not that much helpful information contained:

https://crash-stats.mozilla.org/report/index/4e8c0808-2bfe-4ff3-9ff4-ee6ae0190520#tab-details

Are you using a custom Firefox binary as shipped by your distribution? If yes, please try again with an official Firefox release.

**Comment by fanilosendrison** [comment]
@whimboo I installed the latest official Firefox release manually but same result. Still no idea about what causes this crash so unwillingly I'm going to give a try to Chrome. Which upsets me a bit because I spent so much time learning about geckodriver and FF .. 
Thank you for your help !

**Comment by whimboo** [comment]
@fanilosendrison, would you mind a last try? What happens when you set the preference `browser.tabs.unloadOnLowMemory` to `false` for that Firefox profile? Does it still crash?

**Comment by whimboo** [comment]
Also when it still crashes with the official release I would really like to see the minidump files. Those should really contain the correct addresses for symbolication. Thanks!
