### ISSUE TITLE
Can't create new profile based on existing profile

### ISSUE THREAD

**Issue by GenialRapier** [mozilla/geckodriver#1556]
## System

* Version:  0.23.0 
* Platform:  Windows 10 Enterprise 64-bit
* Firefox:  60.6.2esr(32-bit) 
* Selenium:  3.14.0 

## Testcase
Dim foxProfile = New FirefoxProfile(strProfilePath)

I want to import all settings from an existing Firefox profile. I can't find a way to do it. Creating Firefox profile from an existing Firefox profile always resulted in a crash.

I can use -profile "profilepath" with no problem, but it is not the result that I want. I want to be able to use the profile for normal use and for automation at the same time.

## Stacktrace
Exception thrown: 'System.ArgumentException' in mscorlib.dll

**Comment by andreastt** [comment]
Sorry, this isn’t a support forum. If Firefox crashes on loading a profile, you should report that in Bugzilla.

**Comment by whimboo** [comment]
Also pre-configuring a profile is outside of the scope of geckodriver. It might be related to Selenium if the client binding supports cloning a profile.
