### ISSUE TITLE
Can't set some preferences with selenium-python (geckodriver 32 bit)

### ISSUE THREAD

**Issue by kevin7600** [mozilla/geckodriver#1557]
## System

* Version: 24, 32 bit
* Platform: Windows10
* Firefox: 60.5.1esr (32-bit)
* Selenium: selenium 3.141.0

## Python Code

`from selenium import webdriver`

`profile = webdriver.FirefoxProfile()`
`profile.set_preference("browser.download.folderList",2)#unchanged`
`profile.set_preference("browser.download.useDownloadDir",True)#doesn't work`
`profile.set_preference("browser.download.dir",'C:\\Users\\')#doesn't work`
`profile.set_preference('browser.download.downloadDir','C:\\Users\\')#doesn't work`
`profile.set_preference('browser.helperApps.neverAsk.saveToDisk','text/csv')#works!`
`profile.set_preference('browser.download.autohideButton',False)#works!`

`driver = webdriver.Firefox(firefox_profile=profile,executable_path=PATH_TO_GECKO_EXE + "geckodriver24_32.exe")`
`driver.get("about:config")`

## Results
Only some about:config settings are set, most aren't changed

## Note
I only have this problem with geckodriver 32 bit. The 64 bit version can set all the about:config settings perfectly fine

**Comment by whimboo** [comment]
You want to use the [prefs capabilities](https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#prefs-object) to set the preferences.
