### ISSUE TITLE
Webdriver opens but don't put the URL

### ISSUE THREAD

**Issue by gabrielgambarra** [mozilla/geckodriver#1562]
## System

* Version: 0.24.0
* Platform: Linux - Ubuntu
* Selenium: selenium-3.141.0

I'm trying to run a test that I did a fill tomes ago and the Firefox opens, but doesn't put the URL I want. How can I fix this? I already tried to update selenium and the geckodriver, but nothing yey.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by gabrielgambarra** [comment]
[geckodriver.log](https://github.com/mozilla/geckodriver/files/3237468/geckodriver.log)

Here it is. I thought I was using the last version, but it's 0.20.1.

**Comment by andreastt** [comment]
From the log:

```
1559227051591	Marionette	DEBUG	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1559227051591	Marionette	DEBUG	0 <- [1,1,{"error":"unknown command","message":"newSession","stacktrace":"WebDriverError@chrome://marionette/content/error.js:179: ... t@chrome://marionette/content/server.js:236:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:492:20\n"},null]
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: http://%(server)s/dummy/blocklist//buckets/monitor/collections/changes/records?_expected=%221559174406944%22 is not a valid URL..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:201:13

Exiting due to channel error.
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
[Child 20440, Chrome_ChildThread] WARNING: pipe error: Pipe quebrado: file /build/firefox-Ci7f25/firefox-68.0~b5+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 727
Exiting due to channel error.
```

It looks like the geckodriver you’re using is incompatible with the version of Firefox you’re using it with. Please check the [support matrix](https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html) in the documentation.

If you’re on geckodriver 0.20.1, it’s only compatible with Firefoxen 55 <=> 62. This is also highlighted in the release notes for later versions.

I hope this helps! Let me know if you’re able to resolve the problem.

**Comment by andreastt** [comment]
For what it’s worth, we have https://bugzilla.mozilla.org/show_bug.cgi?id=1481444 on file to make geckodriver give a more useful error message when it tries to connect to a Firefox it doesn’t support.

**Comment by gabrielgambarra** [comment]
@andreastt it worked! I installed the version 62 of firefox. Thanks!

**Comment by whimboo** [comment]
@gabrielgambarra you should better upgrade geckodriver and Firefox to the latest releases instead of running tests with outdated and no longer maintained releases.
