### ISSUE TITLE
TLS certificate errors are ignored by marionette

### ISSUE THREAD

**Issue by amkhlv** [mozilla/geckodriver#1566]
## System

* Version: 0.24.0
* Platform: Debian Buster
* Firefox: 67.0
* Selenium: "org.seleniumhq.selenium" % "selenium-firefox-driver" % "3.141.59"

     val ffProfile = new FirefoxProfile(ffProfilePath)

     ffProfile.setAcceptUntrustedCertificates(false)

     ffOptions.setProfile(ffProfile)

     val driver = new FirefoxDriver(ffOptions)

I am getting:

    Marionette      WARN    TLS certificate errors will be ignored for this session

`setAcceptUntrustedCertificates(false)` is ignored, 

can freely navigate to dangerous links on [badssl.com](https://badssl.com)

## Testcase

[https://expired.badssl.com/](https://expired.badssl.com/)

**Comment by andreastt** [comment]
I’m unsure what it means to set this option on the profile. As far as I’m aware, it’s only possible to configure the ` acceptUntrustedCerts` capability through capabilities. Can you explain what the client  you’re using is doing?

Also, could you please attach a [trace-level log] from geckodriver? That might help explain what is going on between the client and the server on the wire level.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by amkhlv** [comment]
Thank you! I think I am just confused, precisely about capabilities. Could you please point me to the instructions, on how to set them ? I am using Scala. My `sbt` file has:

      libraryDependencies += "org.seleniumhq.selenium" % "selenium-firefox-driver" % "3.141.59"

My code for initializing the driver is:
 
     System.setProperty(FirefoxDriver.SystemProperty.DRIVER_USE_MARIONETTE, "true")
     System.setProperty(FirefoxDriver.SystemProperty.BROWSER_PROFILE, "Robot")

     def getDriver(timeout: Long): FirefoxDriver = {
       val ffOptions = new FirefoxOptions()
       val ffProfilePath = new java.io.File("/home/andrei/.mozilla/firefox/Robot")
       val ffProfile = new FirefoxProfile(ffProfilePath)
       ffProfile.setAcceptUntrustedCertificates(false)
       ffOptions.setProfile(ffProfile)
       val driver = new FirefoxDriver(ffOptions)
       driver.manage().timeouts().implicitlyWait(timeout, TimeUnit.SECONDS)
       driver
  }

I could not find instructions on how to set Capabilities... There is `driver.getCapabilities()`,
but there is no `driver.setCapability(...)` 

Please help me !

**Comment by amkhlv** [comment]
I am looking at this page: [https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Capabilities.html#)

It does not mention certificate policies. Where can I find the list of all `prefs` ?

**Comment by andreastt** [comment]
Sorry, I don’t know how to set capabilities using the Scala client.

The last link you gave only lists Firefox specific capabilities that are part of `moz:firefoxOptions`. `acceptInsecureCerts`, on the other hand, is a _WebDriver_ capability supported by all browsers.

A while back I wrote some documentation about `acceptInsecureCerts` on MDN:
https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/acceptInsecureCerts

Unfortunately it only includes a Python example, but it is roughly equivalent to what you would do in Java.

So instead of passing along a `ffOptions` you typically want to pass in a WebDriver capabilities object, similar to `DesiredCapabilities` in Java, to `FirefoxDriver`’s constructor.

WebDriver capabilities are further explained here:
https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities

**Comment by whimboo** [comment]
I think it is better to get this topic discussed with the Scala community. As written this is not a preference but a capability, and they should be able to give you the information in how to set capabilities. I'm fairly sure that this also works through the `FirefoxDriver()` constructor.

**Comment by amkhlv** [comment]
Thank you, this is very informative! In fact the problem seems to be solved by adding the line:

    ffOptions.setAcceptInsecureCerts(false)

**Comment by andreastt** [comment]
I’m a little confused why the Scala client would conflate Firefox specific options with WebDriver capabilities, as the two are distinct concepts. It may be worth raising this concern with the maintainer of the client.
