### ISSUE TITLE
This is output from Firefox you don't have to worry about unless it is causing your test to fail. And I don't see indication for that.

### ISSUE THREAD

**Issue by nimitjain1986** [mozilla/geckodriver#1569]
This is output from Firefox you don't have to worry about unless it is causing your test to fail. And I don't see indication for that.

As you said you cannot see the original issue anymore I'm going to close this report.

_Originally posted by @whimboo in https://github.com/mozilla/geckodriver/issues/1376#issuecomment-422294339_

**Comment by nimitjain1986** [comment]
Error: Channel closing: too late to send/recv, messages will be lost
 I am still able to view this error in my console of eclipse

**Comment by whimboo** [comment]
Again, and as said on the other issue, this is output from Firefox and as such not geckodriver related.
