### ISSUE TITLE
save_screenshot after set_window_size does not produce image of proper dimensions

### ISSUE THREAD

**Issue by dojutsu-user** [mozilla/geckodriver#1574]
## System

* Version: v0.24.0
* Platform: Ubuntu 18.04.2 LTS
* Firefox: Firefox Quantum 66.0.5 (64-bit)
* Selenium: 3.141.0 (python binding)

After I change window dimension by `set_window_size` and take screenshot by `save_screenshot`, the screenshot obtained does not have proper height. It should have the height which I set in `set_window_size`.
Eg.

```python3
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
>>> driver.get('https://docs.readthedocs.io/en/stable/')
>>> driver.set_window_size(width=800, height=600)
>>> driver.set_window_size(width=800, height=600)  # I don't know why I have to do this twice
>>> driver.save_screenshot('test.png')
```

The screenshot obtained has dimensions -- **Width: 800px, Height 526px**.
It should be of -- **Width: 800px, Height: 600px**

**Comment by andreastt** [comment]
The set window size command controls the dimensions of the application window and not that of the viewport, so this would be expected behaviour. This is similar to [`window.resizeTo`](https://developer.mozilla.org/en-US/docs/Web/API/Window/resizeTo).
