### ISSUE TITLE
xpath does not support name()

### ISSUE THREAD

**Issue by javaone199** [mozilla/geckodriver#1575]
element.findElement(By.xpath(".//*[name()='button' or name()='input']"));

This works fine for Chrome and Edge.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by KroArtem** [comment]
We have the following xpaths:
``` .//*[name()='use']```
``` .//*[name()='svg'][contains(@class, 'stream-permalink-icon')]```

Both work correctly in Firefox 67. JFYI.

**Comment by andreastt** [comment]
@KroArtem This issue is about `name()` in XPath expressions. If you think that’s a regression, you should file a separate issue.

**Comment by KroArtem** [comment]
@andreastt , I just wanted to note `name()` in XPath expressions works ok for me in Firefox.

**Comment by andreastt** [comment]
Oh sorry, I misread the last line in your comment. Appologies!

**Comment by whimboo** [comment]
No feedback from the reporter. Closing the issue.
