### ISSUE TITLE
Cannot take full page screenshot of horizontal scroll document

### ISSUE THREAD

**Issue by takeya0x86** [mozilla/geckodriver#1580]
The `GET /session/{session id}/moz/screenshot/full` endpoint cannot take full page screenshot of horizontal scroll document. takes viewport only.

Vertical scroll page works fine.

## System

* Version: 0.24.0
* Platform: macOS Mojave 10.14.5
* Firefox: 67.0.4
* Selenium: java 4.0.0-alpha-2

## Testcase

HTML file:
https://gist.github.com/takeya0x86/f8f1e61e6d5785a872081864ee96c714

```java
void testFullPageScreenshot() throws IOException {
  Firefox driver = new FirefoxDriver()
  driver.get("file:///path/to/screen_x_long.html");
  Path screenShot = driver.getFullPageScreenshotAs(OutputType.FILE).toPath();
  Files.copy(screenShot, Paths.get("sc01.png"));
  driver.quit();
}
```

## Trace-level log

[gecko_log.log](https://github.com/mozilla/geckodriver/files/3359568/gecko_log.log)

**Comment by whimboo** [comment]
Thanks! I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1571424 for that particular issue.

**Comment by whimboo** [comment]
This is now fixed in todays Firefox Nightly 73 build.
