### ISSUE TITLE
Session terminates after timout due to Polling for changes failed on dummy blocklist

### ISSUE THREAD

**Issue by TravFitz** [mozilla/geckodriver#1582]
GeckoDriver version: 0.24.0
Mozilla Firefox 67.0.4
Linux: 4.15.18-041518
Java 10.0.2
Selenium: 3.141.59

using driver.navigate().to("url") after page timeout or if page load takes too long (roughly 15 - 20 seconds) I receive an error when checking for polling changes that causes the session to drop and subsequent calls to the driver session to return NoSuchSessionExceptions.

Stack Log:
mozrunner::runner
INFO
Running command: "/usr/lib/firefox/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.Jvg57j5IiMuX"
1562724906474	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1562724906476 addons.webextension.screenshots@mozilla.org WARN Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1562724906477 addons.webextension.screenshots@mozilla.org WARN Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1562724913335	Marionette	INFO	Listening on port 39435
1562724913409	Marionette	WARN	TLS certificate errors will be ignored for this session
Jul. 10, 2019 12:15:13 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Page has timed out trying other avenues
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: http://%(server)s/dummy/blocklist//buckets/monitor/collections/changes/records?_expected=%221562719311956%22 is not a valid URL..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:203:13
1562724965445	Marionette	INFO	Stopped listening on port 39435
[Parent 7057, Gecko_IOThread] WARNING: pipe error (131): Connection reset by peer: file /build/firefox-ubqoiK/firefox-67.0.4+build1/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 357

Trace-log:
org.openqa.selenium.NoSuchSessionException: Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'mytim', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.18-041518-generic', java.version: '10.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 67.0.4, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20190620092152, moz:geckodriverVersion: 0.23.0, moz:headless: false, moz:processID: 7057, moz:profile: /tmp/rust_mozprofile.Jvg57j..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.15.18-041518-generic, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: c95b8132-6014-46b6-9b7b-c506185f0f70
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.getCurrentUrl(RemoteWebDriver.java:287)

**Comment by whimboo** [comment]
It's not a trace log and the blocklist error is not the reason for the session drop. Please attach a real [trace-level log] from geckodriver, which would help to further investigate the issue.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
No response from the reporter. Closing the issue.

**Comment by TravFitz** [comment]
Hi @whimboo, thanks for your assistance, I worked out what the issue was after enabling full stack trace.
It was occurring due to a redirect in the page that we where going to, it was not seeing the page as fully loaded after the redirect had occurred, thus timing out. Thank you again for your assistance.

**Comment by whimboo** [comment]
Ok, so did this page use the `http-equiv=refresh` method to redirect?

**Comment by TravFitz** [comment]
@whimboo not by the looks of it, it uses a server 301 with location redirect in the headers.

**Comment by whimboo** [comment]
So using that method might also cause a problem then. From that view it should be a dupe of #634.
