### ISSUE TITLE
The code doesn't go down

### ISSUE THREAD

**Issue by GandalfLiu** [mozilla/geckodriver#1583]
## System

* Version: 0.24.0
* Platform: redhat7.4
* Firefox: 62
* Selenium: 3.141

## Testcase
from selenium import webdriver
driver = webdriver.Firefox(executable_path="geckodriver_path")

## Trace-level log
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

![6WWQG1 70YR7LU7OY}N((%U](https://user-images.githubusercontent.com/42861671/60954820-35ee1b00-a332-11e9-9ff1-122a0f69bf6a.png)

This program has been stuck in   driver = webdriver.Firefox(executable_path="geckodriver_path")

**Comment by GandalfLiu** [comment]
## geckodriver.log
[Parent 24667, Gecko_IOThread] WARNING: pipe error (45): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

(firefox:27464): Gdk-ERROR **: The program 'firefox' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3070 error_code 3 request_code 10 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
ExceptionHandler::GenerateDump cloned child 28292
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
/usr/bin/firefox: line 2: 27464 Trace/breakpoint trap   (core dumped) /usr/lib64/firefox/firefox

**Comment by andreastt** [comment]
It looks to me like you’re trying to run the Linux version on Firefox on Windows, which is why the X server is complaining that it can’t start it.

In any case, this isn’t geckodriver related.
