### ISSUE TITLE
Marionette WARN Timed Promise timed out after 500 ms: stacktrace

### ISSUE THREAD

**Issue by michaljanjankowski** [mozilla/geckodriver#1584]
## System
* Version: geckodriver v0.24.0
* Platform: Windows 10
* Firefox: Firefox Quantum 68.0 (64-bit)
* Selenium: Python 3.4.0, Selenium 3.141.0

## Testcase
Problem happens, when trying to click in Add presentation "li" html tag:
"div class="popover-menu""
 "ul"
    "li" ... "/li"
    "li" Add presentation "/li"
    "li"  Duplicate presentation "/li"
"/ul"
"<" and ">" changed to chotation marks

I execute the following code file: selenium_utilities.py:
   try:
        element = WebDriverWait(page, 10).until(
            EC.element_to_be_clickable((By.XPATH,"//*[@class='popover-menu']/ul/li[text() = 'Add presentation']"))
        )
        logging.info("Element found {}".format(element.text))
        element.click()
        logging.info("and clicked in selenium_utilietes")
    except:
        logging.info("FAIL selenium_utilities.py 332")

In my test case log I observe, that webelement was successfully found and clicked :
selenium_utilities.py      331 INFO     Element found Add presentation
selenium_utilities.py      333 INFO     and clicked in selenium_utilietes

However in Firefox interaction seems to be stopped, and in geckodriver log I observe the following situation:
1) Element is found
2) Element is checked if it is displayed
3) Element is checked if it is enabled
4) For diagnostic reasons text is taken form this element, Text apears in the test log.
5) Element is clicked 
6) Promise timeout appears, and there is no interaction in web-browser

Very similar problem happens, when I try to use Python Selenium ActionChains. 
Here is geckodriver log part, from situation described in above points 1-6:

1563193979733	Marionette	DEBUG	0 -> [0,19,"WebDriver:FindElement",{"using":"xpath","value":"//*[@class='popover-menu']/ul/li[text() = 'Add presentation']"}]
1563193979738	Marionette	DEBUG	0 <- [1,19,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"a4959baa-477a-4689-8b8c-7eaaa4232928"}}]
1563193979732	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"a4959baa-477a-4689-8b8c-7eaaa4232928"}}
1563193979732	webdriver::server	DEBUG	-> GET /session/6671c2d0-16b0-4cd9-8c22-e48c69ceb396/element/a4959baa-477a-4689-8b8c-7eaaa4232928/displayed 
1563193979741	Marionette	DEBUG	0 -> [0,20,"WebDriver:IsElementDisplayed",{"id":"a4959baa-477a-4689-8b8c-7eaaa4232928"}]
1563193979753	Marionette	DEBUG	0 <- [1,20,null,{"value":true}]
1563193979748	webdriver::server	DEBUG	<- 200 OK {"value":true}
1563193979748	webdriver::server	DEBUG	-> GET /session/6671c2d0-16b0-4cd9-8c22-e48c69ceb396/element/a4959baa-477a-4689-8b8c-7eaaa4232928/enabled 
1563193979756	Marionette	DEBUG	0 -> [0,21,"WebDriver:IsElementEnabled",{"id":"a4959baa-477a-4689-8b8c-7eaaa4232928"}]
1563193979762	Marionette	DEBUG	0 <- [1,21,null,{"value":true}]
1563193979748	webdriver::server	DEBUG	<- 200 OK {"value":true}
1563193979763	webdriver::server	DEBUG	-> GET /session/6671c2d0-16b0-4cd9-8c22-e48c69ceb396/element/a4959baa-477a-4689-8b8c-7eaaa4232928/text 
1563193979765	Marionette	DEBUG	0 -> [0,22,"WebDriver:GetElementText",{"id":"a4959baa-477a-4689-8b8c-7eaaa4232928"}]
1563193979774	Marionette	DEBUG	0 <- [1,22,null,{"value":"Add presentation"}]
1563193979763	webdriver::server	DEBUG	<- 200 OK {"value":"Add presentation"}
1563193979763	webdriver::server	DEBUG	-> POST /session/6671c2d0-16b0-4cd9-8c22-e48c69ceb396/element/a4959baa-477a-4689-8b8c-7eaaa4232928/click {"id": "a4959baa-477a-4689-8b8c-7eaaa4232928"}
1563193979776	Marionette	DEBUG	0 -> [0,23,"WebDriver:ElementClick",{"id":"a4959baa-477a-4689-8b8c-7eaaa4232928"}]
1563193980296	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:223:64

## Stacktrace
From Selenium side there are no errors after try of click.

## Trace-level log
There is full geckdriver log in the attachment.
[geckodriver_20190716.log](https://github.com/mozilla/geckodriver/files/3396355/geckodriver_20190716.log)

**Comment by andreastt** [comment]
This is normally not anything to worry about. It is hard to detect if clicking an element causes navigation and we use a timeout for.

Is this causing any kind of behavioural difference? If so, we need to look closer.

**Comment by michaljanjankowski** [comment]
Yes. This cause that there is no click reaction in browser. Selenium makes click successfully, than this click is visible in geckodriver log, than this promise timeout happens and this click is not seen in browser and it is not seen in tested application. Despite the fact that element is clickable manually in this browser after the test.

**Comment by michaljanjankowski** [comment]
After further analysis of the problem, I have found a behavior that could lead to the root cause of the problem. When I make a click, that does not cause navigation traffic, I mean this click causes changes on given web page, than "Cancled page load lister because no navigation has been detected" print is showned in the log, like following:
1563292150341	Marionette	DEBUG	0 -> [0,16,"WebDriver:ElementClick",{"id":"1789ff2e-f29e-4a67-87d9-b26bbaa7a553"}]
1563292150565	Marionette	DEBUG	[6442450945] Canceled page load listener because no navigation has been detected

and the response for this Request commes back:
1563292150566	Marionette	DEBUG	0 <- [1,16,null,{"value":null}]

But the next try of click, that click is in Actions Chain or it is explicite: WebDriver:ElementClick, causes the timeout at once:
1563292150626	Marionette	DEBUG	0 -> [0,20,"WebDriver:PerformActions",{"actions":[{"actions":[{"duration":250,"origin":{"element-6066-11e4-a52e-4f735466cecf":"108 ... e"},{"duration":0,"type":"pause"},{"duration":0,"type":"pause"},{"duration":2000,"type":"pause"}],"id":"key","type":"key"}]}]
1563292150645	Marionette	WARN	TimedPromise timed out after 0 ms: stacktrace:

and there is no Response for this click Request or this Response comes after few timed outs. I would like to emphasize that this second try click is not realized in browser. Maybe because of earlier cancelation of page load lisner ?

**Comment by michaljanjankowski** [comment]
> This is normally not anything to worry about. It is hard to detect if clicking an element causes navigation and we use a timeout for.
> 
> Is this causing any kind of behavioural difference? If so, we need to look closer.

Hello Andreas, thank you for fast replay. I have given additional information in two below comments.

**Comment by whimboo** [comment]
Actions behave differently to Element Click, and are low level. It means that clicking a link will NOT wait for the page to be loaded. That's something you will have to check on your own. Only for Element click we kept this behavior for backward compatibility reasons. 

For reproduction it would be best if you could supply a real minimized HTML example.

**Comment by shinxi** [comment]
We're also facing some similar issue when selecting an item from AutoComplete result(we are using react-autocomplete component), steps:
1. Input some text and wait for the autocomplete result.
2. Select one item from the result.

And then below error throws.
> 1564546249636	Marionette	WARN	TimedPromise timed out after 500 ms: stacktrace:
bail@chrome://marionette/content/sync.js:223:64

**Comment by andreastt** [comment]
Without a reproducible test case, this is not an actionable issue. I’m happy to re-open it if one is provided.

**Comment by mixailom** [comment]
I am facing the same issue as @shinxi :

**Comment by andreastt** [comment]
@mixailom We can’t guess what that autocomplete drop-down looks like, i.e. we don’t have the source code or a document that show-cases the problem. This means we can’t reproduce the problem.

**Comment by mixailom** [comment]
I don't have permission to post our code, but you can use any amazon product page to reproduce the issue. Select any product, add it to the shopping cart and go to the cart and there is a drop-down to edit quantity of the product. Selenium will fail with exactly the same error. I hope this helps to reproduce the issue.

**Comment by andreastt** [comment]
Please read https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html about how to reduce and provide reproducible test cases.

**Comment by whimboo** [comment]
Please note that a follow-up issue with more data was created as #1608.
