### ISSUE TITLE
geckodriver not searching system path for Firefox binary on FreeBSD

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1585]
The code that geckodriver is using to locate the Firefox binary on the system is not as comprehensive as the code we were using in Selenium for the legacy Firefox driver.

I'm pulling out all of the binary location code from Ruby (https://github.com/SeleniumHQ/selenium/pull/7375) because this is the driver's responsibility. But we have this issue reported:
https://github.com/SeleniumHQ/selenium/issues/7219

Where Firefox binary was located here:
/usr/local/bin/firefox

...and geckodriver couldn't find it by default

It is also in PATH, but I know that Chromedriver also does not respect PATH when locating the Chrome/Chromium binary, so I don't think that is essential, but it's an option.

The intermediate fix is to tell users to specify the location in their code when passing in capabilities, but ideally geckodriver should support this at least as well as the old Selenium code did.

**Comment by andreastt** [comment]
The code that locates the Firefox binary can be viewed here:
https://searchfox.org/mozilla-central/source/testing/mozbase/rust/mozrunner/src/runner.rs#302-450
https://searchfox.org/mozilla-central/source/testing/mozbase/rust/mozrunner/src/path.rs

How we locate binary is described in detail on https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#binary.

Is this a FreeBSD specific problem? I see that runner.rs uses a Linux-specific build guard which could explain why it doesn’t search the system path.

**Comment by andreastt** [comment]
I’m not able to reproduce the problem if I put a Firefox binary in /usr/local/bin/firefox on Linux, which is another indication this could be non-Linux-but-still-Unix specific. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1566778.

**Comment by titusfortner** [comment]
It looks like this was fixed in 0.26 release
