### ISSUE TITLE
Include Cargo.lock file again

### ISSUE THREAD

**Issue by blodan** [mozilla/geckodriver#1586]
In release 0.23.0 and forward you seem to have stopped shipping the Cargo.lock file you are building your binaries with in both the source .tar.gz and .zip files.

Could you please add it back?

I'm the maintainer of the FreeBSD package and for version 0.23.0 and 0.24.0 I've kind of had to yolo some dependency versions because I don't know which versions you are building against.

**Comment by andreastt** [comment]
The canonical repository for geckodriver is https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver and it has the Cargo.lock file with the exact dependencies. We only use this GitHub repository for issue tracking and making releases through Travis.

See https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html for build instructions.

**Comment by blodan** [comment]
@andreastt there is no Cargo.lock file in the repository you linked, and how do i get the version of the 0.24.0 releae of the code from there? Neither the branches or tags seems to be reflecting a release?

So if we take the last release for example (0.24.0) how do i get the source out including the Cargo.lock file?

**Comment by andreastt** [comment]
geckodriver is part of a cargo workspace, so the Cargo.lock you’re looking for is here:
https://searchfox.org/mozilla-central/source/Cargo.lock

There are unfortunately no branches or tags linking to geckodriver releases in the Mercurial repository, but fortunately we started including the SHA1 the release made from starting with 0.24.0! It doesn’t look like this information made it over to https://github.com/mozilla/geckodriver/releases, but you can see it in the changelog: https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md#71

The commit you want to check out for 0.24.0 is 917474f3473e.

I’ll make sure the SHA1 gets put on the GitHub releases page from now on.
