### ISSUE TITLE
Implement W3C Actions API

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#159]
The marionette backend for this is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1292178
The WebDriver API patch is in https://github.com/jgraham/webdriver-rust/tree/actions

This blocks https://github.com/SeleniumHQ/selenium/issues/2285

**Comment by rajeshtaneja** [comment]
Can this be given some love, we have been stuck with FF 47.0.1 because we have lot of tests which depend on moveto and doubleclick.

**Comment by rafis** [comment]
Strange, but before Marionette, I don't remember technology name (maybe XUL Runner), this feature was working. Now I'm getting error `POST /session/0856e028-504a-7bd9-8198-d9dbc706f291/moveto did not match a known command`.

**Comment by pfrenssen** [comment]
Here is the PR for webdriver: https://github.com/mozilla/webdriver-rust/pull/23

**Comment by vikasvoladri** [comment]
In which version of Geckodriver will this issue be resolved? we have lot of tests which depend on actions class of selenium webdriver

**Comment by bocharsky-bw** [comment]
@vikasvoladri use Google Chrome for tests instead of FireFox. It works for me

**Comment by cylimaki** [comment]
Is there any plan to start to develop the Move To any time soon?  Is there a development schedule plan?  Would I be able to help the community develop this?

**Comment by jgraham** [comment]
We are aware that this is a high priority for many people and we are actively working on implementing the W3C standard API. Locking the issue to prevent more me-too comments.

**Comment by andreastt** [comment]
The relevant routing pieces have now landed in webdriver-rust and geckodriver. Parsing action chains and basic dispatching of keys have landed in Marionette.

**Comment by andreastt** [comment]
Firefox 52 (53?) onwards contains a mostly specification-conforming implementation of the W3C WebDriver actions API. I believe the Selenium language bindings are doing work to support this.

@mjzffr, can you give an update on the progress of this?

**Comment by mjzffr** [comment]
Firefox 52 Release and Firefox 52 ESR provide a mostly-conforming implementation with geckodriver 0.15 for key actions, pause, pointer actions (pointerType: mouse). 

Some fixes have been made beyond that and will be available with geckodriver 0.16 in Firefox 55, 54, mostly in 53 and the next ESR52.

Highest priority is to fix known issues with some synthesized key events (https://bugzilla.mozilla.org/show_bug.cgi?id=1332279) and mouse click with navigation (https://bugzilla.mozilla.org/show_bug.cgi?id=1345653) and to grow the existing suite of wdspec web-platform tests. 

Support for pen and touch pointerType will come next.

**Comment by AutomatedTester** [comment]
Closing this now as there is just follow up work that will happen in bugzilla. Selenium client bindings have been updated.
