### ISSUE TITLE
FIrefox/gheckodriver/web page opening and an error message display

### ISSUE THREAD

**Issue by KAHINA-kabyle** [mozilla/geckodriver#1590]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## code 

package automatichetest;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Myclass {

public static void main(String[] args) throws InterruptedException{
System.setProperty("webdriver.gecko.driver", "C:\\Users\\hb0501\\eclipse-workspace\\MyFirstTestProject\\lib\\geckodriver\\geckodriver.exe");	
WebDriver driver = new FirefoxDriver() ;
driver.get("https://www.seleniumhq.org/");
}
}

Error and web page opening
**1563458333728	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\hb0501\\AppData\\Local\\Temp\\rust_mozprofile.tkUomD4WkEnZ"
1563458334316	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1563458334316	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1563458334316	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1563458334316	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1563458336459	Marionette	INFO	Listening on port 53856
1563458336956	Marionette	WARN	TLS certificate errors will be ignored for this session
Jul 18, 2019 2:58:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFOS: Detected dialect: W3C**
****
Any solution please

**Comment by grizzlydevil** [comment]
System

    Version: Python 3.7
    Platform: Linux Mint 64bit
    Firefox: 68.0 (64-bit)
    Selenium: 3.141.0
    PyCharm: 2019.1.3 (Community edition)

code

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()

/home/meska/PycharmProjects/DS/venv/bin/python /home/meska/PycharmProjects/DS/start.py
Traceback (most recent call last):
  File "/home/meska/PycharmProjects/DS/start.py", line 4, in <module>
    driver = webdriver.Firefox()
  File "/home/meska/PycharmProjects/DS/venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/meska/PycharmProjects/DS/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/meska/PycharmProjects/DS/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/meska/PycharmProjects/DS/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/meska/PycharmProjects/DS/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities


Process finished with exit code 1

Any solution please

**Comment by andreastt** [comment]
The “TLS certificate errors will be ignored for this session” error is emitted when the `acceptInsecureCerts` capability is set to true.
