### ISSUE TITLE
geckodriver error while collecting data

### ISSUE THREAD

**Issue by managedb630** [mozilla/geckodriver#1591]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

![Screenshot from 2019-07-18 09-37-23](https://user-images.githubusercontent.com/52727662/61473576-480c3100-a9a4-11e9-80d3-26d2fa73d0d1.png)
![Screenshot from 2019-07-18 21-06-18](https://user-images.githubusercontent.com/52727662/61473578-48a4c780-a9a4-11e9-9b0a-683e5c947731.png)
![Uploading Screenshot from 2019-07-18 21-07-14.png…]()
![Uploading Screenshot from 2019-07-18 21-07-19.png…]()
![Uploading Screenshot from 2019-07-18 21-07-30.png…]()

**Comment by whimboo** [comment]
The first screenshot shows a list index out of bounds. I feel this is more a client issue, and not related to geckodriver at all. If it would, a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) would be necessary.
