### ISSUE TITLE
Navigation to docments served by HTTP/2 occasionally hang causes hangs

### ISSUE THREAD

**Issue by ptahchiev** [mozilla/geckodriver#1592]
## System

* Version: v0.24.0.linux-64
* Platform: Ubuntu Linux 18.0
* Firefox: 68.0
* Selenium: selenium-java/3.9.1
* Java 11

## Testcase

So with Java8 it all works fine, but I recently migrated to Java 11 and now my tests stop at random points in the code and refuse to continue.  The point of code almost always looks like this:
```
driver.get("some-page-here");
```

Also it seems to be OK with Chrome driver (although with Chrome driver I get other types of errors such as "element is not clickable") but at least it doesn't hang.
## Trace-level log
I have attached the trace log.

**Comment by ptahchiev** [comment]
[log.log](https://github.com/mozilla/geckodriver/files/3419181/log.log)

**Comment by ptahchiev** [comment]
Also I just remembered - with Java11 I have the HTTP2 enabled. Could this be the problem?

**Comment by ptahchiev** [comment]
Yes, I tested with Java11 and HTTP1.1 and it all seems to work fine. Again with Java11 and HTTP2 it hangs and stops responding.

**Comment by andreastt** [comment]
geckodriver serves HTTP/1.1, so your Java client can’t be communicating with it over HTTP/2. I don’t yet know why having a HTTP/2-enabled Java version should cause HTTP/1.1 to break, but I suspect this may not be the root of the problem.

From a quick glance at the logs, it looks like it hangs on navigation:

```
1563827194545   webdriver::server       DEBUG   -> POST /session/d9b2a878-47db-4a1a-b62f-9223c254997c/url {"url":"https://localhost:8112/storefront/en/US/checkout/login"}
1563827194547   Marionette      DEBUG   0 -> [0,20,"WebDriver:Navigate",{"url":"https://localhost:8112/storefront/en/US/checkout/login"}]
1563827194555   Marionette      TRACE   [4294967297] Received DOM event beforeunload for https://localhost:8112/storefront/en/US/Women%27s/Swim/Separates/Surfside-Halter-Bikini-Top/p/surfside-halter?site=samplestore-b2c
 2019-07-22 23:26:48,270 org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor [elasticsearch[4RwXJHa][management][T#2]] INFO : low disk watermark [85%] exceeded on [4RwXJHa6QiieL9CJkmaPGA][4RwXJHa][/home/petar/workspa
ce/nemesis-archetype/target/esindex/data/nodes/0] free: 56.7gb[12.5%], replicas will not be assigned to this node
[INFO] Listening for transport dt_socket at address: 8000
 2019-07-22 23:27:19,783 org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor [elasticsearch[4RwXJHa][management][T#2]] INFO : low disk watermark [85%] exceeded on [4RwXJHa6QiieL9CJkmaPGA][4RwXJHa][/home/petar/workspa
ce/nemesis-archetype/target/esindex/data/nodes/0] free: 56.7gb[12.5%], replicas will not be assigned to this node
 2019-07-22 23:27:49,788 org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor [elasticsearch[4RwXJHa][management][T#2]] INFO : low disk watermark [85%] exceeded on [4RwXJHa6QiieL9CJkmaPGA][4RwXJHa][/home/petar/workspa
ce/nemesis-archetype/target/esindex/data/nodes/0] free: 56.7gb[12.5%], replicas will not be assigned to this node
```

By the looks of it we see a `beforeunload` event for https://localhost:8112/storefront/en/US/Women%27s/Swim/Separates/Surfside-Halter-Bikini-Top/p/surfside-halter?site=samplestore-b2c, but never get any load events for https://localhost:8112/storefront/en/US/checkout/login. Does it hang at this exact location/document every time?

**Comment by ptahchiev** [comment]
Hi @andreastt  with selenium and gecko driver I'm testing a tomcat that has http2 enabled. If the tomcat serves the pages via HTTP1.1 all tests are fine. But if tomcat serves the pages via HTTP2, then the selenium tests hang. 
And no, they hang at different calls, but most of the time it is a place like this:
```
driver.get("some-page-here");
```

**Comment by whimboo** [comment]
@ptahchiev so what happens when you load those pages via HTTP2 manually in Firefox? Do those loads finish? Best use the developer tools to verify that.

**Comment by ptahchiev** [comment]
@whimboo  Yes they load, and they load faster I think :)

**Comment by andreastt** [comment]
> with selenium and gecko driver I'm testing a tomcat that has http2 enabled. If the tomcat serves the pages via HTTP1.1

Aha! Sorry, I completely misunderstood the premise of your bug report. I didn’t realise you were talking about the _web server_.

**Comment by whimboo** [comment]
With geckodriver we disable speculative connections by setting `network.http.speculative-parallel-limit` to `0`. What happens if you set this to `6` which is currently the default?

**Comment by ptahchiev** [comment]
Hi @whimboo how can I change this value?

**Comment by whimboo** [comment]
You can set preferences through capabilities. For an example and how the capabilities dict has to look like check https://firefox-source-docs.mozilla.org/testing/geckodriver/Capabilities.html#capabilities-example.

**Comment by ptahchiev** [comment]
Hello,
I tried setting this:
```
capabilities.setCapability("network.http.speculative-parallel-limit", 6);
```
but the result is still the same - it still hangs.

**Comment by whimboo** [comment]
Note, that this is not a capability but a preference. See https://seleniumhq.github.io/selenium/docs/api/java/ for the exact Java code examples.

**Comment by andreastt** [comment]
Specifically, this is the page you're looking for:
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxOptions.html

**Comment by ptahchiev** [comment]
But,
I'm doing the same just going through capabilities object:
```
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setJavascriptEnabled(true);
capabilities.setCapability("marionette", true);
capabilities.setCapability("acceptSslCerts", true);
capabilities.setCapability("network.http.speculative-parallel-limit", 6);
new FirefoxDriver(new FirefoxOptions(capabilities))
```
Still it hangs

**Comment by whimboo** [comment]
When Firefox is open and hanging, open `about:config` in a new tab and check if that specific preference has been set correctly. I don't use the Java bindings, so that logic you gave above is a bit strange. Also given that the `FirefoxOptions` are a subset of capabilities.

**Comment by ptahchiev** [comment]
![parallel-limit](https://user-images.githubusercontent.com/5320045/61824070-ce71b880-ae65-11e9-92d0-67ceda211aba.png)

**Comment by whimboo** [comment]
Ok, so it's something different. Mind creating a HTTP log? It can be done by just setting some env variables for Firefox. See the following page for details:

https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/HTTP_logging#Linux

Please note that the file will be large, and Github might not allow such a file to be attached. Usually zipping it might help.

**Comment by whimboo** [comment]
Another option would be to make a copy of the generated Firefox profile before the test finishes and the temporary profile gets deleted. I assume using that profile, a manual load of the HTTP2 resource is still causing a hang? If yes, there is a prefs.js file in that profile folder, which could be bisected. Once we know what preference is causing it, we could check for a solution. Thanks!

**Comment by ptahchiev** [comment]
[moz-log.zip](https://github.com/mozilla/geckodriver/files/3428604/moz-log.zip)

**Comment by ptahchiev** [comment]
I don't know how to make a copy of the generated Firefox profiles :(

**Comment by whimboo** [comment]
the location of the profile should be immediately visible in the geckodriver.log file. It's under the temporary folder. Then as best add a long sleep to the test, which will allow you to make a copy of it.

**Comment by whimboo** [comment]
There is actually nothing in the HTTP logs where I could get some info from. The time range is all from 20:07 to 20:09. So I hope we can figure out the problem by stripping down the used custom preferences.

**Comment by whimboo** [comment]
1.5 years passed-by without further reply from the reporter. I assume that this issue doesn't exist anymore, and as such closing it. If it still happens with recent Firefox releases please let us know.
