### ISSUE TITLE
Get error - AttributeError: 'TwitterBot' object has no attribute 'login' while making an Twitter bot using python

### ISSUE THREAD

**Issue by AxaySushir** [mozilla/geckodriver#1598]
## System

* Version: v0.24.0 win64
* Platform: Windows 10 + version 1903
* Firefox: 68.0.1 (64-bit)
* Selenium: version 3.141 

## Testcase

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time 

class TwitterBot:
    def __init__(self,username,password):
        self.username = username
        self.password = password
        self.bot = webdriver.Firefox()

def login(self):
    bot = self.bot
    bot.get('https://twitter.com/')
    time.sleep(60)
    email = bot.find_element_by_class_name('email-input')
    password = bot.find_element_by_class_name('session[password]')
    email.clear()
    password.clear()
    email.send_keys(self.username)
    password.send_keys(self.password)



td = TwitterBot('user@gmail.com', 'password')
td.login() 
```

## Stacktrace

C:\Users\baps\Desktop\Web app\machine learning>python app.py
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    td.login()
AttributeError: 'TwitterBot' object has no attribute 'login'

C:\Users\baps\Desktop\Web app\machine ### learning>

## Trace-level log
it only opens a blank firefox tab and then nothing happens

**Comment by whimboo** [comment]
This has nothing to do with Geckodriver but all about your Python code. Also as it looks like the `login()` method is not part of the TwitterBot class. For further questions and help please reach out to the Selenium forums. Thanks.
