### ISSUE TITLE
What's the mean  'FirefoxBinary' object has no attribute 'strip'?

### ISSUE THREAD

**Issue by passjwhub** [mozilla/geckodriver#1602]
## System

* Version:  v0.24.0
* Platform: macOS  10.14.4
* Firefox:  66.0a1
* Selenium: 3.141.0

## Testcase
I just run this
from lib.selenium import webdriver
from lib.selenium.webdriver import FirefoxOptions
from lib.selenium.webdriver.common.action_chains import ActionChains
from lib.selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from lib.selenium.webdriver.firefox.firefox_binary import FirefoxBinary
ff_mac_install_path = "/Firefox\ Nightly.app/Contents/MacOS/firefox"
ff_mac_bin_path = FirefoxBinary(ff_mac_install_path)
ff_option = FirefoxOptions()
catp = DesiredCapabilities().FIREFOX 
catp['marionette'] = False     
brewer = webdriver.Firefox(firefox_binary=ff_mac_bin_path, capabilities=catp, executable_path=oper_environment.ff_driver_path())
brewer.get('www.cnn.com')
brewer.quit()

## Trace-level log
webdriver.Firefox(firefox_binary=ff_mac_bin_path, capabilities=catp, executable_path=oper_environment.ff_driver_path(), firefox_options=ff_option)
  File "/lib/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    options.binary = firefox_binary
  File "/lib/selenium/webdriver/firefox/options.py", line 60, in binary
    new_binary = FirefoxBinary(new_binary)
  File "/3.6/lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 48, in __init__
    if not self._start_cmd.strip():
AttributeError: 'FirefoxBinary' object has no attribute 'strip'
ile object to redirect the firefox process output to. It can be sys.stdout.
                      Please note that with parallel run the output won't be synchronous.
                      By default, it will be redirected to /dev/null.
        """
        self._start_cmd = firefox_path
        # We used to default to subprocess.PIPE instead of /dev/null, but after
        # a while the pipe would fill up and Firefox would freeze.
        self._log_file = log_file or open(os.devnull, "wb")
        self.command_line = None
        if self._start_cmd is None:
            self._start_cmd = self._get_firefox_start_cmd()
        if not self._start_cmd.strip():
            raise WebDriverException(
                "Failed to find firefox binary. You can set it by specifying "
                "the path to 'firefox_binary':\n\nfrom "
                "selenium.webdriver.firefox.firefox_binary import "
                "FirefoxBinary\n\nbinary = "
                "FirefoxBinary('/path/to/binary')\ndriver = "
                "webdriver.Firefox(firefox_binary=binary)")
        # Rather than modifying the environment of the calling Python process
        # copy it and modify as needed.
        self._firefox_env = os.environ.copy()
        self._firefox_env["MOZ_CRASHREPORTER_DISABLE"] = "1"
        self._firefox_env["MOZ_NO_REMOTE"] = "1"
        self._firefox_env["NO_EM_RESTART"] = "1"

**Comment by passjwhub** [comment]
I was just use  concurrent.futures ProcessPoolExecutor  and async
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
File "/3.6/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
File "/ff_driver.py", line 317, in product_page_start
    brewer = webdriver.Firefox(firefox_binary=ff_mac_bin_path, capabilities=catp, executable_path= ff_mac_install_path)
File "lib/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    options.binary = firefox_binary
File"lib/selenium/webdriver/firefox/options.py", line 60, in binary
    new_binary = FirefoxBinary(new_binary)
FIle"lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 48, in __init__
    if not self._start_cmd.strip():
AttributeError: 'FirefoxBinary' object has no attribute 'strip'
"""

**Comment by andreastt** [comment]
This is a Python client issue and not related to geckodriver. My guess is that `FirefoxBinary` is a complex object and not a `string`, so does not implement `strip()`.

**Comment by passjwhub** [comment]
I had fixed the problems， its seems like  cause by the Firefox install path that was  include space like this "Firefox app"， I just re-install，its work now!
