### ISSUE TITLE
Unable to click on elements inside FRAME

### ISSUE THREAD

**Issue by DivyaJettigari** [mozilla/geckodriver#1603]
## System

* Version:  geckodriver version:0.24 
* Platform:  Windows  
* Firefox:  68 
* Selenium: selenium-java+ 3.141.59

## Testcase

Unable to click on element inside the Frame with above versions.
private DesiredCapabilities getFirefoxCapabilities() {
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability("marionette", true);
capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, getFirefoxOptions());
capabilities.setCapability("moz:webdriverClick", false);
return capabilities;
}

private FirefoxOptions getFirefoxOptions() {
	FirefoxOptions options = new FirefoxOptions();
	options.addArguments("--headless");
	options.setLogLevel(FirefoxDriverLogLevel.TRACE);
	return options;
}
and then
driver = new FirefoxDriver(getFirefoxCapabilities());

Please Suggest and let me if i'm missing something.
Find my attached full trace log.

## Trace-level log
[gecko.log](https://github.com/mozilla/geckodriver/files/3520046/gecko.log)

**Comment by andreastt** [comment]
This is not a reproducible bugs, i.e. you haven’t provided a reduced test case or a script that showcases the problem. Please read https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html on how to submit a reproducible test case.
