### ISSUE TITLE
Geckodriver not compatible in SunOS

### ISSUE THREAD

**Issue by satya-acharya** [mozilla/geckodriver#1604]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by andreastt** [comment]
SunOS is not a supported configuration, but you should be able to self-serve a build by following the instructions in https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html, provided SunOS is a supported toolchain by Rust (I didn’t check.)

**Comment by satya-acharya** [comment]
Thanks for your response. It's Oracle Solaris 5.11 (11.3 SPARC). I will try to follow your suggestion & if required will definitely need some guidance.

Thanks in advance!
