### ISSUE TITLE
Can anyone help me with Geckodriver build for Solaris OS

### ISSUE THREAD

**Issue by satya-acharya** [mozilla/geckodriver#1606]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by satya-acharya** [comment]
Below is my environment.
uname -r  
5.11 
cat /etc/release 
Oracle Solaris 11.3 SPARC
 
Geckodriver 0.17.0 or higher, Firefox 52.9.0 or higher, Python 2.7.14, Selenium 3.141.0

**Comment by andreastt** [comment]
Hi, I already answered this in https://github.com/mozilla/geckodriver/issues/1604.
