### ISSUE TITLE
SendKeys hangs in Firefox 69+ in settings area

### ISSUE THREAD

**Issue by mscrivo** [mozilla/geckodriver#1610]
## System

* Version: 0.24
* Platform: Windows 10 1903
* Firefox: 69.0 (64-bit)
* Selenium: C# 3.141.0

## Testcase

We have a tear down process in our test suite that clears all data in firefox after each run.  Essentially, the test tear down runs this function:

```C#
private static void CleanupFirefoxData(IWebDriver driver)
{
    driver.Navigate().GoToUrl("about:preferences#privacy");

    var elm = driver.FindElement(By.CssSelector("#clearSiteDataButton"));
    elm.Click();

    driver.SwitchTo().ActiveElement().SendKeys(Keys.Tab + Keys.Tab + Keys.Tab + Keys.Enter);
    driver.SwitchTo().Alert().Accept();
}
```

Which worked perfectly on Firefox 68 and lower, however, it has stopped working on Firefox 69 and (70 dev edition).  It now hangs indefinitely on this line:

`driver.SwitchTo().ActiveElement().SendKeys(Keys.Tab + Keys.Tab + Keys.Tab + Keys.Enter);`

even though I can see the line was executed properly, because the alert to confirm the deletion comes up when watching the test run.  Clicking on it manually, allows the cleanup to finish without issue, but without intervention it just hangs.

For reference, we based the cleanup process on this post: https://intoli.com/blog/clear-the-firefox-browser-cache/

## Stacktrace

> 2019.09.04 15:33:05.493    WARN Exception during TearDown: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:53728/session/5fbb236a-e7fd-4be2-8d52-cdf421a14523/element/5e86c33c-3044-4bbb-9bed-6ad1354c66fb/value timed out after 180 seconds.

## Trace-level log

Here are the logs from Firefox dev tools console, when the test runs:
[trace.log](https://github.com/mozilla/geckodriver/files/3576336/trace.log)

I've tried enable trace logs as per the docs, but am unable to get them from selenium.

**Comment by whimboo** [comment]
First you shouldn't use `about:preferences` to invoke any kind of action. If there is a need to clean-up another way has to be found. Btw. why aren't you creating a new profile, or use a pre-configured profile for each test? Is it maybe because the teardown has to run between each single test?

Note that cleaning the cache is basically an operation which needs chrome (not content) context privileges. And then it is a modal dialog and not an user prompt. That said the call to `activeElement` should fail given that modal dialog is open, and no switch to alert has been called before. 

Also the attached geckodriver log is less helpful given that it isn't a trace log, and also has been cut off a lot. See [our documenation](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) in how to request trace logs to be created.

**Comment by whimboo** [comment]
I tried to reproduce this problem with a Python test but I'm failing to port it. Not sure what the active element above is, but for me it's the search field inside the preferences. And when the `Clear Data` sub dialog has been opened, the active element hasn't changed. Now by sending 3x tabs, I end-up on the Firefox/Nightly icon inside the locationbar. Pressing Enter opens the site information panel.

**Comment by whimboo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1579814 might help here but implementing it isn't a high priority. 

So if you could try different Firefox 69 beta releases we could figure out which of the releases regressed for you. It makes it easier to find the regression range. https://bugzilla.mozilla.org/show_bug.cgi?id=1477977 might be a candidate but I cannot see right now, what specifically could have caused this.

**Comment by andreastt** [comment]
I think @whimboo’s suggestion in https://bugzilla.mozilla.org/show_bug.cgi?id=1579790 to restrict access to `about:*` pages in content context is reasonable.

Whatever happens beyond that with regards to Element Send Keys interaction in chrome context is undefined.

**Comment by mscrivo** [comment]
> First you shouldn't use `about:preferences` to invoke any kind of action. If there is a need to clean-up another way has to be found. Btw. why aren't you creating a new profile, or use a pre-configured profile for each test? Is it maybe because the teardown has to run between each single test?

Yes, we need to start from a clean slate for each test. Creating a new profile in between each test run takes way too long, so this was our compromise, especially given it had worked well up to Firefox 68.  If there's another way to completely clean the browser's history that doesn't take a long time to do, I'd be all for using it.

**Comment by mscrivo** [comment]
> So if you could try different Firefox 69 beta releases we could figure out which of the releases regressed for you

The issue happens on Firefox 69b3 (which was the earliest beta I could find on http://ftp.mozilla.org/pub/firefox/releases) ... and I just verified that it does not happen on Firefox 68.0.2.  Are

**Comment by whimboo** [comment]
Can you please also test the developer edition builds? Hopefully the first one doesn't already show the problem: https://archive.mozilla.org/pub/devedition/releases/

**Comment by mscrivo** [comment]
Just did, 69.0b1 from that link exhibits the problem.

**Comment by whimboo** [comment]
That means it regressed during the development when Firefox 69 was shipped as Nightly. If you have the time and energy to bisect the range, maybe with the help of [mozregression](https://pypi.python.org/pypi/mozregression/) that would be appreciated.

According to the [release calendar](https://wiki.mozilla.org/Release_Management/Calendar) build to test would be between 2019-03-18 and 2019-05-20. If you don't want to use mozregression with the `-c script` option, there is also [mozdownload](https://pypi.python.org/pypi/mozdownload) to download those builds.

**Comment by mscrivo** [comment]
Got it, the problem was introduced in this build:

http://ftp.mozilla.org/pub/firefox/nightly/2019/06/2019-06-14-10-00-22-mozilla-central/

This build, immediately before it, works fine:
http://ftp.mozilla.org/pub/firefox/nightly/2019/06/2019-06-13-21-53-35-mozilla-central/

**Comment by mscrivo** [comment]
@whimboo were you able to track it down with the above?

**Comment by mscrivo** [comment]
Seems like this has been fixed in Firefox 71 Dev edition

**Comment by whimboo** [comment]
Sorry for not getting back earlier. When I have a look to the above mentioned builds the changes which went into the failing build were:

https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=d72ab884f0394d6e9ab723f03bd43c90a84d7e5b&tochange=6c5b432d7460f7ffd715e988fa179a93d4f7e4ae

But I cannot find any change which could have affected the behavior of geckodriver and Marionette. Also interesting to hear that it now works with Firefox 71 dev edition.

As it looks like the problem has somewhat fixed, and we don't have to spend more time in investigating it. So thanks for your feedback!
