### ISSUE TITLE
Unexpected connnection refused on first spawn of geckodriver.

### ISSUE THREAD

**Issue by rasjani** [mozilla/geckodriver#1616]
## System

* Version: 0.25.0
* Platform: Windows
* Firefox: 68.0 
* Selenium: 3.41.0 Python

## Testcase

First off, this is really bad bug report, reason later:

Im running a test set in Azure Pipelines for osx/linux/windows and after the 0.25.0 release hit my pipeline, *first* time selenium started geckodriver, i get `WebDriverException: connection refused´ exception.

After the test run, when the pipeline wants to collect the build logs, geckodriver.log is still open/locked so, it almost feels like the geckodriver process is still running. And because i run on hosted agents, i just cant fetch those atm .. 

However, after pinning my geckodriver on windows to 0.24.0, i havent seen the issue.

**Comment by andreastt** [comment]
Are you having any problems starting the binary manually?  Is there a firewall on your system that blocks the new executable?

**Comment by rasjani** [comment]
I run Windows on azure because i dont have access to Windows.  Thus, checking if i can run things manually is a bit hard atm.  Considering that it is only the first invocation that fails (my tests open geckodriver around 24 times within the whole test run) I’d assume that it might not be windows firewall.  Now that the binary is signed - maybe there’s some delay when verifying the binary ? And since it’s already verified from the first run, consecutive launches don’t have that delay on the fresh image ?  But that’s just speculation - I don’t know anything about the topic.

**Comment by whimboo** [comment]
What does first run mean here? Is it the really first run of the binary, or does it also always happen after restarting Windows? Maybe you could use the [FileMon](https://docs.microsoft.com/en-us/sysinternals/downloads/filemon) tool from Microsoft, and figure out which exact system call/access fails?

**Comment by rasjani** [comment]
First Run in my scenario:

* Azure spins a new agent (fresh image, dunno if its booted up before or not).
* First test that requires firefox spawns geckodriver from selenium python api and fails and marking the testcase as failed
* Suite gets finished and new suite starts, new geckodriver is spawned, and it works.

Since i dont have access to windows devices and the tests on azure run on  hosted agents - to which i probably cant rdp into - i cant provide more details at this time.

**Comment by whimboo** [comment]
Given that you are running on Windows, could you check if the test builds on issue #1617 make a difference for you? See https://github.com/mozilla/geckodriver/issues/1617#issuecomment-536076417 for the links. Thanks.

**Comment by rasjani** [comment]
During my testrun, i launch geckodriver about 25 times and only the first launch seemed to be failing.  If the issue would be due to missing dll, i'd geckodriver wouldnt launch at all. 

But i can give a try but using a separate binary as its now shipped, will take time as i have to make changes to my ci pipeline..

**Comment by whimboo** [comment]
The only other thing might be related to the signed builds. Do you have access to the Windows Event viewer, or at least the logs from it? Maybe we can find some interesting info in there. Are on those workers running any kind of antivirus software?

**Comment by rasjani** [comment]
Im actually seeing this now in v0.24.0 too.  Not that often but its there.

**Comment by whimboo** [comment]
Can anyone please try the release candidate builds of geckodriver 0.26.0? I would like to know if those fix the problem for you all.

https://github.com/mozilla/geckodriver/releases/tag/v0.26.0

**Comment by rasjani** [comment]
so far looks good - no random failures..

**Comment by whimboo** [comment]
Great to hear that. So yes, lets close this issue.
