### ISSUE TITLE
Corrupted screenshots from Firefox 69 through latest Geckodrivers and Selenium APIs

### ISSUE THREAD

**Issue by alex4k** [mozilla/geckodriver#1619]
## System

* Version: 0.24, 0.25
* Platform: Windows 2012R2, Windows 10 
* Firefox:69
* Selenium:  3.141.0

## Testcase

I see a strange behavior for latest Firefox 69 with Geckodriver 0.25, 0.25 on Windows platforms (haven't checked on others). When I try to make screenshots for some SVG contents with highlighted areas through Selenium API, the resulting image does not contain highlighted areas or it is wrong. I have attached two SVG files (
[test-highlight.zip](https://github.com/mozilla/geckodriver/files/3633201/test-highlight.zip), 
[Single-Multiline.zip](https://github.com/mozilla/geckodriver/files/3633202/Single-Multiline.zip)
)  to reproduce the error and screenshots with results (
![test-highlight](https://user-images.githubusercontent.com/46774513/65281002-3973fe80-db3a-11e9-844a-38af2f753365.png)
![Single-Multiline](https://user-images.githubusercontent.com/46774513/65281015-41cc3980-db3a-11e9-982f-57d18a9bc245.png)

).
 This issue can be reproduced with the following python code:

from selenium import webdriver
from selenium.webdriver.firefox.options import Options

source_file = 'file://path_to_svg_file'
    opts = Options()
    opts.log.level = "trace"
    driver = webdriver.Firefox(options=opts)
    driver.get(source_file)
    time.sleep(10)
    driver.get_screenshot_as_file("screenshot.png")
    driver.quit()

## Stacktrace

no errors have been produced by the client-side

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/3633192/geckodriver.log)

**Comment by whimboo** [comment]
Did the same also happen with Firefox 68?

**Comment by alex4k** [comment]
No, it does not happen for Firefox 68.

**Comment by whimboo** [comment]
Would you mind testing the different Firefox 69 devedition builds to figure out when it actually started to happen? Please check build 1 first, and if it isn't affected do a bisect across all the different releases. All the builds can be found at https://archive.mozilla.org/pub/devedition/releases/. Thanks!

**Comment by alex4k** [comment]
Yes, sure we will check the dev builds and share results here!

**Comment by alex4k** [comment]
The first dev build where the issue raised is 69.0b1. It didn't happen in 68 dev builds and release one.

**Comment by alex4k** [comment]
The issue is still active with Geckodriver 0.26.

**Comment by whimboo** [comment]
Further changes to the screenshot feature have been made over the last Firefox releases. Can you please check again with the latest release or even beta? Thanks.

**Comment by whimboo** [comment]
Now I have tested both examples myself with Firefox 70, and it works as expected. It means that https://bugzilla.mozilla.org/show_bug.cgi?id=1559592 fixed that bug.
