### ISSUE TITLE
POST /session/foo/moveto did not match a known command

### ISSUE THREAD

**Issue by rustyx** [mozilla/geckodriver#1622]
## System

* Version: 0.24.0
* Platform: Windows 10 x64
* Firefox: 69.0.1 (64-bit)

## Testcase

Nightwatch spec:
```
this.test = function (browser) {
  browser
    .moveTo(null, 4, 4)
    .end()
}
```

Works fine on Chromedriver, fails on Geckodriver with:

`POST /session/abf4e8f7-f1c1-4206-99b0-0dce7b04e25c/moveto did not match a known command`

According to W3C, moveTo is a valid driver command:
https://drafts.csswg.org/cssom-view/#dom-window-moveto

Note: I do not use Selenium. The error comes from geckodriver itself:

```
$ curl -XPOST http://localhost:4444/session/abf4e8f7-f1c1-4206-99b0-0dce7b04e25c/moveto

{"value":{"error":"unknown command","message":"POST /session/abf4e8f7-f1c1-4206-99b0-0dce7b04e25c/moveto did not match a known command","stacktrace":""}}
```

**Comment by whimboo** [comment]
This is not a valid command as specified in the WebDriver specification. What you want is the `Set Window Rect` command instead:

https://w3c.github.io/webdriver/#set-window-rect
