### ISSUE TITLE
InvalidOperationException: Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: other os error (SessionNotCreated)

### ISSUE THREAD

**Issue by johnny0618** [mozilla/geckodriver#1624]
It runs very well on other machine with same win 10,but it does occurs in this machine.

## System

* Version: geckodriver-v0.25.0-win64
* Platform: Win 10
* Firefox: 69.0.1 (64)
* Selenium: 3.141

## Testcase

        FirefoxOptions options = new FirefoxOptions();
        options.BrowserExecutableLocation="C:\\Program Files\\Mozilla Firefox\\firefox.exe"; 
        options.LogLevel = FirefoxDriverLogLevel.Trace;
        string driverPath = FileUtil.getFileAssetsPath() + "Core\\Tools";
        IWebDriver driver=null;

        driver = new FirefoxDriver(driverPath, options); //<-Add your path

## Stacktrace

InvalidOperationException: Failed to start browser C:\Program Files\Mozilla Firefox\firefox.exe: other os error (SessionNotCreated)
OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError (OpenQA.Selenium.Remote.Response errorResponse)
OpenQA.Selenium.Remote.RemoteWebDriver.Execute (System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2 parameters)
OpenQA.Selenium.Remote.RemoteWebDriver.StartSession (ICapabilities desiredCapabilities)
OpenQA.Selenium.Remote.RemoteWebDriver..ctor (ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
OpenQA.Selenium.Firefox.FirefoxDriver..ctor (OpenQA.Selenium.Firefox.FirefoxDriverService service, OpenQA.Selenium.Firefox.FirefoxOptions options, TimeSpan commandTimeout)
OpenQA.Selenium.Firefox.FirefoxDriver..ctor (System.String geckoDriverDirectory, OpenQA.Selenium.Firefox.FirefoxOptions options, TimeSpan commandTimeout)
OpenQA.Selenium.Firefox.FirefoxDriver..ctor (System.String geckoDriverDirectory, OpenQA.Selenium.Firefox.FirefoxOptions options)

## Trace-level log

See https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
for how to produce a trace-level log.

Sorry I have added 	options.LogLevel =  FirefoxDriverLogLevel.Trace; but got no trace

**Comment by andreastt** [comment]
I suspect this may be related to https://github.com/mozilla/geckodriver/issues/1617. Could you try install the Visual Studio Redistributable Runtime and see if that makes a difference?

**Comment by johnny0618** [comment]
It works!Thank you!

**Comment by whimboo** [comment]
Please note that this is a bug in geckodriver 0.25.0. The dependency on the MSVC runtime package will be removed again with the 0.26.0 release. 

Marking as dupe of issue #1617
