### ISSUE TITLE
Geckodriver for raspberrypi 4

### ISSUE THREAD

**Issue by SG-aniki** [mozilla/geckodriver#1628]
tried https://github.com/mozilla/geckodriver/issues/1515 however no rust folders

info: updating existing rustup installation

Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
pi@raspberrypi:~ $ source $HOME/.cargo/env
pi@raspberrypi:~ $ ls
2019-09-14-213825_1024x768_scrot.png  Desktop    Public
2019-09-14-213826_1024x768_scrot.png  Documents  teamviewer-host_armhf.deb
2019-09-14-213829_1024x768_scrot.png  Downloads  Templates
2019-09-14-213830_1024x768_scrot.png  MagPi      Videos
2019-09-14-213854_1024x768_scrot.png  Music
2019-10-06-152230_1024x768_scrot.png  Pictures
pi@raspberrypi:~ $ cd ..
pi@raspberrypi:/home $ ls
pi
pi@raspberrypi:/home $

**Comment by andreastt** [comment]
You will find instructions building geckodriver for ARM here:
https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html

I hope this helps!

**Comment by SG-aniki** [comment]
before you close anything, have you tested on raspberry pi4?
this is stuck on step: source $HOME/.cargo/env

there is nothing!

https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html

**Comment by andreastt** [comment]
I don’t think sourcing the cargo environment is going to output anything. cargo is the Rust build- and package manager and sourcing $HOME/.cargo/env just makes sure these tools are available.

Next you’ll have to use rustup to install the right toolchain if cross-compiling, and call `cargo build` in the testing/geckodriver subfolder of your checkout of central.

**Comment by SG-aniki** [comment]
tried step by step 

stuck on step 5 here, no such directory, can you advice me please?

Put this in testing/geckodriver/.cargo/config:

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

**Comment by andreastt** [comment]
You have to create the directory and the file.

**Comment by SG-aniki** [comment]
@andreastt no good, thanks for helping, do you have a detail guide?

pi@raspberrypi:~/testing/geckodriver $ rustup target install armv7-unknown-linux-gnueabihf
component 'rust-std' for target 'armv7-unknown-linux-gnueabihf' was automatically added because it is required for toolchain 'stable-armv7-unknown-linux-gnueabihf'
pi@raspberrypi:~/testing/geckodriver $ sudo rustup target install armv7-unknown-linux-gnueabihf
sudo: rustup: command not found
pi@raspberrypi:~/testing/geckodriver $ cargo build --release --target armv7-unknown-linux-gnueabihf
error: could not find `Cargo.toml` in `/home/pi/testing/geckodriver` or any parent directory
pi@raspberrypi:~/testing/geckodriver $

**Comment by nestukh** [comment]
that guide isn't very well written.
here some instruction for raspberry pi (I've got a pi3)

```
sudo apt install -y gcc-arm-linux-gnueabihf libc6-armhf-cross libc6-dev-armhf-cross
git clone --depth=1 https://github.com/mozilla/gecko-dev
curl https://sh.rustup.rs -sSf | bash -s -- -v -y
declare -a bindirs=("$HOME/.cargo/bin")
if [[ "$(cat $HOME/.bashrc | grep -P "^PATH=" )" == "" ]]; then
  echo -e "PATH=\$PATH\n" >> $HOME/.bashrc
fi
for binfolder in "${bindirs[@]}"
do
  if [[ "$(cat $HOME/.bashrc | grep -P "^PATH=" | grep "${binfolder}:")" == "" ]]; then
    sed -i -e "s/^PATH=\"\(.*\)\"/PATH=\"$(echo "$binfolder" | sed "s/\//\\\\\//g"):\1\"/g" $HOME/.bashrc # place with no spaces in it
    export PATH="$PATH:$binfolder"
  fi
done
source $HOME/.bashrc
rustup target install armv7-unknown-linux-gnueabihf
echo -e "[target.armv7-unknown-linux-gnueabihf]
linker = \"arm-linux-gnueabihf-gcc\"" > "$HOME/gecko-dev/testing/geckodriver/.cargo/config"
cd "$HOME/gecko-dev/testing/geckodriver"
cargo build --release --target armv7-unknown-linux-gnueabihf
# test the binary executable with this command
$HOME/gecko-dev/target/armv7-unknown-linux-gnueabihf/release/geckodriver --version
```
