### ISSUE TITLE
v0.26.0 missing win64 build

### ISSUE THREAD

**Issue by hheexx** [mozilla/geckodriver#1630]
In github releases.

**Comment by andreastt** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1573798#c29.

**Comment by andreastt** [comment]
Presumably the `win32` package is in the mean time usable on Windows 64-bit due to the built-in multiarch support.

**Comment by hheexx** [comment]
I tried 32 but hit problem immediately.
https://github.com/mozilla/geckodriver/issues/1631


I'm not sure is it 0.26 problem or win32 problem.
I think it's 0.26 problem because as you say there should be no difference between 32 and 64.

**Comment by hheexx** [comment]
Nope. I tried now and it's bitness problem.
I tried 0.25.0 win32 and it throws InvalidOperationException

it's not the same.

**Comment by hheexx** [comment]
@andreastt When I switch  from 0.25x64 to 0.25x32  gecko driver won't start and creashes with exception: System.InvalidOperationException: Unable to find a matching set of capabilities (SessionNotCreated)

So 64 and 32 are not 'the same'.

**Comment by hheexx** [comment]
Maybe it searches for 32bit Firefox and can't find it ?

**Comment by whimboo** [comment]
Yes, this is most likely the problem if you are using a 64bit version of Firefox. 

I have uploaded the win64 binaries now, so you can download it from the 0.26.0 pre-release page.
