### ISSUE TITLE
Debian 10: Error on starting new session with v 0.26

### ISSUE THREAD

**Issue by dmlemeshko** [mozilla/geckodriver#1634]
## System

* Version: 0.26
* Platform: Debian 10
* Firefox: 69.0
* Selenium: selenium-webdriver: 4.0.0-alpha.5 (Node.js)

## Testcase

Error on starting a new session on **Debian 10**. It works perfectly on Debian 9, Oracle Linux 7, Centos 7, Ubuntu 16.04

The session is started this way:
```
const firefoxOptions = new firefox.Options();

firefoxOptions.headless();
firefoxOptions.set('moz:firefoxOptions', {
  log: { level: 'trace' },
});
const session = await new Builder()
  .forBrowser('firefox')
  .setFirefoxOptions(firefoxOptions)
  .setFirefoxService(new firefox.ServiceBuilder(geckoDriver.path)))
  .build(); 
```

**The issue is not reproduced with geckodriver 0.25**

## Stacktrace

```
10:21:48      │ERROR WebDriverError: invalid argument: can't kill an exited process
10:21:48      │          at Object.throwDecodedError (/var/lib/jenkins/workspace/elastic+kibana+pull-request/JOB/kibana-firefoxSmoke-7/node/linux-immutable/kibana/node_modules/selenium-webdriver/lib/error.js:550:15)
10:21:48      │          at parseHttpResponse (/var/lib/jenkins/workspace/elastic+kibana+pull-request/JOB/kibana-firefoxSmoke-7/node/linux-immutable/kibana/node_modules/selenium-webdriver/lib/http.js:563:13)
10:21:48      │          at Executor.execute (/var/lib/jenkins/workspace/elastic+kibana+pull-request/JOB/kibana-firefoxSmoke-7/node/linux-immutable/kibana/node_modules/selenium-webdriver/lib/http.js:489:26)
10:21:48      │          at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Trace-level log

```
12:27:01 1571135221124	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileeE630o"
12:27:01 1571135221127	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:36601
12:27:01 XPCOMGlueLoad error for file /opt/firefox-69.0/libxul.so:
12:27:01 libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
12:27:01 Couldn't load XPCOM.
12:27:01 1571135221428	mozrunner::runner	DEBUG	Killing process 3687
12:27:01 1571135221428	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}
```

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by dmlemeshko** [comment]
@whimboo I added trace log.

**Comment by whimboo** [comment]
Did you specify `/usr/local/bin/firefox` on your own? Does Firefox start when you use that command yourself? If yes, does it also work when you remove the `-headless` option? Maybe you don't have GTK installed on your system?

**Comment by andreastt** [comment]
This seems indeed to indicate that not all the runtime dependencies are installed:

```
12:27:01 XPCOMGlueLoad error for file /opt/firefox-69.0/libxul.so:
12:27:01 libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
12:27:01 Couldn't load XPCOM.
```

GTK depends on libdbus on Debian, so as @whimboo suggests, ensuring GTK is installed will likely resolve this.

**Comment by dmlemeshko** [comment]
Thank you for quick response, checking the workers

**Comment by whimboo** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1372998 for the known issue.

**Comment by dmlemeshko** [comment]
The problem was on our side. Thank you for the help
