### ISSUE TITLE
geckodriver 0.26.0 brew upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [mozilla/geckodriver#1635]
Relates to https://github.com/Homebrew/homebrew-core/pull/45217

## System

* Version: v0.26.0
* Platform: MacOS
* Firefox: 
* Selenium: 

It looks like there is no source code under the [tag v.026.0](https://github.com/mozilla/geckodriver/tree/v0.26.0). I wonder how we should proceed on the homebrew side.

**Comment by blshkv** [comment]
The archive 0.25.0 has a proper source and it possible to compile it. The latest 0.26.0 has an empty archive please check: https://github.com/mozilla/geckodriver/archive/v0.26.0.tar.gz

**Comment by gpragadheeswaran7** [comment]
Please unsubscribe me from this mailing list!

My email : g.pragadheeswaran@gmail.com

**Comment by whimboo** [comment]
Please note that I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1606297 to enhance the workflow for just building release builds of geckodriver.

**Comment by whimboo** [comment]
Dupe of issue #1695.
