### ISSUE TITLE
Drag and Drop Functionality is not working in Firefox

### ISSUE THREAD

**Issue by sumkumsum** [mozilla/geckodriver#1636]
## System

* Version: geckodriver v0.26.0
* Platform: Window 10
* Firefox: 68.1.0esr (64-bit)/ 69.0.2 (64 bit)
* Selenium: 
    selenium-java: 3.11.0
    selenium-api: 3.11.0
    selenium-firefox-driver : 3.141.59

## Testcase

Drag Drop is not working when action performed via selenium. Manually its working fine.
Please find the java code below. 
**Please note** same code is working fine in Chrome with Chrome Driver.

Also to run, please **change the path** of gecko-driver/chrome-driver as per your local machine.

```
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class DragAndDrop
{
    WebDriver driver;

    @Test
    public void DragnDrop()
    {
        System.setProperty("webdriver.gecko.driver", "C:\\GIT\\Jive\\geckodriver.exe");
        driver = new FirefoxDriver();

        //        System.setProperty("webdriver.chrome.driver", "C:\\GIT\\Jive\\chromedriver.exe");
        //        driver = new ChromeDriver();

        driver.get("http://demo.guru99.com/test/drag_drop.html");

        //Element which needs to drag.          
        WebElement From = driver.findElement(By.id("credit2")).findElement(By.tagName("a"));

        //Element on which need to drop.       
        WebElement To = driver.findElement(By.id("bank")).findElement(By.tagName("li"));

        //Using Action class for drag and drop.        
        Actions act = new Actions(driver);

        //Dragged and dropped.      
        act.dragAndDrop(From, To).build().perform();

    }
}
```

Run this code with firefox driver. It will not work but 
if you comment the geckodriver and 
uncomment the chrome driver than drag and drop functionality works as expected

## Reference html :

http://demo.guru99.com/test/drag_drop.html 

## Expected Output: 

BANK list item (marked in Orange) should be dragged and to be dropped  under account of debit side.

## Actual Output:

BANK list item is just selected and not moving to droppable area.

## Maven Dependencies
```
        <dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-java</artifactId>
	    <version>3.11.0</version>
       </dependency>
        <dependency>
	    <groupId>junit</groupId>
	    <artifactId>junit</artifactId>
	    <version>4.12</version>
	</dependency>
	<dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-firefox-driver</artifactId>
	    <version>3.141.59</version>
	</dependency>
```

## Trace-level log

[TRACE_LEVEL.log](https://github.com/mozilla/geckodriver/files/3743453/TRACE_LEVEL.log)

## Stacktrace

N/A

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by sumkumsum** [comment]
@whimboo ..Trace level log added.

**Comment by whimboo** [comment]
The failure as listed in the log is as following:

>> move target out of bounds","message":"(251, 736) is out of bounds of viewport width (1284) and height (735)

This means that the target of the d&d operation is happening to a location which is not inside the visible viewport. And it turns out just by 1 pixel. What happens when you just increase the window height before this operation so that the viewport gets larger? I assume that Chrome has a higher window size than Firefox by default? @sumkumsum let me know if that works.

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
