### ISSUE TITLE
Need support for IBM PPC64 machines

### ISSUE THREAD

**Issue by leofelipe222** [mozilla/geckodriver#1638]
I was unable to find a version of the binary that can be run on ppc64 architecture. 
Are there any plans to add such support?

**Comment by whimboo** [comment]
No, this architecture is barely used. But you can get the [source of geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html), and try a cross-compile yourself. As it looks like the `--target=powerpc-unknown-linux-gnu` should be used here.
