### ISSUE TITLE
Unable to launch browser (System.ComponentModel.Win32Exception (0x80004005))

### ISSUE THREAD

**Issue by cfnqueue** [mozilla/geckodriver#1640]
## System

* Version: .26 
* Platform: Windows Server 2012R2
* Firefox: 69.0.3
* Selenium: 3.414 

## Testcase
Currently attempting to use FirefoxDriver to launch a Firefox browser, navigate to a url, and perform actions. My application works in my local environment; a browser will launch successfully and navigate to the url. The browser will not start when installed on our test server. The returned error is:
System.ComponentModel.Win32Exception (0x80004005)

Are there additional permissions I can pass in the firefox driver options?

code sample:
```
using (var firefoxService = FirefoxDriverService.CreateDefaultService(Directory.GetCurrentDirectory()))
                    {
                        _logger.Debug("Service created");

                        var ffOptions = new FirefoxOptions();
                        
                        firefoxService.FirefoxBinaryPath = @"..\\..\\Mozilla Firefox\firefox.exe";
                        _logger.Debug("Looking for firefox in path: " + firefoxService.FirefoxBinaryPath.ToString());

                        ffOptions.AddArgument("--width=1");
                        ffOptions.AddArgument("--height=1");

                        _logger.Debug("Creating firefox driver");

                        using (var ffDriver = new FirefoxDriver(firefoxService, ffOptions, TimeSpan.FromSeconds(50)))
                        {
                            _logger.Debug("Driver created;");
                            ffDriver.Navigate().GoToUrl(url);
```

Thanks for the help.

**Comment by cfnqueue** [comment]
Hi andreastt, I confirmed that we are using the correct 64-bit binary on our 64-bit system. I also went and installed the visual studio redistributable. We are still receiving the same error when attempting to open the browser.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by cfnqueue** [comment]
I changed my approach and found that even trying to use Process.Start() fails to open a browser on the server, so that leads me to believe it is a system permission issue and not a gecko driver issue.

**Comment by whimboo** [comment]
Yes, that sounds right. You should solve this problem first. If there is still a problem with geckodriver afterwards just let us know. Until then I will close this issue.
