### ISSUE TITLE
Selenium Webdriver/Geckodriver unstable connection error

### ISSUE THREAD

**Issue by agatol4** [mozilla/geckodriver#1644]
## System

* Version: 0.26.0
* Platform: Windows 7
* Firefox: 70
* Selenium: Webdriver 2.50.0

## Testcase

I'm trying to run a selenium test using ruby. I have downloaded the most recent Geckodriver but, to get the test to run, I had to downgrade Selenium to 2.50.0 (When I had the most up-to-date Selenium, I was receiving an error stating that GeckoDriver couldn't be found; despite the driver being in the PATH).
Now though, the test initially works as it opens a Firefox browser but then just hangs - not redirecting to the url in the test file.
I get the following error:

 Selenium::WebDriver::Error::WebDriverError:    unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)

Is there a sprcific combination of Geckodriver, Firefox and Selenium Webdriver versions that will allow my test file to run?

Thanks in advance.

**Comment by agatol4** [comment]
[blog-test.txt](https://github.com/mozilla/geckodriver/files/3790902/blog-test.txt)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by agatol4** [comment]
Thanks for your response.
Feeling stupid but when I try to run 'geckodriver -vv' as specified in the link you gave I just get an error message of:
 'geckodriver' is not recognized as an internal or external command, operable program or batch file.'

Is there something more I need to have done? I have downloaded geckodriver then added it's location to PATH. Just feels like I haven't installed it properly.

**Comment by whimboo** [comment]
Can you run geckodriver.exe directly? If not maybe you don't have the Microsoft Visual Runtime installed? See issue #1617.

**Comment by agatol4** [comment]
I can get to this point
![image](https://user-images.githubusercontent.com/57188196/68163187-e4f1da80-ff51-11e9-84e9-99e5d93d67e8.png)

**Comment by whimboo** [comment]
In that case something is wrong with the PATH. Please double-check if the entry was added correctly.

**Comment by agatol4** [comment]
![image](https://user-images.githubusercontent.com/57188196/68163894-65fda180-ff53-11e9-9179-02f90110af8d.png)

![image](https://user-images.githubusercontent.com/57188196/68163924-731a9080-ff53-11e9-9d28-b5aa9ec40299.png)

**Comment by whimboo** [comment]
If there is a problem that geckodriver isn't found even in the path, that is outside the scope of this issue. Please try to solve that, and once done I would be happy to continue when being able to have a look at another trace log from version 0.26.0.

**Comment by whimboo** [comment]
You still didn't answer my question about the MSVC runtime (issue #1617)

**Comment by whimboo** [comment]
If you can launch geckodriver with a double click in the Windows Explorer the problem with the path is something totally different and outside of the geckodriver project. It's not actually something we can help you with that. But feel free to reply here once you figured it out.
