### ISSUE TITLE
firefox gets stuck and leaks 50mb/s when launched with -headless

### ISSUE THREAD

**Issue by mo** [mozilla/geckodriver#1646]
repro steps:
1. git clone git@github.com:mo/wdio-webdriver-geckodriver-firefox-memory-leak.git
2. npm install
3. npm test

actual:
Even though test case is just "open google.com and then wait 2 sec", Firefox gets stuck and leaks 50mb/s until crash. If I remove the "-headless" arg from moz:firefoxOptions (in wdio.conf.js) the same TC passes without problems. I see the bug in "htop" where the RES column keeps increasing aggressively:

https://i.imgur.com/CMd97Jw.png

Versions:
selenium 3.141.59 (pinned at the top of wdio.conf.js)
geckodriver 0.26.0 (pinned at the top of wdio.conf.js)
firefox 70 (which is what I have installed)

The bug repro project can also run with a custom Firefox binary if you set env var EE_FIREFOX_BINARY. For example, I can also repro the bug by running:

EE_FIREFOX_BINARY=~/firefox/65.0.2/firefox/firefox npm test

I have also tried various other combinations of selenium/geckodriver/firefox.

How can I tell what Firefox is doing?
How can I tell what Firefox is allocating?

**Comment by mo** [comment]
I tried to run Firefox with:
MOZ_LOG=timestamp,sync,nsHttp:5,cache2:5,DocumentLeak:5,PresShell:5,DocLoader:5,nsDocShellLeak:5,RequestContext:5,LoadGroup:5,nsSocketTransport:5

...and while it was taking 100% CPU and leaking 50mb/s it logged this:
http://temp.minimum.se/firefox-log.txt

**Comment by whimboo** [comment]
This sounds similar to what another user reported and which is tracked on https://bugzilla.mozilla.org/show_bug.cgi?id=1587698. The only difference here seems to be that you are using a different website.

Please have a look at comment 33 and if you could get this script integrated into your tests. Then call it maybe each second and let it write out a memory dump. It would be great to get the latest one before it crashes.

**Comment by mo** [comment]
I tried with nightly as of 2019-11-01 and I see the bug there as well.

I also tried this version of Firefox:
http://archive.mozilla.org/pub/firefox/releases/60.9.0esr/linux-x86_64/en-GB/firefox-60.9.0esr.tar.bz2
...and this version does NOT have the bug, it works perfectly in headless mode.

I tried to launch "firefox -headless http://google.com" straight from a terminal and this reproduces the bug. While I was getting coffee with it running, RES in htop ended up at well over 3GB.

I will have a look at the Marionette memory dumping script next.

**Comment by whimboo** [comment]
If you cold bisect the Firefox releases between 60 and 69 that would be great. It would be good to know when exactly it started to happen.

**Comment by mo** [comment]
@whimboo I can't figure out how to run the marionette script. Do you have a more complete marionette script that opens http://google.com or something?

**Comment by mo** [comment]
Bisection:

62.0.3 has NO bug
64.0.2 has NO bug
65.0 has the bug
65.0.2 has the bug

**Comment by mo** [comment]
65.0b10 has the bug
65.0b3 also has the bug

...and 65.0b3 is the earliest 65.x pre-release available on:
https://ftp.mozilla.org/pub/firefox/releases/

**Comment by mo** [comment]
nightly from 2018-11-14 did NOT HAVE the bug, i.e:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-14-10-02-26-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

nightly from 2018-12-01 had the bug, i.e:
https://archive.mozilla.org/pub/firefox/nightly/2018/12/2018-12-01-21-37-36-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

**Comment by mo** [comment]
this one does NOT HAVE the bug:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-14-22-29-27-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

this one has the bug:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-15-10-00-51-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

this one has the bug:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-15-22-34-44-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

nightly from 2018-11-16 had the bug, i.e:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-16-22-00-54-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

nightly from 2018-11-19 had the bug, i.e:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-19-10-04-48-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

nightly from 2018-11-23 had the bug, i.e:
https://archive.mozilla.org/pub/firefox/nightly/2018/11/2018-11-23-22-02-28-mozilla-central/firefox-65.0a1.en-US.linux-x86_64.tar.bz2

**Comment by mo** [comment]
So it seems the range is essentially around 14th - 15th november 2018. Anything that pops out in the hg logs?

**Comment by whimboo** [comment]
I have seen that you already commented on the bug which is great. Lets follow-up over there for further diagnostics. Thanks a lot!

**Comment by heilaaks** [comment]
The same problem (the CPU shoots up with > FF 64.0.2 headless mode) still seems to exist with Fedora. I have tested this with Fedora 32, 31 and 29. Here is a Dockerfile that can be used to repeat the problem with F31 or F32.

```
# Build container
#     docker build -f Dockerfile.ff.failure -t ff/test .
#
# Run container and attach to it
#     docker run -d --rm --security-opt seccomp:unconfined --name ff-test ff/test:latest
#     docker exec -it ff-test /bin/bash
# 
# Optionally upgrade the system
#     dnf upgrade --refresh
#
# Activate FF 64.0.2 and run test (works)
#     ln -s /usr/local/ff/firefox-64.0.2/firefox /usr/local/bin/firefox
#     exec ${SHELL}
#     firefox --version
#     python3.7 test-ff.py
#
# Activate FF nightly (fails)
#     rm -f /usr/local/bin/firefox
#     ln -s /usr/local/ff/firefox-nightly/firefox /usr/local/bin/firefox
#     exec ${SHELL}
#     firefox --version
#     python3.7 test-ff.py
#
# Stop container
#     docker stop ff-test


#FROM fedora:32
FROM fedora:31

RUN dnf install -y \
    bzip2 \
    firefox \
    findutils \
    grep \
    htop \
    iputils \
    net-tools \
    procps \
    procps-ng \
    python3.7 \
    strace \
    sysstat \
    which && \
    python3.7 -m ensurepip && \
    python3.7 -m pip install --upgrade pip setuptools && \
    python3.7 -m pip install --user selenium

WORKDIR /usr/local/ff
RUN echo -e "\
from selenium import webdriver\n\
from selenium.webdriver.firefox.options import Options\n\
options = Options()\n\
options.headless = True\n\
browser = webdriver.Firefox(options=options)\n\
browser.get(\"http://google.com\")\n\
print (\"Headless Firefox Initialized\")\n\
browser.quit()\n" > test-ff.py

RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -o geckodriver-v0.26.0-linux64.tar.gz && \
    curl -L https://ftp.mozilla.org/pub/firefox/releases/64.0.2/linux-x86_64/en-US/firefox-64.0.2.tar.bz2 -o firefox-64.0.2.tar.bz2 && \
    curl -L "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US" -o firefox-nightly.tar.bz2 && \
    tar -zxvf geckodriver-v0.26.0-linux64.tar.gz && \
    mv geckodriver /usr/local/bin

RUN tar xvjf firefox-64.0.2.tar.bz2 && \
    mv firefox firefox-64.0.2 && \
    tar xvjf firefox-nightly.tar.bz2 && \
    mv firefox firefox-nightly

CMD ["tail", "-F", "-n0", "/etc/hosts"]
```

**Comment by heilaaks** [comment]
The above comment is misleading. The testing was made with a Docker container on the same Fedora 29 host. The problem seems to be related to resources shared from host to containers and all the above scenarios were likely failing due to same issue.

I can confirm that this works with a patched Fedora 29.

I do not have competence to further analyze this but this may be related to networking/system calls. Here is a short strace attached from a FF 72.0a1 (nightly) when the problem is active.

[ff-nightly.log](https://github.com/mozilla/geckodriver/files/3839782/ff-nightly.log)

**Comment by whimboo** [comment]
@heilaaks, if the problem is fixed for you with a patches Fedora I would say the best solution is to file a bug on their bug report system? Or what exactly did you patch? You missed out that part.

Also as noted on https://bugzilla.mozilla.org/show_bug.cgi?id=1587698 the problem seems to be fixed when updating the system (Debian) to the latest version. As such I assume Fedora still misses such a patch?

I don't see why we have to keep this issue longer open. Thank you all for your help in investigating this problem.

**Comment by varesa** [comment]
FYI:

I'm on F30 and just rebooting my system seems to have fixed the issue (for now). I checked that I really am also on the same kernel as the previous boot (saved the version in a file).

Running kernel (again): 5.2.15-200.fc30.x86_64
