### ISSUE TITLE
Firefox crashes in a docker container on Debian 9:  dconf-CRITICAL **: 08:17:40.268: unable to create directory '/home/seluser/.cache/dconf': Permission denied.  dconf will not work properly

### ISSUE THREAD

**Issue by aditya2020** [mozilla/geckodriver#1647]
## System

* Version: 
* Platform:  PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
                     NAME="Debian GNU/Linux"
                    VERSION_ID="9"
                    VERSION="9 (stretch)"
                    ID=debian 
* Firefox: 
* Selenium: 
Docker Info : (using FROM selenium/standalone-firefox) 
docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:57:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

## Stacktrace

pdf-modifier    | (/opt/firefox-latest/firefox-bin:107): dconf-CRITICAL **: 08:17:40.268: unable to create directory '/home/seluser/.cache/dconf': Permission denied.  dconf will not work properly.
pdf-modifier    | 
pdf-modifier    | (/opt/firefox-latest/firefox-bin:107): dconf-CRITICAL **: 08:17:40.270: unable to create directory '/home/seluser/.cache/dconf': Permission denied.  dconf will not work properly.
pdf-modifier    | 
pdf-modifier    | (/opt/firefox-latest/firefox-bin:107): dconf-CRITICAL **: 08:17:40.284: unable to create directory '/home/seluser/.cache/dconf': Permission denied.  dconf will not work properly.
pdf-modifier    | 2019-11-02 08:17:40.727  INFO 1 --- [nio-8192-exec-1] 
pdf-modifier    | 1572682660982	addons.productaddons	INFO	Updates are disabled via media.gmp-manager.updateEnabled

## Trace-level log

pdf-modifier    | 2019-11-02 08:17:46.126  INFO 1 --- [nio-8192-exec-1] 
pdf-modifier    | 1572682666205	Marionette	INFO	Stopped listening on port 36993
pdf-modifier    | 1572682666303	addons.xpi	DEBUG	Calling bootstrap method shutdown on wikipedia@search.mozilla.org version 1.0
pdf-modifier    | 1572682666317	addons.xpi	DEBUG	Calling bootstrap method shutdown on webcompat@mozilla.org version 6.2.0
pdf-modifier    | 1572682666364	addons.xpi	DEBUG	Calling bootstrap method shutdown on twitter@search.mozilla.org version 1.0
pdf-modifier    | 1572682666366	addons.xpi	DEBUG	Calling bootstrap method shutdown on screenshots@mozilla.org version 39.0.0
pdf-modifier    | 1572682666369	addons.xpi	DEBUG	Calling bootstrap method shutdown on google@search.mozilla.org version 1.0
pdf-modifier    | 1572682666372	addons.xpi	DEBUG	Calling bootstrap method shutdown on formautofill@mozilla.org version 1.0
pdf-modifier    | 1572682666430	addons.xpi	DEBUG	Calling bootstrap method shutdown on ebay@search.mozilla.org version 1.0

pdf-modifier    | 1572682666431	addons.xpi	DEBUG	Calling bootstrap method shutdown on default-theme@mozilla.org version 1.0
pdf-modifier    | 1572682666433	addons.xpi	DEBUG	Calling bootstrap method shutdown on ddg@search.mozilla.org version 1.0
pdf-modifier    | 1572682666435	addons.xpi	DEBUG	Calling bootstrap method shutdown on bing@search.mozilla.org version 1.0
pdf-modifier    | 1572682666441	addons.xpi	DEBUG	Calling bootstrap method shutdown on amazondotcom@search.mozilla.org version 1.1
pdf-modifier    | JavaScript error: resource://services-settings/RemoteSettingsClient.jsm, line 149: Error: Unknown callback
pdf-modifier    | [Parent 45, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 728
pdf-modifier    | 
pdf-modifier    | ###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv

I see inside my docker container the dconf directory did get created :

total 20
drwx------ 5 seluser seluser 4096 Nov  2 08:17 .
drwxrwxrwx 1 seluser root    4096 Nov  2 08:17 ..
drwx------ 2 seluser seluser 4096 Nov  2 08:17 dconf
drwxr-xr-x 2 seluser seluser 4096 Nov  2 08:17 fontconfig
drwx------ 3 seluser seluser 4096 Nov  2 08:17 mozilla

I dont know why Marionette stops listening. I have the same setup in my own local MAC env MacOS Mojave 10.14.5 and the same test case works
Docker details :
docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by whimboo** [comment]
This is not a full tracelog. Some parts before Marionette stopped listening are missing. So please *attach* a full trace log. Don't add it as comment. Thanks.

**Comment by whimboo** [comment]
No further reply from the reporter. Closing the issue.
