### ISSUE TITLE
Unable to call Geckodriver from Command Line

### ISSUE THREAD

**Issue by agatol4** [mozilla/geckodriver#1649]
System

    Version: 0.26.0
    Platform: Windows 7
    Firefox: 70
    Selenium: Webdriver 2.50.0

Testcase

I have downloaded Geckodriver and added it's location to PATH but the command prompt error says that geckodriver is an unknown command.
What changes do I need to make?

![image](https://user-images.githubusercontent.com/57188196/68330324-f8748100-00ca-11ea-996f-e23f9808455e.png)

![image](https://user-images.githubusercontent.com/57188196/68330490-44bfc100-00cb-11ea-9f66-9e70fe27f335.png)

![image](https://user-images.githubusercontent.com/57188196/68330517-50ab8300-00cb-11ea-980a-5ec4dc5345b8.png)

**Comment by whimboo** [comment]
Please do not file dupes but keep the conversation in issue #1644.
