### ISSUE TITLE
Unable to set preferences 

### ISSUE THREAD

**Issue by ManthiraMani** [mozilla/geckodriver#1651]
## System

* Version:  0.24.0 
* Platform: Linux/Windows + 10
* Firefox: 68.1.0 
* Selenium: 3.14.0 

## Testcase

Unable to set preference to handle downloading files like excel, pdf, doc etc.  When i am trying to download  am  not able to complete the processes.

**Comment by whimboo** [comment]
This is not a support forum to request help. Also necessary information like source code, stacktrace, trace log haven't been provided. As such this issue is not actionable. 

Please note that setting preferences should be done via the Firefox options capabilities.
