### ISSUE TITLE
Unable to change History settings in gecko driver.exe

### ISSUE THREAD

**Issue by ManthiraMani** [mozilla/geckodriver#1652]
## System

* Version: Gecko Driver - 0.24.0 - Windows - 64
* Platform: Windows - 10 , Suse Linux,
* Firefox: 68.1.0
* Selenium: 3.14.0

## Testcase
In firefox browser I have changed "about:preferences#privacy"  to Use Custom settings for history.  But In gecko driver i am not able to change the same settings. It always shows "Remember History" 
My concern here how would i change to custom history?
 Kindly help me on this. I want to change my browser Setting > Privacy & Security > History

**Comment by whimboo** [comment]
This is not a support forum. Please see https://support.mozilla.org/en-US/ for help.
