### ISSUE TITLE
Files not getting downloaded as per FirefoxOptions - addPreference

### ISSUE THREAD

**Issue by ManthiraMani** [mozilla/geckodriver#1654]
## System
Version: 0.24.0
Platform: Linux/Windows + 10
Firefox: 68.1.0
Selenium: 3.14.0
Testcase

Files not getting downloaded  automatically.  like .excel, pdf, doc, html, .xls etc. 
![1573736162098](https://user-images.githubusercontent.com/38881746/68859134-a8ba3900-070c-11ea-966a-092fc71e399b.JPEG)
![1573736204603](https://user-images.githubusercontent.com/38881746/68859224-cf786f80-070c-11ea-99ce-8c7c07348a01.JPEG)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
