### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by medsouaidi** [mozilla/geckodriver#1655]
## System

* Geckodriver Version: 23 / 25
* Platform:  Linux 32 bit
* Firefox: 66 32 bit
* Python : 3.4.3 / 2.7.6
* Selenium: 3.141.0

## Testcase

from selenium import webdriver

driver = webdriver.Firefox()
    
url="https://www.baidu.com/"
driver.get(url)

## Stacktrace

i get this error !

Traceback (most recent call last):
  File "bing2.py", line 5, in <module>
    with webdriver.Firefox() as driver:
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by medsouaidi** [comment]
hi Whiboo thanks for your reply :100: 
the trace-level log : 

1573773476088	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilefrn6ez"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573773534072	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilewvAlai"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573773849360	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilev3tKDW"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573841440734	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile56H9Iw"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573841682107	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileE6bSHu"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573842423138	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile2TzF34"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573843838471	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile0wY0ys"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573844041896	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileet8eda"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573946191618	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilehFJfAw"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573946380134	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilerVrIHK"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573946825402	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile3T7QZz"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573947017357	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilePkUvFH"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1573947983237	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.xmiaPbusdNa5"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)
1574110025098	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.GdAtYp4TakZf"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/o which is owned by o.)

**Comment by whimboo** [comment]
I think the trace log is pretty clear in what's happening here. Did you check that yourself? See this line which repeats over and over again:

> Running Firefox as root in a regular user's session is not supported. ($HOME is /home/o which is owned by o.)

This is not a geckodriver issue, but a broken test setup on that machine.

**Comment by medsouaidi** [comment]
thanks .. i change the permission to my user "o" it's work right now thanks again :100:
