### ISSUE TITLE
[Suggestion] Catch end of load with FavIcon

### ISSUE THREAD

**Issue by nolme** [mozilla/geckodriver#1657]
Hi,

catching end of page load is a question often asked. There are many workaround solutions (wait time, searching for particular html tag...) but no real solution.
In my case, I saw on Firefox that FavIcon rendering in the tab indicate the page real end of load with all javascript (otherwise, there's a moving dot animation).

So, is there a way to implement a function which retrieve the FavIcon ?

Vincent

**Comment by andreastt** [comment]
Using the normal page loading strategy, WebDriver waits for `document.readyState` to be `complete` before returning from navigation. This marks that the document has been completely loaded and parsed, that the all sub-resources have finished loading, and that the DOM `load` event is about to fire. There are no further web-observable events to wait for.

What happens beyond this is within the control of the document. For example, many frameworks do additional manipulation of the DOM to set up the web application properly, which may include asynchronous loading of further resources. You need to explicitly wait for a ready event from the user JS or a state within your document to be sure the web application is ready for interaction.

**Comment by nolme** [comment]
I think I'm in the case of asynchronous loading because I already catch readyState and that's not enough. Can you be a bit more precise with your sentence "wait for a ready event from the user JS" ? I'm not sure to understand. Thanks.

**Comment by andreastt** [comment]
You need to make sure the web application either emits an event, or that it sets some state, to indicate it is ready for interaction.

How the web document behaves after having been loaded is beyond the control of the web browser, so the WebDriver program needs to synchronise the state directly with the document.
