### ISSUE TITLE
Downloading geckodriver... events.js:183

### ISSUE THREAD

**Issue by skazichris** [mozilla/geckodriver#1659]
## System

* Version: geckodriver@1.19.1
* Platform: Linux
* Firefox: 60.7.2esr (64-bit)
* Selenium: selenium-side-runner@3.15.0

npm install -g geckodriver
/usr/local/bin/geckodriver -> /usr/local/lib/node_modules/geckodriver/bin/geckodriver

> geckodriver@1.19.1 postinstall /usr/local/lib/node_modules/geckodriver
> node index.js

Downloading geckodriver... events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'geckodriver.tar.gz'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.19.1 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.19.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-23T14_05_12_170Z-debug.log

**Comment by andreastt** [comment]
I’m sorry, we don’t maintain any npm packages for geckodriver. You should report this issue to however maintains this.
