### ISSUE TITLE
Firefox/geckodriver does not recognize copy of Profile

### ISSUE THREAD

**Issue by chrismcmahon** [mozilla/geckodriver#1662]
I want to create a custom Firefox Profile that I can put in source control and use in arbitrary docker-selenium containers. My experience indicates that this is not possible, although one person claims to have done this.

My custom Profile differs from a standard Profile in two ways: it has a certificate installed (cert9.db file); and it has the preference for 'security.default_personal_cert" changed to "Select Automatically" (prefs.js)

I have two docker-selenium containers, both running the latest versions of docker-selenium. The source container is the standard Firefox Standalone Debug container https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneFirefoxDebug for which I have VNC access. 

The target container is a firefox_grid container that supports video, from the fork of docker-selenium here: https://github.com/elgalu/docker-selenium. I do not have VNC access to the target container, but I can get a shell there by using `docker exec -it firefox_grid_1 /bin/bash` and I can take a screenshot of the running browser there. Because one is a fork of the other, they are running the same version of Ubuntu and have the same version of Firefox (version 70 as I write this) and the same geckodriver.

In Firefox in the source container I install my certificate and change my preference. Using VNC I navigate Firefox to my target web page and confirm that the certificate and preferences are behaving as I expect. In `about:profiles` I confirm that only one Profile exists, and that it is named 'default-release' and that it is set as the default profile.

In a shell on the source image I do 'tar -czvf' on /home/seluser/.mozilla to create 'ffprofile.tar.gz' that contains the whole '.mozilla' directory.

I transfer the file ffprofile.tar.gz to my target system. There I have a Dockerfile that injects the whole `.mozilla` directory into the firefox_grid_1 image by doing `docker build -f Dockerfile -t has_ff_profile .`

```
FROM elgalu/selenium
USER seluser
ADD ff_profile.tar.gz /home/seluser/
```

I have a docker-compose.yml file where I point the Firefox image to `has_ff_profile`. I bring the grid up with that image. I use `docker ps` to confirm that my grid node is running the correct image.

In a shell on the source image I do `ls -al /home/seluser/.mozilla`. In a shell on the firefox_grid_1 target image I do the same command. The results are identical. Thus I expect that the Profile on the target image will behave in the same way as the Profile on the source image. I should be able to navigate to my web page that requires a certificate. 

I use Selenium with Ruby/Watir to launch a browser instance with `@browser = Watir::Browser.new :firefox, marionette: true, acceptInsecureCerts: true, url: "http://0.0.0.0:4444/wd/hub", profile: "default-release"` (Note: I have tried this with and without the 'profile' argument with the same result.) Upon navigating to my page that requires a certificate I get the Firefox error page that says "Secure Connection Failed An error occurred during a connection to myhost:myport. SSL peer cannot verify your certificate. Error code: SSL_ERROR_BAD_CERT_ALERT". 

I can't access the target image with VNC but I can take a screenshot of the "about:profiles" page: 
![one6_profile](https://user-images.githubusercontent.com/204643/69989136-36b16480-1500-11ea-8dc7-fb8aab77dc29.png)

Note that on the screenshot I do not see a notice saying "Profile: default-release/This is the profile in use and it cannot be deleted." Nor do I see the page say "Default Profile: yes". I see both of these things in `about:profiles` in Firefox in the source image. (Note: I also tried injecting the `.cache` directory as well as the `.mozilla` directory into the target image in my Dockerfile, with the same result.)

I would expect that having two identical Profiles in identical `.mozilla` directories on docker images running the same version of Ubuntu and the same version of Firefox would have identical behavior with regard to certificates and preferences, but that seems not to be true.

* For a detailed timeline of my working on this, as well as the original claim that manipulating a profile like this should work, see this issue reported against the elgalu fork of docker-selenium: https://github.com/elgalu/docker-selenium/issues/344
* For a possibly related bug reported by Titus Fortner as a result of my trying to get this to work in a different way, see https://github.com/mozilla/geckodriver/issues/1656

**Comment by whimboo** [comment]
You don't want to package everything below `.mozilla`. That is not going to work. Instead zip the specific profile folder with everything needed contained inside, and provide it as the base64 encoded string for the `profile` capability under [firefoxOptions](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions). As such the profile will be unzipped to a temporarily location, and used by Firefox.

**Comment by chrismcmahon** [comment]
I think what you are describing with the base64 encoded string for the profile capability is the issue that Titus Fortner reported in #1656 noted in my original report. I tried injecting the .mozilla directory only after exhausting every means to launch Firefox with a custom profile the way you describe. Again note that there is at least one reasonable claim that adding the whole .mozilla folder will work, although it may require circumstances I cannot create in place.

**Comment by chrismcmahon** [comment]
Also note that docker deploys the entire .mozilla directory, and Firefox *recognizes* the entire directory as a Profile. I would really like to know why Firefox does not *use* the Profile that it finds in the target docker image. If I knew where the relevant source code resides, I might even be able to find the line where that happens.

**Comment by titusfortner** [comment]
I don't think zipping the profile directory is a workable solution at this point. It is much too large to send remotely at this point. There needs to be a better solution

**Comment by chrismcmahon** [comment]
@whimboo you said "You don't want to package everything below .mozilla. That is not going to work."  Empirically I discovered that Firefox Profiles seem to only work on the host (or exact copy of the host) on which they are created. I am very curious about what software mechanism enforces that constraint. I am also curious about the reasoning behind this constraint. The indications from the browser drivers over the past several years is that there is no reason why Profiles should not be portable.

**Comment by chrismcmahon** [comment]
@whimboo Can you confirm for us that a Firefox instance launched from Selenium/geckodriver will *never* use a Profile, even if one exists, even if the existing Profile is set to 'default:yes', even if launched with an argument such as "profile: 'default-release'"? That seems to be my experience at this time.

**Comment by whimboo** [comment]
@chrismcmahon sorry that I dropped this issue for such a long time. You update went through unnoticed. :( I just read your initial comment again and saw that you were using the name of the profile for the `profile` capability. Note that geckodriver wants a path to that profile instead. It is not going to search on disk where a given profile might exist based on the provided name. Maybe that was the problem?
