### ISSUE TITLE
Headless geckodriver sometimes hangs before pageshow

### ISSUE THREAD

**Issue by andrewnicols** [mozilla/geckodriver#1663]
## Summary
When running geckodriver with a headless firefox session, the page sometimes hangs between `DOMContentLoaded` and `pageshow`.

I can replicate this reliably on _some_ of our CI nodes but not all of them. Rebooting the nodes allows the headless mode to work again.

## System

* Version: geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
* Platform: Linux (Docker)
* Firefox: 70.0
* Selenium: 3.141.59 but replicated direct with Geckodriver

## Testcase
Originally raised against https://github.com/SeleniumHQ/docker-selenium/issues/984 but have brought it here given it is possible to replicate this without Selenium.

```
#~/bin/bash

set -e

docker run \
    --rm \
    -d \
    --name selenium \
    -p 4444:4444 \
    -e START_XVFB=false \
    --shm-size=6g \
    -v `pwd`:`pwd` \
    selenium/standalone-firefox:3 \
        geckodriver \
	--host 0.0.0.0 \
	--log trace

function cleanup {
    echo "============================================================================"
    echo "Docker logs:"
    docker logs selenium
    docker stop selenium
}
trap cleanup EXIT
function fail {
    echo "============================================================================"
    echo "Docker logs:"
    docker logs selenium
    docker kill selenium
}
trap fail INT

sleep 4

echo "Creating session:"
SESSIONID=`curl -d '{"capabilities": {"firstMatch": [{"acceptInsecureCerts": false, "browserName": "firefox", "moz:firefoxOptions": {"args": [ "-headless"], "log": {"level": "trace"}}}]}}' http://localhost:4444/session | python3 -c "import sys, json; print(json.load(sys.stdin)['value']['sessionId'])"`
echo
echo
echo "Got a session with id '${SESSIONID}"

echo "Deleting cookies:"
curl -X DELETE "http://localhost:4444/session/${SESSIONID}/cookie"
echo
echo

echo "Fetching user agent:"
curl -d '{"script":"return navigator.userAgent;", "args": []}' "http://localhost:4444/session/${SESSIONID}/execute/sync"
echo
echo

echo "Setting windowrect:"
curl -d '{"width":1366, "height":768}' "http://localhost:4444/session/${SESSIONID}/window/rect"
echo
echo

echo "Setting URL:"
curl -d '{"url":"http:\/\/google.com\/"}' "http://localhost:4444/session/${SESSIONID}/url"
echo

echo "Deleting cookies:"
curl -X DELETE "http://localhost:4444/session/${SESSIONID}/cookie"
echo
echo

echo "Deleting window:"
curl -X DELETE "http://localhost:4444/session/${SESSIONID}/window"
echo
echo
```

## Stacktrace

None available.

### STDOUT

[gecko.log.txt](https://github.com/mozilla/geckodriver/files/3930251/gecko.log.txt)

### STDERR
Pertinent error log parts:
```
*** You are running in headless mode.
[Parent 12, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 728
[Parent 12, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 728
[Parent 12, Gecko_IOThread] WARNING: pipe error: Broken pipe: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 728

###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
```

Full error log also available, but it's 450MB which is primarily full of:
```
###!!! [Parent][MessageChannel] Error: (msgtype=0xA40001,name=PVsync::Msg_Notify) Channel error: cannot send/recv
```

**Comment by andreastt** [comment]
That looks like a Firefox crash to me. There’s some information in https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html how to get at crash dumps.

**Comment by andrewnicols** [comment]
Thanks @andreastt,

I've been trying to get the dumps without success. Not sure if I'm doing something wrong, but specifying a `-profile /tmp/gecko` option to the list of arguments just causes the curl to hang until it times out. I get a notification of headless mode in the geckodriver logs, the new profile directory is filled, and Firefox is shown as running in the process list, but I do not get a sessionid.

Any suggestions?

**Comment by andrewnicols** [comment]
I eventually managed to get the logs by moving the minidumps directory out of the profile and symlinking it back in place before I requested the URL.

Attached.      
[1663.zip](https://github.com/mozilla/geckodriver/files/3937647/1663.zip)

**Comment by andrewnicols** [comment]
https://crash-stats.mozilla.org/report/index/804666b6-3adb-4e4b-a607-25c610191209

**Comment by whimboo** [comment]
Great detective work @andrewnicols. That's pretty helpful. I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1602393 to cover this bug.

Would you mind doing the following checks if possible?

1) Run the tests with the most recent Firefox release v71.0, or even better with a Nightly build. Does it still happen?
2) Can you reproduce when running in non-headless mode?
3) Are all URLs affected?

**Comment by andrewnicols** [comment]
Thanks @whimboo,

I've tried with both nightly, and 71.0 and I'm not seeing this issue on those versions. Apologies for wasting your time.

For anyone else coming across this, I only saw this on headless mode, with or without xvfb available, and on all URLs that I tried.

Thanks for your help,

Closing.

**Comment by whimboo** [comment]
Great to hear! Thanks for checking.
