### ISSUE TITLE
Failed to decode response from marionette - only on single core VM

### ISSUE THREAD

**Issue by joerg1985** [mozilla/geckodriver#1664]
## System

* Version: 0.26.0
* Platform: Windows 10 / Version 1809
* Firefox: 71.0 (64-Bit) / 70.0.1 (64-Bit) (tried both)
* Selenium: Java 3.141.59

## Testcase

Not able to reproduce at a singe point, happens randomly while running tests on a single core VM with 8gb RAM, on a real machine everything works fine.

## Workaround 

Set the "Content process limit" to 1 and the issue is gone.
options.addPreference("dom.ipc.processCount", 1);

## Stacktrace

[ERROR]   00:00:36 -------- THROWABLE --------
[ERROR]            org.openqa.selenium.WebDriverException: Failed to decode response from marionette
[ERROR]            Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
[ERROR]            System info: host: '{removed}', ip: '{removed}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.5'
[ERROR]            Driver info: org.openqa.selenium.remote.RemoteWebDriver
[ERROR]            Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 71.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191202093317, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 10948, moz:profile: C:\Users\{removed}\AppData\Lo..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 556f08e0-844a-48f8-90ff-84d...}
[ERROR]            Session ID: 556f08e0-844a-48f8-90ff-84d3b8bfe0b0
[ERROR]            	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR]            	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR]            	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR]            	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[ERROR]            	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
[ERROR]            	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
[ERROR]            	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
[ERROR]            	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
[ERROR]            	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
[ERROR]            	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
[ERROR]            	at org.openqa.selenium.remote.RemoteWebElement.isSelected(RemoteWebElement.java:146)

## Trace-level log

1575654216885	webdriver::server	DEBUG	-> POST /session/556f08e0-844a-48f8-90ff-84d3b8bfe0b0/elements {
  "value": "#drop",
  "using": "css selector"
}
1575654216895	Marionette	DEBUG	0 -> [0,18,"WebDriver:FindElements",{"using":"css selector","value":"#drop"}]
1575654216897	Marionette	DEBUG	0 <- [1,18,null,[{"element-6066-11e4-a52e-4f735466cecf":"c005c0a2-d39b-4315-9905-1c9c7cfe004f"}]]
1575654216897	webdriver::server	DEBUG	<- 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"c005c0a2-d39b-4315-9905-1c9c7cfe004f"}]}
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1575654217210	Marionette	DEBUG	Closed connection 0
1575654217317	webdriver::server	DEBUG	-> GET /session/556f08e0-844a-48f8-90ff-84d3b8bfe0b0/element/c005c0a2-d39b-4315-9905-1c9c7cfe004f/selected 
1575654217317	webdriver::server	DEBUG	Deleting session
[Child 11832, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1575282935/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 4260, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1575282935/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341
[Child 4260, Chrome_ChildThread] WARNING: pipe error: 109: file z:/task_1575282935/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 341

**Comment by andreastt** [comment]
This sounds like a crash in the Firefox inter-process communication subsystem, and is therefore not directly related to geckodriver.

There’s some information over at https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html about extracting crash dumps when using geckodriver.

**Comment by joerg1985** [comment]
Hi, 

i tried to get a dump, but not successfull so far, could someone explain how to "hard-code the Marionette port so geckodriver can connect" using the Java bindings?

# hard-code the Marionette port so geckodriver can connect
    service_args=["--marionette-port", "2828"])

Thanks!

**Comment by whimboo** [comment]
Sorry but I don't use the Java bindings. But I assume you would need something around the GeckoDriverService: https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/firefox/GeckoDriverService.html

**Comment by joerg1985** [comment]
Thanks for the hint, i am still not able to create a dump due to following reason.

Only if i set profile.setPreference("intl.accept_languages", "de") the browser crashes, if the profile is set to an empty directory the browser does not crash.

This is the code i use to reproduce the issue on the VM:

`URL url = new URL("http://{your server}:4444/wd/hub");`
`FirefoxOptions options = new FirefoxOptions();`
`options.setBinary({your binary});`

`FirefoxProfile profile = new FirefoxProfile();`
`profile.setPreference("intl.accept_languages", "de");`
`options.setProfile(profile);`

`RemoteWebDriver driver = new RemoteWebDriver(url, options);`

`System.out.println("SID: " + driver.getSessionId());`

**Comment by whimboo** [comment]
You could add a delay in your test and grab a copy of the generated profile from the temp location. With that you should be able to run it via a custom profile, and fetch the crash reports.

**Comment by tkp-alhamsya** [comment]
The same problem here, geckodriver does not run on single core. Maybe more cores on the server will run smoothly.

**Comment by whimboo** [comment]
@joerg1985 have you had a chance to check my last comment?

**Comment by tkp-alhamsya** [comment]
> Hi,
> 
> i tried to get a dump, but not successfull so far, could someone explain how to "hard-code the Marionette port so geckodriver can connect" using the Java bindings?
> `# hard-code the Marionette port so geckodriver can connect`
> ` service_args=["--marionette-port", "2828"])`
> Thanks!

@joerg1985  I suggest for you, to use multiple core because my problem is resolved.

**Comment by 7up2008** [comment]
Is there any solution for workaround ?
I'm still facing this issue even though my VM is not single core ...

Mozilla Firefox 73.0.1
selenium==3.141.0
Python 3.5.3

**Comment by petersg45** [comment]
I have the same issue:
os.name: 'Linux', os.arch: 'amd64',
os.version: '3.10.0-514.el7.x86_64', 
java.version: '1.8.0_242' 
browserName: firefox, 
browserVersion: 65.0.2, 
moz:geckodriverVersion: 0.26.0
[2020-03-22 16:48:50,598] [WARN] com.blackducksoftware.qa.webdriver.library.WebDriverUtil [WebDriverUtil.java:156]: Caught Exception
org.openqa.selenium.WebDriverException: Failed to decode response from marionette

Happens every time browser is loading a table that has a certain amount of entries

**Comment by alhamsya** [comment]
@petersg45 Please run command `nproc` in the terminal

**Comment by petersg45** [comment]
4

**Comment by alhamsya** [comment]
> 4 From: Alhamsya Bintang Dyasta <notifications@github.com> Reply-To: mozilla/geckodriver <reply@reply.github.com> Date: Sunday, March 22, 2020 at 2:10 PM To: mozilla/geckodriver <geckodriver@noreply.github.com> Cc: Peter SanGiovanni <psangiovanni@blackducksoftware.com>, Mention <mention@noreply.github.com> Subject: Re: [mozilla/geckodriver] Failed to decode response from marionette - only on single core VM (#1664) @petersg45<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=NT7MQHYVLcCvJd-rZ5keLVt1Q6cYPksQUXYY802UkcM&e=> Please run command nproc in the terminal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664-23issuecomment-2D602249084&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=Otaaj8yWl3Z2CZX5qhRsIHNPDu6xBBVV2oC2ZfYAvEc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA6ANYOWJGD22KUMKG5NJUTRIZH6HANCNFSM4JW6HZGQ&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=6BOMQ8gnXJAjvUrKxZnSf-d65dWic2luPmmkGxqfDEw&e=>.

@petersg45  If so this problem is not a single-core VM. however caused versioning, you can try downgrade for selenium.

**Comment by petersg45** [comment]
How far down should I go?

**Comment by alhamsya** [comment]
> How far down should I go? From: Alhamsya Bintang Dyasta <notifications@github.com> Reply-To: mozilla/geckodriver <reply@reply.github.com> Date: Monday, March 23, 2020 at 1:21 PM To: mozilla/geckodriver <geckodriver@noreply.github.com> Cc: Peter SanGiovanni <psangiovanni@blackducksoftware.com>, Mention <mention@noreply.github.com> Subject: Re: [mozilla/geckodriver] Failed to decode response from marionette - only on single core VM (#1664) 4 From: Alhamsya Bintang Dyasta notifications@github.com<mailto:notifications@github.com> Reply-To: mozilla/geckodriver reply@reply.github.com<mailto:reply@reply.github.com> Date: Sunday, March 22, 2020 at 2:10 PM To: mozilla/geckodriver geckodriver@noreply.github.com<mailto:geckodriver@noreply.github.com> Cc: Peter SanGiovanni psangiovanni@blackducksoftware.com<mailto:psangiovanni@blackducksoftware.com>, Mention mention@noreply.github.com<mailto:mention@noreply.github.com> Subject: Re: [mozilla/geckodriver] Failed to decode response from marionette - only on single core VM (#1664<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=VPyfrogg9NoKGm2EUR2YHQwa2IduKfWKtv6mW83IlVI&e=>) @petersg45<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ryWYIJ2q8ZC8RMPOll34Z3u48zbRmuBqXcK92YxxWU0&e=>https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=NT7MQHYVLcCvJd-rZ5keLVt1Q6cYPksQUXYY802UkcM&e= Please run command nproc in the terminal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664-23issuecomment-2D602249084&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=Otaaj8yWl3Z2CZX5qhRsIHNPDu6xBBVV2oC2ZfYAvEc&e=, or unsubscribehttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA6ANYOWJGD22KUMKG5NJUTRIZH6HANCNFSM4JW6HZGQ&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=6BOMQ8gnXJAjvUrKxZnSf-d65dWic2luPmmkGxqfDEw&e=. @petersg45<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ryWYIJ2q8ZC8RMPOll34Z3u48zbRmuBqXcK92YxxWU0&e=> If so this problem is not a single-core VM. however caused versioning, you can try downgrade for selenium. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664-23issuecomment-2D602740126&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=mg40lqAea2cETOXXJg2jF1fMxxef8HzObQBoVlc7WIM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA6ANYMGZC4CPJYSNZDEGDLRI6K6FANCNFSM4JW6HZGQ&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ShNyOlNQiYEvEhyHDJwt2r-gVRS1YE83LD3Rux2MSDI&e=>.

you can try to check version run the terminal command like this `java -jar selenium-server.jar`

**Comment by alhamsya** [comment]
> How far down should I go? From: Alhamsya Bintang Dyasta <notifications@github.com> Reply-To: mozilla/geckodriver <reply@reply.github.com> Date: Monday, March 23, 2020 at 1:21 PM To: mozilla/geckodriver <geckodriver@noreply.github.com> Cc: Peter SanGiovanni <psangiovanni@blackducksoftware.com>, Mention <mention@noreply.github.com> Subject: Re: [mozilla/geckodriver] Failed to decode response from marionette - only on single core VM (#1664) 4 From: Alhamsya Bintang Dyasta notifications@github.com<mailto:notifications@github.com> Reply-To: mozilla/geckodriver reply@reply.github.com<mailto:reply@reply.github.com> Date: Sunday, March 22, 2020 at 2:10 PM To: mozilla/geckodriver geckodriver@noreply.github.com<mailto:geckodriver@noreply.github.com> Cc: Peter SanGiovanni psangiovanni@blackducksoftware.com<mailto:psangiovanni@blackducksoftware.com>, Mention mention@noreply.github.com<mailto:mention@noreply.github.com> Subject: Re: [mozilla/geckodriver] Failed to decode response from marionette - only on single core VM (#1664<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=VPyfrogg9NoKGm2EUR2YHQwa2IduKfWKtv6mW83IlVI&e=>) @petersg45<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ryWYIJ2q8ZC8RMPOll34Z3u48zbRmuBqXcK92YxxWU0&e=>https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=NT7MQHYVLcCvJd-rZ5keLVt1Q6cYPksQUXYY802UkcM&e= Please run command nproc in the terminal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664-23issuecomment-2D602249084&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=Otaaj8yWl3Z2CZX5qhRsIHNPDu6xBBVV2oC2ZfYAvEc&e=, or unsubscribehttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA6ANYOWJGD22KUMKG5NJUTRIZH6HANCNFSM4JW6HZGQ&d=DwMCaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=AZDwkFyiVAT0p0is8nbF74veHp_8PjCtuntdEuINvFo&s=6BOMQ8gnXJAjvUrKxZnSf-d65dWic2luPmmkGxqfDEw&e=. @petersg45<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_petersg45&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ryWYIJ2q8ZC8RMPOll34Z3u48zbRmuBqXcK92YxxWU0&e=> If so this problem is not a single-core VM. however caused versioning, you can try downgrade for selenium. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mozilla_geckodriver_issues_1664-23issuecomment-2D602740126&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=mg40lqAea2cETOXXJg2jF1fMxxef8HzObQBoVlc7WIM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AA6ANYMGZC4CPJYSNZDEGDLRI6K6FANCNFSM4JW6HZGQ&d=DwMFaQ&c=DPL6_X_6JkXFx7AXWqB0tg&r=WFHLM5pFu-w0EvPcaGRfKdIYZYQmk3QK1ZIgi5OfrtDaKBoe7Tfb5LgGmW3xrRG3&m=rlS0gzVEWcQBDtXX4eOd7p8wycEvzjfPgaARLVa6GAo&s=ShNyOlNQiYEvEhyHDJwt2r-gVRS1YE83LD3Rux2MSDI&e=>.

@petersg45 You can try to check version run the terminal command like this `java -jar selenium-server.jar`

**Comment by petersg45** [comment]
I have java 8 I was asking about version of selenium? I have 3.141.59 running currently

**Comment by whimboo** [comment]
No further reply from the reporter. So closing this issue.

For everyone else commented here. None of the comments are helpful given that there is no trace log given. Also each of you might face a different issue. So feel free to file a new issue specifically to your own problem.

**Comment by petersg45** [comment]
@whimboo can you point me in direction for getting a stack trace on docker? TIA

**Comment by whimboo** [comment]
Please have a look at https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html in how to create such a log. Thanks.

**Comment by petersg45** [comment]
I’ve tried quite a few attempts. I am running headless in a container on a build machine.  Tried writing out to /tmp but no luck getting any output.
If I’m in a container I’m thinking I need a way to write to file system. Directory is not being created.

**Comment by petersg45** [comment]
This is my Java Code right before crash happens.  It’s always when loading a Page that has a Table in it with certain amount of enties.


 File pathToGeckoDriver = new File(System.getProperty("user.home") + "/WebDriverDownloads/geckodriver_linux64-0.26.0.jar");

        File pathToBinary = new File("/opt/firefox/firefox-bin");

        // Custom profile folder to keep the minidump files

        final Path basedir = FileSystems.getDefault().getPath("/tmp");

        final String tmp_dir_prefix = ".selenium";

        Path tmp_dir = null;

        try {

            tmp_dir = Files.createTempDirectory(basedir, tmp_dir_prefix);

        } catch (IOException e) {

            // TODO Auto-generated catch block

            e.printStackTrace();

        }

        // Use the above folder as custom profile

        FirefoxBinary firefoxBinary = new FirefoxBinary(pathToBinary);

        firefoxBinary.addCommandLineOptions("-profile");

        firefoxBinary.addCommandLineOptions(tmp_dir.toString());

        // WebDriver webDriver = null;

        WebDriver webDriver = new FirefoxDriver(

                new GeckoDriverService.Builder()

                        .usingFirefoxBinary(firefoxBinary)

                        .usingPort(2828)

                        .usingDriverExecutable(pathToGeckoDriver)

                        .build());

**Comment by whimboo** [comment]
@petersg45 sorry but those problems are outside of geckodriver. It will create the log files on the same host it runs on. So you will have to figure out how to retrieve them.

**Comment by petersg45** [comment]
Are any of these the correct files to debug the crash for Failed to decode response from marionette issue I am having?

Thanks
Peter

**Comment by petersg45** [comment]
OK went into Safe Mode and filed crash report from there
efdde5e9-ec2e-4516-9c42-981810200328 is ID may have sent in 4 for same issue
How do I follow what happens next?

Much appreciation
Peter SanGiovanni

**Comment by whimboo** [comment]
@petersg45 your crash report can be found here:
https://crash-stats.mozilla.com/report/index/efdde5e9-ec2e-4516-9c42-981810200328

Which size of `dev/shm` do you have set? The default value might not be enough and you want to increase it. See https://github.com/SeleniumHQ/docker-selenium#running-the-images for details. If that is the case your case is covered by #285.

**Comment by petersg45** [comment]
It’s 2 GB

**Comment by petersg45** [comment]
I take that back let me check with releng team

Thanks
Peter

**Comment by whimboo** [comment]
@petersg45 which command actually causes this problem? Is it when taking a screenshot?

**Comment by petersg45** [comment]
No when loading the user page. Seems like the shared memory helped.
Fails right there when page is loading.  I have a video and can attach screenshot if you like.


From Test:

testDoc("Navigate to User Admin Page");

usersPageActions.navigateToPage();

**Comment by whimboo** [comment]
No, that's not necessary. If increasing the memory helped it's great to hear. Good we got this solved.
