### ISSUE TITLE
driver.manage().addCookie() hanging forever

### ISSUE THREAD

**Issue by ramsestom** [mozilla/geckodriver#1665]
When I try to add a cookie with `driver.manage().addCookie(mycookie)` the program is hanging forever and the code after this line is never executed.
I tried with a cookie retrieved from a previous selenium instance or with a manually set cookie (tried different combinations of domain/secure/httponly …) and the result is always the same

## System
* Version: 0.26.0
* Platform: Windows 10 Pro 64
* Firefox: 70.0.1 (64 bits)
* Selenium: java 3.141.5

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines]. Also running the test again with a more recent release of Firefox (71.0) or even a Nightly build would be appreciated.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by dagguh** [comment]
In my case `addCookie` was throwing:`org.openqa.selenium.InvalidCookieDomainException: Document is cookie-averse` and I swallowed the exception in some higher layer.

**Comment by whimboo** [comment]
No response from the reporter. Closing the issue.
