### ISSUE TITLE
segmentation fault geckodriver

### ISSUE THREAD

**Issue by lsq** [mozilla/geckodriver#1667]
## System

* Version:  0.26.0
* Platform:  android 9.0
* Firefox: firefox focus
* Selenium: 

## Testcase
> curl -v -d '{"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"androidPackage": "org.mozilla.focus","androidActivity": "org.mozilla.focus.GeckoViewActivity","androidIntentArguments": ["-d", "http://www.google.com"]}}}}' http://localhost:4444/session
\*   Trying 127.0.0.1:4444...
\* TCP_NODELAY set
\* Connected to localhost (127.0.0.1) port 4444 (#0)
\> POST /session HTTP/1.1
\> Host: localhost:4444
\> User-Agent: curl/7.67.0
\> Accept: */*                           
\> Content-Length: 212                       
\> Content-Type: application/x-www-form-urlencoded                                      
 \>                                    
 \* upload completely sent off: 212 out of 212 bytes                                      
\* Empty reply from server                
 \* Connection #0 to host localhost left intact                                          
 curl: (52) Empty reply from server

## Trace-level log
>geckodriver -v
1576111741730   geckodriver     DEBUG   Listening on 127.0.0.1:4444
1576111745765   webdriver::server       DEBUG       -> POST /session {"capabilities": {"alwaysMatch": {"moz:firefoxOptions": {"androidPackage": "org.mozilla.focus","androidActivity": "org.mozilla.focus.GeckoViewActivity","androidIntentArguments": ["-d", "http://www.google.com"]}}}}
[1]    16791 segmentation fault  geckodriver -v

**Comment by whimboo** [comment]
Please use `-vv` for tracing log output. Also how does your test look like? Can you paste a minimized version which still reproduces it?
