### ISSUE TITLE
Attach to already-running Firefox instance

### ISSUE THREAD

**Issue by wolfmanstout** [mozilla/geckodriver#1669]
I would like to attach WebDriver to an already-running Firefox instance that I've started myself separately from WebDriver. This is functionality that Chrome supports by starting Chrome with --remote-debugging-port=XXXX and then setting debuggerAddress=127.0.0.1:XXXX when connecting via WebDriver:
https://sites.google.com/a/chromium.org/chromedriver/capabilities

I scoured the web and couldn't find any way to do this in Firefox. There are examples of reusing a session that was started in an earlier WebDriver invocation, but there appears to be no way to reuse a Firefox instance that was started manually.

Note that this is something that Selenium team said can only be supported on a per-browser basis:
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/18#issuecomment-191402419

I'm aware of the caveats when reusing an existing Firefox instance and why this is generally not advisable for integration testing. I have found another valuable use case for WebDriver automation, though, and that is to enable voice-control of my browser (for accessibility reasons). In this scheme, it doesn't make sense to have to start Firefox via WebDriver. I realize that this is an unusual use case, but hopefully you will agree it's a a sign of success when a system is used in ways that the original developers had not imagined. Thus far, I've been using this functionality on Chrome and doing without it on Firefox, but recently I've added enough features that I will have to switch over if this is unavailable. I'm a big Firefox supporter so I'm hoping to avoid that.

Is this something you would consider supporting? Firefox already supports the --start-debugger-server <port> flag, so hopefully it would be possible to leverage that to connect a WebDriver client.

**Comment by whimboo** [comment]
geckodriver has the `--connect-existing` command line argument that can be used for that. Run `geckodriver --help` for a full list of available arguments.
