### ISSUE TITLE
firefox version and gecko driver mapping

### ISSUE THREAD

**Issue by bboycs** [mozilla/geckodriver#1670]
Hi, 
i would like to know is that any way to get the mapping of firefox version with supported gecko version.

As i know for chrome driver, we are able to start the webdriver-manager with argument version.chrome=<chrome version> and it will be able to download the respective chrome driver.

However for firefox, browser version is difference from gecko driver, so it will still require to manual work to check the gecko version when we install a difference firefox version.

Thank you very much

**Comment by andreastt** [comment]
Unlike chromedriver, a particular geckodriver is not tied to one specific version of Firefox.

New releases of geckodriver are generally backwards compatible with earlier Firefox versions, although you may of course find that features introduced in newer releases are not available in previous versions of Firefox.

You will find a support matrix in the geckodriver documentation:
https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

From this you can see that the latest release at the time of writing, 0.26.0, supports Firefox releases back to version 60. If you use 0.26.0 with Firefox < 60 you may find that certain features won’t work and in those cases you should consider using the geckodriver version listed in the support matrix.

**Comment by bboycs** [comment]
Thank you for the explanation
