### ISSUE TITLE
Firefox dies with "connection refused" error message

### ISSUE THREAD

**Issue by jsvachon2** [mozilla/geckodriver#1671]
## System

* Version: 0.26.0
* Platform:  AWS Linux 2
* Firefox: 71.0
* Selenium: Python 3.7.4 w/ selenium 3.141.0

## Testcase

from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import time

options = Options()
options.add_argument("--headless")
options.log.level="trace"
caps = webdriver.DesiredCapabilities().FIREFOX
caps["marionette"] = True
browser = webdriver.Firefox(options=options, capabilities=caps, executable_path=r"./geckodriver.exe")
browser.get('https://duckduckgo.com')
logo = browser.find_elements_by_css_selector('#logo_homepage_link')
print(logo[0].text)
browser.quit()

## Stacktrace

1576787942587   mozrunner::runner       INFO    Running command: "/usr/local/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilekIseS0"
1576787942592   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:41213

(firefox:12641): GLib-GObject-CRITICAL **: gtype.c:2722: You forgot to call g_type_init()

(firefox:12641): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed

(firefox:12641): GLib-GObject-CRITICAL **: g_object_new: assertion `G_TYPE_IS_OBJECT (object_type)' failed
1576788002686   mozrunner::runner       DEBUG   Killing process 12641
1576788002688   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"timeout","message":"connection refused","stacktrace":""}}

## Trace-level log

Could not be generated... I followed the guide but it barely changes anything to the geckdriver.log's content... I would be happy to get the trace for you 

## Other infos

I can start the geckodriver without any issue:

./geckodriver.exe -vv
1576788680316   geckodriver     DEBUG   Listening on 127.0.0.1:4444

I want/need to use FF in headless mode but starting FF without the headless mode and through xvfb gives the same result

**Comment by whimboo** [comment]
@jsvachon2  does AWS Linux 2 has the GTK packages installed? If not this is just https://bugzilla.mozilla.org/show_bug.cgi?id=1372998.

**Comment by jsvachon2** [comment]
I do have GTK installed...

rpm -qa|fgrep -i gtk
webkitgtk3-2.4.11-2.amzn2.0.1.x86_64
libdbusmenu-gtk3-16.04.0-4.amzn2.0.1.x86_64
gtk-update-icon-cache-3.22.26-4.amzn2.x86_64
libappindicator-gtk3-12.10.0-13.amzn2.0.1.x86_64
libindicator-gtk3-12.10.1-6.amzn2.0.1.x86_64
**gtk3-3.22.26-4.amzn2.x86_64**

**Comment by andreastt** [comment]
That Firefox fails to start on the system is not a geckodriver issue. I would recommend raising a bug against Firefox.
