### ISSUE TITLE
Getting error Service geckodriver unexpectedly exited. Status code was: 3221225595

### ISSUE THREAD

**Issue by Dmitry131** [mozilla/geckodriver#1672]
**##** System

* Version:  0.26.0
* Platform:  Win 10
* Firefox:  71.0
* Selenium:   3.141.0

## Testcase

from selenium import webdriver

driver = webdriver.Firefox()
driver.get('https://www.google.com')

## Stacktrace

self = <selenium.webdriver.firefox.service.Service object at 0x037160B8>

    def assert_process_still_running(self):
        return_code = self.process.poll()
        if return_code is not None:
>           raise WebDriverException(
                'Service %s unexpectedly exited. Status code was: %s'
                % (self.path, return_code)
            )
E           **selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 3221225595**

## Trace-level log

Could you help me resolve this problem? In system path was added route to my geckodriver file.
I'll be grateful !

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Dmitry131** [comment]
I resolved my issue via installing Microsoft Visual Studio redistributable
runtime. Thanks

**Comment by Dmitry131** [comment]
Fixed issue in my side

**Comment by whimboo** [comment]
Thanks. That makes it a dupe of #1617.
