### ISSUE TITLE
Component not initialized

### ISSUE THREAD

**Issue by mscrivo** [mozilla/geckodriver#1673]
## System

Version: geckodriver 0.26.0
Platform: Windows Server 2019
Firefox: 69.0.1+
Selenium: Selenium.WebDriver 3.141.0 (.net)

## Stacktrace

OpenQA.Selenium.WebDriverException : [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://marionette/content/modal.js :: get window :: line 199"  data: no]
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)

## Notes
- Not consistent, happens about every 2nd test run, somewhere in the middle of our test suite.
- Does not occur with Firefox 68 or lower

This is the exact same issue as reported in https://github.com/mozilla/geckodriver/issues/1623.  The only difference being that it was with the Java version of Selenium, instead of the .net one, so the problem is clearly not with Selenium, but with Firefox 69+.

I had commented on that issue, which I thought was a very relevant comment, that the proposed solution of setting `prompts.tab_modal.enabled=true` cannot be done in the .net selenium.  So I'm looking for an alternate solution.

Error when trying to set preference:

> System.ArgumentException : Preference prompts.tab_modal.enabled may not be overridden: frozen value=False, requested value=True

**Comment by whimboo** [comment]
Ok, I think the .net client also uses the generic preferences as set by Selenium for a new FirefoxProfile. As such your problem should be related to https://github.com/SeleniumHQ/selenium/issues/7776. 

To not be affected by that just let geckodriver create your Firefox profile, and don't do it via Selenium. See this [example](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#Example) in how to specify necessary preferences.

There is nothing we can do on our side. Turning this pref off is not supported.
