### ISSUE TITLE
No longer support arm7hf?

### ISSUE THREAD

**Issue by washmore** [mozilla/geckodriver#1674]
want a latest release for arm7hf.

**Comment by andreastt** [comment]
ARMv7 HF builds were depreated in September 2018:
https://lists.mozilla.org/pipermail/tools-marionette/2018-September/000035.html

You can however self-serve a build for ARM following these instructions:
https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html

**Comment by whimboo** [comment]
This is actually a dupe of #1515.

**Comment by Lennyz1988** [comment]
Run this script on your Raspberry in the /home/pi folder. This script will compile the geckodriver on the Raspberry Pi.

https://github.com/mozilla/geckodriver/issues/1628#issuecomment-543339232

Direct link:

https://gist.github.com/nestukh/4da25f3aa2360d770490ee434bff3dde#file-installheadlessfirefoxonpi-sh-L214
