### ISSUE TITLE
.click() event fails as part of Selenium test script

### ISSUE THREAD

**Issue by lysannef** [mozilla/geckodriver#1675]
## System

* Version: geckodriver 0.26.0 
* Platform: ppc64le
* Firefox:  68.3.0
* Selenium: 3.141.0
* Python 3.6

## Issue
The click event when executed as part of a selenium script  fails.
```
button = browser.find_element_by_xpath('//a[@id="quickstartButton"]')
button.click()
```
whereas if clicked manually works perfectly fine.

Observations from the networking tab are as follows.
As part of the selenium script , we get a 503 forbidden error

![ppc64le_failure](https://user-images.githubusercontent.com/43135876/72319292-cda73a00-36c4-11ea-902e-8c8e4de73b1e.PNG)

If I click the same button manually, we get a 200 ok

![ppc64le_manually_success](https://user-images.githubusercontent.com/43135876/72319380-0b0bc780-36c5-11ea-9812-4a6c90f1901c.PNG)

## Stacktrace
python3 google_test.py 
Traceback (most recent call last):
  File "google_test.py", line 33, in <module>
    WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, "logo")))
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/4057605/geckodriver.log)

Have we missed anything?

**Comment by whimboo** [comment]
Your version of Firefox is kinda outdated. Please upgrade to the latest release and try again. For more details of the timed out promise I would even suggest to test with a recent beta build. You can get one from here: https://www.mozilla.org/en-US/firefox/channel/desktop/#beta

**Comment by lysannef** [comment]
Working on the build of a higher version of Firefox. Will report the findings.

**Comment by lysannef** [comment]
@whimboo 
I upgraded my firefox build to version 72.0.
I am however getting the following error  when executing as non root user

```
Traceback (most recent call last):
  File "seleniumtest.py", line 12, in <module>
    browser = webdriver.Firefox(options=options)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
   raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

PFA the geckodriver.log file at a trace level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/4128334/geckodriver.log)



Using root , I get the following error :

```
*** You are running in headless mode.
1580305733355   mozrunner::runner       DEBUG   Killing process 2495
1580305733355   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}
```


Please let me know if I am missing something . 
Thanks !

**Comment by lysannef** [comment]
@whimboo  Just an update , the click event times out with the following error message 
```
 Canceled page load listener because no navigation has been detected
```
It seems to be similar to the issue https://github.com/mozilla/geckodriver/issues/1090 
PFA the geckodriver trace log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/4147891/geckodriver.log)

**Comment by whimboo** [comment]
@lysannef would you mind trying to send the click command for the quickstart button multipe times? Do none of those actually cause a click for you, or is at least one triggering the navigation?

**Comment by lysannef** [comment]
@whimboo  I have added 5 click events as well as a WebDriverWait(browser, 200).
However, each one of the click events times out and none trigger navigation.

**Comment by whimboo** [comment]
I tested that myself on MacOS and it works pretty fine. Given that you are on Linux maybe you can give us more details about your system. Which distribution are you using? Which window manager is in use? Does it also fail in headless? Does it only not work on this specific page, or are other URLs also affected?

**Comment by lysannef** [comment]
@whimboo  We are using the following system:

OS: **Linux** 
Distro: **CentOS**
Arch: **ppc64le**
Window Manager : **Vncserver /Viewer setup**

It gives the same error in headless mode . I have tried with multiple URLs . It loads the first page(using the url) , however any click( redirection to another page ) fails. 
It does not navigate.

If I manually click links via the browser  it works. Using the webdriver in a testing script however it throws this issue

**Comment by whimboo** [comment]
Interesting. So I assume there is some kind of problem in how this event is propagated, and this might be related to your VNC setup. Do you have a chance to directly try it out on that box without using VNC? Also when you are using the devtools in Firefox does calling `click()` on that element trigger the navigation? Or does that also fail?

**Comment by lysannef** [comment]
@whimboo , 
Okay, so we are just using vncserver to get a visual on what is happening when the Selenium script is being executed .It just gives a graphical user interface to the virtual machine we running firefox on.

We have tried it in headless mode, that does not use vnc setup. However, we see the same issue there as well.
When using devtools in Firefox, the click event triggers the navigation and moves to the next page .

**Comment by whimboo** [comment]
@lysannef ok, and executing a script like `document.getElementById("quickstartButton").click()` via geckodriver also works? If yes there might be a problem in how we synthesize the click event because `click()` doesn't just call `element.click()`. 

Do you have another machine and OS where you have the same problem?

**Comment by lysannef** [comment]
@whimboo I tried executing a script via geckodriver and it works.
```
driver.execute_script("document.getElementById('quickstartButton').click()")
```

I have also tried it using an ubuntu distribution. It fails with the same issue there as well. Have not tried it on any different OS.
I have tried the same on an x86-linux system and the geckodriver/click event works fine
Our end goal would be to run test cases on a linux -ppc64le architecture system

**Comment by whimboo** [comment]
@lysannef so you mean this is basically always failing on the ppc64le architecture, but not x86 or x86_64? If that is the case, I may have to ask you for some further help in digging deeper into the Marionette code, which is exercised by geckodriver. That will make it easier to debug, as having to provide try builds for Firefox with custom patches. Maybe you could even join us on irc.mozilla.org/#interop for a better and direct communication. Thanks!

**Comment by lysannef** [comment]
@whimboo  I can help with digging deeper into the Marionette code and the working on a ppc64le system.

> Maybe you could even join us on irc.mozilla.org/#interop for a better and direct communication. Thanks!

Will join the channel shortly and get in touch with you there.

**Comment by whimboo** [comment]
Hi @lysannef. We have seen us shortly on IRC. I wonder if you were able to make any progress in building Firefox and running some Marionette tests.

**Comment by lysannef** [comment]
@whimboo Yes I have been able to build firefox, however almost all my marionette tests are failing . 

```
./mach test testing/marionette/test/unit --sequential
 0:00.43 INFO Found node at /root/.nvm/versions/node/v10.19.0/bin/node
 0:00.43 INFO Found moz-http2 at /mozilla-unified/testing/xpcshell/moz-http2/moz-http2.js
 0:00.60 INFO Running tests sequentially.
 0:00.60 SUITE_START: xpcshell - running 15 tests
 0:00.61 TEST_START: testing/marionette/test/unit/test_action.js
 0:00.79 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:00.80 TEST_START: testing/marionette/test/unit/test_assert.js
 0:00.97 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:00.98 TEST_START: testing/marionette/test/unit/test_browser.js
 0:01.14 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:01.16 TEST_START: testing/marionette/test/unit/test_capabilities.js
 0:01.33 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:01.34 TEST_START: testing/marionette/test/unit/test_cookie.js
 0:01.50 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:01.51 TEST_START: testing/marionette/test/unit/test_dom.js
 0:01.69 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:01.70 TEST_START: testing/marionette/test/unit/test_element.js
 0:01.88 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:01.89 TEST_START: testing/marionette/test/unit/test_error.js
 0:02.05 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.06 TEST_START: testing/marionette/test/unit/test_evaluate.js
 0:02.23 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.24 TEST_START: testing/marionette/test/unit/test_format.js
 0:02.42 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.44 TEST_START: testing/marionette/test/unit/test_message.js
 0:02.62 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.62 TEST_START: testing/marionette/test/unit/test_modal.js
 0:02.81 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.81 TEST_START: testing/marionette/test/unit/test_navigate.js
 0:02.98 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:02.99 TEST_START: testing/marionette/test/unit/test_prefs.js
 0:03.16 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:03.17 TEST_START: testing/marionette/test/unit/test_sync.js
 0:03.33 TEST_END: FAIL, expected PASS - xpcshell return code: -11
 0:03.34 INFO INFO | Result summary:
 0:03.34 INFO INFO | Passed: 0
 0:03.34 INFO INFO | Failed: 15
 0:03.34 INFO INFO | Todo: 0
 0:03.34 INFO INFO | Retried: 0
 0:03.34 SUITE_END
 0:03.34 INFO Node moz-http2 server shutting down ...
 0:03.34
Overall Summary
===============

xpcshell
~~~~~~~~
Ran 15 checks (15 tests)
Expected results: 0
Unexpected results: 15
  test: 15 (15 fail)

Unexpected Results
------------------
FAIL testing/marionette/test/unit/test_action.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_assert.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_browser.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_capabilities.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_cookie.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_dom.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_element.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_error.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_evaluate.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_format.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_message.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_modal.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_navigate.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_prefs.js - xpcshell return code: -11
FAIL testing/marionette/test/unit/test_sync.js - xpcshell return code: -11
```

Is there something I'm missing ?

**Comment by whimboo** [comment]
@lysannef I was fixing a problem with element click recently and it's available in Firefox 82 beta 4. Can you please re-check if it is still a problem or fixed now? Thanks.

**Comment by whimboo** [comment]
Closing due to no reply from the reporter, and with the assumption this is fixed now.
