### ISSUE TITLE
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down 1579490633964

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [mozilla/geckodriver#1676]
## System

* Version: geckodriver-v0.24.0-linux64.tar.gz
* Platform: https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard/3.0
* Firefox: apt-get update && apt-get install firefox 
* Selenium: selenium-server-standalone-3.11.0.jar

## Testcase

I get the error when running Selenium tests in ruby capybara/rspec:

scenario 'Admin clicks contact', type: :feature, js: true do
      capy_login admin.username, admin.password
      visit_contacts_path contact
      
      sleep 1
      click_link contact.name # error happens right here!

## Stacktrace

```
[Parent 13179, Gecko_IOThread] WARNING: pipe error (83): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
1579490633964   Marionette  INFO    Stopped listening on port 34265

Right after this message, one of the tests fail:

1.1) Failure/Error: click_link contact.name

          Selenium::WebDriver::Error::InvalidSessionIdError:
            Tried to run command without establishing a connection
          # ./spec/features/contacts_spec.rb:114:in `block (3 levels) in <top (required)>'

1.2) Failure/Error: e = error

          Selenium::WebDriver::Error::InvalidSessionIdError:
            Tried to run command without establishing a connection
          # /root/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.4/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'

```
So I am pretty confidant the cause of the error is that Gecko error. Since this runs in an AWS CodeBuild Docker container, I do know the software running on the machine:

- apt-get -qq update
- apt-get -qq install build-essential libqt4-dev libxml2-dev libxslt1-dev nodejs xvfb firefox default-jdk libmagickcore-dev
- wget -qq "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz" -O /tmp/geckodriver.tgz
- tar zxf /tmp/geckodriver.tgz -C /usr/bin/
- rm /tmp/geckodriver.tgz
- wget -qq "https://selenium-release.storage.googleapis.com/3.11/selenium-server-standalone-3.11.0.jar" -O /usr/local/bin/selenium-server-standalone.jar
- DISPLAY=:1 xvfb-run --server-args="-screen 0, 1920x1080x24" java -jar /usr/local/bin/selenium-server-standalone.jar &

This error is causing my Selenium tests to fail very frequently. How can I fix the problem?

**Comment by whimboo** [comment]
You actually hit a crash of Firefox, and specifically of a tab. To retrieve more details about this crash please follow the instructions from https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html.

**Comment by whimboo** [comment]
I assume you don't hit this crash when not using xvfb? If yes, did you install a window manager like `fluxbox` for xvfb?

**Comment by lovefamilychildrenhappiness** [comment]
Sometimes the crash occurs in desktop environment (non-headless). But mainly it occurs when running headless using xvfb. You recommend to install fluxbox?

**Comment by whimboo** [comment]
It's small and doesn't add much overhead. Try it out if it works. If not, you can always remove it again. But please try to upload the generated minidump files, so that I can tell you more about the crash.

**Comment by Sakthi101088** [comment]
@whimboo 
Even i am getting the above error while executing the test in geckodriver. The same test cases are passed with chromedriver. If anyone got solution, please share with me too,

Environment Details:
1) Ubuntu 18.04.3 LTS - Docker container
2) Selenium Version -  3.11.0
3) Firefox Version - Mozilla Firefox 72.0.1
4) Gecko Driver Version - v0.25.0

**Comment by whimboo** [comment]
@Sakthi101088 please file your own issue, and add the details as requested via https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html. Thanks.

**Comment by whimboo** [comment]
Such a case simply shows that a web content process has crashed. There is nothing that we can do in geckodriver. If such an error raises the underlying issue in Firefox needs to be investigated and fixed.
