### ISSUE TITLE
Right click & mouse move of actions library is not working in Firefox browser using protractor

### ISSUE THREAD

**Issue by khizargujjar** [mozilla/geckodriver#1677]
**System:**
driver version: geckodriver 0.26.0 or geckodriver 0.25.0
Platform: Windows 10
Firefox: 69
Selenium: 3.141.59
protractor Version: 5.4.2
typescript

**Issue:**
When using 
await browser.actions().mouseMove(selector).perform();
await browser.actions().click(selector, protractor.Button.RIGHT).perform();

got this error for Firefox:
WebDriverError: HTTP method not allowed

While for Chrome same script is working fine

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by khizargujjar** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

**Comment by khizargujjar** [comment]
I got locator error now with different version
![picturemessage_wnfrbf0f a1a](https://user-images.githubusercontent.com/24990548/73007860-1a121880-3e2f-11ea-94f1-c4ef0396faf7.png)

While same locator working fine with Chrome

**Comment by khizargujjar** [comment]
With gecko 0.26.0, For this script
        

> await browser.actions().mouseMove(quinclogo).perform();
>         await browser.sleep(2000);
>         await browser.actions().click(quinclogo, protractor.Button.RIGHT).perform();

I got this error
![rect](https://user-images.githubusercontent.com/24990548/73008164-c81dc280-3e2f-11ea-8c29-4dc6d3ec8198.PNG)

And it left click on given locator rather than right click.
