### ISSUE TITLE
Feature: option to disable navigator.webdriver == true ?

### ISSUE THREAD

**Issue by hheexx** [mozilla/geckodriver#1680]
Is there any plan to support flag that disables navigator.webdriver property that screams to sites that they are run in selenium?

Chrome has similar flag (disable-automation)

**Comment by whimboo** [comment]
I cannot find that Chrome has such an option. Can you please point to the documentation?

**Comment by hheexx** [comment]
Sure. 
https://stackoverflow.com/a/57304986/2406518
https://stackoverflow.com/a/56635123/2406518


I think you should also add disable-automation or similarly named parameter that controls all modifications you do to webdriver controlled browser compared to vanilla.

**Comment by whimboo** [comment]
This page doesn't list any `disable-automation` flag, and also doesn't say anything about `navigator.webdriver`.

**Comment by hheexx** [comment]
I'm looking now, I read it wrong. Here https://stackoverflow.com/a/56635123/2406518
I didn't saw it's no longer possible from version 79.

Anyway, it still disables all other modifications. I need to have environment as close as possible to vanilla browser. 

There is no disable-automation flag, they exclude enable-automation flag but the result is the same.

I can modify navigator.webdriver with a extension. Can you add switch that disables all other changes that are not required?

**Comment by whimboo** [comment]
Ok, so Chrome doesn't allow this also. And that is because the WebDriver spec defines that property on the Navigator object, which has to be set to `true` when tests are running with webdriver enabled:

https://w3c.github.io/webdriver/#interface

Implementations have to be conformant to this requirement. As such we will not provide a way to circumvent that.

**Comment by ScamCast** [comment]
In firefox (about:config), there is a "dom.webdriver.enabled" option that you can disable.

Also you can set this with "add_experimental_option" (python)

```
options= Options()
options.add_experimental_option("prefs", {
    "dom.webdriver.enabled": False,
})
driver = webdriver.Chrome(CHROME_DRIVER, options=options)
```

**Comment by ep0x** [comment]
Options.AddArgument("--disable-blink-features=AutomationControlled");
Try this

**Comment by ScamCast** [comment]
@ep0x that's for Chrome only.

I had commented the same thing above, but they deleted it for some reason.
