### ISSUE TITLE
getGroupParticipantIDs Timed out after 500000 ms

### ISSUE THREAD

**Issue by mhndm** [mozilla/geckodriver#1681]
## System

* Version: geckodriver 0.24.0
* Platform: Linux
* Firefox: 61

when i try to get many elements i get very long time out  500000 ms
how i can decrease the time out to 10 seconds ?

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Also please upgrade both geckodriver and Firefox to the most recent releases before creating the log.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
