### ISSUE TITLE
Not able to fetch browser/console logs using geckodriver

### ISSUE THREAD

**Issue by parth7695** [mozilla/geckodriver#1682]
## System

* Version: 0.26.0 
* Platform: Ubuntu 18.04/ Windows 10
* Firefox: 72.0.1
* Selenium: client + version

## Testcase

I have been wanting to fetch the browser/console error logs using selenium/geckodriver on firefox and it just doesn't work. I know there have been certain discussion threads about this issue, but I believe this feature for log interface is not yet supported (correct me if I am wrong), as I have tried multiple ways and workaround to get my thing working, but it doesnt, whereas fetching browser logs from chrome via selenium works like a charm. This testing is really critical and would want to know from anyone or the geckodriver dev community as to how can I get this working. My requirement is just a basic feature where in I can fetch browser/console error logs from firefox in an automated fashion.

**Comment by whimboo** [comment]
We only offer support for console entries. For details see https://github.com/mozilla/geckodriver/issues/284#issuecomment-458305621.
