### ISSUE TITLE
Where can I download source code of a release tag?

### ISSUE THREAD

**Issue by vext01** [mozilla/geckodriver#1686]
Hi,

I used to clone a release tag of this repo and run `cargo build`, but it seems the code has moved elsewhere (to a mercurial mono-repo by the look of it) and without the geckodriver version tags.

So how can I download the source code of e.g. 0.26.0? Do you make source tarballs maybe?

Thanks

**Comment by packerbacker89** [comment]
https://hg.mozilla.org/mozilla-unified/file/tip/testing/geckodriver

**Comment by vext01** [comment]
I know where to find the source code, but unless I'm mistaken there are no geckodriver tags in the new hg repo.

How would I get (for example) version 0.26.0 of geckodriver from the above hg repo?

**Comment by whimboo** [comment]
[This document](https://firefox-source-docs.mozilla.org/testing/geckodriver/Building.html) describes how to build geckodriver from the Mercurial repository. Also each release as listed on https://github.com/mozilla/geckodriver/releases has a specific commit id referenced. For 0.26 this is [e9783a644016](https://hg.mozilla.org/mozilla-central/rev/e9783a644016aa9b317887076618425586730d73)

**Comment by vext01** [comment]
> Also each release as listed on https://github.com/mozilla/geckodriver/releases has a specific commit id referenced. For 0.26 this is e9783a644016

Thanks! That was the missing detail I was missing.

In the future you could add tags to the hg repo, as that'd be much simpler.
