### ISSUE TITLE
KeyboardEvent.Key is allways empty

### ISSUE THREAD

**Issue by kornelf** [mozilla/geckodriver#169]
SendKeys generates browser events (onKeyPress, onKeyDown etc.) with missing field 'KeyboardEvent.Key' in it.

**Comment by kornelf** [comment]
Same issue is in chromedriver.
Link with description and reproduction test.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1411#c2

**Comment by andreastt** [comment]
Closing this as a duplicate of https://github.com/mozilla/geckodriver/issues/348.
