### ISSUE TITLE
.NET Gecko Driver Component Not initialized

### ISSUE THREAD

**Issue by bennywolf1991** [mozilla/geckodriver#1690]
## System

* Version: 0.25.0 / 0.26.0
* Platform: Windows 10
* Firefox: 68.4.2user
* Selenium: 3.141

## Testcase
Hi, I have some issue with Gecko Driver throwing "Component not initialized" exception. However this only happens to certain sites not all of them. 

So we have 2 environments here at work, **DEV** and _QC_. Virtually there isn't any difference between the 2 except for their links which **DEV** has ".abc.def" at the ends and _QC_ doesn't. we only put ".abc.def" as trusted uris so for **DEV**, I have to use MS AUI to sign in, which is not an issue. The issue is, the same code works fine on **Dev** but crashes on _QC._

Here's my current setups:
1. I don't use custom profile via Selenium because it's been known to cause this exact exception
2. I saw some FF config online that prompts.tab_modal.enabled=true may affect performance, but things are fine on QC. (My settings for **prompts.tab_modal.enabled** is default at TRUE) and .NET Selenium cannot change this.
3. I previously used Gecko 0.26.0, someone on Github suggested, 0.25.0, I tried it but to no avail.

## Stacktrace

Error: OpenQA.Selenium.WebDriverException
Error: [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://marionette/content/modal.js :: get window :: line 143"  data: no]
Stack:    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)

So I inspect the chrome://marionette/content/modal.js

This is where the error happens

  get window() {
    if (this.win_) {
      let win = this.win_.get();
      if (win && win.parent) {  <==== Line 143
        return win;
      }
    }
    return null;
  }

Any possible fix or temporary solution to this? I've seen this being dragged around for a while with out any definitive solution and known that this is an ongoing issue. Any help is greatly appreciated.

NOTE: I don't have permission to change Firefox version, it is company standard.

**Comment by bennywolf1991** [comment]
### Update on this issue
Can I put this as a Bug in Gecko driver? 
So apparently I found the work around.

### Bug
Even if Selenium does not modify Firefox config, using Firefox Authentication to sign in to certain webpages that are not on Trusted Uris list also cause the "Component not initialized" exception to be thrown.

### Summary
From the previous example, **QC** and **DEV** have different URL configuration so I go into **Mozilla.cfg** to add **QC** into the trusted Uris list. By letting Firefox pull my credential from there, **QC** works perfectly without any issue.

### Question Remain
So making ANY change to Firefox config while Marionette is controlling it can potentially throw that Exception? Any suggestion going forward from here?

Thanks!

**Comment by whimboo** [comment]
AFAIR this was a bug in Marionette in older releases of Firefox. And you are using 68ESR as it looks like. Please check with a recent release of Firefox if that problem is still persistent. Also please provide a trace log as requested when filing an issue. Thanks.

**Comment by bennywolf1991** [comment]
Thank you for your reply!

Regarding Firefox version. There's nothing I can do about it since it is company standard and they don't want to move away from this version for some reason (gpo compatibility they stated), we tend stick with current FF until ops decides to push new version out. 

About logging, I tried to pull log but keep getting Null Reference Exception.
Below is the one that I use:

Driver.Manage().Logs.GetLog(OpenQA.Selenium.LogType.Browser)

Thank you!!

**Comment by whimboo** [comment]
Would you mind at least to test how a release behaves? That would be valuable information for me.

**Comment by bennywolf1991** [comment]
Hi Whimboo,

### Roadblock
I just talked to ops and they refused to push new FF version onto my machine. Their reasoning is that they want me to test on "company-approved product" (which in a way make sense, still). GPO blocks me from making change to certain "approved" software, so that's not an option for me.

### Workaround
So what I can do now is setting this all up on my personal machine at home and try to see if I can replicate the issue. It seems to only affect websites that use either AngularJS or Dynamics, I'm not sure (it never happens to cold fusion (.cfm)). I'll update this thread when I have some results coming up.

### Test Plan

I'll just install FF68ESR onto my machine with Selenium 0.25 to see if I can replicate the issue first then see if the latest version'll fix it. If you have any additional suggestion, please feel free to let me know.

Thanks!!

**Comment by whimboo** [comment]
You do not have to install firefox. You could just pick a [zip file](https://archive.mozilla.org/pub/firefox/candidates/73.0.1-candidates/build1/win64/en-US/firefox-73.0.1.zip) of the 73.0.1 release and run it after unzipping. It doesn't leave traces behind, so you can safely remove the folder afterward.

**Comment by bennywolf1991** [comment]
Hello,

Just a short update. i haven't had the time to test FF over the weekend because we have a release that ends on Monday morning. I'll be doing the testing for newer FF this week.

Thanks,

**Comment by bennywolf1991** [comment]
Quick update on this. I ran all of the test cases that I've had trouble with using FF 73 and it works! Thanks. Although I doubt I can use it for actual testing at least the issue is fixed with this version. 

P/S: This maybe a dumb question, does FF73 use mozilla.cfg? Ops team put some lockdown and security bypass in the current mozzilla.cfg for our current FF68, when I try copying that cfg over to 73, it doesn't look like anything is copied when I look into the **about:config**.

**Comment by whimboo** [comment]
I cannot answer that for sure, but afair configs are only in use in ESR releases.

Regarding a possible fix for Firefox 68ESR I would have to know which patch actually fixed it. As such would you mind to bisect the Firefox releases (69 - 73), so we at least know in which release it was fixed? This should help me to identify the right patch for uplift. Thanks!

**Comment by bennywolf1991** [comment]
Hi Whimboo,

Firefox 69.0 fixes the issue. I ran 10+ tests that failed on 68.5 and 68.6. The changes may be due to this file: **chrome://marionette/content/modal.js**

I put them to side by side comparison and found out that from 69 onward, they put in about 80+ lines of code to handle _common-dialog_ and _tabmodal-dialog_ I ran back and test 68.5, all tests that don't concern modal pass. As soon as I do something with modal dialog, things fall apart.

Is there a way to replace **marionette/content/modal.js** for Firefox? Maybe if we can copy Marionette's for FF69 to 68 and see if it fixes the issue.

Thanks!

**Comment by bennywolf1991** [comment]
Another thing to bring up. I've read this article on Mozilla and seen that ESR release schedule will be 68.5 - 12 from **now till August** and 78.x from **July** till end of **Q4**. Does it mean we're stuck with this until July?

**Comment by whimboo** [comment]
Thanks. So this is most likely fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1477977.

Mind checking these two Nightly builds?

This should fail: https://archive.mozilla.org/pub/firefox/nightly/2019/06/2019-06-13-09-56-33-mozilla-central/
This should pass: https://archive.mozilla.org/pub/firefox/nightly/2019/06/2019-06-14-10-00-22-mozilla-central/

If my assumption is correct, I could have a look if it would be possible to uplift the patch to 68ESR.

**Comment by whimboo** [comment]
This issue seems to have been fixed a while ago.
