### ISSUE TITLE
Geckodriver-A exception with a null response

### ISSUE THREAD

**Issue by mulanirubi** [mozilla/geckodriver#1691]
@groovecoder-mozilla-owner

Gecko Version -0.26.0
firefox version-66.0
Emulator-Samsung Galaxy S8

Getting an Issue-"A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:53721/session. The status of the exception was ReceiveFailure, and the message was: The underlying connection was closed: An unexpected error occurred on a receive."

For following code-

            FirefoxOptions options1 = new FirefoxOptions();
           options1.LogLevel = FirefoxDriverLogLevel.Trace;
            options1.AddAdditionalCapability("androidPackage", "org.mozilla.firefox");
            options1.SetPreference(CapabilityType.PlatformName,"android");
           var  Driver = new FirefoxDriver(@"Path To geckoDriver",options1, 
           TimeSpan.FromSeconds(60));

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by mulanirubi** [comment]
Thanks for Your Response @whimboo 
Here i am attaching tracelog and screenshot where firefox invokes in emulator but after few seconds it crashes with an exception "A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:49956/session. The status of the exception was ReceiveFailure, and the message was: The underlying connection was closed: An unexpected error occurred on a receive.""

I have observed that after invoke of firefox in emulator/device its setting get reset like Remote debugging disables and whatever settings i have made in about:config resets to previous.

Can also look at the following issue i am having with the device-https://github.com/mozilla/geckodriver/issues/1689

[Trace_log.txt](https://github.com/mozilla/geckodriver/files/4249949/Trace_log.txt)
![Screenshot](https://user-images.githubusercontent.com/3082737/75247503-12f87480-57f8-11ea-8056-7702b18b0938.png)

**Comment by whimboo** [comment]
Would you mind doing me a favor and test it also with Firefox Nightly that can be downloaded from [Google PlayStore](https://play.google.com/store/apps/details?id=org.mozilla.fennec_aurora&hl=en) too? Does that show the same behavior? Note that this is the new Firefox as driven by GeckoView, and it would be good to know if only the old Firefox (Fennec) is affected here.

**Comment by mulanirubi** [comment]
Thanks for the response 
Yes,I have checked on Nightly,Beta and Fennac versions of firefox on devices.

on Nightly version it says that Firefox Nightly version has stopped working.

**Comment by mulanirubi** [comment]
Android Device OS- 7.0
Checked on Firefox Nightly version. But getting an exception "adb error: couldn't create file: Permission denied" on device.

Please check trace log

[Tracelog_Device.txt](https://github.com/mozilla/geckodriver/files/4250218/Tracelog_Device.txt)

**Comment by whimboo** [comment]
Maybe the failure is a red herring. I can see a wrong path delimiter here:

> /data/local/tmp\org.mozilla.fennec_aurora-geckoview-config.yaml

We fixed that a while ago on https://bugzilla.mozilla.org/show_bug.cgi?id=1609263. Given that version 0.27 hasn't been released yet, would you mind testing a nightly build of geckodriver? It can be found here:

https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&tier=1%2C2%2C3&searchStr=geckodriver%2Cwin&revision=afa247928245d02b1305a1850eb39f19b84a2f35

Click on the `+2` for your platform, and select the `s` (signed) job. In the lower pane you can find the `geckodriver.zip` archive with the binary included. Does it work now?

**Comment by whimboo** [comment]
No further reply from the reporter. I assume it works now. Feel free to reopen in case it still exists.
