### ISSUE TITLE
JSON decoding of remote response failed.

### ISSUE THREAD

**Issue by nantuko86** [mozilla/geckodriver#1694]
## System

* Version: 0.26.0
* Platform: centos6
* Firefox:  68.5
* Selenium: 
I am not usign Selenium , because i want to run all the processes in the same machine . 
* webdriver : [ last version installed by composer ]

I am using Codeception to run tests 

## Testcase

Settings for Webdriver  ( from the file Codeception's 'acceptance.suite.yml' ):

 - WebDriver:
             url: "http://127.0.0.1:8000"
             window_size: 800x600
             host: 127.0.0.1
             port: 9515
             http_proxy: direct
             browser: firefox

Settings for Geckodriver :

`geckodriver --port=9515`

## Stacktrace

When I run the tess I receive the following error :

`
[Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'HTTP method not allowed'
`

## Trace-level log
The trace log was empty 

## Wireshark 

i checked all the process and using tcp_dump and whireshark I saw that the test is pointing to this address ( http://172.0.0.1:8000/wd/hub/ ) instead of ( http://172.0.0.1:8000 ) .

How can I remove/disable this part of address (wd/hub)?

If i run everything on the local machine , should I  have to install and set up also Selenium ? I read from this article that i can run Geckodriver whitout Selenium (https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone)

**Comment by yesdevnull** [comment]
Try adding `path: ''` to your WebDriver config in `acceptance.suite.yml` - that fixed it for me.

**Comment by whimboo** [comment]
This doesn't seem to be an issue related to geckodriver bug Codeception. You might want to file an issue / support ticket there.
