### ISSUE TITLE
Consider making source tarballs of releases.

### ISSUE THREAD

**Issue by vext01** [mozilla/geckodriver#1695]
Hi,

I started a clone of the monorepo nearly an hour ago and hg is reporting I still have an hour and a half left.

Have you considered making release tarballs of geckodriver source code so that end users don't have to clone the massive repo? Cargo makes it easy to push source releases to crates.io.

Thanks

**Comment by vext01** [comment]
I eventually got the repo cloned, but I had to do it on a remote machine with more bandwidth than my home connection. The clone kept taking too long and timing out.

Next I tried rolling my own source tarball, but it seems that the geckodriver sources are not stand-alone.

Steps:
 * clone mono repo
 * `hg up` to the release tag for 0.26.0
 * tar up the geckodriver subdirectory.
 * untar the archive elsewhere.
 * `cargo build`

```
$ cargo build
    Updating crates.io index
error: failed to load source for a dependency on `mozdevice`

Caused by:
  Unable to update /home/edd/research/pub_manager_scripts/mozbase/rust/mozdevice

Caused by:
  failed to read `/home/edd/research/pub_manager_scripts/mozbase/rust/mozdevice/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Would it be possible to make the sources stand alone so that users wishing to build from source don't have to clone the 7.5GiB mono-repo?

(I eventually want to make a binary package for OpenBSD, but I can only do so if i can get a small source tarball)

Thanks

**Comment by longspell** [comment]
You can download the testing path (ie `curl -o tip.zip https://hg.mozilla.org/mozilla-central/archive/tip.zip/testing/`) which is ~123MB at the time of this comment, that resolved the `No such file or directory` failure you posted above when I ran into the same error.

**Comment by vext01** [comment]
Thanks!

Well 123MB is better than 7.5GB, but it's still too large to use as a distfile for binary packages.

**Comment by vext01** [comment]
Here's a script which makes a stand-alone source tarball. Copy it to `dist.py` in `testing/geckodriver`. When run from that directory it will make a tarball in the `./target/dist/` directory.

```
#!/usr/bin/env python3
"""
Generate a standalone Geckodriver distfile from within a mozilla-unified clone.

Geckodriver depends upon several crates local to the mozilla-unified source
tree. This script bundles up the Geckodriver source code and the local
dependencies into a standalone tarball for easy distribution.

Usage:
    dist.py <version>

For example `dist.py 1.2.3` will create `target/dist/geckodriver-1.2.3.tar.gz`.

"""

import toml
import sys
import os
import shutil
import tarfile
from tempfile import TemporaryDirectory

OUT_DIR = "target/dist"


def main(version):
    os.makedirs(OUT_DIR, exist_ok=True)
    with TemporaryDirectory() as tmpd:
        print(make_tarball(tmpd, populate_dest_dir(tmpd, version)))


def populate_dest_dir(tmpd, version):
    deps = get_dep_paths()
    dest_dir = os.path.join(tmpd, f"geckodriver-{version}")
    os.mkdir(dest_dir)

    # Copy main sources.
    geckodriver_dest_dir = os.path.join(dest_dir, f"geckodriver")
    shutil.copytree(".", geckodriver_dest_dir)

    # Copy local dependencies.
    for dep in deps:
        dep_dest_dir = os.path.join(geckodriver_dest_dir, dep)
        os.makedirs(os.path.dirname(dep), exist_ok=True)  # Scaffold dirs.
        shutil.copytree(dep, dep_dest_dir)
        return os.path.basename(dest_dir)


def get_dep_paths():
    """Find local dependencies that need to be distributed along with the
    geckodriver sources"""

    with open("Cargo.toml") as f:
        cargo_toml = toml.load(f)

    paths = set()
    for dep in cargo_toml["dependencies"].values():
        if not isinstance(dep, dict):
            # Then it's a simple dependency that can't have a `path` override.
            # e.g. `base64 = "0.10"`.
            continue

        if "path" not in dep:
            # Doesn't have a `path` override.
            continue

        path = dep["path"]
        if path.startswith("./") or (len(path) > 0 and path[0].isalnum()):
            # A crate in a subdir of CWD. No need to consider.
            continue

        assert path.startswith("../")
        paths.add(path)
    return paths


def make_tarball(tmpd, direc):
    tgz_name = f"{direc}.tar.gz"
    tgz_path = os.path.abspath(os.path.join(OUT_DIR, tgz_name))
    os.chdir(tmpd)
    with tarfile.open(tgz_path, "w:gz") as tgz:
        tgz.add(direc)
    return tgz_path


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        sys.exit(1)

    main(sys.argv[1])
```

For the current hg tip, this makes a 244KB tarball :)

Perhaps it could be imported and used it to make stand-alone source releases?

**Comment by whimboo** [comment]
@vext01 thanks for bringing this up. I already had this idea a while ago but haven't had the time to actually get started with it. Maybe you can have a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1606297? What it was missing is some clarification around building geckodriver with such a reduced set of files. Once we figured that out, we could definitely take your script as base and extend it. If you don't mind we should continue the discussion on that mentioned bug.

**Comment by whimboo** [comment]
Please note that as long as the above mentioned bug hasn't been fixed I will continue to make the latest source available via Github. It means the 0.27.0 release will have it included.

**Comment by vext01** [comment]
@whimboo So as of 0.27.0, if I download a release from this repo, I will get the actual geckodriver sources? That'd be great!

**Comment by vext01** [comment]
I'm not sure if you are using the script above, but note that it had a bug!

I've moved the script into a git repo, along with the fix, [here](https://github.com/vext01/mk-geckodriver-tarball/).

**Comment by whimboo** [comment]
No, I don't have to. But thanks.

**Comment by blshkv** [comment]
can you upload latest releases into crates please?

https://crates.io/api/v1/crates/mozdevice/0.2.0/download
https://crates.io/crates/mozdevice is still 0.1.0.

Thanks

**Comment by andreygursky** [comment]
Building from source the 0.27.0 version released 7 days ago still fails:
```
$ mkdir /tmp/geckodriver
$ cd /tmp/geckodriver/
$ wget https://github.com/mozilla/geckodriver/archive/v0.27.0.tar.gz
$ tar xf geckodriver-0.27.0.tar.gz
$ cd geckodriver-0.27.0/
$ cargo build -v --release
    Updating crates.io index
error: failed to select a version for the requirement `mozdevice = "^0.2.0"`
  candidate versions found which didn't match: 0.1.0
  location searched: crates.io index
required by package `geckodriver v0.27.0 (/tmp/geckodriver/geckodriver-0.27.0)`
$
```

**Comment by whimboo** [comment]
yes, there is an unforeseen problem we have to fix first. Until then please build geckodriver from https://hg.mozilla.org/mozilla-unified. Sorry for the inconvenience.

**Comment by whimboo** [comment]
I've uploaded version 0.2.0 of mozdevice to crates.io, and geckodriver can be perfectly built from a Github checkout.

Sorry to all of you, who faced troubles in not having the source tarballs available for the last releases. We will make sure to continue releasing those for future releases of geckodriver.

**Comment by whimboo** [comment]
Sadly not. crates.io is used to share libraries but not binaries. See https://doc.rust-lang.org/cargo/reference/publishing.html. As such we do not upload any crates to that page.
