### ISSUE TITLE
Potential Malware in Windows Release

### ISSUE THREAD

**Issue by GuittonHubert** [mozilla/geckodriver#1696]
## System

* Version: 0.26.0
* Platform: Windows 10 64-bits
* Firefox: 73.0.1 64-bits
* Selenium: 3.141.0
* Python: 3.5

## Testcase

When submitting data to a HTML form, the browser opens a new tab pointing to a dubious advertising page. At this stage, I cannot confirm that the issue is in the Selenium version I use, or in the Gecko driver. Please note that using the same code with the Chrome driver, it does not happen.

Find below an excerpt of my Python code:

```python
# Step 1) Open Firefox
browser = webdriver.Firefox()

# Step 2) Navigate to XXX website
browser.get('https://XXX/account/login')

# Step 3) Search & Enter the Email & Enter Password
username = browser.find_element_by_id("emailAddress")
password = browser.find_element_by_id("password")

wait = WebDriverWait(browser, 10)

submit  = browser.find_element_by_id("signInButton")
username.send_keys("my email address")
password.send_keys("my password")

# Step 4) Click Login
submit.click()
```

From then on, the browser shows the expected web page, but also opens a new tab as mentioned earlier on.

## Stacktrace

None

**Comment by whimboo** [comment]
If you downloaded a dubious release of Firefox from somewhere you should clearly replace it with an official release from Mozilla. You can always get those from https://www.mozilla.org/en-US/firefox/new/. 

Note that this has nothing to do with geckodriver, and as such I'm closing this issue.
