### ISSUE TITLE
HTTP Method not allowed

### ISSUE THREAD

**Issue by lf94** [mozilla/geckodriver#1698]
## System

* Version: 0.26.0
* Platform: Debian buster
* Firefox:  68.4.1esr (64-bit)
* Selenium: 4.0.0-alpha5 (selenium-webdriver npm package)

## Issue

No matter what I do, geckodriver is reporting HTTP Method not allowed. So one good thing is, at least selenium can connect to it, since I've been able to get it to report back a bad connection.

I'm wondering if it's the selenium version at fault here. What version is recommended?

## Testcase

Follow the guide here https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode . It's exactly what I did.

## Stacktrace

No stack trace.

## Trace-level log

Running `geckodriver -vv` does not result in any trace log. It outputs the 1 (non-error) line it usually outputs.

**Comment by lf94** [comment]
Downgrading to selenium-webdriver@3.6.0 results in the same error: HTTP method not allowed .

**Comment by lf94** [comment]
Next I will be following https://firefox-source-docs.mozilla.org/testing/marionette/Debugging.html to see if there are any communication issues with geckodriver and my local firefox installation.

**Comment by whimboo** [comment]
Trace level logs would still be helpful. I'm not sure what has to be used to activate those when using the npm package. Maybe check their documentation.

**Comment by lf94** [comment]
Ah, I can get you the selenium-webdriver output. I understand what follows is probably not what you're asking for. I will come back with more after doing some digging in the package.

The code:

```
const webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

const firefox = require('selenium-webdriver/firefox');

const options = new firefox.Options()
  .setBinary('/usr/bin/firefox-esr');

const driver = new webdriver.Builder()
    .forBrowser('firefox')
    .usingServer('http://127.0.0.1:4444/wd/hub')
    .setFirefoxOptions(options)
    .build();

driver.get('https://www.github.com');
driver.sleep(3000).then(() => driver.quit());
```

The output:

```
$ node index.js
/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

WebDriverError: HTTP method not allowed
    at parseHttpResponse (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/lib/http.js:536:11)
    at /home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at createDriver (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/node_modules/selenium-webdriver/index.js:632:16)
    at Object.<anonymous> (/home/lee/Code/Mine/Automation/aggregator/aggregator-cpc/index.js:14:6)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  name: 'WebDriverError',
  remoteStacktrace: ''
}
```

**Comment by lf94** [comment]
Well looks like this alternative way to set things up works:

```
const webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

const firefox = require('selenium-webdriver/firefox');

const options = new firefox.Options();
const service = new firefox.ServiceBuilder().build();
const driver = firefox.Driver.createSession(options, service);

driver.get('https://www.youtube.com');

```

I found this here https://github.com/SeleniumHQ/selenium/issues/6219 .

While the issue using the original code still remains, this allows me to continue what I want to do.

I'll leave it up to you @whimboo to decide if it should be closed or remain open. I hope this helps others.

**Comment by bonjonbovi87** [comment]
For my daily regression setup I run the latest selenium/stanalone-firefox images and I hit `HTTP method not allowed` after instantiating the browser in W3C mode and attempting to inject javascript via the /execute/ endpoint.  The version of that Firefox is 70 on Ubuntu.

I do not hit this error in W3C mode when running on Firefox 73 on Windows.  I'm hoping the next update to selenium/standalone-firefox uses at least v73 and fixes the error, so , so @lf94 try updating Firefox.

**Comment by whimboo** [comment]
So it doesn't sound like a problem with geckodriver then. Closing the issue.
