### ISSUE TITLE
Robot framework/Pycharm : SessionNotCreatedException: Message : Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by gonab2017** [mozilla/geckodriver#1699]
Below is my simple script , it shows Unable to find matching capabilities. I saw for similar issue earlier explanation and I tried to add OperatingSystem library but still it shows same issue.
I tried multiple ways installing / downloading multiple times Pycharm/Python/ Robotframwork, chromedriver correct versions etc.
But still could not able to make it work.
I do not understand why issue come as gekodriver log and it shows Opening browser firefox to base url , whereas I am using clearly chore.

Pycharm=2019.2
Python=3.7.6
robotframwork=3.1.2
rotboframwork-seleniumlibrary=4.3.0

Please help. Is there any issue with porxy  or persmission? I really dont undersatnd.

*** Settings ***
Documentation  This is some basic sample code
Library  SeleniumLibrary
Library  OperatingSystem

*** Variables ***

*** Test Cases ***
User must sign in to check out
    [Documentation]  This is under Test case
    [Tags]  Smoke
    set environment variable  webdriver.chrome.driver  C:\bin\chromedriver.exe
    open browser  http://www.amazon.com  chrome
    sleep  3s
    maximize browser window
    close browser

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
