### ISSUE TITLE
It is not possible to set a prompt value

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#17]
INFO: Executing: setAlertValue [2c70c183-25a1-49e2-aeb5-0a6b0275939d, setAlertValue {text=cheese}]
ERROR:webdriver::server: Returning status BadRequest
ERROR:webdriver::server: Returning body {"message":"Missing 'handle' parameter","status":"invalid argument"}

**Comment by andreastt** [comment]
`setAlertValue` should map to `sendKeysToDialog` in Marionette.  For the sake of inconsistency this is specified as **Send Alert Text**.

**Comment by FrankBorland** [comment]
I'm having a similar behaviour but with a slightly different error when using the following Java code: 

`driver.switchTo().alert().sendKeys("test")`

The error message is: org.openqa.selenium.WebDriverException: keySequence.join is not a function

**Comment by andreastt** [comment]
@FrankBorland The [specification says](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-send-alert-text) that the input should be an array of strings. Can you increase logging so we can tell what Selenium sends to geckodriver?

**Comment by FrankBorland** [comment]
The log contains this:

Executing: setAlertValueW3C [d7ecd6d7-9124-441e-a4bc-5e67be290fca, setAlertValueW3C {text=test}]

**Comment by andreastt** [comment]
What driver is that? _setAlertValueW3C_ sounds suspicious.

**Comment by FrankBorland** [comment]
I used the latest realeased Selenium Java bindings (version 2.53.1) in combination with the org.openqa.selenium.firefox.MarionetteDriver class.

**Comment by FrankBorland** [comment]
This is the line of code from the Java binding: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L1088

**Comment by andreastt** [comment]
A bit of history here: I advocated changing the spec to taking a string like it appears it is sending, but got told that wasn’t what Selenium was doing and that we should keep in sync with the _Element Send Keys_ command that takes an array of unicode code points as strings.

**Comment by andreastt** [comment]
This was discussed in https://github.com/w3c/webdriver/pull/255 where I think some confusion arose around what Selenium is _actually_ doing. From @FrankBorland’s log above it appears Selenium is sending a single string value such as `{text: "foo"}` as the body.

**Comment by AutomatedTester** [comment]
Initial PR at https://github.com/jgraham/webdriver-rust/pull/39 to get this fixed.

**Comment by harshg0910** [comment]
Geckodriver : 0.10.0
Selenium : 3.0.0beta3
Firefox : 48.0.2

I'm getting "Missing 'text' parameter (IndexOutOfBounds)"
when I use webDriver.SwitchTo().Alert().SendKeys(text); to set text in prompt pop-up
While enabling logs, I got :
1475055482152 Marionette TRACE conn0 <- [1,10,null,{"value":"prompt text"}]

Will this be resolved in next release as I can see related pull request 
https://github.com/jgraham/webdriver-rust/pull/39 ?

**Comment by andreastt** [comment]
@harshg0910 We need to land https://github.com/jgraham/webdriver-rust/pull/39, release a new webdriver-rust version, then upgrade geckodriver, and land https://github.com/mozilla/geckodriver/pull/151.

**Comment by andreastt** [comment]
This should be resolved now.
