### ISSUE TITLE
Content type not sent when session not created properly.

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#170]
Steps to reproduce:

1) Send garbage data to the "new session" end point

Expected results:

An HTTP response containing JSON explaining the reason for the failure, with the content type set to "application/json" or similar.

Actual result:

The response contains JSON, but the Content-Type header is not set.

**Comment by andreastt** [comment]
This should be set in https://github.com/jgraham/webdriver-rust/blob/master/src/server.rs#L224, but it looks like we may be setting it too late?

**Comment by andreastt** [comment]
We appear to be setting the `Content-Type` header correctly to `application/json` now:

```
% curl -v -d "asdasd" http://localhost:4444/session
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4444 (#0)
> POST /session HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 6
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 6 out of 6 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Connection: close
< Date: Fri, 31 Mar 2017 08:47:16 GMT
< Content-Length: 86
< 
* Curl_http_done: called premature == 0
* Closing connection 0
{"error":"invalid argument","message":"Failed to decode request body as json: asdasd"}% 
```
