### ISSUE TITLE
using curl to open URL in new tab

### ISSUE THREAD

**Issue by glitsj16** [mozilla/geckodriver#1702]
## System

* Version: geckodriver 0.26.0
* Platform: Linux
* Firefox: 74.0
* Selenium: not relevant in this context, I need to use curl instead

After starting Firefox with the `-marionette` flag I can succesfully use geckodriver/curl to open a URL using this simple bash script:

```
#!/bin/bash

_browser_path="/mnt/lab16.sda3/00.firefox/firefox"
_curl="/usr/bin/curl"
_server="http://127.0.0.1:4444/session"
_sess_id_file="/tmp/geckodriver-session-id"

case "$1" in
    start)
	# wait for Firefox
	sleep 4
        # start geckodriver
	geckodriver -b "$_browser_path" --connect-existing --marionette-port 2828 &
	# get remote-control session ID
	sleep 4
	_sess_raw="$(${_curl} -s -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' ${_server})"
	_sess_id="$(echo "$_sess_raw" | jq '.value.sessionId' | sed 's/"//g')"
	echo "$_sess_id" > "$_sess_id_file"
        exit 0
        ;;
    stop)
        _id="$(head -n 1 "$_sess_id_file")"
        rm -f "$_sess_id_file" &
        pkill geckodriver &
        exit 0
        ;;
    *)
        # open http{s) URI's only
        if [[ "$1" =~ http:// ]] || [[ "$1" =~ https:// ]]; then
            _id="$(head -n 1 "$_sess_id_file")"
            # load URL
            ${_curl} -s -d "{\"url\": \"$1\"}" ${_server}/${_id}/url
        else
	    echo "Unsupported action - aborting."
            exit 1
        fi
        ;;
esac
```

I am trying to expand the script so URL's open in a new (background) tab, using the `curl` interface. And that's where I could use some help/pointers. According to the [webdriver protocol](https://w3c.github.io/webdriver/#protocol) there are endpoints for executing a script (either synchronously or asynchronously):

Method 	URI Template 						Command
POST	/session/{session id}/execute/sync 		Execute Script
POST	/session/{session id}/execute/async 	Execute Async Script

I've seen how this can be done in selenium [here](https://github.com/mozilla/geckodriver/issues/903#issuecomment-324956768), but I need to use curl. How would I pass this javascript

`window.open("https://www.example.com", "_blank");
`
to the appropriate URI template with curl? Is that possible/documented somewhere?

**Comment by whimboo** [comment]
Please note that this question is more related to webdriver itself but not to a specific driver. 

But to answer your question please have a look at the WebDriver specification at https://w3c.github.io/webdriver/#executing-script. Both methods and their HTTP end-points are described there.
