### ISSUE TITLE
invalid argument: can't kill an exited process

### ISSUE THREAD

**Issue by jonfen** [mozilla/geckodriver#1704]
## System

* Version: v0.26.0
* Platform: Ubuntu 19.10 - Linux yoga-ubuntu 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Firefox: 74
* Selenium: python/pip selenium==3.141.0

## Testcase

https://github.com/jonfen/utah-repeaters

If I manually run

```bash
"/usr/bin/firefox" "-marionette" "-profile" "/tmp/tmp8rij8g30.selenium" "-foreground" "-no-remote"
```
**The browser opens fine on Ubuntu 19.10, and this issue does not exist on an Ubuntu 18.04 instance I have**.

## Stacktrace

1584927656672	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/tmp8rij8g30.selenium" "-foreground" "-no-remote"
1584927656673	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:33247
ExceptionHandler::GenerateDump cloned child 9843
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1584927658077	mozrunner::runner	DEBUG	Killing process 9804
1584927658077	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}

## Trace-level log

1584927656672	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/tmp8rij8g30.selenium" "-foreground" "-no-remote"
1584927656673	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:33247
ExceptionHandler::GenerateDump cloned child 9843
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1584927658077	mozrunner::runner	DEBUG	Killing process 9804
1584927658077	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}

**Comment by whimboo** [comment]
I don't see any output from Firefox in the log, so I doubt this is a trace level log. Please check https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html again, in how to create a correct one. Thanks.

**Comment by jonfen** [comment]
@whimboo I followed that, https://github.com/jonfen/utah-repeaters/blob/master/app.py line 33  am I doing something else wrong?

**Comment by whimboo** [comment]
So what happens when you first start geckodriver on your own, and then run the following command?

> curl -X POST localhost:4444/session --data {}

Does it show the same problem with Firefox?

**Comment by whimboo** [comment]
No further response, so closing the issue. We can re-open once the requested information has been provided.

**Comment by BrodaUa** [comment]
Hello, I face the similar issue, but with strange details.
When I run the Geckodriver locally or inside the docker container it works fine, but whenever I try to run such container in Google Cloud, I get the following:

## geckodriver.log:
1587780842085	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.ubCkR5hjFiMa"
1587780842099 geckodriver::marionette DEBUG Waiting 60s to connect to browser on 127.0.0.1:33007
*** You are running in headless mode.
[61, Main Thread] WARNING: failed to open shm: Function not implemented: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/shared_memory_posix.cc, line 246
ExceptionHandler::GenerateDump cloned child 69
ExceptionHandler::SendContinueSignalToChild sent continue signal to child	
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
1587780842839 mozrunner::runner DEBUG Killing process 61
1587780842839 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"unknown error","message":"invalid argument: can't kill an exited process","stacktrace":""}}

## System:
Linux d6092e5b40ee 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 GNU/Linux
geckodriver 0.23.0 ( 2018-10-04)
Mozilla Firefox 75.0
selenium==3.141.0

**Comment by whimboo** [comment]
@BrodaUa next time please do not add comments on already closed issues. That's not helpful. For now just read the error message: `failed to open shm: Function not implemented`. As it looks like `/dev/shm` isn't working. Check with `df -h` if there is such a device. If not the docker container needs a fix, or maybe it's not allowed in Google Cloud.
