### ISSUE TITLE
function might have stalled-too long to launch the browser-not even launching now

### ISSUE THREAD

**Issue by Mahmoussam** [mozilla/geckodriver#1709]
## System

* Version:  geckodriver version 
* Platform: Windows 7 32-bit 
* Firefox: last firefox release
* Selenium: last java selenium client

the problem:
I have been facing "function might have stalled"exception when pressing on button (was working before )so i used send keys function to send Keys.RETURN key,this fixed it for this button but when sending keys to other text fields (no buttons here) i get same problem.I thought about checking new releases and found that Firefox has new update ,after updating and trying i got above error but then no more work,browser doesn't launch ,no log,no thing!

# Testcase

```
            ProfilesIni allProfiles = new ProfilesIni();
            FirefoxProfile profile = allProfiles.getProfile("blobot");
            profile.setPreference(FirefoxProfile.PORT_PREFERENCE, 7046);
            FirefoxOptions opt = new FirefoxOptions();
            
            opt.setLogLevel(FirefoxDriverLogLevel.TRACE);
            opt.setProfile(profile);
            driver = new FirefoxDriver(opt);
            //doing some stuff
            //in case something happened in our process we quit
            driver.quit()//--->throws null pointer exception!!


```

## Stacktrace

at begin i was able to see the stack trace but currently nothing gets printed,the browser doesn't open.

## Trace-level log

no thing printed to stdout (netbeans)
no files generated

EVERYTHING WAS FINE TILL YESTERDAY.
note ,a friend had copy of my software yesterday ,was working yesterday too but having same problem today.
if any info needed ,just ask me.
thanks in advanced.

**Comment by Mahmoussam** [comment]
No response....
I fixed it by downgrading to firefox 75 and got back log-stacktrace

**Comment by whimboo** [comment]
The last Firefox release is version 75. So I don't understand what you mean with downgrading to version 75 fixes it for you.
