### ISSUE TITLE
New Session end point should ignore JSON keys it doesn't recognise

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#171]
The spec used to say that parameters that were not understood should be ignored. This is to allow the protocol to evolve over time, and to allow vendors to experiment with vendor-specific parameters without needing to add them to the spec. The language in http://www.w3.org/TR/webdriver/#dfn-match-a-request doesn't mention unused parameters right now, but I will clarify this soon.

This feature is used when hand-shaking to determine whether a remote end speaks the W3C or OSS selenium protocol. Specifically, the W3C spec says that the required and desired capabilities need to be placed in a "capabilities" parameter, whereas the OSS implementation sets "desiredCapabilities" and "requiredCapabilities" as parameters in their own right. A local end can attempt to set the parameters required for both OSS and W3C and then look at the `status` and `state` fields to determine which dialect to speak.

As of 0.9, geckodriver fails to create a session when all parameters are not identified. This makes it impossible to handshake with using the above mechanism, requiring multiple (potentially slow) HTTP calls or additional logic in all intermediary nodes and local ends.

**Comment by andreastt** [comment]
This will get fixed by [bug 1326534](https://bugzilla.mozilla.org/show_bug.cgi?id=1326534).

**Comment by andreastt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1326534 has landed and is available in Firefox 52 onwards.
