### ISSUE TITLE
Copyright notice for geckodriver 0.26.0

### ISSUE THREAD

**Issue by nagik** [mozilla/geckodriver#1710]
## System

* Version: geckodriver 0.26.0
* Platform: Windows

## Testcase

Looking for copyright notice for the source code.  Is there a copyright notice for geckodriver 0.26.0?

**Comment by whimboo** [comment]
The source of geckodriver is part of https://hg.mozilla.org/mozilla-central/, which means the license from that same repository applies. All the details can be found in https://hg.mozilla.org/mozilla-central/file/tip/LICENSE.

If you have further questions please let us know. Thanks.

**Comment by nagik** [comment]
Thank you very much for the confirmation.

**Comment by nagik** [comment]
Hi, thanks much for the info.  I’m specifically looking for a copyright notice for geckodriver. I understand that the license terms are same as Mozilla Public License, but I would like get a copyright notice that is specific to geckodriver. Please point me to the copyright notice that applies to geckodriver.

**Comment by whimboo** [comment]
This has all been clarified on https://groups.google.com/forum/#!topic/mozilla.tools.marionette/N_9Fs9UFb-8 now.
