### ISSUE TITLE
Ubuntu over Gnome wrong window size management

### ISSUE THREAD

**Issue by arazgulyaev** [mozilla/geckodriver#1717]
## System

* Version: geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
* Platform: Ubuntu 18.04
* Firefox: 75.0 (64-bit)
* Selenium: Java bindings 3.141.59

## Testcase

Document:

```html
<html>
  <head/>
  <body>
    <input type="button" style="margin: 50px;">
  </body>
</html>
```
Steps to reproduce:

1. Execute the following code against the page demonstrated above:
```java
public void testWindowSize(){
    driver.manage().window().setSize(new Dimension(300, 300));
    Point windowPosition = driver.manage().window().getPosition();
    Dimension windowSize = driver.manage().window().getSize();
    Point windowBottomLeft = new Point(windowPosition.getX(), windowPosition.getY() + windowSize.getHeight());
    System.out.println("Window dimensions: " + windowSize.toString());
    System.out.println("Window top left position: " + windowPosition.toString());
    System.out.println("Window bottom left position: " + windowBottomLeft.toString());
    // Set some breakpoint to here or reasonably large Thread.seep in order
    // to have time to capture whole screen screenshot
}
```
2. While the browser is displayed take a screenshot of the entire screen
3. Open that screenshot in some editor and examine window's dimensions in pixels

**Code output:**

```
Window dimensions: (450, 300)
Window top left position: (50, 27)
Window bottom left position: (50, 327)
```

**OBSERVED:**
1. Output shows that the window horizontal size is 450 px (despite it has been explicitly set to 300). The screenshot shows that the horizontal size is really 450 px.
2. Top left corner of the window on the screenshot is indeed where the code has printed
3. Vertical size of a window according to a screenshot is significantly bigger than 300 px

![ff_size](https://user-images.githubusercontent.com/922976/80582993-4cc44200-8a18-11ea-9f21-8130e7f9d917.png)

**EXPECTED:**
Real sizes corresponds to what is declared in code

## Stacktrace

Not relevant to the issue

## Trace-level log

[trace-level.log](https://github.com/mozilla/geckodriver/files/4550952/trace-level.log)

**Comment by whimboo** [comment]
From the trace log:

```
1588153606131	Marionette	DEBUG	0 -> [0,5,"WebDriver:GetWindowRect",{}]
1588153606132	Marionette	DEBUG	0 <- [1,5,null,{"x":88,"y":65,"width":450,"height":300}]
```

Yes, so 450px is the minimum width Firefox can be sized to. It's not possible to set a smaller size.

In regards of the height the title bar of the window is not included here. Given by the spec we use `window.outerHeight`, but due to https://bugzilla.mozilla.org/show_bug.cgi?id=581866 there is nothing we can do for geckodriver/marionette. It needs a fix for Firefox.

As such there is nothing wrong with geckodriver and it works as expected. Closing the issue.
