### ISSUE TITLE
acceptInsecureCerts capability is ignored

### ISSUE THREAD

**Issue by ghostwords** [mozilla/geckodriver#1718]
## System

* Version: 0.26.0
* Platform: Ubuntu Linux 16.04
* Firefox: 75
* Selenium: Python bindings version 3.141.0

## Testcase

Setting `acceptInsecureCerts` to `False` is ignored by geckodriver. The same pattern works with ChromeDriver.

In the following example, the `unhandledPromptBehavior` setting is respected, while `acceptInsecureCerts` remains set to `True`.

```python
            caps = DesiredCapabilities.FIREFOX.copy()
            caps['acceptInsecureCerts'] = False;
            caps['unhandledPromptBehavior'] = "ignore";

            self.driver = webdriver.Firefox(firefox_profile=profile,
                                            firefox_binary=self.firefox_path,
                                            options=opts,
                                            desired_capabilities=caps,
                                            service_log_path=os.path.devnull)
```

(The above code is from [badger-sett/crawler.py](https://github.com/EFForg/badger-sett/blob/47a6eda45ac1f887e0acaaa1f609cbd002bf0b5f/crawler.py#L317-L325))

**Comment by ghostwords** [comment]
Also note that `acceptInsecureCerts` defaults to `True`, while it defaults to `False` with ChromeDriver.

**Comment by whimboo** [comment]
This is not a problem with geckodriver or Firefox but with Selenium. Check the following code:
https://github.com/SeleniumHQ/selenium/commit/ec8ff72941afbe41d64295462771e8644882d7db

@AutomatedTester any idea why that capability has been set to always be `true`?

**Comment by whimboo** [comment]
Here a reference to my log when running a plain geckodriver session:

```
1588231286880	webdriver::server	DEBUG	-> POST /session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": false}, "firstMatch": []}}
[..]
1588231292088	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"f079d556-2b14-5442-9d75-6968ab3d12a5","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"77.0a1","moz:accessibilityChecks":false,"moz:buildID":"20200430035135","moz:geckodriverVersion":"0.26.0","moz:headless":false,"moz:processID":75360,"moz:profile":"/var/folders/c2/q_47wqh13n902fj9_zxczclr0000gn/T/rust_mozprofile79t7HK","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"mac","platformVersion":"19.3.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
```

**Comment by whimboo** [comment]
As best file an issue with Selenium.

**Comment by AutomatedTester** [comment]
> This is not a problem with geckodriver or Firefox but with Selenium. Check the following code:
> [SeleniumHQ/selenium@ec8ff72](https://github.com/SeleniumHQ/selenium/commit/ec8ff72941afbe41d64295462771e8644882d7db)
> 
> @AutomatedTester any idea why that capability has been set to always be `true`?

Selenium wants to support people using insecure certificates all the time. The WebDriver WG wanted it turned off as a default. Unfortunately,  that would be a breaking change in webdriver.

**Comment by whimboo** [comment]
> Selenium wants to support people using insecure certificates all the time. The WebDriver WG wanted it turned off as a default. Unfortunately, that would be a breaking change in webdriver.

And why is that not set for other browsers, but only Firefox?

**Comment by AutomatedTester** [comment]
Because the other browsers haven't implemented it properly the last time I
checked. Feel free to check their implementations and raise the relevant
bugs.

**Comment by whimboo** [comment]
But whatever other browsers do, why do we even not allow users of Selenium to override the capability? Right now it's not even possible to turn it off. So no way to run tests with invalid certs.

**Comment by ghostwords** [comment]
Not to mention Selenium is used for other browser automation tasks beyond running tests.

**Comment by ghostwords** [comment]
I created an issue in the Selenium repo; and it was immediately closed by a bot. Not a great user experience.

**Comment by AutomatedTester** [comment]
> I created an issue in the Selenium repo; it was immediately closed by a bot. Not a great user experience.

Unfortunately, it looks like you didn't follow the template or the contributions guide so the bot assumed it was a low quality bug.

**Comment by AutomatedTester** [comment]
> But whatever other browsers do, why do we even not allow users of Selenium to override the capability? Right now it's not even possible to turn it off. So no way to run tests with invalid certs.

The capability ordering between the old way and the new way was being done incorrectly. It appears that Chrome still accepts the older style capabilities. geckodriver is being more stringent here.

**Comment by ghostwords** [comment]
>Unfortunately, it looks like you didn't follow the template or the contributions guide so the bot assumed it was a low quality bug.

I understand what happened. My point is that rigid templates and auto-rejection by bots are a poor way to treat contributors. It's the phone call tree experience ported to GitHub.
