### ISSUE TITLE
Selenium::WebDriver::Error::NoSuchAlertError

### ISSUE THREAD

**Issue by jcoyne** [mozilla/geckodriver#1721]
## System

* Version: 0.26.0
* Platform: macOS 10.15.3
* Firefox: 76.0.1
* Selenium: ruby selenium-webdriver 3.142.7

## Testcase

in progress.  This is challenging because it seems to be indeterminate, and only occurs in a test suite after a few tests have run.  It does not occur when running a single test.

## Stacktrace

```
Unable to find WebDriverError@chrome://marionette/content/error.js to read failed line
          Selenium::WebDriver::Error::NoSuchAlertError:
          # WebDriverError@chrome://marionette/content/error.js:175:5
          # NoSuchAlertError@chrome://marionette/content/error.js:376:5
          # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3388:11
          # GeckoDriver.prototype.dismissDialog@chrome://marionette/content/driver.js:3301:8
          # despatch@chrome://marionette/content/server.js:305:40
          # execute@chrome://marionette/content/server.js:275:16
          # onPacket/<@chrome://marionette/content/server.js:248:20
          # onPacket@chrome://marionette/content/server.js:249:9
          # _onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20
```

## Trace-level log

In progress

**Comment by whimboo** [comment]
This is a regression in Firefox and equivalent to https://bugzilla.mozilla.org/show_bug.cgi?id=1629147. Basically it needs a [fix for the prompter code](https://bugzilla.mozilla.org/show_bug.cgi?id=1631362), which will hopefully land soon.

But that is beta, and nightly only right now. So are you really using the 76 release?

**Comment by jcoyne** [comment]
@whimboo thanks for the help. 🤷 looks like 76 to me:
<img width="350" alt="Screen Shot 2020-05-12 at 7 10 14 AM" src="https://user-images.githubusercontent.com/92044/81689276-bcc2c700-941f-11ea-9768-5f37969021ca.png">

**Comment by whimboo** [comment]
Ok, then please provide a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html).

**Comment by whimboo** [comment]
This should actually be fixed since Firefox 78. If not feel free to reopen the issue.
