### ISSUE TITLE
Run test with a PowerUser

### ISSUE THREAD

**Issue by Nawakator** [mozilla/geckodriver#1722]
## Run test with a different user (PowerUser)

* Version: Driver Gecko 64
* Platform: Windows 10 En 64
* Firefox: 76.0.1
* Selenium: Selenium Java 3.141.59

## Testcase

The Admin local user can start the test with no difficuluty.
The user Test is just PowseUser (not admin)
I set fullright to C:\Temp to this user Test and I've got this issue :
permission denied

Just try to start the driver with any url.

The temporary test folder (C:\Temp\rust_mozprofile0TADm3) was coreate but it just contain user.js and nothing else !

Is there any other directory used by firefox tests that should have elevated right ?

## Stacktrace

2020/05/13 13:42:44 - WD_____ - Create Driver Firefox
2020/05/13 13:43:02 - WD_____ - Error while create webdriver : permission denied

## Trace-level log

1589370170918	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Temp\\rust_mozprofile0TADm3"
1589370170934	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:50497
Error: Access was denied while trying to open files in your profile directory.
[GFX1-]: shader-c[2020a-c0h5e-:13T11 :S4h2ad:e5r 1dZis kE cRaRchOeR i sw neobt rseupnpdoretred_
b
indings::program_cache] shader-cache: Shader disk cache is not supported

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

1589370182306	mozrunner::runner	DEBUG	Killing process 2748
1589370182306	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"permission denied","stacktrace":""}}

**Comment by whimboo** [comment]
I assume you see the same problem when you run `C:\Program Files\Mozilla Firefox\firefox.exe -no-remote -profile C:\Temp\rust_mozprofile0TADm3` manually?

**Comment by Nawakator** [comment]
The folder C:\Temp\rust_mozprofile0TADm3 dose not exist
It was created by gecko/firefox and deleted at the end of test

**Comment by whimboo** [comment]
Right, then create the folder under that directory yourself please. I could imagine there is a permission issue here. Otherwise start a test, and kill the geckodriver process while the test is eg. waiting for a longer time. That way you could retain the profile folder.

**Comment by Nawakator** [comment]
This user have full control on this folder.
I can manualy create a folder under C:\Temp
The temporary created folder just contains user.js with geckdriver.
If I start a test as admin the folder contains a lots of files.

Is there a default template folder that firefox used to initialize this temporary folder.
Maybe the user can reade this template folder  ?

**Comment by Nawakator** [comment]
I've got a more precise log with latest tests.
See attached log file 
[1127136_1589704194_98.txt](https://github.com/mozilla/geckodriver/files/4642401/1127136_1589704194_98.txt)

**Comment by whimboo** [comment]
A tab is crashing for you. Please follow https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html to fetch the minidumps and how to upload those. Please send me the resulting link as described. Thanks.

**Comment by whimboo** [comment]
No reply from reporter. I'm happy to reopen when you can send us the crash details.
