### ISSUE TITLE
window.wrappedJSObject is undefined

### ISSUE THREAD

**Issue by pmeenan** [mozilla/geckodriver#1725]
Using marionette, WebPageTest needs to use window.wrappedJSObject to communicate with code on the page in the global scope.  Using the same code with webdriver throws a Javascript exception into the Python interface claiming that "window.wrappedJSObject is undefined".  Is there a supported way to communicate outside of the JS sandbox or do I need to find a different way to communicate with my extension?

```Python
driver.execute_script('return window.wrappedJSObject.wptagentGetInteractivePeriods();')
```

Actual code is [here](https://github.com/WPO-Foundation/wptagent/blob/webdriver/internal/firefox.py#L656).

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? 

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

You would have to switch into Chrome scope to have access to webextension code. By default geckodriver runs with content privileges only. See the other issue regarding setting preferences in how to do that.

**Comment by pmeenan** [comment]
Thanks.  I decided to change the extension to push data as it happens instead of to pull it from the agent so this is no longer a problem
