### ISSUE TITLE
Any way to modify prefs after the browser has started?

### ISSUE THREAD

**Issue by pmeenan** [mozilla/geckodriver#1726]
WebPageTest usually adds a PTST/xxx string to the end of the default browser UA string. To do that, it first needs to get the UA string from the browser, modify it and then update the pref for overriding the UA string with the new string.

Marionette allowed for modifying prefs at runtime, after the browser has been launched.  Is there any way to do that with the python webdriver interface?

**Comment by whimboo** [comment]
If really necessary you could temporarily [switch into chrome scope](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L226) and run `WebDriver:ExecuteScript` with code like:

```
const { Services } = ChromeUtils.import("resource://gre/modules/Services.jsm");
Services.prefs.setStringPref("general.useragent.override", new_value);
```

**Comment by pmeenan** [comment]
Worked perfectly, thanks.
