### ISSUE TITLE
Geckodriver connection refused error in centos 7

### ISSUE THREAD

**Issue by erdemontas** [mozilla/geckodriver#1735]
**System**
Version: 0.26
Platform: CentOS Linux release 7.6.1810
Firefox: 68.9.0-1.el7.centos
Selenium: 3.14.1)

In centos 7, I am having issues with geckodriver.(and chromedriver also, maybe this means something)

Here is tracelog

```
1592575949115	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/tmpnq2_u2uc.selenium" "-headless" "-foreground" "-no-remote"
1592575949116	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:37564
Running without a11y support!
*** You are running in headless mode.
1592576009147	mozrunner::runner	DEBUG	Killing process 4220
[Child 4560, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builddir/build/BUILD/firefox-68.9.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
[Child 4534, Chrome_ChildThread] WARNING: pipe error (46): Connection reset by peer: file /builddir/build/BUILD/firefox-68.9.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
Exiting due to channel error.
[Child 4622, Chrome_ChildThread] WARNING: pipe error (3): Connection reset by peer: file /builddir/build/BUILD/firefox-68.9.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 358
Exiting due to channel error.
[Child 4534, Chrome_ChildThread] WARNING: pipe error: Broken pipe: file /builddir/build/BUILD/firefox-68.9.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 727
1592576009492	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"connection refused","stacktrace":""}}
Exiting due to channel error.
```

Test case:
```
import tempfile
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
bina= r"/usr/bin/firefox"
profile = tempfile.mkdtemp(".selenium")
print("*** Using profile: {}".format(profile))

opts = Options()
opts.add_argument("-profile")
opts.add_argument(profile)
opts.add_argument('-headless')
opts.log.level = "trace"
opts.binary = bina

browser = webdriver.Firefox(options=opts, executable_path=r'/usr/bin/geckodriver')
browser.get('https://google.com')
```

Also note that when I typed geckodriver in terminal nothing happens. It just gives no output. Same behavior happens with chromedriver as well. 

Additionaly When I typed firefox, firefox opens 45-50 seconds later but no lo luck with geckodriver.

![image](https://user-images.githubusercontent.com/29041073/85157738-908f3700-b264-11ea-8cfe-6f32f16cd997.png)

EDIT:
After I see [this page](https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html),
I did `java -Dwebdriver.gecko.driver=/usr/bin` and `geckodriver ` command gives output. But still no luck with test case in a python script
Why this command related with geckodriver?

**Comment by whimboo** [comment]
Firefox is starting up very slowly on your system, and geckodriver simply stops trying to connect to it after 60s. That's why it's killing the Firefox process.

I would suggest that you create a [start-up Gecko profile](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler#Profiling_Firefox_Startup) for investigation. Hereby don't use geckodriver but directly Firefox. So run it like:

```
MOZ_PROFILER_STARTUP=1 MOZ_PROFILER_SHUTDOWN=%abs_path%/profile.json /usr/bin/firefox -marionette
```

When Firefox has been started and the location bar shows the robot icon on the left please quit Firefox by selecting `File` - `Quit`. Then you can find the created json file at the given location, which you then have to upload via https://profiler.firefox.com/, and then publish on that page. Please send us the publish URL for investigation. Thanks a lot!

**Comment by TilBlechschmidt** [comment]
This ticket is plenty old but I'm running into the same issues. The link regarding the start-up Gecko profile is unfortunately dead but I managed to capture the profile regardless:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5037967/128726598-a8d2495d-0cfa-44c2-a02f-fe15c273e1eb.png">
[69975a40-49c6-40f9-9198-eedab95ac70b_profile.json.zip](https://github.com/mozilla/geckodriver/files/6955360/69975a40-49c6-40f9-9198-eedab95ac70b_profile.json.zip)

It seems that firefox is just stuck for 50 seconds in a call to `pthread_cond_wait` presumably waiting for the Web Extension and Web Content subprocess to become responsive.

**Comment by TilBlechschmidt** [comment]
Some more details:
The system was lightly loaded (with 25 browser instances) at the time this profile was taken. A screenshot of htop is included below. It looks like the child processes of firefox take a long time to start up. However, for example the geckodriver process amongst other observed processes on the same host start and become responsive within milliseconds. This leads me to believe it has something to do with Firefox itself or the way it spawns the children / what they do after startup.

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/5037967/128743721-bda6878d-fbb3-46cc-9c65-2b1db65fe9f4.png">

**Comment by whimboo** [comment]
@TilBlechschmidt this is great information. Thanks a lot. But I think that this warrants a concrete bug for Firefox. Would you mind filing one under https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Startup%20and%20Profile%20System? Make sure to add all the details from above, and afterward reference the bug number here. 

This specific issue I will close now given that we never heard back from the original reporter.
