### ISSUE TITLE
Geckodriver for raspberry 4, raspbian buster

### ISSUE THREAD

**Issue by h4kuna** [mozilla/geckodriver#1737]
Hello i tried build geckodriver for raspbian buster, like is described here #1628 and [manual](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html).

And last step failed. Could you help me how fix it? `MOZ_TOPOBJDIR not defined`

```
$ cargo build --release --target armv7-unknown-linux-gnueabihf
   Compiling static_prefs v0.1.0 (/home/pi/testing/gecko-dev-master/modules/libpref/init/static_prefs)
   Compiling try-lock v0.2.2
   Compiling quick-error v1.2.1
   Compiling mime v0.3.16
error: environment variable `MOZ_TOPOBJDIR` not defined
  --> modules/libpref/init/static_prefs/src/lib.rs:12:5
   |
12 |     env!("MOZ_TOPOBJDIR"),
   |     ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `static_prefs`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Thank you for help.

**Comment by SpaceDevz** [comment]
Have you tried to do what you were trying again? Maybe the system couldn't handle that much processes?

**Comment by h4kuna** [comment]
I tried two times. For this moment i use chromedriver.

**Comment by whimboo** [comment]
@h4kuna can I assume that you checked out the [Github repository](https://github.com/mozilla/gecko-dev) and not the Mercurial one as it can be found at https://hg.mozilla.org/mozilla-central?

**Comment by h4kuna** [comment]
I downloaded from github zip file from master https://github.com/mozilla/gecko-dev/archive/master.zip

**Comment by whimboo** [comment]
Ok, so it's the git version. I actually noticed it myself today with Mercurial. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1649707 for that. Thanks for reporting.

**Comment by whimboo** [comment]
Actually that is a failure which comes up when you run `cargo build` from the top source dir. Make sure to first change into `testing/geckodriver`, and then run `cargo build`. That should fix it. Please let me know. Thanks.

**Comment by h4kuna** [comment]
You have right. I am sorry. Works fine.

**Comment by whimboo** [comment]
Please note that with the next release I will push the source again to Github. So there shouldn't be a need to clone mozilla-central for now.

**Comment by whimboo** [comment]
FYI for the 0.27.0 release the source is available again on the Github repo. So there is no need to clone mozilla-central.
