### ISSUE TITLE
Issues in sending fake video using gecko driver

### ISSUE THREAD

**Issue by RajathTester** [mozilla/geckodriver#1745]
## System

* Version: geckodriver-v0.26.0-win64
* Platform: Windows
* Firefox: version 77
* Selenium: 3.14

Hi i am getting '403 forbidden access' when trying to send fake mp4 video for one of the testcase. I was able to do it seamlessly in case of chrome with chrome driver using an .y4m file. Can you please help me. Any help would be highly appreciated.

**Comment by whimboo** [comment]
Without any kind of information there is nothing we can help with. Send your code or create a minized testcase that reproduces it. I'm happy to reopen the issue whenever the information has been given.
