### ISSUE TITLE
Trailing spaces are auto-generated in the input fields using Gecko driver with Selenium Java

### ISSUE THREAD

**Issue by kayalsoumya** [mozilla/geckodriver#1746]
## System-
* Version: <geckodriver-v0.26.0-macos.tar>
* Platform: <macOS + 10.13.2 (17C88)-->
* Firefox: <78.0.2 (64-bit)>
* Selenium: <3.141.59>

## Testcase-
1. Launch the firefox driver after setting up the required pre-requisite
2. Enter data in email id & password field 
3. Note the auto-generated space before the email id & password fields
4. By default, the email id & password field entries are being converted into Upper case letters

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by kayalsoumya** [comment]
> ## System-
> * Version: <geckodriver-v0.26.0-macos.tar>
> * Platform: <macOS + 10.13.2 (17C88)-->
> * Firefox: <78.0.2 (64-bit)>
> * Selenium: <3.141.59>
> 
> ## Testcase-
> 1. Launch the firefox driver after setting up the required pre-requisite
> 2. Enter data in email id & password field
> 3. Note the auto-generated space before the email id & password fields
> 4. By default, the email id & password field entries are being converted into Upper case letters



> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html).

1595344221584	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/h3/9r8g36pd5rs34v__yl0jlztm0d711w/T/rust_mozprofileGXlR4G"
1595344237311	Marionette	INFO	Listening on port 59573
1595344366228	Marionette	INFO	Stopped listening on port 59573

**Comment by kayalsoumya** [comment]
Attached the log along with the issue.

**Comment by whimboo** [comment]
This is still not a trace level log. Please confirm that by checking for `TRACE` entries beside `INFO` and `DEBUG`. Also a minimized example would be good to have.

**Comment by whimboo** [comment]
Closing issue as we haven't gotten a trace log yet. I'm happy to reopen if you provide all the requested information. thanks.
