### ISSUE TITLE
JavaScript error: resource://gre/modules/URIFixup.jsm, line 281: NS_ERROR_FAILURE: Should pass a non-null uri

### ISSUE THREAD

**Issue by sfilimonau** [mozilla/geckodriver#1748]
## System

* Version: v0.26.0-win64
* Platform: Windows 10
* Firefox: 78.0.2 64 bit
* Selenium: java-3.141.59

## Testcase

driver.manage().window().maximize();
driver.get("https://app.stylerow.com/");

Error is replicated for other URLs as well (google.com, facebook.com).
Replicated only when used driver.manage().window().maximize();

## Trace-level log

1595460748971	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Sergey\\AppData\\Local\\Temp\\rust_mozprofileK2hesW"
1595460748979	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:55902
1595460749313	Marionette	TRACE	Marionette enabled
1595460749337	Marionette	TRACE	Received observer notification toplevel-window-ready
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
1595460750462	Marionette	TRACE	Received observer notification marionette-startup-requested
1595460750462	Marionette	TRACE	Waiting until startup recorder finished recording startup scripts...
1595460750488	Marionette	TRACE	All scripts recorded.
1595460750488	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1595460750488	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1595460750488	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1595460750488	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1595460750489	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1595460750489	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1595460750489	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1595460750489	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1595460750489	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1595460750490	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1595460750490	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1595460750490	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1595460750490	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1595460750491	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1595460750491	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1595460750491	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1595460750491	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1595460750491	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1595460750491	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1595460750492	Marionette	DEBUG	Setting recommended pref dom.push.connection.enabled to false
1595460750492	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1595460750492	Marionette	DEBUG	Setting recommended pref extensions.getAddons.discovery.api_url to data:, 
1595460750492	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1595460750492	Marionette	DEBUG	Setting recommended pref privacy.trackingprotection.enabled to false
1595460750492	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1595460750493	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1595460750493	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1595460750494	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1595460750494	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1595460750524	Marionette	INFO	Listening on port 55902
1595460750524	Marionette	DEBUG	Marionette is listening
1595460750983	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:55903
1595460750983	geckodriver::marionette	DEBUG	Connection to Marionette established on 127.0.0.1:55902.
1595460750983	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1595460750984	Marionette	WARN	TLS certificate errors will be ignored for this session
1595460750997	Marionette	TRACE	[10] Frame script loaded
1595460750998	Marionette	TRACE	[10] Frame script registered
1595460751002	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"92f6f76b-f296-42b0-b472-581b9814263f","capabilities":{"browserName":"firefox","browserVersion":"78.0. ... \rust_mozprofileK2hesW","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1595460751004	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"92f6f76b-f296-42b0-b472-581b9814263f","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"78.0.2","moz:accessibilityChecks":false,"moz:buildID":"20200708170202","moz:geckodriverVersion":"0.26.0","moz:headless":false,"moz:processID":23176,"moz:profile":"C:\\Users\\Sergey\\AppData\\Local\\Temp\\rust_mozprofileK2hesW","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1595460751053	webdriver::server	DEBUG	-> POST /session/92f6f76b-f296-42b0-b472-581b9814263f/window/maximize {
}
1595460751055	Marionette	DEBUG	0 -> [0,2,"WebDriver:MaximizeWindow",{}]
JavaScript error: resource://gre/modules/URIFixup.jsm, line 281: NS_ERROR_FAILURE: Should pass a non-null uri
1595460751310	Marionette	DEBUG	0 <- [1,2,null,{"x":-8,"y":-8,"width":2576,"height":1416}]
1595460751310	webdriver::server	DEBUG	<- 200 OK {"value":{"x":-8,"y":-8,"width":2576,"height":1416}}
1595460751314	webdriver::server	DEBUG	-> POST /session/92f6f76b-f296-42b0-b472-581b9814263f/url {
  "url": "https:\u002f\u002fapp.stylerow.com\u002f"
}
1595460751314	Marionette	DEBUG	0 -> [0,3,"WebDriver:Navigate",{"url":"https://app.stylerow.com/"}]
1595460751318	Marionette	TRACE	[10] Received DOM event beforeunload for about:blank
1595460751948	Marionette	TRACE	[10] Received DOM event pagehide for about:blank
1595460753580	Marionette	TRACE	[10] Received DOM event DOMContentLoaded for https://app.stylerow.com/
1595460755141	Marionette	TRACE	[10] Received observer notification outer-window-destroyed
1595460756551	Marionette	TRACE	[10] Received DOM event pageshow for https://app.stylerow.com/
1595460756552	Marionette	DEBUG	0 <- [1,3,null,{"value":null}]
1595460756558	webdriver::server	DEBUG	<- 200 OK {"value":null}

**Comment by sfilimonau** [comment]
Similar issue has been previously reported in #1730 but while this was closed opened a new one.
Apologize for the offtop but has also the error below been tracked which is in the logs as well?
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.

**Comment by sfilimonau** [comment]
Initially specified incorrect error. Sorry for the confusion.

**Comment by whimboo** [comment]
Both of those Javascript errors are coming from Firefox and shouldn't affect your test result at all. @sfilimonau, am I correct here? It's just a side-effect of issue #1046.

**Comment by sfilimonau** [comment]
@whimboo Yes, you're right.

**Comment by whimboo** [comment]
Thanks for your quick reply. I'm going to dupe to issue #1046 then.
