### ISSUE TITLE
geckodriver: source packages for version 0.26.0 contain no source code

### ISSUE THREAD

**Issue by CFoltin** [mozilla/geckodriver#1750]
## System

* Version: 0.26.0
* Platform: All
* Firefox: n.a.
* Selenium: n.a.

## Testcase

Download and unpack https://github.com/mozilla/geckodriver/archive/v0.26.0.zip 
It contains some md files, but no code.
The same happens to the tar.gz package.

## Stacktrace

n.a. 

## Trace-level log

n.a.

**Comment by jgraham** [comment]
This is fixed with 0.27.0
