### ISSUE TITLE
[Question] Is there any publically available API to get the geckodriver latest given a firefox major version?

### ISSUE THREAD

**Issue by symonk** [mozilla/geckodriver#1751]
Does anything exist for geckodriver similar to chrome in the sense that, Given a major firefox version I can programmatically (easily - without having to parse the release(s) page with beautiful soup / do my own matrix / resolving) retrieve the latest appropriate geckodriver version?

for example:

`https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84`

I can easily parse which version of chromedriver to use given this major (84) release.  I want to do the same for Geckodriver, but struggling to find anything?

**Comment by jgraham** [comment]
We don't have anything like that at the moment. geckodriver tends to be more loosely coupled to Firefox than chromedriver is to Chrome; we typically expect to support every current release (i.e. everything since the last ESR) with each geckodriver. Currently we support Firefox back to 60.

**Comment by whimboo** [comment]
You can also check https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html for the currently supported releases of Firefox.
