### ISSUE TITLE
Provide Windows ARM64 binaries

### ISSUE THREAD

**Issue by danelkay** [mozilla/geckodriver#1754]
As Firefox now natively supports Windows ARM64 (aka aarch64), it should be possible to provide a native version of geckodriver as well.

**Comment by whimboo** [comment]
We don't have an ETA for that yet. But you can follow the status at https://bugzilla.mozilla.org/show_bug.cgi?id=1534461.

**Comment by whimboo** [comment]
Those builds will be shipped with the next geckodriver 0.32.0 release.
