### ISSUE TITLE
Leadfoot Node.js bindings fail to map errors to types

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/geckodriver#176]
In the FxA content server tests we run some scripts asynchronously using the executeAsync command. We sometimes expect these scripts to timeout. Using the old Firefox driver, the error thrown was `ScriptTimeout`. The error using Marionette/geckodriver is `script timeout` with a message of `Timed out`

Here's the trace showing the sequence:

```
15:45:29.671 INFO - Executing: [script wait: 5000])
1470926729673   Marionette  TRACE   conn0 -> [0,85,"timeouts",{"ms":5000,"type":"script"}]
1470926729673   Marionette  TRACE   conn0 <- [1,85,null,{}]
15:45:29.674 INFO - Done: [script wait: 5000]
15:45:29.676 INFO - Executing: [execute async script: return (function (command, done) {
          function check() {
            var storedEvents;
            try {
              storedEvents = JSON.parse(sessionStorage.getItem('webChannelEvents')) || [];
            } catch (e) {
              storedEvents = [];
            }

            if (storedEvents.indexOf(command) > -1) {
              done();
            } else {
              setTimeout(check, 50);
            }
          }

          check();
        }).apply(this, arguments);, [fxaccounts:login]])
1470926729678   Marionette  TRACE   conn0 -> [0,86,"executeAsyncScript",{"args":["fxaccounts:login"],"newSandbox":false,"script":"return (function (command, done) {\n          function check() {\n            var storedEvents;\n            try {\n              storedEvents = JSON.parse(sessionStorage.getItem('webChannelEvents')) || [];\n            } catch (e) {\n              storedEvents = [];\n            }\n\n            if (storedEvents.indexOf(command) > -1) {\n              done();\n            } else {\n              setTimeout(check, 50);\n            }\n          }\n\n          check();\n        }).apply(this, arguments);","scriptTimeout":null,"specialPowers":false}]
1470926729678   Marionette  INFO    sendAsync 8ef2750c-4b52-0e4b-a68a-c9d3e6edf978
1470926734684   Marionette  TRACE   conn0 <- [1,86,{"error":"script timeout","message":"Timed out","stacktrace":""},null]
15:45:35.015 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Timed out (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.01 seconds
```

The `message` field in the below line is the one we surfaced to our tests:

> 1470926734684 Marionette  TRACE   conn0 <- [1,86,{"error":"script timeout","message":"Timed out","stacktrace":""},null]

**Comment by andreastt** [comment]
geckodriver implements the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) and not the Selenium protocol. The specification moved to using string-based error codes and it looks like the Selenium client binding you are using is not mapping the WebDriver conformant error codes to the right error types.

**Comment by andreastt** [comment]
I filed https://github.com/SeleniumHQ/selenium/issues/2607.

**Comment by andreastt** [comment]
@shane-tomlinson Which version of the Selenium Node.js bindings are you using? It looks like there is support for string-based error codes in the master branch: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/error.js#L393

**Comment by shane-tomlinson** [comment]
@vladikoff - Do you happen to know the answer to @andreastt question above? Which version is Leadfoot using?

**Comment by vladikoff** [comment]
> Which version is Leadfoot using?

Custom. We don't use js from https://github.com/SeleniumHQ/selenium/tree/master/javascript/node

**Comment by andreastt** [comment]
Right, I mistakenly filed a bug on Selenium in this case. Does Leadfoot have an issue tracker?

**Comment by vladikoff** [comment]
@andreastt we got an issue going here: https://github.com/theintern/leadfoot/issues/72 or we can make a new one *shrugs*
