### ISSUE TITLE
timeout on session start

### ISSUE THREAD

**Issue by meike-hecker** [mozilla/geckodriver#1763]
Hi,

I am trying to make geckodriver work with https://github.com/Quviq/webdrv.(as reference; If you need the code I am using I can provide it)
The scenario I am facing is to test a service where access is only possible with client certificate. I want to use a profile & have firefox to accept insecure certs.

If I require insecure certs (and profile) geckodriver seems to not be able to access the browser when started.
The window opens but geckodriver returns a timeout error.
If I enter the url window the cert is picked automatically & page loads as expected.

## System

* Version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
* Platform: linux
* Firefox: 79.0
(* Selenium:) using local experimental version of https://github.com/Quviq/webdrv

## Testcase

Starting a browser with acceptInsecureCerts=true and a profile.
Browsing to locally running service.
Not sure what you need. 

## Stacktrace
%%% selenium_SUITE ==> real.request_login_page_ff: FAILED
%%% selenium_SUITE ==> {{badmatch,{error,{html_error,timeout}}},
 [{selenium_SUITE,request_login_page_ff,1,
                  [{file,"/home/meike/work/PH2/test/test/selenium_SUITE.erl"},
                   {line,195}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}

## Trace-level log

 geckodriver -v -p 9516
1597915135750	geckodriver	INFO	Listening on 127.0.0.1:9516
1597915146672	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","acceptInsecureCerts":true,"moz:firefoxOptions":{"args":["--profile selenium_admin"]}}}}
1597915146672	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1597915146672	geckodriver::capabilities	DEBUG	Found version 79.0
1597915146674	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "--profile selenium_admin" "-foreground" "-no-remote"
1597915146674	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:36127
1597915206690	mozrunner::runner	DEBUG	Killing process 27689

###!!! [Child][MessageChannel] Error: (msgtype=0x5F0006,name=PIdleScheduler::Msg_Schedule) Channel error: cannot send/recv

Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
1597915206716	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"Connection refused (os error 111)","stacktrace":""}}

**Comment by meike-hecker** [comment]
Same with: Selenium java-4.0.0-alpha-6

public static void main(String[] args) {
        System.setProperty("webdriver.gecko.driver", "/home/meike/bin/geckodriver");
        ProfilesIni profile = new ProfilesIni();
    	FirefoxProfile myprofile = profile.getProfile("selenium_admin");

        FirefoxOptions options = new FirefoxOptions();
        options.setProfile(myprofile);
        options.addArguments("--profile selenium_admin");
        options.setHeadless(false);
        options.addPreference("acceptInsecureCerts",true);
        options.setLogLevel(FirefoxDriverLogLevel.TRACE);

        WebDriver driver=new FirefoxDriver(options);
        driver.get(<url>);
        driver.close();
}

1597916545823	geckodriver	INFO	Listening on 127.0.0.1:10969
1597916599384	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "--marionette" "--profile selenium_pb_admin" "-foreground" "-no-remote"
1597916599390	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:46289
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.0.0-alpha-6', revision: '5f43a29cfc'
System info: host: 'meike-ThinkPad-T450s', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-42-generic', java.version: '14.0.2'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:603)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:136)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:188)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:176)
	at TestMyApp.main(TestMyApp.java:30)
Caused by: java.lang.RuntimeException: NettyHttpHandler request execution error
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:72)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:47)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:56)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:55)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:138)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:582)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:10969 after 60000 ms
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:201)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:57)
	... 16 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:10969 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
1597916659400	mozrunner::runner	DEBUG	Killing process 29016
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
1597916659425	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"Connection refused (os error 111)","stacktrace":""}}

**Comment by thc202** [comment]
Seems to be a duplicate of #1058.

**Comment by meike-hecker** [comment]
Sorry, for not finding the #1058 

It seems I have two issues. I am nor able to load the page when "acceptInsecureCerts":true is set (no profile set) 
I first assumed the problems are related to acceptInsecureCerts.

geckodriver -v -p 9516
1597918158825	geckodriver	INFO	Listening on 127.0.0.1:9516
1597918165927	webdriver::server	DEBUG	-> POST /session {"capabilities":{"alwaysMatch":{"browserName":"firefox","acceptInsecureCerts":true,"moz:firefoxOptions":{}}}}
1597918165928	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
1597918165928	geckodriver::capabilities	DEBUG	Found version 79.0
1597918165930	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileDDqfsn"
1597918165930	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:46565
console.error: SearchCache: "_readCacheFile: Error reading cache file:" (new Error("", "(unknown module)"))
1597918169115	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1597918169116	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1597918169116	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1597918169117	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1597918169118	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1597918169119	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1597918169119	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1597918169120	Marionette	DEBUG	Setting recommended pref browser.tabs.remote.separatePrivilegedContentProcess to false
1597918169120	Marionette	DEBUG	Setting recommended pref browser.tabs.unloadOnLowMemory to false
1597918169120	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1597918169120	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1597918169121	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1597918169121	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1597918169122	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1597918169123	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1597918169123	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1597918169123	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1597918169124	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1597918169124	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1597918169125	Marionette	DEBUG	Setting recommended pref dom.push.connection.enabled to false
1597918169126	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1597918169126	Marionette	DEBUG	Setting recommended pref extensions.getAddons.discovery.api_url to data:, 
1597918169126	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1597918169126	Marionette	DEBUG	Setting recommended pref privacy.trackingprotection.enabled to false
1597918169126	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1597918169127	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1597918169127	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1597918169130	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1597918169224	Marionette	INFO	Listening on port 46565
1597918169224	Marionette	DEBUG	Marionette is listening
1597918169247	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:43326
1597918169267	geckodriver::marionette	DEBUG	Connection to Marionette established on 127.0.0.1:46565.
1597918169269	Marionette	DEBUG	0 -> [0,1,"WebDriver:NewSession",{"acceptInsecureCerts":true,"browserName":"firefox"}]
1597918169270	Marionette	WARN	TLS certificate errors will be ignored for this session
1597918169315	Marionette	DEBUG	0 <- [1,1,null,{"sessionId":"90c6db1a-57b0-4246-83ed-c5d4fcd3a38f","capabilities":{"browserName":"firefox","browserVersion":"79.0" ... /rust_mozprofileDDqfsn","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1597918169318	webdriver::server	DEBUG	<- 200 OK {"value":{"sessionId":"90c6db1a-57b0-4246-83ed-c5d4fcd3a38f","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"79.0","moz:accessibilityChecks":false,"moz:buildID":"20200720193547","moz:geckodriverVersion":"0.27.0","moz:headless":false,"moz:processID":33407,"moz:profile":"/tmp/rust_mozprofileDDqfsn","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"linux","platformVersion":"5.4.0-42-generic","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1597918169361	webdriver::server	DEBUG	-> GET /status 
1597918169361	webdriver::server	DEBUG	<- 200 OK {"value":{"message":"Session already started","ready":false}}
1597918169362	webdriver::server	DEBUG	-> POST /session/90c6db1a-57b0-4246-83ed-c5d4fcd3a38f/url {"url":"https://172.17.0.2:3001/gui/#/"}
1597918169363	Marionette	DEBUG	0 -> [0,2,"WebDriver:Navigate",{"url":"https://172.17.0.2:3001/gui/#/"}]
1597918469386	Marionette	DEBUG	0 <- [1,2,{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/cont ... 5:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:381:11\n"},null]
1597918469387	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:381:11\n"}}
JavaScript error: resource://gre/modules/URIFixup.jsm, line 281: NS_ERROR_FAILURE: Should pass a non-null uri

**Comment by meike-hecker** [comment]
workaround for #1058 worked
