### ISSUE TITLE
Page load stuck after few runs

### ISSUE THREAD

**Issue by roysouma** [mozilla/geckodriver#1765]
## System

* Version: 0.27.0
* Platform: Windows 10
* Firefox: 68.11.0esr (64-bit)
* Selenium: 3.141.0

## Testcase

driver.Navigate().GoToUrl("url");

## Stacktrace

No error thrown. Driver is just stuck at loading page. First couple of times everything runs as expected, then suddenly navigate to url gets stuck in 3rd or 4th run.

## Trace-level log

1597995105647   geckodriver     INFO    Listening on 127.0.0.1:50226
1597995108094   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\roysouma\\AppData\\Local\\Temp\\rust_mozprofilevp8s1o"
1597995108101   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:50232
1597995110108   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:50232.
1597995110147   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"075d55f5-af57-416f-afcc-1de07ef7f262","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"68.11.0","moz:accessibilityChecks":false,"moz:buildID":"20200720181548","moz:geckodriverVersion":"0.27.0","moz:headless":false,"moz:processID":28588,"moz:profile":"C:\\Users\\roysouma\\AppData\\Local\\Temp\\rust_mozprofilevp8s1o","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
1597995110152   webdriver::server       DEBUG   -> POST /session/075d55f5-af57-416f-afcc-1de07ef7f262/window/maximize {}
1597995110154   webdriver::server       DEBUG   <- 200 OK {"value":{"x":-7,"y":-7,"width":1295,"height":695}}
1597995110367   webdriver::server       DEBUG   -> POST /session/075d55f5-af57-416f-afcc-1de07ef7f262/url {"url":"https://docs.corp.amazon.com/WebViewer/#/"}
1597995410390   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:371:11\n"}}

**Comment by roysouma** [comment]
The issue is pretty frustrating as suite runs absolutely fine for a couple of runs and then page load gets stuck. On opening the URL manually, the URL loads properly which confirms the issue is with geckodriver, as with Chromedriver this issue is not encountered.

**Comment by whimboo** [comment]
Is that Java, .net, or which specific language? Each binding has its own implementation and will differ.

**Comment by roysouma** [comment]
It is in .Net

**Comment by whimboo** [comment]
Ok, so not sure what's going wrong then. What you could do instead is to set the following preference for Firefox: `marionette.log.level=Trace`. It should have the same effect for Marionette, where I would need the information from. Thanks.

**Comment by roysouma** [comment]
Hi, adding this line profile.SetPreference("marionette.log.level", "Trace"); reduced the verbosity rather. I think I have written it incorrect. Can you please provide the correct syntax that you mentioned above?
`FirefoxOptions options = new FirefoxOptions();
            if (headless)
            {
                options.AddArguments("--headless");
            }

            var profileManager = new FirefoxProfileManager();
            var profile = profileManager.GetProfile(Profile);
            if (!string.IsNullOrEmpty(optionalDownloadPath))
            {
                profile.SetPreference("marionette.log.level", "Trace");
                profile.SetPreference("browser.download.folderList", 2);
                profile.SetPreference("browser.download.dir", optionalDownloadPath);
                profile.SetPreference("browser.helperApps.neverAsk.saveToDisk", "text/csv,image/png,image/jpeg,text/html,text/plain,application/msword,application/pdf,application/x-pdf,application/download,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                profile.SetPreference("browser.helperApps.neverAsk.openFile", "text/csv,image/png,image/jpeg,text/html,text/plain,application/msword,application/pdf,application/x-pdf,application/download,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                profile.SetPreference("browser.download.manager.focusWhenStarting", false);
                profile.SetPreference("browser.download.useDownloadDir", true);
                profile.SetPreference("browser.helperApps.alwaysAsk.force", false);
                profile.SetPreference("browser.download.manager.alertOnEXEOpen", false);
                profile.SetPreference("browser.download.manager.closeWhenDone", true);
                profile.SetPreference("browser.download.manager.showAlertOnComplete", false);
                profile.SetPreference("browser.download.manager.useWindow", false);
                profile.SetPreference("services.sync.prefs.sync.browser.download.manager.showWhenStarting", false);
                profile.SetPreference("pdfjs.disabled", true);
                options.SetPreference("pdfjs.enabledCache.state", false);
                profile.SetPreference("plugin.scan.plid.all", false);
                profile.SetPreference("plugin.scan.Acrobat", "99.0");
                profile.SetPreference("plugin.disable_full_page_plugin_for_types", "application/pdf,application/vnd.adobe.xfdf,application/vnd.fdf,application/vnd.adobe.xdp+xml");
            }

            options.Profile = profile;
            var webDriver = new FirefoxDriver(_firefoxDriverService, options, TimeSpan.FromMinutes(customTimeout));
            webDriver.Manage().Window.Maximize();

            return webDriver;`

This is how my driver is getting created.

**Comment by whimboo** [comment]
I never worked with the .net bindings so I cannot say for sure. But the code above looks reasonable.

**Comment by roysouma** [comment]
Ya and things also work fine for around 3-4 runs before the issue occurs. I checked the ports being used also and marionette picks up a free port only. Really getting difficult to find the root cause. One thing which I have consistently found is this happens in case of back to back runs. If a sufficient time gap is there between runs I have seen the occurrence reduce.

**Comment by roysouma** [comment]
As per the site https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html the code snippet mentioned for trace logs, I had used while posting the issue and with this code snippet I got the trace which I have provided earlier.

**Comment by whimboo** [comment]
Without having a Marionette trace log we aren't able to help because it would include some very helpful information. I'm not sure why it's not part of the generated log files. Maybe there is a problem with the .net bindings.

Other things you could try are:
* Do other drivers like chromedriver also show that?
* Are you using a proxy, which could malfunction for repeatedly requested page loads?
* Try to use WireShark and check what data actually gets returned after start loading the page. Maybe it's not a problem with Firefox / Marionette but the network?

**Comment by roysouma** [comment]
I'm not using proxy but I'm connected to office VPN and I have tested with chromedriver and this issue doesn't occur there. I have ran 20 times also back to back with chromedriver and it runs fine. With marionette, max successful runs have been 4 and then the issue occurs.
So there is no problem with the network.
And for the generated log files would it generate anything else before page load? I see the error in the log above as 1597995410390 webdriver::server DEBUG <- 500 Internal Server Error {"value":{"error":"timeout","message":"Timeout loading page after 300000ms","stacktrace":"WebDriverError@chrome://marionette/content/error.js:175:5\nTimeoutError@chrome://marionette/content/error.js:444:5\nnotify@chrome://marionette/content/listener.js:371:11\n"}}

I will check with wireshark and update the thread. But till then is there any flag to increase log verbosity?

**Comment by whimboo** [comment]
Again. Set the `marionette.log.level=Trace` preference. By doing that entries like these have to appear in the log:

```
0:09.54 pid:66996 1598436963460	Marionette	DEBUG	0 -> [0,4,"WebDriver:Navigate",{"url":"http://web-platform.test:8000/webdriver/tests/support/html/frames.html"}]
 0:09.54 pid:66996 1598436963467	Marionette	TRACE	[10] Received DOM event beforeunload for about:blank
 0:09.58 pid:66996 1598436963503	Marionette	TRACE	[10] Received DOM event pagehide for about:blank
 0:09.60 pid:66996 1598436963514	Marionette	TRACE	[10] Received DOM event DOMContentLoaded for http://web-platform.test:8000/webdriver/tests/support/html/frames.html
 0:09.70 pid:66996 1598436963624	Marionette	TRACE	[10] Received DOM event pageshow for http://web-platform.test:8000/webdriver/tests/support/html/frames.html
 0:09.70 pid:66996 1598436963624	Marionette	DEBUG	0 <- [1,4,null,{"value":null}]
```

**Comment by whimboo** [comment]
No further reply from reporter. As such closing the issue.
