### ISSUE TITLE
"path to the driver executable must be set by the webdriver.gecko.driver system property"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/geckodriver#177]
The following exception is not clear:

> Exception: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

The [README.md](https://github.com/mozilla/geckodriver/blob/master/README.md) does not provide any info on `webdriver.gecko.driver`.

What is a `system property`? Is it a capability or a firefox profile option?

**Comment by jgraham** [comment]
I… have no idea. I guess this error is coming from the client bindings [1] probably.

[1] https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L110

**Comment by vladikoff** [comment]
uh oh that code is from 2012 as well. 📼

**Comment by vladikoff** [comment]
I'm guessing setting `setPreference('webdriver.gecko.driver'` is not gonna do anything because geckodriver or Firefox do not support that. 

cc @barancev

**Comment by AutomatedTester** [comment]
This is https://github.com/SeleniumHQ/selenium/issues/2600 so am closing.
