### ISSUE TITLE
Can Firefox be launched with geckodriver while displaying Firefox without using --connect-existing?

### ISSUE THREAD

**Issue by marvinirwin** [mozilla/geckodriver#1775]
## System

* Version: geckodriver 0.27.0 (7b8c4f32cdde 2020-07-28 18:16 +0000)
* Platform: Debian GNU/Linux 10 (buster)
* Firefox: 80.0.1 (64-bit)
* Selenium: N/A

I can run firefox with the correct DISPLAY value and make it use the display I would like

`$ DISPLAY=host.docker.internal:0 /opt/firefox/firefox `

I can run geckodriver successfully using the same Firefox binary, but firefox will not use the Window specified in DISPLAY

`$ DISPLAY=host.docker.internal:0 geckodriver --binary=/opt/firefox/firefox "--host=0.0.0.0"`

However I can orchestrate it with the display I want with --connect-existing

```
$ EXPORT DISPLAY=host.docker.internal:0
$ /opt/firefox/firefox --marionette & geckodriver --connect-existing --marionette-port 2828
```

**Comment by whimboo** [comment]
Can you please check which environment variables have been passed through geckodriver to firefox process? Is the `DISPLAY` one set? Usually we pass-through all of them.
