### ISSUE TITLE
How to set firefox preferences to download/save files

### ISSUE THREAD

**Issue by SureshB123** [mozilla/geckodriver#1776]
## System

* Platform: Windows 10
* Firefox: 80.0.1
* Selenium: 3.141.59

## Testcase
Hi,

My preferences for chrome in serenity properties file is as follows:

chrome_preferences.download.default_directory=${user.dir}\\src\\test\\resources\\Downloads
chrome_preferences.downloadPath=${user.dir}\\src\\test\\resources\\Downloads
chrome_preferences.download.directory_upgrade=true
chrome_preferences.profile.default_content_settings.popups=0
chrome_preferences.download.prompt_for_download=false
chrome_preferences.safebrowsing.enabled=false
chrome_preferences.safebrowsing.disable_download_protection=true
chrome_preferences.behavior=allow

It's perfectly working fine when i am running my scripts and trying to download Excel/PDF on chrome.

For Firefox, i kept my preferences in properties file as follows:

firefox.preferences("browser.download.folderList", 2)
firefox.preferences("browser.helperApps.alwaysAsk.force", false)
firefox.preferences("browser.download.dir", ${user.dir}\\src\\test\\resources\\Downloads)
firefox.preferences("browser.download.defaultFolder",${user.dir}\\src\\test\\resources\\Downloads)
firefox.preferences("browser.download.manager.showWhenStarting", false)

browser is launching but i am getting save popup as we usually get after downloading in firefox.

and also, i tried this

firefox.preferences="browser.download.dir=${user.dir}\\src\\test\\resources\\Downloads;browser.helperApps.alwaysAsk.force=false;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.download.folderList=2;"

In this case, browser is not launching.

Where am i going wrong here.

**Comment by SureshB123** [comment]
Below property worked for me:

**firefox.preferences=browser.download.folderList=2;browser.helperApps.alwaysAsk.force=false;browser.download.dir=${user.dir}\\src\\test\\resources\\Downloads;browser.download.manager.showWhenStarting=false;browser.download.useDownloadDir=true;browser.helperApps.neverAsk.saveToDisk=multipart/x-zip, application/zip, application/x-zip-compressed, application/x-compressed, application/msword, application/csv, text/csv, image/png , image/jpeg, application/pdf, text/html, text/plain, application/excel, application/vnd.ms-excel, application/x-excel, application/x-msexcel, application/octet-stream**

But for PDF firefox opens the pdf in another tab insted of downloading it. 
Do we have any solution for this?

**Comment by whimboo** [comment]
Maybe set `pdfjs.disabled=true` to disable the internal PDF viewer.

**Comment by SureshB123** [comment]
Thanks @whimboo , it worked 👍
