### ISSUE TITLE
Missing link in 0.27.0 release notes

### ISSUE THREAD

**Issue by simonw** [mozilla/geckodriver#1782]
The release notes here: https://github.com/mozilla/geckodriver/releases/tag/v0.27.0

<img width="1122" alt="Release_0_27_0_·_mozilla_geckodriver" src="https://user-images.githubusercontent.com/9599/94971272-81529300-04bb-11eb-8cba-89b3c8ee7806.png">

That should link here: https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html

**Comment by whimboo** [comment]
Thanks for reporting! I've updated the release notes now.
