### ISSUE TITLE
Informative output on stderr

### ISSUE THREAD

**Issue by qabi** [mozilla/geckodriver#1784]
## System

* Version: 0.27.0
* Platform: Ubuntu
* Firefox: Version 81
* Selenium: Java library

When using geckodriver in cron jobs, it is a problem that some lines are printed to stderr, as this indicates to the surroundings that something went wrong.

I get the following lines:

`okt. 05, 2020 5:00:10 AM org.openqa.selenium.remote.ProtocolHandshake createSession`
`INFO: Detected dialect: W3C`

If I understand correctly the first line comes from firefox, and the second one from the Java selenium framework. In both cases they should not be printed to stderr, but stdout. I have found no settings or such that can fix this. (Driver output is already set to stdout, log level set to WARN etc.)

**Comment by whimboo** [comment]
No, both of these lines are coming from Selenium. You should create an issue on their repository. Thanks.
