### ISSUE TITLE
Selenium can't find firefox on android... where is firefox binary in android?

### ISSUE THREAD

**Issue by digilevi2006** [mozilla/geckodriver#1789]
Hello FF devs,

I tried to use selenium in python beeware, and geckodriver is correctly opening the geckodriver in `/data/user/0/com.example.helloworld/lib/./lib_geckodriver.so` but it throws error like this:

`Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox`

will selenium firefox work on android or iOS? Should I post this in Selenium instead? 

I am actually using Android studio with genymotion Emulator on osx. I downloaded the Intel apk from 
`https://download.mozilla.org/?product=fennec-latest&os=android-x86&lang=multi`

Thanks everyone.

**Comment by whimboo** [comment]
All you have to setup is the `androidPackage` in the `moz:firefoxOptions` capabilities. See https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#android for details. Then it will automatically connect to the emulator or device.

**Comment by digilevi2006** [comment]
Hi @whimboo 

Thank you for your reply. I have seen that article before and would like to ask first if it’s possible to package the geckodriver inside the apk and run it as a standalone android app? If not geckodriver, the geckoview? Or is it an impossible task? I just thought it would be possible like what i did with my selenium python - pyinstaller windows cli program. 
i’m actually using beeware to package all to android. 
if you say it’s not possible then i’ll stop from this point. 

Thanks

**Comment by whimboo** [comment]
No, we don't package it and the shipped geckodriver releases will run on the host device, and not the device itself.

**Comment by digilevi2006** [comment]
I see. How bout the geckoview which i suppose a module/plugin for android?

**Comment by whimboo** [comment]
Note that GeckoView is an Android component that can be embedded into any application. But you cannot use it directly. Means you always need an Android package to start and therefore need at least the `androidPackage` capability.

But this discussion is off-topic to the initial question and as such I'm going to lock this issue.
