### ISSUE TITLE
Unable to lanuch the Firefox browser on an Android device via geckodriver

### ISSUE THREAD

**Issue by mohammedyouness** [mozilla/geckodriver#1791]
## System

* Version: geckodriver v0.27.0 (2020-07-27, 7b8c4f32cdde)
* Platform: Windows 10 (64-bit) 
* Firefox: v81.1.4 
* Selenium: 3.141.0 

## Testcase
`options = webdriver.FirefoxOptions()
options.add_experimental_option("androidPackage", "org.mozilla.firefox")
options.add_experimental_option("androidUseRunningApp", True)
driver = webdriver.Firefox("C:\\Users\\mhmdyunus\\Downloads\\Drivers\\geckodriver.exe", options=options)
driver.get("https://www.google.com")
driver.quit()`

## Stacktrace
AttributeError: type object 'Options' has no attribute 'add_experimental_option'

## Trace-level log
[geckodriver.log](https://github.com/mozilla/geckodriver/files/5371237/geckodriver.log)

## Detailed-Explanation
I've already a python script that is responsible for launching the Chrome browser on an android device and It works fine with no problem, and here's the code
`from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_experimental_option("androidPackage", "com.android.chrome")
options.add_experimental_option('androidUseRunningApp', True)
driver = webdriver.Chrome("C:\\Users\\mhmdyunus\\Downloads\\Drivers\\chromedriver.exe", options=options)
driver.get("https://www.google.com")
driver.quit()
`
Recently, Android support has been added to geckodriver: https://github.com/mozilla/geckodriver/releases/tag/v0.27.0

What I'm trying to do is that I want to reconfigure/customize the above code, so It can launch the Firefox browser Instead of the Chrome browser. but, I am not able to do so due to the above error

**Comment by t3ch9** [comment]
Geckodriver: v0.27.0
Platform: Windows 10 (64-bit)
Android Firefox: v81.1.2
Selenium: 3.141.0

I am experiencing the same issue. Unable to connect python selenium webdriver/geckodriver to Firefox on Android.

For connecting selenium webdriver/chromedriver, I use to following code to connect to Chrome on Android:

from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_experimental_option('androidPackage', 'com.android.chrome')
driver = webdriver.Chrome("C:\\chromedriver.exe", options=options)

What would be the corresponding python code to connect selenium webdriver/geckodriver to Firefox on Android?

**Comment by t3chd** [comment]
> Geckodriver: v0.27.0
> Platform: Windows 10 (64-bit)
> Android Firefox: v81.1.2
> Selenium: 3.141.0
> 
> I am experiencing the same issue. Unable to connect python selenium webdriver/geckodriver to Firefox on Android.
> 
> For connecting selenium webdriver/chromedriver, I use to following code to connect to Chrome on Android:
> 
> from selenium import webdriver
> options = webdriver.ChromeOptions()
> options.add_experimental_option('androidPackage', 'com.android.chrome')
> driver = webdriver.Chrome("C:\webdrivers\chromedriver.exe", options=options)
> 
> What would be the corresponding python code to connect selenium webdriver/geckodriver to Firefox on Android?

Same problem. I am using Firefox Nightly: 201009 17:03 Build #2015768715

**Comment by whimboo** [comment]
As the failure shows the problem is that you are trying to use a non-existent method. For Firefox options there is no such `add_experimental_option` available. As such you will have to adapt your code to set specific options only if Chrome is used.
