### ISSUE TITLE
HTTP Error 429: too many requests when downloading geckodriver on Travis

### ISSUE THREAD

**Issue by idgserpro** [mozilla/geckodriver#1793]
When I try to download geckodriver on Travis, I get the error below:

```
$ wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
--2020-10-14 14:20:34--  https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 429 too many requests
2020-10-14 14:20:34 ERROR 429: too many requests.


The command "wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz" failed and exited with 8 during .
```

See: https://travis-ci.org/github/collective/collective.cover/jobs/735735429#L1683

It seems that github limits the number of requests. Is there any other place to download geckodriver? Any suggestions on how to get around the problem?

**Comment by thc202** [comment]
Travis CI allows to cache files between builds: https://docs.travis-ci.com/user/caching/#arbitrary-directories

**Comment by idgserpro** [comment]
@thc202 thanks for your response! This would lessen the problem. However, the cache expires in 28 days:

https://docs.travis-ci.com/user/caching/#caches-expiration

 So, that would not be a definitive solution. Is there any other repository where I can download geckodriver?

**Comment by whimboo** [comment]
This is not a problem with geckodriver but your CI setup. Cache the binary as requested and refresh the cache regularly but not for each and every CI job.
