### ISSUE TITLE
For python on windows 10, geckodriver.exe is returning Unable to find matching set of capabilities

### ISSUE THREAD

**Issue by jhok2013** [mozilla/geckodriver#1795]
## System

* Version: geckodriver 0.27.0
* Platform: Windows 10
* Firefox: 81.0.2 (64-bit)
* Selenium: 3.141.0

## Testcase

```{python}
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

opts: Options = Options()
opts.headless = True

browser = webdriver.Firefox(
    executable_path=r"C:\\project\\bin\\geckodriver-win32.exe",
    options=opts
)

browser.get("https://google.com")
browser.quit()
```

## Stacktrace

Traceback (most recent call last):
  File ".\test_name_gen_api.py", line 24, in test_get_names
    self.name_gen_api.get_names(race_name='aasimar', source='default')
  File "..\dndnamegen\name_gen_api.py", line 39, in get_names
    browser = webdriver.Firefox(
  File "C:\Python\Python38\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
matching set of capabilities

## Trace-level log

1602881253577	geckodriver	INFO	Listening on 127.0.0.1:55210
1602882030501	geckodriver	INFO	Listening on 127.0.0.1:55382
1602882084358	geckodriver	INFO	Listening on 127.0.0.1:55404
1602882148365	geckodriver	INFO	Listening on 127.0.0.1:55425
1602882265640	geckodriver	INFO	Listening on 127.0.0.1:55472
1602882775338	geckodriver	INFO	Listening on 127.0.0.1:55578
1602883298460	geckodriver	INFO	Listening on 127.0.0.1:55775

After it runs into this problem the general log doesn't log anything else.

**Comment by noobmonxter** [comment]
### I was also searching for a fix, and came across this.


```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
cap = DesiredCapabilities().FIREFOX
cap["marionette"] = False
driver = webdriver.Firefox(capabilities=cap)
driver.get('https://example.com/')
```

**Comment by whimboo** [comment]
You actually hit a crash of Firefox, and specifically of a tab. To retrieve more details about this crash please follow the instructions from https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html.

**Comment by livelace** [comment]
It's easy to check, tbh.
According to https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html

```
curl -H 'Content-Type: application/json' -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session

user@localhost ~ $ ./.local/bin/geckodriver --log trace
1603281936652   geckodriver     INFO    Listening on 127.0.0.1:4444
1603281943706   webdriver::server       DEBUG   -> POST /session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}
1603281943706   geckodriver::capabilities       DEBUG   Trying to read firefox version from ini files
1603281943706   geckodriver::capabilities       DEBUG   Trying to read firefox version from binary
1603281943730   geckodriver::capabilities       DEBUG   Found version Mozilla Firefox 80.0
1603281943730   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}

```

if set empty capabilities - it works.
```
browser = webdriver.Firefox(executable_path="/usr/bin/geckodriver", options=browser_options, desired_capabilities={}, capabilities={})
```

It's not about tabs or crash, this question about compatibility.

**Comment by whimboo** [comment]
@livelace your issue is #1756, which should not be the same as what the original reporter is having.

**Comment by fenchu** [comment]
Try with latest betadrivers `pip install selenium==4.0.0a6.post2`

**Comment by whimboo** [comment]
@jhok2013 do you have some updates regarding my comment from 9 days ago?
