### ISSUE TITLE
How to save a web page as PDF use selenium webdriver?

### ISSUE THREAD

**Issue by SigmaBM** [mozilla/geckodriver#1800]
## System

* Version: 0.27.0
* Platform: MacOS 10.15.7
* Firefox: 82.0
* Selenium: 3.141.0

## Testcase

```
from selenium import webdriver

options = webdriver.FirefoxOptions()
profile = webdriver.FirefoxProfile()

browser = webdriver.Firefox(firefox_options=options, firefox_profile=profile)
browser.get('https://www.google.com')
browser.execute_script("window.print();")
browser.quit()
```

How should I set the options and profile to save the page as PDF? And set the save path and print options?

**Comment by whimboo** [comment]
geckodriver already supports the [WebDriver Print](https://w3c.github.io/webdriver/#print) command. So you will have to wait until the Selenium bindings will actually support it. See https://github.com/SeleniumHQ/selenium/issues/8802.
