### ISSUE TITLE
 for Mozilla FireFox, .setValue() picks the wrong value in notcustom drop-down

### ISSUE THREAD

**Issue by KapustinMaxim** [mozilla/geckodriver#1802]
## System

* Version: 0.27.0
* Platform: Windows 7
* Firefox: firefox (82.0.1)
* Selenium: selenium-webdriver: 4.0.0-alpha.7

## Testcase

steps:

run test.js in mozilla FireFox browser
.setValue('css selector','.select-language','Deutsch') piks "Español"
.setValue('css selector','.select-language',"fr") piks "Română‎"

expected results
.setValue('css selector','.select-language','Deutsch') piks "Deutsch"
.setValue('css selector','.select-language',"fr") piks "Français"

```
module.exports = {
        'step 1' :  function (browser) {
        browser
          .url('http://www.w3bai.com/ru/w3css/w3css_dropdowns.html')
          .maximizeWindow()
        
          .pause(1000)
          .waitForElementVisible('css selector','select.form-control:nth-child(1)',' visible')
    
          .setValue('css selector','.select-language','Deutsch')
          .pause(1000)
          .setValue('css selector','.select-language',"fr")
          .pause(1000)
          .end(); 
               },    };
```

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by KapustinMaxim** [comment]
this is it?

13:27:10.129 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
13:27:10.188 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4144
2020-10-30 13:27:10.219:INFO::main: Logging initialized @207ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:27:10.387 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
13:27:10.510 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4144
13:27:15.296 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptSslCerts": true,
  "browserName": "firefox",
  "firefox": {
    "w3c": false
  },
  "javascriptEnabled": true,
  "marionette": true,
  "name": "Temp"
}
13:27:15.297 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1604039235331	geckodriver	INFO	Listening on 127.0.0.1:23934
1604039236122	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "e:\\Temp\\rust_mozprofile6BVoi0"
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1604039237822	Marionette	INFO	Listening on port 50149
13:27:18.309 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
13:27:18.341 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 5cafbea0-3279-4448-8f22-64d67494a505 (org.openqa.selenium.firefox.GeckoDriverService)
JavaScript error: http://www.w3bai.com/ru/w3css/w3css_dropdowns.html, line 51: ReferenceError: $ is not defined
JavaScript error: http://www.w3bai.com/lib/w3schools_footer.js, line 268: ReferenceError: LRS is not defined
JavaScript error: http://www.w3bai.com/lib/custom.js, line 4: ReferenceError: $ is not defined
JavaScript error: http://www.w3bai.com/lib/w3schools_footer.js, line 21: ReferenceError: googletag is not defined
Can't find symbol 'eglSwapBuffersWithDamageEXT'.
1604039245822	Marionette	INFO	Stopped listening on port 50149

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost


###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

13:27:26.242 INFO [ActiveSessions$1.onStop] - Removing session 5cafbea0-3279-4448-8f22-64d67494a505 (org.openqa.selenium.firefox.GeckoDriverService)

**Comment by whimboo** [comment]
No, it's not. Is a geckodriver.log file being created in the current working directory? It has to contain entries like the following:

```
1604072704644	Marionette	DEBUG	2 -> [0,11,"WebDriver:FindElement",{"using":"css selector","value":"select.form-control:nth-child(1)"}]
1604072704659	Marionette	DEBUG	2 <- [1,11,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"bf469f26-b569-6643-a335-4f09750570a7"}}]
1604072704683	Marionette	DEBUG	2 -> [0,12,"WebDriver:FindElement",{"using":"xpath","value":"/html/body/div[2]/div/ul[2]/li[1]/div/select/option[5]"}]
1604072704692	Marionette	DEBUG	2 <- [1,12,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"2bc1e06e-d3f9-2b4d-be87-ee3c7e66c322"}}]
1604072704707	Marionette	DEBUG	2 -> [0,13,"WebDriver:GetElementProperty",{"id":"2bc1e06e-d3f9-2b4d-be87-ee3c7e66c322","name":"value"}]
1604072704730	Marionette	TRACE	[2147483672] Child actor created for window id 2147483709
1604072704731	Marionette	TRACE	[2147483672] Parent actor created
1604072704741	Marionette	DEBUG	2 <- [1,13,null,{"value":"de"}]
de
1604072704746	Marionette	DEBUG	2 -> [0,14,"WebDriver:ElementClick",{"id":"2bc1e06e-d3f9-2b4d-be87-ee3c7e66c322"}]
1604072704757	Marionette	TRACE	Received message beforeunload for http://www.w3bai.com/ru/w3css/w3css_dropdowns.html
JavaScript error: , line 0: uncaught exception: undefined
1604072705394	Marionette	TRACE	Received message pagehide for http://www.w3bai.com/ru/w3css/w3css_dropdowns.html
1604072705524	Marionette	TRACE	Received message DOMContentLoaded for http://www.w3bai.com/de/w3css/w3css_dropdowns.html
```

As you can see in my log it's not possible to use a CSS selector for the option given that all of them are identical. Instead I used an XPATH selector and that correctly retrieved the element, and actually caused the German version of the page to be loaded.

As long as it is not clear what `.setValue('css selector','.select-language','Deutsch')` actually does - and here we need the trace logs - there is nothing we can actually do. I'm happy to reopen and check again if you can provide trace logs.
