### ISSUE TITLE
Selenium in IPython: Process unexpectedly closed with status 11

### ISSUE THREAD

**Issue by huytrvan** [mozilla/geckodriver#1804]
## System

* Version: 0.28.0
* IPython: 7.19.0
* OS: Ubuntu 20.10
* Firefox: 82.0
* Selenium: 3.141.0
* Python3 venv

## Testcase
```
from selenium import webdriver

driver = webdriver.Firefox(
    executable_path='.driver/geckodriver')
```
## Stacktrace
For Gecko 0.28.0:
```
WebDriverException: Message: Process unexpectedly closed with status 11
```

Later I try Gecko 0.27.0:
```
WebDriverException: Message: invalid argument: can't kill an exited process
```
## Trace-level log
For Gecko 0.28.0:
```
1604671176046	geckodriver	INFO	Listening on 127.0.0.1:52981
1604671177061	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileeF7rKv"
1604671177063	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:35135
1604671190021	Marionette	TRACE	Marionette enabled
ExceptionHandler::GenerateDump cloned child 5798ExceptionHandler::WaitForContinueSignal waiting for continue signal...

ExceptionHandler::SendContinueSignalToChild sent continue signal to child
1604671190614	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 11","stacktrace":""}}
```

For Gecko 0.27.0:
```
1604737362943	geckodriver	INFO	Listening on 127.0.0.1:33027
1604737362957	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile4d7Ge9"
ExceptionHandler::GenerateDump cloned child 19624
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```
## Description:
The testcase above works only in `terminal` but not `IPython` (from official Python extension VSCode). I try to reinstall `python3 venv` and different gecko version but nothing works.

If you need additional info I would love to provide.

**Comment by huytrvan** [comment]
**Here is the the Crash Report folder**
[tmpcyoi8p9z.selenium.zip](https://github.com/mozilla/geckodriver/files/5504376/tmpcyoi8p9z.selenium.zip)

**Comment by huytrvan** [comment]
This problem only happens with latest Firefox (82.0) for Ubuntu and geckodriver (0.28). 
I have tested with latest Chrome driver and no issue found there.

**Comment by whimboo** [comment]
Thank you for the report, and the attached profile folder of Firefox. I just submitted the contained minidump file, and here are the details about this crash of Firefox:

https://crash-stats.mozilla.org/report/index/98e21585-70d0-486d-be9f-c46720201112

The crash here seems to be related to some system libraries, specifically `libpng16`. Can you please check if that related package is up-to-date? Also is that problem particularly new since one of the recent Firefox updates? Did you also see it with older releases of Firefox?

**Comment by huytrvan** [comment]
@whimboo, thank you for your comment. 
`Geckodriver` worked before I updated my `Ubuntu` 20.04 to 20.10. 
It is possible that there is problem with `libpng16` package like the report said.
It could also be incompatibility `geckodriver` 0.28 and `firefox` 82.0, I assume, because `firefox` was updated as well. 
Anyways, I can't confirm your questions right now so I will have to close this issue. 
Thanks again

**Comment by whimboo** [comment]
@huytrvan, would you mind to check if older Firefox releases are affected by that? Like the version you used before the upgrade to Ubuntu 20.10. If that also fails we could isolate it to the libpng16 package.


You can always download an archive of the release from https://archive.mozilla.org/pub/firefox/releases/.
