### ISSUE TITLE
Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result

### ISSUE THREAD

**Issue by ewwerpm** [mozilla/geckodriver#1807]
## System

* Version: 
* Platform: windows 7
* Firefox: 82.0.3 (64 位)
* Selenium: geckodriver 0.27.0

## Testcase

styleMy = driver.find_element_by_xpath("//*[@id='show_msg']")
#styleMy = driver.find_element_by_id("show_msg")
print(styleMy.is_displayed())
print("********************")
visibilityMy = driver.find_element_by_id("show_msg").get_attribute('style')
print(visibilityMy)
if(visibilityMy.find("visibility: visible")>=0):
  
程序是为了检测http://xkz.cbirc.gov.cn/jr/ 网站的验证码窗口的。以上两种写法，在chrome里完美检测，在Firefox里，都有几率检测不到验证码。

## Stacktrace
参考: 1、https://www.newsmth.net/nForum/#!article/Python/159970
2、https://stackoverflow.com/questions/64300232/why-does-selenium-return-the-result-which-is-not-my-respect-randomly

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by ewwerpm** [comment]
but,how to get  a trace-level log from geckodriver? where is the trace-level log？thanks ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henrik&amp;nbsp;Skupin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月16日(星期一) 晚上8:40
收件人:&nbsp;&quot;mozilla/geckodriver&quot;<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;&quot;ewwerpm&quot;<1437399109@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)

**Comment by ewwerpm** [comment]
你的邮箱设置的接收附件 的大小是多少？我5m的附件，发不过去。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/geckodriver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 晚上8:40
收件人:&nbsp;"mozilla/geckodriver"<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;"想你是我的幸福"<1437399109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)





 
Could you please attach a trace-level log from geckodriver? Read more about reporting actionable bugs in our contribution guidelines.

**Comment by whimboo** [comment]
See the link in my recent comment in how to get a trace log. Also this is an English speaking issue tracker. As such please do not send messages with some Asian language. Thanks.

**Comment by ewwerpm** [comment]
i  have sent a log file,  is  it  no use ？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henrik&amp;nbsp;Skupin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月20日(星期五) 晚上10:10
收件人:&nbsp;&quot;mozilla/geckodriver&quot;<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;&quot;ewwerpm&quot;<1437399109@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)

**Comment by whimboo** [comment]
No log file has been received. As already said please attach it here.

**Comment by ewwerpm** [comment]
my log file is larger than 5m,your email refuse me.Would you mind telling me a larger email address？or use QQ？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henrik&amp;nbsp;Skupin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月25日(星期三) 晚上9:13
收件人:&nbsp;&quot;mozilla/geckodriver&quot;<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;&quot;ewwerpm&quot;<1437399109@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)

**Comment by ewwerpm** [comment]
Maybe I can make a new logfile,wait a moment------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henrik&amp;nbsp;Skupin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月25日(星期三) 晚上9:13
收件人:&nbsp;&quot;mozilla/geckodriver&quot;<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;&quot;ewwerpm&quot;<1437399109@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)

**Comment by ewwerpm** [comment]
this is the log where the bug exist。 please read it





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/geckodriver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上9:13
收件人:&nbsp;"mozilla/geckodriver"<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;"想你是我的幸福"<1437399109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)





 
No log file has been received. As already said please attach it here.

**Comment by ewwerpm** [comment]
styleMy = driver.find_element_by_xpath("//*[@id='show_msg']") 
 #styleMy = driver.find_element_by_id("show_msg") 
 print(styleMy.is_displayed()) 
 print("********************") 
 visibilityMy = driver.find_element_by_id("show_msg").get_attribute('style') 
 print(visibilityMy) 
 if(visibilityMy.find("visibility: visible")&gt;=0): 
&nbsp;&nbsp;
 程序是为了检测http://xkz.cbirc.gov.cn/jr/ 网站的验证码窗口的。以上两种写法，在chrome里完美检测，在Firefox里，都有几率检测不到验证码。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/geckodriver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上9:13
收件人:&nbsp;"mozilla/geckodriver"<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;"想你是我的幸福"<1437399109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)





 
No log file has been received. As already said please attach it here.

**Comment by whimboo** [comment]
We are not making progress here. As long as you cannot send the log there is nothing we can do. I'm happy to reopen when one gets attached.

**Comment by ewwerpm** [comment]
the log is in the&nbsp; attachment，please readit.

1606387103238&nbsp;&nbsp;&nbsp; geckodriver&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on 127.0.0.1:51156
1606387103490&nbsp;&nbsp;&nbsp; mozrunner::runner&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Running command: "D:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofilei8AKHA"
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
1606387110610&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on port 51161
1606387111011&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; WARN&nbsp;&nbsp;&nbsp; TLS certificate errors will be ignored for this session
JavaScript warning: http://xkz.cbirc.gov.cn/jr/js/jquery-1.3.2.min.js, line 19: unreachable code after return statement
JavaScript error: http://xkz.cbirc.gov.cn/jr/js/licencequery.js, line 404: TypeError: Ext.getDom(...) is null
[Parent 10672, Gecko_IOThread] WARNING: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/process_util_win.cc:166
1606387140503&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Stopped listening on port 51161
1606387148591&nbsp;&nbsp;&nbsp; geckodriver&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on 127.0.0.1:51229
1606387149118&nbsp;&nbsp;&nbsp; mozrunner::runner&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Running command: "D:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofileKtovGb"
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
1606387155531&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on port 51234
1606387155982&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; WARN&nbsp;&nbsp;&nbsp; TLS certificate errors will be ignored for this session
JavaScript warning: http://xkz.cbirc.gov.cn/jr/js/jquery-1.3.2.min.js, line 19: unreachable code after return statement
JavaScript error: http://xkz.cbirc.gov.cn/jr/js/licencequery.js, line 404: TypeError: Ext.getDom(...) is null
[Parent 12736, Gecko_IOThread] WARNING: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/process_util_win.cc:166
1606387193297&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Stopped listening on port 51234
1606387201642&nbsp;&nbsp;&nbsp; geckodriver&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on 127.0.0.1:51307
1606387202167&nbsp;&nbsp;&nbsp; mozrunner::runner&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Running command: "D:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofilecw8SxN"
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
1606387210084&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Listening on port 51312
1606387210258&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; WARN&nbsp;&nbsp;&nbsp; TLS certificate errors will be ignored for this session
JavaScript warning: http://xkz.cbirc.gov.cn/jr/js/jquery-1.3.2.min.js, line 19: unreachable code after return statement
JavaScript error: http://xkz.cbirc.gov.cn/jr/js/licencequery.js, line 404: TypeError: Ext.getDom(...) is null
1606387377545&nbsp;&nbsp;&nbsp; Marionette&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; Stopped listening on port 51312

**Comment by whimboo** [comment]
As it looks like there are version conflicts with your graphics driver:

> [GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.

I would suggest that you reinstall these, and first check for a more up-to-date version.

**Comment by ewwerpm** [comment]
would&nbsp; you mind recurrenting my problem？as it is very easy. if&nbsp; what you say&nbsp; is correct ( because  there are version conflicts ), running&nbsp; firefox&nbsp; should always return FALSE。 but the reality is that 5 times return TRUE，and 1 time retrun FALSE. i don't know why， and chrome always(e.g.&nbsp; 6 times ) return TRUE. thanks ! below is the code:
driver.get("http://xkz.cbirc.gov.cn/jr/")
wait = WebDriverWait(driver, 10)

table_yanZhengMa = wait.until(
                EC.presence_of_element_located((By.XPATH, "/html/body/div[5]/table"))
    #这个不对，没有验证码窗口也返回FirefoxWebElement  在TX 里点 Focus也能调出验证码窗口，问题不明
            )
print(table_yanZhengMa)
#visibilityMy = driver.find_element_by_xpath("/html/body/div[5]/table").get_attribute('id')
styleMy = driver.find_element_by_xpath("//*[@id='show_msg']")
#styleMy = driver.find_element_by_id("show_msg")
print(styleMy.is_displayed())
print("********************")
visibilityMy = driver.find_element_by_id("show_msg").get_attribute('style') 
print(visibilityMy)
if(visibilityMy.find("visibility: visible")&gt;=0):
#if(context.eval('sign')=="visible"):
    print("需要输入验证码")





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/geckodriver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午4:02
收件人:&nbsp;"mozilla/geckodriver"<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;"想你是我的幸福"<1437399109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)





 
As it looks like there are version conflicts with your graphics driver:
  
[GFX1-]: Mismatched driver versions between the registry 8.810.4.5000 and DLL(s) 8.15.10.2279,&nbsp; reported.
  
I would suggest that you reinstall these, and first check for a more up-to-date version.

**Comment by whimboo** [comment]
Note that this page is barely accessible, and most of the time doesn't even load for me. So I will ask the very last time for a trace log. Note that that the last log from https://github.com/mozilla/geckodriver/issues/1807#issuecomment-734531233 is NOT a trace log. There need to be `TRACE` entries included.

**Comment by ewwerpm** [comment]
maybe you are in the area out of China,but you can use Vpn.curiously，does this project have Chinese devloper？thanks------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henrik&amp;nbsp;Skupin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月1日(星期二) 晚上8:18
收件人:&nbsp;&quot;mozilla/geckodriver&quot;<geckodriver@noreply.github.com&gt;;
抄送:&nbsp;&quot;ewwerpm&quot;<1437399109@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mozilla/geckodriver] Firefox selenium 有几率不能获得预期结果，但是用chrome selenium 100%行。Firefox cannot get the Expected result (#1807)
