### ISSUE TITLE
Geckodriver 0.28.0 cannot start Firefox on Android

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#1808]
## System

* Version: 0.28.0
* Platform: macOS 10.15.7
* Firefox: 82.1.3
* Selenium: 

## Testcase

Upgrading from Geckodriver 0.27.0 to 0.28.0 breaks starting Firefox on Android. 
<img width="316" alt="Screen Shot 2020-11-16 at 9 11 42 AM" src="https://user-images.githubusercontent.com/540757/99233898-20291980-27f4-11eb-8ade-45b6735ea703.png">

The problem persists after I've tried to start using Geckodriver, so when I try to start Firefox directly using the GUI on my phone, I also get that crash. Reverting to Geckodriver 0.27.0 fixes the problem. Starting using 0.27.0 and then through the GUI fixes it.

I use latest Browsertime: `browsertime --android -b firefox https://www.wikipedia.org -vvv` (however I'm gonna revert that to use 0.27.0).

## Stacktrace

https://gist.githubusercontent.com/soulgalore/5bb6c51801d01d72aa806b6f20154cd3/raw/77c16e98a02bd85ea254a7dfc6b4c9935917256c/geckobrowsertime-log.log

**Comment by whimboo** [comment]
@soulgalore is that a rooted or unrooted device with Android 7? This might most likely be related to the Android storage changes we did for 0.28.0. CC'ing @bclary.

Regarding the crashes when starting Firefox manually afterward does the file `/data/local/tmp/org.mozilla.firefox-geckoview-config.yaml` remain on the device after Firefox and geckodriver quit? If yes, do you force kill geckodriver? The attached log doesn't show helpful information only that it waits to connect to Firefox, and then it ends.

**Comment by whimboo** [comment]
Also an interesting line from the log:

```
1605517461399	mozdevice	DEBUG	execute_host_command: >> "shell:run-as org.mozilla.firefox cp -aR /data/local/tmp/49b1bf83-3baa-4d86-982f-85888e5de8ae /data/data/org.mozilla.firefox/test_root/org.mozilla.firefox-geckodriver-profile/cert9.db"
1605517461439	mozdevice	DEBUG	execute_host_command: << "run-as: Package \'org.mozilla.firefox\' is not debuggable\n"
```

@bclary are releases of Firefox not debuggable?

**Comment by soulgalore** [comment]
It's not rooted. I've tested on two devices (our new performance device lab and and at home) and get the same thing. The device at work run 8.0.0. I can make a new trace, so I just wait until it stops or how long should I wait? I don't do anything special to quit geckodriver, I just control+c through browsertime but I don't know how that is propagated. Let me check for the file.

**Comment by soulgalore** [comment]
Ok, if I do a adb logical it looks like this: https://gist.github.com/soulgalore/95a1a31d6ce2971a40fe967b05ce7a31
And for gecko driver (keeping it running longer this time): https://gist.github.com/soulgalore/8212d625fc0ab25c2f9ef94d7aa3baec

Checked and yes, the file (/data/local/tmp/org.mozilla.firefox-geckoview-config.yaml)  is on the device after I stopped.

**Comment by bclary** [comment]
> Also an interesting line from the log:
> 
> ```
> 1605517461399	mozdevice	DEBUG	execute_host_command: >> "shell:run-as org.mozilla.firefox cp -aR /data/local/tmp/49b1bf83-3baa-4d86-982f-85888e5de8ae /data/data/org.mozilla.firefox/test_root/org.mozilla.firefox-geckodriver-profile/cert9.db"
> 1605517461439	mozdevice	DEBUG	execute_host_command: << "run-as: Package \'org.mozilla.firefox\' is not debuggable\n"
> ```
> 
> @bclary are releases of Firefox not debuggable?

No, they aren't as far as I know.

**Comment by bclary** [comment]
I suppose if the device is not rooted and the app isn't debuggable we can jump through some hoops looking at the android version to determine if scoped storage is required and if we could get by without root while using the sdcard for the test profile and not using run-as. We would probably have to coordinate corresponding changes to mozdevice at the same time. This wouldn't help with recent versions of Android that require scoped storage but it might be worth the effort.

**Comment by whimboo** [comment]
I gave some instructions via Matrix. @soulgalore it would be great if you could tell us if that helped. Especially the workaround to manually set `sdcard` as storage option.

**Comment by soulgalore** [comment]
I just tried, yes it worked! If I set `–android-storage sdcard` it works, I need to push the option so we can use it with Browsertime. Thanks for the help @whimboo ! 

One thing: At least using Safari copying the options on https://firefox-source-docs.mozilla.org/testing/geckodriver/Flags.html#code-android-storage-var-android-storage-var-code adds only one "-"-sign before the option, making Geckodriver crash, so copy/paste the config doesn't work.

**Comment by whimboo** [comment]
@bclary would you mind filing a bug for geckodriver so we can better auto-detect the case from Peter? Not sure which exact path have have to take care about here.

@soulgalore interesting. We should get the docs fixed. But anyway which options do you use at all? When I use `-android-storage` the binary complains about an inappropriate option.

**Comment by soulgalore** [comment]
@whimboo sorry it should be `--android-storage sdcard` the docs are wrong.

**Comment by soulgalore** [comment]
See https://github.com/mozilla/geckodriver/issues/1808#issuecomment-729540963 :)

**Comment by whimboo** [comment]
> One thing: At least using Safari copying the options on https://firefox-source-docs.mozilla.org/testing/geckodriver/Flags.html#code-android-storage-var-android-storage-var-code adds only one "-"-sign before the option, making Geckodriver crash, so copy/paste the config doesn't work.

I'm going to fix that via https://bugzilla.mozilla.org/show_bug.cgi?id=1679376. Thanks for reporting! There are just too many dashes...

> @whimboo sorry it should be `--android-storage sdcard` the docs are wrong.

What do you mean that the docs are wrong?

So you only specified `–android-storage sdcard` and no other flag? Mind attaching the logs for this crash? Or do you mean that geckodriver just prints out the help contents and quit? That's what should actually happen here.

**Comment by soulgalore** [comment]
I mean it works when you use two dashes. Or don't it work for you? If I use 0.28.0 and adds ` --android-storage sdcard` it works.

**Comment by whimboo** [comment]
Well, you mentioned a crash of geckodriver when using a single hyphen only. But as it sounds like this is not the case.

Lets wait for the feedback from Bob, and then decide which step to take next.

**Comment by soulgalore** [comment]
Ah I see, sorry. When you run through Selenium the error message is: 
` Error: Server terminated early with status 64` and you need to turn on verbose logging to actually find out what's the problem.

**Comment by whimboo** [comment]
I see. Thanks for letting me know. Would be good if a proper exit code would be reported. But that's out of our hands.

**Comment by soulgalore** [comment]
So what's the way forward here do you think? Is there a drawback if I add "android-storage=sdcard" as default in Browsertime, or what was the reason for the original change? Right now as a user you only get an error/failure if you do not do anything.

**Comment by whimboo** [comment]
There is https://bugzilla.mozilla.org/show_bug.cgi?id=1680407 now that will cover improvements to the auto-detection. For now set a storage option that will work for you. `sdcard` should be fine for now, but I cannot say right now how Android 11 and later will work. I need to take a look at bug first.

**Comment by soulgalore** [comment]
Thanks @whimboo !

**Comment by whimboo** [comment]
With the [geckodriver 0.29.1](https://github.com/mozilla/geckodriver/releases/tag/v0.29.1) release today this should no longer be a problem.
