### ISSUE TITLE
How to make Firefox bootup in responsive design mode?

### ISSUE THREAD

**Issue by Ardy000** [mozilla/geckodriver#1810]
I am using a scheduled timer to run my program and can't manually put Firefox into responsive design mode when it starts.

How do I make Firefox be launched in responsive design mode?

Need it to happen automatically when Firefox is opened.

Either having Firefox boot into it by default (preferred)

Or as part of my code in python

Or as part of a geckodriver/selenium setting

-TIA

Version: 28.0
Platform: macOS
Firefox: 83.0
Selenium: 3.141.0

**Comment by whimboo** [comment]
This is not a functionality that will be included in geckodriver given that the WebDriver specification doesn't handle emulating devices. I don't know if there is a preference for Firefox, which could handle that. So maybe check the [Firefox Support website](https://support.mozilla.org/products/firefox).
