### ISSUE TITLE
Firefox browser closed immeditately with robot icon after running script

### ISSUE THREAD

**Issue by theinhtitenyo** [mozilla/geckodriver#1814]
[System]

* Version: geckodriver version 0.28 (64 bit)
* Platform: window 10
* Firefox: 83.0(64 bit) 
* Selenium: 3.141.0 , urllib3 - (1.26.2)

This is the script
from selenium import webdriver

driver = webdriver.Firefox(executable_path=r'D:\geckodriver.exe')
driver.set_page_load_timeout(30)
driver.get("https://www.google.com/")
driver.quit()

I wanted to start selenium but that happens, 

Please check attached screenshot
![robot_firefox_closed](https://user-images.githubusercontent.com/56152430/100423399-4f743c00-30ba-11eb-8219-8cc9b271a0f3.png)

**Comment by whimboo** [comment]
I cannot see any problems here. The script creates the driver, which starts Firefox. After the navigation to google.com the driver quits Firefox. Not sure what else you would expect here.
