### ISSUE TITLE
Execute geckodriver without admin rigths

### ISSUE THREAD

**Issue by Inmich** [mozilla/geckodriver#1818]
## Execution rights for geckodriver
Dear all,

Due to organization restiction we can not run geckodriver with Admin rights, is there any possibility to execute geckodriver without admin rights?.

Thanks a lot,

**Comment by whimboo** [comment]
This is not a geckodriver issue, but how you run your code. Just point the tool (Selenium, etc)  that you are using to the downloaded geckodriver binary in whatever directory that will be. There are no admin-only restrictions.
