### ISSUE TITLE
Improve error message when Firefox binary not found

### ISSUE THREAD

**Issue by davehunt** [mozilla/geckodriver#182]
I spend some time today trying to work out why I was seeing `WebDriverException: Message: entity not found (WARNING: The server did not provide any stacktrace information)` and eventually it turned out to be that the path to Firefox was incorrect. When running through Selenium 3.0.0-beta2 the GeckoDriver process was started, then I got the mentioned exception, and the GeckoDriver process was orphaned. Ideally we should kill the process, and pass a meaningful message back to Selenium that indicates there was an issue finding the binary.

**Comment by jgraham** [comment]
I don't recognise that message, so I surmise it's a Selenium message. Possibly we need to change something about the error we are sending back too; we currently send back and UnknownError [1], but maybe Selenium is expecting SessionNotCreated or something.

[1] https://github.com/mozilla/geckodriver/blob/master/src/marionette.rs#L322

**Comment by xmo-odoo** [comment]
As of Selenium 3.4 the message seems to have changed, with the same ultimate issue the message I got was "Unable to find a matching set of capabilities" (rather than any indication that the Firefox binary was not found)

**Comment by andreastt** [comment]
@xmo-odoo That is indeed a message from geckodriver, but that issue is tracked in https://github.com/mozilla/geckodriver/issues/832.

@davehunt I suggest filing a Selenium issue about this if it is still reproducible.
