### ISSUE TITLE
Crash when signing into Microsoft https://my.visualstudio.com/Subscriptions

### ISSUE THREAD

**Issue by stefrey** [mozilla/geckodriver#1827]
## System

* Version: 86.0a1-20210104090857
* Platform: Android 9
* Firefox: Nightly 210105 17:01 (Build #2015785611)
* Selenium: 
AC: 71.0.20210105122039, b1b5b2056
GV: 86.0a1-20210104090857
AS: 67.

##Error
After signing into Microsofts https://my.visualstudio.com/Subscriptions, the Browser crashes, or remains in a state where no new sites are loaded, just black screen.

## Stacktrace
89386a76-589b-4dd7-b108-70144af50c76
<native crash>

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Also attaching relevant parts from the adb logcat would be kinda helpful.

What kind of uuid is it what you added under stacktrace?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
No reply from reporter. We are happy to reopen when we got all the requested information.
