### ISSUE TITLE
Select .selectBy doesn't seem to work for dropdown

### ISSUE THREAD

**Issue by TestSheepNZ** [mozilla/geckodriver#183]
The following code worked fine previously, and with the ChromeDriver.

I've defined a Select element based on a dropdown list, this line executes fine

		Select select = new Select(driver.findElement(By.name ("identityMenu")));

However when I try either of these commands, I get an .ElementNotVisible exception,

		select.selectByIndex(8);
		select.selectByValue("ANON");

This was trying to grab the comments on a blogger page.

Error code in a bit more detail,

Exception in thread "main" org.openqa.selenium.ElementNotVisibleException: Element is not visible (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20 milliseconds
Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'MikeTa-LT001', ip: '172.17.134.113', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160726073904, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]

**Comment by andreastt** [comment]
Duplicated by https://github.com/mozilla/geckodriver/issues/94. [Bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955) just landed in the integration repository, and should be available in Nightly soon.
