### ISSUE TITLE
Problem about pythonw

### ISSUE THREAD

**Issue by DQSSSSS** [mozilla/geckodriver#1832]
## System

* Version: geckodriver version : 0.29
* Platform: Windows 10
* Firefox: 84.0.2
* Selenium: 3.141.0

## Testcase

In 'test.pyw':

```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

if __name__ == '__main__':
    opt = Options()
    opt.add_argument('--headless')
    with webdriver.Firefox(options=opt) as driver:
        driver.get("https://github.com")
```

I want to implement a program that runs completely in the background, so I use 'pythonw.exe'. 
But it will show the console with title "geckodriver.exe", how can I solve it? 
![image](https://user-images.githubusercontent.com/19804552/105209165-7f086780-5b84-11eb-87c2-2d8a25893789.png)

Maybe I think I should use 'opt.add_argument(XXXX)' to achieve it, but I can't find this list of these arguments, please help me!
Thank you so much!!

**Comment by whimboo** [comment]
There is nothing geckodriver can do here. The calling application, in this case Selenium, has to make sure that the geckodriver binary is called in a way that no window opens. Btw. does the same also happen for chromedriver?

**Comment by DQSSSSS** [comment]
> There is nothing geckodriver can do here. The calling application, in this case Selenium, has to make sure that the geckodriver binary is called in a way that no window opens. Btw. does the same also happen for chromedriver?

![image](https://user-images.githubusercontent.com/19804552/105670161-8c727880-5f1b-11eb-8465-7807f10518a7.png)
Here is the result for chromedriver, so the reason for this problem is Selenium?

**Comment by whimboo** [comment]
Maybe. But I don't actually know. Sorry.

**Comment by 19bischof** [comment]
Had the same problem and found a short and simple solution.
Edit this file _Lib\site-packages\selenium\webdriver\common\service.py_  and change the creationflag from 0 to 0x08000000
So from this:

```
def start(self):
        """
        Starts the Service.

        :Exceptions:
         - WebDriverException : Raised either when it can't start the service
           or when it can't connect to the service
        """
    try:
            cmd = [self.path]
            cmd.extend(self.command_line_args())
            self.process = subprocess.Popen(cmd, env=self.env,
                                            close_fds=system() != 'Windows',
                                            stdout=self.log_file,
                                            stderr=self.log_file,
                                            stdin=PIPE,
                                            creationflags=self.creationflags)
```
                                            
To this:
```
def start(self):
        """
        Starts the Service.

        :Exceptions:
         - WebDriverException : Raised either when it can't start the service
           or when it can't connect to the service
        """
        try:
            cmd = [self.path]
            cmd.extend(self.command_line_args())
            CREATE_NO_WINDOW = 0x08000000
            self.process = subprocess.Popen(cmd, env=self.env,
                                            close_fds=system() != 'Windows',
                                            stdout=self.log_file,
                                            stderr=self.log_file,
                                            stdin=PIPE,
                                            # creationflags=self.creationflags)
                                            creationflags=CREATE_NO_WINDOW)
```
And self.creationflags defaults to 0 in __init__.
Stackoverflow-answer: https://stackoverflow.com/questions/7006238/how-do-i-hide-the-console-when-i-use-os-system-or-subprocess-call
I used Windows btw.
