### ISSUE TITLE
Feature: Add set_network_conditions to geckodriver

### ISSUE THREAD

**Issue by Avnsx** [mozilla/geckodriver#1834]
Didn't find anything similar to it in geckodriver, would be kinda nice to see; to be able to throttle network just as in chromedriver.

```
DOCUMENTATION
Sets Chrome network emulation settings.

Args
 - network_conditions: A dict with conditions specification.

Usage
    driver.set_network_conditions(
        offline=False,
        latency=5,  # additional latency (ms)
        download_throughput=500 * 1024,  # maximal throughput
        upload_throughput=500 * 1024)  # maximal throughput

    Note: 'throughput' can be used to set both (for download and upload).
```

**Comment by JaPyR** [comment]
I think it's related to https://bugzilla.mozilla.org/show_bug.cgi?id=1571358

**Comment by whimboo** [comment]
This is non WebDriver classic standard and as such we are not going to implement it for this particular protocol. But with WebDriver BiDi we will eventually get to emulating network conditions. Whereby it might still take a little bit. Feel free to observe the status and roadmap via https://w3c.github.io/webdriver-bidi/.
