### ISSUE TITLE
Random Proxy Issues

### ISSUE THREAD

**Issue by DevelopWithJon** [mozilla/geckodriver#1835]
I'm using Selenium on Python. For some reason when I load a driver with a proxy I will get an error.

I will attempt it again with the same proxy and it will load. I have tested the proxies and they all checkout. I'm just not sure why this is happening and why its so irregular.

Error: Reached error page: about:neterror?e=proxyConnectFailure&u=https

Here is the snippet of the code where I load the proxy:

 def get_proxy(self, proxy):
        active_proxy = random.choice(proxy)
        print(active_proxy)
        
        parse = Proxyparse().parser(active_proxy)
        
        
        if len(parse) == 4:
            
            print("Using authentication")
            
            host = parse[0]
            port = parse[1]
            user = parse[2]
            passw = parse[3]
            
            self.options = {
            'proxy': {
            'http': f'http://{user}:{passw}@{host}:{port}',
            'https': f'https://{user}:{passw}@{host}:{port}',
            'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
            }
        }
            self.s = requests.Session()
            self.s.proxies = {
              "http": f"http://{user}:{passw}@{host}:{port}",
              "https": f"https://{user}:{passw}@{host}:{port}",
            }
        else:
            print('no authentication needed')
            
            host = parse[0]
            port = parse[1]
            
            self.options = {
            'proxy': {
                'http': f'http://@{host}:{port}',
                'https': f'https://@{host}:{port}',
                'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
                }
            }
            
            self.s = requests.Session()
            self.s.proxies = {
              "http": f"http://{host}:{port}",
              "https": f"http://{host}:{port}",
            }
        
        
        return self.options, self.s def get_proxy(self, proxy):
        active_proxy = random.choice(proxy)
        print(active_proxy)
        
        parse = Proxyparse().parser(active_proxy)
        
        
        if len(parse) == 4:
            
            print("Using authentication")
            
            host = parse[0]
            port = parse[1]
            user = parse[2]
            passw = parse[3]
            
            self.options = {
            'proxy': {
            'http': f'http://{user}:{passw}@{host}:{port}',
            'https': f'https://{user}:{passw}@{host}:{port}',
            'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
            }
        }
            self.s = requests.Session()
            self.s.proxies = {
              "http": f"http://{user}:{passw}@{host}:{port}",
              "https": f"https://{user}:{passw}@{host}:{port}",
            }
        else:
            print('no authentication needed')
            
            host = parse[0]
            port = parse[1]
            
            self.options = {
            'proxy': {
                'http': f'http://@{host}:{port}',
                'https': f'https://@{host}:{port}',
                'no_proxy': 'localhost,127.0.0.1,dev_server:8080'
                }
            }
            
            self.s = requests.Session()
            self.s.proxies = {
              "http": f"http://{host}:{port}",
              "https": f"http://{host}:{port}",
            }
        
        
        return self.options, self.s

def get_fox(self, proxy): 
        
        use_proxies = "Y"
        prox = self.get_proxy(proxy)
        options = prox[0]
        self.s = prox[1]
        F_options = Options()
        F_options.headless = False
        F_options.log.level = "fatal"
        profile = webdriver.FirefoxProfile()
        profile.set_preference("dom.webdriver.enabled", False)
        profile.set_preference('useAutomationExtension', False)
        profile.update_preferences()
        desired = DesiredCapabilities.FIREFOX
        gecko_path = os.getcwd() + "/geckodriver.exe"
        if use_proxies == 'Y':
            self.drive = webdriver.Firefox(options = F_options,
            firefox_profile=profile,        
            seleniumwire_options=options,
            desired_capabilities=desired, executable_path=gecko_path) 
        else: 
             self.drive = webdriver.Firefox(desired_capabilities=desired, executable_path=gecko_path)
             self.drive.set_window_size(1920, 1080)
        
        #self.drive = webdriver.Chrome(ChromeDriverManager().install(), seleniumwire_options=options)
        return self.drive
    
    def request_site(self, proxy):

## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by Andriy-Smirnov** [comment]
I'm getting the same issues with Firefox 86 and geckodriver 0.29.0:
Intermittent failures as if proxy gets lost:
OpenQA.Selenium.WebDriverException : Reached error page: about:neterror?e=proxyResolveFailure&u=...

**Comment by whimboo** [comment]
In the above example I do not see that the proxy information gets passed as a capability:
https://w3c.github.io/webdriver/#proxy

Instead some custom preferences are getting set. Does changing that fixes the problem?
