### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by davidefiorini** [mozilla/geckodriver#1836]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by davidefiorini** [comment]
Hi, firefox driver will it work with macos Big Sur ?

**Comment by whimboo** [comment]
Yes, until we release a native Aarch64 build Rosetta 2 will emulate the current MacOS binary for M1. See https://bugzilla.mozilla.org/show_bug.cgi?id=1677471 for the progress.
