### ISSUE TITLE
Password manager KeePass not working anymore with the latest FF

### ISSUE THREAD

**Issue by SorinGFS** [mozilla/geckodriver#1849]
## System

* Platform: windows 8.1 x64
* Firefox: 86.0 (latest installed today)

## Testcase

After update I can't use my KeePass to login websites. KeePass gives me an error:

`Object reference not set to an instance of an object.` 
![Like this:](https://user-images.githubusercontent.com/25417015/109323027-af19e900-785b-11eb-9549-8327c6728512.png)

I'm not sure if this is the right place to put this issue, I wasn't able to find another, but I know one thing for sure: am a big fan of Firefox, is my only browser, but if this problem is not resolved quickly not the KeePass will be the one I'll drop!

**Comment by whimboo** [comment]
Thank you for the report but it doesn't look to be related to geckodriver, which this repository is about. Mind filing a bug on https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=General instead? This would need further investigation so also mention the version of Keypass you are using over there. Thanks.
