### ISSUE TITLE
geckodriver compilation failed on travis

### ISSUE THREAD

**Issue by davidemoro** [mozilla/geckodriver#185]
Hi,

I'm trying to compile on the fly a fresh and always update geckodriver on TravisCI but I get a compilation error:
* https://travis-ci.org/tierratelematics/tierra_qa/builds/153486964

I'm pretty sure that my travisCI is quite similar to the one provided in geckodriver:
* https://github.com/tierratelematics/tierra_qa/blob/cba0893e32078b066cfd35c879d202fd5ee5aa56/.travis.yml

Thank you in advance

**Comment by davidemoro** [comment]
In a previous build the compilation of geckodriver went fine (yesterday):
* https://travis-ci.org/tierratelematics/tierra_qa/builds/153338480

**Comment by jgraham** [comment]
Oh, exciting. I suspect the release of a new Rust is breaking things in some way, but I don't know quite why that should be. Looking at your `.travis.yml` file I don't see any caching, but if I'm forgetting something and there is some caching going on I might try forcibly clearing the caches before your next build?

**Comment by davidemoro** [comment]
I dont't know: I've switched to a released version of geckodriver meanwhile (obviously the build is faster now) and now is ok.

Probably if you release a geckodriver-PLATFORM-latest.tar.gz people will be able to install on travis always the latest release without the need of compile it (longer builds, problems with caching, rust versione and so on). What do you think about that?

**Comment by andreastt** [comment]
I think what you’re describing is that you think it’s hard to fetch the latest release automatically. It’s not.

You can always find out the latest release by using _git-ls-remote(1)_ or [Github’s REST API](https://developer.github.com/changes/2015-02-18-new-releases-api-methods/):

    % git ls-remote --tags https://github.com/mozilla/geckodriver.git | sort -t '/' -k 3 -V | tail -1
    1c2ec08cf02d6fa25796781d281487afcb0f8f99        refs/tags/v0.10.0

**Comment by jgraham** [comment]
We are also seeing the underlying issue on travis: https://travis-ci.org/mozilla/geckodriver/jobs/154177252

Seems like linking with musl is broken for some reason.

**Comment by davidemoro** [comment]
Cool, thank you @jgraham and @andreastt!

**Comment by jgraham** [comment]
We fixed this locally by using beta rather than stable to compile; it turns out that some changes in the Rust CI meant that stable needed a newer binutils than travis could provide. However the upstream was fixed to not use the problematic features, so as of 0.12 this issue will go away again.
