### ISSUE TITLE
Official download of geckodriver

### ISSUE THREAD

**Issue by modywahab** [mozilla/geckodriver#1852]
## System

* Version: latest
* Platform: Linux Redhat 7
* Firefox: 78.7
* Selenium: latest

Hi, my company blocks downloads coming from GitHub, and I just want to know if there’s another official source for downloading geckodriver

**Comment by whimboo** [comment]
As of right now there is no other site. All of our releases are hosted on Github only, and there won't be a different location in the short term. Sorry.

In case you need binaries for CI jobs it would be better to cache them locally and not trying to download them each and every time.
