### ISSUE TITLE
Android Firefox Always Show Welcome to Firefox Beta and Driver Never Connects to Marionette

### ISSUE THREAD

**Issue by loganrenz** [mozilla/geckodriver#1855]
## System

* Version: 0.29.0
* Platform: macOS / Android 10
* Firefox: Beta 87.0.0-beta.2
* Selenium: javascript 4.0.0-beta.1

## Testcase

Try to start Android Firefox with appium, appium-geckodriver, selenium-webdriver and GeckoDriver-0.29.0

        capabilities = {
          "marionette": true,
          "acceptInsecureCerts": true,
          'browserName': 'MozillaFirefox',
          'automationName': 'Gecko',
          'platformName': 'mac',
          'verbosity': 'trace',
          'androidStorage': "sdcard",
          'moz:debuggerAddress': true,
          'moz:firefoxOptions': {
            'androidDeviceSerial': 'ZY326VDNR8',
            'androidPackage': 'org.mozilla.firefox_beta',
            'androidActivity': 'org.mozilla.gecko.BrowserApp',
          }          
        };

        const webdriver = require('selenium-webdriver');
        driver = new webdriver.Builder()
          .usingServer("http://localhost:4723/wd/hub")
          .withCapabilities(capabilities)
          .build();
        
        await driver.get(karma_server_address);

The app starts up, but it shows the welcome screen. In the welcome screen there are no tabs open. In this state, if you turn on the debugger from the settings menu, the app will crash. If you tap start browsing, go to a page, then enable remote debugger, the GeckoDriver will connect to marionette.

If remote debugging is turned on as a pref in firefox options, marionette crashes like this:

[debug] [W3C] Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: TypeError: this.curBrowser is null
[debug] [W3C] GeckoDriver.prototype.newSession@chrome://marionette/content/driver.js:681:7
[debug] [W3C] despatch@chrome://marionette/content/server.js:295:40
[debug] [W3C] execute@chrome://marionette/content/server.js:265:16
[debug] [W3C] onPacket/<@chrome://marionette/content/server.js:238:20
[debug] [W3C] onPacket@chrome://marionette/content/server.js:239:9
[debug] [W3C] _onJSONObjectReady/<@chrome://marionette/content/transport.js:504:20

## Trace-level log

[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"marionette":true,"acceptInsecureCerts":true,"browserName":"MozillaFirefox","automationName":"Gecko","platformName":"mac","verbosity":"trace","androidStorage":"sdcard","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}},"capabilities":{"alwaysMatch":{"acceptInsecureCerts":true,"browserName":"MozillaFirefox","platformName":"mac","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}}}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"marionette":true,"acceptInsecureCerts":true,"browserName":"MozillaFirefox","automationName":"Gecko","platformName":"mac","verbosity":"trace","androidStorage":"sdcard","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}},null,{"alwaysMatch":{"acceptInsecureCerts":true,"browserName":"MozillaFirefox","platformName":"mac","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1614875484045 (10:31:24 GMT-0600 (Central Standard Time))
[Appium] The following capabilities were provided in the JSONWP desired capabilities that are missing in W3C capabilities: ["marionette","automationName","verbosity","androidStorage"]
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   marionette
[BaseDriver]   automationName
[BaseDriver]   verbosity
[BaseDriver]   androidStorage
[Appium] Appium v1.20.2 creating new GeckoDriver (v0.3.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "acceptInsecureCerts": true,
[debug] [BaseDriver]     "browserName": "MozillaFirefox",
[debug] [BaseDriver]     "platformName": "mac",
[debug] [BaseDriver]     "moz:debuggerAddress": true,
[debug] [BaseDriver]     "moz:firefoxOptions": {
[debug] [BaseDriver]       "androidDeviceSerial": "ZY326VDNR8",
[debug] [BaseDriver]       "androidPackage": "org.mozilla.firefox_beta",
[debug] [BaseDriver]       "androidActivity": "org.mozilla.gecko.BrowserApp",
[debug] [BaseDriver]       "args": [
[debug] [BaseDriver]         "--connect-existing",
[debug] [BaseDriver]         "--marionette-port",
[debug] [BaseDriver]         "2828"
[debug] [BaseDriver]       ],
[debug] [BaseDriver]       "env": {
[debug] [BaseDriver]         "MOZ_DEV_EDITION": "true"
[debug] [BaseDriver]       }
[debug] [BaseDriver]     },
[debug] [BaseDriver]     "appium:marionette": true,
[debug] [BaseDriver]     "appium:automationName": "Gecko",
[debug] [BaseDriver]     "appium:verbosity": "trace",
[debug] [BaseDriver]     "appium:androidStorage": "sdcard"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   moz:debuggerAddress
[BaseDriver]   marionette
[BaseDriver] Session created with session id: c4f598d9-d7f0-4595-acc7-0b86a616ca27
[GeckoDriverServer] Starting '/usr/local/bin/geckodriver' with args ["-vv","-p",5200,"--android-storage","sdcard"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[debug] [GeckoDriverServer] [geckodriver] 1614875484058	geckodriver	INFO	Listening on 127.0.0.1:5200
[debug] [GeckoDriverServer] [geckodriver] 1614875484059	webdriver::server	DEBUG	-> GET /status
[debug] [GeckoDriverServer] [geckodriver] 1614875484059	webdriver::server	DEBUG	<- 200 OK {"value":{"message":"","ready":true}}
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"","ready":true}}
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","acceptInsecureCerts":true,"platformName":"mac","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}}}}
[debug] [GeckoDriverServer] [geckodriver] 1614875484062	webdriver::server	DEBUG	-> POST /session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","acceptInsecureCerts":true,"platformName":"mac","moz:debuggerAddress":true,"moz:firefoxOptions":{"androidDeviceSerial":"ZY326VDNR8","androidPackage":"org.mozilla.firefox_beta","androidActivity":"org.mozilla.gecko.BrowserApp","args":["--connect-existing","--marionette-port","2828"],"env":{"MOZ_DEV_EDITION":"true"}}}}}
[debug] [GeckoDriverServer] [geckodriver] 1614875484065	mozdevice	WARN	adb server response contained hexstring length 119 and message length was 119 and message was "ZY326VDNR8             device usb:342884352X product:troika_na model:motorola_one_action device:troika transport_id:33\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875484066	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875484066	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875484066	mozdevice	DEBUG	execute_host_command: >> "shell:id"
[debug] [GeckoDriverServer] [geckodriver] 1614875484122	mozdevice	DEBUG	execute_host_command: << "uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875484123	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875484123	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875484123	mozdevice	DEBUG	execute_host_command: >> "shell:su 0 id"
[debug] [GeckoDriverServer] [geckodriver] 1614875489208	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875489209	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875489209	mozdevice	DEBUG	execute_host_command: >> "shell:su -c id"
[debug] [GeckoDriverServer] [geckodriver] 1614875489337	mozdevice	DEBUG	execute_host_command: << "uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0\r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875489338	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875489338	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875489338	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'setenforce permissive\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875489433	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875489434	geckodriver::android	DEBUG	Android port forward (51700 -> 2829) started
[debug] [GeckoDriverServer] [geckodriver] 1614875489434	geckodriver::android	DEBUG	Connecting: options=AndroidOptions { activity: Some("org.mozilla.gecko.BrowserApp"), device_serial: Some("ZY326VDNR8"), intent_arguments: None, package: "org.mozilla.firefox_beta", storage: Sdcard }, storage=Sdcard) test_root=/mnt/sdcard/test_root, run_as_package=None
[debug] [GeckoDriverServer] [geckodriver] 1614875489435	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875489435	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875489435	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'pm list packages org.mozilla.firefox_beta\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875489548	mozdevice	DEBUG	execute_host_command: << "package:org.mozilla.firefox_beta\r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875489552	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875489552	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875489552	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'pm clear org.mozilla.firefox_beta\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875489901	mozdevice	DEBUG	execute_host_command: << "Success\r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875489901	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875489902	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875489902	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'pm grant org.mozilla.firefox_beta android.permission.READ_EXTERNAL_STORAGE\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490139	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490140	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490140	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490140	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'pm grant org.mozilla.firefox_beta android.permission.WRITE_EXTERNAL_STORAGE\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490271	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490271	mozdevice	DEBUG	Creating /mnt/sdcard/test_root
[debug] [GeckoDriverServer] [geckodriver] 1614875490272	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490272	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490272	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'mkdir -p /mnt/sdcard/test_root\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490350	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490351	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490351	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490351	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'chmod  -R 777 /mnt/sdcard/test_root\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490431	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490431	mozdevice	DEBUG	Deleting /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile
[debug] [GeckoDriverServer] [geckodriver] 1614875490432	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490432	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490432	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'rm -rf /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490504	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490504	mozdevice	DEBUG	Pushing /var/folders/_s/77jms4yd0_l597n_1h_6fp_h0000gn/T/rust_mozprofileQ7qpzM to /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile
[debug] [GeckoDriverServer] [geckodriver] 1614875490505	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490505	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490505	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'ls /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490575	mozdevice	DEBUG	execute_host_command: << "ls: /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile: No such file or directory\r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875490576	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490576	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490576	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'ls /mnt/sdcard/test_root\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490649	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] 1614875490649	mozdevice	DEBUG	Creating /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile
[debug] [GeckoDriverServer] [geckodriver] 1614875490650	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490650	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490650	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'mkdir -p /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490725	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490726	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490726	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490726	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'chmod  -R 777 /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490799	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490805	geckodriver::android	DEBUG	Content of generated GeckoView config file:
[debug] [GeckoDriverServer] ## GeckoView configuration YAML
[debug] [GeckoDriverServer] ##
[debug] [GeckoDriverServer] ## Auto-generated by geckodriver.
[debug] [GeckoDriverServer] ## See https://mozilla.github.io/geckoview/consumer/docs/automation.
[debug] [GeckoDriverServer] ---
[debug] [GeckoDriverServer] env:
[debug] [GeckoDriverServer]   MOZ_DEV_EDITION: "true"
[debug] [GeckoDriverServer]   MOZ_CRASHREPORTER: "1"
[debug] [GeckoDriverServer]   MOZ_CRASHREPORTER_NO_REPORT: "1"
[debug] [GeckoDriverServer]   MOZ_CRASHREPORTER_SHUTDOWN: "1"
[debug] [GeckoDriverServer] args:
[debug] [GeckoDriverServer]   - "--marionette"
[debug] [GeckoDriverServer]   - "--profile"
[debug] [GeckoDriverServer]   - /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile
[debug] [GeckoDriverServer] [geckodriver] 1614875490805	geckodriver::android	DEBUG	Pushing GeckoView configuration file to /data/local/tmp/org.mozilla.firefox_beta-geckoview-config.yaml
[debug] [GeckoDriverServer] [geckodriver] 1614875490806	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490806	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490806	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'ls /data/local/tmp\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490876	mozdevice	DEBUG	execute_host_command: << "apk1614638611536.apk                           perfd     \r\norg.mozilla.fenix-geckoview-config.yaml        test_root \r\norg.mozilla.firefox-geckoview-config.yaml      vysor.pwd \r\norg.mozilla.firefox_beta-geckoview-config.yaml \r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875490883	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490883	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490883	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'am set-debug-app --persistent org.mozilla.firefox_beta\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875490978	mozdevice	DEBUG	execute_host_command: << ""
[debug] [GeckoDriverServer] [geckodriver] 1614875490978	geckodriver::android	DEBUG	Launching org.mozilla.firefox_beta/org.mozilla.gecko.BrowserApp
[debug] [GeckoDriverServer] [geckodriver] 1614875490979	mozdevice	DEBUG	execute_host_command: >> "host:transport:ZY326VDNR8"
[debug] [GeckoDriverServer] [geckodriver] 1614875490979	mozdevice	DEBUG	execute_host_command: << []
[debug] [GeckoDriverServer] 1614875490979	mozdevice	DEBUG	execute_host_command: >> "shell:su -c \'am start -W -n org.mozilla.firefox_beta/org.mozilla.gecko.BrowserApp --es args \"--marionette --profile /mnt/sdcard/test_root/org.mozilla.firefox_beta-geckodriver-profile\"\'"
[debug] [GeckoDriverServer] [geckodriver] 1614875491884	mozdevice	DEBUG	execute_host_command: << "Starting: Intent { cmp=org.mozilla.firefox_beta/org.mozilla.gecko.BrowserApp (has extras) }\r\nStatus: ok\r\nLaunchState: COLD\r\nActivity: org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity\r\nTotalTime: 791\r\nWaitTime: 794\r\nComplete\r\n"
[debug] [GeckoDriverServer] [geckodriver] 1614875491884	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:51700
[WD Proxy] Error: timeout of 240000ms exceeded
[WD Proxy]     at createError (/usr/local/lib/node_modules/appium/node_modules/axios/lib/core/createError.js:16:15)
[WD Proxy]     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:280:16)
[WD Proxy]     at Object.onceWrapper (node:events:485:26)
[WD Proxy]     at RedirectableRequest.emit (node:events:378:20)
[WD Proxy]     at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/appium/node_modules/follow-redirects/index.js:13:24)
[WD Proxy]     at ClientRequest.emit (node:events:378:20)
[WD Proxy]     at Socket.emitRequestTimeout (node:_http_client:780:9)
[WD Proxy]     at Object.onceWrapper (node:events:484:28)
[WD Proxy]     at Socket.emit (node:events:390:22)
[WD Proxy]     at Socket._onTimeout (node:net:480:8)
[WD Proxy]     at listOnTimeout (node:internal/timers:557:17)
[WD Proxy]     at processTimers (node:internal/timers:500:7)
[GeckoDriver] Ending Gecko Driver session
[GeckoDriverServer] geckodriver has exited with code null, signal SIGTERM
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1614875544063 (10:32:24 GMT-0600 (Central Standard Time))
[debug] [W3C] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [W3C]     at GeckoProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [W3C]     at runMicrotasks (<anonymous>)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:94:5)
[debug] [W3C]     at GeckoDriverServer.start (/usr/local/lib/node_modules/appium/node_modules/appium-geckodriver/lib/gecko.js:185:5)
[debug] [W3C]     at GeckoDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-geckodriver/lib/driver.js:59:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 500 60022 ms - 1001
[HTTP]

**Comment by loganrenz** [comment]
There seem to be some files that are written to shared_prefs that drive whether the welcome screen has been seen. I notice that when we pm clear org.mozilla.firefox_beta all that data is wiped out. So we don't have any record of having launched before.

**Comment by loganrenz** [comment]
I was able to solve this problem by passing some androidIntentArguments

              'moz:firefoxOptions': {
                "log": {"level": "trace"},
                'androidDeviceSerial': 'XXX',
                'androidPackage': 'org.mozilla.firefox_beta',
                'androidActivity': 'org.mozilla.gecko.BrowserApp',
                androidIntentArguments: [
                  '-a', "android.intent.action.VIEW",
                  '-d', my_fun_url],
                'profile': profileb64

I also had a problem with self signed certificates that I solved by creating a new profile on desktop and import the certificates I needed into it then passing it as a base64 encoded zip. 

I have one final hurdle that I need to overcome, and that's clicking the Allow DRM button. I need to playback DRM'd content. That seems to be controlled by a site permissions database that gets overwritten each time the browser starts. I've tried a number of different preferences, but none of them seem to work.

**Comment by loganrenz** [comment]
That site permissions database is not part of the profile but located here:  /data/data/org.mozilla.firefox_beta/databases

I've observed these files being updated after tapping the Allow button

site_permissions_database-wal
site_permissions_database-shm

I could make copies of these files, but I haven't figured out how to put them in place.

**Comment by whimboo** [comment]
By using `BrowserApp` as activity it will indeed not work. This activity isn't made for automation.

With the [geckodriver 0.29.1](https://github.com/mozilla/geckodriver/releases/tag/v0.29.1) release today this should no longer be a problem. Just specify the package name, and geckodriver will pick defaults for the activity and the intent arguments.
