### ISSUE TITLE
get_attribute('value') returns 'None' on form input if value is not explicitly defined.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/geckodriver#186]
Version

- Selenium 3.0.0b2
- GeckoDriver v0.10.0-macos

I have a test that checks the `value` attribute of an `input[type="email"]` field using the following code:

```
self.find_element(*self._email_locator).get_attribute('value')
```

The simplified HTML markup is as follows:

```
<input id="id_email" type="email">
```

GeckDriver/Marionette will return `None` here because the `value` attribute does not yet exist in the HTML markup, due to the field being empty.

If I change the markup to as follows, then GeckDriver/Marionette returns an empty string `""`.

```
<input id="id_email" type="email" value="">
```

I think this behavior should probably be consistent, as the `value` attribute does not have to be explicitly defined itself for form input values to be read. The older FirefoxDriver and all other browsers return an empty string `""`, regardless to if the attribute is present in the markup or not.

**Comment by jgraham** [comment]
The W3C spec separated out the idea of reading an attribute (something in markup) and a property (something in the DOM). In this case you want to read the value *property* because as you note there is no value *attribute*. I don't know how Selenium 3 will represent this in the API (whether it will expose two methods or continue trying to smoosh everything together into one method).

**Comment by alexgibson** [comment]
> I don't know how Selenium 3 will represent this in the API (whether it will expose two methods or continue trying to smoosh everything together into one method).

Is this in an issue tracker somewhere where I can keep track of what's decided?

**Comment by jgraham** [comment]
cc @AutomatedTester

**Comment by andreastt** [comment]
My initial plan was to ship a shim in Selenium 2.x that papered over the differences between _Get Element Attribute_ and _Get Element Property_. You can see the initial work on that in https://github.com/SeleniumHQ/selenium/issues/2301.

In the interim the Selenium project has started work on Selenium 3, but I don’t know if they are planning any API changes for that release, i.e. whether they will expose the commands separately. Perhaps @lukeis can provide some input on this.

**Comment by alexgibson** [comment]
Thanks for all the insights so far,

Right now, things like simply checking for a class name fail too:

```
@property
def is_selected(self):
>   return 'current' in self.root.get_attribute('class')
E   TypeError: argument of type 'NoneType' is not iterable
```

I feel like these types of things are probably pretty common in terms of testing patterns (we have a large suite of tests for [mozilla.org](https://github.com/mozilla/bedrock) where I am kicking the tires here). While I appreciate all the comments & insights as to the reason for this change, I feel like closing the issue with no clear resolution or path forward is perhaps premature?

**Comment by AutomatedTester** [comment]
@alexgibson The python code has landed and is waiting for the next release. In the next release we have 2 calls for property and attribute because conflating them was a silly design choice.

For now you can have a try catch here to call `execute_script` if you hit this exception.

**Comment by andreastt** [comment]
This is a Selenium issue, and not a geckodriver issue.

**Comment by alexgibson** [comment]
> @alexgibson The python code has landed and is waiting for the next release. In the next release we have 2 calls for property and attribute because conflating them was a silly design choice.

> For now you can have a try catch here to call execute_script if you hit this exception.

Thanks for the info, I'll wait for the next release.
