### ISSUE TITLE
Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by mockdeep** [mozilla/geckodriver#1862]
Over the past day or two we've started frequently seeing the error below in our builds on CircleCI. We're using `selenium-webdriver` with Capybara and Rails. I'm wondering if it maybe has something to do with the latest release of Firefox. Unfortunately, I'm not sure how to get more information for you, but I'll see if I can get the TraceLogs working on CircleCI. One thing I've noticed is that the issue seems to only be happening on the *first* interaction with Firefox, so tests after the first one run fine.

## System

* Version: 0.29.0
* Platform: Linux (CircleCI)
* Firefox: 87.0
* Selenium: selenium-webdriver (3.142.7) (Ruby)

## Stacktrace

```
     Selenium::WebDriver::Error::UnknownError:
       Process unexpectedly closed with status 1
```

**Comment by whimboo** [comment]
Have you had a chance to check for trace logs? Without those we unfortunately cannot do anything. Sorry.

**Comment by mockdeep** [comment]
@whimboo sorry for the delay. We got around to it yesterday. The logs are attached below. The file is huge, but the first test failure mark (the F at the beginning of the line) is on line 97, so I think what you're interested in will be in the first 100 or so lines. Also, we managed to the solve the problem for ourselves by upgrading our build image. We were using the `circleci/ruby:2.6.6-stretch-browsers` docker image but upgraded to `circleci/ruby:2.6.6-buster-browsers` and the problem went away.

If you end up finding a fix, I'll be happy to see if it works on `stretch` for you.

[output.log.tar.gz](https://github.com/mozilla/geckodriver/files/6268057/output.log.tar.gz)

**Comment by whimboo** [comment]
So here is the underlying problem:

```
1617666172319	mozrunner::runner	INFO	Running command: "/usr/local/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileWZVzpD"
1617666172319	geckodriver::marionette	DEBUG	Waiting 60s to connect to browser on 127.0.0.1:40123
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :99
1617666172419	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}}
```

So there is a problem with opening the display, which strongly seems to be a system related problem. So something in that `buster` image got fixed so it's not happening there. Are there different versions of the browsers only, or do they also modify system libraries? Which version of Firefox has the `stretch` docker image?

**Comment by mockdeep** [comment]
@whimboo both `buster` and `stretch` have Firefox 87. One thing to note, though, is that this issue started occurring for us around March 24, which is [right after 87 was released](https://www.mozilla.org/en-US/firefox/87.0/releasenotes/).

**Comment by whimboo** [comment]
Was there maybe an update of the docker image? Some other system library might be causing it given that version 87 works fine in a newer docker release.

I'm afraid that there might be nothing that we can do here. Would it be ok with you to close the issue?

**Comment by mockdeep** [comment]
It doesn't look like [the specific Dockerfile](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.6.6-stretch/browsers/Dockerfile) has been updated in a while, but it inherits from others which may have seen more recent updates.

I'm fine closing the issue if you don't think it's worth pursuing, since we were able to find a fix.

**Comment by Oleh-Hrebchuk** [comment]
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
