### ISSUE TITLE
Fatal compiler error (fix included)

### ISSUE THREAD

**Issue by csBlueChip** [mozilla/geckodriver#1863]
(are ALL errors/warnings fatal in rust??)

* Version: v0.29 source release ...typo is still in the main branch [8/Apr/2021]
* Platform: Pi4 raspbian
* rustc: 1.51.0 (2fd73fabe 2021-03-23)

## test case
wget https://github.com/mozilla/geckodriver/archive/v0.29.0.tar.gz
tar xvzf v0.29.0.tar.gz
cd geckodriver-0.29.0
cargo build

## issue
warning: unnecessary trailing semicolon
   --> src/command.rs:126:10
    |
126 |         };
    |          ^ help: remove this semicolon
    |
    = note: `#[warn(redundant_semicolons)]` on by default

warning: unnecessary trailing semicolon
   --> src/command.rs:133:10
    |
133 |         };
    |          ^ help: remove this semicolon

warning: unnecessary trailing semicolon
   --> src/command.rs:140:10
    |
140 |         };
    |          ^ help: remove this semicolon

warning: 3 warnings emitted

## resolution
Remove the semicolons off the end of the 3 structs

**Comment by whimboo** [comment]
Thanks for the report. This has already been fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1690551.

Given that we are going to release a new geckodriver version today anyway, check back later today.
