### ISSUE TITLE
The macOS release naming deviates from previously release names

### ISSUE THREAD

**Issue by stefanvermaas** [mozilla/geckodriver#1866]
## System
* Version: `v0.29.1`
* Platform: macOS `v11.2.3`

Previous releases for macOS were packaged up in `geckodriver-v0.xx.x-macos.tar.gz`. However, the latest release seems to be packaged up differently (missing the `.tar` part). This breaks other software (e.g. `ruby on rails`) depending on a consistent package name for the releases.

I'm not sure whether it should be up to the `geckodriver` to be fixed, but deviating from previously consistent naming of the releases seems to be something for the `geckodriver`.

**Comment by stefanvermaas** [comment]
To be more precise than "ruby on rails". It seems `webdrivers` depends on the consistent naming of the releases; https://github.com/titusfortner/webdrivers

**Comment by whimboo** [comment]
Sorry for that. I just fixed the broken file names for MacOS binaries. Thanks for reporting it!

**Comment by stefanvermaas** [comment]
Thanks @whimboo
