### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable: ver/v0.29.1/macos/geckodriver]

### ISSUE THREAD

**Issue by ValeriiIavtushenko** [mozilla/geckodriver#1868]
## System

Version: 
 Platform: 
 Firefox: 
Selenium: 

## Stacktrace

Looking for [geckodriver v0.29.1 macos] driver in cache 
File found in cache by path [/Users/sturm/.wdm/drivers/geckodriver
OSError: [Errno 86] Bad CPU type in executable: ver/v0.29.1/macos/geckodriver]

**Comment by whimboo** [comment]
Dupe of #1867.
