### ISSUE TITLE
Gecko Driver on Windows 7 - 32 bit version.

### ISSUE THREAD

**Issue by rajeevpbn** [mozilla/geckodriver#187]
Hi All,
I am running tests in windows 7, 32 bit, And right now the latest version of Gecko driver is not available in 32 bit. If i use this 64 bit, it is asking for "the version is not right" box. If i download older one 32 bit, its asking for VC dll is missing. 

I am not able to run firefox at all. 

And mostly in chrome driver, clicks are not working so. right now my work is in dead end.

Please help me on this.

Thank you,
Rajeev

**Comment by jgraham** [comment]
https://github.com/mozilla/geckodriver/issues/146

**Comment by rajeevpbn** [comment]
Thanks @jgraham - Can you make it fast on windows. I am unable to run the tests.

**Comment by rajeevpbn** [comment]
Hi @andreastt, @jgraham  - I tried to build the geckodriver release locally, but i was getting an build errors. so only depending on your releases.

**Comment by rajeevpbn** [comment]
Any update on this? Still waiting for this build. It's been long.

**Comment by jgraham** [comment]
0.11 will have a build. We are currently working through the few remaining blockers.

**Comment by rajeevpbn** [comment]
Thank you

**Comment by rajeevpbn** [comment]
It could have been better, you guys prioritize the issue, It's a blocker in 32 bit OS versions. In most of the cases, we won't be able to ask to change the OS?. Waiting for long.

**Comment by andreastt** [comment]
This isn’t productive. Locking conversation.
