### ISSUE TITLE
Cannot enable trace-level log in Python to further troubleshoot

### ISSUE THREAD

**Issue by danwagnerco** [mozilla/geckodriver#1874]
## System

* Version: geckodriver-v0.29.1-win64
* Platform: Windows 10 Pro 64-bit Version 2004 Build 19041.928
* Firefox: 78.9.0esr (64-bit)
* Selenium: Python selenium==3.141.0

## Testcase
Overall goal is to launch and control a FF browser via Selenium. However, even the most basic:

```
from selenium import webdriver
browser = webdriver.Firefox()
```

yields an error on my laptop:

```
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

Though the Firefox browser successfully opens each time... interesting, time to troubleshoot! When I attempt to enable the trace-level log, though, I get another error:

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
browser = webdriver.Firefox(options=ops)
```

yields:

```
AttributeError: 'Options' object has no attribute 'log'
```

(Source for trace-level logging: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html#python)

## Stacktrace
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-7966706ba30c> in <module>()
      3 
      4 opts = Options()
----> 5 opts.log.level = "trace"
      6 browser = webdriver.Firefox(options=ops)

AttributeError: 'Options' object has no attribute 'log'
```

## Trace-level log
N/A due to issue above in attempting to set geckodriver log level to "trace".

This is a real head-scratcher to me because as far as I can tell, there IS a log attribute on the Options class:

https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/firefox/options.py#L46

but I am also a garbage developer 😂 

**What is the right way to enable trace-level geckodriver logging for the Python version of Selenium?**

**Comment by whimboo** [comment]
If the above doesn't work you should file an issue at https://github.com/SeleniumHQ/selenium/issues.

Another way to enable trace logs is to pass `service_args` to `webdriver.Firefox()` and start geckodriver with `-vv`. If there is a problem too, you can still set the Firefox preference `marionette.log.level` to `Trace`.

Feel free to file a separate issue for the real underlying problem. This one is not geckodriver specific.
