### ISSUE TITLE
Unable to retrieve window handles when previous session restored

### ISSUE THREAD

**Issue by vitidev** [mozilla/geckodriver#1876]
Initially, I set `browser.startup.page=3` (restore session on startup) when starting new firefox instanse for existing profile

    from selenium import webdriver
    from selenium.webdriver.firefox.options import Options

    options = Options()
    options.binary = 'firefox.exe'
    options.profile = r"..."
    options.set_preference("dom.webdriver.enabled", False)
    options.set_preference("browser.startup.page", 3)
    driver = webdriver.Firefox(options=options)

But, I think so, that this is the same [issue](https://github.com/mozilla/geckodriver/issues/1790), just not completely fixed. 

## System

* Version: 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
* Platform: Windows 10 64bit
* Firefox: 88.0
* Selenium: None

## Testcase

* `browser.startup.page=3` in `about:config`
* Launch geckodriver with the parameters --log trace --connect-existing --marionette-port 2828
* Attempt to retrieve handles for existing tabs

## Stacktrace

N/A

## Trace-level log

    geckodriver.exe -vv --connect-existing  --marionette-port 2828
    1619174084452   geckodriver     INFO    Listening on 127.0.0.1:4444
    1619174087276   webdriver::server       DEBUG   -> POST /session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {}}, "desiredCapabilities": {}}
    1619174087277   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:2828
    1619174087279   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:2828.
    1619174087283   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"89a878ce-fa3b-49c3-a0a2-4d21e4b585dc","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"88.0","moz:accessibilityChecks":false,"moz:buildID":"20210415204500","moz:geckodriverVersion":"0.29.1","moz:headless":false,"moz:processID":18248,"moz:profile":"V:\\AppData\\FireFox\\Wax","moz:shutdownTimeout":60000,"moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows","platformVersion":"10.0","rotatable":false,"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify"}}}
    1619174087289   webdriver::server       DEBUG   -> GET /session/89a878ce-fa3b-49c3-a0a2-4d21e4b585dc/window/handles
    1619174087291   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"unknown error","message":"TypeError: browser.browsingContext is null","stacktrace":"GeckoDriver.prototype.getIdForBrowser@chrome://marionette/content/driver.js:1122:15\nget@chrome://marionette/content/driver.js:197:28\nGeckoDriver.prototype.getWindowHandles@chrome://marionette/content/driver.js:1167:3\ndespatch@chrome://marionette/content/server.js:291:40\nexecute@chrome://marionette/content/server.js:264:16\nonPacket/<@chrome://marionette/content/server.js:237:20\nonPacket@chrome://marionette/content/server.js:238:9\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:504:20\n"}}

**Comment by whimboo** [comment]
The problem here is that tabs in the background aren't loaded yet and as such don't have a handle. We are aware of this issue and cover it via https://bugzilla.mozilla.org/show_bug.cgi?id=1682062.
