### ISSUE TITLE
Can't pass the Cloudflare browser check before accessing the webpage

### ISSUE THREAD

**Issue by miki676** [mozilla/geckodriver#1878]
## System

* Version: 0.29.1
* Platform: Linux
* Firefox: latest
* Selenium: webdriver.Remote()

## Testcase

When visiting a webpage using the following selenium code:

class VisitSitesTest():
    def testMethod(self):
        selenium_url = "http://localhost:4444/wd/hub"
        caps = {'browserName': 'firefox'}
        driver = webdriver.Remote(command_executor=selenium_url, desired_capabilities=caps)
        driver.get(https://doge.click/visit/Vx7Acw)
        time.sleep(10)
        driver.close()
        driver.quit()

## Stacktrace
Receving error log in developer tools' console  in geckodriver (firefox) while visiting webpage before Cloudfare redirects  to the webpage, I see the following error.

1 - [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

After using java script in console I received alert:

  Site wants to
  Store files on this device

(Alert appears for 1-2 seconds)

Cloudflare keeps reloading and changing Ray ID everysecond ( RAY ID is identification ID of the new user, which Cloudflare wants to store and to identificate in the next visits) and again I see the same error.

Java script which gave me alert is:

var requestedBytes = 10241024280;
navigator.webkitPersistentStorage.requestQuota (
requestedBytes, function(grantedBytes) {
window.webkitRequestFileSystem(PERSISTENT, grantedBytes, onInitFs, errorHandler);
}, function(e) { console.log('Error', e); }
);

In normal firefox browser, Cloudflare's check finishes and redirects to webpage, but in geckodriver keeps giving the error.

How to solve this error so Cloudflare could store ID and continue?

**Comment by whimboo** [comment]
Are you sure that you are running geckodriver and Firefox? It looks more like a problem with Chrome. There is no such `webkitPersistentStorage` support available in Firefox given that it is built upon Gecko and not WebKit.

As such I don't think that this bug is valid. But feel free to attach the [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) if it's Firefox and we can reopen the issue. Thanks!

**Comment by miki676** [comment]
My bad. I thought that the same issue will get in console geckodriver like in chromedriver as the problem was - Couldn't pass the browser check of Cloudflare. 
I ran again the python code and I got report from console as following:

Cookie “cf_chl_prog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite v1:4:385
Some cookies are misusing the recommended “sameSite“ attribute 4
Cookie “cf_chl_2” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite v1:1:29663
Cookie “cf_chl_2” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite v1:1:29818
Cookie “cf_chl_prog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 3 v1:1:29663
Cookie “cf_chl_prog” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 v1:1:29663


I also attaching the tracelog:
[geckodriver.log](https://github.com/mozilla/geckodriver/files/6420993/geckodriver.log)

So the problem is the same, can't redirect to webpage. 
How can I solve this?

**Comment by miki676** [comment]
whimboo
If there is a solution could you please give the step by step  solution code? I am new in python programming.
Thank you.

**Comment by miki676** [comment]
By the way, I am using this code to the debug faster:

import time
from selenium import webdriver

firefox_options = webdriver.FirefoxOptions()
firefox_options.log.level = "trace"


browser = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver", options=firefox_options)
time.sleep(10)
browser.get('https://doge.click/vc/qmZ7bj')
browser.quit()
browser.close()

**Comment by whimboo** [comment]
What should be the result when loading https://doge.click/vc/qmZ7bj? Should it automatically forward to some page? When I open the page in a recent version of Firefox I only get a DDOS protection page.

**Comment by miki676** [comment]
First Cloudflare checks the browser storing the RAY ID (RAY ID - is identification ID to identificate the visitor in future visits, which is normal standard and passes in normal browsers after the check process.. After that  Cloudflare will redirect to the given webpage: https://doge.click/vc/qmZ7bj   - which is ads.

In normal browser, if it's frist visit to the webpage, I get Cloudflare browser check, and at next visit I  don't pass the broswer check, because RAY ID has been already stored. But if I use incognito I also go through Cloudflare browser check, and if I don't close the incognito tab and revisit the new webpage from (https://doge.click), I don't go through browser check, only when I close and open new incognito tab I go through the Cloudflares browser check. 

Here is a picture of browser check
![Cloudflares browser check](https://user-images.githubusercontent.com/76637616/117144888-4c514a80-add4-11eb-8fc8-107936653021.jpg)

After redirection:
![After the check](https://user-images.githubusercontent.com/76637616/117144921-57a47600-add4-11eb-955a-7dbb1a07c2b0.jpg)

It was already visited. If it was not visited, the link will be the same (https://doge.click/vc/qmZ7bj - which is only for 1 visit,) and could see the webpage.

You can check this one, - https://doge.click/vc/uYr3qz , in incognito mode. 
By the way, the link will not forward to some page, it will show the webpage with the given link.

Here is the result of this page - https://doge.click/vc/CnrzJh
![the result of link](https://user-images.githubusercontent.com/76637616/117145851-6b041100-add5-11eb-8f84-d95ddf4c2b2c.jpg)

And I must watch the ads.  As you can see the link didn't change and didn't forward to another link.
I hope you understood me.

**Comment by whimboo** [comment]
@miki676 can you please check if you can see the same problem with starting Firefox directly with the `-marionette` command line argument, and navigating to that page manually? Starting Firefox without `-marionette` works fine?

Due to the 1-click limit of the above provided URLs I cannot actually test myself.

**Comment by miki676** [comment]
@whimboo, can you please give the code how to do that? I am sorry I am new in programming and Linux. Thank you for understanding.

**Comment by whimboo** [comment]
There is no code needed. Just start Firefox via the terminal and pass `--marionette` as argument for a manual  page load. Then close Firefox and start it again without the argument, and run the same page load again.

**Comment by kiyotaka4946g** [comment]
>There is no code needed. Just start Firefox via the terminal and pass --marionette as argument for a manual page load. Then close Firefox and start it again without the argument, and run the same page load again.

It needs change "enable.marionette" in "about:config" and clear site's cookies.
Probably caused by this issue.
https://github.com/mozilla/geckodriver/issues/1680
https://stackoverflow.com/questions/67341346/how-to-bypass-cloudflare-bot-protection-in-selenium/67341360

Change to chromedriver.
Or use profile set cookies ,by manualy run firefox and change "enable.marionette" to "false" and go to URL.Whenever cookie expire, manualy run needed.

**Comment by whimboo** [comment]
There is nothing else actionable anymore. As we have seen certain pages including CloudFlare prevents access when `navigator.webdriver` is set, but that's on their own will. It's nothing that we can change.
