### ISSUE TITLE
cant run 

### ISSUE THREAD

**Issue by don4848** [mozilla/geckodriver#1880]
└─# pip install -r requirements.txt
Requirement already satisfied: terminaltables>=3.1.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (3.141.0)
Requirement already satisfied: Pillow>=5.4.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (8.1.2)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (2.11.3)
Requirement already satisfied: user-agent>=0.1.9 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.1.9)
Requirement already satisfied: pathlib2>=2.3.5 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2.3.5)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/site-packages (from selenium>=3.141.0->-r requirements.txt (line 2)) (1.26.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.9/site-packages (from Jinja2>=2.10->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.15.0)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv                                             
                                                                                                  
┌──(root💀kali)-[~/Desktop/QRLJacking/QRLJacker]
└─# python3 QrlJacker.py --help
Traceback (most recent call last):
  File "/root/Desktop/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'
                                                                                                  
┌──(root💀kali)-[~/Desktop/QRLJacking/QRLJacker]
└─# python3.9 QrlJacker.py --help                                                             1 ⨯
Traceback (most recent call last):
  File "/root/Desktop/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'
                                                                                                  
┌──(root💀kali)-[~/Desktop/QRLJacking/QRLJacker]
└─# python3.9 QrlJacker.py                                                                    1 ⨯
Traceback (most recent call last):
  File "/root/Desktop/QRLJacking/QRLJacker/QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by whimboo** [comment]
Hi. This issue has nothing to do with geckodriver but is related to some Python package that you are using. Best is to get in contact with their developers to get it fixed.
