### ISSUE TITLE
Failed to download geckodriver

### ISSUE THREAD

**Issue by sachinyadav342** [mozilla/geckodriver#1883]
**ERROR** :  
raise RuntimeError(f'Failed to download geckodriver archive: {url}')
RuntimeError: Failed to download geckodriver archive: https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.tar.gz

I am using using windows 10

Step1 : installed geckodriver
command : pip install geckodriver-autoinstaller

Step2: Executed below program

from selenium import webdriver
import geckodriver_autoinstaller

geckodriver_autoinstaller.install()
driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title

Step3: when i opend below Link as mentioned in above error section web page opens and say Not found.
Link : https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-win32.tar.gz

![image](https://user-images.githubusercontent.com/53603246/117541576-2b863080-b032-11eb-9ba7-3daa9f0c22fc.png)

Step4: When i went to : https://github.com/mozilla/geckodriver/releases/v0.29.1/

i saw there for windows gekodriver is in .zip format (geckodriver-v0.29.1-win32.zip) and from error i came to know that it is downloading .tar.gz file.

So plz add .tar.gz file for windows gekodriver

**Comment by whimboo** [comment]
This [is a known bug](https://github.com/yeongbin-jo/python-geckodriver-autoinstaller/issues/7) in the `geckodriver-autoinstaller`Python package that is not owned by us.

**Comment by sachinyadav342** [comment]
So how this will get resolved ..?

**Comment by sachinyadav342** [comment]
so can you change the format of driver?
instead of .zip add as tar.gz.
i think will resolve issue

**Comment by whimboo** [comment]
We aren't going to use a tar.gz format for Windows binaries. As previously said the problem needs to be fixed in `geckodriver-autoinstaller`.

**Comment by sachinyadav342** [comment]
Okay.

So then should i report to them or it is already reported??

Regards,
Sachin yadav

**Comment by whimboo** [comment]
See my comment from 4 days ago. There is the link to the other issue.
