### ISSUE TITLE
Hang when getting a URL with a fragment if already on same page

### ISSUE THREAD

**Issue by roadrunner2** [mozilla/geckodriver#189]
The following code snippet demonstrates the problem: calling `driver.get(<url-with-a-fragment>)` hangs if the browser is already on that page (i.e. same URL but without the fragment part):
```java
import org.openqa.selenium.firefox.MarionetteDriver;

public class GoToFragmentHang {
    public static void main(String[] args) throws Exception {
        MarionetteDriver driver = new MarionetteDriver();
        System.out.println("getting main page");
        driver.get("https://github.com/mozilla/geckodriver");
        System.out.println("getting readme fragment");
        driver.get("https://github.com/mozilla/geckodriver#readme");  // this hangs
        System.out.println("done");
        driver.quit();
    }
}
```
This problem is quite severe for projects that use things like [Sammy](http://www.sammyjs.org/) where almost all navigation is via different fragments.

I've verified that this is a geckodriver (or FF) issue, not a MarionetteDriver one, as it can also be reproduced by sending webdriver protocol requests manually (curl) to the geckodriver.

Environment is: FF 48, geckodriver v0.9.0, selenium-firefox-driver 2.53.1 .

**Comment by jgraham** [comment]
#150
