### ISSUE TITLE
ElementNotInteractable exception when calling SendKeys on element under a ShadowRoot

### ISSUE THREAD

**Issue by kenparkerjr** [mozilla/geckodriver#1894]
## System

* Version: geckodriver 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)
* Platform: Windows 10
* Firefox: 89.0 (64-bit)
* Selenium: Selenium 3.141.0

## Testcase

Use javascript to get an input element under a shadowRoot.
`var script = document.querySelector('.myshadow').shadowRoot.querySelector('.myinput');`
`var element = (IWebElement)((IJavaScriptExecutor)_driver).ExecuteScript(script);`
`element.SendKeys("Automated")`

## Stacktrace
  Message: 
    OpenQA.Selenium.ElementNotInteractableException : Element <input id="..." class="dds__form-control" name="firstName" type="text"> is not reachable by keyboard
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
    RemoteWebElement.SendKeys(String text)

## Trace-level log

Exception thrown: 'OpenQA.Selenium.WebDriverException' in WebDriver.dll
An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code
Failed to decode response from marionette

**Comment by kenparkerjr** [comment]
This is similar to the below issue:   
https://github.com/mozilla/geckodriver/issues/1414

**Comment by whimboo** [comment]
It's actually a dupe. Thanks.
