### ISSUE TITLE
Error geckdriver in server linux "dconf-CRITICAL **"

### ISSUE THREAD

**Issue by JonathanG19** [mozilla/geckodriver#1896]
## System

* Version: 0.29.1
* Platform: 14.04.6 LTS, Trusty Tahr
* Firefox: 66.0.3
* Selenium: 3.141.0

I have a routine that has stopped working and is giving me these errors in geckodriver.log:

1623098508424	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilesFP3pI"
*** You are running in headless mode.
1623098509067	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1623098509068	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1623098509068	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*

(firefox:7231): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

(firefox:7231): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
1623098510834	Marionette	INFO	Listening on port 45092

(firefox:7231): dconf-CRITICAL **: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.

I can't understand why it stopped working

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Also note that Firefox 66.0.3 is very old and no longer maintained. You should run your tests with the recent Firefox 89 release.
