### ISSUE TITLE
Selenium v3.0.0-beta2 Navigate().GoToUrl() do not work when I call that second time

### ISSUE THREAD

**Issue by Efusoft** [mozilla/geckodriver#190]
OS:
Windows 10 

Selenium Version:
v3.0.0-beta2

Browser:
Firefox 48.0.1

I use geckodriver v0.10.0.

string url1 = "something1", url2 = "something2";

var profile = new FirefoxProfile();
DesiredCapabilities capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability("marionette", true);
FirefoxDriver driver = new FirefoxDriver(profile);
driver.Navigate().GoToUrl(url1);
driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));
driver.Navigate().GoToUrl(url2);
driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(10));

ERROR: driver open url1, but do not open url2. When open driver first time driver.Navigate().GoToUrl() method working success but second time it doesn't work.

**Comment by jgraham** [comment]
Does `url2` differ from `url1` only in the fragment part? If so this is #150 which is fixed in gecko but not yet released.

**Comment by Efusoft** [comment]
Yes url1 differ from url2. Sorry when gecko will be released. Thanks.

**Comment by andreastt** [comment]
Navigating from `something1` to `something2` is known to work. From `something` to `something` or `something#else` does not work outside of Nightly, but is fixed by [bug 1280300](https://bugzilla.mozilla.org/show_bug.cgi?id=1280300) which I just requested an uplift for.

**Comment by Efusoft** [comment]
Thanks. But I use Firefox 48.0.1. I have one other problem too first time driver.Navigate().GoToUrl(url1) method working success but second time ( driver.Navigate().GoToUrl(url1) ) it doesn't work.
