### ISSUE TITLE
Geckodriver unexpectedly exited with status code

### ISSUE THREAD

**Issue by ScuteMC** [mozilla/geckodriver#1900]
I am getting an error when trying to start the bot that i made. Checked the code but it was clean the error that i get is: selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: -4
Any help would be appreciated

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
