### ISSUE TITLE
File upload on Android

### ISSUE THREAD

**Issue by a-en** [mozilla/geckodriver#1904]
## System

* Version: 0.29.1
* Platform: Android 9
* Firefox: 88.1.4
* Selenium: 3.141.59

## Testcase

1. driver.get("https://the-internet.herokuapp.com/upload")
2. driver.findElement(By.id("file-upload")).sendKeys("/tmp/test.file");

There are couple of notes to be added:
- if I use LocalFileDetector while running test locally, I get `HTTP method is not allowed error` (which seems to be explained [here](https://github.com/mozilla/geckodriver/issues/1532#issuecomment-479447336))
- if I don't use LocalFileDetector, I get FileNotFoundException

So I'm under impression that now it is expected to work only with files that are available within emulator/device (so they don't need LocalFileDetector and could be located on mounted file system)

However, it is not that convenient because it requires to push all of the needed files at some point to emulator. Would really appreciate clarification on file upload functionality.

**Comment by whimboo** [comment]
Note that it all depends on where the browser is actually running. In your case it's on the Android device / emulator. At that point it doesn't have access to your host's machine file system. And as such I indeed would expect this failure.

To prevent that you would indeed have to push all the required files needed for upload to the device, or create these dynamically by the test. 

Or is chromedriver behaving differently here?

**Comment by EINBOX** [comment]
Can you share the config details to launch firefox browser on android emulator ?
is it required appium alone or appium along with Geckodriver services to test mobile browser application<firefox>?
