### ISSUE TITLE
Print command fails for large documents

### ISSUE THREAD

**Issue by betterphp** [mozilla/geckodriver#1905]
## System
* Version: `0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)`
* Platform: Ubuntu 21.04 docker image
* Firefox: `89.0.2+build1-0ubuntu0.21.04.1`
* Selenium: `4.0.0-beta.4`

## Stacktrace
```
Marionette threw an error: RangeError: too many arguments provided for a function call
GeckoDriver.prototype.print@chrome://marionette/content/driver.js:3117:37
```

The issue comes from the line
```
return {
  value: btoa(String.fromCharCode.apply(null, bytes)),
};
```
in the `GeckoDriver.prototype.print` function.

`.apply` will pass the given array as function arguments and it seems like Firefox has a 500000 limit

![image](https://user-images.githubusercontent.com/788007/124400938-11a95700-dd1e-11eb-94d8-8c083f456e13.png)

This essentially means there is a 500kb limit on any created PDF files.

**Comment by betterphp** [comment]
A couple of related issues
* https://github.com/mozilla/activity-stream/issues/3099
* https://stackoverflow.com/questions/38432611/converting-arraybuffer-to-string-maximum-call-stack-size-exceeded
* https://stackoverflow.com/questions/42263108/why-does-apply-with-too-many-arguments-throw-maximum-call-stack-size-exceeded

A common fix seems to be chunking the read file in to 1kb bits before appending in to the output. Not sure where to go to try and contribute that change though :(

**Comment by whimboo** [comment]
Thanks a lot for reporting the issue. We already had a similar issue with our CDP implementation, which already got fixed but it was missed for Marionette. As such I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1719124 for that particular issue.

Would you still have interest to contribute a fix? If yes, please let me know over on Bugzilla and I'm happy to guide you along the whole process. Thanks!

**Comment by betterphp** [comment]
Can do, would be fun to have a go

This seems to be my first problem though.

![image](https://user-images.githubusercontent.com/788007/124447843-ae4d1280-dd79-11eb-8a48-0ad2a634318a.png)

**Comment by betterphp** [comment]
I've emailed that address as the message suggests

**Comment by whimboo** [comment]
Sounds wonderful. So please let me know in case you don't get a reply until mid/end of this week. Until then you can have a look at https://mozilla-version-control-tools.readthedocs.io/en/latest/hgmozilla/unifiedrepo.html in how to get started with the repo. Thanks!

**Comment by whimboo** [comment]
Hi @betterphp, did you hear back from the Bugzilla admins? If not please let me know and also tell me the email address that you want to get re-activated. Thanks!

**Comment by betterphp** [comment]
No I didn't, Figured everything else out though, quite fun to work on :)

Email is jacek@kuzemczak.co.uk

**Comment by whimboo** [comment]
That's great to hear. In case of questions feel free to join us in https://chat.mozilla.org/#/room/#remote-protocol:mozilla.org. That should make it easier to discuss remaining questions.

Regarding Bugzilla I've asked some admin. Lets see that we can make progress here.

**Comment by betterphp** [comment]
That's great thanks :)

**Comment by whimboo** [comment]
@betterphp from https://github.com/mozilla/geckodriver/issues/1905#issuecomment-873948860 I just saw that you should be able to re-activate the account by requesting a password change from the login page. Did you actually try that?

**Comment by whimboo** [comment]
I was notified that your account has been already re-enabled on July 5th. So it should be all fine. Please let me know if that is the case. Thanks.

**Comment by betterphp** [comment]
Hey, sorry for the delay - yes I'm in now thanks.

The password reset gave the same error before but does seem to have worked today.

**Comment by reinhrst** [comment]
As I understand from https://bugzilla.mozilla.org/show_bug.cgi?id=1719124, the fix is scheduled for inclusion in Firefox 93; I can confirm that in the latest nightly, printing large pages through Marionette works again! Thanks!

**Comment by whimboo** [comment]
Yes, that is correct. And great to hear that it is working for you. As such closing this issue.

Big thanks to @betterphp for fixing it!
