### ISSUE TITLE
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:87)

### ISSUE THREAD

**Issue by Akmaxhub** [mozilla/geckodriver#1914]
## System

* Java Version: 16.0.1
* Platform: Selenium
* Chrome Driver: 3.141.59
* Selenium: 3.141.59
* Windows

## Testcase

I am able to connect to Selenium Grid local host without any issue. But while running code, getting below mentioned error.

## Trace-level log

FAILED CONFIGURATION: @BeforeTest setupDriver(org.testng.TestRunner@286b39c2)
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {browserName: chrome, platform: ANY, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: }
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TEST', ip: '192.168.29.31', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.1'
Driver info: driver.version: ChromeBrowserDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:87)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)

**Comment by whimboo** [comment]
This report looks invalid. The used driver here is `ChromeBrowserDriver`, which hasn't anything to do with geckodriver.
