### ISSUE TITLE
Selenium Remote Web Driver not starting with Firefox Profile given

### ISSUE THREAD

**Issue by alexfernandezv** [mozilla/geckodriver#1921]
### Test Case
I want to install a custom extension in a Firefox remote web driver. To achieve that I have created a FirefoxProfile and added the custom extension via setExtension. The problem is that the profile I have just created is not added to the Driver instance. Here is the piece of code I have used:
```
          File firefoxExtension = new File("src\\main\\resources\\browser-extensions\\firefox-extension.xpi");
          FirefoxProfile profile = new FirefoxProfile();
          profile.addExtension(firefoxExtension);
          FirefoxOptions options = new FirefoxOptions();
          options.setProfile(profile);
          capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS,options);

        try {
            return new RemoteWebDriver(new URL("https://" + username + ":" + accessKey + "@"
                    + environmentVariables.getProperty("browserstack.server") + "/wd/hub"), capabilities);
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
```
### System
Remote Platform: Windows 10
Firefox version: 68
Selenium: 3.141.59
Selenium Hub: Browser Stack

### Expected result

1. Browser opened
2. Profile loaded with the extension
3. Browser can be interacted using RemoteWebDriver

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
