### ISSUE TITLE
gzip: stdin: not in gzip format when trying to extract archive

### ISSUE THREAD

**Issue by Aegis940** [mozilla/geckodriver#1928]
## System

* Version: 0.29.1
* Platform: Debian 10 64bits
* gzip 1.9.3

I don't manage to extract the archive. I get the following error: `gzip: stdin: not in gzip format`
Command line: `tar xzf geckodriver-v0.29.1-linux64.tar.gz`

**Comment by whimboo** [comment]
Please have a look if the file has been correctly downloaded. Maybe you had a network issue and the download stopped earlier. You can verify a successful download of this file with the MD5 hash in https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz.asc.

For me it works fine, and the binary can be successfully extracted.
