### ISSUE TITLE
 Message: Connection refused (os error 111)"

### ISSUE THREAD

**Issue by sazollne** [mozilla/geckodriver#1929]
## System

* Version: Geckodriver 0.29.1
* Platform: CentOS Linux release 7.9.2009 (Core)
* Firefox: Mozilla Firefox 78.13.0esr
* Selenium: 3.141.0 

## Testcase
    def selenium(self):
        options = FirefoxOptions() 
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')
        binary = ("/usr/bin/firefox")
        self.browser = webdriver.Firefox(firefox_binary=binary,
        executable_path="/home/omoscott/projects/Webscraping/extractors/geckodriver",
        options=options,service_log_path="/home/omoscott/projects/Webscraping/extractors/geckodriver.log")

########## getAllLinks fuction ##########
Traceback (most recent call last):
  File "lapolarfirefox.py", line 463, in <module>
    all_the_links, all_the_data = Container().run()
  File "lapolarfirefox.py", line 452, in run
    self.all_links = self.getAllLinks(self.configuration.url_list, self.configuration.results_by_page)
  File "lapolarfirefox.py", line 346, in getAllLinks
    lapolar = LapolarHttpExtractor()
  File "lapolarfirefox.py", line 32, in __init__
    self.configuration = Configuration()
  File "lapolarfirefox.py", line 154, in __init__
    self.selenium()
  File "lapolarfirefox.py", line 193, in selenium
    self.browser = webdriver.Firefox(firefox_binary=binary, executable_path="/home/omoscott/projects/Webscraping/extractors/geckodriver",
  File "/home/omoscott/anaconda3/envs/webscraping/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/omoscott/anaconda3/envs/webscraping/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/omoscott/anaconda3/envs/webscraping/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/omoscott/anaconda3/envs/webscraping/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/omoscott/anaconda3/envs/webscraping/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)

## Trace-level log
*** You are running in headless mode.
1631283237174	Marionette	INFO	Listening on port 41853
1631283237312	Marionette	WARN	TLS certificate errors will be ignored for this session
1631283237547	geckodriver	INFO	Listening on 127.0.0.1:51620
Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
1631283238920	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "--marionette" "--headless" "--no-sandbox" "--disable-dev-shm-usage" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofilegPCKN9"

Good afternoon I have tried to run a Script using geckodriver on Centos Linux, nevertheless It cant work after contacting with url. I dont know, how to fix the problem. The result message is "selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)".
 

[geckodriver.log](https://github.com/mozilla/geckodriver/files/7145473/geckodriver.log)

**Comment by whimboo** [comment]
There seem to be different issues here:

1) Some of you code is trying to start Firefox in normal mode without having a `DISPLAY` variable set. Within the log that affects a couple of start, and looks like `Error: no DISPLAY environment variable specified`.

2)Using `headless` mode there is a `DBUS` error, which indicates that there is also this missing `DISPLAY` variable. Here is the appropriate error: `Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`.

So all in all this looks like a system configuration issue and not related to geckodriver.
