### ISSUE TITLE
Firefox isn't started through WSL2 because of "Net::ReadTimeout (Net::ReadTimeout)"

### ISSUE THREAD

**Issue by austin-wangyu** [mozilla/geckodriver#1930]
## System

* Version: Geckodriver 0.29.1
* Platform: Ubuntu 20.04.1 LTS via WSL2 on Windows 10
* Firefox: 92.0
* Selenium: selenium-webdriver Ruby gem 4.0.0.rc1

## Test Case
I am running a Cucumber test with Selenium and Geckodriver with the following configuration for Selenium and Capybara:
```
Capybara.javascript_driver  = :selenium
Selenium::WebDriver.logger.level = :debug
opts = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
driver = Selenium::WebDriver.for :firefox, options: opts
```
The tests themselves do not run, no Firefox window is opened, and according to assistance provided to me on Stackoverflow, "[geckodriver in trace mode should be telling you more than it is](https://stackoverflow.com/questions/69185661/selenium-netreadtimeout-on-tests-that-pass-instantly-without-javascript-tag)." It was recommended to me that I file a bug report here. Please let me know if there is other information that I ought to provide to better assist the process, or if this is not relevant.

## Trace-level log
Upon running `cucumber features/admin/admin_authentication.feature`, this is the log I get in the console:

```
"/home/nacho/Github/cs370/config/local_env.yml"
2021-09-15 18:16:20 DEBUG Selenium Executing Process ["/usr/bin/geckodriver", "--port=4444"]
2021-09-15 18:16:20 DEBUG Selenium polling for socket on ["127.0.0.1", 4444]
1631754980132   geckodriver     INFO    Listening on 127.0.0.1:4444
2021-09-15 18:16:20 WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
2021-09-15 18:16:20 INFO Selenium -> POST session
2021-09-15 18:16:20 INFO Selenium    >>> http://127.0.0.1:4444/session | {"capabilities":{"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"log":{"level":"trace"}}}}}
2021-09-15 18:16:20 DEBUG Selenium      > {"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.0.0.rc1 (ruby linux)", "Content-Length"=>"105"}
1631754980402   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofileFaHMgO"
1631754980403   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:38581
Net::ReadTimeout (Net::ReadTimeout)
```
There are more lines of Ruby erroring out, but they didn't appear relevant so I didn't paste them above. Just in case, I've attached a .txt with the full excerpt. [geckodriver error log.txt](https://github.com/mozilla/geckodriver/files/7174591/geckodriver.error.log.txt)

**Comment by whimboo** [comment]
Please test outside of Ruby, by starting the geckodriver binary yourself:

```
/usr/bin/geckodriver -vv --binary /usr/bin/firefox
```

Then use curl to request a new WebDriver session:

```
curl -v http://localhost:4444/session -X POST -H "Content-Type: application/json" -d '{}'
```

Does that bring up a new Firefox, and correctly report logs? Maybe that's a problem with the Ruby bindings.

**Comment by austin-wangyu** [comment]
Tab 1: `$ /usr/bin/geckodriver -vv --binary /usr/bin/firefox` 
Tab 2: `curl -v http://localhost:4444/session -X POST -H "Content-Type: application/json" -d '{}'`

Tab 1 output: 
```
1631780109034   geckodriver     INFO    Listening on 127.0.0.1:4444
1631780125404   webdriver::server       DEBUG   -> POST /session {}
1631780125404   webdriver::command      WARN    You are using deprecated legacy session negotiation patterns (desiredCapabilities/requiredCapabilities), see https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities#Legacy
1631780125406   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofilepV0eXB"
1631780125407   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1:36603
1631780255463   mozrunner::runner       DEBUG   Killing process 21812
1631780255464   geckodriver::browser    DEBUG   Browser process stopped: signal: 9
1631780255464   webdriver::server       DEBUG   <- 500 Internal Server Error {"value":{"error":"timeout","message":"Connection refused (os error 111)","stacktrace":""}}
```

Tab 2 output:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:4444...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4444 (#0)
> POST /session HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 2
>
* upload completely sent off: 2 out of 2 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-type: application/json; charset=utf-8
< cache-control: no-cache
< content-length: 91
< date: Thu, 16 Sep 2021 08:15:25 GMT
<
* Connection #0 to host localhost left intact
{"value":{"error":"timeout","message":"Connection refused (os error 111)","stacktrace":""}}
```

Firefox did not open in the VcXsrv/xfce4 window. This indicates that it's a problem with my environment, right? I would like to mention, as I forgot to above, that this entire testing process (cucumber, selenium, geckodriver) was working a few months ago and only broke recently when I tried running it again, same codebase and everything. Are there any local system settings I should check to confirm that it's my machine?

**Comment by whimboo** [comment]
Are you able to start Firefox yourself via the command line? Try it out with a specified profile like: `/usr/bin/firefox --marionette --no-remote --profile /tmp/rust_mozprofilepV0eXB`.

If that fails it's clearly an issue with Firefox. It might be good to check older Firefox releases, to figure out what's the last working release. Nevertheless I would propose to file a bug in Bugzilla instead. A good initial component would be [Firefox :: General](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=General). When you filed please let me know about the bug number. Thanks.

That said it's very unlikely that this is a geckodriver issue. As such closing this bug.

**Comment by austin-wangyu** [comment]
I didn't have the file `/tmp/rust_mozprofilepV0eXB`, so when I ran the line provided as written it came up with a popup error on screen saying "Your Firefox profile cannot be loaded. It may be missing or inaccessible." However, trying that line of code with any of the other `rust_mozprofile[suffix]` opened a firefox window. Does that still classify as a Firefox issue?

**Comment by whimboo** [comment]
Maybe some preference that geckodriver sets is causing some misbehavior with your setup. As such could you please attach a [trace-level log] from geckodriver? Thanks.

I'm going to reopen the issue for now.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by austin-wangyu** [comment]
Hi, sorry but since I wasn't getting any progress made trying to debug/fix the issue, I just completely reinstalled Ubuntu and set up my environment from scratch; that resolved the issue, so I won't be able to provide any more insight on what went wrong.

**Comment by whimboo** [comment]
So it sounds like there was an issue with this specific Ubuntu installation. Would have been good to know what caused that, but also good to hear that it's working for you now.
