### ISSUE TITLE
Error WebDriverException: Message: Failed to decode response from marionette with updated Firefox and gecko

### ISSUE THREAD

**Issue by sofiand-png** [mozilla/geckodriver#1934]
## System

* Version: geckodriver-v0.29.0
* Platform: RobotFramework docker with ubuntu:16.04
* Firefox: 88.0
* Selenium: robotframework-seleniumlibrary==4.5.0
* Pabot version: 1.13
 I use pabot to run the tests in parallel in Jenkins inside a docker.
Notes: 
* each test case uses Close All Browsers in the tear down + there is a sleep of 5 sec after closing browsers.
* each test case uses its own browser (means that each test case creates a new browser)
* The issue is sporadic
* Screenshot :
![log-screenshot](https://user-images.githubusercontent.com/54711158/133797697-c11c8ad4-407d-46a8-aa1d-44f63f7d0ca1.PNG)

## Testcase
Start AUT
    [Arguments]    ${browser}
    [Documentation]    *Starting the access to the system Login page*
    ...    ``Browser`` argument that specifies the browser to use
    ...    Create the driver, depending on the browser and the mode
    ...    Access the system page
    ...
    ${url}    Get Main URL #This KW is going to return the URL to access the application
    Run Keyword if    '${browser}' == 'Chrome' and ${HEADLESS}    Run Chrome
    Run Keyword if    '${browser}' == 'Firefox' and ${HEADLESS}    Run Firefox
    Run Keyword if    not ${HEADLESS} and '${browser}' == 'Chrome'    Run Standard Chrome
    Run Keyword if    not ${HEADLESS} and '${browser}' == 'Firefox'    Run Standard    ${browser}    ${url}
    #Take Screenshot
    Delete All Cookies
    Delete All Sessions
    ${url}    get_main_url
    Go To    ${url}
    Set Selenium Speed    0
    
## Stacktrace
3 files were generated in the test artifcats but I am not sure if these are the relevant logs

[geckodriver-3.log](https://github.com/mozilla/geckodriver/files/7186317/geckodriver-3.log)
[geckodriver-2.log](https://github.com/mozilla/geckodriver/files/7186318/geckodriver-2.log)
[geckodriver-1.log](https://github.com/mozilla/geckodriver/files/7186319/geckodriver-1.log)

## Trace-level log
see attachment
[log-trace.txt](https://github.com/mozilla/geckodriver/files/7186282/log-trace.txt)

**Comment by whimboo** [comment]
The logs from geckodriver should be [trace-level logs]. Can you please attach one of these?

[trace-level logs]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by sofiand-png** [comment]
[geckodriver-223.log](https://github.com/mozilla/geckodriver/files/7217831/geckodriver-223.log)
The issue happened yesterday on my local envionment (Windows 10 , Firefox 91.0.2, geckodriver v0.29.0
This is the first time the issue happens on my local environment.
Usually I run the tests with robot command in my local env.
I have a also a log when the same test case has run without this issue (it was the run just before for which this the log :
[geckodriver-222.log](https://github.com/mozilla/geckodriver/files/7217847/geckodriver-222.log)

**Comment by sofiand-png** [comment]
The recent execution linked to recently attached logs showed another error message in the test log : 
![image](https://user-images.githubusercontent.com/54711158/134513844-a846a010-9124-4dee-97aa-88800a38db29.png)

**Comment by whimboo** [comment]
> [geckodriver-223.log](https://github.com/mozilla/geckodriver/files/7217831/geckodriver-223.log)

This is still not a requested trace log. Please check again. There have to be `Marionette Trace` entries to be listed.

Nevertheless I can see a problem when trying to remove the certificate override. Can you please check if the same happens when not setting the `acceptInsecureCerts` capability?

**Comment by simonprovost** [comment]
Any update?

**Comment by whimboo** [comment]
@simonprovost if you want to see updates the requested information would have to be provided. If that's not happening we will have to close the issue. You can help with that by recording and attaching a trace log. Instructions see above. Thanks.

**Comment by whimboo** [comment]
Closing issue because no helpful information has been provided in the last half year.
