### ISSUE TITLE
geckodriver 0.30.0 doens't allow connections from local IPv6 address (::1)

### ISSUE THREAD

**Issue by anthony0lai** [mozilla/geckodriver#1936]
## System

**Hit in both systems below**
### Laptop setup
* Version: 0.30
* Platform: Windows 10 Enterprise Version 1909
* Firefox: 92.0.1 (64-bit)
* Selenium: 3.141.0 on dotnet core 5.0.401

### [Microsoft Azure hosted agent Windows 2019 (20210920 update)](https://github.com/actions/virtual-environments/pull/4122)
* Version: 0.30
* Platform: Windows Server 2019 10.0.17763 Build 2183
* Firefox: 92.0
* Selenium: 3.141.0 on dotnet core 5.0.401

## Testcase
Running the following C# code to initialize firefox using gecko driver 
```csharp
// firefoxWDPath is a string where contains the folder full path of gecko driver binary

IWebDriver webDriver = null;
var firefoxOptions = new FirefoxOptions();
string webDriverFileName = "geckodriver.exe";

 FirefoxDriverService _firefoxDriverService = FirefoxDriverService.CreateDefaultService(firefoxWDPath, webDriverFileName);
_firefoxDriverService.Host = "::1";
webDriver = new FirefoxDriver(_firefoxDriverService, firefoxOptions);
```

Exception will be thrown with error message: Fail to initialize Firefox webdriver - Cannot start the driver service on http://localhost:(port number)/

The problem will not longer exist if geckodriver.exe is reverted with 0.29.1 binary

## Stacktrace
Error found in windows eventviewer (Laptop setup system only)
![image](https://user-images.githubusercontent.com/37915758/134602399-26f1ca26-2736-4618-bc49-885c0a3dc699.png)
![image](https://user-images.githubusercontent.com/37915758/134602464-4832c700-e940-46a3-b1b1-4c054e95db47.png)

## Trace-level log
N/A as firefox cannot be initialized at all

**Comment by whimboo** [comment]
There is also https://github.com/mozilla/geckodriver/issues/1935. As it looks like there is a problem with IPv6 and `::1` is not detected as local loopback interface. We are going to investigate via https://bugzilla.mozilla.org/show_bug.cgi?id=1732622.

**Comment by whimboo** [comment]
We got this fixed. See #1972 for details.
