### ISSUE TITLE
Space saving After Build: Raspberrypi 4 Geckodriver

### ISSUE THREAD

**Issue by walksonair** [mozilla/geckodriver#1937]
This isn't an issue per se but rather a plea for help/advice on how to save space on my rPi4. Can I get rid of any of the following directories after a successful build?

```
~/.cargo
~/.rustup
~/testing
```

**Comment by whimboo** [comment]
You can write your own small make file (script) that would delete those files after a build. This is nothing we can provide given that those folders act as caches, and will speed-up builds later on.

**Comment by walksonair** [comment]
I was just looking for an answer as to whether or not it is ok the delete those listed directors after my build and that it will not result in any runtime issues.

Thanks for the response.
