### ISSUE TITLE
Bind --websocket-port on start

### ISSUE THREAD

**Issue by p0deje** [mozilla/geckodriver#1938]
## System

* Version: geckodriver 0.30.0 (d372710b98a6 2021-09-16 10:29 +0300)
* Platform: macos 12.0 Beta (21A5522h)
* Firefox: -
* Selenium: -

## Testcase

1. Run geckodriver with `--websocket-port` argument:

```
$ geckodriver --port 4445 --websocket-port 9223
1632846981802	geckodriver	INFO	Listening on 127.0.0.1:4445
```

2. Run another geckodriver with the same `--websocket-port`:

```
$ geckodriver --port 4446 --websocket-port 9223
```

I would expect the second instance to fail with `Address already in use` error because it would bind to the same 9223 port. Yet, it is not binding at all and the port remains free. This can be a problem because any other process can also take this port.

## Stacktrace

None.

## Trace-level log

None.

**Comment by whimboo** [comment]
Thanks for the report. 

Please note that it is not geckodriver which binds this port but Firefox. geckodriver only passes it through. As such if keeping the port locked in geckodriver, Firefox won't be able to make use of it.

Instead we want to allow Firefox to use a system allocated port and let geckodriver read it during Firefox startup from a file as written in the Firefox profile. See https://bugzilla.mozilla.org/show_bug.cgi?id=1751844 for details.

@jgraham I assume that we can close this issue, or do you see some improvements when a specific websocket port has been specified via geckodriver?

**Comment by jgraham** [comment]
Yeah, I don't think we can do much here given that geckodriver itself isn't binding the port. Binding the port at startup and then unbinding it right before session start is of course possible, but it doesn't really solve the problem, just changes the race a bit. Generally we should encourage users to use a system-assigned port where possible, rather than specifying one explicitly.
