### ISSUE TITLE
macOS binaries for v0.30.0 (2021-09-16) are mislabeled

### ISSUE THREAD

**Issue by fseesink** [mozilla/geckodriver#1939]
## System

* Version: 0.30.0 (2021-09-16)
* Platform: macOS
* Firefox: 92.0.1
* Selenium: 

On this page:  https://github.com/mozilla/geckodriver/releases/tag/v0.30.0

* `geckodriver-v0.30.0-macos-aarch64.tar.gz`, in fact, contains the Intel x64 binary, while
* `geckodriver-v0.30.0-macos.tar.gz` contains the ARM64 (Apple M1) binary.

**Comment by whimboo** [comment]
This has been fixed a while ago via #1932. Maybe you have a bad cache?

**Comment by fseesink** [comment]
You fixed but never updated the version then I take it.  I likely downloaded it soon after 0.3.0 was released.  Since no new version was posted, was no way to know things were fixed.  Weird I couldn't find #1932 when I first came, as I typically search before posting.  But thanks for letting me know.  Will just pull it down again.

**Comment by whimboo** [comment]
Good to hear that it was an older downloaded file! In regards of pushing a new release this won't work given that you can only do it once and you cannot re-use the same version. Also there were no code changes, so that updating a release is the way to go. And that I did here.
