### ISSUE TITLE
Method not allowed while using send keys to input type "file"  which can be  visible and can be find using webDriver. The display  attribute is already set to block using JS and the input WebElement is accessible.

### ISSUE THREAD

**Issue by Gaurav1789** [mozilla/geckodriver#1942]
## System

* Version: 
* Platform: 
* Firefox: 
we execute JS  script on this Element to enable the browse button(by setting display style attribute to block) and then select a local path which works in chrome but fails in Firefox in _upload method.
in _upload method of  selenium web-driver  while executing Command.UPLOAD_FILE in Firefox we get method not allowed 

same thing works successfully in chrome driver with no change to test script

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
