### ISSUE TITLE
unble to execute geckodriver through mobile in windows 

### ISSUE THREAD

**Issue by ghost** [mozilla/geckodriver#1943]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by Mitrabhanu-tech** [comment]
i have already set the path for geckodriver in enviorment variable ,but still facing the same issue
