### ISSUE TITLE
SessionNotCreatedError: A new session could not be created. Details: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by Mitrabhanu-tech** [mozilla/geckodriver#1944]
## System

* Version: 0.30.0
* Platform: windows 10
* Firefox: 
* Selenium: 

## Testcase
cap.setCapability(MobileCapabilityType.AUTOMATION_NAME,"Gecko");
		cap.setCapability(MobileCapabilityType.BROWSER_NAME,"firefox");
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME,"Android");
		cap.setCapability("deviceOrientation","portriat");
		//cap.setCapability(" androidStorage","internal");
		final Map<String,Object> firefoxOptions = new HashMap<>();
		firefoxOptions.put("androidPackage", "org.mozilla.firefox");
		//firefoxOptions.put("androidActivity", "org.mozilla.geckoview_example.GeckoView");
		firefoxOptions.put("androidDeviceSerial", "67853479");
		cap.setCapability("maxInstances", "1");
		cap.setCapability("moz:firefoxOptions", firefoxOptions);
		cap.setCapability("acceptInsecureCerts", true);
		cap.setCapability("stacktrace", true);
		
		final Map<String,Object> firefoxOptions1 = new HashMap<>();
		firefoxOptions1.put("level", "trace");
		cap.setCapability("log", firefoxOptions1);
		
		final Map<String,Object> firefoxOptions2 = new HashMap<>();
		firefoxOptions2.put("MOZ_LOG", "nsHttp:5");
		firefoxOptions2.put("MOZ_LOG_FILE", "/mnt/sdcard/log");
		cap.setCapability("androidIntentArguments", firefoxOptions2);

## Trace-level log

[Appium] Appium v1.22.0 creating new GeckoDriver (v0.3.3) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "acceptInsecureCerts": true,
[debug] [BaseDriver]     "appium:androidIntentArguments": {
[debug] [BaseDriver]       "MOZ_LOG": "nsHttp:5",
[debug] [BaseDriver]       "MOZ_LOG_FILE": "/mnt/sdcard/log"
[debug] [BaseDriver]     },
[debug] [BaseDriver]     "browserName": "firefox",
[debug] [BaseDriver]     "appium:deviceOrientation": "portriat",
[debug] [BaseDriver]     "appium:log": {
[debug] [BaseDriver]       "level": "trace"
[debug] [BaseDriver]     },
[debug] [BaseDriver]     "appium:maxInstances": "1",
[debug] [BaseDriver]     "moz:firefoxOptions": {
[debug] [BaseDriver]       "androidDeviceSerial": "67853479",
[debug] [BaseDriver]       "androidPackage": "org.mozilla.firefox"
[debug] [BaseDriver]     },
[debug] [BaseDriver]     "platformName": "android",
[debug] [BaseDriver]     "appium:stacktrace": true,
[debug] [BaseDriver]     "appium:automationName": "Gecko",
[debug] [BaseDriver]     "appium:deviceName": "67853479"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   androidIntentArguments
[BaseDriver]   deviceOrientation
[BaseDriver]   log
[BaseDriver]   maxInstances
[BaseDriver]   stacktrace
[BaseDriver] Session created with session id: f17be5f3-4a5c-4e66-aa06-38f99851ce8f
[GeckoDriverServer] Starting 'C:\Users\Mitrabhanu Pradhan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-geckodriver\geckodriver\geckodriver.exe' with args ["-p",5200]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:5200/status] with no body
[debug] [GeckoDriverServer] [geckodriver.exe] 1633961867666     geckodriver     INFO    Listening on 127.0.0.1:5200
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"","ready":true}}
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:5200/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","acceptInsecureCerts":true,"moz:firefoxOptions":{"androidDeviceSerial":"67853479","androidPackage":"org.mozilla.firefox"},"platformName":"android"}}}
[WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Unable to find a matching set of capabilities","stacktrace":""}}
[debug] [W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[GeckoDriver] Ending Gecko Driver session
[GeckoDriverServer] geckodriver.exe has exited with code null, signal SIGTERM
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1633961867716 (19:47:47 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Unable to find a matching set of capabilities
[debug] [W3C]     at errorFromW3CJsonCode (C:\Users\Mitrabhanu Pradhan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
[debug] [W3C]     at ProxyRequestError.getActualError (C:\Users\Mitrabhanu Pradhan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
[debug] [W3C]     at GeckoProxy.command (C:\Users\Mitrabhanu Pradhan\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:272:19)
[debug] [W3C]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[HTTP] <-- POST /wd/hub/session 500 785 ms - 879
[HTTP]

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
