### ISSUE TITLE
Host header mismatch message is misleading

### ISSUE THREAD

**Issue by TilBlechschmidt** [mozilla/geckodriver#1947]
## System

* Version: v0.30.0
* Platform: macOS 12
* Firefox: 91.0.2
* Selenium: Postman 😜

## Testcase

1. Launch geckodriver locally on the default port (4444)
2. Open Postman and send a POST request with the following body to `127.0.0.1:4444/session`
```
{
    "capabilities": {
        "firstMatch": [
            {
                "browserName": "firefox"
            }
        ]
    }
}
```
3. It spits out a session ID. Plug that into a GET request to `127.0.0.1:4444/session/<id>/title`
4. Overwrite the automagically calculated `Host` header by Postman with `127.0.0.1` (without the port)

## Stacktrace

```
{
    "value": {
        "error": "unknown error",
        "message": "Host header doesn't match server 127.0.0.1",
        "stacktrace": ""
    }
}
```

<img width="644" alt="Screenshot 2021-10-14 at 12 52 05" src="https://user-images.githubusercontent.com/5037967/137305514-d0675635-bae8-4d3c-9e54-8b23156fdbfd.png">

## Trace-level log

Inapplicable.

## What should happen?

The error message should contain the full expected host header, not just the IP — or not match the port. Setting the header to `127.0.0.1:4444` works as expected.

**Comment by whimboo** [comment]
The fix landed a while ago and will be part of the next geckodriver release. If it's important for you then you could use a [nightly build of geckodriver](https://treeherder.mozilla.org/jobs?repo=mozilla-central&searchStr=gd-s%2Cmac&revision=2c2b8330e2a5f7f7fc7480bcc852f7ea44e1a1ee&selectedTaskRun=KVijQsMQQiKl1_Ada0CNog.0).

Thanks again for reporting!
