### ISSUE TITLE
sendAsync Standard_Error

### ISSUE THREAD

**Issue by WanderingKazuma** [mozilla/geckodriver#195]
Running Selenium 3 on geckodriver 0.10.0 on osx java 1.8.0_40 from gradle. It looks like the driver.close(); function isn't doing anything, but the driver.quit(); function is closing the browser at the end of the execution. I am also seeing the following in the console. I am running my gradle task with the --info flag.
```
User Dropdown Test - Tests > User Dropdown Tests > TopNav.UserDropdown.MyAccount_HeaderVisible STANDARD_ERROR
    1472066507570      	Marionette     	INFO   	sendAsync 5a7516e9-5829-b847-809f-cd0291e804d2
    1472066507576      	Marionette     	INFO   	sendAsync 5a7516e9-5829-b847-809f-cd0291e804d2
    1472066507589      	Marionette     	INFO   	sendAsync 5a7516e9-5829-b847-809f-cd0291e804d2
    1472066507595      	Marionette     	INFO   	sendAsync 5a7516e9-5829-b847-809f-cd0291e804d2
```

Seeing this about 15-30 times on a single run where the script logs in and clicks on the header menu items. The script is successful in logging in, but not all the header menu items are clicked (watching for page changes and not seeing anything).

**Comment by andreastt** [comment]
This is a leftover debug statement and nothing to worry about. It was removed in [bug 1280645](https://bugzilla.mozilla.org/show_bug.cgi?id=1280645), and I just requested it to be uplifted to Aurora and Beta.
