### ISSUE TITLE
Struggling to config the geckodriver to connect to an opened firefox instead of each time opening a new window

### ISSUE THREAD

**Issue by ThomasSun001** [mozilla/geckodriver#1950]
System
I have an Centos 64-bit OS

I'm trying to run cucumber selenium automation tests with geckodriver and firefox

I searched online foe how to run firefox with forehand mode running during test stage
this is probably the closest command I can get
firefox --remote-debugging-port 4444
but this command works seems bizarre, it opens browser and jumps to a random local page where I have no idea to reason about

Here's a snippet from the ruby:
    options = Selenium::WebDriver::Firefox::Options.new
    options.add_argument("--connect-existing")
    options.add_argument("--marionette-host=127.0.0.1")
    options.add_argument("--marionette-port=4444")
    $driver = Selenium::WebDriver.for(:firefox,options:options)

When I actually trigger the test, it just opens a new browser window instead of the existing one which is not what I expect 

Anyone here can help?
thx for any help

**Comment by whimboo** [comment]
Running Firefox with `--remote-debugging-port` is not configuring the Marionette component, which backs the WebDriver implementation. To run Marionette you have to use the `--marionette` command line argument instead. By default it will start on port `2828` but can be configured via the Firefox preference `marionette.port`. And that's the number that geckodriver needs for `--marionette-port` if you want to connect to this particular Firefox instance.

Note that `--remote-debugging-port` is used for the upcoming WebDriver BiDi protocol but I don't see that this is wanted here.
