### ISSUE TITLE
Geckodriver seems to ignore Cache-Control: no-cache directive

### ISSUE THREAD

**Issue by pmgexpo17** [mozilla/geckodriver#1951]
## System

* Version: 30.0
* Platform: linux kernel 5.11.0-38-generic
* Firefox: 93.0
* Marionette-driver: 3.1.0 

Edit 1 : After further reflection I'm not sure I should expect Firefox to cache url request responses in the profile
This is probably the job of a proxy and probably a reverse proxy, in terms of the best proxy arrangement
**Please advise if Firefox can do response caching in the profile storage** 

Edit 2 :
I found a [mozilla caching doc resource](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching) which says :
"This page will mostly talk about browser and proxy caches, but there are also gateway caches, CDN, reverse proxy caches and load balancers that are deployed on web servers for better reliability, performance and scaling of web sites and web applications"
If I want Firefox to doing caching in memory or profile storage, **does that mean my mitmproxy Cache-Control command should specify a private cache?** :
mitmdump --ignore-hosts 'google|facebook|yahoo' --setheader :~q:Cache-Control:private

Edit 3 : 
Not sure if the following info is still relevant apart from Firefox args or config that setups a private browser cache ?

I'm in the process of developing a python scraping package 
I investigated how to setup [firefox options](https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions) when configuring marionette-driver
Here is my json configuration and marionette_driver setup code :
{
  "marionetteDriver": {
    "capabilities": {
      "acceptInsecureCerts": true,
      "proxy": {
        "proxyType": "manual",
        "httpProxy": "127.0.0.1:8080",
        "sslProxy": "127.0.0.1:8080"
      }
    },
    "enableWebRender": true,
    "firefoxArgs": ["-profile","/data/mozilla/firefox/profile/profile-A2"],
    "geckoKind": "fxdesktop",
    "geckoVerbosity": true,
    "logRoot": "/data/mozilla/geckodriver/log",
    "preferences": {},
    "pathToBinary": "/usr/lib/firefox/firefox",
    "startSessionTimeout": 60,
    "timeouts": {
      "implicit": 10,
      "page_load": 90
    }
  }
}
def __post_init__(self, configA: Note):
    logfile = "{}/gecko-session-{}.log".format(configA.logRoot, datetime.now().strftime('%y%m%d%H%M%S'))
    browser = None
    browser = Marionette(
      app=configA.geckoKind,
      app_args=configA.firefoxArgs,
      bin=configA.pathToBinary,
      enable_webrender=configA.enableWebRender,
      gecko_log=logfile,
      headless=True,
      verbose=configA.geckoVerbosity)
    logger.debug("Marionette instance creation succeeded ... now to create a new browser session ...")
    caps = browser.start_session(capabilities=configA.capabilities,timeout=configA.startSessionTimeout)
    logger.debug(f"Marionette session startup suceeded with capabilities : \n{caps}")
    logger.debug("Adding marionette session preferences ...")
    for method, args in configA.preferences.items():
      if hasattr(browser, method):
        logger.debug("Applying marionettte preference : {}, {}".format(method, args))
        getattr(browser, method)(*args)
    browser.timeout.implicit = configA.timeouts["implicit"]
    browser.timeout.page_load = configA.timeouts["page_load"]

For proxy purposes, I'm running this mitmdump command
mitmdump --ignore-hosts 'google|facebook|yahoo' --setheader :~q:Cache-Control:no-cache

My program opens the target website url numerous times for consecutive tasks in a job
After the initial page opens, I was hoping firefox would return the cached response for future requests of the same url
Sometimes, there is a 90sec page load timeout for a page that should be cached !
By modified date, I can see that firefox is writing content in the configured profile region at /data/mozilla/firefox/profile/profile-A2
**Please advise how to effectively setup binary firefox to consistently use caching**

DEBUG:27-10-2021 10:40:03 AM,operatorMA.py:105 MarionetteOperator created a new browser tab window with handle :
2c5d5fb9-c38b-4b6a-88aa-0605a03daf36
DEBUG:27-10-2021 10:40:03 AM,operatorMA.py:106 ... and is closing the previous iteration browser tab :
57ba40f5-432a-485f-9b18-bb9d45031235
INFO:27-10-2021 10:40:03 AM,operatorMA.py:135 about to request serving url : https://www.scrape-target.com.au
INFO:27-10-2021 10:40:13 AM,operatorMA.py:139 request completed in 10.5866 seconds !

DEBUG:27-10-2021 10:42:11 AM,operatorMA.py:105 MarionetteOperator created a new browser tab window with handle :
6cd9a64f-17d3-4630-a181-952019717190
DEBUG:27-10-2021 10:42:11 AM,operatorMA.py:106 ... and is closing the previous iteration browser tab :
2c5d5fb9-c38b-4b6a-88aa-0605a03daf36
INFO:27-10-2021 10:42:11 AM,operatorMA.py:135 about to request serving url : https://www.scrape-target.com.au
INFO:27-10-2021 10:42:17 AM,operatorMA.py:139 request completed in 6.4171 seconds !

DEBUG:27-10-2021 10:42:41 AM,operatorMA.py:99 MarionetteOperator creating a new tab window ...
DEBUG:27-10-2021 10:42:41 AM,operatorMA.py:105 MarionetteOperator created a new browser tab window with handle :
03f6abde-5a00-44ba-9526-dacb4f1e475b
DEBUG:27-10-2021 10:42:41 AM,operatorMA.py:106 ... and is closing the previous iteration browser tab :
6cd9a64f-17d3-4630-a181-952019717190
INFO:27-10-2021 10:42:41 AM,operatorMA.py:135 about to request serving url : https://www.scrape-target.com.au
ERROR:27-10-2021 10:44:11 AM,operatorMA.py:142 Marionette_driver errored loading url :  https://www.scrape-target.com.au
TimedPromise timed out after 90000 ms
stacktrace:
	WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5
	TimeoutError@chrome://remote/content/shared/webdriver/Errors.jsm:450:5
	bail@chrome://remote/content/marionette/sync.js:230:19

**Comment by whimboo** [comment]
> Please advise how to effectively setup binary firefox to consistently use caching

geckodriver doesn't modify the cache handling of Firefox. As such any questions related to using the disk or memory cache should be raised in any of the [Firefox support channels](https://support.mozilla.org/en-US/products/firefox). It should be enough to use Firefox with a default profile directly (without geckodriver) to reproduce the problem and solve it. If some preferences need to be set, these can for sure be specified in `moz:firefoxOptions`.

I'm going to close this issue now, but feel free to respond in case you found the answer.

**Comment by pmgexpo17** [comment]
@whimboo thanks for directing me to [Firefox support channels](https://support.mozilla.org/en-US/products/firefox)
