### ISSUE TITLE
[SE 4.0] Geckodriver run fine from IDE but got an error WebDriverException from executable jar

### ISSUE THREAD

**Issue by michaeljclark125** [mozilla/geckodriver#1952]
## System

* Version: 0.30.0
* Platform: Windows 10
* Firefox: v93 64bit
* Selenium: 4.0.0

## Testcase

Geckodriver works fine when run from IDE (netbeans 12.5) but it doesn't work when I run from executable jar (Firefox browser doesn't open and nothing happens). I got an error below (I catch ex from joptionpane):
```
org.openqa.selenium.WebDriverException: Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'DESKTOP-LMSUFO4', ip: '10.8.0.3', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: driver.version: FirefoxDriver

```

## Stacktrace

I don't have error trace because it run file from IDE (netbeans).

**Comment by haumacher** [comment]
Same problem here, the exception is as follows: 

```
Exception in thread "main" org.openqa.selenium.WebDriverException: Build info: version: '4.0.0', revision: '3a21814679'
System info: host: 'defr-ltux-123', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-84-generic', java.version: '11.0.11'
Driver info: driver.version: FirefoxDriver
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:230)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
```

I think the reason is the following: You packaged your tool into a fat jar by adding all dependencies to the executable jar. But the selenium drivers rely on the Java service mechanism (java.util.ServiceLoader), where `/META-INF/services/org.openqa.selenium.remote.service.DriverService$Builder` files are looked up from the class path. Normally, each Jar provides its own version of that file. But if you generate a fat JAR, the different versions of the service files overwrite each other. In the result, only one service definition is placed in the fat JAR - unfortunately not the one that loads the gekodriver. 

To circumvent this problem, only add a single driver JAR to your fat JAR, or do not deploy as fat JAR.

**Comment by haumacher** [comment]
With Eclipse, you can package the required jars into the fat jar instead of extracting them (which prevents the problem described above):

![image](https://user-images.githubusercontent.com/5607145/139560650-5f2e90f9-e1c9-472f-8f06-545920e7f51c.png)

**Comment by michaeljclark125** [comment]
Thanks for your idea. However Geckodriver worked fine with selenium 3.141.59 but it doesn't work if using selenium 4.0. So I think there are some bugs from Geckodriver with Selenium 4.0.

I'm using netbeans & it seems doesn't have Library handling "Package required libraries into generated JAR".

Please advise me. Thanks.

**Comment by haumacher** [comment]
Seems to be a dependency problem. If I use 

```
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>4.0.0</version>
		</dependency>
```
I get the firefox and the chrome driver as dependency and packaging as fat jar produces the problem described above. However, if I only use 
```
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>4.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>4.0.0</version>
		</dependency>
```
which works for my setting, I only get the firefox driver and packaging as fat jar results in a runnable application.

**Comment by whimboo** [comment]
This is not an issue with geckodriver but with Selenium. To get a possible bug fixed please report an issue on the appropriate Selenium tracker, or NetBeans. Whatever fits better.
