### ISSUE TITLE
Gecko+Selenum not recognize space on downlaod folder

### ISSUE THREAD

**Issue by hildogjr** [mozilla/geckodriver#1955]
## System

* Version: 0.30.0 
* Platform: Linux Unbuntu 20.04 
* Firefox: 94.0 
* Selenium: 4.0.0 

I am raising the bug reported here https://github.com/SeleniumHQ/selenium/issues/9697. In this test case, Selenium + Geckdrive is not recognizing the `< space> ` on my download path definition and and keeping using my system default download folder.

## Testcase

```python
from selenium.webdriver import FirefoxOptions

DOWNLOAD_PATH = ... # Use some path with space and/or latin special characters (é/á/`/ç/ã).

opts = FirefoxOptions()
opts.set_preference('browser.download.dir', DOWNLOAD_PATH)
opts.set_preference('browser.download.lastDir', DOWNLOAD_PATH)
#browser = webdriver.Firefox(profile, options=opts, executable_path=gecko_driver_path)
browser = webdriver.Firefox(options=opts, executable_path=gecko_driver_path)
```

**Comment by whimboo** [comment]
Thank you for reporting! Would you mind attaching the generated `user.js`/`prefs.js` files to this issue? Therefore create a test that has a very long sleep or stop it with a debugger, and then check the output where geckodriver creates the profile. In the profile's root folder these files can be found.

I tried to reproduce on MacOS by using `"browser.download.dir": "/Users/whimboo/code/_test á"` but it looks all fine in Firefox.

Also which locales do you have set? You can get the details by running `locales` in your terminal.

**Comment by hildogjr** [comment]
My mistake: the error was present at Firefox<94.0 + gecko<0.30.

I am closing this and the respective https://github.com/SeleniumHQ/selenium/issues/9697 after test `<space> ` and latin characters.

**Comment by whimboo** [comment]
Thanks! Good to hear that this issue is no longer present.
