### ISSUE TITLE
Old geckodriver releases raise an exception (code 64) if started with unsupported --websocket-port argument

### ISSUE THREAD

**Issue by its-ogawa** [mozilla/geckodriver#1959]
## System

* Version: 0.26.0
* Platform: CentOS 6.9
* Firefox: 78.5.0esr
* Selenium: 4.0.0

## Testcase

geckodriver throws an exception (code 64).
What is the cause?

Also, is there a page with the code for the exception?

Any advice would be appreciated in advance.

```
# python scripts/like_sample.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "scripts/like_sample.py", line 21, in <module>
    session = InstaPy(username=USERNAME,
  File "/root/anaconda3/envs/ipy38/lib/python3.8/site-packages/instapy/instapy.py", line 327, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/root/anaconda3/envs/ipy38/lib/python3.8/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "/root/anaconda3/envs/ipy38/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 175, in __init__
    self.service.start()
  File "/root/anaconda3/envs/ipy38/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self.assert_process_still_running()
  File "/root/anaconda3/envs/ipy38/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/anaconda3/envs/ipy38/bin/geckodriver unexpectedly exited. Status code was: 64
```

**Comment by its-ogawa** [comment]
When I changed the version of INAPPROPRIATEgeckodriver to the latest 0.29.1 obtained from the following, the Status code became 1.
https://anaconda.org/conda-forge/geckodriver/files

What action do I need to take?

```
# wget https://anaconda.org/conda-forge/geckodriver/0.29.1/download/linux-64/geckodriver-0.29.1-h3146498_0.tar.bz2
... snip ...
# conda install geckodriver-0.29.1-h3146498_0.tar.bz2
... snip ...

# python scripts/like_sample.py
... snip ...
.../geckodriver unexpectedly exited. Status code was: 1
```

**Comment by whimboo** [comment]
Please update to geckodriver 0.30.0, and try again. Further please provide [trace logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) of geckodriver. It may also help to upgrade Firefox to at least the latest 91 ESR release.

**Comment by its-ogawa** [comment]
Before I knew it, 0.30.0 had been added!

I got 0.30.0 and confirmed that I don't get Exceptions.
Thank you very much.

The FireFox version is still the same.


Sadly, I got another CRITICAL error.
Maybe there is a problem with my account this time.



```
(ipy38) [root@<hostname> python]# python scripts/like_sample.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "/root/InstaPy" :]
InstaPy Version: 0.6.14
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-11-15 19:10:04] [<username>]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-11-15 19:10:04] [<username>]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-11-15 19:10:04] [<username>]  - Internet Connection Status: ok
INFO [2021-11-15 19:10:04] [<username>]  - Current IP is "2001:240:bb82:2300::1:1b" and it's from "Japan/JP"
INFO [2021-11-15 19:10:04] [<username>]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-11-15 19:10:04] [<username>]  - window.navigator.webdriver response: None
INFO [2021-11-15 19:10:04] [<username>]  - Hide Selenium Extension: ok
INFO [2021-11-15 19:10:07] [<username>]  - Cookie file not found, creating cookie...
........................................................................................................................
CRITICAL [2021-11-15 19:10:47] [<username>]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2021-11-15 19:10:48] [<username>]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 47.54 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-11-15 19:10:48] [<username>]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

**Comment by whimboo** [comment]
Again, without a trace log there is nothing that we can actually help with in regards of the currently provided details. So please attach one. Thanks.

**Comment by its-ogawa** [comment]
@whimboo 

I'm sorry.
I was thinking that the above log was it.

How can I get the trace log?

I am running the following command, but it does not output any results after the first line.

```
(ipy38) [root@<hostname> python]# geckodriver --log trace
1637022710856   geckodriver     INFO    Listening on 127.0.0.1:4444
```

**Comment by whimboo** [comment]
Sure, that will be all that's written to `stdout` as long as no client connects to geckodriver and tries to create a session. You want to modify your original code so it starts geckodriver with that option or `-vv`. Then you will get all the trace log entries correctly printed out.

**Comment by its-ogawa** [comment]
You will only get the following message
How can I get a log to track down the cause?

```
geckodriver -vv
1637051403715 geckodriver DEBUG Listening on 127.0.0.1:4444
```

**Comment by whimboo** [comment]
Is that with a client connecting to geckodriver? I doubt so. The client needs to send at least the new session command. You could use curl to do that. See the examples here:

https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone

**Comment by ernstki** [comment]
@its-ogawa You are probably running a `geckodriver` older than 0.30.0.

Here's how you can confirm:

```python
from selenium import webdriver
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = 'trace'

# source: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html#python
# via: https://github.com/mozilla/geckodriver/issues/1959
browser = webdriver.Firefox(options=opts)

browser.get('https://github.com')

assert 'GitHub' in browser.title
```

Look at the contents of `geckodriver.log` in the current working directory and if you see

```
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context
```

…then the version of `geckodriver` you have is too old for the version of Selenium you have.

I'm a bit frustrated by this, too, and I don't know what's the right answer. Nowhere in the Selenium documentation did I see anything stating "geckodriver 0.30.0 or higher is required," so I feel like the `selenium` Python library should be trying harder to accommodate the older `geckodrivers` that are out there, for example, [in MacPorts](https://ports.macports.org/port/geckodriver/). I mean the last release, 0.29.0, does not have the `--websocket-port` option, and it's not even _that_ old—January 2021.

As a workaround, try [downloading a binary](https://github.com/mozilla/geckodriver/releases) of 0.30.0 for your platform and make sure it shows up first in your shell's search path (putting it `~/bin` should be fine), then run your tests again.

**Comment by its-ogawa** [comment]
Binary download is a very good idea.
I've checked that too.
However, it is now possible to install 0.30.0 using anaconda as well.

**Comment by yacov-ma** [comment]
Hi,
I'm running on mac version Monterey 12.1

and getting the error as well.

attached trace log:
====== WebDriver manager ======
Driver [<>/geckodriver] found in cache
Traceback (most recent call last):
  File "<>", line 12, in <module>
      return webdriver.Firefox(executable_path=GeckoDriverManager(version='v0.30.0').install())
  File "<>/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    self.service.start()
  File "<>/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "<>/PycharmProjects/webDriverManagerDemo/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service <>/.wdm/drivers/geckodriver/macos/v0.30.0/geckodriver unexpectedly exited. Status code was: 64

**Comment by ernstki** [comment]
@yacov-ma Please follow the instructions [above](https://github.com/mozilla/geckodriver/issues/1959#issuecomment-1002382891) to have `geckodriver` write its own error log. From the contents of the `geckodriver.log` file, you should be able to determine why geckodriver "unexpectedly exited."

The status code returned to Selenium (64) may be the same, but the underlying problem could be different. Inspecting `geckodriver.log` is how you ascertain that.

**Comment by yacov-ma** [comment]
@ernstki Thank you for the quick reply.

This was actually the issue.
meanwhile, I'm using the workaround, any idea when they release a new version that fixes it?

**Comment by whimboo** [comment]
Thanks everyone for the feedback. As it has been manifested the problem here is not geckodriver but Selenium. As such you should create an issue on the Selenium repository instead, so that an option could be added to not always pass the `--websocket-port` argument. If that request gets denied you will have to use older releases of Selenium if testing with older geckodriver releases is really needed.

**Comment by ernstki** [comment]
> This was actually the issue. meanwhile, I'm using the workaround, any idea when they release a new version that fixes it?

@yacov-ma Unless there is some obstacle in your environment preventing you from doing so, I would recommend just downloading a newer `geckodriver` binary from the [releases page](https://github.com/mozilla/geckodriver/releases), and putting that somewhere in your search path.

This is beyond the scope of this issue, but if you are doing Selenium testing as one specific user, then `~/bin` is the obvious choice for Mac and Linux. On Windows, you can drop the binary in `C:\Windows\System32` for a quick-and-dirty solution. [This blog post](https://zwbetz.com/how-to-add-a-binary-to-your-path-on-macos-linux-windows/) explains the steps for adding an arbitrary directory to the search path on all three platforms.

Just on principle, I'd like to see Selenium "fixed" to support geckodriver <0.30, but it's not something I'm going to invest time in when there's a quick workaround that works fine for my testing environment.

**Comment by whimboo** [comment]
Note that the support for older geckodriver releases highly depend on the Selenium binding that you are using. In case for Python it works still fine for geckodriver releases before 0.30.0. So which bindings are you using?

**Comment by Rabelaiss** [comment]
I'm trying to connect to an existing Firefox instance using selenium in python.
Versions:
Firefox 100.0.1 (64 bit)
selenium 4.1.3
python 3.10.1
geckodriver 0.31.0 (it is contained in the python folder, i.e. it is in PATH)
First I open the Firefox instance in cmd with the command

```
"C:\Program Files\Mozilla Firefox\firefox.exe" --start-debugger-server --profile C:\FirefoxTEMP
```

Then on python I run the following commands

```
from selenium import webdriver

option = webdriver.FirefoxOptions()
options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
driver = webdriver.Firefox(options=options)
```

but get an error on the last line

```
~\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py in __init__(self, firefox_profile, firefox_binary, capabilities, proxy, executable_path, options, service_log_path, service_args, service, desired_capabilities, log_path, keep_alive)
    145         # options overrides capabilities
    146         if options:
--> 147             if options.binary:
    148                 self.binary = options.binary
    149             if options.profile:

AttributeError: 'Options' object has no attribute 'binary'
```

What am I doing wrong? Is there a solution? Thanks

**Comment by whimboo** [comment]
@Rabelaiss your question is not related to this issue at all, and which is also closed.

Also this question seems to be more related to Selenium than geckodriver. I would suggest to ask over there.

**Comment by Rabelaiss** [comment]
@whimboo Pardon me, I thought it was related since I was redirected here from another question #1980 where an user was trying to connect to an existing instance of Firefox.

**Comment by JianquanZhao** [comment]
> When I changed the version of INAPPROPRIATEgeckodriver to the latest 0.29.1 obtained from the following, the Status code became 1. https://anaconda.org/conda-forge/geckodriver/files
> 
> What action do I need to take?
> 
> ```
> # wget https://anaconda.org/conda-forge/geckodriver/0.29.1/download/linux-64/geckodriver-0.29.1-h3146498_0.tar.bz2
> ... snip ...
> # conda install geckodriver-0.29.1-h3146498_0.tar.bz2
> ... snip ...
> 
> # python scripts/like_sample.py
> ... snip ...
> .../geckodriver unexpectedly exited. Status code was: 1
> ```

specify the path of the geckodriver may fix this error in the follow way:
options = Options()
options.add_argument("--headless")
options.binary_location='./firefox/firefox'
options.add_argument('--headless')
driver = webdriver.Firefox(service=Service('./geckodriver'),options=options)

**Comment by whimboo** [comment]
As per our [support table for geckodriver](https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html) the 0.29.1 version can only be used up to Firefox 90. And this is most likely not what you want given that support for this Firefox version ended ages ago.

**Comment by its-ogawa** [comment]
@whimboo 
Thanks for letting me know about Supported platforms.
The reason I asked the question is because I wanted to use a Python library that required geckodriver as a WebDriver back then, 2 years ago.
I haven't tried it recently, but would like to try it with the latest geckodriver.
