### ISSUE TITLE
.get() method fails unnecessarily.

### ISSUE THREAD

**Issue by git-avinash** [mozilla/geckodriver#1961]
## System

* Version: 0.30.0
* Platform: Windows 10
* Firefox: 94.0.1
* Selenium: 3.141.0

## Testcase

When I fire a .get() request to get page selenium often raises a Timeout error. I have overwritten the timeout to 2m or 120s but the problem is often times the method won't even start loading the page. It would just sit for straight 2mins doing nothing and then raise a timeout error when it didn't even attempt to load up the page.

## Stacktrace

Traceback (most recent call last):
  File "c:\linkedin-worker-mobile-ip-auth\src\actions\make_request.py", line 19, in make_request
    browser.get(target_url)
  File "C:\Users\Administrator\.virtualenvs\linkedin-worker-mobile-ip-auth-_tVmaOWf\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Administrator\.virtualenvs\linkedin-worker-mobile-ip-auth-_tVmaOWf\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\.virtualenvs\linkedin-worker-mobile-ip-auth-_tVmaOWf\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: TimedPromise timed out after 120000 ms

## Trace-level log

1637070488054	webdriver::server	DEBUG	-> POST /session/17dae212-641a-42d4-a83b-c8a6857bda9d/url {"url": "https://www.linkedin.com/in/damian-marcin-groblewski-95b01b225/"}
1637070488057	Marionette	DEBUG	0 -> [0,78,"WebDriver:Navigate",{"url":"https://www.linkedin.com/in/damian-marcin-groblewski-95b01b225/"}]
1637070488060	Marionette	TRACE	[19] Received event beforeunload for https://www.linkedin.com/feed/
JavaScript error: , line 0: uncaught exception: Object
JavaScript error: , line 0: uncaught exception: Object
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
1637070608080	Marionette	DEBUG	0 <- [1,78,{"error":"timeout","message":"TimedPromise timed out after 120000 ms","stacktrace":"WebDriverError@chrome://remote/cont ... r@chrome://remote/content/shared/webdriver/Errors.jsm:450:5\nbail@chrome://remote/content/marionette/sync.js:230:19\n"},null]
1637070608079	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"timeout","message":"TimedPromise timed out after 120000 ms","stacktrace":"WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nTimeoutError@chrome://remote/content/shared/webdriver/Errors.jsm:450:5\nbail@chrome://remote/content/marionette/sync.js:230:19\n"}}

**Comment by whimboo** [comment]
Strange. There is no indication that the target page is getting loaded at all. To reproduce do you actually have to be logged in? Or does it also fail when not being logged in? Also do you have some specific Firefox preferences set or using just a default profile as created by geckodriver?

**Comment by git-avinash** [comment]
I was not able to reproduce the error actually as it happens randomly irrespective of the user is logged in or not. But when the error was noticed than most of the time, the user was logged in. And yes, I have custom prefs set, here's all the prefs I'm using:

    firefox_profile.set_preference("intl.accept_languages", "en-US")
    firefox_profile.set_preference("general.useragent.override", user_agent)
    firefox_profile.set_preference("media.volume_scale", "0.0")
    firefox_profile.set_preference("browser.aboutConfig.showWarning", False)
    firefox_profile.set_preference("dom.webdriver.enabled", False)
    firefox_profile.set_preference("dom.webnotifications.enabled", False)
    firefox_profile.set_preference("useAutomationExtension", False)
    firefox_profile.update_preferences()

**Comment by whimboo** [comment]
Hm, it would be good if you could create a minimized test for a not-logged in user, as best also by not using the Firefox profile as generated by Selenium. Instead use `from selenium.webdriver.firefox.options import Options` and `opts = Options(); opts.preferences.update()` to set the required preferences. It might be that Selenium sets some more. Maybe also try with the preference `fission.autostart` set to `false`.

**Comment by git-avinash** [comment]
from selenium import webdriver
  from selenium.webdriver import Firefox
  
  from defaults import extension_path, adbloacker_path, driver_path
  
  
  def make_browser(proxy_host: str, proxy_port: str, user_agent: str) -> Firefox:
      """
      Spawns a browser for scraping with proxies set
      """
  
      firefox_options = webdriver.FirefoxOptions()
      firefox_profile = webdriver.FirefoxProfile()
  
      firefox_options.log.level = "trace"
      firefox_options.headless = False
      firefox_options.add_argument("--no-sandbox")
      firefox_options.add_argument("--disable-dev-shm-usage")
  
      firefox_profile.set_preference("intl.accept_languages", "en-US")
      firefox_profile.set_preference("general.useragent.override", user_agent)
      firefox_profile.set_preference("media.volume_scale", "0.0")
      firefox_profile.set_preference("browser.aboutConfig.showWarning", False)
      firefox_profile.set_preference("dom.webdriver.enabled", False)
      firefox_profile.set_preference("dom.webnotifications.enabled", False)
      firefox_profile.set_preference("useAutomationExtension", False)
      firefox_profile.set_preference("fission.autostart", False)
      # firefox_profile.set_preference("general.platform.override", "iPhone")
      firefox_profile.update_preferences()
  
      PROXY = f"{proxy_host}:{proxy_port}"
  
      webdriver.DesiredCapabilities.FIREFOX['proxy'] = {
          "httpProxy": PROXY,
          # "ftpProxy": PROXY,
          "sslProxy": PROXY,
          "proxyType": "MANUAL",
  
      }
  
      browser = webdriver.Firefox(
          executable_path=driver_path,
          firefox_profile=firefox_profile,
          options=firefox_options
      )
  
      browser.install_addon(extension_path, temporary=True)
      browser.install_addon(adbloacker_path, temporary=True)
      browser.set_page_load_timeout(120)
  
      # Apple iPhone X:      375, 812
      # Apple iPhone XS Max: 414, 896
      # browser.set_window_size(414, 896)
      browser.maximize_window()
  
      return browser

Okay, I have added "fission.autostart" set to false and would start testing now, and this is the full code of how the browser is instantiated so please take a look at it and check if there's anything that might be a cause of that.

**Comment by whimboo** [comment]
I can see that there is a proxy in use. This might be a candidate why it's not working. Can you please test without that? Also please test by no installing any extension, and by removing one/both of the Firefox arguments for sandbox and shm usage. All of these settings could have an influence.

**Comment by git-avinash** [comment]
Hi, yes I have been doing some tests with different proxies and I think it's indeed the proxies. Seems to work well now!

**Comment by whimboo** [comment]
Great to hear that. In that case there is nothing left for us to do.
