### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'geckodriver'

### ISSUE THREAD

**Issue by jcraffael** [mozilla/geckodriver#1963]
## System

* Version: 0.30.0
* Platform: ubuntu 20.04
* Firefox: 87/89/91/94
* Selenium: 4.0.0

## Testcase
By using Selenium on Python to open firefox with the latest geckodriver I got this error:
`OSError: [Errno 8] Exec format error: 'geckodriver'`
I did download the geckodriver-v0.30.0-linux64.tar.gz asset and tried with different abovementioned versions of Firefox, but always got this same error. No trace log is produced probably because geckodriver has not started yet

**Comment by whimboo** [comment]
The problem here is not with firefox but with the geckodriver executable. What does `file geckodriver` tell you? I assume you have a 64bit system and not a 32bit?

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.
