### ISSUE TITLE
Selenium added --websocket-port unconditionally as argument - breaks geckodriver when used with --connect-existing

### ISSUE THREAD

**Issue by deadmike** [mozilla/geckodriver#1965]
selenium added one line which is always present when launching geckodriver that breaks geckodriver. they are stating it is correct to always have that present and y'all need to fix it... (see below for links and more narrative)

line 198: https://github.com/SeleniumHQ/selenium/blame/0f95b2788d72cea2b328197c01967921b69953e0/dotnet/src/webdriver/Firefox/FirefoxDriverService.cs

## System

* Version: latest
* Platform:  windows 
* Firefox: latest
* Selenium: latest 

## Testcase

FirefoxDriverService firefoxDriverService = FirefoxDriverService.CreateDefaultService(browserSettings.DriverLocation);
                    firefoxDriverService.HideCommandPromptWindow = false;
                    firefoxDriverService.Port = 0;
                    firefoxDriverService.BrowserCommunicationPort = 2828;
                    firefoxDriverService.Host = "127.0.0.1";
                    firefoxDriverService.ConnectToRunningBrowser = true;
                    var tmpDriver = new FirefoxDriver(firefoxDriverService, ffOptions);

geckodriver: The argument '--connect-existing' cannot be used with '--websocket-port'

========== ISSUE REPORTED TO SELENIUM ===============
https://github.com/SeleniumHQ/selenium/issues/10096
"This was added as part of #9817, **please report this to https://github.com/mozilla/geckodriver** as it would need to be sorted out by the GeckoDriver team, at least as a first step."

https://github.com/SeleniumHQ/selenium/issues/9817
=================== OFFENDING CODE ===========================
the below line was added sept 28 with no conditions to all launching of geckdriver and selenium team is saying it will not be conditionally added, that it will ALWAYS be present and y'all are not up to the BiDi spec?

Line 198: https://github.com/SeleniumHQ/selenium/blame/0f95b2788d72cea2b328197c01967921b69953e0/dotnet/src/webdriver/Firefox/FirefoxDriverService.cs

**[dotnet] Add --websocket-port command line argument for geckodriver
argsBuilder.Append(string.Format(CultureInfo.InvariantCulture, " --websocket-port {0}", PortUtilities.FindFreePort()));**

**Comment by whimboo** [comment]
As mentioned on the Selenium issue https://github.com/SeleniumHQ/selenium/issues/10096#issuecomment-994655300 the usage of both arguments is not allowed and as such should not be used. Lets favor to continue the discussion over on the Selenium issue. 

Thanks for letting us know!
