### ISSUE TITLE
Wrong link: downloaded geckodriver-v0.30.0-linux64.tar.gz got version 0.29.1

### ISSUE THREAD

**Issue by hemiaomiao89** [mozilla/geckodriver#1976]
## System

* Version: 0.30.0
* Platform: Ubuntu 16.04
* Firefox: 88.0
* Selenium: 4.1.0

## Testcase

geckodriver downloaded from https://github.com/mozilla/geckodriver/releases link geckodriver-v0.30.0-linux64.tar.gz
Version checked by `geckodriver --version`
```
geckodriver 0.29.1 (970ef713fe58 2021-04-08 23:34 +0200)

The source code of this program is available from
testing/geckodriver in https://hg.mozilla.org/mozilla-central.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```
I've also tried link 
- geckodriver-v0.30.0-linux32.tar.gz: actually is version 0.29.1
- geckodriver-v0.30.0-macos.tar.gz: actually is version 0.29.1
- geckodriver-v0.30.0-win64.zip: version 0.30.0

**Comment by whimboo** [comment]
You might do something wrong when trying to run the right binary. It looks all fine to me. Here an example for MacOS:

```
➜ wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz
[..]
Saving to: ‘geckodriver-v0.30.0-macos.tar.gz’
➜ tar xvf geckodriver-v0.30.0-macos.tar.gz
x geckodriver
➜ ./geckodriver --version
geckodriver 0.30.0 (d372710b98a6 2021-09-16 10:29 +0300)
```

Check that:
1) The right file has been downloaded (compare the size and md5 hash if available)
2) The right binary is started and not another geckodriver that is in the PATH
