### ISSUE TITLE
ARM64 builds

### ISSUE THREAD

**Issue by lazzurs** [mozilla/geckodriver#1978]
## System

* Version:0.30.0
* Platform: Linux/macOS
* Firefox: any
* Selenium: any

## Problem

Could we please have arm64 builds for both Linux and macOS please?

**Comment by whimboo** [comment]
With the geckodriver release 0.30.0 we started to provide ARM64 builds. See the [geckodriver-v0.30.0-macos-aarch64.tar.gz](https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos-aarch64.tar.gz) asset.

As such this issue remains for Linux which is already covered in issue #1956. Marking issue as dupe.
