### ISSUE TITLE
close() & quit() commands dont work in Firefox Browser Version 48.0

### ISSUE THREAD

**Issue by Easyman123** [mozilla/geckodriver#198]
https://github.com/SeleniumHQ/selenium/issues/2667

OS: Windows 7 Enterprise 64 Bit

Selenium Version: selenium-server-standalone-3.0.0-beta2.jar Package

Browser: Firefox Browser Version 48.0

Geckodriver Version: geckodriver-v0.10.0-win64

Expected in Firefox Browser:
The driver.close() command should close the current browser window on which the focus is set.
The driver.quit() command should close all opened browser windows and end the whole WebDriver session.

What happens:
When I run my test in Selenium WebDriver using Java everything works fine so far. But with execution of driver.quit() command in the @After hook I get the following error:

[Child 12868] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2046

One second later the firefox browser closes as wished but directly followed by UnreachableBrowserException with below stacktrace and the test results in a fail:

Failure in after hook:StepDefinitionsBrowserCombinationTestWithHooks.tearDownFirefox() Message: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died. Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700' System info: host: 'PC45770', ip: '141.77.197.75', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91' Driver info: driver.version: RemoteWebDriver Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160817112116, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}] Session ID: fef2d090-008f-4d43-ba5b-6ec66cae2aab at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:706) at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:531) at cucumber.features.StepDefinitionsBrowserCombinationTestWithHooks.tearDownFirefox(StepDefinitionsBrowserCombinationTestWithHooks.java:68) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at cucumber.runtime.Utils$1.call(Utils.java:37) at cucumber.runtime.Timeout.timeout(Timeout.java:13) at cucumber.runtime.Utils.invoke(Utils.java:31) at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60) at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223) at cucumber.runtime.Runtime.runHooks(Runtime.java:211) at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:205) at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46) at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165) at cucumber.runtime.Runtime.run(Runtime.java:121) at cucumber.api.cli.Main.run(Main.java:36) at cucumber.api.cli.Main.main(Main.java:18) Caused by: java.lang.IllegalStateException: UnixUtils may not be used on Windows at org.openqa.selenium.os.ProcessUtils.getProcessId(ProcessUtils.java:188) at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.getPID(UnixProcess.java:222) at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$300(UnixProcess.java:201) at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:132) at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155) at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:196) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:649) ... 19 more

When I use the close() command instead nothing happens as if Selenium would ignore this code line.
That means that currently I have to manually close all browser windows after every test execution to not to receive UnreachableBrowserException which ends up in a failed test.
With IE and Google Chrome Browser I dont experience the issue described as above.

Steps to reproduce:
Just try to run a simple test (like open the browser, wait a few seconds and close the browser again) against Firefox Browser Version 48.0 using Selenium beta2 Version and geckodriver. Try out both - close() and quit() - methods.

For Example:
`package cucumber.features;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import cucumber.api.java.Before;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;

public class StepDefinitionsTestQuitAndClose {

	WebDriver driver = null;
	
	@Before
	public void setUp(){
		System.setProperty("webdriver.gecko.driver", "<location of geckodriver.exe>");
	}
	@Given("^I open the site$")
	public void i_open_the_site() throws Throwable {
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.get("https://www.google.de/#gws_rd=ssl");
	}
	@When("^I wait for few seconds$")
	public void i_wait_for_few_seconds() throws Throwable {
		Thread.sleep(5000);
	}
	@Then("^I close the site$")
	public void i_close_the_site() throws Throwable {
		if(driver != null)
			driver.quit();
	}
}`

Thanks in advance!

**Comment by Easyman123** [comment]
Quick Update:

I downgraded firefox to version 47.0 and still had the same error. Now I have tried version 46.0 and everything passed without any problems.
As you need the geckodriver to run tests in firefox browser since version 47.0+ I suppose that maybe there is something wrong with the geckodriver.

**Comment by jgraham** [comment]
The latest version is 0.10.0. You probably want to use that with the latest Selenium beta.

**Comment by andreastt** [comment]
This could be related to https://github.com/mozilla/geckodriver/issues/172, but it’s hard to tell from the information available here.

**Comment by saladisathish** [comment]
This is reproducible in Firefox 48.0.2 & Selenium-java-3.0.0-beta2. driver.close() doesnt close the firefox.  Here is the code to reproduce:
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TesterFile {

public static WebDriver wd;
public static void main(String[] args) {

    System.setProperty("webdriver.gecko.driver","C:\\Users\\<User>\\tools\\geckodriver.exe");
    wd = new FirefoxDriver();
    wd.get("http://www.google.com");

    wd.close();
}
}

**Comment by Easyman123** [comment]
@jgraham:
I probably described that I'm using the latest geckodriver version (0.10.0) and the latest selenium version (3.0.0-beta2). This is actually why I opened this issue - because driver.quit() doesnt work in geckodriver 0.10.0 with selenium server 3.0.0-beta2 but works when using geckodriver version 0.9.0 with selenium server standalone 3.0.0-beta1!
I just tested and tried out the driver.quit() command on different versions and therefore I used geckodriver version 0.9.0 and selenium 3.0.0-beta1 instead of geckodriver version 0.10.0 and selenium 3.0.0-beta2.
And for this reasion your above answer neither provides a solution nor solves this problem. So why did you close the issue?

Are there any workarounds?

**Comment by Easyman123** [comment]
**Reproducible Test Scripts**


### UnreachableBrowserException: Error communicating with the remote browser. It may have died.

`import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Test {

	private static WebDriver driver = null;
	
	public static void main(String[] args){
		System.setProperty("webdriver.gecko.driver", "<location of geckodriver.exe>");
		
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		driver.get("https://www.google.de/#gws_rd=ssl");
		
		if(driver != null)
			driver.quit();
	}

}`


### Nothing happens: (Browser stays opened)

`import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Test {

	private static WebDriver driver = null;
	
	public static void main(String[] args){
		System.setProperty("webdriver.gecko.driver", "<location of geckodriver.exe>");
		
		driver = new FirefoxDriver();
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
		driver.get("https://www.google.de/#gws_rd=ssl");
		
		if(driver != null)
			driver.close();
	}

}`

**Comment by jajavi** [comment]
I have exactly the same problem  with geckodriver version (0.10.0) and the latest selenium version (3.0.0-beta3)

**Comment by andreastt** [comment]
I’m going to lock this issue because it’s not productive.
