### ISSUE TITLE
Cannot set proxy on geckodriver with Java

### ISSUE THREAD

**Issue by NA-Dev** [mozilla/geckodriver#1983]
I have tried every way of setting proxies on the internet, and I can't get any of them to work. No errors are shown. How am I supposed to set the proxy settings? Works fine in chromedriver with `--proxy-server=`.

## System

* Geckodriver: 0.30.0
* Platform: Linux and Windows
* Firefox: 91.4.0 (Linux) and 96.0.3 (Windows)
* Selenium: Java Selenium 3.141.59

## Testcase
```
FirefoxOptions options = new FirefoxOptions();
options.addArguments("--width=1920");
options.addArguments("--height=1080");
System.setProperty("webdriver.gecko.driver", browserDriver);

ProfilesIni profileIni = new ProfilesIni();
FirefoxProfile profile = profileIni.getProfile("default");

// Tried this
Proxy proxy = new Proxy();
proxy.setHttpProxy("p.webshare.io:9999");
options.setCapability("proxy", proxy);

// Also tried this
profile.setPreference("network.proxy.type", 1);
profile.setPreference("network.proxy.http", "p.webshare.io");
profile.setPreference("network.proxy.http_port", 9999);

options.setProfile(profile);
driver = new FirefoxDriver(options);
```

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Note that proxies have to be set via capabilities and not set as preferences.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
As the log shows the proxy settings are not applied via the [`proxy` capabilities](https://w3c.github.io/webdriver/#proxy). But nevertheless the log doesn't show a problem with navigation here. So what's not working for this specific test run?

**Comment by NA-Dev** [comment]
I put in the code that is supposed to set the proxy capabilities as far as I know. If that is not setting them, then how do I do it?
```
Proxy proxy = new Proxy();
proxy.setHttpProxy("p.webshare.io:9999");
options.setCapability("proxy", proxy);
```

**Comment by whimboo** [comment]
I just saw that you are using Selenium 3.x. Could you maybe check if Selenium 4 is showing the same behavior? I would be interested in a trace log too. If the proxy is still set via Firefox preferences I would file an upstream Selenium issue.

Beside the above topic please also follow up on my question from the last comment. Thanks.

**Comment by NA-Dev** [comment]
I can't update to Selenium 4 at this time. It requires code changes that would need to be figured out. I have answered all your questions. The issue with this test run is that I cannot get the driver to use a proxy address. Do you have a solution for Selenium 3 or not?

**Comment by whimboo** [comment]
As I have said in my two last comments I cannot see an issue with the page load for google.com in your log:

```
1643649937121	Marionette	DEBUG	0 -> [0,14,"WebDriver:Navigate",{"url":"https://www.google.com"}]
1643649937125	Marionette	TRACE	[19] Received event beforeunload for about:blank
1643649937401	Marionette	TRACE	[19] Received event pagehide for about:blank
1643649937659	Marionette	TRACE	[19] Received event DOMContentLoaded for https://www.google.com/
1643649937813	Marionette	TRACE	[19] Received event pageshow for https://www.google.com/
```

Marionette navigates and google.com gets loaded just fine which the `pageshow` event indicates. Maybe the wrong log has been attached?

**Comment by NA-Dev** [comment]
The page is loading fine, that is not the issue I am writing about. The issue is that it loads with my normal IP address, and NOT with the proxy IP address I set. How can I get the proxy address to be used? I set it to capabilities, but it doesn't work.

**Comment by whimboo** [comment]
Oh, I see. So I would suggest to add a long sleep or break point to your test and then when Firefox is open go to `about:config` (type it in the urlbar). Then accept the warning and filter all the preferences for `network.proxy`. Do you see the proxy values added? I assume not and something is wrong with the profile generation in your selenium binding.

**Comment by NA-Dev** [comment]
I have not tried this with Selenium 4, and still proxy is never set. I tried every method I can find online, none of them work.

**Comment by whimboo** [comment]
@NA-Dev so my suggestion helped to get the proxy correctly set?

**Comment by NA-Dev** [comment]
Not really. I gave up on Selenium 3 and eventually upgraded to Selenium 4. Works fine with Selenium 4. What I needed help with was getting it to work on Selenium 3.
