### ISSUE TITLE
Bad CPU type in executable / UsageError: Line magic function `%` not found.

### ISSUE THREAD

**Issue by olyamarch** [mozilla/geckodriver#1984]
## System

* Version: 0.30.0
* Platform: macOS/Big Sur 11.2.3
* Firefox: 96.0.3
* Selenium: pip install selenium (installed today)

## Testcase

any

## Stacktrace

```
from selenium import webdriver
browser = webdriver.Firefox(executable_path="/Users/user/Downloads/geckodriver_2") 
browser.get("https://google.com/")
```

Generates a mistake: 

OSError: [Errno 86] Bad CPU type in executable: '/Users/user/Downloads/geckodriver_2'

Tried the following as was proposed by mazilla:

`% xattr -r -d com.apple.quarantine geckodriver
`

Got the mistake:

UsageError: Line magic function `%` not found.

What should I try?

Thank you

**Comment by whimboo** [comment]
`Bad CPU type` means that you may have downloaded the wrong binary for Mac. Do you have an Intel CPU and maybe downloaded the aarch64 archive?

**Comment by whimboo** [comment]
No reply from reporter. Closing the issue.

**Comment by mab66** [comment]
> `Bad CPU type` means that you may have downloaded the wrong binary for Mac. Do you have an Intel CPU and maybe downloaded the aarch64 archive?

Hi Whimboo, that's it! Although I have a 64 bit os I needed to download macOS version instead of aarch64. Thank you.
