### ISSUE TITLE
Actions.moveToElement() is not working correctly in FireFox Driver, when target element is inside Shadow DOM.

### ISSUE THREAD

**Issue by MaheshkumarPalled** [mozilla/geckodriver#1986]
## System

* Version: 30
* Platform: macOSMonterey, version 12.2
* Firefox: FireFox 91.5.0esr (64-bit)
* Selenium: Java 3.14.0, 4.1.1, 4.1.2

## Testcase

I'm trying to perform mouse hover on a webElement which is inside an iFrame of Shadow DOM, so that it expands the list and then I continue by choosing the displayed option.

Below code is working fine with Chrome browser.

How can we reproduce the issue?
public void mouseOverOnElement(WebElement targetElement) {
Actions builder = new Actions(webDriver);
builder.moveToElement(targetElement).perform(); // This didn't work in FireFox
builder.moveToElement(targetElement).build().perform(); // This didn't work in FireFox

//Also tried to achieve it with Java script executor. 

JavaScriptExecutor js = (JavascriptExecutor) webDriver;
js.executeScript("arguments[0].onmouseover", targetElement); // Didn't work,
js.executeScript("arguments[0].scrollIntoView(true);", targetElement); // Didn't work.
}

Sample html. here I'm trying to hover on "dropdown_sample" field.

<div id="ra-shado-root">
    #shadow-root (open)
       <iframe id = "test_iframe">
          #document
             <head />
             <body>
              <div id="drop-down-test">
                    dropdown_Sample
              </div>
            </body>
       </iframe>
</div>

## Stacktrace

There is no error but mouse hover is happening on unexpected element. 

## Trace-level log

NA

Note: 
Initially I thought it's the selenium issue but seems something specific to geckdriver.
Issue created against selenium : https://github.com/SeleniumHQ/selenium/issues/10327

**Comment by whimboo** [comment]
At the time when this issue was filed there was no support for finding elements within a shadow DOM. With [geckodriver 0.33.0](https://github.com/mozilla/geckodriver/releases/tag/v0.33.0) and Firefox 113.0 this feature got added. 

I'm closing this issue given that it should work as expected now. If it doesn't please let us know and we can reopen. Thanks.
