### ISSUE TITLE
0.30.0: this is not win32 application

### ISSUE THREAD

**Issue by JeanPaulLucien** [mozilla/geckodriver#1988]
## System

* Version: 0.30
* Platform: Windows XP
* Firefox: not used
* Selenium: not installed

## Testcase
1. Download archive from GH.
2. Unpack archive and start exe.

**Comment by kingthorin** [comment]
Per: https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

> Since Windows XP support in Firefox was dropped with Firefox 53, we do not support this platform.

**Comment by whimboo** [comment]
This is true but shouldn't be the underlying problem. Nevertheless I don't think that we will get an answer from the reporter and that this is an actual valid issue. As such closing as invalid.

**Comment by JeanPaulLucien** [comment]
@whimboo 32 bit
I even can't try how it will bug on my browser version.

Was there support for Firefox below 52?

**Comment by JeanPaulLucien** [comment]
geckodriver
Proxy for using W3C WebDriver-compatible clients to interact with Gecko-based browsers.
My browser is Gecko-Based, based on Firefox.

**Comment by whimboo** [comment]
Please see https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

The oldest release of Firefox that is supported by geckodriver 0.30.0 is 78ESR.
