### ISSUE TITLE
Include date of the release date of the gecko drivers

### ISSUE THREAD

**Issue by sherrif10** [mozilla/geckodriver#1989]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## Testcase

Forexample i find it more accurate when  you include date of the driver that it have been released such that it can give a user a confident to which driver to  download for use. this can also be included in the readme.

**Comment by whimboo** [comment]
@sherrif10 could you please explain which missing feature you are referring to here? Is it about the release notes (CHANGES.md) or release page which both have the date of release set, some command line argument, or something totally different? Thanks.

**Comment by sherrif10** [comment]
Thaanks @whimboo . its about adding release dates in release nots. probably in readme file

**Comment by whimboo** [comment]
Ok, so the readme file will not contain details for each and every release. Therefore we have the [CHANGES.md](https://github.com/mozilla/geckodriver/blob/release/CHANGES.md) file which tracks all the details. Further also https://github.com/mozilla/geckodriver/releases contains each release and the appropriate date.

**Comment by sherrif10** [comment]
thanks for the response.
