### ISSUE TITLE
Unable to setup Firefox Browser Privacy using non-deprecated methods options and set_preference

### ISSUE THREAD

**Issue by dlarocheRolle** [mozilla/geckodriver#1991]
## System

* Version: geckodriver version 0.30
* Platform: Ubuntu 20.04.3
* Firefox: 97.0
* Selenium: 4.1.0

## Testcase
I run the following code, and i am checking the FireFox > Settings >Privacy & Security > Browser Privacy

The value of Browser Privacy remains at 'custom' instead of being changed to 'standard' (same behavior if i try other options)

from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options

import time
import os

# Create proxy
from browsermobproxy import Server
server = Server(path="/home/administrator/browsermob-proxy-2.1.4-bin/browsermob-proxy-2.1.4/bin/browsermob-proxy")
server.start()
proxy = server.create_proxy()

# Create Options and add proxy
options=Options()
options.use_firefox = True 
# commenting the line below does not remove the issue
options.proxy= proxy.selenium_proxy()

# set preferences - 
options.set_preference('moz:browser.contentblocking.category', 'standard')
# options.set_preference('browser.contentblocking.category', 'standard') - not working as well

driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()),options=options)

driver.get("https://www.google.com/")

print ("Options")
print(options)
print ("---------------------------------------------------------------------------------------------------------")
print ("Driver Capability")
print(driver.capabilities) 
print ("---------------------------------------------------------------------------------------------------------")

server.stop()
# following line is commented to check the profile of the Firefox Browser that is open by webDriver
# driver.quit()

## Stacktrace

===== WebDriver manager ======
Current firefox version is 97.0
Get LATEST geckodriver version for 97.0 firefox
Driver [/home/administrator/.wdm/drivers/geckodriver/linux64/v0.30.0/geckodriver] found in cache
Options
<selenium.webdriver.firefox.options.Options object at 0x7f06a1b84850>
---------------------------------------------------------------------------------------------------------
Driver Capability
{'acceptInsecureCerts': True, 'browserName': 'firefox', 'browserVersion': '97.0', 'moz:accessibilityChecks': False, 'moz:buildID': '20220202182137', 'moz:debuggerAddress': 'localhost:53623', 'moz:geckodriverVersion': '0.30.0', 'moz:headless': False, 'moz:processID': 8585, 'moz:profile': '/tmp/rust_mozprofileeOwGS7', 'moz:shutdownTimeout': 60000, 'moz:useNonSpecCompliantPointerOrigin': False, 'moz:webdriverClick': True, 'pageLoadStrategy': 'normal', 'platformName': 'linux', 'platformVersion': '5.13.0-30-generic', 'proxy': {'httpProxy': 'localhost:8097', 'proxyType': 'manual', 'sslProxy': 'localhost:8097'}, 'setWindowRect': True, 'strictFileInteractability': False, 'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000}, 'unhandledPromptBehavior': 'dismiss and notify'}
---------------------------------------------------------------------------------------------------------

**Comment by whimboo** [comment]
Note that you are trying to set a preference by actually specifying a vendor specific capability. This won't work. Please check https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions#prefs in how to correctly set preferences.
