### ISSUE TITLE
Release Plan?

### ISSUE THREAD

**Issue by mohe2015** [mozilla/geckodriver#1994]
## System

* Version: 0.30.0
* Platform: Linux (NixOS unstable)
* Firefox: 97.0.2
* Selenium: npm  "selenium-webdriver": "^4.1.1"

## Question

Hello. I would like to know if there is any release schedule publicly available or if there is a release scheduled?

From https://bugzilla.mozilla.org/show_bug.cgi?id=1489490#c10 I understand that a new release would be required to get the bugfix for getting the shadow root.

Kind regards
Moritz

**Comment by whimboo** [comment]
We are handling the 0.31.0 release via https://bugzilla.mozilla.org/show_bug.cgi?id=1723202.
