### ISSUE TITLE
Marionette changes port listening

### ISSUE THREAD

**Issue by badr-elmazaz** [mozilla/geckodriver#1995]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

## Testcase
I am calling a function that generate a new browser session if it doesnt exist before the function returns I save the command executor url and the session id, the problem is when I try to reconnect to that address it refuses the connection, I checked the gecko logs and I noticed that when the function is returned it changes the port listening and the connection to the old port fails.

Here the gecko logs as you can see the port changes automatically from 51632 to 51641:
## Stacktrace

1646865476715   geckodriver INFO    Listening on 127.0.0.1:51632
1646865481639   mozrunner::runner   INFO    Running command: "C:\\Tor Browser\\Browser\\firefox.exe" "--marionette" "--remote-debugging-port" "51633" "-no-remote" "-profile" "C:\\Users\\user~1\\AppData\\Local\\Temp\\rust_mozprofilelqkMuc"
console.log: "TorSettings: loadFromPrefs()"
console.log: "TorConnect: Init"
console.log: "TorConnect: observed profile-after-change"
console.log: "TorConnect: observing topic 'TorBootstrapStatus'"
console.log: "TorConnect: observing topic 'TorBootstrapError'"
console.log: "TorConnect: observing topic 'TorProcessExited'"
console.log: "TorConnect: observing topic 'TorLogHasWarnOrErr'"
console.log: "TorConnect: observing topic 'torsettings:ready'"
console.log: "TorSettings: observed profile-after-change"
1646865482265   Marionette  INFO    Marionette enabled
console.log: "TorConnect: will load after bootstrap => [about:blank]"
console.error: "Could not load engine blockchair-onion@search.mozilla.org: Error: Extension is invalid"
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 161: TypeError: Cc[aContract] is undefined
DevTools listening on ws://localhost:51633/devtools/browser/cef1d78c-1e54-43d6-8629-ab6bd5d77a41
1646865485196   Marionette  INFO    Listening on port 51641
JavaScript error: chrome://torbutton/content/tor-circuit-display.js, line 478: TypeError: myController is null
JavaScript error: resource://torbutton/modules/tor-control-port.js, line 81: NS_ERROR_CONNECTION_REFUSED: Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIScriptableInputStream.available]
JavaScript error: resource://torbutton/modules/tor-control-port.js, line 117: NS_ERROR_CONNECTION_REFUSED: Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIOutputStream.write]
1646865485374   RemoteAgent WARN    TLS certificate errors will be ignored for this session

###!!! [Child][MessageChannel] Error: (msgtype=0x390097,name=PContent::Msg_InitBackground) Channel closing: too late to send/recv, messages will be lost

JavaScript error: resource://gre/modules/PromiseWorker.jsm, line 106: Error: Could not get children of file(C:\Users\user\AppData\Local\Temp\rust_mozprofilelqkMuc\thumbnails) because it does not exist

**Comment by whimboo** [comment]
You are confused by geckodriver and Marionette. While geckodriver is the proxy that understands the [WebDriver wire protocol](https://w3c.github.io/webdriver/) it communicates internally with Marionette which is built into Firefox. As such important for you is the port geckodriver is listening on, and that doesn't change unless you have specified `0` for a system allocated port. But even then the port will not change for the current geckodriver process.

**Comment by whimboo** [comment]
If there is still something that is not working please give us exact steps and attach [a trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html) from geckodriver.
