### ISSUE TITLE
NoSuchWindowException: Browsing context has been discarded

### ISSUE THREAD

**Issue by kretschmannj** [mozilla/geckodriver#1997]
I've recently started seeing this intermittent error when running Nightwatch (Selenium) tests from Firefox ...

```
   Response 500 POST /wd/hub/session/a4830cbe-1c5b-4605-af9d-0001de9d92ef/execute (13ms)
   {
     sessionId: null,
     state: 'no such window',
     class: 'org.openqa.selenium.remote.Response',
     value: {
       additionalInformation: '\nDriver info: driver.version: unknown',
       localizedMessage: 'Browsing context has been discarded\n' +
         "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
         "System info: host: 'WS000001QGWR93L', ip: '10.17.245.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'\n" +
         'Driver info: driver.version: unknown',
       systemInformation: "System info: host: 'WS000001QGWR93L', ip: '10.17.245.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'",        
       supportUrl: null,
       cause: null,
       suppressed: [],
       message: 'Browsing context has been discarded\n' +
         "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
         "System info: host: 'WS000001QGWR93L', ip: '10.17.245.216', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'\n" +
         'Driver info: driver.version: unknown',
       class: 'org.openqa.selenium.NoSuchWindowException',
       buildInformation: null
     },
     status: 23
}
```

I'm using Mozilla Firefox 98.0 which was released on March 8th, just about the time I started seeing this issue.

Similar (possibly related) issue posted back in 2019 ...
[https://github.com/mozilla/geckodriver/issues/1553](https://github.com/mozilla/geckodriver/issues/1553)

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? 

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by kretschmannj** [comment]
I just opened an issue on the Nightwatch GitHub project as I think I've narrowed this down to some sort of issue with a package called nightwatch-xhr.  For reference, ... [https://github.com/nightwatchjs/nightwatch/issues/3112](https://github.com/nightwatchjs/nightwatch/issues/3112)

**Comment by whimboo** [comment]
Thanks for the information. Given that this issue seems to be related to a different product lets close this issue for now. Feel free to reopen if it's not the case.
