### ISSUE TITLE
Getting the value of a boolean attribute should return true or null

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#20]
1441559328414   Marionette  DEBUG   conn0 -> ({"name":"getElementAttribute","parameters":{"id":"7f366da6-405f-4ae6-aae6-0d86e2a6e781","name":"disabled"},"sessionId":"cf570ea6-4056-49b9-ab38-0e63a471d824","to":"0"})
1441559328418   Marionette  DEBUG   conn0 client <- ({"from":"0","value":"false","status":"success","sessionId":"cf570ea6-4056-49b9-ab38-0e63a471d824"})
ERROR:webdriver::server: Returning status Ok
ERROR:webdriver::server: Returning body {"value":"false"}

**Comment by jgraham** [comment]
@andreastt Marionette issue? This seems like a terrifying requirement because without access to the actual idl I don't think it's possible to tell if an attribute is boolean or not (without setting the value). So an implementation would have to keep a continually-maintained list of such attributes.

**Comment by jgraham** [comment]
Maybe it's possible to implement if you know the DOM attribute that reflects the content attribute since you can check if it returns `true` when a value is set. But again I don't think that's something you can know in general without an explicit list.

**Comment by andreastt** [comment]
I’m going to respond to this in more depth later, but I just wanted to point out there’s a lengthy discussion about this over in w3c/webdriver#187.

**Comment by jgraham** [comment]
Did this get fixed?

**Comment by andreastt** [comment]
This did get fixed.
