### ISSUE TITLE
Exception: The path to the driver executable must be set by the webdriver.gecko.driver system property

### ISSUE THREAD

**Issue by ileshmistry** [mozilla/geckodriver#200]
Hello

I am new to NightWatch.JS and trying to get the basic working. However I am getting the following issue, can you help me please?

Starting selenium server... started - PID:  19532

[Google] Test Suite
=======================

Running:  Demo test Google

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ state: 'unhandled error',
  sessionId: null,
  hCode: 25418301,
  value:
   { localizedMessage: 'The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases',
     cause: null,
     suppressed: [],
     message: 'The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases',
     hCode: 27395628,
     class: 'java.lang.IllegalStateException',
     screen: null },
  class: 'org.openqa.selenium.remote.Response',
  status: 13 }

I have downloaded the webdrivers, but not sure where to set them for this to be picked up?

Thanks
Ilesh

**Comment by andreastt** [comment]
This is a Selenium error message. It says you need to set the `webdriver.gecko.driver` Java VM property. I believe you do this by passing the `-D` flag to the _java_ binary:

    java -Dwebdriver.gecko.driver=/path/to/driver …

**Comment by Tuman829** [comment]
@andreastt i am running into this issue while using the [Seleniumhq jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/Seleniumhq+Plugin). Any thoughts on how to configure properly?

**Comment by trotzig** [comment]
@Tuman829 It looks like you or someone else asked the same question in the issue tracker for that project: https://issues.jenkins-ci.org/browse/JENKINS-40459

It might be good to have that bit of context here as well. I don't expect you'll get any answer from folks in this project since this is not a bug in geckodriver (afaict).

**Comment by Tuman829** [comment]
@trotzig  that is me

**Comment by andreastt** [comment]
This is completely out of context for geckodriver. Locking this conversation.
