### ISSUE TITLE
FreeBSD Release

### ISSUE THREAD

**Issue by schrodyn** [mozilla/geckodriver#2000]
Hi,

Can you please include FreeBSD in your releases.

Thanks.

**Comment by whimboo** [comment]
Thank you for filing this issue. Regarding your request I can say that we are not providing packages for platform specific package managers. The integration work relies on the appropriate distribution teams. 

Note that soon we will at least support `cargo install geckodriver` in case that would be helpful to you (but would still require the Rust tool chain to be installed).

**Comment by schrodyn** [comment]
Hi,

Sorry, maybe I didn't explain properly. On the releases page you have binaries built for Windows, Linux and macos. You do not ship FreeBSD binaries. Can you please start to build FreeBSD ELF binaries and include them in your releases?

**Comment by whimboo** [comment]
Ah I see. So we do not have infrastructure to generate these kind of builds and you are the first one who requested this. It would be very low on our list and probably never get enabled. As such I'm sorry but you could ask FreeBSD maintainers for a package, install the next upcoming release via `cargo install`, or build it on your own.

**Comment by schrodyn** [comment]
Thanks, Whimboo. I've been building it myself without issue, just FYI. I will hit up the maintainer to ask that they keep the pkg up to date. Many thanks.

**Comment by swannie-eire** [comment]
thanks "cargo install geckodriver" worked on FreeBSD jail
