### ISSUE TITLE
Is it possible to extend the creation of firefoxdriver with desired capabilities and firefox profile options?

### ISSUE THREAD

**Issue by swathikvsr** [mozilla/geckodriver#201]
I have a requirement to create firefox driver using both desired capabilities and firefox profile options right now the constructor doesn't have option that accepts both desired capabilities and firefox profile  is it possible to extend the functionality?

**Comment by andreastt** [comment]
See the [README](https://github.com/mozilla/geckodriver/blob/9f73170ca476a22926b5af3532fb709cc62fbb81/README.md#firefox-capabilities). Note that the capabilities are changing in the next release following 0.10.0 to match what chromedriver more closely.
