### ISSUE TITLE
Intermittent `TimedPromise timed out after 300000 ms` on `click()`

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/geckodriver#2019]
## System

* Version: v0.31.0
* Platform: Windows 10
* Firefox: Firefox 100.0 (but also noticed with previous versions - 99.0, 98.0)
* Selenium: 4.1.5

## Testcase

On https://addons.mozilla.org/en-US/firefox/, click on the "Themes" link in the header menu. The element is located in this `html` bit:
```
<ul class="SectionLinks Header-SectionLinks"><li><a class="SectionLinks-link SectionLinks-link-extension" href="/en-US/firefox/extensions/">Extensions</a></li><li><a class="SectionLinks-link SectionLinks-link-theme" href="/en-US/firefox/themes/">Themes</a>
```

## Stacktrace
[stacktrace.zip](https://github.com/mozilla/geckodriver/files/8685089/stacktrace.zip)

## More details

I'm receiving this error intermittently and always for a `click()` event; It can happen randomly with elements I have to click on. I'm also generating a test report after each run and I can see in the captured screenshot at failure that the click occurred actually, given that the expected page was opened.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? 

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
Closing issue due to missing feedback from reporter.

**Comment by AlexandraMoga** [comment]
@whimboo apologies for the late reply. This error is intermittent so I haven't been able to pull out driver logs. I've managed to reproduce it recently and I have log output for it. Hope this helps. 

[driver.log](https://github.com/mozilla/geckodriver/files/9478989/driver.log)

**Comment by whimboo** [comment]
@AlexandraMoga thanks for the logs. So the test is clicking a link that redirects to a download. This is known to be broken and needs to be handled differently. I'm going to duplicate this issue to issue #1065.
