### ISSUE TITLE
Gecko driver not support FakerLibrary - with robotframework , data not added to the field 

### ISSUE THREAD

**Issue by santasamirz** [mozilla/geckodriver#2022]
## System

* Version: 
* Platform: 
* Selenium: 

Testcase

${fakerdataa}    FakerLibrary.Random Int                  
    Input Text    ${Email}    ${fakerdataa}

Stacktrace
no input text added to the field : field still empty

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Closing due to missing feedback from reporter.
