### ISSUE TITLE
geckodriver unexpectedly exited. Status code was: 64

### ISSUE THREAD

**Issue by daeeros** [mozilla/geckodriver#2024]
## System

* Version: 0.31.0
* Platform: Windows
* Firefox: 
* Selenium: Python/4.2.0

## Stacktrace

```
 raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64
```

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Also are you really using geckodriver 0.31.0 here? If yes which arguments are getting passed to the Service by Selenium?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Closing due to missing feedback from reporter.

**Comment by fenchu** [comment]
Hi I have the same error: same spec as above:
```
  File "c:\dist\work\multitenant-fullstack-test\tools\selenium.py", line 189, in myWebdriver
    driver = webdriver.Firefox(options=options, desired_capabilities=d)
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 175, in __init__
    self.service.start()
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\dist\venvs\multitenant-fullstack-test\lib\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 64
```
my config is:
```
        if os.environ['WEBDRIVER'].lower()=='firefox':
            # profiles is buggy in firefox either blank or not load at all
            options = selenium.webdriver.firefox.options.Options()
            options.log.level = "trace"
            d = DesiredCapabilities.FIREFOX
            d['loggingPrefs'] = {'browser': 'ALL'}
            driver = webdriver.Firefox(options=options, desired_capabilities=d)
```
This used to work fine with older geckodrivers, our web-frontend has for a long time crashed when using firefox, so I just wantet to test if it worked with 0.31.0 geckodriver

**Comment by fenchu** [comment]
I found the rootcause, it was wrong geckodriver in path:
```
geckodriver.exe --version
geckodriver 0.29.0 (cf6956a5ec8e 2021-01-14 10:31 +0200)
```
updated to v0.31.0 it is all fine. Could you please add some versioning control into geckodriver, like chromedriver has had for years.

**Comment by whimboo** [comment]
We keep our version backward compatible so no new release is needed compared to chromedriver whenever the browser gets updated. And this is a real benefit. As such it's on the users behalf to use the correct version of geckodriver with Selenium.

**Comment by ioanpier** [comment]
If installing the latest driver doesn't fix your issue, another problem might if you had set the folder where profiles are saved, but the folder was later deleted.

You can set the folder by setting the environment variable "TMPDIR"
