### ISSUE TITLE
Cant change driver log location

### ISSUE THREAD

**Issue by apacelus** [mozilla/geckodriver#2032]
## System

* Version:  latest(using [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager) to download the driver)
* Platform:  Linux, Ubuntu 22.04 LTS
* Firefox:  102.0.1
* Selenium:  python, 4.3.0

## Issue
Log still gets saved to main dir instead of the sub dir "./log"

## Code
```
driver = webdriver.Firefox(log_path="./logs/driver.log", service=FirefoxService(GeckoDriverManager().install()))
```

**Comment by whimboo** [comment]
The class that you are using here is part of the Selenium code but not geckodriver. geckodriver itself just logs to stdout which is then piped in Selenium.

**Comment by apacelus** [comment]
So how do I change the log location for it?

**Comment by whimboo** [comment]
You will have to consult the Selenium documentation, or file an issue over there in case there is no option available.
