### ISSUE TITLE
Doesn't work correctly in Windows 10

### ISSUE THREAD

**Issue by tellts** [mozilla/geckodriver#2037]
## System

* Version:  0.31.0
* 
* Firefox: Firefox 103.0.2.
* Selenium:  4.4.0

## Testcase

from selenium import webdriver
import time

driver = webdriver.Firefox(executable_path="C:\\webdriver\\geckodriver.exe")

time.sleep(5)
driver.quit()

## Trace-level log

c:\parsing\bs\DynamicBS\dbs1_3.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(executable_path="C:\\webdriver\\geckodriver.exe")

I ask you to write a version of the browser with which the webdriver starts up and works fine.

**Comment by emwitchcraft** [comment]
lmao this has nothing to do with the webdriver not working and everything to do with you not using selenium correctly.

**Comment by tellts** [comment]
I found a portable version of the April Firefox release, that is, the one that was released when the webdriver release was published. As well as instructions on how to bind it to the webdriver in the context of path visibility. But just haven't tried it yet.

**Comment by whimboo** [comment]
As @emwitchcraft already said this is not an issue with geckodriver but the Selenium framework / binding that you are using. Please consult their documentation in how to do it right.
