### ISSUE TITLE
Firefox portable on Windows

### ISSUE THREAD

**Issue by tellts** [mozilla/geckodriver#2038]
Sorry, but I don't understand how and where to enter this if you need to install it on a computer where portable Firefox will be used.
`% mkdir $HOME/tmp

% TMPDIR=$HOME/tmp geckodriver`

**Comment by whimboo** [comment]
It's unclear what this issue is about. And it doesn't seem to be specific to geckodriver but how to run it? 

I'm closing but will be happy to answer any questions in case it becomes clear what the problem actually is.

**Comment by tellts** [comment]
I meant that these lines of the console command window are indicated in the release description. But I do not know how to practically use them and where and how to insert them correctly.
https://github.com/mozilla/geckodriver/releases/tag/v0.31.0

**Comment by whimboo** [comment]
This entry has nothing to do with the portable version of Firefox on Windows. It's only an issue with Snap packages on some Linux distributions.

**Comment by tellts** [comment]
If I use the Firefox browser on Windows, do I need to install the latest version of the browser that was released now, or is it better to use the April version of the browser, which is current at the time the driver was released?

**Comment by whimboo** [comment]
For security reasons and to run with the latest features always use the most recent version of Firefox. The compatibility matrix you can find at https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html.
