### ISSUE TITLE
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by sumitsg004** [mozilla/geckodriver#2047]
## System

* Version: geckodriver version - 0.31.0
* Platform: Linux
* Firefox: version 81
* Selenium: 4.2.2

Hi Team,

Getting this error when running selenium using firefox. Versions and environment details are mentioned above. 

Error - geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context
Error injecting constructor, org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Any help is really appreciated.

**Comment by whimboo** [comment]
You are using a totally outdated version of Firefox. Please update to the latest release which is at 105 and this should not be a problem.
