### ISSUE TITLE
Geckodriver 0.32.0 can no longer locate system wide Firefox installation on Windows?

### ISSUE THREAD

**Issue by ngladitz** [mozilla/geckodriver#2053]
## System

* Version: 0.32.0
* Platform: Windows 10
* Firefox: 105.0.3
* Selenium: selenium-webdriver@4.5.0

## Testcase

I tried to update geckodriver from 0.31.0 to 0.32.0.
With the update geckodriver can no longer locate the system wide Firefox installation.

## Trace-level log

```
1665739034407	geckodriver	INFO	Listening on 127.0.0.1:58734
1665739034434	webdriver::server	DEBUG	-> GET /status 
1665739034434	webdriver::server	DEBUG	<- 200 OK {"value":{"message":"","ready":true}}
1665739034439	webdriver::server	DEBUG	-> POST /session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"browserName":"firefox","moz:firefoxOptions":{"prefs":{"devtools.console.stdout.content":true}}}}}
1665739034443	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line","stacktrace":""}}
```

**Comment by moritz2k** [comment]
@AlexHendriks The win64 is just hidden on that page, click on "show all assets" at the bottom.

**Comment by ngladitz** [comment]
Ah thanks I didn't realize that I might have replaced a 64-bit 0.31.0 with a 32-bit 0.32.0. If the 32-bit version indeed does not locate a 64-bit Firefox installation that is likely what I ran into here.

**Comment by whimboo** [comment]
@ngladitz so the 64bit geckodriver binary works fine with the default installation of Firefox? I'm fairly sure that this was the problem given that we haven't changed anything for the detection code on Windows.

**Comment by ngladitz** [comment]
@whimboo yes thank you I've just confirmed that switching to the 64-bit build fixes the issue for me.
