### ISSUE TITLE
Reads non-conformant capabilities from New Session body

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#206]
The WebDriver specification says that the desired- and required capabilities should be contained inside a `capabilities` JSON object, like this:

``` js
{
  capabilities: {
    desiredCapabilities: <object>,
    requiredCapabilities: <object>
  }
}
```

This differs from how Selenium sends capabilities:

``` js
{
  desiredCapabilities: <object>,
  requiredCapabilities: <object>
}
```

geckodriver seems to support only the latter, making it non-conformant to the spec.

**Comment by andreastt** [comment]
Or I guess part of the problem here is that I was assuming `firefoxOptions` would be read from one of `desiredCapabilities` and `requiredCapabilities`.  This might not be the case.

**Comment by jgraham** [comment]
Deferring this since the capabilities setup may undergo further churn.

**Comment by andreastt** [comment]
This is now fixed as part of the new-New Session negotiation and https://bugzilla.mozilla.org/show_bug.cgi?id=1326534, available in Firefox 52 onwards.
