### ISSUE TITLE
Issue with updating FF ESR from 78.9 to 91.9

### ISSUE THREAD

**Issue by ashrivastava-qa** [mozilla/geckodriver#2061]
## System

We had some existing geckodriver/intern.js tests passing on ESR 78 w/ geckodriver 0.29.1. When we tried updating these tests to ESR 91 (w/ geckodriver 0.31.0) they started throwing errors for “Browsing context has been discarded”. And we’re also seeing an error in the logs about driver.version being unknown. 
To test it out we downgraded the geckodriver and ESR version back to 0.29.1 and 78 resp and the tests worked again.

* Version: 0.31.0
* Platform: macOS 12.5.1 
* Firefox: 106.2.0 
* Selenium: 3.141.59

## Testcase

The tests could be found [here](https://github.com/mozilla/fxa/blob/main/packages/fxa-content-server/tests/functional/pairing.js)

## Stacktrace

```
firefox on mac - pairing - it can pair (5.113s)
    NoSuchWindow: [GET http://localhost:4444/wd/hub/session/bc6df076-56c8-4f7a-be32-9a405dc29337/screenshot] Browsing context has been discarded
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'ashrivastava-9jlvdq', ip: 'fd3b:767e:fef2:1:f:e2ae:9c0:e8c6%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '14'
    Driver info: driver.version: unknown
      at pollForScreenshot @ tests/functional/pairing.js:81:8
      at Command.<anonymous> @ tests/functional/pairing.js:108:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:65:10
      at Command.<anonymous> @ tests/functional/lib/helpers.js:79:18
      at Command.<anonymous> @ tests/functional/lib/helpers.js:73:10
      at Test.it can pair [as test] @ tests/functional/pairing.js:149:12
      @ ../../src/lib/Test.ts:268:51
      at Test.it can pair [as test] @ tests/functional/pairing.js:153:17
      @ ../../src/lib/Test.ts:268:51
      at Test.it can pair [as test] @ tests/functional/pairing.js:211:17
      @ ../../src/lib/Test.ts:268:51
```

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by ashrivastava-qa** [comment]
This issue is resolved. Thanks!
