### ISSUE TITLE
Selenium RemoteWebDriver wraps dictionary responses in value field

### ISSUE THREAD

**Issue by mehmetg** [mozilla/geckodriver#207]
webelement::rect() returns value not compliant with spec level 'w3c' 
i.e. the rect data is nested under a 'value' key in the return value like in the old spec. 

``` json
{  
   "status":0,
   "sessionId":"b7040c41-00d7-4486-8c86-b8c715bdff2f",
   "value":{  
      "point":null,
      "dimension":null,
      "width":600,
      "y":314,
      "x":20,
      "hCode":44480,
      "height":87,
      "class":"org.openqa.selenium.Rectangle"
   },
   "state":"success",
   "hCode":493044042,
   "class":"org.openqa.selenium.remote.Response"
}
```

**Comment by mehmetg** [comment]
This may be python bindings setting the spec level wrong, but the expectation was that this would be equivalent to FF47.

**Comment by andreastt** [comment]
The botched return value above aside, what are you expecting to be returned? [Get Element Rect](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect) should return, according to the spec, a dictionary of `x`, `y`, `width`, and `height`.

The return value you pasted above appears to have been mangled quite severely by the Selenium remote server, but it looks like all of the fields are present inside the `value` field.

**Comment by mehmetg** [comment]
@andreastt: The problem I see with it is it does not have the same structure as the chrome or ff47 response.  The question is more about the spec level supported than the content, which I agree looks fine. The expected response from the command  by the python bindings is
```   
   {  
   "point":null,
   "dimension":null,
   "width":98,
   "y":10954,
   "x":20,
   "hCode":-620756992,
   "height":17,
   "class":"org.openqa.selenium.Rectangle"
}
```

The selenium spec is all but vague about the response model and the developers of the binding may have assumed a flat structure meaning the data would not be nested under 'value' key.

**Comment by andreastt** [comment]
The other fields in the JSON object you have pasted come from the Selenium intermediary node and not FirefoxDriver itself. I don’t know why Selenium augments the response with these fields, but they are completely unnecessary.

WebDriver conformant client bindings should rely on the response data structures set out by [the specification](http://w3c.github.io/webdriver/webdriver-spec.html). If they rely on proprietary Selenium additions we either need to specify those (if we deem them important) or treat the cases as bugs.

In the concrete case of the above, `point`, `dimension` , `hCode`, and `class` are all superfluous. If you have code that relies on any of those, that is a bug.

**Comment by mehmetg** [comment]
@andreastt: I have no code that relies on those. 
The code below fails with FF48/GD
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L393-L402

I think there's a disagreement between your interpretation of the wc3 and the python binding authors. I filed a separate issue with them: https://github.com/SeleniumHQ/selenium/issues/2731

**Comment by andreastt** [comment]
I don’t think I understand the problem you’re reporting then. What exact error and stacktrace are you getting from the Python code you linked to?

**Comment by mehmetg** [comment]
@andreastt:
Python expects:
```json
{  
   "point":null,
   "dimension":null,
   "width":98,
   "y":10954,
   "x":20,
   "hCode":-620756992,
   "height":17,
   "class":"org.openqa.selenium.Rectangle"
}
```

and gets:

```json
{  
   "status":0,
   "sessionId":"b7040c41-00d7-4486-8c86-b8c715bdff2f",
   "value":{  
      "point":null,
      "dimension":null,
      "width":600,
      "y":314,
      "x":20,
      "hCode":44480,
      "height":87,
      "class":"org.openqa.selenium.Rectangle"
   },
   "state":"success",
   "hCode":493044042,
   "class":"org.openqa.selenium.remote.Response"
}
```
The end result is a key error on 'x' as the x field is under rect['value']['x'] not rect['x']

**Comment by andreastt** [comment]
OK. So I think you’re running geckodriver through a RemoteWebDriver in Selenium, am I right?

I suspect the Selenium intermediary isn’t compatible with the W3C WebDriver spec in that it tries to encapsulate responses from geckodriver and pass them on in the same way that it does for Selenium drivers.

In other words, when the Python bindings speak to W3C conformant remote ends it expects the response body from _Get Element Rect_ to be a dictionary where `x`, `y`, `height`, and `width` are exposed on the top-level of the JSON structure. Selenium drivers wrap these inside a `value` dictionary.

geckodriver returns the correct thing, but I suspect the Selenium server reconstructs the JSON structure into something that isn’t conformant. An educated guess is that you will not see the problem above if you tell the Python client to interact directly with geckodriver, hence the problem lies in the Selenium RemoteWebDriver.

**Comment by andreastt** [comment]
I’m keeping this bug open as a tracking bug.

**Comment by mehmetg** [comment]
I just checked Java bindings: https://github.com/SeleniumHQ/selenium/blob/291a4873df17dd85013cdbb21f31493b1698a74a/java/client/src/org/openqa/selenium/remote/RemoteWebElement.java#L352-L360

The line below suggests your format to be correct. Python bindings need some attention.
https://github.com/SeleniumHQ/selenium/blob/291a4873df17dd85013cdbb21f31493b1698a74a/java/client/src/org/openqa/selenium/remote/RemoteWebElement.java#L354

Thank you.

**Comment by andreastt** [comment]
I don’t think this issue is with the Python bindings. They look at the response body and extract `x`, `y`, `width`, and `height` directly from that: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L393-L402

**Comment by mehmetg** [comment]
I think I understand now. In that case the problem is with Se Server and the Java bindings.

Se server wraps the rect data into a value field and he java bindings assume that they should be wrapped. I wish the documentation would be clearer. 

To make it clear this is the correct w3c format as per  [Get Element Rect Spec](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect)

```json
{ 
   "status":0,
   "width":98,
   "y":10954,
   "x":20,
   "height":17,
}
```

**Comment by andreastt** [comment]
I believe this may have been fixed in a recent beta release of Selenium 3, and I have seen no similar issues reported for a while. I’m going to close this tracking bug.

**Comment by mehmetg** [comment]
Yes, it has been fixed indeed. Thank you! 👍

**Comment by jamesaspence** [comment]
Hi, using selenium server standalone 3.4.0 has this issue again. All of my responses are looking like this:

```
{ value: { sessionId: '058084b4c9c29f9303a78a071f553daa',
    status: 0,
    value: null } }
```
