### ISSUE TITLE
How to wait until a page is fully loaded?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [mozilla/geckodriver#2071]
I use the following HTTP request to access the page source. It appears to get the page source at the time when the request is received. When the page is still loaded (e.g., by javascript), whatever will be loaded later is not available in the result. 

```
curl -s http://127.0.0.1:<port_id>/session/<sesion_id>/source
```

If I want to wait to make sure some element is available or until the page is fully loaded, do I have to periodically get the source and check it? Or this is a more efficient way to help me achieve this goal without having to wait for more time than unnecessary.

## System

* Version: NA
* Platform: NA
* Firefox: NA
* Selenium: NA

## Testcase

NA

## Stacktrace

NA

## Trace-level log

NA

**Comment by whimboo** [comment]
As I have said in the other issues please get it in contact via the given communication channel. The issue tracker here is not for support questions but for bug issues and feature requests.

https://chat.mozilla.org/#/room/#webdriver:mozilla.org
