### ISSUE TITLE
How to get the HTML code of an element?

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [mozilla/geckodriver#2072]
https://developer.mozilla.org/en-US/docs/Web/WebDriver

I only see commands like the following on the above page. But I don't see a way to get the HTML code of an element.

- Get Element Attribute
- Get Element Property
- Get Element Tag Name

I tried outerHTML. But it does not seem to be there. Do I miss anything?

```
$ curl -s -H 'Content-Type: application/json' -d '{"url":"http://httpbin.org"}' http://127.0.0.1:4444/session/91ba315a-d796-440f-8e45-35d384fb1c8a/url
{"value":null}
$ curl -s -H 'Content-Type: application/json' -d '{"using":"xpath","value":"//h2[@class=\"title\"]"}' http://127.0.0.1:4444/session/91ba315a-d796-440f-8e45-35d384fb1c8a/element
{"value":{"element-6066-11e4-a52e-4f735466cecf":"74d674fc-7f39-49ee-9a25-5bbafe6aaff9"}}
$ curl -s http://127.0.0.1:4444/session/91ba315a-d796-440f-8e45-35d384fb1c8a/element/74d674fc-7f39-49ee-9a25-5bbafe6aaff9/attribute/outerHTML
{"value":null}
```

## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by whimboo** [comment]
As I have said in the other issues please get it in contact via the given communication channel. The issue tracker here is not for support questions but for bug issues and feature requests.

https://chat.mozilla.org/#/room/#webdriver:mozilla.org
