### ISSUE TITLE
Cannot Hide Geckodriver console window

### ISSUE THREAD

**Issue by ReMiOS** [mozilla/geckodriver#2073]
## System

* Version: geckodriver 0.32.0
* Platform: Windows 11 / Python 3.9.13 
* Firefox: 108.0.1
* Selenium: 4.6.0 and above

## Testcase

After updating Selenium from 4.5.0 to any higher version the geckodriver console window cannot be hidden.
( using Pyinstaller with --noconsole and --onefile option )

I've tried various options in the code, but none seems to hide the console window

Using CREATE_NO_WINDOW worked until selenium v4.6.0:
```
service = Service( geckodriver )
service.creationflags = subprocess.CREATE_NO_WINDOW
```

Tried adding the code below, but without result
`options.add_argument('--disable-gpu') `

```
flag = 0x08000000  # No-Window flag
webdriver.common.service.subprocess.Popen = functools.partial(webdriver.common.service.subprocess.Popen, creationflags=flag )
or webdriver.common.service.subprocess.Popen = functools.partial( subprocess.Popen, creationflags=flag )
```

**Comment by whimboo** [comment]
Geckodriver doesn't open a console at all. This is all done by Selenium. As you said it regressed after upgrading to a new Selenium version. As such please file an issue against Selenium.

**Comment by ReMiOS** [comment]
Thanks for your reply.

I've created an issue at Selenium:
https://github.com/SeleniumHQ/selenium/issues/11465
