### ISSUE TITLE
Getting 'WebDriverError: HTTP method not allowed' error message while using actions class methods

### ISSUE THREAD

**Issue by d-sprasad** [mozilla/geckodriver#2074]
## System

* Version: v0.32.0
* Platform: macOS
* Firefox: 102.2.0esr (64-bit)
* Selenium WebdriverJS: 3.6.0

## Testcase

Geeting 'WebDriverError: HTTP method not allowed' error message while using actions class methods, below are the details:-

Node version: v16.13.1
WebDriverJs version: 3.6.0

Sample code:

await driver.actions().sendKeys(Key.ENTER).perform()

Observed, in http.js file in Selenium 3.6.0 still using older endpoints like
[cmd.Name.SEND_KEYS_TO_ACTIVE_ELEMENT, post('/session/:sessionId/keys')]
[cmd.Name.MOVE_TO, post('/session/:sessionId/moveto')]

Please add support for above end points so older selenium tests will also work with latest gecko driver

## Stacktrace

WebDriverError: HTTP method not allowed
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:536:11)
    at /node_modules/selenium-webdriver/lib/http.js:441:30

**Comment by whimboo** [comment]
Those end-points are not WebDriver spec compatible, and I wonder why Selenium 3.6.0 were still using these. Nevertheless this is an old Selenium release and you may want to upgrade to a 4.x release.
