### ISSUE TITLE
Where to find versions compatability of selenium with geckodriver and firefox

### ISSUE THREAD

**Issue by camproto** [mozilla/geckodriver#2077]
## System

* Version: ???
* Platform: Windows 10 and linux
* Firefox: ???
* Selenium: 3.13.0

## Compatability matrix needed

I'm for my automated UI testing currently bound by arquillian 1.7.0 to the old Selenium version 3.13.0. (plan to get rid of arquillian in a later step)

Which version of geckodriver is intended to work with Selenium 3.13.0? 
Looking for best practices!
Tried several versions from same year 2018, but always get strange protocol errors from webDriver. 
Which geckodriver versions are tested against 3.13.0? 

And next with Firefox version is a good match for this geckodriver version?

**Comment by whimboo** [comment]
The details are available in our README:
https://github.com/mozilla/geckodriver#readme

That refers to https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html. I hope that helps.
