### ISSUE TITLE
Change in tagging convention broke `wasm-pack` tool

### ISSUE THREAD

**Issue by mwu-tow** [mozilla/geckodriver#2080]
The recent `v0.32.1` release is actually tagged twice: once as `v0.32.1` and once as `0.32.1`. This is unlike [previous releases](https://github.com/mozilla/geckodriver/tags), where only v-number style of tags was used.
This caused regressions in projects that assumed so-far scheme of naming things, like Rust's [`wasm-pack`](https://github.com/rustwasm/wasm-pack/issues/1219).

If this change was not intentional, please remove the `0.32.1` tag.

**Comment by whimboo** [comment]
Sorry, I thought that was already done. I've now removed the accidentally created tag name `0.32.1`. Thanks for your report!
