### ISSUE TITLE
firefoxOptions profile is different than the one that selenium ruby binding sends

### ISSUE THREAD

**Issue by Marcelovk** [mozilla/geckodriver#209]
I am trying to use the firefoxOptions capability, using the current master, as it was added after the 0.10 release.

If you try to use Selenium:WebDriver::Firefox::Profile, and pass it to firefoxOptions.profile, the end result passed to geckodriver is the profile wrapped around a zip, like this

`firefoxOptions={profile={zip=<profile base64encoded and zipped>...`

I dont know if you were trying to achieve compatibility or not, as the selenium way of doing that would be adding that as a capability named "firefox_profile". 

Should It be compatible with the firefox_profile cabability?

**Comment by andreastt** [comment]
The Selenium bindings likely need to be updated to support the `firefoxOptions` concept. I don’t want to do that before 0.11 is released.

**Comment by andreastt** [comment]
I believe utilities that support `moz:firefoxOptions`, as it is now called, have been added to all major Selenium client bindings. Please open bugs against the Selenium project if this is not the case.

The `firefox_profile` capability that was supported initially has been removed in favour of `{"moz:firefoxOptions": {"profile": <profile>}}`. You can read the full documentation in the project’s README.
