### ISSUE TITLE
clear() was updated in the atoms, please update them in GeckoDriver

### ISSUE THREAD

**Issue by diemol** [mozilla/geckodriver#2094]
Hi folks, 

This pull request https://github.com/SeleniumHQ/selenium/pull/11504 updated how clear() works in the atoms, it could be a good idea to update the atoms in GeckoDriver. 

Would that be possible?

Thank you,

**Comment by whimboo** [comment]
@diemol we cannot update that atom in the driver without a spec change. Please file a WebDriver classic issue or even provide a PR so that this can be updated.

**Comment by whimboo** [comment]
Actually as per spec the `clear` atom should not be in use at all:

```
Selenium
    The following functions are defined within the [Selenium](https://selenium.dev/) project, at revision a6b161a159c3d581b130f03a2e6e35f577f38dec.

        [bot.dom.getVisibleText](https://github.com/SeleniumHQ/selenium/blob/a6b161a159c3d581b130f03a2e6e35f577f38dec/javascript/atoms/dom.js#L1007)
        [bot.dom.isShown](https://github.com/SeleniumHQ/selenium/blob/a6b161a159c3d581b130f03a2e6e35f577f38dec/javascript/atoms/dom.js#L573)
```

Also Marionette doesn't make use of it. So I don't think that there is any work to do.

**Comment by diemol** [comment]
Thank you for the feedback, @whimboo!
