### ISSUE TITLE
Cannot process with 'headless' variable

### ISSUE THREAD

**Issue by RatexMak** [mozilla/geckodriver#2095]
## System

* Version: geckodriver 0.32.2
* Platform: Linux Ubuntu20.04-Server
* Firefox: Mozilla Firefox 111.0
* Selenium: 3.12.0

When I was writing a testcase with java, I passed 'headless=ture' to gechodriver. Howerver, it seems that geckodriver is not take 'headless' as a variable?

![image](https://user-images.githubusercontent.com/33491425/225691549-170ce278-4220-40af-be99-46fc61ee28a8.png)

**Comment by whimboo** [comment]
This is not a problem with geckodriver given that the headless option is not part of the capabilities as passed from Selenium. As such please consult the Selenium documentation in how to use that flag correctly. Thanks.
