### ISSUE TITLE
Doesn't wait redirected page after clicking on link

### ISSUE THREAD

**Issue by nvborisenko** [mozilla/geckodriver#2101]
## System

* Version: 0.33.0
* Platform: Windows 10
* Firefox: 109.0
* Selenium: 4.8.2

My element is
```html
<a href="/redirect">Open</a>
```

where `/redirect` is a resource

```
Request Method: GET
Status Code: 302 Found

Response Headers:
  Location: https://www.my_sut.com/target
```

It means when I click on the link, then `/target` page should be opened. And it works.

But geckodriver doesn't wait until `/target` page loads. By the way, chromedriver does wait.

Using simple code:
```csharp
var driver = new FirefoxDriver();
driver.Url = "https://my_sut.com";

driver.FindElement(By.Tag("a")).Click();
Console.WriteLine(driver.Url); // shows https://my_sut.com, not https://www.my_sut.com/target
```

**Comment by whimboo** [comment]
This is basically the same as issue #634 and can happen for any kind of navigation.
