### ISSUE TITLE
PrintParameter not working in print  webdriver api

### ISSUE THREAD

**Issue by xuing** [mozilla/geckodriver#2106]
## System

* Version: 0.33.0
* Platform: Windows
* Firefox: 111.0.1 (64 )
* Selenium: 4.8.3 

## Testcase
any website with backgroud,

## Describe

I use the following code to print the web page as a PDF, but without the background
~~~
            print_options = PrintOptions()
            print_options.background = True
            print_options.page_size = 'A4'
            print_options.landscape = False
            print_options.scale = 1
            print_options.shrink_to_fit = True
            pdf_data = driver.print_page(print_options)
~~~
![image](https://user-images.githubusercontent.com/11143269/233042200-6111ab00-cf42-4007-9302-5ddcc9a131ae.png)

I also use geckodriver directly, but also no backgroud. 
![image](https://user-images.githubusercontent.com/11143269/233044254-f4deb3ae-f9f6-4e95-992e-e31adacc0218.png)

**Comment by whimboo** [comment]
This was fixed in Firefox 113. Please see issue #2001.
