### ISSUE TITLE
Undesired Logging

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#2111]
Geckodriver outputs so much stuff to the console. My expectation is that I can pass in values to the driver with `--log` and only see the filtered output. Is this output intended not to be able to be filtered via the driver?

## System

* Version: 0.33
* Platform: macOS
* Firefox: 113
* Selenium: 4.9.1

## Testcase

This code: 
```
  System.setProperty(GeckoDriverService.GECKO_DRIVER_LOG_LEVEL_PROPERTY, "FATAL");
  driver = new FirefoxDriver();
```

Starts the driver with:
```
[--port=35197, --websocket-port=10277, --allow-origins, http://127.0.0.1:10277, http://localhost:10277, http://[::1]:10277, --log, fatal]
```

## Trace-level log

https://gist.github.com/titusfortner/22f2aa1b167041ba0fae3e1cf3c7ae71

**Comment by whimboo** [comment]
@titusfortner isn't that a dupe of issue #619?

**Comment by titusfortner** [comment]
Ah, yes, looks like it. Thanks.
