### ISSUE TITLE
geckodriver0.16.0 cargo build Compile error

### ISSUE THREAD

**Issue by HysUnknown** [mozilla/geckodriver#2114]
## System

* Version: 0.16.0
* Platform: linux-arm64
* Firefox: 52.3.0
* Selenium: 

## Testcase
firefox=52.3.0 on my linux computer, I need to compile geckodriver0.16.0 into arm64 package, but the following problems appear, could you please answer them?

error log:
$cargo build
  Downloaded miniz-sys v0.1.12 (registry `tuna`)
  Downloaded cc v1.0.79 (registry `tuna`)
  Downloaded 2 crates (140.8 KB) in 2.26s
   Compiling slog v1.5.2
   Compiling cc v1.0.79
   Compiling rand v0.3.15
   Compiling memchr v1.0.1
error[E0277]: `core::fmt::Opaque` cannot be shared between threads safely
   --> /home/gxxc/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/slog-1.5.2/src/ser.rs:228:24
    |
228 | impl SyncSerialize for fmt::Arguments<'static> {}
    |                        ^^^^^^^^^^^^^^^^^^^^^^^ `core::fmt::Opaque` cannot be shared between threads safely
    |
    = help: within `Arguments<'static>`, the trait `Sync` is not implemented for `core::fmt::Opaque`
    = note: required because it appears within the type `&core::fmt::Opaque`
    = note: required because it appears within the type `ArgumentV1<'static>`
    = note: required because it appears within the type `[ArgumentV1<'static>]`
    = note: required because it appears within the type `&[ArgumentV1<'static>]`
    = note: required because it appears within the type `Arguments<'static>`
note: required by a bound in `SyncSerialize`
   --> /home/gxxc/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/slog-1.5.2/src/ser.rs:120:33
    |
120 | pub trait SyncSerialize: Send + Sync  + 'static {}
    |                                 ^^^^ required by this bound in `SyncSerialize`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `slog` due to previous error

**Comment by whimboo** [comment]
geckodriver 0.16.0 was released on Apr 21, 2017. And there is no support for that release since 0.16.1 and 0.17.0 have been released. You should really update both geckodriver and Firefox to the most recent official versions.

**Comment by whimboo** [comment]
No, but with recent geckodriver releases we ship arm64 builds by default for all major platforms: https://github.com/mozilla/geckodriver/releases/tag/v0.33.0

**Comment by HysUnknown** [comment]
All right, thanks
