### ISSUE TITLE
Cannot set browser.link.open_newwindow preference

### ISSUE THREAD

**Issue by Gerald94** [mozilla/geckodriver#2120]
## System

* Version: 0.33.0
* Platform: Windows 10
* Firefox: 114.0.2
* Selenium: 7.4.1 + 3.141.59

In my testcase i click an link and i want that the link always opens in a new tab instead of a new window.

In my capabilites i want to set the preference:

option = new FirefoxOptions();
option.addPreference("browser.link.open_newwindow", 3);

When i execute the test i get the following error:

Preference browser.link.open_newwindow may not be overridden: frozen value=2, requested value=3

Does anybody know how to fix that?

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Actually which binding of Selenium is that? I can see references to that in the Selenium repository:
https://github.com/search?q=repo%3ASeleniumHQ%2Fselenium+%22frozen+value%22&type=code

**Comment by whimboo** [comment]
Ok, so I think that this is a Selenium issue and that [you should use Selenium 4](https://github.com/SeleniumHQ/selenium/issues/5540#issuecomment-537427727) to get it working.

**Comment by Gerald94** [comment]
Oh i think you are right. But for me it is no possible to switch to Selenium 4 now, this takes some time.

Is it somehow possible to set this preference fixed in geckodriver or firefox? As a fast workaround?

**Comment by whimboo** [comment]
You would have to ask the Selenium folks if there would be a workaround. Maybe use that formerly mentioned issue for that.
