### ISSUE TITLE
github api limit to retrieve geckodriver

### ISSUE THREAD

**Issue by bboycs** [mozilla/geckodriver#2123]
As mention in the title. 
Is there any other mirror get geckodriver instead of github api ? 
current using webdriver-manager accross multiple machines (vm) which will hit github api call limit

**Comment by whimboo** [comment]
It's not expected that your infrastructure downloads the same binary over an over again. A cache should probably be used for it. I would suggest that you file an issue for https://github.com/bonigarcia/webdrivermanager.
