### ISSUE TITLE
can't find element when run in eks which node don't have GPU

### ISSUE THREAD

**Issue by Matrix-Zhang** [mozilla/geckodriver#2127]
## System

* Version: instrumentisto/geckodriver:debian
* Platform:  aws eks
* Firefox: instrumentisto/geckodriver:debian
* Selenium:  rust thirtyfour

## Trace-level log
1692110697385	geckodriver	INFO	Listening on 127.0.0.1:4444
1692110703093	mozrunner::runner	INFO	Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/opt/firefox/firefox" "--marionette" "--headless" "-no-remote" "-profile" "/tmp/rust_mozprofile3vIYHc"
Error: no such element: Id(ContentPlaceHolder1_txtUserName)
*** You are running in headless mode.
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
[GFX1-]: glxtest: libpci missing
[GFX1-]: glxtest: libGL.so.1 missing
[GFX1-]: No GPUs detected via PCI

1692110703283	Marionette	INFO	Marionette enabled
1692110703337	Marionette	INFO	Listening on port 46399
Read port: 46399
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.error: ({})
console.error: (new TypeError("linkMap is undefined", "resource://gre/modules/NewTabUtils.sys.mjs", 2003))
-------------------------------------
is this is normal behavior?

**Comment by whimboo** [comment]
Can you please provide a full trace level log for geckodriver? You can get that by passing the `-vv` argument to it. Does it also happen in headful mode?

**Comment by Matrix-Zhang** [comment]
it caused by anti crawler,

**Comment by whimboo** [comment]
Thanks for letting us know and good to see it's not a problem on our side.
