### ISSUE TITLE
help me install geckodriver on Mac

### ISSUE THREAD

**Issue by Demidof** [mozilla/geckodriver#2128]
Can you tell me how to install it on a mac? I installed tbselenium, but I can't install geckodriver. I ask for help

**Comment by whimboo** [comment]
Geckodriver is a downloadable binary. See the appropriate package on the release page [like the one for the 0.33.0 release](https://github.com/mozilla/geckodriver/releases/tag/v0.33.0). If that's problem for tbselenium you should contact their maintainers.
