### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status -1

### ISSUE THREAD

**Issue by tebiodl** [mozilla/geckodriver#2137]
## System

* Version: [0.33.0](https://github.com/mozilla/geckodriver/releases/tag/v0.33.0)
* Platform: Windows 10
* Firefox: 117.0.1
* Selenium: 3.141

## Testcase

webdriver.Firefox(executable_path=r'C:\Programs\Firefox\geckodriver.exe', firefox_binary=binary, firefox_profile=selenium_profile)

## Stacktrace

selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status -1

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html
