### ISSUE TITLE
could someone compile last version of gecko for windows 32 bits?

### ISSUE THREAD

**Issue by jajavi** [mozilla/geckodriver#215]
it is already compiled for windows 64 bits, but all my machines are windows 32
could someone compile it or tell wich steps follow to compile it from scratch?
thanks in advance
Javier

**Comment by andreastt** [comment]
If you’re already on a Windows 32-bit OS you should be able to compile it normally using `cargo build`.

**Comment by jajavi** [comment]
Ok, I will do it, but I need to install a lot of thing in my machine. (and i am just a selenium tester)
Once I have 32-bit file compiled, do you want me to upload somewhere?

**Comment by andreastt** [comment]
We are already compiling 32-bit Windows binaries in our CI as of https://github.com/mozilla/geckodriver/commit/994cb3177414e51ac7bef8bdeb143beef2fda4d6.

**Comment by jajavi** [comment]
where can I find compiled file for windows 32 bits?

It is not realesed at https://github.com/mozilla/geckodriver/releases

[https://avatars2.githubusercontent.com/u/131524?v=3&s=400]<https://github.com/mozilla/geckodriver/releases>

Releases · mozilla/geckodriver · GitHub<https://github.com/mozilla/geckodriver/releases>
github.com
geckodriver - WebDriver <-> Marionette proxy ... Only upgrade to this version if you are using Selenium 3 beta releases.




________________________________
De: Andreas Tolfsen <notifications@github.com>
Enviado: miércoles, 7 de septiembre de 2016 13:54
Para: mozilla/geckodriver
Cc: jajavi; Author
Asunto: Re: [mozilla/geckodriver] could someone compile last version of gecko for windows 32 bits? (#215)


We are already compiling 32-bit Windows binaries in our CI as of 994cb31<https://github.com/mozilla/geckodriver/commit/994cb3177414e51ac7bef8bdeb143beef2fda4d6>.

-

**Comment by andreastt** [comment]
It’s not in a released version yet.

**Comment by jgraham** [comment]
You can see the remaining 0.11 issues at https://github.com/mozilla/geckodriver/milestone/1

**Comment by jajavi** [comment]
I don´t understand you. If you are compiling it for 32 bit windows. should i wait till you upload compiled version to release pages?
I have already installed on my windows compiler but is not easy for me to compiles on rust with gcc dependencies, it fails everywhere (due to my incapacity, but it is not easy for me,and i am sure, for many others)

**Comment by jgraham** [comment]
0.11 should be released in a few days. Are you OK waiting for that?

**Comment by jajavi** [comment]
oh yes, now I understand. 
I am looking forward this new release, i will wait.
Thanks for everything

**Comment by jajavi** [comment]
Lates news: I have finally compiled by myself geckodriver version 0.10.0
If someone needs it tell me where to upload
