### ISSUE TITLE
Failed to download geckodriver archive

### ISSUE THREAD

**Issue by GermanAizek** [mozilla/geckodriver#2158]
ERROR :
File "C:\Python312\Lib\site-packages\geckodriver_autoinstaller\utils.py", line 179, in download_geckodriver
    raise RuntimeError(f'Failed to download geckodriver archive: {url}')
    RuntimeError: Failed to download geckodriver archive: https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-win32.tar.gz

1. install geckodriver `pip install geckodriver-autoinstaller`
2. Run program
```
from selenium import webdriver
import geckodriver_autoinstaller

geckodriver_autoinstaller.install()
driver = webdriver.Firefox()
```

OS: windows 10

**Comment by whimboo** [comment]
On Windows we ship ZIP archives. So the correct URL is:
http://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-win32.zip

As such please raise an issue against the geckodriver_autoinstaller project.
