### ISSUE TITLE
Certification error "Your connection is not secure"

### ISSUE THREAD

**Issue by manjunatha-mr** [mozilla/geckodriver#216]
Not able to close the certification error "Your connection is not secure" by adding below capabilities and profile.

ProfilesIni allProfiles = new ProfilesIni();
		FirefoxProfile myProfile = new FirefoxProfile();
		myProfile.setAcceptUntrustedCertificates(true);
		myProfile.setAssumeUntrustedCertificateIssuer(false);
		WebDriver driver=new FirefoxDriver(myProfile);

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
		WebDriver driver = new FirefoxDriver(capabilities);

profile.setAcceptUntrustedCertificates(true);
                profile.setAssumeUntrustedCertificateIssuer(true);
                capability2.setCapability(FirefoxDriver.PROFILE, profile);

We are using below versions:
 Geckodriver v0.10.0. 
Selenium: 3.0.0 beta-3 and 
Firefox: 48.0.2

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/93.

**Comment by mbn217** [comment]
same for me , I facing this problem as of now

**Comment by andreastt** [comment]
@mbn217 Ensure you’re using the very latest Firefox Nightly.
