### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:50047 exception with selenium and gecko

### ISSUE THREAD

**Issue by urec56** [mozilla/geckodriver#2163]
## System

* Version: 1709131392277   geckodriver     INFO    Listening on 127.0.0.1:4444 (Last)
* Platform: Linux Kernel: 6.7.5-arch1-1
* Firefox: Version 122.0.1 (64-bit)  
* Selenium: Python + selenium==4.18.1

## Testcase

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

opts = Options()
opts.log.level = "trace"
driver = Firefox(options=opts)
```
or
```python
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options

url = 'https://www.youtube.com/watch?v=hVvHAPDX9Kk'

opts = Options()
opts.log.level = "trace"
driver = webdriver.Firefox(options=opts)
```
both

## Stacktrace

```
Traceback (most recent call last):
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/test_parser.py", line 11, in <module>
    driver = webdriver.Firefox(options=opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 69, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/mnt/urec/trash/some/all/PycharmProjects/VideoGrep2/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:50047
```

## Trace-level log

This file didn't created

**Comment by whimboo** [comment]
Thank you for the report. I have some questions:

* Is that an issue after you upgraded Selenium? 
* Is that a local test or a remote test? 
* Are you using IPv6 beside IPv4?

**Comment by urec56** [comment]
I install it for the first time
It was local test on my PC
I use IPv4 instead of IPv6 because I don't have v6

**Comment by whimboo** [comment]
Is `localhost` correctly set to `127.0.0.1`? I cannot see why it should fail otherwise.

Please check again if there is really no `geckodriver.log` file present. It should really be there given that this failure from above comes from geckodriver, and it should have already written content to stdout (as captured by Selenium and piped to that file).

**Comment by urec56** [comment]
```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By

url = sys.argv[1]

opts = Options()
opts.log.level = "trace"
driver = Firefox(options=opts)
driver.get(url)
```

Am i right?

I don't have any `geckodriver.log` in my directory
![image](https://github.com/mozilla/geckodriver/assets/152381868/ee9f2c9c-193a-4719-9735-ea4d034a1a82)

**Comment by whimboo** [comment]
Without trace logs I cannot really help. Maybe you could use WireShark to record the HTTP requests / responses with geckodriver? This could give an idea what might go wrong here.

**Comment by whimboo** [comment]
Btw. you can also use a plain `curl` command to actually get this tested. We have [some documentation](https://firefox-source-docs.mozilla.org/testing/geckodriver/Usage.html#standalone), which describes what you have to do.

**Comment by urec56** [comment]
Sorry. I don't have any time to check this now. If I will, I'll check it and return some info here

**Comment by whimboo** [comment]
That's fine. I'll close the issue for now and we are happy to reopen in case it is indeed a problem on our side.
