### ISSUE TITLE
SeleniumManager Exception managing firefox

### ISSUE THREAD

**Issue by jayprojects** [mozilla/geckodriver#2168]
## System

* Version:  0.34.0 
* Platform: Red Hat 8.9 
* Firefox: 115.3
* Selenium: selenium-java + 4.12.1

## Testcase
I'm running a Java-Selenium use case on Red Hat instance, on headless mode. 
Its running behind proxy, both Firefox and Geckodriver is pre installed via Docker image. 
The selenium code runs fine and does what it supposed to do as expected, however it shows a warning at the line "new FirefoxDriver(options)"

`... org.openqa.selenium.manager.SeleniumManager lambda$runCommand$1 
WARNING: Exception managing firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: dns error: failed to lookup address information: Name does not resolve) 
`

The warning indicates, selenium manager tries to check/get latest geckodriver, which it doesn't have access to, due to proxy.

As mentioned, we already have all required dependencies in the OS image and like to disable geckodriver latest release check by the selenium manager.

I tried setting "app.update.auto" & "app.update.enabled" to false on the options, that did not help.

Thank you.

**Comment by whimboo** [comment]
Thank you for the report, but as it looks like this is an issue purely with the Selenium manager. This tool is not related to geckodriver and you should file an issue on its own GitHub repository.
