### ISSUE TITLE
please add some install directions to readme

### ISSUE THREAD

**Issue by bionicles** [mozilla/geckodriver#2169]
can you please put a prominent code block above the fold featuring the recommended installation method? even the docs didn't seem to have anything on this. cargo? github releases? build from source? what do you think is best?

**Comment by whimboo** [comment]
Thanks for filing the issue!

I'm going to update the readme over on https://bugzilla.mozilla.org/show_bug.cgi?id=1888085.

**Comment by whimboo** [comment]
The documentation has been updated.
