### ISSUE TITLE
Robot Framework with Firefox hangs on browser startup with specified alternate profile path given. 

### ISSUE THREAD

**Issue by stevereiss** [mozilla/geckodriver#2170]
## System

* Version: 0.34.0 (c44f0d09630a 2024-01-02 15:36 +0000)
* Platform: Microsoft Windows [Version 10.0.22631.3374]
* Firefox: Firefox v124.0.1 64-bit
* Selenium: selenium 4.19.0

* Robot Framework : 
robotframework                      7.0
robotframework-pythonlibcore        4.4.0
robotframework-requests             0.9.6
robotframework-selenium2library     3.0.0
robotframework-seleniumlibrary      6.2.0

## Testcase

Robot Code : 
-------------

  LOGIN_URL = local accessable address
  profile_location = C:\GitLab-Repos\Quantamatics\quantamatics_test\Browser_Tests\Common\Profiles\FireFoxAutomationUserProfile

  (profile has most all options turned off - allow downloads no dialog, anonymous browser

  SeleniumLibrary.Open Browser    ${LOGIN_URL}    browser=ff  ff_profile_dir=${profile_location}

## Stacktrace

Error in Geckodriver Log : 
---------------------------

1711988209703	geckodriver	INFO	Listening on 127.0.0.1:51490
1711988241896	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--remote-debugging-port" "51491" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "C:\\Users\\STEVEN~1\\AppData\\Local\\Temp\\rust_mozprofileMu5FIS"
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
1711988242981	Marionette	INFO	Marionette enabled
Dynamically enable window occlusion 0
1711988243062	Marionette	INFO	Listening on port 51506
WebDriver BiDi listening on ws://127.0.0.1:51491
Read port: 51506
1711988243314	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
DevTools listening on ws://127.0.0.1:51491/devtools/browser/bceca4fc-6ae9-4770-b4f2-94fc0838ed93
JavaScript error: resource://gre/modules/PromiseWorker.sys.mjs, line 96: Error: Could not get children of file(C:\Users\STEVEN~1\AppData\Local\Temp\rust_mozprofileMu5FIS\thumbnails) because it does not exist
1711988273882	addons.xpi	ERROR	System addon update list error SyntaxError: XMLHttpRequest.open: 'http://%(server)s/dummy-system-addons.xml' is not a valid URL.
console.error: services.settings: 
  Message: StorageError: Storage error: UnknownError: IndexedDB: main/quicksuggest pruneAttachments() IndexedDB:  pruneAttachments() in main/quicksuggest The operation failed for reasons unrelated to the database itself and not covered by any other error code.
  Stack:
    StorageError@resource://services-settings/RemoteSettingsClient.sys.mjs:153:5
_adjustedError@resource://services-settings/RemoteSettingsClient.sys.mjs:928:14
maybeSync@resource://services-settings/RemoteSettingsClient.sys.mjs:816:38

JavaScript error: , line 0: uncaught exception: Object
console.error: (new StorageError("Storage error: UnknownError: IndexedDB: main/quicksuggest pruneAttachments() IndexedDB:  pruneAttachments() in main/quicksuggest The operation failed for reasons unrelated to the database itself and not covered by any other error code.", "resource://services-settings/RemoteSettingsClient.sys.mjs", 153))
Exiting due to channel error.
Exiting due to channel error.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Maybe this can / will reveal more information. Thanks.


[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
Closing as incomplete because of a missing reply from the reporter, but happy to reopen if more details are provided, which demonstrate that this is an issue with geckodriver or Firefox.
