### ISSUE TITLE
ElementSendKeys calls scrollIntoView when an element is already visible

### ISSUE THREAD

**Issue by andrewnicols** [mozilla/geckodriver#2183]
## System

* Version: 0.34.0
* Platform: Linux / MacOS
* Firefox: 127.0.2
* Selenium: n/a

I don't currently have a testcase for this because I'm not sure how best to demonstrate this.

https://www.w3.org/TR/webdriver2/#element-send-keys states:

> NOTE
> The [Element Send Keys](https://www.w3.org/TR/webdriver2/#dfn-element-send-keys) [command](https://www.w3.org/TR/webdriver2/#dfn-commands) [scrolls into view](https://www.w3.org/TR/webdriver2/#dfn-scrolls-into-view) the form control [element](https://dom.spec.whatwg.org/#concept-element) and then sends the provided keys to the [element](https://dom.spec.whatwg.org/#concept-element). In case the [element](https://dom.spec.whatwg.org/#concept-element) is not [keyboard-interactable](https://www.w3.org/TR/webdriver2/#dfn-keyboard-interactable), an [element not interactable](https://www.w3.org/TR/webdriver2/#dfn-element-not-interactable) [error](https://www.w3.org/TR/webdriver2/#dfn-error) is returned.

The scroll into view definition states:
> To scroll into view an [element](https://dom.spec.whatwg.org/#concept-element) perform the following steps *only if the element is not already [in view](https://www.w3.org/TR/webdriver2/#dfn-in-view)*:

(emphasis mine)

The issue is that the Marionette `interaction.sys.mjs::webdriverSendKeysToElement` always calls `lazy.dom.scrollIntoView(containerEl);` and that [_always_ calls `scrollIntoView()`](https://searchfox.org/mozilla-central/rev/b368ed8b48c0ea8ed2f1948e4776a6fbb5976dff/remote/shared/DOM.sys.mjs#1037-1041). 

That is to say that Marionette always scrolls into view, regardless of whether it is necessary or not.

**Comment by andrewnicols** [comment]
Ah apologies - I forget what has to be reported where.

Reported to Marionette: https://bugzilla.mozilla.org/show_bug.cgi?id=1906095

**Comment by whimboo** [comment]
This issue is now fixed thanks to @andrewnicols's work and will be available in the next Firefox Nightly build today.
