### ISSUE TITLE
rust 1.80.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [mozilla/geckodriver#2189]
seeing some build failure as

```
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.23/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++
```

see https://github.com/time-rs/time/issues/693

**Comment by whimboo** [comment]
@chenrui333 does that even happen with the updated Cargo.lock? After a `cargo update` the build was working for me before I released geckodriver.

**Comment by whimboo** [comment]
Oh, most likely you were using the sources of the 0.34.0 release? If that's the case please pull the recent changes for geckodriver 0.35.0 and build again. It should now work.

**Comment by whimboo** [comment]
The geckodriver 0.35.0 release should have fixed that. If it's still happening for you with this release feel free to reopen.
