### ISSUE TITLE
Protractor using geckodriver 0.35.0 gives "InvalidArgumentError: missing field `capabilities`"

### ISSUE THREAD

**Issue by alexhutson1** [mozilla/geckodriver#2191]
## System

* Version: 0.35.0
* Platform: Windows 11
* Firefox: 128.0 and 78.9.0esr
* Selenium: 3.141.59

## Testcase

We are using protractor version 7.0.0 against multiple versions of Firefox. geckodriver 0.34.0 seems to work where 0.35.0 does not. I can work on producing a more refined reproduction if required.

## Stacktrace

```
[11:10:42] D/launcher - Running with --troubleshoot
[11:10:42] D/launcher - Protractor version: 7.0.0
[11:10:42] D/launcher - Your base url for tests is http://localhost:4200/
Report destination:   report\e2e\screenshots\index.html
[11:10:42] I/launcher - Running 1 instances of WebDriver
[11:10:42] I/direct - Using FirefoxDriver directly...
[11:10:42] E/runner - Unable to start a WebDriver session.
[11:10:42] E/launcher - Error: InvalidArgumentError: missing field `capabilities`
    at Object.throwDecodedError (C:\work\folder\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (C:\work\folder\node_modules\selenium-webdriver\lib\http.js:519:13)
    at C:\work\folder\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Closing report
[11:10:42] E/launcher - Process exited with error code 100
```

**Comment by alexhutson1** [comment]
Looks like this is to do with how Protractor uses `multiCapabilities`: https://github.com/angular/protractor/blob/4bc80d1a459542d883ea9200e4e1f48d265d0fda/lib/launcher.ts#L111

This would now need to be `capabilities` with a `firstMatch` or `alwaysMatch` property inside it: https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities

Protractor is deprecated so will only be able to set `multiCapabilities`. It can no longer work with the latest versions of `geckodriver` given it has removed support for legacy capabilities.

Feel free to close as not planned if this is desired.

**Comment by alexhutson1** [comment]
It seems like in theory Protractor could support the new `capabilities` object, but because the version we're using of protractor uses selenium-webdriver 3.6.0, this version does not support the new object whatsoever: https://github.com/SeleniumHQ/selenium/blob/selenium-3.6.0/javascript/node/selenium-webdriver/lib/webdriver.js

Selenium-webdriver sends something to geckodriver that it does not understand.

In theory, by upgrading Protractor to a later version, which uses a later version of selenium-webdriver, we could continue to use geckodriver.

**Comment by whimboo** [comment]
Thanks for letting us know about the details of ProTractor. Yes, that is indeed the problem here and as it looks like it will not be solved. You can still continue to use geckodriver 0.34.0 in case you haven't ported your tests to another framework. Until now there is no maximum version of a supported Firefox set and it should still work for a couple of Firefox releases.
