### ISSUE TITLE
How to open firefox browser in maximize form using browser options 

### ISSUE THREAD

**Issue by ghost** [mozilla/geckodriver#2195]
## System

* Version: 0.35.0
* Platform: Windows 11
* Firefox: 129.0.2 (64-bit)
* Selenium: 4.23.1

## Testcase
options.addArguments("--start-maximized"); :not maximizing the firefox browser like this

![image](https://github.com/user-attachments/assets/0fce8a43-a7d4-4d8f-99d2-ecbd3501284a)

Instead, it is opening like this

![image](https://github.com/user-attachments/assets/ea2a2f5b-63ef-4789-914f-5c1959f432df)

for options.addArguments("--kiosk");

![image](https://github.com/user-attachments/assets/36f79803-f012-469f-af75-9b5561820104)

**Comment by whimboo** [comment]
There is no such `--start-maximized` command line argument for Firefox. You could use `--window-size` and specifying a fixed width and height like `--window-size 1280x1024`. Otherwise let geckodriver start Firefox as normal and then run the `Maximize Window` command to switch to maximize mode.

**Comment by julienw** [comment]
hey @whimboo, from my testing, `--window-size` doesn't seem to do anything for a "normal" firefox... The message in `--help` says it's about screenshots, but I couldn't make it work either.

Anyway I think having an easy way to run firefox maximized would be beneficial as it's not always easy to run protocol commands from the test frameworks.

**Comment by whimboo** [comment]
Firefox doesn't actually support a maximize command line argument. But instead there is `--kiosk` mode. Maybe this could help you (beside the other limitations with this mode)?
