### ISSUE TITLE
No win64 Version in release 0.35

### ISSUE THREAD

**Issue by hMutzner** [mozilla/geckodriver#2201]
## System

* Version: <35>
* Platform: <windows 11 pro>
* Firefox: <130.0.1>
* Selenium: <newest>

**Comment by whimboo** [comment]
The assets might not be showing completely for you. So please expand and you will see the Windows 64bit version of geckodriver. Otherwise here is the direct download:

https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-win64.zip
