### ISSUE TITLE
Firefox crashes with latest NoScript addon on EFF's browser test page

### ISSUE THREAD

**Issue by MatzFan** [mozilla/geckodriver#2202]
## System

* Geckodriver: 0.35.0
* Platform: Linux LMDE 6 (faye) - based on Debian bookworm
* Firefox: 115.15.0esr
* Selenium: 4.25.0

## Testcase
```ruby
logger = Selenium::WebDriver.logger
logger.level = :debug
options = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
driver = Selenium::WebDriver.for :firefox, options: options
driver.install_addon '/path/to/noscriptv11.4.40.xpi'
driver.get 'https://firstpartysimulator.net/kcarter?&aat=1' # linked from https://coveryourtracks.eff.org
Selenium::WebDriver::Wait.new(timeout: 60, interval: 1).until { driver.find_element(id: 'summary_sentence') }
driver&.quit # line 26 in my test code (where the failure occurs) is this line
```

## Stacktrace
```
Selenium::WebDriver::Error::InvalidSessionIdError: Tried to run command without establishing a connection
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/response.rb:63:in `add_cause'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/response.rb:41:in `error'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/http/common.rb:101:in `new'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/http/common.rb:101:in `create_response'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/http/common.rb:67:in `call'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/bridge.rb:685:in `execute'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/remote/bridge.rb:212:in `quit'
    /home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.25.0/lib/selenium/webdriver/common/driver.rb:188:in `quit'
    test/features/fingerprinting/test_eff.
rb:26:in `ensure in test__eff_fingerprint_is_non_unique'
    test/features/fingerprinting/test_eff.rb:26:in `test__eff_fingerprint_is_non_unique'
```
## Trace-level log

`A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down` at line 327

[1727864384.log](https://github.com/user-attachments/files/17228148/1727864384.log)

## Additional information

I first discovered this issue in the tests for my [selenium_tor](https://gitlab.com/matzfan/selenium-tor) Ruby project, but am reporting it here as I was able to reproduce it with the regular Firefox browser. I've not tested FF 128, but suspect the problem will be present for the following reasons:

My investigations so far lead me to think this is definitely related to changes in the NoScript add-on, as my [test](https://gitlab.com/matzfan/selenium-tor/-/blob/master/test/features/fingerprinting/test_eff.rb?ref_type=heads) code runs fine with NoScript <= 11.4.37. It ran fine with Tor Browser 13 (stable) and all Tor Browser 14 alpha versions up to 14.0a6. It broke with 14.0a7 (which [upgrades](https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/raw/main/projects/browser/Bundle-Data/Docs-TBB/ChangeLog.txt) NoScript to 11.4.40). TB 14 is based on FF 128 and my test code runs fine in 14.0a7 with NoScript 11.4.37 installed. Additionally, upgrading NoScript to v11.4.38rc1 and above in previous TB 14 alpha builds, or TB 13 stable results in the crash behavior reported here.

NoScript 11.4.38rc changes are [here](https://github.com/hackademix/noscript/compare/11.4.37...11.4.38rc1). They include [these](https://github.com/hackademix/nscl/compare/9f59d8d823cc58b2a9c751b4db7715658b68cc67...c3fd029c9c08c472601dcff1fbc3c0edcaf98c27#diff-fb60a05aa66e6c7688f48255d6d9b50153216937af09f3be014b4f17c4558c9f) changes in the `nscl` submodule. Hope this helps.

**Comment by MatzFan** [comment]
I should have noted that `driver&.quit` is in an `ensure` block in my actual test code - which is why execution reached that far.

**Comment by whimboo** [comment]
Hi, so Firefox 115ESR actually reached its end of life for Linux and the last version just got released. That means that a crash on that branch of Gecko will not be fixed anymore. Also if you see the crash for TB only, it might be a problem on their side.

As you say it works fine when you are using the alpha of the next TB release, which is based on the 128ESR branch. Given that no crash is happening there it sounds like that whatever caused it has been addressed.

From the log I cannot tell what's causing the crash. But if you are interested in to know what exactly it triggered you could try to get the minidump file and get it uploaded for crash processing:

https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html

Otherwise there is nothing more that we can do here. If you upload please let us know. Thanks!

**Comment by MatzFan** [comment]
Hi @whimboo, I've tried to generate a crash report as per the instructions you linked to, but although I see a `mindumps` dir being setup in my `test_profile_dir` it remains empty, even after a crash. I modified the code above to the following - am I doing something wrong? Appreciate your help as this is my first time trying to analyze minidumps.
```ruby
logger = Selenium::WebDriver.logger
logger.level = :debug
options = Selenium::WebDriver::Firefox::Options.new(log_level: :trace)
options.add_argument '-profile'
options.add_argument 'tmp/test_profile_dir'
service = Selenium::WebDriver::Service.firefox
service.port = 2828
driver = Selenium::WebDriver.for :firefox, options: options, service: service
driver.install_addon '/path/to/noscriptv11.4.40.xpi'
driver.get 'https://firstpartysimulator.net/kcarter?&aat=1' # linked from https://coveryourtracks.eff.org
Selenium::WebDriver::Wait.new(timeout: 60, interval: 1).until { driver.find_element(id: 'summary_sentence') }
driver&.quit
```

**Comment by whimboo** [comment]
I think this looks fine. Does the log tell that a content process crashed? If it still doesn't work you could also try to use the `--enable-crash-reporter` argument for geckodriver (service). But please only use it for investigating the crash. Thanks.

**Comment by MatzFan** [comment]
> Does the log tell that a content process crashed?

Yes: line 327 in my original trace-level log: `A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down`.

I've actually made some progress and found that using the default profile bundled with Tor Browser stops the crashes, but I'd still like to be able to figure out how to generate `minidumps`. I guess it is possible TB prevents these from being written, but I'll try the `--enable-crash-reporter` flag anyhow, thanks.

**Comment by whimboo** [comment]
Oh yes, that could be. If the default profile works I would suggest to check which preferences are set. You could bisect the list of preferences until you figured out which one is causing the crash.

**Comment by MatzFan** [comment]
@whimboo can you point me at the docs/specs on what exactly `--enable-crash-reporter` does (I see it is new in 0.35.0)?

Paradoxically enough enabling this flag fixes the crashes, so I'd like to know if it is setting any prefs, as obviously I can't use it in production code! Btw you seem to have a broken link at https://firefox-source-docs.mozilla.org/testing/geckodriver/CrashReports.html. Looks like the link under the text "view the crash reports" is missing a "/" after mozilla.org.

**Comment by MatzFan** [comment]
I wonder actually if this points to a bigger issue, as surely the crash reporter's enabled status should not affect application behavior which is leading to a crash? However, if I add the following to my code above the crash behavior is in fact reliably stopped.
```ruby
...
service.args << '--enable-crash-reporter'
...
```
Also, is the logic [here](https://searchfox.org/mozilla-central/source/testing/geckodriver/src/browser.rs#127) the right way around? It seems to read as though the 3 crash reporter env vars are set to true if the `--enable-crash-reporter` command line flag is *not* (!) set.

**Comment by whimboo** [comment]
Sorry for the late reply! So yes, there shouldn't be a difference in behavior but maybe `MOZ_CRASHREPORTER_SHUTDOWN` has a side-effect here.

For now lets try to figure out why it's crashing. We will soon have a way to [backup the minidump files to a specific location](https://bugzilla.mozilla.org/show_bug.cgi?id=1882338). Once landed we could give you a nightly build of geckodriver to actually test if that works for you. By next week we should get it landed.

If you cannot await you could update your test to have a try/catch and stop the script before the session gets deleted by geckodriver. Then manually observe the `minidumps` subfolder of the used Firefox profile for the minidump. If you can grab it and upload maybe we could see why it's not crashing when the argument is used.

**Comment by MatzFan** [comment]
Hi @whimboo by all means, I'm happy to test the relevant geckodriver nightly, let me know when it is out.

The issue was with a specific release of the NoScript extension and I also reported it there. It was fixed and I've not seen a repeat with newer releases. I did also get confirmation from the Tor Project (you may recall my Selenium project is based on Tor Browser) that they prevent minidumps from being reported. Even so, I'd like to get minidumps working in case I need to use them for future debugging.
