### ISSUE TITLE
UnexpectedAlertPresentException exc.msg does not contain the prompt message

### ISSUE THREAD

**Issue by justinearl** [mozilla/geckodriver#2204]
## System

* Version: 0.35
* Platform: Linux
* Firefox: 131.0 (64-bit)
* Selenium: 4.25.0

## Description

The exception raised in geckodriver does not contain the prompt message anymore. In selenium `UnexpectedAlertPresentException` we do not have any info anymore what was the content of the automatically dismissed prompt

Current message
```log
"message":"Unexpected alert dialog detected. Performed handler \"dismiss\""
```

Previous message
```log
"message":"Dismissed user prompt dialog: This is a triggered alert!"
```

Is this the expected behavior now for geckodriver? For chrome the prompt message is still passed to the exception.

## Testcase

```python
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options
from selenium.common.exceptions import UnexpectedAlertPresentException


firefox_options = Options()
# firefox_options.unhandled_prompt_behavior = "ignore"
firefox_options.log.level = "trace"
service = Service(executable_path=geckodriver_path, log_output="trace.log")
driver = webdriver.Firefox(service=service, options=firefox_options)

try:
    driver.get("data:text/html,<html><body></body></html>")
    driver.execute_script("alert('This is a triggered alert!');")
    assert driver.switch_to.alert.text
    driver.title  # Trigger unexpected alert
    assert False, "No exception"
except UnexpectedAlertPresentException as e:
    print(f"Exception: {e}")
    print(e.msg)
finally:
    driver.quit()
```

## Stacktrace

```
Alert Text: None
Message: Unexpected alert dialog detected. Performed handler "dismiss"
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
UnexpectedAlertOpenError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:800:5
GeckoDriver.prototype._handleUserPrompts@chrome://remote/content/marionette/driver.sys.mjs:2962:11
```

## Trace-level log

Attached file
[trace.log](https://github.com/user-attachments/files/17321119/trace.log)

```log
1728528535324	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unexpected alert open","message":"Unexpected alert dialog detected. Performed ... Errors.sys.mjs:800:5\nGeckoDriver.prototype._handleUserPrompts@chrome://remote/content/marionette/driver.sys.mjs:2962:11\n"}}
```

Old Trace log from Firefox 125.0.1
[trace.log](https://github.com/user-attachments/files/17321053/trace.log)
 
```log
1728527680840	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unexpected alert open","message":"Dismissed user prompt dialog: This is a tri ... Errors.sys.mjs:800:5\nGeckoDriver.prototype._handleUserPrompts@chrome://remote/content/marionette/driver.sys.mjs:2835:13\n"}}
```

-->

**Comment by justinearl** [comment]
It seems that the "data", that contains the message, is not passed anymore?

```log
1728535271794	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unexpected alert open","message":"Unexpected alert dialog detected. Performed ... Errors.sys.mjs:800:5\nGeckoDriver.prototype._handleUserPrompts@chrome://remote/content/marionette/driver.sys.mjs:2962:11\n"}}
```

**Comment by juliandescottes** [comment]
The error message changed in https://bugzilla.mozilla.org/show_bug.cgi?id=1884650

I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1924469 to discuss about adding the message again

**Comment by juliandescottes** [comment]
@justinearl can you share the code where you use this error message?

**Comment by justinearl** [comment]
@juliandescottes It is something like this

```python
...
firefoxPrefix = 'Dismissed user prompt dialog: '
if exc.alert_text:
      alertText = exc.alert_text  # from chrome
elif exc.msg and exc.msg.startswith(firefoxPrefix):
      alertText = exc.msg.removeprefix(firefoxPrefix)
...
```

**Comment by juliandescottes** [comment]
Thanks for the feedback! So our message will still be a bit different, so you will have to update your code ultimately. I will add an example here once it lands.

**Comment by juliandescottes** [comment]
@justinearl the error message will be updated to 

```
`Unexpected ${promptType} dialog detected. Performed handler "${handlerConfig.handler}". Dialog text: ${textContent}`,
```

As you can see the "prefix" part is now dynamic, so you'll need to update your code to handle this.

**Comment by whimboo** [comment]
This got fixed and will be available in today's Nighty build of Firefox with the target to be released in 133. For 132 we are too late.

Also please note that we may go ahead with providing the dialog text in the future via the `data.text` property on error responses. When we do we are most likely reverting the above change again and you won't have to scrape the text out of the error message anymore. Feel free to follow https://bugzilla.mozilla.org/show_bug.cgi?id=1925934 to see the status.

**Comment by whimboo** [comment]
With the next geckodriver 0.36.0 release we are going to send the dialog text via the optional data["text"] field of the error message now. We did not yet revert the Marionette part - I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1948236 for that.
