### ISSUE TITLE
FitNesse- Selenium - NoSuchDriverException: Unable to obtain chromedriver Error in FitNesse with Selenium

### ISSUE THREAD

**Issue by Sabirsk64** [mozilla/geckodriver#2205]
## System

* Version: 

org.openqa.selenium.remote.NoSuchDriverException: Unable to obtain: geckodriver, error geckodriver must exist: geckodriver-windows-%dbit.exe
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.18'
Driver info: driver.version: FirefoxDriverc

No Method setBrowserSizeToMaximum[0] in class nl.hsac.fitnesse.fixture.slim.MapFixture.
Available methods:
addValueTo(java.lang.Object, java.lang.String) -> void
addValueToIn(java.lang.Object, java.lang.String, java.util.Map) -> void
allKeys() -> class java.util.ArrayList
allValues() -> class java.util.ArrayList
aroundSlimInvoke(fitnesse.slim.fixtureInteraction.FixtureInteraction, java.lang.reflect.Method, java.lang.Object[]) -> class java.lang.Object
clearValue(java.lang.String) -> boolean
clearValues() -> void
contentEquals(java.lang.Object) -> boolean
contentOfEquals(java.util.Map, java.lang.Object) -> boolean
copyMap() -> interface java.util.Map
copyValuesFrom(java.util.Map) -> void
copyValuesFromTo(java.util.Map, java.util.M
[Pom.zip](https://github.com/user-attachments/files/17397083/Pom.zip)
ap) -> void
equals(java.lang.Object) -> boolean
expandPeriodsInNamesToNestedMaps(boolean) -> void
expandsPeriodsInNamesToNestedMaps() -> boolean
get(java.lang.String) -> interface java.util.Map
getClass() -> class java.lang.Class
getMapHelper() -> class nl.hsac.fitnesse.fixture.util.MapHelper
globalValue(java.lang.String) -> class java.lang.String
hashCode() -> int
notify() -> void
notifyAll() -> void
repeatAtMostTimes() -> int
repeatAtMostTimes(int) -> void
repeatCount() -> int
repeatInterval() -> long
reset() -> void
set(java.lang.String, java.lang.Object) -> void
setBase64EncodedContentOfAsValueFor(java.lang.String, java.lang.String) -> void
setBooleanValueFor(boolean, java.lang.String) -> void
setBooleanValueForIn(boolean, java.lang.String, java.util.Map) -> void
setContentOfAsValueFor(java.lang.String, java.lang.String) -> void
setDoubleValueFor(double, java.lang.String) -> void
setDoubleValueForIn(double, java.lang.String, java.util.Map) -> void
setGlobalValueTo(java.lang.String, java.lang.String) -> void
setIntValueFor(int, java.lang.String) -> void
setIntValueForIn(int, java.lang.String, java.util.Map) -> void
setMapHelper(nl.hsac.fitnesse.fixture.util.MapHelper) -> void
setRepeatIntervalToMilliseconds(int) -> void
setValueFor(java.lang.Object, java.lang.String) -> void
setValueForIn(java.lang.Object, java.lang.String, java.util.Map) -> void
setValuesFor(java.lang.String, java.lang.String) -> void
setValuesForIn(java.lang.String, java.lang.String, java.util.Map) -> void
size() -> int
sizeOf(java.lang.Object) -> int
sizeOfIn(java.lang.String, java.util.Map) -> int
timeSpentRepeating() -> long
toString() -> class java.lang.String
value(java.lang.String) -> class java.lang.Object
valueIn(java.lang.String, java.util.Map) -> class java.lang.Object
wait() -> void
wait(long) -> void
wait(long, int) -> void
waitMilliseconds(int) -> [boolean](`url`)
waitSeconds(int) -> boolean

**Comment by whimboo** [comment]
If geckodriver cannot be detected then it is an issue with Selenium but not geckodriver itself. You most likely want to consult the Selenium documentation, or file an issue on their repository.

**Comment by Sabirsk64** [comment]
Thank you @whimboo for your help. Have a nice day !
