### ISSUE TITLE
Firefox 48.0.2 + geckodriver 0.9 + selenium 3.0.0.b2 + Python 3.5.2

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [mozilla/geckodriver#221]
Code: 
`from selenium import webdriver`
`from selenium.webdriver.common.desired_capabilities import DesiredCapabilities`
`caps = DesiredCapabilities.FIREFOX`
`caps["marionette"] = True`
`driver = webdriver.Firefox(capabilities=caps)`

 **Error message**:
'ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`
I am using the name "geckodriver" for the geckodriver.exe, didn't change to wires.exe.
I can't run any cases, either, such as 
`from selenium import webdriver`
`browser = webdriver.Firefox()`
`browser.get('http://www.seleniumhq.org/')`

Error would be:
`selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: `C:\Users\XXX\AppData\Local\Temp\tmp3khgxbsn If you specified a log_file in the FirefoxBinary constructor, check it for details.`

I have searched every singe solution from the web but could find the solution, any guidance would be appreciate.

**Comment by andreastt** [comment]
This issue is severely lacking in details to reproduce it, but I don’t think this is a geckodriver issue.
