### ISSUE TITLE
Does geckodriver support Firefox 45.0.2 ?

### ISSUE THREAD

**Issue by HackToday** [mozilla/geckodriver#224]
I am using selenium  2.53.1.  and test against Firefox 45.0.2

When tried geckodriver, it seems something not work,  I learnt from someone pointed me this link:

` https://github.com/mozilla/geckodriver#supported-firefoxen`

It only works with Firefox 48 or onwards. 

Does that mean it can not work with Firefox 45.0.2 ?  
I am sorry to ask here, since not find proper way to get answer.  Thanks

**Comment by jgraham** [comment]
Effectively no. The backend is integrated into gecko and so with older gecko many or all features may not work. This churn will stop once we have something more final of course :) In the meantime you need to use FirefoxDriver for Gecko <= 47.

**Comment by andreastt** [comment]
Generally the more recent the Firefox, the more bug fixes and features it will have. For the time being, using [Nightly builds](https://nightly.mozilla.org/) is the safest choice.

Otherwise you can remain on Firefox 45 with Selenium 2.53.1 (or Firefox 47.0.1) until geckodriver + Marionette is more stable.

**Comment by HackToday** [comment]
Hi @andreastt and @jgraham  That's a funny issue here.

As from selenium https://github.com/SeleniumHQ/selenium/issues/2559 

They said firefox have something issue, and selenium can not work with Firefox 48.

While pytest-selenium said, it support geckodriver, but geckodriver need at least Firefox 48.


That's seems can not be solved with circular version conflicts.

**Comment by andreastt** [comment]
geckodriver != FirefoxDriver

Firefox 48 and onwards ships with add-on signing which fundamentally breaks FirefoxDriver. You need to use geckodriver, which is our implementation of WebDriver, from Firefox 48 onwards.

**Comment by HackToday** [comment]
Hi @andreastt  All I have is referred from here.
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

It said 
> Marionette, the next generation of FirefoxDriver, 


did you know if your geckodriver  implemention works with selenium or not ?

If yes, which selenium version works with that geckodriver ? Please specify that which  geckodriver version works with selenium version.


Thanks

**Comment by davehunt** [comment]
> While pytest-selenium said, it support geckodriver, but geckodriver need at least Firefox 48.

pytest-selenium is simply a convenience plugin for pytest that provides your tests with a Selenium driver instance via a fixture. It depends on the official python package for Selenium, and therefore supports anything that package (and the version of Selenium server you're using) is compatible with.

**Comment by andreastt** [comment]
@HackToday I don’t exactly know which Selenium version works with geckodriver, but a recent pre-release of 3.x is a safe bet.

**Comment by rafis** [comment]
Which version of geckodriver (wires) is compatible with Firefox 45.0.2?

**Comment by jgraham** [comment]
There isn't one. Please read the other comments in the issue; geckodriver's backend is implemented in Firefox itself and old versions simply don't have the necessary code.
