### ISSUE TITLE
Update Selenium language bindings to support firefoxOptions dictionary

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#228]
geckodriver 0.11.0 will introduce a new `firefoxOptions` dictionary that is much like `chromeOptions` offered by Blink. This is documented in the [README](https://github.com/mozilla/geckodriver#firefox-capabilities) and the relevant code changes landed in https://github.com/mozilla/geckodriver/commit/d475a3d492f3375651e841e8d8bd07e6689919b7.

To summarise, geckodriver supports a dictionary like the following, where all keys are optional:

```json
{
  …
  "firefoxOptions": {
    "binary": "/path/to/firefox",
    "args": ["--foo", "--bar"],
    "prefs": {
      "preference name": 42,
      "another preference name": false
    },
    "profile": "base64 encoded zip file of profile",
    "log": {
      "level": "trace"
    }
  }
}
```

To prepare for this change we will need to update the relevant Selenium client bindings so that their utility functions for setting Firefox options understand how to generate the dictionary.

We are not intending to patch this in a backwards compatible manner as geckodriver is still in an alpha stage. In the case of outdated geckodrivers, the only recommendation is to upgrade.

Selenium bindings to patch:

- [ ] Python
- [ ] Node.js
- [ ] C#
- [ ] Java
- [x] Ruby

**Comment by andreastt** [comment]
Cc @jimevans @lukeis @jleyba @titusfortner @AutomatedTester

**Comment by titusfortner** [comment]
I've compiled master, and verified that the Ruby implementation I wrote works with firefoxOptions.
But all the option switches for starting geckodriver are still there as well. Are those (e.g. `--port` & `--binary`) going away in 0.11?

**Comment by andreastt** [comment]
@titusfortner Thanks for fixing Ruby!

The command-line flags are not going away with this change. The `firefoxOptions` capabilities is a way to override the flags.

These flags are still available:

```
geckodriver 0.10.0 
WebDriver implementation for Firefox.

USAGE:
    geckodriver [FLAGS] [OPTIONS]

FLAGS:
        --connect-existing    Connect to an existing Firefox instance
    -h, --help                Prints help information
    -v                        Log level verbosity (-v for debug and -vv for
                              trace level)
    -V, --version             Prints version and copying information

OPTIONS:
    -b, --binary <BINARY>           Path to the Firefox binary
        --log <LEVEL>               Set Gecko log level [values: fatal, error,
                                    warn, info, config, debug, trace]
        --marionette-port <PORT>    Port to use to connect to Gecko (default:
                                    random free port)
        --host <HOST>               Host ip to use for WebDriver server
                                    (default: 127.0.0.1)
    -p, --port <PORT>               Port to use for WebDriver server (default:
                                    4444)
```

**Comment by jleyba** [comment]
I will make the changes for nodejs when 0.11 is released.

**Comment by retorquere** [comment]
I've just upgraded to selenium-webdriver 3.0.0 -- do I interpret the above correctly that I should have the profile as a base64-encoded string in the options? The profile I use for testing is 1.8MB, zipped, that's one big string to have there.

Are there samples on how to use 3.0.0 from Ruby? I've installed geckodriver but am not making much headway yet.

**Comment by andreastt** [comment]
@retorquere I don’t think the Ruby bindings support the renamed `moz:firefoxOptions` dictionary yet, but you can as you say construct the capabilities dictionary manually:

```
{
    "moz:firefoxOptions": {
        "profile": "<base 64 encoded profile directory>"
    }
}
```

**Comment by retorquere** [comment]
But this is then the full 1.8MB in a base64 string, not just the path to it? And how do I give this dict to Selenium?

**Comment by andreastt** [comment]
You would typically call `Profile.to_json` and pass the dict in to the FirefoxDriver constructor using the `:desired_capabilities` symbol.

It is a Base64 encoded string because the driver cannot be guaranteed to be on the local system when used remotely. There is no change from what Selenium is doing here.

**Comment by retorquere** [comment]
Alright. Is there a snippet that shows how to put all of this together?

**Comment by andreastt** [comment]
Paging @titusfortner.

**Comment by ambirag** [comment]
`profile = Selenium::WebDriver::Firefox::Profile.new`
        `profile['app.update.auto'] = false`
        `profile['app.update.enabled'] = false`
        `profile['app.update.service.enabled'] = false`
        `profile['app.update.staging.enabled'] = false`
        `profile['app.update.silent'] = false`
        `profile['plugin.state.flash'] = 0`
        `require 'base64'`
        `profile64=Base64.encode64(profile.to_s)`
        `capabilities = Selenium::WebDriver::Remote::Capabilities.firefox(marionette: true, :firefox_options => {'zip' => {profile: profile64}})`
`Watir::Browser.new(:firefox, :desired_capabilities => capabilities, :http_client => http_client)`

@retorquere @titusfortner this is how I did and its working for me, tested this on FFv45 by setting marionette = false , and on FFv49 marionette=true.
