### ISSUE TITLE
Firefox 48.0.1 -Windows 32 bit version Gecko driver is not available to suppport selenium automation

### ISSUE THREAD

**Issue by Sameer-gadhave** [mozilla/geckodriver#231]
Would you be releasing Gecko driver for **32 bit Windows OS** which   supports Mozilla Firefox version 48.0 and above versions?

Also- please let us know - which is the latest gecko driver version is available and working with Mozilla Firefox version >= 47  on **32 bit windows OS**

**Comment by andreastt** [comment]
Compilation for Windows 32-bit was fixed in https://github.com/mozilla/geckodriver/commit/994cb3177414e51ac7bef8bdeb143beef2fda4d6 and will be part of the next release (0.11.0).
