### ISSUE TITLE
Expose geckodriver version in Status command

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#232]
Would it make sense to return the geckodriver version with session capabilities (similar to how [chromedriver does it](https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Returned-Capabilities))?

**Comment by andreastt** [comment]
When geckodriver is feature complete it shouldn’t matter much what version it is, as it is only a HTTP proxy. Marionette, which provides the actual WebDriver implementation, sits inside Gecko and can therefore be identified by the Firefox version.

Other opinions welcome.

**Comment by andreastt** [comment]
We talked about capabilities at the F2F in Libson and we decided to adopt https://github.com/w3c/webdriver/pull/327 for capabilities and creating sessions.

It would maybe make some sense, however, to return the version number as part of the newly introduced [Status](http://w3c.github.io/webdriver/webdriver-spec.html#status) command.

**Comment by AutomatedTester** [comment]
This was added in https://github.com/mozilla/webdriver-rust/commit/9eb725aa076e47d8b8963e74581add48d53e25a8
