### ISSUE TITLE
Unable to set firefox profile preferences to download/save files

### ISSUE THREAD

**Issue by beereniche** [mozilla/geckodriver#236]
After I've upgraded to gecko driver, I noticed that I'm not able to download files,using firefox profile, and set following preferences, they are ignored:

`FirefoxProfile.setPreference("browser.download.folderList", 2);
FirefoxProfile.setPreference("browser.helperApps.alwaysAsk.force", false);
FirefoxProfile.setPreference("browser.download.manager.showWhenStarting",false); 
FirefoxProfile.setPreference("browser.download.dir", downloadPath); 
FirefoxProfile.setPreference("browser.download.downloadDir", downloadPath); 
FirefoxProfile.setPreference("browser.download.defaultFolder", downloadPath);`

I'm usign firefox 48.0 and Java Selenium 3.0.0-beta3

**Comment by andreastt** [comment]
Can you verify that those settings are being set when when you start the browser?

**Comment by krmahadevan** [comment]
@andreastt Not sure if this observation is related or not, but I don't find any code path within FirefoxDriver that makes use of the profile that was passed to it.

The `FirefoxDriver.createCommandExecutor` ( see [here](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxDriver.java#L236-L245)) makes use of the passed in Firefox profile only when instantiating a org.openqa.selenium.firefox.FirefoxDriver.LazyCommandExecutor.

```
private static final CommandExecutor createCommandExecutor(Capabilities desiredCapabilities,
                                                           FirefoxBinary binary,
                                                           FirefoxProfile profile) {
  if (isLegacy(desiredCapabilities)) {
    return new LazyCommandExecutor(binary, profile);
  }
  GeckoDriverService.Builder builder = new GeckoDriverService.Builder();
  builder.usingPort(0);
  return new DriverCommandExecutor(builder.build());
}

```

**Comment by andreastt** [comment]
@krmahadevan That looks very much like a possible culprit. I’m going to file this under “more Selenium issues”.

**Comment by krmahadevan** [comment]
@andreastt Thanks. Please let me know if there is any way in which I can contribute a fix for this :) and I will gladly try taking a jab at this.

**Comment by andreastt** [comment]
@krmahadevan I filed https://github.com/SeleniumHQ/selenium/issues/2835.

**Comment by andreastt** [comment]
Closing.
