### ISSUE TITLE
Add Linux 32-bit build

### ISSUE THREAD

**Issue by sorinello** [mozilla/geckodriver#237]
It seems that there is no 32-bit binary for Linux systems. The one available for download is for 64-bit systems, thus it does not work on 32-bit platform.

Even if 64-bit systems are much more common that 32-bit nowdays, they are not entirely extinct.

**Comment by andreastt** [comment]
They are virtually extinct though. I have not come across a 32-bit CPU in many years. Unless you have compelling reasons why we should support it, I’m tempted to close this.

**Comment by sorinello** [comment]
My rationale is as follows:

* I'm pretty sure that there are companies using older 32-bit machines to do the UI testing. Usually these tasks don't require 64-bit systems with 4 GB RAM
* I am imagining a scenario where the system under test must be a 32-bit platform and tests are run locally
* Having a 64-bit architecture processor does not necessarily imply that the  OS installed is 64-bit. I am imagining a scenario where several 32-bit OS VM's  might be installed on a 64-bit processor system.
* I guess the same rationale is available also for Windows, which will have a 32-bit binary in the next release of geckodriver. Don't imagine Linux is only used on  the server side. There might be testers or developers running Linux desktops on older 32-bit hardware
* I am surprised that no one asked this build before
* Someone from the #Selenium IRC chat told me that I should create a ticket for this (Note: I am not a Selenium official)
* Maybe none of the above are true in a perfect world, and if you don't agree with them, you can close the issue.

**Comment by cgoldberg** [comment]
I'd be hesitant to spend any cycles on speculative needs. (see: YAGNI)

**Comment by sorinello** [comment]
@cgoldberg I think that the problem is a bit more deeper than just to invoke YAGNI. For example, recently, on the xubuntu dev mailing list there was a discussion about dropping the 32-bit build. The thread received a lot of replies, and there is a plethora of reasons given against it. The conclusion was that the topic would be re-discussed in 2018, since it seems a lot of people still download and use 32-bit versions. I am sure the day when 32-bit will be totally slacked is coming, and that day might be near, but I don't feel we are there yet.  

I personally don't have any statistics about the machines geckodriver is running, but from the OS'es point of view, 32-bit is not extinct yet..

**Comment by andreastt** [comment]
I reached out to Google and Sauce Labs to get some actual fact and empiricism into this conversation. 

Google uses 32-bit Windows VMs, which we will provide builds for in 0.11.0, but only have 64-bit Linux. Sauce on the other hand are migrating their 32-bit Linux VMs to 64-bit, and the status as of a few weeks ago is that this was not complete yet.
