### ISSUE TITLE
Actions is malfunctionting 

### ISSUE THREAD

**Issue by tahashinegp** [mozilla/geckodriver#238]
I have written a code for switching tabs in chorme like this : Actions actions= new Actions(driver);
actions.sendkeys(Keys.tab).sendkeys(keys.control).build.perform(). it was working fine after executing 3 4 time its not wrking now. before this i have added driver.getwindowhandle();. i have found this previous work also..

**Comment by andreastt** [comment]
Duplicate https://github.com/mozilla/geckodriver/issues/233
