### ISSUE TITLE
geckodriver doesn't getTitle of initial home page

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#241]
Steps to reproduce:

1. Create a profile with two preferences: `"browser.startup.page", 1` and `"browser.startup.homepage", "https://www.google.co.uk/"`. 
2. Start geckodriver using this profile.
3. Call "getTitle" 

Expected result:

Title of "Google" should be returned.

Actual result:

Empty string returned.

**Comment by shs96c** [comment]
Failing test in Java: 

```
DesiredCapabilities caps = new FirefoxOptions()
      .addPreference("browser.startup.page", 1)
      .addPreference("browser.startup.homepage", pages.xhtmlTestPage)
      .addTo(DesiredCapabilities.firefox());
driver = new FirefoxDriver(caps);
shortWait.until(ExpectedConditions.titleIs("XHTML Test Page"));
```

**Comment by andreastt** [comment]
I can confirm this. We’re likely not injecting the frame script into the first active browser when starting a new session.

**Comment by andreastt** [comment]
I was wrong earlier. It looks like the browser is opened on about:blank and we only wait for the `document.readyState` to reach "complete" on that document. The homepage is then loaded in through… some mechanism, causing a race condition between the new session creation and getting the title.

**Comment by florentbr** [comment]
The browser is probably loading the URL defined in `startup.homepage_override_url`.
I would set the preference `browser.startup.homepage_override.mstone` to `ignore` to disable the override.

**Comment by andreastt** [comment]
We could set the `browser.startup.homepage_override.mstone` pref (we do in the Marionette harness in mozilla-central), but this will only mask the issue. I find that the race condition is still there when setting `startup.homepage_welcome_url` to some URL and `startup.homepage_welcome_url.additional` to an empty string. In other words, this isn’t a problem directly related to spinning up two tabs on startup.

**Comment by andreastt** [comment]
If we think it’s fine to disallow people to set a startup homepage when using geckodriver, I’m fine with making this change.
