### ISSUE TITLE
"firefoxOptions" should be "-moz-firefox-options" to be spec compliant

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#242]
https://w3c.github.io/webdriver/webdriver-spec.html#protocol-extensions states that vendor specific extensions should use a vendor prefix and an optional product name in URLs. To avoid clashes with other products and extensions, it may be best to use something similar for vendor-specific capabilities.

Of course, this means that https://w3c.github.io/webdriver/webdriver-spec.html#capabilities needs to be updated. :)

**Comment by andreastt** [comment]
`firefoxOptions` has now been renamed `moz:firefoxOptions`, which is conformant with the spec’s new definition of ‘extension capabilities’.
