### ISSUE TITLE
form submit done with post?

### ISSUE THREAD

**Issue by mb73** [mozilla/geckodriver#247]
When I am trying to submit a form, my web app tells me “HTTP method POST is not supported by this URL”. That does not happen e.g. with ChromeDriver. Any idea?

Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:30:04 -0700'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160922113459, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=2680, browserVersion=49.0.1, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, device=desktop}]

**Comment by andreastt** [comment]
What command are you using?

**Comment by mb73** [comment]
It's called submit() in ScalaTest.

**Comment by andreastt** [comment]
The W3C WebDriver specification doesn’t implement that. You should file a bug with your language binding for them to backport it using other WebDriver primitives.

**Comment by mb73** [comment]
Sorry, but I don't understand. I should file a bug where? To tell someone at w3c to specify submit should be done with HTTP get instead of post? is that right?

**Comment by andreastt** [comment]
No you got that all wrong. I’ve filed https://github.com/SeleniumHQ/selenium/issues/2854 for you.
