### ISSUE TITLE
get_window_size throws NPE with sel3-beta4 & FF49.0.1

### ISSUE THREAD

**Issue by gempesaw** [mozilla/geckodriver#257]
After some investigation, it looks like this issue is on the selenium side: https://github.com/SeleniumHQ/selenium/issues/2856. But, in case anyone is looking for the issue here: when attempting to run `get_window_size` with `selenium-standalone-server-3.0.0-beta4.jar`, an NPE is thrown. 

``` python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
caps = DesiredCapabilities.FIREFOX
caps["marionette"] = True
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4444/wd/hub',
    desired_capabilities=caps
)
size = driver.get_window_size()
print size
```

[Associated selenium server stacktrace](https://gist.github.com/gempesaw/0d4e7e79d7578382aedc9812d19c9c9f). It works fine when using the Python bindings directly to `geckodriver`, ie with `webdriver.Firefox()` vs `webdriver.Remote()`. It also works fine when using `sel3-beta3.jar` instead of the newer `beta4.jar`.

**Comment by andreastt** [comment]
This is a Selenium bug. We implement the Get Element Rect command, which Selenium should use to extract window dimension information.
