### ISSUE TITLE
Publish 0.10.0 to crates.io?

### ISSUE THREAD

**Issue by frankier** [mozilla/geckodriver#258]
It seems 0.10.0 has been released for some time. Selenium 3.0.0-beta 3 is only compatible with 0.10.0. Would it be possible to publish 0.10.0 to crates.io for easy(er) installation? Thanks :)

**Comment by andreastt** [comment]
You mean for installation through `cargo install geckodriver`?

**Comment by jgraham** [comment]
We can, although the received wisdom I had was that `cargo install` was really intended for rust development tools only (like `rustfmt` or `racer`). But now `ripgrep` is `cargo install`able, so I don't know if there's consensus on that, really.

In any case "download a `tar.gz` and extract it to anywhere on your `$PATH` doesn't seem like it's too hard?

**Comment by andreastt** [comment]
@jgraham Can we retract the current 0.8.0 release from crates.io and close this?

https://github.com/mozilla/geckodriver/issues/384#issuecomment-265849989

**Comment by andreastt** [comment]
Ping @jgraham again.

**Comment by legoktm** [comment]
Removing the older release from crates.io seems like moving in the wrong direction to me. I have an interest in packaging geckodriver for Debian so we can use it [at Wikimedia](https://phabricator.wikimedia.org/T137797). The [proposed rust packaging policy](https://wiki.debian.org/Teams/RustPackaging/Policy) is entirely based around being installable via cargo. So it would be nice if newer versions of geckodriver could be published on crates.io.

**Comment by andreastt** [comment]
I can’t find anything in Debian’s packaging policy that requires a crate to be installable via `cargo install`. The purpose of Debian packaging is _to not_ require third-party tooling such as cargo to be present on the system, neither for building (“[a]pplication packages must not allow Cargo to access the network when building”, which directly contradicts how `cargo install` works) or installation.

**Comment by legoktm** [comment]
Right, sorry I was unclear. I meant that all of the automated tooling is based around being installable via cargo. It will always be possible to create a package manually, but it would be easier for me to do it using those tools, hence my comment :)

**Comment by andreastt** [comment]
We are not going to publish geckodriver in the future to crates.io on the grounds that it is not a software library.

Packaging geckodriver for Debian is possible by checking out the git repository or fetching the source tarball from the releases section. One of these options is very likely what you want to do if you intend to package geckodriver for Debian (which by the way would be very welcome!).

**Comment by legoktm** [comment]
OK, gotcha. Should <https://crates.io/crates/geckodriver> be removed to avoid confusion and prevent people from downloading older releases?
