### ISSUE TITLE
Is geckodriver's find element response object deliberately different?

### ISSUE THREAD

**Issue by gempesaw** [mozilla/geckodriver#259]
(Using FF49.0.1 and/or FF48.0.2, Geckodriver 0.10.0, sel3-beta4 standalone jar.)

Hi, thanks for all the hard work on geckodriver! I've found that the response to find element (`POST /session/:sessionId/element`) is different between geckodriver and the selenium standalone server jar.

From geckodriver, the key that corresponds to the element ID has its own UUID on it:

```
REQ: POST, session/0a0af85d-6556-c74b-b324-697a98287f41/element, {"value":"div","using":"css selector"}
RES: {
    "value": {
        "element-6066-11e4-a52e-4f735466cecf": "e1ae9c33-85eb-2245-9273-af7da455aa75"
    }
}
```

whereas from RemoteDriver via standalone server jar, the key is simply `ELEMENT`:

```
REQ: POST, session/beabd546-b1a4-4cc0-baf6-bdd57c7d1332/element, {"value":"div","using":"css selector"}
RES: {
    "class": "org.openqa.selenium.remote.Response",
    "hCode": 1200604265,
    "sessionId": "beabd546-b1a4-4cc0-baf6-bdd57c7d1332",
    "state": "success",
    "status": 0,
    "value": {
        "ELEMENT": "0"
    }
}
```

Um, any idea if this change is intended? Will this be the response format for `geckodriver` going forward such that I should handle either response formats? Probably not the right place to ask, but any idea if Selenium3 will be moving to this response format? It's the first I've seen the new format so it surprised me. Thanks again!

**Comment by andreastt** [comment]
geckodriver is an implementation of the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html), which is pointed out in the README, and consequently does not implement the Selenium JSON wire protocol, so this change is expected.

As far as I understand Selenium aims to provide a Selenium-to-WebDriver shim that lets Selenium 3 clients speak to both W3C WebDriver and Selenium WebDriver remotes. I believe much of this is already available in the beta builds of Selenium 3. Individual language bindings have to varying degree also done work on this.

**Comment by gempesaw** [comment]
Oh, I wasn't aware that the WebDriver spec and the JSONWireProtocol deviated like this. Thanks for the information and sorry for the trouble. Cheers!
