### ISSUE TITLE
Unable to set Firefox --start-debugger-server option

### ISSUE THREAD

**Issue by jasonLaster** [mozilla/geckodriver#260]
When I upgraded to selenium 3, the `--start-debugger-server` is no longer passed in.

```
/Applications/Firefox.app/Contents/MacOS/firefox-bin --marionette --profile /var/folders/wn/0pxdh48551d4xw9h93k3bb600000gn/T/rust_mozprofile.q90c3eu8AY8E
```

Here is where i try to set the [binary argument](https://github.com/devtools-html/debugger.html/blob/master/bin/firefox-driver.js#L20-L22). The docs make it seem like I should now set the _argument_ as an `Option` [here](https://github.com/devtools-html/debugger.html/blob/master/bin/firefox-driver.js#L39-L40), but i don't see an args field or setArgument function.

I tried updating `setFirefoxBinary` to include setting builder arguments [here](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/firefox/index.js#L437), which looked close but I concluded it probably wasn't effectively passing the arguments to gecko-driver, so i stopped.

``` patch
+  if (binary.args_.length > 0) {
+    this.addArguments.apply(this, binary.args_);
+ }
```

Thanks in advance for the help!

**Comment by jgraham** [comment]
geckodriver currently takes arguments from the `firefox_args` capability. In the future this will change to a 'moz:firefoxOptions` capability with an `args` key. I'm not exactly sure how this maps to the selenium API.

**Comment by andreastt** [comment]
`moz:firefoxOptions` has now been added, which can be used for passing in arguments to the Firefox binary. See the README for documentation.
