### ISSUE TITLE
Change New Session to take overhauled capabilities

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#262]
https://github.com/w3c/webdriver/pull/327

**Comment by andreastt** [comment]
I think we may want to delay the introduction of `firstMatch` and `alwaysMatch` as long as we can. geckodriver has so far been on the forefront of introducing [W3C WebDriver](http://w3c.github.io/webdriver/webdriver-spec.html) functionality, but I don’t think we want to be the first implementing this.

**Comment by AutomatedTester** [comment]
this has been done
