### ISSUE TITLE
Not taking a full screenshot

### ISSUE THREAD

**Issue by khj1218** [mozilla/geckodriver#265]
I'm using python selenium 3.0.0b and gechodriver 0.10.0 w/ Firefox 49 and tried to take a screenshot of a page, but it's not taking a full screenshot any more. The screenshot was taken for only visible section in the window.

```python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

caps = DesiredCapabilities.FIREFOX
caps["marionette"] = True
caps["binary"] = '/usr/bin/firefox'
driver = webdriver.Firefox(capabilities=caps)
driver.get_screenshot_as_png()
```

**Comment by andreastt** [comment]
This is by design. The WebDriver specification makes a compromise which is implementable in all browsers to take a screenshot of the visible portion of the viewport.

I think we might want to add a geckodriver/Marionette extension command to get the full document screenshot, however.
