### ISSUE TITLE
Can't install extension with 0.11.1 using Selenium v3.0.0-beta-3

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#272]
Hello,
has something changed in how extensions should be installed between 0.10 and 0.11.1 that aren't insync with Selenium? We are using Selenium Javascript version latest beta (3), and for 0.10 it works fine, but when we switch to 0.11.1 [the extension](https://github.com/firebug/har-export-trigger) doesn't get installed (I'm testing using Firefox 49.0). Switching back to 0.10 it works again.

Is there a way now when using Selenium Javascript flavour to turn on logging for Geckodriver?

Best
Peter

**Comment by andreastt** [comment]
If you consult the [changelog](https://github.com/mozilla/geckodriver/blob/master/CHANGES.md) you will see that the accepted capabilities changed in 0.11. Specifically, the `firefox_profile` capability was replaced by a `moz:firefoxOptions` dictionary (akin to `chromeOptions`). You can see the [README](https://github.com/mozilla/geckodriver#firefox-capabilities) on how to use it.

The tl;dr is that you need to pass `{"moz:firefoxOptions": {"profile": <base 64 encoded string>}}` instead of `{"firefox_profile": <base 64 encoded string>}`.

**Comment by tobli** [comment]
It seems this is not yet present in the node.js selenium implementation: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/firefox/index.js#L139 still uses the old ```firefox_profile```capability.

**Comment by soulgalore** [comment]
eh, the tl;dr is that you don't follow semantic versioning, but that's fine in a way since your goal is to reach 1.0 when you fully supports the webdriver spec (?) but I think you should make that clear in the README. Also you should make it clear in the CHANGELOG when you break support for Selenium or maybe Selenium users isn't your main goal with the Geckodriver, then make that clear in the README too.

**Comment by jgraham** [comment]
Actually we are following semver (or the usual Rust variant). In semver any 0.Y.Z release is considered backwards incompatible with any earlier release. In the Rust variant changes to the patch level (Z) are considered backwards compatible (so 0.11.0 and 0.11.1 are compatible releases but 0.12.0 is not).

I also think the changelog covered this issue.

**Comment by andreastt** [comment]
Yes, this is indeed covered in [CHANGES.md](https://github.com/mozilla/geckodriver/blob/master/CHANGES.md#0110-2016-10-10). I also sent [an email to tools-marionette@](https://groups.google.com/forum/#!topic/mozilla.tools.marionette/azXL4a5ntfo) and [a blog post](https://sny.no/2016/10/geckodriver-0.11.1) about it.

**Comment by smatei** [comment]
Hi @andreastt,

I want to start Firefox from marionette with some extension installed.

I have created a separate profile, installed one extension on that profile, then created a zip

C:\Users\Stefan\AppData\Roaming\Mozilla\Firefox\Profiles\m5gpjt1w.selenium (profile folder)
C:\Users\Stefan\AppData\Roaming\Mozilla\Firefox\Profiles\m5gpjt1w.selenium.zip

According to your docs ( https://github.com/mozilla/geckodriver/blob/master/README.md#firefox-capabilities - Base64-encoded zip of a profile directory to use as the profile for the Firefox instance. This may be used to e.g. install extensions or custom certificates. ), I have set the base64 encoded content of the zipped profile, along with user agent, log level and proxy settings.

`
		
                JsonObject prefs = new JsonObject();
		JsonObject ua = new JsonObject();
		prefs.add("prefs", ua);    
		ua.addProperty("general.useragent.override", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36");           

		JsonObject log = new JsonObject();
		log.addProperty("level", "debug");
		prefs.add("log", log);

		File file = new File("C:\\Users\\Stefan\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\m5gpjt1w.selenium.zip");
		byte[] content = FileUtils.readFileToByteArray(file);
		
		prefs.addProperty("profile", ByteString.of(content).base64());
		
		required.setCapability("moz:firefoxOptions", prefs);

		JsonObject json = new JsonObject();
		json.addProperty("proxyType", "MANUAL");
		json.addProperty("httpProxy", aHost);
		json.addProperty("httpProxyPort", aPort);
		json.addProperty("sslProxy", aHost);
		json.addProperty("sslProxyPort", aPort);
		
		required.setCapability("proxy", json);  
`

Anyway, when Firefox starts, there is no extension installed (user agent, log level and proxy are set fine). Is there anything I do wrong? Is there any other way to do this? 

Best Regards,
Stefan Matei

**Comment by andreastt** [comment]
The Base64 encoded string isn’t meant to be passed directly to the `moz:firefoxOptions` key. See the documentation.

**Comment by smatei** [comment]
@andreastt 
I have added it to "profile", then profile added to moz: firefoxOptions. Here is what I send:

> [{proxy={"proxyType":"MANUAL","httpProxy":"192.12x.19x.7x","httpProxyPort":1212,"sslProxy":"192.12x.19x.7x","sslProxyPort":1212}, moz:firefoxOptions={"prefs":{"general.useragent.override":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36"},"log":{"level":"debug"},"profile":"UEsDBBQAAAAAAE+EWEkAAAAAAAAAAAAAAAASAAAAbTVncGp0MXcuc2VsZW5pd........................NsFBAAAAA=="}}]

This is what I have understood from https://github.com/mozilla/geckodriver/blob/master/README.md#firefox-capabilities

> Base64-encoded zip of a profile directory to use as the profile for the Firefox instance. This may be used to e.g. install extensions or custom certificates. 

Is there any more documentation? Can you please give me a working sample (any language python, java...)?

**Comment by andreastt** [comment]
You are passing a Base64 encoded string of a zip file though.
