### ISSUE TITLE
geckodriver sometimes returns "element not visible"

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#275]
We removed "element not visible" from the spec a while ago. The correct response is probably "element not interactable" with an explanation that the element isn't visible.

**Comment by naveenmehra** [comment]
Facing similar issues Object.org.openqa.selenium.NoSuchElementException , Web-driver version: '3.4.0', Firefox version 53.0.2

**Comment by andreastt** [comment]
We fixed this with the 0.16.0 release.
