### ISSUE TITLE
Does  geckodriver have stable release for selenium 3.0？

### ISSUE THREAD

**Issue by HackToday** [mozilla/geckodriver#278]
As selenium now have stable release 3.0, when geckodriver will have stable release version for that ？

From github releases, I am not quite sure which version is stable for selenium 3.0

**Comment by TQL1337** [comment]
`geckodriver-v0.11.1`

I'm using right now. Seems to work fine.

**Comment by davehunt** [comment]
Until there is a stable release, you should be using the latest alpha release, which is currently 0.11.1. When a new geckodriver version is released there may be a short period of time where the Selenium language bindings are incompatible, but we're working to limit the impact of that. I believe this should be less likely after the 0.12 release, which will contain further changes to capabilities according to recent changes to the WebDriver spec.

**Comment by HackToday** [comment]
Ok. @davehunt  Seems stable release in geckodriver still a long term.
