### ISSUE TITLE
canot unpack release drive archives

### ISSUE THREAD

**Issue by PavelNiedoba** [mozilla/geckodriver#279]
I can unzip 
https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
but when i try to untar it:

tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

ps. I found that it's the executable itself

would you mind: removing the .tar from archive name
add .bin to zipped filename ?
just to follow conventions?

**Comment by jgraham** [comment]
jgraham@luna:~/Downloads$ gunzip geckodriver-v0.11.1-linux64.tar.gz
    jgraham@luna:~/Downloads$ tar xf geckodriver-v0.11.1-linux64.tar
    jgraham@luna:~/Downloads$ ./geckodriver 
    1476456020200	geckodriver	INFO	Listening on 127.0.0.1:4444

This works afaict.
