### ISSUE TITLE
Command line option to start firefox hidden on windows

### ISSUE THREAD

**Issue by aplicacionamedida** [mozilla/geckodriver#281]
There is a use case that it's not possible with geckodriver. Suppose the situation that someone wants to start firefox hidden on windows. This feature is possible on Linux setting an environment variable DISPLAY and using Xvfb. On windows the only solution is to get a handle for the window, for example using the title, and then to call the win32 API function "ShowWindow" once the browser is started. Using Autohotkey a programmer has the functions "WinGet" and  "WinHide". The trick is to set an UUID as the title of the browser to identify the window easily.  However it's not possible on windows to start directly a hidden firefox using geckodriver. 

This is an interesting feature to avoid interruptions and annoyances during the interaction of the user with the desktop environment.

**Comment by andreastt** [comment]
I would suggest filing a bug with Firefox directly to support this. It’s not something geckodriver on its own can solve.
