### ISSUE TITLE
Getting below error with Selenium 3.0 and firefox 47

### ISSUE THREAD

**Issue by AnayaGoyal** [mozilla/geckodriver#283]
```
[TestNG] Running:
  C:\Users\chinar.goyal\AppData\Local\Temp\testng-eclipse--1651797521\testng-customsuite.xml

launching firefox browser
1476778667434	geckodriver	INFO	Listening on 127.0.0.1:14230
Oct 18, 2016 1:47:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1476778667917	mozprofile::profile	INFO	Using profile path C:\Users\CHINAR~1.GOY\AppData\Local\Temp\rust_mozprofile.ZLF8DVrTt8FL
1476778667967	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1476778668007	geckodriver::marionette	INFO	Connecting to Marionette on localhost:49527
1476778669303	Marionette	INFO	Listening on port 49527
[GFX1-]: [D3D11] create component blender failed: 0x80070057, 0
[GFX1-]: [D3D11] create component blender failed: 0x80070057, 0
Oct 18, 2016 1:47:52 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

Code: 
```
String driverPath = "<path to gecko driver executable>";
	public WebDriver driver;
	
	@Test
	public void launchBrowser() {
		System.out.println("launching firefox browser"); 
		System.setProperty("webdriver.gecko.driver", "D:\\Selenium\\Driver\\GeckoDriver\\geckodriver.exe");
		
		driver = new FirefoxDriver();
	}

	@Test
	public void openApplication() {
		driver.navigate().to("https://www.google.com");
	}
```

**Comment by andreastt** [comment]
I don’t see an error. Closing.

**Comment by AnayaGoyal** [comment]
I am still getting above error.

**Comment by davehunt** [comment]
> I am still getting above error.

There is no error in the output you have pasted. Please describe the issue you are having with GeckoDriver, or provide some output that demonstrates your issue.

**Comment by Siddharathsharma** [comment]
I am also receiving same error. 

1479545725857	geckodriver	INFO	Listening on 127.0.0.1:25260
Nov 19, 2016 2:25:26 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1479545726598	mozprofile::profile	INFO	Using profile path C:\Users\SIDDHA~1\AppData\Local\Temp\rust_mozprofile.UhKJg6YEtqQb
1479545726608	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1479545726622	geckodriver::marionette	INFO	Connecting to Marionette on localhost:49623
1479545727878	Marionette	INFO	Listening on port 49623
Nov 19, 2016 2:25:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
**Unable to load webdriver firefox · Issue #2577 · SeleniumHQ/selenium · GitHub**

For the code 👎 
package first;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class Testing1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		///https://github.com/mozilla/geckodriver/releases
		System.setProperty("webdriver.gecko.driver","C:\\geckodriver\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.get("https://github.com/SeleniumHQ/selenium/issues/2577");
		System.out.println(driver.getTitle());
				}

}
Configuration :- 
Selenium 3.0
Mozilla 50 V
Java 1.8

Please suggest, what action i should take further.

**Comment by jgraham** [comment]
This seems like a selenium problem rather than a bug in geckodriver. I suggest contacting the selenium project.

**Comment by BasavarajRathod** [comment]
I am also getting the same error 
Selenium 3.01
Mozilla 50 v
java 1.8

[1480425865161geckodriverINFOListening on 127.docx](https://github.com/mozilla/geckodriver/files/619070/1480425865161geckodriverINFOListening.on.127.docx)

**Comment by BasavarajRathod** [comment]
1480425865161	geckodriver	INFO	Listening on 127.0.0.1:45542
Nov 29, 2016 6:54:25 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
1480425865878	mozprofile::profile	INFO	Using profile path C:\Users\Basu\AppData\Local\Temp\rust_mozprofile.0pcbwUB6hMZy
1480425865883	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1480425896014	geckodriver::marionette	INFO	Connecting to Marionette on localhost:50204
1480425898590	Marionette	INFO	Listening on port 50204
Nov 29, 2016 6:55:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

I am also getting the same error
Selenium 3.01
Mozilla 50 v
java 1.8

Please fix it argent  and Thanks advance

**Comment by VikasSalunke** [comment]
2125988	geckodriver	INFO	Listening on 127.0.0.1:32468
1499842126381	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox with args ["-marionette"]
1499842130360	Marionette	INFO	Listening on port 43966
Jul 12, 2017 12:18:50 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1499842177170	Marionette	INFO	New connections will no longer be accepted
