### ISSUE TITLE
Implement Status endpoint

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#286]
https://w3c.github.io/webdriver/webdriver-spec.html#status

**Comment by andreastt** [comment]
Since this is a spec addition we need to add it to https://github.com/mozilla/webdriver-rust/ first. Then implement the marshaling for those in geckodriver after you upgrade the webdriver dependency.

**Comment by AutomatedTester** [comment]
This will need to be implemented after the next WebDriver-Rust release otherwise GeckoDriver will no longer compile.

**Comment by vkatsikaros** [comment]
A draft for the geckodriver side of the change (doesn't compile yet). Note: to test compiling I merged [AutomatedTester:close_window](https://github.com/AutomatedTester/wires/tree/close_window) in my local geckodriver.

Now, when it comes to changing the geckodriver side I tried https://github.com/vkatsikaros/geckodriver/tree/286/try1 .I inversed the `match`es as mentioned on [IRC](http://logs.glob.uno/?c=mozilla%23ateam&s=1+Nov+2016&e=14+Nov+2016#c1082071). 

- I get a compilation error
```
$ cargo build
   Compiling geckodriver v0.11.1 (file:///home/vag/projects/geckodriver)
error[E0308]: mismatched types
   --> src/main.rs:163:66
    |
163 |     let listening = try!(webdriver::server::start(addr, handler, extension_routes())
    |                                                                  ^^^^^^^^^^^^^^^^^^ expected reference, found struct `std::vec::Vec`
src/main.rs:163:21: 164:60 note: in this expansion of try! (defined in <std macros>)
    |
    = note: expected type `&[(hyper::method::Method, &str, marionette::GeckoExtensionRoute)]`
    = note:    found type `std::vec::Vec<(hyper::method::Method, &'static str, marionette::GeckoExtensionRoute)>`

error: aborting due to previous error

error: Could not compile `geckodriver`.
```
I am unsure how to debug this (is it something I caused or something other commits caused). 

- In IRC it was mentioned that `Basically the idea is that Status is meant to be reachable without a Marionette connection, i.e. when self.connection is None.` However, in the spec in [4. Nodes](https://w3c.github.io/webdriver/webdriver-spec.html#nodes) I read about `Intermediary Node` and `Endpoint Node` nodes. Also in [7.3 Status](https://w3c.github.io/webdriver/webdriver-spec.html#status) mentions 
```
Let body be a new JSON Object with the following properties:

ready
    The remote end’s readiness state. 
message
    An implementation-defined string explaining the remote end’s readiness state. 
```
So if a Marionette connection is not needed (ie no firefox launched) for the Status command, does this mean that geckodriver is an `Endpoint Node`?

- Silly question: what webdriver response should I return? I got a bit confused on which `WebDriverResponse` I should pick. Just to make the draft compile, I faked it by returning [an error](https://github.com/vkatsikaros/geckodriver/blob/286/try1/src/marionette.rs#L422).

**Comment by andreastt** [comment]
Resolved by https://github.com/mozilla/geckodriver/commit/3dbe0a93a7ec7525ed6907f853fc6b6af7564a7e.
