### ISSUE TITLE
Selenium version vs. geckodriver version

### ISSUE THREAD

**Issue by qqilihq** [mozilla/geckodriver#287]
The [releases list](https://github.com/mozilla/geckodriver/releases) says "Only upgrade to this version if you are using Selenium 3 beta releases." for v.0.10.0.

However, how about v.0.11.0 and v.0.11.1. With which Selenium versions can they be used? 3 only, or also 2.x?

**Comment by davehunt** [comment]
From 0.10 on, only Selenium 3.0 is supported. This is due to changes in the various Selenium client bindings. We should make this clear in the README.

**Comment by qqilihq** [comment]
Thank you for clarifying. Would be good indeed to have this in the README.

**Comment by andreastt** [comment]
I don’t really want to go through the extra labour of mapping Selenium versions against geckodriver for each language binding. This feels like a job for the Selenium project.
