### ISSUE TITLE
driver.find_element(xpath: '//body').text doesn't work well

### ISSUE THREAD

**Issue by Khrol** [mozilla/geckodriver#288]
Selenium 3.0
Ruby
Firefox 49.0.1
Driver v0.11.1

Steps to reproduce:
1. Clone https://github.com/Khrol/rails_tests_demo
2. Run rails app `bundle exec rails s`
3. Change driver to Firefox in `./tests/1_ui.rb`
3. Run test `bundle exec ruby ./tests/1_ui.rb`

Text is somehow equal to "Country" instead of "Average rate:\n7.5".

Video: https://youtu.be/6pTopImPrCw

**Comment by drobota** [comment]
I think that is because of https://github.com/mozilla/geckodriver/issues/96
You get result from previous page :)

**Comment by Khrol** [comment]
@drobota agree. Closing as duplicate.
