### ISSUE TITLE
Latest version is not available in nuget.org

### ISSUE THREAD

**Issue by minoseah629** [mozilla/geckodriver#290]
Nuget.org currently use 0.9.0 as the last package available. 

Please put the latest on nuget.org 

https://www.nuget.org/packages/WebDriver.GeckoDriver/

**Comment by andreastt** [comment]
I have no idea what Nuget.org is. We have nothing to do with it.

**Comment by minoseah629** [comment]
I would appreciate if you would investigate the issue with other contributors of your group instead of straight dismissing this.
