### ISSUE TITLE
Generate checksums of downloadable files

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#292]
For security and auditing reasons we should generate a list of checksums of the downloadable files we offer from the geckodriver project.

**Comment by theforgottenviking** [comment]
Couldn't agree more. I rely heavily on checksums while troubleshooting. Thanks for creating the issue!

**Comment by shwoodard** [comment]
Please?!  You're shipping binaries here that a lot of people rely on in secure environments.  Would be nice to know we got what you wanted us to have.

**Comment by andreastt** [comment]
Patches accepted (-:

**Comment by shwoodard** [comment]
Hmm... I think it's just a matter of computing the sha before you upload~

**Comment by jgraham** [comment]
tbh the threat model here seems very limited. Does publishing a hash of the file defend against anything except accidentally corrupt downloads? The files are served over https from a well-known location and any attacker with access to the server could equally replace the files containing the hashes.

I'm happy to publish the hashes, but if there's some big security win it isn't obvious to me.

**Comment by andreastt** [comment]
I’m somewhat concerned by the fact that geckodriver gets re-distributed through 3rd party sources such as the NuGet .NET package manager. There also exists a Node.js NPM module that automatically downloads geckodriver. In both these cases it would be good to test the downloads against the known-good checksums, but in principle I agree with you: the actual attack surface here is small. The benefit mostly lies in auditing.

**Comment by jgraham** [comment]
I think that scenario only makes sense if there exists a user who

* Installs geckodriver using some third party tool
* Has access to the zip/tar file downloaded by that tool
* Has the knowledge and ability to generate a checksum of that download
* Can download the checksum file from our releases page
* Cannot simply download the package file from our releases page (e.g. because the download is too large).

I doubt such a user exists, particularly because geckodriver is so small (by modern standards). There might be a stronger argument relating to a 4Gb ISO file or similar. If you don't trust the third party tool to do the right thing here then why do you trust it not to execute malicious code itself?

**Comment by theforgottenviking** [comment]
I see this as an opportunity to help standardize the driver efforts within the testing community. 

Things that would help with that is a parseable file, preferably JSON. This JSON file would contain all the releases, broken out by LATEST and then VERSION(s). That object would contain the path to the driver and its checksum. This would allow those of us in the community to develop efficient driver managers that don't rely on heavy and often times annoying HTML parsers.

**Comment by andreastt** [comment]
Common practice in this area is to provide, per release, one PGP-signed file per archive or one file listing the checksums for all archives. We should try very hard not to invent a new standard. One PGP-signed .asc file per archive we publish will ensure existing tooling in this area can be used.

Because third party resources may start distributing geckodriver at any point without our approval (they don’t need it), there should be a way to verify that the distributed archives aren’t corrupted in the process. When an archive is redistributed, most serious package managers will do implicit checksum verification on behalf of the user. By PGP-signing the checksums, it is possible to verify that the checksum file too was not maliciously manipulated (web of trust, &c.).

**Comment by bloudraak** [comment]
Checksums offer no guarantees in terms of security and auditing. It also eliminates the ability of many security products to prove its integrity and validate its reputation.  Once binaries on the services are compromised due to unauthorized access, there is no automated way to inform security products that the binary running on their systems is impacted.  On Windows you'll need to look at [Authenticode Code Signing](https://blogs.msdn.microsoft.com/ieinternals/2011/03/22/everything-you-need-to-know-about-authenticode-code-signing/).  Mozilla already digitally signs Firefox binaries.

**Comment by whimboo** [comment]
For reference issue #1116 has been reopened, and will be handle differently.

**Comment by whimboo** [comment]
@andreastt shall we close this issue in favor of #1116?

**Comment by andreastt** [comment]
@whimboo We still need checksums for the downloadable .zips?

**Comment by whimboo** [comment]
We should get those mostly for free I think when building via taskcluster. But sure, lets leave this issue open until https://bugzilla.mozilla.org/show_bug.cgi?id=1372587 has been fixed.

**Comment by andreastt** [comment]
Another thing that was discussed earlier in this thread was PGP signing the checksums so users know they are correct and from an authenticated source, but we can split that out to a separate task after we have checksums accompanying the release notes.

**Comment by whimboo** [comment]
Also this we should have automatically or with very minimal work. For example see: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/. Lookout for both the checksum files of a platform.

**Comment by whimboo** [comment]
With https://bugzilla.mozilla.org/show_bug.cgi?id=1577110 fixed on May 8th we have signed geckodriver binaries for Mac and Windows in our CI. For Linux we have checksum files. That means we will make use of these builds starting with the next 0.27.0 release.

For the latest nightly build see:
https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.geckodriver

**Comment by gtkpr** [comment]
> tbh the threat model here seems very limited. Does publishing a hash of the file defend against anything except accidentally corrupt downloads? The files are served over https from a well-known location and any attacker with access to the server could equally replace the files containing the hashes.
> 
> I'm happy to publish the hashes, but if there's some big security win it isn't obvious to me.

Couldn't you just post the hash in multiple places (i.e. somewhere else in addition to github) as an extra line of defense? Creates much more work for the malicious actor. If the two (or multiple) public checksums do not correspond, then something is amiss.

**Comment by gtkpr** [comment]
> With https://bugzilla.mozilla.org/show_bug.cgi?id=1577110 fixed on May 8th we have signed geckodriver binaries for Mac and Windows in our CI. For Linux we have checksum files. That means we will make use of these builds starting with the next 0.27.0 release.
> 
> For the latest nightly build see:
> https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-central.latest.geckodriver

Where do I find the checksum for any given webdriver?

**Comment by whimboo** [comment]
Given that builds for Windows and MacOS are all signed with a certificate from Mozilla we do not supply checksum files for these builds. Only on Linux were no signing takes place you can find the checksum files (.asc extension) beside the builds. This applies to the above Nightly and also release builds.
