### ISSUE TITLE
OSError: [Errno 20] Not a directory error while starting firefox

### ISSUE THREAD

**Issue by saikirankv** [mozilla/geckodriver#295]
I'm using selenium 3.0, MacOSX, python2.7
I specified the geckodriver path in PATH enviroment variable

`from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
firefox_capabilities['binary'] = '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin'
os.environ["PATH"] = os.path.expanduser('~/geckodriver')
driver = webdriver.Firefox()
`
Its showing

`
---------------------------------------------------------------------------
/environments/test-env/lib/python2.7/site-packages/selenium/webdriver/common/service.pyc in start(self)
     62             self.process = subprocess.Popen(cmd, env=self.env,
     63                                             close_fds=platform.system() != 'Windows',
---> 64                                             stdout=self.log_file, stderr=self.log_file)
     65         except TypeError:
     66             raise

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
   1336 
   1337 

OSError: [Errno 20] Not a directory`

**Comment by andreastt** [comment]
This looks to be a problem with the Selenium Python bindings, and not with geckodriver.
