### ISSUE TITLE
can't pass firefox binary path capability to remote web driver

### ISSUE THREAD

**Issue by ljlm** [mozilla/geckodriver#301]
tried to create an automated test using ff 49 with selenium-standalone-2.48 with marionette 0.11.1
seems that the driver doesn't make use of the capability "firefox_binary" and tries to find the path on the system path (windows):
also tried "binary" with same result:
"Cannot find firefox binary in PATH"

Setting firefox.exe folder on path is not a good option because I am using several versions of firefox on same machine.

**Comment by jgraham** [comment]
The binary is now read from a `moz:firefoxCapabilities` object, as described in the `README` file.
