### ISSUE TITLE
Certificate issue when accessing non-SSL page that contains SSL XHR request

### ISSUE THREAD

**Issue by green-mdoerflinger** [mozilla/geckodriver#306]
I am running selenium webdriver automation on Windows 10 using geckodriver 0.11.1 and Firefox 49.0.2 with selenium-webdriver 3.0.1 and Java 8. 

My test opens a page thru HTTP (Unfortunately i am not allowed to publish the link used). The page itself sends a XHR request to an HTTPS Url. These requests fail with a certificate error:
```
<URL> uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

Error code: SEC_ERROR_UNKNOWN_ISSUER
```

Here is a screenshot of the network tab in the firefox debugger. 
![capture1](https://cloud.githubusercontent.com/assets/10849280/19758591/11be7da0-9c29-11e6-9d1c-fb837141f3a7.png)

The certificate is a Thawte certificate and in regular firefox sessions its accepted without a hitch. 

![capture2](https://cloud.githubusercontent.com/assets/10849280/19758633/41d2a2d2-9c29-11e6-850a-b987800dab8b.png)

Can you find out what is causing this issue? The problems only appears on Windows 10. The same code runs fine on Windows 7 and OSX 10.11 using the same version of the tools involved. 

Thanks,
Marc

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/93.

**Comment by green-mdoerflinger** [comment]
The certificate in this case was not a self-signed certificate. Do you think its the same issue?

**Comment by andreastt** [comment]
That sounds like a cross-site scripting problem. Exactly how do you send an XHR request? From the page itself, or from an injected script using geckodriver?

**Comment by green-mdoerflinger** [comment]
The request is sent from the page itself. How exactly i do not know, as i did not implement it myself and the code is minified. :( 
Everything works fine when the browser is not controlled by webdriver. The issue appears only when accessing the page with the browser being controlled by Webdriver and on Windows 10 (W7 and OSX work fine). 

Once i saw its a HTTPS request and that the certificate is declined, i thought it might have something to do with how the firefox profile is set up when creating the webdriver instance.

**Comment by green-mdoerflinger** [comment]
Can you provide me with a email or some other (non public) way to contact you, then i can send you a sample Java code to reproduce the issue.

**Comment by green-mdoerflinger** [comment]
@andreastt can you please provide me with a non-public way of contacting you (email, skype, ...) so i can send you sample code to reproduce the issue. Thanks.

**Comment by andreastt** [comment]
Please provide something that is publicly accessible.

**Comment by green-mdoerflinger** [comment]
@andreastt unfortunately our client does not allow me to do that at this moment. i will have to come back to you on that issue later.

**Comment by green-mdoerflinger** [comment]
I investigated further into the issue. I think it has to do with the preference 'security.fileuri.strict_origin_policy'. I tried to override it manually in the code to false to make sure it does not interfere any more, but there is no change in the behavior. 
Is it possible that settings of preferences on FirefoxProfile is not working properly yet?
