### ISSUE TITLE
Protractor is not compatible with geckodriver, unable to wait for angularjs controls on UI

### ISSUE THREAD

**Issue by vijaysp77** [mozilla/geckodriver#307]
I am using protractor on top of iWebDriver in c# selenium, geckodriver works fine if I use plain IWebDriver but if it comes with NgWebDriver (Protractor) then it gets fail, shows plugin-container exe is stopping firefox pop-up. Error as 
Error occurred with message : Error in Login Document was unloaded during execution (UnexpectedJavaScriptError)

**Comment by andreastt** [comment]
This is a totally unactionable issue. Closing.
