### ISSUE TITLE
Problem with more than one same elements in DOM

### ISSUE THREAD

**Issue by KAMISHEVFOREVER** [mozilla/geckodriver#309]
Hello,

Recently we upgraded to Selenium 3.0.1 with FirefoxDriver backed by gecodriver 0.1.11. After the upgrade we found a problem with By.linkText locator, In Selenium 2 it was selecting the first VISIBLE element, where in Selenium 3 (geckodriver) it selects first in the DOM (no matter visible or not).

Step to reproduce:
```html
<html>
  <body>
    <a href="#" id="hiddenLink" style="display: none">Text</a>
    <a href="#" id="visibleLink">Text</a>
  </body>
</html>
```

Try By.linkText("Text") and returned element is the first not visible one.

Regards,
SK

**Comment by andreastt** [comment]
(Un)fortunately the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) does not take into account visibility for element retrieval, so this is an expected change when using geckodriver.

**Comment by KAMISHEVFOREVER** [comment]
Hi andreastt,

Thanks for fast response from your side. I just want to add that in Selenium 2 + firefoxdriver it(By.linkText) was selecting the first VISIBLE element in UI and now we fix this problem with changing geckodriver with another (no matter chrome or ie, in our case chromedriver). You are absolutely right for the spec, but we will be very happy if Firefox begin to support some of nice old extras : )

Regards,
SK
