### ISSUE TITLE
geckodriver v0.11.1 is not showing up from NuGet package in Visual Studio

### ISSUE THREAD

**Issue by rtpd01** [mozilla/geckodriver#311]
Can someone please make it available in Nuget package download from Visual Studio? The current available version is v0.9.0.  Would like to get the newer version through Nuget package download in VS.

Thanks.

**Comment by andreastt** [comment]
We don’t manage the Nuget entry. We __do not__ recommend using unsolicited binaries from foreign sources other than https://github.com/mozilla/geckodriver/releases.
