### ISSUE TITLE
Building geckodriver on FreeBSD fails.

### ISSUE THREAD

**Issue by jackmaco** [mozilla/geckodriver#313]
$ fetch https://github.com/mozilla/geckodriver/archive/v0.11.1.tar.gz
v0.11.1.tar.gz                                100% of   33 kB  257 kBps 00m00s
$ tar -xzvf v0.11.1.tar.gz
x geckodriver-0.11.1/
x geckodriver-0.11.1/.gitignore
x geckodriver-0.11.1/.travis.yml
x geckodriver-0.11.1/CHANGES.md
x geckodriver-0.11.1/Cargo.lock
x geckodriver-0.11.1/Cargo.toml
x geckodriver-0.11.1/LICENSE
x geckodriver-0.11.1/README.md
x geckodriver-0.11.1/build.sh
x geckodriver-0.11.1/ci.sh
x geckodriver-0.11.1/i686-trusty/
x geckodriver-0.11.1/i686-trusty/Dockerfile
x geckodriver-0.11.1/src/
x geckodriver-0.11.1/src/capabilities.rs
x geckodriver-0.11.1/src/logging.rs
x geckodriver-0.11.1/src/main.rs
x geckodriver-0.11.1/src/marionette.rs
x geckodriver-0.11.1/src/tests/
x geckodriver-0.11.1/src/tests/profile.zip
$ ls
geckodriver-0.11.1      v0.11.1.tar.gz
$ cd geckodriver-0.11.1/
$ ls
CHANGES.md      Cargo.lock      Cargo.toml      LICENSE         README.md       build.sh        ci.sh           i686-trusty     src
$ sh build.sh
+ main
+ TOOLCHAIN=stable
+ [ ! -z '' ]
+ rustup_install stable
+ export 'PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/paul/bin:/home/paul/.cargo/bin'
+ curl https://sh.rustup.rs -sSf
+ sh -s -- -y '--default-toolchain=stable'
info: downloading installer
info: syncing channel updates for 'stable-x86_64-unknown-freebsd'
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'rust-docs'
info: downloading component 'cargo'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'rust-docs'
info: installing component 'cargo'
info: default toolchain set to 'stable'

  stable installed - rustc 1.12.1 (d4f39402a 2016-10-19)

+ print_versions
+ rustc -V
rustc 1.12.1 (d4f39402a 2016-10-19)
+ cargo -V
cargo 0.13.0-nightly (109cb7c 2016-08-19)
+ rustup_target_add
+ rustup target list
+ grep -E ' \((default|installed)\)'
x86_64-unknown-freebsd (default)
+ '[[' '==' i686-pc-windows-gnu ]]
build.sh: [[: not found
+ cargo_config
+ local prefix
+ return
+ cargo_build
+ local mode
+ [ -z '' ]
+ mode=debug
+ local modeflag
+ [ debug '==' release ]
+ cargo build --target
error: Expected argument for flag '--target' but reached end of arguments.

Usage:
    cargo build [options]
$

**Comment by andreastt** [comment]
The build.sh script is not meant to be used for compilation locally. Please use the standard Rust toolchain as explained in the _Building_ section of the [README](https://github.com/mozilla/geckodriver#building).

**Comment by jackmaco** [comment]
Ah works perfect now thank you, should I upload my binary compiled driver to you somehow?

**Comment by andreastt** [comment]
If you would like to experiment with adding a Travis CI cross compile build from Linux to FreeBSD, you would be more than welcome to do so. For us to include FreeBSD amongst the officially released binaries, we will need to build it off the same infrastructure we use to build our other binaries.

**Comment by teamblubee** [comment]
Howdy, did this happen? Setting up a cross build for FreeBSD?

**Comment by andreastt** [comment]
Still not building for FreeBSD in CI.
