### ISSUE TITLE
Not compatible with FF49

### ISSUE THREAD

**Issue by jpschewe** [mozilla/geckodriver#314]
With the latest release, 0.11.1, I'm unable to use the driver with FF49 and selenium. When the Firefox window comes up I look at the extensions and I see that it says that the extension 3.0.0 beta2 is not compatible with Firefox 49.

Is there a way to work around this?

**Comment by andreastt** [comment]
Where does it say this?

Also, since this issue is totally unactionable I’m closing it.

**Comment by jpschewe** [comment]
Here's a screenshot of what I see:
![ff49-webdriver](https://cloud.githubusercontent.com/assets/226585/19832040/09ae4944-9ddf-11e6-8608-9c0e834b1123.png)

I'm launching the driver like this:
```java
    MarionetteDriverManager.getInstance().setup();

    final DesiredCapabilities capabilities = DesiredCapabilities.firefox();
    capabilities.setCapability("marionette", false);
    final WebDriver selenium = new FirefoxDriver(capabilities);
```

**Comment by andreastt** [comment]
geckodriver/Marionette is not implemented as an extension. The extension you see there is FirefoxDriver from the Selenium project. It is not compatible with Firefox 47 onwards.

**Comment by jpschewe** [comment]
OK. The I expect that I'm synergies using the driver wrong. What is the
correct set of calls to use this driver with selenium? So far I get a
window opening and then nothing happens until selenium times out. Using an
older FF it ask works.

**Comment by andreastt** [comment]
You should consult the Selenium documentation.

**Comment by jpschewe** [comment]
I tried that and got no where. How do you expect this driver to be
instantiated so that it can be properly used? I posted the code that I am
using and what I sre in my browser. Do those lines look correct for
instantiatung the driver?

**Comment by andreastt** [comment]
That isn’t a question for the geckodriver project, but for Selenium.

**Comment by davehunt** [comment]
@jpschewe by setting the 'marionette' capability to `false` you are forcing Selenium to use the legacy Firefox driver, which does not use GeckoDriver, and is not expected to work in Firefox 48 or later. Change this to `true` and make sure you have the GeckoDriver binary in your path to run your tests against recent Firefox releases. If you're still having issues, please consult the Selenium documentation and user group.
