### ISSUE TITLE
Problem when signaling termination to forked geckodriver

### ISSUE THREAD

**Issue by vkatsikaros** [mozilla/geckodriver#317]
I notice a weird behavior when signaling a forked geckodriver for termination (I hope I am not doing something very dumb/wrong).

In the example script I use (1), I fork a geckodriver, then I issue webdriver commands (create session, go to url, find element, delete session), and then I signal the child process for termination. I notice that while the parent is alive, the child doesn't go away.
```
% perl geckodriver_singal.pl 
geckodriver PID 23024
1478106000676	geckodriver	INFO	Listening on 127.0.0.1:25000
POST /session
1478106002683	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.zjTkHZse8kOv
1478106002684	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox
1478106002687	geckodriver::marionette	INFO	Connecting to Marionette on localhost:50362

(firefox:23051): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:23051): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:23051): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:23051): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1478106003829	Marionette	INFO	Listening on port 50362
1478106005939	Marionette	INFO	startBrowser 81b856f6-d71b-496c-810f-58dee534cfb6
POST /session/81b856f6-d71b-496c-810f-58dee534cfb6/url

(/usr/lib/firefox/plugin-container:23133): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:23133): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:23133): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:23133): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
POST /session/81b856f6-d71b-496c-810f-58dee534cfb6/element
DELETE /session/81b856f6-d71b-496c-810f-58dee534cfb6
[Child 23133] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-XpkqMU/firefox-49.0+build4/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 316
[Child 23133] ###!!! ABORT: Aborting on channel error.: file /build/firefox-XpkqMU/firefox-49.0+build4/ipc/glue/MessageChannel.cpp, line 2052
[Child 23133] ###!!! ABORT: Aborting on channel error.: file /build/firefox-XpkqMU/firefox-49.0+build4/ipc/glue/MessageChannel.cpp, line 2052
Signal 15 no 1
Signal 15 no 2
Signal 15 no 3
Signal 15 no 4
Signal 15 no 5
$VAR1 = '23023 perl geckodriver_singal.pl
23024 geckodriver
23321 sh -c pgrep -fla geckodriver; pgrep -fla firefox
23321 sh -c pgrep -fla geckodriver; pgrep -fla firefox
';

% pgrep -fla geckodriver; pgrep -fla firefox
# no output
```
Note how the geckodriver child pid 23024 is alive, but then disappears after the main script ends.

My env
----------
```
geckodriver 0.11.1
Mozilla Firefox 49.0
Ubuntu 14.04
% uname -a
Linux lala 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

(1) Example script
-------------------
```
#!/usr/bin/perl
use strict;
use warnings;
use feature qw(say);

use Data::Dumper;
use JSON::XS;

my @command = qw{ /usr/local/bin/geckodriver --port 25000 };
my $pid = fork();
die 'Fork failed' if not defined $pid;
if (not $pid) {
    exec(@command) or die $!;
}
say "geckodriver PID $pid";
sleep(2); # wait for geckodriver to launch
my $host = 'localhost:25000';
my $url = '/session';

say "POST $url";
my $res;
$res = decode_json( `curl --silent -X POST ${host}$url --data '{}'` );
my $sessionId = $res->{sessionId};

$url = "/session/$sessionId/url";
say "POST $url";
$res = decode_json( `curl --silent -X POST ${host}$url --data '{"url":"https://www.adzuna.co.uk"}'` );

$url = "/session/$sessionId/element";
say "POST $url";
$res = decode_json( `curl --silent -X POST ${host}$url --data '{"using":"css selector","value":"h1"}'` );

$url = "/session/$sessionId";
say "DELETE $url";
$res = decode_json( `curl --silent -X DELETE ${host}$url --data '{}'` );

foreach my $i (1..5) {
    say "Signal 15 no $i";
    if( kill(15, $pid) == 0 ) {
		print "No signal sent\n";
        last;
	};
    sleep(3);
}
my $ps_res = `pgrep -fla geckodriver; pgrep -fla firefox`;
say Dumper $ps_res;
```

**Comment by andreastt** [comment]
If you fork a program without waiting for it you are in a danger of creating zombie processes.

It’s not entirely clear to be what behaviour you are expecting here: From your code it looks like you are running some commands that implicitly causes Firefox to terminate itself, then you send SIGTERM five times to the geckodriver process. What processes are you expecting to be alive at this point?

As far as my reckoning goes, the Firefox process (and its children) should go away after you send DELETE to `/session/$sessionId`, then geckodriver should disappear when you send it the termination signal. My guess is that geckodriver does not handle signal 15, so have you tried with 9?

**Comment by vkatsikaros** [comment]
From your comments, it sounds like my pattern of thought might not be 100% correct.

Let me explain a bit more clearly what I try to do: 
a) fork geckodriver 
b) parent sends some webdriver commands 
c) parent sends DELETE webdriver command 
d) firefox dies 
e) geckodriver is still alive

So I was looking for a way to kill the geckodriver process. At that point I said lets do
f) signal geckodriver.

> What processes are you expecting to be alive at this point?

At that point (e) I see that the geckodriver process is still alive (see output below, line marked with `<=====`). The fact that is still alive looks normal as i) nothing mentions that a webdriver DELETE the last session, affects geckodriver ii) there is no "command" to terminate the geckodriver itself. So, I guess it's up to owner to signal it.

> My guess is that geckodriver does not handle signal 15, so have you tried with 9

I modified the signaling code with
```
foreach my $s (15, 15, 9, 9, 2, 2) {
    say "Signal $s";
    if( kill($s, $pid) == 0 ) {
		print "No signal sent\n";
        last;
	};
    sleep(3);
}
```
It looks like neither 9 or 2 and handled.
```
% firefox --version && geckodriver --version
Mozilla Firefox 50.1.0
geckodriver 0.11.1

% perl geckodriver_singal.pl 
geckodriver PID 1981
1483526206664	geckodriver	INFO	Listening on 127.0.0.1:25000
POST /session
1483526208694	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.9Ze5q0l7fobA
1483526208696	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox
1483526208700	geckodriver::marionette	INFO	Connecting to Marionette on localhost:48578

(firefox:1991): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:1991): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(firefox:1991): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(firefox:1991): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
1483526210249	Marionette	INFO	Listening on port 48578

(/usr/lib/firefox/plugin-container:2090): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2090): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2090): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

(/usr/lib/firefox/plugin-container:2090): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
POST /session/db556c1d-7b78-43d7-b0cc-57ecc0226824/url
POST /session/db556c1d-7b78-43d7-b0cc-57ecc0226824/element
DELETE /session/db556c1d-7b78-43d7-b0cc-57ecc0226824
[Child 2090] ###!!! ABORT: Aborting on channel error.: file /build/firefox-motZyY/firefox-50.1.0+build2/ipc/glue/MessageChannel.cpp, line 2056
[Child 2090] ###!!! ABORT: Aborting on channel error.: file /build/firefox-motZyY/firefox-50.1.0+build2/ipc/glue/MessageChannel.cpp, line 2056
Signal 15
Signal 15
Signal 9
Signal 9
Signal 2
Signal 2
$VAR1 = '1980 perl geckodriver_singal.pl
1981 geckodriver                                     <=====
3448 sh -c pgrep -fla geckodriver; pgrep -fla firefox
3448 sh -c pgrep -fla geckodriver; pgrep -fla firefox
';
```

**Comment by vkatsikaros** [comment]
> If you fork a program without waiting for it you are in a danger of creating zombie processes.

I think I get what you mean, but I am not sure if this is related to my expectations above. I'll brush up my linux process&signals skills, modify my test script if needed, and reply to this and https://github.com/mozilla/geckodriver/issues/317#issuecomment-270344972.

**Comment by andreastt** [comment]
So your expectation is for geckodriver to exit when the browser process does?

**Comment by vkatsikaros** [comment]
>>The fact that is still alive looks normal as i) nothing mentions that a webdriver DELETE the last session, affects geckodriver ii) there is no "command" to terminate the geckodriver itself. So, I guess it's up to owner to signal it.

> So your expectation is for geckodriver to exit when the browser process does?

I don't have a specific expectation or behavior in mind for geckodriver when the browser exits, I've only noticed that it doesn't, so it should be up to me to signal it. The reason for not having a concrete opinion about this, is that I am not equipped enough to see the full picture when it comes to marionette and browser testing/manipulation.

Having said that, it looks normal to me that the geckodriver stays alive when the browser dies. In this case, once it's started, one shouldn't have to worry about launching a new geckodriver, in case the previous has died.

**Comment by andreastt** [comment]
OK, let me explain the lifetime of the various processes involved so we can get to the bottom of this: The geckodriver process is normally started by either your language binding or the remote server you’re connecting to (like Selenium RemoteWebDriver, Selenium Grid, or Sauce) before the initial new session request has been made. After the geckodriver HTTPD is spun up, your client will attempt to create a session. This usually happens when you construct a new `FirefoxDriver` or `RemoteWebDriver` object instance.

When geckodriver receives the new session request, it will start a Firefox subprocess (which itself also has a number of subprocesses) and connect to the Marionette remote control interface via TCP. Once both connections are established, it will return to the user.

When you close the last top-level browsing context (“window”) or quit the driver session, it will delete the session and shut down Firefox. This currently has some issues, as you will have seen from your logs regarding the “Aborting on channel error” message. There may be a few gremlins related to this to iron out, and this is on my list, but generally speaking, the error message you’re seeing shouldn’t impact you.

What’s important to note is that at this point, even though Firefox quits and/or crashes, the geckodriver process is meant to live on. It will only shut down when signalled to do so, and it is the responsibility of its parent process to manage its lifetime. In other words, there is no explicit command or API to shutdown geckodriver itself.

**Comment by vkatsikaros** [comment]
@andreastt thanks for the detailed explanation!

Ok, so I am either doing sth wrong with my signaling (more likely :) ) or geckodriver doesn't handle well signals 15, 9, and 2 well (less likely).

While brushing up my linux process skills, as promised, I stumbled upon [this](http://docstore.mik.ua/orelly/perl/cookbook/ch16_20.htm) and [this](http://perldoc.perl.org/perlipc.html). My test code wasn't doing anything with wait (or SIGCHLD), so geckodriver was lingering around (what `ps` would mark as `defunct`).

However, if I add `$SIG{CHLD} = 'IGNORE';` (perl's way of `signal(SIGCHLD, SIG_IGN);` [to prevent the creation of zombies](http://man7.org/linux/man-pages/man2/sigaction.2.html)) to my test code (my guess for the right place is after the fork), things look better.

```
DELETE /session/43eea145-9183-44b3-9bb2-72a16dd61bfc
[Child 13545] ###!!! ABORT: Aborting on channel error.: file /build/firefox-motZyY/firefox-50.1.0+build2/ipc/glue/MessageChannel.cpp, line 2056
[Child 13545] ###!!! ABORT: Aborting on channel error.: file /build/firefox-motZyY/firefox-50.1.0+build2/ipc/glue/MessageChannel.cpp, line 2056
Signal 15
Signal 15
No signal sent
$VAR1 = '13461 perl geckodriver_singal.pl
14855 sh -c pgrep -fla geckodriver; pgrep -fla firefox
14855 sh -c pgrep -fla geckodriver; pgrep -fla firefox
';
```

So, if I now got this correctly, it's my test code that doesn't behave properly.

**Comment by whimboo** [comment]
@vkatsikaros so to get a conclusion... is it all working now and can we close this issue?

**Comment by vkatsikaros** [comment]
@whimboo sorry for the late reply, I didn't have the time to work on the issue that triggered the problem (on  the perl webdriver client side). However, so far all evidence suggest it was the client's problem. I'll close the issue.

If I collect evidence that there is a problem on the geckodriver side, I can always reopen the issue.

**Comment by whimboo** [comment]
Thanks!
