### ISSUE TITLE
Error - org.openqa.selenium.remote.ProtocolHandshake createSession

### ISSUE THREAD

**Issue by soul3510** [mozilla/geckodriver#318]
After upgrading selenium from 2.53.1 to 3.0.1:

Trying to run on FF49 gives me the following: 

Nov 03, 2016 10:45:59 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Nov 03, 2016 10:46:11 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

**Comment by jgraham** [comment]
Are you actually using geckodriver or the old FirefoxDriver? It's very difficult to tell what's happening from that short piece of log, but I expect you have not configured selenium correctly to use geckodriver.

**Comment by reginabecker** [comment]
Help for this error
INFORMAÇÕES: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
jan 03, 2017 4:29:58 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFORMAÇÕES: Detected dialect: OSS



import io.appium.java_client.MobileElement;
import io.appium.java_client.SwipeElementDirection;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import static org.junit.Assert.*;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Rough {
	@Test
	public void test() throws MalformedURLException {
		// caminho da aplicação que sera testada
		File appDir = new File("src");
		File app    = new File(appDir, "bookMyShow-ucb.apk");
		
		//capacidades (indicando a plataforma, dispositivo e aplicacao)
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
		
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "200");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		
		// abre a conexao com o servidor (URL) e executa sob um dispositivo (descrito pela capacidade)
		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		driver.findElementById("com.bt.bms:id/btnNoThanks").click();
		driver.findElementById("com.bt.bms:id/dismiss").click();
		MobileElement abc = (MobileElement)driver.findElement(By.className("android.widget.CheckedTextView"));
		abc.swipe(SwipeElementDirection.UP,6000);
		//abc.tap(left, duration);
		abc.zoom();
	}
}

**Comment by Anki1208** [comment]
Browner: Firefox version 47
OS: windows 7
Selenium version 3.2.0
gecko driver version 0.15.0

My Code:
package TEST;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class CLASS {

public static void main(String[] args) {
    // declaration and instantiation of objects/variables
	WebDriver driver ;
	System.setProperty("webdriver.firefox.marionette","C:\\Users\\59894\\Downloads\\Gecko\\geckodriver.exe");
	driver = new FirefoxDriver();
    String baseUrl = "https://www.google.co.in/?gfe_rd=cr&ei=I2_PWJ6hO-Px8AfL16TYBQ";
    String expectedTitle = "Google";
    String actualTitle = "";

    // launch Fire fox and direct it to the Base URL
    driver.get(baseUrl);

    // get the actual value of the title
    actualTitle = driver.getTitle();

    /*
     * compare the actual title of the page with the expected one and print
     * the result as "Passed" or "Failed"
     */
    if (actualTitle.contentEquals(expectedTitle)){
        System.out.println("Test Passed!");
    } else {
        System.out.println("Test Failed");
    }
   
    //close Fire fox
    driver.close();
   
    // exit the program explicitly
    System.exit(0);
}

}

Getting error: Mar 20, 2017 12:03:49 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Output: Test Passed!( google open in new tab but still getting above error)

**Comment by andreastt** [comment]
You need to use Selenium 3.3 or newer with geckodriver 0.15.0 as it made a backwards incompatible change to the way responses are sent to stay in conformance with the WebDriver standard.

**Comment by andreastt** [comment]
Also locking this, since the issue is very old.
