### ISSUE TITLE
Selenium Webdriver 3.0.1 + gecko driver  v0.11.1 is not working in mozilla firefox 49.0.2

### ISSUE THREAD

**Issue by thareek** [mozilla/geckodriver#319]
Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:347)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)

**Comment by kumar1004101** [comment]
I am also facing same issue..when I am trying to execute, getting below error.

Firefox : 49.02
Latest selenium webdriver java 3.0.1


org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
08198ce6fd}","syncGUID":"t1ICGFLgCrTQ","location":"app-global","version":"49.0.2","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1477019070000,"updateDate":1477019070000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.2","maxVersion":"49.0.2"}],"targetPlatforms":[],"seen":true}
1478186334682	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1478186334683	DeferredSave.extensions.json	DEBUG	Save changes
1478186334683	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1478186334683	addons.xpi-utils	DEBUG	Updating add-on states
1478186334687	addons.xpi-utils	DEBUG	Writing add-ons list
1478186334690	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1478186334691	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.3
1478186334691	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1478186334691	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1478186334692	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1478186334692	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1478186334694	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1478186334694	addons.manager	DEBUG	Provider finished startup: XPIProvider
1478186334694	addons.manager	DEBUG	Starting provider: LightweightThemeManager

**Comment by nsjanani** [comment]
Faced the same issue.
Tried the below steps and it seems to work.. Please check out 👍 
1. Uninstall the new Firefox version 49
2. Download the old version 44
3. Allow it to upgrade to 49
4. Now with this combination of Firefox 49 and Selenium 3.0.1, it did work !!

**Comment by andreastt** [comment]
Unable to reproduce this from this scarcity of information. I suspect this is a Selenium issue anyway.

**Comment by thareek-b** [comment]
provided workaround did not work.

**Comment by prakashvivek89** [comment]
Please see the comments on this link : https://github.com/SeleniumHQ/selenium/issues/2990
