### ISSUE TITLE
New session response status 500 : failed to lookup address information

### ISSUE THREAD

**Issue by jcorentin** [mozilla/geckodriver#321]
Hi !
I'm trying to setup together : 
- selenium 3.0.1 (python implementation, v3.5)
- geckodriver 0.11.1
- firefox 49.0.2

I can't guess if this is a wrong configuration on my side or a bug but this is the traceback I get when creating an instance of webdriver.Firefox
```
Traceback (most recent call last):
File "functional_tests.py", line 3, in <module>
    browser = webdriver.Firefox()
File "selenium/webdriver/firefox/webdriver.py", line 145, in __init__
    keep_alive=True)
File "selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
File "selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
File "selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
File "selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: failed to lookup address information: Try again
```
Content of geckodriver.log : 
`1478316057937   geckodriver     INFO    Listening on 127.0.0.1:51649`

Selenium seems to successfully launch geckodriver service.
It's getting an Http response on NEW_SESSION command. However, it only contains status 500 and above error message.

I haven't found any similar occurence on marionette bug tracker or this one.
I've tried searching for location of error message or any clue in geckodriver and marionette source code in vain. 
I don't have the skills to know where to look at now but i'm ready to help with more debug info.

Thanks !

**Comment by andreastt** [comment]
Can you please [increase the logging verbosity of geckodriver](https://github.com/andreastt/geckodriver/blob/capabilities-docs/README.md) and run your program again?

**Comment by jcorentin** [comment]
Thanks for your quick reply.
geckodriver output with option --log debug :  
"""1478369292880   webdriver::httpapi      DEBUG   Creating routes
1478369292883   hyper::server   DEBUG   threads = 5
1478369292883   geckodriver     INFO    Listening on 127.0.0.1:38099
1478369299126   hyper::server   DEBUG   Incoming stream
1478369299126   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:55854
1478369309124   hyper::server   DEBUG   Incoming stream
1478369309124   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:55862
1478369309125   hyper::server   DEBUG   Incoming stream
1478369309125   hyper::server::request  DEBUG   Request Line: Post AbsolutePath("/session") Http11
1478369309125   hyper::server::request  DEBUG   Headers { User-Agent: Python http auth, Accept-Encoding: identity, POST: /session, Content-Length: 160, Content-type: application/json;charset="UTF-8", Host: 127.0.0.1:38099, Connection: keep-alive, Accept: application/json, }
1478369309125   webdriver::server       DEBUG   Got request POST AbsolutePath("/session")
1478369309125   webdriver::command      DEBUG   Got request body {"requiredCapabilities": {}, "desiredCapabilities": {"platform": "ANY", "browserName": "firefox", "marionette": true, "version": "", "javascriptEnabled": true}}
1478369314131   webdriver::server       DEBUG   Returning status InternalServerError
1478369314131   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"failed to lookup address information: Try again"}
1478369314131   hyper::server::response DEBUG   writing head: Http11 InternalServerError
1478369314131   hyper::server::response DEBUG   headers [
Headers { Content-Length: 85, Content-Type: application/json, Date: Sat, 05 Nov 2016 18:08:34 GMT, Connection: close, }]
1478369314131   hyper::server::response DEBUG   write 85 bytes
1478369314131   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:55864
1478369314131   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:55864
"""

**Comment by andreastt** [comment]
Thank you, can you please also try `trace` for `my_options.log.level`?

**Comment by jcorentin** [comment]
Geckodriver.log with my_options.log.level set to trace : 
```
1478407350411   geckodriver     INFO    Listening on 127.0.0.1:50275
1478407370554   webdriver::server       DEBUG   Returning status InternalServerError
1478407370554   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"failed to lookup address information: Try again"}
1478407370554   hyper::header   TRACE   Headers.set( "Content-Type", ContentType(Mime(Application, Json, [])) )
1478407370555   hyper::header   TRACE   Headers.set( "Content-Length", ContentLength(85) )
1478407370555   hyper::server::response DEBUG   writing head: Http11 InternalServerError
1478407370555   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 50, tm_min: 42, tm_hour: 4, tm_mday: 6, tm_mon: 10, tm_year: 116, tm_wday: 0, tm_yday: 310, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 555044385 })) )
1478407370555   hyper::server::response DEBUG   headers [
Headers { Connection: close, Content-Length: 85, Date: Sun, 06 Nov 2016 04:42:50 GMT, Content-Type: application/json, }]
1478407370555   hyper::server::response DEBUG   write 85 bytes
1478407370555   hyper::server::response TRACE   ending
1478407370555   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:59558
1478407370555   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:59558
```

**Comment by jcorentin** [comment]
I conducted some additional tests : 

Test 1) 
- I launch firefox with flag --marionette
- I launch geckodriver with options --connect-existing --marionette-port 2828 --log trace
- I manually request a new session by using `curl -i -X POST -H "Content-Type: application/json" -d '{}' http://127.0.0.1:4444/session
`
Output of geckodriver : 
```
1478499439102   webdriver::httpapi      DEBUG   Creating routes
1478499439110   hyper::server   DEBUG   threads = 5
1478499439110   geckodriver     INFO    Listening on 127.0.0.1:4444
1478499447390   hyper::server   DEBUG   Incoming stream
1478499447390   hyper::buffer   TRACE   get_buf []
1478499447390   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1478499447390   hyper::buffer   TRACE   get_buf [u8; 4096][0..139]
1478499447390   hyper::http::h1 TRACE   try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 52, 52, 52, 52, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 99, 117, 114, 108, 47, 55, 46, 52, 57, 46, 49, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 42, 47, 42, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 50, 13, 10, 13, 10, 123, 125])
1478499447391   hyper::http::h1 TRACE   Request.try_parse([Header; 100], [u8; 139])
1478499447391   hyper::http::h1 TRACE   Request.try_parse Complete(137)
1478499447391   hyper::header   TRACE   raw header: "Host"=[49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 52, 52, 52, 52]
1478499447391   hyper::header   TRACE   raw header: "User-Agent"=[99, 117, 114, 108, 47, 55, 46, 52, 57, 46, 49]
1478499447391   hyper::header   TRACE   raw header: "Accept"=[42, 47, 42]
1478499447391   hyper::header   TRACE   raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110]
1478499447391   hyper::header   TRACE   raw header: "Content-Length"=[50]
1478499447391   hyper::server::request  DEBUG   Request Line: Post AbsolutePath("/session") Http11
1478499447391   hyper::server::request  DEBUG   Headers { User-Agent: curl/7.49.1, Content-Length: 2, Content-Type: application/json, Accept: */*, Host: 127.0.0.1:4444, }
1478499447391   hyper::header   TRACE   Headers.set( "Connection", Connection([Close]) )
1478499447391   hyper::http::h1 TRACE   Sized read, remaining=2
1478499447391   hyper::http::h1 TRACE   Sized read: 2
1478499447391   hyper::http::h1 TRACE   Sized read, remaining=0
1478499447391   webdriver::server       DEBUG   Got request POST AbsolutePath("/session")
1478499447391   webdriver::command      DEBUG   Got request body {}
1478499452395   webdriver::server       DEBUG   Returning status InternalServerError
1478499452395   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"failed to lookup address information: Try again"}
1478499452395   hyper::header   TRACE   Headers.set( "Content-Type", ContentType(Mime(Application, Json, [])) )
1478499452395   hyper::header   TRACE   Headers.set( "Content-Length", ContentLength(85) )
1478499452395   hyper::server::response DEBUG   writing head: Http11 InternalServerError
1478499452395   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 32, tm_min: 17, tm_hour: 6, tm_mday: 7, tm_mon: 10, tm_year: 116, tm_wday: 1, tm_yday: 311, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 395423011 })) )
1478499452395   hyper::server::response DEBUG   headers [
Headers { Content-Length: 85, Content-Type: application/json, Connection: close, Date: Mon, 07 Nov 2016 06:17:32 GMT, }]
1478499452395   hyper::server::response DEBUG   write 85 bytes
1478499452395   hyper::server::response TRACE   ending
1478499452395   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:40038
1478499452395   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:40038
```
Output of firefox --marionette : 
`1478499415800   Marionette      INFO    Listening on port 2828`

I didn't find how to increase marionette server logging verbosity on the MDN. I have no output in browser toolbox console either. Could you please tell me how to do it ?


Test 2)
- I installed python marionette_client
- I start firefox --marionette
- I run following code :   
```
client = marionette.Marionette('localhost', port=2828)
client.start_session()
```
Everything works flawlessly in this case.

**Comment by andreastt** [comment]
The “failed to lookup address information: Try again” error we’re seeing here must come from somewhere inside https://github.com/mozilla/webdriver-rust/blob/master/src/server.rs#L187-L218, which a quick Google search indicates could have something to do with DNS name resolution.

Do you have localhost mapped to something special on your system? Can you try using `127.0.0.1` instead? What OS is your system?

> I didn't find how to increase marionette server logging verbosity on the MDN. I have no output in browser toolbox console either. Could you please tell me how to do it ?

The Marionette verbosity is set through the [`marionette.logging` preference by geckodriver](https://github.com/mozilla/geckodriver/blob/master/src/marionette.rs#L406-L408), but this won’t be propagated properly when you connect to an existing instance of Firefox.

**Comment by jcorentin** [comment]
Problem solved !

I'm using Archlinux, after some searches on the wiki, i found the following note :

Note: systemd provides hostname resolution via the myhostname nss module (enabled by default in /etc/nsswitch.conf), which means that changing hostnames in /etc/hosts is normally not necessary. However several users have reported bugs such as delays in network-based applications when the hostname was not set correctly in /etc/hosts. See #Local network hostname resolution for details. 

I edited /etc/hosts to include localhost, it's now working fine.

Thanks a lot for your help.

**Comment by andreastt** [comment]
Great to hear!
