### ISSUE TITLE
How to make geckodriver less verbose 

### ISSUE THREAD

**Issue by louis57** [mozilla/geckodriver#323]
Geckodriver and Selenium 3 are working fine. I have only one issue is that the tests are very verbose, sometimes not interested. 

Is there anyway to make it less verbose or a way to change its verbosity? 

Thanks in advance.

**Comment by andreastt** [comment]
You don’t say anything about what version of geckodriver you are using, but geckodriver 0.10 onwards defaults to INFO (and above) level logging for optimised Firefox builds and DEBUG (and above) for non-optimised debug builds.

You can override this by setting the [`level` capability in `moz:firefoxOptions`](https://github.com/mozilla/geckodriver/blob/master/README.md#log-object) to your desired level or use the `--log-level` flag.

**Comment by louis57** [comment]
Ah sorry, I forgot to mention I am using geckodriver v0.11.1, just edited my question. Thanks for the answer, I'll give it a try.

**Comment by andreastt** [comment]
Like I said, you should be seeing INFO level messages from 0.11.1 if you use a stable Firefox build.
