### ISSUE TITLE
For Selenium 3.0.1  FF v. 38 and FF v.49(gecko)  return diff result for element.getAttribute("src")

### ISSUE THREAD

**Issue by OlegRomaniuck** [mozilla/geckodriver#325]
Good morning. 
I have moved to a new version selenium 3.0.1. So what I have found when I started my  old tests 
below config if its important (i dont konw )
(Config selenium 3.0.1 ) 
FF 38 create 
File pathToBinary = new File("src\\main\\java\\property\\drivers\\firefoxe driver\\firefox.exe");
                    FirefoxBinary ffBinary = new FirefoxBinary(pathToBinary);
                    FirefoxProfile ffProfile = new FirefoxProfile();
                    DesiredCapabilities legacyCapabilities = DesiredCapabilities.firefox();
                    legacyCapabilities.setCapability("marionette", false);
                    driver = new FirefoxDriver(ffBinary, ffProfile, legacyCapabilities); 
return driver;

FF 49 (gecko)
                    DesiredCapabilities firefoxCapabilities = DesiredCapabilities.firefox();                    System.setProperty("webdriver.gecko.driver","\\src\\main\\java\\property\\drivers\\geckodriver.exe");
                    driver = new FirefoxDriver(firefoxCapabilities);
return driver;

for ff 49 http://prntscr.com/d50wfi
String src=getInitWebDriver().findElement(By.id("captcha_img")).getAttribute("src");
System.out.println("Version  for ff 49 : "+ src );
src is /manager/captcha/image/rjt4hjf913f9562hjh545jhjkhsdsd3a248cde2fe162/
for ff 38 http://prntscr.com/d50zgg

  String src=getInitWebDriver().findElement(By.id("captcha_img")).getAttribute("src");
   System.out.println("Version  for ff 38 : "+ src );
src is https://dummy.com/manager/captcha/image/13623ef679ce7da2ebdhfhdfjhd457845hj661/

part of html http://prntscr.com/d50xy3

**Comment by andreastt** [comment]
This is an expected change moving from Selenium WebDriver to [W3C WebDriver](http://w3c.github.io/webdriver/webdriver-spec.html), which geckodriver implements. Selenium needs to provide an atom for returning the magic property-attribute conflation it does when speaking to W3C conformant remotes.

This was tracked in https://github.com/SeleniumHQ/selenium/issues/2301 but I don’t know why this doesn’t work with your language bindings. I would file a bug with Selenium.
