### ISSUE TITLE
Geckodriver is not returning expected element coordinates

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#331]
Dear Geckodriver team,

I'm using the following environment:

- Windows 10
- Firefox 49.0.2
- Geckodriver 0.11.1
- Selenium 3.0.1

When I lookup a WebElement, get it's coordinates and move the mouse to this position, it is not moved to the expected place.

I've attached a short example by opening the Google entry page and moving the mouse pointer to the upper left corner of the SearchField.

[MoveMouse.java.txt](https://github.com/mozilla/geckodriver/files/584091/MoveMouse.java.txt)

Additionally I also attached a screenshot of the current result, when executing this script. x-coordinate looks ok, but y-coordinate is way to small.

![elementcoordinatesnotcorrect](https://cloud.githubusercontent.com/assets/20477996/20188877/fa445d7c-a77a-11e6-944e-eee141d46296.png)

Any idea, where this might result from?

Thanks and regards
mgavilan

**Comment by leonard84** [comment]
If you want to use `java.awt.Robot` you need to take into account that the coordinates reported by webdriver are relative to the rendered website not the OS. So you need to correct for the title and url-bar. My recommendation is to use https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/Actions.html instead

**Comment by mgavilan** [comment]
@leonard84: Thanks a lot for this hint. I immediatelly tried the alternative way using Selenium Actions, this is my short example:

[MoveMouse_WithActions.txt](https://github.com/mozilla/geckodriver/files/587204/MoveMouse_WithActions.txt)

As you can see, I'm using moveToElement() to get the mouse moved over the SearchField and sendKeys() to enter some search term.
None of both is resulting in the expected behaviour, as nothing else happens after opening the web page.

Is this maybe still a lack of functionality with the new geckodriver to support Selenium Actions?

Thanks and regards
mgavilan

**Comment by leonard84** [comment]
@mgavilan yes I also stumbled on this issue today, `Actions` are not support atm see #233

**Comment by andreastt** [comment]
You say that geckodriver is not returning the expected coordinates, yet you omit what the return value of `driver.findElement(By.id("sbtc")).getLocation()` is.

@leonard84 is correct that WebDriver is meant to return an element’s location relative to the viewport and not the screen and that the actions API is not implemented in geckodriver yet.

I’m going to go ahead and close this issue as getting coordinates with geckodriver works to the extent of my knowledge. Please let me know if you think this is a mistake.
