### ISSUE TITLE
Not able to generate Har file with new version of Selenium 3.0.1 and Firefox 49

### ISSUE THREAD

**Issue by satishgowda** [mozilla/geckodriver#332]
OS:
Windows
Selenium Version:
3.0.1
Browser:
Firefox 49

I was working with selenium 2.53 and Firefox 47 version with "netExport-0.9b7.xpi" and firebug version "firebug-2.0.17-fx.xpi" it was working fine to capture network traffic into HAR file
now with new version selenium 3.0.1 and firefox version 49 and i am using "netExport-0.9b7.xpi" and firebug version "firebug-2.0.18-fx.xpi" it is not working fine

I am not able to generate with new version of Selenium and Firefox
could you please check on this

i referred https://eveningsamurai.wordpress.com/2013/06/29/capturing-network-traffic-using-selenium-webdriverfirebug/

**Comment by andreastt** [comment]
This seems unrelated to geckodriver.

**Comment by soulgalore** [comment]
@satishgowda you should look at https://github.com/firebug/har-export-trigger
