### ISSUE TITLE
Set Window Position not moving Firefox browser window

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#335]
Dear Geckodriver team,

I'm using the following environment:

- Windows 10
- Firefox 49.0.2
- Geckodriver 0.11.1
- Selenium 3.0.1

I've followed an issue reported with [issue #113 - Missing Set Window Position endpoint](https://github.com/mozilla/geckodriver/issues/113) as I was facing exceptions with older geckodriver versions, when trying to position the Friefox browser window.

If I got it right, the actual change was implemented with [commit #254 - Set Window position and Get Window Position](https://github.com/mozilla/geckodriver/pull/254) and is supposed to be contained in geckodriver version 0.11 and greater, correct?

While I do not get exceptions with geckodriver 0.11.1 anymore, when using setPosition() method of FirefoxDriver, the browser window is not moved to the expected screenposition though. 

Here I attach a small example opening a Firefox browser instance and doing some modification to the browser window size (setSize()) and position (setPosition()).

[NewFirefoxDriver_setPosition.java.txt](https://github.com/mozilla/geckodriver/files/587196/NewFirefoxDriver_setPosition.java.txt)

By executing you will notice, the browser is opened and the size is changed stepwise, but the position is not.

Any idea, why this is not working?

Thanks and regards
mgavilan

**Comment by andreastt** [comment]
This could be specific to Windows, although we do run test for this in the Mn test job on try. Do you have the bandwidth to do the legwork to check if this works as expected on Linux or macOS?

**Comment by andreastt** [comment]
@mgavilan ↑

**Comment by AutomatedTester** [comment]
Closing since there has not been any information in over a month

**Comment by mgavilan** [comment]
Sorry for the late reply. Actually I'm not able to check this on Linux or macOS. Shall I wait for the next release 0.12 or Selenium > 3.0.1?

**Comment by BrandonDude** [comment]
Still an issue!

**Selenium:** 3.3.1
**Geckodriver:** 0.15.0
**Firefox:** 52.1.2 (ESR) [32 & 64 bit]
**Windows:** 7

**Comment by AutomatedTester** [comment]
@BrandonDude 
Please can you retry with selenium 3.4, GeckoDriver 0.17 and latest release of Firefox

**Comment by BrandonDude** [comment]
I have been avoiding selenium 3.4 because of issues [3895](https://github.com/SeleniumHQ/selenium/issues/3895).

**Comment by BrandonDude** [comment]
I tried again with:

**Selenium:** 3.4
**Geckodriver:** 0.17.0
**Firefox:** 54.0 (64-bit)
**Windows:** 7

Still an issue. This has also been reported in issues [403](https://github.com/mozilla/geckodriver/issues/403) & [676](https://github.com/mozilla/geckodriver/issues/676).
