### ISSUE TITLE
Can't find element by link text if a <i> tag is inside the <a> tag

### ISSUE THREAD

**Issue by patrickmjansen** [mozilla/geckodriver#337]
Firefox 49.0.2
Selenium 3.0.1
Geckodriver: geckodriver-v0.11.1-win64.zip

```
<a class="btn btn-small article-edit" href="javascript:void(0);">
    <i class="icon-pencil"></i>
&nbsp;Rediger</a>
```

When searching for driver.find_element_by_link_text(" Rediger") timeoutException occur.

When getting the element with css_selector 
driver.find_element_by_css_selector(".btn.btn-small.article-edit").text
it returns ' Rediger'

**Comment by MattiSG** [comment]
@patrickmjansen Why was this issue closed? I have a similar problem and would love to have your experience  :wink:

**Comment by patrickmjansen** [comment]
I don't remember to be honest. Probably thought it was something wrong on my side. I can reopen the issue

**Comment by andreastt** [comment]
I think it’s possible we might be doing some padding/text trimming of the input, which would explain why this would fail.

**Comment by whimboo** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1381519 for Firefox 61. Now we find the element as the text gets rendered.
