### ISSUE TITLE
Actions.dragAndDropBy doesn't work properly ?!

### ISSUE THREAD

**Issue by louis57** [mozilla/geckodriver#338]
I don't know if someone already asked. I have problem with class Actions, the functions, for example: dragAndDropBy(), moveToElement(), clickAndHold(), etc. don't work properly. I always get exception "InvocationTargetException".

Is there any solutions for this?

I am using geckodriver v0.11.1, with Firefox 49.0.2

Thanks for the help.

**Comment by andreastt** [comment]
The Selenium action API is not implemented in geckodriver. We are however tracking the implementation of the _W3C_ action API in https://github.com/mozilla/geckodriver/issues/233.

**Comment by louis57** [comment]
Thanks for the confirmation. I thought it myself. 
Hope the implementation is coming soon.
