### ISSUE TITLE
Will Gecko Web Driver ever wait for the page to load 

### ISSUE THREAD

**Issue by kcrump** [mozilla/geckodriver#340]
Hello:

I am using Windows 8 and Firefox 50.0 (however I experienced this issue on previous versions of Firefox).
Gecko does not wait until the page loads before it allows my test to continue.  The old firefox web driver would wait.   Is there something that I could add to my script so that Gecko could wait until the page loads before continuing?  I am using a script that records how long it takes pages to load. 
[load.txt](https://github.com/mozilla/geckodriver/files/592880/load.txt)

**Comment by SKharlanov** [comment]
Hi,

I also faced this issue. Waiting methods based on javascript commands can't help.

**Comment by andreastt** [comment]
No reproducible steps provided. Closing.

**Comment by kcrump** [comment]
@andreastt what steps do you need for me to provide?  I am using MyEclipse and I attached the script that I am using?

**Comment by SKharlanov** [comment]
@andreastt 
Env: Win7, ff50, geckodriver 0.11, webdriver 3.0.1.
Reproduced on every page. In order to check you can use code from attachment in the very first message.

This issue is bloker for automation, please don't ignore it.

Thanks.

**Comment by andreastt** [comment]
I can’t reproduce this on “any page”.

**Comment by jgraham** [comment]
@SKharlanov It would be really helpful if you could provide a HTML page (and perhaps script) that clearly acts as a minimal testcase e.g. one where some WebDriver command will result in the text FAIL being returned if the implementation doesn't do what you expect, but will result in the text PASS being returned if it does.

**Comment by kcrump** [comment]
I cannot provide you with the html page that I use because it is an internal page that you will not be able to access.  I did provide you with a script going to the w3 site.  When this runs on my browser it doesn't look like the 2nd link is being accessed (or clicked on).   


package com.kcrump;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;

import org.apache.commons.lang3.time.StopWatch;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Time_Load2forhim {
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
	System.setProperty("webdriver.gecko.driver", "C:\\resources\\geckodriver\\geckodriver.exe");  //nmark if using geckodriver 
	driver = new FirefoxDriver();
	baseUrl = "http://www.w3schools.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    driver.manage().window().maximize();
  }

  @Test
  public void testTimeLoad2forhim() throws Exception {
    driver.get(baseUrl);
    StopWatch pageLoad = new StopWatch();
    

    pageLoad.start();
    driver.findElement(By.xpath("//nav[@id='mySidenav']/a")).click();
    WebDriverWait wait1 = new WebDriverWait(driver, 10);
    wait1.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Go to HTML Examples!")));
    pageLoad.stop();
    long pageLoadTime_ms1 = pageLoad.getTime();
    long pageLoadTime_Seconds1 = pageLoadTime_ms1 / 1000;
    System.out.println("First Link on w3 page: " + pageLoadTime_ms1 + " milliseconds");
    System.out.println("First Link on w3 page: " + pageLoadTime_Seconds1 + " seconds");
    System.out.println("====================================");
    pageLoad.reset();
   
    pageLoad.start();
    driver.findElement(By.linkText("HTML Editors")).click();
    WebDriverWait wait2 = new WebDriverWait(driver, 10);
    wait2.until(ExpectedConditions.presenceOfElementLocated(By.linkText("HTML Basic")));
    pageLoad.stop();
    long pageLoadTime_ms2 = pageLoad.getTime();
    long pageLoadTime_Seconds2 = pageLoadTime_ms2 / 1000;
    System.out.println("2nd Link on W3: " + pageLoadTime_ms2 + " milliseconds");
    System.out.println("2nd Link on W3: " + pageLoadTime_Seconds2 + " seconds");
    System.out.println("===========================================");
    
    pageLoad.reset();
    driver.close();
  }

  @After
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}

**Comment by andreastt** [comment]
We didn’t ask you to provide the internal page but a minimised test case that proves the failure. The Java code you pasted contains so much extra nonsense that it is not useful for the purposes of reproducing the problem.

**Comment by kcrump** [comment]
Have you tried to reproduce. I provided a test case in the beginning of the thread.  Your tone is really unnecessary.

**Comment by phoenix384** [comment]
There is #308, which addresses the same topic and which is still open.
This is the main issue, that blocks us (and many others, I'm sure) from using GeckoDriver. I don't know why this problem isn't being addressed with a higher priority.
