### ISSUE TITLE
WebElement#sendKeys does not trigger change event for input elements in Firefox on Linux

### ISSUE THREAD

**Issue by Snipx** [mozilla/geckodriver#341]
Hi,

I have an input element on the webpage that has a _change_ event listener attached to it and I am trying to upload a file with Selenium using the following approach:

` driver.findElement(cssSelector("input[accept='application/pdf']")).sendKeys(filePath);`

This works perfectly in Firefox on Windows, namely _change_ event is triggered for _input_ element, but unfortunately this does not work on Linux.

I can verify that the _sentKeys_ method did what it had do, namely the _**file**_ entry in the input element contains the desired file. However, the _change_ event is not triggered.

I have found a workaround: triggering _change_ event manually by executing JavaScript from Selenium:

`((FirefoxDriver)driver).executeScript("document.getElementsByTagName('input')[0].dispatchEvent(new Event('change'))");`

But of course it would be great if the same Selenium test code worked both for Windows and Linux in the same way.

Best,
Alexey

**Comment by andreastt** [comment]
You didn’t mention what version of Firefox you are running. I believe this was fixed with [bug 1280947](https://bugzilla.mozilla.org/show_bug.cgi?id=1280947) which is available in Firefox 50 onwards. Please test again in [Nightly](https://nightly.mozilla.org/).
