### ISSUE TITLE
Support for setting URL prefix

### ISSUE THREAD

**Issue by blueimp** [mozilla/geckodriver#343]
The [W3C Webdriver Spec](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-url-prefix) defines the option of a URL prefix:

> A remote end has an associated URL prefix, which is used as a prefix on all WebDriver-defined URLs on that remote end. This must either be undefined or an path-absolute URL.

Will this be implemented as argument to the geckodriver binary?
e.g. `geckodriver --url-base=/wd/hub`, which is the argument used by chromedriver (albeit they support the Selenium JSON wire protocol and not the W3C Webdriver API, as far as I know).

**Comment by andreastt** [comment]
I think it would be good to add this, but it isn’t a priority from our side. If you, or anyone else, has some time to spare I believe this would be a good getting-started-with-Rust bug.

**Comment by blueimp** [comment]
Good reply! :)
I'm not familiar with Rust yet, will see if I find the time.

**Comment by jgraham** [comment]
FWIW I'm reluctant to take this unless I clearly understand the usecase. I can see how some service allowing connections to multiple browsers might add a path prefix (an dinternally route to multiple serers on multiple ports), but geckodriver isn't that.

**Comment by blueimp** [comment]
The use case and reason why I posted this is to achieve backwards compatibility with the default path prefix of selenium hub.
Many clients will use shims to support both the Selenium JSON Wire Protocol and the W3C Webdriver API and supporting the path prefix here will help in the transition.

**Comment by andreastt** [comment]
How does changing the default path help with migration? I am sympathetic to the argument that we shouldn’t add complexity if we can avoid it. The less code to maintain, the better.

**Comment by blueimp** [comment]
It helps with migration of those webdriver clients that use a default path prefix of `/wd/hub`, e.g. Nightwatch.js (albeit Nightwatch.js does not support the W3C spec fully).  
They'll need their path prefix option set to the root path, which limits the out-of-the box experience when switching from Selenium to Geckodriver, which otherwise would only be a hostname change (if both run on port 4444).

However I'm also fine with closing this issue for simplicity's sake.  
If this should in any way rise in importance for myself, I'll reopen it with an accompanying pull request.

**Comment by andreastt** [comment]
Can you link to the relevant code in Nightwatch.js? Are they simply expecting the remote end to be present at a certain endpoint?

The reason I’m asking this is that they must surely know the hostname and port of the remote service so they can connect the client to it. If they were to define this as `http://127.0.0.1:1234/some/root` instead of as individual values, they could parse this information out for free rather than having to deduce it. Immediately, this sounds like a configuration problem with Nightwatch.js.

**Comment by blueimp** [comment]
They do have an undocumented option to override the default path prefix of `/wd/hub/`:
https://github.com/nightwatchjs/nightwatch/search?utf8=%E2%9C%93&q=default_path_prefix

Nightwatch.js might also not be the best example, as I had an unfruitful discussion with the maintainer about Webdriver compatibility, as they have only poor support:
https://github.com/nightwatchjs/nightwatch/issues/1285

**Comment by andreastt** [comment]
I think even if we change geckodriver to allow setting the default path prefix to `/wd/hub`, you will still run into more issues with the differences between the Selenium WebDriver protocol and the W3C WebDriver protocol.

To return to the issue at hand: I personally like programs that you can pass a string that lets it deduce where to spin up a service, i.e.

    % geckodriver http://10.12.35.1:1234/foo/bar

might bind it to a non-TLS public interface on the `/foo/bar` path. However, this is a lot of added complexity for not much apparent gain, considering I think Nightwatch.js will likely run into more problems once it manages to create a session.

**Comment by blueimp** [comment]
I agree, passing in the full endpoint URL makes a lot of sense, I use that pattern myself.
I don't have any affiliation with Nightwatch.js other than that we use it as a capable e2e testing framework.

I'll close this ticket now as I don't wanna waste more of your time and like I said, if I should have a stronger need for this, I'll reopen with a pull request.

**Comment by andreastt** [comment]
I am slightly puzzled that Nightwatch.js implements the WebDriver API directly, but I do feel the right long-term solution would be to make it easier to configure where the endpoint where Nightwatch.js makes the connection.

FWIW I wouldn’t personally object to changing geckodriver to accept input that would set the path, but it’s not a priority for us.
