### ISSUE TITLE
Service geckodriver unexpectedly exited. Status code was: 2

### ISSUE THREAD

**Issue by ahmf200** [mozilla/geckodriver#345]
Hey everyone, I'm currently at a loss as to why I'm getting this issue, I've added geckodriver to PATH but still no luck. I'm using Selenium 3.0.1 but if you need anymore information, let me know ^^.

```
Traceback (most recent call last):
  File "test_script1.py", line 20, in <module>
    run_test()

  File "test_script1.py", line 6, in run_test
    driver = webdriver.Firefox()

  File "C:\Users\fahad.ahmed\Python3.5.2ACTUAL\lib\site-packages\selenium\webdri
ver\firefox\webdriver.py", line 135, in __init__
    self.service.start()

  File "C:\Users\fahad.ahmed\Python3.5.2ACTUAL\lib\site-packages\selenium\webdri
ver\common\service.py", line 86, in start
    self.assert_process_still_running()

  File "C:\Users\fahad.ahmed\Python3.5.2ACTUAL\lib\site-packages\selenium\webdri
ver\common\service.py", line 99, in assert_process_still_running
    % (self.path, return_code)

selenium.common.exceptions.WebDriverException: Message: Service geckodriver unex
pectedly exited. Status code was: 2 #
```

**Comment by andreastt** [comment]
Please have a look at the stdout and stderr from geckodriver. I believe the Selenium Python bindings stores this in a file called geckodriver.log in your current working directory by default. Otherwise you will have to modify the client binding’s source code to surface it.

**Comment by Poonam-Patnaik** [comment]
I am getting the same issue but unable to fix. Could you please provide the solution in detail.

**Comment by ahmf200** [comment]
Which python / geckodriver version are you using?

**Comment by Poonam-Patnaik** [comment]
Python 3.6  geckodriver  0.17

**Comment by whimboo** [comment]
You need at least Selenium 3.4 to run your test with geckodriver. So upgrade to that version.

**Comment by austinHeisleyCook** [comment]
selenium.common.exceptions.WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 2


Process finished with exit code 1

is anyone else  gettinh this bug

**Comment by andreastt** [comment]
Locking this thread because no one are able to provide a trace-level log. Read more about reporting actionable bugs in our [contribution guidelines].

[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs
