### ISSUE TITLE
Creating FirefoxDriver fails if log_path is not specified

### ISSUE THREAD

**Issue by JuryFrid** [mozilla/geckodriver#349]
Found on selenium v.3.0.1 for python.

Code which fails:
`driver = webdriver.Firefox(log_path = "")`
I've just wanted to run FF driver and do not have some trash logs I didn't expected.

Crash in Selenium occurs in
`selenium/webdriver/firefox/service.py`
on line 48.
Snippet of code (doc ommited):
`class Service(service.Service):

    def __init__(self, executable_path, port=0, service_args=None,
            log_path="geckodriver.log", env=None):

        if log_path:
            log_file = open(log_path, "a+")

        service.Service.__init__(
            self, executable_path, port=port, log_file=log_file, env=env)
        self.service_args = service_args or []`

In my case variable log_path is empty string and variable log_file doesn't exist. Using this variable emits crash.

**Workaround:**
use `webdriver.Firefox(log_path = os.devnull)`

**Comment by davehunt** [comment]
Thanks for the issue, it indeed looks like we need to avoid passing a value for `log_file` if `log_path` is not specified. Would you be interested in writing a test and patch for this?

**Comment by davehunt** [comment]
Sorry, I just noticed this is raised in the geckodriver project. Please could you raise it in Selenium: https://github.com/SeleniumHQ/selenium/issues

**Comment by JuryFrid** [comment]
Oops. Ok. I'll link it here.
