### ISSUE TITLE
Connection times out on navigating away from image document

### ISSUE THREAD

**Issue by theforgottenviking** [mozilla/geckodriver#350]
After navigating to a second image (_png, jpg_ or _gif_), despite the combination, a user of **Geckodriver** cannot navigate to another page or quit their browser.

**Machine Information**
```
jriddle@jriddle-ltm:/tmp$ uname -a
Darwin jriddle-ltm.internal.company.com 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

**Geckodriver Information**
```
geckodriver 0.11.1

The source code of this program is available at
https://github.com/mozilla/geckodriver.

This program is subject to the terms of the Mozilla Public License 2.0.
You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```
```
MD5 (geckodriver) = cf2b59b1b26728e86770b37429d061e5
```

**Ruby Script**
```
#!/usr/bin/env ruby

require 'selenium-webdriver'

# JPG
#link1       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-01.jpg"
#link2       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-02.jpg"

# PNG
#link1       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-01.png"
#link2       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-02.png"

# GIF
link1       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-01.gif"
link2       = "http://jesseriddle.me/geckodriver/bug-01/geckodriver-test-02.gif"


driver      = Selenium::WebDriver.for(:firefox)
sleep_val   = 2

puts "Driver: Open"
driver

puts "Navigating to #{link1}"
driver.get link1
puts "Sleeping for #{sleep_val} second(s)"
sleep(sleep_val)

puts "Navigating to #{link2}"
driver.get link2
puts "Sleeping for #{sleep_val} second(s)"
sleep(sleep_val)

puts "Navigating to http://www.googe.com"
driver.get "http://www.google.com"
puts "Sleeping for #{sleep_val} second(s)"
sleep(sleep_val)

puts "Driver: Quit"
driver.quit
```

**Net::Error**
```
/Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `catch'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1411:in `transport_request'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1384:in `request'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1377:in `block in request'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/jriddle/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:103:in `response_for'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:57:in `request'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:659:in `raw_execute'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:634:in `execute'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:146:in `get'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/navigation.rb:32:in `to'
	from /Users/jriddle/.rvm/gems/ruby-2.1.6/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:132:in `get'
	from ./test.rb:19:in `<main>'
```

**Comment by jgraham** [comment]
Can you post a trace-level log (see the README.md for how to set this in the capabilities)?

**Comment by theforgottenviking** [comment]
@jgraham ,

While I see how the log options. How do I pass this properly to the driver? That part of the documentation doesn't seem to exist. If provided, I wouldn't mind writing additional documentation to help others easily reference how to do this in the future.

**Comment by andreastt** [comment]
@theforgottenviking You need to consult your language binding’s documentation on how to set capabilities.

**Comment by theforgottenviking** [comment]
@andreastt 

Sorry, struggling to get the Moz:FirefoxOptions stuff to work properly (again, the documentation isn't really clear nor can I find examples of it in the wild)

I'm using Ruby, can you help me understand what I am not doing correctly?

```
caps    = Selenium::WebDriver::Remote::Capabilities.firefox("log", "{level: trace}")
driver  = Selenium::WebDriver.for :remote, :url => "http://localhost:4444/wd/hub", :desired_capabilities => caps
```

**Comment by andreastt** [comment]
You’re close. I think this would work:

```rb
caps = Selenium::WebDriver::Remote::Capabilities.firefox({"moz:firefoxOptions": {"log": {"level": "trace"}}})
driver = Selenium::WebDriver.for :remote, :url => "http://localhost:4444/wd/hub", :desired_capabilities => caps
```

**Comment by theforgottenviking** [comment]
No bueno. 

```
jriddle@jriddle-ltm:/var/tmp$ ./github_issue.rb 
./github_issue.rb:20: syntax error, unexpected ':', expecting =>
....firefox({"moz:firefoxOptions": {"log": {"level": "trace"}}})
...                               ^
./github_issue.rb:20: syntax error, unexpected ':', expecting =>
...({"moz:firefoxOptions": {"log": {"level": "trace"}}})
...                               ^
./github_issue.rb:20: syntax error, unexpected ':', expecting =>
...efoxOptions": {"log": {"level": "trace"}}})
...                               ^
./github_issue.rb:20: syntax error, unexpected '}', expecting end-of-input
...ns": {"log": {"level": "trace"}}})
...        

```

Heading to lunch, will try again when I get return

BTW: Rubocop(Static Code Analyzer) says the following:
```
jriddle@jriddle-ltm:/var/tmp$ rubocop github_issue.rb 
Inspecting 1 file
E

Offenses:

github_issue.rb:20:79: E: unexpected token tCOLON
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
caps = Selenium::WebDriver::Remote::Capabilities.firefox({"moz:firefoxOptions": {"log": {"level": "trace"}}})
                                                                              ^

1 file inspected, 1 offense detected
```

**Comment by andreastt** [comment]
Right, I don’t know Ruby syntax anymore:

```rb
caps = Selenium::WebDriver::Remote::Capabilities.firefox({"moz:firefoxOptions" => {:log => {:level => "trace"}}})```

**Comment by theforgottenviking** [comment]
@andreastt,

Thanks. That seems to have corrected the syntax error. Running into an issue with connection refused now 🙄

**Comment by andreastt** [comment]
That seems unrelated to this issue. Perhaps try to run the geckodriver locally instead of through a RemoteWebDriver.

**Comment by theforgottenviking** [comment]
@andreastt ,

Sorry, my experience in using capabilities is relatively limited. Would I did this, and the script executed by no trace log data was available on output.

`driver = Selenium::WebDriver.for :firefox, :desired_capabilities => {"moz:firefoxOptions" => {:log => {:level => "trace"}}}`

**Comment by andreastt** [comment]
It is probably being swallowed by the Ruby bindings you are using. I don’t know if it creates a geckodriver.log in your current working directory like Python does, but I’m sure there is some way to redirect it to stdout.

Perhaps @titusfortner knows.

**Comment by theforgottenviking** [comment]
@andreastt 

According to **https://www.w3.org/TR/webdriver/**, you can pass a file option.

```
"moz:firefoxOptions": {
      "binary": "/usr/bin/firefox",
      "args": ["--no-remote"],
      "prefs": {
        "dom.ipc.processCount": "8"
      },
      "log": {
        "level": "trace",
        "file": "/tmp/geckodriver.log"
      }
    }
```

**Comment by titusfortner** [comment]
The spec is what the bindings pass to the driver

Each language will translate code for that. Right now this works in Ruby. It's implemented the same way as the existing chrome_options, but I'll work on getting this better documented.

```
opts = {
      "binary": "/usr/bin/firefox",
      "args": ["--no-remote"],
      "prefs": {
        "dom.ipc.processCount": "8"
      },
      "log": {
        "level": "trace",
        "file": "/tmp/geckodriver.log"
      }
    }
caps = Selenium::WebDriver::Remote::Capabilities.firefox(firefox_options: opts)
driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps
```

**Comment by andreastt** [comment]
geckodriver unfortunately does not support a `file` key in `moz:firefoxOptions`.

**Comment by theforgottenviking** [comment]
Alright, looks like something else isn't quite right. When I executed what @titusfortner provided, nothing is written to stdout. I did have to change the semi-colons to hash rockets because Ruby was complaining about it (v2.1.6).

```opts = {
      "log" => {
        "level" => "trace",
      }
    }

caps = Selenium::WebDriver::Remote::Capabilities.firefox(firefox_options: opts)
driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps
```

**Comment by titusfortner** [comment]
Sigh. I think I need to implement new Options classes for Firefox & Chrome because of the Ruby string vs symbol confusions.

So far I've only tested profile & binary, so I don't know what log level looks like, yet.

Also, if you run that code with `$DEBUG = true` it will show you exactly what is getting sent to and returned from the driver, which is helpful in making sure it is geckodriver issues and not Ruby issues. :-D

**Comment by theforgottenviking** [comment]
There is also confusion between Ruby's 1.9 Hash Syntax vs the 'hash rockets' which are frowned upon by Rubocop (Ruby Style Guide)

**Comment by theforgottenviking** [comment]
@titusfortner Should they be strings or symbols?

**Comment by titusfortner** [comment]
Right, exactly. If the key is a string, then you need to use a hash rocket.

The Ruby code does the [translation for `:firefox_options`](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/w3c_capabilities.rb#L194-L195).

But inside the value itself, the keys need to be strings as well, hence the hash rockets
```
{"log" => {"level" => "trace"}}
```

So geckodriver should know what to do with that.

**Comment by andreastt** [comment]
IIRC a symbol is internally the same as a string in Ruby. `moz:firefoxOptions` is special because it contains `:` (colon). In other words, Ruby doesn’t care if you use a string or a symbol.

**Comment by theforgottenviking** [comment]
Lulz. So where does that leave me? 💃

**Comment by titusfortner** [comment]
What does this do?

```
$DEBUG = true
opts = {"log" => {"level" => "trace"}}
caps = Selenium::WebDriver::Remote::Capabilities.firefox(firefox_options: opts)
driver = Selenium::WebDriver.for :firefox, desired_capabilities: caps
# The rest of your code...
```

**Comment by theforgottenviking** [comment]
@titusfortner 

[Output is available here](http://jesseriddle.me/geckodriver/bug-01/debug-output.txt)

**Comment by jgraham** [comment]
@theforgottenviking Thanks! That's really helpful. This looks rather like a marionette issue that I suspect we can reproduce without geckodriver.

**Comment by theforgottenviking** [comment]
@jgraham ,
No worries. It's a really weird and interesting bug. Happy fixing! Glad I could help. 

@titusfortner, 
If you end up fleshing out stuff when it comes to the options confusion, hit me up. I'll be happy to walkthrough any changes and let you know where the documentation seems sparse.

**Comment by titusfortner** [comment]
Thanks @theforgottenviking 
We have a ruby-ruby-ruby-ruby channel on the [Selenium Slack](http://seleniumhq.herokuapp.com/) if you want to join in on the conversations about it :)

**Comment by andreastt** [comment]
Confirming that Marionette does not return when navigating to an image document. We probably make some assumptions that are only true for HTML/XHTML/SVG like documents in our navigation algorithm.

**Comment by andreastt** [comment]
This appears to reproduce when navigating to an image document then on to _any other_ document.

**Comment by andreastt** [comment]
Further investigation shows that we are not receiving DOMContentLoaded events for ImageDocuments (.gif/.jpg/.png). We will have to short-circuit the navigation algorithm in the web progress listener. Filed [bug 1322772](https://bugzilla.mozilla.org/show_bug.cgi?id=1322772).

**Comment by andreastt** [comment]
[Bug 1322772](https://bugzilla.mozilla.org/show_bug.cgi?id=1322772) was fixed and uplifted to Aurora, which means it will also be in the next ESR.

@theforgottenviking If you’d like, it would be useful if you could try to reproduce this with the [latest Firefox Nightly](http://nightly.mozilla.org/)?
