### ISSUE TITLE
Getting "Application Error" on using driver.quite() method

### ISSUE THREAD

**Issue by ranjprashant** [mozilla/geckodriver#351]
I am having Selenium (Java) version "3.0.1",Firefox version 50.0 (32 bit), OS Windows Server 2012 and geckodriver-v0.11.1-win32, while using  driver.quite() method, once browser is closed by selenium getting error as attached file.
![firefoxerror](https://cloud.githubusercontent.com/assets/1745155/20424742/70c23b52-ad45-11e6-9ef7-2e60d54a0ba0.png)
Also tried with 64 bit Firefox and gecko driver , same error found.

[Child 4780] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Nov 18, 2016 4:16:50 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 1152

**Comment by AutomatedTester** [comment]
Unfortunately this bug is not actionable. I am happy to reopen this bug when there are steps to reproduce this issue.
