### ISSUE TITLE
Segmentation Fault on Raspberry Pi Model B 1

### ISSUE THREAD

**Issue by raphasampaio** [mozilla/geckodriver#354]
I've downloaded the geckodriver-v0.11.1-arm7hf and returned segmentation fault when I tried to execute it on my Raspberry Pi Model B 1. My OS is Raspbian GNU/Linux 8.0 (jessie)

`pi@raspberrypi:~ $ ./geckodriver -v`
`Segmentation fault`

I tried to execute the same release on the Raspberry Pi Model B 3 and was successfully.

**Comment by jgraham** [comment]
Raspberry Pi series 1 seems to have an ARM6 processor so it doesn't work with an ARM7 binary. I don't think we plan to add support for older arm versions at this time, but you may be able to cross compile yourself using something like the arm-unknown-linux-gnueabihf target (I'm not sure).
