### ISSUE TITLE
After successful run of selenium java program getting below error

### ISSUE THREAD

**Issue by swapnilga** [mozilla/geckodriver#361]
Nov 23, 2016 4:47:38 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Nov 23, 2016 4:47:39 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

How can we remove above error?

I am using: 
Selenium version:- 3.0.1
Firefox version:- 47+
geckodriver version:- v0.11.1
Eclipse:- Neon release 4.6.0
[error.xlsx](https://github.com/mozilla/geckodriver/files/607826/error.xlsx)

**Comment by AutomatedTester** [comment]
That is not an error, as it shows it is an `INFO` level log and is coming from the Selenium project. If it is really an issue, raise with them
