### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by trotzig** [mozilla/geckodriver#366]
I maintain [happo](https://github.com/Galooshi/happo), an open source tool to prevent visual regressions. We're eagerly awaiting cb67c0aa66 so that we can speed up screenshotting individual elements. Is there any chance you can carve a new release with this new bit of functionality added?

**Comment by trotzig** [comment]
I'm closing this issue to reduce noise. I trust that the release will come when it is ready.

**Comment by andreastt** [comment]
Thank you. It will.

**Comment by lencioni** [comment]
It looks like there is a milestone tracking the next version: https://github.com/mozilla/geckodriver/issues?q=is%3Aissue+milestone%3A0.12+is%3Aopen

**Comment by andreastt** [comment]
I think we want to postpone some of those to 0.13. I will update the list accordingly.

**Comment by andreastt** [comment]
Updated https://github.com/mozilla/geckodriver/milestone/2 for 0.12 and created https://github.com/mozilla/geckodriver/milestone/3 for 0.13.
