### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver

### ISSUE THREAD

**Issue by woof09** [mozilla/geckodriver#371]
Hi, Could any one please help :( 

I am trying to set up a Selenium using PyCharm as IDE with Python.
I am using Python 2.7.12, Selenium 2.7, Mac OS Sierra, Firefox 50.0.1.
I am installing the site-packages using **pip** (with **get-pip.py** file)

Below is the structure of what the Libraries look like;
<img width="1266" alt="screen shot 2016-11-30 at 10 50 48 am" src="https://cloud.githubusercontent.com/assets/24259555/20734017/c694a3b8-b6ea-11e6-8d19-e38fc003e644.png">

This is the code that I am trying to run:
``from selenium import webdriver``
``from selenium.webdriver.common.keys import Keys``

``driver = webdriver.Firefox()``
``driver.get("http://www.python.org")``
``assert "Python" in driver.title``
``elem = driver.find_element_by_name("q")``
``elem.clear()``
``elem.send_keys("pycon")``
``elem.send_keys(Keys.RETURN)``
``assert "No results found." not in driver.page_source``
``driver.close()``

I have edited the System PATH as well;
`$cat paths`
`/usr/local/bin`
`/usr/bin`
`/bin`
`/usr/sbin`
`/sbin`
`/Users/cicilia/Documents/webdrivers/chrome`
`/Users/cicilia/Documents/webdrivers/firefox`

_I saved the geckodriver on that path_

I keep getting this error:
`/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/cicilia/PycharmProjects/CiciliaAutomation/searchproducts.py`
`Traceback (most recent call last):`
  `File "/Users/cicilia/PycharmProjects/CiciliaAutomation/searchproducts.py", line 4, in <module>
    driver = webdriver.Firefox()`
  `File "/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
    self.service.start()`
 ` File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 92, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)`
`selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service geckodriver`

``Process finished with exit code 1``

What did I miss?

**Comment by davehunt** [comment]
Your Selenium version of '2.7' doesn't match a recent release. Please try installing the latest python bindings for Selenium (currently 3.0.2) and try again. Also, I see you have a geckodriver.log. If you're still having issues please share the contents of that file.

**Comment by woof09** [comment]
Hi @davehunt , thank you for your reply.

I just did an upgrade on the binding by doing
`$sudo python setup.py install`

I downloaded the files from https://pypi.python.org/pypi/selenium

I re run the code but still giving me the same error.
below is the **geckodriver.log** file looks like.

<img width="1272" alt="screen shot 2016-12-01 at 10 23 36 am" src="https://cloud.githubusercontent.com/assets/24259555/20775844/22f6027a-b7b1-11e6-8b07-fc51b4b146ba.png">


Also, I noticed it has multiple interpreter URLs
/Library/Python/.... 
/System/Library/Framework/Python.Framework/...

<img width="1071" alt="screen shot 2016-12-01 at 10 32 51 am" src="https://cloud.githubusercontent.com/assets/24259555/20775905/775b3ef2-b7b1-11e6-98d4-d4cf780cb86e.png">

I tried both of the interpreter but still not doing the job

any idea?

**Comment by woof09** [comment]
Managed to fix this.
I reset my mac and delete the HDD and start from the beginning again.
Something with the installation.

All good now.

**Comment by chenea** [comment]
seriously？ Do you ever know what wrong here? cause i met with this problem and can't find a good way to do.

**Comment by chenea** [comment]
Solved in https://github.com/SeleniumHQ/selenium/issues/2903
