### ISSUE TITLE
Conditions in checking if element exist/not

### ISSUE THREAD

**Issue by woof09** [mozilla/geckodriver#377]
Hi,

I am having problem figuring out this logic by using the find by element API in selenium webdriver using Python.
I am trying to check if an error message is appeared. IF yes, then do A, IF not then do B.
It's always throwing me error which element doesn't exist instead of moving to B if it does.

Any idea?

 ```
if (browser_init.firefoxDriver.find_element_by_xpath("//div[@role='alert'][@class='alert alert-info']").is_displayed() != 0):
                print ("Account is Suspended")
            elif (browser_init.firefoxDriver.find_element_by_xpath("//div[@role='alert'][@class='alert alert-info']").is_displayed() == 0):
                print ("Account is Active")
```

**Comment by cgoldberg** [comment]
you can use exception handling as flow control.  catch `NoSuchElementException` when `find_element_by_xpath` fails:

```
from selenium import webdriver

driver = webdriver.Firefox()
driver.get(url)

try:
    xpath = "//div[@role='alert'][@class='alert alert-info']"
    driver.find_element_by_xpath(xpath):
    print("Account is Suspended")
except NoSuchElementException:
    print("Account is Active")
```

**Comment by woof09** [comment]
hi @cgoldberg , Thank you.
Yep managed to figure this out using your solution as well.

Thanks heaps.
