### ISSUE TITLE
Add 32-bit Windows to releases

### ISSUE THREAD

**Issue by DrMarcII** [mozilla/geckodriver#38]
We are using 32-bit Windows in our test infra at Google, so a 32-bit build add to the release would be helpful.

**Comment by AutomatedTester** [comment]
This was done in 0.7.1

**Comment by andreastt** [comment]
Related to this we want to use Travis to make releases, which is tracked in #72 and depends on #73.

**Comment by juangj** [comment]
The most recent release contained a 64-bit build, but not a 32-bit one. Could we get a 32-bit Windows binary? Is building it reasonably automatable, or no?

**Comment by furqanmlk** [comment]
Have you guys figured that issue out?

I still cant find geckodriver for Win 32 but machine

**Comment by andreastt** [comment]
@furqanmlk The necessary changes have landed and we are building i686-pc-windows-gnu targets in CI, but we haven’t released a new version of geckodriver yet. See the [milestone](https://github.com/mozilla/geckodriver/milestone/1) for the remaining issues.
