### ISSUE TITLE
Geckodriver hanging when the script is failing.

### ISSUE THREAD

**Issue by Sourabh25** [mozilla/geckodriver#382]
Whenever the script is failing, the geckodriver hang every time. I have to kill the process. I am using selenium webdriver 3.0.1 with FF 49. The script is working fine in chrome.

**Comment by jgraham** [comment]
I would love to help you, but without the information in the issue template, particularly a log, it's impossible to tell what's happening here. I don't know what you mean by "script is failing" for example. I will reopen this issue if you can provide that extra information.
