### ISSUE TITLE
Will geckodriver protocol follow WebDriver general specifiction?

### ISSUE THREAD

**Issue by zdm** [mozilla/geckodriver#391]
WebDriver spec. describes JSON response structure.
PhantomJS and chromedriver follows this spec., but geckodriver responds in own format.
This make geckodriver not portable and requires additional efforts to integrate it in webdrivers stack.
For example, in case of error remote API should return:
```
{
    session_id: "<session-id>",
    status: "<status>",
    value: "<value>"
}
```

other example, when webelement found, API return:
```
{
    ELEMENT: "<element-id>"
}
```
but geckodriver returns:
```
{
    "<element-id>": "<element-id>"
}
```
I am sorry, but who decided to return hash with random key?
etc...

**Comment by jgraham** [comment]
geckodriver will follow the [w3c spec](https://w3c.github.io/webdriver/webdriver-spec.html). It will not follow the legacy Selenium protocol. There have been some recent changed in the spec that are not yet reflected in current geckodriver, however I don't think that affects the examples above.

**Comment by zdm** [comment]
Please, look at this part of spec, that you are follows:

https://w3c.github.io/webdriver/webdriver-spec.html#handling-errors

Geckodriver returns completely different results.

**Comment by andreastt** [comment]
And just to be clear here, it is PhatnomJS and chromedriver that does not follow the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html).
