### ISSUE TITLE
iFrame window not closed and browser not response more. Browser stuck every time when  iFrame window close code execute

### ISSUE THREAD

**Issue by miranivishal** [mozilla/geckodriver#400]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version :
50.1.0

## Platform
Windows

## Steps to reproduce -
Step 1 : Switch to iFrame window using cssselector with below code.
driver.switchTo().frame(driver.findElement(By.cssSelector("iframe[id='winpopup_content']")));

Step 2 : Now close this pop up window by cross sign option with below issue.
driver.findElement(By.xpath("html/body/div[2]/div")).click();

While second step going to execute, it just crashed browser and give exception breakpoint breakpoint has been reached 0x80000003 error.

Note: I was using above code for last 6 month daily basis with Mozila 42.0 and Selenium 2.53.0 but after apply Mozila Latest version with Selenium 3.0.1 & geckodriver it start throwing error and I can't get any online solution for that.

**Comment by AutomatedTester** [comment]
For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

If a [concise reproducible test case](http://sscce.org/) is not added within the next 4 weeks this issue will be closed. 

See [CONTRIBUTING.md](https://github.com/mozilla/geckodriver/blob/master/CONTRIBUTING.md#issue-reports)

**Comment by andreastt** [comment]
Not reproducible and no new information added. Closing. Happy to reopen if this is provided.
