### ISSUE TITLE
Inconsistent logging returned when port is already in use

### ISSUE THREAD

**Issue by johndharrison** [mozilla/geckodriver#401]
Firefox Version: 50.0.2
Gecko Driver Version:  geckodriver-v0.11.1-linux64.tar.gz
Platform: Ubuntu 16.04

Start geckodriver or any other process so port gecko will use is blocked.

Start another geckodriver process:

```
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175045210	webdriver::httpapi	DEBUG	Creating routes
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175046619	webdriver::httpapi	DEBUG	Creating routes
1482175046622	geckodriver	ERROR	Address in use (os error 98)
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175047962	webdriver::httpapi	DEBUG	Creating routes
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175048978	webdriver::httpapi	DEBUG	Creating routes
1482175048981	geckodriver	ERROR	Address in use (os error 98)
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175049906	webdriver::httpapi	DEBUG	Creating routes
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175050674	webdriver::httpapi	DEBUG	Creating routes

```

The return from the logs is inconsistent. The port geckodriver is to use is not free. We see

- Sometimes no logging reported

- Sometimes "1482163849037	webdriver::httpapi	DEBUG	Creating routes"

- Sometimes
"1482163849037	webdriver::httpapi	DEBUG	Creating routes"
"1482163849040	geckodriver	ERROR	Address in use (os error 98)"

Expected behaviour when port is already in use:

```
john@ubuntu:~/.local/share/binman_geckodriver/linux64/0.11.1$ ./geckodriver --log trace
1482175046619	webdriver::httpapi	DEBUG	Creating routes
1482175046622	geckodriver	ERROR	Address in use (os error 98)
```

**Comment by andreastt** [comment]
Confirmed. We’re doing something wrong in our setup of slog in https://github.com/mozilla/geckodriver/blob/master/src/logging.rs#L106-L120.

**Comment by codenoid** [comment]
closed ? why ?

**Comment by andreastt** [comment]
This bug wasn’t about the actual error, but that the error message was inconsistently logged.

The error you’re seeing means you already have something bound to said port. A trick is to bind to port 0 and have the system atomically allocate a free port.

**Comment by codenoid** [comment]
`A trick is to bind to port 0 and have the system atomically allocate a free port.`

with geckodriver ?, how ? '-'

**Comment by andreastt** [comment]
`geckodriver --port 0`

**Comment by codenoid** [comment]
@johndharrison are you use selenium ?
