### ISSUE TITLE
Cannot get window's size/position if the display is scaled

### ISSUE THREAD

**Issue by yoongu** [mozilla/geckodriver#405]
**System Setup:**

- Windows 10
- Firefox 50.1.0
- GeckoDriver 0.11.1
- Selenium 3.0.1

**Steps to Reproduce:**
1. Increase the DPI scaling of the display from 100% to some larger value [1]. This is how things are configured by default on laptops with high-resolution displays, e.g., Dell XPS13.
2. Launch Firefox and try to get the size/position of the window.

**Symptom:**
An exception is raised with the message `Failed to interpret x as integer`, or `Failed to interpret height as integer`.

**Likely Explanation:**
When the display is scaled, the window could have a floating-point size/position. But geckodriver assumes that they should always be integers, and tries to convert them to `u64` [2], which fails.

**Suggested Fix:**
The WebDriver standard does indeed specify the size/position values to be integers [3]. But when their actual values are floating-point, could geckodriver possibly round them to be integers, instead of trying to convert them to integers (which would fail)?

[1] http://www.windows10update.com/2015/05/windows-10-tutorials-79-change-dpi-scaling-level-for-displays/
[2] https://github.com/mozilla/geckodriver/blob/master/src/marionette.rs#L552
[3] https://w3c.github.io/webdriver/webdriver-spec.html#resizing-and-positioning-windows

**Comment by andreastt** [comment]
I’ve never come across scaled high-DPI displays that have floating point resolutions. Are you sure this is a thing?

**Comment by yoongu** [comment]
I don't fully understand how Windows handles dpi-scaling, but yes I'm very sure that I'm getting floating point numbers for the browser window's coordinates. I think the problem may be reproduced on any monitor as long as the dpi is larger than 100% -- it's 250% on my laptop.

**Comment by andreastt** [comment]
What does `window.screenX`/`window.screenY` give you in the devtools console?

**Comment by andreastt** [comment]
Marionette quite literally uses `window.screenX`/`window.screenY` to determine the window’s position: https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/browser.js#L271-L279

For the sake of completeness, what does `window.outerWidth`/`window.outerHeight` give you on a scaled display? The Marionette implementation is https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/driver.js#L2507-L2518.

**Comment by yoongu** [comment]
Hmm... `window.outerWidth/Height` is also giving me integers. I just tried to replicate this issue on my laptop again (I usually work on my desktop), but I can't seem to... I think I may have conflated this issue with the other one I filed: #404.

Thanks for looking into this, and I'll close this issue at this time.

**Comment by andreastt** [comment]
@yoongu Thanks for the quick turnaround from your side. I think #404 is a real issue and I’ve filed https://github.com/mozilla/webdriver-rust/pull/55 to address it in the WebDriver Rust library. It also requires a change in geckodriver once we upgrade the dependency.

**Comment by yoongu** [comment]
Thank you Andreas.
