### ISSUE TITLE
Can not open a new tab by sending COMMAND-t from robotframework

### ISSUE THREAD

**Issue by lamcee** [mozilla/geckodriver#406]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.1.0

## Platform
macOS 10.12.2

## Steps to reproduce -
My robot framework script would be

```
*** Settings ***
Library           Selenium2Library

*** Variables ***
${URL}         http://www.bing.com

*** Test Cases ***
Test Tab Open
    Open Browser   ${URL}     Firefox
    Sleep     3
    Press Key    xpath=.//BODY     CONTROL-t
    #Press Key    xpath=.//BODY     COMMAND-t
```

Actually it will open `http://www.bing.com` but there's no new tab be opened. I've tried both `CONTROL-t` and `COMMAND-t`

**Comment by andreastt** [comment]
This is expected behaviour, as WebDriver does not automate UI, but the web platform. Control + T should fire the appropriate keydown/keyup/keypress DOM events, but not necessarily open a new tab since this is a security escalation issue that lets you escape from content to chrome space.
