### ISSUE TITLE
Firefox tests failed to run

### ISSUE THREAD

**Issue by alek75** [mozilla/geckodriver#408]
## Firefox Version
50.1.0/latest gecko driver

## Platform
virtual machine /Windows Server 2012/node.js (webdriverio test framework)

## Steps to reproduce -
The issue occurs in our CI solution. When a build is triggered the following error is thrown - 

\node_modules\cucumber\lib\cucumber\runtime\event_broadcaster.js:30
            throw error;
            ^
function timed out after 10000 milliseconds

which does not bring a lot of information and i believe it is not the main reason as the suite is running fine when its triggered manually on my pers machine, when I log in virtual machine and run tests, again, manually. I do not have such issue with other browsers and i did try a lot of different configurations in the test framework services as versions.

The only difference i can notice at this point is that when a build is triggered no real display is presented as all things are launched as services, system user ect. I did manage to run the suite against latest firefox in a cloud solution - BrowserStack - but there you can watch how the suite is running real time i.e there is something like a virtual screen (just guess).

NOTE: Everything runs smoothly with 49.0 version of firefox

Cheers

**Comment by andreastt** [comment]
You will need to include a verbose log from geckodriver and more detailed steps to reproduce this issue if we are to have a chance at finding out what is wrong and potentially fixing it. See the README for how to configure geckodriver to produce verbose logs.

I’m happy to re-open this issue when it contains enough information to be actionable.

**Comment by alek75** [comment]
Hello, 

Today I've tried to do as suggested but i guess my lack of knowledge did not allow me to do it. This will take time i guess... 
If you some of you have time to spend in it it is very easy to reproduce. All you need is to have a build set up with Jenkins or TfsBuildAgent to run on a VM (WinServer2012). 

I'll give a try again to get logs though

Cheers lads

**Comment by alek75** [comment]
Hello guys, 

I've got something, not exactly sure that it is the thing you're need but still is something....
[selenium.txt](https://github.com/mozilla/geckodriver/files/687344/selenium.txt)

Regards

**Comment by andreastt** [comment]
That log is not sufficient, I’m afraid.

**Comment by alek75** [comment]
Take a look at this one...
[selenium.txt](https://github.com/mozilla/geckodriver/files/689950/selenium.txt)

**Comment by alek75** [comment]
Ok, I've deleted my last post as I am thinking that this file is more close to what we are looking at (hopefully) ...
[selenium.txt](https://github.com/mozilla/geckodriver/files/689970/selenium.txt)

**Comment by alek75** [comment]
Still no?

**Comment by jgraham** [comment]
I don't think that has the trace level logging that would be most helpful here, but I think it's closer. Can you try one more with trace level logs in the capabilities?

**Comment by alek75** [comment]
The logs I've posted above are done with this configuration. Is this same as you suggested in your last post?

capabilities: [
        {
            maxInstances: 1,
            browserName: 'firefox',
            marionette: true,
            FirefoxOptions: {
                "log": {
                    "level": "trace"
                }
            }
        }
    ],
