### ISSUE TITLE
Aborting on channel error: ipc/glue/MessageChannel.cpp, line 2046

### ISSUE THREAD

**Issue by rjulie95** [mozilla/geckodriver#409]
In order to help us efficiently investigate your issue, please provide the following information:

## Steps to reproduce -
I launch this command : java -jar selenium-html-runner-3.0.1.jar -htmlSuite "*firefox" "http://google.fr" "y:\Imacros\Macros\Femina.html" "c:\tmp\seleniumResults.html"

 - [ ] A *minimal* HTML file 
[FeminaTest.html.txt](https://github.com/mozilla/geckodriver/files/677827/FeminaTest.html.txt)

 - [ ] A [trace level log]

[geckodriver.txt](https://github.com/mozilla/geckodriver/files/677833/geckodriver.txt)

[LogSelenium.txt](https://github.com/mozilla/geckodriver/files/677838/LogSelenium.txt)

I have this error message and i don't know why

Thank

**Comment by andreastt** [comment]
Unable to reproduce this. You also did not include a trace-level verbose log from geckodriver, which you can get by passing `-vv` or setting the `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` capability.

I am happy to consider re-opening this if you add sufficient information that we can reproduce it.
