### ISSUE TITLE
gecko driver issue

### ISSUE THREAD

**Issue by jithu121212** [mozilla/geckodriver#410]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.1.0

## Platform
Linux Mint

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function stopIfBlocked() on null

**Comment by andreastt** [comment]
Not a geckodriver issue, but a Symfony issue.
