### ISSUE TITLE
gecko driver issue #2

### ISSUE THREAD

**Issue by jithu121212** [mozilla/geckodriver#411]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.0.1

## Platform
Linux Mint

## Steps to reproduce -

[Facebook\WebDriver\Exception\UnknownServerException]                                  
  The driver is not executable: /home/d4/yii/yii2-app-basic/selenium-server/geckodriver

**Comment by andreastt** [comment]
Unable to reproduce. Quite possibly you have downloaded the wrong executable for your system?
