### ISSUE TITLE
Cannot maximize the Firefox when use geckodriver on selenium to launch browser 

### ISSUE THREAD

**Issue by John0731** [mozilla/geckodriver#412]
Hi guys,

I've updated my selenium version from 2.53.0 to 3.0.1 just now and also try to use geckodriver to lanch Firefox on selenium.

When I use statement  "driver.manage().window().setSize(new Dimension(1920,1080))" try to maximize the Firefox then occurred the error.  After noted this statement that it can works well.

I attacked two logs that you can take a look at them.

[Failed_Log.txt](https://github.com/mozilla/geckodriver/files/681988/Failed_Log.txt)
[Passed_Log.txt](https://github.com/mozilla/geckodriver/files/681989/Passed_Log.txt)

Thanks,
John

**Comment by andreastt** [comment]
Please include a trace-level verbose log from geckodriver by either passing `-vv` or configuring the `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` capability. That “maximising a window fails” is not a useful bug report.

I’m happy to re-open this issue if you add enough information that it is reproducible. I will add that resizing the window works fine in the WPT tests on Linux. You also did not add any information regarding what system you are on or which versions of Firefox and geckodriver you are using.
