### ISSUE TITLE
AcceptUntrustedCertificates capability not working

### ISSUE THREAD

**Issue by JoshuaBurns** [mozilla/geckodriver#420]
Firefox 50.1.0
Selenium Webdriver 3.0.1
Selenium Support 3.0.1
geckodriver v0.12.0-win64.zip
Nunit 3.4.1

I am unable to navigate to unsecured sites.  I can verify that on Firefox 46.0.1 with Selenium 2.53 that I am able to navigate to the untrusted site. Upgraded Selenium, Firefox, and using geckodriver and I am unable to go to the same internal site. 

Here is what I was running

```
using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Firefox;
using POMAuctivaTest.AuctivaPageModels;

namespace POMAuctivaTest.TestSuite
{
    [TestFixture]
    [Category("test")]
    public class Test
    {
        public IWebDriver driver { get; set; }
        [OneTimeSetUp]
        public void setUp()
        {
            FirefoxProfile ffProfile = new FirefoxProfile();
            //ffProfile.SetPreference("acceptInsecureCerts", true);
            ffProfile.AcceptUntrustedCertificates = true;
            driver = new FirefoxDriver(ffProfile);
        }

        [Test]
        public void test()
        {            
            driver.Manage().Window.Maximize();
            driver.Navigate().GoToUrl("https://expired.badssl.com/");
            System.Threading.Thread.Sleep(5000);        
            driver.FindElement(By.CssSelector("#content > h1"));   // expired.badssl.com header  
        }

        [OneTimeTearDown]
        public void tearDown()
        {
            driver.Quit();
        }
    }
}
```

Not sure if I set the property correctly but being that by default it is `true` makes this seem to be a bug.

**Comment by andreastt** [comment]
You are using a Firefox that is too old. Please use [Firefox Nightly](https://nightly.mozilla.org/) when using geckodriver.

**Comment by JoshuaBurns** [comment]
Ahh ok thank you. 

Do you know when I should be able to use geckodriver with Firefox Stable release? I like to keep my testing environment as close to the user as possible so prefer to keep browsers on the latest stable release.

**Comment by andreastt** [comment]
As you can tell from the tracking information in [bug 1103196](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196), the `acceptInsecureCerts` capability will be available in Firefox 52, which is the [current](http://whattrainisitnow.com/) Aurora/Dev Edition.

It’s hard to say when geckodriver and Marionette will be feature complete, but you can [track the current implementation status on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status).

**Comment by JoshuaBurns** [comment]
:+1:

**Comment by ambirag** [comment]
@andreastt 
I am using 
52.0a2 (2017-01-09) (64-bit) (Aurora as suggested) , 
Selenium Webdriver 3.0
GeckoDriver - 0.13.0

I have the following in profile:
` profile['accept_untrusted_certs']=true`
`profile['acceptInsecureCerts'] = true`
`profile['assume_untrusted_certificate_issuer']=false`

When I run the test, i get this error
`Exception when launching Firefox browser, retrying after 10 seconds: Given platformVersion [object String] "any", but current platform version is [object String] "16.1.0"`

**Comment by andreastt** [comment]
@ambirag That seems unrelated to this issue. I recently landed https://bugzilla.mozilla.org/show_bug.cgi?id=1326534 which rewrote the capabilities parsing in Marionette to _more_ conforming to the WebDriver specification. It seems that the client you are using is sending "any" for the `platformVersion` capability, which doesn’t match "firefox". You should either not set it (null), set it to "*" (match anything), or "firefox".

**Comment by andreastt** [comment]
I filed https://github.com/SeleniumHQ/selenium/issues/3345 about the "any" issue.

**Comment by ambirag** [comment]
thanks @andreastt 
I managed to go past this error by doing this
`capabilities['platformVersion']= "16.1.0"`
But even though I am using 52.0a2 (2017-01-11) (64-bit) (64-bit) - Aurora , i still get this insecure connection error.

**Comment by andreastt** [comment]
I don’t really know what you’re getting past. As I said, you _need to use_ the most recently Nightly.

**Comment by ambirag** [comment]
@andreastt what I meant is, even when I use the following combination of things
52.0a2 (2017-01-13) (64-bit) DailyEdition,
Selenium Webdriver 3.0
GeckoDriver - 0.13.0, i still get this "your connection is not secure" error 
https://support.mozilla.org/en-US/kb/troubleshoot-SEC_ERROR_UNKNOWN_ISSUER?as=u&utm_source=inproduct

**Comment by andreastt** [comment]
@ambirag Did you even read what I wrote? Please do me the decency to read what I write before replying.

Please use the latest Firefox Nightly you can get from https://nightly.mozilla.org/.

**Comment by JoshuaBurns** [comment]
@andreastt 

Firefox 52.0 was released today, which was the version this [bug 1103196](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196) was "VERIFIED FIXED" in. 

GeckoDriver 0.14.0
Nunit 3.6.1
Selenium 3.2
Firefox 52.0 (32-bit)

```
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using System;

namespace POMAuctivaTest.TestSuite
{
    [TestFixture]
    [Category("test")]
    public class Test
    {
        public IWebDriver driver { get; set; }
        [OneTimeSetUp]
        public void setUp()
        {
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
            FirefoxProfile ffprofile = new FirefoxProfile();
            ffprofile.AcceptUntrustedCertificates = true;
            FirefoxOptions options = new FirefoxOptions();
            options.Profile = ffprofile;
            driver = new FirefoxDriver(service, options, TimeSpan.FromSeconds(90));
        }

        [Test]
        public void test()
        {
            driver.Manage().Window.Maximize();
            driver.Navigate().GoToUrl("https://expired.badssl.com/");
            System.Threading.Thread.Sleep(5000);
            driver.FindElement(By.CssSelector("#content > h1"));   // expired.badssl.com header 
        }

        [OneTimeTearDown]
        public void tearDown()
        {
            driver.Quit();
        }
    }
}
```

This is still throwing a `NoSuchElementException` as the page is blocked. Did I do something wrong here or is this still not fixed in the stable release of Firefox 52?

**Comment by fenollp** [comment]
@JoshuaBurns 
You still need to equivalent of 
```python
capa = DesiredCapabilities.FIREFOX
capa['loggingPrefs'] = {'browser':'ALL'}
capa['acceptSslCerts'] = True
capa['acceptInsecureCerts'] = True

driver = webdriver.Firefox(capabilities=capa)
```

**Comment by JoshuaBurns** [comment]
So I am have tried you suggestion and I am still unable to access unsecured certs. I am attaching screenshots of two different ways I tried initializing the driver. The screenshots show that when I debug the driver I can see that the `acceptInsecureCerts` capability is not getting set to `true`. This seems like a bug to me and will open a new ticket if you believe it is. But maybe I am not initializing this correct for C#

![geckodriver-acceptinsecurecerts1](https://cloud.githubusercontent.com/assets/19497855/23712144/d773397c-03d6-11e7-8b79-20930164e2d7.png)
![geckodriver-acceptinsecurecerts2](https://cloud.githubusercontent.com/assets/19497855/23712143/d770a126-03d6-11e7-88ec-50f5f099318f.png)

**Comment by binken** [comment]
I also have the same issue.

**Comment by binken** [comment]
I also have the same issue for 52 version

**Comment by andreastt** [comment]
It would be useful if someone could attach a trace-level log from geckodriver. It is explained in the README how to crank up the logging verbosity. (Basically turn on the `{"moz:firefoxOptions: {"logging": {"level": "trace"}}}` capability.)

**Comment by andreastt** [comment]
Also, I should add you need to be using Firefox Nightly.

**Comment by JoshuaBurns** [comment]
I would like to provide a trace-level log for geckodriver but am not sure where the log writes to. I have initialized my browser with the following setup 

 ```
           FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
            service.FirefoxBinaryPath = @"C:\Program Files\Nightly\firefox.exe";
            FirefoxProfile profile = new FirefoxProfile();
            profile.AcceptUntrustedCertificates = true;
            profile.AssumeUntrustedCertificateIssuer = true;
            FirefoxOptions ffoptions = new FirefoxOptions();
            ffoptions.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
            ffoptions.AddAdditionalCapability(CapabilityType.HasNativeEvents, true);            
            ffoptions.AddAdditionalCapability("acceptSslCerts", true);
            ffoptions.AddAdditionalCapability("acceptInsecureCerts", true);
            ffoptions.LogLevel = FirefoxDriverLogLevel.Trace;
            ffoptions.Profile = profile;

            driver = new FirefoxDriver(service, ffoptions, TimeSpan.FromSeconds(30));
```

And did not see any logs added to my project directory.

**Comment by binken** [comment]
It is working by using the Nightly Build. But I would like to know why it's not working by using Firefox 52.
When we can use the formal release version for the testing?

**Comment by JoshuaBurns** [comment]
@binken -- How are you setting your binary path to the nightly firefox.exe? I was unable to get my tests to even launch Nightly kept launching FF 52 even when I explicitly set the binary path in the above example.

**Comment by andreastt** [comment]
The geckodriver log is written to stdout. I don’t know if it is captured by the Selenium bindings you are using.

**Comment by andreastt** [comment]
@binken If you consult the README, you can use `{"moz:firefoxOptions": {"binary": "/path/to/nightly"}}` to set the Firefox binary path.

**Comment by bobmshannon** [comment]
I am also having this issue using Geckdriver 0.15 coupled with Selenium 3.3.0.

**Comment by binken** [comment]
I am quite interested in when we can use the formal release not the nightly

**Comment by JoshuaBurns** [comment]
@andreastt: Here are some geckodriver trace logs.

Firefox Nightly 55 WORKED
[Nightly55.0a1_2017_03_16_TRACE.txt](https://github.com/mozilla/geckodriver/files/848042/Nightly55.0a1_2017_03_16_TRACE.txt)


Firefox 52.0 (32-bit) NOT WORKING
[FF52.0_trace.txt](https://github.com/mozilla/geckodriver/files/848046/FF52.0_trace.txt)

I accidentally ran against Firefox 47.02 and it worked?! Ill include the trace in case it helps with anything. 
[FF47.02_trace.txt](https://github.com/mozilla/geckodriver/files/848065/FF47.02_trace.txt)


And here is how I was initializing the driver instance. 
```
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
service.Port = 4444;
FirefoxProfile profile = new FirefoxProfile();
profile.AcceptUntrustedCertificates = true;
profile.AssumeUntrustedCertificateIssuer = true;
FirefoxOptions ffoptions = new FirefoxOptions();
//ffoptions.BrowserExecutableLocation = @"C:\Program Files\Nightly\firefox.exe";
ffoptions.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);            
ffoptions.AddAdditionalCapability(CapabilityType.HasNativeEvents, true);            
ffoptions.AddAdditionalCapability("acceptSslCerts", true);
ffoptions.AddAdditionalCapability("acceptInsecureCerts", true);
ffoptions.SetLoggingPreference(LogType.Browser.ToString(), LogLevel.All);
ffoptions.LogLevel = FirefoxDriverLogLevel.Trace;
ffoptions.Profile = profile;
driver = new FirefoxDriver(service, ffoptions, TimeSpan.FromSeconds(30));
```

**Comment by andreastt** [comment]
Glad it is working in Nightly.

**Comment by joejoseph00** [comment]
[for those using behat/selenium/php firefox , and need to acceptInsecureCerts , might want to look at my comment here](https://github.com/SeleniumHQ/docker-selenium/issues/518#issuecomment-355386858)

**Comment by java123code** [comment]
Firefox driver is not getting launch on **Virtual machine**
   1. resources I used : C# , Selenium 3.8 , VS 2017, Jenkins , VM machine (windows 10) , Nunit v3.9, geckoDrive v19,  firefox v56/57 

    2. I can execute firefox / chrome browser cases on local machine 

    3. I can execute chrome browser cases on VM machine 

    4. Issue : **I can Not execute firefox cases on VM machine and its throwing below error.** 

OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost:50352/

TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
I am adding few code below where issue is throwing issue
Stacktrace

   at OpenQA.Selenium.DriverService.Start()
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(String geckoDriverDirectory, FirefoxOptions options, TimeSpan commandTimeout)
   at MPAutomation.Driver.Initialize(String browser) in D:\Workspace.Automation\MPproject\MPAutomation\Utility\Driver.cs:line 79
# code on this line : Instance = new FirefoxDriver(service.FirefoxBinaryPath, options, TimeSpan.FromSeconds(10));  
  at MPAutomation.BaseTest.Init() in D:\Workspace.Automation\MPproject\MPAutomation\Utils\BaseTest.cs:line 54
  #code here :  LoginPage.GoTo(Settings.BrowserType); # I am passing "Firefox"
--TearDown
   at MPAutomation.Driver.Close() in D:\Workspace.Automation\MPproject\MPAutomation\Utility\Driver.cs:line 117
   # Instance.Close();
   at MPAutomation.BaseTest.Cleanup() in D:\Workspace.Automation\MPproject\MPAutomation\Utils\BaseTest.cs:line 97


-------------------------------------------------------------
here is implementation : 
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(DrivePath);
                service.FirefoxBinaryPath = DrivePath;
                FirefoxProfile profile = new FirefoxProfile();
                profile.AcceptUntrustedCertificates = true;
                FirefoxOptions options = new FirefoxOptions();
                options.AcceptInsecureCertificates = true;
                options.Profile = profile;
                Instance = new FirefoxDriver(service.FirefoxBinaryPath, options, TimeSpan.FromSeconds(100));
                Instance.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);           
                Utility.Logger.Write("***** Firefox Browser has been initialized now  *********");

      public static string GetDriverPath()
        {
            
            var outPutDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var relativePath = @"..\..\bin\Debug\BrowserDriver";
            //var relativePath = @"..\..\bin\Debug";
            var DriverPath = Path.GetFullPath(Path.Combine(outPutDirectory, relativePath));
            return  DriverPath;
        }

**Comment by andreastt** [comment]
@java123code Please don’t hijack closed issues.
