### ISSUE TITLE
Can firefoxOptions contain both prefs and profile?

### ISSUE THREAD

**Issue by DrMarcII** [mozilla/geckodriver#421]
The Selenium project's implementation of
[FirefoxOptions](https://github.com/SeleniumHQ/selenium/blob/93f5a238b2503c28a680100c2c657143a31cd627/java/client/src/org/openqa/selenium/firefox/FirefoxOptions.java#L192)
disallows setting both prefs and profile, but the documentation here makes no reference to this limitation. 

Is Selenium protecting against something that is not a problem, or should the documentation here be updated to reflect this limitation?

**Comment by jgraham** [comment]
You can set a custom profile and then write additional prefs into that profile. So Selenium is wrong here.
