### ISSUE TITLE
geckodriver not able to connect to existing firefox sessions

### ISSUE THREAD

**Issue by meeotch** [mozilla/geckodriver#430]
I can't seem to get geckodriver to re-connect to an existing firefox session.  

## Firefox Version
50.1.0

## Platform
windows 7, geckodriver-v0.13.0-win64

## Steps to reproduce -
(The following steps are based on using Selenium 3.0 from an interactive python shell.)

1)  instantiate a Firefox Webdriver, which will automatically spin up an instance of geckodriver along with the associated Firefox browser:   wd = FirefoxWebDriver(executable_path="./geckodriver")

2)  find the url to reach geckodriver:  wd.service.service_url

3)  find the session_id of your webdriver:  wd.session_id

4)  find the marionette port that Firefox is listening on:  I've been doing this by grepping it out of prefs.js in the auto-created temp firefox profile.  Maybe there's a better way?

5)  verify that geckodriver and firefox are listening on the ports from 2) and 4) above using netstat -a -b -o

6)  load a web page into firefox, then verify that geckodriver and firefox are connected, by manually poking the interface from a different browser:  http://127.0.0.1:13460/session/<session_id>/url should return the url that you loaded

7)  kill geckodriver.  I've found that hitting ctrl-c in the interactive python session will actually pass a quit signal to geckodriver, which is a little weird.  

8)  manually restart geckodriver and attempt to connect to the existing firefox:
geckodriver.exe --connect-existing --marionette-port <port-from-step-4> --port <port-from-step-2> --log trace

9)  again verify that geckodriver and firefox are listening on the same ports as before, using netstat

10)  now try to poke the interface as in 6) again.  This time, you'll get:
{"error":"unknown error","message":"Tried to run command without establishing a connection"}
demonstrating that they're not actually talking to each other.

Trace log (everything after the first three lines is the result of the url request in step 9):

```
geckodriver.exe --connect-existing --marionette-port 13466 --port 13460 --log trace

1484447430379   webdriver::httpapi      DEBUG   Creating routes
1484447430390   hyper::server   DEBUG   threads = 2
1484447430390   geckodriver     INFO    Listening on 127.0.0.1:13460

***** url request results start here:  ******
1484447435458   hyper::server   DEBUG   Incoming stream
1484447435458   hyper::buffer   TRACE   get_buf []
1484447435458   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1484447435488   hyper::server   DEBUG   Incoming stream
1484447435488   hyper::buffer   TRACE   get_buf []
1484447435488   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1484447435511   hyper::buffer   TRACE   get_buf [u8; 4096][0..423]
1484447435511   hyper::http::h1 TRACE   try_parse([71, 69, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 102, 49, 49, 101, 54, 48, 49, 100, 45, 51, 100, 57, 49, 45, 52, 54, 98, 54, 45, 97, 51, 100, 56, 45, 51, 48, 97, 98, 98, 99, 97, 49, 101, 48, 48, 57, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 49, 51, 52, 54, 48, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 107, 101, 101, 112, 45, 97, 108, 105, 118, 101, 13, 10, 67, 97, 99, 104, 101, 45, 67, 111, 110, 116, 114, 111, 108, 58, 32, 109, 97, 120, 45, 97, 103, 101, 61, 48, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 116, 101, 120, 116, 47, 104, 116, 109, 108, 44, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 120, 104, 116, 109, 108, 43, 120, 109, 108, 44, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 120, 109, 108, 59, 113, 61, 48, 46, 57, 44, 105, 109, 97, 103, 101, 47, 119, 101, 98, 112, 44, 42, 47, 42, 59, 113, 61, 48, 46, 56, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 77, 111, 122, 105, 108, 108, 97, 47, 53, 46, 48, 32, 40, 87, 105, 110, 100, 111, 119, 115, 32, 78, 84, 32, 54, 46, 49, 59, 32, 87, 79, 87, 54, 52, 41, 32, 65, 112, 112, 108, 101, 87, 101, 98, 75, 105, 116, 47, 53, 51, 55, 46, 51, 54, 32, 40, 75, 72, 84, 77, 76, 44, 32, 108, 105, 107, 101, 32, 71, 101, 99, 107, 111, 41, 32, 67, 104, 114, 111, 109, 101, 47, 51, 51, 46, 48, 46, 49, 55, 53, 48, 46, 49, 53, 52, 32, 83, 97, 102, 97, 114, 105, 47, 53, 51, 55, 46, 51, 54, 13, 10, 68, 78, 84, 58, 32, 49, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 44, 115, 100, 99, 104, 13, 10, 65, 99, 99, 101, 112, 116, 45, 76, 97, 110, 103, 117, 97, 103, 101, 58, 32, 101, 110, 45, 85, 83, 44, 101, 110, 59, 113, 61, 48, 46, 56, 13, 10, 13, 10])
1484447435511   hyper::http::h1 TRACE   Request.try_parse([Header; 100], [u8; 423])
1484447435511   hyper::http::h1 TRACE   Request.try_parse Complete(423)
1484447435511   hyper::header   TRACE   raw header: "Host"=[49, 50, 55, 46, 48, 46, 48, 46, 49, 58, 49, 51, 52, 54, 48]
1484447435511   hyper::header   TRACE   raw header: "Connection"=[107, 101, 101, 112, 45, 97, 108, 105, 118, 101]
1484447435511   hyper::header   TRACE   raw header: "Cache-Control"=[109, 97, 120, 45, 97, 103, 101, 61, 48]
1484447435511   hyper::header   TRACE   raw header: "Accept"=[116, 101, 120, 116, 47, 104, 116, 109, 108, 44, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 120, 104, 116, 109, 108, 43, 120, 109, 108, 44, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 120, 109, 108, 59, 113, 61, 48, 46, 57, 44, 105, 109, 97, 103, 101, 47, 119, 101, 98, 112, 44, 42, 47, 42, 59, 113, 61, 48, 46, 56]
1484447435511   hyper::header   TRACE   raw header: "User-Agent"=[77, 111, 122, 105, 108, 108, 97, 47, 53, 46, 48, 32, 40, 87, 105, 110, 100, 111, 119, 115, 32, 78, 84, 32, 54, 46, 49, 59, 32, 87, 79, 87, 54, 52, 41, 32, 65, 112, 112, 108, 101, 87, 101, 98, 75, 105, 116, 47, 53, 51, 55, 46, 51, 54, 32, 40, 75, 72, 84, 77, 76, 44, 32, 108, 105, 107, 101, 32, 71, 101, 99, 107, 111, 41, 32, 67, 104, 114, 111, 109, 101, 47, 51, 51, 46, 48, 46, 49, 55, 53, 48, 46, 49, 53, 52, 32, 83, 97, 102, 97, 114, 105, 47, 53, 51, 55, 46, 51, 54]
1484447435511   hyper::header   TRACE   raw header: "DNT"=[49]
1484447435511   hyper::header   TRACE   raw header: "Accept-Encoding"=[103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 44, 115, 100, 99, 104]
1484447435511   hyper::header   TRACE   raw header: "Accept-Language"=[101, 110, 45, 85, 83, 44, 101, 110, 59, 113, 61, 48, 46, 56]
1484447435511   hyper::server::request  DEBUG   Request Line: Get AbsolutePath("/session/f11e601d-3d91-46b6-a3d8-30abbca1e009/url") Http11
1484447435511   hyper::server::request  DEBUG   Headers { Host: 127.0.0.1:13460, Connection: keep-alive, Cache-Control: max-age=0, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36, DNT: 1, Accept-Encoding: gzip,deflate,sdch, Accept-Language: en-US,en;q=0.8, }
1484447435511   hyper::header   TRACE   Headers.set( "Connection", Connection([Close]) )
1484447435511   webdriver::server       DEBUG   Got request GET AbsolutePath("/session/f11e601d-3d91-46b6-a3d8-30abbca1e009/url")
1484447435511   webdriver::server       DEBUG   Returning status InternalServerError
1484447435511   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"Tried to run command without establishing a connection"}
1484447435511   hyper::header   TRACE   Headers.set( "Content-Type", ContentType(Mime(Application, Json, [])) )
1484447435511   hyper::header   TRACE   Headers.set( "Content-Length", ContentLength(92) )
1484447435511   hyper::server::response DEBUG   writing head: Http11 InternalServerError
1484447435511   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 35, tm_min: 30, tm_hour: 2, tm_mday: 15, tm_mon: 0, tm_year: 117, tm_wday: 0, tm_yday: 14, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 511424000 })) )
1484447435512   hyper::server::response DEBUG   headers [
Headers { Connection: close, Content-Type: application/json, Content-Length: 92, Date: Sun, 15 Jan 2017 02:30:35 GMT, }]
1484447435512   hyper::server::response DEBUG   write 92 bytes
1484447435512   hyper::server::response TRACE   ending
1484447435512   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:13519
1484447435512   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:13519
1484447445488   hyper::buffer   TRACE   get_buf []
1484447445488   hyper::server   TRACE   tcp closed, cancelling keep-alive loop
1484447445488   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:13520
```

**Comment by andreastt** [comment]
I don’t think there is support in the Selenium Python bindings for connecting to an existing Firefox session. You need to be aware that the Firefox binary must be started with the `--marionette` flag to enable the Marionette automation protocol geckodriver uses, and that it by default binds the server to port 2828.

You are getting `{"error":"unknown error","message":"Tried to run command without establishing a connection"}` demonstrating that _they do in fact talk to one another_. This is an error message Marionette sends back when you haven’t started a Marionette session before trying to speak to it. geckodriver starts a Marionette session implicitly when you make a POST request to `/session`.

**Comment by meeotch** [comment]
Andreas - thanks for the reply.  You are correct that the Selenium Python bindings don't implement re-connection.  In fact, I implemented it myself, and it works, as long as the original geckodriver instance is running.  The original geckodriver talks to the Firefox instance it was "born" with, and I can run Selenium scripts that talk to the existing geckodriver/firefox pair without starting new ones.

The issue I'm having is (I believe) unrelated to Selenium, however.  If you review the steps I outlined above, I'm trying to re-start geckodriver "manually" (i.e., not through Selenium) after it dies, and trying to re-connect it to the same Firefox instance that it was previously talking to.  I believe I have both ports (the --marionette-port and the http --port) set correctly.  I'm testing this, again, "manually", by accessing the http interface directly.  So Selenium is only involved in spinning up the original Firefox / geckodriver pair, and then not again after that.

Am I understanding your second paragraph correctly to mean that there is more required than just passing the appropriate port numbers to the restarted geckodriver instance?  Specifically, that I have to poke geckodriver and get it to start a new session?  (And will the existing Firefox instance use this new session automagically?)  

I apologize if any of these are noob questions.  This is my first encounter with geckodriver - I previously had reusable Firefox sessions implemented within "stock" Selenium, and all that was required was stuffing existing values into the appropriate places.

**Comment by andreastt** [comment]
If you terminate geckodriver and start another instance, you first loose the WebDriver existing WebDriver session and geckodriver looses the connection to Marionette, causing Marionette to also stop the current Marionette session.

When you start geckodriver again, it sounds like you are setting all the right settings which again is proved by the fact you’re getting an error message from Marionette. But because you’ve lost all session state, you need to make a POST request to `/session` to in order to create a new WebDriver session in geckodriver (and for geckodriver to create a new Marionette session in Firefox).

**Comment by meeotch** [comment]
Thanks again for the rapid reply.  So if I'm understanding you correctly, the existing Firefox instance doesn't need any of this info - it will talk to the new geckodriver instance simply by virtue of the fact that it's already listening on the marionette port.  It's only geckodriver that needs to initialize the session internally.  (And of course I'll have to capture the new session_id, so that Selenium can properly pass it in with requests to the new geckodriver.)

**Comment by andreastt** [comment]
You will get a new session ID every time you create a new session. When you create a new WebDriver session, it will call down to geckodriver which proxies the command to Marionette.
