### ISSUE TITLE
"missing marionette protocol field in handshake" error while using Selenium 3.0 and geckodriver 0.13 on Ubuntu Linux

### ISSUE THREAD

**Issue by pajoshi** [mozilla/geckodriver#433]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
35.0.1

## Platform
Ubuntu 14.04 LTS

## Steps to reproduce -
I tried to run the following Python script on my Ubuntu machine:

###################################
from bs4 import BeautifulSoup
from selenium import webdriver
driver = webdriver.Firefox() #I actually used the chromedriver and did not test firefox, but it should work.
profile_link="https://www.linkedin.com/in/johnsmith1"
driver.get(profile_link)
html=driver.page_source
soup=BeautifulSoup(html) #specify parser or it will auto-select for you
summary=soup.find('section', { "id" : "summary" })
print summary.getText()

#############################################

 - [ ] I'm using https://www.linkedin.com/in/johnsmith1 to get this person's basic profile.

 - [ ] Traceback (most recent call last):
  File "LinkedInURLScraping_URLLib2.py", line 4, in <module>
    driver = webdriver.Firefox() #I actually used the chromedriver and did not test firefox, but it should work.
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 150, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Missing 'marionetteProtocol' field in handshake

** If any of the above are missing we will have to unforunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
> I actually used the chromedriver and did not test firefox, but it should work.

I don’t even…

> Firefox Version: 35.0.1

If you read the README carefully, you will note that we only support Firefox Nightly.
