### ISSUE TITLE
WebDriverException: Message: Permission denied to access property "_wrapped"

### ISSUE THREAD

**Issue by dada20042030** [mozilla/geckodriver#438]
Dear Mozilla Geckodriver team,

I have recently already faced a similar issue by using JavascriptExecutor.executeScript(), which also lead to "Permission denied to access property "_wrapped"" error

## Firefox Version
- Firefox 50.1.0 stable
- Selenium version 3.0, Python 2.7
- marionette/geckdriver version 0.13

## Issue
On some webpage, I use the following to check for active document:
```
driver.execute_script("return document.readyState")
```
When the above executes, I get the following WebDriverException:
```
WebDriverException: Message: Permission denied to access property "_wrapped"
```

Is this a bug?

**Comment by andreastt** [comment]
Unable to reproduce this. Please come back with a reproducible test case.

**Comment by andreastt** [comment]
Also, please try again with the latest Nightly.

**Comment by jrgifford** [comment]
Our QA team ran into this bug, although we use watir on top of selenium. Switching to ESR fixed it. I'll ask QA to try nightly and report back with a minimal test case.

**Comment by kimek** [comment]
For a now I know that this issue start from release 48 of Firefox on Linux/Windows as I didn't test them on other platforms yet. Version from 38 till 47 are ok. I've used Selenium 2.4 till 3.4 and gecko 1.4-1.6.1 - same issues. Sites which I'm trying to get is on SHA-256. 

Using theintern.js and basic submit form in functional testing on basic backbone application.

× firefox 48 on Windows 7 - Pet Quote (functional) - submit form (24.989s)
UnknownError: [POST http://(redacted)@localhost:4444/wd/hub/session/950af04c5ce5449288658c2adb9855fa/element/9/submit] Permission denied to access property "_wrapped" (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 138 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'xxx', ip: 'xxx', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{rotatable=false, debug=true, raisesAccessibilityExceptions=false, marionette=true, webdriver.remote.quietExceptions=true, appBuildId=20160726073904, version=48.0, platform=XP, proxy={}, browserstack.local=false, command_id=1, specificationLevel=0, acceptSslCerts=false, browserVersion=48.0, platformVersion=6.1, XULappId={XXXXXXXX-XXXX-XXXX-XXXX-XXXX}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop, firefox_profile=UEsDBBQAAAAIAAJosEqIUd2BCAcAA...}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX
  at runRequest  <node_modules/leadfoot/Session.js:92:40>
  at <node_modules/leadfoot/Session.js:113:39>
  at new Promise  <node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/leadfoot/Session.js:67:10>
  at Element._post  <node_modules/leadfoot/Element.js:23:31>
  at Element.submit  <node_modules/leadfoot/Element.js:217:15>
  at Command.<anonymous>  <node_modules/leadfoot/Command.js:680:19>
  at <node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/dojo/Promise.ts:237:7>
  at <node_modules/dojo/nextTick.ts:44:3>
  at Command.target.(anonymous function) [as submit]  <node_modules/leadfoot/Command.js:674:11>
  at Test.registerSuite.submit form [as test]  <tests/functional/Recorder.js:88:7>
  at <node_modules/intern/lib/Test.js:191:24>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at nextTickCallbackWith0Args  <node.js:436:9>
  at process._tickCallback  <node.js:365:13>

**Comment by andreastt** [comment]
@kimek I’m afraid Firefox 48 isn’t supported. Please consider using Firefox Nightly with geckodriver whilst it is in a pre-release stage.

**Comment by kimek** [comment]
Thank you @andreastt . This explain everything. 
Any docs why this happen or opened ticket ?

**Comment by andreastt** [comment]
@kimek You can see the [Supported Firefoxen](https://github.com/mozilla/geckodriver#supported-firefoxen) section in the README for more details.
