### ISSUE TITLE
Command-line parameter for parent path of profile-directory?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [mozilla/geckodriver#443]
## Firefox Version

45.6, Tor Browser Bundle

## Platform

OSX

## Steps to reproduce -

geckodriver invokes the firefox binary in such a way that the profile-directory specified by `--profile` has the same parent path across multiple invocations. I suppose that's not something one would *think* would be a source of problems.

However, TBB (Tor Browser Bundle), which is a firefox derivative, always creates a directory two levels up in the parent path of the profile-directory, which must be unique per running instance of TBB (it contains tor-related files). So, it would be great if it were possible to pass geckodriver a command-line argument such that the parent-path of the profile can be specified, i.e. so the user can make sure it's unique per invocation.

**Comment by andreastt** [comment]
I don’t understand the issue. The profile path passed by geckodriver is, I believe, an absolute path. By default, each invocation of geckodriver uses a new temporary profile.

Also, I should highlight that Firefox 45.6 is not supported.

**Comment by michaelsbradleyjr** [comment]
It is an absolute path, but the parent portion of the path preceding the uniquely-named profile-directory is shared across all invocations; at least on OSX that looks like:

`/var/folders/d2/fzhx_5gjaaaaaaaaaaaa4rrm0000gn/T/rust_mozprofile.<random>`

The `fzhx_5gjaaaaaaaaaaaa4rrm0000gn` portion *may* change across reboots of the OS, but otherwise will be the same across invocations of `geckdodriver`.

I realize 45.6 isn't supported, but that's a side issue. If TBB were presently based on a supported firefox version the problem would be the same, i.e. that the profiles' parent path is the same across invocations. Two points on that: (1) I was just being honest about the version in question; (2), in a single-instance scenario I've been able to drive TBB (45.6) to my satisfaction, even though it's not supported, but I want to drive more than one instance simultaneously, thus I filed this issue.

Also, another fix for this is for TBB to be modified so as to provide for a configurable-path for the tor-related directory it creates. That may or not be a change the project's maintainers are willing to make, but I am filing a bug report with them as well.

**Comment by andreastt** [comment]
> The fzhx_5gjaaaaaaaaaaaa4rrm0000gn portion may change across reboots of the OS, but otherwise will be the same across invocations of geckdodriver.

I think the location of temporary files on macOS is an characteristic of the system. Correspondingly, on Linux all temporary files and directories end up in `/tmp/rust_mozprofile.<random>` and although the directory is empties on reboot, it _never_ changes.

We use the [tempdir](https://github.com/rust-lang-nursery/tempdir) crate in [rust-mozprofile](https://github.com/jgraham/rust_mozprofile) to create the temporary directory, and it uses the Rust standard library’s `env::temp_dir` to get at the system temporary directory: https://github.com/rust-lang-nursery/tempdir/blob/master/src/lib.rs#L147

[`env::temp_dir`](https://doc.rust-lang.org/std/env/fn.temp_dir.html) can be overridden (on Unix systems) with the `TMPDIR` environmental variable, which seems to point to `/tmp` on Unix systems: https://github.com/rust-lang/rust/blob/51d29343c04a27570a8ff8282611007d6e6408de/src/libstd/sys/unix/os.rs#L466. Now it’s a bit unclear if macOS shares this implementation, but I suspect maybe /tmp is a symlink for /var/folders/d2/5gjaaaaaaaaaaaa4rrm0000gn/T on your system?

**Comment by michaelsbradleyjr** [comment]
Thanks so much, will experiment with `$TMPDIR` on macOS re: all the above.

**Comment by AutomatedTester** [comment]
Closing as there isnt much we can do. We are using the directory that the system tells us to use.
