### ISSUE TITLE
Unable to invoke given URL in selenium

### ISSUE THREAD

**Issue by rrahul31** [mozilla/geckodriver#447]
Firefox: 45.0

Code:

package automatonFrmwrk;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class CheckData {
	 static WebDriver driver;
	  	public static void main(String[] args)  {
			  System.setProperty("webdriver.gecko.driver", "F:\\New folder (2)\\geckodriver.exe");
			    WebDriver driver = new FirefoxDriver();
			 		    driver.navigate().to("https://www.google.com");
		}
}

Output:

1485601085972	geckodriver	INFO	Listening on 127.0.0.1:18398
Jan 28, 2017 4:28:06 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1485601086591	mozprofile::profile	INFO	Using profile path C:\Users\san\AppData\Local\Temp\rust_mozprofile.pCg5ZJQZdWTT
1485601086600	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1485601086621	geckodriver::marionette	INFO	Connecting to Marionette on localhost:50204

Its not at all navigating to google.com, simply opening firefox and navigate to "C:\Users\san\AppData\Local\Temp\"

Please help

**Comment by andreastt** [comment]
Unable to reproduce with information available here. Please don’t waste my time with non-reproducible issues.
