### ISSUE TITLE
Firefox has stopped working

### ISSUE THREAD

**Issue by azhwani** [mozilla/geckodriver#449]
# Meta
OS : windows 7
Mozilla : 51.0.1
Selenium : 3.0.1
Geckodriver : 0.13.0

When I execute a JAVA program , everything works fine until driver.quit(), Mozilla Firefox returns

Firefox has stopped working!

**Comment by andreastt** [comment]
You show utter disrespect for my time as a maintainer of this program. Please don’t waste my time with issues that cannot be reproduced.
