### ISSUE TITLE
release v0.14.0 does not have a macos binary

### ISSUE THREAD

**Issue by cnishina** [mozilla/geckodriver#450]
Could the release for v0.14.0 also have a macos release binary? Thanks!

**Comment by jgraham** [comment]
It will as soon as travis has a free OSX machine to do the build: https://travis-ci.org/mozilla/geckodriver/jobs/197022877

**Comment by cnishina** [comment]
Aaah so not really an issue. I just need to have patience. Closing since not an issue.
