### ISSUE TITLE
Missing geckodriver-v0.14.0-macos.tar.gz build?

### ISSUE THREAD

**Issue by schmidtkp** [mozilla/geckodriver#454]
The macos build appears to be missing from the v0.14.0 release.  Is this by design? Or an oversight?

**Comment by andreastt** [comment]
Travis is having macOS issues (https://www.traviscistatus.com/incidents/k79mjcv403c4) and the package should appear once it clears its backlog.

**Comment by schmidtkp** [comment]
Thanks! Sorry I missed seeing the prior issue pointing this out.

**Comment by andreastt** [comment]
@schmidtkp It’s there now! https://github.com/mozilla/geckodriver/releases/tag/v0.14.0
