### ISSUE TITLE
How to set the log object for geckodriver through selenium

### ISSUE THREAD

**Issue by sureshkumar-skc** [mozilla/geckodriver#456]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
50.1 x64 bit

## Platform
e.g. Windows 10 x 64bit

## Steps to reproduce -
System.setProperty("webdriver.gecko.driver", geckoDirverPath);
	
	LoggingPreferences logs = new LoggingPreferences();
	logs.enable(LogType.BROWSER, Level.OFF);
        logs.enable(LogType.SERVER, Level.OFF);
        logs.enable(LogType.DRIVER, Level.OFF);
        logs.enable(LogType.PROFILER, Level.OFF);
        logs.enable(LogType.CLIENT, Level.OFF);
        System.out.println(logs.getEnabledLogTypes());
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        System.out.println("CapabilityType.LOGGING_PREFS: "+CapabilityType.LOGGING_PREFS);
        capabilities.setCapability(CapabilityType.LOGGING_PREFS, logs);
		capabilities.setCapability("marionette", true);
		WebDriver driver = new FirefoxDriver(capabilities);

Still, I am getting the error messages in my console:

1486116717189	geckodriver	INFO	Listening on 127.0.0.1:14606
Feb 03, 2017 3:41:57 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1486116718146	mozprofile::profile	INFO	Using profile path C:\Users\SURESH~2\AppData\Local\Temp\rust_mozprofile.uc0Qy3KQM1Aw
1486116718180	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe
1486116718201	geckodriver::marionette	INFO	Connecting to Marionette on localhost:53125
1486116718771	addons.manager	DEBUG	Application has been upgraded
1486116718966	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1486116718972	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1486116718986	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1486116718992	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1486116718995	addons.manager	DEBUG	Starting provider: XPIProvider
1486116718996	addons.xpi	DEBUG	startup
................. 

Any way to set this logging level from the capabilities of the selenium webdriver ?

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
The log API in Selenium is not part of the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) and thus not supported by geckodriver. Sorry.
