### ISSUE TITLE
Occasional erroneous window handle until window is switched to

### ISSUE THREAD

**Issue by lmtierney** [mozilla/geckodriver#458]
## Firefox Version
Nightly

## Platform
OSX/Linux

## Steps to reproduce -
 - [X] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [X] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

This is a pretty minor bug, but seems to be a bug nonetheless. 
The issue is that sometimes when opening a new window/tab through a `_blank` link, a 'temporary' window handle seems to be assigned to it. e.g. `[u'2147483649', u'2147483653', u'2147483656', u'31']` but once that window is switched to, it gets a new id e.g. `[u'2147483649', u'2147483653', u'2147483656', u'2147483659']`

This only happens when the `browser.link.open_newwindow` preference is set to `2` (which is the default for all profiles created via selenium since legacy ff driver couldn't control tabs). Running the same script without a profile (where `browser.link.opennewwindow` defaults to `3`)) has no issues. Unfortunately, since standalone server always creates a temporary profile if one isn't supplied, `_blank` links will always open in new windows and could experience this bug.

A minimal html file would be the following, although it's recreated via tourdedave's site as used in the script:
```
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <a href='#', target='_blank'>Click Here</a>
  </body>
</html>
```

Script to reproduce:
```
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.firefox.options import Options

options = Options()
options.binary = '/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin'
options.log.level = 'trace'

driver = webdriver.Firefox(firefox_options=options, firefox_profile=webdriver.FirefoxProfile())
driver.get('http://the-internet.herokuapp.com/windows')
link = driver.find_element_by_css_selector('.example a')
for _ in range(3):
    link.click()
WebDriverWait(driver, 2).until(lambda d: len(d.window_handles) > 3)
print(driver.window_handles)
last = driver.window_handles[-1]
print(last)
driver.switch_to.window(last)
print(driver.window_handles)
driver.quit()
```
Remove the passed `firefox_profile` and it doesn't happen.

Output from the script: 
```
[u'2147483649', u'2147483653', u'2147483656', u'31']
31
[u'2147483649', u'2147483653', u'2147483656', u'2147483659']
```

Also, it doesn't seem to happen if the number of windows opened is < 4. If I open anything greater than 3, it's usually the last window open that has this odd window handle.

Geckodriver.log is attached 
[geckodriver.txt](https://github.com/mozilla/geckodriver/files/754859/geckodriver.txt)

**Comment by jgraham** [comment]
Thanks for the high quality bug report.

**Comment by whimboo** [comment]
@lmtierney, could you please re-test with a recent Nightly or beta build of Firefox? This might be fixed with my patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1368965, where we sometimes injected a chrome window handle inappropriately.

**Comment by lmtierney** [comment]
@whimboo looks good!

**Comment by whimboo** [comment]
Thank you for testing it that quickly. It's great to hear that my patch fixed it.
