### ISSUE TITLE
https is supported in gecko driver in selenium3.0.1

### ISSUE THREAD

**Issue by vivethtihavinu** [mozilla/geckodriver#459]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
From the "About" dialog.

## Platform
e.g. Windows/OSX/Linux

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by jgraham** [comment]
I don't understand what this issue is trying to report.

**Comment by vivethtihavinu** [comment]
if i pass the url https://google.com it is not supported in geckodriver it shows advance add exception that page if i use firfoxprofile also same page is dispalyed how can i handle this in selenium 3.0.1 version
