### ISSUE TITLE
Multiple Empty Firefox windows are opened

### ISSUE THREAD

**Issue by iamjamalkhan** [mozilla/geckodriver#462]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
31.4.0

## Platform
Linux

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:
 1. Selenium 3.0.1 with GeckoDriver
 2. Trying to init Firefox driver by using Gecko but older firefox version.
 3. As Expected GeckoDriver does not work with older Firefox, but it opens empty Firefox windows before throwing exception.
 4. It should throw exception before itself, so that it does not open any empty Firefox window.
[log.txt](https://github.com/mozilla/geckodriver/files/765220/log.txt)

 
** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
Firefox 31.4.0 is certainly not supported. Please use Firefox Stable onwards. For the best experience, use Firefox Nightly.
