### ISSUE TITLE
Take screenshot with X resolution instant of viewpoint

### ISSUE THREAD

**Issue by klausenbusk** [mozilla/geckodriver#465]
## Firefox Version
51.0.1

## Platform
Linux (Ubuntu 16.04)

## Steps to reproduce -
The spec currently says about screencapture: `They work by dumping a snapshot of the initial viewport’s framebuffer as a lossless PNG image.` ([spec](https://w3c.github.io/webdriver/webdriver-spec.html#screen-capture)). This means there isn't anyway to take a screenshot with X resolution, you can set WindowSize and hope for the best, but WindowSize != viewpoint.

Ex Python code:
```
from selenium import webdriver

capabilities=webdriver.DesiredCapabilities.FIREFOX.copy()
# Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1338771
capabilities['moz:firefoxOptions'] = {'prefs': {"browser.tabs.remote.autostart.2": False}}
driver = webdriver.Remote(desired_capabilities=capabilities, command_executor='http://127.0.0.1:4444')

driver.set_window_size(1920, 1080)

driver.get('http://google.com')
driver.save_screenshot('google.png')
driver.get('http://facebook.com')
driver.save_screenshot('facebook.png')
driver.quit()
```
I get two screenshot which is off by a different number of pixels:
```
google.png:   PNG image data, 1920 x 1009, 8-bit/color RGBA, non-interlaced
facebook.png: PNG image data, 1907 x 1009, 8-bit/color RGBA, non-interlaced
```

This isn't really a bug but more a feature request and I'm not sure how it could be "fixed" (custom extension?)

**Comment by andreastt** [comment]
This _is_ indeed a bug. I am guessing it is probably using the document’s boundaries instead of the viewport’s.

**Comment by klausenbusk** [comment]
> This is indeed a bug.

Are you sure about that? What I understand [setWindowSize](https://hg.mozilla.org/mozilla-central/file/tip/testing/marionette/driver.js#l2426) set the `outerWidth`, but [takeScreenshot](https://hg.mozilla.org/mozilla-central/file/tip/testing/marionette/driver.js#l2286) take a screenshot of the viewpoint (`innerWidth`).
Or do you referrer to the "off by a different number of pixel" bug?

**Comment by andreastt** [comment]
Marionette currently uses `document.documentElement.clientWidth`/`clientHeight`, which is the full size of the document element and which may reach outside the bounds of the viewport. The intention of the [WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-take-screenshot) is to cover only the viewport. This means we should look at `window.innerWidth`/`innerHeight`.

**Comment by klausenbusk** [comment]
@andreastt Any update on this? Is there any upstream Firefox bug I can follow?

**Comment by klausenbusk** [comment]
Upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1385706

**Comment by whimboo** [comment]
This was fixed by @klausenbusk for Firefox 66. Thanks a lot!
