### ISSUE TITLE
UnknownCommandError: GET /session/{sessionID}/element/{elementID}/location did not match a known command

### ISSUE THREAD

**Issue by zenonwch** [mozilla/geckodriver#471]
## Firefox Version
51.0.1 (64 bit)

## Platform
macOS Sierra 10.12.3

## Geckodriver Version
0.14.0

## Steps to reproduce -
Node.js v7, selenium-webdriver 3.0.1

Getting error if selenium trying to execute the command driver.findElement({valid locator}).getLocation()

UnknownCommandError: GET /session/e362d785-035c-4342-ae9b-cbd9c1ce88fd/element/f7e9090c-79c2-8249-b1df-8f080ce9b6e6/location did not match a known command

**Comment by andreastt** [comment]
`/{session id}/location` isn’t a WebDriver command endpoint. You probably want `/{session id}/rect`, which returns a dictionary of x/y/width/height properties.

Are you sure you’re using the most up to date Node.js bindings? If so and the problem persists, please consider filing a bug on the Selenium project.

Thanks!

**Comment by zenonwch** [comment]
But why it works for other browsers (chrome, ie, safari) ? It looks like a geckodriver issue. Also get a lot similar errors with geckodriver (e.g. for moveTo).

**Comment by andreastt** [comment]
@zenonwch Because Chrome, IE, and Safari do not implement the W3C WebDriver protocol, and Selenium is missing a shim to do conversion between the Selenium- and the WebDriver protocol.
