### ISSUE TITLE
error: Found argument '-f' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by JMVM** [mozilla/geckodriver#474]
## Firefox Version
GeckoDriver 0.14.0

## Platform
Windows 8

## Steps to reproduce -
Launching directly by command line:

**geckodriver.exe -foreground**

```
error: Found argument '-f' which wasn't expected, or isn't valid in this context


USAGE:
    geckodriver.exe [FLAGS] [OPTIONS]

For more information try --help

```
NOTE:
- Note that this is the command executed by **Selenium FirefoxDriver when using geckodriver as binary**: https://github.com/SeleniumHQ/selenium/issues/3410

**Comment by andreastt** [comment]
That sounds like a Selenium bug. We can’t be blamed for a consumer using a wrong flag.

**Comment by JMVM** [comment]
Yes, it was my fault using Selenium in wrong way.

I think it's not very clear compatibility issues in the past about.

Thanks
