### ISSUE TITLE
Unable to kill the process.

### ISSUE THREAD

**Issue by pankaj186** [mozilla/geckodriver#479]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
From the "About" dialog.
51.0.1

## Platform
e.g. Windows 10 64bit

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

When I am tring to close the web driver using driver.close() then in console I am observing this logline.
`[Child 2872] ###!!! ABORT: Aborting on channel error.: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2056
Feb 19, 2017 2:11:53 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 5400`

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
You haven’t provided any information on what version of geckodriver you’re using, but I believe https://bugzilla.mozilla.org/show_bug.cgi?id=1311350, which is available in Firefox 52 onwards, and geckodriver 0.14.0 ensures closing the last window ends the WebDriver session.

If you would run this test again with [Firefox Nightly](https://nightly.mozilla.org/) and geckodriver 0.14.0 to see if it has been resolved, I would be much obliged.

In the meantime I will close this issue as I suspect it has been resolved.
