### ISSUE TITLE
Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'

### ISSUE THREAD

**Issue by Devcoo** [mozilla/geckodriver#480]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Version 51

## Platform
e.g. Windows

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements: running the below scriot:

```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class endtoend {

	public static void main(String[] args) {
		WebDriver driver;
		System.setProperty("webdriver.Firefoxdriver","C:\\Softwares\\Selenium\\Firefox driver\\geckodriver.exe");
		driver = new FirefoxDriver();
		driver.get("http://www.amazon.in");
		

	}

}
```

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
Well, where is Firefox installed?

**Comment by Devcoo** [comment]
C:\\Users\myname\AppData\Local\Mozilla Firefox\firefox.exe

**Comment by andreastt** [comment]
[rust_mozrunner looks at](https://github.com/jgraham/rust_mozrunner/blob/master/src/runner.rs#L206) SOFTWARE → SOFTWARE\\WOW6432Node → mozilla.org\\Mozilla → Mozilla → \\bin → PathToExe in the Windows registry to find the path to the Firefox binary.

What does this read on your system’s registry? Are there any related Firefox/Mozilla entries in the registry that give any clues?

**Comment by Devcoo** [comment]
Name: (Default)
Type: REG_SZ
Data: (Value not set)

**Comment by Devcoo** [comment]
do i need to delete or modify this?

**Comment by Devcoo** [comment]
I think that is correct.
also just below the Path is mentioned and it is the same which i told you in registry.
please let me know what can be done to resolve this issue

**Comment by Devcoo** [comment]
PFA of the error
![error](https://cloud.githubusercontent.com/assets/25884100/23104796/6f304654-f6fa-11e6-933d-322623d7c38a.jpg)

**Comment by andreastt** [comment]
@jgraham Do you have any idea what could be the matter here? How do we proceed debugging this?
