### ISSUE TITLE
Windows Defender detects virus "Trojan:Win32:Manrele.G!cl" after downloading geckodriver-v0.14.0-win32.zip

### ISSUE THREAD

**Issue by dday1231** [mozilla/geckodriver#481]
Note: this issue does not occur when downloading geckodriver-v0.14.0-win64.zip.

Note: since this involves Windows and Windows Defender I'm not sure if this problem has anything to do with the geckodriver-v0.14.0-win32.zip file, ie, maybe my computer has been compromised, or maybe Windows Defender is misidentifying a virus in this instance. Does anyone else see this "issue"? Is this particular file safe to use?

## Platform
Windows 10

## Steps to reproduce -

1. Download this file: https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-win32.zip in Edge, Chrome, or Firefox on a Windows 10 machine with Windows Defender turned on.

Result: 

In Chrome and IE as soon as the file has finished downloading Windows Defender runs against the zip file and claims to have detected a virus called "Trojan:Win32:Manrele.G!cl" and immediately quarantines the trojan and deletes the zip file. In Firefox one can download the zip file, but Windows goes through the same virus detection/deletion process when the user unzips the downloaded zip file.

**Comment by andreastt** [comment]
Windows is certainly misidentifying it as a virus. I don’t think there’s anything we can do about this from geckodriver’s side.

**Comment by dday1231** [comment]
Thanks @andreastt
