### ISSUE TITLE
geckodriver get CssValue color is different from previous firefoxdriver

### ISSUE THREAD

**Issue by zzhengjian** [mozilla/geckodriver#482]
old firefoxdriver get: rgba(x, x, x, 1)

geckodriver get: rgb(x, x, x)

chrome and IE drivers is getting same format as old firefoxdriver.

geckodriver version: 0.14
selenium-webdriver version: 3.1.0
ruby 2.2

**Comment by andreastt** [comment]
It is the other drivers that are not implementing the [WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-get-element-css-value) correctly. CSS colour values should be returned unaltered from the browser. This means they will either be returned as rgb or rgba.

You are welcome to file a bug on Selenium to provide a temporary shim for this if you’d like.
