### ISSUE TITLE
Not able to click on Element in Firefox but element.clear is working

### ISSUE THREAD

**Issue by RapoluRajesh** [mozilla/geckodriver#483]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Version : 51.01 / 64 bit

## Platform
Windows 8

## Steps to reproduce -
The scenario is i need to login to Cashkaro site "http://cashkaro.com" below is the code i am using
the line highlighted in bold is not executing 
"**driver.findElement(By.name("pwd-txt")).click();**"
// Launching application
		driver.get("http://cashkaro.com");
		//String parentHandle = driver.getWindowHandle();
		
		// Click on Sign In Link
		driver.findElement(By.xpath(".//a[text()='SIGN IN']")).click();
		
		
		//Switch to Iframe
		WebElement fr = driver.findElement(By.xpath(".//*[@class='cboxIframe']"));
		driver.switchTo().frame(fr);
		
		
		// Logging in
		driver.findElement(By.id("uname")).clear();
		driver.findElement(By.id("uname")).sendKeys("rajeshre@hotmail.com");

		Thread.sleep(2000);
		driver.findElement(By.name("pwd-txt")).clear();
		**driver.findElement(By.name("pwd-txt")).click();**
		driver.findElement(By.name("pwd")).sendKeys("Passport1!");
		Thread.sleep(2000);
		
		driver.findElement(By.id("sign_in")).click();

 HTML Code:

<em id="login_msg" class="fw fl error">
<em id="login_block" class="fw fl error">Your account has been temporarily blocked by CashKaro. Please contact on support@cashkaro.com with your email for further details.</em>
<input id="uname" name="uname" maxlength="50" autofocus="autofocus" tabindex="1" value="Email" onfocus="if(this.value=='Email'){this.value=''}" onblur="if(this.value==''){this.value='Email'}" type="text"/>
<input id="pwd-txt" tabindex="2" name="pwd-txt" value="Password" style="display: inline;" type="text"/>
<input id="pwd" name="pwd" autocomplete="off" style="display: none;" value="" type="password"/>
<a class="fl link" href="/forgot_password.php">Forgot Password?</a>

**Comment by andreastt** [comment]
I don’t understand the issue. What error are you seeing? What are you expecting to happen?

**Comment by RapoluRajesh** [comment]
Steps to reproduce:
1. Launch the application "http://cashkaro.com/"
2.click on Sign in link 
3. Enter Uid and Pwd in the new frame and click sign in

in the third step while i am entering UId and pwd via send keys uid it is entering but for pwd it is not entering, then i noticed password field has two input tags as mentioned below:

<input id="pwd-txt" tabindex="2" name="pwd-txt" value="Password" style="display: inline;" type="text"/>
<input id="pwd" name="pwd" autocomplete="off" style="display: none;" value="" type="password"/>

then i had written below code:

//Switch to Iframe
	WebElement fr = driver.findElement(By.xpath(".//*[@class='cboxIframe']"));
	driver.switchTo().frame(fr);
	
	
	// Logging in
	driver.findElement(By.id("uname")).clear();
	driver.findElement(By.id("uname")).sendKeys("rajeshre@hotmail.com");

	Thread.sleep(2000);
	driver.findElement(By.name("pwd-txt")).clear(); // this is working
	**driver.findElement(By.name("pwd-txt")).click();** // this is not working once we click then other input field will enabled and due to which i am not able to enter the password.

	driver.findElement(By.name("pwd")).sendKeys("Passport1!");

Below is the error i am getting :+1: 

Exception in thread "main" org.openqa.selenium.ElementNotVisibleException: Element is not visible (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 29 milliseconds

**Comment by PascalGit1** [comment]
Check if `driver.findElement(By.name("pwd-txt")).clear(); ` Doesn't already set the input to display:none.
else you can just skip the click part and do `driver.findElement(By.name("pwd")).sendKeys("Passport1!");`
right after the .clear()

**Comment by AutomatedTester** [comment]
The error is saying that it isn't visible so I suspect your script has a timing issue. If I manually navigate to the site and do the following I can't reproduce it

``` python
>>> f=webdriver.Firefox()
... # get site to login page
>>> frame = f.find_element("xpath", ".//*[@class='cboxIframe']")
>>> f.switch_to_frame(frame)
>>> pwd = f.find_element("name", "pwd-txt")
>>> pwd.send_keys("foobar")
>>>
```
