### ISSUE TITLE
Tarballs should contain a directory with its own name

### ISSUE THREAD

**Issue by cartwrightian** [mozilla/geckodriver#484]
Untarring the osx package provides a binary called 'geckodriver' with no supporting docs, readme or directory structure. It might be better practice to at least include a versioned folder name, then a subdir called bin and then finally the binary itself. This would make it much easier to manage multiple versions for installers.

i.e. unpack to geckodriver0.14.0/bin/geckodriver

**Comment by andreastt** [comment]
You can extract to a given directory by passing `-C` to tar(1):

    % tar xf geckodriver-v0.14.0-linux64.tar.gz -C geckodriver-0.14

**Comment by andreastt** [comment]
But it’s probably a good idea to provide one directory on the top-level with the same name as the package. This is what literally every other tarball in the world does.

**Comment by jgraham** [comment]
Chromedriver doesn't; it just provides an zipped executable. I would expect consistency among WebDriver implementations to be unusually valuable to people scripting the install of these things.

**Comment by andreastt** [comment]
Good point. It’s probably not worth the effort then.
