### ISSUE TITLE
Any plans to support CapabilityType.SUPPORTS_LOCATION_CONTEXT

### ISSUE THREAD

**Issue by cartwrightian** [mozilla/geckodriver#485]
My current tests rely on CapabilityType.SUPPORTS_LOCATION_CONTEXT to enable/disable location, are there plans to support this capability in geckodriver?

Currently I use (in java):

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.SUPPORTS_LOCATION_CONTEXT, true);
driver = new FirefoxDriver(capabilities);

**Comment by andreastt** [comment]
Since this is not in the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) we have no plans to support enabling/disabling geolocation.

**Comment by cartwrightian** [comment]
Just to check: things currently possible with Firefox and webdriver now
won't make it into gecko driver if not in the webdriver specs? Does this
apply in general?

**Comment by andreastt** [comment]
Yes.
