### ISSUE TITLE
2 Errors

### ISSUE THREAD

**Issue by stamerpro** [mozilla/geckodriver#487]
1) No support extensions Made using WebExtensions, the error lies in the fact that when building extensions using WebExtensions, no install.rdf file, please correct this mistake as many extensions are collected using this method and can not be used
2) If you open two windows that Execute_script method performs JS code in the first window
Firefox 51
Windows 10

**Comment by andreastt** [comment]
If you want your issues to be taken seriously, you need to provide one bug report per issue and exact reproducible steps with a good description of your problem. I literally cannot figure out from the above what the issue is. Please don’t waste our time.
