### ISSUE TITLE
Geckodriver get stucked when using appointed profile

### ISSUE THREAD

**Issue by guohainan** [mozilla/geckodriver#491]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
51.0.1

## Platform
Windows

## Geckodriver Version
v0.14.0

## Steps to reproduce -
1. Use command "firefox -p", create a new profile named "selenium"

2. Run below codes:
public static void main( String[] args )
    {
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        
        ProfilesIni allProfiles = new ProfilesIni();
		FirefoxProfile profile = allProfiles.getProfile("selenium");
		
		capabilities.setCapability(FirefoxDriver.PROFILE, profile);
		
		System.setProperty("webdriver.gecko.driver", "D:\\geckodriver.exe");
		
		WebDriver driver = new FirefoxDriver(capabilities);
		
		driver.get("https://www.google.com/");
		
		driver.findElement(By.id("wrong_id"));
    }

3. Results:
I got below messy log on console ( below just a fragment log )：
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIADOIVkoAAAAAAAAAAAAAAAALAAAAYWRkb25zLmpzb26r
VipOzkjNTVSyMtVRSkxJyc8rVrKKjq0FAFBLBwi+vi0XGgAAABgAAABQSwMEFAAICAgAM4hWSgA
AAAAAAAAAAAAAABUAAABBbHRlcm5hdGVTZXJ2aWNlcy50eHQDAFBLBwgAAAAAAgAAAAAAAABQSwMEFAAICAgAM4hWSgAAAAAAAAAAAAAAAA0AAABibG9ja2xpc3QueG1s7H1ncxtH1u73+ytUrq16qd3bcOdwa/c1spMsy5ZtOUir6kiCBAEIAJNI//d7GsCACZRACOCQkhwkcjAc9nQ45znpOf/+6ni/++gwDkedfu8

4. My questions:
Is it a bug that geckodriver print too much log? And my program finally is stucked.

**Comment by andreastt** [comment]
I don’t understand what the actual problem is. What exception are you seeing? Please attach a trace-level log if you think this is not a Selenium issue. I will be happy to re-open this issue when enough information to reproduce it has been added.

**Comment by guohainan** [comment]
@andreastt The problem is that the logger print "profile=UEsDBBQACAgIADOIVkoAAAA........" without stopping, even if the trace-level log can not show, finally my programm crashed.

**Comment by andreastt** [comment]
Again, please attach the full trace-level log.

**Comment by guohainan** [comment]
@andreastt Please try the steps what i said, you won't get the trace-level log, that's the problem.

**Comment by andreastt** [comment]
So geckodriver doesn’t produce any output to stdout at all?

**Comment by guohainan** [comment]
@andreastt what i got is:
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIADOIVkoAAAAAAAAAAAAAAAALAAAAYWRkb25zLmpzb26r
VipOzkjNTVSyMtVRSkxJyc8rVrKKjq0FAFBLBwi+vi0XGgAAABgAAABQSwMEFAAICAgAM4hWSgA
AAAAAAAAAAAAAABUAAABBbHRlcm5hdGVTZXJ2aWNlcy50eHQDAFBLBwgAAAAAAgAAAAAAAABQSwMEFAAICAgAM4hWSgAAAAAAAAAAAAAAAA0AAABibG9ja2xpc3QueG1s7H1ncxtH1u73+ytUrq16qd3bcOdwa/c1spMsy5ZtOUir6kiCBAEIAJNI//d7GsCACZRACOCQkhwkcjAc9nQ45znpOf/+6ni/++gwDkedfu8..........

Nothing else.

**Comment by andreastt** [comment]
There are instructions in the README for how to enable verbose trace-level logs. Judging from this bug you haven’t made any serious attempt so far in making this issue reproducible.
