### ISSUE TITLE
RELEASE DOWNLOAD IS UNAVAILABLE

### ISSUE THREAD

**Issue by sean-hill** [mozilla/geckodriver#501]
https://github.com/mozilla/geckodriver/releases/download/v0.13.0/geckodriver-v0.13.0-linux64.tar.gz is currently unavailable for download. Please fix ASAP!!! Production servers are depending on this download. Thank you. 👍

**Comment by sean-hill** [comment]
Seems that cloudfront is down. This is not a mozilla problem.

**Comment by andreastt** [comment]
GitHub downloads are backed by Amazon S3, and S3 is down causing the geckodriver downloads to be unavailable. Sorry, but there’s nothing we can do about this.

As an aside, that your production environment depends on downloads from a remote server, can be characterised as a disaster waiting to happen.

**Comment by sean-hill** [comment]
Agreed 👍🏻
