### ISSUE TITLE
Geckodriver options being ignored in Python

### ISSUE THREAD

**Issue by jl-678** [mozilla/geckodriver#502]
Hi,

Here are the details:

Firefox: 51..0.1
Geckodriver: v0.14.0
Selenium: 3.0.2
Python: 2.7.12
OS: Ubuntu 16.04

Here is my basic Python code.  None of these settings are being utilized by Geckodriver.  For example, logging level is still "Info" and the path to the Firefox binary is purposefully wrong.  I am trying to get the "display" option to work and that seems to be ignored too.  Am I doing something wrong?  Thank you!

Here is the code:

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pyvirtualdisplay import Display

headless = True

if headless:
    display = Display(visible=0, size=(800, 600))
    display.start()

cap = DesiredCapabilities.FIREFOX.copy()
cap['marionette'] = True
cap['binary'] = '/usr/bin/firefox2'
cap['log'] = {"level":"trace"}
cap['args'] = ["--display=:99"]
browser = webdriver.Firefox(capabilities=cap)
browser.get('http://inventwithpython.com')
try:
    elem = browser.find_element_by_class_name('bookcover')
    print('Found <%s> element with that class name!' % (elem.tag_name))
except:
    print('Was not able to find an element with that name.')

if headless:
    browser.quit()
    display.stop()
```

**Comment by andreastt** [comment]
`binary`, `log`, and `args` are not recognised by geckodriver. Please see the README for available capabilities.

Since you’re using the Selenium Python bindings, you most likely want to use `selenium.webdriver.firefox.options.FirefoxOptions` to send settings to geckodriver.
