### ISSUE TITLE
How to run FF in headless mode

### ISSUE THREAD

**Issue by mysoundmagic** [mozilla/geckodriver#508]
## Firefox Version
51.0.1 64 bit

## Platform
Linux Ubuntu

How to run firefox in headless Mode ?

i've run below command in terminal 

> Xvfb :1 -screen 0 1024x168x8 &

my part of code :

>  	String Xport = System.getProperty("lmportal.xvfb.id", ":1");
> 		final File firefoxPath = new File(System.getProperty("lmportal.deploy.firefox.path", "/usr/bin/firefox"));
> 		FirefoxBinary firefoxBinary = new FirefoxBinary(firefoxPath);
> 		firefoxBinary.setEnvironmentProperty("DISPLAY", Xport);
> 	  
> 	System.setProperty("webdriver.gecko.driver", "geckodriver");
>     driver = new FirefoxDriver(firefoxBinary, null);

when I'm execute from eclipse firefox still show up.

**Comment by andreastt** [comment]
Running Firefox in an X virtual framebuffer does not actually make Firefox headless; it just redirects the visual Firefox window to another (virtual) X display.

You need to ensure that the DISPLAY environment variable is passed on to geckodriver. I would assume this is done by `firefoxBinary.setEnvironmentProperty`, but you would have to investigate further why this is not working.

**Comment by mysoundmagic** [comment]
thank you for your answer. Is there a way to investigate ? or is there another way to make FF actual headless ?

**Comment by andreastt** [comment]
There is ongoing work in https://bugzilla.mozilla.org/show_bug.cgi?id=1338004 to make it possible to run Firefox headlessly.

Regarding how to debug this, I think the easiest thing is to write a wrapper script around the firefox binary that prints the `DISPLAY` environmental variable before it `exec`’s firefox.
