### ISSUE TITLE
Selenium 3.0.2 - Geckodriver - firefox 51 - Not custom profile runs

### ISSUE THREAD

**Issue by pedkoz** [mozilla/geckodriver#509]
Hi,

Custom profile desn't run when it has some customiazation, for example a certificate, but it happens when i add other type of customization.

If folder profile is empty, it runs fine, but if there is some content in the folder profile i receive 

Result StackTrace:	
System.InvalidOperationException: corrupt deflate stream.

It only happens with custom profile.

## Firefox Version
51.0.1

## Platform
Windows

## Steps to reproduce -
My firefox config is:

                    FirefoxOptions options = new FirefoxOptions();
                    options.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
                    options.AddAdditionalCapability(CapabilityType.IsJavaScriptEnabled, true);
                    options.AddAdditionalCapability(CapabilityType.HasNativeEvents, true);

                    FirefoxProfileManager profileM = new FirefoxProfileManager();

                    FirefoxProfile profiles = new FirefoxProfile(@"D:\Path\AppData\Roaming\Mozilla\Firefox\Profiles\t9e6qlj9.L2-cockPit");

//Tried too with
//FirefoxProfile profiles = profileM.GetProfile("ProfileName");

                        options.Profile = profiles;

                    FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();                                                      
                    TimeSpan t = TimeSpan.FromSeconds(10);
                    Driver = new FirefoxDriver(service, options, t);

**Comment by andreastt** [comment]
This sounds like a problem with the language binding you are using:

>  System.InvalidOperationException: corrupt deflate stream.

Please attach the full stacktrace and a trace-level log from geckodriver.

**Comment by pedkoz** [comment]
The stacktrace i receive is:

Test Name:	TestFirefoxProfileTest
Test FullName:	Project.Tests.TestFirefoxProfile.TestFirefoxProfileTest
Test Source:	D:\workspace\Company.Selenium.Framework\Tests\TestFirefoxProfile.cs : line 64
Test Outcome:	Failed
Test Duration:	0:00:03.5505053

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service, FirefoxOptions options, TimeSpan commandTimeout)
   at Project.Tests.TestFirefoxProfile.SetupTest() in D:\workspace\Company.Selenium.Framework\Tests\TestFirefoxProfile.cs:line 48
Result Message:	Initialization method Project.Tests.TestFirefoxProfile.SetupTest threw exception. System.InvalidOperationException: System.InvalidOperationException: corrupt deflate stream.

I am running in geckodriver with a dll from the nuget repository, i need to check how i can get the trace from that geckodriver... i know if i ru in a grid i can, but i would be using remotedriver and not firefoxdriver....

Regards,

**Comment by pedkoz** [comment]
In addition i am using Selenium 3.2.0 in C# with Visual Studio.

Using geckodriver.

Other code i have tested with same result:

            FirefoxProfileManager profileManager = new FirefoxProfileManager();

            FirefoxProfile profiles= new FirefoxProfile();
            profiles = profileManager.GetProfile("L2-cockPit");

            FirefoxOptions options = new FirefoxOptions();
            options.Profile = profiles;
            options.AddAdditionalCapability(CapabilityType.LoggingPreferences, "INFO");

            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
            //service.FirefoxBinaryPath = @System.IO.Directory.GetCurrentDirectory() + "\\Common\\SeleniumDrivers\\wire.exe";                                                    
            TimeSpan t = TimeSpan.FromSeconds(10);
            Driver = new FirefoxDriver(service, options, t);

Regards,

**Comment by andreastt** [comment]
Judging from the stack, something goes wrong when it tries to serialise the Firefox profile. Can you please attach a trace-level geckodriver log as requested?

**Comment by pedkoz** [comment]
Hello,

I got log from geckodriver.exe --log trace:

It finished after 11 minutes, it runs thousand of thousand of lines with coded lines....
HRlbnNpb25zL2Z4ZHJpdmVyQGdvb2dsZWNvZGUuY29tL2NvbnRlbnQvZG9tbWVzc2VuZ2VyLmpzUEsBAhcLFAAAAAgAiGBXSs7qU99dAgAANgQAADcAAAAAAAAAAAAAAACB8hYcAWV4dGVuc2lvbnMvZnhkcml2ZXJAZ29vZ2xlY29kZS5jb20vY29udGVudC9meGRyaXZlci54dWxQSwECFwsUAAAACACIYFdKpsEI7c8FAABvDQAANAAAAAAAAAAAAAAAAIGkGRwBZXh0ZW5zaW9ucy9meGRyaXZlckBnb29nbGVjb2RlLmNvbS9jb250ZW50L3NlcnZlci5qc1BLAQIXCxQAAAAIAIhgV0o6OSjIewUAAAIOAAA3AAAAAAAAAAAAAAAAgcUfHAFleHRlbnNpb25zL2Z4ZHJpdmVyQGdvb2dsZWNvZGUuY29tL3Jlc291cmNlL2V2YWx1YXRlLmpzUEsBAhcLFAAAAAgAiGBXSi963tdbBQAABAwAADwAAAAAAAAAAAAAAACBlSUcAWV4dGVuc2lvbnMvZnhkcml2ZXJAZ29vZ2xlY29kZS5jb20vcmVzb3VyY2UvbW9kdWxlcy90aW1lci5qc1BLAQIXCxQAAAAIAIhgV0rjg6b1YzQBAG+zBQBIAAAAAAAAAAAAAAAAgUorHAFleHRlbnNpb25zL2Z4ZHJpdmVyQGdvb2dsZWNvZGUuY29tL3Jlc291cmNlL21vZHVsZXMvd2ViLWVsZW1lbnQtY2FjaGUuanNQSwECFwsUAAAACABAGE1INxha5Yd9SQAAubkAHgAAAAAAAAAAAAAAAIETYB0BZ21wLWVtZS1hZG9iZS8xNy9lbWUtYWRvYmUuZGxsUEsBAhcLFAAAAAgAQBhNSHRYUMrMAAAANQEAAB8AAAAAAAAAAAAAAACB1t1mAWdtcC1lbWUtYWRvYmUvMTcvZW1lLWFkb2JlLmluZm9QSwECFwsUAAAACABAGE1I9XX0tdJrAABWKQEAIgAAAAAAAAAAAAAAAIHf3mYBZ21wLWVtZS1hZG9iZS8xNy9lbWUtYWRvYmUudm91Y2hlclBLAQIXCxQAAAAIAHui/UimFFcGuCgGAMiBDQAjAAAAAAAAAAAAAAAAgfFKZwFnbXAtZ21wb3BlbmgyNjQvMS42L2dtcG9wZW5oMjY0LmRsbFBLAQIXCxQAAAAIAI22+0jHRcNpYQAAAHQAAAAkAAAAAAAAAAAAAAAAgepzbQFnbXAtZ21wb3BlbmgyNjQvMS42L2dtcG9wZW5oMjY0LmluZm9QSwECFwsUAAAACAA0iGJK3ThObnEBAAC9AwAAJwAAAAAAAAAAAAAAAIGNdG0BZ21wLXdpZGV2aW5lY2RtLzEuNC44Ljg2Ni9tYW5pZmVzdC5qc29uUEsBAhcLFAAAAAgANIhiSio3J4c2Tz0ASHt8ACkAAAAAAAAAAAAAAACBQ3ZtAWdtcC13aWRldmluZWNkbS8xLjQuOC44NjYvd2lkZXZpbmVjZG0uZGxsUEsBAhcLFAAAAAgAT0ZmSnfpaqMJAAAADAAAACgAAAAAAAAAAAAAAACBwMWqAXNhZmVicm93c2luZy9nb29nLWJhZGJpbnVybC1zaGF2YXIuY2FjaGVQSwECFwsUAAAACABPRmZKjZguR4QNAgCEGgMAJwAAAAAAAAAAAAAAAIEPxqoBc2FmZWJyb3dzaW5nL2dvb2ctYmFkYmludXJsLXNoYXZhci5wc2V0UEsBAhcLFAAAAAgAT0ZmSnWXh3yIoQEAPuMBACoAAAAAAAAAAAAAAACB2NOsAXNhZmVicm93c2luZy9nb29nLWJhZGJpbnVybC1zaGF2YXIuc2JzdG9yZVBLAQIXCxQAAAAAAMuOYkognKJk7EEAAOxBAAAvAAAAAAAAAAAAAAAAgah1rgFzYWZlYnJvd3NpbmcvZ29vZy1kb3dubG9hZHdoaXRlLWRpZ2VzdDI1Ni5jYWNoZVBLAQIXCxQAAAAIAMuOYkrE2tNCBQAAABAAAAAuAAAAAAAAAAAAAAAAgeG3rgFzYWZlYnJvd3NpbmcvZ29vZy1kb3dubG9hZHdoaXRlLWRpZ2VzdDI1Ni5wc2V0UEsBAhcLFAAAAAgAy45iSnPQOj/NTAAAnFIAADEAAAAAAAAAAAAAAACBMriuAXNhZmVicm93c2luZy9nb29nLWRvd25sb2Fkd2hpdGUtZGlnZXN0MjU2LnNic3RvcmVQSwECFwsUAAAAAABPRmZKzq/AFmwAAABsAAAAJgAAAAAAAAAAAAAAAIFOBa8Bc2FmZWJyb3dzaW5nL2dvb2ctbWFsd2FyZS1zaGF2YXIuY2FjaGVQSwECFwsUAAAACABPRmZKVfO5JDMSCgD6aQoAJQAAAAAAAAAAAAAAAIH+Ba8Bc2FmZWJyb3dzaW5nL2dvb2ctbWFsd2FyZS1zaGF2YXIucHNldFBLAQIXCxQAAAAIAE9GZkrlX7hLvBcQAFWXEAAoAAAAAAAAAAAAAAAAgXQYuQFzYWZlYnJvd3NpbmcvZ29vZy1tYWx3YXJlLXNoYXZhci5zYnN0b3JlUEsBAhcLFAAAAAgAT0ZmSnfpaqMJAAAADAAAACQAAAAAAAAAAAAAAACBdjDJAXNhZmVicm93c2luZy9nb29nLXBoaXNoLXNoYXZhci5jYWNoZVBLAQIXCxQAAAAIAE9GZkrOJX3GUdMHAEAhCAAjAAAAAAAAAAAAAAAAgcEwyQFzYWZlYnJvd3NpbmcvZ29vZy1waGlzaC1zaGF2YXIucHNldFBLAQIXCxQAAAAIAE9GZkqNDt7T9HIUAMSxFAAmAAAAAAAAAAAAAAAAgVME0QFzYWZlYnJvd3NpbmcvZ29vZy1waGlzaC1zaGF2YXIuc2JzdG9yZVBLAQIXCxQAAAAIAFBGZkp36WqjCQAAAAwAAAAnAAAAAAAAAAAAAAAAgYt35QFzYWZlYnJvd3NpbmcvZ29vZy11bndhbnRlZC1zaGF2YXIuY2FjaGVQSwECFwsUAAAACABQRmZKouW+cb4TBACkAgUAJgAAAAAAAAAAAAAAAIHZd+UBc2FmZWJyb3dzaW5nL2dvb2ctdW53YW50ZWQtc2hhdmFyLnBzZXRQSwECFwsUAAAACABQRmZKMjI74Bt8BAAbwAUAKQAAAAAAAAAAAAAAAIHbi+kBc2FmZWJyb3dzaW5nL2dvb2ctdW53YW50ZWQtc2hhdmFyLnNic3RvcmVQSwECFwsUAAAAAAASiGJKBdcOsqzWAACs1gAAKQAAAAAAAAAAAAAAAIE9CO4Bc2FmZWJyb3dzaW5nL21venN0ZC10cmFjay1kaWdlc3QyNTYuY2FjaGVQSwECFwsUAAAACAASiGJKxNrTQgUAAAAQAAAAKAAAAAAAAAAAAAAAAIEw3+4Bc2FmZWJyb3dzaW5nL21venN0ZC10cmFjay1kaWdlc3QyNTYucHNldFBLAQIXCxQAAAAIABKIYkreJo8/iuEAADjyAAArAAAAAAAAAAAAAAAAgXvf7gFzYWZlYnJvd3NpbmcvbW96c3RkLXRyYWNrLWRpZ2VzdDI1Ni5zYnN0b3JlUEsBAhcLFAAAAAAAEohiSjCFB6xsvwQAbL8EAC4AAAAAAAAAAAAAAACBTsHvAXNhZmVicm93c2luZy9tb3pzdGQtdHJhY2t3aGl0ZS1kaWdlc3QyNTYuY2FjaGVQSwECFwsUAAAACAASiGJKxNrTQgUAAAAQAAAALQAAAAAAAAAAAAAAAIEGgfQBc2FmZWJyb3dzaW5nL21venN0ZC10cmFja3doaXRlLWRpZ2VzdDI1Ni5wc2V0UEsBAhcLFAAAAAgAEohiSnywTLIm+wQAEFgFADAAAAAAAAAAAAAAAACBVoH0AXNhZmVicm93c2luZy9tb3pzdGQtdHJhY2t3aGl0ZS1kaWdlc3QyNTYuc2JzdG9yZVBLAQIXCxQAAAAAAExGZkpdIQy+LAAAACwAAAAkAAAAAAAAAAAAAAAAgcp8+QFzYWZlYnJvd3NpbmcvdGVzdC1ibG9jay1zaW1wbGUuY2FjaGVQSwECFwsUAAAACABMRmZKxNrTQgUAAAAQAAAAIwAAAAAAAAAAAAAAAIE4ffkBc2FmZWJyb3dzaW5nL3Rlc3QtYmxvY2stc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZK4KO8w08AAADoAAAAJgAAAAAAAAAAAAAAAIF+ffkBc2FmZWJyb3dzaW5nL3Rlc3QtYmxvY2stc2ltcGxlLnNic3RvcmVQSwECFwsUAAAAAABMRmZKbp1ySSwAAAAsAAAAJQAAAAAAAAAAAAAAAIERfvkBc2FmZWJyb3dzaW5nL3Rlc3QtZm9yYmlkLXNpbXBsZS5jYWNoZVBLAQIXCxQAAAAIAExGZkrE2tNCBQAAABAAAAAkAAAAAAAAAAAAAAAAgYB++QFzYWZlYnJvd3NpbmcvdGVzdC1mb3JiaWQtc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZKyDd8cE8AAADoAAAAJwAAAAAAAAAAAAAAAIHHfvkBc2FmZWJyb3dzaW5nL3Rlc3QtZm9yYmlkLXNpbXBsZS5zYnN0b3JlUEsBAhcLFAAAAAAATEZmSsHweGQsAAAALAAAACYAAAAAAAAAAAAAAACBW3/5AXNhZmVicm93c2luZy90ZXN0LW1hbHdhcmUtc2ltcGxlLmNhY2hlUEsBAhcLFAAAAAgATEZmSsTa00IFAAAAEAAAACUAAAAAAAAAAAAAAACBy3/5AXNhZmVicm93c2luZy90ZXN0LW1hbHdhcmUtc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZKQtvjyk8AAADoAAAAKAAAAAAAAAAAAAAAAIETgPkBc2FmZWJyb3dzaW5nL3Rlc3QtbWFsd2FyZS1zaW1wbGUuc2JzdG9yZVBLAQIXCxQAAAAAAExGZkopcyzOLAAAACwAAAAkAAAAAAAAAAAAAAAAgaiA+QFzYWZlYnJvd3NpbmcvdGVzdC1waGlzaC1zaW1wbGUuY2FjaGVQSwECFwsUAAAACABMRmZKxNrTQgUAAAAQAAAAIwAAAAAAAAAAAAAAAIEWgfkBc2FmZWJyb3dzaW5nL3Rlc3QtcGhpc2gtc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZKSuPr1U8AAADoAAAAJgAAAAAAAAAAAAAAAIFcgfkBc2FmZWJyb3dzaW5nL3Rlc3QtcGhpc2gtc2ltcGxlLnNic3RvcmVQSwECFwsUAAAAAABMRmZKaVbj9EwAAABMAAAAJAAAAAAAAAAAAAAAAIHvgfkBc2FmZWJyb3dzaW5nL3Rlc3QtdHJhY2stc2ltcGxlLmNhY2hlUEsBAhcLFAAAAAgATEZmSsTa00IFAAAAEAAAACMAAAAAAAAAAAAAAACBfYL5AXNhZmVicm93c2luZy90ZXN0LXRyYWNrLXNpbXBsZS5wc2V0UEsBAhcLFAAAAAgATEZmSk+dSyp0AAAAEAEAACYAAAAAAAAAAAAAAACBw4L5AXNhZmVicm93c2luZy90ZXN0LXRyYWNrLXNpbXBsZS5zYnN0b3JlUEsBAhcLFAAAAAAATEZmSlt8qbAsAAAALAAAACkAAAAAAAAAAAAAAACBe4P5AXNhZmVicm93c2luZy90ZXN0LXRyYWNrd2hpdGUtc2ltcGxlLmNhY2hlUEsBAhcLFAAAAAgATEZmSsTa00IFAAAAEAAAACgAAAAAAAAAAAAAAACB7oP5AXNhZmVicm93c2luZy90ZXN0LXRyYWNrd2hpdGUtc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZKZKkeMk8AAADoAAAAKwAAAAAAAAAAAAAAAIE5hPkBc2FmZWJyb3dzaW5nL3Rlc3QtdHJhY2t3aGl0ZS1zaW1wbGUuc2JzdG9yZVBLAQIXCxQAAAAAAExGZkppushgLAAAACwAAAAnAAAAAAAAAAAAAAAAgdGE+QFzYWZlYnJvd3NpbmcvdGVzdC11bndhbnRlZC1zaW1wbGUuY2FjaGVQSwECFwsUAAAACABMRmZKxNrTQgUAAAAQAAAAJgAAAAAAAAAAAAAAAIFChfkBc2FmZWJyb3dzaW5nL3Rlc3QtdW53YW50ZWQtc2ltcGxlLnBzZXRQSwECFwsUAAAACABMRmZKp7aQfU4AAADoAAAAKQAAAAAAAAAAAAAAAIGLhfkBc2FmZWJyb3dzaW5nL3Rlc3QtdW53YW50ZWQtc2ltcGxlLnNic3RvcmVQSwECFwsUAAAACACyfWZK/gRTdv4MAAAFJQAAOgAAAAAAAAAAAAAAAIEghvkBc2F2ZWQtdGVsZW1ldHJ5LXBpbmdzL2IzZjRjNTJlLTU2NzktNDI1NS04ODI2LWI0ZmFjNTllMDA4MVBLAQIXCxQAAAAIAHV9ZkpyQKFkEAMAAAcKAAAgAAAAAAAAAAAAAAAAgXaT+QFzZXNzaW9uc3RvcmUtYmFja3Vwcy9wcmV2aW91cy5qc1BLAQIXCxQAAAAIAOxy/UhK2sDzAwQAAIYKAAAuAAAAAAAAAAAAAAAAgcSW+QFzZXNzaW9uc3RvcmUtYmFja3Vwcy91cGdyYWRlLmpzLTIwMTYwMzAzMTM0NDA2UEsBAhcLFAAAAAgABHT9SOMqNDZiAgAAhwUAAC4AAAAAAAAAAAAAAACBE5v5AXNlc3Npb25zdG9yZS1iYWNrdXBzL3VwZ3JhZGUuanMtMjAxNjA2MjMxNTQwNTdQSwECFwsUAAAACABPfWZKhvSyzm0CAAA+BgAALgAAAAAAAAAAAAAAAIHBnfkBc2Vzc2lvbnN0b3JlLWJhY2t1cHMvdXBncmFkZS5qcy0yMDE3MDEyNTA5NDEzMVBLAQIXCxQAAAAIAOZy/Ui1a5isFgAAAB0AAAAiAAAAAAAAAAAAAAAAgXqg+QFzdG9yYWdlL3Blcm1hbmVudC9jaHJvbWUvLm1ldGFkYXRhUEsBAhcLFAAAAAgATn1mStLUUocVAAAAKgAAACUAAAAAAAAAAAAAAACB0KD5AXN0b3JhZ2UvcGVybWFuZW50L2Nocm9tZS8ubWV0YWRhdGEtdjJQSwECFwsUAAAACABOfWZKLtgnOP4EAAAAwAAANQAAAAAAAAAAAAAAAIEoofkBc3RvcmFnZS9wZXJtYW5lbnQvY2hyb21lL2lkYi8yOTE4MDYzMzY1cGl1cHNhaC5zcWxpdGVQSwECFwsUAAAACADmcv1In2nMvyYAAAAuAAAALwAAAAAAAAAAAAAAAIF5pvkBc3RvcmFnZS9wZXJtYW5lbnQvbW96LXNhZmUtYWJvdXQraG9tZS8ubWV0YWRhdGFQSwECFwsUAAAACABOfWZKTYC0tCMAAABEAAAAMgAAAAAAAAAAAAAAAIHspvkBc3RvcmFnZS9wZXJtYW5lbnQvbW96LXNhZmUtYWJvdXQraG9tZS8ubWV0YWRhdGEtdjJQSwECFwsUAAAACACMfWZKTgHEha11AAAAQAEAQwAAAAAAAAAAAAAAAIFfp/kBc3RvcmFnZS9wZXJtYW5lbnQvbW96LXNhZmUtYWJvdXQraG9tZS9pZGIvODE4MjAwMTMyYWVibW9vdWh0LnNxbGl0ZVBLAQIXCxQAAAAAAEtGZkpDv6ajAgAAAAIAAAAUAAAAAAAAAAAAAAAAgW0d+gF3ZWJhcHBzL3dlYmFwcHMuanNvblBLBQYAAAAArwGvAQmjAAChHfoBAAA=","binary":"C:\\Program Files\\Mozilla Firefox\\firefox.exe","marionette.logging":true}}}
1488876231638   mozprofile::profile     INFO    Using profile path C:\Users\PEDROJ~1\AppData\Local\Temp\rust_mozprofile.nFXuNG03wxjW
1488876231639   geckodriver::capabilities       DEBUG   Extracting profile to C:\Users\PEDROJ~1\AppData\Local\Temp\rust_mozprofile.nFXuNG03wxjW\addons.json
1488876231640   geckodriver::capabilities       DEBUG   Extracting profile to C:\Users\PEDROJ~1\AppData\Local\Temp\rust_mozprofile.nFXuNG03wxjW\AlternateServices.txt
1488876231651   webdriver::server       DEBUG   Returning status InternalServerError
1488876231651   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"corrupt deflate stream","stacktrace":"stack backtrace:\n   0:   0x4d1796 - <no info>\n   1:   0x440e7b - <no info>\n   2:   0x430568 - <no info>\n   3:   0x41b654 - <no info>\n   4:   0x40732d - <no info>\n   5:   0x6755a7 - <no info>\n   6:   0x66f822 - <no info>\n   7: 0x76f35de3 - RtlUnicodeStringToInteger"}
1488876231651   hyper::header   TRACE   Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1488876231651   hyper::header   TRACE   Headers.set( "Cache-Control", CacheControl([NoCache]) )
1488876231651   hyper::header   TRACE   Headers.set( "Content-Length", ContentLength(348) )
1488876231651   hyper::server::response DEBUG   writing head: Http11 InternalServerError
1488876231652   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 51, tm_min: 43, tm_hour: 8, tm_mday: 7, tm_mon: 2, tm_year: 117, tm_wday: 2, tm_yday: 65, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 651260500 })) )
1488876231652   hyper::server::response DEBUG   headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 348
, Date: Tue, 07 Mar 2017 08:43:51 GMT
, }]
1488876231652   hyper::server::response DEBUG   write 348 bytes
1488876231652   hyper::server::response TRACE   ending
1488876231656   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:27730
1488876231656   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:27730

Regards,

**Comment by andreastt** [comment]
Thanks! The relevant part to that log is this:

```
1488876231651   webdriver::server       DEBUG   Returning status InternalServerError
1488876231651   webdriver::server       DEBUG   Returning body {"error":"unknown error","message":"corrupt deflate stream","stacktrace":"stack backtrace:\n   0:   0x4d1796 - <no info>\n   1:   0x440e7b - <no info>\n   2:   0x430568 - <no info>\n   3:   0x41b654 - <no info>\n   4:   0x40732d - <no info>\n   5:   0x6755a7 - <no info>\n   6:   0x66f822 - <no info>\n   7: 0x76f35de3 - RtlUnicodeStringToInteger"}
```

[`RtlUnicodeStringToInteger`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff562973(v=vs.85).aspx) is part of a Windows driver, which I guess gets called by Rust somewhere when the profile is being decompressed? @jgraham, do you have any idea who could be the sinner here?

**Comment by kirhgoph** [comment]
I have the same problem with Firefox 52, Selenium 3.3.
I was investigating process of profile deserialisation with ProcessMonitor and that's what I got:
[ProcMon.xlsx](https://github.com/mozilla/geckodriver/files/835717/ProcMon.xlsx)
Looks like geckodriver starts to successfully unpack profile, asks detailed info about processed files and fails to get information about them.

**Comment by JoshuaBurns** [comment]
@pedkoz: sorry to ask this here but how did you get a TRACE log for geckcodriver. I am trying to get one for a geckodriver bug I believe i am encountering and cannot figure out where these logs are being written to. I am also using Selenium 3.2, geckodriver 0.15, Firefox 52, Visual Studio 2015 and .NET 4.5 c#. Could you please share how you initialized your browser to get geckodriver TRACE logs in C#? 

Here is what I did and I am not seeing any geckodriver logs 

```
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
FirefoxProfile profile = new FirefoxProfile();
profile.AcceptUntrustedCertificates = true;
profile.AssumeUntrustedCertificateIssuer = true;
FirefoxOptions ffoptions = new FirefoxOptions();
 //ffoptions.BrowserExecutableLocation = @"C:\Program Files\Nightly\firefox.exe";
ffoptions.AddAdditionalCapability(CapabilityType.AcceptSslCertificates, true);
ffoptions.AddAdditionalCapability(CapabilityType.HasNativeEvents, true);            
ffoptions.AddAdditionalCapability("acceptSslCerts", true);
ffoptions.AddAdditionalCapability("acceptInsecureCerts", true);
ffoptions.SetLoggingPreference(LogType.Browser.ToString(), LogLevel.All);
ffoptions.LogLevel = FirefoxDriverLogLevel.Trace;
ffoptions.Profile = profile;
```

**Comment by kirhgoph** [comment]
Not sure if it's appropriate to answer here...
But, @JoshuaBurns you can run geckodriver manually with parameters "--port 4444 --log trace" and change your code so as it looked like:
```
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService();
service.Port = 4444;
service.FirefoxBinaryPath = @"path/to/nightly";
FirefoxProfile profile = new FirefoxProfile();
profile.AcceptUntrustedCertificates = true;
```

After you ran geckodriver with correct parameters, you should see a console window with some log messages.
Then you should run your test and you'll see that you program has successfully connected yo your running geckodriver.

ALso I've seen in another bug you asked for setting a path to nightly, so I've inserted proper line for you.

**Comment by pedkoz** [comment]
Hello,

What i did, it was running the geckodriver.exe from a CMD console with some parameters for getting more traces and after I changed my config in the test for running with remoteDriver sending all the capabilities for firefox browser in my localhost:4444 as I run the geckodriver manually all the remoteDriver send the request to the geckodriver and it lunch the firefox... so i saw the logs in the geckodriver console with CMD.

Best regards,

**Comment by pedkoz** [comment]
Hello,

Is there some update regarding this issue?

Regards,

**Comment by kirhgoph** [comment]
I've posted a workaround for this issue in this thread a bit earlier:

> Delete all empty files in profile directory (in your case it's D:\Path\AppData\Roaming\Mozilla\Firefox\Profiles\t9e6qlj9.L2-cockPit
> and try again

Also I've created #545 pull request which was merged.
So I guess in the next version of geckodriver this issue will be fixed.
Until that time you should use workaraound

**Comment by pedkoz** [comment]
Great!! 

Ok, thank you very much, by now i can do that and i will wait for the update. 

Best regards,

**Comment by DLemberger** [comment]
Might also be related to a .net framework bug: http://stackoverflow.com/questions/43253372/starting-a-specific-firefox-profile-with-selenium-3

Here is a little overwrite of a selenium function which helped me to start custom profiles again. The ZipStorer which is used in Selenium to open the Profiles has a bug which can be fixed with using ZipArchive instead

**Comment by dash521** [comment]
@kirhgoph I have the same question as @jburns24 .  I'm new to geckodriver and I'm trying to figure out how to get the trace logs.  I have the Firefox configs in a method that I use when the browser is called.  Is that where I should put it? I'm not seeing a console window or logs. Any help any of you can provide me will be deeply appreciated.

**Comment by kirhgoph** [comment]
@dash521 as I remember, somewhere in your code must be a line like "[...] FirefoxDriverService.CreateDefaultService(); [...]"
after this line you should put config for geckodriver

**Comment by whimboo** [comment]
@kirhgoph please consult https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html in how to get the trace log.

**Comment by kirhgoph** [comment]
@whimboo Hi, there is a pull request #545 which fixed this bug. Is it possible to close this bug now?

**Comment by whimboo** [comment]
Oh, sure! As it looks like we just missed to close it. Thanks for letting us know.
