### ISSUE TITLE
Where is the source code of the Gecko Driver

### ISSUE THREAD

**Issue by Elmue** [mozilla/geckodriver#512]
Here on Github I see some *.rs files.
But I have a 6 megabyte GeckoDriver.
Where is the source code of that 6 megabyte ?

**Comment by vkatsikaros** [comment]
The *.rs files contain the source code for geckodriver. The programming language used is [Rust](www.rust-lang.org) hence the `rs` file extension.

**Comment by jgraham** [comment]
Geckodriver is a static rust binary that links in several external libraries plus parts of the rust standard library. The `Cargo.lock` file details all the library dependencies (except the stdlib), the `.rs` files in the tree are all the geckodriver-specific code.

**Comment by andreastt** [comment]
@Elmue If you need the source code you can either check out the geckodriver git repository, or download one of the source code tarballs from the releases list.

See my attached screenshot:

![screenshot-2017-03-06-134646](https://cloud.githubusercontent.com/assets/399120/23612456/6c91a1fc-0273-11e7-8172-bb458f9d0e72.png)

**Comment by jakirkham** [comment]
Does one just build from the [`release` branch]( https://github.com/mozilla/geckodriver/tree/release )?

**Comment by whimboo** [comment]
@jakirkham if you only want release builds then yes, just pull from the release branch.
