### ISSUE TITLE
FireFox 51.0.1, GeckoDriver 0.14 on Mac OS I'm receiving missing or invalid type argument for pointer action trying to perform a doubleClick.  We perform the following 	CommonStuff.performDoubleClick(action, driver, recordTitle);  In CommonStuff the code that is failing is  action.doubleClick(elementToDoubleClickOn).perform();  This was working previously, 

### ISSUE THREAD

**Issue by WonderWoman01** [mozilla/geckodriver#513]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
From the "About" dialog.

## Platform
e.g. Windows/OSX/Linux

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
It’s considered bad practice to file bugs on older Firefoxen. Whenever you report bug on software you should ensure you check if the problem is present in the latest version of the software. I would urge you to test again with [Firefox Nightly](https://nightly.mozilla.org/), and if the problem still persists, supply the information that is requested in the issue template.

**Comment by abhishekjn** [comment]
I am also getting the same error, when using geckodriver with action class. Please find below code snippet which shows action class in use:

new Actions(driver).moveByOffset(500, 500).perform();
here, driver is instance of geckodriver.

Environment details:
OS: Windows 7, 64 bit
Browser: 55.0a1 (2017-03-06) (32-bit) (Firefox Nightly)
GeckoDriver: geckodriver-v0.14.0-win64

Could you please look into this.

Regards,
Abhishek Jain

**Comment by andreastt** [comment]
Locking.
