### ISSUE TITLE
GeckoDriver fails to launch the website when running with ant builds

### ISSUE THREAD

**Issue by sanoopkarakkat** [mozilla/geckodriver#514]
Hi All,

I am using ant build (running build.xml via command line) for building my selenium project. While using the geckodriver with ant build for running the tests, the browser opens up, but the website which I have given is not getting launched. But no errors is getting populated in the cmd window. Is anyone else having the same issue? Please let me know.

Selenium Version : 3.01
JDK : 1.8
Platform : Windows10

Much Appreciated!..

**Comment by andreastt** [comment]
Please don’t waste my time with bad bug reports. There is absolutely no way I can guess what is wrong with the description you have given. Please provide a minimal set of reproducible steps. Happy to re-open this issue when that is provided.
