### ISSUE TITLE
Cannot mousemove on canvas element in Firefox 51

### ISSUE THREAD

**Issue by tamvo94** [mozilla/geckodriver#516]
I have a code to mouse move on canvas:

    let canvas = element(by.id(`canvas`)).getWebElement();
    return browser.actions()
      .mouseMove(canvas, {x: 100, y: 100})
      .mouseDown()
      .mouseMove(canvas,  {x: 200, y: 350})
      .mouseUp()
      .perform();

But have issue:

```
Failed: POST /session/3bfcfe08-4464-4ac4-8dfb-bb7bd87e955e/moveto did not match a known command
      at WebDriverError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:27:5)
      at UnknownCommandError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:296:5)
      at Object.throwDecodedError (D:\e2e\node_modules\selenium-webdriver\lib\error.js:477:11)
      at parseHttpResponse (D:\e2e\node_modules\selenium-webdriver\lib\http.js:499:15)
      at doSend.then.response (D:\e2e\node_modules\selenium-webdriver\lib\http.js:440:13)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: mouseMove
      at Driver.schedule (D:\e2e\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
      at actions.map.action (D:\e2e\node_modules\selenium-webdriver\lib\actions.js:124:23)
      at Array.map (native)
      at D:\e2e\node_modules\selenium-webdriver\lib\actions.js:123:29
      at TaskQueue.execute_ (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2970:14)
      at TaskQueue.executeNext_ (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2953:27)
      at asyncRun (D:\e2e\node_modules\selenium-webdriver\lib\promise.js:2813:27)
      at D:\e2e\node_modules\selenium-webdriver\lib\promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
  From: Task: ActionSequence.perform
      at ActionSequence.perform (D:\e2e\node_modules\selenium-webdriver\lib\actions.js:122:33)
```
**Bug report**

Node Version: v6.9.5
Protractor Version: 5.1.1
Browser(s): Firefox 51
Gecko driver: 0.14
Operating System and Version Windown 10 64 bit
Your protractor configuration file
 ```
 browserName: 'firefox',
    marionette: true,
directConnect: true,
```

**Comment by nex0ma** [comment]
moveToElement not worked.

    val node = remote.findElements(By.xpath("""//*[name()='svg']/*[name()='g']/*[name()='path'][22]""")).get(0)
    action.moveToElement(node, 200, 180).click().build().perform()


[info] - should равны *** FAILED ***
[info]   org.openqa.selenium.UnsupportedCommandException: **POST /session/237280f8-10b2-4587-bd0a-78f02208efa7/moveto did not match a known command**
[info] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
[info] System info: host: 'pc', ip: '172.16.4.125', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
[info] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[info] Capabilities [{moz:profile=C:\Users\RE7BC~1.KHA\AppData\Local\Temp\ru_mozprofile.hqKe1zzruwPQ, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0, platformVersion=6.1, moz:processID=2796, browserName=firefox, platformName=windows_nt}]
[info] Session ID: 237280f8-10b2-4587-bd0a-78f02208efa7
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[info]   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:127)
[info]   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
[info]   at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
[info]   at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
[info]   at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
[info]   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)

firefox: 51.0.1 (64-бит)
geckodriver: 0.13, 0.15
os.name: 'Windows 7', 
os.arch: 'amd64', 
os.version: '6.1', 
java.version: '1.8.0_11'

initialization:
```
    dc = DesiredCapabilities.firefox()
    dc.setCapability("gecko", true) // как выйдет драйвер, так и установить
    remote = new FirefoxDriver(dc)

    action = new Actions(remote) // этим будем двигать мышкой
```



But in remote mode another exception:

[info] ru.z_it.dit.asutk.ppm.repository.integral.E011_WebDB6292 *** ABORTED ***
[info]   org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{gecko=true, marionette=true, browserName=firefox, version=, platform=ANY}], required capabilities = Capabilities [{}]
[info] Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
[info] System info: host: 'pc', ip: '172.16.4.125', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_11'
[info] Driver info: driver.version: RemoteWebDriver
[info]   at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
[info]   at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
[info]   at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
[info]   at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
[info]   at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
[info]   at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
[info]   at ru.z_it.dit.asutk.ppm.repository.Database.BrowserParameters.<init>(ConnectionParameters.scala:229)
[info]   at ru.z_it.dit.asutk.ppm.repository.integral.E011_WebDB6292.beforeAll(E011_WebDB6292.scala:79)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
initialization in remotewebdriver:
```
        dc = DesiredCapabilities.firefox()
        dc.setCapability("gecko", true) // как выйдет драйвер, так и установить
        remote = new RemoteWebDriver(new URL("http://localhost:4444/"), dc) //  worked

    action = new Actions(remote) // этим будем двигать мышкой
```

**Comment by andreastt** [comment]
`/session/{session id}/moveto` is not a valid WebDriver endpoint. I think the Selenium language binding you are using does not support the [W3C WebDriver standard](http://w3c.github.io/webdriver/webdriver-spec.html) action API. I would file an issue with the Selenium project about fixing this.
