### ISSUE TITLE
Unable to create remote session using the geckodriver v0.15.0

### ISSUE THREAD

**Issue by mihaibuba** [mozilla/geckodriver#520]
When attempting to start the test using the version 0.15.0 of geckodriver Firefox starts (the window is loaded on screen, then the attached error is displayed in the JUnit stack trace and console and the test stops.
The Firefox window and the geckodriver process remain started and have to be killed manually.

## Firefox Version
v52.0 32-bit; v52.0 64-bit; 53.0b1 32-bit; Nightly: 55.0a1 (2017-03-08) (64-bit)

## geckodriver Version
v0.15.0-win64

## selenium version
v 3.2.0

## Platform
Windows 7 64bit, Java 8.0.121 JDK

## Steps to reproduce -
System.setProperty("webdriver.gecko.driver", FIREFOX_DRIVER_PATH);
new FirefoxDriver();

## JUnit logs 

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@7f1302d6, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@43ee72e6}], required capabilities = Capabilities [{}]
Build info: version: '3.2.0', revision: '8c03df6b79', time: '2017-02-23 10:51:31 +0000'
System info: host: 'CYP-509436-DEV', ip: '10.152.68.49', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:293)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:272)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:267)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:263)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:122)
	at org.oneblood.sms.automation.config.Config.init(Config.java:61)
	at org.oneblood.sms.automation.config.Config.loadConfig(Config.java:130)
	at org.oneblood.sms.automation.config.Config.loadConfig(Config.java:123)
	at org.oneblood.sms.tests.login.TestBase.start(TestBase.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

java.lang.NullPointerException
	at org.oneblood.sms.tests.login.TestBase.end(TestBase.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.Verifier$1.evaluate(Verifier.java:35)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

## Console (geckodriver) logs
1489011378474	geckodriver	INFO	Listening on 127.0.0.1:43977
1489011379042	mozprofile::profile	INFO	Using profile path C:\Users\MIHAI~1.BUB\AppData\Local\Temp\rust_mozprofile.krn1w43Ck6dV
1489011379054	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args []
1489011379063	geckodriver::marionette	INFO	Connecting to Marionette on localhost:50245
1489011379239	addons.manager	DEBUG	Application has been upgraded
1489011379378	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1489011379383	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1489011379391	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1489011379395	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1489011379395	addons.manager	DEBUG	Starting provider: XPIProvider
1489011379396	addons.xpi	DEBUG	startup
1489011379396	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489011379397	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489011379397	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489011379397	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489011379397	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489011379398	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1489011379398	addons.xpi	DEBUG	checkForChanges
1489011379398	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489011379398	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1489011379399	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1489011379399	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489011379400	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1489011379400	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489011379400	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1489011379400	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489011379401	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1489011379401	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489011379401	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1489011379402	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489011379402	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1488491056000},"e10srollout@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1488491056000},"firefox@getpocket.com":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1488491056000},"webcompat@mozilla.org":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1488491056000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1488491056000}}}
1489011379407	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\MIHAI~1.BUB\AppData\Local\Temp\rust_mozprofile.krn1w43Ck6dV\extensions.json
1489011379408	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1489011379414	DeferredSave.extensions.json	DEBUG	Save changes
1489011379414	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1489011379416	DeferredSave.extensions.json	DEBUG	Starting timer
1489011379417	DeferredSave.extensions.json	DEBUG	Save changes
1489011379417	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1489011379421	DeferredSave.extensions.json	DEBUG	Save changes
1489011379421	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1489011379423	DeferredSave.extensions.json	DEBUG	Save changes
1489011379424	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1489011379426	DeferredSave.extensions.json	DEBUG	Save changes
1489011379426	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1489011379431	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489011379434	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1489011379434	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1489011379435	DeferredSave.extensions.json	DEBUG	Save changes
1489011379435	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1489011379436	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489011379437	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.9
1489011379438	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1489011379438	DeferredSave.extensions.json	DEBUG	Save changes
1489011379439	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1489011379439	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489011379442	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1489011379442	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1489011379442	DeferredSave.extensions.json	DEBUG	Save changes
1489011379443	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1489011379443	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489011379444	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1489011379444	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1489011379444	DeferredSave.extensions.json	DEBUG	Save changes
1489011379444	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1489011379444	DeferredSave.extensions.json	DEBUG	Save changes
1489011379445	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{1497fb57-ad1e-4849-b197-25acc4d4164e}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1488491056000,"updateDate":1488491056000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489011379445	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489011379445	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{3eab376e-e063-4bfd-b470-e27def66eb3f}","location":"app-system-defaults","version":"1.9","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1488491056000,"updateDate":1488491056000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7181,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489011379445	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489011379445	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{22c87a4b-e86d-481c-8059-e804a3df9298}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1488491056000,"updateDate":1488491056000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920279,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489011379445	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489011379446	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{ccda174b-e834-4da6-b30b-38154e5892f5}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1488491056000,"updateDate":1488491056000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1454,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489011379446	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489011379446	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{9e042238-4557-411b-8f81-c160cf108ba4}","location":"app-global","version":"52.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1488491056000,"updateDate":1488491056000,"applyBackgroundUpdates":1,"skinnable":true,"size":19581,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1489011379446	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489011379447	DeferredSave.extensions.json	DEBUG	Save changes
1489011379447	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1489011379447	addons.xpi-utils	DEBUG	Updating add-on states
1489011379448	addons.xpi-utils	DEBUG	Writing add-ons list
1489011379450	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489011379450	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1489011379451	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489011379452	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1489011379452	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489011379453	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1489011379454	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489011379454	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1489011379455	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1489011379455	addons.manager	DEBUG	Provider finished startup: XPIProvider
1489011379455	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1489011379455	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1489011379455	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1489011379456	addons.manager	DEBUG	Starting provider: GMPProvider
1489011379460	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1489011379460	addons.manager	DEBUG	Provider finished startup: GMPProvider
1489011379461	addons.manager	DEBUG	Starting provider: PluginProvider
1489011379461	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1489011379461	addons.manager	DEBUG	Provider finished startup: PluginProvider
1489011379461	addons.manager	DEBUG	Completed startup sequence
1489011379943	Marionette	INFO	Listening on port 50245
1489011380925	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1489011380925	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1489011380925	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1489011380937	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1489011380938	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1489011380938	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1489011380940	DeferredSave.extensions.json	DEBUG	Starting write
1489011381077	DeferredSave.extensions.json	DEBUG	Write succeeded
1489011381078	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19

**Comment by jgraham** [comment]
You need to update to selenium 3.3.

**Comment by iamjamalkhan** [comment]
Hi, 

I am facing the same issue even with Selenium 3.3.0 

[junit] Unable to create new remote session. desired capabilities = Capabilities [{firefox_binary=/root/Jamal/firefox/firefox, marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@1e6a3214, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@368247b9}], required capabilities = Capabilities [{}]
    [junit] Build info: version: 'unknown', revision: '86a5d70', time: '2017-02-16 07:47:51 -0800'
    [junit] System info: host: 'dls', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-229.el7.x86_64', java.version: '1.8.0_31'
    [junit] Driver info: driver.version: FirefoxDriver

**Comment by mihaibuba** [comment]
It worked with Selenium 3.3.0 
Thank you.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/52.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/523.

**Comment by sirinibin** [comment]
Selenium 3.4.0 now recommends Geckodriver v0.16.0 strongly. This combo worked well with me.
Please refer the below link
https://stackoverflow.com/questions/45510338/selenium-webdriver-3-4-0-geckodriver-0-18-0-firefox-which-combination-w
