### ISSUE TITLE
python selenium  firefox  proxy   not work(https)

### ISSUE THREAD

**Issue by quanjin9099** [mozilla/geckodriver#521]
I use a proxy to connect to https://www.google.com 
profile->network.proxy(network.proxy.http,network.proxy.http_port)
But not connected, 
---- can be ruled out is a proxy problem, 
The same agent In the manual set to firefox when it is working
But http is working
 Https is not working
why？
what should I do, 
Https can work properly?

**Comment by quanjin9099** [comment]
profile.set_preference("network.proxy.type", 1)
            profile.set_preference("network.proxy.share_proxy_settings", True)
            profile.set_preference("network.http.use-cache", False)
            profile.set_preference("network.proxy.http", agent_IP)
            profile.set_preference("network.proxy.http_port", int(agent_Port))
            profile.set_preference('network.proxy.ssl_port', int(agent_Port))
            profile.set_preference('network.proxy.ssl', agent_IP)
            profile.set_preference('network.proxy.socks', agent_IP)
            profile.set_preference('network.proxy.socks_port', int(agent_Port))

**Comment by andreastt** [comment]
This isn’t an actionable issue report.
