### ISSUE TITLE
Unable to open URL using gecko driver 0.15.0

### ISSUE THREAD

**Issue by snpanigrahi9** [mozilla/geckodriver#522]
In order to help us efficiently investigate your issue, please provide the following information:

Firefox 52.0

Gecko driver 0.15.0

Window 7 64 bit

Selenium java client library version :  3.1.0  and 3.2.0

Steps to reproduce -

Use the following code

package demo1;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Executer2 {

	public static void main(String[] args){
		
		
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		capabilities.setCapability("acceptInsecureCerts", true);
		capabilities.setJavascriptEnabled(true);
		capabilities.setCapability("marionette", true);
		WebDriver driver = new FirefoxDriver(capabilities);
		System.setProperty("webdriver.gecko.driver", System.getProperty("user.dir") + "/geckodriver.exe");
			driver.get("http://www.google.com");
			driver.close();
					
		
	}

}

Console output 

1489040848237	geckodriver	INFO	Listening on 127.0.0.1:12941
1489040848781	mozprofile::profile	INFO	Using profile path C:\Users\A0705286\AppData\Local\Temp\1\rust_mozprofile.z85rfle6hE0q
1489040848828	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args []
1489040848852	geckodriver::marionette	INFO	Connecting to Marionette on localhost:59480
1489040852084	addons.manager	DEBUG	Application has been upgraded
1489040852274	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1489040852276	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1489040852279	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1489040852282	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1489040852283	addons.manager	DEBUG	Starting provider: XPIProvider
1489040852283	addons.xpi	DEBUG	startup
1489040852283	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489040852285	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489040852285	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489040852286	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489040852286	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489040852287	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1489040852288	addons.xpi	DEBUG	checkForChanges
1489040852288	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1489040852289	addons.xpi	DEBUG	Loaded add-on state from prefs: {}
1489040852290	addons.xpi	DEBUG	New add-on aushelper@mozilla.org in app-system-defaults
1489040852291	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489040852291	addons.xpi	DEBUG	New add-on e10srollout@mozilla.org in app-system-defaults
1489040852292	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489040852292	addons.xpi	DEBUG	New add-on firefox@getpocket.com in app-system-defaults
1489040852293	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489040852293	addons.xpi	DEBUG	New add-on webcompat@mozilla.org in app-system-defaults
1489040852294	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489040852294	addons.xpi	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1489040852295	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489040852296	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","st":1488490724000},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","st":1488490724000},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","st":1488490725000},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","st":1488490724000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","st":1488490724000}}}
1489040852306	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\A0705286\AppData\Local\Temp\1\rust_mozprofile.z85rfle6hE0q\extensions.json
1489040852307	addons.xpi-utils	DEBUG	Attempting to upgrade from SQLITE database
1489040852309	addons.xpi-utils	DEBUG	Migrating data from sqlite
1489040852309	addons.xpi-utils	ERROR	Unable to read anything useful from the database
1489040852311	addons.xpi-utils	DEBUG	New add-on aushelper@mozilla.org installed in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1489040852341	DeferredSave.extensions.json	DEBUG	Save changes
1489040852342	addons.xpi-utils	DEBUG	New add-on e10srollout@mozilla.org installed in app-system-defaults
1489040852346	DeferredSave.extensions.json	DEBUG	Starting timer
1489040852348	DeferredSave.extensions.json	DEBUG	Save changes
1489040852348	addons.xpi-utils	DEBUG	New add-on firefox@getpocket.com installed in app-system-defaults
1489040852419	DeferredSave.extensions.json	DEBUG	Save changes
1489040852419	addons.xpi-utils	DEBUG	New add-on webcompat@mozilla.org installed in app-system-defaults
1489040852426	DeferredSave.extensions.json	DEBUG	Save changes
1489040852427	addons.xpi-utils	DEBUG	New add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} installed in app-global
1489040852445	DeferredSave.extensions.json	DEBUG	Save changes
1489040852445	addons.manager	DEBUG	Registering startup change 'installed' for aushelper@mozilla.org
1489040852452	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489040852458	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1489040852458	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1489040852459	DeferredSave.extensions.json	DEBUG	Save changes
1489040852460	addons.manager	DEBUG	Registering startup change 'installed' for e10srollout@mozilla.org
1489040852461	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489040852465	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.9
1489040852466	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1489040852467	DeferredSave.extensions.json	DEBUG	Save changes
1489040852467	addons.manager	DEBUG	Registering startup change 'installed' for firefox@getpocket.com
1489040852467	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489040852472	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1489040852472	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1489040852473	DeferredSave.extensions.json	DEBUG	Save changes
1489040852473	addons.manager	DEBUG	Registering startup change 'installed' for webcompat@mozilla.org
1489040852474	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489040852476	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.0
1489040852476	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1489040852477	DeferredSave.extensions.json	DEBUG	Save changes
1489040852477	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1489040852477	DeferredSave.extensions.json	DEBUG	Save changes
1489040852478	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{a62f73c4-943c-49bc-8690-1aa26931e6f8}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1488490724000,"updateDate":1488490724000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8486,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489040852478	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1489040852478	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{75e12e99-c162-4da9-8440-616922de2e86}","location":"app-system-defaults","version":"1.9","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1488490724000,"updateDate":1488490724000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":7181,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489040852479	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1489040852479	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{081b5c66-3abd-41cf-b0a1-ec43d31d2a96}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1488490725000,"updateDate":1488490725000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":920279,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489040852480	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1489040852480	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{80c83fe2-4e21-4b34-99fa-73ebd254a138}","location":"app-system-defaults","version":"1.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1488490724000,"updateDate":1488490724000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":1454,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1489040852480	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1489040852481	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{cc551639-c6a8-4877-a223-fdfb5aa12c10}","location":"app-global","version":"52.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1488490724000,"updateDate":1488490724000,"applyBackgroundUpdates":1,"skinnable":true,"size":19581,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"52.0","maxVersion":"52.0"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false}
1489040852481	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1489040852482	DeferredSave.extensions.json	DEBUG	Save changes
1489040852484	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1489040852484	addons.xpi-utils	DEBUG	Updating add-on states
1489040852490	addons.xpi-utils	DEBUG	Writing add-ons list
1489040852502	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1489040852504	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1489040852506	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1489040852507	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.9
1489040852508	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1489040852509	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1489040852511	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1489040852512	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1489040852514	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1489040852514	addons.manager	DEBUG	Provider finished startup: XPIProvider
1489040852514	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1489040852514	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1489040852515	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1489040852515	addons.manager	DEBUG	Starting provider: GMPProvider
1489040852526	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1489040852526	addons.manager	DEBUG	Provider finished startup: GMPProvider
1489040852526	addons.manager	DEBUG	Starting provider: PluginProvider
1489040852527	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1489040852527	addons.manager	DEBUG	Provider finished startup: PluginProvider
1489040852527	addons.manager	DEBUG	Completed startup sequence
1489040853302	Marionette	INFO	Listening on port 59480
JavaScript error: resource://app/components/nsBrowserGlue.js, line 1900: NS_ERROR_ABORT: Component returned failure code: 0x80004004 (NS_ERROR_ABORT) [nsIPrefBranch.getComplexValue]
1489040853490	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1489040853490	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1489040853491	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1489040854047	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1489040854048	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1489040854048	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1489040854052	DeferredSave.extensions.json	DEBUG	Starting write
1489040854112	Marionette	WARN	TLS certificate errors will be ignored for this session
1489040854578	DeferredSave.extensions.json	DEBUG	Write succeeded
1489040854578	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, acceptInsecureCerts=true, browserName=firefox, javascriptEnabled=true, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@365185bd, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@18bf3d14}], required capabilities = Capabilities [{}]
Build info: version: 'unknown', revision: '86a5d70', time: '2017-02-16 07:47:51 -0800'
System info: host: 'AINDLPB3RCTM', ip: '10.209.146.46', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:293)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:272)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:267)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:130)
	at demo1.Executer2.main(Executer2.java:17)
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\HP\Unified Functional Testing\bin\java_shared\classes";"C:\Program Files (x86)\HP\Unified Functional Testing\\bin\java_shared\classes\jasmine.jar"

**Comment by phystem** [comment]
I guess you have to use **Selenium 3.3.0** . As Per[ Selenium Java ChangeLog](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG)

v3.3.0
======

* Support for geckodriver v0.15.0.
* Deprecated seldom used FirefoxDriver constructors.
* Added javadocs to show best way to create a new FirefoxDriver:
  ```
  DesiredCapabilities caps = new FirefoxOptions()
       // For example purposes only
      .setProfile(new FirefoxProfile())
      .addTo(DesiredCapabilities.firefox());
  WebDriver driver = new FirefoxDriver(caps);
  ```
* Stream New Session capabilities to disk before use to avoid eating
  every byte of available memory.
* Beginnings of local-end implementation of the w3c New Session
  capabilities. There's still some work to do.

**Comment by snpanigrahi9** [comment]
ok...thanks.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/523.
