### ISSUE TITLE
geckodriver v0.15.0 couldn't start: Unable to create new remote session

### ISSUE THREAD

**Issue by louis57** [mozilla/geckodriver#525]
## Firefox Version
52.0 (64-bit)

## Platform
OS X El Capitan, Version 10.11.6 (15G1217)

## Selenium Version
3.2.0

Since the release of geckodriver v0.15.0 yesterday, I couldn't start the test. Browser is opened, but it got stuck at creating new driver, and i get this exception:

> org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session

When I switched back to geckodriver v0.11.0, it works normally

**Comment by jgraham** [comment]
You need to upgrade to Selenium 3.3 (it is released but not listed except on the GitHub page)

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/523.
