### ISSUE TITLE
Negative offset not supported for action pointerMove

### ISSUE THREAD

**Issue by florentbr** [mozilla/geckodriver#527]
### Firefox Version
55.0a1 Nightly, Windows 10

### Description
When the `origin` is set to an element, the coordinates of the event emitted by Marionette are the center of the element + provided offset `x` and `y`.

But when the provided offset is negative, an exception is raised:

> invalid argument
> Expected 'x' ([object Number] -10) to be >= 0
> 

### Expected:
A negative offset should be supported.

### Example:

```js
{
  'actions': [
    {
      'id': 'mouse1',
      'type': 'pointer',
      'parameters': {
        'pointerType': 'mouse'
      },
      'actions': [
        {
          'type': 'pointerMove',
          'x': -10,
          'y': -10,
          'duration': 50,
          'origin': {
            'element-6066-11e4-a52e-4f735466cecf': '4996c8eb-9b84-46a1-887b-0497c44dff75'
          }
        },
        {
          'type': 'pointerDown',
          'button': 0
        },
        {
          'type': 'pause',
          'duration': 1
        },
        {
          'type': 'pointerUp',
          'button': 0
        }
      ]
    }
  ]
}
```

**Comment by arberK** [comment]
+1

**Comment by andreastt** [comment]
cc @mjzffr

**Comment by mjzffr** [comment]
This got fixed in Marionette in https://bugzilla.mozilla.org/show_bug.cgi?id=1347658
