### ISSUE TITLE
Negative positioning of the window not supported

### ISSUE THREAD

**Issue by florentbr** [mozilla/geckodriver#528]
The note from release v0.13.0 indicates that it's possible to provide negatives numbers to position the window:

> Window position coordinates are allowed to be negative numbers, to cater for maximized window positioning on Windows

But as of version 55.0a1 Nightly, it is still not possible. The following exception is raised for the `setWindowPosition`:

Expected [object Number] -1800 to be >= 0

Command:

```
44:[0,11,"setWindowPosition",{"x":-1800,"y":0}]
```

**Comment by Twyllo** [comment]
Try with bigger values than display width, it should 'hide' it that way

**Comment by andreastt** [comment]
Supplying negative coordinates should be possible following https://bugzilla.mozilla.org/show_bug.cgi?id=1340775. The error message you are seeing (`Expected [object Number] -1800 to be >= 0`) stems from Marionette, which means the checks in geckodriver and webdriver-rust are passing.

Can you double check that you are running against the latest [Nightly](https://nightly.mozilla.org/)? Also, could you please include the stacktrace returned with the error?

**Comment by florentbr** [comment]
@andreastt, the fix landed on nightly since I posted this issue.
The issue is no longer present with nightly 55.0.a1 25/03/2017.

**Comment by andreastt** [comment]
Glad to hear it ツ
