### ISSUE TITLE
Selenium 3.3, FireFox 52.0 and Gecko 0.15

### ISSUE THREAD

**Issue by drFrankWhite** [mozilla/geckodriver#532]
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.Test;

public class ExampleFour {

  String driverPath = "/Users/myName/Desktop/folder/";
  public WebDriver driver;

  @Test
  public void launchBrowser() {
    System.out.println("launching firefox browser");
    System.setProperty("webdriver.gecko.driver", driverPath+"geckodriver");
    driver = new FirefoxDriver();
  }

  @Test
  public void openApplication() {
    driver.navigate().to("http://www.google.com");
  }

  @Test
  public void closeDriver() {
    if(driver!=null) {
      driver.close();
    }
  }
}

the `driver = new FirefoxDriver();` is prompting the error below:

`1489182245434	geckodriver	INFO	Listening on 127.0.0.1:41715
Mar 10, 2017 4:44:05 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1489182245691	mozprofile::profile	INFO	Using profile path /var/folders/b8/3r2f80y1525g68yb54qqlmn80000gn/T/rust_mozprofile.InsWjS9DEZqL
1489182245692	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1489182245694	geckodriver::marionette	INFO	Connecting to Marionette on localhost:59776
1489182246344	Marionette	INFO	Listening on port 59776
Mar 10, 2017 4:44:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Mar 10, 2017 4:44:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection

org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{moz:firefoxOptions={binary=Optional.empty, args=[], legacy=null, logLevel=null, prefs={}, profile=null}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'glucas', ip: '10.0.3.12', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_25'
Driver info: driver.version: FirefoxDriver`

I've seen versions of this message all over and none of the solutions I've seen have worked.  Please help.

## Firefox Version
From the "About" dialog.

## Platform
OSX

**Comment by SankySyS** [comment]
I had the same issue using Selenium 3.3.0. But 3.3.1 resolved this issue.

**Comment by drFrankWhite** [comment]
@SankySyS well I'm glad you were able to resolve this issue.  Thats encouraging as I wasted way too much time on this yesterday.  Just curious, do you have the Maven dependency info for the Selenium 3.3.1 version you're referencing?  I only see 3.3.0 here:

[https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.3.0](url)

and here:

[http://www.seleniumhq.org/download/](url)

**Comment by SankySyS** [comment]
@drFrankWhite 

http://selenium-release.storage.googleapis.com/index.html?path=3.3/
and 
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.seleniumhq.selenium%22

**Comment by drFrankWhite** [comment]
update: my initial issue persists with selenium-java and selenium-firefox-driver set to 3.3.1

**Comment by cdev09** [comment]
hi, i experience this error with the gecko driver path

System.setProperty("webdriver.gecko.driver", driverPath+"geckodriver");
"/Users/myName/Desktop/folder/";

path should be using \\ instead of /
System.setProperty("webdriver.gecko.driver", "C:\\path\\to\\geckodriver.exe"); 

regards

**Comment by AutomatedTester** [comment]
This has been fixed in Selenium Java 3.3.1.
