### ISSUE TITLE
Selenium 3.3.0 Gecko 0.15 - win64  firefox 51 51.0.1 (32-bit) Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by deepakguna** [mozilla/geckodriver#534]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
51.0.1 (32-bit)

## Platform
 Windows

## Steps to reproduce -
i am getting following exception on trying to connect to firefox -Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms 

Selenium 3.3.0 Gecko 0.15 - win64 firefox 51 51.0.1 (32-bit) 

stack trace 
[stack trace.txt](https://github.com/mozilla/geckodriver/files/836438/stack.trace.txt)

**Comment by snpanigrahi9** [comment]
51 will not work gecko 0.15
Try with 52.0 firefox.

**Comment by andreastt** [comment]
Not reproducible.
