### ISSUE TITLE
NoSuchElementException when finding an element by id which contains space character in its value

### ISSUE THREAD

**Issue by ninjateamdn** [mozilla/geckodriver#536]
## Environment:
Windows 7
Firefox 51.0.1
GeckoDriver 0.14
Selenium 3.1.0

## Steps to reproduce -
Exception when trying to find an element by id which contains space character in its value:
Ex: WebElement element = driver.findElement(By.id("adr_control test"));

## Log
org.openqa.selenium.NoSuchElementException: Unable to locate element: #adr_control test
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: 'LGDN14307-W7D01', ip: '192.168.190.171', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20170125094131, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=1076, browserVersion=51.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, firefox_profile=UEsDBBQACAgIAAF2bUoAAAAAAAAAA...}]
Session ID: 3ea6eab7-7e3f-4c2a-84e3-c6f9b93b1ee3
*** Element info: {Using=id, value=adr_control test}

**Comment by AutomatedTester** [comment]
This is invalid html, that's why we can't find it.

See https://html.spec.whatwg.org/#the-id-attribute, it can't have a white space in the ID
