### ISSUE TITLE
InvalidSelectorException when finding an element by id which has value in format "number + space character + number"

### ISSUE THREAD

**Issue by ninjateamdn** [mozilla/geckodriver#537]
## Environment:
Windows 7
Firefox 51.0.1
GeckoDriver 0.14
Selenium 3.1.0

## Steps to reproduce -
Exception when trying to find an element by id which has value in format "number + space character + number":
Ex: WebElement element = driver.findElement(By.id("5 5"));

## Log:
org.openqa.selenium.InvalidSelectorException: Given css selector expression "#\35  5" is invalid: InvalidSelectorError: '#\35  5' is not a valid selector: "#\35  5"
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: 'LGDN14307-W7D01', ip: '192.168.190.171', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20170125094131, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=6464, browserVersion=51.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, firefox_profile=UEsDBBQACAgIADV3bUoAAAAAAAAAA...}]
Session ID: 40bd888e-61e1-4e03-87b8-1d5907756837
*** Element info: {Using=id, value=5 5}

**Comment by AutomatedTester** [comment]
The id attribute can not have space in it. See https://html.spec.whatwg.org/#the-id-attribute

**Comment by jgraham** [comment]
No, that's an authoring conformance requirement, and we are expected to handle invalid content here. I imagine there's an escaping bug somewhere. But probably in the client, if it's rewriting this as a CSS selector.

**Comment by snpanigrahi9** [comment]
@AutomatedTester 
Actually in my scenario, I have the id with '_' symbol.
Its not working with firefox 52.0 in windows 7.
Same id is working fine with chrome browsers.
With firefox lower versions it was working as well.

So we are facing a lot of selenium issues in latest firefox and gecko driver.

Automation with latest firefox using gecko driver seems very challenging now a days..

**Comment by AutomatedTester** [comment]
@ninjateamdn 

Can you raise an issue with the selenium team for them to escape this properly before sending it over. Chromium doesn't use the new locators which is allowing it through.
