### ISSUE TITLE
function click() cannot work on an invisible row

### ISSUE THREAD

**Issue by ninjateamdn** [mozilla/geckodriver#538]
## Environment:
Windows 7
Firefox 51.0.1
GeckoDriver 0.14
Selenium 3.1.0

## Steps to reproduce -
We have a table with many rows and there are some rows which is outside of the table's frame. 
We try to use function click() on these invisible rows but it does not work.
For visible rows, action works correctly.

**Comment by AutomatedTester** [comment]
Selenium does not interact with hidden or non-displayed elements.
