### ISSUE TITLE
Firefox 52 and WebDriver 0.14.0 cannot start

### ISSUE THREAD

**Issue by algot** [mozilla/geckodriver#539]
## Firefox Version
52.0 32-bit
## Platform
Windows 10 x64

## Steps to reproduce -
I've installed Visual Studio 2017.
Created new Console Application project in "C:\dev\Selenium\QaShahin\WebDriverFramework" folder.
Add following packages by nuget:
- Selenium.Firefox.WebDriver.0.14.0
- Selenium.Support.3.3.0
- Selenium.WebDriver.3.3.0
- Selenium.WebDriver.ChromeDriver.2.28.0
- Selenium.WebDriver.IEDriver.3.3.0
- Selenium.WebDriver.PhantomJS.Xplatform.2.45.0.1

When I try to run following code:

`
using System;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

namespace WebDriverFramework
{
  class Program    { 
static void Main(string[] args)    {
      IWebDriver driver = new FirefoxDriver();
    }
  }
}
`

I got error 

'Cannot find a file named 'C:\dev\Selenium\QaShahin\WebDriverFramework\WebDriverFramework\bin\Debug\webdriver.json' or an embedded resource with the id 'WebDriver.FirefoxPreferences'. '

**Comment by platinumtest** [comment]
Did you try using Gecko Driver v0.15 first?  The devs say that if you are using Selenium 3.3, you have to use gecko driver 0.15.

**Comment by algot** [comment]
**platinumtest**
> 
I used latest stable Gecko Driver and Selenium provided by nuget.
Do you mean that I should install them manually?

**Comment by algot** [comment]
I've installed GeckoDriver 0.15 instead of 0.14
`Install-Package Selenium.WebDriver.GeckoDriver.Win32 -Pre `
But I get the same error.

**Comment by shaynemclevy** [comment]
With 0.14/3.2.0 i had to make a Firefox service that points to the exe.
ex. FirefoxDriverService.CreateDefaultService(/*path*/);

**Comment by AutomatedTester** [comment]
This appears to be a selenium issue. Please upgrade to latest Selenium/GeckoDriver and try again. If that still breaks raise the issue with that project.

**Comment by ajit-jadhav** [comment]
**Firefox 30/Firefox52+ Selenium 3.5.2 + WebDriver 3.5.2 can not start Firefox**
