### ISSUE TITLE
Unable to run firefox on running selenium grid in the background

### ISSUE THREAD

**Issue by ambikashri** [mozilla/geckodriver#541]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.1
## Platform
e.g. Windows
## Steps to reproduce -
I am using selenium 3.0.1 with gecko driver version 0.13.0.

On running the grid in the foreground, Firefox browser gets allocated and opens the console but on running the grid in the background, the grid console shows Firefox browser as graded out but script throws Net::ReadTimeout error.

I have configured the selenium grid in the task scheduler to run in the background.

**Comment by mandarin77** [comment]
I to am having a similar issue. I have selenium grid(hub) and node running as windows task scheduler upon startup. When I run chrome through grid it works perfect. When I try to run Firefox, on the console it grays out showing that the node is running and the step shows URL executing, but it just hangs at that step and even if I stop the run from eclipse, the console still shows the session as running so Iam forced to restart the node machine. I was on selenium 3.0.1 with Firefox 52 and I even tried updating selenium to 3.3 and it is still not working.

**Comment by andreastt** [comment]
This bug report doesn’t contain enough information to be actionable. Sorry.
