### ISSUE TITLE
Unable to create new remote session.

### ISSUE THREAD

**Issue by sandeepreddy475** [mozilla/geckodriver#542]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform = Windows

I am getting below exception when tried to execute using selenium 3.0.1 version and geckodriver-v0.15.0-win64 can you please let me know the reason why this is happening?

Exception:- Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@123ef382, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@123ef382, version=, platform=ANY}], required capabilities = Capabilities [{}]

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [x] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [x] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by platinumtest** [comment]
Try updating both Selenium and Firefox to the latest and greatest. I had the same issue last week and this did the trick.

**Comment by AutomatedTester** [comment]
please upgrade selenium
