### ISSUE TITLE
 Driver.Manage().Timeouts().ImplicitWait gives runtime error {not a number} 

### ISSUE THREAD

**Issue by davidPGH** [mozilla/geckodriver#544]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform
Windows c#

## Steps to reproduce -
the following code resulted in a runtime error: "[timeouvalue0 ]not a number" same error forced me to update from ImplicitlyWait Chromedriver runs fun with either

             TimeSpan timeoutValue = timeout ?? TimeSpan.FromSeconds(60);
            WebDriverWait wait = new WebDriverWait(Driver, timeoutValue);
            wait.Until(d => d.PageSource.ToLower().Contains("</html"));
            Driver.Manage().Timeouts().ImplicitWait = timeoutValue;

**Comment by AutomatedTester** [comment]
Please make sure that you are using the latest Selenium/GeckoDriver.

This issue is part of https://github.com/SeleniumHQ/selenium/issues/3607 and should be tracked there.

**Comment by S-Kerrigan** [comment]
I can confirm this issue:
WD: v3.3.1
FD: v0.15.0

From Maven:
```
<dependency>
	<groupId>org.testng</groupId>
	<artifactId>testng</artifactId>
	<version>6.8.8</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-java</artifactId>
	<version>3.3.1</version>
</dependency>
```
From JAVA-code:
```
DriverPath = "C:\\Users\\... ...\\src\\main\\resources\\Drivers\\Gecko\\geckodriver.exe";
				System.setProperty("webdriver.gecko.driver", DriverPath);
				profile.setEnableNativeEvents(true);

				if (hubKey) {
					try {
						DesiredCapabilities capabilities = DesiredCapabilities.firefox();
						capabilities.setBrowserName("firefox");
						capabilities.setPlatform(Platform.WINDOWS);
						capabilities.setCapability("marionette", true);
						URL url = new URL("http://192.168.1.2:4444/wd/hub");
						driver = new RemoteWebDriver(url,capabilities);
					} catch (Exception ex) {
						ex.printStackTrace();
					}
				} else {
					driver = new FirefoxDriver();
				}

				driver = new EventFiringWebDriver(driver).register(eventListener);
				driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
```
Result log from cmd:
```
org.openqa.selenium.WebDriverException: Not a Number
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '______', ip: '__.__.__.__', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161208153507, version=50.1.0, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=4708, browserVersion=50.1.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 19882a93-0397-46ba-8410-7b3433511a40
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
        at org.openqa.selenium.firefox.FirefoxDriver.access$100(FirefoxDriver.java:67)
        at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:288)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTimeouts.implicitlyWait(EventFiringWebDriver.java:560)
```

**Comment by S-Kerrigan** [comment]
Very strange, after full rebuild trouble is missing. Yes, nothing a problems. Cause - my bad hands. Sorry.

**Comment by Zwilicht** [comment]
Has the same Error: 
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);  
not a number

In C#
I have the  latest Selenium/GeckoDriver Version.
it´s 3.3.0 in C#  why is the Java Version 3.3.1 ?
It is only fixed in Java?

**Comment by Twyllo** [comment]
driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(7);

@Zwilicht,

Working for me on c#, 3.3.0, 0.15.0 - win 10/server 2012

**Comment by Zwilicht** [comment]
OK thanks.
I didn´t have the latest Firefox (had ff 50.0.1). 
After upgrading to 52.0.1 it works without error.

**Comment by S-Kerrigan** [comment]
Yes, i think, we have a troubles because in readme from new versions not any saying about, that need FF with build no less a 52.

**Comment by jgraham** [comment]
Unfortunately, due to the way that geckodriver works, and the fact that the implementation is not yet stable, it is currently always necessary to use the latest avaiable Firefox. Once we have a complete implementation of the WebDriver 1 spec ("geckodriver 1.0") then we would expect all subsequent Firefoxes to work with all subseqent geckodrivers, unless you use some post-1.0 features.

**Comment by S-Kerrigan** [comment]
Hm... interesting. Ok, thank you.

**Comment by davidPGH** [comment]
YAY ! After upgrading to 52.0.1 (had 52.0.0) it works without error....Seems to respond slower than Selenium 2 (having to tweak explicit waits on tests that ran robustly on Selenium2, but that's to be expected on pre-version 1 drivers)

**Comment by prashant08** [comment]
Not working for me 
I am getting issue using C#-Selenium on below code:

public static void SetImplicitWait(this IWebDriver driver, TimeSpan waitTime)
    {
        driver.Manage().Timeouts().ImplicitWait = waitTime;
    }
System.NotImplementedException: Driver instance must comply with the W3C specification to support getting timeout values.

Please help to resolve this issue.
Selenium Web driver . : 3.141
Chrome Driver : 2.45

**Comment by whimboo** [comment]
@prashant08 using chrome driver but filing a comment for geckodriver doesn't make sense. If it's failing for chromedriver then report a bug over there.

Closing comments on this issue given that there is nothing more to add.
