### ISSUE TITLE
InvalidSelectorException when finding an element by attribute which has single quote (') character in value

### ISSUE THREAD

**Issue by ninjateamdn** [mozilla/geckodriver#546]
## Environment:
Windows 7
Firefox 51.0.1
GeckoDriver 0.14
Selenium 3.1.0

## Steps to reproduce:
Exception when trying to find an element by attribute which contains single quote (') character in its value:
Ex: WebElement element = driver.findElement(By.name("value'123"));

## Log:
org.openqa.selenium.InvalidSelectorException: Given css selector expression "*[name='value'123']" is invalid: InvalidSelectorError: '*[name='value'123']' is not a valid selector: "*[name='value'123']"
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.1.0', revision: '86a5d70', time: '2017-02-16 07:57:44 -0800'
System info: host: 'LGDN14307-W7D01', ip: '192.168.190.171', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20170125094131, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=7820, browserVersion=51.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt, firefox_profile=UEsDBBQACAgIABKLb0oAAAAAAAAAA...}]
Session ID: e476890f-4f42-4536-b025-17ecdf15f679
*** Element info: {Using=name, value=value'123}

**Comment by jgraham** [comment]
That seems like a selenium issue. Please file it in their bug tracker.

**Comment by gyanachand** [comment]
Is this fixed? Any detail would help!
