### ISSUE TITLE
Cannot read the firefox browser console

### ISSUE THREAD

**Issue by puneetkaur11** [mozilla/geckodriver#549]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox 52
selenium server 3.3.1
geckodriver 0.15.0

## Platform
OSX/Mac 10.11.6

## Steps to reproduce -
===================
if(browserType.equals("firefox")){
	FirefoxProfile profile=new FirefoxProfile();
	profile.setPreference("intl.accept_languages",language);
	cap = DesiredCapabilities.firefox();
	cap.setCapability(FirefoxDriver.PROFILE, profile);
	cap.setCapability("marionette", true);
        driver= new RemoteWebDriver(new URL(nodeURL), cap);
	s = (String) ((JavascriptExecutor) driver).executeScript("return navigator.userAgent;");

	driver.manage().window().maximize();
	driver.navigate().to(appURL);
}

@AfterMethod(alwaysRun=true)
	public List<String> afterMethod(ITestResult result) throws ExecutionException, Exception {
		
		if (result.getStatus() == ITestResult.FAILURE) {

			String methodDescription = result.getMethod().getDescription();
			int resultStatus= result.getStatus();

			System.out.println(resultStatus);

			if (resultStatus == 2){
				resultS = "<b>"+"FAILED" + "</b>";
			}

			testCaseResult.add(methodDescription + " : " + "<b>" + "<font color=#ff0000>" +"FAIL" + "</b>");
			LogEntries logs=analyzeLog();
}

	public LogEntries analyzeLog() {

		LogEntries logs = driver.manage().logs().get("browser"); // fails here
		for (LogEntry entry : logs) {
		System.out.println(new Date(entry.getTimestamp()) + " " + entry.getLevel() + " " +      entry.getMessage());
		} return logs;
	}

## ERROR:
========
org.openqa.selenium.UnsupportedCommandException: POST /session/dbd843df-46d0-1f49-8c5e-7d4e690e9a79/log did not match a known command
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'MacBook-Pro-4.local', ip: '2601:646:8701:5d50:7c8d:2023:b243:b2e0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/b5/k62v_k1x40l5g6sjcb7hnv040000gp/T/rust_mozprofile.iP1UehkVhzJT, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=52.0, platformVersion=15.6.0, moz:processID=34117, browserName=firefox, platformName=darwin}]
Session ID: dbd843df-46d0-1f49-8c5e-7d4e690e9a79
Command duration or timeout: 66 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by andreastt** [comment]
The Selenium log API is not supported by geckodriver.

**Comment by arun2003** [comment]
Is this issue fixed? I am also not able to capture console errors from Firefox 53.0.2 (32-bit) using selenium 3.3.0

**Comment by andreastt** [comment]
@arun2003 The Selenium log API isn’t supported by geckodriver.

**Comment by xmo-odoo** [comment]
@andreastt is there an other tracking bug to follow an eventual implementation of the webdriver/selenium log API?

**Comment by andreastt** [comment]
@xmo-odoo https://github.com/w3c/webdriver/issues/406
