### ISSUE TITLE
geckodriver.exe is throwing os error 10013

### ISSUE THREAD

**Issue by ambikashri** [mozilla/geckodriver#550]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
51.0.1

## Platform
Windows10, Windows 8.1 Pro

## Steps to reproduce -
On running geckodriver.exe it throws the below error 
1489660004367   geckodriver     ERROR   An attempt was made to access a socket in a way forbidden by its access permissions. (os error 10013)

**Comment by andreastt** [comment]
According to https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx:

> An attempt was made to access a socket in a way forbidden by its access permissions. An example is using a broadcast address for sendto without broadcast permission being set using setsockopt(SO_BROADCAST).
>
> Another possible reason for the WSAEACCES error is that when the bind function is called (on Windows NT 4.0 with SP4 and later), another application, service, or kernel mode driver is bound to the same address with exclusive access. Such exclusive access is a new feature of Windows NT 4.0 with SP4 and later, and is implemented by using the SO_EXCLUSIVEADDRUSE option.

Perhaps you should check what is running on the ports geckodriver/Firefox is trying to bind to? I need more information to be able to reproduce this.

Also, you should always run any issues you file against this project with Firefox Nightly for the most accurate report.

Locking this until enough reproducible information is added.

**Comment by ambikashri** [comment]
geckodriver is using port 4444. The same port is being used by the selenium hub by default.
Also, on downgrading the firefox browser to version 49.0.1 , geckodriver version 0.14.0 started working fine.

**Comment by andreastt** [comment]
WebDriver remote ends are supposed to be interchangeable, hence why geckodriver listens on port 4444 by default. It should be possible to replace geckodriver with a Selenium hub server to gain matrix selection of multiple browsers. This is what is known as an ‘intermediary’ or proxy server.

Selenium is supposed to start geckodriver on a different port when it itself is bound to port 4444, and I believe this is what it does in https://github.com/SeleniumHQ/selenium/blob/4b7f4021ee2467e7c7e9782ef0ab50bac1dc8613/java/client/src/org/openqa/selenium/firefox/GeckoDriverService.java#L121 and https://github.com/SeleniumHQ/selenium/blob/4b7f4021ee2467e7c7e9782ef0ab50bac1dc8613/java/client/src/org/openqa/selenium/remote/service/DriverService.java#L298.

It’s really hard to help you unless you investigate this issue closer yourself.

**Comment by ambikashri** [comment]
I still face this issue when the hub is on another system and node on other system.

**Comment by ambikashri** [comment]
Is this something to do with Selenium Grid 3.0.1 jar? I specifically get "Net::ReadTimeout" error while running with firefox browser version 51.0.1. But the same setup goes fine when the browser is downgraded to version 49.0.1

**Comment by andreastt** [comment]
Well Selenium 3.0.1 is too old to be used with geckodriver. The README says you need to use 3.3.1 or newer. Preferably, the very latest version.

Firefox 49.0.1 also isn’t supported by geckodriver.
