### ISSUE TITLE
[geckodriver]Selenium 3.3.1 & Firefox 52.0 move_to_element not work

### ISSUE THREAD

**Issue by salanhess** [mozilla/geckodriver#554]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0+ geckodriver 0.15.0 

## Platform
OSX 10.10.4

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:
`from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
import time

driver = webdriver.Firefox()
driver.get("http://global.bing.com/")
driver.implicitly_wait(20)

mouse = driver.find_element_by_id("off_link")
ActionChains(driver).move_to_element(mouse).perform()
time.sleep(5)
#print(driver.find_element_by_id("officemenu_word_img"))
driver.find_element_by_id("officemenu_word_img").click()`

/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 /Users/hbai/PycharmProjects/interview/Selenium_study/C15_select_list.py
Traceback (most recent call last):
  File "/Users/hbai/PycharmProjects/interview/Selenium_study/C15_select_list.py", line 15, in <module>
    driver.find_element_by_id("officemenu_word_img").click()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 491, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: 

Process finished with exit code 1

**Comment by andreastt** [comment]
The issue here does not appear to be that element move doesn’t work, but that the element is not displayed in the viewport when you try to interact with it. It’s impossible to tell why this is since you didn’t attach a reproducible test case. Happy to re-open once this is provided.

**Comment by dwt** [comment]
Well, on my system the element move indeed doesn't work  as it doesn't bring up the popup / hover menu when the mouse move is executed.

So, could you please reopen?

I've attached a slightly commented script (as I'm having the same issue on the same software combination.

```python
#!/usr/bin/env python

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
import time

driver = webdriver.Firefox()
driver.get("http://global.bing.com/")
driver.implicitly_wait(20)

# this should open the menu to let you choose the office product to launch - but doesn't
mouse = driver.find_element_by_link_text("Office Online")
ActionChains(driver).move_to_element(mouse).perform()
# When trying to execute the above line in pdb I get this error all the time:
# *** WebDriverException: Message: Expected 'id' mouse to be mapped to InputState whose subtype is undefined, got: pointerMove
# manually hovering over this menu entry (top line) makes the test work
time.sleep(5)
#print(driver.find_element_by_id("officemenu_word_img"))
# this should open the word online app in a new tab/window
driver.find_element_by_id("officemenu_word_img").click()
```

**Comment by salanhess** [comment]
@dwt 
[Git not support re-open issue feature,](http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github) could you open a new issue with your issue steps and @me if possible, thanks!

**Comment by dwt** [comment]
@salanhess To my understanding the simplest way would be for @andreastt to reopen the issue  - which he has promised. So I would wait a bit.

**Comment by andreastt** [comment]
That `move_to_element` doesn’t work as expected I attribute to the lack of a shim in the Selenium language bindings. geckodriver and Marionette both support moving a pointer to an element now (following https://bugzilla.mozilla.org/show_bug.cgi?id=1337133), and I’m guessing that the primitives used for action sequences in the Selenium Python bindings are not correctly mapping `move_to_element` to the correct W3C WebDriver action.

Maybe @AutomatedTester can comment, since he has done some work on Selenium in this area.

**Comment by dwt** [comment]
Looking at the selenium source code it certainly looks like they implemented something: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/action_chains.py#L274

**Comment by andreastt** [comment]
So I experimented with the [wdclient](https://github.com/w3c/wdclient) client we use to test geckodriver, and I am certainly able to make geckodriver click an element after moving the mouse:

```py
import webdriver
import urllib
import time

def inline(doc):
    return "data:text/html;charset=utf-8,{}".format(urllib.quote(doc))

caps = {"moz:firefoxOptions": {"binary": "/home/ato/src/gecko/obj-x86_64-pc-linux-gnu/dist/bin/firefox"}}

with webdriver.Session("127.0.0.1", 4444, desired_capabilities=caps) as session:
    session.url = inline("""
        <style>
        * { padding: 0; margin: 0; }
        button { position: absolute; top: 100px; left: 100px; }
        </style>

        <button onclick="this.style.background = 'pink'">click me</button>
        """)

    time.sleep(2)

    button = session.find.css("button", all=False)
    session.actions.sequence("pointer", "foo") \
        .pointer_move(5, 5, origin=button) \
        .pointer_down(0) \
        .pointer_up(0) \
        .perform()

    time.sleep(10)
```

(Sorry for the poor quality of the code.)
