### ISSUE TITLE
Crashing one thread breaks application

### ISSUE THREAD

**Issue by Twyllo** [mozilla/geckodriver#557]
## Version
FF 52.0.0, 52.0.1 32bit
Gecko 0.15.0
Selenium 3.3.0
Win 10, Win Server 2012

Using multiple threads on pc, I get error on bottom which completely halts application even though every thing & every thread is in try catch blocks. Is there a way around this without using intermediary app?

Happens with 0.2 - 2% chance randomly. Maybe multithreading isnt even the problem but theres a bigger chance to fail...

Error: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 10054, message: "An existing connection was forcibly closed by the remote host." } }', src\libcore\result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by andreastt** [comment]
Do you have a way to reproduce this?

**Comment by andreastt** [comment]
Closing this until reproducible steps are added. Happy to re-open at a later stage.
