### ISSUE TITLE
driver.switch_to.alert.authenticate(login, password) not implemented

### ISSUE THREAD

**Issue by dwt** [mozilla/geckodriver#559]
The problem is that the backend for this method seems not to be implemented in marionette / geckodriver.

Please see the appended script for a reproduction. A workaround I found is also documented there.

## Firefox Version
52.0.1

## Platform
Windows/OSX/Linux

## Steps to reproduce -
The following script demonstrates the problem:

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Firefox()
try:
    url = 'https://zms-test.de/manage_main'
    login = 'wrong'
    password = 'wrong'
    driver.get(url)
    driver.switch_to.alert.authenticate(login, password)
    # workaround
    # driver.switch_to.alert.send_keys(login + Keys.TAB + password)

except Exception as e:
    print e
    driver.quit()
```
This outputs:

```Message: POST /session/4a37f61f-50d6-8f42-aced-d6603e78ad5e/alert/credentials did not match a known command```

on the line `driver.switch_to.alert.authenticate(login, password)`

geckodriver.log:
```
1490114321981	geckodriver	INFO	Listening on 127.0.0.1:59636
1490114322997	mozprofile::profile	INFO	Using profile path /var/folders/m0/9n0003n56d13lzplwcxk_ldr0000gn/T/rust_mozprofile.h5l9dm0Bvz2y
1490114322999	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args []
1490114323011	geckodriver::marionette	INFO	Connecting to Marionette on localhost:59645
1490114323696	Marionette	INFO	Listening on port 59645
1490114324044	Marionette	WARN	TLS certificate errors will be ignored for this session
2017-03-21 17:38:45.512 plugin-container[81677:23729554] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x953b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-03-21 17:38:45.516 plugin-container[81677:23729554] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9803, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1490114326245	Marionette	INFO	New connections will no longer be accepted
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[Child 81677] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
[Child 81677] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2143
```

Do you need any more info to reproduce?

**Comment by andreastt** [comment]
Basic Auth dialogues are not specified by the WebDriver standard, and thus not supported in geckodriver.

**Comment by dwt** [comment]
Uhm, that is surprising. Could you please link to the recommended workaround for future reference?

**Comment by whimboo** [comment]
> Basic Auth dialogues are not specified by the WebDriver standard, and thus not supported in geckodriver.

Well, I have to add that HTTP authentication dialogs have to be supported in Marionette itself because we need that for the Firefox functional tests. So `accept()` and `dismiss()` will work, but not sure what geckodriver will pass through. So you may not have access to its ui, means to the user and password fields.

**Comment by andreastt** [comment]
I’m not aware of a workaround.
