### ISSUE TITLE
geckodriver for raspbian

### ISSUE THREAD

**Issue by dddjjj** [mozilla/geckodriver#560]
Just wondering if there is a geckodriver for raspbian to be used on the popular Raspberry Pi or there is a plan for making one.

**Comment by cgoldberg** [comment]
does the ARM build not work?

**Comment by dddjjj** [comment]
It does work on Raspberry Pi 1 which is armv6.

**Comment by andreastt** [comment]
Due to the low requirement for this, I’m inclined to say you should buy a newer machine that supports ARMv7 HF or compile it yourself. Using [Rustup](http://rustup.rs/) it is quite easy to build geckodriver. See the README for further building instructions.
