### ISSUE TITLE
Python Appear an issue "KeyError: 'sessionId'" Lable:geckoderiver

### ISSUE THREAD

**Issue by makeYao** [mozilla/geckodriver#561]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox  48.0.2
geckoderiver：geckodriver-v0.15.0-win64

## Platform
![selenium](https://cloud.githubusercontent.com/assets/26588934/24181631/18222caa-0ef7-11e7-9e4c-2bf22ddef759.png)
 Windows

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by whimboo** [comment]
The screenshot in comment 0 shows that you are not utilizing GeckoDriver and Marionette for this test. So I assume this is a Selenium webdriver specific issue?

**Comment by andreastt** [comment]
Please use Firefox Nightly, as well as the latest Selenium client bindings and server.

**Comment by makeYao** [comment]
OK I try
