### ISSUE TITLE
Profile.SetPreference(“intl.accept_languages“, “de“) does not work with geckodriver 0.15.0

### ISSUE THREAD

**Issue by KPKA** [mozilla/geckodriver#562]
My Firefox is installed with English as language. My tests depend on different languages, so I want to choose the language during startup. Earlier when Firefox was supported by Selenium itself it worked correctly. Since we have to use geckodriver it doesn’t work anymore.
Can anybody help me, please?

## Firefox Version
Firefox 52.0.1

## Platform
Windows 7

## Selenium Version
Selenium Version: 3.3.0

## Used Language
.Net Version: 4.5.1

## Actual Behavior
Firefox should start with the expected language.

## Expected Behavior
Firefox starts with the installed language.

## Steps to reproduce 

```
var profile = new FirefoxProfile();
profile.SetPreference("intl.accept_languages”, "de");
 
var capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile);
capabilities.SetCapability("marionette", true);
capabilities.SetCapability("acceptSslCerts", true);
capabilities.SetCapability("acceptInsecureCerts", true);

var timeSpan = TimeSpan.FromSeconds(120);
var uri = new Uri(“www.anyuri.com”);
var driver = new RemoteWebDriver(uri, capabilities, timeSpan);
driver.Manage().Window.Maximize();`

I tried it in another way, too:
`var capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile);
capabilities.SetCapability("marionette", true);
capabilities.SetCapability("acceptSslCerts", true);
capabilities.SetCapability("acceptInsecureCerts", true);
capabilities.SetCapability("intl.accept_languages", "de-DE");
            
var timeSpan = TimeSpan.FromSeconds(120);
var uri = new Uri(TestSuiteConfiguration.SelenumHubFirefoxEvaluationURL);
var driver = new RemoteWebDriver(uri, capabilities, timeSpan);
driver.Manage().Window.Maximize();
return driver;
```

## Log

```
14:56:17.899 INFO - Executing: [get all cookies])
14:56:17.915 INFO - Done: [get all cookies]
14:56:21.440 INFO - Executing: [take screenshot])
14:56:21.565 INFO - Done: [take screenshot]
14:56:21.627 INFO - Executing: [delete session: be997639-6932-48a6-b7cb-62994946a8c3])
14:56:23.109 ERROR - Unable to kill process with PID 14724
14:56:23.109 INFO - Done: [delete session: be997639-6932-48a6-b7cb-62994946a8c3]
12:47:49.618 INFO - Executing: [new session: Capabilities [{acceptSslCerts=true, marionette=true, acceptInsecureCerts=true, browserName=firefox, intl.accept_languages=de-DE, version=, platform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]])
12:47:49.618 INFO - Creating a new session for Capabilities [{acceptSslCerts=true, marionette=true, acceptInsecureCerts=true, browserName=firefox, intl.accept_languages=de-DE, version=, platform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]
12:47:49.618 INFO - Unable to use profile: class java.util.HashMap
12:47:52.285 INFO - Detected dialect: W3C
12:47:52.287 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, marionette=true, acceptInsecureCerts=true, browserName=firefox, intl.accept_languages=de-DE, version=, platform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]]
12:47:52.359 INFO - Executing: [maximise window])
12:47:52.395 INFO - Done: [maximise window]
```

**Comment by andreastt** [comment]
`intl.accept_languages` is not a capability, but a preference. You will want to set this in in the Firefox-specific option capability, like `{"moz:firefoxOptions": {"prefs": [{"intl.accept_languages": "de-DE"}]}}`. See the README for more examples.

**Comment by andreastt** [comment]
The relevant part of the README is https://github.com/mozilla/geckodriver#prefs-object.

**Comment by KPKA** [comment]
I have tried this in different ways:
'
var profile = new FirefoxProfile();
profile.SetPreference("intl.accept_languages", "de-DE");

var capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile);
capabilities.SetCapability("marionette", true);
capabilities.SetCapability("acceptSslCerts", true);
capabilities.SetCapability("acceptInsecureCerts", true);
          
capabilities.SetCapability("profile", profile);
capabilities.SetCapability("moz:firefoxOptions", profile);
var timeSpan = TimeSpan.FromSeconds(120);
var uri = new Uri(TestSuiteConfiguration.SelenumHubFirefoxEvaluationURL);
var driver = new RemoteWebDriver(uri, capabilities, timeSpan);
driver.Manage().Window.Maximize();'

But it doesn't work. The log which is produced:

`12:09:21.544 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, marionette=true, acceptInsecureCerts=true, profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}, browserName=firefox, moz:firefoxOptions={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}, version=, platform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]]
`

The second way which I tried is:
          
`var profile = new FirefoxProfile();
var opt = new FirefoxOptions();
opt.SetPreference("intl.accept_languages", "de-DE");
            
var capabilities = DesiredCapabilities.Firefox();
capabilities.SetCapability(FirefoxDriver.ProfileCapabilityName, profile);
capabilities.SetCapability("marionette", true);
capabilities.SetCapability("acceptSslCerts", true);
capabilities.SetCapability("acceptInsecureCerts", true);
capabilities.SetCapability("moz:firefoxOptions", opt);
var timeSpan = TimeSpan.FromSeconds(120);
var uri = new Uri(TestSuiteConfiguration.SelenumHubFirefoxEvaluationURL);
var driver = new RemoteWebDriver(uri, capabilities, timeSpan);
driver.Manage().Window.Maximize();`

It doesn't work, too. The log which is produced:
`12:15:04.456 INFO - Done: [new session: Capabilities [{acceptSslCerts=true, marionette=true, acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={BrowserExecutableLocation=null, UseLegacyImplementation=false, Profile=null, LogLevel=7}, version=, platform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]]
`

Can you tell me how I can get this preference ("intl.accept_languages") into "moz:firefoxOptions"?

**Comment by jgraham** [comment]
I think you need to ask the maintainer of the .NET selenium bindings; what you're doing looks reasonable, but I don't know the details of how those bindings work.
