### ISSUE TITLE
org.openqa.selenium.WebDriverException: Not a Number exception while setting implicitly wait

### ISSUE THREAD

**Issue by Max-Hab** [mozilla/geckodriver#564]
## Firefox Version
45.8.0
geckodriver-v0.15.0-win64

## Platform
Widows 7, 64 bit

## Steps to reproduce -
1. Instantiate new local driver:` WebDriver driver= new FirefoxDriver();`
2. Execute command:     `driver.manage().timeouts().implicitlyWait(0, TimeUnit.SECONDS);`

Exception is thrown.
The same is for 1 second and etc.
Exception trace:

org.openqa.selenium.WebDriverException: Not a Number
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: '', ip: '', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_66'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20170301181722, version=45.8.0, platform=XP, proxy={}, specificationLevel=1, acceptSslCerts=false, browserVersion=45.8.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 1b8fea21-9ca1-45ad-afaf-36f109368108
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:99)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:43)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.firefox.FirefoxDriver.access$100(FirefoxDriver.java:67)
	at org.openqa.selenium.firefox.FirefoxDriver$1$1.implicitlyWait(FirefoxDriver.java:288)

Log
[log.txt](https://github.com/mozilla/geckodriver/files/862362/log.txt)

**Comment by andreastt** [comment]
Firefox 45 isn’t supported. Please use [Firefox Nightly](https://nightly.mozilla.org/).

**Comment by Grifan** [comment]
Hi! I have problem which looks like that, but my ff version 46.0. Can u tell how i have to use ff nightly?

**Comment by cimdalli** [comment]
Using **selenium-java-3.3.1** and **geckodriver-v0.15.0** works fine.

**Comment by stripurari** [comment]
Using selenium-java-3.3.1 and geckodriver-v0.14.0 
Firefox 46.0.1 on mac OS Sierra 10.12
Still I get org.openqa.selenium.WebDriverException: Not a Number exception is thrown. 
Any help appreciated. Thanks

**Comment by andreastt** [comment]
Firefox 46 is not supported. You should consider using [Firefox Nightly](https://nightly.mozilla.org/).

**Comment by stripurari** [comment]
@andreastt Thank you for quick reply.
Now browser opens up and navigate to the required site also, but later it is giving new exception, I tried to find a solution for that, but I didn't get. Here is the exception: **org.openqa.selenium.WebDriverException: 
Error: Permission denied to access property "H"**

Please help me out with this. Thank you.

**Comment by andreastt** [comment]
@stripurari That seems like an unrelated issue. Do you mind filing a new issue and attaching a trace-level geckodriver log? There are instructions in the README on how to crank up the log level.

**Comment by tkleiber** [comment]
I see the same issue with firefox 50.1.0 and geckodriver 0.16.0, so which firefox version is supported?

**Comment by andreastt** [comment]
@tkleiber See the ‘Supported Firefoxen’ section in the README: https://github.com/mozilla/geckodriver#supported-firefoxen

**Comment by aashwinitrivedi** [comment]
I have faced same issues.. but got solution for this..
please check configurations details if this might be helpful for u guys
FF 48.0.2 win32
selenium 3.3.1
gecko driver ver 0.15

below small code for FF Initialization
System.setProperty("webdriver.gecko.driver", "E://Users//Downloads//selenium_3.3//geckodriver-v0.15.0-win32//geckodriver.exe");
		DesiredCapabilities capabilities = DesiredCapabilities.firefox();
		driver = new FirefoxDriver(capabilities);
		driver.get("www.google.com");

**Comment by andreastt** [comment]
@aashwinitrivedi That is not a solution! Please report whatever issues you are having as a new bug instead of hijacking this for support.

You are also using outdated versions of Selenium and geckodriver, which explains many of the issues you are having.
