### ISSUE TITLE
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -Dwebdriver.gecko.driver=geckodriver.exe

### ISSUE THREAD

**Issue by shohilbagdai** [mozilla/geckodriver#566]
In order to help us efficiently investigate your issue, please provide the following information:

I have just download geckodriver0.15.0 and selenium standalone3.3.1
and getting this issue

## Firefox Version 51.01
From the "About" dialog.

## Platform
e.g. Windows

## Steps to reproduce -
ava -jar selenium-server-standalone-3.3.1.jar -Dwebdriver.gecko.driver="geckodriver.exe" -Dwebdriver.chrome.driver="chromedriver.exe"

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
That seems like a problem in your program or in Selenium.
