### ISSUE TITLE
Performance worse than Edge, Chrome

### ISSUE THREAD

**Issue by vantruongt2** [mozilla/geckodriver#569]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox 51.0, gecko driver 0.14.0, Selenium 3.0.1

## Platform
Windows

#### For example

I try to 
 - [ ] Navigate to google page. Chrome takes about 6s, Edge takes about 7s, Firefox takes about 11s to navigate
 - [ ] Enter on search textbox. Chrome takes about 300ms, Edge takes about 100ms, Firefox takes about 300ms to enter

#### Sample code
		long st =  System.currentTimeMillis();
		//RemoteWebDriver remote = new RemoteWebDriver(new URL("http://localhost:9515"), DesiredCapabilities.chrome());
		RemoteWebDriver remote = new RemoteWebDriver(new URL("http://localhost:4444"), DesiredCapabilities.firefox());	
		//RemoteWebDriver remote = new RemoteWebDriver(new URL("http://localhost:17556"), DesiredCapabilities.edge());	
		remote.get("http://google.com");		
		System.out.println(System.currentTimeMillis()-st);
		
		Thread.sleep(2000);
		
		st =  System.currentTimeMillis();
		remote.findElement(By.name("q")).sendKeys("Selenium");
		System.out.println(System.currentTimeMillis()-st);

**Comment by vinhkd** [comment]
Up

**Comment by cgoldberg** [comment]
it's hard to infer anything about performance based on this benchmark:
 * It consists of a single sample
 * the environment details are unknown
 * latency from fetching remote content is included in timing

I don't think any conclusions can be drawn based on the OP's anecdotal observation.

**Comment by snpanigrahi9** [comment]
I am agree with this issue.
Performance is very poor in firefox as compared to chrome.

**Comment by AutomatedTester** [comment]
Since you are using remote server there could be, and I am willing to bet, there are potential speed issues there as it does internal translating.

Removing the remote server and doing extremely simple timing tests for navigation I get

```python
>>> from selenium import webdriver
>>> def navigate():
...   import datetime
...   start = datetime.datetime.now()
...   f.get("http://www.mozilla.org")
...   stop = datetime.datetime.now()
...   print("it took {}".format(stop - start))
...
>>> f=webdriver.Firefox()
>>> navigate()
it took 0:00:01.872920
>>> f.quit()
>>> f=webdriver.Chrome()
>>> navigate()
it took 0:00:01.609057
```

**Comment by AutomatedTester** [comment]
Looking at typing into Google search I see the following

```python
>>> def type_in_google():
...   import datetime
...   start = datetime.datetime.now()
...   f.get("http://www.google.com")
...   stop = datetime.datetime.now()
...   print("it took {} to navigate".format(stop - start))
...   q = f.find_element_by_name("q")
...   start = datetime.datetime.now()
...   q.send_keys("XHTML might be the future... maybe")
...   stop = datetime.datetime.now()
...   print("it took {} to type".format(stop - start))
...
>>> f.quit()
>>> f=webdriver.Firefox()
>>> type_in_google()
it took 0:00:01.790378 to navigate
it took 0:00:00.327782 to type
>>> f.quit()

>>> f=webdriver.Chrome()
>>> type_in_google()
it took 0:00:09.144507 to navigate
it took 0:00:00.717345 to type
>>> f.quit()
```

**Comment by AutomatedTester** [comment]
The last two comments are made using Python 2.7.13, Firefox 53.0.2 and GeckoDriver 0.16.1

**Comment by AutomatedTester** [comment]
I am going to close this as a Selenium issue and suggest you raise the issue with them.
