### ISSUE TITLE
Expose full document screen capture endpoint

### ISSUE THREAD

**Issue by andos561** [mozilla/geckodriver#570]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.1

## Platform
macOS Sierra

## Steps to reproduce -
To capture the whole page in screenshots in v0.15.0, I changed
marionette.rs line 924 to
data.insert("full".to_string(), Json::Boolean(true));

but that only captures the whole page vertically. Horizontally it still crops at the Browser window viewport. What do I need to change to get the whole page in the screenshot?

**Comment by andreastt** [comment]
We have support for taking full document screenshots in Marionette, but it isn’t exposed in geckodriver yet since it is a proprietary non-WebDriver API. WebDriver only expects the capture area to be the viewport. We do, however, want to expose this under a Mozilla-specific namespace in geckodriver.

**Comment by cezarypiatek** [comment]
Hi
This feature is really crucial for my selenium wrapper. Is there any way to workaround this until you add some kind of switcher? When are you going to add this option?  May I help somehow to bring this forward?

**Comment by cezarypiatek** [comment]
@andreastt could you tell me when are you planning to expose this feature in geckodriver? This issue has over a half year and nothing change. I'm asking again because it's very crucial for my project.

**Comment by andreastt** [comment]
@cezarypiatek There is a vague intent, but this is low priority from our side. I am happy to receive patches for this.

**Comment by whimboo** [comment]
@andreastt you tagged this issue with geckodriver. Do we actually have a bug for it filed?

**Comment by andreastt** [comment]
@whimboo The canonical source of geckodriver was on GitHub when I filed this.

**Comment by whimboo** [comment]
@andreastt sure, but would you mind to file a bug which describes whatever we want to have? Thanks.

**Comment by andreastt** [comment]
Sure, sorry about the delay. Here’s the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1431148
