### ISSUE TITLE
Can't install 32exe Notice ntdll.dll missing but the dll works well

### ISSUE THREAD

**Issue by AnnNing** [mozilla/geckodriver#581]
## when i install the win32 geckodriver.exe ( i tried every version released ),they all notice ntdll.dll  is missing ,but i have ntdll.dll in C:\WINDOWS\system32 ,whose version is 5.1.2600.6055 . I wonder is my os version not supported or the dll is the problem ?

Please help me out ，3Q

**Comment by andreastt** [comment]
Windows XP is not supported by geckodriver. Please upgrade your operating system and apply all the latest service packs.
