### ISSUE TITLE
Firefox is not able to get the URL provided

### ISSUE THREAD

**Issue by umesh-naik** [mozilla/geckodriver#582]
OS: windows 7, 64-bit
Selenium: 3.0.1
Gecodriver version: 0.15.0

With the above configuration and with the URL provided with `driver.get(TestURL)`, Firefox is not able to open the URL but it is initialized.

**Comment by davehunt** [comment]
You haven't provided the value for `TestURL`, the language of the Selenium bindings (3.0.1 sounds like it's not the latest for any language), the version of Firefox, or any details of the error. Please provide details according to the issue template.
