### ISSUE TITLE
Actions.click(WebElement) is not triggered

### ISSUE THREAD

**Issue by asashour** [mozilla/geckodriver#584]
## Firefox Version
ESR 52.0.1 (64-bit)

## geckodriver version
v0.15.0

## Platform
Windows

## Steps to reproduce -

```
<html><body>
<select id='s' multiple>
  <option selected value='one'>One</option>
  <option value='two'>Two</option>
  <option selected value='three'>Three</option>
</select>
</body></html>
```

        DesiredCapabilities capabilities = DesiredCapabilities.firefox();

        FirefoxOptions ffOptions = new FirefoxOptions();
        ffOptions.setLogLevel(Level.ALL);
        capabilities.setCapability("moz:firefoxOptions", ffOptions);

        final WebDriver driver = new FirefoxDriver(capabilities);

        try {
            driver.get("http://localhost:8080/");
            final WebElement multiSelect = driver.findElement(By.id("s"));
            final List<WebElement> options = multiSelect.findElements(By.tagName("option"));

            // options.get(0).click();
            new Actions(driver).click(options.get(0)).perform();

            System.out.println(options.get(0).isSelected());
            System.out.println(options.get(1).isSelected());
            System.out.println(options.get(2).isSelected());
        }
        finally {
            driver.quit();
        }

Expected (as IE/Chrome):
```
true
false
false

```

Actual:
```
true
false
true

```
It seems `geckodriver` doesn't trigger the click action on `<option>` elements.

Here is the [log file](https://github.com/mozilla/geckodriver/files/879803/log.txt)

**Comment by andreastt** [comment]
You can’t use the actions API to interact with `<option>` elements since they are not interactable/displayed. IE/Chrome is wrong here.

**Comment by andreastt** [comment]
To be clear, the actions API is meant as a low-level “do as I tell you to” interface to gain direct control of the mouse pointer. The _Element Click_ command is high-level and will perform extra magic to let you select a (non-interactable) `<option>` element inside `<select>`. This is supported by geckodriver and Marionette.

**Comment by asashour** [comment]
Just a hint, I see with geckodriver `0.16`,  selenium-firefox-driver `3.4.0` and Firefox `52.1.0 ESR`, this seems to be changed.

And the actual values now match with ChromeDriver:
```
true
false
false
```

However, InternetExplorerDriver `3.4.0` was changed to print:
```
true
false
true
```

**Comment by andreastt** [comment]
Is there a particular reason why you can’t click an element directly? `options.get(0).click()` is the way WebDriver recommends selecting an option.

**Comment by asashour** [comment]
Actually, my focus is to know how web driver should exactly behave, in order to implement it in `HtmlUnitDriver`, and I am using Firefox/Chrome/IE as reference implementations.

**Comment by andreastt** [comment]
Most drivers are converging around the [W3C WebDriver standard](https://w3c.github.io/webdriver/webdriver-spec.html), which explains exactly how a driver should behave. Unfortunately Selenium itself is not entirely compliant yet, but it is getting there.
