### ISSUE TITLE
Keyhandler Unsupported by your browser while running robotframework test on firefix browser using geckdriver

### ISSUE THREAD

**Issue by RajeshAchuthan** [mozilla/geckodriver#586]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
53.0
Geckdriver 0.15
Robotframework
Python 2.7.1
Selenium 3.3.0

## Platform
Windows

## Steps to reproduce -
My tests were working fine with Selenium 2.53, Robotframework (python 2.7.1) on firefox browser 46.0. I have upgraded selenium to 3.3.0, downloaded geckodriver. Test opened firefox browser and performed login succesfully. On the first page there is a input box, where had to enter string 'A B C'. While entering the string I am getting the error (popup dialog box) saying "Key handler not supported by your browser". If same string with out space in between them (ABC), works fine. Apparently space is causing the problem. Since I have changed both webdriver & browser I am not sure if its related to geckodriver. But I can't prove either way as geck driver doesnt work with older revision of firefox and firefox 2.53 doesnt work with older version of webdriver. I have tried with .14, .13 versiosn of geckodrivers

Thanks for the help in advance

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
Please provide a reproducible test case, i.e. a minimal HTML example and the required geckodriver instructions to showcase the problem.

**Comment by RajeshAchuthan** [comment]
HTML source for the element (not yet public facing site)
<input type="text" class="fastInputText" name="fastpathTextbox" id="fastpathTextbox" size="15" onclick="if (ptCheckUnsavedSessions(event)) {var leaveScript='blur();'; stayOnPageQuery(leaveScript); return false;}">
element screen shot is attached.
![capture](https://cloud.githubusercontent.com/assets/26778063/24527334/e019acf2-155e-11e7-9571-1ea2f61b90b1.PNG)

Geckodriver used is 0.15
Entering string into above contro from selenium 3.3.0 (even with 3.0) throug geckodriver, getting the popup dialog box saying key handler unsupported by your browser. I could manually enter same string. 
WIth older version of selenium (2.53) its working fine

**Comment by andreastt** [comment]
How do you expect me to reproduce this from a _screenshot_? Please don’t waste my time.

**Comment by RajeshAchuthan** [comment]
THis is not public facing web site and dont have access to the source code. I tried saving HTM source page  code, tried to save as html, when opened didnt show the controls as shown above. for your reference attached zip file of the source code. Please tell me your suggestion on what else I can get you to have this issue resolved.
This is very important for me to get resolved. Please let me know what else I can do to help you. If required I can try conducting a screen share to show you the issue. 
[issue.zip](https://github.com/mozilla/geckodriver/files/885862/issue.zip)
