### ISSUE TITLE
unable to close browser using firefox version 52.0.2

### ISSUE THREAD

**Issue by prajyot7** [mozilla/geckodriver#587]
In order to help us efficiently investigate your issue, please provide the following information:

Firefox 52.0.2

windows 7 64bit

Gecko driver 0.15

**Comment by moin-a-s** [comment]
Hi, I am also facing the same issue, I am using the following combination,
Firefox 52.0.2

windows 10 64bit

Gecko driver 0.15

On driver.quit() I am getting the exception "Unable to close firefox"

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/285.
