### ISSUE TITLE
Custom HTML Tag is not clickable

### ISSUE THREAD

**Issue by Tomek678** [mozilla/geckodriver#588]
## Firefox Version
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'tomek-Lenovo-Z51-70', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-66-generic', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/tmp/rust_mozprofile.0hmnUgmuHXB4, rotatable=false, timeouts={implicit=0, page load=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=52.0.1, platformVersion=4.4.0-66-generic, moz:processID=29242, browserName=firefox, platformName=linux}]
Session ID: abfb57fe-5cef-4728-8878-641d9a7f37cd
 
http://storage2.static.itmages.com/i/17/0330/h_1490868634_8302178_2038cce182.png

More info:
Selenium Sever Standalone 3.3.1
Geckodriver 0.15.0

I'm not able to click on custom html tag, create by Angular2. 
I don't have any errors but click action is no trigger.

**Comment by andreastt** [comment]
This is a prime example of a terrible bug report. Please don’t waste our time with non-reproducible bug reports such as this.

You should provide a minimal HTML file and geckodriver instruction set, along with your expected and actual findings, that easily lets us diagnose the problem.
