### ISSUE TITLE
Improve capabilities matching error messages

### ISSUE THREAD

**Issue by andreastt** [mozilla/geckodriver#591]
As is very clearly exemplified by https://github.com/mozilla/geckodriver/issues/585, we have to improve the error messages produced by the new-New Session negotiation. The “Unable to find a matching set of capabilities” error message that is returned if _any capability_ fails to decode or match is simply not good enough.

**Comment by andreastt** [comment]
I wonder if this should be a priority to fix before 0.16.0.

**Comment by AutomatedTester** [comment]
Duplicate of #832
