### ISSUE TITLE
Selenium executeScript returns differente value in Firefox 52.0.2 ESR and Firefox 47.0.2

### ISSUE THREAD

**Issue by lorenzofidalgo** [mozilla/geckodriver#596]
## Firefox Version
52.0.2 (64-bit)

## Platform
Linux

## Steps to reproduce
Hi! I have seen executeScript method from Selenium returns different values in Selenium 3.0.1 + Firefox 47.0.2 and in Selenium 3.3.1 + Firefox 52.0.2 ESR.
The following two java lines return "frameexists" as true in Selenium 3.0.1 + Firefox 47.0.2 and false in Selenium 3.3.1 + Firefox 52.0.2 ESR. Right value is true:

```
driver.executeScript("frameexists = window.frames[3].frames['appFrame']");
frameexists = (Boolean) driver.executeScript("return typeof(frameexists) !== 'undefined'");
```
Beisdes, if you execute all together in a single executeScript instruction it works right and returns true in both contexts (3.0.1 and 3.3.1): 

`frameexists = (Boolean) driver.executeScript("frameexists = window.frames[3].frames['appFrame']; return typeof(frameexists) !== 'undefined'");`

To test it you can follow the following steps:

1. Go to http://ec2-54-254-60-234.ap-southeast-1.compute.amazonaws.com/openbravo/security/Login_FS.html
2. Login using the following credentials:
User Name: Demo
Password: Demo
3. Click the second green icon from the top left corner (Quick Launch feature) and then enter "Session Preferences" text to go to that window. After that, click it or just press Enter key to access. (It should be also possible access to that window using "Ctrl + o" shortcut to use Quick Launch feature and then enter "Session Preferences" and Enter key).
4. Now you are in "Session Preferences" window. It is In that page where you must use the aforementioned executeScripts to check its behaviour.

**Comment by andreastt** [comment]
How are we supposed to diagnose this issue if you haven’t included the HTML document? Please provide _a minimal_ HTML document that showcases the problem.

**Comment by lorenzofidalgo** [comment]
Updated.

**Comment by lorenzofidalgo** [comment]
The "waiting for reporter feedback" label should have been removed days ago.

**Comment by andreastt** [comment]
This is not an actionable bug, sorry.

**Comment by whimboo** [comment]
So you are using two different calls to `executeScript()`. The second will run in a new sandbox, and as such doesn't have access to variables from the first call to `executeScript()`. But even with the above code you don't seem to store the result of the first call as a global variable inside the sandbox. So re-using the same sandbox won't even help.
