### ISSUE TITLE
Implement an endpoint for installing addons

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#597]
Marionette exposes an API for installing and uninstalling addons. We should add this as a custom endpoint for geckodriver, much like we currently do for e.g. switching to chrome context.

**Comment by jgraham** [comment]
@mjzffr Do you fancy having a go at this? I don't think it's too hard; just follow the approach of the other custom commands.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/211.
