### ISSUE TITLE
Webdriver compatebility issues with latest updates for FF/Gecko

### ISSUE THREAD

**Issue by gamcusa** [mozilla/geckodriver#600]
Hi,
I had Webdriver framework in place that was very stable.
After i upgraded Firefox to latest v52 and Gecko v15, i started facing issues.
Finally i was able to launch the Firefox but still have errors while running. Basicly it doesnot recognize some object due to waiting element to be clickable. 

I see the issue **wait.until** statement in the class. The error is "The method until(Function<? super WebDriver,V>) in the type FluentWait<WebDriver> is not applicable for the arguments (ExpectedCondition<WebElement>)"

still not able to do anything in Chrome. Browser is lunched and blank tab opens.

## Firefox Version
From the "About" dialog.
52.0.2 (32-bit)

## Platform
e.g. Windows/OSX/Linux
Windows 7 Ent 64 bit

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
Please provide a clear explanation of what the problem actually is along with a reproducible test case. This isn’t actionable in any way.
