### ISSUE TITLE
User utilizing GeckoDriver v0.15.0 and Selenium Java 3.3.1, unable to use driver.get("www.google.com")

### ISSUE THREAD

**Issue by nylifeinnj** [mozilla/geckodriver#602]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.2 (32-bit)

## Platform
Windows 10 Pro

## Code to reproduce -

System.setProperty("webdriver.gecko.driver", "G://HenryC- QA Automation//Selenium//geckodriver.exe");
driver = new FirefoxDriver(); 
driver.get("www.google.com");

 My browser appears, but I was not taken to www.google.com

After I downgraded to GeckoDriver v0.14.0, the functionality worked as expected.

![image](https://cloud.githubusercontent.com/assets/23008759/24673700/35d1d502-1947-11e7-889c-7d56e7f7be56.png)

**Comment by cgoldberg** [comment]
make it a real URL:  `driver.get("https://www.google.com")`

**Comment by andreastt** [comment]
You’re not saying what actually happens. What error are you getting?

**Comment by nylifeinnj** [comment]
So as I use this code to open Firefox (even with a real URL), I expected it to drive to https://www.google.com.

However after the browser window opens, the address bar briefly flashes with a blue border (indicating that the driver had touched upon it), but quickly leaves off. I have received no errors for this issue and the browser window stays blank, as depicted in my above screenshot. 

Please note that when I used GeckoDriver v0.14.0, I was driven to Google, as expected, even when using Selenium 3.3.1.

**Comment by andreastt** [comment]
I still don’t understand what the issue is. First, as @cgoldberg points out, `www.google.com` is not a valid URL: it should be given as `https://www.google.com`. Second, when you say you “received no errors”, does that mean it hangs forever?

Can you please attach a trace-level geckodriver log? See the README on how to crank up the logging verbosity.

**Comment by andreastt** [comment]
I should also point out that you must use the absolute latest version of Selenium, since earlier Selenium versions had compatibility problems with the WebDriver standard.

**Comment by nylifeinnj** [comment]
I have pointed out with my last comment that I have used a real URL when I corrected my code, even if I did not explicitly define it in my example.

The issue that I am facing is that when Selenium opens up my Firefox browser (using GeckoDriver v0.15.0), it does not drive to https://www.google.com. Rather, it stays a blank browser screen. Furthermore, I have received no errors for this issue. 

Unless Selenium Client Version 3.3.1 is not the latest Selenium version, can you let me know if I missing any code needed to enact this behavior?

**Comment by andreastt** [comment]
Could you include a trace-level log from geckodriver?

**Comment by nylifeinnj** [comment]
I am having a tough time understanding the README, as to where I put the code to change the default logs. Can you show me how to change the default logs in Java please?

**Comment by nylifeinnj** [comment]
Please disregard my last post. 

It appears that when Selenium updated to Client 3.3.1, the FirefoxOptions.java class may have been corrupted. I have separately pulled a Maven Dependency for Selenium Java 3.3.1 and found that many of the classes displayed the message "invalid LOC header (bad signature))" and could not be accessed. When I changed back to Selenium 3.3.0, I had faced no issues accessing the FirefoxOptions.java class and was able to pull all logs.

This is the TRACE log that I have pulled:

1491361852851	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"browserName":"firefox","platform":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1491361854041	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"34568309-d70d-4fcd-815e-9afce295cdbf","capabilities":{"browserName":"firefox","browserVersion":"52.0.2","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":5972,"moz:profile":"C:\\Users\\HENRY~1.CHE\\AppData\\Local\\Temp\\rust_mozprofile.AM41hpHOMK7F","moz:accessibilityChecks":false}}]
1491361854053	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1491361854053	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1491361854053	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(477) )
1491361854053	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 54, tm_min: 10, tm_hour: 3, tm_mday: 5, tm_mon: 3, tm_year: 117, tm_wday: 3, tm_yday: 94, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 53378100 })) )
1491361854053	hyper::server::response	DEBUG	write 477 bytes
1491361854053	hyper::server::response	TRACE	ending
1491361854089	hyper::buffer	TRACE	get_buf []
1491361854089	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1491361854090	hyper::buffer	TRACE	get_buf [u8; 4096][0..247]
1491361854090	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 110, 117, 108, 108, 47, 119, 105, 110, 100, 111, 119, 47, 109, 97, 120, 105, 109, 105, 122, 101, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 50, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 75, 101, 101, 112, 45, 65, 108, 105, 118, 101, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 13, 10, 13, 10, 123, 125])
1491361854090	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 247])
1491361854090	hyper::http::h1	TRACE	Request.try_parse Complete(245)
1491361854090	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491361854090	hyper::header	TRACE	raw header: "Content-Length"=[50]
1491361854090	hyper::header	TRACE	raw header: "Host"=[108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52]
1491361854090	hyper::header	TRACE	raw header: "Connection"=[75, 101, 101, 112, 45, 65, 108, 105, 118, 101]
1491361854090	hyper::header	TRACE	raw header: "User-Agent"=[65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41]
1491361854090	hyper::header	TRACE	raw header: "Accept-Encoding"=[103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101]
1491361854090	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1491361854090	hyper::http::h1	TRACE	Sized read, remaining=2
1491361854090	hyper::http::h1	TRACE	Sized read: 2
1491361854090	hyper::http::h1	TRACE	Sized read, remaining=0
1491361854097	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1491361854097	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1491361854097	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(440) )
1491361854097	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 54, tm_min: 10, tm_hour: 3, tm_mday: 5, tm_mon: 3, tm_year: 117, tm_wday: 3, tm_yday: 94, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 97494800 })) )
1491361854102	hyper::buffer	TRACE	get_buf []
1491361854102	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1491361854102	hyper::buffer	TRACE	get_buf [u8; 4096][0..266]
1491361854102	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 110, 117, 108, 108, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 51, 50, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 75, 101, 101, 112, 45, 65, 108, 105, 118, 101, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 13, 10, 13, 10, 123, 34, 117, 114, 108, 34, 58, 34, 104, 116, 116, 112, 115, 58, 47, 47, 119, 119, 119, 46, 103, 111, 111, 103, 108, 101, 46, 99, 111, 109, 34, 125])
1491361854103	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 266])
1491361854103	hyper::http::h1	TRACE	Request.try_parse Complete(234)
1491361854113	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491361854113	hyper::header	TRACE	raw header: "Content-Length"=[51, 50]
1491361854113	hyper::header	TRACE	raw header: "Host"=[108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52]
1491361854113	hyper::header	TRACE	raw header: "Connection"=[75, 101, 101, 112, 45, 65, 108, 105, 118, 101]
1491361854113	hyper::header	TRACE	raw header: "User-Agent"=[65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41]
1491361854113	hyper::header	TRACE	raw header: "Accept-Encoding"=[103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101]
1491361854113	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1491361854113	hyper::http::h1	TRACE	Sized read, remaining=32
1491361854113	hyper::http::h1	TRACE	Sized read: 32
1491361854113	hyper::http::h1	TRACE	Sized read, remaining=0
1491361854115	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1491361854115	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1491361854115	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(440) )
1491361854115	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 54, tm_min: 10, tm_hour: 3, tm_mday: 5, tm_mon: 3, tm_year: 117, tm_wday: 3, tm_yday: 94, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 115543800 })) )
1491361854115	hyper::server::response	TRACE	ending
1491361855204	hyper::buffer	TRACE	get_buf []
1491361855204	hyper::buffer	TRACE	read_into_buf buf[0..4096]
1491361855204	hyper::buffer	TRACE	get_buf [u8; 4096][0..270]
1491361855204	hyper::http::h1	TRACE	try_parse([80, 79, 83, 84, 32, 47, 115, 101, 115, 115, 105, 111, 110, 47, 110, 117, 108, 108, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116, 104, 58, 32, 51, 54, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 75, 101, 101, 112, 45, 65, 108, 105, 118, 101, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101, 13, 10, 13, 10, 123, 34, 117, 114, 108, 34, 58, 34, 104, 116, 116, 112, 115, 58, 47, 47, 117, 97, 116, 46, 102, 117, 110, 100, 97, 116, 105, 111, 110, 46, 99, 111, 109, 47, 34, 125])
1491361855204	hyper::http::h1	TRACE	Request.try_parse([Header; 100], [u8; 270])
1491361855204	hyper::http::h1	TRACE	Request.try_parse Complete(234)
1491361855204	hyper::header	TRACE	raw header: "Content-Type"=[97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 32, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491361855204	hyper::header	TRACE	raw header: "Content-Length"=[51, 54]
1491361855204	hyper::header	TRACE	raw header: "Host"=[108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 57, 51, 54, 52]
1491361855204	hyper::header	TRACE	raw header: "Connection"=[75, 101, 101, 112, 45, 65, 108, 105, 118, 101]
1491361855204	hyper::header	TRACE	raw header: "User-Agent"=[65, 112, 97, 99, 104, 101, 45, 72, 116, 116, 112, 67, 108, 105, 101, 110, 116, 47, 52, 46, 53, 46, 50, 32, 40, 74, 97, 118, 97, 47, 49, 46, 56, 46, 48, 95, 49, 50, 49, 41]
1491361855204	hyper::header	TRACE	raw header: "Accept-Encoding"=[103, 122, 105, 112, 44, 100, 101, 102, 108, 97, 116, 101]
1491361855204	hyper::header	TRACE	Headers.set( "Connection", Connection([Close]) )
1491361855204	hyper::http::h1	TRACE	Sized read, remaining=36
1491361855204	hyper::http::h1	TRACE	Sized read: 32
1491361855204	hyper::http::h1	TRACE	Sized read, remaining=4
1491361855204	hyper::http::h1	TRACE	Sized read: 4
1491361855204	hyper::http::h1	TRACE	Sized read, remaining=0
1491361855206	hyper::header	TRACE	Headers.set( "Content-Type", ContentType(Mime(Application, Json, [(Charset, Utf8)])) )
1491361855206	hyper::header	TRACE	Headers.set( "Cache-Control", CacheControl([NoCache]) )
1491361855206	hyper::header	TRACE	Headers.set( "Content-Length", ContentLength(440) )
1491361855206	hyper::server::response	DEBUG	writing head: Http11 NotFound
1491361855206	hyper::header	TRACE	Headers.set( "Date", Date(HttpDate(Tm { tm_sec: 55, tm_min: 10, tm_hour: 3, tm_mday: 5, tm_mon: 3, tm_year: 117, tm_wday: 3, tm_yday: 94, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 206008400 })) )

Please let me know any other information you would need. Thanks!

**Comment by maurizio-lattuada** [comment]
Hi, FYI this issue could be due to Selenium v3.3.1, look at [this issue](https://github.com/SeleniumHQ/selenium/issues/3711)

I downgraded selenium-java 3.3.1 to 3.3.0 and everything started to work fine

**Comment by andreastt** [comment]
I doubt that; the reporter is able to start a session.

**Comment by maurizio-lattuada** [comment]
Agree, but I had the same behaviour: Firefox was launched, but blank page, no web pages loaded.
Then, by putting an appropriate try catch when creating a new instance of FirefoxDriver (initialized with a specific profile), I caught an exception reporting exactly the same error stated in the Selenium issue I linked in my previous message.

**Comment by nylifeinnj** [comment]
Interesting. It appears that I was not able to get it work either with Selenium v3.3.0 and Geckdriver v0.15.0. And since I am able to get Selenium v3.3.1 and Geckodriver v0.14.8 to work, I am staying with this setup until these issues with the latest Geckodriver are definitively resolved.

**Comment by andreastt** [comment]
I’m not really able to deduce anything of value from https://github.com/mozilla/geckodriver/issues/602#issuecomment-291740618, other than the fact that the geckodriver server never receives any further commands after the session is started. This could indicate a language binding problem.

I also see you’ve tested using Firefox 52.0.2, which doesn’t have a lot of the more recent updates to Marionette. Could you try with [Firefox Nightly](https://nightly.mozilla.org/)?

**Comment by nylifeinnj** [comment]
I got Selenium Java v3.3.1 and GeckoDriver v0.15.0 to work with FF 52.0.2 on my home computer, which runs on Windows 7. However when I tried again on my work computer which runs on Windows 10, the browser again drove nowhere. 

On a side note, Selenium Java v3.3.1 also appears very unstable on both Windows 7 and Windows 10, sometimes causing my code to not compile unless I restart the computer and clean up the builds.

**Comment by andreastt** [comment]
So the log included above doesn’t appear to be complete, and I don’t really have any better guesses than that this is an issue with the language binding you’re using.

If you’re able to debug this and find out what the problem is, I’m happy to re-open this. But currently, there’s nothing actionable I can do here without a more reproducible bug report.

**Comment by nylifeinnj** [comment]
Hi Andreas,

I have actually corrected my Firefox Version to the 64-bit version and reran with Geckodriver v0.15.0 on Windows 10 (64-bit computer). The issue where the URL is not getting entered into the address bar is still persisting. However, I am getting a new error in the log:

[GPU 6404] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346

Please advise.

**Comment by andreastt** [comment]
@nylifeinnj The error being printed in the output is nothing to worry about.
