### ISSUE TITLE
What's the default profile?

### ISSUE THREAD

**Issue by gsnedders** [mozilla/geckodriver#605]
The README.md lists a bunch of Firefox options as a capability including profile (a path to a ZIP'd profile), but it doesn't state what the default profile is. Is it the user's default profile? Is it a new empty profile? Does it use a new custom profile (if so, how does it differ from the defaults)?

**Comment by andreastt** [comment]
The default is a new, temporary profile with some needed automation preferences set. The path to it is returned in the capabilities as `moz:profile`.
