### ISSUE TITLE
Running unit tests and getting

### ISSUE THREAD

**Issue by MikeGitIt** [mozilla/geckodriver#608]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox Developer Edition 54.0a2
## Platform
Windows
## Steps to reproduce -
This is being run from the unit test but all it is testing is whether or not an element is displayed and then entering a string of text, the username, into the field (How hard is that?). The chrome tests run just fine on the same page (hmmmmm):
 - [ ] System.InvalidOperationException : Expected [object Undefined] undefined to be a string (IndexOutOfBounds)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
   at DPEXSelenium.Firefox_Tests.DpexLoginFirefox.ProcessLogin(String username, String password) in C:\MyProjects\Sandbox\DPEXSelenium\DPEXSelenium\Firefox Tests\DPEXLoginFirefox.cs:line 90
   at DPEX.Specs.DPEXLoginFirefoxSteps.GivenThePageHasLoadedInFirefox() in C:\MyProjects\Sandbox\DPEXSelenium\DPEX.Specs\Steps\DPEXLoginFirefoxSteps.cs:line 29
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at DPEX.Specs.Features.DPEXLoginFirefoxFeature.ScenarioCleanup()
   at DPEX.Specs.Features.DPEXLoginFirefoxFeature.ICanLoginToThePortalSuccessfully() in C:\MyProjects\Sandbox\DPEXSelenium\DPEX.Specs\Features\DPEXLoginFirefox.feature:line 10

Given I have an open Firefox browser
-> done: DPEXLoginFirefoxSteps.GivenIHaveAnOpenBrowser() (8.8s)
And The page has loaded in Firefox
-> error: Expected [object Undefined] undefined to be a string (IndexOutOfBounds)
When I login to the site in Firefox
-> skipped because of previous errors
Then the result in FireFox should be true
-> skipped because of previous errors

 - [ ] HTML
`<html webdriver="true" lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
</head>
<body onpageshow="setPath()" onclick="clicked=true;" onunload="CheckBrowser()">

    <div id="portalOneContainer"></div>

    <div id="wrapper" class="container">
        <input id="ReturnPath" name="ReturnPath" value="/DEV_DAD_Renderer" type="hidden">
        <div id="renderbody" class="container">
<div class="TitleLabel1">
    <br>
    <b>Log In - Enter your user name and password below.</b><br>
</div><br>
<script src="Dovetail%20Public%20Exchange_files/jquery_002.js"></script>
<script src="Dovetail%20Public%20Exchange_files/jquery.htm"></script>

    <div class="box1">
        <div style="font-size:100%;">

<form action="/Dev_DAD_Renderer/Account/Login" method="post">                <fieldset class="content1">
                    <br>
                    <ol class="ol">
                        <li class="li">
                            <label class="Label" for="UserName" style="font-weight: bold;">User name</label>
                            <input class="textbox" data-val="true" data-val-required="The User name field is required." id="UserName" name="UserName" type="text">
                            <span class="field-validation-valid" data-valmsg-for="UserName" data-valmsg-replace="true"></span>
                        </li>
                        <br>
                        <li class="li">
                            
                            <label>Password </label>&nbsp;
                            <input class="textbox" data-val="true" data-val-required="The Password field is required." id="pwdBox" name="Password" type="password">
                            <span class="field-validation-valid" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                        </li>        
                    </ol>
                </fieldset>
 <div class="row">
                    <div class="col-xs-4">
                        <input value="Log in" id="submitButton" class="submit1" type="submit">
                    </div>
                  </div>
                <br><br>
</form>        
</div>
 </div>
    </div>
    </div>
    <br><br>
</body></html>`

**Comment by andreastt** [comment]
I can’t parse what this issue is about. Sorry.

**Comment by alvladimirov** [comment]
Having same problem with Firefox v53. Downgrading back to v52 solved the problem.
Gecko Driver version: v0.15.0

CODE that triggers this - a SendKeys() call:
```
[FindsBy(How = How.Id, Using = "Eligibility_DOBDay")] 
private IWebElement Eligibility_DoB_Day;
<....>
Eligibility_DoB_Day.SendKeys(p.ToString());
```

ELEMENT I'm trying to interact with:
`<input class="xxshort numeric_dayofmonth" data-val="true" data-val-number="The field DOBDay must be a number." id="Eligibility_DOBDay" maxlength="2" name="Eligibility.DOBDay" pattern="[0-9]*" value="" autocomplete="off" type="text">`



EXCEPTION:
Execute
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Expected [object Undefined] undefined to be a string (IndexOutOfBounds)
HResult: -2146233079
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
   --- End of inner exception stack trace ---

**Comment by andreastt** [comment]
If this is about send keys not working (I can’t really guess without a trace-level log!), then it is broken with the latest Firefox _Nightly_ and geckodriver 0.15.0. Upgrading to 0.16.0 when it comes out should solve any incompatibilities between Nightly and geckodriver.

I don’t know what the issue is about Firefox 53 though.

**Comment by MatejQ** [comment]
Just got the same issue after freshly upgrading Firefox to version 53. On version 52, tests were running fine. The error seems to be triggered by SendKeys() call in Selenium, which is necessary to pass the login page.

**Comment by kaspmode** [comment]
Me to same issue SendKeys() generates error, besides go back to the older version does anybody has a solution?  :(

**Comment by andreastt** [comment]
The send keys problems have already  been reported in https://github.com/mozilla/geckodriver/issues/659, and been fixed.

**Comment by whimboo** [comment]
Well, we should note that geckodriver 0.16 would be required which hasn't been released yet.

**Comment by whimboo** [comment]
Can someone please verify with https://github.com/mozilla/geckodriver/releases/tag/v0.16.1? Thanks.

**Comment by alvladimirov** [comment]
Works perfectly fine for me. 
GeckoDriver : 0.16.1 (32bit)
Selenium: 3.4.0
Firefox: v53

I checked with exactly the same code that used to fail on SendKeys ().
Thank you for the prompt fix!

**Comment by adeelilyas** [comment]
Just update GeckoDriver to the latest with Firefox v53 and it will work.  Download the one you required from [here](https://github.com/mozilla/geckodriver/releases).
