### ISSUE TITLE
Switch to window doesn't select top-level browsing context

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#610]
## Firefox Version
55.0a1 (2017-04-06) (64-bit)
geckodriver 0.15

## Platform
Windows 7

## Steps to reproduce
Selenium Java test WindowSwitchingTest.testShouldFocusOnTheTopMostFrameAfterSwitchingToAWindow, the main part is:
```
    Set<String> currentWindowHandles = driver.getWindowHandles();
    String mainWindow = driver.getWindowHandle();

    driver.findElement(By.id("a-link-that-opens-a-new-window")).click();
    wait.until(newWindowIsOpened(currentWindowHandles));

    // switch to a non-top-level browsing context
    driver.switchTo().frame("myframe");

    driver.switchTo().window("newWindow");
    driver.switchTo().window(mainWindow);
    
    // check that we're back to top-level browsing context
    driver.findElement(By.name("myframe")); // fail
```

**Comment by whimboo** [comment]
@andreastt, did you already file a bug for that issue or only labeled it as `marionette`? I'm not able to find an existing bug report. So if I should file one please let me know.

**Comment by andreastt** [comment]
I haven’t investigated this issue yet, but it’s bound to be Marionette related.

**Comment by whimboo** [comment]
It's indeed a bug in Marionette. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1364434 to track it.

**Comment by udaybng** [comment]
Any update on this bug? am facing same issue

**Comment by whimboo** [comment]
This will be fixed in the next Firefox Nightly build today.
