### ISSUE TITLE
Clicking disabled element returns error

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#615]
## Firefox Version
55.0a1 (2017-04-06) (64-bit)
geckodriver 0.15

## Platform
Windows 7

## Steps to reproduce
According to the standard, click should not take into account state of the element (enabled/disabled).

Actual behavior is:
```
1491589318392	webdriver::server	DEBUG	Got request POST AbsolutePath("/session/c8b30889-9960-4f35-82c1-50e882b13bac/element/b141bbe8-3f57-4ba2-bb8d-91f9ba5ad256/click")
1491589318393	Marionette	TRACE	0 -> [0,17,"clickElement",{"id":"b141bbe8-3f57-4ba2-bb8d-91f9ba5ad256"}]
1491589318392	webdriver::command	DEBUG	Got request body {"id":"b141bbe8-3f57-4ba2-bb8d-91f9ba5ad256"}
1491589318392	geckodriver::marionette	DEBUG	→ 67:[0,17,"clickElement",{"id":"b141bbe8-3f57-4ba2-bb8d-91f9ba5ad256"}]
1491589318402	Marionette	TRACE	0 <- [1,17,{"error":"invalid element state","message":"Element is not enabled","stacktrace":"WebDriverError@chrome://marionette/content/error.js:211:5\nInvalidElementStateError@chrome://marionette/content/error.js:308:5\nseleniumClickElement@chrome://marionette/content/interaction.js:208:11\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\ndispatch/<@chrome://marionette/content/listener.js:363:15\n"},null]
1491589318402	geckodriver::marionette	DEBUG	← [1,17,{"error":"invalid element state","message":"Element is not enabled","stacktrace":"WebDriverError@chrome://marionette/content/error.js:211:5\nInvalidElementStateError@chrome://marionette/content/error.js:308:5\nseleniumClickElement@chrome://marionette/content/interaction.js:208:11\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:389:16\nTaskImpl_run@resource://gre/modules/Task.jsm:327:15\nTaskImpl@resource://gre/modules/Task.jsm:277:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\ndispatch/<@chrome://marionette/content/listener.js:363:15\n"},null]
1491589318403	webdriver::server	DEBUG	Returning status BadRequest
1491589318403	webdriver::server	DEBUG	Returning body {"value":{"error":"invalid element state","message":"Element is not enabled","stacktrace":"stack backtrace:\n   0:           0x61f07f - <no info>\n   1:           0x61fe59 - <no info>\n   2:           0x43b0b5 - <no info>\n   3:           0x420313 - <no info>\n   4:           0x408307 - <no info>\n   5:           0x6750f9 - <no info>\n   6:           0x416877 - <no info>\n   7:           0x66ed53 - <no info>\n   8:         0x76da59cd - BaseThreadInitThunk"}}
```

**Comment by andreastt** [comment]
Examining the spec closer], I do recognise that [it doesn’t have a step regarding checking if the element is disabled or not](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-click).

Is this something we want to put in, @shs96c?

**Comment by shs96c** [comment]
Reading the code in the old Firefox driver (which is essentially "canonical" for Selenium usage), there's a visibility check, before (ultimately) descending to the Atoms' `bot.action.click` function which doesn't perform any check to see if the element is enabled or disabled.

In other words, it's quirky to click on an element that's disabled, but a user could do it, and so it's allowed. I've double-checked and the chrome implementation does the same as the Selenium firefox-driver.

**Comment by andreastt** [comment]
Thanks for checking, @shs96c! That’s fair enough. I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1355546 to fix this.

**Comment by shs96c** [comment]
I've added a test in seleniumhq/selenium@6c7b4b4741419dfb231c7541bb2dbd3fe32d3291

**Comment by barancev** [comment]
There are many tests for this and similar cases in ElementSelectingTest

**Comment by andreastt** [comment]
I had a look into this, and Marionette does not check if the element is enabled when using the WebDriver-conforming Element Click command implementation. We have https://bugzilla.mozilla.org/show_bug.cgi?id=1321516 to enable this by default, but it is currently hidden by the `{specificationLevel: 1}` capability, due to the fact that WebDriver’s click behaviour is subtly different to that of Selenium.

**Comment by shs96c** [comment]
The two click methods (w3c and selenium) should be effectively identical, unless there's some subtlety around visibility. Where do they differ? We should tighten things to bring the two into congruence.

**Comment by andreastt** [comment]
Marionette’s default Element Click implementation checks if the element is enabled, whereas our opt-in WebDriver conforming implementation does not.

**Comment by whimboo** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1321516 which enabled the WebDriver conformant interactability checks by default in Firefox 58.
