### ISSUE TITLE
geckodriver lost sessionId when we try to navigate

### ISSUE THREAD

**Issue by uskovboris** [mozilla/geckodriver#616]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.2 (either x86/x64)
geckodriver v0.15.0

## Platform
Windows on Hyper-V

## Steps to reproduce -

Remove firefox
Download latest firefox version
Install one

(Reporduces even if we removed 52.0.2 and then install 52.0.2 again)

Execute code:

            var firefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe"; // of Program FIles (X86) 

            var profile = new FirefoxProfile();
            
            var proxy = new Proxy();
            proxy.IsAutoDetect = true;
            profile.SetProxyPreferences(proxy); //We use a proxy server

            var options = new FirefoxOptions();
            options.Profile = profile;

            options.LogLevel = FirefoxDriverLogLevel.Trace;
            options.BrowserExecutableLocation = firefoxBinaryPath;

            var service = FirefoxDriverService.CreateDefaultService();
            service.FirefoxBinaryPath = firefoxBinaryPath;
            var Driver = new FirefoxDriver(service, options, TimeSpan.FromMinutes(3));

            Driver.Navigate().GoToUrl("https://wwww.yandex.ru"); //Actual, any url

**IT SEEMS THAT geckodriver lost the sessionId somewhere**
-------------------------------------------------------------------------------------

Trace:
1491595276279   geckodriver     INFO    Listening on 127.0.0.1:1365
1491595277388   mozprofile::profile     INFO    Using profile path C:\Users\AUTO
TE~1\AppData\Local\Temp\rust_mozprofile.194yRTp2zmbz
1491595277466   geckodriver::marionette INFO    Starting browser C:\Program File
s\Mozilla Firefox\firefox.exe with args []
1491595277482   geckodriver::marionette INFO    Connecting to Marionette on loca
lhost:1369
1491595279545   geckodriver::marionette DEBUG   TCP connection established
1491595280966   geckodriver::marionette DEBUG   < {"applicationType":"gecko","ma
rionetteProtocol":3}
1491595280966   geckodriver::marionette DEBUG   > 176:[0,1,"newSession",{"capabi
lities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"platf
orm":"ANY","version":""},"requiredCapabilities":{}},"sessionId":null}]
1491595283377   geckodriver::marionette DEBUG   < [1,1,null,{"sessionId":"5d3c84
39-f3af-45ae-97d1-cb526e88e734","capabilities":{"browserName":"firefox","browser
Version":"52.0.2","platformName":"windows_nt","platformVersion":"6.1","pageLoadS
trategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page loa
d":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processI
D":5600,"moz:profile":"C:\\Users\\AUTOTE~1\\AppData\\Local\\Temp\\rust_mozprofil
e.194yRTp2zmbz","moz:accessibilityChecks":false}}]
1491595283381   webdriver::server       DEBUG   Returning status Ok
1491595283382   webdriver::server       DEBUG   Returning body {"value": {"sessi
onId":"5d3c8439-f3af-45ae-97d1-cb526e88e734","value":{"acceptInsecureCerts":fals
e,"browserName":"firefox","browserVersion":"52.0.2","moz:accessibilityChecks":fa
lse,"moz:processID":5600,"moz:profile":"C:\\Users\\AUTOTE~1\\AppData\\Local\\Tem
p\\rust_mozprofile.194yRTp2zmbz","pageLoadStrategy":"normal","platformName":"win
dows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeo
uts":{"implicit":0,"page load":300000,"script":30000}}}}
1491595283386   hyper::header   TRACE   Headers.set( "Content-Type", ContentType
(Mime(Application, Json, [(Charset, Utf8)])) )
1491595283386   hyper::header   TRACE   Headers.set( "Cache-Control", CacheContr
ol([NoCache]) )
1491595283390   hyper::header   TRACE   Headers.set( "Content-Length", ContentLe
ngth(473) )
1491595283390   hyper::server::response DEBUG   writing head: Http11 Ok
1491595283395   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm {
tm_sec: 23, tm_min: 1, tm_hour: 20, tm_mday: 7, tm_mon: 3, tm_year: 117, tm_wday
: 5, tm_yday: 96, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 395123500 })) )
1491595283400   hyper::server::response DEBUG   headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 473
, Date: Fri, 07 Apr 2017 20:01:23 GMT
, }]
1491595283400   hyper::server::response DEBUG   write 473 bytes
1491595283400   hyper::server::response TRACE   ending
1491595283400   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:1368
1491595283400   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:136
8
1491595339189   hyper::server   DEBUG   Incoming stream
1491595339189   hyper::buffer   TRACE   get_buf []
1491595339189   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1491595339189   hyper::buffer   TRACE   get_buf [u8; 4096][0..161]
1491595339189   hyper::http::h1 TRACE   try_parse([80, 79, 83, 84, 32, 47, 115,
101, 115, 115, 105, 111, 110, 47, 47, 116, 105, 109, 101, 111, 117, 116, 115, 32
, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97,
 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32,
 105, 109, 97, 103, 101, 47, 112, 110, 103, 13, 10, 67, 111, 110, 116, 101, 110,
 116, 45, 84, 121, 112, 101, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 1
11, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 117, 1
16, 102, 45, 56, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104,
111, 115, 116, 58, 49, 51, 54, 53, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45,
 76, 101, 110, 103, 116, 104, 58, 32, 51, 50, 13, 10, 13, 10])
1491595339189   hyper::http::h1 TRACE   Request.try_parse([Header; 100], [u8; 16
1])
1491595339189   hyper::http::h1 TRACE   Request.try_parse Complete(161)
1491595339189   hyper::header   TRACE   raw header: "Accept"=[97, 112, 112, 108,
 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32, 105, 109, 97,
103, 101, 47, 112, 110, 103]
1491595339205   hyper::header   TRACE   raw header: "Content-Type"=[97, 112, 112
, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97,
 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491595339205   hyper::header   TRACE   raw header: "Host"=[108, 111, 99, 97, 10
8, 104, 111, 115, 116, 58, 49, 51, 54, 53]
1491595339205   hyper::header   TRACE   raw header: "Content-Length"=[51, 50]
1491595339205   hyper::server::request  DEBUG   Request Line: Post AbsolutePath(
"/session//timeouts") Http11
1491595339205   hyper::server::request  DEBUG   Headers { Accept: application/js
on, image/png
, Content-Type: application/json;charset=utf-8
, Host: localhost:1365
, Content-Length: 32
, }
1491595339205   hyper::header   TRACE   Headers.set( "Connection", Connection([C
lose]) )
1491595339205   hyper::http::h1 TRACE   Sized read, remaining=32
1491595339205   hyper::http::h1 TRACE   Sized read: 32
1491595339205   hyper::http::h1 TRACE   Sized read, remaining=0
1491595339205   webdriver::server       DEBUG   Got request POST AbsolutePath("/
session//timeouts")
1491595339221   webdriver::server       DEBUG   Returning status NotFound
1491595339221   webdriver::server       DEBUG   Returning body {"value":{"error"
:"unknown command","message":"POST /session//timeouts did not match a known comm
and","stacktrace":"stack backtrace:\n   0:   0x5ecb16 - <no info>\n   1:   0x428
f24 - <no info>\n   2:   0x41e9ff - <no info>\n   3:   0x406151 - <no info>\n
4:   0x63c066 - <no info>\n   5:   0x410ad4 - <no info>\n   6:   0x637241 - <no
info>\n   7: 0x752cef1c - BaseThreadInitThunk\n   8: 0x770a367a - RtlInitializeE
xceptionChain"}}
1491595339221   hyper::header   TRACE   Headers.set( "Content-Type", ContentType
(Mime(Application, Json, [(Charset, Utf8)])) )
1491595339221   hyper::header   TRACE   Headers.set( "Cache-Control", CacheContr
ol([NoCache]) )
1491595339221   hyper::header   TRACE   Headers.set( "Content-Length", ContentLe
ngth(433) )
1491595339236   hyper::server::response DEBUG   writing head: Http11 NotFound
1491595339236   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm {
tm_sec: 19, tm_min: 2, tm_hour: 20, tm_mday: 7, tm_mon: 3, tm_year: 117, tm_wday
: 5, tm_yday: 96, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 236836900 })) )
1491595339236   hyper::server::response DEBUG   headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 433
, Date: Fri, 07 Apr 2017 20:02:19 GMT
, }]
1491595339236   hyper::server::response DEBUG   write 433 bytes
1491595339236   hyper::server::response TRACE   ending
1491595339236   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:1413
1491595339236   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:141
3
1491595358190   hyper::server   DEBUG   Incoming stream
1491595358190   hyper::buffer   TRACE   get_buf []
1491595358190   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1491595358190   hyper::buffer   TRACE   get_buf [u8; 4096][0..188]
1491595358190   hyper::http::h1 TRACE   try_parse([80, 79, 83, 84, 32, 47, 115,
101, 115, 115, 105, 111, 110, 47, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49,
 46, 49, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97, 112, 112, 108, 105, 99,
97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32, 105, 109, 97, 103, 101,
47, 112, 110, 103, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 1
01, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 11
1, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10,
72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 51
, 54, 53, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116,
104, 58, 32, 51, 50, 13, 10, 13, 10, 123, 34, 117, 114, 108, 34, 58, 34, 104, 11
6, 116, 112, 115, 58, 47, 47, 119, 119, 119, 119, 46, 121, 97, 110, 100, 101, 12
0, 46, 114, 117, 34, 125])
1491595358190   hyper::http::h1 TRACE   Request.try_parse([Header; 100], [u8; 18
8])
1491595358206   hyper::http::h1 TRACE   Request.try_parse Complete(156)
1491595358206   hyper::header   TRACE   raw header: "Accept"=[97, 112, 112, 108,
 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32, 105, 109, 97,
103, 101, 47, 112, 110, 103]
1491595358206   hyper::header   TRACE   raw header: "Content-Type"=[97, 112, 112
, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97,
 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491595358206   hyper::header   TRACE   raw header: "Host"=[108, 111, 99, 97, 10
8, 104, 111, 115, 116, 58, 49, 51, 54, 53]
1491595358206   hyper::header   TRACE   raw header: "Content-Length"=[51, 50]
1491595358206   hyper::server::request  DEBUG   Request Line: Post AbsolutePath(
"/session//url") Http11
1491595358206   hyper::server::request  DEBUG   Headers { Accept: application/js
on, image/png
, Content-Type: application/json;charset=utf-8
, Host: localhost:1365
, Content-Length: 32
, }
1491595358206   hyper::header   TRACE   Headers.set( "Connection", Connection([C
lose]) )
1491595358206   hyper::http::h1 TRACE   Sized read, remaining=32
1491595358206   hyper::http::h1 TRACE   Sized read: 32
1491595358206   hyper::http::h1 TRACE   Sized read, remaining=0
1491595358206   webdriver::server       DEBUG   Got request POST AbsolutePath("/
session//url")
1491595358206   webdriver::server       DEBUG   Returning status NotFound
1491595358222   webdriver::server       DEBUG   Returning body {"value":{"error"
:"unknown command","message":"POST /session//url did not match a known command",
"stacktrace":"stack backtrace:\n   0:   0x5ecb16 - <no info>\n   1:   0x428f24 -
 <no info>\n   2:   0x41e9ff - <no info>\n   3:   0x406151 - <no info>\n   4:
0x63c066 - <no info>\n   5:   0x410ad4 - <no info>\n   6:   0x637241 - <no info>
\n   7: 0x752cef1c - BaseThreadInitThunk\n   8: 0x770a367a - RtlInitializeExcept
ionChain"}}
1491595358222   hyper::header   TRACE   Headers.set( "Content-Type", ContentType
(Mime(Application, Json, [(Charset, Utf8)])) )
1491595358222   hyper::header   TRACE   Headers.set( "Cache-Control", CacheContr
ol([NoCache]) )
1491595358222   hyper::header   TRACE   Headers.set( "Content-Length", ContentLe
ngth(428) )
1491595358222   hyper::server::response DEBUG   writing head: Http11 NotFound
1491595358222   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm {
tm_sec: 38, tm_min: 2, tm_hour: 20, tm_mday: 7, tm_mon: 3, tm_year: 117, tm_wday
: 5, tm_yday: 96, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 222145500 })) )
1491595358222   hyper::server::response DEBUG   headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 428
, Date: Fri, 07 Apr 2017 20:02:38 GMT
, }]
1491595358222   hyper::server::response DEBUG   write 428 bytes
1491595358222   hyper::server::response TRACE   ending
1491595358222   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:1419
1491595358222   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:141
9
1491595403047   hyper::server   DEBUG   Incoming stream
1491595403047   hyper::buffer   TRACE   get_buf []
1491595403047   hyper::buffer   TRACE   read_into_buf buf[0..4096]
1491595403047   hyper::buffer   TRACE   get_buf [u8; 4096][0..188]
1491595403047   hyper::http::h1 TRACE   try_parse([80, 79, 83, 84, 32, 47, 115,
101, 115, 115, 105, 111, 110, 47, 47, 117, 114, 108, 32, 72, 84, 84, 80, 47, 49,
 46, 49, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 97, 112, 112, 108, 105, 99,
97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32, 105, 109, 97, 103, 101,
47, 112, 110, 103, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 84, 121, 112, 1
01, 58, 32, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 11
1, 110, 59, 99, 104, 97, 114, 115, 101, 116, 61, 117, 116, 102, 45, 56, 13, 10,
72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 49, 51
, 54, 53, 13, 10, 67, 111, 110, 116, 101, 110, 116, 45, 76, 101, 110, 103, 116,
104, 58, 32, 51, 50, 13, 10, 13, 10, 123, 34, 117, 114, 108, 34, 58, 34, 104, 11
6, 116, 112, 115, 58, 47, 47, 119, 119, 119, 119, 46, 121, 97, 110, 100, 101, 12
0, 46, 114, 117, 34, 125])
1491595403047   hyper::http::h1 TRACE   Request.try_parse([Header; 100], [u8; 18
8])
1491595403047   hyper::http::h1 TRACE   Request.try_parse Complete(156)
1491595403047   hyper::header   TRACE   raw header: "Accept"=[97, 112, 112, 108,
 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 44, 32, 105, 109, 97,
103, 101, 47, 112, 110, 103]
1491595403063   hyper::header   TRACE   raw header: "Content-Type"=[97, 112, 112
, 108, 105, 99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 59, 99, 104, 97,
 114, 115, 101, 116, 61, 117, 116, 102, 45, 56]
1491595403063   hyper::header   TRACE   raw header: "Host"=[108, 111, 99, 97, 10
8, 104, 111, 115, 116, 58, 49, 51, 54, 53]
1491595403063   hyper::header   TRACE   raw header: "Content-Length"=[51, 50]
1491595403063   hyper::server::request  DEBUG   Request Line: Post AbsolutePath(
"/session//url") Http11
1491595403063   hyper::server::request  DEBUG   Headers { Accept: application/js
on, image/png
, Content-Type: application/json;charset=utf-8
, Host: localhost:1365
, Content-Length: 32
, }
1491595403063   hyper::header   TRACE   Headers.set( "Connection", Connection([C
lose]) )
1491595403063   hyper::http::h1 TRACE   Sized read, remaining=32
1491595403063   hyper::http::h1 TRACE   Sized read: 32
1491595403063   hyper::http::h1 TRACE   Sized read, remaining=0
1491595403063   webdriver::server       DEBUG   Got request POST AbsolutePath("/
session//url")
1491595403063   webdriver::server       DEBUG   Returning status NotFound
1491595403063   webdriver::server       DEBUG   Returning body {"value":{"error"
:"unknown command","message":"POST /session//url did not match a known command",
"stacktrace":"stack backtrace:\n   0:   0x5ecb16 - <no info>\n   1:   0x428f24 -
 <no info>\n   2:   0x41e9ff - <no info>\n   3:   0x406151 - <no info>\n   4:
0x63c066 - <no info>\n   5:   0x410ad4 - <no info>\n   6:   0x637241 - <no info>
\n   7: 0x752cef1c - BaseThreadInitThunk\n   8: 0x770a367a - RtlInitializeExcept
ionChain"}}
1491595403063   hyper::header   TRACE   Headers.set( "Content-Type", ContentType
(Mime(Application, Json, [(Charset, Utf8)])) )
1491595403063   hyper::header   TRACE   Headers.set( "Cache-Control", CacheContr
ol([NoCache]) )
1491595403063   hyper::header   TRACE   Headers.set( "Content-Length", ContentLe
ngth(428) )
1491595403079   hyper::server::response DEBUG   writing head: Http11 NotFound
1491595403079   hyper::header   TRACE   Headers.set( "Date", Date(HttpDate(Tm {
tm_sec: 23, tm_min: 3, tm_hour: 20, tm_mday: 7, tm_mon: 3, tm_year: 117, tm_wday
: 5, tm_yday: 96, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 79051900 })) )
1491595403079   hyper::server::response DEBUG   headers [
Headers { Connection: close
, Content-Type: application/json; charset=utf-8
, Cache-Control: no-cache
, Content-Length: 428
, Date: Fri, 07 Apr 2017 20:03:23 GMT
, }]
1491595403079   hyper::server::response DEBUG   write 428 bytes
1491595403079   hyper::server::response TRACE   ending
1491595403079   hyper::server   DEBUG   keep_alive = false for 127.0.0.1:1425
1491595403094   hyper::server   DEBUG   keep_alive loop ending for 127.0.0.1:142
5

**Comment by andreastt** [comment]
It is your client binding that is loosing track of the session ID. You can see that it makes requests of the style `/session//url` to geckodriver, which would obviously fail.

I suspect that this is fallout from some recent change we made to make geckodriver more WebDriver conforming. Can you upgrade to Selenium 3.3.1 and report back if that doesn’t resolve your issue?

**Comment by uskovboris** [comment]
According to http://www.seleniumhq.org/download/ the version 3.3.1 available only for Java, but we use Microsoft .NET. 
According to the Change Log:

* Better support for geckodriver v0.15.0. Notably, exceptions returned
  from the remote end are now unwrapped properly.

Is it possible to make .NET Selenium edition be compatible with geckodriver 0.15.1?

**Comment by uskovboris** [comment]
We use the latest .NET Selenium version which is available from  http://www.seleniumhq.org/download/ 
C#	3.3.0	2017-03-07

**Comment by andreastt** [comment]
I don’t understand why are the .NET bindings aren’t compatible.
