### ISSUE TITLE
Add support for specifying command line arguments for the binary

### ISSUE THREAD

**Issue by davehunt** [mozilla/geckodriver#62]
We should allow additional command line arguments to be passed to the browser instance when it's launched. An example would be to pass `-foreground` to force the browser to steal focus, which may be required for some tests.

**Comment by andreastt** [comment]
Marionette uses synthetic input which should not require the browser to be in focus. There is also a note under [_Command Contexts_](http://w3c.github.io/webdriver/webdriver-spec.html#command-contexts) in the specification that states

> In accordance with the focus section of the [HTML] specification, commands are unaffected by whether the operating system window has focus or not.

**Comment by jgraham** [comment]
I'm pretty sure that there are other ways focus can be exposed on the platform. It doesn't seem like an unreasonable request, irrespective of whether `-foreground` is a valid use case.

**Comment by andreastt** [comment]
Under what circumstances does the browser _not_ take focus when it is launched? I guess I don’t fully understand what `-foreground` does.

**Comment by jgraham** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=746243#c87 - it seems to be OSX only

**Comment by andreastt** [comment]
Right, then it makes sense to ensure it gets focus on Mac OS too. However, note that WebDriver doesn’t guarantee that it stays in focus for the duration of the session. If the system steals focus, this must be ascribed to “environment issues”.

**Comment by davehunt** [comment]
Perhaps I shouldn't have given an example! 😛 The reason I did was that Selenium's current Firefox driver [adds the `-foreground` argument](https://github.com/SeleniumHQ/selenium/blob/a91690bd4131e17a3190ea1f3ae94ec946fa40a9/py/selenium/webdriver/firefox/firefox_binary.py#L84), and I have a test that triggers a doorhanger popup notification in Firefox. Doing this in Selenium with GeckoDriver/Marionette does not display the notification unless I click on the Firefox window. It is my suspicion that `-foreground` may resolve this. That said, I would most certainly prefer a solution that does not steal focus whenever Firefox is launched and for focus to be required for the test to execute successfully. I currently cannot experiment with `-foreground` as there's no option to provide additional arguments. I could fork GeckoDriver and build it myself with the additional argument to test my theory. I am using Mac OS.

**Comment by davehunt** [comment]
I just forked https://github.com/jgraham/rust_mozrunner and added the `-foreground` argument, then built geckodriver with this version, and the doorhanger is now being shown. I'd still like to prevent the need for having this focus, but this would at least allow me to proceed with my tests.

**Comment by davehunt** [comment]
I'm not sure where to start with a patch for geckodriver that forwards additional command line arguments to mozrunner, and I'm not sure I want the additional argument to be hardcoded in mozrunner as I have in my local patch.

**Comment by andreastt** [comment]
There are a few ways we can do it, I think. @jgraham should correct me here.

1. The [FirefoxRunner ctor](https://github.com/jgraham/rust_mozrunner/blob/master/src/runner.rs#L72) can be changed to take an additional `args: Vec<String>` argument.
2. The [default argument list](https://github.com/jgraham/rust_mozrunner/blob/master/src/runner.rs#L82) can be initialised with `vec!["--foreground"]`.
3. It can be hard-coded next to [the other required arguments](https://github.com/jgraham/rust_mozrunner/blob/master/src/runner.rs#L104).

I personally think option 3 is fine, if that is what (Python) mozrunner is doing.

**Comment by davehunt** [comment]
@jgraham how do you think we should proceed? I'd be happy to have a stab at this, but it will be my first experience with rust. I think even if we just patch mozrunner to include the argument by default, there's still value in being able to pass additional arguments to the binary via Selenium.

**Comment by jgraham** [comment]
https://github.com/mozilla/geckodriver/pull/65

i should maybe have good-first-bugged this, but by the time I knew for sure how to make it work, I had just written the code.
