### ISSUE TITLE
Implement anon [attribute] locator commands

### ISSUE THREAD

**Issue by whimboo** [mozilla/geckodriver#63]
To be able to access anonymous child nodes of [XBL bindings](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XBL) in chrome scope of the browser, we would need a new locator command. If you don't know about anonymous content read up about [here](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XBL/XBL_1.0_Reference#Anonymous_Content). 

For [accessing anonymous nodes](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XBL/XBL_1.0_Reference/Anonymous_Content#Scoping_and_Access_Using_the_DOM) the methods [`getAnonymousNodes()`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XBL/XBL_1.0_Reference/DOM_Interfaces#getAnonymousNodes) and [`getAnonymousElementByAttribute()`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XBL/XBL_1.0_Reference/DOM_Interfaces#getAnonymousElementByAttribute) can be used.

Usage wise `getAnonymousElementByAttribute()` will be necessary more often given that you want to look for a specific attribute value like `anonid` or `class`.

If you are curious how to find out what elements are actually anonymous in Firefox you can install the [DOM Inspector](https://addons.mozilla.org/de/firefox/addon/dom-inspector-6622/). Inspect the main browser window and search for the locationbar (`urlbar`). Anything which is in red color beneath this node is anonymous content and can only be accessed by the above mentioned methods.

As of right now its not possible to use those methods given that it would require to pass through a dictionary and not only a string. It means there might be some more work to do. But I will leave this up to  @jgraham and @AutomatedTester to comment on.

**Comment by whimboo** [comment]
Some examples can be found in [Firefox Puppeteer's ui modules](https://dxr.mozilla.org/mozilla-central/source/testing/puppeteer/firefox/firefox_puppeteer/ui) like:

Accessing the context menu of the urlbar: https://dxr.mozilla.org/mozilla-central/source/testing/puppeteer/firefox/firefox_puppeteer/ui/browser/toolbars.py#118

`parent = self.urlbar.find_element(By.ANON_ATTRIBUTE, {'anonid': 'textbox-input-box'})`

**Comment by jgraham** [comment]
Apparently I forgot to comment here; I implemented these in the [xbl_anonymous](https://github.com/mozilla/geckodriver/tree/xbl_anonymous) branch. The setup is a little different from the extant implementation because these are separate endpoints and only implement the semantics of the underlying implementation (i.e. one child node by attribute, or all children).

**Comment by davehunt** [comment]
I believe this was fixed in https://github.com/mozilla/geckodriver/commit/e2a6c301dc0f1b55ba67942d85b84357300dbefc by @andreastt?

**Comment by andreastt** [comment]
Yes. I also exposed this in the Selenium Python client in https://github.com/SeleniumHQ/selenium/commit/18432f5b0fb4fcd477fec1f02914c9ddd8c72793.
