### ISSUE TITLE
WebDriverException: Message: Not a Number

### ISSUE THREAD

**Issue by qitaos** [mozilla/geckodriver#633]
In order to help us efficiently investigate your issue, please provide the following information:

I use robotfram

ework+Selenium2Library to run test case. Selenium is 3.3.3, Firefox is 50.0, geckodriver is 0.15.0 win32. When I run the test case, Firefox browser was launched. Then raise "WebDriverException: Message: Not a Number". 

## Firefox Version
50.0

## Platform
Windows7

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [x] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

trace level log : 

```
POST http://127.0.0.1:50277/session {"capabilities": {"alwaysMatch": {}, "acceptInsecureCerts": true, "javascriptEnabled": true, "platform": "ANY", "browserName": "firefox", "version": "", "moz:firefoxOptions": {}, "marionette": true, "firstMatch": []}, "desiredCapabilities": {"acceptInsecureCerts": true, "javascriptEnabled": true, "platform": "ANY", "browserName": "firefox", "version": "", "moz:firefoxOptions": {}, "marionette": true}}
```

Finished Request

```
POST http://127.0.0.1:50277/session/a6a4ccce-ba31-4fdb-8918-7ccbb166d700/timeouts {"sessionId": "a6a4ccce-ba31-4fdb-8918-7ccbb166d700", "script": 5000}
```

Finished Request

WebDriverException: Message: Not a Number

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
The request

    POST http://127.0.0.1:50277/session/a6a4ccce-ba31-4fdb-8918-7ccbb166d700/timeouts {"sessionId": "a6a4ccce-ba31-4fdb-8918-7ccbb166d700", "script": 5000}

isn’t using a valid format for the Set Timeouts command.

The [Set Timeouts](https://w3c.github.io/webdriver/webdriver-spec.html#set-timeouts) command expects this input format, where all fields are optional:

    {
        "script": <number>,
        "pageLoad": <number>,
        "implicit": <number>
    }

The JSON Object you pass contains a `sessionId` field with a string, and this is why it is complaining about the value not being a number.

I suggest you file a bug with your language binding.

**Comment by andreastt** [comment]
I also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1355471 to improve the error message in this case.

**Comment by qitaos** [comment]
Well, this is using Selenium2Library + Selenium. so if you said JSON contains a sessionId field is the reason. I think this is standard using. If this is bug, maybe it's Selenium bug.
But I think more reason might be the geckodriver's bug.

**Comment by qitaos** [comment]
I add the chromedriver log and iedriver log below. Each JSON Object has contains sessionId. Why they won't be failed for "not a number"?

chromedriver log:

09:05:33.515	INFO	Opening browser 'gc' to base url 'http://www.baidu.com/'	
09:05:37.545	DEBUG	POST http://127.0.0.1:56761/session {"capabilities": {"platform": "ANY", "javascriptEnabled": true, "alwaysMatch": {}, "browserName": "chrome", "version": "", "firstMatch": [], "chromeOptions": {"args": [], "extensions": []}}, "desiredCapabilities": {"platform": "ANY", "browserName": "chrome", "version": "", "javascriptEnabled": true, "chromeOptions": {"args": [], "extensions": []}}}	
09:05:41.214	DEBUG	Finished Request	
09:05:41.215	DEBUG	POST http://127.0.0.1:56761/session/9fcaf2c6b746055dd6df839ceda0dcce/timeouts/async_script {"sessionId": "9fcaf2c6b746055dd6df839ceda0dcce", "ms": 5000.0}	
09:05:41.219	DEBUG	Finished Request	
09:05:41.220	DEBUG	POST http://127.0.0.1:56761/session/9fcaf2c6b746055dd6df839ceda0dcce/timeouts/implicit_wait {"sessionId": "9fcaf2c6b746055dd6df839ceda0dcce", "ms": 0.0}	
09:05:41.224	DEBUG	Finished Request	
09:05:41.224	DEBUG	POST http://127.0.0.1:56761/session/9fcaf2c6b746055dd6df839ceda0dcce/url {"url": "http://www.baidu.com/", "sessionId": "9fcaf2c6b746055dd6df839ceda0dcce"}	
09:05:42.446	DEBUG	Finished Request	
09:05:42.446	DEBUG	Opened browser with session id 9fcaf2c6b746055dd6df839ceda0dcce	
09:05:42.447	TRACE	Return: 1

iedriver log:


09:13:18.431	INFO	Opening browser 'ie' to base url 'http://www.baidu.com/'	
09:13:22.450	DEBUG	POST http://127.0.0.1:57421/session {"capabilities": {"platform": "WINDOWS", "javascriptEnabled": true, "alwaysMatch": {}, "browserName": "internet explorer", "version": "", "firstMatch": []}, "desiredCapabilities": {"platform": "WINDOWS", "browserName": "internet explorer", "version": "", "javascriptEnabled": true}}	
09:13:26.816	DEBUG	Finished Request	
09:13:26.817	DEBUG	POST http://127.0.0.1:57421/session/df47b4d5-e2f8-4d03-9468-dae9c14dbd89/timeouts/async_script {"sessionId": "df47b4d5-e2f8-4d03-9468-dae9c14dbd89", "ms": 5000.0}	
09:13:26.837	DEBUG	Finished Request	
09:13:26.837	DEBUG	POST http://127.0.0.1:57421/session/df47b4d5-e2f8-4d03-9468-dae9c14dbd89/timeouts/implicit_wait {"sessionId": "df47b4d5-e2f8-4d03-9468-dae9c14dbd89", "ms": 0.0}	
09:13:26.843	DEBUG	Finished Request	
09:13:26.844	DEBUG	POST http://127.0.0.1:57421/session/df47b4d5-e2f8-4d03-9468-dae9c14dbd89/url {"url": "http://www.baidu.com/", "sessionId": "df47b4d5-e2f8-4d03-9468-dae9c14dbd89"}	
09:13:28.327	DEBUG	Finished Request	
09:13:28.328	DEBUG	Opened browser with session id df47b4d5-e2f8-4d03-9468-dae9c14dbd89	
09:13:28.328	TRACE	Return: 1

**Comment by andreastt** [comment]
chromedriver doesn’t follow the W3C WebDriver specification by default, so the issue here is that your language binding includes the  sessionId field in the JSON Object for Set Timeouts.

Maybe you can file a bug with that language binding? Is it a Selenium language binding?
