### ISSUE TITLE
Error on attempt to install marionette driver with pip

### ISSUE THREAD

**Issue by mjbe** [mozilla/geckodriver#635]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.2 (64-bit) for Ubuntu

## Platform
Linux

## Steps to reproduce -

It makes no difference if install is attempted with pip or pip3, with or without sudo, and sudo with or without -H. They all give the same error:

```
$ sudo pip3 install marionette_driver
Collecting marionette_driver
  Downloading marionette_driver-2.2.0.tar.gz
Collecting mozrunner>=6.13 (from marionette_driver)
  Downloading mozrunner-6.13.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 1.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0829rk11/mozrunner/setup.py", line 24, in
<module>
        assert sys.version_info[0] == 2
    AssertionError
   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-0829rk11/mozrunner/
```

:::

**Comment by andreastt** [comment]
This isn’t an issue tracker for the marionette_driver Python package.

**Comment by whimboo** [comment]
As a side-note we do not support Python 3 for this Python package yet. For more details see https://bugzilla.mozilla.org/show_bug.cgi?id=1355537.
