### ISSUE TITLE
alwaysMatch/firstMatch capabilities are not processed correctly on Windows

### ISSUE THREAD

**Issue by juangj** [mozilla/geckodriver#637]
## Firefox Version
52.0.2

I have built:
* `geckodriver` at 72abe37b99cef7637135d5e5d902f7ba0df9a84b,
* `webdriver-rust` at https://github.com/mozilla/webdriver-rust/commit/50a0ee1bc6d37fef72066b8014e2b4fd85fa2f46, and
* `rust_mozrunner` with a local modification so it passes the flag `-marionette` instead of `--marionette`, as discovered on https://github.com/mozilla/geckodriver/commit/2e0054b90ecf1acbe8b442af54441e3cc746933f#commitcomment-21725495.

## Platform
Windows

This does not happen on Linux, for some reason I can't fathom.

## Steps to reproduce -
Apologies if I copy these wget commands down wrong; don't have an easy way to copy them out of my Windows environment. The capabilities should be visible in the log files, though.

### Using W3C request (alwaysMatch/firstMatch)

`wget.exe http://localhost:5555/session --post-data="{\"alwaysMatch\": {\"browserName\": \"firefox\", \"acceptInsecureCerts\": true, \"moz:firefoxOptions\": {\"prefs\": {\"network.captive-portal-service.enabled\": false}}}, \"firstMatch\": [{}]}"`

Geckodriver log: [geckodriver.w3c.log.txt](https://github.com/mozilla/geckodriver/files/915170/geckodriver.w3c.log.txt)

The returned capabilities include `"acceptInsecureCerts":false`, and the requested pref is not set correctly in `about:config`.

Suspiciously, Geckodriver appears to send empty capabilities to Marionette:
>1491960773928	geckodriver::marionette	DEBUG	→ 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]

### Using legacy request (desiredCapabilities)

`wget.exe http://localhost:5555/session --post-data="{\"desiredCapabilities\": {\"browserName\": \"firefox\", \"acceptInsecureCerts\": true, \"moz:firefoxOptions\": {\"prefs\": {\"network.captive-portal-service.enabled\": false}}}}"`

Geckodriver log: [geckodriver.legacy.log.txt](https://github.com/mozilla/geckodriver/files/915169/geckodriver.legacy.log.txt)

The requested pref is shown correctly in `about:config`.

**Comment by juangj** [comment]
Can't reproduce this now -- not sure if something was fixed incidentally or if I was doing something silly and wrong before.

**Comment by andreastt** [comment]
This issue had slipped under my radar, sorry.

We recently found https://github.com/mozilla/geckodriver/issues/638 affecting new session negotiation on macOS due to failing to look up the Firefox version. If left unfixed, that would have caused geckodriver to be unusable on that platform. If there is an issue with similar consequences on Windows, we ought to fix it before the 0.16.0 release.

**Comment by andreastt** [comment]
Confirmed working on Windows.
