### ISSUE TITLE
Second call to SetWindowRect causes hang in geckodriver

### ISSUE THREAD

**Issue by jimevans** [mozilla/geckodriver#643]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
55.0a1 (2017-04-12) (32-bit)

## Platform
Windows

## Steps to reproduce -

Execute the following code using the Selenium .NET bindings (exact W3C WebDriver protocol commands are included as comments):

    FirefoxOptions options = new FirefoxOptions();
    options.LogLevel = FirefoxDriverLogLevel.Trace;
    options.BrowserExecutableLocation = @"C:\Program Files (x86)\Nightly\firefox.exe";

    // POST /session
    // command body:
    // {
    //     "capabilities": {
    //         "alwaysMatch" : {
    //             "browserName": "firefox",
    //             "acceptInsecureCerts": true,
    //             "moz:firefoxOptions": {
    //                 "binary": "C:\Program Files (x86)\Nightly\firefox.exe",
    //                 "log": {
    //                     "level": "trace"
    //                 }
    //             }
    //         }
    //    }
    // }
    IWebDriver driver = new FirefoxDriver(options);

    // POST /session/{sessionId}/window/rect
    // command body: { "width": 1024, "height": 768 }
    driver.Manage().Window.Size = new Size(1024, 768);

    // Driver hangs at this line of code, never returns.
    driver.Manage().Window.Size = new Size(1024, 768);

    driver.Quit();

 - [X] A *minimal* HTML file (or files) that can be used to reproduce the issue:

No HTML page needed, as no navigation is done, and can be reproduced directly from the immediately-opened browser window.

 - [X] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. 

```
1492031483713   geckodriver     INFO    Listening on 127.0.0.1:54486
1492031540643   geckodriver::marionette INFO    Starting browser \\?\C:\Program Files (x86)\Nightly\firefox.exe with args ["-marionette"]
1492031542661   geckodriver::marionette DEBUG   Connected to Marionette on localhost:54532
1492031542736   geckodriver::marionette TRACE   ← {"applicationType":"gecko","marionetteProtocol":3}
1492031542751   geckodriver::marionette TRACE   → 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1492031542996   geckodriver::marionette TRACE   ← [1,1,null,{"sessionId":"3f24d176-fd2e-477f-bce2-3bb452caf6c8","capabilities":{"browserName":"firefox","browserVersion":"55.0a1","platformName":"windows_nt","platformVersion":"10.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":14420,"moz:profile":"C:\\Users\\seatt\\AppData\\Local\\Temp\\rust_mozprofile.s0G9tgIyUZx5","moz:accessibilityChecks":false}}]
1492031543030   webdriver::server       DEBUG   Returning status Ok
1492031543038   webdriver::server       DEBUG   Returning body {"value": {"sessionId":"3f24d176-fd2e-477f-bce2-3bb452caf6c8","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"55.0a1","moz:accessibilityChecks":false,"moz:processID":14420,"moz:profile":"C:\\Users\\seatt\\AppData\\Local\\Temp\\rust_mozprofile.s0G9tgIyUZx5","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1492031545113   webdriver::server       DEBUG   Got request POST AbsolutePath("/session/3f24d176-fd2e-477f-bce2-3bb452caf6c8/window/rect")
1492031545114   webdriver::command      DEBUG   Got request body {"width":1024,"height":768}
1492031545115   geckodriver::marionette TRACE   → 67:[0,2,"setWindowRect",{"height":768,"width":1024,"x":null,"y":null}]
1492031545208   geckodriver::marionette TRACE   ← [1,2,null,{"x":4,"y":4,"width":1024,"height":768}]
1492031545210   webdriver::server       DEBUG   Returning status Ok
1492031545211   webdriver::server       DEBUG   Returning body {"value": {}}
1492031545212   webdriver::server       DEBUG   Got request POST AbsolutePath("/session/3f24d176-fd2e-477f-bce2-3bb452caf6c8/window/rect")
1492031545213   webdriver::command      DEBUG   Got request body {"width":1024,"height":768}
1492031545213   geckodriver::marionette TRACE   → 67:[0,3,"setWindowRect",{"height":768,"width":1024,"x":null,"y":null}]
```

**Comment by pbi-qfs** [comment]
I could reproduce the problem with Java Selenium bindings on FF 53, 54, and 55.

It happens, if you try to set a size which the browser already has:
```java
driver.manage().window().setSize(new Dimension(500,500))
driver.manage().window().setSize(new Dimension(500,600))
driver.manage().window().setSize(new Dimension(500,500))
driver.manage().window().setSize(new Dimension(500,500)) // blocks here
```
or:

```java
Dimension size = driver.manage().window().getSize()
driver.manage().window().setSize(size)
```

**Comment by andreastt** [comment]
I fixed the window position case, but not the window size case. I can confirm I’m seeing the issue described here when setting the window size to the window’s current size.

**Comment by andreastt** [comment]
Patched this in https://bugzilla.mozilla.org/show_bug.cgi?id=1357878.

**Comment by FelipeJK** [comment]
Only getting window size is throwing the exception "org.openqa.selenium.WebDriverException: getWindowRect". I am using Selenium driver 3.34.0, geckodriver 0.16.1 and FF 52.1.1 ESR.

- Getting the windowDimension size...
1494617242267	webdriver::server	DEBUG	â†’ GET /session/cce999bf-940d-48bd-b4a5-b5f5e2e7a45c/window/rect 
1494617242272	geckodriver::marionette	TRACE	â†’ 26:[0,599,"getWindowRect",{}]
1494617242273	Marionette	TRACE	conn0 -> [0,599,"getWindowRect",{}]
1494617242274	Marionette	TRACE	conn0 <- [1,599,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494617242274	geckodriver::marionette	TRACE	â†? [1,599,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494617242274	webdriver::server	DEBUG	â†? 404 Not Found {"value":{"error":"unknown error","message":"getWindowRect","stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x43a15d - <no info>\n   3:           0x4474c9 - <no info>\n   4:           0x445208 - <no info>\n   5:           0x41ddb1 - <no info>\n   6:           0x4091c7 - <no info>\n   7:           0x6bc939 - <no info>\n   8:           0x415a19 - <no info>\n   9:           0x6b6e43 - <no info>\n  10:     0x7ffb90128364 - BaseThreadInitThunk"}}
mai 12, 2017 4:27:22 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
1494617244344	webdriver::server	DEBUG	â†’ GET /session/cce999bf-940d-48bd-b4a5-b5f5e2e7a45c/window/rect 
1494617244353	geckodriver::marionette	TRACE	â†’ 26:[0,600,"getWindowRect",{}]
1494617244353	Marionette	TRACE	conn0 -> [0,600,"getWindowRect",{}]
1494617244354	Marionette	TRACE	conn0 <- [1,600,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494617244354	geckodriver::marionette	TRACE	â†? [1,600,{"error":"unknown command","message":"getWindowRect","stacktrace":"WebDriverError@chrome://marionette/content/error.js:200:5\nUnknownCommandError@chrome://marionette/content/error.js:444:5\nDispatcher.prototype.execute/req<@chrome://marionette/content/dispatcher.js:121:13\nTaskImpl_run@resource://gre/modules/Task.jsm:319:42\nTaskImpl@resource://gre/modules/Task.jsm:277:3\ncreateAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nDispatcher.prototype.execute@chrome://marionette/content/dispatcher.js:118:13\nDispatcher.prototype.onPacket@chrome://marionette/content/dispatcher.js:89:5\nDebuggerTransport.prototype._onJSONObjectReady/<@chrome://marionette/content/server.js -> resource://devtools/shared/transport/transport.js:483:11\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\nexports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14\n"},null]
1494617244354	webdriver::server	DEBUG	â†? 404 Not Found {"value":{"error":"unknown error","message":"getWindowRect","stacktrace":"stack backtrace:\n   0:           0x489f6f - <no info>\n   1:           0x48ad59 - <no info>\n   2:           0x43a15d - <no info>\n   3:           0x4474c9 - <no info>\n   4:           0x445208 - <no info>\n   5:           0x41ddb1 - <no info>\n   6:           0x4091c7 - <no info>\n   7:           0x6bc939 - <no info>\n   8:           0x415a19 - <no info>\n   9:           0x6b6e43 - <no info>\n  10:     0x7ffb90128364 - BaseThreadInitThunk"}}
mai 12, 2017 4:27:24 PM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]

**Comment by andreastt** [comment]
@FelipeJK I commented on this in a https://github.com/mozilla/geckodriver/issues/703, but unfortunately the `setWindowRect` Marionette command is only available in Firefox 53 or greater. See https://bugzilla.mozilla.org/show_bug.cgi?id=1347589 for more information.

**Comment by FelipeJK** [comment]
Thanks Andreas. Any plans to implement the fix for FF 52?

Em 12 de mai de 2017 18:14, "Andreas Tolfsen" <notifications@github.com>
escreveu:

@FelipeJK <https://github.com/felipejk> I commented on this in a #703
<https://github.com/mozilla/geckodriver/issues/703>, but unfortunately the
setWindowRect Marionette command is only available in Firefox 53 or
greater. See https://bugzilla.mozilla.org/show_bug.cgi?id=1347589 for more
information.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mozilla/geckodriver/issues/643#issuecomment-301187596>,
or mute the thread

**Comment by andreastt** [comment]
Since Firefox 52 is stable, we are unlikely to uplift it there due to the risks involved.

**Comment by Trucnt** [comment]
Hi @andreastt ,
I tried with FF v55b10. It was better but I still got a fail when the vertical size is unchanged.
Pls help to check it.
Tks.

**Comment by juangj** [comment]
@Trucnt It would help the Geckodriver team immensely if you provided minimal example code to reproduce your failure, and a trace-level log from Geckodriver. Please see the original post in this thread for an example.

**Comment by Trucnt** [comment]
Hi @juangj ,
- Double check this issue:
I performed set window size 2 times as below: 
`driver.Manage().Window.Size = new Size(1024, 768);`
`driver.Manage().Window.Size = new Size(1024, 768);`
>> The issue is fixed. Firefox runs smoothly.

- However, double checked with other scenario: I changed **Width** value and kept Height value. 
>> We face the new issue. The Windows size is **NOT** changed and there is **NO errors** log in the Report. 
**Note: the issue is JUST happened with FF v55**

**Comment by andreastt** [comment]
@Trucnt I can’t reproduce this with Firefox Nightly. Can you please file a new issue after you’ve tested with Nightly? It would be good if you included a trace-level geckodriver log.

**Comment by Trucnt** [comment]
```
public static void main(String[] args) {
        try {

            System.setProperty("webdriver.gecko.driver", "D:\\KDD_v1\\drivers\\geckodriver_Win64.exe");
            WebDriver webDriverFirefox = new FirefoxDriver();
            webDriverFirefox.get("https://www.youtube.com/");
            Actions actions = new Actions(webDriverFirefox);

// Set size of window to 600 x 555
            webDriverFirefox.manage().window().setSize(new Dimension(600, 555));
            Thread.sleep(2000);
// Set size of window to 1000 x 555
            webDriverFirefox.manage().window().setSize(new Dimension(1000, 555));

// ** ==> Expected: window size = 1000 x 555, but actual window size still 600 x 555**

            Thread.sleep(5000);

            webDriverFirefox.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
>>## Expected: window size = 1000 x 555, but actual window size still 600 x 555

**Comment by andreastt** [comment]
@Trucnt Unfortunately that didn’t contain a _trace-level_ log (only debug). When you produce it, can you please file a new bug so we don’t hijack this closed issue?
