### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by Mikeux** [mozilla/geckodriver#648]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.02 32bit

## Platform
Windows7 64bit

Even I updated all libraries (C# Selenium 3.3, gecko 0.15) I get "not secure" issue when I try to use some specific webpage. (That worked fine 2-3 month earlier)

![image](https://cloud.githubusercontent.com/assets/1476339/25005387/0eef912c-2059-11e7-83d9-5a2979b6c5c7.png)

Here is the setting trials with I try setup the driver:

FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(Functions.LocalDir + @"Bat", "geckodriver.exe");

FirefoxOptions options = new FirefoxOptions();
String path = Functions.LocalDir + @Log.DownloadFilepath;

//Automatically download
options.SetPreference("browser.download.folderList", 2);
options.SetPreference("browser.download.dir", path);
options.SetPreference("browser.helperApps.neverAsk.openFile", "application/json");
options.SetPreference("browser.helperApps.neverAsk.saveToDisk", "application/json");
options.SetPreference("browser.helperApps.neverAsksaveToDisk", "application/x-msexcel,application/excel,application/x-excel,application/excel,application/x-excel,application/excel,application/vnd.ms-excel,application/x-excel,application/x-msexcel");
//Not necessary
options.SetPreference("browser.download.manager.focusWhenStarting", false);
options.SetPreference("browser.helperApps.alwaysAsk.force", false);
options.SetPreference("browser.download.manager.alertOnEXEOpen", false);
options.SetPreference("browser.download.manager.closeWhenDone", false);
options.SetPreference("browser.download.manager.showAlertOnComplete", false);
options.SetPreference("browser.download.manager.useWindow", false);
options.SetPreference("services.sync.prefs.sync.browser.download.manager.showWhenStarting", false);
options.SetPreference("pdfjs.disabled", true);

options.SetPreference("browser.cache.disk.enable", false);
options.SetPreference("browser.cache.memory.enable", false);
options.SetPreference("browser.cache.offline.enable", false);
options.SetPreference("network.http.use-cache", false);

options.SetPreference("network.auth.subresource-http-auth-allow", 2);
options.SetPreference("network.auth.subresource-http-auth-allow", 2);

options.AddAdditionalCapability("acceptInsecureCerts", true);
options.SetPreference("acceptSslCerts", true);
options.AddAdditionalCapability("acceptSslCerts", true);
options.SetPreference(CapabilityType.AcceptSslCertificates, true);
options.SetPreference("acceptInsecureCerts", true);

options.AddArgument("--trustAllSSLCertificates");

driver = new FirefoxDriver(service, options, new TimeSpan(0, 0, 10, 0));

**Comment by andreastt** [comment]
It’s hard to debug this without a trace-level log from geckodriver (see the README on how to crank up the logging verbosity). I’m not able to reproduce this with Firefox Nightly using the following capabilities:

```js
{"desiredCapabilities": {"acceptInsecureCerts": true, "moz:firefoxOptions": {"binary": "/home/ato/src/gecko/obj-x86_64-pc-linux-gnu/dist/bin/firefox", "log": {"level": "trace"}}}}
```

It is possible that the Firefox version you use is too old and doesn’t have the necessary patches from https://bugzilla.mozilla.org/show_bug.cgi?id=1103196. I would recommend trying again setting the capabilities I use above and pointing the `binary` field to the location of the Nightly executable.

**Comment by whimboo** [comment]
Also please have a look at https://www.hskupin.info/2017/01/23/using-selenium-and-webdriver-to-interact-with-insecure-ssl-pages-in-firefox/ which could give you a hint how to do it with the C# bindings.
