### ISSUE TITLE
Please release v0.16.0 that exists in change log and doesn't exist in releases.

### ISSUE THREAD

**Issue by inzerion** [mozilla/geckodriver#652]
Please release v0.16.0 that exists in change log and doesn't exist in releases.

We found that our sendKeys doesn't work properly for element and element lost DOM presence after element.sendKeys. 

I see that you have relative updates for sendKeys in change.log, but there no released artifacts to download

**Comment by andreastt** [comment]
We’re holding off with the release because there are various issues reported on broken New Session negotiation.

**Comment by andreastt** [comment]
Updated the changelog in https://github.com/mozilla/geckodriver/commit/dccea97b6cc709b4bd93146ea12c7d9b0b356688.
