### ISSUE TITLE
Is Proxy setting is supported in geckodriver (geckodriver-v0.15.0-win64), 

### ISSUE THREAD

**Issue by newton143** [mozilla/geckodriver#654]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
48.0.2

## Platform
Windows

##Language
C#

## Steps to reproduce -
FirefoxOptions options = new FirefoxOptions();
options.SetPreference("network.proxy.http", "localhost");
options.SetPreference("network.proxy.http_port", "8080");
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(Settings.DriverDirectory, "geckodriver.exe");
service.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
TimeSpan time = TimeSpan.FromSeconds(10);
WebDriver = new FirefoxDriver(service, options, time);

##Error
Im getting an exception

##Clarification:
How to use proxy in marionette(geckodriver) in C#

**Comment by andreastt** [comment]
Yes it is, but you’re using a fairly ancient Firefox version. Please consider using [Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly) for the best experience with geckodriver.

**Comment by newton143** [comment]
Just added below line, issue is resolved
options.UseLegacyImplementation = false;
