### ISSUE TITLE
geckodriver 0.16 can't click on an element hidden by double overflow

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#662]
## Firefox Version
Nightly: 55.0a1 (2017-04-20) (64-bit)
Geckodriver: f46d65ccdc7b22d773977fb3b3fb6a57108ddfd2

## Platform
OSX

## Steps to reproduce -
 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue
```
<!DOCTYPE html>
<html>
<head>
  <title>Page with overflow: auto</title>
  <style type="text/css">
    html, body {
        width: 100%;
        height: 100%;
        overflow: auto;
    }
  </style>
</head>
<body>
  <div style="height: 5000px;">Placeholder</div>
  <div>
    <a id="link" href="target_page.html">Click me!</a>
  </div>
</body>
</html>
```

Selenium to reproduce the issue, but it boils down to an `Element Click`

```
WebDriver driver = new FirefoxDriver();
driver.get("the-html-above");
driver.findElement(By.id("link")).click();
```

It is expected that the driver navigate away from the page. It doesn't.

**Comment by barancev** [comment]
For the record: this test works for me (Windows, Firefox Nightly, geckodriver 0.16)
Also it works on travis: https://travis-ci.org/SeleniumHQ/selenium/jobs/224611764#L925

**Comment by whimboo** [comment]
Same here with geckodriver 0.23 and latest Firefox Nightly. If you still face the problem please reopen.
