### ISSUE TITLE
sendKeys to a disabled text input does not throw

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#668]
## Firefox Version
55.0a1 (2017-04-21) (64-bit)
geckodriver 0.16

## Platform
Windows

## Steps to reproduce -
 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).
```
<input type="text" id="disabledTextElement2" disabled="" />
```
Scenario:
```
driver.findElement(By.id("disabledTextElement2")).sendKeys("bar");
```
It is expected that "element not interactable" error should appear.

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.
```
1492804716192	webdriver::server	DEBUG	→ POST /session/f6db3b77-edf9-4a5f-9992-44c4d28fadb3/element {"value":"#disabledTextElement2","using":"css selector"}
1492804716192	geckodriver::marionette	TRACE	→ 76:[0,4,"findElement",{"using":"css selector","value":"#disabledTextElement2"}]
1492804716197	Marionette	TRACE	0 -> [0,4,"findElement",{"using":"css selector","value":"#disabledTextElement2"}]
1492804716200	Marionette	TRACE	0 <- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"611d8af5-0341-4de4-aeea-f457134698fc","ELEMENT":"611d8af5-0341-4de4-aeea-f457134698fc"}}]
1492804716200	geckodriver::marionette	TRACE	← [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"611d8af5-0341-4de4-aeea-f457134698fc","ELEMENT":"611d8af5-0341-4de4-aeea-f457134698fc"}}]
1492804716200	webdriver::server	DEBUG	← 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"611d8af5-0341-4de4-aeea-f457134698fc"}}

1492804716211	webdriver::server	DEBUG	→ POST /session/f6db3b77-edf9-4a5f-9992-44c4d28fadb3/element/611d8af5-0341-4de4-aeea-f457134698fc/value {"id":"611d8af5-0341-4de4-aeea-f457134698fc","text":"bar","value":["b","a","r"]}
1492804716212	geckodriver::marionette	TRACE	→ 106:[0,5,"sendKeysToElement",{"id":"611d8af5-0341-4de4-aeea-f457134698fc","text":"bar","value":["b","a","r"]}]
1492804716214	Marionette	TRACE	0 -> [0,5,"sendKeysToElement",{"id":"611d8af5-0341-4de4-aeea-f457134698fc","text":"bar","value":["b","a","r"]}]
1492804716259	Marionette	TRACE	0 <- [1,5,null,{}]
1492804716259	geckodriver::marionette	TRACE	← [1,5,null,{}]
1492804716259	webdriver::server	DEBUG	← 200 OK {"value": {}}
```

**Comment by andreastt** [comment]
According to the description of [Element Send Keys](https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys) in the specification, we shouldn’t return an error when the element is disabled. Does Selenium expect this behaviour?

I find this a bit strange, since Element Click _not does_ check if the element is disabled (see https://bugzilla.mozilla.org/show_bug.cgi?id=1355546 and https://github.com/mozilla/geckodriver/issues/615#issuecomment-293334471).

**Comment by barancev** [comment]
click operation is defined for any visible element. sendKeys operation is defined for focusable elements only.

Specification reads "In case the element is not keyboard-interactable, an element not interactable error is returned", where keyboard-interactable is defined as "has a focusable area, or is the body element".

A disabled input has no focusable area.

**Comment by andreastt** [comment]
You’re right, this should check whether the element is keyboard-interactable and return an error if that is not the case.

I tried implementing keyboard-interactability some time ago but quickly gave up due to its complexity. I will have another go at scoping the problem in the future.

**Comment by barancev** [comment]
According to the regression testing, this issue has been fixed, the test started to pass.

**Comment by andreastt** [comment]
Sounds good. Closing.

**Comment by whimboo** [comment]
That should have been the result of the landing of my patch on https://bugzilla.mozilla.org/show_bug.cgi?id=1414322.
