### ISSUE TITLE
geckodriver.exe 0.16.0for win32 detected as malware by Windows Defender on Window 10

### ISSUE THREAD

**Issue by jsakamoto** [mozilla/geckodriver#671]
## Platform

Windows 10 ver.10.0.15063 x64

## Steps to reproduce

on Windows 10,

1. right click geckodriver.exe (win32) on Explorer to show context menu.
2. Chose [Scan with Windows Defender] context menu item.

## Additional Information

VirusTotal reported "it is not malware." except Microsoft Windows Defender.

https://www.virustotal.com/en/file/688edae9e403d20ec35e94042451d859a6cc01f62e6dc48e7d898594f67aa681/analysis/1492816767/

I submitted the geckodriver.exe file to Microsoft Malware Protection Center as "I think it is not malware."

https://www.microsoft.com/en-us/security/portal/submission/SubmissionHistory.aspx?SubmissionId=dd7c0607-24ce-407b-ae54-090eced357ab&wa=wsignin1.0

Interestingly, Microsoft Malware Protection Center said Detection Status is "Not detected".

Therefore, I believe it is false detection by Windows Defender.

**Comment by jsakamoto** [comment]
## Update

I re-scanned geckodriver.exe (win32) with VirusTotal right now, detection rate was increased from 1 to 3.

https://www.virustotal.com/en/file/688edae9e403d20ec35e94042451d859a6cc01f62e6dc48e7d898594f67aa681/analysis/1492847263/

![image](https://cloud.githubusercontent.com/assets/95908/25302594/3ff85644-277c-11e7-9362-fbf9f753e41a.png)

P.S. The Win64 version was not reported as malware. VirusTotal reported that it is clearly safe.

**Comment by andreastt** [comment]
To my knowledge, we made no notable changes to the way the Rust binaries were compiled in the 0.16.0 release. This also does not seem to be a problem for the x86_64 binary for Windows.

I don’t know if this is simply down to the fact that Window Defender is unable to recognise the binary structures of Rust programs yet? I also don’t know if there is anything we can trivially do about this without help from Microsoft. Any input on this would is welcome (-:

@jimevans also notified me about this moments after the release was made.

**Comment by sashaanderson** [comment]
Same issue here. I just downloaded geckodriver-v0.16.0-win32.zip, right-click Extract All... > Extract, as soon as it gets to 100%, Windows defender shows the alert "Found some malware / Windows Defender is removing it" and it deletes the "geckodriver.exe" file. No such issue with v0.15.
![image](https://cloud.githubusercontent.com/assets/11536706/25307335/5fc49122-276d-11e7-9983-4bcff9a56e91.png)

**Comment by jsakamoto** [comment]
**Update:**

The detection rate on VirusTotal was increased from 1/60 > 3/60 > 6/60 😭 

https://www.virustotal.com/en/file/688edae9e403d20ec35e94042451d859a6cc01f62e6dc48e7d898594f67aa681/analysis/1492906167/

![image](https://cloud.githubusercontent.com/assets/95908/25309479/597e947e-2809-11e7-8a10-a78eafbc51c1.png)

I reported McAfee to explain it will false detection.

**Comment by changot08** [comment]
Getting the virus detection as well. geckodriver-v0.16.0-win32.zip

![image](https://cloud.githubusercontent.com/assets/26811779/25324113/752f9e00-28f6-11e7-8874-a2a4a1fdf25a.png)

**Comment by andreastt** [comment]
FWIW “me too” comments here are not particularly useful in resolving the issue.

This is obviously a false-positive. According to the risk evaluation of Symantec, [Trojan.Gen.6](https://www.symantec.com/security_response/writeup.jsp?docid=2016-122103-3723-99&vid=55650) indicates binary patterns that have not yet been classified. We likely need users to contact their antivirus vendors to tell them this is a false-positive and ask them to classify Rust binary patterns.

I found [a topic on a similar malware warning in the Rust installer](https://users.rust-lang.org/t/malware-in-rust-installer/8058) which does not fill me with confidence in getting this resolved, but there seems to be little we can do from our side. Please contact your antivirus vendors and let them know this is a false-positive.

**Comment by jsakamoto** [comment]
Hi @changot08 ,I think, you may can report from here: https://submit.symantec.com/false_positive/

**Comment by changot08** [comment]
@jsakamoto thanks. I already submitted a false positive using the link you provided and I also reported it to our security team to try to exclude the file geckodriver.exe from our anti virus software.

**Comment by changot08** [comment]
@jsakamoto symantec already responded. So if anyone is using norton anti virus it should be good to go once they roll out the next live update.

![image](https://cloud.githubusercontent.com/assets/26811779/25340628/f2d106cc-2938-11e7-9b96-a172fb90ad64.png)

**Comment by andreastt** [comment]
@changot08 That is great work, thanks! Let’s hope that they are working on a long-term solution for Rust binaries so that future geckodriver.exe’s with a different hash are also problem free.

**Comment by AutomatedTester** [comment]
@changot08 
Thank you greatly for the hard work you have put in here to help us!

**Comment by jsakamoto** [comment]
McAfee replay e-mail to me about fixed false detection. 

And, Microsoft also fixed it.

https://www.virustotal.com/en/file/688edae9e403d20ec35e94042451d859a6cc01f62e6dc48e7d898594f67aa681/analysis/1493071948/

![image](https://cloud.githubusercontent.com/assets/95908/25362322/294f37aa-298e-11e7-96b9-c2228ae85aa3.png) :tada:

There are still 6/60 false detection in VirusTotal, but It seems to be improving because big titles of anti malware software are fixed false detection.

**Comment by jsakamoto** [comment]
Should I close this issue? (I think, it is OK to close this issue.)

**Comment by AutomatedTester** [comment]
If anyone else comes across this bug, please tell flag it in your antivirus as a false positive.
