### ISSUE TITLE
set page load timeout is not work

### ISSUE THREAD

**Issue by wengoooooooo** [mozilla/geckodriver#677]
## Firefox Version
Firefox 52.0, 
geckodriver 0.15, 
selenium 3.4, 
python 2.7

## Platform
Windows 7

## Steps to reproduce -
This code in the geckodriver version 0.11 is worked, but not work in the geckodriver version 0.15
```python
driver = webdriver.Firefox()
driver.set_page_load_timeout(1)  # not work
driver.get("https://www.kidsroom.de/en/")
```

**Comment by andreastt** [comment]
There’s little point in reporting bugs on older versions of geckodriver.

**Comment by whimboo** [comment]
@wengoooooooo, so is this fixed for you with the latest releases of Geckodriver, and Firefox 54.0 (currently beta) or Firefox Nightly?

**Comment by wengoooooooo** [comment]
@whimboo , latest releases of Geckodriver, and Firefox 53 already fix the bug

**Comment by whimboo** [comment]
Wonderful. Thanks for the feedback.
