### ISSUE TITLE
v0.7.1 and windows

### ISSUE THREAD

**Issue by merrua** [mozilla/geckodriver#68]
Is there a windows version of v0.7.1 ? I see there was for 0.6.2. Was it just missed?

**Comment by andreastt** [comment]
There appears not to be one for [0.7.1](https://github.com/mozilla/geckodriver/releases/tag/v0.7.1). Who built it for Windows last time? @AutomatedTester?

**Comment by jgraham** [comment]
The solution going forward here is to create a travis setup that can test, [cross-]compile and make the actual release.

**Comment by andreastt** [comment]
Do we know of any other Rust projects that do this and which we can draw inspiration from?

**Comment by AutomatedTester** [comment]
There is now a windows build available. Unfortunately one of our dependencies broke on Windows.

**Comment by andreastt** [comment]
See #72 about using Travis to perform releases. #73 adds cross-compilation for Windows.
