### ISSUE TITLE
Update issue template to request a script to reproduce the issue

### ISSUE THREAD

**Issue by whimboo** [mozilla/geckodriver#682]
Right now we only require the HTML file and a trace log. It will also be of help to have a script which reproduces the issue. With that we could see which binding has been used, if it is affected or not updated, or if the test is doing a mistake.

**Comment by jgraham** [comment]
We often get a script whether we ask for it or not. I intentionally didn't request one because,  whatever binding is used, a trace-level log should show us exactly what's going on over the wire, and I don't want to give the impression that we will spend time setting up different client bindings and tracking down their bugs.

**Comment by AutomatedTester** [comment]
@whimboo please submit a PR so we can then tweak as asked for in the original email thread

**Comment by andreastt** [comment]
I posit that the skilled bug reporters will supply the necessary information to reproduce a bug anyway, and that those who are not simply will delete/ignore selectively when faced with the wall of text that currently makes out our issue template.

The single most useful thing they can provide is the trace-level log from geckodriver, which includes the Firefox version. We could maybe consider returning the geckodriver version number as a capability, but I’m hesitant that people might start using it conditionally…

**Comment by whimboo** [comment]
The wall of text is indeed a problem. Can't we simply strip this down and maybe add links to a wiki page here on the repository, which explains things in more detail?

While checking issues all the last week I have seen that in most cases we had to ask the version of the language binding. So this might also be a good candidate to be added.

**Comment by andreastt** [comment]
It would also be possible to move some of the explanation text to an HTML comment, which isn’t rendered when an issue is posted. Servo does this.

**Comment by whimboo** [comment]
I pushed an update to my fork. @andreastt, @jgraham, @AutomatedTester what do you think?

https://github.com/whimboo/geckodriver/issues/new

**Comment by whimboo** [comment]
This actually got landed a month ago via PR #768.
