### ISSUE TITLE
latest gecko driver downloads updates during tests which highly impacts performance

### ISSUE THREAD

**Issue by SergioLeone** [mozilla/geckodriver#686]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version 
53.0 x64

## Platform 
Windows 7 x64

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

When running my tests firefox driver stops executing commands because it starts downloading some things. Sometimes it resumes after download, sometimes fails because of timeout for page load. Still, even if it resumes, the delay for download is big, like a few minutes sometimes.
And the starting point for download is very random, sometimes it starts before running tests, sometimes in the middle of test suite.

Here's the log:

```
1493190654998   addons.productaddons    INFO    sending request to: https://aus5.mozilla.org/update/3/GMP/53.0/20170413192749/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%206.1.1.0
%20(x64)/default/default/update.xml
1493190656309   addons.productaddons    INFO    Completed downloading document
1493190656675   addons.productaddons    INFO    downloadXHR File download. status=200
1493190656684   addons.productaddons    INFO    Downloaded file will be saved to C:\Users\L094540\AppData\Local\Temp\tmpaddon-c40aec
1493190658529   addons.productaddons    INFO    downloadXHR File download. status=200
1493190658536   addons.productaddons    INFO    Downloaded file will be saved to C:\Users\L094540\AppData\Local\Temp\tmpaddon-2e96c4
```

I have added the following preferences to the profile that I'm creating in test setup method

```
ffprofile.setPreference("app.update.enabled", false);
ffprofile.setPreference("app.update.service.enabled", false);
ffprofile.setPreference("app.update.auto", false);
ffprofile.setPreference("app.update.staging", false);
ffprofile.setPreference("app.update.silent", false);
```

however the result is the same.

Haven't noticed this behavior with selenium 3.3.* and firefox 49.0.2, only started with latest selenium+geckodriver

**Comment by andreastt** [comment]
@whimboo Do you know what’s going on here, given that you’re somewhat familiar with update tests? Are we missing setting some prefs in https://github.com/mozilla/geckodriver/blob/master/src/prefs.rs?

**Comment by andreastt** [comment]
@SergioLeone When you say “latest geckodriver”, do you mean you’re using 0.16.0?

**Comment by whimboo** [comment]
The above is not for application updates but its a download of GMP plugins (https://wiki.mozilla.org/GeckoMediaPlugins). So if you don't need those the appropriate prefs should be turned off. Just search for `gmp` in about:config to disable particular plugins.

**Comment by SergioLeone** [comment]
@andreastt yes, 0.16.0

@whimboo Thanks, I'll look into that.

**Comment by SergioLeone** [comment]
@whimboo could you please shed some light on these logs:
I think I have managed to disable the gmp downloads, but the driver is still checking some extensions.
```
2017-04-27 09:26:33.635 ←[32m[INFO]←[m [SeleniumDriverBuilder$FirefoxDriverBuilder.build.47] - Building firefox driver.
1493265395017   geckodriver     INFO    Listening on 127.0.0.1:28741
1493265400951   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1493265400954   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1493265400963   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1493265400966   addons.manager  DEBUG   Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1493265400968   addons.manager  DEBUG   Starting provider: XPIProvider
1493265400968   addons.xpi      DEBUG   startup
1493265400970   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1493265400971   addons.xpi      DEBUG   checkForChanges
1493265400971   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1493265400972   addons.xpi      DEBUG   Loaded add-on state from prefs: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Users\\L094540\\IdeaProjects\\Browsers\\Firefox_53.0
_64bit\\browser\\features\\aushelper@mozilla.org.xpi","e":true,"v":"2.0","st":1492142093000},"e10srollout@mozilla.org":{"d":"C:\\Users\\L094540\\IdeaProjects\\Browsers\\Firefox_53.0_
64bit\\browser\\features\\e10srollout@mozilla.org.xpi","e":true,"v":"1.14","st":1492142093000},"firefox@getpocket.com":{"d":"C:\\Users\\L094540\\IdeaProjects\\Browsers\\Firefox_53.0_
64bit\\browser\\features\\firefox@getpocket.com.xpi","e":true,"v":"1.0.5","st":1492142093000},"webcompat@mozilla.org":{"d":"C:\\Users\\L094540\\IdeaProjects\\Browsers\\Firefox_53.0_6
4bit\\browser\\features\\webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1492142093000}},"winreg-app-user":{"esso@oracle.com":{"d":"C:\\Program Files (x86)\\Passlogix\\v-GO SSO\\H
elper\\Web\\Firefox Extension","e":false,"v":"7.2.0.145","st":1487043753357,"mt":1385998466000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Users\\L094540\\Idea
Projects\\Browsers\\Firefox_53.0_64bit\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"53.0","st":1492142093000}}}
1493265400974   addons.xpi      DEBUG   getInstallState changed: true, state: {}
1493265401063   addons.xpi-utils        DEBUG   Opening XPI database C:\Users\L094540\AppData\Local\Temp\rust_mozprofile.2UB05FyndPHr\extensions.json
1493265401071   addons.xpi-utils        DEBUG   Successfully read XPI database
1493265401076   addons.xpi-utils        DEBUG   Add-on aushelper@mozilla.org removed from app-system-defaults
1493265401079   DeferredSave.extensions.json    DEBUG   Save changes
1493265401080   addons.xpi-utils        DEBUG   Add-on e10srollout@mozilla.org removed from app-system-defaults
1493265401086   DeferredSave.extensions.json    DEBUG   Save changes
1493265401087   addons.xpi-utils        DEBUG   Add-on firefox@getpocket.com removed from app-system-defaults
1493265401088   DeferredSave.extensions.json    DEBUG   Save changes
1493265401088   addons.xpi-utils        DEBUG   Add-on webcompat@mozilla.org removed from app-system-defaults
1493265401089   DeferredSave.extensions.json    DEBUG   Save changes
1493265401089   addons.xpi-utils        DEBUG   Add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} removed from app-global
1493265401090   DeferredSave.extensions.json    DEBUG   Save changes
1493265401091   addons.xpi-utils        DEBUG   Add-on esso@oracle.com removed from winreg-app-user
1493265401092   DeferredSave.extensions.json    DEBUG   Save changes
1493265401165   addons.xpi      DEBUG   Loading bootstrap scope from C:\Users\L094540\IdeaProjects\Browsers\Firefox_53.0_64bit\browser\features\aushelper@mozilla.org.xpi
1493265401190   addons.xpi      DEBUG   Calling bootstrap method uninstall on aushelper@mozilla.org version 2.0
1493265401192   addons.manager  DEBUG   Registering startup change 'uninstalled' for aushelper@mozilla.org
1493265401198   addons.xpi      DEBUG   Loading bootstrap scope from C:\Users\L094540\IdeaProjects\Browsers\Firefox_53.0_64bit\browser\features\e10srollout@mozilla.org.xpi
1493265401226   addons.xpi      DEBUG   Calling bootstrap method uninstall on e10srollout@mozilla.org version 1.14
1493265401226   addons.manager  DEBUG   Registering startup change 'uninstalled' for e10srollout@mozilla.org
1493265401228   addons.xpi      DEBUG   Loading bootstrap scope from C:\Users\L094540\IdeaProjects\Browsers\Firefox_53.0_64bit\browser\features\firefox@getpocket.com.xpi
1493265401304   addons.xpi      DEBUG   Calling bootstrap method uninstall on firefox@getpocket.com version 1.0.5
1493265401306   addons.manager  DEBUG   Registering startup change 'uninstalled' for firefox@getpocket.com
1493265401308   addons.xpi      DEBUG   Loading bootstrap scope from C:\Users\L094540\IdeaProjects\Browsers\Firefox_53.0_64bit\browser\features\webcompat@mozilla.org.xpi
1493265401317   addons.xpi      DEBUG   Calling bootstrap method uninstall on webcompat@mozilla.org version 1.0
1493265401318   addons.manager  DEBUG   Registering startup change 'uninstalled' for webcompat@mozilla.org
1493265401320   addons.xpi      ERROR   Failed to process extension changes at startup: TypeError: aAddon._installLocation is undefined (resource://gre/modules/addons/XPIProvider.jsm
:718:1) JS Stack trace: canRunInSafeMode@XPIProvider.jsm:718:1 < callBootstrapMethod@XPIProvider.jsm:4823:76 < processFileChanges@XPIProviderUtils.js:2142:9 < checkForChanges@XPIProv
ider.jsm:3760:34 < startup@XPIProvider.jsm:2793:25 < callProvider@AddonManager.jsm:272:12 < _startProvider@AddonManager.jsm:756:5 < startup@AddonManager.jsm:938:9 < startup@AddonMana
ger.jsm:3129:5 < observe@addonManager.js:65:9
1493265401322   addons.xpi      DEBUG   No changes found
1493265401323   addons.xpi      DEBUG   Add-ons list is invalid, rebuilding
1493265401323   addons.xpi-utils        DEBUG   Deleting add-ons list
1493265401328   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1493265401329   addons.manager  DEBUG   Provider finished startup: XPIProvider
1493265401329   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1493265401329   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1493265401330   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1493265401331   addons.manager  DEBUG   Starting provider: GMPProvider
1493265401353   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1493265401353   addons.manager  DEBUG   Provider finished startup: GMPProvider
1493265401353   addons.manager  DEBUG   Starting provider: PluginProvider
1493265401354   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1493265401354   addons.manager  DEBUG   Provider finished startup: PluginProvider
1493265401355   addons.manager  DEBUG   Completed startup sequence
1493265401829   DeferredSave.extensions.json    DEBUG   Starting timer
1493265401865   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1493265401865   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1493265401865   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
1493265401911   DeferredSave.extensions.json    DEBUG   Starting write
1493265402229   DeferredSave.extensions.json    DEBUG   Write succeeded
1493265402230   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 19
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1493265403648   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1493265403648   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1493265403649   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
Apr 27, 2017 9:26:44 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
2017-04-27 09:26:45.217 ←[32m[INFO]←[m [AbstractTest.abstractTest_SetUp.64] - SetUp Successfull. Driver: FirefoxDriver: firefox on ANY (2e9cf9f9-bc21-4fca-8c93-c946c0a0bc10)

```

I'm not sure if this is an issue so I didn't want to open a new issue. 
I often get this error while driver is executing commands, sometimes very often (after every test method or so) and it hangs the test execution 
```
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListSh
ortcut.app]
```
Couldn't find any information with regards to this error.


My current setup is as follows:
```
            log.info("Building firefox driver.");

            LoggingPreferences preferences = new LoggingPreferences();
            preferences.enable("INFO", Level.INFO);

            DesiredCapabilities caps = DesiredCapabilities.firefox();
            caps.setCapability(CapabilityType.BROWSER_NAME, "firefox");
            caps.setCapability(CapabilityType.BROWSER_VERSION, "53.0");
//            caps.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
//            caps.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
//            caps.setCapability(CapabilityType.SUPPORTS_JAVASCRIPT, true);
//            caps.setCapability(CapabilityType.HAS_NATIVE_EVENTS, true);
            caps.setCapability(CapabilityType.LOGGING_PREFS, preferences);
//            caps.setCapability(CapabilityType.ENABLE_PROFILING_CAPABILITY, true);
            caps.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
            caps.setCapability(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, 0);
            caps.setPlatform(Platform.WINDOWS);
            caps.setCapability("marionette", true);

            ProfilesIni profilesIni = new ProfilesIni();
            FirefoxProfile ffprofile = profilesIni.getProfile(firefoxProfileName);
            ffprofile.setAcceptUntrustedCertificates(true);
            ffprofile.setAssumeUntrustedCertificateIssuer(true);
            ffprofile.setPreference("enableNativeEvents", true);
            ffprofile.setPreference("disableAddons", true);
            ffprofile.setPreference("app.update.enabled", false);
            ffprofile.setPreference("app.update.service.enabled", false);
            ffprofile.setPreference("app.update.auto", false);
            ffprofile.setPreference("app.update.staging.enabled", false);
            ffprofile.setPreference("app.update.silent", false);
            ffprofile.setPreference("media.gmp-provider.enabled", false);
            ffprofile.setPreference("extensions.update.enabled", false);
            ffprofile.setPreference("extensions.update.autoUpdateDefault", false);
            ffprofile.setPreference("lightweightThemes.update.enabled", false);

            FirefoxOptions options = new FirefoxOptions();
            options.setBinary(browserBinary);
            options.setProfile(ffprofile);
            options.setLogLevel(Level.SEVERE);

            System.setProperty("webdriver.gecko.driver", driverBinary);
```

**Comment by whimboo** [comment]
All those warnings/failures you can see here in the output are Firefox internal. The same applies to the listed add-ons. Those are the ones integrated in Firefox directly. So you don't have to worry about those.

Also a couple of the prefs you are setting yourself will be set by geckodriver anyway. So you can remove a couple of those. Just compare your list with the following one:

https://github.com/mozilla/geckodriver/blob/2e0054b90ecf1acbe8b442af54441e3cc746933f/src/prefs.rs

Please also have a look at issue #619. We might want to just stop the JS logging from the browser, which can be annoying.

**Comment by whimboo** [comment]
So I had a look into the logging capabilities of Firefox and the problem we have is that mostly each component can define it's own logger with a specific level. Means the log level of the root logger is not taking into account. Here an example of the addons logger:

https://dxr.mozilla.org/mozilla-central/rev/0b77ed3f26c5335503bc16e85b8c067382e7bb1e/toolkit/mozapps/extensions/AddonManager.jsm#171

It means that whatever the root logger is set to we will see even DEBUG output from this logger, until we would set the level of the root logger to eg. Info during the initialization of Marionette. But that would not stop all the output during startup of Firefox.

The only option I currently see is to really disable any kind of logging for modules you do not need. Actually I have no idea where `addons.productaddons` is coming from. But at least its under `addons` and should be controllable via the preference `extensions.logging.enabled` set to `False`. Given that it is disabled by default, I wonder where it could be enabled. It's not listed in your code above.

**Comment by whimboo** [comment]
@andreastt, I wonder if we should at least update the root logger level dependening on which log level we allow for Marionette. So that once Marionette has been initialized, we only log what the user has allowed.

**Comment by SergioLeone** [comment]
@whimboo thank you for your input. You are correct, I don't have any browser logging enabled anywhere in my code except for the setup I've specified above.
However, I've tried explicitly providing this preference ` ffprofile.setPreference("extensions.logging.enabled", false);` and I'm getting the following exception `Java.lang.IllegalArgumentException: Preference extensions.logging.enabled may not be overridden: frozen value=true, requested value=false`

**Comment by whimboo** [comment]
Hm, are you using the Java or Javascript binding? At least for the former one I can see that a lot of preferences are frozen which will cause those massive log output:

https://github.com/SeleniumHQ/selenium/blob/282e7e882782c8ef18ec418212eba10f30dab9ed/javascript/firefox-driver/webdriver.json

**Comment by SergioLeone** [comment]
@whimboo I'm using java bindings.

**Comment by whimboo** [comment]
So you will have to do some investigation on your side with the Java bindings why this preference is locked. Maybe @barancev can help, given that he already contributed to the Java bindings in the Selenium repository.

**Comment by barancev** [comment]
One can't change "frozen" preferences in a custom profile due to legacy FirefoxDriver restrictions.

But geckodriver provides a better way to pass preferences without creating a custom profile.
```
FirefoxOptions options = new FirefoxOptions();
options.addPreference("extensions.logging.enabled", false);
WebDriver driver = new FirefoxDriver(options);
```
It should allow to pass any preferences, there are no restrictions on the binding side.

**Comment by whimboo** [comment]
Btw is there a reason why `extensions.logging.enabled` is True by default?

**Comment by whimboo** [comment]
Maybe it was enabled due to the former FirefoxDriver which was implemented as an extension, and with extension logging it was possible to see failures in loading it? Now with Marionette in-place there is no extension anymore. So I would say that it should not turned on by default.

**Comment by whimboo** [comment]
Well, now I see the point. When using Geckodriver the profile class shouldn't be used at all, but every preference has to be passed via `FirefoxOptions`.

@SergioLeone, does the above proposal fixes your issue with the logging output? 

What else remains for this issue on your side? I think that we can close it, or?

**Comment by SergioLeone** [comment]
I have just tried the fix proposed by @barancev and it gives the same exception.

```
DesiredCapabilities caps = DesiredCapabilities.firefox();
caps.setCapability(CapabilityType.BROWSER_NAME, "firefox");
caps.setCapability(CapabilityType.BROWSER_VERSION, "53.0");
caps.setCapability(CapabilityType.LOGGING_PREFS, preferences);
caps.setCapability(CapabilityType.ENABLE_PROFILING_CAPABILITY, true);
caps.setCapability(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, 1);
caps.setPlatform(Platform.WINDOWS);

String profilePath = "C:\\Users\\L094540\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\pj8i6838.luke.skywalker";
FirefoxProfile ffprofile = new FirefoxProfile(new File(profilePath));

FirefoxOptions options = new FirefoxOptions();
options.addPreference("extensions.logging.enabled", false);

return new FirefoxDriver(options.addTo(caps));

getting:
`java.lang.IllegalArgumentException: Preference extensions.logging.enabled may not be overridden: frozen value=true, requested value=false`

```

**Comment by SergioLeone** [comment]
Sorry, my bad, I was still passing custom profile through options via `options.setProfile(ffProfile)`
After I removed this line I'm not able to see addons logs anymore.

**Comment by whimboo** [comment]
Good, and with GMP disabled, I assume you do no longer have the issues as described in the initial comment?

**Comment by SergioLeone** [comment]
Yes, so far so good. At least for now I don't see the driver attempting gmp update downloads. 
I still have an issue with tests hanging, but it seems like testng dataprovider issue, not geckodriver (Unfortunately I can not verify my tests on another browser to be sure completely so I'll have to dig into this further.)

Thank you @whimboo and @barancev for the help, have been fighting with this for the past two days.

**Comment by nir20ane** [comment]
@whimboo , @SergioLeone 

I am facing the same issue:

Firefox 52.0
Gecko driver 15.0
Selenium 3.3

	System.setProperty("webdriver.gecko.driver","\\geckodriver-v0.15.0-win64/geckodriver.exe");
	FirefoxProfile firefoxProfile = new FirefoxProfile();       
	firefoxProfile.setPreference("browser.helperApps.alwaysAsk.force", false);
	firefoxProfile.setPreference("browser.download.folderList",2);
	firefoxProfile.setPreference("browser.download.manager.showWhenStarting",false);
	firefoxProfile.setPreference("browser.download.panel.shown",false);
        firefoxProfile.setPreference("extensions.blocklist.enabled", false);
	firefoxProfile.setPreference("browser.download.manager.alertOnEXEOpen", false);
	firefoxProfile.setPreference("browser.download.manager.focusWhenStarting", false);
	firefoxProfile.setPreference("browser.download.manager.useWindow", true);
	firefoxProfile.setPreference("browser.download.manager.closeWhenDone", true);
	firefoxProfile.setPreference("media.gmp-manager.cert.requireBuiltIn",false);
	firefoxProfile.setPreference("media.gmp-manager.cert.checkAttributes",false);
	firefoxProfile.setPreference("media.gmp-provider.enabled",false);
	firefoxProfile.setPreference("media.gmp-widevinecdm.enabled",false);
	firefoxProfile.setPreference("media.gmp-widevinecdm.visible",false);
	firefoxProfile.setPreference("media.gmp.trial-create.enabled",false);

DesiredCapabilities dc = DesiredCapabilities.firefox(); 
FirefoxOptions options = new FirefoxOptions();
options.addPreference("log", "{level: trace}");
options.setBinary("C:/Program Files (x86)/Mozilla Firefox/firefox.exe");
//options.addPreference("extensions.logging.enabled", false);
dc.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
dc.setCapability("marionette", true);
dc.setCapability("moz:firefoxOptions", options);
driver = new FirefoxDriver(dc);
baseURL = "http://"; 		
driver.manage().timeouts().implicitlyWait(8000, TimeUnit.SECONDS);
driver.manage().window().maximize();

My Log:

1493190654998   addons.productaddons    INFO    sending request to: https://aus5.mozilla.org/update/3/GMP/53.0/20170413192749/WINNT_x86_64-msvc-x64/en-US/release/Windows_NT%206.1.1.0
%20(x64)/default/default/update.xml
1493190656309   addons.productaddons    INFO    Completed downloading document
1493190656675   addons.productaddons    INFO    downloadXHR File download. status=200

Please help me in resolving this

**Comment by whimboo** [comment]
@nir20ane please read through the issue first before commenting me too. The answer can be found here: https://github.com/mozilla/geckodriver/issues/686#issuecomment-297694079. And what I read you are exactly doing the same.

**Comment by nir20ane** [comment]
I am not passing any custom profile here. Could you please help me in letting me know the mistake? thank you.

**Comment by barancev** [comment]
Yes you do:
```
dc.setCapability(FirefoxDriver.PROFILE, firefoxProfile);
```
Use FirefoxOptions to pass all the required preferences.

**Comment by nir20ane** [comment]
Thank you very much for your help @barancev , @whimboo. It works now.

**Comment by javaversion** [comment]
Hi guys,

I'am using Firefox 47.0.1 with selenium  3.4.0

Could you advise how to change "frozen" preferences if we don't use  geckodriver? 
I would like to turn off all prefs related to GMP.
If my understanding is correct FirefoxOptions is to be used with geckodriver?

Any help will be highly appreciated.

**Comment by whimboo** [comment]
@javaversion not sure what else beside geckodriver you want to use?

**Comment by andreastt** [comment]
@javaversion Firefox 47 isn’t supported by geckodriver. You can set Firefox preferences through the `moz:firefoxOptions` dictionary. See the README for details.
