### ISSUE TITLE
Method Navigate().GoToUrl("url") does not work with GeckoDriver 0.16.0

### ISSUE THREAD

**Issue by vas1l3k** [mozilla/geckodriver#688]
## Firefox Version
53.0 (64 bit)

## Platform
Windows 10

## Other
GeckoDriver 0.16.0
Selenium 3.4

## Steps to reproduce
When I am trying to run this code from Visual Studio
` driver.Navigate().GoToUrl("https://www.google.com");`
Firefox starts and then URL adress is not put to the URL bar, so there is only blank screen and nothing happened

The last GeckoDriver where `Navigate().GoToUrl("url")` works for me is 0.13.0

**Comment by andreastt** [comment]
I’m sorry, but I can’t guess from the information you have provided what is wrong. You were asked to include a trace-level log from geckodriver in the issue template, but that’s missing.

**Comment by Twyllo** [comment]
Try with 32bit firefox

**Comment by Sakatox** [comment]
Just chiming in to say Windows 7 is also affected.

**Comment by vas1l3k** [comment]
When debugging this appears after `driver.Navigate().GoToUrl("https://www.google.com");` is executed

![gecko](https://cloud.githubusercontent.com/assets/28051174/25469108/9d70349e-2b1a-11e7-893c-7867eded13fa.png)

Is that trace-level log u need?

**Comment by andreastt** [comment]
@Twyllo Unlike the IEDriver, geckodriver does not require you to use the same 32-bit or 64-bit architecture for Firefox because they communicates via TCP. You can use a 32-bit with geckodriver with a 64-bit Firefox or vice versa.

@Sakatox You provided no evidence that Windows 7 is affected. Please include a trace-level geckodriver log.

@vas1l3k Please include a trace-level geckodriver log. I can’t guess from a screenshot what is wrong.

**Comment by vas1l3k** [comment]
I am including screen with trace-level geckodriver log
![trace](https://cloud.githubusercontent.com/assets/28051174/25516435/e6e58ed2-2bea-11e7-9832-55d34b3056da.png)

**Comment by andreastt** [comment]
@vas1l3k If you look near the bottom of that log you will see `→ POST /session//url {"url":"https://www.google.cz/"}`. This _should_ say `/session/<SESSION ID>/url`. This means that your language binding is not picking up the session ID that is being returned to it.

What language binding are you using? Are you sure you have the most recent version of it?

**Comment by vas1l3k** [comment]
How Could I found out which version of language binding I have, please?

**Comment by andreastt** [comment]
@vas1l3k I… don’t know?

**Comment by Twyllo** [comment]
@andreastt Yes, but im talking about trying with 32bit firefox not geckodriver. Same code worked for me on 32bit ff while on 64bit didnt or worked worse.

**Comment by andreastt** [comment]
@Twyllo Unlike the IEDriver, whether you use 32-bit or 64-bit version of geckodriver or Firefox does not matter.

**Comment by AutomatedTester** [comment]
@vas1l3k 

I am closing this bug for now as this appears to be a bug in your binding that you are using. If you have more detail that we can act on let us know and we can try reopen this bug.

**Comment by RoakyWood** [comment]
Same issue, please answer the question.
