### ISSUE TITLE
incorrect behavior of "element scroll" capability (gecko 0.16.0)

### ISSUE THREAD

**Issue by SergioLeone** [mozilla/geckodriver#691]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
53.0 64-bit

## Platform
Windows 7 64-bit

## Steps to reproduce -
`caps.setCapability(CapabilityType.ELEMENT_SCROLL_BEHAVIOR, 1);`

Actual: Setting this capability to either 0 or 1 has no difference whatsoever, and the driver always scrolls the element to top of viewport.
Expected: should scroll to bottom if set to 1

**Comment by andreastt** [comment]
I don’t know what `CapabilityType.ELEMENT_SCROLL_BEHAVIOR`, but it is not supported by geckodriver.

**Comment by SergioLeone** [comment]
@andreastt probably it was there for early firefox driver a log time ago, thought it is still working. 

From selenium wiki (https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities):

> elementScrollBehavior 	integer 	Allows the user to specify whether elements are scrolled into the viewport for interaction to align with the top (0) or bottom (1) of the viewport. The default value is to align with the top of the viewport. Supported in IE and Firefox (since 2.36)

**Comment by andreastt** [comment]
Hm, I see. Thanks for the information on where it comes from.

We don’t intend to support that capability. WebDriver by default scrolls an element in to the viewport, if it is not in view already, to the bottom.
