### ISSUE TITLE
browser.helperApps.alwaysAsk.force not working (To avoid download file popup)

### ISSUE THREAD

**Issue by newton143** [mozilla/geckodriver#705]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox Nightly 55.0a1 (2017-04-19) (64-bit)

## Platform
Windows

## Language
C#

## Steps to reproduce -
FirefoxOptions options = new FirefoxOptions();
options.UseLegacyImplementation = false;
                        options.UseLegacyImplementation = false;
                        options.SetPreference("browser.download.folderList", 2);
                        options.SetPreference("browser.download.manager.showWhenStarting", false);
                        options.SetPreference("browser.download.dir", Settings.DownloadDirectory);
                      //options.SetPreference("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream");
                        options.SetPreference("browser.helperApps.neverAsk.openFile", "");
                        options.SetPreference("browser.helperApps.alwaysAsk.force", false);
                        options.SetPreference("browser.download.manager.alertOnEXEOpen", false);
                        options.SetPreference("browser.download.manager.focusWhenStarting", false);
                        options.SetPreference("browser.download.manager.useWindow", false);
                        options.SetPreference("browser.download.manager.showAlertOnComplete", false);
                        options.SetPreference("browser.download.manager.closeWhenDone", true);
                        options.SetPreference("pdfjs.disabled", true);
FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(Settings.DriverDirectory, "geckodriver.exe");
                        service.FirefoxBinaryPath = @"C:\Program Files\Nightly\firefox.exe";
WebDriver = new FirefoxDriver(service, options, time);

##Description
Im trying not to list all MIME Types  (http://www.freeformatter.com/mime-types-list.html) in my code options.SetPreference("browser.helperApps.neverAsk.saveToDisk", "application/octet-stream");

so i'm using options.SetPreference("browser.helperApps.alwaysAsk.force", false) but i'm getting the download popup while trying to download from the url  https://www.microsoft.com/en-us/download/details.aspx?id=30653

Please help me

**Comment by andreastt** [comment]
If I consult about:config on my Firefox installation, `browser.helperApps.alwaysAsk.force` is by default false. So I don’t expect this to change Firefox’ behaviour in any noteworthy way.

Perhaps you intend to set it to true?

**Comment by whimboo** [comment]
I don't think that there is a way to not cause the unknown content type window to appear. As Andreas said setting this pref to `true` will always bring up this dialog. The way how you could solve this is to figure out the MIME type before you work with the file in Firefox. In most cases the test should know about it.
