### ISSUE TITLE
ExpectedConditions bug

### ISSUE THREAD

**Issue by iquinity** [mozilla/geckodriver#708]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
53.0

## Platform
Windows

## Steps to reproduce -
I have a  dropdown menu and then in the drop down menu i want to click the Logout element simple as that. If u use this method to click Logout it works `driver.findElement(By.linkText("Logout")).click();` however, if i use `wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Logout"))).click();` it doesn't work and throws a timeout exception as if it can't find the element. Investigating this case i found out that it can't find element that are located in a span either (Don't really know how it is connected, but the important part is that it finds it easy in other browsers). After that i went a little bit further and left the `driver.findElement(By.linkText("Logout"));` method be. After this method i wanted to check the URL after it logs me out as follows: `wait.until(ExpectedConditions.urlToBe("https://whateverexample"));` and then in this case i get the following error: `org.openqa.selenium.ElementNotInteractableException: `

**Comment by andreastt** [comment]
The expected condition utility classes are a client-side feature and not implemented by geckodriver. The error you are seeing is new as of geckodriver 0.16.0 and replaces the old `ElementNotVisibleException` you would have seen in this case before.

**Comment by jayjay86** [comment]
Is there any proposal for replacing expected conditions? I need an option to upgrade...

**Comment by andreastt** [comment]
I don’t understand the question. Expected conditions is a Selenium utility class offered by _Selenium_, using WebDriver’s/geckodriver’s primitives.
