### ISSUE TITLE
Use Travis to cross-compile

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#71]
It should be possible, with a little effort, to get Travis cross-compiling wptrunner for other platforms. This is a prerequisite for making releases using wptrunner.

**Comment by andreastt** [comment]
Do we know of any other Rust programs which does this that we can draw inspiration from?

**Comment by jgraham** [comment]
https://github.com/japaric/rust-cross/blob/master/.travis.yml

**Comment by filmaj** [comment]
would love to see regular windows releases!

**Comment by andreastt** [comment]
See #72 for also making releases using Travis.
