### ISSUE TITLE
Geckodriver cannot locate a remote web element C#

### ISSUE THREAD

**Issue by MissNixxi** [mozilla/geckodriver#710]
## Firefox Version
53

##geckodriver
16

## Platform
Windows

## Steps to reproduce -
Logs into website (this is not open to public I cannot give you site details)
Loads page
We send in the information that is required to find the remote element.  See method below
```
public void ClickCellByColumnHeaderAndRowIndex(string dataIndex, int RowIndex, IWebElement gridElement)
        {
            if (theGrid != gridElement)
            {
                CacheGridColumnInformation(gridElement);
            }

            var element = driver.FindElements(By.XPath("//*[contains(text(),'Loading...')]"));
            foreach (IWebElement item in element)
            {
                WaitIWebElementNotVisible(item);
            }

            int colIndex = gridColumnIndex[dataIndex];

            RemoteWebElement currentEventCell =
                (RemoteWebElement)
                gridElement.FindElements(
                    By.CssSelector("tr[data-recordindex=\"" + RowIndex + "\"] td:nth-child(" + colIndex + ")"))[0];
            var ScrollIt = currentEventCell.LocationOnScreenOnceScrolledIntoView;
            WaitElementToBeClickable(currentEventCell);
            currentEventCell.Click();
        }
```
Should find the element and click on the cell.  I am getting this exception below: 
`threw exception: 

`OpenQA.Selenium.NoSuchElementException: Could not find element by: By.CssSelector: input[name="FunctionRoomOptionId"]
StackTrace (I would do the geckodriver however I do not use capabilities and I am not find any .Net documentation on how to add it):

at OpenQA.Selenium.Support.PageObjects.DefaultElementLocator.LocateElement(IEnumerable`1 bys)
at OpenQA.Selenium.Support.PageObjects.WebElementProxy.get_Element()
at OpenQA.Selenium.Support.PageObjects.WebElementProxy.Invoke(IMessage msg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at OpenQA.Selenium.IWebElement.SendKeys(String text)

Running FF 47.0.1 webdriver version 2.53.1 did not have this issue.  

Please see attached txt file containing html.
[grid.txt](https://github.com/mozilla/geckodriver/files/976847/grid.txt)

**Comment by andreastt** [comment]
Firefox 47.0.1 and Selenium 2.53.1 is absolutely not supported, please see the README.

In the case where it fails to find the element, it is usually because the element doesn’t exist in the DOM.

**Comment by MissNixxi** [comment]
@andreastt  Did you actually read the question.  I upgraded to firefox 53, selenium 3.4, geckodriver 16.  Using legacy 47.0.1 FF and Selenium 2.5.3 the remote webelements were located, after update all tests with remote elements cannot be found and are failing.

**Comment by andreastt** [comment]
Sorry, I did not read the entire issue in its entirety before making that comment.

Can you provide a minimal HTML document where the selector fails to find the element? It would be great if you could minimise the test case.

As I said, the most common cause for this error is that the element does, indeed, not exist in the DOM.

**Comment by MissNixxi** [comment]
@andreastt once the click occurs on the cell the input attribute is then added to the bottom of the dom.  What I am thinking is it is not recognizing the dom change.  The html code is extremely long and would be extremely long to show what I mean without posting thousands of lines once before click and then again when dom changes and adds the input attribute.

**Comment by andreastt** [comment]
That’s why it would be great if you could debug this and come up with a minimised HTML test case. Otherwise I’m sorry to say I can’t help you.

**Comment by MissNixxi** [comment]
@andreastt  yikes I'll do my best. Ext-js is the pain in the rear when it comes to html.

**Comment by MissNixxi** [comment]
@andreastt I have updated with the html inside a txt file.

**Comment by andreastt** [comment]
I had a quick look at the attached HTML document, and I can’t find an `<input>` element with the ID `FunctionRoomOptionId` in it. In fact, I don’t see any elements with that ID.

**Comment by MissNixxi** [comment]
@andreastt  sorry about that.  It is happening with both elements I must of grabbed the wrong one.  It is literally the same issue replacing the name of functionroomoptionid with taxgroup

**Comment by andreastt** [comment]
I expect you included an HTML document which requires interaction for some other element to appear? What is needed is a static HTML document with a DOM structure where the desired element exists, but where geckodriver fails to locate it.

If the case is that geckodriver fails to locate the element _because_ interaction is needed to reveal it, you probably need to use a wait condition or a increase the implicit wait timeout.

**Comment by andreastt** [comment]
I expect you included an HTML document which requires interaction for some other element to appear? What is needed is a static HTML document with a DOM structure where the desired element exists, but where geckodriver fails to locate it.

If the case is that geckodriver fails to locate the element _because_ interaction is needed to reveal it, you probably need to use a wait condition or a increase the implicit wait timeout.

**Comment by AutomatedTester** [comment]
@MissNixxi Have you got a static HTML document where we can see this issue as asked for in the last comment?

**Comment by whimboo** [comment]
No further feedback from the reporter within 3 weeks. I'm going to close this issue for now. Once we get a testcase we can reopen the issue.
