### ISSUE TITLE
geckodriver must match with Firefox version release for compatibility

### ISSUE THREAD

**Issue by vairamsvsjdo** [mozilla/geckodriver#718]
## Firefox Version
53.0.0

## Platform
windows 7, windows 10.

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:
https://bugzilla.mozilla.org/show_bug.cgi?id=1362609

 - [x ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by jgraham** [comment]
This isn't an issue report; it's a link to an invalid bug.

AFAICT your problem is that you are trying to upgrade Firefox or Geckodriver without using a matching selenium release. It's expected that old versions of selenium will not work at present as we converge on the W3C standard protocol.
