### ISSUE TITLE
Add cookie failed with InvalidCookieDomainError

### ISSUE THREAD

**Issue by vimagick** [mozilla/geckodriver#719]
Geckodriver version: 0.16.1
Firefox version: 53.0.2 (64-bit)
Python version: 2.7.13
Selenium version: 3.4.1
Platform: MacOS

## Steps to reproduce

```python
from selenium.webdriver import Firefox

ff = Firefox()
ff.get('https://github.com/')

print ff.get_cookies()

# the following cookie was chosen from above
ff.add_cookie({
    'domain': '.github.com',
    'expiry': None,
    'httpOnly': False,
    'name': '_gat',
    'path': '/',
    'secure': False,
    'value': '1'
})
```

```python
---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-112-d848e442d4c8> in <module>()
      6   u'path': u'/',
      7   u'secure': False,
----> 8   u'value': u'1'
      9 })

/Users/kev/.virtualenvs/selenium/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in add_cookie(self, cookie_dict)
    702
    703         """
--> 704         self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
    705
    706     # Timeouts

/Users/kev/.virtualenvs/selenium/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.pyc in execute(self, driver_command, params)
    250         response = self.command_executor.execute(driver_command, params)
    251         if response:
--> 252             self.error_handler.check_response(response)
    253             response['value'] = self._unwrap_value(
    254                 response.get('value', None))

/Users/kev/.virtualenvs/selenium/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.pyc in check_response(self, response)
    192         elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
    193             raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
--> 194         raise exception_class(message, screen, stacktrace)
    195
    196     def _value_or_default(self, obj, key, default):

WebDriverException: Message: ReferenceError: InvalidCookieDomainError is not defined
```

Chrome, Safari and PhantomJS allow leading dot in `domain`.
Firefox doesn't allow it.

**Comment by andreastt** [comment]
This appears to be a programming error in the Selenium Python client. Please report the issue there.

**Comment by AutomatedTester** [comment]
this is a bug in marionette. see https://bugzilla.mozilla.org/show_bug.cgi?id=1362990

**Comment by andreastt** [comment]
Ignore my earlier comment. A generic `webdriver error` is being returned from the Marionette server because the `InvalidCookieDomainError` error is missing. It was the Python stacktrace that confused me.

**Comment by vimagick** [comment]
However, it shouldn't throw any exception.

```python
for i in ff.get_cookies():
    ff.add_cookie(i)
```

**Comment by andreastt** [comment]
> However, it shouldn't throw any exception.
> 
> ```python
> for i in ff.get_cookies():
>     ff.add_cookie(i)
> ```

That seems unrelated to the issue originally reported.

In any case, Marionette checks if `document.location.host` contains
the given domain, which it won’t if the domain contains a leading dot.
The dot is not part of the host.

Quoting the Marionette source code:

```js
    if (!opts.domain) {
      opts.domain = this.document.location.host;
    } else if (this.document.location.host.indexOf(opts.domain) < 0) {
      throw new InvalidCookieDomainError(
          "You may only set cookies for the current domain");
    }
```

**Comment by vimagick** [comment]
@andreastt Chrome browser allows leading dot.

**Comment by andreastt** [comment]
Yeah, that’s not really a good argument.

**Comment by andreastt** [comment]
Reading the WebDriver specification’s definition of [Add Cookie](https://w3c.github.io/webdriver/webdriver-spec.html#add-cookie), we shouldn’t limit cookies from being added for other domains. I wonder if this is the desired behaviour?

It’s also not clear to me if `.github.com` is a valid domain to create a cookie for.

Maybe @AutomatedTester can give some input.

**Comment by AutomatedTester** [comment]
Changing the bug from one issue to another is really poor form!

The original issue has now been fixed. 

As for why we limit to the current domain, this is a historic for when some drivers are written in JavaScript. We would need to investigate whether we want to support `.top.level.domain`.

You could raise an issue against https://github.com/w3c/webdriver
