### ISSUE TITLE
Use Travis to make releases

### ISSUE THREAD

**Issue by jgraham** [mozilla/geckodriver#72]
If we cross compile using travis, then we can also use the GH API to check if there is a new release tag associated with the current push, but no corresponding release and, if so, get it to upload the builds as the new release.

**Comment by andreastt** [comment]
As was pointed out in [bug 1216995](https://bugzilla.mozilla.org/show_bug.cgi?id=1216995) the dynamic builds using glibc we produce on one Linux system may not work on another. When we move to use Travis to make releases, I suggest we use statically compiled binaries backed by the musl C library. These builds are already available in #73.

**Comment by jgraham** [comment]
Note that the builds in #73 are debug mode, not release mode, so we want to change that for releases.

In general see https://docs.travis-ci.com/user/deployment/releases/ for how to fix this issue.
