### ISSUE TITLE
When click hide element show "ElementNotInteractableException"

### ISSUE THREAD

**Issue by crazy-canux** [mozilla/geckodriver#720]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0 (64-bit)

## Platform
CentOS 7.0

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [x] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

it's public website.

 - [x] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

this is the source code.

![capture](https://cloud.githubusercontent.com/assets/14313415/25791899/f0b8ba7a-33f5-11e7-8a15-8c42bafdcc01.PNG)

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

run it like this:

$ python script.py firefox
and you will see the error.

Don't know why the hide element can not be click?

**Comment by AutomatedTester** [comment]
WebDriver does not allow hidden elements to be hidden so GeckoDriver will not allow it. To get the elements in there you would need to click the element  with id `gbwa` first and then another click on the other elements.

**Comment by crazy-canux** [comment]
@AutomatedTester ， Thanks for response.
If you see the code, that's what I do. I did two click.
But, still doesn't work.

**Comment by AutomatedTester** [comment]
@crazy-canux unfortunately you put a screenshot of the code and when I looked that the html you need to click 2 elements and your elements appear . If you want us to look into this further you will need to give us a meaningful way to reproduce the issue.

As requested, we need a script we can run, not a screenshot of code, and the html.
