### ISSUE TITLE
GeckoDriver Selenium 3.3 - FF issue, WebDriverException handlers time out

### ISSUE THREAD

**Issue by Eyalc1974** [mozilla/geckodriver#721]
Recently we upgraded our Selenium C# binding , v3.4.0 and we are start using the Gecko Driver , so we are using v 0.16.1, We notice that after click that open new window (FF) we got WebDriverException handlers time out, pops from : driver.WindowHandles,

We are wondering if it is common issue or if you know how to workaround that issue?

## Firefox Version
53.0.2 (32bit)

## Platform
Windows 7

## Steps to reproduce -
Any website that has button in DOM that open new page, then use driver.WindowHandles

Exception:
The HTTP request to the remote WebDriver server for URL localhost:56195/session/c2c37bf7-7001-41dc-8a5a-75b7f6b60233‌​/… timed out after 60 seconds.
Stack Trace: 
 'HttpCommandExecutor.cs:line 121 at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(‌​Command commandToExecute) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\DriverServ‌​iceCommandExecutor.c‌​s:line 84 at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebD‌​river.cs:line 1177 at OpenQA.Selenium.Remote.RemoteWebDriver.get_WindowHandles() in c:\Projects\webdriver\dotnet\src\webdriver\Remote\RemoteWebD‌​river.cs'

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
This is impossible to say since you did not add a trace-level geckodriver log. It is certainly not expected to hang on getting the current window handles, but you have unfortunately not provided a reproducible bug report.

**Comment by Eyalc1974** [comment]
Reproduce steps are impossible since it is internal site, but can you explain me how to provide logs for GeckoDriver?

**Comment by andreastt** [comment]
You can see the README for how to configure the trace-level logs. Basically you need to pass the `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` object as part of your capabilities.

**Comment by Eyalc1974** [comment]
[GeckoLogs.txt](https://github.com/mozilla/geckodriver/files/985717/GeckoLogs.txt)

see logs attached, let me know if it fine with you,

**Comment by andreastt** [comment]
Those are the trace-level logs, but a lot of it appears to be missing.
Instead of copying it from the terminal, you should redirect the
process’ output to a file.

**Comment by Eyalc1974** [comment]
Hi 
Please see my code below, can you instruct me how to do it? (redirect console log to file)

public void Setup()
{
     var driverService = FirefoxDriverService.CreateDefaultService();
     driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
    driverService.HideCommandPromptWindow = false;                        
    driverService.SuppressInitialDiagnosticInformation = true;
    FirefoxOptions ffOpt = new FirefoxOptions();
    ffOpt.LogLevel = FirefoxDriverLogLevel.Trace;
    m_driver = new FirefoxDriver(driverService, ffOpt, TimeSpan.FromSeconds(60));
}

**Comment by andreastt** [comment]
I don’t know C#, so you’ll have to figure this out for yourself.
Maybe consult the client documentation?

**Comment by whimboo** [comment]
@Eyalc1974 do you have an update for us?

**Comment by Eyalc1974** [comment]
Hi 
Can you let me know for sure that GeckoDriver isworking fine in case you call to:
driver.WindowHandles()
While using Selenium 3.4.0 (.net binding) + latest FF 52.02(32bit) ? 
it is basic flow, Can you approve that that function is working fine? if yes you can close that case, 
You don't need any logs, you can use gecko with Selenium in case you have two windows open, just call to the above function and you should see the exception describe above in that thread, 

BTW - on Git page  "Marionette and geckodriver are not yet feature complete. This means that they do not yet offer full conformance with the WebDriver standard or complete compatibility with Selenium" , 
So you recommend to use right now that driver with latest FF? 

Thanks
Eyal

**Comment by whimboo** [comment]
Selenium Python bindings work just fine with Nightly:
```
    def test_page(self):
        self.driver.window_handles
```

1495102052290	geckodriver::marionette	TRACE	→ 27:[0,2,"getWindowHandles",{}]
1495102052297	Marionette	TRACE	0 -> [0,2,"getWindowHandles",{}]
1495102052299	Marionette	TRACE	0 <- [1,2,null,["2147483649"]]
1495102052301	geckodriver::marionette	TRACE	← [1,2,null,["2147483649"]]
1495102052302	webdriver::server	DEBUG	← 200 OK {"value":["2147483649"]}

As @andreastt said earlier, it looks like a problem with the Selenium .net# bindings. Otherwise I still miss a full code example and the full trace log. As long as you don't provide the information there is nothing we can do. 

We can reopen this issue if it turns out to be a problem with GeckoDriver. Right now I cannot see it.
