### ISSUE TITLE
How to change firefox profile preferences like "security.insecure_field_warning.contextual.enabled"

### ISSUE THREAD

**Issue by RSant0s** [mozilla/geckodriver#727]
## Firefox Version
53.0.2 (32-bit)

## geckodriver Version
0.16.1

## What happens
When I try to automate login on an unsafe page, the firefox opens a new tab "https://support.mozilla.org/1/firefox/53.0.2/WINNT/pt-PT/insecure-password".

How can I disable this? I think that property "security.insecure_field_warning.contextual.enabled" is related to this behavior but i don't know how i could disable it by python code.

I try the following code but without success:

[...]
firefox_driver = path_drivers + "geckodriver.exe"
profile = webdriver.FirefoxProfile()
profile.set_preference("security.insecure_field_warning.contextual.enabled", False)
return webdriver.Firefox(executable_path=firefox_driver, firefox_profile=profile)

The preference doesn't change, remains with True value.

Any idea?

Best regards,

Ruben Santos

**Comment by andreastt** [comment]
I suspect your client is not creating the `moz:firefoxOptions`
object correctly.  If you look at the README, it is possible to pass
preferences through a JSON Object instead of passing along an entire
profile.  I would file a bug against the client.

**Comment by RSant0s** [comment]
How can i do it in python?

**Comment by andreastt** [comment]
> How can i do it in python?

Consult your client’s documentation.

**Comment by whimboo** [comment]
This happens because the first entry of the autocomplete box seems to get clicked. When I do this manually I can clearly see that this mentioned support page gets opened. So if you select an entry from the autocomplete list make sure it's the correct one.
