### ISSUE TITLE
Selenium 3.4.0 Unable to find matching capabilities ON Raspberry Pi with 0.16.1

### ISSUE THREAD

**Issue by Quedgely** [mozilla/geckodriver#728]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
Firefox 45.9.0
Iceweasel 45.9.0 

## Platform
Raspbian 2017-04-10 (updated and upgraded as of 2017-05-08)
Raspberry Pi 3

## Steps to reproduce -
On a clean build of Raspbian run the following commands:
sudo update -y
sudo dist-upgrade -y
sudo apt-get install iceweasel
sudo pip3 install selenium

to install iceweasel 45.9.0 and selenium 3.4.1

Download geckodriver  0.16.1 for ARM from https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-arm7hf.tar.gz

Extract and save to /usr/local/bin
restart Pi and run the following Python script in Python 3

> from selenium import webdriver
> driver = webdriver.Firefox()
> 
> driver.get('http://google.com')
> print (driver.title)

this results in the same error as detailed in https://github.com/SeleniumHQ/selenium/issues/3884

**Comment by jgraham** [comment]
Unfortunately 45 is not a supported release. You could try setting `acceptInsecureCerts` to `false` in the capabilties; which might help.

**Comment by Quedgely** [comment]
Using version 0.15.0 has resolved the issue was 45 supported in it? 
Do you have a table of supported FireFox versions for each geckodriver version I can refer to?

**Comment by andreastt** [comment]
See https://github.com/mozilla/geckodriver#supported-firefoxen.

**Comment by gouessej** [comment]
@Quedgely I have a similar problem. We should ask Mozilla to provide pre-compiled binary files for ARM until Raspbian and Debian provides a more recent packaged version of Firefox. Firefox 53.0.2 is available as pre-compiled binary files for Linux 32-bit x86 and 64-bit amd64 but not for ARM. As far as I remember, it's possible to tell Selenium which version of Firefox to use by using the property webdriver.firefox.bin.
