### ISSUE TITLE
Marionette log entries are missing on Windows

### ISSUE THREAD

**Issue by KSKS** [mozilla/geckodriver#730]
## Firefox Version
Firefox Nightly 55.0a1 2017-05-09

## Platform
Windows 7

Geckodriver 0.16.0
webdriver.js 3.4.0

## Steps to reproduce -
Start geckodriver as a standalone process, with "--log trace" as argument
Use webdriver.js to connect to geckodriver, then start Firefox

Expected: The log from geckodriver shows Marionette entries
Actual: Marionette logs are missing on Windows

The same script running on OSX produced log with Marionette entries.

[osx.txt](https://github.com/mozilla/geckodriver/files/988403/osx.txt)
[win.txt](https://github.com/mozilla/geckodriver/files/988405/win.txt)

**Comment by andreastt** [comment]
In the Firefox instance that is started on Windows, can you pause the script and report back what value the `marionette.log.level` preference has in about:config?

**Comment by KSKS** [comment]
The value of `marionette.log.level` is `TRACE`. The value of `marionette.logging` is also `TRACE`.

**Comment by whimboo** [comment]
@KSKS can you please check again with geckodriver 0.18? The release 0.16 was a bit busted on Windows, which might have caused this problem. Thanks.

**Comment by whimboo** [comment]
No response from reporter. Closing the issue.
