### ISSUE TITLE
No "Nightly Features" on Firefox 55

### ISSUE THREAD

**Issue by MDTsai** [mozilla/geckodriver#733]
## Firefox Version
Firefox 55 Nightly, some build after 2017-05-02-03-02-11

## Platform
Windows 7, 64-bit

## Others
Selenium Version:  3.4.1, python
Gecko Driver: 0.16.1

## Steps to reproduce -
1. Download and extract latest Nightly
2. Using:
```
    # Create a Firefox Binary from folder
    binary = FirefoxBinary("./firefox/firefox.exe")
    # Create Firefox WebDriver
    firefox = webdriver.Firefox(firefox_binary=binary)

    # Visit webcompat-ua-dummy, verify title and page
    firefox.get("http://webcompat-ua-dummy.schub.io/")
```
expect to see Firefox image
3. Open about:support, no Nightly features

Here is the test result:
geckodriver 0.15.0 + Firefox 55 2017-05-02-03-02-11 works
geckodriver 0.15.0 + Firefox 55 2017-05-04-03-03-20 with Nightly Feature but can't get URL
geckodriver 0.16.1 + Firefox 55 2017-05-04-03-02-11 no Nightly Feature but can get URL
geckodriver 0.16.1 + Firefox 55 2017-05-04-03-03-20 no Nightly Feature but can get URL

**Comment by AutomatedTester** [comment]
Speaking to a few people we don't appear to have anything deployed at the moment. At any rate, Marionette or GeckoDriver or Selenium is not doing anything to block that feature in Firefox. I suggest raising a Firefox issue on Bugzilla

**Comment by MDTsai** [comment]
@AutomatedTester geckodriver 0.16.1 + Firefox Nightly works for me on ubuntu 16.04, but not on Windows 7. Just leave information here to see if anyone also have such problem.

**Comment by andreastt** [comment]
@MDTsai Can you file a separate issue about that and attach a trace-level geckodriver log to it?

**Comment by whimboo** [comment]
Btw a bug got filed for this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1364385

Please note that we might have general issues with Marionette/Geckodriver on Windows those days.

**Comment by MDTsai** [comment]
Thanks @whimboo, I also file this issue on bugzilla. Please let me know if I can help on debug or clarify anything.
