### ISSUE TITLE
New connections will no longer be accepted after switching content

### ISSUE THREAD

**Issue by littlerunavay** [mozilla/geckodriver#736]
## Firefox Version
53.0.02

## Platform
Windows 10 x64

## Description of issue
Marionette is giving information that new connections will no longer be accepted after the WebDriver  is switching content.

## Steps to reproduce -

`1494804793701	Marionette	INFO	New connections will no longer be accepted`

Java code snippet:

<pre><code>
public void deleteOffer(){
	driver.findElement(By.xpath("html/body/main/div/div/div/div[2]/a[2]")).click();
	driver.switchTo().alert().accept();
	driver.switchTo().defaultContent();
	driver.findElement(By.xpath("html/body/div[1]/div")).click();
}

**Comment by AutomatedTester** [comment]
This is an `INFO` message. The WebDriver spec only allows 1 connection the to the browser so this is just to let you know a session is in progress and we won't allow any more `newSession` commands

**Comment by andreastt** [comment]
To be clear, Marionette logs this when Firefox is quitting to notify you that the server isn’t accepting any further connections beyond this point.

It doesn’t have anything to do with connection limits; in fact Marionette supports multiple connections.
