### ISSUE TITLE
Context click options doesn't work with Mozilla Firefox

### ISSUE THREAD

**Issue by prabhurohith** [mozilla/geckodriver#738]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
54.0 and 53.0.2

## Platform
Windows

## Steps to reproduce -
- Try to do context click using selenium web driver 

Actual Result
- The context click doesn't happen on the web element

Trace Logs

Trying context click here

```
1494852411301	webdriver::server	DEBUG	â†’ POST /session/e1560ed1-526d-41f5-8bb1-8d58b9b564a3/actions {"actions":[{"id":"default mouse","type":"pointer","parameters":{"pointerType":"mouse"},"actions":[{"duration":100,"x":0,"y":0,"type":"pointerMove","origin":{"ELEMENT":"41a17aae-b503-4905-aec3-37afda7a0157","element-6066-11e4-a52e-4f735466cecf":"41a17aae-b503-4905-aec3-37afda7a0157"}},{"button":2,"type":"pointerDown"},{"button":2,"type":"pointerUp"}]}]}
1494852411302	geckodriver::marionette	TRACE	â†’ 331:[0,242,"performActions",{"actions":[{"actions":[{"duration":100,"origin":{"element-6066-11e4-a52e-4f735466cecf":"41a17aae-b503-4905-aec3-37afda7a0157"},"type":"pointerMove","x":0,"y":0},{"button":2,"type":"pointerDown"},{"button":2,"type":"pointerUp"}],"id":"default mouse","parameters":{"pointerType":"mouse"},"type":"pointer"}]}]
1494852411303	Marionette	TRACE	0 -> [0,242,"performActions",{"actions":[{"actions":[{"duration":100,"origin":{"element-6066-11e4-a52e-4f735466cecf":"41a17aae-b503-4905-aec3-37afda7a0157"},"type":"pointerMove","x":0,"y":0},{"button":2,"type":"pointerDown"},{"button":2,"type":"pointerUp"}],"id":"default mouse","parameters":{"pointerType":"mouse"},"type":"pointer"}]}]
1494852411455	Marionette	TRACE	0 <- [1,242,null,{}]
1494852411457	geckodriver::marionette	TRACE	â†? [1,242,null,{}]
1494852411457	webdriver::server	DEBUG	â†? 200 OK {"value": {}}
performed context click here
JavaScript error: resource://app/modules/WindowsJumpLists.jsm, line 403: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIJumpListShortcut.app]
1494852459632	webdriver::server	DEBUG	â†’ POST /session/e1560ed1-526d-41f5-8bb1-8d58b9b564a3/element {"value":"//span[contains(text(), 'Cancel all')]","using":"xpath"}
```

However when i tried to perform click action using Actions class it worked and below is stack trace for comparison

```
Trying context click here
1494852637183	webdriver::server	DEBUG	â†’ POST /session/3df2686b-cd6a-45d7-b2c8-ea22f97cd487/actions {"actions":[{"id":"default mouse","type":"pointer","parameters":{"pointerType":"mouse"},"actions":[{"duration":100,"x":0,"y":0,"type":"pointerMove","origin":{"ELEMENT":"f8834c5b-7317-47d9-bc4d-a62dae24928d","element-6066-11e4-a52e-4f735466cecf":"f8834c5b-7317-47d9-bc4d-a62dae24928d"}},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}]}]}
1494852637184	geckodriver::marionette	TRACE	â†’ 331:[0,242,"performActions",{"actions":[{"actions":[{"duration":100,"origin":{"element-6066-11e4-a52e-4f735466cecf":"f8834c5b-7317-47d9-bc4d-a62dae24928d"},"type":"pointerMove","x":0,"y":0},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}],"id":"default mouse","parameters":{"pointerType":"mouse"},"type":"pointer"}]}]
1494852637195	Marionette	TRACE	0 -> [0,242,"performActions",{"actions":[{"actions":[{"duration":100,"origin":{"element-6066-11e4-a52e-4f735466cecf":"f8834c5b-7317-47d9-bc4d-a62dae24928d"},"type":"pointerMove","x":0,"y":0},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}],"id":"default mouse","parameters":{"pointerType":"mouse"},"type":"pointer"}]}]
1494852637511	Marionette	TRACE	0 <- [1,242,null,{}]
1494852637526	geckodriver::marionette	TRACE	â†? [1,242,null,{}]
1494852637526	webdriver::server	DEBUG	â†? 200 OK {"value": {}}
performed context click here
1494852641546	webdriver::server	DEBUG	â†’ POST /session/3df2686b-cd6a-45d7-b2c8-ea22f97cd487/element {"value":"//span[contains(text(), 'Cancel all')]","using":"xpath"}
```

**Comment by andreastt** [comment]
On the surface, the stacks you have pasted are similar? You also have not described what you expect to happen when you context click? If you check the dispatched DOM events, I’m quite sure you will see that the correct events are fired.

**Comment by prabhurohith** [comment]
When i context click i am expecting a set of options to get displayed which happens in chrome when i use the same command.I have attached the screenshot of the behaviour in chrome

[FFIssue.docx](https://github.com/mozilla/geckodriver/files/1004360/FFIssue.docx)

**Comment by andreastt** [comment]
A right click in web content using WebDriver is not meant to make it possible to interact with the context menu, according to the specification. Closing.

**Comment by prabhurohith** [comment]
Hi ,

I don't want to interact with context menu but do right click on web
element here.As per the implementation in code context click() will do
right click on a web element.
Please help me if some additional steps I need to do in order to do a right
click.

Regards,
Rohith P

On May 16, 2017 7:57 PM, "Andreas Tolfsen" <notifications@github.com> wrote:

A right click in web content using WebDriver is not meant to make it
possible to interact with the context menu, according to the specification.
Closing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/geckodriver/issues/738#issuecomment-301799632>,
or mute the thread

**Comment by andreastt** [comment]
You didn’t answer my earlier question. On the surface the messages sent to geckodriver look alright, but the stacks also look the same.

**Comment by codingphil** [comment]
See also issue https://github.com/mozilla/geckodriver/issues/680 which describes that the `contextmenu` event is definitely not sent by the context click.

It seems that it sends a click event but the `contextmenu` event is missing.

With the `contextmenu` event you can handle right clicks in your javascript code.

**Comment by prabhurohith** [comment]
Seems this is similar to issue #660
