### ISSUE TITLE
Using geckodriver 0.16.1 on Firefox Nightly 55 Windows 7 doesn't load system addon

### ISSUE THREAD

**Issue by MDTsai** [mozilla/geckodriver#739]
## Firefox Version
Firefox 55 Nightly, 32/64 bits, some build after 2017-05-02-03-02-11

## Platform
Windows 7, 64-bit

## Others
Selenium Version: 3.4.1, python
Gecko Driver: 0.16.1

## Steps to reproduce -
1. Download and extract latest Nightly
2. Using:
```
    # Create a Firefox Binary from folder where extracts Firefox Nightly
    binary = FirefoxBinary("./firefox/firefox.exe")
    # Create Firefox WebDriver
    firefox = webdriver.Firefox(firefox_binary=binary)

    # Visit webcompat-ua-dummy, verify title and page
    firefox.get("http://webcompat-ua-dummy.schub.io/")
```
expect to see Firefox image
3. Open about:support, no Nightly features

Here is the test result:
geckodriver 0.15.0 + Firefox 55 2017-05-02-03-02-11 works
geckodriver 0.15.0 + Firefox 55 2017-05-04-03-03-20 with Nightly Feature but can't get URL
geckodriver 0.16.1 + Firefox 55 2017-05-02-03-02-11 no Nightly Feature but can get URL
geckodriver 0.16.1 + Firefox 55 2017-05-04-03-03-20 no Nightly Feature but can get URL
geckodriver 0.16.0 and 0.16.1 come with the same result.

@andreastt attach [geckodriver.txt](https://github.com/mozilla/geckodriver/files/1003067/geckodriver.txt) when fail with AddonManager error message.
Another discussion on https://bugzilla.mozilla.org/show_bug.cgi?id=1364385

**Comment by MDTsai** [comment]
Compare with profile manually run from Firefox Nightly, there is no extension.json in the temp profile created by geckodriver. I suspect it's why I can't see any system addon?

**Comment by KieronAllsop** [comment]
Identical issue with
Firefox 53
Windows 10
Selenium 3.41 or 3.42
Selenium Standalone Server 3.4.0
Robot Framework Selenium2Library

**Comment by andreastt** [comment]
We explicitly disable distro addons from being enabled in https://searchfox.org/mozilla-central/source/testing/geckodriver/src/prefs.rs#146. I suggest passing in `{"extensions.installDistroAddons": true}` as part of the `prefs` JSON Object in `moz:firefoxOptions` to solve this.

**Comment by whimboo** [comment]
As bug 1364385 states the addon manager and several other components in Firefox were busted due to an incompatible path prefix on Windows. See also issue #702.

The fix for this will be part of the next geckodriver release.
