### ISSUE TITLE
Windows 7 and v0.7.1 (VCRUNTIME140.dll missing error)

### ISSUE THREAD

**Issue by pravinrmali** [mozilla/geckodriver#74]
added wires.exe executable in the path and made necessary changes as per (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver), but getting 'wires.exe - System error' (The program can't start because VCRUNTIME140.dll is missing from your computer. Try reinstalling the program to fix this problem.)

**Comment by andreastt** [comment]
We should probably build geckodriver statically so a separate runtime is not needed. In the meantime you can [download the C++ runtime from Microsoft’s website](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

@pravinrmali Could you possibly test if http://sny.no/e/geckodriver1.exe runs on your system, _without_the runtime first? This is a cross-compiled binary using the mingw compiler chain on Linux.

**Comment by pravinrmali** [comment]
I already have x64 bit 'Visual C++ Redistributable for Visual Studio 2015', do I need 32 bit version of this redistributable ?

I tested 'geckodriver1.exe', renamed it to 'wires.exe' and added to system path, and now it's complaining for __Firefox profile__ 
__Error I got:__
 unknown option: {:profile=>#<Selenium::WebDriver::Firefox::Profile:0x4482b58 @model=nil, @native_events=true, @secure_ssl=false, @untrusted_issuer=true, @load_no_focus_lib=false, @additional_prefs={"browser.helperApps.alwaysAsk.force"=>false, "browser.download.folderList"=>2, "pdfjs.disabled"=>true, __deleted long error just to avoid long comment__ , @extensions={}>} (ArgumentError)

then removed __profile__, now Firefox launched but did not start my test application. 
       `caps = Selenium::WebDriver::Remote::Capabilities.firefox("firefoxOptions" => {"args" => ["--always-authorize-plugins"]},:marionette => true)`
        `browser = Capybara::Selenium::Driver.new(app, :browser => :firefox, :profile => profile, :desired_capabilities => caps)`

**Comment by maxpolk** [comment]
Looks like you need the 32-bit redistributable [I found here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by andreastt** [comment]
@maxpolk Do you have the opportunity to test https://sny.no/e/geckodriver1.exe without either runtime?

According to file it should be a 64-bit version:

```
% file geckodriver1.exe 
geckodriver1.exe: PE32+ executable (console) x86-64, for MS Windows
```

**Comment by ejones-deluxe** [comment]
@andreastt I was able to run using that version of geckodriver without either runtime installed.

**Comment by ecwootten** [comment]
@andreastt I'm running Windows 8.1, and installing the 64-bit driver you suggest without either of the runtimes has worked for me. Firefox is up and running again, thank you :-)

**Comment by andreastt** [comment]
@ecwootten Great! This should be the default once #83 is merged.

**Comment by AutomatedTester** [comment]
when #83 is merged we will need to close https://bugzilla.mozilla.org/show_bug.cgi?id=1280854

**Comment by andreastt** [comment]
This has long since been resolved.
