### ISSUE TITLE
Firefox doesn't return Browser Version

### ISSUE THREAD

**Issue by danwan** [mozilla/geckodriver#741]
FF: 53.0.2
Gecko: 16.1
Selenium 3.0
Platform:C#

I'm using:
var capabilities = ((RemoteWebDriver) driver).Capabilities;
_returnValue = capabilities.Version;

To get the version of the running browser. With Chrome and phantomjs it works perfectly fine.
But with FF it returns an empty string.

Is there a different way to do this now with Gecko? 

Thank you
Dan

**Comment by jgraham** [comment]
This is returned in the capabilities. So I think you should try updating to latest Selenium and if itt still doesn't work as expected file a bug on that project.
