### ISSUE TITLE
Using Actions in Chrome Context

### ISSUE THREAD

**Issue by ChaseWPDEV** [mozilla/geckodriver#742]
## Firefox Version
53.0.2
## Selenium Version
3.4.1
## Geckodriver Version
0.16.1
## Platform
Linux, Ubuntu 16.04

## Steps to reproduce -
Attempting to use the CONTEXT_CHROME feature in selenium. A trivial example from IDLE:
>>> d=webdriver.Firefox()
>>> d.set_context('chrome')
>>> urlbar=d.find_element('id','urlbar')
>>> urlbar.send_keys('http://google.com') #from this point on, the browser basically stops responding
>>> go=d.find_element('id', 'urlbar-go-button')
>>> go.click()
>>> urlbar.send_keys('http://google.com')

Nothing showing up in the geckodriver.log:
1494946407069	geckodriver::marionette	INFO	Starting browser /usr/lib/firefox/firefox.sh with args ["-marionette"]
1494946415160	Marionette	INFO	Listening on port 32864
1494946415337	Marionette	WARN	TLS certificate errors will be ignored for this session

Again, this is a trivial example, the larger purpose is to test/automate sites with security device logins, certificates, etc.

Thanks for any help you can offer.

**Comment by AutomatedTester** [comment]
Chrome support for Actions is not available. Unfortunately it is also extremely low priority. I have raised https://bugzilla.mozilla.org/show_bug.cgi?id=1365886 for us to look at it eventually. If you want to take a stab at it feel free to comment in the bug and we can see about mentoring you through it.
