### ISSUE TITLE
geckodriver 0.16.1 can't setPageSize on firefox 52.0 ESR

### ISSUE THREAD

**Issue by zzhengjian** [mozilla/geckodriver#743]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0 ESR

## Platform
Windows

Ruby: 2.2.6
Selenium-WebDriver: 3.4.0
## Steps to reproduce -
Start Firefox 52.0 ESR and then try to call setPageSize method.
Seeing below error:
setWindowRect (Selenium::WebDriver::Error::UnknownError)

**Comment by AutomatedTester** [comment]
Unfortunately this didnt make it into the Firefox 52 ESR release cycle. Please use Firefox 53+.

**Comment by tuxayo** [comment]
> Unfortunately this didnt make it into the Firefox 52 ESR release cycle. Please use Firefox 53+.

Should the README reflect this? https://github.com/mozilla/geckodriver#supported-firefoxen

"Support is best in Firefox 52.0.3 and onwards" → "Support is best in Firefox 53 and onwards"

And I suppose v0.15.0 is the best to work with Firefox 52 ESR right?

**Comment by andreastt** [comment]
@tuxayo Thanks for the reminder. I’ve updated the README according to your suggestion.
