### ISSUE TITLE
new Actions(driver).moveToElement(element).click().perform() for selenium 3.4.0 FF 53.0.2

### ISSUE THREAD

**Issue by vlakkara** [mozilla/geckodriver#744]
org.openqa.selenium.InvalidArgumentException:
Could not find webelement key
InvalidArgument

not able to click the element , earlier it used to work for older version for FF 2.47 and selenium 2.53 but not for latest  spec below.

Specs:
Firefox: 53.0.2 (64 bit windows
Geckodriver 0.16.1  windows 64 bit
Selenium:3.4.0
OS: Windows 10 Enterprise
JDK version : 1.8.0_131

new Actions(driver).moveToElement(element).click().perform();  is not working
but right now i am direclty using like below
element.click(); this is working for button clicks.
it throws invalid argument exception.

## Firefox Version
Firefox: 53.0.2 (64 bit windows

## Platform
Specs:
OS: Windows 10 Enterprise

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.245 s <<< FAILURE! - in TestSuite
[ERROR] studentCanvasFindAndLaunchCourse(com.cisco.netacad.canvas.sanity.NetAcadStudentCanvasTest)  Time elapsed: 5.166 s  <<< FAILURE!                                                                                                         org.openqa.selenium.InvalidArgumentException:
Could not find webelement key
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'VISLAKKA-48UKY', ip: '10.155.52.211', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'                                                                                                Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\vislakka\AppData\Local\Temp\rust_mozprofile.Dwjr0BQcBF0V, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0.2, platformVersion=10.0, moz:processID=8904.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]                                                    Session ID: 996f3f9e-fa60-48d4-81be-a5fafa45ac54                                                                                at com.cisco.netacad.canvas.sanity.NetAcadStudentCanvasTest.studentCanvasFindAndLaunchCourse(NetAcadStudentCanvasTest.java:43)

## Steps to reproduce -
Please provide a description of how to reproduce the problem, including the following essential elements:

 - [ ] A *minimal* HTML file (or files) that can be used to reproduce the issue (this should not be your production site, unless you are unable to isolate the problem, but a page containing only the elements required to observe the problem).

 - [ ] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by AutomatedTester** [comment]
The issue you are hitting is either SeleniumHQ/selenium#3808 or is a separate Java Bindings issue. Please raise an issue with the Selenium project, we are not getting the valid data across the wire and are erroring appropriately

**Comment by charlesfradley** [comment]
I have a simialr problem trying to use  moveToElement()  i.e. :

  org.openqa.selenium.InvalidArgumentException:
Could not find webelement key

Firefox 52.4.0 (32-bit)

**Comment by andreastt** [comment]
@charlesfradley Firefox 52 is not supported by geckodriver. Please don’t hijack old issues.
