### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by codekaizer** [mozilla/geckodriver#748]
Hi Geckodriver community,

I have a problem using Geckodriver.

```
1495299180874   geckodriver::marionette INFO    Starting browser /usr/lib/firefox/firefox with args ["-marionette"]
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :99
```

I'm using the following versions:

- Firefox 53.0
- Linux Fedora 22
- Geckodriver 0.16.1

Refer to my [post](http://stackoverflow.com/questions/44088743/xvfb-connection-refused-when-running-test-script-via-browser-on-fedora) for more info.

I really appreciate your help!

**Comment by jrbenny35** [comment]
This doesnt look like a geckodriver problem. Are you sure the xvfb display is starting?

**Comment by codekaizer** [comment]
Hi @jrbenny35,

Thank you for your response.

Here's what I've got.

Check if Xvfb is running:
```
$ [codekaizer@localhost web]$ ps auxT |grep Xvfb
codekai+  1967  4.0  0.5 180848 24272 pts/1    S    20:57   0:00 Xvfb :99 -ac
codekai+  1976  0.0  0.0 115824  2284 pts/1    S+   20:57   0:00 grep --color=auto Xvfb
```

Check if X99 socket is listening to a port
```
[codekaizer@localhost web]$ netstat -lnp |grep Xvfb
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
unix  2      [ ACC ]     STREAM     LISTENING     1331752  1967/Xvfb            /tmp/.X11-unix/X99
unix  2      [ ACC ]     STREAM     LISTENING     1331751  1967/Xvfb            @/tmp/.X11-unix/X99
```

**Comment by codekaizer** [comment]
I've also tried: `xvfb-run -a python crawler.py` and `DISPLAY=:99 python crawler.py`

Both are successful if ran from the command line.
However, if script is triggered from the browser via PHP's `shell_exec(cmd)`, that's the time it's showing the error.

**Comment by AutomatedTester** [comment]
I suggest asking in the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) on how to solve this issue. This is not a GeckoDriver. You need to make sure that you are telling the command to run Selenium that you want to use a different display.
