### ISSUE TITLE
Driver fails to connect with the browser main page

### ISSUE THREAD

**Issue by nirp1981** [mozilla/geckodriver#75]
Hello , 
I try to communicate with the page content via javascript but it looks like the driver doesnt work in the same context as the main page.For example navigating to google and trying to read a var that already exists in the page will throw an exception.The same piece of code works fine in all other drivers.
I used wires 0.7.1 , and tried firefox 46 & 47.
Thanks

@Test
	public void test1() throws Exception{
		WebDriver _driver; 
		DesiredCapabilities dc = DesiredCapabilities.firefox();
		OSUtils.setSystemProperty("webdriver.firefox.bin", "C:\\FirefoxOfficial\\firefox.exe");
		OSUtils.setSystemProperty("webdriver.gecko.driver","C:\\Wires\\wires.exe");
		_driver = new MarionetteDriver(dc);
		_driver.navigate().to("https://www.google.com/");
		Thread.sleep(2000);
		JavascriptExecutor jx = (JavascriptExecutor) _driver;
		Object varNum = jx.executeScript("return gadgets;");
		System.out.println(varNum);
	}

This is the output:

org.openqa.selenium.WebDriverException: ReferenceError: gadgets is not defined (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 35 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:01:03'
System info: host: 'WALKME200', ip: '192.168.3.155', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_71'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20160502172042, version=46.0.1, platform=XP, proxy={}, specificationLevel=1, acceptSslCerts=false, browserVersion=46.0.1, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 397e956c-6a77-4dc3-865c-c3e1f6e76854
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:575)

This is the driver`s log:

1465460585734	Marionette	DEBUG	Marionette enabled via build flag and pref
1465460585932	Marionette	INFO	Listening on port 2828
1465460586433	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:62380
1465460586446	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":null,"sessionId":null}]
1465460586448	Marionette	CONFIG	Changing capabilities: {"browserName":"Firefox","browserVersion":"46.0.1","platformName":"Windows_NT","platformVersion":"6.1","specificationLevel":"1","raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160502172042","device":"desktop","version":"46.0.1"}
1465460586980	Marionette	DEBUG	loaded listener.js
1465460586984	Marionette	DEBUG	loaded listener.js
1465460587090	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"15d1b671-ef2a-4e02-b801-a2c3f806fe2f","capabilities":{"browserName":"Firefox","browserVersion":"46.0.1","platformName":"Windows_NT","platformVersion":"6.1","specificationLevel":"1","raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160502172042","device":"desktop","version":"46.0.1"}}]
1465460587135	Marionette	TRACE	conn0 -> [0,2,"get",{"url":"https://www.google.com/"}]
1465460588996	Marionette	TRACE	conn0 <- [1,2,null,{}]
JavaScript warning: https://normandy.cdn.mozilla.net/static/js/bundles/selfrepair-7575f6d27445b45bcffb.js, line 9825: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
1465460593616	Marionette	TRACE	conn0 -> [0,3,"executeScript",{"args":[],"newSandbox":false,"script":"return gadgets;","scriptTimeout":null,"specialPowers":false}]
1465460593619	Marionette	TRACE	conn0 <- [1,3,{"error":"javascript error","message":"ReferenceError: gadgets is not defined","stacktrace":"execute_script\ninline javascript, line 0\nsrc: \"var __marionetteFunc = function(){return gadgets;};__marionetteFunc.apply(null, __marionetteParams);\"\nStack:\n__marionetteFunc@dummy file:0:35\n@dummy file:0:56\n"},null]

**Comment by andreastt** [comment]
I believe this has been addressed by [bug 1123506](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506), which was uplifted to Firefox 48 only yesterday. Can you try again in Firefox 48, 49, or Nightly?

**Comment by hjwp** [comment]
Hi! Is there a workaround for accessing js globals using older/supported firefoxen?  or is the only solution here to upgrade to 48+?

**Comment by andreastt** [comment]
@hjwp You will have to upgrade to >= 48. We aren’t uplifting this to 47 (stable).

**Comment by yuliaSharabi** [comment]
I am still getting it in FF V50.

**Comment by andreastt** [comment]
@yuliaSharabi Yes it shold be. Please provide a reproducible test case if you think it is broken, otherwise your comment is just an unsubstantiated claim.
