### ISSUE TITLE
Can´t invoke and load Firefox browser with Webdriver properly

### ISSUE THREAD

**Issue by tina492** [mozilla/geckodriver#752]
In order to help us efficiently investigate your issue, please provide the following information:

Firefox 53.0.3 (64-bit)

OSX Yosemite, Version 10.10.5 

I'm doing a Selenium Webdriver online course and the first thing to do is invoke the browser. As I'm using Firefox I downloaded Geckodriver and attached the path in my java class. I've seen more people had the same issue but I don't know how to fix it. If someone could help me out with this I would really appreciate it.

Cheers.

This is my Java class:
```java
 package basics;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.safari.SafariDriver;

public class Browserinvocation {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.setProperty("webdriver.gecko.driver","/Users/macbook/Downloads/Tools/Gecko/geckodriver");
		WebDriver driver=new FirefoxDriver();
		
		
	}

}
```

And when I run it, this is what I get:

```
1495542397512	geckodriver	INFO	Listening on 127.0.0.1:32622
1495542399465	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
1495542406210	Marionette	INFO	Listening on port 50289
2017-05-23 13:26:47.493 plugin-container[4430:310804] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x474f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-23 13:26:47.494 plugin-container[4430:310804] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8817, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-05-23 13:26:47.495 plugin-container[4430:310804] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
May 23, 2017 1:26:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```
![snip20170523_2](https://cloud.githubusercontent.com/assets/8091560/26354404/5530f478-3fbc-11e7-8c00-1eb20fd763dd.png)

**Comment by AutomatedTester** [comment]
@tina492 is the browser starting up. What you have shown so far is nothing worth worrying about.

**Comment by tina492** [comment]
@AutomatedTester Alright, so what should I do in order to open the browser? I read that if I use Firefox v 52.0 rather than v53 will fix the issue. So I installed it and I get the same issue...

**Comment by AutomatedTester** [comment]
@tina492 the browser opening with a blank page is exactly what your code is telling it to do. 

If you add in `driver.get("https://www.mozilla.org")` after instantiating the FirefoxDriver it will navigate to https://www.mozilla.org.

You can also send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users) where there is an awesome army of people willing to talk you through the next steps.
