### ISSUE TITLE
can not load the extension in Windows but it works in OSX

### ISSUE THREAD

**Issue by iamau32** [mozilla/geckodriver#753]
## Firefox Version
53.0.3
## Platform
Windows7
geckodriver v0.16.1
selenium-webdriver 3.4.0
java
## Steps to reproduce -
the extension file:
[modify_headers.xpi.zip](https://github.com/mozilla/geckodriver/files/1028322/modify_headers.xpi.zip)
the code:

```
System.setProperty("webdriver.gecko.driver", "the path of the driver");
FirefoxProfile profile=new FirefoxProfile();
profile.addExtension(new File("modify_headers.xpi"));
profile.setPreference("modifyheaders.headers.Referer", "url");
profile.setPreference("modifyheaders.config.active", true);
profile.setPreference("modifyheaders.config.alwaysOn", true);		
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability(FirefoxDriver.PROFILE, profile);	
WebDriver driver=new FirefoxDriver(capabilities);
driver.get("http://www.google.com");
```
the log:
```
1495698579343	geckodriver	INFO	Listening on 127.0.0.1:43069
1495698581132	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1495698581645	addons.manager	DEBUG	Application has been upgraded
1495698581646	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:671 < startup()@resource://gre/modules/AddonManager.jsm:834 < startup()@resource://gre/modules/AddonManager.jsm:3129 < observe()@resource://gre/components/addonManager.js:65
1495698581649	addons.manager	DEBUG	Completed startup sequence
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
[GFX1-]: CreateShaderResourceView failed for format87
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1495698585784	Marionette	INFO	Listening on port 31365
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2570: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1495698586196	Marionette	WARN	TLS certificate errors will be ignored for this session
```
**The extension doesn't be installed, but it works in OSX.**

**Comment by andreastt** [comment]
With Firefox 48 addons need to be signed to be installed in Firefox. This means any addon that is installed to a profile through `profile.addExtension` needs to have been signed by AMO.

I would check that you’re able to install the addon manually on both platforms. If that still fails, you know why.

**Comment by iamau32** [comment]
I can not install the addon in geckodriver,the addon is:

`https://addons.mozilla.org/en-US/firefox/addon/modify-headers/`

Click the 'Add to Firefox' button The geckodriver will log:

`JavaScript error: resource://gre/modules/AddonManager.jsm, line 2038: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized`

Is it normal? But everything is ok in OSX

**Comment by andreastt** [comment]
>> JavaScript error: resource://gre/modules/AddonManager.jsm, line 2038: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
> 
> Is it normal? But everything is ok in OSX

Just to be clear, you _don’t_ see this line in the log on macOS?

**Comment by iamau32** [comment]
Yes, on macOS it works fine.


在 2017年5月26日，下午11:04，Andreas Tolfsen <notifications@github.com<mailto:notifications@github.com>> 写道：


JavaScript error: resource://gre/modules/AddonManager.jsm, line 2038: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized

Is it normal? But everything is ok in OSX

Just to be clear, you don’t see this line in the log on macOS?

**Comment by andreastt** [comment]
> Yes, on macOS it works fine.

That’s not really what I asked. Do you see the log entry on macOS?

**Comment by LordValmos** [comment]
Same problem with : 
Mozilla : 53.0.3 (32Bits)
OS : Windows 7
Selenium : 3.4.1

**Comment by whimboo** [comment]
It doesn't make sense to have multiple issues for the same underlying problem. So everything add-ons related is now covered by issue #715.
