### ISSUE TITLE
Obtaining the existing session ID via the HTTP API

### ISSUE THREAD

**Issue by fluffysquirrels** [mozilla/geckodriver#758]
For my use case I'd like to obtain the session ID via the WebDriver HTTP API for the established session if one exists.

I can already use the command `GET /status` to determine a session exists:

```
 % curl http://localhost:4444/status 
{"value":{"message":"Session already started","ready":false}}%
```

And as a workaround I could use e.g. `GET /session/foo/url` and scrape the error message with the existing session ID:

```
 % curl -sS http://localhost:4444/session/foo/url | jq '.'
{
  "value": {
    "error": "invalid session id",
    "message": "Got unexpected session id foo expected 1687e068-15c4-4157-a8d4-2fcdd497bd84",
    "stacktrace": "[...]" // Skipped for length
  }
}
```
But I'd like to modify geckodriver to obtain the session ID more idiomatically through the HTTP API.

## Option 1: Implement something similar to `GET /sessions`

The Selenium JsonWireProtocol document describes the command [`GET /sessions`](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessions) to obtain the IDs and capabilities of existing sessions. This would be my first preference to implement, except the W3C WebDriver spec's [list of commands](https://w3c.github.io/webdriver/webdriver-spec.html#list-of-endpoints) seems to have removed this one.

We could add something similar as a [vendor-specific protocol extension](https://w3c.github.io/webdriver/webdriver-spec.html#protocol-extensions) such as `GET /sessions/moz/gecko` and still comply with the WebDriver spec. There are already protocol extensions in geckodriver [here](https://github.com/mozilla/geckodriver/blob/60e7a430dc38a9e1921928c0cd996bb5fc00198b/src/marionette.rs#L57-L80).

## Option 2: Add session ID property to `GET /status`

The [spec for `GET /status`](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-status) describes the properties required but permits extra data to be returned:

> Implementations may optionally include additional meta information as part of the body, but the top-level properties ready and message are reserved and must not be overwritten.

We could add a new property `sessionId` or similar when a session already exists.

------

Any thoughts on the above two options?

I could solve my problem a different way using the scraping workaround described or by storing the session ID out of band somewhere, but I think modifying geckodriver would be cleaner and more maintainable, and the extra session ID data could be useful to others.

I'd be delighted to submit a PR for this if a commiter approves of one of the options above (or some other solution).

Many thanks, Alex.

**Comment by andreastt** [comment]
This is more an issue for the [WebDriver specification](https://github.com/w3c/webdriver), but obtaining the current session ID from the final remote end after session creation is consciously not made possible through an API. There are a couple of reasons for this.

Mainly, it makes it more difficult for a malicious attacker to sniff and hijack existing WebDriver sessions, adding to the [layered security](https://en.wikipedia.org/wiki/Layered_security) of WebDriver. If the attacker has shell execution access to the machine you obviously have bigger problems, but there is a potential attack vector that involves MITM’ing the WebDriver session connection. Since the wire protocol is HTTP, the thinking is that not providing an explicit API for getting the active session ID makes it slightly less trivial for an attacker _without_ direct shell access to the machine to hijack the session.

There are obvious ways to mitigate this by having the intermediary node (the Selenium server proxy/multiplexer) or the local end (client) maintain a list of session IDs. It could potentially expose a private API with a list of active session IDs and their routing. This would make more sense, since the intermediary node allows you to create more than one session: a final remote end, like geckodriver, is consciously limited to a single active session.

The W3C WebDriver specification never defined GET `/sessions`, but my final concern about defining it in the specification would be about proportionality. A WebDriver final endpoint node is black box indistinguishable from an intermediary node. This means that any request made to the intermediary must behave exactly like if you would request it from the endpoint node, and vice versa. If the intermediary implemented GET `/sessions` to return current sessions, its return value would be different from if you were to request it from the endpoint node—in other words, you would get different results depending on which node your request ended up. Because it is technically possible to have chained intermediary nodes, e.g. a multiplexing server calling another such multiplexer, and because it is not possible to “direct” a request to a specific node, it would be impossible to make such an API deterministic.

All this said, it is entirely conceivable that an intermediary node such as the Selenium server might expose a list of sessions in GET `/status` or a separate and custom GET `/selenium/sessions` endpoint, but it would be in the understanding that if an attacker has access to the WebDriver session allocator server in the first place, then your WebDriver cluster has been compromised.

I hope this helps!

**Comment by fluffysquirrels** [comment]
Thank you for your helpful and detailed response. I hadn't considered the
WebDriver security model.

Currently it is possible to scrape the active session ID through many of
the `GET /session/:session_id/*` commands as it is reported through the
error message. I presume it would be desirable to stop this to avoid
information disclosure that could lead to session hijacking. Would you like
to see a PR for this?

Regarding the security concerns, it seems like a command line argument to
activate session enumeration would help. The user must discover and turn on
the feature, at which point they would hopefully read some kind of security
warning and judge whether or not the feature is worth the risk. Or perhaps
this is wishful thinking and some users would hurriedly type the flag
without understanding the consequences. What do you think?

The other option which comes to mind is a shared secret passed to
geckodriver as a command line option, environment variable, or in a file
with path given on the command line. This seems like a fair amount of work,
arousing your (and my) proportionality concerns.

You mentioned adding the session enumeration at the client or on a proxy.
My application is currently a stateless console app and I want to re-use
sessions between runs; I could stash some state somewhere. Selenium Server
/ Grid may support my use case, but it's unclear as the only documentation
seems to be 5 years old and very incomplete (e.g. [Configuring Selenium
Grid](
http://www.seleniumhq.org/docs/07_selenium_grid.jsp#configuring-selenium-grid)).
I'd rather not touch Selenium Grid if I can avoid it, are there other
existing Selenium proxy / middleware implementations you aware of?

The last option I haven't tried yet is to start Firefox myself with
Marionette enabled on a known port, then restart geckodriver and recreate a
session each time I need to use it. If this works it might be worth a blog
or FAQ entry somewhere.



On 28 May 2017 12:12, "Andreas Tolfsen" <notifications@github.com> wrote:

This is more an issue for the WebDriver specification
<https://github.com/w3c/webdriver>, but obtaining the current session ID
from the final remote end after session creation is consciously not made
possible through an API. There are a couple of reasons for this.

Mainly, it makes it more difficult for a malicious attacker to sniff and
hijack existing WebDriver sessions, adding to the layered security
<https://en.wikipedia.org/wiki/Layered_security> of WebDriver. If the
attacker has shell execution access to the machine you obviously have
bigger problems, but there is a potential attack vector that involves
MITM’ing the WebDriver session connection. Since the wire protocol is HTTP,
the thinking is that not providing an explicit API for getting the active
session ID makes it slightly less trivial for an attacker *without* direct
shell access to the machine to hijack the session.

There are obvious ways to mitigate this by having the intermediary node
(the Selenium server proxy/multiplexer) or the local end (client) maintain
a list of session IDs. It could potentially expose a private API with a
list of active session IDs and their routing. This would make more sense,
since the intermediary node allows you to create more than one session: a
final remote end, like geckodriver, is consciously limited to a single
active session.

The W3C WebDriver specification never defined GET /sessions, but my final
concern about defining it in the specification would be about
proportionality. A WebDriver final endpoint node is black box
indistinguishable from an intermediary node. This means that any request
made to the intermediary must behave exactly like if you would request it
from the endpoint node, and vice versa. If the intermediary implemented GET
/sessions to return current sessions, its return value would be different
from if you were to request it from the endpoint node—in other words, you
would get different results depending on which node your request ended up.
Because it is technically possible to have chained intermediary nodes, e.g.
a multiplexing server calling another such multiplexer, and because it is
not possible to “direct” a request to a specific node, it would be
impossible to make such an API deterministic.

All this said, it is entirely conceivable that an intermediary node such as
the Selenium server might expose a list of sessions in GET /status or a
separate and custom GET /selenium/sessions endpoint, but it would be in the
understanding that if an attacker has access to the WebDriver session
allocator server in the first place, then your WebDriver cluster has been
compromised.

I hope this helps!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/geckodriver/issues/758#issuecomment-304507343>,
or mute the thread

**Comment by fluffysquirrels** [comment]
Thank you for your helpful and detailed response. I hadn't considered the WebDriver security model.

Currently it is possible to scrape the active session ID through many of the `GET /session/:session_id/*` commands as it is reported through the error message. I presume it would be desirable to stop this to avoid information disclosure that could lead to session hijacking. Would you like to see a PR for this?

Regarding the security concerns, it seems like a command line argument to activate session enumeration would help. The user must discover and turn on the feature, at which point they would hopefully read some kind of security warning and judge whether or not the feature is worth the risk. Or perhaps this is wishful thinking and some users would hurriedly type the flag without understanding the consequences. What do you think?

The other option which comes to mind is a shared secret passed to geckodriver as a command line option, environment variable, or in a file with path given on the command line. This seems like a fair amount of work, arousing your (and my) proportionality concerns.

You mentioned adding the session enumeration at the client or on a proxy. My application is currently a stateless console app and I want to re-use sessions between runs; I could stash some state somewhere. Selenium Server / Grid may support my use case, but it's unclear as the only documentation seems to be 5 years old and very incomplete (e.g. [Configuring Selenium Grid](http://www.seleniumhq.org/docs/07_selenium_grid.jsp#configuring-selenium-grid)). I'd rather not touch Selenium Grid if I can avoid it, are there other existing Selenium proxy / middleware implementations you aware of?

The last option I haven't tried yet is to start Firefox myself with Marionette enabled on a known port, then restart geckodriver and recreate a session each time I need to use it. If this works it might be worth a blog or FAQ entry somewhere.

**Comment by AutomatedTester** [comment]
`GET /sessions` is a Selenium Grid only endpoint for intermediary nodes to know what sessions they think are alive. This is one of the main reasons why it hasnt made it into the W3C Spec.

Unfortunately I can't see how your app is going to work if it is not going to keep state around GeckoDriver. When you call GeckoDriver `newSession` it is going to start the browser and give you back a session id. If you don't have that then you are going to be doing needless commands which will return `[invalid session error](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-invalid-session-id)` which would tell you that you need a new session anyway. 

We won't be implementing this feature at this time.

**Comment by fluffysquirrels** [comment]
Thanks both for your thoughts. I did end up storing the state in my client app easily enough.

I still think it would be a good idea to stop disclosing the existing session ID in error messages, providing layered security as @andreastt mentioned.

Regards, Alex.

**Comment by andreastt** [comment]
@fluffysquirrels Can you show an example of an error message that does this?

**Comment by fluffysquirrels** [comment]
Sure:

```sh
 % curl -sS http://localhost:4444/session/foo/url | jq '.'
{
  "value": {
    "error": "invalid session id",
    "message": "Got unexpected session id foo expected 1687e068-15c4-4157-a8d4-2fcdd497bd84",
    "stacktrace": "[...]" // Skipped for length
  }
}
```

[This](https://github.com/mozilla/webdriver-rust/blob/master/src/server.rs#L108-L110) looks like the code in webdriver-rust that generates the message.

**Comment by andreastt** [comment]
@fluffysquirrels Thanks! I reported https://github.com/mozilla/webdriver-rust/issues/98.
