### ISSUE TITLE
Marionette doesn't accept a hostport as a proxy address

### ISSUE THREAD

**Issue by juangj** [mozilla/geckodriver#764]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
55.0a1 (2017-06-01)

This has actually been happening for as long as I can remember having used Marionette/Geckodriver. We had put in a workaround for it, and I thought we'd filed a bug about it but I can't find it, so we probably forgot.

## Platform
OSX at the moment, but it probably happens on all of them

## Steps to reproduce -

Request a new session with these capabilities:
```json
{
  "capabilities": {
    "alwaysMatch": {
      "proxy": {
        "proxyType": "manual",
        "httpProxy": "localhost:8888"
      }
    }
  }
}
```

The response is:
```json
{
  "error":"session not created",
  "message":"InvalidArgumentError: Expected [object Undefined] undefined to be an integer",
  "stacktrace":"..."
}
```

Here's the trace log: [geckodriver.log.txt](https://github.com/mozilla/geckodriver/files/1046833/geckodriver.log.txt)

If you split the hostport into two fields, then the session creation succeeds:
```json
"proxy": {
  "proxyType": "manual",
  "httpProxy": "localhost",
  "httpProxyPort": 8888
}
```

The error message appears to come from Marionette, but it seems like it may be easier to fix this by having Geckodriver just split the hostport. (And then it would work for all versions of Firefox, not just newer versions.)

**Comment by whimboo** [comment]
Right, the Webdriver spec also says: `A domain, and optional port preceeded by a colon`.

Given that geckodriver is our proxy between the spec and the custom socket protocol supported by Marionette, it's the former which needs the fix.

**Comment by whimboo** [comment]
@juangj, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1369827 to get your request implemented. Thanks for bringing it up.

**Comment by juangj** [comment]
Thanks! Do you prefer new bugs to be filed on Bugzilla at this point? I remember there was some plan to get Geckodriver imported in mozilla-central, but I'm not sure whether the intent was to move development over there too -- or maybe that has already happened.

**Comment by whimboo** [comment]
mozilla-central is the canonical repository now. We won't merge code into the github repo. Instead @andreastt will mark the master branch soon for clarity.

Regarding your question... if you will file clear and detailed bugs like this one please go ahead. Otherwise we prefer new issues here, which mostly might need further investigation on our side before a real bug gets filed.

**Comment by andreastt** [comment]
Also sprach Henrik Skupin:

> mozilla-central is the canonical repository now. We won't merge code
> into the github repo. Instead @andreastt will mark the master branch
> soon for clarity.

Thanks for reminding me.  I have now “tombstoned” the GitHub
project and added a notice to the README, redirecting any future patch
submissions to Bugzilla.

We will keep the GitHub project around for publishing releases and as an
area to triage bug reports.

@juangj’s issues are always of the highest quality, so feel free to
report them directly to Testing :: geckodriver in Bugzilla.

**Comment by whimboo** [comment]
Please also see the discussion on https://github.com/w3c/webdriver/issues/949

**Comment by whimboo** [comment]
> I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1369827 to get your request implemented. 

The feature is now available in Firefox Nightly. To use it with geckodriver you will need a nightly build or wait for the next release.

**Comment by gjundat95** [comment]
Work in Selenium 3.14.2, Firefox 62, C# .NET 4.5

```
 FirefoxOptions firefoxOptions = new FirefoxOptions();
            firefoxOptions.SetPreference("network.proxy.type", 1);
            firefoxOptions.SetPreference("network.proxy.socks", "127.0.0.1");
            firefoxOptions.SetPreference("network.proxy.socks_port", 1080);

            IWebDriver driver = new FirefoxDriver(service, firefoxOptions);
```
