### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by AutomatedTester** [mozilla/geckodriver#769]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
All

## Platform
All

## Steps to reproduce -
when calling `session/<session id>/window/fullscreen we dont get anything. This has been implemented in Marionette. We just need the rest completed

 - [ x] A [trace level log](https://github.com/mozilla/geckodriver#firefox-capabilities) from a geckodriver session that demonstrates the problem using the minimal example file. Note: this is *not* the same as a selenium log.

** If any of the above are missing we will have to unfortunately close your issue. We will gladly reopen the issue once all the information requested has been added **

**Comment by andreastt** [comment]
This is now implemented in geckodriver as far as I can tell.

**Comment by jineshqa** [comment]
Firefox 54.0.1, gechodriver version 0.18.0 => Issue is still reproducible.

**Comment by andreastt** [comment]
@jineshqa But it would help you tested with the Firefox version we actually develop against before claiming it is still reproducible. You will note from https://bugzilla.mozilla.org/show_bug.cgi?id=1370510 that it is only available in Firefox 55 and greater.

**Comment by jineshqa** [comment]
@andreastt My bad, apologies. I didn't know this is being tracked somewhere else.

**Comment by Debanjan-B** [comment]
@AutomatedTester @lmtierney @shs96c  Can anyone confirm if the `fullscreen` mode is supported by the **`Python`** Clients as well?

**Comment by andreastt** [comment]
@Debanjan-B That is a question for the Selenium project, not geckodriver.
