### ISSUE TITLE
async_script doesn't work?

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#77]
Hey,
really excited about the new driver! We run the project [Browsertime](https://github.com/tobli/browsertime) and we use the NodeJS version of Selenium and we started to move to the Geckodriver since we need to with Firefox 47 but there's one thing that stops us and that is that it doesn't seems to work with running async scripts (in the Selenium world driver. executeAsyncScript). When I tried I get: 
<pre>
POST /session/21c00e28-7c85-274f-a797-85f566f13ac9/timeouts/async_script did not match a known command
</pre>
And we use that to get the HAR file from the [HAR-export-trigger](https://github.com/firebug/har-export-trigger) when we test the performance of a page. I use geckodriver-0.8.0-OSX.

Thanks
Peter

**Comment by andreastt** [comment]
The WebDriver specification differs from Selenium in a number of subtle ways. The [Set Timeout](http://w3c.github.io/webdriver/webdriver-spec.html#set-timeout) command takes a dict with one or more of the following entries:

* `script`
* `page load`
* `implicit`

There is no `/session/{session id}/timeouts/async_script` endpoint in WebDriver.
