### ISSUE TITLE
Implement a "/shutdown" endpoint

### ISSUE THREAD

**Issue by shs96c** [mozilla/geckodriver#771]
With reference to https://github.com/SeleniumHQ/selenium/issues/3978. The ChromeDriver and IEDriverServer both understand a `/shutdown` endpoint that can be used to quit the service. All the official language bindings attempt to call this URL before killing the service process. It might be nice to also implement this in geckodriver.

**Comment by andreastt** [comment]
There is no `/shutdown` endpoint in the specification, and we have `/session/{session id}/quit` to end the session. I would consider it the responsibility of the parent process to stop geckodriver when it is no longer needed.

**Comment by shs96c** [comment]
`/shutdown` kills the entire service rather than a single session. It's not in the spec, and the parent processes do kill the geckodriver process.

This endpoint is just how all the language bindings notify the driver service to quit, allowing a controlled shutdown rather than a potential `kill -9` That's why I said it might be nice to also implement this is geckodriver :)

**Comment by andreastt** [comment]
Ideally a parent process should ask nicely with SIGTERM (15) before using SIGKILL (9). This would be functionally equivalent to having an HTTP endpoint for it.

**Comment by shs96c** [comment]
Sure. That'd be the nice way to do it. None of the language bindings do that, but it'd also be nice (the java ones might…). Feel free to open a reciprocal selenium issue :)

**Comment by jimevans** [comment]
@andreastt Given that Windows doesn't have SIGTERM and SIGKILL, what's the suggestion for that platform?

**Comment by andreastt** [comment]
As I said, just terminating geckodriver is absolutely fine. There’s no state in geckodriver that requires cleanup.

**Comment by jgraham** [comment]
If there is a requirement to have an endpoint here it should be in the spec. But an endpoint for this seems like bad design since you probably don't want random clients to shut down the entire service. Instead that can be in control of whoever owns the process using standard os methods for pprocess control. Closing this, but feel free to reopen if there's anything extra we should do here.
