### ISSUE TITLE
sendKeys(" ") does not check checkbox

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#777]
## Platform and application details
Windows 10 Creators Update
Firefox: 54.0 (beta)
Selenium: 3.4 (Java)

## Steps to reproduce
Run the following Java Selenium test.
```java
  public void testSendKeysSpaceToCheckbox()  {
    webDriver.navigate().to("https://mdn.mozillademos.org/en-US/docs/Web/HTML/Element/input/checkbox$samples/Basic_example");
    
    WebElement checkbox = webDriver.findElementById("checkBox");
    assertEquals("input", checkbox.getTagName());
    assertEquals("checkbox", checkbox.getAttribute("type"));
    
    assertFalse("checkbox is NOT selected before pressing SPACE", checkbox.isSelected());
    
    checkbox.sendKeys(" ");
    
    assertTrue("checkbox is selected after pressing SPACE", checkbox.isSelected());
  }
```
It will fail with `java.lang.AssertionError: checkbox is selected after pressing SPACE`

A simple test page with a checkbox with the id "checkBox" is used:
https://mdn.mozillademos.org/en-US/docs/Web/HTML/Element/input/checkbox$samples/Basic_example

- [ ] A trace level log:
[geckodriver-log_sendKeysSpaceToCheckbox.txt](https://github.com/mozilla/geckodriver/files/1060873/geckodriver-log_sendKeysSpaceToCheckbox.txt)

**Comment by andreastt** [comment]
It’s not supposed to be possible to select a checkbox using the high-level `WebElement.sendKeys` API. You need to use the low-level actions API for that.

**Comment by codingphil** [comment]
This is not very intuitive. Both variants of sendKeys() methods should have the same functionality.
At least for the Java programmer it is not very understandable.

Have you any reference to a standard/spec where it is defined that this should not work?
At least in Chrome this works fine.

**Comment by andreastt** [comment]
Also sprach Philip Lonsing:

> This is not very intuitive. Both variants of sendKeys() methods should
> have the same functionality.

Whilst they may appear to do the same thing, the high-level Element Send
Keys command is a do-as-I-mean shorthand which also runs a number of
checks, such as ensuring it is keyboard-interactable, scrolling it into
view, focussing it, &c.

The low-level variant that is part of the actions API, consists of
the two primitives keyUp and keyDown, to achieve the same effect.
Effectively you will run [keyDown(<spacebar pua>), keyUp(<spacebar
pua>)].

> Have you any reference to a standard/spec where it is defined that
> this should not work?

https://w3c.github.io/webdriver/webdriver-spec.html#element-send-keys

> At least in Chrome this works fine.

Chrome does not implement the specification.
