### ISSUE TITLE
RemoteWebDriver - Nightly Browser - GeckoDriver - Timeout Exception

### ISSUE THREAD

**Issue by newton143** [mozilla/geckodriver#779]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Windows
* Nightly Browser
* selenium-server-standalone-3.4.0.jar

## Steps to reproduce
Java -Dwebdriver.gecko.driver=C:/Temp/Drivers/geckodriver.exe -jar C:/Users/QAAutomation/Downloads/selenium-server-standalone-3.4.0.jar -port 5555

- [ ] Reproducable testcase:
Ran below code, Nightly Browser opened  at remote server but throwing timeout exception in my local machine.
            /*---------C# FireFox----------*/
            FirefoxProfile fp = new FirefoxProfile();           
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
            desiredCapabilities = DesiredCapabilities.Firefox();
            desiredCapabilities.IsJavaScriptEnabled = true;
            desiredCapabilities.SetCapability("firefox_profile", fp);
            desiredCapabilities.SetCapability("marionette", true);
            desiredCapabilities.SetCapability("firefox_binary", @"C:\Program Files\Nightly\firefox.exe");
            var proxy = new Proxy { HttpProxy = "localhost:8080" };
            desiredCapabilities.SetCapability(CapabilityType.Proxy, proxy);
            var driver = new RemoteWebDriver(new Uri("http://10.5.5.66:5555/wd/hub"), desiredCapabilities);

## Exception
An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll

## Message
The HTTP request to the remote WebDriver server for URL http://10.5.5.66:5555/wd/hub/session timed out after 60 seconds.

## StackTrace
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at AutoITTest.Program.Main(String[] args) in C:\TrainingDemo\RemoteServer\AutoITTest\Program.cs:line 37
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

- [ ] A trace level log:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\QAAutomation>cd C:\Selenium\nssm-2.24\win64

C:\Selenium\nssm-2.24\win64>nssm install FireFoxRemoteServer
Error creating service!
CreateService(): The specified service already exists.

C:\Selenium\nssm-2.24\win64>nssm remove FireFoxRemoteServer
Service "FireFoxRemoteServer" removed successfully!

C:\Selenium\nssm-2.24\win64>nssm install FireFoxRemoteServer
Service "FireFoxRemoteServer" installed successfully!

C:\Selenium\nssm-2.24\win64>nssm remove FireFoxRemoteServer
Service "FireFoxRemoteServer" removed successfully!

C:\Selenium\nssm-2.24\win64>nssm install FireFoxRemoteServer
Error creating service!
CreateService(): The specified service has been marked for deletion.

Service "FireFoxRemoteServer" installed successfully!

C:\Selenium\nssm-2.24\win64>nssm remove FireFoxRemoteServer
Service "FireFoxRemoteServer" removed successfully!

C:\Selenium\nssm-2.24\win64>nssm install FireFoxRemoteServer
Service "FireFoxRemoteServer" installed successfully!

C:\Selenium\nssm-2.24\win64>cd C:\Program Files\Java\jdk1.8.0_131\bin

C:\Program Files\Java\jdk1.8.0_131\bin>Java -Dwebdriver.gecko.driver=C:/Temp/Dri
vers/geckodriver.exe -jar C:/Users/QAAutomation/Downloads/selenium-server-standa
lone-3.4.0.jar -port 5555
18:13:38.716 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
18:13:38.718 INFO - Launching a standalone Selenium Server
2017-06-08 18:13:38.763:INFO::main: Logging initialized @579ms to org.seleniumhq
.jetty9.util.log.StdErrLog
18:13:38.905 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:13:38.908 INFO - Driver provider com.opera.core.systems.OperaDriver registrat
ion is skipped:
Unable to create new instances on this machine.
18:13:38.909 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:13:38.910 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
18:13:38.912 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform
=MAC}] does not match the current platform VISTA
2017-06-08 18:13:39.021:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-06-08 18:13:39.113:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletC
ontextHandler@d8355a8{/,null,AVAILABLE}
2017-06-08 18:13:39.278:INFO:osjs.AbstractConnector:main: Started ServerConnecto
r@5f2108b5{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-06-08 18:13:39.282:INFO:osjs.Server:main: Started @1097ms
18:13:39.283 INFO - Selenium Server is up and running
18:13:56.821 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and c
lientGoneTimeout 1800000 polling every 180000
18:13:56.868 INFO - Executing: [new session: Capabilities [{proxy={httpProxy=loc
alhost:8080, proxyType=MANUAL}, firefox_binary=C:\Program Files\Nightly\firefox.
exe, marionette=true, browserName=firefox, javascriptEnabled=true, version=, pla
tform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificateI
ssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null, De
leteAfterUse=true, AcceptUntrustedCertificates=true}}]])
18:13:56.971 INFO - Creating a new session for Capabilities [{proxy={httpProxy=l
ocalhost:8080, proxyType=MANUAL}, firefox_binary=C:\Program Files\Nightly\firefo
x.exe, marionette=true, browserName=firefox, javascriptEnabled=true, version=, p
latform=ANY, firefox_profile={EnableNativeEvents=true, AssumeUntrustedCertificat
eIssuer=true, AlwaysLoadNoFocusLibrary=false, Port=7055, ProfileDirectory=null,
DeleteAfterUse=true, AcceptUntrustedCertificates=true}}]
18:13:57.844 INFO - Unable to use profile: class java.util.HashMap
18:13:57.849 INFO - Unable to use profile: class java.util.HashMap
1496970837947   geckodriver     INFO    Listening on 127.0.0.1:29041
1496970838631   mozprofile::profile     INFO    Using profile path C:\Users\QAAU
TO~1\AppData\Local\Temp\rust_mozprofile.YgRiICjAwSqH
1496970838706   geckodriver::marionette INFO    Starting browser C:/Program File
s/Nightly/firefox.exe with args []
1496970838719   geckodriver::marionette INFO    Connecting to Marionette on loca
lhost:64576

C:\Program Files\Java\jdk1.8.0_131\bin>Java -Dwebdriver.gecko.driver=C:/Temp/Dri
vers/geckodriver.exe -jar C:/Users/QAAutomation/Downloads/selenium-server-standa
lone-3.4.0.jar -port 5555
18:18:13.726 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
18:18:13.742 INFO - Launching a standalone Selenium Server
2017-06-08 18:18:13.789:INFO::main: Logging initialized @575ms to org.seleniumhq
.jetty9.util.log.StdErrLog
18:18:13.914 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:18:13.929 INFO - Driver provider com.opera.core.systems.OperaDriver registrat
ion is skipped:
Unable to create new instances on this machine.
18:18:13.929 INFO - Driver class not found: com.opera.core.systems.OperaDriver
18:18:13.929 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
18:18:13.929 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform
=MAC}] does not match the current platform VISTA
2017-06-08 18:18:14.046:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-06-08 18:18:14.140:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletC
ontextHandler@d8355a8{/,null,AVAILABLE}
2017-06-08 18:18:14.265:INFO:osjs.AbstractConnector:main: Started ServerConnecto
r@5f2108b5{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-06-08 18:18:14.265:INFO:osjs.Server:main: Started @1058ms
18:18:14.280 INFO - Selenium Server is up and running
18:18:48.005 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and c
lientGoneTimeout 1800000 polling every 180000
18:18:48.047 INFO - Executing: [new session: Capabilities [{proxy={httpProxy=loc
alhost:8080, proxyType=MANUAL}, firefox_binary=C:\Program Files\Nightly\firefox.
exe, marionette=true, browserName=firefox, javascriptEnabled=true, version=, pla
tform=ANY}]])
18:18:48.136 INFO - Creating a new session for Capabilities [{proxy={httpProxy=l
ocalhost:8080, proxyType=MANUAL}, firefox_binary=C:\Program Files\Nightly\firefo
x.exe, marionette=true, browserName=firefox, javascriptEnabled=true, version=, p
latform=ANY}]
1496971129141   geckodriver     INFO    Listening on 127.0.0.1:27826
1496971129830   mozprofile::profile     INFO    Using profile path C:\Users\QAAU
TO~1\AppData\Local\Temp\rust_mozprofile.uTBKvgtFADBv
1496971129908   geckodriver::marionette INFO    Starting browser C:/Program File
s/Nightly/firefox.exe with args []
1496971129924   geckodriver::marionette INFO    Connecting to Marionette on loca
lhost:64891

**Comment by andreastt** [comment]
I’m unable to parse what this issue report is about. Can you please clarify it?

A cursory look at your code, neither of these capabilities are recognised by geckodriver:

```c#
desiredCapabilities.SetCapability("firefox_profile", fp);
desiredCapabilities.SetCapability("marionette", true);
desiredCapabilities.SetCapability("firefox_binary", @"C:\Program Files\Nightly\firefox.exe");
```

Please see the README for the supported capabilities.

**Comment by newton143** [comment]
Still facing the timeout issue

FirefoxOptions fo = new FirefoxOptions();
fo.BrowserExecutableLocation = @"C:\Program Files\Nightly\firefox.exe";
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities = DesiredCapabilities.Firefox();
desiredCapabilities.SetCapability("moz:firefoxOptions", fo);
var driver = new RemoteWebDriver(new Uri("http://10.5.5.66:5555/wd/hub"), desiredCapabilities,
TimeSpan.FromMinutes(2));

## Trace Log
     Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.
C:\Users\QAAutomation>cd C:\Program Files\Java\jdk1.8.0_131\bin

C:\Program Files\Java\jdk1.8.0_131\bin>Java -Dwebdriver.gecko.driver=C:/Temp/Dri
vers/geckodriver.exe -jar C:/Users/QAAutomation/Downloads/selenium-server-standa
lone-3.4.0.jar -port 5555
15:19:00.721 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
15:19:00.722 INFO - Launching a standalone Selenium Server
2017-06-09 15:19:00.767:INFO::main: Logging initialized @579ms to org.seleniumhq
.jetty9.util.log.StdErrLog
15:19:00.905 INFO - Driver class not found: com.opera.core.systems.OperaDriver
15:19:00.906 INFO - Driver provider com.opera.core.systems.OperaDriver registrat
ion is skipped:
Unable to create new instances on this machine.
15:19:00.906 INFO - Driver class not found: com.opera.core.systems.OperaDriver
15:19:00.907 INFO - Driver provider com.opera.core.systems.OperaDriver is not re
gistered
15:19:00.908 INFO - Driver provider org.openqa.selenium.safari.SafariDriver regi
stration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform
=MAC}] does not match the current platform VISTA
2017-06-09 15:19:01.014:INFO:osjs.Server:main: jetty-9.4.3.v20170317
2017-06-09 15:19:01.106:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletC
ontextHandler@d8355a8{/,null,AVAILABLE}
2017-06-09 15:19:01.232:INFO:osjs.AbstractConnector:main: Started ServerConnecto
r@5f2108b5{HTTP/1.1,[http/1.1]}{0.0.0.0:5555}
2017-06-09 15:19:01.235:INFO:osjs.Server:main: Started @1048ms
15:19:01.239 INFO - Selenium Server is up and running
15:19:17.614 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and c
lientGoneTimeout 1800000 polling every 180000
15:19:17.661 INFO - Executing: [new session: Capabilities [{browserName=firefox,
moz:firefoxOptions={BrowserExecutableLocation=C:\Program Files\Nightly\firefox.
exe, UseLegacyImplementation=false, Profile=null, LogLevel=7}, version=, platfor
m=ANY}]])
15:19:17.688 INFO - Creating a new session for Capabilities [{browserName=firefo
x, moz:firefoxOptions={BrowserExecutableLocation=C:\Program Files\Nightly\firefo
x.exe, UseLegacyImplementation=false, Profile=null, LogLevel=7}, version=, platf
orm=ANY}]
1497046758738 geckodriver INFO Listening on 127.0.0.1:41360
1497046759396 mozprofile::profile INFO Using profile path C:\Users\QAAU
TO~1\AppData\Local\Temp\rust_mozprofile.9jrJ18l35ggM
1497046759408 geckodriver::marionette INFO Starting browser C:\Program File
s\Nightly\firefox.exe with args []
1497046759488 geckodriver::marionette INFO Connecting to Marionette on loca
lhost:58153
Unable to read VR Path Registry from C:\Users\QAAutomation\AppData\Local\openvr
openvrpaths.vrpath
[GPU 5180] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-cen-w64-ntly-00
0000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line
346
Unable to read VR Path Registry from C:\Users\QAAutomation\AppData\Local\openvr
openvrpaths.vrpath
[Parent 5036] WARNING: pipe error: 995: file c:/builds/moz2_slave/m-cen-w64-ntly
-000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, li
ne 464
Unable to read VR Path Registry from C:\Users\QAAutomation\AppData\Local\openvr
openvrpaths.vrpath
[Child 2500] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-cen-w64-ntly-
000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, lin
e 346
[Child 2500] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-cen-w64-ntly-
000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, lin
e 346

**Comment by whimboo** [comment]
This is not a trace log you pasted here. Please read again in the readme how to retrieve one.
