### ISSUE TITLE
Browser don't openend but junit test successful on console with remark NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized

### ISSUE THREAD

**Issue by VrushaliHaldankar** [mozilla/geckodriver#784]
In order to help us efficiently investigate your issue, please provide the following information:

1497528299485	geckodriver	INFO	Listening on 127.0.0.1:25348
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
1497528300082	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
1497528300663	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_JVavaScrAiLpUtE )e"r r olro:c arteisoonu:r c"eJ:S/ /fgrraem/em :: reosdouulrecse/:A/d/dgorneM/amnoadguelre.sj/sFmi,l elUitniel s1.6j5s7m:  :N:S _FEiRlReOURt_iNlOsT__gIeNtIDTiIrA L:I:Z ElDi:n Addoen M7a0n"a g edra tias:  nnoot]  iSntiatcika ltirzaecde
:
 FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
1497528304945	Marionette	INFO	Listening on port 53036
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
Jun 15, 2017 5:35:05 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

## Platform and application details
* Platform: Windows7  32 Bit
* Firefox: 54 Bit
* Selenium: selenium-java-3.4.0 and geckodriver-v0.16.1-win32

## Steps to reproduce
1.
RegistrationTest.java

@Before
	public void  beforeTest() throws IOException
	{
		initialize();
		TestUtil.isSkip("RegistrationTest");
		Assume.assumeTrue(false);
		
	}
	--------------------------------------------
TestUtil.java

public static boolean isSkip(String testCase)
	{
		for (int rowNum=2; rowNum <= datatable.getRowCount("Test Cases");rowNum++ )
		{
			if(testCase.equals(datatable.getCellData("Test Cases", "TCID", rowNum)))
			{
				if(datatable.getCellData("Test Cases", "Runmode", rowNum).equals("Y"))
						return false;
				else
					return true;
			}
		}
		return false;
}
-----------------------------------------------

TestBase.java
public static Xls_Reader  datatable =null;
datatable = new Xls_Reader(System.getProperty("user.dir")+"//src//Config//Suite1.xlsx");

**Comment by andreastt** [comment]
I’m sorry, but I can’t make any sense of this issue. Please follow the guide set out in the issue template when filing issues and ensure the Markdown doesn’t get mangled.

**Comment by whimboo** [comment]
No, the issue is totally clear and was the reason why I pushed to get out a quick geckodriver 0.17.0 release. :) So this is a dupe of issue #702.
