### ISSUE TITLE
Enhancement Request: Add NuGet package as part of release

### ISSUE THREAD

**Issue by rhyous** [mozilla/geckodriver#785]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows
* Firefox: n/a
* Selenium: latest release and future releases

## Steps to reproduce
This is not a bug it is an enhancement request.

The .NET community has moved to obtained dependencies via NuGet. NuGet is a dependency management tool developed and run by the .Net Foundation. www.nuget.org. It would be beneficial if the selenium web driver for firefox were published as a NuGet package.

It can be added to a build script.

- [ ] Reproducable testcase:
Open Visual Studio.
Create an MSTest project. 
Add Selenium via Manage NuGet packages.
Try to add the FIrefox Selenium driver via NuGet package.
The only NuGet package is not produced by you and therefore not trustworthy.
We cannot find 

- [ ] A trace level log:
n/a

**Comment by andreastt** [comment]
I don’t think it is the responsibility of the geckodriver developers to do distribution packaging, whether this is for NuGet, npm, PyPI, yard, crates.io, Debian, Fedora, Homebrew, MacPorts, or whatever else. We are happy for volunteers to package geckodriver in whatever way they see fit, provided the copying restrictions are respected.

We intend to provide signing of releases in the future to ensure end-users and package managers can verify the integrity of binaries. This is tracked in https://github.com/mozilla/geckodriver/issues/292.
