### ISSUE TITLE
Cannot access global JS variables when executing script

### ISSUE THREAD

**Issue by roadrunner2** [mozilla/geckodriver#79]
JS executed via the `/session/{sessionid}/execute/sync` url appears to operate on a "window" object that is distinct from the actual "window" object that JS inside the page operates on. E.g. assume the following snippet in the html page:
```html
    <script type="text/javascript">
      window.onload = function() {
        window.foobar = "hi";
      };
    </script>
```
Then the request `curl -d '{"script":"return window.foobar;", "args":[]}' 'http://localhost:2002/session/<sessionid>/execute/sync'` returns `{"value":null}`.

Interestingly enough values can be set and then retrieved, though they don't affect (i.e. are not visible to) the JS in the page:
```
$ curl -d '{"script":"window.foobar = \\"bye\\";", "args":[]}' 'http://localhost:2002/session/<sessionid>/execute/sync'
{"value":null}
$ curl -d '{"script":"return window.foobar;", "args":[]}' 'http://localhost:2002/session/<sessionid>/execute/sync'
{"value":"bye"}
```

Obviously this works fine using the FirefoxDriver, ChromeDriver, etc.

**Comment by andreastt** [comment]
This was fixed in [bug 1123506](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506). The fix is available in Firefox 48 and onwards.

Note that Firefox stable is unsupported and I would generally recommend to use Nightly.
