### ISSUE TITLE
Race condition in marionette and geckodriver

### ISSUE THREAD

**Issue by vortic** [mozilla/geckodriver#793]
## Platform and application details
* Platform: Ubuntu 16.04
* Firefox: 54.0
* Selenium: 3.4.2

## Steps to reproduce
Start several instances of `webdriver.Firefox()`. Some will fail with an error because the socket is already in use.

- [ ] Reproducable testcase:
~~~python
def goto_page(page):
    driver = webdriver.Firefox()
    driver.get(page)
    driver.quit()

pages = [] # some long list of pages
num_requests = 0
job = []
while True:
    page = next(pages, None)
    if num_requests == self.max_requests or page is None:
        for p in job:
            p.start()
        for p in job:
            p.join()
        job = []
        num_requests = 0
    if page is None:
        break
    p = Process(target=goto_page, args=[page])
    job.append(p)
    num_requests += 1
~~~

- [ ] A trace level log:
Here is the relevant log from `geckodriver.log`:

~~~
JavaScript error: chrome://marionette/content/server.js, line 330: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]

...

*************************
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: NetworkError when attempting to fetch resource.
Full stack: 
*************************
~~~

**Comment by vortic** [comment]
Two questions:
1. Is it possible to specify a custom port to use through selenium's `webdriver.Firefox()` constructor? I could not find any relevant information about ports [in the API](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.webdriver.html?highlight=webdriver.firefox#selenium.webdriver.firefox.webdriver.WebDriver)
2. If not, is it possible to kill a failed instance of `webdriver.Firefox()`? Currently it just hangs, and the entire test cannot continue.

**Comment by jgraham** [comment]
This seems like it's an issue with the selenum bindings. geckodriver supports specifying a port, so I'm not sure what else we can do here. I suggest asking in a selenium-specific channel.
