### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by jackric** [mozilla/geckodriver#794]
This repo is just a README... 4030c529d says the repo moved to Mozilla hosting but there is no obvious link to it near the top of the README, as I would expect.

**Comment by davehunt** [comment]
The source code is linked from https://github.com/mozilla/geckodriver#contributing

**Comment by jackric** [comment]
OK, that's at the bottom of the page. Why not put something at the top? Wanting see source != wanting to contribute

**Comment by andreastt** [comment]
Thanks for the suggestion. I’ve moved it further up.
