### ISSUE TITLE
Trying to create Geckodriver build for Raspberry Pi Model B (ARMv6) - help needed

### ISSUE THREAD

**Issue by Colin1964** [mozilla/geckodriver#796]
## Platform and application details
* Platform: RPi Model B rev 2 (ARMv6) running Raspian Jessie
* Firefox: Firefox 55
* Selenium: Python 3.4.3

## Steps to reproduce
geckodriver-v0.17.0-arm7hf is not compatible with ARM6 ARCH and returns segmentation fault when I tried to execute it on my Raspberry Pi Model B 1

- [x] Reproducable testcase:
pi@raspberrypi:~ $ ./geckodriver -v
Segmentation fault

Still have same issue as #354 and #560 (both closed) when trying to run geckodriver on RPi Model B Rev 2 (ARMv6) so I assume the decision not to and updates since 0.11.1 still do not include an ARM6 compatible version.  @andreastt - I have looked at info in README and I am looking to build ARM6 version if I can but as a bit of a newbie the info here seems a bit limited so I have a few questions:
I've downloaded Rustup onto my Win10 machine as I think this might be easier (faster) than using my RPi Mod B for the build. Will this work i.e. can i specify the target ARCH for the build?
What source files do I need to create the build?
Is there a MAKE file template or instructions on what needs to be included?
Any help would be appreciated.

**Comment by andreastt** [comment]
You can use rustup to install an alternate cross-compile target toolchain.

To list the available toolchains:

```
% rustup target list | grep arm
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armv7-apple-ios
armv7-linux-androideabi
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabihf
armv7s-apple-ios
```

To cross-compile Rust code you need to use `cargo build --release --target <toolchain>`, which may also require you to set up the correct linker in `.cargo/config` depending on which toolchain you use.

You could take a look at https://searchfox.org/mozilla-central/source/testing/geckodriver/ci.sh and https://searchfox.org/mozilla-central/source/testing/geckodriver/build.sh for how we do cross compilation of geckodriver from Linux x86_64 to ARMv7 (arm-unknown-linux-musleabihf).
