### ISSUE TITLE
Firefox doesn't close if onbeforeunload() function is hit on Quit

### ISSUE THREAD

**Issue by phasze** [mozilla/geckodriver#797]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
Windows 7/8/10
Firefox 54
Selenium 3.4.0 geckodriver 0.17.0

## Steps to reproduce
Fire an onbeforeunload() event while closing the browser.  An alert will show (something like 'This page is asking you to confirm that you want to leave - data you have entered may not be saved' text can be displayed) with two buttons, 'Leave Page' and 'Stay on Page'.  This prevents the browser from closing and in a Grid setup will prevent firefox from ever being freed up for another test run.

- [ ] Reproducable testcase:
navigate here and try and close firefox: http://www.4guysfromrolla.com/demos/OnBeforeUnloadDemo1.htm

**Comment by whimboo** [comment]
In case you mean the following code it works all fine for me on macOS:

```
    def test_page(self):
        self.driver.get("http://www.4guysfromrolla.com/demos/OnBeforeUnloadDemo1.htm")
        self.driver.close()
```

Please show your code and as best the trace log from geckodriver as requested in the new issue template. If we don't get this we will close the issue.

**Comment by phasze** [comment]
Try it with a grid setup.  I only mentioned that in the end of my first post but it appears to be specific to being run from the grid (remotewebdriver)

**Comment by andreastt** [comment]
We can’t reproduce this unless you add a trace-level log from geckodriver.

**Comment by phasze** [comment]
#797 provides the additional step needed.  - .quit()
