### ISSUE TITLE
with selenium mozilla will opened but url not getted..

### ISSUE THREAD

**Issue by mprjsp** [mozilla/geckodriver#799]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: 
* Firefox: 
* Selenium: 

## Steps to reproduce

- [ ] Reproducable testcase:

- [ ] A trace level log:

**Comment by mprjsp** [comment]
i get this..
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
5-3208198ce6fd}","syncGUID":"ommNmFwma9Xp","location":"app-global","version":"49.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1474578384000,"updateDate":1474578384000,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
1498581742324	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1498581742325	DeferredSave.extensions.json	DEBUG	Save changes
1498581742326	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1498581742326	addons.xpi-utils	DEBUG	Updating add-on states
1498581742327	addons.xpi-utils	DEBUG	Writing add-ons list
1498581742331	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1498581742332	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1498581742332	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1498581742333	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1498581742334	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1498581742334	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1498581742337	addons.manager	DEBUG	Provider finished startup: XPIProvider
1498581742337	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1498581742337	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1498581742338	addons.manager	DEBUG	Starting provider: GMPProvider
1498581742347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1498581742348	addons.manager	DEBUG	Starting provider: PluginProvider
1498581742348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1498581742349	addons.manager	DEBUG	Completed startup sequence
1498581744468	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1498581744468	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1498581744469	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1498581744470	DeferredSave.extensions.json	DEBUG	Starting write
1498581745094	addons.repository	DEBUG	No addons.json found.
1498581745094	DeferredSave.addons.json	DEBUG	Save changes
1498581745098	DeferredSave.addons.json	DEBUG	Starting timer
1498581745150	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1498581745150	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1498581745151	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1498581745639	DeferredSave.extensions.json	DEBUG	Write succeeded
1498581745640	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1498581745641	DeferredSave.addons.json	DEBUG	Starting write
1498581745717	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at pavab.main(pavab.java:11)
Exception in thread "main" org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe) on port 7055; process output follows: 
5-3208198ce6fd}","syncGUID":"ommNmFwma9Xp","location":"app-global","version":"49.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1474578384000,"updateDate":1474578384000,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
1498581742324	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1498581742325	DeferredSave.extensions.json	DEBUG	Save changes
1498581742326	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1498581742326	addons.xpi-utils	DEBUG	Updating add-on states
1498581742327	addons.xpi-utils	DEBUG	Writing add-ons list
1498581742331	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1498581742332	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1498581742332	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1498581742333	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1498581742334	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1498581742334	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1498581742337	addons.manager	DEBUG	Provider finished startup: XPIProvider
1498581742337	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1498581742337	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1498581742338	addons.manager	DEBUG	Starting provider: GMPProvider
1498581742347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1498581742348	addons.manager	DEBUG	Starting provider: PluginProvider
1498581742348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1498581742349	addons.manager	DEBUG	Completed startup sequence
1498581744468	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1498581744468	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1498581744469	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1498581744470	DeferredSave.extensions.json	DEBUG	Starting write
1498581745094	addons.repository	DEBUG	No addons.json found.
1498581745094	DeferredSave.addons.json	DEBUG	Save changes
1498581745098	DeferredSave.addons.json	DEBUG	Starting timer
1498581745150	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1498581745150	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1498581745151	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1498581745639	DeferredSave.extensions.json	DEBUG	Write succeeded
1498581745640	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1498581745641	DeferredSave.addons.json	DEBUG	Starting write
1498581745717	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'PRASHANTH-PC', ip: '192.168.0.103', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at pavab.main(pavab.java:11)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
5-3208198ce6fd}","syncGUID":"ommNmFwma9Xp","location":"app-global","version":"49.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1474578384000,"updateDate":1474578384000,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
1498581742324	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1498581742325	DeferredSave.extensions.json	DEBUG	Save changes
1498581742326	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1498581742326	addons.xpi-utils	DEBUG	Updating add-on states
1498581742327	addons.xpi-utils	DEBUG	Writing add-ons list
1498581742331	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1498581742332	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1498581742332	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1498581742333	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1498581742334	addons.xpi	DEBUG	Registering manifest for C:\Program Files\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1498581742334	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1498581742337	addons.manager	DEBUG	Provider finished startup: XPIProvider
1498581742337	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1498581742337	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1498581742337	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1498581742338	addons.manager	DEBUG	Starting provider: GMPProvider
1498581742347	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: GMPProvider
1498581742348	addons.manager	DEBUG	Starting provider: PluginProvider
1498581742348	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1498581742348	addons.manager	DEBUG	Provider finished startup: PluginProvider
1498581742349	addons.manager	DEBUG	Completed startup sequence
1498581744468	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1498581744468	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1498581744469	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1498581744470	DeferredSave.extensions.json	DEBUG	Starting write
1498581745094	addons.repository	DEBUG	No addons.json found.
1498581745094	DeferredSave.addons.json	DEBUG	Save changes
1498581745098	DeferredSave.addons.json	DEBUG	Starting timer
1498581745150	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1498581745150	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1498581745151	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1498581745639	DeferredSave.extensions.json	DEBUG	Write succeeded
1498581745640	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1498581745641	DeferredSave.addons.json	DEBUG	Starting write
1498581745717	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
	... 7 more

**Comment by jgraham** [comment]
You need to use the latest Selenium release.

**Comment by mprjsp** [comment]
k.tq.
