### ISSUE TITLE
Cannot get rid of "first run" page

### ISSUE THREAD

**Issue by ojii** [mozilla/geckodriver#80]
I've been using selenium + Firefox webdriver to test my web app, but Firefox 47 broke selenium integration again, and the proposed resolution was to switch to geckodriver instead. However after doing so, I can no longer get rid of the "first run" page. What makes matters even worse is that this "first run" page opens in a separate window that doesn't close then the selenium webdriver shuts down.

This is how I try to disable it:

```python
profile = webdriver.FirefoxProfile()
profile.set_preference(
    'browser.startup.homepage_override.mstone',
    'ignore'
)
profile.set_preference(
    'browser.startup.homepage',
    'about:blank'
)
profile.set_preference(
    'startup.homepage_welcome_url',
    'about:blank'
)
profile.set_preference(
    'startup.homepage_welcome_url.additional',
    'about:blank'
)
profile.set_preference(
    'intl.accept_languages',
    'en'
)
capabilities = webdriver.DesiredCapabilities.FIREFOX
capabilities['marionette'] = True
driver = Firefox(firefox_profile=profile, capabilities=capabilities)
```

How can I get rid of that damn page with geckodriver?

**Comment by fspinillo** [comment]
If you're still having trouble this is how I'm doing it:

```
fp = webdriver.FirefoxProfile()
fp.set_preference('browser.startup.homepage_orverride.mstone', 'ignore')
fp.set_preference('startup.homepage_welcome_url.additional', 'about:blank')
```

**Comment by andreastt** [comment]
I wonder if [bug 1239552](https://bugzilla.mozilla.org/show_bug.cgi?id=1239552) resolves this. It is available in Firefox 49 onwards.

**Comment by andreastt** [comment]
Of course it isn’t available in Firefox 49 because that is all related to the Marionette harness. I’ve submitted https://github.com/mozilla/geckodriver/pull/222 to geckodriver to patch it here as well.
