### ISSUE TITLE
Firefox Has Stopped Working

### ISSUE THREAD

**Issue by xinzx** [mozilla/geckodriver#803]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows 7 SP1
* Firefox: 54 64-bit
* Selenium: 3.4.3

## Steps to reproduce
Geckodriver v0.17.0
After executed script(Open Browser and Close Browser), the window pops-up "Firefox Has Stopped Working"

**Comment by andreastt** [comment]
Not reproducible.
