### ISSUE TITLE
Add Minimize Window endpoint

### ISSUE THREAD

**Issue by Sl0v3C** [mozilla/geckodriver#806]
## Platform and application details
* Platform: Ubuntu 12.04
* Firefox: FireFox 56
* Selenium: 3.4.3

## Steps to reproduce
there is no minimize window command

**Comment by andreastt** [comment]
It is true that geckodriver is missing an endpoint for minimise the window, but the Marionette remote protocol does not implement a command to minimise the window yet. It is fine to introduce this endpoint to the geckodriver- and webdriver crates before implementing it in Marionette, of course.

**Comment by AutomatedTester** [comment]
This has been added to Geckodriver and webdriver rust
