### ISSUE TITLE
Fullscreen with WebDriver.fullscreen() -> 'WebDriver' object has no attribute 'fullscreen' 

### ISSUE THREAD

**Issue by Frankstar** [mozilla/geckodriver#807]
as stated in #492 the problem should be fixed with https://bugzilla.mozilla.org/show_bug.cgi?id=1189749

So i tried it again with 
Manjaro 17.02 / 4.11.8-1
Aurora 56.0a1
geckodriver v0.17.0
selenium 3.4.3
python3

```
geckodriver = "/opt/geckodriver"
capabilities = DesiredCapabilities.FIREFOX
capabilities["marionette"] = True
browser = webdriver.Firefox(capabilities=capabilities, executable_path=geckodriver)
```

`browser.fullscreen()` gives me

> 'WebDriver' object has no attribute 'fullscreen'

so im not sure, is this now a geckodriver issue or selenium didnt implement fullscreen?

**Comment by Frankstar** [comment]
just saw #769 - but im not sure if this is related since im an java noob

**Comment by andreastt** [comment]
A missing API on the client is an issue with the client, and not with geckodriver. geckodriver 0.17.0 and greater has a `POST /session/{session id}/window/fullscreen` endpoint that can be used to send Firefox into fullscreen mode.

**Comment by Frankstar** [comment]
for the track -> https://github.com/SeleniumHQ/selenium/issues/4290
