### ISSUE TITLE
Question: Supporting stable Firefox

### ISSUE THREAD

**Issue by soulgalore** [mozilla/geckodriver#81]
Could you please elaborate on the plan for the releases of Geckodriver? When I read the issues and the releases it says either that "Only Nightly, DevEdition and Beta are officially supported" or that you should use Firefox nightly. But since the release of Firefox 47 you need to drive it with Marionette/Gecko so if I'm running Selenium and want to use Firefox 47 that is not supported? Meaning users should stay on 46 until Geckodriver 1.0? Or what's the big picture/plan?

**Comment by jgraham** [comment]
@AutomatedTester can provide a more detailed answer here, but essentially the issue at the moment is that a number of gecko-side fixes are needed to make geckodriver work, and these have not all reached the stable channel (or indeed been implemented) yet. So nightly is the best bet *for now* simply because it has the most bugfixes. Over time these will work their way into stable and then that will be fully supported.

**Comment by andreastt** [comment]
I’ll just add to @jgraham’s answer that [Nightly](http://nightly.mozilla.org/) is your safest bet, simply because it has more Marionette bug fixes and features than stable does.

You can [track the progress of the Marionette implementation in Gecko on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status).

**Comment by AutomatedTester** [comment]
@soulgalore

The reason for me specifying beta through Nightly is there is a [patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1123506) that I think most people would appreciate. After that the most fundamental bit of functionality that is missing is `Actions`. This is having a huge overhaul to allow be more atomic actions especially when interacting with services like Browserstack, Saucelabs, TestBot and <insert any other Selenium in the cloud company>

My current thinking is that I will add stable to the supported versions from Firefox 48 even if actions is missing. My anecdotal evidence is showing that Actions APIs are not used that heavily. 

If you have the capacity to run some Marionette tests now and report any unexpected differences between FirefoxDriver and Marionette this will be greatly appreciated.

**Comment by soulgalore** [comment]
Thanks for the clarifications!

I've seen two things that differ between FirefoxDriver and Marionette when you use it from Selenium:
https://github.com/mozilla/geckodriver/issues/77 but I guess then it is a Selenium implementation issue. However if you run the same code, it breaks in Marionette but not in FirefoxDriver.

The other thing is that the [HAR export trigger](https://github.com/firebug/har-export-trigger) doesn't work with Marionette, we use it automate HAR creation from Selenium. I haven't been able to see why, could be that there's a change in installing add-ons that I've missed? https://github.com/firebug/har-export-trigger/issues/30

**Comment by andreastt** [comment]
@soulgalore 

> I've seen two things that differ between FirefoxDriver and Marionette when you use it from Selenium:
#77 but I guess then it is a Selenium implementation issue.

Yes, so this needs to be patched in the client binding you’re using. I’m happy to give directions if you open a PR in Selenium and mention me in it.

> The other thing is that the HAR export trigger doesn't work with Marionette, we use it automate HAR creation from Selenium.

Is this using WebDriver primitives to do something? Can you tell what isn’t working? It would be useful if you pasted the output from Marionette (stdout) somewhere. If you set the `marionette.logging` preference to "`TRACE`" it will give you more detailed logs.

**Comment by soulgalore** [comment]
Cool, I've created an issue for Selenium,  I'll update the issue for HAR export trigger, could you @andreastt point me in the right direction to setup logs for Marionette?

**Comment by andreastt** [comment]
@soulgalore It depends a bit which binding you’re using, but passing in a profile with custom preferences should do the trick.

I think in the Selenium Python bindings you’d do:

```py
profile = webdriver.FirefoxProfile()
profile.set_preference("marionette.logging", "TRACE")
driver = webdriver.Firefox(profile)
```

**Comment by soulgalore** [comment]
ah thanks @andreastt I use nodejs. I've added to my profile but where do I get the log (we create a new profile per run)? Can I choose where it will be?

**Comment by andreastt** [comment]
@soulgalore I believe the log will go to stdout.

**Comment by soulgalore** [comment]
@andreastt yes but I think Selenium swallow it somewhere,  I will try tonight if I can get it to work.

**Comment by andreastt** [comment]
@soulgalore You’re right. I looked at the code, and in the Java bindings there’s a _FirefoxBinary#getConsoleOutput_ method: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxBinary.java#L213

You should be able to get at it by calling `driver.binary.getConsoleOutput()`, although I see it’s marked protected so you might have to jump through a few hoops with the Java typesystem.

**Comment by andreastt** [comment]
Also I see that _FirefoxBinary_ has a public method whereby you can give it your own _OutputStream_: https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/firefox/FirefoxBinary.java#L240

**Comment by soulgalore** [comment]
sorry for commenting on a closed issue: @andreastt is there away to get the log with the new 0.9.0 version? I can't find a way to set it in Selenium. I can start the Geckodriver with -vv but when I use Selenium it starts a new instance the Geckodriver. Is there a way to make it connect to an already started version?

**Comment by andreastt** [comment]
@soulgalore I agree Selenium does not do a good job at surfacing log information from drivers.

If you’re using the Node.js bindings from Selenium I believe you can set the option `stdio` here to "`inherit`", or just change the code directly: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/io/exec.js#L118
