### ISSUE TITLE
Marionette won't connect with browser after opening

### ISSUE THREAD

**Issue by ZathrasOne** [mozilla/geckodriver#811]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows 7 Enterprise, 64 bit
* Firefox: 54.0.1 (32-bit) and 54.0.1 (64-bit)
* Selenium: Selenium 3.4.0, Marionette driver, Geckodriver.exe version 0.17, both Win 32-bit and 64-bit

## Steps to reproduce
String currentDir = System.getProperty("user.dir");
String driversDir = currentDir + "/Drivers";
DesiredCapabilities capabilities;
String marionetteDriverLocation = "";
marionetteDriverLocation = driversDir+"/geckodriver.exe";
capabilities = DesiredCapabilities.firefox();
FirefoxOptions ffOptions = new FirefoxOptions();
ffOptions.setLogLevel(Level.FINEST);
ffOptions.setBinary("C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe");
capabilities.setCapability("moz:firefoxOptions", ffOptions);
capabilities.setCapability("marionette", true);
driver = new MarionetteDriver(capabilities);
driver.manage().deleteAllCookies();
driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
driver.get("https://www.soundtransit.org");

- [ ] Reproducable testcase:
Webdriver does not communicate with the browser to get a website address...

- [ ] A trace level log:
Creating new driver: Firefox, , {}, www.qa01.soundtransit.org1499383183124	geckodriver	INFO	Listening on 127.0.0.1:8671
1499383183203	geckodriver::marionette	INFO	Starting browser C:/Program Files (x86)/Mozilla Firefox/firefox.exe with args ["-marionette"]
1499383185211	geckodriver::marionette	TRACE	  connection attempt 0/600
1499383185735	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1499383185736	Marionette	INFO	Listening on port 55164
1499383186311	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:55164
1499383186314	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:55176
1499383186315	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1499383186315	geckodriver::marionette	TRACE	-> 205:[0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"platform":"ANY","version":""}},"marionette":true,"platform":"ANY","version":""}]
1499383186317	Marionette	TRACE	0 -> [0,1,"newSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox","marionette":true,"platform":"ANY","version":""}},"marionette":true,"platform":"ANY","version":""}]
1499383186321	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6584,"moz:profile":"C:\\Users\\ritterb\\AppData\\Local\\Temp\\rust_mozprofile.5x1CvujsxtqV","moz:accessibilityChecks":false}
1499383186340	Marionette	DEBUG	loaded listener.js
1499383186347	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"a3ba219a-cf69-4bc8-803c-a872f163b446","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6584,"moz:profile":"C:\\Users\\ritterb\\AppData\\Local\\Temp\\rust_mozprofile.5x1CvujsxtqV","moz:accessibilityChecks":false}}]
1499383186347	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"a3ba219a-cf69-4bc8-803c-a872f163b446","capabilities":{"browserName":"firefox","browserVersion":"54.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6584,"moz:profile":"C:\\Users\\ritterb\\AppData\\Local\\Temp\\rust_mozprofile.5x1CvujsxtqV","moz:accessibilityChecks":false}}]
1499383186347	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"a3ba219a-cf69-4bc8-803c-a872f163b446","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":false,"moz:processID":6584,"moz:profile":"C:\\Users\\ritterb\\AppData\\Local\\Temp\\rust_mozprofile.5x1CvujsxtqV","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1499383186381	webdriver::server	DEBUG	-> DELETE /session/null/cookie 
1499383186382	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}
1499383186384	webdriver::server	DEBUG	-> POST /session/null/timeouts {"type":"page load","ms":180000}
1499383186388	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}
1499383186390	webdriver::server	DEBUG	-> POST /session/null/timeouts {"type":"script","ms":60000}
1499383186391	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}
1499383186397	webdriver::server	DEBUG	-> POST /session/null/execute {"script":"window.screenX = arguments[0]; window.screenY = arguments[1]","args":[0,0]}
1499383186398	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"unknown command","message":"POST /session/null/execute did not match a known command","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x42bb79 - <no info>\n   3:   0x4219cd - <no info>\n   4:   0x4042b1 - <no info>\n   5:   0x4066e0 - <no info>\n   6:   0x687086 - <no info>\n   7:   0x413f86 - <no info>\n   8:   0x6823d1 - <no info>\n   9: 0x7540336a - BaseThreadInitThunk\n  10: 0x777c9902 - RtlInitializeExceptionChain"}}
1499383198852	webdriver::server	DEBUG	-> POST /session/null/timeouts {"type":"implicit","ms":20000}
1499383198856	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}
Completed executing Desktop_BaseClass.beforeClass
[Invoker 15068839] Invoking @BeforeMethod Desktop_BaseClass.beforeMethod(java.lang.reflect.Method)[pri:0, instance:test.java.desktop.testCases.regression.RSSNewsFeed@1edc48a]
About to begin executing Desktop_BaseClass.beforeMethod
1499383219516	webdriver::server	DEBUG	-> DELETE /session/null/cookie 
1499383219518	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}
Navigating to: 'http://www.qa01.soundtransit.org/'
1499383260726	webdriver::server	DEBUG	-> POST /session/null/url {"url":"http://www.qa01.soundtransit.org/"}
1499383260729	webdriver::server	DEBUG	<- 404 Not Found {"value":{"error":"invalid session id","message":"Got unexpected session id null","stacktrace":"stack backtrace:\n   0:   0x49dbf6 - <no info>\n   1:   0x435fd7 - <no info>\n   2:   0x41b927 - <no info>\n   3:   0x404309 - <no info>\n   4:   0x4066b7 - <no info>\n   5:   0x687086 - <no info>\n   6:   0x413b48 - <no info>\n   7:   0x6823d1 - <no info>\n   8: 0x7540336a - BaseThreadInitThunk\n   9: 0x777c9902 - RtlInitializeExceptionChain"}}

**Comment by andreastt** [comment]
It looks like your Selenium client is passing the wrong session ID to the geckodriver HTTPD:

```
1499383186390 webdriver::server DEBUG -> POST /session/null/timeouts 
```

I am guessing it fails to pick up the session ID that is returned from geckodriver when starting a new session. Please file a bug with your client binding maintainers.
