### ISSUE TITLE
Selenium gives back wrong number of open Tabs using Firefox

### ISSUE THREAD

**Issue by DavidGangel** [mozilla/geckodriver#812]
## Meta -
OS:  Mac OS Sierra
Selenium Version:  Selenium 3.4.0
Browser:  Firefox 54.0.1 (64bit)

## Expected Behavior -
A new tab opens with the loaded PDF file. In SUM you have 2 tab opened. Selenium should return that there are 2 tabs.

## Actual Behavior -
List<String> tabs = new ArrayList<>(driver.getWindowHandles());
Assert.assertTrue(tabs.size() > 1, "New PDF window was not opened after clicking PDF button");
These lines are telling that there is only one tab opened.
The same test passes on Chrome.

## Steps to reproduce -
1. Open the URL:
http://www.audi-boerse.de/gebrauchtwagen/audi/a3/a3-sportback/celle/diesel/automatik/105ps-frontantrieb-silber-2_DEU52183F-8236.htm#/i/s/l|12,1,STAT_GWPLUS,U
2. Click on the "Druckoptionen"
3. Click on the PDF

**Comment by jgraham** [comment]
@whimboo

**Comment by whimboo** [comment]
As requested in the new issue template please provide the test or at least the trace log.

**Comment by DavidGangel** [comment]
I provided the reproduction steps.
Where can I find the requested logs?

**Comment by whimboo** [comment]
No, you didn't provide them in detail enough, that we can see what the test is doing. I checked it locally with plain Marionette and it works fine for me when manually opening the pdf in a new tab.

Regarding the logs its all part of the new issue template which I referred to in my last comment. So check that or have a look at the readme file, which gives an example here: https://github.com/mozilla/geckodriver/#capabilities-examples

**Comment by DavidGangel** [comment]
The issue is not that the script is not able to open the PDF.
The issue is after Firefox opens the PDF in new tab you have 2 opened tabs.
However this line tells you have only 1 tab:
List tabs = new ArrayList<>(driver.getWindowHandles());
Assert.assertTrue(tabs.size() > 1, "New PDF window was not opened after clicking PDF button");

**Comment by whimboo** [comment]
Please show your complete code. How long are you waiting for the tab to be opened? There is no information about that which I can get out of your comments. Sorry.

**Comment by whimboo** [comment]
This works just fine for me:

```
        self.driver.get("http://www.audi-boerse.de/gebrauchtwagen/audi/a3/a3-sportback/celle/diesel/automatik/105ps-frontantrieb-silber-2_DEU52183F-8236.htm#")
        while True:
            print self.driver.window_handles
            time.sleep(.1)
```

Here the output:
> [u'2147483649']
[click on pdf link]
> [u'2147483649', u'2147483653']

**Comment by DavidGangel** [comment]
@whimboo  which geckodriver version do you use?

**Comment by andreastt** [comment]
This behaviour is (probably) not specific to geckodriver version, but to which version of Firefox you are using.

**Comment by whimboo** [comment]
Correct. You need Firefox 55 Beta or 56 Nightly, to see it working correctly.

**Comment by DavidGangel** [comment]
Ok then going to try out Firefox 55 Beta on this week and get back to you with the result.
Thank you for the support!

**Comment by DavidGangel** [comment]
I did try to run the test at SauceLab, but it's not able to start none on dev or beta:
Your test errored. The Sauce VM failed to prepare for this test. For help, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages

@whimboo do you know when will be the current Beta released?

**Comment by whimboo** [comment]
Hm, not that sure what I wrote 2 days ago. Basically you should get it working even with the latest release version of Firefox. Just add a wait until condition to your test, so that it waits until the new window handle is available. And again, without any log or real code example I cannot give any other feedback.

I'm closing this issue given that there doesn't seem to be anything actionable on our side.

**Comment by DavidGangel** [comment]
@whimboo please find the testNG code below:
```
public void testPdfGeneration() {

		LOGGER.info("Step 1 - Enter into the Car Portal");
		LandingPage landing = navigateToLandingPage();

		LOGGER.info("Step 2 - Click on '*hits' (landing.openHitsSearchResults()) - Search results page appears");
		SearchResultsPage searchResultsPage = landing.getSearchMenu().openHitsSearchResults();

		LOGGER.info("Step 3 - 3. Click on a the first car (searchResults.getCarSummary(0) - carInfoPage appears");
		carInfoPage = searchResultsPage.selectCar(1);
		String carName = carInfoPage.getCarNameText();
		carInfoPage.openPDF();

		LOGGER.info("Look for pdf window");
		List<String> tabs = new ArrayList<>(driver.getWindowHandles());
		Assert.assertTrue(tabs.size() > 1, "New PDF window was not opened after clicking PDF button");

		// wait added here for IE issues
		syncHelper.suspend(4000);
		driver.switchTo().window(tabs.get(1));
		String url = driver.getCurrentUrl();
		String pdf = AudiHelper.readPdfByUrl(url);
		Assert.assertTrue(pdf.contains(carName));

		AudiHelper.takeSnapshot("PDF_Shown");
	}
```
Where can I find the geckoDriver logs on the filesystem on MacOS?

If I add a 10sec wait that also does not helps.

**Comment by whimboo** [comment]
At which line of the code are you adding the 10s of sleep? 

The log file should be in the current working directory and is called geckodriver.log.

**Comment by whimboo** [comment]
Sorry, but I don't know TestNG so you may want to get it in contact with their support or community to figure it out.

**Comment by DavidGangel** [comment]
Khm, it should nothing to do with TestNG.
AFAIK geckodriver is a standalone process, so it's logging is managed by you guys.

**Comment by whimboo** [comment]
Then search your harddrive for such a file. If you are using geckodriver it has to create it.
