### ISSUE TITLE
Endpoints Not Accessible /session/{session id}/execute

### ISSUE THREAD

**Issue by vinfur** [mozilla/geckodriver#814]
On New Version of gecko driver
following /session/{session id}/execute Endpoint inst accessible 
on looking into change logs its found that those were discontinued
Please Continue following endpoint as it is helpful for using javascript functionalities

Thanks In Advance

**Comment by andreastt** [comment]
`/session/{session id}/execute` has been replaced by `/session/{session id}/execute/sync` to be in alignment with the [WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html).

You didn’t say which client you used, but I suspect you either need to upgrade to the most latest version or file a bug against the client binding.
