### ISSUE TITLE
Can't work out how to get a geckodriver trace in Python

### ISSUE THREAD

**Issue by djowett** [mozilla/geckodriver#816]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Ubuntu 16.04
* Firefox: 54.0
* Selenium: 3.4.3

## Steps to reproduce
This works prefectly until I try to add a firefox_options parameter as below:

	import os.path

	from django.contrib.staticfiles.testing import StaticLiveServerTestCase
	from easyprocess import EasyProcessCheckInstalledError
	from pyvirtualdisplay import Display
	from selenium import webdriver
	from selenium.common.exceptions import WebDriverException
	from selenium.webdriver.firefox.options import Log, Options

	class SeleniumTestCase(StaticLiveServerTestCase):

		def setUp(self):
			# setUp is where you instantiate the selenium webdriver and load the browser.
			try:
				self.display = Display(visible=0, size=self.virtualscreensize)
				self.display.start()
			except EasyProcessCheckInstalledError:
				print "xfvb not installed ... continuing assuming physical display available"
				self.display = None

			log_file = os.path.expanduser('~/geckodriver.log')
                        
			options = Options()
			log = Log()
			log.level = 'trace'
			options.set_preference("log", log)

			self.selenium = webdriver.Firefox(log_path=log_file, firefox_options=options)

- [x] A trace level log:
   This is what I can't produce!

**Comment by andreastt** [comment]
You’re setting the log level as  _preference_, not a capability. In any case, please raise this issue with the maintainers of the Selenium Python client.

**Comment by whimboo** [comment]
Capabilities in the Python binding are getting set via:

```
        capabilities = DesiredCapabilities.FIREFOX.copy()
        capabilities["moz:firefoxOptions"] = {
            "log": {
                "level": "trace",
            },
        }
        self.driver = webdriver.Firefox(capabilities=capabilities)
```

**Comment by djowett** [comment]
Thanks @whimboo, that's very helpful.  I found that the below also worked, but went with your suggestion in the end (the to_capabilities() method doesn't add much it seems)

            capabilities = DesiredCapabilities.FIREFOX.copy()
            log = Log()
            log.level = 'trace'
            capabilities['moz:firefoxOptions'] = log.to_capabilities()

            self.selenium = webdriver.Firefox(log_path=self.log_file, capabilities=capabilities)

**Comment by davehunt** [comment]
FWIW another approach is to use the Options class, which can be passed independently from capabilties. You shouldn't need to hard-code the `moz:firefoxOptions` key:

```python
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

options = Options()
options.log.level = 'trace'
selenium = Firefox(firefox_options=options)
```
