### ISSUE TITLE
Accessing webdriver's "maximize_window()" throws an error.

### ISSUE THREAD

**Issue by Sumedh31** [mozilla/geckodriver#824]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows 10
* Firefox: 54.0.1 (32-bit)
* Selenium:  Python language bindings for Selenium WebDriver.+Version 3.4.3 

## Steps to reproduce
Use maximize_window() webdriver method in the code.

**Note:** This issue appears only with latest geckodriver v0.18.0 and had been working fine till v0.17.0

- [ ] Reproducable testcase:
When used **self.driver.maximize_window()** in the code, it throws an error saying "selenium.common.exceptions.WebDriverException: Message: Failed to find width field"
stack trace for the selenium webdriver is:
self.driver.maximize_window()
  File "$Path\selenium-3.4.3\selenium\webdriver\remote\webdriver.py", line 588, in maximize_window
    self.execute(command, {"windowHandle": "current"})
  File "$Path\selenium-3.4.3\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "$Path\selenium-3.4.3\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to find width field

- [ ] A trace level log:
A coding exception was thrown and uncaught in a Task.

Full message: TypeError: NetworkError when attempting to fetch resource.
Full stack: 
*************************
1499930946037	Marionette	INFO	Ceased listening
 C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1499930165941	geckodriver::marionette	INFO	Connecting to Marionette on localhost:51662
1499930166362	Marionette	WARN	Deprecated preference marionette.defaultPrefs.enabled detected, please use marionette.enabled
1499930167720	Marionette	INFO	Listening on port 51662
1499930167951	Marionette	WARN	TLS certificate errors will be ignored for this session
1499930715984	geckodriver	INFO	Listening on 127.0.0.1:51874
1499930718030	mozprofile::profile	INFO	Using profile path C:\Users\USERNAME~1.TAM\AppData\Local\Temp\rust_mozprofile.2BLOWLcHVFDM
1499930718037	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe
1499930718044	geckodriver::marionette	INFO	Connecting to Marionette on localhost:51880
1499930718441	Marionette	WARN	Deprecated preference marionette.defaultPrefs.enabled detected, please use marionette.enabled
1499930719907	Marionette	INFO	Listening on port 51880
1499930720062	Marionette	WARN	TLS certificate errors will be ignored for this session
1499930948926	Marionette	INFO	Ceased listening
1499944605073	geckodriver	INFO	geckodriver 0.18.0
1499944605079	geckodriver	INFO	Listening on 127.0.0.1:50027
1499944607132	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1499944608967	Marionette	INFO	Listening on port 50033
1499944609145	Marionette	WARN	TLS certificate errors will be ignored for this session
1499944609686	Marionette	INFO	New connections will no longer be accepted
1499944804542	geckodriver	INFO	Listening on 127.0.0.1:50157
1499944806548	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1499944808376	Marionette	INFO	Listening on port 50163
1499944808567	Marionette	WARN	TLS certificate errors will be ignored for this session
1499944868385	Marionette	INFO	New connections will no longer be accepted
1499945095652	geckodriver	INFO	geckodriver 0.18.0
1499945095657	geckodriver	INFO	Listening on 127.0.0.1:50405
1499945097698	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1499945099528	Marionette	INFO	Listening on port 50411
1499945099715	Marionette	WARN	TLS certificate errors will be ignored for this session
1499945100238	Marionette	INFO	New connections will no longer be accepted

**Comment by SankySyS** [comment]
#820

**Comment by JingMa87** [comment]
I have the same issue. This is my code:
```
System.setProperty("webdriver.gecko.driver", "C:\\Program Files (x86)\\geckodriver-v0.18.0-win32\\geckodriver.exe");
DesiredCapabilities capabilities = DesiredCapabilities.firefox();
capabilities.setCapability("marionette", true);
driver = new FirefoxDriver(capabilities);
driver.get("http://damasifa.unicorn.eu/Cfrmset.asp");
driver.manage().window().maximize();
```

**Comment by andreastt** [comment]
I’m closing this bug, since it is a duplicate of #820.
