### ISSUE TITLE
"Delete Session" command blocked by JS task

### ISSUE THREAD

**Issue by jugglinmike** [mozilla/geckodriver#825]
## Platform and application details

* Platform: GNU/Linux (Ubuntu 16.04)
* Firefox: Nightly; 56.0a1 (2017-07-12) (64-bit)
* GeckoDriver version: 0.18.0
* Selenium: Python binding; version 3.4.2

## Steps to reproduce

Currently, the Delete Session command seems to interact with the browser's task queue. In
the following example, the browser is scripted to enter a blocking loop. The
subsequent Delete Session command does not complete until after that loop terminates:

    from selenium import webdriver

    browser = webdriver.Firefox(firefox_binary='/opt/mozilla/firefox-nightly/firefox')

    browser.execute_script('''
      setTimeout(function() {
          while (true) {}
        }, 0);''')

    browser.quit()

As far as I know, neither the command processing model nor the Delete Session command
itself interact with the JavaScript event loop. If that's right, then the Delete Session
command ought to complete regardless of the state of the task queue.

GeckoDriver log:

    1499958221035	geckodriver	INFO	geckodriver 0.18.0
    1499958221035	webdriver::httpapi	DEBUG	Creating routes
    1499958221038	geckodriver	INFO	Listening on 127.0.0.1:45233
    1499958222039	webdriver::server	DEBUG	-> POST /session {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"binary": "/opt/mozilla/firefox-nightly/firefox"}}, "firstMatch": []}, "desiredCapabilities": {"acceptInsecureCerts": true, "browserName": "firefox", "moz:firefoxOptions": {"binary": "/opt/mozilla/firefox-nightly/firefox"}}}
    1499958222039	geckodriver::capabilities	DEBUG	Trying to read firefox version from ini files
    1499958222040	geckodriver::capabilities	DEBUG	Found version 56.0a1
    1499958222148	geckodriver::marionette	INFO	Starting browser /opt/mozilla/firefox-nightly/firefox with args ["-marionette"]
    1499958222149	geckodriver::marionette	TRACE	  connection attempt 0/600
    1499958222249	geckodriver::marionette	TRACE	  connection attempt 1/600
    1499958222350	geckodriver::marionette	TRACE	  connection attempt 2/600
    1499958222450	geckodriver::marionette	TRACE	  connection attempt 3/600
    1499958222550	geckodriver::marionette	TRACE	  connection attempt 4/600
    1499958222630	Marionette	DEBUG	Received observer notification "profile-after-change"
    1499958222650	geckodriver::marionette	TRACE	  connection attempt 5/600
    1499958222696	Marionette	DEBUG	Received observer notification "command-line-startup"
    1499958222697	Marionette	INFO	Enabled via --marionette
    1499958222751	geckodriver::marionette	TRACE	  connection attempt 6/600
    1499958222851	geckodriver::marionette	TRACE	  connection attempt 7/600
    1499958222951	geckodriver::marionette	TRACE	  connection attempt 8/600
    1499958223051	geckodriver::marionette	TRACE	  connection attempt 9/600
    1499958223151	geckodriver::marionette	TRACE	  connection attempt 10/600
    1499958223252	geckodriver::marionette	TRACE	  connection attempt 11/600
    1499958223352	geckodriver::marionette	TRACE	  connection attempt 12/600
    1499958223452	geckodriver::marionette	TRACE	  connection attempt 13/600
    1499958223552	geckodriver::marionette	TRACE	  connection attempt 14/600
    1499958223652	geckodriver::marionette	TRACE	  connection attempt 15/600
    1499958223751	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
    1499958223753	geckodriver::marionette	TRACE	  connection attempt 16/600
    1499958223754	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
    1499958223853	geckodriver::marionette	TRACE	  connection attempt 17/600
    1499958223938	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
    1499958223940	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
    1499958223941	Marionette	INFO	Listening on port 43077
    JavaScript error: chrome://marionette/content/server.js, line 350: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
    1499958223953	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:43077
    1499958224039	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:53842
    1499958224049	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
    1499958224049	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
    1499958224054	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
    1499958224058	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"56.0a1","platformName":"linux","platformVersion":"4.8.0-58-generic","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":4648,"moz:profile":"/tmp/rust_mozprofile.xsYjP66zczRj","moz:accessibilityChecks":false}
    1499958224058	Marionette	WARN	TLS certificate errors will be ignored for this session
    1499958224112	Marionette	DEBUG	Register listener.js for window 2147483649
    1499958224133	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"c4e83e0c-7a0b-465a-8b81-4db7004b71d3","capabilities":{"browserName":"firefox","browserVersion":"56.0a1","platformName":"linux","platformVersion":"4.8.0-58-generic","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":4648,"moz:profile":"/tmp/rust_mozprofile.xsYjP66zczRj","moz:accessibilityChecks":false}}]
    1499958224142	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"c4e83e0c-7a0b-465a-8b81-4db7004b71d3","capabilities":{"browserName":"firefox","browserVersion":"56.0a1","platformName":"linux","platformVersion":"4.8.0-58-generic","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":4648,"moz:profile":"/tmp/rust_mozprofile.xsYjP66zczRj","moz:accessibilityChecks":false}}]
    1499958224142	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"c4e83e0c-7a0b-465a-8b81-4db7004b71d3","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"56.0a1","moz:accessibilityChecks":false,"moz:processID":4648,"moz:profile":"/tmp/rust_mozprofile.xsYjP66zczRj","pageLoadStrategy":"normal","platformName":"linux","platformVersion":"4.8.0-58-generic","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
    1499958224143	webdriver::server	DEBUG	-> POST /session/c4e83e0c-7a0b-465a-8b81-4db7004b71d3/execute/sync {"sessionId": "c4e83e0c-7a0b-465a-8b81-4db7004b71d3", "args": [], "script": "\n  setTimeout(function() {\n      while (true) {}\n    }, 0);"}
    1499958224144	geckodriver::marionette	TRACE	-> 169:[0,2,"executeScript",{"args":[],"newSandbox":false,"script":"\n  setTimeout(function() {\n      while (true) {}\n    }, 0);","scriptTimeout":null,"specialPowers":false}]
    1499958224145	Marionette	TRACE	0 -> [0,2,"executeScript",{"args":[],"newSandbox":false,"script":"\n  setTimeout(function() {\n      while (true) {}\n    }, 0);","scriptTimeout":null,"specialPowers":false}]
    1499958224152	Marionette	TRACE	0 <- [1,2,null,{"value":null}]
    1499958224153	geckodriver::marionette	TRACE	<- [1,2,null,{"value":null}]
    1499958224153	webdriver::server	DEBUG	<- 200 OK {"value":null}
    1499958224156	webdriver::server	DEBUG	-> DELETE /session/c4e83e0c-7a0b-465a-8b81-4db7004b71d3 
    1499958224156	geckodriver::marionette	TRACE	-> 37:[0,3,"quit",{"flags":["eForceQuit"]}]
    1499958224162	Marionette	TRACE	0 -> [0,3,"quit",{"flags":["eForceQuit"]}]
    1499958224163	Marionette	INFO	New connections will no longer be accepted
    WARNING: At least one completion condition is taking too long to complete. Conditions: [{"name":"SessionStore: flushing all windows","state":{"total":1,"current":0},"filename":"resource:///modules/sessionstore/SessionStore.jsm","lineNumber":1584,"stack":["resource:///modules/sessionstore/SessionStore.jsm:ssi_onQuitApplicationGranted:1584","resource:///modules/sessionstore/SessionStore.jsm:ssi_observe:767","chrome://marionette/content/driver.js:GeckoDriver.prototype.quit:3116",""]}] Barrier: quit-application-granted
    1499958275259	Marionette	TRACE	0 <- [1,3,null,{"cause":"shutdown"}]
    1499958275284	geckodriver::marionette	TRACE	<- [1,3,null,{"cause":"shutdown"}]
    1499958275284	webdriver::server	DEBUG	Deleting session
    1499958275284	geckodriver::marionette	DEBUG	Stopping browser process
    1499958275309	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by whimboo** [comment]
Good find. Basically this is [bug 1391594](https://bugzilla.mozilla.org/show_bug.cgi?id=1391594) now. Given that we disable the slow running script dialog by setting "dom.max_script_run_time"=0, we always see this when running tests with Marionette client or Geckodriver.

Interestingly something has been changed for Firefox 57 now and this problem even appears without having this pref changed.

I will close this issue given that it's Firefox itself which misbehaves here. Lets see which improvements we can make.

**Comment by jugglinmike** [comment]
Got it. Thanks!

**Comment by whimboo** [comment]
FYI this is now fixed on mozilla-central for Firefox 58. There will be no uplift for 57 as it looks like.
