### ISSUE TITLE
Feature request: Accept addons as base64 in /moz/addon/install

### ISSUE THREAD

**Issue by juangj** [mozilla/geckodriver#829]
(I can move this to Bugzilla if you'd rather it be there.)

The `/moz/addon/install` command accepts a path to the addon, e.g.,
```
{
  "path": "/tmp/my-addon.xpi",
  "temporary": true
}
```

For use cases where Geckodriver is running on a remote machine, it would be more convenient to be able to give a base64 blob, which Geckodriver would presumably decode and write to a temporary file, like it does with base64-encoded profiles.

Does this seem reasonable? And if so ... my guess is that it wouldn't be terribly high on your priority list, so I could give it a shot, though I guess I'd have to figure out how to send patches to mozilla-central.

**Comment by andreastt** [comment]
I think it’s a good idea to accept a Base64 string. An easy fix would be to make geckodriver accept this and put the addon somewhere temporary, then pass the path of the file onto Marionette. That way no changes to Marionette would be necessary.

What do you think?

**Comment by juangj** [comment]
Exactly what I was thinking. And Geckodriver would reject the request if it contained both a path and a base64 string.

**Comment by juangj** [comment]
Here's a sample patch that works, but isn't really pretty: [issue829.patch.txt](https://github.com/mozilla/geckodriver/files/1166846/issue829.patch.txt)

There are at least a few things I don't like about this:
* The temporary file is never deleted. There are plenty of options for creating temporary files that are automatically deleted when the file reference is dropped. That would be convenient, but I'm not sure where we should stash a reference to the file -- we need to hold onto it at least until the command is executed by Marionette.
* Because I create the temporary file in `from_json`, there's now a case where calling `from_json` followed by `to_json` yields different JSON than you started with. Actually, `from_json` seems like the wrong place for this, too -- it could be done in `MarionetteCommand.from_webdriver_message`, for example.

Any thoughts? Particularly around the question of how to manage the temp file.

(Also, should we be doing this somewhere else? Like moving the bug to Bugzilla and attaching a patch there, or on Mozreview, or...?)

**Comment by juangj** [comment]
Oh, and, I'd definitely appreciate any feedback about Rust idioms/style.

**Comment by whimboo** [comment]
@juangj having a bug filed on Bugzilla would be great. Same for your patch being uploaded to Mozreview. If you haven't done this yet, here some information https://wiki.mozilla.org/User:Mjzffr/New_Contributors.

Thanks!

**Comment by juangj** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1383931

**Comment by whimboo** [comment]
As I have seen the patch landed for geckodriver so that we can mark this issue as done. Thank you for the contribution!
