### ISSUE TITLE
timed out exception error when inizializing firefox driver

### ISSUE THREAD

**Issue by rravichandar** [mozilla/geckodriver#830]
Versions IIS: 10.0.15063.0
firefox: 55.0b9 (64-Bit)
firefox driver: Selenium.Firefox.WebDriver.0.18.0 (Installed from Nuget package manager)

Exception that occured:
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:52220/session timed out after 60 seconds. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Timeout für Vorgang überschritten.
bei System.Net.HttpWebRequest.GetResponse()
bei OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
--- Ende der internen Ausnahmestapelüberwachung ---
bei OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
bei OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
bei OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
bei OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
bei OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
bei OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
bei OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxDriverService service).

The firefox driver was initialized using following steps
 FirefoxOptions options = new FirefoxOptions();
                            options.BrowserExecutableLocation = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
                            options.LogLevel = FirefoxDriverLogLevel.Trace;
                            options.SetPreference("webdriver.log.driver.file", @"path to log file");
                            Iwebdriver driver = new FirefoxDriver(options);

**Comment by rravichandar** [comment]
I guess the issue has to do something with Remote Webdriver eventhough the local webdriver was used. The firefox(32) and geckodriver(32) starts in the background (Since IIS was used, the browser and the driver runs in the background) before this exception is thrown

**Comment by rravichandar** [comment]
This issue is resolved. It has nothing to do with gecko driver but when the Application PoolIdentity in IIS was changed to LocalSystem, it started working again.

**Comment by VNatra** [comment]
Hi,
I am seeing the same above issue. could you please suggest why?.

I am using c# and firefox

Set Up
	OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:54851/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
	Status: Timeout
	HResult: -2146233079
	at System.Net.HttpWebRequest.GetResponse()
	at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
	   --- End of inner exception stack trace ---
	HResult: -2146233088
	at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
	at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
	at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
	at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
	at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
	at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
	at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
	Selenium\Driver.cs(76,0): at PPM.QA.Framework.UI.Selenium.Driver.GetWebDriver()
	Selenium\Driver.cs(37,0): at PPM.QA.Framework.UI.Selenium.Driver.Initialize()
	Tests\TestBaseUi.cs(139,0): at PPM.QA.Tests.UI.Tests.TestFixtureBaseUi.FixtureSetUp()

**Comment by VNatra** [comment]
My scripts use to run fine on local and via Teamcity, not sure suddenly I am seeing this issue again. Your help is appreciated

**Comment by andreastt** [comment]
Please don’t resurrect long-closed issues but report a new one instead.

There’s unfortunately nothing in your paste that tells what is going wrong. Perhaps consider attaching a trace-level log when if you end up submitting a new issue.
