### ISSUE TITLE
Resource Timing API not showing correct resources in Selenium

### ISSUE THREAD

**Issue by skjindal93** [mozilla/geckodriver#831]
## Meta -
OS:  OSX
Selenium Version:  3.4.3
Browser:  Firefox
Browser Version:  54.0.1 

## Steps To Reproduce -
I have geckodriver latest version installed and I am running latest Firefox version. I wrote a selenium script to just open a URL in firefox and keep the browser open (I am not calling driver.close() or driver.quit())

Here is what the script looks like

```
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("https://www.nrk.no/")
```

<img width="1440" alt="screen shot 2017-07-18 at 9 52 46 am" src="https://user-images.githubusercontent.com/1905603/28302605-f5100d06-6bab-11e7-8473-bc4de7fb0843.png">

Now, the website is just reloaded again, so that the resources are fetched from cache. NOTE: I refreshed by just pressing enter in the address bar

The number of resources reported by Resource Timing API is < 40. Same is the discrepancy with the number of resources in Developer Tools in Networks tab. This is happening for every website.

<img width="1440" alt="screen shot 2017-07-18 at 9 54 03 am" src="https://user-images.githubusercontent.com/1905603/28302623-146f4db0-6bac-11e7-9f8e-2be8cdac7165.png">

This is not happening if I just run plain Firefox and refresh the page in the same way. The resources number match always, irrespective of the number of times I refresh the web page.

## Expected Behavior -
Number of resources for the refresh should almost be same as first reload

## Actual Behavior -
Number of resources for refresh is very less than the first reload

**Comment by whimboo** [comment]
Not sure I understand but when I do the steps in Firefox Nightly I see 130 entries for the first load of the page, and 123 for a page reload. And this is outside of Geckodriver and Marionette.

**Comment by skjindal93** [comment]
Exactly my point. If you do this without geckodriver, then it works fine. But, if you use selenium with geckodriver and do the same test. There is a huge difference in number of resources reported in first load vs second load(from cache)

**Comment by AutomatedTester** [comment]
@skjindal93 when you say this works fine without geckodriver, did you test with a new profile?

**Comment by skjindal93** [comment]
@AutomatedTester Yeah. What do you mean by new profile? I opened a new Firefox window. And the results were okay. There was no difference in number of resources reported at the time of first load vs second load

**Comment by AutomatedTester** [comment]
Since GeckoDriver or anything related to this has no impact on how this works I am going to close the bug. Also your last comment says its now okay. 

If this continues to happen I suggest you raise a bug on [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=DOM)

**Comment by skjindal93** [comment]
@AutomatedTester I said it worked fine without geckodriver. I found problem when I ran with geckodriver and got unexpected results

**Comment by AutomatedTester** [comment]
@skjindal93 create a new profile and test with that. https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile

**Comment by skjindal93** [comment]
@AutomatedTester It continues to happen even after creating a new profile. I don't think this is a Firefox bug. It is happening only when I launch Firefox using geckodriver.

**Comment by andreastt** [comment]
I tried navigating to https://www.nrk.no/ both with and without Marionette on a fresh profile (cold cache), then navigating to the same URL again (warm cache) and saw no discrepancy:

* With Marionette:
  * Cold cache: 128
  * Warm cache: 33
* Without Marionette:
  * Cold cache: 133
  * Warm cache: 28

After calling `driver.refresh()`, I also see the expected 125 resources.

Can you please help explain to me if this is not what you expect or if your findings don’t match? Please ensure you test with Firefox Nightly, as we don’t do development against Firefox 54.
