### ISSUE TITLE
Safe Browsing

### ISSUE THREAD

**Issue by Heavenwalker** [mozilla/geckodriver#836]
Opening a malicious site using geckodriver will not display the warning page (while Firefox and Safe Browsing do indeed block it). Any idea why this is happening?

I'm using this script with Python on Windows 10

BE ADVISED THE URL IN USE IS MARKED AS NOT SAFE (although it has been already brought down)

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

def checksite():

    binary = FirefoxBinary('C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe')
    firefox_capabilities = DesiredCapabilities.FIREFOX
    firefox_capabilities['marionette'] = True
    ffProfilePath="C:\\Users\\ntemk\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\qisythxl.default-
    1499803672837\\"
    profile = webdriver.FirefoxProfile(profile_directory=ffProfilePath)
    geckoPath = 'C:\seldriver\geckodriver.exe'
    driver = webdriver.Firefox(firefox_profile=profile, capabilities=firefox_capabilities, 
    executable_path=geckoPath, firefox_binary=binary)
    driver.get("http://www.network-2018.esy.es/")
    time.sleep(5)
    driver.quit()

checksite()
```

Thanks.

**Comment by AutomatedTester** [comment]
We specifically disable safe browsing when in control of Marionette/GeckoDriver. If you want it reenabled you will need to switch the prefs back using Firefox Options

**Comment by Heavenwalker** [comment]
Still even if i enable safebrowsing via preferences, when i launch Firefox via selenium, safebrowsing is still disabled 

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
#C:\Users\ntemk\AppData\Roaming\Mozilla\Firefox\Profiles\qisythxl.default-1499803672837

def checksite():

    opts=Options()

    fp = webdriver.FirefoxProfile()
    fp.set_preference("browser.safebrowsing.blockedURIs.enabled", True)
    fp.set_preference("browser.safebrowsing.downloads.enabled", True)
    fp.set_preference("browser.safebrowsing.enabled", True)
    fp.set_preference("browser.safebrowsing.forbiddenURIs.enabled", True)
    fp.set_preference("browser.safebrowsing.malware.enabled", True)
    fp.set_preference("browser.safebrowsing.phishing.enabled", True)
    driver = webdriver.Firefox(firefox_profile=fp)
    driver.get("http://www.google.com")

checksite()
```

**Comment by andreastt** [comment]
I’m willing to bet the Python client is not forwarding the profile you pass to `firefox_profile`, so it would be good if you included a trace-level geckodriver log so we could verify.

You should consider using the `FirefoxOptions` object instead, which lets you specify preferences without passing a several megabyte-large .zip file across the wire.

**Comment by whimboo** [comment]
Please note that the safe browsing files are not getting downloaded immediately after you have started Firefox. We have to randomize the delay here, but usually it should happen within the first minutes. If you want to force it please have a look at the following pure marionette test which somewhat exercises this code path.

https://dxr.mozilla.org/mozilla-central/source/testing/firefox-ui/tests/functional/security/test_safe_browsing_initial_download.py

Important should be the the preference `browser.safebrowsing.provider.google.nextupdatetime`.
