### ISSUE TITLE
Version numbers different for Windows vs Linux / OSX

### ISSUE THREAD

**Issue by jclx** [mozilla/geckodriver#84]
Windows has an extra 'v' character after '-' before version number. Causes issue with Selenium-Standalone download when on windows (firefox: '%s/v%s/geckodriver-%s-%s'). Works for Linux.

geckodriver-0.8.0-linux64.gz
geckodriver-0.8.0-OSX.gz

geckodriver-v0.8.0-win32.zip

**Comment by andreastt** [comment]
Thanks for the bug report! This will be fixed as part of https://github.com/mozilla/geckodriver/pull/83.
