### ISSUE TITLE
Please help with issue

### ISSUE THREAD

**Issue by vernekarrasika66** [mozilla/geckodriver#842]
Platform and application details
 Platform:  Windows64bit
Selenium: Version: Neon.3 Release (4.6.3)

code

---------------------
package org.ej.firsttest;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

class a {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
	        System.setProperty("webdriver.gecko.driver","D:\\\\selenium project\\library\\geckodriver.exe");
		WebDriver driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
		driver.get("http://www.facebook.com");
		driver.manage().window().maximize();
		//driver.quit();
		
		
		}

}
------------------------
This script run the and display required facebook window but display below message please resolve.

1500984017609	geckodriver	INFO	Listening on 127.0.0.1:33631
1500984019015	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1500984026768	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd32 v= and igd10iumd32 v=
1500984034229	Marionette	INFO	Listening on port 4284
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
Jul 25, 2017 5:30:35 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

**Comment by jgraham** [comment]
I don't think there's anything worrying here, if it's actually working like you say.

**Comment by andreastt** [comment]
There are problems with maximising the window with Firefox stable as shown in https://github.com/mozilla/geckodriver/issues/820 and the temporary fix is to use Firefox 55, but I can’t tell if that’s related to this issue.

**Comment by vernekarrasika66** [comment]
if I remove driver.manage().window().maximize(); line then also irt display below message.    


 1501154608062	geckodriver	INFO	Listening on 127.0.0.1:36059
1501154608631	geckodriver::marionette	INFO	Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1501154610328	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIFile.create]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1657: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd32 v= and igd10iumd32 v=
1501154615176	Marionette	INFO	Listening on port 5480
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
Jul 27, 2017 4:53:35 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
JavaScript warning: http://192.168.3.69:800/Scripts/js/jquery.handsontable.full.js, line 6209: unreachable code after return statement

**Comment by vernekarrasika66** [comment]
I am already using Firefox 55

**Comment by whimboo** [comment]
You are using an earlier version of Geckodriver from before its 0.17 release. This is a dupe of issue #702.

**Comment by vernekarrasika66** [comment]
I am using  geckodriver-v0.18.0-win64

**Comment by whimboo** [comment]
Then why are you seeing the following output line?

> 1500984019015 geckodriver::marionette INFO Starting browser \?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]

This should not be present since the 0.17 release, which is indicating a busted Firefox due to the '\?\' prefix.

**Comment by andreastt** [comment]
FWIW geckodriver 0.18.0 also logs the version number when it starts.
