### ISSUE TITLE
Release links are not available

### ISSUE THREAD

**Issue by Orekhov** [mozilla/geckodriver#843]
Release links are not available

For example, [https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-win64.zip](https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-win64.zip)

**Comment by edwarddamato** [comment]
+1 for this issue. It seems to be something related to **amazonaws**.

![image](https://user-images.githubusercontent.com/19622548/28572671-e639f640-713f-11e7-9a3f-6dc63b1583e7.png)

**Comment by Orekhov** [comment]
It is a global github issue.
Here is the reply from the github team that I just received:
> Our team is currently working to resolve a known issue with release downloads that began earlier today.

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/839.
