### ISSUE TITLE
Unable to download geckodriver from download page

### ISSUE THREAD

**Issue by ourydiallo** [mozilla/geckodriver#844]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: MacOS
* Firefox: 54
* Selenium: 3.4

## Steps to reproduce
download links are not working. if you go to https://github.com/mozilla/geckodriver/releases and click on any of the version, you get 'Secured connection failed' page
e.g. https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-macos.tar.gz

**Comment by AutomatedTester** [comment]
I can't seem to recreate this issue. Are you going through a proxy?

**Comment by jgraham** [comment]
I think GitHub was having problems yesterday. Please reopen if it still happens.
