### ISSUE TITLE
Firefox 54.1.0 not able to launch with gecko driver (v0.18.0) in TeamCity slave machine (run as windows service)

### ISSUE THREAD

**Issue by mvcskumar** [mozilla/geckodriver#847]
Firefox 54.1.0 not able to launch with gecko driver (v0.18.0) in TeamCity slave machine

## Platform and application details
* Platform: Windows Server 2016
* Firefox: 54.1.0
* Selenium: Selenium 3.4

## Steps to reproduce

When running maven as command prompt it is working but when we run from TeamCity, i am getting the below error

[02:47:08][Step 1/1] 1501123628282	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] ###!!! [Parent][MessageChannel] Error: (msgtype=0x440001,name=PContent::Msg_PBrowserConstructor) Channel error: cannot send/recv
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] ###!!! [Parent][MessageChannel] Error: (msgtype=0x440001,name=PContent::Msg_PBrowserConstructor) Channel error: cannot send/recv
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 381: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIScriptSecurityManager.getLoadContextCodebasePrincipal]
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] ###!!! [Parent][MessageChannel] Error: (msgtype=0x440001,name=PContent::Msg_PBrowserConstructor) Channel error: cannot send/recv
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 261: TypeError: frameLoader.tabParent is null
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] ###!!! [Parent][MessageChannel] Error: (msgtype=0x2C008F,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] ###!!! [Parent][MessageChannel] Error: (msgtype=0x2C0082,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
[02:47:08][Step 1/1] 
[02:47:08][Step 1/1] JavaScript error: resource://app/modules/ContentCrashHandlers.jsm, line 137: TypeError: browser.permanentKey is not a non-null object
[02:47:08][Step 1/1] JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 261: TypeError: frameLoader.tabParent is null
[02:47:08][Step 1/1] JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 45: NS_ERROR_NOT_INITIALIZED: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]
[02:55:37][Step 1/1] 1501124137747	addons.manager	INFO	Skipping background update check

Java code:

		if(browserType.equalsIgnoreCase("Firefox"))
			{
				System.setProperty("webdriver.gecko.driver", "resources\\geckodriver_win64.exe");
				FirefoxProfile profile = new FirefoxProfile();			 
				profile.setPreference("browser.download.folderList", 2);
				profile.setPreference("browser.download.manager.showWhenStarting", false);
				profile.setPreference("browser.download.dir", downloadPath);
				profile.setPreference("browser.helperApps.neverAsk.openFile",
						"text/csv,application/x-msexcel,application/excel,application/x-excel,application/vnd.ms-excel,image/png,image/jpeg,text/html,text/plain,application/msword,application/xml");
				profile.setPreference("browser.helperApps.neverAsk.saveToDisk",
		"text/csv,application/x-msexcel,application/excel,application/x-excel,application/vnd.ms-excel,image/png,image/jpeg,text/html,text/plain,application/msword,application/xml");
				profile.setPreference("browser.helperApps.alwaysAsk.force", false);
				profile.setPreference("browser.download.manager.alertOnEXEOpen", false);
				profile.setPreference("browser.download.manager.focusWhenStarting", false);
				profile.setPreference("browser.download.manager.useWindow", false);
				profile.setPreference("browser.download.manager.showAlertOnComplete", false);
				profile.setPreference("browser.download.manager.closeWhenDone", false);
				driver = new FirefoxDriver(profile);
			}

**Comment by andreastt** [comment]
`JavaScript error: chrome://global/content/bindings/remote-browser.xml, line 261: TypeError: frameLoader.tabParent is null` looks pretty bad, but as far as I know we don’t support running Firefox or geckodriver as a Windows service.

**Comment by mvcskumar** [comment]
Sorry.. may be mistake.. we are running TeamCity agent instance as window
service

**Comment by whimboo** [comment]
There is a crash happening on startup. Can you please try with a recent Firefox Nightly build, and check how that works? It supports headless on Windows, and should have some of the issues in the log fixed.

**Comment by mvcskumar** [comment]
Still issue is exist, attached the log file

Firefox Nightly version - 57.0a1 (2017-08-07) (64-bit)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by whimboo** [comment]
So it's clearly a content crash of the first tab. Sadly we don't have a way yet to get the crash signature via geckodriver. Maybe in case you have access to the machine where the tests are running, mind checking if there are unsent crash reports? You can find those here: https://support.mozilla.org/en-US/kb/mozillacrashreporter#w_viewing-reports-outside-of-firefox

**Comment by ngocvo3103** [comment]
Got the somewhat same issue when starting my test project (maven) with Jenkins (running as a service) on windows. However, everything runs fine if I use windows command prompt to run the test project.

- Platform: Windows Server 2008 R2
- Firefox version: 55.0.3
- Gecko Driver version: 0.18.0
- Selenium version: 3.5.1

Error message as below

> 1505497560234	geckodriver	INFO	geckodriver 0.18.0
> 1505497560244	geckodriver	INFO	Listening on 127.0.0.1:42859
> log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> 1505497560924	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
> 1505497561165	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
> 1505497561568	Marionette	INFO	Enabled via --marionette
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x28008C,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x280080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
> 
> JavaScript error: resource:///modules/ContentCrashHandlers.jsm, line 135: TypeError: WeakMap key must be an object, got undefined
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x44001E,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x28008C,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv
> 
> 
> ###!!! [Parent][MessageChannel] Error: (msgtype=0x280080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

**Comment by whimboo** [comment]
This is a dupe of issue #466. Locking now.
