### ISSUE TITLE
Windows resize call failing after when called more than 2 times for the same session 

### ISSUE THREAD

**Issue by vveliev** [mozilla/geckodriver#851]
Hey , i'm having problem with firefox specifically , as the code does resize call before each test case .... and it time out after 2 successful calls 

## Platform and application details
* Platform: Linux
* Firefox: 54
* Selenium: 3.34

## Steps to reproduce

```
@browser.manage.window.resize_to(1920, 1050)
```
```
@browser.manage.window.resize_to(1920, 1050)
```
```
@browser.manage.window.resize_to(1920, 1050) <-- this call will timeout
```
- [ ] Reproducable testcase:

- [ ] A trace level log:

**Comment by andreastt** [comment]
Fixed in Firefox 55 in https://bugzilla.mozilla.org/show_bug.cgi?id=1357878.
