### ISSUE TITLE
Unable to install addon with /session/:session-id:/moz/addon/install

### ISSUE THREAD

**Issue by cedricalfonsi** [mozilla/geckodriver#852]
Hello !

I'm unable to install webext plugins using the entry point : 
`/session/:session-id:/moz/addon/install`

I thought this entry point was implemented, I might do something wrong calling it.

## Platform and application details
* Platform: OSX 10.12.5
* Firefox: 53 / 54.0.1 / Developer Edition
* Selenium: 3.4 / 3.3.1
* geckodriver: 0.18 / 0.17

## Steps to reproduce
Calling the entry point
`/session/:session-id:/moz/addon/install`

with the required data
```
$data = [
    'temporary' => true,
    'path' => '/path/to/the/extension.zip'
];
```

- [ ] output:
`UnknownCommandException: POST /session/:session-id:/moz/addon/install`

Thanks in advance,
Cheers

**Comment by andreastt** [comment]
`:session-id:` in your above paste should be replaced by the ID of the session that is created from `POST /session`. It is of course entirely possible that Firefox 53/54 is too old to have a Marionette command for this, but it’s hard to tell without a trace-level geckodriver log.

**Comment by cedricalfonsi** [comment]
Hello @andreastt,

Thanks for your answer.
I do use a real session id, the :session-id: expression is only here to make the message clearer (I thought).

I have the selenium logs, but I can't find the geckodriver log file.

Here the selenium log :
https://gist.github.com/cedricalfonsi/9d2ec18861590f24a049ec0405489e93

**Comment by andreastt** [comment]
It doesn’t look like that log contains any entries from geckodriver.

**Comment by cedricalfonsi** [comment]
do you have any idea how to retrieve the geckodriver log ?
I looked for a log file, trying to change the log level, nothing seems to work.

**Comment by cedricalfonsi** [comment]
Just tested with the Nightly of Firefox, same error.

**Comment by andreastt** [comment]
It is described in the README how to make geckodriver emit trace-level logs. The tl;dr is that you need to pass the `-vv` flag or the `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` as a capability. The log is written to stdout, which you need to capture by e.g. redirecting it to a file.

Without an exact description of what input you’re sending geckodriver, it is impossible for me to guess what’s wrong.

**Comment by whimboo** [comment]
So I tried the same with the Python Selenium bindings but the latest release misses this feature. If @AutomatedTester could release a new version I would like to check how all this works from the Selenium side.

**Comment by whimboo** [comment]
With the Python bindings of Selenium 3.5 it works just fine:

1502458501825	Marionette	TRACE	0 -> [0,2,"addon:install",{"path":"/data/code/gecko/testing/marionette/harness/marionette_harness/www/addons/webextension-signed.xpi","temporary":false}]
1502458502444	Marionette	TRACE	0 <- [1,2,null,{"value":"{d3e7c1f1-2e35-4a49-89fe-9f46eb8abf0a}"}]
