### ISSUE TITLE
Run geckdriver without display on Ubuntu 16.04

### ISSUE THREAD

**Issue by Tsyklop** [mozilla/geckodriver#854]
## System
* Version: 0.18.0
* Platform: Ubuntu 16.04
* Firefox: 54.0.1
* Selenium: 3.4.0

## Testcase

I try run geckodriver and firefox in Ubuntu 16.04, but i get error:
`GDK_BACKEND does not match available displays` and crash. 

how fix this? or how run on Ubuntu 16.04 without disaply?

before i try use phantomjs, But it loads pages for a very long time. I dont now why.

## Stacktrace

Java stack trace: https://pastebin.com/YPPTCvVq

## Trace-level log

https://pastebin.com/vy6Y2jpj

**Comment by andreastt** [comment]
This isn’t a support forum for Linux, but it doesn’t look like Firefox starts at all for you. You need to set the `DISPLAY` output variable to the X display that Xvfb (or similar) has created for you in the shell session that geckodriver runs in.

Alternatively you can pass the `-headless` flag to Firefox (through a geckodriver capability in `moz:firefoxOptions`) and use Firefox’ built in headless support, although that is probably better in Firefox Nightly than in 54. See the README for an example on how to configure this.

**Comment by Tsyklop** [comment]
@andreastt i try use xvfb on this [guide](http://www.alittlemadness.com/2008/03/05/running-selenium-headless/). But not working.

**Comment by Tsyklop** [comment]
@andreastt can help me?

**Comment by andreastt** [comment]
The guide already mentions you need to put the `DISPLAY` output variable in your shell.

For example:

```
% Xvfb :99
