### ISSUE TITLE
The setup profile wipes the logging setting

### ISSUE THREAD

**Issue by BabyRoot** [mozilla/geckodriver#856]
## System
* Version: 0.18.0
* Platform: Windows 10
* Firefox: 54.0.1 32bit
* Selenium: 3.4.0

## Testcase

```
FirefoxOptions options = new FirefoxOptions();		
FirefoxProfile myProfile = new FirefoxProfile(); 
		        
options.setLogLevel(Level.OFF);
//options.setProfile(myProfile);
        
return new FirefoxDriver(options);
```

If i set myProfile in options (or in capabilities - .setCapability(FirefoxDriver.PROFILE, myProfile) ), option for LogLevel stop working.

 **log for testcase (сorrect work)**:
> Options {binary=Optional.empty, args=[], legacy=false, logLevel=OFF, prefs={}, profile=null}

> 1501857342126	geckodriver	INFO	geckodriver 0.18.0
> 1501857342133	geckodriver	INFO	Listening on 127.0.0.1:11544
> авг 04, 2017 5:35:46 PM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C
> авг 04, 2017 5:35:46 PM com.codeborne.selenide.webdriver.WebDriverFactory adjustBrowserSize
> WARNING: Cannot maximize FirefoxDriver: org.openqa.selenium.WebDriverException: Failed to find width field
> Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
> System info: host: 'VASYA-DESKTOP', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_92'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities [{moz:profile=C:\Users\user\AppData\Local\Temp\rust_mozprofile.ux6FG893XQEP, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=10.0, moz:processID=3724.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
> Session ID: 626889df-b05f-461a-af71-02c74cd3d6db

**If set profile in options:**

> Options {binary=Optional.empty, args=[], legacy=false, logLevel=OFF, prefs={}, profile=org.openqa.selenium.firefox.FirefoxProfile@17a4e61}

> 1501857404976	geckodriver	INFO	geckodriver 0.18.0
> 1501857404984	geckodriver	INFO	Listening on 127.0.0.1:38849
> 1501857406242	addons.manager	DEBUG	Application has been upgraded
> 1501857406277	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
> 1501857406279	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
> 1501857406285	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
> 1501857406289	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
> 1501857406292	addons.manager	DEBUG	Starting provider: XPIProvider
> 1501857406293	addons.xpi	DEBUG	startup
> 1501857406294	addons.xpi	INFO	Removing all system add-on upgrades.

**Comment by andreastt** [comment]
The profile shouldn’t clear your log level setting. Are you sure it is working in the first place?

Can you please include a geckodriver trace-log?

**Comment by BabyRoot** [comment]
```
FirefoxOptions options = new FirefoxOptions();
FirefoxProfile myProfile = new FirefoxProfile();
options.setLogLevel(Level.ALL);
//options.setProfile(myProfile);
return new FirefoxDriver(options);
```
Give me result - [ALL.txt](https://github.com/mozilla/geckodriver/files/1201439/ALL.txt)

```
FirefoxOptions options = new FirefoxOptions();
FirefoxProfile myProfile = new FirefoxProfile();
options.setLogLevel(Level.ALL);
options.setProfile(myProfile);
return new FirefoxDriver(options);
```

Give me result - [PROFILE_ALL.txt](https://github.com/mozilla/geckodriver/files/1201438/PROFILE_ALL.txt)

**Comment by andreastt** [comment]
In the first example, it doesn’t look like `options.setLogLevel(Level.ALL)` is being sent at all:

```
1501873657535	geckodriver::marionette	TRACE	-> 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
1501873657537	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
```

This should have included a `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` object inside the capabilities object, which means that your client is doing something strange. Is it writing the `marionette.log.level` preference to the profile itself?

Also, without seeing what’s on the packet level I’m not sure how much help I can be. Can you please provide a more detailed diagnostic? On the surface, it sounds like this is a Selenium problem.

**Comment by BabyRoot** [comment]
I did a little investigation - yes it looks like it's a problem in Selenium, I already created a ticket there [The setup FirefoxProfile in FirefoxOptions wipes the logging setting](https://github.com/SeleniumHQ/selenium/issues/4410)

**Comment by AutomatedTester** [comment]
Selenium issue has been closed
