### ISSUE TITLE
Firefox 47 does not start

### ISSUE THREAD

**Issue by zeitalexgithub** [mozilla/geckodriver#86]
Hi all,
just got Firefox upgraded to 47 and my Selenium Test stoped working with FirefoxDriver and selenium-server-standalone.
Now I am trying to switch to geckodriver. 
My system:
-    Win 7 64 bit
-    webdrivermanager1.4.5.jar
-    geckodriver-v0.8.0-win32
-    vc.redist.x86 & vc.redist.x64

After starting 
`geckodriver.exe -b "C:\Program Files\Mozilla Firefox\firefox.exe" `
it is failing to start and I am getting: 
`thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 10013, message: "Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzul\u{e4}ssig." } })', ../src/libcore\result.rs:746`

more on: https://github.com/bonigarcia/webdrivermanager/issues/35

Any help is appreciated
Alex

**Comment by jgraham** [comment]
It seems like something was unable to bind to the required socket. Please try again with either current master or 0.9.0, which will be released tomorrow and let me know if that makes a difference. Otherwise, please run with `RUST_BACKTRACE=1` and `RUST_LOG=debug` in the environment, so that we get a stack trace and logging information.

**Comment by andreastt** [comment]
Also try to use [Nightly](http://nightly.mozilla.org/) or Firefox 48 and above, as Firefox 47 is not supported.

**Comment by AbinashCSelenium** [comment]
With FF48 also it is not working - Unable to launch the browser

**Comment by jgraham** [comment]
I still think this is most likely a system configuration issue preventing you from creating the server. Can you run e.g.  `python -m SimpleHTTPServer 4444` (syntax may be slightly different on Windows)? If that fails I think you have a local configuration issue that's preventing programs from starting servers on localhost.

**Comment by andreastt** [comment]
I’m happy to re-open this if the debug information requested above is supplied.
