### ISSUE TITLE
maximaze() does not work properly with FF 55

### ISSUE THREAD

**Issue by eugenedani** [mozilla/geckodriver#860]
* Version: 0.17 or 0.18
* Platform: Windows 10 (OS build 15063)
* Firefox: 55.0
* Selenium: WebDriver 3.4.0 (Java)

If you have already maximized FF window webDriver.manage().window().maximize() command will minimize FF window instead of leaving it as it is.

**Comment by andreastt** [comment]
I doubt that calling this command will actually _minimize_ the window, but it will return the window to normal window state iff the window is already maximized.

**Comment by eugenedani** [comment]
ok, even it will return window to normal state this is not expected behavior. it never worked like this. now because of this issue some our tests started failed. i understand that u do not fix it but it becames really annoying to work with firefox. after each new ff webdriver release we have to add "if firefox then"

**Comment by andreastt** [comment]
How are you otherwise meant to get the window _out_ of maximized state?

**Comment by eugenedani** [comment]
you can add specific method for it. or if it is not possible then it will be good to have a method isMaximized to check current browser window state to understan that happen if maximize() method will be used.

**Comment by andreastt** [comment]
It will be possible to add that to the client with the next release of geckodriver because it returns a window rect object with a `state` field containing the current [window state](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-window-state).

**Comment by eugenedani** [comment]
it will be great . thanks.
just one thing if i understand it correctly you can use setSize method to get out of maximize state. please, correct me if i'm wrong

**Comment by andreastt** [comment]
Yes, but that will put the window in the set size, and not return it to its original size like you would expect if you clicked the maximise button twice.

**Comment by eugenedani** [comment]
ok. got it
thank you for explanation

**Comment by whimboo** [comment]
@andreastt I actually see a conflict with the webdriver spec here which says: `This typically increases the window to the maximum available size without going full-screen.` There is nothing in the spec which covers the part to restore a window with the exact same  command. I would say that we have to update the spec or make it clear that we want that. CC @shs96c, and @AutomatedTester.

**Comment by andreastt** [comment]
I would argue that a better API would address this by making the _Set Window Rect_ command accept a `state` field of _window states_ (minimised, maximised, fullscreen, normal) so that there would be no ambiguity what _Maximize Window_ did.

**Comment by andreastt** [comment]
Okay, the relevant changes to the specification has landed to make {Fullscreen,Minimize,Maximize} Window idempotent (calling them a second time is an in-op). I’ve submitted a series of patches in https://bugzilla.mozilla.org/show_bug.cgi?id=1391691 to fix this in Marionette, which should address this issue.
