### ISSUE TITLE
SSL Webpage Specific case error

### ISSUE THREAD

**Issue by vinfur** [mozilla/geckodriver#866]
## System
* Version:  0.18.0
* Platform: Windows  7
* Firefox: 54.0.1
* Selenium: NA

## Testcase

Navigate to https://services(.) gst(.)gov(.)in/services/login
shows certificate error while using gecko driver
while normally using FF it navigates easily
While Trying to google solution i came across this article https://stackoverflow.com/questions/30868708/how-to-use-ssl-certificates-in-selenium-web-driver

Going through this i realised that certificates arent there .
i dont know if this is right place to raise issue regarding this.
even after making ff to accept insecure certs still site has protection for keeping it secure .

**Comment by whimboo** [comment]
The referenced host is not reachable at all for me. So please figure out how to make it accessible by public, or provide us with a trace log as requested for the initial comment. How to do that you can find in the README.

**Comment by vinfur** [comment]
Reference Host Is Reachable
https://services.gst.gov.in

Please Try Navigating
I will provide trace log at night if you cant connect now
@whimboo

**Comment by whimboo** [comment]
This host is still not reachable for me. Please provide the trace level log. Thanks.

**Comment by vinfur** [comment]
> 1502711652564   webdriver::httpapi      DEBUG   Creating routes
1502711652564   geckodriver     INFO    Listening on 127.0.0.1:4444
1502711652955   webdriver::server       DEBUG   -> POST /session {"desiredCapabi
lities":{"javascriptEnabled":true,"loggingPrefs": {"performance": "ALL"},"native
Events":true,"browserName":"firefox","acceptInsecureCerts":true,"databaseEnabled
":true,"acceptSslCerts":true,"trustAllSSLCertificates":true}}
1502711656401   geckodriver::marionette INFO    Starting browser C:\Program File
s\Mozilla Firefox\firefox.exe with args ["-marionette"]
1502711658450   geckodriver::marionette TRACE     connection attempt 0/600
1502711660586   geckodriver::marionette TRACE     connection attempt 1/600
1502711661692   geckodriver::marionette DEBUG   Connected to Marionette on local
host:52638
1502711661696   geckodriver::marionette TRACE   <- {"applicationType":"gecko","m
arionetteProtocol":3}
1502711661696   geckodriver::marionette TRACE   -> 479:[0,1,"newSession",{"accep
tInsecureCerts":true,"acceptSslCerts":true,"browserName":"firefox","capabilities
":{"desiredCapabilities":{"acceptInsecureCerts":true,"acceptSslCerts":true,"brow
serName":"firefox","databaseEnabled":true,"javascriptEnabled":true,"loggingPrefs
":{"performance":"ALL"},"nativeEvents":true,"trustAllSSLCertificates":true}},"da
tabaseEnabled":true,"javascriptEnabled":true,"loggingPrefs":{"performance":"ALL"
},"nativeEvents":true,"trustAllSSLCertificates":true}]
1502711661742   geckodriver::marionette TRACE   <- [1,1,null,{"sessionId":"04ed8
312-5c26-472f-9367-a45680fc7134","capabilities":{"browserName":"firefox","browse
rVersion":"54.0.1","platformName":"windows_nt","platformVersion":"6.1","pageLoad
Strategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad
":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID
":5176,"moz:profile":"C:\\Users\\pc\\AppData\\Local\\Temp\\rust_mozprofile.gX6AB
nGmmd69","moz:accessibilityChecks":false}}]
1502711661742   webdriver::server       DEBUG   <- 200 OK {"value": {"sessionId"
:"04ed8312-5c26-472f-9367-a45680fc7134","capabilities":{"acceptInsecureCerts":tr
ue,"browserName":"firefox","browserVersion":"54.0.1","moz:accessibilityChecks":f
alse,"moz:processID":5176,"moz:profile":"C:\\Users\\pc\\AppData\\Local\\Temp\\ru
st_mozprofile.gX6ABnGmmd69","pageLoadStrategy":"normal","platformName":"windows_
nt","platformVersion":"6.1","rotatable":false,"specificationLevel":0,"timeouts":
{"implicit":0,"pageLoad":300000,"script":30000}}}}
1502711661790   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/url {"url":"https://services.gst.gov.in/services/login"}
1502711661791   geckodriver::marionette TRACE   -> 64:[0,2,"get",{"url":"https:/
/services.gst.gov.in/services/login"}]
1502711663386   geckodriver::marionette TRACE   <- [1,2,null,{}]
1502711663387   webdriver::server       DEBUG   <- 200 OK {"value": {}}
1502711667437   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element {"using":"css selector","value":"#username"}
1502711667443   geckodriver::marionette TRACE   -> 64:[0,3,"findElement",{"using
":"css selector","value":"#username"}]
1502711667457   geckodriver::marionette TRACE   <- [1,3,null,{"value":{"element-
6066-11e4-a52e-4f735466cecf":"6db72af1-db80-4381-94f0-408493549690","ELEMENT":"6
db72af1-db80-4381-94f0-408493549690"}}]
1502711667467   webdriver::server       DEBUG   <- 200 OK {"value":{"element-606
6-11e4-a52e-4f735466cecf":"6db72af1-db80-4381-94f0-408493549690"}}
1502711667519   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element/6db72af1-db80-4381-94f0-408493549690/value {"text"
:"abc","value":["abc"]}
1502711667529   geckodriver::marionette TRACE   -> 106:[0,4,"sendKeysToElement",
{"id":"6db72af1-db80-4381-94f0-408493549690","text":"abc","value":["a","b","c"]}
]
1502711667728   geckodriver::marionette TRACE   <- [1,4,null,{}]
1502711667731   webdriver::server       DEBUG   <- 200 OK {"value": {}}
1502711667767   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element {"using":"css selector","value":"#user_pass"}
1502711667772   geckodriver::marionette TRACE   -> 65:[0,5,"findElement",{"using
":"css selector","value":"#user_pass"}]
1502711667795   geckodriver::marionette TRACE   <- [1,5,null,{"value":{"element-
6066-11e4-a52e-4f735466cecf":"b2d0293a-5943-4d66-8e94-3060ca8fae22","ELEMENT":"b
2d0293a-5943-4d66-8e94-3060ca8fae22"}}]
1502711667803   webdriver::server       DEBUG   <- 200 OK {"value":{"element-606
6-11e4-a52e-4f735466cecf":"b2d0293a-5943-4d66-8e94-3060ca8fae22"}}
1502711667849   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element/b2d0293a-5943-4d66-8e94-3060ca8fae22/value {"text"
:"abc","value":["abc"]}
1502711667857   geckodriver::marionette TRACE   -> 106:[0,6,"sendKeysToElement",
{"id":"b2d0293a-5943-4d66-8e94-3060ca8fae22","text":"abc","value":["a","b","c"]}
]
1502711668015   geckodriver::marionette TRACE   <- [1,6,null,{}]
1502711668018   webdriver::server       DEBUG   <- 200 OK {"value": {}}
1502711668060   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element {"using":"css selector","value":"#captcha"}
1502711668064   geckodriver::marionette TRACE   -> 63:[0,7,"findElement",{"using
":"css selector","value":"#captcha"}]
1502711668079   geckodriver::marionette TRACE   <- [1,7,null,{"value":{"element-
6066-11e4-a52e-4f735466cecf":"5c77e4ae-e1fb-4f99-a09c-a3eef946858f","ELEMENT":"5
c77e4ae-e1fb-4f99-a09c-a3eef946858f"}}]
1502711668086   webdriver::server       DEBUG   <- 200 OK {"value":{"element-606
6-11e4-a52e-4f735466cecf":"5c77e4ae-e1fb-4f99-a09c-a3eef946858f"}}
1502711668132   webdriver::server       DEBUG   -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/element/5c77e4ae-e1fb-4f99-a09c-a3eef946858f/click {}
1502711668137   geckodriver::marionette TRACE   -> 66:[0,8,"clickElement",{"id":
"5c77e4ae-e1fb-4f99-a09c-a3eef946858f"}]
1502711668405   geckodriver::marionette TRACE   <- [1,8,null,{}]
1502711668410   webdriver::server       DEBUG   <- 200 OK {"value": {}}


hopefully this does help

**Comment by whimboo** [comment]
I don't see your problem. Navigating to the page works just fine:

```
1502711661790 webdriver::server DEBUG -> POST /session/04ed8312-5c26-4
72f-9367-a45680fc7134/url {"url":"https://services.gst.gov.in/services/login"}
1502711661791 geckodriver::marionette TRACE -> 64:[0,2,"get",{"url":"https:/
/services.gst.gov.in/services/login"}]
1502711663386 geckodriver::marionette TRACE <- [1,2,null,{}]
1502711663387 webdriver::server DEBUG <- 200 OK {"value": {}}
```

**Comment by vinfur** [comment]
Navigation Works But AS Insecure Page
But Its A Secured Page
and js has been implemented by website to avoid xmlhhtprequest on unsecured protocol
so m unable to login on page
normally on firefox page opens perfectly with secured https
while on gecko it doesnt

**Comment by whimboo** [comment]
Then why are you running with `"acceptInsecureCerts":true` when providing the trace output? Also please take a screenshot of the window when running the test.

**Comment by vinfur** [comment]
@whimboo any update?

**Comment by whimboo** [comment]
So if the page clearly doesn't load with `acceptinsecurecerts` kept as `false` (which is the default) it means that it is not secure to work with it. I cannot say why it's failing because you still haven't sent the type of certificate failure.

Also as you indicated any XMLHttpRequest are refused due to insecure data. This is nothing to blame geckodriver for. It's a security feature of the browser.

I would strongly propose to get the site fixed by using a valid SSL certificate, or that you check your machine for malware which could act as man in the middle and intercepts your connection.
