### ISSUE TITLE
Action perform() fails

### ISSUE THREAD

**Issue by ygsf** [mozilla/geckodriver#868]
## System
* Version: 3.4.0
* Platform: macOS 10.11.5
* Firefox: 3.4.0
* Selenium: 3.4.0

## Testcase

I'm writing the script for page: http://todomvc.com/examples/angularjs/#/
Step1: sendKeys to write new todo item and enter 
Step2: Double click the new item to allow update.
The code for update is:
        Actions action = new Actions(driver);
        action.moveToElement(toDoElem).doubleClick(toDoElem).perform();

The failure happen on .perform action.

## Log  and Stacktrace:

objc[91448]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
1502589978789	geckodriver	INFO	Listening on 127.0.0.1:3394
1502589979118	mozprofile::profile	INFO	Using profile path /var/folders/y2/pnrnw3hd4yz9rx5fpj_2gqh9r_tq2q/T/rust_mozprofile.wFZve3qaGkEj
1502589979119	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin
1502589979152	geckodriver::marionette	INFO	Connecting to Marionette on localhost:53903
1502589979733	Marionette	INFO	Listening on port 53903
Aug 13, 2017 12:06:21 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

org.openqa.selenium.InvalidArgumentException: Missing or invalid type argument for pointer action
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info:  os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161129173726, version=50.0.2, platform=MAC, proxy=Proxy(), command_id=1.0, specificationLevel=0.0, acceptSslCerts=false, processId=91450.0, browserVersion=50.0.2, platformVersion=15.5.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, javascriptEnabled=true, platformName=darwin}]
Session ID: 3cac2a03-2ec0-6c4e-81f5-f48f2ee09f43
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
  at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:703)
  at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:631)
  at org.openqa.selenium.interactions.Actions.perform(Actions.java:593)

**Comment by whimboo** [comment]
So some things we need:

* Correct versions of geckodriver (you might want to upgrade)
* A trace level log (see the README on this repository)

You are using Firefox 50.0.2 which is no longer supported. Please clearly upgrade your browser to 55.0 or if not possible at least 52.0ESR.

Also please update to Selenium 3.5 which has been released some days ago, if that changes something.

**Comment by TJEvans** [comment]
Seeing the same problem writing unit tests for a selenium framework. 
geckodriver 0.18.0
FF 55.0.3

Testcase - 
Expect that the color of the button text changes when double clicked
Actual, after double click the rgb value remains white

steps:
load url: http://www.seleniumframework.com/Practiceform/
By doubleClickBtn = By.id("doubleClick");
new Actions(driver).action.moveToElement(doubleClickBtn ).doubleClick(doubleClickBtn ).perform();
validate new CSS color property of doubleClickbtn

Logs:
1504190706996	webdriver::server	DEBUG	-> POST /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/element {"value":"#doubleClick","using":"css selector"}
1504190707002	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"bc53655d-306b-445d-9741-9fa27afa5bad"}}
1504190707010	webdriver::server	DEBUG	-> GET /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/element/bc53655d-306b-445d-9741-9fa27afa5bad/css/color 
1504190707019	webdriver::server	DEBUG	<- 200 OK {"value":"rgb(255, 255, 255)"}
1504190707026	webdriver::server	DEBUG	-> POST /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/elements {"value":"#doubleClick","using":"css selector"}
1504190707031	webdriver::server	DEBUG	<- 200 OK {"value":[{"element-6066-11e4-a52e-4f735466cecf":"bc53655d-306b-445d-9741-9fa27afa5bad"}]}
1504190707041	webdriver::server	DEBUG	-> POST /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/execute/sync {Crazy long Sync JS},"args":[{"element-6066-11e4-a52e-4f735466cecf":"bc53655d-306b-445d-9741-9fa27afa5bad"}]}
1504190707078	webdriver::server	DEBUG	<- 200 OK {"value":true}
1504190707089	webdriver::server	DEBUG	-> GET /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/element/bc53655d-306b-445d-9741-9fa27afa5bad/enabled 
1504190707097	webdriver::server	DEBUG	<- 200 OK {"value":true}
1504190707105	webdriver::server	DEBUG	-> POST /session/1b86c42c-1490-41e4-b126-4b628f6c8f57/actions {"actions":[{"id":"default mouse","type":"pointer","parameters":{"pointerType":"mouse"},"actions":[{"duration":100,"x":0,"y":0,"type":"pointerMove","origin":{"ELEMENT":"bc53655d-306b-445d-9741-9fa27afa5bad","element-6066-11e4-a52e-4f735466cecf":"bc53655d-306b-445d-9741-9fa27afa5bad"}},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}]}]}
1504190707247	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by AutomatedTester** [comment]
@TJEvans your issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1385476

Closing this bug as information asked for hasnt been given.
