### ISSUE TITLE
Back action on a page with iframes hangs the driver for 5 minutes and throws an exception.

### ISSUE THREAD

**Issue by pradhan-v** [mozilla/geckodriver#870]
**_Page details..._**
Page 1 : One link pointing to page 2.
Page 2 : has 2 iframes. Each iframe has a page with a text box and a submit button. On click of the submit button, the form is submitted to bing/google.com to perform a search.

**_Navigation..._**
Click on the link in page 1 to go to page 2.
In the first iframe, enter text in the text box and click submit. The form is submitted and the search is performed.
Navigate back.
Navigate back (again)

_The first back action is performed but, an exception is thrown after 5 minutes._

## System
* Version: 0.18
* Platform: Windows, Mac
* Firefox: 53
* Selenium: 3.4, Java 1.8

## Testcase

Java program.
performActionInFrame1() method uses webdriver to perform the search action in the iframe and performActionInFrame2() uses javascript to do the same.

	public class FirefoxBackAction {
	  private WebDriver driver;

	  public static void main(String[] args) throws Exception {
		FirefoxBackAction fba = new FirefoxBackAction();
		fba.setUp();
		fba.testBackAction();
		fba.tearDown();
	  }

	  // @Before
	  public void setUp() throws Exception {
		System.setProperty("webdriver.gecko.driver", "<path to geckodriver.exe>");
		driver = new FirefoxDriver();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	  }

	  // @Test
	  public void testBackAction() throws Exception {
		driver.get("https://pradhan-v.github.io/");
		for (int i = 0; i < 2; i++) {
		  driver.findElement(By.linkText("Firefox back button Issue")).click();
		  // performActionInFrame1();
		  performActionInFrame2();
		  goBackTwice();
		}
	  }

	  private void goBackTwice() throws Exception {
		driver.navigate().back();
		driver.navigate().back();
	  }

	  private void performActionInFrame1() throws Exception {
		((JavascriptExecutor) driver).executeScript( "document.getElementById('iframe_a').contentWindow.document.getElementsByName('q')[0].value='search';");
		((JavascriptExecutor) driver).executeScript( "document.getElementById('iframe_a').contentWindow.document.getElementsByTagName('input')[1].click();");
	  }

	  private void performActionInFrame2() throws Exception {
		driver.switchTo().frame("iframe_a");
		driver.findElement(By.name("q")).sendKeys("search");
		driver.findElement(By.id("sub")).click();
		driver.switchTo().defaultContent();
	  }

	  // @After
	  public void tearDown() throws Exception {
		driver.quit();
	  }

	}

## Stacktrace
`
Exception in thread "main" org.openqa.selenium.TimeoutException: Timeout loading page after 300000ms
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'PRADHAN-50', ip: '9.79.150.52', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\Pradhan\AppData\Local\Temp\rust_mozprofile.IxYZx0QhZga5, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=53.0.3, platformVersion=10.0, moz:processID=22952.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 2881fcbf-bea1-49da-bd64-73801d456a32
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:88)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:437)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:150)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:115)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.back(RemoteWebDriver.java:937)
	at com.example.tests.FirefoxBackAction.goBackTwice(FirefoxBackAction.java:84)
	at com.example.tests.FirefoxBackAction.testBackAction(FirefoxBackAction.java:73)
	at com.example.tests.FirefoxBackAction.main(FirefoxBackAction.java:27)
`

**Comment by whimboo** [comment]
Well, the problem here is that you switch back to the parent before issuing the first `back` command. And that would cause a page navigation for frame 1. As such no page load events are received because the parent doesn't see those.

So the solution would be to move `driver.switchTo().defaultContent();` in-between the two calls to `back` inside of `goBackTwice()`.

**Comment by MadPiranha** [comment]
Adding `driver.switchTo().defaultContent();` in-between the two `back()` calls does not help.
This problem is reproducible even if use javascript(executeScript) to perform these actions

**Comment by whimboo** [comment]
The test as following works perfectly fine for me:
```
    def test_page(self):
        self.driver.get("https://pradhan-v.github.io/")
        elem = self.driver.find_element_by_link_text("Firefox back button Issue")
        elem.click()

        frame = self.driver.find_element_by_id("iframe_a")
        self.driver.switch_to_frame(frame)
        search = self.driver.find_element_by_name("q")
        button = self.driver.find_element_by_id("sub")

        search.send_keys("search")
        button.click()

        self.driver.back()
        self.driver.switch_to_frame(None)
        self.driver.back()
```

Please note that you are also using an outdated version of Firefox. So please upgrade.

Also please note that the underlying frame is getting removed by the second `back` navigation. As such you have to switch to the parent frame first. Please also see issue #874 which handles this situation.
