### ISSUE TITLE
Add start firefox process with window not visible

### ISSUE THREAD

**Issue by scottneye** [mozilla/geckodriver#871]
## System

* Platform: Windows 7
* Firefox: FireFox 54

## Testcase

could there be a command line switch to start the firefox process with its window not visible?

**Comment by whimboo** [comment]
What should visible mean? With the current 57 nightly build of Firefox you would be able to run Firefox in headless mode. Is that what you request here? If not please be more clear with the details.

**Comment by whimboo** [comment]
I don't think that this is something we want/can do? First I don't see a command line argument for Firefox which could handle that. Do other browsers have that? Second it's nothing as specified in the spec.

If that is really something what you want, maybe do not specify firefox directly as binary but a shell script which could handle that?

@andreastt what do you think?

**Comment by scottneye** [comment]
I also can't find a way to do it from firefox. Only from the application that starts the browser.

I followed your suggestion and tried to specify programs other than firefox directly as binary which would then call firefox. With both a compiled exe and a vbs script, python throws the error: 'WebDriverException: Message: Unable to find a matching set of capabilities'.

Using a bat script as the binary it does start firefox but then the python script hangs and nothing happens until I close firefox, which then causes the same error as above. I also tried to forward the command line parameters received by the bat script to firefox but the same error pops up without it even starting.

**Comment by andreastt** [comment]
geckodriver is not going to implement functionality for starting Firefox in minimised window state. I don’t see any use cases for that. If you don’t want the window to steal focus whilst you are automating Firefox, you can pass the `-headless` flag to Firefox through the `moz:firefoxOptions` capabilities object. There is even an example in the README on how to configure it.
