### ISSUE TITLE
Selenium does not wait after calling WebElement.submit()

### ISSUE THREAD

**Issue by mgruner** [mozilla/geckodriver#878]
## System
* Version: 0.18.0
* Platform: OS X 10.11.6 (15G1611)
* Firefox: 55.0.2
* Selenium: 3.4.0

## Summary
With Firefox 47 (without marionette), calling `submit()` on a `WebElement` caused Selenium to wait until the page loaded (just as it also works in current Chrome). This is not the case with current Firefox. Is that intended behaviour? Our test suite relies on that implicit wait currently. Thanks for all advice.

## How to reproduce
If a submit() is triggered on a form, the following test code runs in the context of the old page.

@whimboo @davehunt any help will be most appreciated. Sorry, I'm not familiar with the technical details of Selenium's internals.

**Comment by andreastt** [comment]
We can probably leave this open to track the issue in Selenium.

**Comment by mgruner** [comment]
Hello @andreastt. Thanks for your reply. How does this proceed now?

**Comment by andreastt** [comment]
@mgruner This isn’t an issue with geckodriver, and I don’t believe anyone has filed an issue against Selenium yet.

**Comment by mgruner** [comment]
@andreastt can you please explain that? It does work both in old Firefox and also in recent Chrome with Chromedriver. Can it then really be a Selenium issue? Will they not tell me to report it here if it only occurs with Firefox?

**Comment by mgruner** [comment]
I opened an issue at https://github.com/SeleniumHQ/selenium/issues/4570.
