### ISSUE TITLE
Selenium 3.5.0-GeckoDriver 0.18.0-Python 3.6.1 : "OSError: [WinError 6] The handle is invalid" is observed while close() is called through Python PyDev (Eclipse) unittest module

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#879]
## System
* GeckoDriver Version: 0.18.0
* Platform: Windows 8 Pro, 64 bit
* Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0 (Python 3.6.1)

## Testcase
`OSError: [WinError 6] The handle is invalid` error is observed while `close()` method is called through Python PyDev (Eclipse) unittest module.

Code Block:

	import unittest
	from selenium import webdriver
	from selenium.webdriver.common.keys import Keys

	binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'

	class PythonOrgSearch(unittest.TestCase):

	    def setUp(self):
		self.driver = webdriver.Firefox(firefox_binary=binary, executable_path=r'C:\Utility\BrowserDrivers\geckodriver.exe')

	    def test_search_in_python_org(self):
		driver = self.driver
		driver.get("http://www.python.org")
		self.assertIn("Python", driver.title)
		elem = driver.find_element_by_name("q")
		elem.send_keys("pycon")
		elem.send_keys(Keys.RETURN)
		assert "No results found." not in driver.page_source

	    def tearDown(self):
		self.driver.close()

	if __name__ == "__main__":
	    unittest.main()
## Trace-level log

	Finding files... done.
	Importing test modules ... done.

	----------------------------------------------------------------------
	Ran 1 test in 16.387s

	OK
	Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x035559B0>>
	Traceback (most recent call last):
	  File "C:\Python\lib\subprocess.py", line 763, in __del__
	    self._internal_poll(_deadstate=_maxsize)
	  File "C:\Python\lib\subprocess.py", line 1025, in _internal_poll
	    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
	OSError: [WinError 6] The handle is invalid

**Comment by andreastt** [comment]
This appears to be a problem with the Selenium Python client. Please report appropriately.

**Comment by Debanjan-B** [comment]
@andreastt I am sorry, I am not sure where to put Selenium Python client bugs. I thought `mozilla/geckodriver` queue accepts `Java` and `Python` both the bindings.

**Comment by andreastt** [comment]
The Selenium project tracks its issues at https://github.com/seleniumhq/selenium.

**Comment by Debanjan-B** [comment]
Thanks for the help @andreastt
