### ISSUE TITLE
Driver crash when running firefox with an xpi

### ISSUE THREAD

**Issue by nirp1981** [mozilla/geckodriver#88]
Firefox version : 48.0b1
Driver : geckodriver-v0.8.0-win32.zip
Selenium version : 2.53

When adding any XPI to the MarionetteDriver , It crashes immediately after the driver starts, I cant get the logs because the eclipse IDE gets stuck.
Try to run :

```
@Test
public void test1() throws Exception{
    WebDriver _driver; 
    FirefoxProfile profile = new FirefoxProfile();
    profile.addExtension(new File("C:\\Xpi\\firebug.xpi"));
    DesiredCapabilities dc = DesiredCapabilities.firefox();
    dc.setCapability(FirefoxDriver.PROFILE, profile);
    OSUtils.setSystemProperty("webdriver.firefox.bin", "C:\\FirefoxBeta\\firefox.exe");
    OSUtils.setSystemProperty("webdriver.gecko.driver","C:\\Drivers\\geckodriver.exe");
    _driver = new MarionetteDriver(dc);
    }
```

I tried with several xpi files , It happened consistently.

**Comment by jgraham** [comment]
Can you start geckodriver with RUST_LOG=debug in the environment and upload the generated logs? Otherwise a link to an example extension that's failing might help.

**Comment by nirp1981** [comment]
Hello , No problem I am adding two extensions - firebug & our tested extension. Both fail to load.(change the txt to xpi)
Thank you!
[walkme.txt](https://github.com/mozilla/geckodriver/files/336600/walkme.txt)
[firebug.txt](https://github.com/mozilla/geckodriver/files/336595/firebug.txt)

**Comment by andreastt** [comment]
Unable to reproduce.
