### ISSUE TITLE
Support multiple Firefox instances

### ISSUE THREAD

**Issue by zdm** [mozilla/geckodriver#882]
In phantomjs and chromedriver I can POST /session to create new browser session.
But, seems, that with geckodriver I can have only one session, all subsequent requests returning "Session is already started".
How I can start multiple sessions using single geckodriver process?
Is it possible at all or I should run new geckodriver instance each time, when I need new session?

**Comment by andreastt** [comment]
You need multiple geckodriver processes to create multiple sessions. One session of geckodriver can only host a single Firefox process.

In phantomjs or the client you’re using, this should merely be an implementation detail.

**Comment by andreastt** [comment]
It is of course possible to patch geckodriver so that it can support multiple instances of Firefox, but this is not something that is on our list of priorities.

**Comment by zdm** [comment]
I understood, thank you for reply.

**Comment by andreastt** [comment]
I actually quite like the idea that a single geckodriver could support multiple Firefoxen. I am going to leave this bug open for tracking.

**Comment by zdm** [comment]
Yes, this would be perfect and would allow to operate different webdrivers in the same way.

**Comment by klausenbusk** [comment]
Is there anyway I can get the active session id? I need it, so I can kill the session if our program crash between a session create and delete.

**Comment by andreastt** [comment]
@klausenbusk To prevent hijacking of sessions, it’s not possible to get a list of session IDs from WebDriver.

The session ID is only returned from the initial session creation request. If you need to keep track of it in case the program crashes, you could try e.g. serialising it to disk with the understanding that other processes on the system could interfere with it.
