### ISSUE TITLE
Actions.sendKeys(" ") does not click button

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#886]
## System
* Version: 0.18
* Platform: Windows 10 Creators Update
* Firefox: 55.0.2
* Selenium: 3.4

## Testcase

The unit test below fails because sending `" "` to the button does not click the button.
The behavior is the same for other elements except text fields.
If `" "` is replaced by `Keys.SPACE` the test succeeds.

Java Selenium Test:
```java
  @Test
  public void testSendSpaceAsStringToButton_withFocusAndActions_1click() {
    // given
    webDriver.navigate().to("http://localhost/CountingButton.html");
    WebElement button = webDriver.findElementByTagName("button");
    WebElement clickCountElem = webDriver.findElementById("click-count");
    assertEquals("0", clickCountElem.getText());
    webDriver.executeScript("arguments[0].focus()", button);
    
    // when
    new Actions(webDriver).sendKeys(" ").perform();
    
    // then
    assertEquals("1", clickCountElem.getText()); // FAILS!
  }
```

CountingButton.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <title>Counting Button</title>
</head>
<body>
    <h1>Counting Button</h1>
    <button onclick="buttonPressed();">Button</button>
    <p>
        Clicks: <span id="click-count">0</span>
    </p>
    <script>
        var clickCount = 0;
        var clickCountElem = document.getElementById("click-count");

        function buttonPressed() {
            clickCount++;
            clickCountElem.innerText = clickCount
        }
    </script>
</body>
</html>
```

[CountingButtonHTML.zip](https://github.com/mozilla/geckodriver/files/1238566/CountingButtonHTML.zip)

## Stacktrace

```
org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at SendKeysTests.testSendSpaceAsStringToButton_withFocusAndActions_1click(SendKeysTests.java:322)
```

## Trace-level log

[geckodriver-log.zip](https://github.com/mozilla/geckodriver/files/1238564/geckodriver-log.zip)

**Comment by andreastt** [comment]
@mjzffr Is sending `" "` (empty space) meant to trigger a `keydown`, `keyup`, and `click` event on a `<button>`? I think not?

**Comment by mjzffr** [comment]
@andreastt Huh, I've learned something new. Yes, keydown, keyup and click.

click is supposed to fire if you press space while a button has focus. Same for check boxes, but not for anchors. Anchors only react to "enter" key.

**Comment by andreastt** [comment]
> click is supposed to fire if you press space while a button has focus. Same for check boxes, but not for anchors. Anchors only react to "enter" key.

What a remarkable and wonderfully exciting world the web is.

**Comment by AutomatedTester** [comment]
Riased https://bugzilla.mozilla.org/show_bug.cgi?id=1398098

**Comment by whimboo** [comment]
Good news. This has been fixed in Firefox Nightly 76 today via https://bugzilla.mozilla.org/show_bug.cgi?id=1417955.
