### ISSUE TITLE
Is there a way to set the logging level? Default is TRACE.

### ISSUE THREAD

**Issue by kapoorlakshya** [mozilla/geckodriver#89]
Hello,

I am using Watir-WebDriver + Selenium-WebDriver 2.53.3 + geckodriver 0.8.0 for automated testing on Firefox 47. By default, the log level is set to TRACE. Is there a way for me to switch to INFO or completely turn off logging to STDOUT?

I am using Jenkins to run my tests and the console output is a mess. It is hard for me to differentiate between the logs from the AT framework and the driver. My Watir call:

`Watir::Browser.new(:firefox, marionette: true)`

What could I pass in to new() to alter the logging level?

**Comment by andreastt** [comment]
Marionette’s default logging level for optimised builds is _Log.Level.Info_ and _Log.Level.Debug_ for debug/non-optimise builds. Can you check `marionette.logging` in about:config in your build and see if it is bold? If it is bold it means it’s been changed by the user away from the default.

**Comment by kapoorlakshya** [comment]
I do not have an option for **marionette.logging**. I am using the regular build and here are my steps:

`1. firefox.exe -marionette
2. about:config
3. Search for marionette`

I only get marionette.force-local which is set to true.

**Comment by dmansfield** [comment]
I also get TRACE level logging using MarionetteDriver from selenium (WebDriver) using Java. I've done nothing in particular to enable this that I'm aware of. I have no marionette settings at all in "about:config" in a regular browser session, and I have the same "force-local" as @kapoorlakshya

**Comment by andreastt** [comment]
@kapoorlakshya @dmansfield What Firefox version are you using? Marionette lives inside Gecko.

**Comment by kapoorlakshya** [comment]
I am on 47.0.

**Comment by andreastt** [comment]
Can you try with Nightly to see if that makes a difference? 47 is not supported.

**Comment by kapoorlakshya** [comment]
I tried Nightly 50.0a1 (2016-06-14) 32-Bit and it does not have the **marionette.logging** option.

> 47 is not supported.

That is strange. Selenium-WebDriver has switched to using geckodriver for Firefox 46+ (http://stackoverflow.com/questions/37693106/selenium-2-53-not-working-on-firefox-47 and https://github.com/SeleniumHQ/selenium/issues/1862). If I use the FirefoxDriver, I get a timeout error:

`Selenium::WebDriver::Error::WebDriverError: unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055)`

What else could I possibly use for Firefox 47 then?

**Comment by andreastt** [comment]
> That is strange. Selenium-WebDriver has switched to using geckodriver for Firefox 47+

Don’t believe everything you read on the internet (-:

Firefox 47 does ship with Marionette, but it might not have all the necessary bug fixes and patches to work properly.

> What else could I possibly use for Firefox 47?

I would suggest using Nightly or wait for the release of 47.0.1 that will fix the issues FirefoxDriver is having.

**Comment by soulgalore** [comment]
@andreastt so 47.0.1 will work with the Firefoxdriver again and the switch will be in 48?

**Comment by kapoorlakshya** [comment]
Good to know 47.0.1 will support it. Do you by any chance have an ETA?

> Don’t believe everything you read on the internet (-:

I assumed the Selenium Member @lukeis who stated that would know what he is talking about :P

Thanks for responding!

**Comment by lukeis** [comment]
what did i say exactly? :)

Selenium 3.0 will switch to using geckodriver by default... current releases haven't switched.

**Comment by kapoorlakshya** [comment]
Hello @lukeis,

I just realized what I did. I confused myself and misspoke about selenium switching to marionette for Firefox 47+. I should have said that you recommend using marionette for Firefox 47+. Does that sound correct? I apologize for the confusion here. 

In this issue (https://github.com/SeleniumHQ/selenium/issues/1862), you posted:

> We're unlikely to fix this and you should start using Marionete

I was experiencing the same issue with Firefox 47 so after reading your comment I started messing around with marionette.

**Comment by andreastt** [comment]
> Good to know 47.0.1 will support it. Do you by any chance have an ETA?

@kapoorlakshya I think it depends on the release engineering team at Mozilla, and we’re all at a work week in London this week. @AutomatedTester might know more.

> so 47.0.1 will work with the Firefoxdriver again and the switch will be in 48?

@soulgalore That’s correct.

**Comment by andreastt** [comment]
I still want to find out why the logging level is TRACE by default, however. Can someone confirm what logging output Nightly (Firefox 50) gives when using Marionette?

**Comment by kapoorlakshya** [comment]
I found something interesting...

When I run my tests locally on Firefox 47.0 with marionette, I do not see any logging - same as FirefoxDriver on Firefox 46. However, when I run my tests via Jenkins, I see TRACE logging. This behavior is experienced in both 47.0 and Nightly 50.0a1 (2016-06-16).

Here are a few lines from the beginning of the log:

```
1466104520021	Marionette	DEBUG	Marionette enabled via build flag and pref
1466104520181	Marionette	INFO	Listening on port 2828
1466104520437	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:60463
1466104520473	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{"acceptSslCerts":false,"browserName":"firefox","browserVersion":null,"marionette":true,"pageLoadStrategy":"normal","platformName":null,"platformVersion":"any"},"requiredCapabilities":{}},"sessionId":null}]
1466104520474	Marionette	CONFIG	Changing capabilities: {"browserName":"Firefox","browserVersion":null,"platformName":null,"platformVersion":"6.1","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160604131506","device":"desktop","version":"47.0","marionette":true,"pageLoadStrategy":"normal"}
1466104521113	Marionette	DEBUG	loaded listener.js
1466104521115	Marionette	DEBUG	loaded listener.js
1466104521254	Marionette	TRACE	conn0 <- [1,1,null,{"sessionId":"f2a4ac1e-557d-4175-8629-35f15b87f148","capabilities":{"browserName":"Firefox","browserVersion":null,"platformName":null,"platformVersion":"6.1","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"WINDOWS_NT","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160604131506","device":"desktop","version":"47.0","marionette":true,"pageLoadStrategy":"normal","command_id":1}}]
```

**Comment by andreastt** [comment]
I found the reason for this. The `marionette.logging` preference is being set to true in https://github.com/mozilla/geckodriver/blob/master/src/marionette.rs#L118, causing Marionette to trigger compatibility behaviour for Gecko <= 45 in https://github.com/mozilla/gecko-dev/blob/master/testing/marionette/components/marionettecomponent.js#L87, which was to log everything.

**Comment by kapoorlakshya** [comment]
Thanks for figuring that out, @andreastt! Any idea when this enhancement will be released?

**Comment by andreastt** [comment]
@kapoorlakshya #103 is now on master which fixes this issue. It makes the default log level in Gecko INFO for optimised builds and DEBUG for debug builds. You can use `-v`, `-vv`, or `--log _LEVEL_` to override this from geckodriver.

I don’t think we should make another release until #83 is ready.

**Comment by goyalvipul** [comment]
Hi,
I am also facing the same logs while triggering firefox 50 as well.
I want to switch them off.

Quetion -- How to add "-v" argument, while we trigger the firefox from selenium..
This argument can be added using eclipse, but how can this be done when done from command line.

Please help.. It is very important for my project.

Regards,
Vipul Goyal

**Comment by skiaheliou** [comment]
> @goyalvipul Please consult your language binding’s documentation.

@andreastt Please provide an example location for this. I've seen this reply in a few places and it can be a real dead-end.

**Comment by andreastt** [comment]
@skiaheliou I don’t know? You didn’t say which bindings you were using. I’m assuming http://seleniumhq.org/docs, https://seleniumhq.github.io/selenium/docs/api/javascript/, http://seleniumhq.github.io/selenium/docs/api/py/, or http://seleniumhq.github.io/selenium/docs/api/java/?

**Comment by ChpNick** [comment]
I also have the problem, and I would like to turn logging off

**Comment by lvlmd** [comment]
the same. i can't find how to turn ON logs on java

**Comment by automateaway** [comment]
hi Guys, 
I found this solution works really well to suppress debug log messages:
(1) Inside your framework, when you are creating a firefox driver, add this line of code System.setProperty("webdriver.gecko.driver", "<path to your script launching gecko driver>);

(2) If you are running on Mac machine, create a gecko shell script to include the lines of code, I find gecko driver 0.11.0 works best with FF 52.0, FF 51, etc. You will need similar script on Windows

SOURCE="${BASH_SOURCE[0]}"     
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
$DIR/geckodriver0.11.0 "$@" 2>&1 | grep -Ev '(addons.manager|DEBUG|INFO)'

**Comment by andreastt** [comment]
Locking.
