### ISSUE TITLE
Unable to open new tab in Firefox

### ISSUE THREAD

**Issue by arshad01** [mozilla/geckodriver#890]
## System
* Version: 0.18.0
* Platform: Linux Ubuntu 16.04 LTS
* Firefox: 55.0.2 (64bit)
* Selenium: python 3.5.0

## Testcase

```
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.firefox.firefox_profile import FirefoxProfile

import time

binary = FirefoxBinary()
profile = FirefoxProfile()
profile.set_preference('--log', 'DEBUG')

driver = webdriver.Firefox(firefox_binary=binary, firefox_profile=profile)
driver.get('http://google.com')
e=driver.find_element_by_tag_name('body')
e.send_keys(Keys.CONTROL + 't')

time.sleep(30)

driver.quit()
```

## Trace-level log

[gecko_trace.txt](https://github.com/mozilla/geckodriver/files/1241247/gecko_trace.txt)

**Comment by andreastt** [comment]
Control + T is not supposed to open a new tab in Firefox.

**Comment by arshad01** [comment]
CONTROL+t does open a new tab in Firefox on Linux (ubuntu). Attached is a screenshot. Also, before I upgraded to FF 55, I was using it in FF 54 without any problem.

![screen shot 2017-08-22 at 7 07 11 pm](https://user-images.githubusercontent.com/588364/29562836-911196a2-876d-11e7-953b-20ab96d4f682.png)

**Comment by andreastt** [comment]
The WebDriver API input mechanisms target web content, and are explicitly meant to prevent interaction with the Firefox chrome and the surrounding system’s widget set.

**Comment by whimboo** [comment]
Please see issue #786.
