### ISSUE TITLE
GeckoDriver executables needs to show the architecture info (32 bit / 64 bit) along with the version number.

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#894]
## System
* GeckoDriver Version: 0.18.0
* Platform: Windows8 Pro, 64 bit
* Firefox: Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0

## Testcase

Calling `geckodriver.exe -V` through Windows CLI doesn't reveals `geckodriver.exe` architecture info (32 bit / 64 bit).

## Stacktrace

- `GeckoDriver` (32-bit):

```
	C:\Utility\BrowserDrivers\geckodriver-v0.18.0-win32>geckodriver.exe -V
	geckodriver 0.18.0

	The source code of this program is available from
	testing/geckodriver in https://hg.mozilla.org/mozilla-central.

	This program is subject to the terms of the Mozilla Public License 2.0.
	You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

- `GeckoDriver` (64-bit):

```
	C:\Utility\BrowserDrivers\geckodriver-v0.18.0-win64>geckodriver.exe -V
	geckodriver 0.18.0

	The source code of this program is available from
	testing/geckodriver in https://hg.mozilla.org/mozilla-central.

	This program is subject to the terms of the Mozilla Public License 2.0.
	You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
```

Currently, `IEDriverServer` does shows the architecture info in-terms of 32 bit / 64 bit.

```
        C:\Utility\BrowserDrivers>IEDriverServer.exe -v
        IEDriverServer.exe 3.5.0.0 (32-bit)`
```

**Comment by andreastt** [comment]
I don’t see any reason to show the architecture of geckodriver. The architecture of geckodriver bears no importance on its function.

**Comment by Debanjan-B** [comment]
I think you are missing my point that I am supplying an argument `-V` to see the version details of the `geckodriver.exe`. If the version details of the binaries released can't differentiate between 32-bit and 64-bit architecture probably you are pushing the end-user to a grey area.

I would like to have @AutomatedTester or @shs96c take on this.

**Comment by andreastt** [comment]
A binary’s target architecture is an observable trait, whereas the version number isn’t:

```
% file geckodriver 
geckodriver: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=c2c585c233fd409776a279a13cbc966142a2c963, not stripped
```

I’d like to reiterate that you don’t need, on Windows, to pair a 32-bit geckodriver to a 32-bit Firefox, so you will only ever need _one_ binary on any given system.

**Comment by Debanjan-B** [comment]
@andreastt I think the end user should have the flexibility to use the `64-bit geckodriver.exe` and `32-bit geckodriver.exe` at their disposal when the `Mozilla Firefox Browser` is `64-bit` install.

`IEDriverServer.exe` does supports this interchangeability.

If there is at all any dependency binding between `64-bit geckodriver.exe` & `64-bit Mozilla Firefox Browser` instance and `32-bit geckodriver.exe` & `32-bit Mozilla Firefox Browser` instance, a documentation in the Release Notes may be helpful.

**Comment by andreastt** [comment]
As I just said, there isn’t.
