### ISSUE TITLE
platformName should return "windows"

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#897]
WebDriver specs mentions `platformName` to be **`windows`** 

In chapter [7. Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.-capabilities), section [7.2 Processing Capabilities](https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities#x7.2-processing-capabilities):
> windows

GeckoDriver v0.18.0 returns `platformName` as **`windows_nt`**

## System
* GeckoDriver Version: 0.18.0
* Platform: Windows8 Pro, 64 bit
* Firefox: Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0

## Testcase

Minimum Code Block:

	package demo;

	import java.util.Map;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_platformName
	{
		public static void main(String[] args) 
		{
			String attribute = "platformName";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value :"+ value);
		}
	}

## Stacktrace

Console Output:

    Key : platformName Value :windows_nt

**Comment by andreastt** [comment]
The specification has changed since this was implemented in Marionette, but to clarify, the specification doesn’t say we _have_ to return `windows`; we are free to return `windows_nt` if we wish.

However, this is probably a case where we ought to change.

**Comment by Debanjan-B** [comment]
@andreastt  Can you please point me to the last updated specification for our reference?

Since yesterday I started tracking the `The WebDriver specification` from [**`Browser Testing and Tools Working Group`**](https://www.w3.org/testing/browser/). The  document titled [**`WebDriver
W3C Candidate Recommendation 23 August 2017`**](https://w3c.github.io/webdriver/webdriver-spec.html) looks to me the most updated one being signed by [**`@shs96c`**](http://www.rocketpoweredjetpants.com/) [**`@AutomatedTester`**](http://www.theautomatedtester.co.uk/) and [**`Mozilla`**](https://www.mozilla.org/en-US/)

Please let me know if we are tracking the right document.

**Comment by andreastt** [comment]
That is the correct document. The value for `platformName` is given as non-normative text in a note.

**Comment by andreastt** [comment]
I filed https://github.com/w3c/webdriver/issues/1047 to clarify why normative text is being used in a note in the specification. I want that cleared up before we make a change to Marionette.

**Comment by Debanjan-B** [comment]
Thanks for the update @andreastt

**Comment by andreastt** [comment]
So the conclusion from https://github.com/w3c/webdriver/issues/1047 was that it is correct for geckodriver to accept `windows` as input and return a more specific Windows version (`windows_nt`) in the returned capabilities. Closing this.
