### ISSUE TITLE
Selenium 3.5.0-geckoDriver : GeckoDriver returning "moz:processID" as a float value

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#898]
GeckoDriver returning "moz:processID" as a float value (example `788.0`)

## System
* GeckoDriver Version: 0.18.0
* Platform: Windows8 Pro, 64 bit
* Firefox: Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0

## Testcase

Minimal Code Block:

	package demo;

	import java.util.Map;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_moz_processID
	{
		public static void main(String[] args) 
		{
			String attribute = "moz:processID";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			WebDriver driver = new FirefoxDriver();
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value :"+ value);
		}
	}

## Stacktrace

Console Output:

    Key : moz:processID Value :788.0

**Comment by whimboo** [comment]
As stated on https://bugzilla.mozilla.org/show_bug.cgi?id=1392992 this is invalid.
