### ISSUE TITLE
Selenium 3.5.0-GeckoDriver 0.18.0-Java : GeckoDriver is not able to set any of the timeouts within  marionette hence timeouts remains unimplemented.

### ISSUE THREAD

**Issue by Debanjan-B** [mozilla/geckodriver#899]
Selenium 3.5.0-GeckoDriver 0.18.0-Java : GeckoDriver is not able to set any of the timeouts within  marionette hence timeouts remains unimplemented.

When user tries to set `pageLoadTimeout`, `implicitlyWait` and `setScriptTimeout` as follows:

```
driver.manage().timeouts().pageLoadTimeout(9, TimeUnit.SECONDS);
driver.manage().timeouts().implicitlyWait(18,TimeUnit.SECONDS);
driver.manage().timeouts().setScriptTimeout(27, TimeUnit.SECONDS);
```

The following configurations seems doesn't gets set within `marionette` as follows:

- `pageLoadTimeout`:

```
1503490597019	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"pageLoad":9000}
1503490597023	geckodriver::marionette	TRACE	-> 37:[0,2,"setTimeouts",{"pageLoad":9000}]
1503490597032	Marionette	TRACE	0 -> [0,2,"setTimeouts",{"pageLoad":9000}]
1503490597035	Marionette	TRACE	0 <- [1,2,null,{}]
1503490597037	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1503490597037	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

- `implicitlyWait`:

```
1503490597049	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"implicit":18000}
1503490597051	geckodriver::marionette	TRACE	-> 38:[0,3,"setTimeouts",{"implicit":18000}]
1503490597074	Marionette	TRACE	0 -> [0,3,"setTimeouts",{"implicit":18000}]
1503490597078	Marionette	TRACE	0 <- [1,3,null,{}]
1503490597080	geckodriver::marionette	TRACE	<- [1,3,null,{}]
1503490597080	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

- `setScriptTimeout`:

```
1503490597087	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"script":27000}
1503490597089	geckodriver::marionette	TRACE	-> 36:[0,4,"setTimeouts",{"script":27000}]
1503490597111	Marionette	TRACE	0 -> [0,4,"setTimeouts",{"script":27000}]
1503490597114	Marionette	TRACE	0 <- [1,4,null,{}]
1503490597115	geckodriver::marionette	TRACE	<- [1,4,null,{}]
1503490597115	webdriver::server	DEBUG	<- 200 OK {"value": {}}
```

## System
* GeckoDriver Version: 0.18.0
* Platform: Windows8 Pro, 64 bit
* Firefox: Firefox: 55.0.2 (64-bit)
* Selenium: 3.5.0

## Testcase

Minimum Code block:

	package demo;

	import java.util.Map;
	import java.util.concurrent.TimeUnit;
	import java.util.logging.Level;

	import org.openqa.selenium.Capabilities;
	import org.openqa.selenium.WebDriver;
	import org.openqa.selenium.firefox.FirefoxDriver;
	import org.openqa.selenium.firefox.FirefoxOptions;
	import org.openqa.selenium.remote.RemoteWebDriver;

	public class WEBDRIVER_timeouts
	{
		public static void main(String[] args) 
		{
			String attribute = "timeouts";
			System.setProperty("webdriver.gecko.driver", "C:\\Utility\\BrowserDrivers\\geckodriver.exe");
			FirefoxOptions options = new FirefoxOptions();
			options.setLogLevel(Level.ALL);
			WebDriver driver =  new FirefoxDriver(options);
			driver.manage().timeouts().pageLoadTimeout(9, TimeUnit.SECONDS);
			driver.manage().timeouts().implicitlyWait(18,TimeUnit.SECONDS);
			driver.manage().timeouts().setScriptTimeout(27, TimeUnit.SECONDS);
			driver.get("https://google.com");
			Capabilities cap = ((RemoteWebDriver) driver).getCapabilities();
			Map<String, ?> map = cap.asMap();
			Object value = map.get(attribute);
			System.out.println("Key : " + attribute + " Value :"+ value);
		}
	}

## Stacktrace

Console Output:

    Key : timeouts Value :{implicit=0.0, pageLoad=300000.0, script=30000.0}

## Trace-level log

	1503490580281	geckodriver	INFO	geckodriver 0.18.0
	1503490580290	geckodriver	INFO	Listening on 127.0.0.1:1873
	1503490581117	geckodriver::marionette	INFO	Starting browser C:\Program Files\Mozilla Firefox\firefox.exe with args ["-marionette"]
	1503490582751	Marionette	DEBUG	Received observer notification "profile-after-change"
	1503490583115	geckodriver::marionette	TRACE	  connection attempt 0/600
	1503490583304	Marionette	DEBUG	Received observer notification "command-line-startup"
	1503490583304	Marionette	INFO	Enabled via --marionette
	1503490585220	geckodriver::marionette	TRACE	  connection attempt 1/600
	1503490587326	geckodriver::marionette	TRACE	  connection attempt 2/600
	1503490589439	geckodriver::marionette	TRACE	  connection attempt 3/600
	1503490589562	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
	1503490589563	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
	1503490591538	geckodriver::marionette	TRACE	  connection attempt 4/600
	1503490593642	geckodriver::marionette	TRACE	  connection attempt 5/600
	1503490593859	Marionette	DEBUG	Received observer notification "domwindowclosed"
	1503490593860	Marionette	DEBUG	Received observer notification "domwindowclosed"
	Unable to read VR Path Registry from C:\Users\AtechM_03\AppData\Local\openvr\openvrpaths.vrpath
	[GPU 6544] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
	Unable to read VR Path Registry from C:\Users\AtechM_03\AppData\Local\openvr\openvrpaths.vrpath
	[Child 5480] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
	[Child 5480] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
	1503490594683	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
	1503490594684	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
	1503490594685	Marionette	INFO	Listening on port 57904
	1503490594703	Marionette	INFO	Listening on port 57904
	1503490594749	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:57904
	1503490594766	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:57931
	1503490594766	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
	1503490594766	geckodriver::marionette	TRACE	-> 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
	1503490594773	Marionette	TRACE	0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
	1503490594777	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"6.2","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6752,"moz:profile":"C:\\Users\\ATECHM~1\\AppData\\Local\\Temp\\rust_mozprofile.kyeqXhabcgje","moz:accessibilityChecks":false}
	1503490595357	addons.productaddons	WARN	Failed downloading via XHR, status: 0, reason: error
	1503490596729	Marionette	DEBUG	loaded listener.js
	1503490596763	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"05bc321f-04ec-4dc0-b023-a588b14ecb48","capabilities":{"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"6.2","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6752,"moz:profile":"C:\\Users\\ATECHM~1\\AppData\\Local\\Temp\\rust_mozprofile.kyeqXhabcgje","moz:accessibilityChecks":false}}]
	1503490596786	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"05bc321f-04ec-4dc0-b023-a588b14ecb48","capabilities":{"browserName":"firefox","browserVersion":"55.0.2","platformName":"windows_nt","platformVersion":"6.2","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":6752,"moz:profile":"C:\\Users\\ATECHM~1\\AppData\\Local\\Temp\\rust_mozprofile.kyeqXhabcgje","moz:accessibilityChecks":false}}]
	1503490596786	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"05bc321f-04ec-4dc0-b023-a588b14ecb48","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"55.0.2","moz:accessibilityChecks":false,"moz:processID":6752,"moz:profile":"C:\\Users\\ATECHM~1\\AppData\\Local\\Temp\\rust_mozprofile.kyeqXhabcgje","pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"6.2","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
	Aug 23, 2017 5:46:36 PM org.openqa.selenium.remote.ProtocolHandshake createSession
	INFO: Detected dialect: W3C
	1503490597019	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"pageLoad":9000}
	1503490597023	geckodriver::marionette	TRACE	-> 37:[0,2,"setTimeouts",{"pageLoad":9000}]
	1503490597032	Marionette	TRACE	0 -> [0,2,"setTimeouts",{"pageLoad":9000}]
	1503490597035	Marionette	TRACE	0 <- [1,2,null,{}]
	1503490597037	geckodriver::marionette	TRACE	<- [1,2,null,{}]
	1503490597037	webdriver::server	DEBUG	<- 200 OK {"value": {}}
	1503490597049	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"implicit":18000}
	1503490597051	geckodriver::marionette	TRACE	-> 38:[0,3,"setTimeouts",{"implicit":18000}]
	1503490597074	Marionette	TRACE	0 -> [0,3,"setTimeouts",{"implicit":18000}]
	1503490597078	Marionette	TRACE	0 <- [1,3,null,{}]
	1503490597080	geckodriver::marionette	TRACE	<- [1,3,null,{}]
	1503490597080	webdriver::server	DEBUG	<- 200 OK {"value": {}}
	1503490597087	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/timeouts {"script":27000}
	1503490597089	geckodriver::marionette	TRACE	-> 36:[0,4,"setTimeouts",{"script":27000}]
	1503490597111	Marionette	TRACE	0 -> [0,4,"setTimeouts",{"script":27000}]
	1503490597114	Marionette	TRACE	0 <- [1,4,null,{}]
	1503490597115	geckodriver::marionette	TRACE	<- [1,4,null,{}]
	1503490597115	webdriver::server	DEBUG	<- 200 OK {"value": {}}
	1503490597123	webdriver::server	DEBUG	-> POST /session/05bc321f-04ec-4dc0-b023-a588b14ecb48/url {"url":"https://google.com"}
	1503490597124	geckodriver::marionette	TRACE	-> 40:[0,5,"get",{"url":"https://google.com"}]
	1503490597139	Marionette	TRACE	0 -> [0,5,"get",{"url":"https://google.com"}]
	1503490597165	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
	1503490598076	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
	1503490598076	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
	1503490598335	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.in/?gfe_rd=cr&ei=JHKdWfjLMKPT8gfHuJHgBg"
	1503490599156	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "4294967301"
	1503490599162	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.co.in/?gfe_rd=cr&ei=JHKdWfjLMKPT8gfHuJHgBg"
	1503490599165	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.in/?gfe_rd=cr&ei=JHKdWfjLMKPT8gfHuJHgBg"
	1503490599870	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.co.in/?gfe_rd=cr&ei=JHKdWfjLMKPT8gfHuJHgBg"
	1503490599882	Marionette	TRACE	0 <- [1,5,null,{}]
	1503490599887	geckodriver::marionette	TRACE	<- [1,5,null,{}]
	1503490599888	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by andreastt** [comment]
Your above trace doesn’t include a call to `GET /session/{session id}/timeouts` that proves that the timeout values aren’t being set. Can you make a call to that so that Marionette’s `getTimeouts` command is invoked?

**Comment by whimboo** [comment]
No response from reporter. Closing issue.
