### ISSUE TITLE
Firefox 55: maximize() does toggle browser size, not just maximize!

### ISSUE THREAD

**Issue by mgavilan** [mozilla/geckodriver#900]
## System
* Version: 0.17.0 & 0.18.0
* Platform: Windows 10
* Firefox: Firefox 55.0.2
* Selenium: Java 3.4.0 & Java 3.5.2

## Testcase
Looks like with Firefox 55, the maximize() function does no longer just maximize, but toggles between max and earlier size!

import org.openqa.selenium.firefox.FirefoxDriver;

public class FirefoxTest {
	
	public static void main(String[] args) throws InterruptedException {
		FirefoxDriver driver = new FirefoxDriver();
		driver.get("http://google.com");
		System.out.println("Initial Firefox Size: " + driver.manage().window().getSize());

		driver.manage().window().maximize();
		System.out.println("Firefox Size after 1. maximize: " + driver.manage().window().getSize());
		Thread.sleep(3000);

		driver.manage().window().maximize();
		System.out.println("Firefox Size after 2. maximize: " + driver.manage().window().getSize());
		Thread.sleep(3000);

		driver.manage().window().maximize();
		System.out.println("Firefox Size after 3. maximize: " + driver.manage().window().getSize());
		
		driver.quit();
	}
}

## Stacktrace

Firefox 54.0.1
Initial Firefox Size: (1280, 1040)
Firefox Size after 1. maximize: (1936, 1176)
Firefox Size after 2. maximize: (1936, 1176)
Firefox Size after 3. maximize: (1936, 1176)

Firefox 55.0.2
Initial Firefox Size: (1280, 1040)
Firefox Size after 1. maximize: (1936, 1176)
Firefox Size after 2. maximize: (1280, 1040)
Firefox Size after 3. maximize: (1936, 1176)

## Trace-level log
As the log is quite lengthy, I decided to upload the log file:
[Trace-Level-Log.txt](https://github.com/mozilla/geckodriver/files/1248233/Trace-Level-Log.txt)

**Comment by andreastt** [comment]
The WebDriver specification previously said drivers should restore the window when maximised. This was rectified in the specification and is fixed in Firefox (57) with https://bugzilla.mozilla.org/show_bug.cgi?id=1391691.
