### ISSUE TITLE
moveToElement() fails if element is larger than viewport

### ISSUE THREAD

**Issue by codingphil** [mozilla/geckodriver#901]
## System
* Version: 0.18
* Platform: Windows 10 Creators Update
* Firefox: 55.0.2
* Selenium: 3.5.2 (Java)

## Testcase

The test executes `moveToElement()` for an element which is way larger than the viewport.
It seems that geckodriver tries to move the mouse pointer to the center of the element which outside the viewport and therefore the `MoveTargetOutOfBoundsException` exception is thrown.
Instead geckodriver should respect the [in-view center point](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-in-view-center-point) and move the mouse pointer to the center of the intersection rectangle of the elements client rectangle and the viewport rectangle.
See WebDriver spec [17.4.3 Pointer Actions](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-in-view-center-point) "dispatch a pointerMove action".

Java Selenium Test:
```java
driver.manage().window().setSize(new Dimension(1024, 600));
driver.navigate().to("http://localhost/scrollDown.html");
WebElement longDiv = driver.findElementById("longDiv");

new Actions(driver).moveToElement(longDiv).perform();
// unexpected throws:
// org.openqa.selenium.interactions.MoveTargetOutOfBoundsException:
// (497.5, 2580.866668701172) is out of bounds of viewport width (1012) and height (509)
```

scrollDown.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Scroll Down</title>
    <style>
        #longDiv {
            height: 5000px;
            background: lemonchiffon;
        }
        #scrollable {
            background: greenyellow;
        }
    </style>
</head>
<body>
<h1>Scroll Down</h1>
<div id="longDiv">
</div>
<div id="scrollable"><h2>Scrolled Element</h2></div>
</body>
</html>
```
[scrollDown.html.zip](https://github.com/mozilla/geckodriver/files/1248402/scrollDown.html.zip)

## Stacktrace

```java
org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (497.5, 2580.866668701172) is out of bounds of viewport width (1012) and height (509)
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'yyyyyyy', ip: '10.71.34.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\.......\rust_mozprofile.6c8ScxKGqQyS, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=true, browserVersion=55.0.2, platformVersion=10.0, moz:processID=19984, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 50236985-435d-4d04-94cb-69885008a6a7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:707)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:643)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:599)
	at com.borland.webdriverbehavior.test.gecko.bugreports.ActionsMouseMove.testMouseMove_toElementWayLargerThanViewport(ActionsMouseMove.java:44)
```

## Trace-level log

[geckodriverlog.zip](https://github.com/mozilla/geckodriver/files/1248412/geckodriverlog.zip)

**Comment by andreastt** [comment]
@jgraham @mjzffr Should `moveToElement` use the in-view centre point of the element instead? Potential spec issue?

**Comment by codingphil** [comment]
From a users point of view I would find it the best option like it is stated in the standard by now: Use in-view center point. Otherwise it would be hard for the user to ensure that the center of the dom element is in the viewport (it is impossible to achieve that via `DomElement.scrollIntoView()`) before calling `moveToElement()`.

From the WebDriver spec 17.4.3 Pointer Actions "dispatch a pointerMove action".
> An object that represents a web element
> Let element be equal to the result of trying to get a known element with argument origin.
> Let x element and y element be the result of calculating the in-view center point of element.
> Let x equal x element + x offset, and y equal y element + y offset.

**Comment by andreastt** [comment]
> Otherwise it would be hard for the user to ensure that the center of the dom element is in the viewport (it is impossible to achieve that via JavaScript DomElement.scrollIntoView()) before calling moveToElement().

The element can be so much larger than the viewport that its centre point might not be in the viewport after scrolling.

**Comment by codingphil** [comment]
That's exact the problem. If it remains as it is now implemented in geckodriver (center of element), then we need some way that the user can scroll the point into view.
Theoretically in most cases it is possible to scroll one point into view.
Practically now we have only JS DomElement.scrollIntoView() which can scroll either to the top or the bottom of the element.

**Comment by jgraham** [comment]
This is right in the spec and is a bug in geckodriver. That test seems like something that should be added to the testsuite; are you able to convert it to a [web-platform-test](https://github.com/web-platform-tests)?

**Comment by andreastt** [comment]
Yes. It looks like the specification is using the correct terminology here:

> Let x element and y element be the result of calculating the in-view center point of element. 

I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1393831 to have the `pointerMove` action use the element’s in-view centre point.

**Comment by mjzffr** [comment]
@codingphil A fix just landed in Firefox 59 thanks to a volunteer contributor. According to my tests, it works correctly now. I will request to uplift the fix to 58. If you find it doesn't work right for you in tomorrow's Firefox Nightly (59), please feel free to reopen the issue. Thanks.

**Comment by eyal919** [comment]
The fix doesn't work in FF 59.0b10 (64-bit) - still getting the next error:
Can you please reopen this issue.

> org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (1396.38330078125, 343.20001220703125) is out of bounds of viewport width (1280) and height (950)
> Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
> System info: host: 'XXX.com', ip: 'fe80:0:0:0:b5:d6b5:6172:80e1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_60'
> Driver info: org.openqa.selenium.firefox.FirefoxDriver
> Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 59.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 4426, moz:profile: /var/folders/52/h2p507ln2f1..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 16.7.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
> Session ID: 11599662-e479-0c44-af49-5e09efde950b
> 
While executing the next code:

```
  Actions actions = new Actions(webDriver);
  actions.moveToElement(element).perform(); // error occur here
```

Thanks

**Comment by arun004po** [comment]
Fix is not working in 59.0b14 (64-bit)
org.openqa.selenium.interactions.MoveTargetOutOfBoundsException: (1759.7582702636719, 1074.816650390625) is out of bounds of viewport width (1920) and height (966)
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'SYDPC1755', ip: '192.168.29.82', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\arunp\AppData\Local\Temp\rust_mozprofile.vUeIM5Yzhgji, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, moz:headless=false, platform=XP, moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=59.0, platformVersion=6.1, moz:processID=11728, browserName=firefox, javascriptEnabled=true, platformName=XP, moz:webdriverClick=true}]
Session ID: 05ff3971-8a31-4b0b-bc00-0fe7e78f75b7
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
  at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
  at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:712)
  at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:638)
  at org.openqa.selenium.interactions.Actions.perform(Actions.java:594)

**Comment by codingphil** [comment]
The test of the original issue submission succeeds with 59.0b14 (64-bit) on my machine. I used the latest Selenium 3.10.0.
I did not test yet where exactly it would click if `new Actions(driver).moveToElement(longDiv).click().perform();` would be executed.

So it seems that the issue is actually fixed.

**Comment by AlexTesterSB** [comment]
@codingphil, If I right understand, this bug will be fixed with Firefox 59 version, which is now only "beta version"

**Comment by codingphil** [comment]
@AlexTesterSB correct. See https://github.com/mozilla/geckodriver/issues/901#issuecomment-347931323

**Comment by whimboo** [comment]
If there are cases which do not work yet with the upcoming Firefox 59.0 release please file separate issues with detailed feedback. Thanks.
