### ISSUE TITLE
platform and platformName capabilities have different values

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#902]
## System
* Version: 0.18
* Platform: windows 7
* Firefox: nightly
* Selenium: 3.5.2 Java

## Testcase
```
FirefoxOptions options = new FirefoxOptions();
options.setBinary("C:/Program Files/Nightly/firefox.exe");
WebDriver driver = new FirefoxDriver(options);
System.out.println(driver.getCapabilities().getCapability("platform"));
System.out.println(driver.getCapabilities().getCapability("platformName"));
```

Prints
```
ANY
windows_nt
```

Expected to print the same value for both capabilities.

**Comment by andreastt** [comment]
`platform` is not a capability we’re returning. It sounds like something an intermediary or your client has introduced.

**Comment by barancev** [comment]
OK, taking issue back to client side.
