### ISSUE TITLE
can't open new tab

### ISSUE THREAD

**Issue by wengoooooooo** [mozilla/geckodriver#903]
## System
* Version: 0.16.1
* Platform: windows 7
* Firefox: 54
* Selenium: python selenium 3.4.2

## Testcase

when loaded firefox default profile and then open new tab is not work

```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import getpass
import glob
profilePath = getpass.getuser()
profile = glob.glob(r'C:\Users\%s\AppData\Roaming\Mozilla\Firefox\Profiles\*.default' % profilePath)[0]
driver = webdriver.Firefox(firefox_profile=profile)
driver.get('https://www.google.com/')

# it's not work
driver.find_element_by_tag_name("body").send_keys(Keys.CONTROL + 't')
```

**Comment by jgraham** [comment]
Opening a new tab in that way isn't expected to work. Key events are sent to the content but not to the browser chrome. WebDriver should gain an API for opening a new tab, but in the meantime you might be able to use `executeScript('window.open())` to get what you  want.

**Comment by wengoooooooo** [comment]
but if i create a new profile it is work
```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Firefox()
driver.get('https://www.google.com/')

# it is work
driver.find_element_by_tag_name("body").send_keys(Keys.CONTROL + 't')

**Comment by whimboo** [comment]
I actually don't think that this works with a new profile. You should provide at least a trace log to proof what you see.
