### ISSUE TITLE
Disable SEC_ERROR_UNKNOWN_ISSUER error

### ISSUE THREAD

**Issue by plaidshirtakos** [mozilla/geckodriver#905]
## System
* Version: 0.18.0
* Platform: Windows 8.1
* Firefox: Firefox 55.0.3 (64-bit)
* Selenium: 3.5.2

## Testcase

Webdriver should disable SEC_ERROR_UNKNOWN_ISSUER error in Firefox. It opens browser window, but I get SEC_ERROR_UNKNOWN_ISSUER. I tried to add this site as an exception in browser, but when new browser window opened I get the same message again instead of the website.

```
FirefoxProfile profile = new FirefoxProfile();
FirefoxOptions options = new FirefoxOptions();
profile.setAcceptUntrustedCertificates(true);
profile.setAssumeUntrustedCertificateIssuer(true);
options.setLogLevel(Level.ALL);
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.ACCEPT_SSL_CERTS, true);
capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, options);
WebDriver driver = new FirefoxDriver(capabilities);
```

## Stacktrace

> 1503912904820	Marionette	TRACE	0 <- [1,3,{"error":"insecure certificate","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:222:5\nInsecureCertificateError@chrome://marionette/content/error.js:318:5\nhandleEvent@chrome://marionette/content/listener.js:241:21\n"},null]
> 1503912904824	geckodriver::marionette	TRACE	<- [1,3,{"error":"insecure certificate","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:222:5\nInsecureCertificateError@chrome://marionette/content/error.js:318:5\nhandleEvent@chrome://marionette/content/listener.js:241:21\n"},null]
> 1503912904825	webdriver::server	DEBUG	<- 400 Bad Request {"value":{"error":"insecure certificate","message":"","stacktrace":"stack backtrace:\n   0:           0x4bb74f - <no info>\n   1:           0x4bbea9 - <no info>\n   2:           0x43ce8d - <no info>\n   3:           0x44ce14 - <no info>\n   4:           0x44944a - <no info>\n   5:           0x4203e1 - <no info>\n   6:           0x407dc7 - <no info>\n   7:           0x6d95b9 - <no info>\n   8:           0x4173a7 - <no info>\n   9:           0x6d38b3 - <no info>\n  10:     0x7ff9e82213d2 - BaseThreadInitThunk"}}

**Comment by andreastt** [comment]
Please attach a full trace-level log. I suspect your Selenium client is not configuring the session correctly by passing the wrong capability for disabling TLS certificates.

**Comment by plaidshirtakos** [comment]
Solved by this code:

```
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setAcceptInsecureCerts(true);
        WebDriver driver = new FirefoxDriver(desiredCapabilities);
```

**Comment by guoper59** [comment]
since new FirefoxDriver(desiredCapabilities); is deprecated what it is the better solution?

**Comment by andreastt** [comment]
@guoper59 Please don’t hijack old and closed issues. Your question is client specific, so you should ask that to the maintainers of your client. To be knowledge, capabilities are not deprecated in geckodriver.
