### ISSUE TITLE
UnhandledAlertException with Gecko Driver

### ISSUE THREAD

**Issue by sriramsubramaniyam** [mozilla/geckodriver#909]
I get windows authentication pop up in my webpage upon the launch. I am using Robot() to handle it. Problem is even though the pop up is handled I get the UnhandledAlertException.

To ensure if the issue is with the way I am handling pop up, I commented the code handling the pop up during debug, handled it manually in the application and still UnhandledAlertException was thrown at-
if (driver.getTitle().trim().equalsIgnoreCase(title))

Here is the snipped of the code am using to handle the pop up-

public void VerifyTitle(String title, String SiteCoreSpain_URL, String UserId, String Password)  {
				
	try {					
		EnterUserId(UserId);
		Thread.sleep(1000);
		EnterPassword(Password);				
		Thread.sleep(1000);					
		if (driver.getTitle().trim().equalsIgnoreCase(title)){				
			System.out.println("PASS");		
		}
		else				
			System.out.println("FAIL");
		
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}

     public void EnterUserId(String userId) throws IOException{
	
	try{
             //create robot for keyboard operations
            Robot rb = new Robot();	    
     	    rb.delay(5000);
     	    //Enter user name by ctrl-v
            StringSelection username = new StringSelection(userId);	            
                Toolkit.getDefaultToolkit().getSystemClipboard().setContents(username, null);       	            
                PressV();
	            PressTAB();
                System.out.println("user id entered");
     	    //wait
            rb.delay(5000);	    
	}catch (Exception e) {
		e.printStackTrace();	
               System.out.println("user id not entered");
	}
}

public void EnterPassword(String password) throws IOException{
try {    
     //create robot for keyboard operations
     Robot rb = new Robot(); 
     rb.delay(5000); 
         //Enter password by ctrl-v
    StringSelection pwd = new StringSelection(password);
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(pwd, null);
    PressV();
        PressTAB();           
    PressENTER();	    
        System.out.println("Password entered");
         //wait
    rb.delay(5000);	    
    }catch (Exception e) {
	e.printStackTrace();	
        testLogger.log(driver, "Password has not been entered");
    }	
}

public void PressTAB() throws AWTException
{
	try{
		Robot robot = new Robot();
		robot.keyPress(KeyEvent.VK_TAB);
		robot.keyRelease(KeyEvent.VK_TAB);
	}catch(AWTException e){
		e.printStackTrace();
	}	
	
}

public void PressV() throws AWTException
{
	try {
		Robot robot = new Robot();		
		robot.keyPress(KeyEvent.VK_CONTROL);
		robot.keyPress(KeyEvent.VK_V);
		robot.keyRelease(KeyEvent.VK_V);
		robot.keyRelease(KeyEvent.VK_CONTROL);
	}catch(AWTException e){
		e.printStackTrace();
	}
}

public void PressENTER() throws AWTException{
	try{
		Robot robot = new Robot();
		robot.keyPress(KeyEvent.VK_ENTER);
		robot.keyRelease(KeyEvent.VK_ENTER);
	}catch(AWTException e){
		e.printStackTrace();
	}
	
}
}

It works fine with chromedriver. I am using Firefox version 55.0.3 and Gecko Driver 18. I tried with other versions of Gecko driver but the issue still exists.

**Comment by andreastt** [comment]
The alert must be handled by geckodriver, using `switchTo().alert().dismiss()`, because of the way we store its state internally. When the check for an unexpected alert is done, we look at whether that command has removed the cached alert.

(This is wrong behaviour of Firefox and will be addressed when we rewrite our user prompt handling to be spec conforming, but explains why you are seeing the above.)

**Comment by schmidtkp** [comment]
@sriramsubramaniyam I'd be very interested to learn how you are using Robot to identify/find the presence of the authentication dialog. Are you simply assuming the authentication dialog will be present and have focus? What happens if the the authentication dialog is not present? What happens if the the authentication dialog does not have focus?

**Comment by sriramsubramaniyam** [comment]
@andreastt  using switchTo() we can handle only web alerts and not the windows one while using Selenium

**Comment by sriramsubramaniyam** [comment]
@schmidtkp I am just assuming the alert is there. The alert appears 4/5 times. Lets say I have handled in my code 5 times but it appears only 4 times. In that scenario the Robot() class enters the data in any webedit available and clicks on any link present. Its not ideal but doesn't fail my test case. Please let me know if there is an ideal solution for this?

**Comment by andreastt** [comment]
@sriramsubramaniyam Then what does this have to do with geckodriver?

**Comment by sriramsubramaniyam** [comment]
@andreastt Though I didn't think it would. I dismissed the alert from driver after handling the pop up and it worked. Thank you.
