### ISSUE TITLE
Clicking an element partly overlapped by another element doesn't synthesize event

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#915]
## System
* Version: 0.18
* Platform: Window 7
* Firefox: 57.0a1 (2017-08-31) (64-bit)
* Selenium: 3.5.3 Java

## Testcase
```
driver.get("https://output.jsbin.com/kuloqaw");
driver.findElement(By.id("btn")).click();
```
## Stacktrace

No errors is just does not click the button. I suppose it clicks the scrollbar that overlaps the center of the button.

**Comment by whimboo** [comment]
This is a problem with the `clickSelenium` method in Marionette. Once we can use the webdriver spec compliant method, this will be fixed. On [bug 1387470](https://bugzilla.mozilla.org/show_bug.cgi?id=1387470) I'm working on a temporarily capability for testing the new click method.

**Comment by whimboo** [comment]
Missed to close this issue. Firefox 58 will have the WebDriver compatible interactability checks turned on by default.
