### ISSUE TITLE
Upgrade To Firefox 55.0.2 And GeckoDriver 0.18.0 Cannot Import Files

### ISSUE THREAD

**Issue by metallica1973** [mozilla/geckodriver#916]
## System
* Version: Geckodriver==0.18.0
* Platform: Ubuntu 14.04 LTS
* Firefox: 55.0.2 (64-bit) 55.0.2+build1-0ubuntu0.14.04.1 was 54.0+build3-0ubuntu0.14.04.1
* Selenium: selenium==3.5.0
* Python: 2.7.6

## Testcase

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

ff = webdriver.Firefox()
ff.set_page_load_timeout(30)
ff.set_window_size(1680,1050)
ff.get("https://10.0.0.149:1414")

##After Login To Our App, I attempt to grab a file and import it in:

time.sleep(5)
ff.find_element_by_xpath("//a[@onclick='importJob(); return false;']").click()
time.sleep(10)
ff.switch_to.frame(1)
ff.find_element_by_xpath("//input[@name='scanjob']").send_keys('/home/daman/Downloads/restore/Big-Bad-Wolf.gz')
ff.find_element_by_xpath("//input[@value='Import']").submit()
ff.switch_to_default_content()

## Stacktrace

File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: File not found: /home/daman/Downloads/restore/Big-Bad-Wolf.gz

I read this post but couldnt find this exact issue on GITHub

[https://stackoverflow.com/questions/45742958/selenium-common-exceptions-webdriverexception-message-file-not-found-path-to](url)

Before the upgrade of Firefox 54 to 55, all worked ok. Thanks

**Comment by andreastt** [comment]
Did you try with Firefox Nightly (57)?

**Comment by metallica1973** [comment]
Thanks. Let me give it a shot and see what I come up with.

**Comment by curtisy1** [comment]
@andreastt @metallica1973 I think this was already fixed in 55.0.3 (released August 25). See https://bugzilla.mozilla.org/show_bug.cgi?id=1383518 for reference. Alas this was a known issue but should have received a hotfix by now.

**Comment by metallica1973** [comment]
Awesome. That did the trick (Firefox 57.0a1)

**Comment by andreastt** [comment]
Great to hear it!
