### ISSUE TITLE
Experiencing firefox driver has stopped working error pop up for driver.Quit()

### ISSUE THREAD

**Issue by gphani91** [mozilla/geckodriver#919]
## System
* Version:  18.0 :32-bit
* Platform: Windows 7 enterprise SP1
* Firefox: 55
* Selenium:  3.5.1

## Testcase
getting firefox driver has stopped working error for driver.Quit() method.

**Comment by mgavilan** [comment]
Dear gphani91,

did you already stumble across the issue with new multi-process architecture for new Firefox releases?

Details and probable (temporary) solutions are mentione here: [#517](https://github.com/mozilla/geckodriver/issues/517) At least for me, as I also faced this Firefox crashes with driver.quit(), this solved the problem.

Regards
Marcos

**Comment by andreastt** [comment]
Not enough reproducible information in this bug. Please see the issue template for what things we need to be able to debug geckodriver issues.
