### ISSUE TITLE
Selenium + Firefox on macOs hugs during startup

### ISSUE THREAD

**Issue by marole** [mozilla/geckodriver#921]
## System
* Version: 0.18.0
* Platform: macOS Sierra 10.12.6
* Firefox: 52.3.0 (64-bit)
* Selenium: 3.5.3 + Java 1.8.0_131

## Testcase

```
System.setProperty("webdriver.gecko.driver", "/Users/mega/Main/temp/geckodriver");
FirefoxOptions ffOptions = new FirefoxOptions();
ffOptions.setLogLevel(Level.ALL);
WebDriver webDriver = new FirefoxDriver(ffOptions);
```

## Stacktrace

No stack trace. The web driver does not start, hugs on last line: WebDriver webDriver = new FirefoxDriver(ffOptions);

## Trace-level log

> Using timeout for story FeedbackList.story of 300 secs.
> 1504430425534	geckodriver	INFO	Listening on 127.0.0.1:38214
> 1504430425912	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
> 1504430426629	geckodriver::marionette	TRACE	  connection attempt 0/600
> 1504430426734	geckodriver::marionette	TRACE	  connection attempt 1/600
> 1504430426836	geckodriver::marionette	TRACE	  connection attempt 2/600
> 1504430426941	geckodriver::marionette	TRACE	  connection attempt 3/600
> 1504430426983	Marionette	DEBUG	Marionette enabled via command-line flag
> 1504430427045	geckodriver::marionette	TRACE	  connection attempt 4/600
> 1504430427055	Marionette	INFO	Listening on port 51837
> 1504430427150	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:51837
> 1504430427168	Marionette	DEBUG	Accepted connection conn0 from 127.0.0.1:51849
> 1504430427184	geckodriver::marionette	TRACE	← {"applicationType":"gecko","marionetteProtocol":3}
> 1504430427185	geckodriver::marionette	TRACE	→ 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
> 1504430427187	Marionette	TRACE	conn0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
> 1504430427190	Marionette	CONFIG	Matched capabilities: {"browserName":"firefox","browserVersion":"52.3.0","platformName":"darwin","platformVersion":"16.7.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"page load":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":2062,"moz:profile":"/var/folders/bs/q6_3bb395dq4zk_m1vr8pv980000gn/T/rust_mozprofile.p8t27wjgoMoA","moz:accessibilityChecks":false}

**Comment by andreastt** [comment]
Firefox 52 isn’t supported. See the README.
