### ISSUE TITLE
NS_ERROR_SOCKET_ADDRESS_IN_USE issue on macOs

### ISSUE THREAD

**Issue by marole** [mozilla/geckodriver#922]
## System
* Version: 0.18.0
* Platform: macOS Sierra 10.12.6
* Firefox: 55.0.3 (64-bit)
* Selenium: 3.5.3 + Java 1.8.0_131

## Testcase

```
System.setProperty("webdriver.gecko.driver", "/Users/mega/Main/temp/geckodriver");
FirefoxOptions ffOptions = new FirefoxOptions();
ffOptions.setLogLevel(Level.ALL);
WebDriver webDriver = new FirefoxDriver(ffOptions);
```

## Stacktrace

No stack trace. The web driver does not start, hugs on last line: WebDriver webDriver = new FirefoxDriver(ffOptions);

## Trace-level log

> 1504447893084  geckodriver    INFO Listening on 127.0.0.1:30990
> 1504447893786  geckodriver::marionette  INFO Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
> 1504447894319  addons.xpi     WARN Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///Applications/Firefox.app/Contents/Resources/omni.ja!/components/addonManager.js:65
> 1504447894558  Marionette     DEBUG     Received observer notification "profile-after-change"
> 1504447894623  Marionette     DEBUG     Received observer notification "command-line-startup"
> 1504447894623  Marionette     INFO Enabled via --marionette
> 1504447894824  geckodriver::marionette  TRACE       connection attempt 0/600
> 1504447894928  geckodriver::marionette  TRACE       connection attempt 1/600
> 1504447895032  geckodriver::marionette  TRACE       connection attempt 2/600
> 1504447895134  geckodriver::marionette  TRACE       connection attempt 3/600
> 1504447895236  geckodriver::marionette  TRACE       connection attempt 4/600
> 1504447895341  geckodriver::marionette  TRACE       connection attempt 5/600
> 1504447895446  geckodriver::marionette  TRACE       connection attempt 6/600
> 1504447895550  geckodriver::marionette  TRACE       connection attempt 7/600
> 1504447895653  geckodriver::marionette  TRACE       connection attempt 8/600
> 1504447895755  geckodriver::marionette  TRACE       connection attempt 9/600
> 1504447895858  geckodriver::marionette  TRACE       connection attempt 10/600
> 1504447895962  geckodriver::marionette  TRACE       connection attempt 11/600
> 1504447895970  Marionette     DEBUG     Received observer notification "sessionstore-windows-restored"
> 1504447895970  Marionette     DEBUG     Received observer notification "sessionstore-windows-restored"
> 1504447896065  geckodriver::marionette  TRACE       connection attempt 12/600
> 1504447896138  Marionette     DEBUG     Setting recommended pref toolkit.cosmeticAnimations.enabled to false
> 1504447896139  Marionette     DEBUG     Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
> 1504447896139  Marionette     INFO Listening on port 52855
> JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
> 1504447896170  geckodriver::marionette  DEBUG     Connected to Marionette on localhost:52855
> 1504447896172  Marionette     DEBUG     Accepted connection 0 from 127.0.0.1:52889
> 1504447896173  geckodriver::marionette  TRACE     ← {"applicationType":"gecko","marionetteProtocol":3}
> 1504447896173  geckodriver::marionette  TRACE     → 62:[0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
> 1504447896174  Marionette     TRACE     0 -> [0,1,"newSession",{"capabilities":{"desiredCapabilities":{}}}]
> 1504447896176  Marionette     CONFIG    Matched capabilities: {"browserName":"firefox","browserVersion":"55.0.3","platformName":"darwin","platformVersion":"16.7.0","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"specificationLevel":0,"moz:processID":1274,"moz:profile":"/var/folders/bs/q6_3bb395dq4zk_m1vr8pv980000gn/T/rust_mozprofile.hFW3bTuTy3QX","moz:accessibilityChecks":false}
>

**Comment by andreastt** [comment]
I believe this has been solved in Firefox 57, but I don’t think that the `NS_ERROR_SOCKET_ADDRESS_IN_USE` error you’re seeing actually impacts the tests. As you can see from the log, you are able to connect and create a WebDriver session,

**Comment by whimboo** [comment]
No, this failure is totally unrelated and has also been fixed in Firefox 56. So just use the latest beta and you will be fine.
