### ISSUE TITLE
Firefox 55 with geckodriver 0.18 run the test on empty page/no browser

### ISSUE THREAD

**Issue by adi-darachi** [mozilla/geckodriver#924]
## System
* Version: 0.18
* Platform: Windowx 10
* Firefox: 53 - 54 - 55
* Selenium: selenium-server-standalone-jar - 3.4.0, selenium-webdriver  - 2.53.3
* marionette is set to 'true' (otherwise it fails on the connection to the standalone server )

## Testcase

I have a setup that works perfectly with chrome/ie/edge (latest), when I try to 
run firefox it look like the code is executing, I can see the logs of the test.
but the browser is showing empty page, also if I close the browser, the test keeps running ( It's like the driver is not connected to any browser), also all the executeScript methods return NULL.

## Stacktrace
The test only throw 
'com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.util.List'
when the test is running 'browser.executeScript'

**Comment by andreastt** [comment]
This sounds like a Selenium JSON Object coercion problem, but without a trace-level log it is not possible to say if it is related to geckodriver.
