### ISSUE TITLE
cannot start driver service on http://localhost

### ISSUE THREAD

**Issue by copavan** [mozilla/geckodriver#926]
## System
* Version: geckodriver-v0.11.1-win64
* Platform: Windows 10
* Firefox: 45.8 ESR
* Selenium: selenium-dotnet-3.0.1

## Testcase: Launch https://www.google.com

--------------------------------------------------------------------------------------------------------------
var driverService = FirefoxDriverService.CreateDefaultService(@"C:\Selenium\GeckoDriver", "geckodriver.exe");
driverService.FirefoxBinaryPath = @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe";
FirefoxDriver driver = new FirefoxDriver(driverService, new FirefoxOptions(), TimeSpan.FromSeconds(10));
--------------------------------------------------------------------------------------------------------------

ON web driver initialization, the last step in the above lines of code, we are seeing "Cannot start the driver service on http://localhost:10424/" error. 

## Stacktrace

---------------------------
geckodriver.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000142). Click OK to close the application. 
---------------------------
OK   
---------------------------

## Trace-level log
Exception: Exception caught: 'OpenQA.Selenium.WebDriverException' in WebDriver.dll ("Cannot start the driver service on http://localhost:10424/"). Exception caught: 'OpenQA.Selenium.WebDriverException' in WebDriver.dll ("Cannot start the driver service on http://localhost:10424/")	21.10s		[13880] <No Name>

**Comment by andreastt** [comment]
I will need a trace-level log from geckodriver to say anything interesting about why this is. An “application was unable to start correctly” error could mean that the executable doesn’t run on your particular system. Are you trying to run a 64-bit binary on a 32-bit installation of Windows?

Do also note that Firefox 45 isn’t supported.

**Comment by copavan** [comment]
@andreastt - After I upgrade to FF 48, i am seeing this issue. Please help

'Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException' in Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll ("Assert.Fail failed. Browser : is not configured properly. Actual error : Cannot find Firefox binary in PATH or default install locations. Make sure Firefox is installed. OS appears to be: Vista")	Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException

**Comment by andreastt** [comment]
@copavan Firefox 48 isn’t supported by geckodriver.

**Comment by copavan** [comment]
@andreastt - which version of Firefox is supported by gecko then ? Only >=50 ?

**Comment by andreastt** [comment]
@copavan This information is available in the README, and I quote:

> geckodriver is not yet feature complete. This means that it does not yet offer full conformance with the WebDriver standard or complete compatibility with Selenium. You can track the implementation status of the latest Firefox Nightly on MDN. We also keep track of known Selenium, remote protocol, and specification problems in our issue tracker.
> 
> Support is best in Firefox 54 and greater, although generally the more recent the Firefox version, the better the experience as they have more bug fixes and features. Some features will only be available in the most recent Firefox versions, and we strongly advise using the latest Firefox Nightly with geckodriver. Since Windows XP support in Firefox was dropped with Firefox 53, we do not support this platform.

**Comment by jagdheesh-reddy** [comment]
i am working on visual studio 2015 with selenium 3.8 on windows 10 machine. using my selenium script i am able to launch gecko or chrome browser, but it throws an exception "cannot start the driver service on localhost:port", and my url's are not loaded after the browser opens. what is the cause and any fix for this?

**Comment by andreastt** [comment]
@jagdheesh-reddy I don’t know, but file a new issue if you think it is a bug instead of hijacking an old one.
