### ISSUE TITLE
Unable to get url with FF55 with protractor

### ISSUE THREAD

**Issue by bboycs** [mozilla/geckodriver#927]
## System
* Version:  0.18.0
* Platform: Window 8.1
* Firefox:   55.0.3
* Selenium:  3.5.0

## Testcase
1. Launch protractor with with Firefox Capabilities on Protractor
2. browser.driver.get("www.google.com");
--> Unable to browse to page with url 

The browser seems close before the browser.driver.get("www.google.com");  execute

## Stacktrace
`12:47:53.182 INFO - Capabilities are: Capabilities {count=1.0, browserName=firefox,platformName=WIN8_1, platform=WIN8_1, }
12:47:53.182 INFO - Capabilities {count=1.0, browserName=firefox, platformName=WIN8_1,platform=WIN8_1, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
12:47:53.182 INFO - Capabilities {count=1.0, browserName=firefox, platformName=WIN8_1,platform=WIN8_1, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)1504586873339   geckodriver     INFO    geckodriver 0.18.01504586873370   geckodriver     INFO    Listening on 127.0.0.1:439931504586873948  geckodriver::marionette INFO    Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]1504586874405   addons.xpi      WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631< checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resourc/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:651504586875137   Marionette      INFO    Enabled via --marionette
12:47:55.323 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@52386d46
12:47:55.323 INFO - /status: Executing GET on /status (handler: Status)
[Child 5760] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 5760] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 3461504586877955   Marionette      INFO    Listening on port 551711504586878052   Marionette      INFO    Listening on port 551711504586878255   Marionette      DEBUG   loaded listener.js
12:47:58.323 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@2688851612:47:58.339 INFO - Handler thread for session 1a05f4dd-a00e-42ab-a9c4-661df80a43e7 (firefox): Executing POST on /session/1a05f4dd-a00e-42ab-a9c4-661df80a43e7/timeouts/async_script (handler: ServicedSession)
12:47:58.386 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@26888516
12:47:58.386 INFO - Handler thread for session 1a05f4dd-a00e-42ab-a9c4-661df80a43e7 (firefox): Executing DELETE on /session/1a05f4dd-a00e-42ab-a9c4-661df80a43e7 (handler: ServicedSession)1504586878416   Marionette      INFO    New connections will no longer be accepted
12:47:58.901 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@26888516
12:48:00.339 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@5441a9ad
12:48:00.339 INFO - /status: Executing GET on /status (handler: Status)
12:48:00.667 ERROR - Unable to kill process with PID 5484
12:48:05.354 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@24e4d632
12:48:05.354 INFO - /status: Executing GET on /status (handler: Status)`

Error on protractor:
[12:54:06] E/runner - Unable to start a WebDriver session.
[12:54:07] E/launcher - Error: UnsupportedOperationError: POST /session/33112aab41dc-4366-9d44-5c1c1f1dd4b9/timeouts/async_script did not match a known command

## Trace-level log
Unfortunately i am not sure how to enable  Trace-level log with protractor

**Comment by bboycs** [comment]
Downgrade to Selenium 3.4.0 and it resolved

**Comment by whimboo** [comment]
@bboycs if that is a specific issue with Selenium, please report it as such. Nothing should block people in upgrading to the latest Selenium version.
