### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by zrx8269** [mozilla/geckodriver#928]
## System
* Version: 018.0
* Platform:  Linux/Windows
* Firefox: 55.0.2
* Selenium: 3.5.3
* Webdriverio: 4.8.0

## Testcase

const webdriverio = require('webdriverio');

var opts = {
	desiredCapabilities: {
		browserName: 'firefox',
		proxy: {
                        proxyType: "manual",
	            httpProxy: "a.b.c",
	            httpProxyPort: 8080,
	            sslProxy: "a.b.c",
	            sslProxyPort: 8080
                  }
	}
};
webdriverio
        .remote(opts)
    .init()
        .url('http://www.google.com');

## Stacktrace
in firefox, cannot set the proxy

**Comment by andreastt** [comment]
Proxies are only properly supported in Firefox 57 AFAIK and you should use the `firstMatch`/`alwaysMatch` capabilities structure as documented in the README.

**Comment by whimboo** [comment]
Also please note that you will also have to wait for the next release of geckodriver which will be 0.19.
