### ISSUE TITLE
Support for untrusted/self-signed TLS certificates

### ISSUE THREAD

**Issue by kliput** [mozilla/geckodriver#93]
Hello,

I don't know if I should post it on Selenium bugtracker or here, but I search for a solution to use geckodriver with sites with untrusted SSL certificates.

According to this post: http://stackoverflow.com/a/25063706 Selenium with original Firefox driver can be configured to accept invalid SSL certificates. However, when I try to use Selenium with Geckodriver (Marionette), these options doesn't work.

I set up a local site with self-signed certificate and add an entry "testing-site.com" to /etc/hosts.

Then I try to use Selenium with Geckodriver with Python code:

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

capabilities = DesiredCapabilities.FIREFOX
capabilities['marionette'] = True
capabilities['acceptSslCerts'] = True

profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True

driver = webdriver.Firefox(firefox_profile=profile, capabilities=capabilities)

driver.get("https://testing-site.com")
print driver.title
```

Result of the script:

```
$ python firefox.py
Traceback (most recent call last):
  File "firefox.py", line 13, in <module>
    driver.get("https://testing-site.com")
  File "/home/kliput/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in get
    self.execute(Command.GET, {'url': url})
  File "/home/kliput/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/home/kliput/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Error loading page
```

In opened Firefox window I can see an "untrusted cert" page.

I tried two environments:

```
OSX ElCapitan
Firefox 47.0
```

```
Kubuntu 14.04.4
Firefox 46.0 (I don't want to upgrade on this machine, because 47 is not supported by old Firefox driver...)
```

Both environments use Geckodriver 0.8.0, Selenium 2.53.5 (Python lib) and Python 2.7.x.

The original built-in Selenium Firefox driver works OK - and it ignores untrusted certs by default without special options.

**Comment by jgraham** [comment]
Yes, this is a known issue. At the moment my best suggestion is to create an empty testing-only profile and either import the CA cert into that using the Firefox GUI or use the `certutil` program from `nss` to add that certificate to the cert store.

Instructions for this are on http://stackoverflow.com/questions/1435000/programmatically-install-certificate-into-mozilla

It is of course very important that this profile with the custom CA is never used for non-testing purposes.

**Comment by andreastt** [comment]
The Marionette bug is [bug 1103196](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196).

**Comment by kliput** [comment]
@jgraham @andreastt OK, thanks for your feedback and advice.

**Comment by ChadKillingsworth** [comment]
This workaround is non-functional in cloud testing environments. For saucelabs we've had to freeze our testing version. As newer FireFox versions continue to be released, the lack of support for self signed certs is becoming a huge pain point.

**Comment by ameyspatil** [comment]
Hoping that the only label being Marionette, has nothing to do with the issue not being prioritized. This is a substantial limitation, and a fix is much anticipated.

**Comment by andreastt** [comment]
+1 comments are not helpful at all. You can track the progress of this in [bug 1103196](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196). I’m going to lock this thread so that there is not more unessential information being added.

**Comment by andreastt** [comment]
This has now been fixed and uplifted to Aurora, which will be the next ESR.

**Comment by andreastt** [comment]
To be clear for users reading this in the future: Support for untrusted/self-signed TLS certificates is available in Firefox 52 or greater. It is provided as an opt-in by setting the `acceptInsecureCerts` capability to true.

**Comment by andreastt** [comment]
https://www.hskupin.info/2017/01/23/using-selenium-and-webdriver-to-interact-with-insecure-ssl-pages-in-firefox/ might be helpful as an example.
