### ISSUE TITLE
Unable to create new Firefox instance due to space issue in '/tmp' directory

### ISSUE THREAD

**Issue by yaswanthbs** [mozilla/geckodriver#932]
## System
* Version: 13
* Platform: Linux - Oracle Enterprise Linux - 3.10.0
* Firefox: 52.2.0
* Selenium: 3.3.0

As we know that Geckodriver is creating rust_mozprofile directories under '/tmp' on linux which is by default. Could you please point us where we can modify the configuration which can create rust_mozprofile path in different location.

Basically 'rust_mozprofile.ZWa4jLe67WEI' this file is getting created in /tmp now. But I want this to be created in /tmp/GeckoDriver.

We have very less space in '/tmp' directory and lot of firefox instances will be created at once, if we don't have space in '/tmp' directory will cause lot of issues.

**Comment by AutomatedTester** [comment]
You can set the TEMP environment variable for your tests so that it puts the profile in the directory you want.
