### ISSUE TITLE
Selenium hub 3.5.3 ignoring Firefox profile set on DesiredCapabilities

### ISSUE THREAD

**Issue by guru-23** [mozilla/geckodriver#933]
## System
* Version: v0.18.0
* Platform: Windows 7, 64 bit
* Firefox: 55.0.3
* Selenium: 3.5.3

## Testcase 

**Test case 1 :** 

Setting **network.proxy.type** on FirefoxProfile object to 0, so that the automation test's which run on FF skip's the proxy and doesnt ask for user authentication.

```
FirefoxProfile fp = new FirefoxProfile();
fp.setPreference("network.proxy.type", 0);
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(FirefoxDriver.PROFILE, fp);
 
```
Create remote webdriver using the above capability object and continue with the test
`new RemoteWebDriver(new URL(SELENIUM_REMOTE_URL), (capabilities));`

**Test case 2 :**

- Executing firefox.exe -p and create a new Firefox profile **AUTO_PRO**
- On browser got to config(about:config) and set **network.proxy.type** to 0 
- Set this profile onto the capabilities before creating Remote WebDriver

```
ProfilesIni profileIni = new ProfilesIni();
FirefoxProfile fp = profileIni.getProfile("AUTO_PRO");
capabilities.setCapability(FirefoxDriver.PROFILE, fp);
```

## Expected Behaviour:
Opened Browser profile should have **network.proxy.type** set to **0** and should skip proxy and connect directly instead.

## Actual behaviour:
Firefox Profile object ignored by Remote node, the firefox browser opened by node creates its own default profile which has **network.proxy.type** set to **5** instead of **0**. 

This scenario works fine if i run the test locally instead of running on a remote selenium hub. 
Have also  tried with different versions, the last one which correctly picks up the set Firefox profile object is 3.4.0. All the selenium-server-standalone jar's from 3.5.0 ignore's the Firefox profile object's set on capabilities.

I have also tried setting "webdriver.firefox.profile" to the new profile name on the config json and pass the same on the node start up, but even then the profile is ignored.

**Comment by AutomatedTester** [comment]
This is a bug in Selenium, please raise an issue with that project
