### ISSUE TITLE
<select> and <option> elements not supported

### ISSUE THREAD

**Issue by DamienLyles** [mozilla/geckodriver#94]
I've never been able to get "select_by" to work using wires/geckodriver.  Is this not supported?

#Ruby code...
oTarget_Element = driver.find_element(:id,"my_element_id")
oSelect = Selenium::WebDriver::Support::Select.new(oTarget_Element)

Marionette code does not like...

oSelect.select_by(:value, "#{option_value}")
select.select_by(:text, "#{option_label}")

**Comment by andreastt** [comment]
This might be related to [bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955) or [bug 1255957](https://bugzilla.mozilla.org/show_bug.cgi?id=1255957).

**Comment by Aviom** [comment]
Same problem under C# (Selenium version="3.0.0-beta2")

IWebElement we = driver.findElement(By.Id("id"));
SelectElement sel = new SelectElement(we);
sel.SelectByText("text1");

{"GET /session/ae79b02d-fed8-4861-aa00-237a54dd6de3/element//attribute/ did not match a known command"}

So we can't choose <option> from <select> under geckodriver?
Any workaround?

**Comment by andreastt** [comment]
Support for `<select>` and `<option>` elements is being added in [bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955).

**Comment by andreastt** [comment]
The patches for [bug 1255955](https://bugzilla.mozilla.org/show_bug.cgi?id=1255955) have now landed on central. I’ve requested uplift to Aurora and Beta.

**Comment by AmanSahni** [comment]
I have downloaded Firefox49 Beta6 version. In that version the same issue is coming. Can you please tell which firefox version contains this bug fix.

**Comment by AmanSahni** [comment]
I have also tried running our application with latest Nightly version.
It is also giving same exception on below line:-
  SelectElement ddlMOF = new SelectElement(firefox.FindElementById("ctl00_plhPageContent_ucItemList_cmbItemList"));

PFB the error details:-
           **An exception of type 'System.NotImplementedException' occurred in WebDriver.dll but was not handled in user code
Additional information: GET /session/e75faf17-10f8-40b4-aa8e-226f599b7e53/element//attribute/ did not match a known command**

Please help me on this. 

Thanks

**Comment by andreastt** [comment]
This is not useful. I’m locking this conversation.
