### ISSUE TITLE
Fail to click item on dropdown list (Angular + Angular material)

### ISSUE THREAD

**Issue by vavdagic** [mozilla/geckodriver#946]
## System
Version: geckodriver-v0.18.0-win64
Platform: Windows 7
Firefox: 55.0.3 (64-bit)
Selenium: python, selenium==3.5.0

## Trace-level log
[fail_to_select_item_from_dropdown_list.txt](https://github.com/mozilla/geckodriver/files/1296270/fail_to_select_item_from_dropdown_list.txt)

**Comment by andreastt** [comment]
You’re clicking not clicking an item in a drop-down list because Angular overshadows this with other styled HTML elements. In any case, this issue report is not reproducible.

You should consider adding a minimal HTML document showcasing the problem.

**Comment by whimboo** [comment]
Maybe this is even related to issue #893.
