### ISSUE TITLE
Can't compile for Arm v.6 (Raspberry pi Zero W)

### ISSUE THREAD

**Issue by speusippo** [mozilla/geckodriver#950]
I'm not able to compile for arm v6: neither directly on a Raspberry pi Zero W nor crosscompiling from Ubuntu x64.
Can anyone upload a compiled geckodriver for armv6?

## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by andreastt** [comment]
We are compiling in CI for ARMv7 HF so presumably it’s possible to do so also for ARMv6. You didn’t include any output from the failed build or steps to reproduce however. What error are you seeing?

**Comment by speusippo** [comment]
jacopo@leopolda:~/geckodriver-0.18.0$ rustc build.rs
/home/jacopo/.rustup/toolchains/stable-arm-unknown-linux-gnueabi/bin/rustc: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory

I mean, probably the problem is in rustc. This is trying to compile selecting in rustup the armv6 arch. under Ubuntu x64.

**Comment by andreastt** [comment]
geckodriver is built with cargo, and for a cross compile to work you also need to install the target toolchain and linkers.

**Comment by speusippo** [comment]
On raspberry pi with raspbian:

pi@raspberrypi:~/geckodriver-0.18.0 $ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: process didn't exit successfully: `rustc -vV` (exit code: 127)
--- stderr
/home/pi/.rustup/toolchains/nightly-arm-unknown-linux-gnueabi/bin/rustc: error while loading shared libraries: librustc_driver-972b6974ec3751ad.so: cannot open shared object file: No such file or directory

**Comment by d0ku** [comment]
I had luck in cross-compiling release 0.19.0 for ARMv6 architecture (Raspberry Pi Zero W also). I've used Docker image from https://github.com/dlecan/rust-crosscompiler-arm . I will write something about the process tomorrow in my repository README, but I've uploaded compiled binary to my repo https://github.com/d0ku/GeckoDriver_ARMv6 . Feel free to use it, I don't guarantee that it is completely working, but it should be functional at the moment.

**Comment by andreastt** [comment]
Closing this as it is apparently possible to compile for ARMv6.
