### ISSUE TITLE
Invalid moz:firefoxOptions field members

### ISSUE THREAD

**Issue by surinder-insonix** [mozilla/geckodriver#953]
## System
* Version: geckodriver-v0.18.0
* Platform: Linux/ubuntu 1704
* Firefox: Firefox 55.0.3
* Selenium: 3.5.3

## Stacktrace
```
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: Exception in thread "main org.openqa.selenium.InvalidArgumentException: Invalid moz:firefoxOptions field members
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: System info: host: 'costcoscraper-instance', ip: '10.0.98.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-32-generic', java.version: '1.8.0_131'
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: Driver info: driver.version: Fi"refoxDriver
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: remote stacktrace: stack backtrace:
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    0:           0x5787ed - backtrace::backtrace::trace::h59229d13f6a8837d
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    1:           0x578942 - backtrace::capture::Backtrace::new::h23089c033eded8f0
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    2:           0x4463cc - webdriver::error::WebDriverError::new::hd11f864b1fdf4510
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    3:           0x440ff3 - <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next::h4f3cf544297176b2
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    4:           0x44baa3 - geckodriver::marionette::MarionetteHandler::create_connection::h6f7058fccafe4367
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    5:           0x425c32 - <webdriver::server::Dispatcher<T, U>>::run::h8f5348b8f5f7c053
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    6:           0x40b22c - std::panicking::try::do_call::hb67c6fb6bcd96195
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    7:           0x5dc20a - panic_unwind::__rust_maybe_catch_panic
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                         at /checkout/src/libpanic_unwind/lib.rs:98
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    8:           0x41b943 - <F as alloc::boxed::FnBox<A>>::call_box::h4100941edc372034
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:    9:           0x5d48a4 - alloc::boxed::{{impl}}::call_once<(),()>
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                         at /checkout/src/liballoc/boxed.rs:650
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                          - std::sys_common::thread::start_thread
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                         at /checkout/src/libstd/sys_common/thread.rs:21
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                          - std::sys::imp::thread::{{impl}}::new::thread_start
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url:                         at /checkout/src/libstd/sys/unix/thread.rs:84
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
Sep 18 06:51:54 costcoscraper-instance startup-script: INFO startup-script-url: #011at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
```

Please  help to resolve this issue. getting this problem after upgrading the selenium version and geckodriver and firefox.

This updated code for selenium 3.5.3 to run the firefox in headless mode.

```java
FirefoxBinary firefoxBinary = new FirefoxBinary();
firefoxBinary.addCommandLineOptions("--headless");
System.setProperty("webdriver.gecko.driver", "/home/karanpal_insonix/geckodriver");
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setBinary(firefoxBinary);
Firefox driver = new FirefoxDriver();
```

**Comment by AutomatedTester** [comment]
Are you using 0.18? I can't reproduce this issue.

Also in 0.18 we started printing the version of Geckodriver to stdout, which is not shown, when we start up.

Please can you attach a trace geckodriver log so we can see more information.

**Comment by surinder-insonix** [comment]
Yes i am using 0.18.0
1505731910626   geckodriver     INFO    geckodriver 0.18.0
1505731910630   geckodriver     INFO    Listening on 127.0.0.1:23069
1505731910622   geckodriver     INFO    geckodriver 0.19.0
1505731910625   geckodriver     INFO    Listening on 127.0.0.1:11942
1505731910622   geckodriver     INFO    geckodriver 0.18.0
1505731910625   geckodriver     INFO    Listening on 127.0.0.1:13678
1505731910622   geckodriver     INFO    geckodriver 0.18.0
1505731910626   geckodriver     INFO    Listening on 127.0.0.1:16971

after these traces i am getting this error "main org.openqa.selenium.InvalidArgumentException: Invalid moz:firefoxOptions field members"

**Comment by andreastt** [comment]
Please attach a trace-level log from geckodriver.

**Comment by surinder-insonix** [comment]
1505735983483	geckodriver	INFO	geckodriver 0.18.0
1505735983494	geckodriver	INFO	Listening on 127.0.0.1:43923
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: Invalid moz:firefoxOptions field members
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-9JON4NV', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4bb74f - <no info>
   1:           0x4bbea9 - <no info>
   2:           0x43ce8d - <no info>
   3:           0x4390dc - <no info>
   4:           0x43dae5 - <no info>
   5:           0x447acf - <no info>
   6:           0x4203e1 - <no info>
   7:           0x407dc7 - <no info>
   8:           0x6d95b9 - <no info>
   9:           0x4173a7 - <no info>
  10:           0x6d38b3 - <no info>
  11:     0x7ffd8d902774 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at HeadlessFirefoxSeleniumExample.run(HeadlessFirefoxSeleniumExample.java:55)
	at HeadLessMain.test(HeadLessMain.java:140)
	at HeadLessMain.main(HeadLessMain.java:128)

**Comment by AutomatedTester** [comment]
Unfortunately that is a stacktrace. You will need to give us the log that comes from GeckoDriver. See https://github.com/mozilla/geckodriver#log-object for setting the capability.

**Comment by surinder-insonix** [comment]
I have only these logs.
1505810561994   geckodriver     INFO    geckodriver 0.18.0
1505810561997   geckodriver     INFO    Listening on 127.0.0.1:16169
1505810562257   geckodriver::marionette INFO    Starting browser /home/karanpal_insonix/firefox/firefox with args ["-marionette"]
1505810562494   addons.xpi      WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsres
ult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource:/
/gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource:/
/gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/Addon
Manager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///home/karanpal_insonix/firefox/omni.ja!/components/addonManager.js:65
1505810562599   addons.xpi      WARN    Add-on activity-stream@mozilla.org is not compatible with application version.
1505810562599   addons.xpi      WARN    Add-on activity-stream@mozilla.org is not compatible with application version.
1505810562605   addons.xpi      WARN    Add-on onboarding@mozilla.org is not compatible with application version.
1505810562606   addons.xpi      WARN    Add-on onboarding@mozilla.org is not compatible with application version.
1505810562609   addons.xpi      WARN    Add-on formautofill@mozilla.org is not compatible with application version.
1505810562610   addons.xpi      WARN    Add-on formautofill@mozilla.org is not compatible with application version.
1505810562796   Marionette      INFO    Enabled via --marionette
1505810563855   Marionette      INFO    Listening on port 45793
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialC
onnection]
1505810563904   Marionette      DEBUG   loaded listener.js
Sep 19, 2017 8:42:43 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

**Comment by andreastt** [comment]
That’s not enough to reproduce this issue. I’m happy to re-open this when enough information to reproduce are added.

Please also be aware that you should run this with Firefox Nightly and the latest geckodriver 0.19.0.
