### ISSUE TITLE
Getting error dialog while using driver.quit()

### ISSUE THREAD

**Issue by ranjprashant** [mozilla/geckodriver#954]
## System
* Version:  v0.19.0
* Platform:  Windows Server 2012
* Firefox: 55.0.3 (64-bit)
* Selenium: 3.5.3
--

## Testcase
System.setProperty("webdriver.gecko.driver", "D://Automation Workspaces//TRB Projects//TRBAutomationFramework_DBSTR//lib//app//Mozilla64\\geckodriver.exe");
WebDriver driver = new FirefoxDriver();
driver.get("http://www.google.com");
driver.quit();

## Stacktrace
1505720649081	geckodriver	INFO	geckodriver 0.19.0
1505720649091	geckodriver	INFO	Listening on 127.0.0.1:37366
1505720649816	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\PRANJA~1\\AppData\\Local\\Temp\\2\\rust_mozprofile.GDrxvCA44thI"
1505720650096	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1505720650589	Marionette	INFO	Enabled via --marionette
Unable to read VR Path Registry from C:\Users\pranjan-a\AppData\Local\openvr\openvrpaths.vrpath
[GPU 44] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\pranjan-a\AppData\Local\openvr\openvrpaths.vrpath
[Parent 6020] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Unable to read VR Path Registry from C:\Users\pranjan-a\AppData\Local\openvr\openvrpaths.vrpath
[Child 4392] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 4392] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1505720652419	Marionette	INFO	Listening on port 56578
1505720652457	Marionette	INFO	Listening on port 56578
1505720653029	Marionette	DEBUG	loaded listener.js
Sep 18, 2017 3:44:13 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1505720653237	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1505720653419	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1505720653420	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1505720653811	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.com/?gws_rd=ssl"
1505720654236	Marionette	DEBUG	Received observer notification "outer-window-destroyed" for "4294967301"
1505720654241	Marionette	DEBUG	Received DOM event "DOMContentLoaded" for "https://www.google.com/?gws_rd=ssl"
1505720654245	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.com/?gws_rd=ssl"
1505720654350	Marionette	DEBUG	Received DOM event "pageshow" for "https://www.google.com/?gws_rd=ssl"
1505720654393	Marionette	INFO	New connections will no longer be accepted
[GPU 44] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w64-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Sep 18, 2017 3:44:24 AM org.openqa.selenium.os.UnixProcess destroy
INFO: Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
	at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
	at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:181)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:137)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:220)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at com.ceb.trb.rough.TestMozilla.main(TestMozilla.java:37)

Sep 18, 2017 3:44:24 AM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 6200

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	firefox.exe
  Application Version:	55.0.3.6445
  Application Timestamp:	599ed8ae
  Fault Module Name:	xul.dll
  Fault Module Version:	55.0.3.6445
  Fault Module Timestamp:	599edd23
  Exception Code:	80000003
  Exception Offset:	0000000000440ce1
  OS Version:	6.2.9200.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	05b3
  Additional Information 2:	05b3ab9c877ad33fb9bde5a74f4d336c
  Additional Information 3:	747b
  Additional Information 4:	747bbb948538db4da94f5e03aad96f4a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
![mozilla isse](https://user-images.githubusercontent.com/1745155/30533070-1fcf8766-9c75-11e7-944c-0c8eb3ee2037.JPG)

**Comment by whimboo** [comment]
Please also see [bug 1401109](https://bugzilla.mozilla.org/show_bug.cgi?id=1401109) which handles this situation.

**Comment by m3dbedb** [comment]
Have you tried `drier.close();` ?

**Comment by whimboo** [comment]
This is fixed now, and only needs to be released with a new release of geckodriver.

**Comment by JoeStoner** [comment]
Selenium 3.12 shows an error on driver.quit() @ FireFox 60 / Win 7 Home Premium / Java 10.0.1 / GeckoDriver 0.20.1

Please see all details here / Thanks a lot:

https://stackoverflow.com/questions/50305819/selenium-3-12-shows-an-error-on-driver-quit-firefox-60-win-7-home-premium

**Comment by andreastt** [comment]
@JoeStoner It’s a bit counter-productive to comment on a closed issue. Why don’t you raise a new one? I didn’t look at the link, but generally we need some more information to be able to fix bugs. See https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#33 about reporting good bugs.
