### ISSUE TITLE
Cannot find any solution fit for Firefox 55.0.3.

### ISSUE THREAD

**Issue by virus-warnning** [mozilla/geckodriver#959]
## System
* Version: 0.16.1 ~ 0.19
* Platform: Windows 10 64
* Firefox: 55.0.3 64-bits
* Selenium: 3.4.0~3.5.3

## Testcase
Using nightwatch 0.9.16.
```js
  browser
      // Visit
      .init()
      .useCss()
      .maximizeWindow()
      .window_handles(function(result) {
         browser.switchWindow(result.value[0]);
      })
      .waitForElementPresent('body', this.WAIT_TIME)

      // Login
      .click('input.username')
      .keys('root', function() {})
      .click('input.password')
      .keys('123', function() {})
      .click('button[type=submit]')

      // Wait
      .waitForElementPresent('#top-menu', this.WAIT_TIME);
  },
```

## Solution List
Selenium | GeckoDriver | Firefox | Status | Detail
---- | ---- | ---- | ---- | ----
3.5.x | 0.19 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.3 | 0.18 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.2 | 0.18 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.1 | 0.18 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.0 | 0.18 x64 | 55.0.3 x64 | X | Jetty NPE.
3.5.3 | 0.17 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.2 | 0.17 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.1 | 0.17 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.0 | 0.17 x64 | 55.0.3 x64 | X | Jetty NPE.
3.5.3 | 0.16.1 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.2 | 0.16.1 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.1 | 0.16.1 x64 | 55.0.3 x64 | X | Cannot send keys and click button.
3.5.0 | 0.16.1 x64 | 55.0.3 x64 | X | Jetty NPE.
3.4.0 | 0.18 x64 | 55.0.3 x64 | X | Cannot send keys.
3.4.0 | 0.17 x64 | 55.0.3 x64 | X | Cannot send keys.
3.4.0 | 0.16.1 x64 | 55.0.3 x64 | X | Insecure password warning.

**Comment by AutomatedTester** [comment]
Unfortunately there is no actionable information in this bug. We would need to see a trace-level log and have html to reproduce this issue. Please add it

**Comment by AutomatedTester** [comment]
Closing as details have not been added.
