### ISSUE TITLE
Anyone can update the version 0.19.0 in the Chocolatey.org?

### ISSUE THREAD

**Issue by marcelopontipedra** [mozilla/geckodriver#965]
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by andreastt** [comment]
We don’t control chocolatey.org, whatever that is. I don’t recommend that you download geckodriver binaries from any other location that from an official source. The official source is this GitHub project.

**Comment by whimboo** [comment]
Chocolatey is a package manager for Windows. But yes, best is to get in contact with the person maintaining this package for Chocolatey so that it can be updated.
