### ISSUE TITLE
Geckodriver doesn't wait for page to load after click using Actions

### ISSUE THREAD

**Issue by barmy-tester** [mozilla/geckodriver#967]
## System
* Version:  0.16.1
* Platform: Windows 10
* Firefox:  55.0.3 
* Selenium: 3.5.2 

## Testcase

Code example:

new Actions(Driver.Instance)
                .MoveToElement(element)
                .Click()
                .Build().Perform();

Nothing helps actually(waiting for ready state, etc.) When I replace Actions with regular Click() method everything works fine. Driver waits for page to load as it should.

**Comment by andreastt** [comment]
The actions API is not meant to wait for the page to load: it is a low-level interface for emulating complex user interaction, so a `mouseDown` followed by `mouseUp` action on a link will not run the steps to wait for a document to load like the high-level Element Click command will.

In this case you need to poll for some known state to be reached in the client. In Selenium I believe a popular option is the `ExpectedConditions`.

**Comment by barmy-tester** [comment]
Can you at least try to change the issue type to improvement and consider implementing it?
It worked perfectly on 'native' FirefoxDriver, and still works on e.g. ChromeDriver as well.

**Comment by andreastt** [comment]
You could raise an issue against the [WebDriver specification](https://github.com/w3c/webdriver). I’m quite sure it’s by design that we don’t wait for page load when using the actions, but that would at least settle the matter.
