### ISSUE TITLE
Why there is no w32 version to download in v.19.0 release ?

### ISSUE THREAD

**Issue by boquedron** [mozilla/geckodriver#969]
## Documentation issue ?

There is **no w32** (windows 32 bits) version to download for version v.19.0. You can check it  in https://github.com/mozilla/geckodriver/releases/tag/v0.19.0 in Downloads section. Is that OK ? I see no references in the release notes.

Thanks in advance

**Comment by andreastt** [comment]
Duplicate of https://github.com/mozilla/geckodriver/issues/951.
