### ISSUE TITLE
Selenium 3.5.0 closing local files with Firefox 55.0.3

### ISSUE THREAD

**Issue by antedesk** [mozilla/geckodriver#971]
## System
* Version: 0.19.0
* Platform: macOS  -->
* Firefox: 55.0.3
* Selenium: Python, version 3.5.0

## Testcase
I'm testing the behavior of my web app locally, using Selium for Python. 
Selenium opens a local page like 
> file:///PATH/index.html

but it doesn't close the browser using the function `quit()` or `close()`.
Everything works fine if I use a real URL like the one in the simple code sample.

## Code Sample
`from selenium import webdriver`
`#url = 'https://www.mozilla.org/it/firefox/'`
`url = 'file:///PATH/index.html'`
`browser = webdriver.Firefox()`
`browser.get(url)`
`browser.quit()`

## Stacktrace
1506333862744   geckodriver INFO    geckodriver 0.19.0
1506333862785   geckodriver INFO    Listening on 127.0.0.1:58655
1506333867917   mozrunner::runner   INFO    Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/t4/wyzrp9ts6p557b4cpfy47htr0000gn/T/rust_mozprofile.ud3p6VmuZ8XM"
1506333869629   addons.xpi  WARN    Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///Applications/Firefox.app/Contents/Resources/omni.ja!/components/addonManager.js:65
1506333870022   Marionette  INFO    Enabled via --marionette
2017-09-25 12:04:32.316 plugin-container[6868:786578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa13b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-09-25 12:04:32.316 plugin-container[6868:786578] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa403, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1506333872898   Marionette  INFO    Listening on port 58664
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
1506333872971   Marionette  WARN    TLS certificate errors will be ignored for this session
1506333873003   Marionette  DEBUG   loaded listener.js
1506333873072   Marionette  DEBUG   Received DOM event "beforeunload" for "about:blank"
1506333873089   Marionette  DEBUG   Received DOM event "pagehide" for "about:blank"
1506333873089   Marionette  DEBUG   Received DOM event "unload" for "about:blank"
1506333873089   Marionette  DEBUG   Received observer notification "outer-window-destroyed" for "2147483649"
1506333873328   Marionette  DEBUG   loaded listener.js
2017-09-25 12:04:33.424 plugin-container[6869:786886] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa43b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-09-25 12:04:33.425 plugin-container[6869:786886] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xa703, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
JavaScript error: file:///PATH/js/jquery.js, line 3: SecurityError: Permission denied to access property "document" on cross-origin object

**Comment by andreastt** [comment]
Can you attach a trace-level log?

**Comment by whimboo** [comment]
To use file:// URLs you have to upgrade to at least Firefox 56, which will be released soon. It's the first release which supports such URLs (see [bug 1332122](https://bugzilla.mozilla.org/show_bug.cgi?id=1332122).
