### ISSUE TITLE
GeckoDriver crashes when opening browser with robot framework selenium keyword "Open Browser"

### ISSUE THREAD

**Issue by eweseong** [mozilla/geckodriver#973]
## System
* Version: 0.19.0
* Platform: Red Hat Enterprise Linux Server release 7.2 (Maipo)
* Firefox: 55.0.3
* Selenium: 3.5.0
* Robotframework: 3.0.2
* robotframework-selenium2library: 1.8.0

## Testcase

I'm running some robot script which opens up a web page in Firefox, perform some automation and closes the browser. On occasion the "Open Browser" will open up the Firefox without inserting the address provided and hangs there without returning error/timeout. I've tried running the script on infinite loop and it is able to run for 103 and 201 tries before hitting the aforementioned error.

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/1335588/geckodriver.log)

The log attached is the default level log, I'm unable to produce a trace level log as the options and preference I've passed in doesn't seems to work.

**Comment by andreastt** [comment]
I’m not able to make any sense out of this issue or the attached (15M!) log. I don’t see how this interfaces with geckodriver or how the robot script attempts to call geckodriver commands.

**Comment by whimboo** [comment]
@eweseong please talk to the maintainers of the framework in how specifying the log level. Once you have it please only upload the relevant pieces of the log but not everything.
