### ISSUE TITLE
TSL certificate exception becomes invalid after script execution

### ISSUE THREAD

**Issue by horsewithnoname1985** [mozilla/geckodriver#974]
## System
* Version: 0.19.0
* Platform: Windows
* Firefox: 55.0.3
* Selenium: 3.5.0

## Testcase
I use a separate profile for my selenium tests, to which I added an TSL certificate exception.
When I run Firefox manually, the exception works fine. But when starting am automated test, where the browser is not closed in the end (via _driver.quit()_), I experience, that the certificate exception is somehow revoked after the selenium script finished. I am not able to (re)add the certificate for this session (clicking 'add' simply does not have any effect) and when trying to access the certificate options (Options/Advanced/Certificates/View Certificates) the browser crashes.
Maybe that's standard behavior, but I did not have that observe the same when using geckodriver 0.18.0 with Firefox 49.0. I tested the temporary profile, selenium created during runtime and accessed it manually and the certificate exception was fine (so the cert8.db file in the profile seems fine).
I did also not experience that behavior when running the same test using chromdriver 2.32 and Chrome 61.0.3163.100.

## Stacktrace
no stacktrace

## Trace-level log
no log

**Comment by andreastt** [comment]
Unless a profile is specifically provided, geckodriver starts with a fresh Firefox profile when you create a new session. You should consider using the `acceptInsecureCerts` capability which will let you bypass all TLS certificate errors.

**Comment by horsewithnoname1985** [comment]
Thanks for your quick response.
I'm afraid that does not solve the issue here. I can enter the page and the script runs perfectly. It's just that after the script finished, these access rights are somehow revoked (Firefox warns me about a non
![2017-09-27_15h51_43](https://user-images.githubusercontent.com/15671429/30917342-172d8e36-a39c-11e7-93ff-45b0cdafdc77.png)

**Comment by andreastt** [comment]
What steps are you actually taking here? Is there a script which will reproduce this? Do you have a trace-level geckodriver log?

With the information available, I’m not sure I actually understand the succession of steps taken and what behaviour you are expecting.

**Comment by whimboo** [comment]
Beside that what @andreastt mentioned, if 0.18 works with Firefox 49 please also try the same version of geckodriver with Firefox 55. Is this also broken or does it work? If it works please check older Firefox releases so we know which version is first affected. Regarding the crash it might be helpful to get the information which could also lead us to a solution. So please follow the steps on [this page](https://support.mozilla.org/en-US/kb/mozillacrashreporter) and give us the URL to the crash report. Thanks.

**Comment by horsewithnoname1985** [comment]
Thanks, guys. Here is the log data: 
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1344520/geckodriver.log)

@whimboo I tried 0.18.0 and 0.19.0 with Firefox 55.0.3, which lead to the same result. 
@andreastt The script controls an intern website, so I can't give you a script to reproduce it. It does load my profile where the certificate is stored, it executes the script. After the script finished, I don't quit the browser window. When manually trying to access the same intern web page, it shows an insecure connection warning  - it seems like my profile has forgotten about the certificate.
Hope you can help me!

**Comment by whimboo** [comment]
So if 0.18 also fails with Firefox 55.0.3 I would suggest that you try all the releases between 49.0 and 55.0.3 and tell me which version is first affected.

**Comment by horsewithnoname1985** [comment]
Sorry for the late reply. I tested several older Firefox versions excluding betas. The error first appears in Firefox 52.0. Up until then, the issue does not occur with either geckodriver 0.18.0 or 0.19.0.

**Comment by whimboo** [comment]
Ok, thank you for the information. To nail down the regression range even further would you mind testing the various beta releases? Best start with 52.0b1 so we know if a change before the first beta caused that, or one afterward.

The archive of beta releases you can find here:
http://archive.mozilla.org/pub/firefox/releases/

**Comment by horsewithnoname1985** [comment]
It happens from 52.0b1 on (tested b1 to b9). 51.0.1 is the last working version

**Comment by whimboo** [comment]
Ok, so before we dive into deeper, can you check with latest Firefox 57.0 Nightly to ensure that it hasn't been already fixed? I would just safe us from having to dig through all those old builds.

Also please let me know which kind of Selenium binding you are using for your test. Is it Python?

**Comment by horsewithnoname1985** [comment]
Yes, I am using Python bindings.
No, the issue is not fixed in the latest Nightly (58.0a1 from 2017-10-09 64-bit).

**Comment by whimboo** [comment]
Given that you are using Python do you have a way to pass in the Firefox binary into your test? If yes, I would recommend that you make use of [mozregression](https://pypi.python.org/pypi/mozregression/) to find the causing changeset. This tool automatically downloads builds by bisecting the range, and can also run a command to determine the pass/fail state.

What you would need is a command like:
`mozregression -g 51 -b 52 --command="myscript %binary%`

That means `myscript` is your entry script which accepts an argument, which in this case mozregression will pass into via `%binary%`. For each iteration this is the current binary of Firefox.

**Comment by horsewithnoname1985** [comment]
I ran the mozregression tool and narrowed it down to:

Bug 1326534 - Rename sessionCapabilities variable for brevity; r=whimboo
MozReview-Commit-ID: KGYk2CgwERy

Here is the binaries information:
app_name: firefox
build_date: 2017-01-06 18:34:55.936000
build_file: C:\Users\Nyscan\.mozilla\mozregression\persist\5ee72effcfb4--autoland--firefox-53.0a1.en-US.win64.zip
build_type: inbound
build_url: https://queue.taskcluster.net/v1/task/NeiALYKxQzCWse0shSfOFQ/runs/0/artifacts/public%2Fbuild%2Ffirefox-53.0a1.en-US.win64.zip
changeset: 5ee72effcfb4beabfb88c1a75b22a9e874f1c3a3
pushlog_url: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=5ee72effcfb4beabfb88c1a75b22a9e874f1c3a3&tochange=73f5e38d40a2e1c89481a40996ead654881e20c1
repo_name: autoland
repo_url: https://hg.mozilla.org/integration/autoland
task_id: NeiALYKxQzCWse0shSfOFQ

Hope you can find the issue.

**Comment by whimboo** [comment]
Great find! But it's hard for me to understand what's wrong. Let me ask you something more. Since this is happening for you how does your test behave when you delete the session in between and create a new one? Does that fail?

Could you also please attach a [trace-level log] from geckodriver?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html

**Comment by whimboo** [comment]
Also when you test that please make sure to use the latest Nightly build of Firefox which can be found here: https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by horsewithnoname1985** [comment]
I couldn't use the latest nightly build, because my script crashed at the first send_keys()_ command. I believe this is a known error (https://github.com/mozilla/geckodriver/issues/659). Since that ticket is restricted, I created a new one for it (https://github.com/mozilla/geckodriver/issues/1047).
Therefore I attached a trace-level log from Firefox 52.0.2, hope that also helps (I did not recreate a session here, this is the normal script run):
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1446658/geckodriver.log)

I am not sure, I understood correctly what you meant: What I did is, let the webdriver quit somewhere in the middle of the script and then made it start a new one and let script finish. As a result, the same error occured, just as before.
If the error is not clear, please ask!

**Comment by horsewithnoname1985** [comment]
I just discovered that I used the wrong geckodriver version for that previous geckodriver.log file.
Also, never mind about the send_keys() issue - it also occured because I used an old geckodriver.  
This geckodriver.log was created with geckodriver 0.19.0 and Firefox Nightly 58.0a1 (2017-11-06, 64 Bit):
[geckodriver.log](https://github.com/mozilla/geckodriver/files/1449307/geckodriver.log)

**Comment by whimboo** [comment]
I assume the changes you did to your test were that a second new session is called at the end? If yes, then this output is interesting:

```
JavaScript error: chrome://pippki/content/exceptionDialog.js, line 326: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
JavaScript error: chrome://pippki/content/exceptionDialog.js, line 326: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
JavaScript error: chrome://pippki/content/exceptionDialog.js, line 326: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]
Unable to read VR Path Registry from C:\Users\Nyscan\AppData\Local\openvr\openvrpaths.vrpath
[Child 3720, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 3720, Chrome_ChildThread] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
```

Basically this directs me to: https://dxr.mozilla.org/mozilla-central/rev/2535bad09d720e71a982f3f70dd6925f66ab8ec7/security/manager/pki/resources/content/exceptionDialog.js#326

I have no idea why trying to get the `nsICertOverrideService` fails in such a case.

@horsewithnoname1985 would you mind to reduce your test to just the following steps:

1. create a new session with cert overrides
2. navigate to such a broken SSL page
3. delete the current session and create a new one
4. navigate to the same page again

Does the above fail? If yes, please change your test one more time by using a URL from the list of bad SSL certificates at https://badssl.com/. I really would like to have a testcase with public available data.

**Comment by horsewithnoname1985** [comment]
Both reduced tests showed the same defect (both internal website and https://self-signed.badssl.com/
I attached the script, hope you can see the defect, too.

```Python
from selenium import webdriver
import time
from selenium.webdriver.firefox.options import Options


opts = Options()
opts.log.level = "trace"

profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True

driver = webdriver.Firefox(firefox_options=opts, firefox_profile=profile)

driver.get("https://self-signed.badssl.com/")
time.sleep(3)
driver.quit()
time.sleep(3)

profile = webdriver.FirefoxProfile()
profile.accept_untrusted_certs = True

driver = webdriver.Firefox(firefox_options=opts, firefox_profile=profile)

driver.get("https://self-signed.badssl.com/")
```

**Comment by horsewithnoname1985** [comment]
Any news?

**Comment by whimboo** [comment]
@horsewithnoname1985 I'm sorry that I missed that issue for so long. But I had a look at your code from the second last comment, and ran it locally with a Nightly build of Firefox and geckodriver 0.19.1. I do not see any failure being reported. In both cases the website with the self-signed certificate is perfectly shown. Can you please check again? Thanks.

**Comment by horsewithnoname1985** [comment]
Hello @whimboo ,
I recently got back to this issue. The problem is not, that the pages cannot be opened - they can. The issue is, that when my Selenium script ends, I keep the browser window open and I want to continue using the untrusted page further by hand.
When you run the script from above and try to access ``https://self-signed.badssl.com/`` again after the script has ended within the same browser instance, the page displays the common 'Your connection is not secure' message and I cannot add the website as trusted server. When clicking Advanced / Add Exception Confirm Security Exceptio there is no action (the window isn't even closed).
Even if I add the exception to the used profile before running the script, it is the same result. It appears, Firefox doesn't recognize my stored exceptions anymore.
Just tested the issue again using Firefox 64.0, Selenium 3.141 and geckodriver 0.23.0.

In the meantime, I am using a workaround by only quitting the script when the browser window is closed manually, putting this at the end of the script:
```python
if isinstance(driver, webdriver.Firefox):
    browser_is_open = True
    while browser_is_open:
        try:
            driver.get_window_size()
            time.sleep(1)
        except WebDriverException:
            browser_is_open = False
```

**Comment by whimboo** [comment]
When geckodriver quits Firefox we reset all preferences, and custom error handlers. As such you can no longer open such a page. That is correct and expected. 

As you said if you need this behavior you will have to teach the test to not close Firefox as long as you have closed it yourself, or some other condition.
