### ISSUE TITLE
It is not possible to upload multiple files with geckodriver

### ISSUE THREAD

**Issue by VitoAlbano** [mozilla/geckodriver#98]
I'm trying to automate a simple test case for the element <input type="files" multiple> which allows to upload multiple files a time.

This results not be possible with same syntax as chrome which takes as separator of files "\n".

How can i simulate via the geckodriver this behaviour?

Thanks

**Comment by andreastt** [comment]
Yes it is. The behaviour you describe in Chrome is not conformant to the [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html).

`<input type=file multiple>` can have more files added to it by subsequence calls to `file_element.send_keys`:

```python
file_element.send_keys("/path/to/foo")
file_element.send_keys("/path/to/bar")
```

To clear the field, you’d call `file_element.clear()`.
