### ISSUE TITLE
Proxy address can not be specified with an IPv6 literal since 0.19.0

### ISSUE THREAD

**Issue by joshbruning** [mozilla/geckodriver#981]
## System
* Version: 0.19.0
* Platform: Debian GNU/Linux 9 (stretch)
* Firefox: 57.0b3 (64-bit)
* Selenium: Java 3.5.3

It works as expected for:
* Version: 0.18.0
* Platform: Debian GNU/Linux 9 (stretch)
* Firefox: 56.0 (64-bit)
* Selenium: Java 3.5.3

## Testcase

// Assume a proxy server that serves a simple page at /this-path-should-never-exist-on-the-web-server on port 8080.
Proxy proxy = new Proxy().setHttpProxy("[::1]:8080");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, proxy);
driver = new ...
driver.get("http://www.google.com/this-path-should-never-exist-on-the-web-server"));

## Stacktrace

org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//www.google.com/this-path-should-never-exist-on-the-web-server&c=UTF-8&f=regular&d=We%20can%E2%80%99t%20connect%20to%20the%20server%20at%20www.google.com.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:368)

## Trace-level log

n/a (I haven't gathered this.)

## Additional information

The HTTP Proxy in about:preferences is set to "[::1]" - ; is the new proxy code not treating the [ and ] appropriately?

Note that we have a ton of proxy tests; however, only the IPv6 literal case for 0.19.0 is failing (IPv4 and hostname still work).

**Comment by andreastt** [comment]
Please provide a trace-level log.

**Comment by whimboo** [comment]
So generally this is not an issue with geckodriver 0.19, but a code change which we will ship with Firefox 57. So you are saying that a proxy as specified in the proxy capabilities of form `[::1]:8080` should be added as host `::1` and port `8080`? 

Basically it's not clear for me why the brackets should be removed, but maybe we have to. I just asked a networking guy for clarification, and should get a response on [bug 1369827](https://bugzilla.mozilla.org/show_bug.cgi?id=1369827#c91).

**Comment by joshbruning** [comment]
A URL must contain the <host>; <host> can be an ipv6 reference (like "[::1]"), but not an ipv6 address (like "::1"). This is so that a URL with a port is not ambiguous.

Firefox works with "HTTP Proxy" (in advanced connection settings... panel) set to an ipv6 address (like "::1"); however, does not work with the ipv6 reference that may be passed to geckodriver ("[::1]"-like component of the <host>:<port> string).

If proxy is passed to geckodriver as "[::1]:8080", Firefox must either support specifying ipv6 <host> literal (like "[::1]") in the preferences implementation - or must pull off the square brackets and pass to Firefox the ipv6 address.

**Comment by joshbruning** [comment]
Reposting as I didn't realize my html-like text would be removed...

A URL must contain the host; host can be an ipv6 reference (like "[::1]"), but not an ipv6 address (like "::1"). This is so that a URL with a port is not ambiguous.

Firefox works with "HTTP Proxy" (in advanced connection settings... panel) set to an ipv6 address (like "::1"); however, does not work with the ipv6 reference that may be passed to geckodriver ("[::1]"-like component of the host:port string).

If proxy is passed to geckodriver as "[::1]:8080", Firefox must either support specifying ipv6 literal (like "[::1]") in the preferences implementation - or must pull off the square brackets and pass to Firefox the ipv6 address.

**Comment by whimboo** [comment]
Thank you. I filed [bug 1406763](https://bugzilla.mozilla.org/show_bug.cgi?id=1406763) to get this fixed. When I have a build including this fix, would you mind testing it?

**Comment by whimboo** [comment]
@joshbruning I got this fixed in Marionette now and the Nightly which has this fix included is from today. You can find it here for download: https://archive.mozilla.org/pub/firefox/nightly/2017/10/2017-10-13-10-01-12-mozilla-central/. Or just upgrade an already existent installation of Firefox Nightly.

Can you please verify that it works now to set IPv6 hosts, and even exlusions in the noProxy list?

**Comment by joshbruning** [comment]
Thanks for the fix! I've already worked around in tests, and so this is not urgent for me.

If it's ok with you, I'd prefer to verify with stable 57 or beta 58 (whatever this makes it into) as I already have automation in place to do so.

Feel free to leave this issue open (I can post my verification and close if appropriate) or close this issue (if not fixed, I can reopen). Or if this is urgent to you, let me know, and I can set aside time to verify for Nightly.

**Comment by whimboo** [comment]
I would love to hear your feedback based on the 58 Nightly build, given that you are currently the only one to verify the fix. If it works for you I want to request uplift for 57.0. 

In the next weeks I will work on tests, and will also include some unit tests using a local proxy with hopefully ipv6 tests included.

Thanks.

**Comment by joshbruning** [comment]
Ok assuming the builds are fairly similar to http://ftp.mozilla.org/pub/firefox/releases/, I should be able to verify sometime within a week. I currently have no tests exercising ipv6 noproxy, so will have to author a new one - and need to do some other work to build a little support for firefox nightly into our automation.

**Comment by whimboo** [comment]
Yes, you only you to extract the archive and run the tests with that included binary. It would be great to hear feedback. Thanks.

Closing this issue given that it is (should) be fixed now.

**Comment by whimboo** [comment]
Ok, I setup a IPv6 network and squid locally. With testing the proxy capabilities for a IPv6 proxy host, I can verify that it works now. I'm going to request the uplift of the patch.

**Comment by joshbruning** [comment]
Hi, I wanted to let you know that I've completed infrastructure to easily define arbitrary Firefox nightly browser configurations - so Google should be able to trivially run existing test cases against them in the future (much improved turnaround time for future verifications). The issue I reported is fixed.

Note that I also implemented a test case to verify Java WebDriver's Proxy#setNoProxy w/ an ipv6 address. (I did not see one in the Selenium open source project even for non-ipv6; however, perhaps I've overlooked it.)

Chrome/ChromeDriver passes my test case; however, Firefox fails (on NEW_SESSION command) with a message like:
"[::1]:19107" was not an array
If attempting to use a hostname, it fails with a message like:
"<SOME_HOST>.google.com:18826" was not an array

As that is a separate issue, I'm declining to re-open this issue - though, I would recommend a setNoProxy integration test be added to the Selenium test suite if it is not already there.

**Comment by whimboo** [comment]
`noProxy` has to be defined as a list of strings. So in your case it should be `["[::1]:19107"]`.

**Comment by joshbruning** [comment]
Thanks. I see that there is no definition of this in the current candidate spec:
https://www.w3.org/TR/webdriver/#proxy

I also see that the unit test in the open source project uses a comma-delimited string:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/ProxyTest.java#L114

And the open source project (at least both the Java and Python clients) seem to assume only a comma-delimited string.

**Comment by whimboo** [comment]
> Thanks. I see that there is no definition of this in the current candidate spec:
> https://www.w3.org/TR/webdriver/#proxy

You are referencing a very outdated spec here. Please check the following URL with content that's becoming the final level 1 spec: https://w3c.github.io/webdriver/webdriver-spec.html#proxy

> I also see that the unit test in the open source project uses a comma-delimited string:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/test/org/openqa/selenium/ProxyTest.java#L114

I think that this is something I also discovered with @shs96c a while ago. Maybe a shim will be added around that to make the transition easier. Here Simon can definitely give a better reply.
