### ISSUE TITLE
Unable to lauch geckodriver using jenkins

### ISSUE THREAD

**Issue by dhruvalpatel007** [mozilla/geckodriver#982]
## System
* Version: 0.19.0(win64) 
* Platform: Windows10 64bit 
* Firefox: 56  
* Selenium: 3.6 

## Stacktrace

jenkins error log
###!!! [Parent][MessageChannel] Error: (msgtype=0x240058,name=PContent::Msg_SetPluginList) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24004C,name=PContent::Msg_GMPsChanged) Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][RunMessage] Error: Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150078,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24003F,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150075,name=PBrowser::Msg_LoadRemoteScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24003F,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24003F,name=PContent::Msg_LoadProcessScript) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2400FC,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x2400FC,name=PContent::Msg_AsyncMessage) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x24001F,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150078,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

Unable to read VR Path Registry from C:\WINDOWS\system32\config\systemprofile\AppData\Local\openvr\openvrpaths.vrpath
JavaScript error: resource:///modules/BrowserUsageTelemetry.jsm, line 328: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIObserverService.removeObserver]

###!!! [Parent][MessageChannel] Error: (msgtype=0x150084,name=PBrowser::Msg_UpdateNativeWindowHandle) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x150078,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
Unable to read VR Path Registry from C:\WINDOWS\system32\config\systemprofile\AppData\Local\openvr\openvrpaths.vrpath
[GPU 14548] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 5.824 s <<< FAILURE! - in TestSuite
[ERROR] setup(automation_code.Virtual_App_Pattern_Dep)  Time elapsed: 5.732 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
Process unexpectedly closed with status: 0
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'DESKTOP-6NM25VN', ip: '172.16.254.43', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4821c4 - <no info>
   1:           0x482933 - <no info>
   2:           0x445159 - <no info>
   3:           0x44c838 - <no info>
   4:           0x43026a - <no info>
   5:           0x40ba4e - <no info>
   6:           0x4119b9 - <no info>
   7:           0x6d2c89 - <no info>
   8:           0x426006 - <no info>
   9:           0x6cd490 - <no info>
  10:     0x7ffa8f898364 - BaseThreadInitThunk
	at automation_code.Virtual_App_Pattern_Dep.setup(Virtual_App_Pattern_Dep.java:13)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   Virtual_App_Pattern_Dep.setup:13 » WebDriver Process unexpectedly closed with ...
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.631 s
[INFO] Finished at: 2017-09-29T15:20:01-04:00
[INFO] Final Memory: 8M/20M

## Trace-level log

org.openqa.selenium.WebDriverException: Process unexpectedly closed with status: 0 Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z' , os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_144' Driver info: driver.version: FirefoxDriver remote stacktrace: stack backtrace:    0:           0x4821c4 - <no info>    1:           0x482933 - <no info>    2:           0x445159 - <no info>    3:           0x44c838 - <no info>    4:           0x43026a - <no info>    5:           0x40ba4e - <no info>    6:           0x4119b9 - <no info>    7:           0x6d2c89 - <no info>    8:           0x426006 - <no info>    9:           0x6cd490 - <no info>   10:     0x7ffa8f898364 - BaseThreadInitThunk 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57) 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104) 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359) 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362) 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136) 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142) 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586) 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217) 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140) 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120) 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98) 	at automation_code.Scenario_Methods.setupff(Scenario_Methods.java:52) 	at automation_code.Virtual_App_Pattern_Dep.setup(Virtual_App_Pattern_Dep.java:13) ... Removed 31 stack frames

**Comment by gavrilfb** [comment]
@dhruvalpatel007 try using this version of firefox
https://public-artifacts.taskcluster.net/ayV20Yn6SjSTNo18JtA-JQ/0/public/build/target.zip
It's debug version of 57b2. Works for me since release version of 57b3 is not.

**Comment by andreastt** [comment]
This issue report lacks most of the things requested in the issue template for us to successfully reproduce the issue.

**Comment by whimboo** [comment]
This is clearly a crash of Firefox. @gavrilfb, just to be sure... you are saying that it was working for you in 57.0b2 but it's failing in 57.0b3 now? @dhruvalpatel007 please confirm that range and yes, provide a trace level log.

**Comment by dhruvalpatel007** [comment]
@whimboo  yes it is a crash and it only fails using jenkins. I tried using the cmd + testng also and it works fine with .bat file but it shows communication error with jenkins. Not sure how to provide exact tarace log. Can you please help me. May be it is having problems in running in headless with ff 56.

**Comment by dhruvalpatel007** [comment]
@gavrilfb the build you provided is a crash build. thanks for the help but can you please confirm that it works fine with your nightly build?

**Comment by dhruvalpatel007** [comment]
@whimboo , Just for your ref- steps to reproduce
-Create sample testNG project
-Create a run.bat file to run the Testng.xml file from cmd
-Create a Jenkins project
-Provide run.bat in shell (build step)
-build

The same run.bat executes flawlessly in my system.

-The same above steps also fails with Maven + Jenkins.
-There is no way I can run tests in Jenkins by using geckodriver 0.19+Jenkins+Selenium 3.6.0+TestNg or Maven

**Comment by whimboo** [comment]
For the trace log please see https://github.com/mozilla/geckodriver#capabilities-example.

Further, are you trying to run it as Windows service, or when the user is logged out? Or why is headless mode necessary?

**Comment by dhruvalpatel007** [comment]
Yes, I am running is from admin user and its running as windows service, Headless mode is not necessary but I am trying to achieve normal UI automation using jenkins for continuous integration. Will send you logs as soon as possible

**Comment by whimboo** [comment]
Ok, so this is basically issue #466. Please continue to discuss further options there.

**Comment by dhruvalpatel007** [comment]
@whimboo , After reading logs, finally i downloaded FF 57 and it worked for me. Thanks alot for your help and time

**Comment by whimboo** [comment]
My pleasure. Good to hear it's working now.
