### ISSUE TITLE
Geckodriver not entering URL driver.Navigate().GoToUrl

### ISSUE THREAD

**Issue by dash521** [mozilla/geckodriver#988]
## System
* Version: <0.19>
* Platform: <Windows 7>
* Firefox: <56.0 64-bit>
* Selenium: <3.5.1>

I'm new to using the geckodriver to execute my test in Firefox.  The code below opens a Firefox browsers but does not enter the url.  

 [TestMethod]
        public void MyTest()
        {
            Browser.Goto("https://yahoo.com");
        }
public class Browser
    {
                ......
    }
public void Goto(string url)
        {
            FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(@"C:\Drivers");
            service.FirefoxBinaryPath = @"C:\\Program Files\\Mozilla Firefox\\firefox.exe";
            IWebDriver Instance = new FirefoxDriver();
            Instance.Navigate().GoToUrl(url);
            
        }

**Comment by andreastt** [comment]
Unable to reproduce this. Please attach a trace-level log from geckodriver.

**Comment by dash521** [comment]
I'm not sure how to produce the trace-level log.  Can you post some instructions I can follow? I'm using c# in selenium.

**Comment by andreastt** [comment]
See the README for how to crank up the verbosity level. Either you pass a `{"moz:firefoxOptions": {"log": {"level": "trace"}}}` capability when creating a session, or the `-vv` flag to the geckodriver process itself.

**Comment by curtisy1** [comment]
@dash521 you could also do:
```
FirefoxOptions options =new FirefoxOptions();
options.LogLevel = FirefoxDriverLogLevel.Trace
```
And then add options to Instance by doing ```new FirefoxDriver(options);```

**Comment by dash521** [comment]
@curtisy1 I was not able to locate the trace file.  However, I was able to run an automated test in an application I use called Browser Stack and the url is entered into the browser address bar and the web site is accessed.  I will just test that way until I gain more knowledge of how to use geckodriver for my selenium automated test.

**Comment by andreastt** [comment]
The trace log is sent to stdout, so you need to capture the output and pipe it to a file.

**Comment by andreastt** [comment]
Unable to reproduce this without a trace-log.
