### ISSUE TITLE
Create new SESSION failed if set Proxy

### ISSUE THREAD

**Issue by Trucnt** [mozilla/geckodriver#996]
## System
* Version: 0.19.0
* Platform: Windows 10
* Firefox: 56.0 (64-bit)
* Selenium: 3.5.3

## Testcase

Can you please use the below java code to reproduce and analyze:
```
public static void main(String[] args) {
        WebDriver webDriver = null;
        try {
            // Set the webdriver
            System.setProperty("webdriver.gecko.driver", "D:\\selenium\\web driver\\firefox\\geckodriver-v0.19-win64.exe");
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            // Set log level
            firefoxOptions.setLogLevel(Level.ALL);
            // create DesiredCapabilities instance
            DesiredCapabilities capabilities = DesiredCapabilities.firefox();
            // set proxy
            String proxyInfo = "10.100.111.123:808";
            Proxy proxy = new Proxy();
            proxy.setProxyType(Proxy.ProxyType.MANUAL);
            proxy.setHttpProxy(proxyInfo)
                    .setFtpProxy(proxyInfo)
                    .setSslProxy(proxyInfo);
            capabilities.setCapability(CapabilityType.PROXY, proxy);
//            capabilities.setCapability(CapabilityType.PROXY, proxy.toJson());
            firefoxOptions.addCapabilities(capabilities);
            // Create new FirefoxDriver instance
            webDriver = new FirefoxDriver(firefoxOptions);
            // Go to Google site
            webDriver.get("https://www.google.com");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (webDriver != null) {
                webDriver.quit();
            }
        }
    }
```

## Stacktrace

Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:           0x4821c4 - <no info>
   1:           0x482933 - <no info>
   2:           0x445159 - <no info>
   3:           0x44eff6 - <no info>
   4:           0x4322e1 - <no info>
   5:           0x40ba4e - <no info>
   6:           0x4119b9 - <no info>
   7:           0x6d2c89 - <no info>
   8:           0x426006 - <no info>
   9:           0x6cd490 - <no info>
  10:     0x7ffcb1352774 - BaseThreadInitThunk
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$100/1962826816.apply(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.W3CHandshakeResponse$$Lambda$102/283318938.apply(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at org.openqa.selenium.remote.ProtocolHandshake$$Lambda$103/320304382.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:255)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:237)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:138)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:103)
	at TestSelenium_3371.main(TestSelenium_3371.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

## Trace-level log

1507089558264	geckodriver	INFO	geckodriver 0.19.0
1507089558271	geckodriver	INFO	Listening on 127.0.0.1:25872
1507089558910	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-profile" "C:\\Users\\TRUC~1.NGU\\AppData\\Local\\Temp\\rust_mozprofile.5Oc6rtcLbew3"
1507089559127	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 < callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 < startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 < observe()@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
1507089559338	Marionette	DEBUG	Received observer notification "profile-after-change"
1507089559638	Marionette	DEBUG	Received observer notification "command-line-startup"
1507089559638	Marionette	INFO	Enabled via --marionette
1507089560940	geckodriver::marionette	TRACE	  connection attempt 0/600
Unable to read VR Path Registry from C:\Users\truc.nguyen\AppData\Local\openvr\openvrpaths.vrpath
[Child 10132] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
[Child 10132] WARNING: pipe error: 109: file z:/build/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
1507089561585	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1507089561693	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1507089561693	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1507089561695	Marionette	INFO	Listening on port 63028
1507089562042	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:63028
1507089562044	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:63039
1507089562044	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1507089562044	geckodriver::marionette	TRACE	-> 419:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","proxy":{"ftpProxy":"10.100.111.123:808","httpProxy":"10.100.111.123:808","proxyType":"manual","sslProxy":"10.100.111.123:808"}}},"proxy":{"ftpProxy":"10.100.111.123:808","httpProxy":"10.100.111.123:808","proxyType":"manual","sslProxy":"10.100.111.123:808"}}]
1507089562046	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox","proxy":{"ftpProxy":"10.100.111.123:808","httpProxy":"10.100.111.123:808","proxyType":"manual","sslProxy":"10.100.111.123:808"}}},"proxy":{"ftpProxy":"10.100.111.123:808","httpProxy":"10.100.111.123:808","proxyType":"manual","sslProxy":"10.100.111.123:808"}}]
1507089562049	Marionette	TRACE	0 <- [1,1,{"error":"session not created","message":"InvalidArgumentError: Expected [object Undefined] undefined to be an integer","stacktrace":"WebDriverError@chrome://marionette/content/error.js:227:5\nInvalidArgumentError@chrome://marionette/content/error.js:354:5\nassert.that/<@chrome://marionette/content/assert.js:383:13\nassert.integer@chrome://marionette/content/assert.js:235:10\nassert.positiveInteger@chrome://marionette/content/assert.js:253:3\nfromJSON@chrome://marionette/content/session.js:219:27\nmatch_@chrome://marionette/content/session.js:422:23\nfromJSON@chrome://marionette/content/session.js:326:12\nGeckoDriver.prototype.newSession@chrome://marionette/content/driver.js:671:25\nTaskImpl_run@resource://gre/modules/Task.jsm:331:42\nTaskImpl@resource://gre/modules/Task.jsm:280:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:401:16\nTaskImpl_run@resource://gre/modules/Task.jsm:339:15\nTaskImpl@resource://gre/modules/Task.jsm:280:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nexecute@chrome://marionette/content/server.js:529:15\nonPacket@chrome://marionette/content/server.js:500:7\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:501:9\n"},null]
1507089562049	geckodriver::marionette	TRACE	<- [1,1,{"error":"session not created","message":"InvalidArgumentError: Expected [object Undefined] undefined to be an integer","stacktrace":"WebDriverError@chrome://marionette/content/error.js:227:5\nInvalidArgumentError@chrome://marionette/content/error.js:354:5\nassert.that/<@chrome://marionette/content/assert.js:383:13\nassert.integer@chrome://marionette/content/assert.js:235:10\nassert.positiveInteger@chrome://marionette/content/assert.js:253:3\nfromJSON@chrome://marionette/content/session.js:219:27\nmatch_@chrome://marionette/content/session.js:422:23\nfromJSON@chrome://marionette/content/session.js:326:12\nGeckoDriver.prototype.newSession@chrome://marionette/content/driver.js:671:25\nTaskImpl_run@resource://gre/modules/Task.jsm:331:42\nTaskImpl@resource://gre/modules/Task.jsm:280:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nTaskImpl_handleResultValue@resource://gre/modules/Task.jsm:401:16\nTaskImpl_run@resource://gre/modules/Task.jsm:339:15\nTaskImpl@resource://gre/modules/Task.jsm:280:3\nasyncFunction@resource://gre/modules/Task.jsm:252:14\nTask_spawn@resource://gre/modules/Task.jsm:166:12\nexecute@chrome://marionette/content/server.js:529:15\nonPacket@chrome://marionette/content/server.js:500:7\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:501:9\n"},null]
1507089562050	webdriver::server	DEBUG	Deleting session
1507089562050	geckodriver::marionette	DEBUG	Stopping browser process
1507089562147	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"session not created","message":"InvalidArgumentError: Expected [object Undefined] undefined to be an integer","stacktrace":"stack backtrace:\n   0:           0x4821c4 - <no info>\n   1:           0x482933 - <no info>\n   2:           0x445159 - <no info>\n   3:           0x44eff6 - <no info>\n   4:           0x4322e1 - <no info>\n   5:           0x40ba4e - <no info>\n   6:           0x4119b9 - <no info>\n   7:           0x6d2c89 - <no info>\n   8:           0x426006 - <no info>\n   9:           0x6cd490 - <no info>\n  10:     0x7ffcb1352774 - BaseThreadInitThunk"}}
org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object Undefined] undefined to be an integer
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'

**Comment by Trucnt** [comment]
Hi @whimboo ,
Can you help to analyze.
Thanks advance.

**Comment by whimboo** [comment]
Firefox 56.0 doesn't include all the changes to proxy capabilities, which I have made recently. What you will need here is the current beta of Firefox 57. The described problem above should then be no longer present. I'm closing this issue now, but we can reopen if you still have some issues.

**Comment by Trucnt** [comment]
That fine on FF 57. Thank you.

**Comment by bhreinb** [comment]
Hi there,

I'm using the following editions of firefox and geckodriver

```
geckodriver-v0.19.0
firefox57.0b6 on Centos7
```

https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0b6/linux-x86_64/en-US/

I'm using protractor to control the instance of firefox. Editions of protractor & webdriver are the following

```
protractor 5.1.1
selenium-webdriver 3.5.0
```

however to set the proxy for firefox I have to set it like so (otherwise it either crashes or doesn't set it)

```
"proxy": {
	"ftpProxy": "127.0.0.1:3128",
	"ftpProxyPort": "3128",
	"httpProxy": "127.0.0.1:3128",
	"httpProxyPort": "3128",
	"proxyType": "manual",
	"sslProxy": "127.0.0.1:3128",
	"sslProxyPort": "3128"
}
```

however, according to the the following release notes
https://github.com/mozilla/geckodriver/releases
in this page I shouldn't be using
ftpProxyPort, httpProxyPort, sslProxyPort, and socksProxyPort. The documentation is seriously confusing to me. Is ftpProxyPort, httpProxyPort, sslProxyPort, and socksProxyPort been deprecated because it looks like it isn't?

**Comment by whimboo** [comment]
The documentation for proxy capabilities can be found here: https://github.com/mozilla/geckodriver#proxy-object. It doesn't mention any of the proxy port keys, so maybe you can tell us what's confusing?

**Comment by whimboo** [comment]
Also if something doesn't still work for you please file a new issues with a trace log included.

**Comment by bhreinb** [comment]
Ok so for the configuration mentioned above that been

```
geckodriver-v0.19.0
firefox57.0b6 on Centos7
```

I had to pass in the following configuration 

```
"proxy": {
	"ftpProxy": "127.0.0.1:3128",
	"ftpProxyPort": "3128",
	"httpProxy": "127.0.0.1:3128",
	"httpProxyPort": "3128",
	"proxyType": "manual",
	"sslProxy": "127.0.0.1:3128",
	"sslProxyPort": "3128"
}
```

it won't set the proxy configuration correctly in firefox if I drop the full host string in '*Proxy' or drop any of the '*ProxyPort' keys. I'm of the assumption from the release notes here https://github.com/mozilla/geckodriver/releases that use of port is fully deprecated now and has been tested from v55 onwards. It probably is an issue in that case and I'll happily supply a trace log for it in a bit

**Comment by whimboo** [comment]
I would suggest that you file a new issue with a trace log included and I can have a look at it. Thanks.

**Comment by bhreinb** [comment]
Hey do you know a way to turn on gecko driver logs via protractor? I asked this question 

`https://stackoverflow.com/questions/41576615/how-to-pass-selenium-server-log-parameter-via-protractor`

on stackoverflow  a good while back but it was only possible to do with 47 at the time. Is that still the case now with 57? Many thanks in advance.

**Comment by whimboo** [comment]
@bhreinb this is not a protractor help site. So I would really suggest that you get in contact with their support or docs to figure it out. I'm sorry, but I don't know.

**Comment by bhreinb** [comment]
No problem I actually don't think protractor support this atm I'm afraid. I spent extensive time researching this yesterday. When they do I will file that issue I was seeing on Centos 7 and firefox 57 namely inability to set the proxy without ftpProxyPort, httpProxyPort, sslProxyPort, and socksProxyPort. Thanks for your help with this. All the best.

**Comment by bhanumedi** [comment]
Selenium-3.141.59
Firefox-65
gecko driver-v0.24
-------------------------
ISSUE:Unable to locate element,  but element is present , working fine with chrome 72
after login-trying to click on menu error occurs, am attaching the trace log
 kindly do the needful
[trace.log](https://github.com/mozilla/geckodriver/files/2884046/trace.log)
