### ISSUE TITLE
geckodriver17.0 is not throwing "UnhandledAlertException"

### ISSUE THREAD

**Issue by maht25** [mozilla/geckodriver#998]
## System
* Version: geckodriver0.17_win64
* Platform: Win7
* Firefox: 52.1.1 ESR 64 bit
* Selenium: selenium-server-standalone-3.6.0 

## Testcase

selenium is not throwing "UnhandledAlertException" when alert popup is present on Browser.
my script is having the below line

WebElement table = driver.findElement(By.xpath("//div[@rn='"+appletRN+"']//table[@class='ui-jqgrid-btable']"));	
by the time when execution control comes to this like  thr will be alert pop present on browser.
so selenium shd throw " UnhandledAlertException" , but with selenium 3.6+geckodrover0.17 we are not getting "UnhandledAlertException" due to which my script fails at some other line instead of failing at above mentioned line,

## Stacktrace

No logs found

## Trace-level log

No trace logs

**Comment by andreastt** [comment]
Please provide a reproducible test case and a trace-level log.

**Comment by whimboo** [comment]
Firefox 52 ESR doesn't have this feature. If you need it you have to upgrade at least to the latest release of Firefox which currently is 56.0.
